// dc_verses/dc111_120.js — D&C verse data
(function() {
var dc111_ch1Verses = [
  { num: "א", words: [
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהֵיכֶם","your God,"],
    ["לֹא","not"],
    ["קָצַפְתִּי","am displeased"],
    ["עַל","with"],
    ["בֹּאֲכֶם","your coming"],
    ["בַּמַּסָּע","journey,"],
    ["הַזֶּה","this"],
    ["אַף","notwithstanding"],
    ["אִוַּלְתְּכֶם׃","your follies."]
  ]},
  { num: "ב", words: [
    ["יֶשׁ־לִי","I have"],
    
    ["אוֹצָר","treasure"],
    ["רַב","much"],
    ["בָּעִיר","in city"],
    ["הַזֹּאת","this"],
    ["לָכֶם","for you,"],
    ["לְטוֹבַת","for the benefit of"],
    ["צִיּוֹן","Zion,"],
    ["וְעַם","and people"],
    ["רַב","many"],
    ["בָּעִיר","in city,"],
    ["הַזֹּאת","this"],
    ["אֲשֶׁר","whom"],
    ["אֶאֱסֹף","I will gather out"],
    ["בְּעִתּוֹ","in due time"],
    ["לְטוֹבַת","for the benefit of"],
    ["צִיּוֹן","Zion,"],
    ["עַל־יֶדְכֶם׃","through your instrumentality."],
    
  ]},
  { num: "ג", words: [
    ["לָכֵן","Therefore"],
    ["נָכוֹן","it is expedient"],
    ["לְהִתְוַדֵּעַ","to form acquaintance"],
    ["אֶל","with"],
    ["אֲנָשִׁים","men"],
    ["בָּעִיר","in city,"],
    ["הַזֹּאת","this"],
    ["כַּאֲשֶׁר","as"],
    ["תֻּנְחוּ","you shall be led,"],
    ["וְכַאֲשֶׁר","and when"],
    ["יִנָּתֵן","it shall be given"],
    ["לָכֶם׃","unto you"]
  ]},
  { num: "ד", words: [
    ["וְהָיָה","And it shall come to pass"],
    ["בְּעִתּוֹ","in due time"],
    ["וְנָתַתִּי","that I will give"],
    ["אֶת־הָעִיר","city"],
    ["הַזֹּאת","this"],
    ["בְּיֶדְכֶם","into your hands,"],
    ["וּמְשַׁלְתֶּם","that you shall have power"],
    ["בָּהּ","over it,"],
    
    ["עַד","insomuch"],
    ["כִּי","that"],
    ["לֹא","not"],
    ["יְגַלּוּ","they shall discover"],
    ["סִתְרֵיכֶם","your secret parts;"],
    ["וְעׇשְׁרָהּ","and its wealth"],
    ["בְּזָהָב","pertaining to gold"],
    ["וּבְכֶסֶף","and silver"],
    ["יִהְיֶה","shall be"],
    ["לָכֶם׃","yours."]
  ]},
  { num: "ה", words: [
    ["אַל","not"],
    ["תִּדְאֲגוּ","Concern yourselves"],
    ["לְחוֹבוֹתֵיכֶם","about your debts,"],
    ["כִּי","for"],
    ["אֶתֵּן","I will give"],
    ["לָכֶם","you"],
    ["כֹּחַ","power"],
    ["לְשַׁלְּמָם׃","to pay them."]
  ]},
  { num: "ו", words: [
    ["אַל","not"],
    ["תִּדְאֲגוּ","Concern yourselves"],
    ["לְצִיּוֹן","about Zion,"],
    ["כִּי","for"],
    ["אֶעֱשֶׂה","I will deal"],
    ["עִמָּהּ","with her"],
    ["חֶסֶד׃","mercifully."]
  ]},
  { num: "ז", words: [
    ["הִתְמַהְמְהוּ","Tarry"],
    ["בַּמָּקוֹם","in place,"],
    ["הַזֶּה","this"],
    ["וּבַסְּבִיבוֹת׃","and in the regions round about;"]
  ]},
  { num: "ח", words: [
    ["וְהַמָּקוֹם","And the place"],
    ["אֲשֶׁר","where"],
    ["רְצוֹנִי","it is my will"],
    ["כִּי","that"],
    ["תֵּשְׁבוּ","you should tarry"],
    ["בּוֹ","in it"],
    ["לָרֹב","for the main,"],
    ["יִוָּדַע","shall be signalized"],
    ["לָכֶם","unto you"],
    ["בִּשְׁלוֹם","by the peace"],
    ["רוּחִי","of my Spirit"],
    ["וּבְכֹחָהּ","and power"],
    ["אֲשֶׁר","that"],
    ["יִזַּל","shall flow"],
    ["אֲלֵיכֶם׃","unto you."]
  ]},
  { num: "ט", words: [
    ["אֶת־הַמָּקוֹם","place"],
    ["הַזֶּה","This"],
    ["תּוּכְלוּ","you may"],
    ["לִשְׂכֹּר","obtain by hire."],
    ["וְדִרְשׁוּ","And inquire"],
    ["הֵיטֵב","diligently"],
    ["אֶת־יֹשְׁבֵי","concerning the inhabitants of"],
    ["הָעִיר","city"],
    ["הַזֹּאת","this"],
    ["הַקַּדְמוֹנִים","more ancient"],
    ["וּמְיַסְּדֶיהָ׃","and its founders."]
  ]},
  { num: "י", words: [
    ["כִּי","For"],
    ["יֵשׁ","there are"],
    ["יוֹתֵר","more"],
    ["מֵאוֹצָר","treasures than"],
    ["אֶחָד","one"],
    ["לָכֶם","for you"],
    ["בָּעִיר","in city."],
    ["הַזֹּאת׃","this"]
  ]},
  { num: "יא", words: [
    ["לָכֵן","Therefore,"],
    ["הֱיוּ","be"],
    ["עֲרוּמִים","wise"],
    ["כַּנְּחָשִׁים","as serpents"],
    ["וּבְכׇל־זֹאת","and yet"],
    ["בְּלֹא","without"],
    ["חֵטְא","sin;"],
    ["וַאֲנִי","And I"],
    ["אָכִין","will order"],
    ["כׇּל־דָּבָר","all things"],
    ["לְטוֹבַתְכֶם","for your good,"],
    ["כְּפִי","according as"],
    ["אֲשֶׁר","that"],
    ["תּוּכְלוּ","you are able"],
    ["לְקַבֵּל","to receive them."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc111_ch1Verses, 'dc111-ch1-verses');



var dc112_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord"],
    ["לְךָ","unto you"],
    ["עַבְדִּי","my servant"],
    ["תּוֹמָס","Thomas:"],
    ["שָׁמַעְתִּי","I have heard"],
    ["תְּפִלּוֹתֶיךָ","your prayers;"],
    ["וְצִדְקוֹתֶיךָ","and your alms"],
    ["עָלוּ","have come up"],
    ["לְזִכָּרוֹן","as a memorial"],
    ["לְפָנַי","before me,"],
    ["בְּעַד","in behalf of"],
    ["אַחֶיךָ","those, your brethren,"],
    ["אֲשֶׁר","who"],
    ["נִבְחֲרוּ","were chosen"],
    ["לְהָעִיד","to bear testimony"],
    ["בִּשְׁמִי","of my name"],
    ["וּלְשׇׁלְחוֹ","and to send it abroad"],
    ["בְּכׇל־הַגּוֹיִם","among all nations,"],
    
    ["וְהַמִּשְׁפָּחוֹת","kindreds,"],
    ["וְהַלְּשׁוֹנוֹת","tongues,"],
    ["וְהָעַמִּים","and people,"],
    ["וְהֻסְמְכוּ","and ordained"],
    ["עַל־יְדֵי","through the instrumentality of"],
    
    ["עֲבָדַי׃","my servants."]
  ]},
  { num: "ב", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְךָ","unto you,"],
    ["הָיוּ","there have been"],
    ["דְּבָרִים","things"],
    ["מְעַטִּים","some few"],
    ["בְּלִבְּךָ","in your heart"],
    ["וְעִמְּךָ","and with you"],
    ["אֲשֶׁר","with which"],
    ["בָּהֶם","in them"],
    ["לֹא","not"],
    ["רָצִיתִי","was well pleased"],
    ["אֲנִי","I,"],
    ["יְהוָה׃","the Lord,"]
  ]},
  { num: "ג", words: [
    ["אַךְ","Nevertheless,"],
    ["כִּי","inasmuch as"],
    ["הִשְׁפַּלְתָּ","you have abased"],
    ["אֶת־נַפְשְׁךָ","thyself"],
    ["תְּרוֹמָם","you shall be exalted;"],
    ["לָכֵן","therefore,"],
    ["נִסְלְחוּ","are forgiven"],
    ["לְךָ","you"],
    ["כׇּל־חַטֹּאתֶיךָ׃","all your sins."]
  ]},
  { num: "ד", words: [
    ["יִיטַב","Let be of good cheer"],
    ["לִבֶּךָ","your heart"],
    ["לְפָנָי","before my face;"],
    ["וְתָעִיד","and you shall bear record"],
    ["בִּשְׁמִי","of my name,"],
    ["לֹא","not"],
    ["לַגּוֹיִם","unto the Gentiles"],
    ["לְבַדָּם","only,"],
    ["כִּי","but"],
    ["אִם","rather"],
    ["גַּם","also"],
    ["לַיְּהוּדִים","unto the Jews;"],
    ["וְתִשְׁלַח","and you shall send forth"],
    ["דְּבָרִי","my word"],
    ["עַד","unto"],
    ["קְצוֹת","the ends of"],
    ["הָאָרֶץ׃","the earth."]
  ]},
  { num: "ה", words: [
    ["לָכֵן","Therefore,"],
    ["רִיב","contend you,"],
    ["בַּבֹּקֶר","morning"],
    ["בַּבֹּקֶר","by morning;"],
    ["וְיוֹם","and day"],
    ["יוֹם","after day"],
    ["יֵצֵא","let go forth"],
    ["קוֹל","voice"],
    ["אַזְהָרָתְךָ","your warning"],
    ["וּבְבוֹא","and when comes"],
    ["הַלַּיְלָה","the night"],
    ["אַל","not"],
    ["יָנוּמוּ","let slumber"],
    ["יוֹשְׁבֵי","the inhabitants of"],
    ["הָאָרֶץ","the earth,"],
    ["מִפְּנֵי","because of"],
    ["דְּבָרְךָ׃","your speech."]
  ]},
  { num: "ו", words: [
    ["יִוָּדַע","Let be known"],
    ["מוֹשָׁבְךָ","your habitation"],
    ["בְּצִיּוֹן","in Zion,"],
    ["וְאַל","and not"],
    ["תָּסִיר","remove"],
    ["אֶת־בֵּיתֶךָ","your house;"],
    ["כִּי","for"],
    ["יֶשׁ־לִי","have"],
    
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["מְלָאכָה","work"],
    ["גְדוֹלָה","a great"],
    ["לְךָ","for you"],
    ["לַעֲשׂוֹת","to do,"],
    ["בְּסַפֵּר","in publishing"],
    ["שְׁמִי","my name"],
    ["בִּבְנֵי","among the children of"],
    ["אָדָם׃","men."]
  ]},
  { num: "ז", words: [
    ["לָכֵן","Therefore,"],
    ["אֱזֹר","gird up"],
    ["מׇתְנֶיךָ","your loins"],
    ["לַמְּלָאכָה","for the work."],
    ["וְהַנְעֵל","Let be shod"],
    ["רַגְלֶיךָ","your feet"],
    ["גַּם","also,"],
    ["כִּי","for"],
    ["נִבְחָרְתָּ","you are chosen,"],
    ["וְדַרְכְּךָ","and your path lies"],
    ["בֶּהָרִים","among the mountains,"],
    ["וּבְגוֹיִם","and among nations."],
    ["רַבִּים׃","many"]
  ]},
  { num: "ח", words: [
    ["וּבִדְבָרְךָ","And by your word"],
    ["גְּבֹהִים","high ones"],
    ["רַבִּים","many"],
    ["יֻשְׁפָּלוּ","shall be brought low,"],
    ["וּבִדְבָרְךָ","and by your word"],
    ["שְׁפָלִים","low ones"],
    ["רַבִּים","many"],
    ["יְרוֹמָמוּ׃","shall be exalted."]
  ]},
  { num: "ט", words: [
    ["יִהְיֶה","shall be"],
    ["קוֹלְךָ","Your voice"],
    ["תּוֹכַחַת","a rebuke"],
    ["לַפּוֹשֵׁעַ","unto the transgressor;"],
    ["וּבְגַעֲרָתְךָ","and at your rebuke"],
    ["יֶחְדַּל","let cease"],
    ["לְשׁוֹן","the tongue of"],
    ["הַמּוֹצִיא","he that utters"],
    ["דִבָּה","slander"],
    ["מֵעִקְּשׁוּתוֹ׃","from its perverseness."]
  ]},
  { num: "י", words: [
    ["הֱיֵה","Be"],
    ["עָנָו","you humble;"],
    ["וַיהוָה","and the Lord"],
    ["אֱלֹהֶיךָ","your God"],
    ["יוֹלִיכְךָ","shall lead you"],
    ["בְּיָדֶךָ","by the hand,"],
    ["וְיִתֶּן","and give"],
    ["לְךָ","you"],
    ["מַעֲנֶה","answer"],
    ["לִתְפִלּוֹתֶיךָ׃","to your prayers."]
  ]},
  { num: "יא", words: [
    ["יָדַעְתִּי","I know"],
    ["לִבֶּךָ","your heart,"],
    ["וְשָׁמַעְתִּי","and have heard"],
    ["תְּפִלּוֹתֶיךָ","your prayers"],
    ["עַל","concerning"],
    ["אַחֶיךָ","your brethren."],
    ["אַל","not"],
    ["תִּשָּׂא","Be partial toward"],
    ["פְּנֵיהֶם","them"],
    ["בְּאַהֲבָה","in love"],
    ["עַל","above"],
    ["רַבִּים","many"],
    ["אֲחֵרִים","others,"],
    ["כִּי","but"],
    ["אִם","rather"],
    ["תְּהִי","let be"],
    ["אַהֲבָתְךָ","your love"],
    ["לָהֶם","for them"],
    ["כָּמוֹךָ","as for thyself;"],
    
    ["וְתִרְבֶּה","and let abound"],
    ["אַהֲבָתְךָ","your love"],
    ["לְכׇל־אָדָם","unto all men,"],
    
    ["וּלְכׇל־אֹהֲבֵי","and unto all who love"],
    
    ["שְׁמִי׃","my name."]
  ]},
  { num: "יב", words: [
    ["וְהִתְפַּלֵּל","And pray"],
    ["בְּעַד","for"],
    ["אַחֶיךָ","your brethren"],
    ["הַשְּׁנֵים־עָשָׂר","of the Twelve."],
    
    ["הוֹכַח","Admonish"],
    ["אוֹתָם","them"],
    ["בְּחֹזֶק","sharply"],
    ["לְמַעַן","for sake,"],
    ["שְׁמִי","my name's"],
    ["וְיִוָּכְחוּ","and let them be admonished"],
    ["עַל","for"],
    ["כׇּל־חַטֹּאתֵיהֶם","all their sins,"],
    ["וִהְיוּ","and be"],
    ["נֶאֱמָנִים","faithful"],
    ["לְפָנַי","before me"],
    ["לִשְׁמִי׃","unto my name."]
  ]},
  { num: "יג", words: [
    ["וְאַחֲרֵי","And after"],
    ["נִסְיוֹנוֹתֵיהֶם","their temptations,"],
    ["וְצָרָה","and tribulation,"],
    ["רַבָּה","much"],
    ["הִנֵּה","behold,"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["אֲמַשֵּׁשׁ","will feel"],
    ["אַחֲרֵיהֶם","after them,"],
    ["וְאִם","and if"],
    ["לֹא","not"],
    ["יַקְשׁוּ","they harden"],
    ["אֶת־לִבָּם","their hearts,"],
    ["וְלֹא","and not"],
    ["יַקְשׁוּ","stiffen"],
    ["אֶת־עׇרְפָּם","their necks"],
    ["נֶגְדִּי","against me,"],
    ["יָשׁוּבוּ","they shall be converted,"],
    ["וְאֶרְפָּאֵם׃","and I will heal them."]
  ]},
  { num: "יד", words: [
    ["וְעַתָּה","Now,"],
    ["אֹמֵר","I say"],
    ["לְךָ","unto you,"],
    ["וַאֲשֶׁר","and what"],
    ["אֹמֵר","I say"],
    ["לְךָ","unto you,"],
    ["אֹמֵר","I say"],
    ["לְכׇל־הַשְּׁנֵים־עָשָׂר","unto all the Twelve:"],
    
    ["קוּמוּ","Arise"],
    ["וְאִזְרוּ","and gird up"],
    ["מׇתְנֵיכֶם","your loins,"],
    ["שְׂאוּ","take up"],
    ["אֶת־צְלַבְכֶם","your cross,"],
    ["לְכוּ","follow"],
    ["אַחֲרַי","me,"],
    ["וּרְעוּ","and feed"],
    ["אֶת־צֹאנִי׃","my sheep."]
  ]},
  { num: "טו", words: [
    ["אַל","not"],
    ["תְּרוֹמְמוּ","Exalt"],
    ["אֶת־נַפְשְׁכֶם","yourselves;"],
    ["אַל","not"],
    ["תִּמְרְדוּ","rebel"],
    ["בְּעַבְדִּי","against my servant"],
    ["יוֹסֵף","Joseph;"],
    ["כִּי","for"],
    ["אָמֵן","verily"],
    ["אֹמֵר","I say"],
    ["לָכֶם","unto you,"],
    ["אֲנִי","I am"],
    ["עִמּוֹ","with him,"],
    ["וְיָדִי","and my hand"],
    ["תִּהְיֶה","shall be"],
    ["עָלָיו","over him;"],
    ["וְהַמַּפְתְּחוֹת","and the keys"],
    ["אֲשֶׁר","which"],
    ["נָתַתִּי","I have given"],
    ["לוֹ","unto him,"],
    ["וְגַם","and also"],
    ["לָכֶם","to youward,"],
    ["לֹא","not"],
    ["יִלָּקְחוּ","shall be taken"],
    ["מִמֶּנּוּ","from him"],
    ["עַד","till"],
    ["בֹּאִי׃","I come."]
  ]},
  { num: "טז", words: [
    ["אָמֵן","Verily"],
    ["אֹמֵר","I say"],
    ["לְךָ","unto you,"],
    ["עַבְדִּי","my servant"],
    ["תּוֹמָס","Thomas,"],
    ["אַתָּה","you are"],
    ["הָאִישׁ","the man"],
    ["אֲשֶׁר","whom"],
    ["בָּחַרְתִּי","I have chosen"],
    ["לָשֵׂאת","to hold"],
    ["מַפְתְּחוֹת","the keys"],
    ["מַלְכוּתִי","of my kingdom,"],
    ["אֲשֶׁר","as pertaining"],
    ["לַשְּׁנֵים־עָשָׂר","to the Twelve,"],
    
    ["בְּכׇל־הַגּוֹיִם׃","abroad among all nations—"],
    
  ]},
  { num: "יז", words: [
    ["לְמַעַן","That"],
    ["תִּהְיֶה","you may be"],
    ["עַבְדִּי","my servant"],
    ["לִפְתֹּחַ","to unlock"],
    ["דֶּלֶת","the door of"],
    ["הַמַּלְכוּת","the kingdom"],
    ["בְּכׇל־מָקוֹם","in all places"],
    ["אֲשֶׁר","where"],
    ["לֹא","not"],
    ["יוּכְלוּ","cannot come;"],
    ["עַבְדִּי","my servant"],
    ["יוֹסֵף","Joseph,"],
    ["וְעַבְדִּי","and my servant"],
    ["סִידְנִי","Sidney,"],
    ["וְעַבְדִּי","and my servant"],
    ["חִירָם","Hyrum,"],
    ["לָבוֹא׃","come"]
  ]},
  { num: "יח", words: [["כִּי","For"], ["עֲלֵיהֶם","on them"], ["הֵטַלְתִּי","have I laid"], ["מַשָּׂא","the burden of"], ["כׇּל־הַכְּנֵסִיּוֹת","all the churches"], ["לַמִּצְעָר׃","for a little season."]]},
  { num: "יט", words: [
    ["לָכֵן","Wherefore,"],
    ["בְּכׇל־אֲשֶׁר","whithersoever"],
    ["יִשְׁלָחוּכֶם","they shall send you,"],
    ["לְכוּ","go,"],
    ["וַאֲנִי","and I"],
    ["אֶהְיֶה","will be"],
    ["עִמָּכֶם","with you;"],
    ["וּבְכׇל־מָקוֹם","and in whatsoever place"],
    ["אֲשֶׁר","that"],
    ["תִּקְרְאוּ","you shall proclaim"],
    ["בִשְׁמִי","my name"],
    ["יִפָּתַח","shall be opened"],
    ["לָכֶם","unto you"],
    ["פֶּתַח","a door"],
    ["גָּדוֹל","effectual great"],
    ["לְמַעַן","that"],
    ["יְקַבְּלוּ","they may receive"],
    ["דְּבָרִי׃","my word."]
  ]},
  { num: "כ", words: [
    ["הַמְקַבֵּל","Whosoever receives"],
    ["דְּבָרִי","my word"],
    ["מְקַבֵּל","receives"],
    ["אֹתִי","me,"],
    ["וְהַמְקַבֵּל","and whosoever receives"],
    ["אֹתִי","me,"],
    ["מְקַבֵּל","receives"],
    ["אוֹתָם","those,"],
    ["הַנְּשִׂיאוּת","the Presidency,"],
    ["הָרִאשׁוֹנָה","First"],
    ["אֲשֶׁר","whom"],
    ["שָׁלַחְתִּי","I have sent,"],
    ["אֲשֶׁר","whom"],
    ["עֲשִׂיתִים","I have made"],
    ["יוֹעֲצִים","counselors"],
    ["לְמַעַן","for sake"],
    ["שְׁמִי","my name's"],
    ["לָכֶם׃","unto you."]
  ]},
  { num: "כא", words: [
    ["וְעוֹד","And again,"],
    ["אֹמֵר","I say"],
    ["לָכֶם","unto you,"],
    ["כׇּל־אֲשֶׁר","that whosoever"],
    ["תִּשְׁלְחוּ","you shall send"],
    ["בִּשְׁמִי","in my name,"],
    ["בְּקוֹל","by the voice of"],
    ["אֲחֵיכֶם","your brethren,"],
    ["הַשְּׁנֵים־עָשָׂר","the Twelve,"],
    
    ["וּמֻרְשִׁים","duly recommended and authorized"],
    ["כַּמִּשְׁפָּט","duly"],
    ["עַל־יֶדְכֶם","by you,"],
    
    ["יִהְיֶה","shall have"],
    ["לָהֶם","to them"],
    ["כֹּחַ","power"],
    ["לִפְתֹּחַ","to open"],
    ["דֶּלֶת","the door"],
    ["מַלְכוּתִי","of my kingdom"],
    ["לְכׇל־גּוֹי","unto any nation"],
    
    ["אֲשֶׁר","whithersoever"],
    ["תִּשְׁלָחוּם׃","you shall send them—"]
  ]},
  { num: "כב", words: [
    ["בַּאֲשֶׁר","Inasmuch as"],
    ["יַשְׁפִּילוּ","they shall humble"],
    ["אֶת־נַפְשָׁם","themselves"],
    ["לְפָנַי","before me,"],
    ["וְיִשְׁמְרוּ","and abide in"],
    ["דְבָרִי","my word,"],
    ["וְיִשְׁמְעוּ","and hearken"],
    ["לְקוֹל","to the voice of"],
    ["רוּחִי׃","my Spirit."]
  ]},
  { num: "כג", words: [
    ["אָמֵן","Verily,"],
    ["אָמֵן","verily,"],
    ["אֹמֵר","I say"],
    ["לָכֶם","unto you,"],
    ["חֹשֶׁךְ","darkness"],
    ["כִּסָּה","covers"],
    ["אֶרֶץ","the earth,"],
    ["וַעֲרָפֶל","and darkness"],
    ["כָּבֵד","gross"],
    ["דַּעַת","the minds of"],
    ["הָעַמִּים","the people,"],
    ["וְכׇל־בָּשָׂר","and all flesh"],
    
    ["הִשְׁחִית","has corrupted"],
    ["אֶת־דַּרְכּוֹ","his way"],
    ["לְפָנָי׃","before my face."]
  ]},
  { num: "כד", words: [
    ["הִנֵּה","Behold,"],
    ["נָקָם","vengeance"],
    ["בָּא","comes"],
    ["מְהֵרָה","speedily"],
    ["עַל","upon"],
    ["יֹשְׁבֵי","the inhabitants of"],
    ["הָאָרֶץ","the earth,"],
    ["יוֹם","a day"],
    ["עֶבְרָה","of wrath,"],
    ["יוֹם","a day"],
    ["בְּעֵרָה","of burning,"],
    ["יוֹם","a day"],
    ["שְׁמָמָה","of desolation,"],
    ["בְּכִי","of weeping,"],
    ["וּמִסְפֵּד","of mourning,"],
    ["וּנְהִי","and of lamentation;"],
    ["וְכַסּוּפָה","and as a whirlwind"],
    ["יָבוֹא","it shall come"],
    ["עַל","upon"],
    ["כׇּל־פְּנֵי","all the face of"],
    ["הָאָרֶץ","the earth,"],
    ["נְאֻם","says"],
    ["יְהוָה׃","the Lord."]
  ]},
  { num: "כה", words: [
    ["וְעַל־בֵּיתִי","And upon my house"],
    ["יָחֵל","shall it begin,"],
    ["וּמִבֵּיתִי","and from my house"],
    ["יֵצֵא","shall it go forth,"],
    ["נְאֻם","says"],
    ["יְהוָה׃","the Lord;"]
  ]},
  { num: "כו", words: [
    ["רִאשׁוֹנָה","First"],
    ["בָּאֵלֶּה","among those"],
    ["אֲשֶׁר","who are"],
    ["בֵּינֵיכֶם","among you,"],
    ["נְאֻם","says"],
    ["יְהוָה","the Lord,"],
    ["אֲשֶׁר","who"],
    ["אָמְרוּ","have professed"],
    ["לָדַעַת","to know"],
    ["שְׁמִי","my name"],
    ["וְלֹא","and not"],
    ["יְדָעוּנִי","have known me,"],
    ["וְגִדְּפוּ","and have blasphemed"],
    ["בִי","against me"],
    ["בְּתוֹךְ","in the midst of"],
    ["בֵּיתִי","my house,"],
    ["נְאֻם","says"],
    ["יְהוָה׃","the Lord."]
  ]},
  { num: "כז", words: [["לָכֵן","therefore"], ["רְאוּ","see to it"], ["פֶּן","lest"], ["תַּלְאוּ","you weary"], ["אֶת־נַפְשְׁכֶם","yourselves"], ["בְּעִנְיְנֵי","trouble concerning the affairs of"], ["כְּנֵסִיָּתִי","my church"], ["בַּמָּקוֹם","in place,"], ["הַזֶּה","this"], ["נְאֻם","says"], ["יְהוָה׃","the Lord."]]},
  { num: "כח", words: [
    ["כִּי","But"],
    ["אִם","rather"],
    ["טַהֲרוּ","purify"],
    ["לְבַבְכֶם","your hearts"],
    ["לְפָנָי","before me;"],
    ["וְאָז","and then"],
    ["לְכוּ","go"],
    ["בְּכׇל־הָעוֹלָם","into all the world,"],
    
    ["וְהַטִּיפוּ","and preach"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["לְכׇל־בְּרִיָּה","unto every creature"],
    ["אֲשֶׁר","who"],
    ["לֹא","not"],
    ["קִבְּלָהּ׃","has received it;"]
  ]},
  { num: "כט", words: [
    ["וְהַמַּאֲמִין","And he that believes"],
    ["וְהַנִּטְבָּל","and is baptized"],
    ["יִוָּשֵׁעַ","shall be saved,"],
    ["וַאֲשֶׁר","and he that"],
    ["לֹא","not"],
    ["יַאֲמִין","believes"],
    ["וְלֹא","and not"],
    ["יִטָּבֵל","is baptized,"],
    ["יֶאְשָׁם׃","shall be damned."]
  ]},
  { num: "ל", words: [
    ["כִּי","for"],
    ["לָכֶם","unto you"],
    ["הַשְּׁנֵים־עָשָׂר","the Twelve,"],
    
    ["וְלָאֵלֶּה","and those,"],
    ["הַנְּשִׂיאוּת","the Presidency,"],
    ["הָרִאשׁוֹנָה","First"],
    ["הַמְמֻנִּים","who are appointed"],
    ["עִמָּכֶם","with you"],
    ["לִהְיוֹת","to be"],
    ["יוֹעֲצֵיכֶם","your counselors"],
    ["וּמַנְהִיגֵיכֶם","and your leaders,"],
    ["נִתַּן","is given"],
    ["כֹּחַ","power"],
    ["הַכְּהֻנָּה","of priesthood"],
    ["הַזֹּאת","this"],
    ["לַיָּמִים","for the days"],
    ["הָאַחֲרוֹנִים","last"],
    ["וְלַזְּמַן","and for the time,"],
    ["הָאַחֲרוֹן","last"],
    ["אֲשֶׁר","in the which"],
    ["בּוֹ","is"],
    ["תְּקוּפַת","the dispensation of"],
    ["מְלֹא","the fulness of times,"],
    ["הָעִתִּים׃","of times"]
  ]},
  { num: "לא", words: [
    ["הַכֹּחַ","Which power"],
    ["הַזֶּה","this"],
    ["אֲשֶׁר","which"],
    ["אַתֶּם","you"],
    ["נֹשְׂאִים","hold,"],
    ["עִם","in connection with"],
    ["כׇּל־אֵלֶּה","all those"],
    ["אֲשֶׁר","who"],
    ["קִבְּלוּ","have received"],
    ["תְּקוּפָה","a dispensation"],
    ["בְּכׇל־עֵת","at any time"],
    ["מֵרֵאשִׁית","from the beginning of"],
    ["הַבְּרִיאָה׃","the creation;"]
  ]},
  { num: "לב", words: [
    ["כִּי","For"],
    ["אָמֵן","verily"],
    ["אֹמֵר","I say"],
    ["לָכֶם","unto you,"],
    ["מַפְתְּחוֹת","the keys of"],
    ["הַתְּקוּפָה","the dispensation,"],
    ["אֲשֶׁר","which"],
    ["קִבַּלְתֶּם","you have received,"],
    ["יָרְדוּ","have come down"],
    ["מֵהָאָבוֹת","from the fathers,"],
    ["וּבָאַחֲרֹנָה","and last of all,"],
    
    ["נִשְׁלְחוּ","being sent down"],
    ["מִן־הַשָּׁמַיִם","from heaven"],
    
    ["אֲלֵיכֶם׃","unto you."]
  ]},
  { num: "לג", words: [
    ["אָמֵן","Verily"],
    ["אֹמֵר","I say"],
    ["לָכֶם","unto you,"],
    ["רְאוּ","behold"],
    ["מַה־גָּדוֹל","how great"],
    
    ["מִשְׁלַחְתְּכֶם","is your calling."],
    ["טַהֲרוּ","Cleanse"],
    ["לְבַבְכֶם","your hearts"],
    ["וּבִגְדֵיכֶם","and your garments,"],
    ["פֶּן","lest"],
    ["יִדָּרֵשׁ","be required"],
    ["דַּם","the blood of"],
    ["הַדּוֹר","generation"],
    ["הַזֶּה","this"],
    ["מִיֶּדְכֶם׃","at your hands."]
  ]},
  { num: "לד", words: [
    ["הֱיוּ","Be"],
    ["נֶאֱמָנִים","faithful"],
    ["עַד","until"],
    ["בֹּאִי","I come,"],
    ["כִּי","for"],
    ["הִנְנִי","behold, I"],
    ["בָא","come"],
    ["מַהֵר","quickly;"],
    ["וּשְׂכָרִי","and my reward"],
    ["אִתִּי","is with me"],
    ["לְשַׁלֵּם","to recompense"],
    ["לְאִישׁ","every man"],
    ["כִּמְפׇעֳלוֹ","according as his work shall be."],
    ["אֲנִי","I am"],
    ["אָלֶף","Alpha"],
    ["וְתָו","and Omega."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc112_ch1Verses, 'dc112-ch1-verses');



var dc113_ch1Verses = [
  { num: "א", words: [
    ["מִי","Who"],
    ["הוּא","is"],
    ["גֵּזַע","the Stem of"],
    ["יִשַׁי","Jesse"],
    ["הַנִּזְכָּר","spoken of"],
    ["בַּפְּסוּקִים","in the verses"],
    ["הָרִאשׁוֹן","1st,"],
    ["וְהַשֵּׁנִי","2d,"],
    ["וְהַשְּׁלִישִׁי","3d,"],
    ["וְהָרְבִיעִי","4th,"],
    ["וְהַחֲמִישִׁי","and 5th"],
    ["לַפֶּרֶק","of the chapter"],
    ["הָאַחַד־עָשָׂר","the eleventh"],
    ["בִּישַׁעְיָהוּ׃","of Isaiah?"]
  ]},
  { num: "ב", words: [
    ["אָמֵן","Verily"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord:"],
    ["הוּא","It is"],
    ["הַמָּשִׁיחַ׃","Christ."]
  ]},
  { num: "ג", words: [
    ["מַה־הוּא","What is"],
    
    ["הַחֹטֶר","the rod"],
    ["הַנִּזְכָּר","spoken of"],
    ["בַּפָּסוּק","in the verse"],
    ["הָרִאשׁוֹן","first"],
    ["לַפֶּרֶק","of the 11th chapter"],
    ["הָאַחַד־עָשָׂר","the eleventh"],
    
    ["בִּישַׁעְיָהוּ","of Isaiah,"],
    ["הַיּוֹצֵא","that should come"],
    ["מִגֵּזַע","of the Stem of"],
    ["יִשָׁי׃","Jesse?"]
  ]},
  { num: "ד", words: [
    ["הִנֵּה","Behold,"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord:"],
    ["הוּא","It is"],
    ["עֶבֶד","a servant"],
    ["בְּיַד","in the hands of"],
    ["הַמָּשִׁיחַ","Christ,"],
    ["אֲשֶׁר","who"],
    ["הוּא","is"],
    ["בְּמִקְצָת","partly"],
    ["צֶאֱצָא","a descendant"],
    ["יִשַׁי","of Jesse"],
    ["וְגַם","as well as"],
    ["אֶפְרַיִם","of Ephraim,"],
    ["אוֹ","or"],
    ["בֵּית","of the house of"],
    ["יוֹסֵף","Joseph,"],
    ["אֲשֶׁר","on whom"],
    ["הֻטַל","there is laid"],
    ["עָלָיו","upon him"],
    ["כֹּחַ","power."],
    ["רַב׃","much"]
  ]},
  { num: "ה", words: [
    ["מַה־הוּא","What is"],
    
    ["שֹׁרֶשׁ","the root of"],
    ["יִשַׁי","Jesse"],
    ["הַנִּזְכָּר","spoken of"],
    ["בַּפָּסוּק","in the verse"],
    ["הָעֲשִׂירִי","10th"],
    ["לַפֶּרֶק","of the chapter"],
    ["הָאַחַד־עָשָׂר׃","the eleventh?"]
  ]},
  { num: "ו", words: [
    ["הִנֵּה","Behold,"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord,"],
    ["הוּא","it is"],
    ["צֶאֱצָא","a descendant of"],
    ["יִשַׁי","Jesse,"],
    ["וְגַם","as well as of"],
    ["יוֹסֵף","Joseph,"],
    ["אֲשֶׁר","unto whom"],
    ["לוֹ","rightly belongs"],
    ["מִשְׁפַּט","the right of"],
    ["הַכְּהֻנָּה","the priesthood,"],
    
    ["וּמַפְתְּחוֹת","and the keys of"],
    ["הַמַּלְכוּת","the kingdom,"],
    ["לְנֵס","for an ensign,"],
    ["וּלְקִבּוּץ","and for the gathering of"],
    ["עַמִּי","my people"],
    ["בְּאַחֲרִית","in the last"],
    ["הַיָּמִים׃","days."]
  ]},
  { num: "ז", words: [
    ["שְׁאֵלוֹת","Questions"],
    ["אֵלִיָּאס","by Elias"],
    ["הִיגְבִּי","Higbee:"],
    ["מַה־פֵּשֶׁר","What is meant by"],
    
    ["הַצַּו","the command"],
    ["בִּישַׁעְיָהוּ","in Isaiah,"],
    ["פֶּרֶק","chapter,"],
    ["נב","52d"],
    ["פָּסוּק","verse,"],
    ["א","1st"],
    ["הָאֹמֵר","which says:"],
    ["לִבְשִׁי","Put on"],
    ["עֻזֵּךְ","your strength,"],
    ["צִיּוֹן","O Zion—"],
    ["וְעַל־אֵי־זֶה","and of what"],
    ["עַם","people"],
    ["דִּבֶּר","spoke"],
    ["יְשַׁעְיָהוּ׃","Isaiah?"]
  ]},
  { num: "ח", words: [
    ["דִּבֶּר","He spoke"],
    ["עַל־אֵלֶּה","of those"],
    ["אֲשֶׁר","whom"],
    ["יִקְרָא","should call"],
    ["אֱלֹהִים","God"],
    ["בְּאַחֲרִית","in the last"],
    ["הַיָּמִים","days,"],
    ["הַנּוֹשְׂאִים","who should hold"],
    ["כֹּחַ","the power of"],
    ["הַכְּהֻנָּה","priesthood"],
    ["לְהָשִׁיב","to bring again"],
    ["אֶת־צִיּוֹן","Zion,"],
    ["וּגְאֻלַּת","and the redemption of"],
    ["יִשְׂרָאֵל","Israel;"],
    ["וְלִלְבֹּשׁ","and to put on"],
    ["עֻזָּהּ","her strength"],
    ["הוּא","is"],
    ["לִלְבֹּשׁ","to put on"],
    ["רְשׁוּת","the authority of"],
    ["הַכְּהֻנָּה","the priesthood,"],
    ["אֲשֶׁר","which"],
    ["לְצִיּוֹן","she, Zion, has"],
    ["מִשְׁפָּט","a right"],
    ["עַל־פִּי","by"],
    ["הַיַּחַשׂ","lineage;"],
    ["וְגַם","also"],
    ["לָשׁוּב","to return"],
    ["אֶל","to"],
    ["הַכֹּחַ","that power"],
    ["אֲשֶׁר","which"],
    ["אָבַד","was lost"],
    ["מִמֶּנָּה׃","from her."]
  ]},
  { num: "ט", words: [
    ["מָה","What"],
    ["עָלֵינוּ","are we"],
    ["לְהָבִין","to understand by"],
    ["מִצִּיּוֹן","Zion"],
    ["הַמִּתְפַּתַּחַת","loosing herself"],
    ["מוֹסְרֵי","from the bands of"],
    ["צַוָּארָהּ","her neck;"],
    ["פָּסוּק","verse?"],
    ["ב׃","2d"]
  ]},
  { num: "י", words: [
    ["עָלֵינוּ","We are"],
    ["לְהָבִין","to understand"],
    ["כִּי","that"],
    ["הַשְּׁאֵרִית","the remnant"],
    ["הַנְּפוֹצָה","scattered"],
    ["נִזְהֶרֶת","is exhorted"],
    ["לָשׁוּב","to return"],
    ["אֶל","to"],
    ["יְהוָה","the Lord"],
    ["מֵאֲשֶׁר","from whence"],
    ["נָפְלָה","she has fallen;"],
    ["וְאִם","which if"],
    ["תַּעֲשֶׂה","she do,"],
    ["כֵּן","so"],
    ["הַבְטָחַת","the promise of"],
    ["יְהוָה","the Lord"],
    ["כִּי","is that"],
    ["יְדַבֵּר","he will speak"],
    ["אֲלֵיהֶם","to them,"],
    ["אוֹ","or"],
    ["יִתֵּן","give"],
    ["לָהֶם","them"],
    ["חָזוֹן","revelation."],
    ["רְאֵה","See"],
    ["פְּסוּקִים","verses."],
    ["ו","the 6th,"],
    ["ז","7th,"],
    ["ח","and 8th"],
    ["מוֹסְרֵי","The bands of"],
    ["צַוָּארָהּ","her neck"],
    ["הֵם","are"],
    ["קִלְלוֹת","the curses of"],
    ["אֱלֹהִים","God"],
    ["עָלֶיהָ","upon her,"],
    ["אוֹ","or"],
    ["שְׁאֵרִית","the remnant of"],
    ["יִשְׂרָאֵל","Israel"],
    ["הַנְּפוֹצָה","scattered"],
    
    ["בֵּין","among"],
    ["הַגּוֹיִם׃","the Gentiles."]
  ]}
];
renderVerseSet(dc113_ch1Verses, 'dc113-ch1-verses');



var dc114_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord:"],
    ["חׇכְמָה","wisdom"],
    ["הִיא","It is"],
    ["לְעַבְדִּי","in my servant"],
    ["דָּוִד","David"],
    ["ו.","W."],
    ["פָּטֵן","Patten,"],
    ["אֲשֶׁר","that"],
    ["יְכַלֶּה","he settle up"],
    ["מַהֵר","as soon as"],
    ["כְּכׇל־אֲשֶׁר","ever"],
    ["יוּכַל","he possibly can"],
    ["אֶת־כׇּל־מְלַאכְתּוֹ","all his business"],
    ["וְיַעֲרֹךְ","and make a disposition"],
    ["אֶת־סַחְרוֹ","of his merchandise,"],
    
    ["לְמַעַן","that"],
    ["יַעֲשֶׂה","he may perform"],
    ["מִשְׁלַחַת","a mission"],
    ["לִי","unto me"],
    ["בָּאָבִיב","spring,"],
    ["הַבָּא","next"],
    ["יַחַד","in company"],
    ["עִם","with"],
    ["אֲחֵרִים","others,"],
    ["שְׁנֵים־עָשָׂר","twelve"],
    ["אַף","even"],
    ["הוּא","himself"],
    ["בְּתוֹכָם","included among them"],
    
    ["לְהָעִיד","to testify"],
    ["בִּשְׁמִי","of my name"],
    ["וּלְבַשֵּׂר","and bear"],
    ["בְּשׂוֹרָה","glad tidings"],
    ["לְכׇל־הָאָרֶץ׃","unto all the world."]
  ]},
  { num: "ב", words: [
    ["כִּי","For"],
    ["אָמֵן","verily"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord,"],
    ["יַעַן","that inasmuch as"],
    ["יֵשׁ","there are"],
    ["בָּכֶם","among you"],
    ["הַמְכַחֲשִׁים","those who deny"],
    ["בִּשְׁמִי","my name,"],
    ["אֲחֵרִים","others"],
    ["יִנָּטְעוּ","shall be planted"],
    ["תַּחְתֵּיהֶם","in their stead"],
    ["וְיִקְחוּ","and receive"],
    ["אֶת־פְּקֻדָּתָם","their bishopric."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc114_ch1Verses, 'dc114-ch1-verses');



var dc115_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord"],
    ["אֲלֵיכֶם","unto you,"],
    ["עַבְדִּי","my servant"],
    ["יוֹסֵף","Joseph"],
    ["סְמִית","Smith,"],
    ["הַבֵּן","Jun.,"],
    ["וְגַם","and also"],
    ["עַבְדִּי","my servant"],
    ["סִידְנִי","Sidney"],
    ["רִיגְדּוֹן","Rigdon,"],
    ["וְגַם","and also"],
    ["עַבְדִּי","my servant"],
    ["חִירָם","Hyrum"],
    ["סְמִית","Smith,"],
    ["וְיֹעֲצֵיכֶם","and your counselors"],
    ["אֲשֶׁר","who"],
    ["הֵם","are"],
    ["וַאֲשֶׁר","and who"],
    ["יִמָּנוּ","shall be appointed"],
    ["אַחֲרֵי־כֵן׃","hereafter."],
    
  ]},
  { num: "ב", words: [
    ["וְגַם","And also"],
    ["אֲלֵיכֶם","unto you,"],
    ["עַבְדִּי","my servant"],
    ["אֶדְוָרְד","Edward"],
    ["פַּרְטְרִיג׳","Partridge,"],
    ["וְיֹעֲצָיו׃","and his counselors;"]
  ]},
  { num: "ג", words: [["וְגַם","And also"], ["אֶל־עֲבָדַי","unto my servants"], ["הַנֶּאֱמָנִים","faithful"], ["אֲשֶׁר","who"], ["בְּסַנְהֶדְרִין","are of the high council of"], ["כְּנֵסִיָּתִי","my church"], ["בְּצִיּוֹן","in Zion,"], ["כִּי","for"], ["כֹּה","thus"], ["יִקָּרֵא","it shall be called,"], ["וְאֶל־כׇּל־הַזְּקֵנִים","and unto all the elders"], ["וְעַם","and people of"], ["כְּנֵסִיַּת","the Church of"], ["יֵשׁוּעַ","Jesus"], ["הַמָּשִׁיחַ","Christ"], ["שֶׁל","of"], ["קְדוֹשֵׁי","the Saints of"], ["אַחֲרִית","the latter part of"], ["הַיָּמִים","the days"], ["הַנְּפוֹצִים","scattered"], ["בְּכׇל־הָאָרֶץ׃","abroad in all the world;"]]},
  { num: "ד", words: [["כִּי","For"], ["כֹּה","thus"], ["תִּקָּרֵא","shall be called"], ["כְּנֵסִיָּתִי","my church"], ["בְּאַחֲרִית","in the last"], ["הַיָּמִים","days,"], ["אַף","even"], ["כְּנֵסִיַּת","the Church of"], ["יֵשׁוּעַ","Jesus"], ["הַמָּשִׁיחַ","Christ"], ["שֶׁל","of"], ["קְדוֹשֵׁי","the Saints of"], ["אַחֲרִית","the latter part of"], ["הַיָּמִים׃","the days"]]},
  { num: "ה", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְכֻלְּכֶם","unto you all:"],
    ["קוּמִי","Arise"],
    ["אוֹרִי","and shine forth,"],
    ["כִּי","that"],
    ["אוֹרֵךְ","your light"],
    ["יִהְיֶה","may be"],
    ["לְנֵס","a standard"],
    ["לַגּוֹיִם׃","for the nations;"]
  ]},
  { num: "ו", words: [
    ["וְהִקָּבֵץ","And that the gathering together"],
    ["עַל־אֶרֶץ","upon the land of"],
    ["צִיּוֹן","Zion,"],
    ["וְעַל","and upon"],
    ["יְתֵדוֹתֶיהָ","her stakes,"],
    ["יִהְיֶה","may be"],
    ["לְמָעוֹז","for a defense,"],
    ["וּלְמַחְסֶה","and for a refuge"],
    ["מִזֶּרֶם","from the storm,"],
    ["וּמֵחֵמָה","and from wrath"],
    ["אֲשֶׁר","when"],
    ["תִּשָּׁפֵךְ","it shall be poured out"],
    ["בְּלֹא־מֶזֶג","without mixture"],
    ["עַל","upon"],
    ["כׇּל־הָאָרֶץ׃","the whole earth."]
  ]},
  { num: "ז", words: [
    ["תְּהִי","Let be"],
    ["הָעִיר","the city,"],
    ["פַּר","Far"],
    ["וֶסְט","West,"],
    ["אֶרֶץ","land"],
    ["קֹדֶשׁ","a holy"],
    ["וְהֻקְדְּשָׁה","and consecrated"],
    ["לִי","unto me;"],
    ["וְתִקָּרֵא","and it shall be called"],
    ["קֹדֶשׁ","most"],
    ["קׇדָשִׁים","holy,"],
    ["כִּי","for"],
    ["הָאֲדָמָה","the ground"],
    ["אֲשֶׁר","whereon"],
    ["אַתָּה","you"],
    ["עֹמֵד","stand"],
    ["עָלֶיהָ","upon"],
    ["קֹדֶשׁ","holy"],
    ["הִיא׃","is"]
  ]},
  { num: "ח", words: [
    ["לָכֵן","Therefore,"],
    ["אֲנִי","I"],
    ["מְצַוֶּה","command"],
    ["אֶתְכֶם","you"],
    ["לִבְנוֹת","to build"],
    ["לִי","unto me,"],
    ["בַּיִת","a house"],
    ["לְקִבּוּץ","for the gathering together of"],
    ["קְדוֹשַׁי","my saints,"],
    ["לְמַעַן","that"],
    ["יַעַבְדוּנִי׃","they may worship me."]
  ]},
  { num: "ט", words: [
    ["וּתְהִי","And let there be"],
    ["רֵאשִׁית","a beginning of"],
    ["הַמְּלָאכָה","work"],
    ["הַזֹּאת","this"],
    ["וִיסוֹדָהּ","and a foundation,"],
    ["וַעֲבוֹדָה","and a work,"],
    ["לְהָכִין","preparatory"],
    ["בַּקַּיִץ","summer;"],
    ["הַבָּא׃","this following"]
  ]},
  { num: "י", words: [
    ["וְתֵחֵל","And let the beginning be made"],
    ["בַּיּוֹם","on the day"],
    ["הָרְבִיעִי","fourth"],
    ["לַחֹדֶשׁ","of the month"],
    ["הַשְּׁבִיעִי","seventh July"],
    ["וּמֵהָעֵת","next;"],
    ["הַהִיא","and from time"],
    ["וָהָלְאָה","that forth"],
    ["יַעֲמֹל","let labor"],
    ["עַמִּי","my people"],
    ["בְּחָרִיצוּת","diligently"],
    ["לִבְנוֹת","to build"],
    ["בַּיִת","a house"],
    ["לִשְׁמִי׃","unto my name;"]
  ]},
  { num: "יא", words: [
    ["וּבְשָׁנָה","And in year"],
    ["אַחַת","one"],
    ["מֵהַיּוֹם","from day"],
    ["הַזֶּה","this"],
    ["יָשׁוּבוּ","let them re-commence"],
    ["לְהָחֵל","to begin"],
    ["לְיַסֵּד","laying"],
    ["יְסוֹד","the foundation of"],
    ["בֵּיתִי׃","my house."]
  ]},
  { num: "יב", words: [
    ["כָּכָה","Thus"],
    ["יַעַמְלוּ","let them labor"],
    ["וּמֵהָעֵת","from time"],
    ["הַהִיא","that"],
    ["וָהָלְאָה","forth"],
    ["בְּחָרִיצוּת","diligently"],
    ["עַד","until"],
    ["כְּלֹתוֹ","it shall be finished,"],
    ["מֵאֶבֶן","from the"],
    ["פִּנָּתוֹ","cornerstone thereof"],
    ["וְעַד","unto"],
    ["רֹאשׁוֹ","the top thereof,"],
    ["עַד־אֲשֶׁר","until"],
    
    ["לֹא","not"],
    ["יִשָּׁאֵר","there shall remain"],
    ["דָּבָר","anything"],
    ["אֲשֶׁר","that"],
    ["לֹא","not"],
    ["נִשְׁלַם׃","is finished."]
  ]},
  { num: "יג", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["אַל־יִלְוֶה","let not get in debt"],
    ["עַבְדִּי","my servant"],
    ["יוֹסֵף","Joseph,"],
    ["וְלֹא","neither"],
    ["עַבְדִּי","my servant"],
    ["סִידְנִי","Sidney,"],
    ["וְלֹא","neither"],
    ["עַבְדִּי","my servant"],
    ["חִירָם","Hyrum,"],
    ["עוֹד","any more"],
    ["לִבְנוֹת","for the building of"],
    ["בַּיִת","a house"],
    ["לִשְׁמִי׃","unto my name;"]
  ]},
  { num: "יד", words: [
    ["אַךְ","But"],
    ["יִבָּנֶה","let be built"],
    ["בַּיִת","a house"],
    ["לִשְׁמִי","unto my name"],
    ["כְּתַבְנִית","according to the pattern"],
    ["אֲשֶׁר","which"],
    ["אַרְאֶה","I will show"],
    ["אֹתָם׃","unto them."]
  ]},
  { num: "טו", words: [
    ["וְאִם","And if"],
    ["לֹא","not"],
    ["יִבְנוּ","build it"],
    ["עַמִּי","my people"],
    ["כְּתַבְנִית","according to the pattern"],
    ["אֲשֶׁר","which"],
    ["אַרְאֶה","I shall show"],
    ["אֶת־נְשִׂיאוּתָם","unto their presidency,"],
    ["לֹא","not"],
    ["אֲקַבְּלֶנּוּ","I will accept it"],
    ["מִיָּדָם׃","at their hands."]
  ]},
  { num: "טז", words: [
    ["וְאִם","But if"],
    ["יִבְנוּ","do build it"],
    ["עַמִּי","my people"],
    ["כְּתַבְנִית","according to the pattern"],
    ["אֲשֶׁר","which"],
    ["אַרְאֶה","I shall show"],
    ["אֶת־נְשִׂיאוּתָם","unto their presidency,"],
    ["אַף","even"],
    ["עַבְדִּי","my servant"],
    ["יוֹסֵף","Joseph"],
    ["וְיֹעֲצָיו","and his counselors,"],
    ["אָז","then"],
    ["אֲקַבְּלֶנּוּ","I will accept it"],
    ["מִיַּד","at the hands of"],
    ["עַמִּי׃","my people."]
  ]},
  { num: "יז", words: [
    ["וְעוֹד","And again,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["רְצוֹנִי","it is my will"],
    ["הוּא","is"],
    ["אֲשֶׁר","that"],
    ["תִּבָּנֶה","should be built up"],
    ["עִיר","the city of"],
    ["פַּר","Far"],
    ["וֶסְט","West"],
    ["מְהֵרָה","speedily"],
    ["בְּהִקָּבֵץ","by the gathering of"],
    ["קְדוֹשַׁי׃","my saints;"]
  ]},
  { num: "יח", words: [
    ["וְגַם","And also"],
    ["יִמָּנוּ","that should be appointed"],
    ["מְקוֹמוֹת","places"],
    ["אֲחֵרִים","other"],
    ["לִיתֵדוֹת","for stakes"],
    ["בַּסְּבִיבוֹת","in the regions round about,"],
    
    ["כַּאֲשֶׁר","as"],
    ["יִגָּלוּ","they shall be manifested"],
    ["לְעַבְדִּי","unto my servant"],
    ["יוֹסֵף","Joseph,"],
    ["מֵעֵת","from time"],
    ["אֶל־עֵת׃","to time."]
  ]},
  { num: "יט", words: [
    ["כִּי","For"],
    ["הִנֵּה","behold,"],
    ["אֶהְיֶה","I will be"],
    ["עִמּוֹ","with him,"],
    ["וַאֲקַדְּשֶׁנּוּ","and I will sanctify him"],
    ["לִפְנֵי","before"],
    ["הָעָם","the people;"],
    ["כִּי","for"],
    ["לוֹ","unto him"],
    ["נָתַתִּי","have I given"],
    ["מַפְתְּחוֹת","the keys of"],
    ["הַמַּלְכוּת","kingdom"],
    ["הַזֹּאת","this"],
    ["וְהָעֲבוֹדָה","and ministry."],
    ["הַזֹּאת","this"],
    ["כֵּן","Even"],
    ["הוּא","so."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc115_ch1Verses, 'dc115-ch1-verses');



var dc116_ch1Verses = [
  { num: "א", words: [
    ["גִּבְעַת","the hill of"],
    ["הַמַּעְיָן","the spring Spring Hill"],
    ["קָרָא","has named"],
    ["לָהּ","it"],
    ["יְהוָה","the Lord"],
    ["אָדָם־אֹנְדִּי־אַהְמָן","Adam-ondi-Ahman,"],
    ["כִּי","because,"],
    ["אָמַר","said he,"],
    ["הוּא","it is"],
    ["הַמָּקוֹם","the place"],
    ["אֲשֶׁר","where"],
    ["יָבוֹא","shall come"],
    ["שָׁמָּה","thither"],
    ["אָדָם","Adam"],
    ["לִפְקֹד","to visit"],
    ["אֶת־עַמּוֹ","his people,"],
    ["אוֹ","or"],
    ["עַתִּיק","the Ancient of"],
    ["יוֹמִין","Days"],
    ["יֵשֵׁב","shall sit,"],
    ["כַּאֲשֶׁר","as"],
    ["דִּבֶּר","spoken of by"],
    ["דָּנִיֵּאל","Daniel"],
    ["הַנָּבִיא׃","the prophet."]
  ]}
];
renderVerseSet(dc116_ch1Verses, 'dc116-ch1-verses');



var dc117_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord"],
    ["לְעַבְדִּי","unto my servant"],
    ["וִילְיָם","William"],
    ["מַרְקְס","Marks,"],
    ["וְגַם","and also"],
    ["לְעַבְדִּי","unto my servant"],
    ["נִיוּאֵל","Newel"],
    ["ק.","K."],
    ["וִיטְנִי","Whitney,"],
    ["יְכַלּוּ","let them settle up"],
    ["אֶת־מְלַאכְתָּם","their business"],
    ["מְהֵרָה","speedily"],
    ["וְיִסְעוּ","and journey"],
    ["מֵאֶרֶץ","from the land of"],
    ["קִרְטְלַנְד","Kirtland,"],
    ["בְּטֶרֶם","before"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["אָשִׁיב","send again"],
    ["אֶת־הַשֶּׁלֶג","the snows"],
    ["עַל־הָאָרֶץ׃","upon the earth."]
  ]},
  { num: "ב", words: [
    ["יֵעוֹרוּ","Let them awake,"],
    ["וְיָקוּמוּ","and arise,"],
    ["וְיֵצְאוּ","and come forth,"],
    ["וְאַל־יִתְמַהְמְהוּ","and not tarry,"],
    ["כִּי","for"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["מְצַוֶּה׃","command it."]
  ]},
  { num: "ג", words: [
    ["לָכֵן","Therefore,"],
    ["אִם","if"],
    ["יִתְמַהְמְהוּ","they tarry"],
    ["לֹא","not"],
    ["יִיטַב","it shall be well"],
    ["לָהֶם׃","with them."]
  ]},
  { num: "ד", words: [
    ["יָשׁוּבוּ","Let them repent"],
    ["מִכׇּל־חַטֹּאתָם","of all their sins,"],
    ["וּמִכׇּל־תַּאֲוַת","and of all covetous"],
    ["בִּצְעָם","their desires,"],
    ["לְפָנַי","before me,"],
    ["נְאֻם","says"],
    ["יְהוָה","the Lord;"],
    ["כִּי","for"],
    ["מַה־לִּי","what is unto me?"],
    
    ["רְכוּשׁ","property"],
    ["נְאֻם","says"],
    ["יְהוָה׃","the Lord."]
  ]},
  { num: "ה", words: [
    ["יֻתְּנוּ","be turned out"],
    ["נְכָסֵי","Let the properties of"],
    ["קִרְטְלַנְד","Kirtland"],
    ["לְחוֹבוֹת","for debts,"],
    ["נְאֻם","says"],
    ["יְהוָה","the Lord."],
    ["יֵלְכוּ","Let go,"],
    ["לָהֶם","them"],
    ["נְאֻם","says"],
    ["יְהוָה","the Lord,"],
    ["וְכׇל־הַנִּשְׁאָר","and whatsoever remains,"],
    
    ["יִשָּׁאֵר","let it remain"],
    ["בְּיֶדְכֶם","in your hands,"],
    ["נְאֻם","says"],
    ["יְהוָה׃","the Lord."]
  ]},
  { num: "ו", words: [
    ["הֲלֹא","For have not"],
    ["לִי","I"],
    ["עוֹף","the fowls of"],
    ["הַשָּׁמַיִם","heaven,"],
    ["וּדְגַת","and also the fish of"],
    ["הַיָּם","the sea,"],
    ["וְחַיַּת","and the beasts of"],
    ["הֶהָרִים","the mountains?"],
    ["הֲלֹא","Have not"],
    ["אֲנִי","I"],
    ["עָשִׂיתִי","made"],
    ["אֶת־הָאָרֶץ","the earth?"],
    ["הֲלֹא","Do not"],
    ["אֲנִי","I"],
    ["אֹחֵז","hold"],
    ["בְּגוֹרָלוֹת","the destinies of"],
    ["כׇּל־צִבְאוֹת","all the armies of"],
    ["גּוֹיֵי","the nations of"],
    ["הָאָרֶץ׃","the earth?"]
  ]},
  { num: "ז", words: [
    ["לָכֵן","therefore"],
    ["הֲלֹא","will I not"],
    ["אַצְמִיחַ","I make to bud"],
    ["שְׁמָמוֹת","solitary places"],
    ["וְאַפְרִיחַ","and to blossom"],
    ["אוֹתָן","them"],
    ["וְאוֹצִיא","and to bring forth"],
    ["לָרֹב","in abundance?"],
    ["נְאֻם","says"],
    ["יְהוָה׃","the Lord."]
  ]},
  { num: "ח", words: [
    ["הַאֵין","Is there not"],
    ["מָקוֹם","room"],
    ["דַּי","enough"],
    ["בְּהָרֵי","on the mountains of"],
    ["אָדָם־אֹנְדִּי־אַהְמָן","Adam-ondi-Ahman,"],
    ["וּבְעַרְבוֹת","and on the plains of"],
    ["אוֹלָהָה־שִׁינֵיהָה","Olaha Shinehah,"],
    ["אוֹ","or"],
    ["הָאָרֶץ","the land"],
    ["אֲשֶׁר","where"],
    ["יָשַׁב","dwelt,"],
    ["בָּהּ","wherein"],
    ["אָדָם","Adam"],
    ["כִּי","that"],
    ["תַחְמְדוּ","you should covet"],
    ["אֶת־מַר","that which is but the drop"],
    ["הַדְּלִי","of the bucket,"],
    ["וְתִזְנְחוּ","and neglect"],
    ["אֶת־הַדְּבָרִים","the matters?"],
    ["הַכְּבֵדִים׃","more weighty"]
  ]},
  { num: "ט", words: [
    ["לָכֵן","Therefore,"],
    ["עֲלוּ","come up"],
    ["הֵנָּה","hither"],
    ["אֶל־אֶרֶץ","unto the land of"],
    ["עַמִּי","my people,"],
    ["אַף","even"],
    ["צִיּוֹן׃","Zion."]
  ]},
  { num: "י", words: [
    ["יִהְיֶה","Let be"],
    ["עַבְדִּי","my servant"],
    ["וִילְיָם","William"],
    ["מַרְקְס","Marks"],
    ["נֶאֱמָן","faithful"],
    ["עַל־מְעַט","over a few things,"],
    ["וְיִשְׁלֹט","and he shall be a ruler"],
    ["עַל־הַרְבֵּה","over many."],
    ["יַעֲמֹד","Let him preside"],
    ["בָּרֹאשׁ","at the head"],
    ["בְּתוֹךְ","in the midst of"],
    ["עַמִּי","my people"],
    ["בְּעִיר","in the city of"],
    ["פַּר","Far"],
    ["וֶסְט","West,"],
    ["וְיִתְבָּרֵךְ","and let him be blessed"],
    ["בְּבִרְכוֹת","with the blessings of"],
    ["עַמִּי׃","my people."]
  ]},
  { num: "יא", words: [
    ["יֵבוֹשׁ","Let be ashamed"],
    ["עַבְדִּי","my servant"],
    ["נִיוּאֵל","Newel"],
    ["ק.","K."],
    ["וִיטְנִי","Whitney"],
    ["מֵחֶבֶר","of the band"],
    ["הַנִּיקוֹלָאִי","Nicolaitane"],
    ["וּמִכׇּל־תּוֹעֲבוֹתֵיהֶם","and of all their abominations,"],
    ["הַנִּסְתָּרוֹת","secret"],
    ["וּמִכׇּל־קָטְנוּת","and of all littleness of"],
    
    ["נַפְשׁוֹ","his soul"],
    ["לְפָנַי","before me,"],
    ["נְאֻם","says"],
    ["יְהוָה","the Lord,"],
    ["וְיַעַל","and come up"],
    ["אֶל־אֶרֶץ","to the land of"],
    ["אָדָם־אֹנְדִּי־אַהְמָן","Adam-ondi-Ahman,"],
    ["וִיהִי","and be"],
    ["לְפָקִיד","a bishop"],
    ["לְעַמִּי","unto my people,"],
    ["נְאֻם","says"],
    ["יְהוָה","the Lord,"],
    ["לֹא","not"],
    ["בְּשֵׁם","in name"],
    ["לְבַד","only"],
    ["כִּי","but"],
    ["אִם","rather"],
    ["בְּמַעֲשֶׂה","in deed,"],
    ["נְאֻם","says"],
    ["יְהוָה׃","the Lord."]
  ]},
  { num: "יב", words: [
    ["וְעוֹד","And again,"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["אֲנִי","I"],
    ["זוֹכֵר","remember"],
    ["אֶת־עַבְדִּי","my servant"],
    ["אוֹלִיבֶר","Oliver"],
    ["גְּרֵינְגֶר","Granger;"],
    ["הִנֵּה","behold,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לוֹ","unto him"],
    ["שְׁמוֹ","that his name"],
    ["יִהְיֶה","shall be had"],
    ["לְזִכָּרוֹן","in remembrance"],
    ["קֹדֶשׁ","sacred"],
    ["מִדּוֹר","from generation"],
    ["לָדוֹר","to generation,"],
    ["לְעוֹלָם","forever"],
    ["וָעֶד","and ever,"],
    ["נְאֻם","says"],
    ["יְהוָה׃","the Lord."]
  ]},
  { num: "יג", words: [["לָכֵן","Therefore,"], ["יִלָּחֵם","let him contend"], ["בְּחָזְקָה","earnestly"], ["לִפְדוּת","for the redemption of"], ["נְשִׂיאוּת","the Presidency of"], ["כְּנֵסִיָּתִי","my Church,"], ["הָרִאשׁוֹנָה","First"], ["נְאֻם","says"], ["יְהוָה","the Lord;"], ["וּבְנָפְלוֹ","and when he falls"], ["יָקוּם","he shall rise"], ["שֵׁנִית","again,"], ["כִּי","for"], ["קָרְבָּנוֹ","his sacrifice"], ["קָדוֹשׁ","shall be more sacred"], ["לִי","unto me"], ["מִתְּבוּאָתוֹ","than his increase,"], ["נְאֻם","says"], ["יְהוָה׃","the Lord."]]},
  { num: "יד", words: [
    ["לָכֵן","Therefore,"],
    ["יַעַל","let him come up"],
    ["הֵנָּה","hither"],
    ["מְהֵרָה","speedily,"],
    ["אֶל־אֶרֶץ","unto the land of"],
    ["צִיּוֹן","Zion;"],
    ["וּבְעִתּוֹ","and in the due time"],
    ["יִהְיֶה","he shall be made"],
    ["לְסֹחֵר","a merchant"],
    ["לִשְׁמִי","unto my name,"],
    ["נְאֻם","says"],
    ["יְהוָה","the Lord,"],
    ["לְטוֹבַת","for the benefit of"],
    ["עַמִּי׃","my people."]
  ]},
  { num: "טו", words: [
    ["לָכֵן","Therefore"],
    ["אַל־יָבוּז","let no despise"],
    ["אִישׁ","man"],
    ["אֶת־עַבְדִּי","my servant"],
    ["אוֹלִיבֶר","Oliver"],
    ["גְּרֵינְגֶר","Granger,"],
    ["אַךְ","but"],
    ["בִּרְכוֹת","the blessings of"],
    ["עַמִּי","my people"],
    ["תִּהְיֶינָה","let be"],
    ["עָלָיו","on him"],
    ["לְעוֹלָם","forever"],
    ["וָעֶד׃","and ever."]
  ]},
  { num: "טז", words: [
    ["וְעוֹד","And again,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["כׇּל־עֲבָדַי","let all my servants"],
    ["בְּאֶרֶץ","in the land of"],
    ["קִרְטְלַנְד","Kirtland"],
    ["יִזְכְּרוּ","remember"],
    ["אֶת־יְהוָה","the Lord"],
    ["אֱלֹהֵיהֶם","their God,"],
    ["וְגַם","and also"],
    ["אֶת־בֵּיתִי","my house"],
    ["לְשׇׁמְרוֹ","to keep it"],
    ["וּלְקַדְּשׁוֹ","and preserve it holy,"],
    ["וּלְהָפֵךְ","and to overthrow"],
    ["אֶת־שֻׁלְחֲנוֹת","the tables of"],
    ["הַשֻּׁלְחָנִים","the moneychangers"],
    ["בְּעִתִּי","in my own due time,"],
    ["נְאֻם","says"],
    ["יְהוָה","the Lord."],
    ["כֵּן","Even"],
    ["הוּא","so."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc117_ch1Verses, 'dc117-ch1-verses');



var dc118_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily,"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord:"],
    ["יִקָּהֵל","Let be held"],
    ["מוֹעֵד","a conference"],
    ["מַהֵר","immediately;"],
    ["וְיֵעָרְכוּ","and let be organized;"],
    ["הַשְּׁנֵים־עָשָׂר","the Twelve"],
    
    ["וְיִמָּנוּ","and let be appointed"],
    ["אֲנָשִׁים","men"],
    ["לְמַלֵּא","to supply"],
    ["מְקוֹם","the place of"],
    ["הַנֹּפְלִים׃","those who are fallen."]
  ]},
  { num: "ב", words: [
    ["יֵשֵׁב","Let remain"],
    ["עַבְדִּי","my servant"],
    ["תּוֹמָס","Thomas"],
    ["יָמִים","for a season"],
    
    ["בְּאֶרֶץ","in the land of"],
    ["צִיּוֹן","Zion,"],
    ["לְהוֹצִיא","to publish"],
    ["דְּבָרִי׃","my word."]
  ]},
  { num: "ג", words: [
    ["וְהַנִּשְׁאָרִים","Let the residue"],
    ["יוֹסִיפוּ","continue"],
    ["לִקְרֹא","to preach"],
    ["מֵהַשָּׁעָה","from hour,"],
    ["הַהִיא","that"],
    ["וְאִם","and if"],
    ["יַעֲשׂוּ","they will do"],
    ["כֵן","this"],
    ["בְּשִׁפְלוּת","in all lowliness of"],
    ["לֵב","heart,"],
    ["בַּעֲנָוָה","in meekness and humility,"],
    ["וּבְאֶרֶךְ","and long-"],
    ["אַפַּיִם","-suffering,"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["נֹתֵן","give"],
    ["לָהֶם","unto them"],
    ["הַבְטָחָה","a promise"],
    ["כִּי","that"],
    ["אֲכַלְכֵּל","I will provide"],
    ["אֶת־מִשְׁפְּחוֹתֵיהֶם","for their families;"],
    ["וּפֶתַח","and an effectual door"],
    ["גָּדוֹל","great"],
    ["יִפָּתַח","shall be opened"],
    ["לָהֶם","for them,"],
    ["מֵעַתָּה","from"],
    ["וָהָלְאָה׃","henceforth."]
  ]},
  { num: "ד", words: [
    ["וּבָאָבִיב","And spring"],
    ["הַבָּא","next"],
    ["יֵצְאוּ","let them depart"],
    ["לַעֲבֹר","to go over"],
    ["אֶת־הַמַּיִם","the waters,"],
    ["הָרַבִּים","great"],
    ["וְשָׁם","and there"],
    ["לְהַשְׁמִיעַ","promulgate"],
    ["בְּשׂוֹרָתִי","my gospel,"],
    ["מְלֹאָהּ","the fulness thereof,"],
    ["וּלְהָעִיד","and bear record"],
    ["בִּשְׁמִי׃","of my name."]
  ]},
  { num: "ה", words: [
    ["יִפָּרְדוּ","Let them take leave"],
    ["מִקְּדוֹשַׁי","of my saints"],
    ["בְּעִיר","in the city of"],
    ["פַּר","Far"],
    ["וֶסְט","West,"],
    ["בַּיּוֹם","on the day"],
    ["הָעֶשְׂרִים־וְשִׁשָּׁה","twenty-sixth"],
    ["לַחֹדֶשׁ","of the month"],
    ["אַפְּרִיל","April"],
    ["הַבָּא","next,"],
    ["עַל","on"],
    ["מְקוֹם","the building-spot of"],
    ["בֵּיתִי","my house,"],
    
    ["נְאֻם","says"],
    ["יְהוָה׃","the Lord."]
  ]},
  { num: "ו", words: [
    ["יִמָּנוּ","Let be appointed"],
    ["עַבְדִּי","my servant"],
    ["ג׳וֹן","John"],
    ["טֵילוֹר","Taylor,"],
    ["וְגַם","and also"],
    ["עַבְדִּי","my servant"],
    ["ג׳וֹן","John"],
    ["אֵי.","E."],
    ["פֵּיג","Page,"],
    ["וְגַם","and also"],
    ["עַבְדִּי","my servant"],
    ["וִילְפוֹרְד","Wilford"],
    ["וּדְרָף","Woodruff,"],
    ["וְגַם","and also"],
    ["עַבְדִּי","my servant"],
    ["וִילָרְד","Willard"],
    ["רִיצָ׳רְדְּס","Richards,"],
    ["לְמַלֵּא","to fill"],
    ["מְקוֹם","the places of"],
    ["הַנֹּפְלִים","those who have fallen,"],
    ["וְיִוָּדַע","and let it be made known"],
    ["לָהֶם","unto them"],
    ["כַּמִּשְׁפָּט","duly officially"],
    ["כִּי","that"],
    ["נִמְנוּ׃","they are appointed."]
  ]}
];
renderVerseSet(dc118_ch1Verses, 'dc118-ch1-verses');



var dc119_ch1Verses = [
  { num: "א", words: [["אָמֵן","Verily,"], ["כֹּה","thus"], ["אָמַר","says"], ["יְהוָה","the Lord,"], ["אֲנִי","I"], ["דוֹרֵשׁ","require"], ["אֶת־כׇּל־עֹדֶף","all surplus"], ["נִכְסֵיהֶם","their property"], ["לָתֵת","to be put"], ["בְּיַד","into the hands of"], ["פָּקִיד","the bishop of"], ["כְּנֵסִיָּתִי","my church"], ["בְּצִיּוֹן׃","in Zion,"]]},
  { num: "ב", words: [["לִבְנוֹת","For the building of"], ["אֶת־בֵּיתִי","my house,"], ["וּלְיַסֵּד","and for the laying of"], ["יְסוֹד","the foundation of"], ["צִיּוֹן","Zion"], ["וְלַכְּהֻנָּה","and for the priesthood,"], ["וּלְחוֹבוֹת","and for the debts of"], ["נְשִׂיאוּת","the Presidency of"], ["כְּנֵסִיָּתִי׃","my Church."]]},
  { num: "ג", words: [
    ["וְזֹאת","And this"],
    ["תִּהְיֶה","shall be"],
    ["רֵאשִׁית","the beginning of"],
    ["מַעֲשַׂר","the tithing of"],
    ["עַמִּי׃","my people."]
  ]},
  { num: "ד", words: [
    ["וְאַחֲרֵי","And after"],
    ["כֵן","that,"],
    ["הַמְעֻשָּׂרִים","those who have thus been tithed"],
    ["יִתְּנוּ","shall pay"],
    ["אֶחָד","one-"],
    ["מֵעֲשָׂרָה","tenth"],
    ["מִכׇּל־תְּבוּאָתָם","of all their interest"],
    ["שָׁנָה","year"],
    ["בְשָׁנָה","by year annually;"],
    ["וְזֹאת","and this"],
    ["תִּהְיֶה","shall be"],
    ["לָהֶם","unto them"],
    ["לְחֻקַּת","a standing law"],
    ["עוֹלָם","forever,"],
    ["לִכְהֻנָּתִי","for my priesthood,"],
    ["הַקְּדוֹשָׁה","holy"],
    ["נְאֻם","says"],
    ["יְהוָה׃","the Lord."]
  ]},
  { num: "ה", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["יִהְיֶה","it shall come to pass"],
    ["כִּי","that"],
    ["כׇּל־הַנֶּאֱסָפִים","all those who gather"],
    ["אֶל־אֶרֶץ","unto the land of"],
    ["צִיּוֹן","Zion"],
    ["יְעֻשְּׂרוּ","shall be tithed"],
    ["מֵעֹדֶף","of surplus"],
    ["נִכְסֵיהֶם","their properties,"],
    ["וְיִשְׁמְרוּ","and shall observe"],
    ["אֶת־הַחֹק","law,"],
    ["הַזֶּה","this"],
    ["אוֹ","or"],
    ["לֹא","not"],
    ["יִמָּצְאוּ","they shall be found"],
    ["רְאוּיִים","worthy"],
    ["לָשֶׁבֶת","to abide"],
    ["בְּקִרְבְּכֶם׃","among you."]
  ]},
  { num: "ו", words: [
    ["וַאֲנִי","And I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["אִם","if"],
    ["לֹא","not"],
    ["יִשְׁמֹר","observe"],
    ["עַמִּי","my people"],
    ["אֶת־הַחֹק","law,"],
    ["הַזֶּה","this"],
    ["לְקַדְּשׁוֹ","to keep it holy,"],
    ["וּלְקַדֵּשׁ","and sanctify"],
    ["בּוֹ","by this law"],
    ["אֶת־אֶרֶץ","the land of"],
    ["צִיּוֹן","Zion"],
    ["לִי","unto me,"],
    ["לְמַעַן","that"],
    ["יִשָּׁמְרוּ","may be kept"],
    ["חֻקֹּתַי","my statutes"],
    ["וּמִשְׁפָּטַי","and my judgments"],
    ["עָלֶיהָ","thereon,"],
    ["לִהְיוֹת","that it may be"],
    ["קֹדֶשׁ","most"],
    ["קׇדָשִׁים","holy,"],
    ["הִנֵּה","behold,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["לֹא","not"],
    ["תִּהְיֶה","it shall be"],
    ["לָכֶם","unto you."],
    ["לְאֶרֶץ","a land of"],
    ["צִיּוֹן׃","Zion"]
  ]},
  { num: "ז", words: [
    ["וְזֹאת","And this"],
    ["תִּהְיֶה","shall be"],
    ["לְמוֹפֵת","an ensample"],
    ["לְכׇל־יְתֵדוֹת","unto all the stakes of"],
    ["צִיּוֹן","Zion."],
    ["כֵּן","Even"],
    ["הוּא","so."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc119_ch1Verses, 'dc119-ch1-verses');



var dc120_ch1Verses = [
  { num: "א", words: [["אָמֵן","Verily,"], ["כֹּה","thus"], ["אָמַר","says"], ["יְהוָה","the Lord,"], ["עַתָּה","now"], ["בָּאָה","is come,"], ["הָעֵת","the time"], ["לְחַלְּקוֹ","that it shall be disposed of"], ["עַל־יְדֵי","by"], ["מוֹעֵצָה","a council,"], ["אֲשֶׁר־בָּהּ","composed of"], ["מִנְּשִׂיאוּת","the Presidency of"], ["כְּנֵסִיָּתִי","my Church,"], ["הָרִאשׁוֹנָה","First"], ["וּמֵהַפָּקִיד","and of the bishop"], ["וּמוֹעַצְתּוֹ","and his council,"], ["וּמֵהַסַּנְהֶדְרִין","and by my high council;"], ["וּבְקוֹלִי","and by my own voice"], ["אֲלֵיהֶם","unto them,"], ["נְאֻם","says"], ["יְהוָה","the Lord."], ["כֵּן","Even"], ["הוּא","so."], ["אָמֵן׃","Amen."]]}
];
renderVerseSet(dc120_ch1Verses, 'dc120-ch1-verses');



})();
