// dc_verses/dc31_40.js — D&C verse data
(function() {
var dc31_ch1Verses = [
  { num: "א", words: [
    ["תּוֹמָס","Thomas"],
    ["בְּנִי","my son"],
    ["בָּרוּךְ","blessed"],
    ["אַתָּה","are you"],
    ["בֶּאֱמוּנָתְךָ","because of your faith"],
    ["בִּמְלַאכְתִּי׃","in my work"],
    ["׃",""]
  ]},
  { num: "ב", words: [
    ["הִנֵּה","behold"],
    ["הָיוּ","you have had"],
    ["לְךָ",""],
    ["צָרוֹת","afflictions"],
    ["רַבּוֹת","many"],
    ["מִפְּנֵי","because of"],
    ["מִשְׁפַּחְתֶּךָ","your family"],
    ["אוּלָם","nevertheless"],
    ["אֲבָרֵךְ","I will bless"],
    ["אֹתְךָ","you"],
    ["וְאֶת־מִשְׁפַּחְתְּךָ","and your family"],
    ["אָכֵן","yea"],
    ["אֶת־טַפְּךָ","your little ones"],
    ["וְיָבוֹא","and cometh"],
    ["הַיּוֹם","the day"],
    ["וְהֶאֱמִינוּ","that they will believe"],
    ["וְיָדְעוּ","and know"],
    ["אֶת־הָאֱמֶת","the truth"],
    ["וְהָיוּ","and be"],
    ["אֶחָד","one"],
    ["עִמְּךָ","with you"],
    ["בַּעֲדָתִי׃","in my church"],
    ["׃",""]
  ]},
  { num: "ג", words: [
    ["הָרֵם","lift up"],
    ["לִבְּךָ","your heart"],
    ["וְגִיל","and rejoice"],
    ["כִּי","for"],
    ["בָאָה","is come"],
    ["עֵת","the hour of your mission"],
    ["הִשָּׁלְחֲךָ","your mission"],
    ["וּלְשׁוֹנְךָ","and your tongue"],
    ["תִּפָּתַח","shall be loosed"],
    ["וְתַשְׁמִיעַ","and you shall declare"],
    ["בְּשׂוֹרַת","glad tidings of"],
    ["שָׂשׂוֹן","of joy"],
    ["גָּדוֹל","great"],
    ["לַדּוֹר","unto generation"],
    ["הַזֶּה׃","this"],
    ["׃",""]
  ]},
  { num: "ד", words: [
    ["תַּשְׁמִיעַ","you shall declare"],
    ["אֶת־הַדְּבָרִים","the things"],
    ["אֲשֶׁר","which"],
    ["נִגְלוּ","have been revealed"],
    ["לְעַבְדִּי","to my servant"],
    ["יוֹסֵף","Joseph"],
    ["סְמִית","Smith Jun."],
    ["תָּחֵל","you shall begin"],
    ["לְהַטִּיף","to preach"],
    ["מֵעַתָּה","from this time forth"],
    ["אָכֵן","yea"],
    ["לִקְצֹר","to reap"],
    ["בַּשָּׂדֶה","in the field"],
    ["הַמַּלְבִּין","which is white already"],
    ["לִשְׂרֵפָה׃","to be burned"],
    ["׃",""]
  ]},
  { num: "ה", words: [
    ["לָכֵן","therefore"],
    ["שְׁלַח","thrust in"],
    ["מַגָּלְךָ","your sickle"],
    ["בְּכׇל־נַפְשְׁךָ","with all-your soul"],
    ["וְחַטֹּאתֶיךָ","and your sins"],
    ["נִסְלְחוּ","are forgiven"],
    ["לְךָ","unto you"],
    ["וְנָשָׂאתָ","and thou shalt be laden"],
    ["אֲלֻמּוֹת","with sheaves"],
    ["עַל־שִׁכְמְךָ","upon-your back"],
    ["כִּי","for"],
    ["שֹׁוֶה","worthy"],
    ["הַפֹּעֵל","the laborer"],
    ["בִּשְׂכָרוֹ","of his hire"],
    ["עַל־כֵּן","wherefore"],
    ["תִּחְיֶה","shall live"],
    ["מִשְׁפַּחְתְּךָ׃","your family"],
    ["׃",""]
  ]},
  { num: "ו", words: [
    ["הִנֵּה","behold"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָךְ","unto you"],
    ["לֵךְ","go"],
    ["מֵהֶם","from them"],
    ["רַק","only"],
    ["לְעֵת","for a"],
    ["קְצָרָה","little time"],
    ["וְהַשְׁמַע","and declare"],
    ["דְּבָרִי","my word"],
    ["וַאֲכִין","and I will prepare"],
    ["לָהֶם","for them"],
    ["מָקוֹם׃","a place"],
    ["׃",""]
  ]},
  { num: "ז", words: [
    ["אָכֵן","yea"],
    ["אֶפְתַּח","I will open"],
    ["אֶת־לְבָבוֹת","the hearts of"],
    ["הָעָם","the people"],
    ["וְקִבְּלוּךָ","and they will receive you"],
    ["וַאֲקִים","and I will establish"],
    ["עֵדָה","a church"],
    ["בְּיָדֶךָ׃","by your hand"],
    ["׃",""]
  ]},
  { num: "ח", words: [
    ["וְחִזַּקְתָּם","and thou shalt strengthen them"],
    ["וַהֲכִינוֹתָם","and prepare them"],
    ["לָעֵת","for the time"],
    ["אֲשֶׁר","which"],
    ["יֵאָסְפוּ׃","they shall be gathered"],
    ["׃",""]
  ]},
  { num: "ט", words: [
    ["סְבֹל","be patient"],
    ["בְּצָרוֹת","in afflictions"],
    ["אַל","not"],
    ["תָּשִׁיב","revile"],
    ["חֶרְפָּה","against those that revile"],
    ["הַנְהֵג","govern"],
    ["בֵּיתְךָ","your house"],
    ["בַּעֲנָוָה","in meekness"],
    ["וֶהְיֵה","and be"],
    ["נֶאֱמָן׃","steadfast"],
    ["׃",""]
  ]},
  { num: "י", words: [
    ["הִנֵּה","behold"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְךָ","unto you"],
    ["תִּהְיֶה","that you shall be"],
    ["רוֹפֵא","a physician"],
    ["לָעֵדָה","unto the church"],
    ["אַךְ","but"],
    ["לֹא","not"],
    ["לְתֵבֵל","unto the world"],
    ["כִּי","for"],
    ["לֹא","not"],
    ["יְקַבְּלוּךָ׃","they will receive you"],
    ["׃",""]
  ]},
  { num: "יא", words: [
    ["לֵךְ","go"],
    ["לְדַרְכְּךָ","your way"],
    ["אֶל־כׇּל־מָקוֹם","whithersoever"],
    ["אֶחְפֹּץ","I will"],
    ["וְיִנָּתֵן","and it shall be given"],
    ["לְךָ","you"],
    ["בְּיַד","by"],
    ["הַמְנַחֵם","the Comforter"],
    ["מָה","what"],
    ["תַּעֲשֶׂה","you shall do"],
    ["וְאָנָה","and whither"],
    ["תֵלֵךְ׃","you shall go"],
    ["׃",""]
  ]},
  { num: "יב", words: [
    ["הִתְפַּלֵּל","pray"],
    ["תָּמִיד","always"],
    ["פֶּן","lest"],
    ["תָּבוֹא","you enter"],
    ["בְמַסָּה","into temptation"],
    ["וּתְאַבֵּד","and lose"],
    ["שְׂכָרֶךָ׃","your reward"],
    ["׃",""]
  ]},
  { num: "יג", words: [
    ["הֱיֵה","be"],
    ["נֶאֱמָן","faithful"],
    ["עַד","unto"],
    ["הַקֵּץ","the end"],
    ["וְהִנֵּה","and lo"],
    ["אִתְּךָ","with you"],
    ["אָנֹכִי","I am"],
    ["הַדְּבָרִים","words"],
    ["הָאֵלֶּה","these"],
    ["אֵינָם","are not"],
    ["מֵאָדָם","of man"],
    ["וְלֹא","nor"],
    ["מֵאֲנָשִׁים","of men"],
    ["כִּי","but"],
    ["אִם",""],
    ["מִמֶּנִּי","of me"],
    ["יֵשׁוּעַ","even Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["גֹּאַלְכֶם","your Redeemer"],
    ["בִּרְצוֹן","by the will of"],
    ["הָאָב","the Father"],
    ["אָמֵן׃","Amen"],
    ["׃",""]
  ]}
];
renderVerseSet(dc31_ch1Verses, 'dc31-ch1-verses');



var dc32_ch1Verses = [
  { num: "א", words: [
    ["וְעַתָּה","and now"],
    ["עַל","concerning"],
    ["עַבְדִּי","my servant"],
    ["פַּרְלִי","Parley"],
    ["פִּ.","P."],
    ["פְּרֶט","Pratt"],
    ["הִנֵּה","behold"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לוֹ","unto him"],
    ["חַי","as live"],
    ["אָנִי","I"],
    ["רְצוֹנִי","I will"],
    ["שֶׁיַּשְׁמִיעַ","that he shall declare"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["וְיִלְמַד","and learn"],
    ["מִמֶּנִּי","of me"],
    ["וְיִהְיֶה","and be"],
    ["עָנָיו","meek"],
    ["וּשְׁפַל","and lowly of"],
    ["רוּחַ׃","heart"],
    ["׃",""]
  ]},
  { num: "ב", words: [
    ["וַאֲשֶׁר","and that which"],
    ["מִנִּיתִי","I have appointed"],
    ["לוֹ","unto him"],
    ["הוּא","is"],
    ["לָלֶכֶת","that he shall go"],
    ["עִם","with"],
    ["עֲבָדַי","my servants"],
    ["אוֹלִיבֵר","Oliver"],
    ["קַאוּדְרִי","Cowdery"],
    ["וּפֶטֶר","and Peter"],
    ["וִיטְמֵר","Whitmer"],
    ["הַבֵּן","Jun."],
    ["אֶל","into"],
    ["הַמִּדְבָּר","the wilderness"],
    ["אֶל","among"],
    ["הַלָּמָנִים׃","the Lamanites"],
    ["׃",""]
  ]},
  { num: "ג", words: [
    ["וְגַם","and also"],
    ["צִיבָא","Ziba"],
    ["יֵלֵךְ","shall go"],
    ["עִמָּהֶם","with them"],
    ["וַאֲנִי","and I"],
    ["עַצְמִי","myself"],
    ["אֵלֵךְ","will go"],
    ["עִמָּהֶם","with them"],
    ["וְאֶהְיֶה","and be"],
    ["בְתוֹכָם","in their midst"],
    ["וַאֲנִי","and I am"],
    ["מֵלִיץ","their advocate"],
    ["לָהֶם",""],
    ["לִפְנֵי","with"],
    ["הָאָב","the Father"],
    ["וְדָבָר","and nothing"],
    ["לֹא","not"],
    ["יִגְבַּר","shall prevail"],
    ["עֲלֵיהֶם׃","against them"],
    ["׃",""]
  ]},
  { num: "ד", words: [
    ["וְיַקְשִׁיבוּ","and they shall give heed"],
    ["לַכָּתוּב","to that which is written"],
    ["וְלֹא","and not"],
    ["יְבַקְשׁוּ","they shall seek"],
    ["לָהֶם","unto them"],
    ["חָזוֹן","revelation"],
    ["אַחֵר","pretend to no other"],
    ["וְיִתְפַּלְּלוּ","and they shall pray"],
    ["תָמִיד","always"],
    ["לְמַעַן","that"],
    ["אֲגַלֶּה","I may unfold"],
    ["אוֹתוֹ","it"],
    ["לְבִינָתָם׃","to their understanding"],
    ["׃",""]
  ]},
  { num: "ה", words: [
    ["וְיַקְשִׁיבוּ","and they shall give heed"],
    ["לַדְּבָרִים","unto words"],
    ["הָאֵלֶּה","these"],
    ["וְלֹא","and not"],
    ["יָבוּזוּ","trifle"],
    ["לָהֶם","unto them"],
    ["וַאֲבָרְכֵם","and I will bless them"],
    ["אָמֵן׃","Amen"],
    ["׃",""]
  ]}
];
renderVerseSet(dc32_ch1Verses, 'dc32-ch1-verses');



var dc33_ch1Verses = [
  { num: "א", words: [
    ["הִנֵּה","behold"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["עֲבָדַי","my servants"],
    ["עֶזְרָא","Ezra"],
    ["וְנוֹרְתְרוֹפּ","and Northrop"],
    ["פִּתְחוּ","open ye"],
    ["אׇזְנֵיכֶם","your ears"],
    ["וְהַאֲזִינוּ","and hearken"],
    ["לְקוֹל","to the voice of"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהֵיכֶם","your God"],
    ["אֲשֶׁר","whose"],
    ["דְּבָרוֹ","word is"],
    ["חַי","quick"],
    ["וְעַצוּם","and powerful"],
    ["חַד","sharper"],
    ["מֵחֶרֶב","than a sword"],
    ["פִּיפִיּוֹת","two-edged"],
    ["לְהַפְרִיד","to the dividing asunder"],
    ["בֵּין","of"],
    ["פֶּרֶק","the joints"],
    ["וּמֹחַ","and marrow"],
    ["נֶפֶשׁ","soul"],
    ["וְרוּחַ","and spirit"],
    ["וּבֹחֵן","and is a discerner of"],
    ["מַחְשְׁבוֹת","the thoughts"],
    ["הַלֵּב","of the heart"],
    ["וּמְזִמּוֹתָיו׃","and its intents"],
    ["׃",""]
  ]},
  { num: "ב", words: [
    ["כִּי","for"],
    ["אָמֵן","verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["נִקְרֵאתֶם","that ye are called"],
    ["לְהָרִים","to lift up"],
    ["קוֹלְכֶם","your voices"],
    ["כְּקוֹל","as with the sound of"],
    ["שׁוֹפָר","a trump"],
    ["לְהַשְׁמִיעַ","to declare"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["לְדוֹר","unto a generation"],
    ["עִקֵּשׁ","crooked"],
    ["וּפְתַלְתֹּל׃","and perverse"],
    ["׃",""]
  ]},
  { num: "ג", words: [
    ["כִּי","for"],
    ["הִנֵּה","behold"],
    ["הַשָּׂדֶה","the field"],
    ["מַלְבִּין","is white"],
    ["לַקָּצִיר","already to harvest"],
    ["וְזֹאת","and"],
    ["הַשָּׁעָה","it is the hour"],
    ["הָאַחַת","eleventh"],
    ["עֶשְׂרֵה",""],
    ["וְהַפַּעַם","and the time"],
    ["הָאַחֲרוֹנָה","last"],
    ["אֲשֶׁר","that"],
    ["אֶקְרָא","I shall call"],
    ["פֹעֲלִים","laborers"],
    ["אֶל","into"],
    ["כַּרְמִי׃","my vineyard"],
    ["׃",""]
  ]},
  { num: "ד", words: [
    ["וְכַרְמִי","and my vineyard"],
    ["הֻשְׁחַת","has become corrupted"],
    ["כֻּלּוֹ","every whit"],
    ["וְאֵין","and there is none"],
    ["עֹשֵׂה","which doeth"],
    ["טוֹב","good"],
    ["זוּלָתִי","save"],
    ["מְעַטִּים","it be a few"],
    ["וְהֵם","and they"],
    ["בַּהֲמוֹן","err in many"],
    ["דְּבָרִים","instances"],
    ["מִפְּנֵי","because of"],
    ["נְכָלֵי","priestcrafts of"],
    ["כֹהֲנִים","priests"],
    ["וְכֻלָּם","all having"],
    ["נִשְׁחָתִים","corrupt"],
    ["בְּדַעְתָּם׃","minds"],
    ["׃",""]
  ]},
  { num: "ה", words: [
    ["וְאָמֵן","and verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["אֶת־הָעֵדָה","that church"],
    ["הַזֹּאת","this"],
    ["הֲקִימוֹתִי","have I established and called forth"],
    ["מִן","out of"],
    ["הַמִּדְבָּר׃","the wilderness"],
    ["׃",""]
  ]},
  { num: "ו", words: [
    ["וְכֵן","and even so"],
    ["אֲקַבֵּץ","will I gather"],
    ["אֶת־בְּחִירַי","mine elect"],
    ["מֵאַרְבַּע","from the four"],
    ["כַּנְפוֹת","quarters of"],
    ["הָאָרֶץ","the earth"],
    ["כׇּל","all"],
    ["הַמַּאֲמִינִים","as will believe"],
    ["בִּי","in me"],
    ["וְהַשֹּׁמְעִים","and hearken"],
    ["לְקוֹלִי׃","and hearken unto my voice"],
    ["׃",""]
  ]},
  { num: "ז", words: [
    ["אָכֵן","yea"],
    ["אָמֵן","verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["הַשָּׂדֶה","the field"],
    ["מַלְבִּין","is white"],
    ["לַקָּצִיר","already to harvest"],
    ["לָכֵן","wherefore"],
    ["שִׁלְחוּ","thrust in"],
    ["מַגָּלֵיכֶם","your sickles"],
    ["וְקִצְרוּ","and reap"],
    ["בְּכׇל","with all"],
    ["מְאֹדְכֶם","your might"],
    ["וּבְכׇל","and"],
    ["דַּעְתְּכֶם","mind"],
    ["וּבְכׇל","and"],
    ["כֹּחֲכֶם׃","strength"],
    ["׃",""]
  ]},
  { num: "ח", words: [
    ["פִּתְחוּ","open"],
    ["פִּיכֶם","your mouths"],
    ["וְיִמָּלְאוּ","and they shall be filled"],
    ["וּתְהִיוּ","and you shall become"],
    ["כְּנְפִי","even as Nephi"],
    ["הַקַּדְמוֹנִי","of old"],
    ["אֲשֶׁר","who"],
    ["הָלַךְ","journeyed"],
    ["מִירוּשָׁלַיִם","from Jerusalem"],
    ["בַּמִּדְבָּר׃","in the wilderness"],
    ["׃",""]
  ]},
  { num: "ט", words: [
    ["אָכֵן","yea"],
    ["פִּתְחוּ","open"],
    ["פִיכֶם","your mouths"],
    ["וְאַל","and spare not"],
    ["תַּחְשֹׂכוּ",""],
    ["וּנְשָׂאתֶם","and ye shall be laden"],
    ["אֲלֻמּוֹת","with sheaves"],
    ["עַל","concerning"],
    ["גַּבְּכֶם","your backs"],
    ["כִּי","for"],
    ["הִנֵּה","behold"],
    ["אִתְּכֶם","with you"],
    ["אָנֹכִי׃","I am"],
    ["׃",""]
  ]},
  { num: "י", words: [
    ["אָכֵן","yea"],
    ["פִּתְחוּ","open"],
    ["פִּיכֶם","your mouths"],
    ["וְיִמָּלְאוּ","and they shall be filled"],
    ["לֵאמֹר","saying"],
    ["שׁוּבוּ","repent"],
    ["שׁוּבוּ","repent"],
    ["וְהָכִינוּ","and prepare ye"],
    ["דֶּרֶךְ","the way of"],
    ["יְהוָה","the Lord"],
    ["וְיַשְּׁרוּ","and make straight"],
    ["נְתִיבוֹתָיו","his paths"],
    ["כִּי","for"],
    ["קָרְבָה","is at hand"],
    ["מַלְכוּת","the kingdom of"],
    ["הַשָּׁמָיִם׃","heaven"],
    ["׃",""]
  ]},
  { num: "יא", words: [
    ["אָכֵן","yea"],
    ["שׁוּבוּ","repent"],
    ["וְהִטָּבְלוּ","and be baptized"],
    ["אִישׁ","every"],
    ["אִישׁ","one"],
    ["מִכֶּם","of you"],
    ["לִסְלִיחַת","for a remission of"],
    ["חַטֹּאתֵיכֶם","your sins"],
    ["אָכֵן","yea"],
    ["הִטָּבְלוּ","be baptized even"],
    ["בַּמַּיִם","by water"],
    ["וְאָז","and then"],
    ["תָּבוֹא","cometh"],
    ["טְבִילַת","the baptism of"],
    ["הָאֵשׁ","fire"],
    ["וְרוּחַ","and the Holy Ghost"],
    ["הַקֹּדֶשׁ׃",""],
    ["׃",""]
  ]},
  { num: "יב", words: [
    ["הִנֵּה","behold"],
    ["אָמֵן","verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["זֹאת","this is"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["וְזִכְרוּ","and remember that"],
    ["כִּי","that"],
    ["יַאֲמִינוּ","they shall have faith"],
    ["בִי","in me"],
    ["אוֹ","or"],
    ["לֹא","not"],
    ["יוּכְלוּ","they can in nowise"],
    ["לְהִוָּשַׁע׃","be saved"],
    ["׃",""]
  ]},
  { num: "יג", words: [
    ["וְעַל","and upon"],
    ["הַסֶּלַע","rock"],
    ["הַזֶּה","this"],
    ["אֶבְנֶה","I will build"],
    ["עֲדָתִי","my church"],
    ["אָכֵן","yea"],
    ["עַל","upon"],
    ["הַסֶּלַע","rock"],
    ["הַזֶּה","this"],
    ["בְּנוּיִים","are built"],
    ["אַתֶּם","ye"],
    ["וְאִם","and if"],
    ["תַּמְשִׁיכוּ","ye continue"],
    ["לֹא","not"],
    ["תִגְבַּר","shall prevail"],
    ["עֲלֵיכֶם","against you"],
    ["שְׁעָרֵי","the gates of"],
    ["שְׁאוֹל׃","hell"],
    ["׃",""]
  ]},
  { num: "יד", words: [
    ["וּזְכַרְתֶּם","and ye shall remember"],
    ["אֶת־כִּתְבֵי","the articles of"],
    ["הָעֵדָה","the church"],
    ["וּבְרִיתוֹתֶיהָ","and its covenants"],
    ["לְשָׁמְרָם׃","to keep them"],
    ["׃",""]
  ]},
  { num: "טו", words: [
    ["וְכֹל","and whoso"],
    ["בַּעַל","having"],
    ["אֱמוּנָה","faith"],
    ["תְּאַשְּׁרוּ","you shall confirm"],
    ["בַּעֲדָתִי","in my church"],
    ["בִּסְמִיכַת","by the laying on of"],
    ["יָדַיִם","the hands"],
    ["וְאֶשְׁפֹּךְ","and I will bestow"],
    ["עֲלֵיהֶם","upon them"],
    ["מַתַּת","the gift of"],
    ["רוּחַ","the Holy Ghost"],
    ["הַקֹּדֶשׁ׃",""],
    ["׃",""]
  ]},
  { num: "טז", words: [
    ["וְסֵפֶר","and the Book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["וְכִתְבֵי","and the scriptures"],
    ["הַקֹּדֶשׁ","holy"],
    ["נִתְּנוּ","are given"],
    ["מִמֶּנִּי","of me"],
    ["לְהוֹרוֹתְכֶם","for your instruction"],
    ["וְכֹחַ","and the power of"],
    ["רוּחִי","my Spirit"],
    ["יְחַיֶּה","quickeneth"],
    ["הַכֹּל׃","all things"],
    ["׃",""]
  ]},
  { num: "יז", words: [
    ["לָכֵן","wherefore"],
    ["הֱיוּ","be"],
    ["נֶאֱמָנִים","faithful"],
    ["וְהִתְפַּלְּלוּ","praying"],
    ["תָמִיד","always"],
    ["נֵרוֹתֵיכֶם","having your lamps"],
    ["מוּטָבִים","trimmed"],
    ["וּבֹעֲרִים","and burning"],
    ["וְשֶׁמֶן","and oil"],
    ["עִמָּכֶם","with you"],
    ["לְמַעַן","that"],
    ["תִּהְיוּ","you may be"],
    ["נְכוֹנִים","ready"],
    ["לְבוֹא","at the coming of"],
    ["הֶחָתָן׃","the Bridegroom"],
    ["׃",""]
  ]},
  { num: "יח", words: [
    ["כִּי","for"],
    ["הִנֵּה","behold"],
    ["אָמֵן","verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["מְהֵרָה","quickly"],
    ["אָבוֹא","I come"],
    ["כֵּן","even so"],
    ["יְהִי",""],
    ["אָמֵן׃","Amen"],
    ["׃",""]
  ]}
];
renderVerseSet(dc33_ch1Verses, 'dc33-ch1-verses');



var dc34_ch1Verses = [
  { num: "א", words: [
    ["בְּנִי","my son"],
    ["אוֹרְסוֹן","Orson"],
    ["הַאֲזֵן","hearken"],
    ["וּשְׁמַע","and hear"],
    ["וּרְאֵה","and behold"],
    ["אֲשֶׁר","what"],
    ["אֲנִי","I"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהִים","God"],
    ["אֹמַר","shall say"],
    ["לְךָ","unto you"],
    ["יֵשׁוּעַ","even Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["גֹּאַלְךָ׃","your Redeemer"],
    ["׃",""]
  ]},
  { num: "ב", words: [
    ["אוֹר","the light"],
    ["הָעוֹלָם","of the world"],
    ["וְחַיָּיו","and its life"],
    ["אוֹר","a light"],
    ["הַזֹּרֵחַ","which shineth"],
    ["בַּחֹשֶׁךְ","in darkness"],
    ["וְהַחֹשֶׁךְ","and the darkness"],
    ["לֹא","not"],
    ["הִשִּׂיגוֹ׃","comprehendeth it"],
    ["׃",""]
  ]},
  { num: "ג", words: [
    ["אֲשֶׁר","who"],
    ["כֹּה","so"],
    ["אָהַב","loved"],
    ["אֶת־הָעוֹלָם","the world"],
    ["וַיִּתֵּן","that he gave"],
    ["אֶת־נַפְשׁוֹ","his own life"],
    ["לְמַעַן","that"],
    ["כׇּל","as many as"],
    ["הַמַּאֲמִינִים","would believe"],
    ["יִהְיוּ","might become"],
    ["בְּנֵי","the sons of"],
    ["הָאֱלֹהִים","God"],
    ["לָכֵן","wherefore"],
    ["אַתָּה","you are"],
    ["בְּנִי׃","my son"],
    ["׃",""]
  ]},
  { num: "ד", words: [
    ["וּבָרוּךְ","and blessed are"],
    ["אַתָּה","you"],
    ["כִּי","because"],
    ["הֶאֱמָנְתָּ׃","you have believed"],
    ["׃",""]
  ]},
  { num: "ה", words: [
    ["וּבָרוּךְ","and more blessed are"],
    ["עוֹד","you"],
    ["כִּי","because"],
    ["נִקְרֵאתָ","you are called"],
    ["מִמֶּנִּי","of me"],
    ["לִדְרֹשׁ","to preach"],
    ["בְּשׂוֹרָתִי׃","my gospel"],
    ["׃",""]
  ]},
  { num: "ו", words: [
    ["לְהָרִים","to lift up"],
    ["קוֹלְךָ","your voice"],
    ["כְּקוֹל","as with the sound of"],
    ["שׁוֹפָר","a trump"],
    ["אָרֹךְ","both long"],
    ["וְחָזָק","and loud"],
    ["וְלִקְרֹא","and cry"],
    ["תְשׁוּבָה","repentance"],
    ["לְדוֹר","unto a generation"],
    ["עִקֵּשׁ","crooked"],
    ["וּפְתַלְתֹּל","and perverse"],
    ["לְהָכִין","preparing"],
    ["דֶּרֶךְ","the way of"],
    ["יְהוָה","the Lord"],
    ["לְבוֹאוֹ","for his coming"],
    ["הַשֵּׁנִי׃","second"],
    ["׃",""]
  ]},
  { num: "ז", words: [
    ["כִּי","for"],
    ["הִנֵּה","behold"],
    ["אָמֵן","verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["קָרְבָה","is soon at hand"],
    ["הָעֵת","the time"],
    ["אֲשֶׁר","that"],
    ["אָבוֹא","I shall come"],
    ["בְּעָנָן","in a cloud"],
    ["בְּכֹחַ","with power"],
    ["וּבְכָבוֹד","and glory"],
    ["גָּדוֹל׃","great"],
    ["׃",""]
  ]},
  { num: "ח", words: [
    ["וְהָיָה","and it shall be"],
    ["יוֹם","a day"],
    ["גָּדוֹל","great"],
    ["בְּעֵת","at the time of"],
    ["בּוֹאִי","my coming"],
    ["כִּי","for"],
    ["כׇל","all"],
    ["הַגּוֹיִם","nations"],
    ["יֶחֱרָדוּ׃","shall tremble"],
    ["׃",""]
  ]},
  { num: "ט", words: [
    ["אַךְ","but"],
    ["לִפְנֵי","before"],
    ["בוֹא","shall come"],
    ["הַיּוֹם","day"],
    ["הַגָּדוֹל","great"],
    ["הַהוּא","that"],
    ["יֶחְשַׁךְ","shall be darkened"],
    ["הַשֶּׁמֶשׁ","the sun"],
    ["וְהַיָּרֵחַ","and the moon"],
    ["יֵהָפֵךְ","be turned"],
    ["לְדָם","into blood"],
    ["וְהַכּוֹכָבִים","and the stars"],
    ["יְמָאֲנוּ","shall refuse"],
    ["לְהָאִיר","their shining"],
    ["וּמֵהֶם","and some"],
    ["יִפְּלוּ","shall fall"],
    ["וְחֻרְבָּנוֹת","and destructions"],
    ["גְּדוֹלִים","great"],
    ["מְחַכִּים","await"],
    ["לָרְשָׁעִים׃","the wicked"],
    ["׃",""]
  ]},
  { num: "י", words: [
    ["לָכֵן","wherefore"],
    ["הָרֵם","lift up"],
    ["קוֹלְךָ","your voice"],
    ["וְאַל","and spare not"],
    ["תַּחְשֹׂךְ",""],
    ["כִּי","for"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהִים","God"],
    ["דִּבֵּר","hath spoken"],
    ["לָכֵן","therefore"],
    ["הִנָּבֵא","prophesy"],
    ["וְיִנָּתֵן","and it shall be given"],
    ["בְּכֹחַ","by the power of"],
    ["רוּחַ","the Holy Ghost"],
    ["הַקֹּדֶשׁ׃",""],
    ["׃",""]
  ]},
  { num: "יא", words: [
    ["וְאִם","and if"],
    ["תִּהְיֶה","you are"],
    ["נֶאֱמָן","faithful"],
    ["הִנֵּה","behold"],
    ["אִתְּךָ","with you"],
    ["אָנֹכִי","I am"],
    ["עַד","until"],
    ["בּוֹאִי׃","I come"],
    ["׃",""]
  ]},
  { num: "יב", words: [
    ["וְאָמֵן","and verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["מְהֵרָה","quickly"],
    ["אָבוֹא","I come"],
    ["אֲנִי","I am"],
    ["אֲדֹנֵיכֶם","your Lord"],
    ["וְגֹאַלְכֶם","and your Redeemer"],
    ["כֵּן","even so"],
    ["יְהִי",""],
    ["אָמֵן׃","Amen"],
    ["׃",""]
  ]}
];
renderVerseSet(dc34_ch1Verses, 'dc34-ch1-verses');



var dc35_ch1Verses = [
  { num: "א", words: [
    ["שִׁמְעוּ","listen"],
    ["לְקוֹל","to the voice of"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהֵיכֶם","your God"],
    ["הָרִאשׁוֹן","even Alpha"],
    ["וְהָאַחֲרוֹן","and Omega"],
    ["הָרֵאשִׁית","the beginning"],
    ["וְהַתַּכְלִית","and the end"],
    ["אֲשֶׁר","whose"],
    ["דַּרְכּוֹ","course is"],
    ["מַעְגָּל","one round"],
    ["נִצְחִי","eternal"],
    ["הוּא","the same"],
    ["הַיּוֹם","today"],
    ["כִּתְמוֹל","as yesterday"],
    ["וּלְעוֹלָם׃","and forever"],
    ["׃",""]
  ]},
  { num: "ב", words: [
    ["אֲנִי","I am"],
    ["יֵשׁוּעַ","Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["בֶּן","the Son of"],
    ["הָאֱלֹהִים","God"],
    ["אֲשֶׁר","who"],
    ["נִצְלַב","was crucified"],
    ["בְּעַד","for"],
    ["חַטֹּאת","the sins of"],
    ["הָעוֹלָם","the world"],
    ["כׇּל","even as many"],
    ["הַמַּאֲמִינִים","as will believe"],
    ["בִּשְׁמִי","on my name"],
    ["לְמַעַן","that"],
    ["יִהְיוּ","they may become"],
    ["בְּנֵי","the sons of"],
    ["הָאֱלֹהִים","God"],
    ["אֶחָד","even one"],
    ["בִּי","in me"],
    ["כַּאֲשֶׁר","as"],
    ["אֲנִי","I"],
    ["אֶחָד","am one"],
    ["בָּאָב","in the Father"],
    ["וְהָאָב","as the Father"],
    ["אֶחָד","is one"],
    ["בִּי","in me"],
    ["לְמַעַן","that"],
    ["נִהְיֶה","we may be"],
    ["אֶחָד׃","one"],
    ["׃",""]
  ]},
  { num: "ג", words: [
    ["הִנֵּה","behold"],
    ["אָמֵן","verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְעַבְדִּי","unto my servant"],
    ["סִידְנִי","Sidney"],
    ["הִבַּטְתִּי","I have looked"],
    ["עָלֶיךָ","upon thee"],
    ["וְעַל","and upon"],
    ["מַעֲשֶׂיךָ","thy works"],
    ["שָׁמַעְתִּי","I have heard"],
    ["תְּפִלָּתֶךָ","thy prayers"],
    ["לִמְלָאכָה","and prepared thee for a work"],
    ["גְדוֹלָה׃","greater"],
    ["׃",""]
  ]},
  { num: "ד", words: [
    ["בָּרוּךְ","blessed"],
    ["אַתָּה","art thou"],
    ["כִּי","for"],
    ["דְבָרִים","things"],
    ["גְּדוֹלִים","great"],
    ["תַּעֲשֶׂה","thou shalt do"],
    ["הִנֵּה","behold"],
    ["נִשְׁלַחְתָּ","thou wast sent forth"],
    ["כְּיוֹחָנָן","even as John"],
    ["לְהָכִין","to prepare"],
    ["הַדֶּרֶךְ","the way"],
    ["לְפָנַי","before me"],
    ["וְלִפְנֵי","and before"],
    ["אֵלִיָּהוּ","Elijah"],
    ["אֲשֶׁר","which"],
    ["יָבוֹא","should come"],
    ["וְלֹא","and not"],
    ["יָדָעְתָּ׃","thou knewest it"],
    ["׃",""]
  ]},
  { num: "ה", words: [
    ["הִטְבַּלְתָּ","thou didst baptize"],
    ["בְמַיִם","by water"],
    ["לִתְשׁוּבָה","unto repentance"],
    ["אַךְ","but"],
    ["הֵם","they"],
    ["לֹא","not"],
    ["קִבְּלוּ","received"],
    ["אֶת־רוּחַ","the Holy Ghost"],
    ["הַקֹּדֶשׁ׃",""],
    ["׃",""]
  ]},
  { num: "ו", words: [
    ["וְעַתָּה","but now"],
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לְךָ","unto thee"],
    ["מִצְוָה","a commandment"],
    ["לְהַטְבִּיל","that thou shalt baptize"],
    ["בְּמַיִם","by water"],
    ["וְהֵם","and they"],
    ["יְקַבְּלוּ","shall receive"],
    ["אֶת־רוּחַ","the Holy Ghost"],
    ["הַקֹּדֶשׁ",""],
    ["בִּסְמִיכַת","by the laying on of"],
    ["הַיָּדַיִם","the hands"],
    ["כְּשָׁלִיחֵי","even as the apostles of"],
    ["קֶדֶם׃","old"],
    ["׃",""]
  ]},
  { num: "ז", words: [
    ["וְהָיָה","and it shall come to pass that"],
    ["מְלָאכָה","a work"],
    ["גְדוֹלָה","great"],
    ["בָּאָרֶץ","shall be in the land"],
    ["בֵּין","even among"],
    ["הַגּוֹיִם","the Gentiles"],
    ["כִּי","for"],
    ["סִכְלוּתָם","their folly"],
    ["וְתוֹעֲבוֹתֵיהֶם","and their abominations"],
    ["יִגָּלוּ","shall be made manifest"],
    ["לְעֵינֵי","in the eyes of"],
    ["כׇל","all"],
    ["הָעַמִּים׃","people"],
    ["׃",""]
  ]},
  { num: "ח", words: [
    ["כִּי","for"],
    ["אֱלֹהִים","God"],
    ["אָנֹכִי","I am"],
    ["וּזְרוֹעִי","and mine arm"],
    ["לֹא","not"],
    ["קָצְרָה","is shortened"],
    ["וְאַרְאֶה","and I will show"],
    ["מוֹפְתִים","miracles"],
    ["אוֹתוֹת","signs"],
    ["וְנִפְלָאוֹת","and wonders"],
    ["לְכׇל","unto all"],
    ["הַמַּאֲמִינִים","those who believe"],
    ["בִּשְׁמִי׃","on my name"],
    ["׃",""]
  ]},
  { num: "ט", words: [
    ["וְכׇל","and whoso"],
    ["הַשֹּׁאֵל","shall ask it"],
    ["בִּשְׁמִי","in my name"],
    ["בֶּאֱמוּנָה","in faith"],
    ["יְגָרֵשׁ","they shall cast out"],
    ["שֵׁדִים","devils"],
    ["יִרְפָּא","they shall heal"],
    ["חוֹלִים","the sick"],
    ["יַעֲשֶׂה","they shall cause"],
    ["עִוְרִים","the blind"],
    ["לִרְאוֹת","to receive their sight"],
    ["וְחֵרְשִׁים","and the deaf"],
    ["לִשְׁמֹעַ","to hear"],
    ["וְאִלְּמִים","and the dumb"],
    ["לְדַבֵּר","to speak"],
    ["וּפִסְחִים","and the lame"],
    ["לָלֶכֶת׃","to walk"],
    ["׃",""]
  ]},
  { num: "י", words: [
    ["וּבִמְהֵרָה","and speedily"],
    ["תָּבוֹא","cometh"],
    ["הָעֵת","the time"],
    ["אֲשֶׁר","that"],
    ["דְּבָרִים","things"],
    ["גְּדוֹלִים","great"],
    ["יִגָּלוּ","are to be shown forth"],
    ["לִבְנֵי","unto the children of"],
    ["הָאָדָם׃","men"],
    ["׃",""]
  ]},
  { num: "יא", words: [
    ["אַךְ","but"],
    ["בְּלֹא","without"],
    ["אֱמוּנָה","faith"],
    ["לֹא","not"],
    ["יִגָּלֶה","shall be shown forth"],
    ["דָבָר","anything"],
    ["זוּלָתִי","except"],
    ["חֻרְבַּן","desolations"],
    ["עַל","upon"],
    ["בָּבֶל","Babylon"],
    ["אֲשֶׁר","the same which"],
    ["הִשְׁקְתָה","has made drink"],
    ["כׇל","all"],
    ["גּוֹיִם","nations"],
    ["מִיֵּין","of the wine of"],
    ["חֲמַת","the wrath of"],
    ["זְנוּתָהּ׃","her fornication"],
    ["׃",""]
  ]},
  { num: "יב", words: [
    ["וְאֵין","and there are none"],
    ["עֹשֶׂה","that doeth"],
    ["טוֹב","good"],
    ["זוּלָתִי","except"],
    ["הַנְּכוֹנִים","those who are ready"],
    ["לְקַבֵּל","to receive"],
    ["מְלֹא","the fulness of"],
    ["בְשׂוֹרָתִי","my gospel"],
    ["אֲשֶׁר","which"],
    ["שָׁלַחְתִּי","I have sent forth"],
    ["לַדּוֹר","unto generation"],
    ["הַזֶּה׃","this"],
    ["׃",""]
  ]},
  { num: "יג", words: [
    ["לָכֵן","wherefore"],
    ["קֹרֵא","I call"],
    ["אֲנִי",""],
    ["הָעוֹלָם","upon the weak things of the world"],
    ["אֲשֶׁר","those who"],
    ["אֵין","have no"],
    ["לָהֶם",""],
    ["לֶקַח","learning"],
    ["וְנִבְזִים","and are despised"],
    ["הֵמָּה",""],
    ["לָדוּשׁ","to thresh"],
    ["הַגּוֹיִם","the nations"],
    ["בְּכֹחַ","by the power of"],
    ["רוּחִי׃","my Spirit"],
    ["׃",""]
  ]},
  { num: "יד", words: [
    ["וּזְרוֹעָם","and their arm"],
    ["תִּהְיֶה","shall be"],
    ["זְרוֹעִי","my arm"],
    ["וַאֲנִי","and I"],
    ["אֶהְיֶה","will be"],
    ["מָגִנָּם","their shield"],
    ["וְצִנָּתָם","their shield and their buckler"],
    ["וַאֲאַזֵּר","and I will gird up"],
    ["מׇתְנֵיהֶם","their loins"],
    ["וְנִלְחֲמוּ","and they shall fight"],
    ["בְגֶבֶר","manfully"],
    ["לְמַעֲנִי","for me"],
    ["וְאֹיְבֵיהֶם","and their enemies"],
    ["יִהְיוּ","shall be"],
    ["תַּחַת","under"],
    ["רַגְלֵיהֶם","their feet"],
    ["וְאַפִּיל","and I will let fall"],
    ["חֶרֶב","the sword"],
    ["לְמַעֲנָם","in their behalf"],
    ["וּבְאֵשׁ","and by the fire of"],
    ["זַעְמִי","mine indignation"],
    ["אֶשְׁמְרֵם׃","will I preserve them"],
    ["׃",""]
  ]},
  { num: "טו", words: [
    ["וְלָעֲנָוִים","and the poor"],
    ["וְלָעֲנִיִּים","and the meek"],
    ["תִּדָּרֵשׁ","shall have preached unto them"],
    ["הַבְּשׂוֹרָה","the gospel"],
    ["וְהֵם","and they"],
    ["יְצַפּוּ","shall be looking forth"],
    ["לְעֵת","for the time of"],
    ["בּוֹאִי","my coming"],
    ["כִּי","for"],
    ["קְרוֹבָה","it is nigh at hand"],
    ["הִיא׃",""],
    ["׃",""]
  ]},
  { num: "טז", words: [
    ["וְיִלְמְדוּ","and they shall learn"],
    ["מְשַׁל","the parable of"],
    ["הַתְּאֵנָה","the fig tree"],
    ["כִּי","for"],
    ["הִנֵּה","behold"],
    ["כְבָר","even now already"],
    ["הַקַּיִץ","summer"],
    ["קָרוֹב׃","is nigh"],
    ["׃",""]
  ]},
  { num: "יז", words: [
    ["וְשָׁלַחְתִּי","and I have sent forth"],
    ["מְלֹא","the fulness of"],
    ["בְשׂוֹרָתִי","my gospel"],
    ["בְּיַד","by the hand of"],
    ["עַבְדִּי","my servant"],
    ["יוֹסֵף","Joseph"],
    ["וּבַחֻלְשָׁה","and in weakness"],
    ["בֵּרַכְתִּיו׃","I blessed him"],
    ["׃",""]
  ]},
  { num: "יח", words: [
    ["וְנָתַתִּי","and I have given"],
    ["לוֹ","unto him"],
    ["מַפְתְּחוֹת","the keys of"],
    ["סוֹד","the mystery of"],
    ["הַדְּבָרִים","those things"],
    ["הַחֲתוּמִים","which have been sealed"],
    ["דְּבָרִים","even things"],
    ["אֲשֶׁר","which were"],
    ["מִיסוֹד","from the foundation of"],
    ["הָעוֹלָם","the world"],
    ["וַאֲשֶׁר","and the things which"],
    ["יָבֹאוּ","shall come"],
    ["מֵעֵת","from time"],
    ["הַזֹּאת","this"],
    ["עַד","until"],
    ["עֵת","the time of"],
    ["בּוֹאִי","my coming"],
    ["אִם","if"],
    ["יַעֲמֹד","he abide"],
    ["בִּי","in me"],
    ["וְאִם","and if"],
    ["לֹא","not"],
    ["אָטַע","I will plant"],
    ["אַחֵר","another"],
    ["תַּחְתָּיו׃","in his stead"],
    ["׃",""]
  ]},
  { num: "יט", words: [
    ["לָכֵן","wherefore"],
    ["שְׁמֹר","watch"],
    ["עָלָיו","over him"],
    ["פֶּן","that"],
    ["תִּכָּשֵׁל","fail not"],
    ["אֱמוּנָתוֹ","his faith"],
    ["וְיִנָּתֵן","and it shall be given"],
    ["בְּיַד","by"],
    ["הַמְּנַחֵם","the Comforter"],
    ["רוּחַ","the Holy Ghost"],
    ["הַקֹּדֶשׁ",""],
    ["הַיּוֹדֵעַ","that knoweth"],
    ["כׇּל","all"],
    ["דָּבָר׃","things"],
    ["׃",""]
  ]},
  { num: "כ", words: [
    ["וּמִצְוָה","and a commandment"],
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לְךָ","unto thee"],
    ["לִכְתֹּב","that thou shalt write"],
    ["לוֹ","for him"],
    ["וְהַכְּתוּבִים","and the scriptures"],
    ["יִנָּתְנוּ","shall be given"],
    ["כַּאֲשֶׁר","even as"],
    ["הֵם","they are"],
    ["בְּחֵיקִי","in mine own bosom"],
    ["לִישׁוּעַת","to the salvation of"],
    ["בְּחִירַי׃","mine own elect"],
    ["׃",""]
  ]},
  { num: "כא", words: [
    ["כִּי","for"],
    ["יִשְׁמְעוּ","they will hear"],
    ["קוֹלִי","my voice"],
    ["וְיִרְאוּנִי","and shall see me"],
    ["וְלֹא","and shall not"],
    ["יִישְׁנוּ","be asleep"],
    ["וְיַעַמְדוּ","and shall abide"],
    ["בְּיוֹם","the day of"],
    ["בּוֹאִי","my coming"],
    ["כִּי","for"],
    ["יִטְהָרוּ","they shall be purified"],
    ["כַּאֲשֶׁר","even as"],
    ["אֲנִי","I am"],
    ["טָהוֹר׃","pure"],
    ["׃",""]
  ]},
  { num: "כב", words: [
    ["וְעַתָּה","and now"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["שְׁבוּ","tarry"],
    ["עִמּוֹ","with him"],
    ["וְהוּא","and he"],
    ["יֵלֵךְ","shall journey"],
    ["עִמָּכֶם","with you"],
    ["אַל","not"],
    ["תַּעַזְבֻהוּ","forsake him"],
    ["וְאָכֵן","and surely"],
    ["הַדְּבָרִים","things"],
    ["הָאֵלֶּה","these"],
    ["יִתְקַיָּמוּ׃","shall be fulfilled"],
    ["׃",""]
  ]},
  { num: "כג", words: [
    ["וּבְעֵת","and inasmuch as"],
    ["אֲשֶׁר",""],
    ["לֹא","not"],
    ["תִכְתֹּב","ye do write"],
    ["הִנֵּה","behold"],
    ["יִנָּתֵן","it shall be given"],
    ["לוֹ","unto him"],
    ["לְהִנָּבֵא","to prophesy"],
    ["וְאַתָּה","and thou"],
    ["תִדְרֹשׁ","shalt preach"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["וְתִקְרָא","and call"],
    ["אֶל","on"],
    ["נְבִיאֵי","the prophets"],
    ["הַקֹּדֶשׁ","holy"],
    ["לְהוֹכִיחַ","to prove"],
    ["דְּבָרָיו","his words"],
    ["כַּאֲשֶׁר","as"],
    ["יִנָּתְנוּ","they shall be given"],
    ["לוֹ׃","him"],
    ["׃",""]
  ]},
  { num: "כד", words: [
    ["שִׁמְרוּ","keep"],
    ["כׇּל","all"],
    ["הַמִּצְוֹת","the commandments"],
    ["וְהַבְּרִיתוֹת","and covenants"],
    ["אֲשֶׁר","which"],
    ["אַתֶּם","ye"],
    ["קְשׁוּרִים","are bound"],
    ["בָּהֶן",""],
    ["וְאָנִיעַ","and I will cause to shake"],
    ["אֶת־הַשָּׁמַיִם","the heavens"],
    ["לְטוֹבַתְכֶם","to shake for your good"],
    ["וְהַשָּׂטָן","and Satan"],
    ["יֶחֱרַד","shall tremble"],
    ["וְצִיּוֹן","and Zion"],
    ["תָּגֵל","shall rejoice"],
    ["עַל","concerning"],
    ["הֶהָרִים","the hills"],
    ["וּפָרְחָה׃","and flourish"],
    ["׃",""]
  ]},
  { num: "כה", words: [
    ["וְיִשְׂרָאֵל","and Israel"],
    ["יִוָּשַׁע","shall be saved"],
    ["בְּעִתִּי","in mine own due time"],
    ["וּבַמַּפְתְּחוֹת","and by the keys"],
    ["אֲשֶׁר","which"],
    ["נָתַתִּי","I have given"],
    ["יִנָּהֲגוּ","shall they be led"],
    ["וְלֹא","and no"],
    ["יִכָּלְמוּ","more be confounded"],
    ["עוֹד׃","at all"],
    ["׃",""]
  ]},
  { num: "כו", words: [
    ["הָרִימוּ","lift up"],
    ["לְבַבְכֶם","your hearts"],
    ["וְשִׂמְחוּ","and be glad"],
    ["כִּי","for"],
    ["גְאֻלַּתְכֶם","your redemption"],
    ["קְרוֹבָה׃","draweth nigh"],
    ["׃",""]
  ]},
  { num: "כז", words: [
    ["אַל","not"],
    ["תִּירְאוּ","fear"],
    ["עֵדֶר","little flock"],
    ["קָטָן",""],
    ["הַמַּמְלָכָה","the kingdom"],
    ["לָכֶם","is yours"],
    ["הִיא",""],
    ["עַד","until"],
    ["בּוֹאִי","I come"],
    ["הִנֵּה","behold"],
    ["מְהֵרָה","quickly"],
    ["אָבוֹא","I come"],
    ["כֵּן","even so"],
    ["יְהִי",""],
    ["אָמֵן׃","Amen"],
    ["׃",""]
  ]}
];
renderVerseSet(dc35_ch1Verses, 'dc35-ch1-verses');



var dc36_ch1Verses = [
  { num: "א", words: [
    ["כֹּה","thus"],
    ["אָמַר","saith"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהִים","God"],
    ["אֲבִיר","the Mighty One of"],
    ["יִשְׂרָאֵל","Israel"],
    ["הִנֵּה","behold"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְךָ","unto you"],
    ["עַבְדִּי","my servant"],
    ["אֶדְוָרְד","Edward"],
    ["בָּרוּךְ","that blessed"],
    ["אַתָּה","you are"],
    ["וְחַטֹּאתֶיךָ","and your sins"],
    ["נִסְלְחוּ","are forgiven"],
    ["לָךְ","you"],
    ["וְנִקְרֵאתָ","and you are called"],
    ["לִדְרֹשׁ","to preach"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["כְּקוֹל","as with the voice of"],
    ["שׁוֹפָר׃","a trump"],
    ["׃",""]
  ]},
  { num: "ב", words: [
    ["וַאֲנִי","and I"],
    ["אָשִׂים","will lay"],
    ["יָדִי","my hand"],
    ["עָלֶיךָ","upon you"],
    ["בְּיַד","by the hand of"],
    ["עַבְדִּי","my servant"],
    ["סִידְנִי","Sidney"],
    ["רִיגְדּוֹן","Rigdon"],
    ["וּתְקַבֵּל","and you shall receive"],
    ["רוּחִי","my Spirit"],
    ["רוּחַ","the Holy Ghost"],
    ["הַקֹּדֶשׁ",""],
    ["הַמְּנַחֵם","even the Comforter"],
    ["אֲשֶׁר","which"],
    ["יְלַמֶּדְךָ","shall teach you"],
    ["דִּבְרֵי","the things of"],
    ["שָׁלוֹם","peace"],
    ["הַמַּמְלָכָה׃","of the kingdom"],
    ["׃",""]
  ]},
  { num: "ג", words: [
    ["וְהִגַּדְתָּ","and you shall declare it"],
    ["בְּקוֹל","with a voice"],
    ["גָּדוֹל","loud"],
    ["לֵאמֹר","saying"],
    ["הוֹשַׁעְנָא","hosanna"],
    ["בָּרוּךְ","blessed be"],
    ["שֵׁם","the name of"],
    ["אֵל","God"],
    ["עֶלְיוֹן׃","the most high"],
    ["׃",""]
  ]},
  { num: "ד", words: [
    ["וְעַתָּה","and now"],
    ["הַקְּרִיאָה","calling"],
    ["הַזֹּאת","this"],
    ["וְהַמִּצְוָה","and commandment"],
    ["הַזֹּאת","this"],
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לָכֶם","unto you"],
    ["עַל","concerning"],
    ["כׇּל","all"],
    ["אָדָם׃","men"],
    ["׃",""]
  ]},
  { num: "ה", words: [
    ["כׇּל","that as many as"],
    ["הַבָּאִים","shall come"],
    ["לִפְנֵי","before"],
    ["עֲבָדַי","my servants"],
    ["סִידְנִי","Sidney"],
    ["רִיגְדּוֹן","Rigdon"],
    ["וְיוֹסֵף","and Joseph"],
    ["סְמִית","Smith"],
    ["הַבֵּן","Jun."],
    ["וּמְקַבְּלִים","embracing"],
    ["אֶת",""],
    ["הַקְּרִיאָה","calling"],
    ["הַזֹּאת","this"],
    ["וְהַמִּצְוָה","and commandment"],
    ["הַזֹּאת",""],
    ["יִסָּמְכוּ","shall be ordained"],
    ["וְיִשָּׁלְחוּ","and sent forth"],
    ["לִדְרֹשׁ","to preach"],
    ["בְּשׂוֹרַת","the gospel"],
    ["עוֹלָם","everlasting"],
    ["בַּגּוֹיִם׃","among the nations"],
    ["׃",""]
  ]},
  { num: "ו", words: [
    ["קֹרְאִים","crying"],
    ["תְּשׁוּבָה","repentance"],
    ["לֵאמֹר","saying"],
    ["הִנָּצְלוּ","save yourselves"],
    ["מִן","from"],
    ["הַדּוֹר","generation"],
    ["הָעִקֵּשׁ","untoward"],
    ["הַזֶּה","this"],
    ["וּצְאוּ","and come forth"],
    ["מִן","out of"],
    ["הָאֵשׁ","the fire"],
    ["וְשִׂנְאוּ","hating"],
    ["גַּם","even"],
    ["אֶת־הַבֶּגֶד","the garments"],
    ["הַנִּכְתָּם","spotted"],
    ["בַּבָּשָׂר׃","with the flesh"],
    ["׃",""]
  ]},
  { num: "ז", words: [
    ["וְהַמִּצְוָה","and commandment"],
    ["הַזֹּאת","this"],
    ["תִּנָּתֵן","shall be given"],
    ["לְזִקְנֵי","unto the elders of"],
    ["עֲדָתִי","my church"],
    ["כׇּל","that every"],
    ["אִישׁ","man"],
    ["אֲשֶׁר","which"],
    ["יְקַבְּלֶנָּה","will embrace it"],
    ["בְּתֹם","with singleness of"],
    ["לֵבָב","heart"],
    ["יִסָּמֵךְ","may be ordained"],
    ["וְיִשָּׁלַח","and sent forth"],
    ["כַּאֲשֶׁר","even as"],
    ["דִּבַּרְתִּי׃","I have spoken"],
    ["׃",""]
  ]},
  { num: "ח", words: [
    ["אֲנִי","I am"],
    ["יֵשׁוּעַ","Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["בֶּן","the Son of"],
    ["הָאֱלֹהִים","God"],
    ["לָכֵן","wherefore"],
    ["אִזְרוּ","gird up"],
    ["מׇתְנֵיכֶם","your loins"],
    ["וּפִתְאֹם","and suddenly"],
    ["אָבוֹא","I will come"],
    ["אֶל","to"],
    ["הֵיכָלִי","my temple"],
    ["כֵּן","even so"],
    ["יְהִי",""],
    ["אָמֵן׃","Amen"],
    ["׃",""]
  ]}
];
renderVerseSet(dc36_ch1Verses, 'dc36-ch1-verses');



var dc37_ch1Verses = [
  { num: "א", words: [
    ["הִנֵּה","behold"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["לֹא","not"],
    ["טוֹב","it is expedient"],
    ["בְּעֵינַי","in me"],
    ["כִּי","for"],
    ["תְתַרְגְּמוּ","ye should translate"],
    ["עוֹד","any more"],
    ["עַד","until"],
    ["לֶכְתְּכֶם","ye should go"],
    ["אֶל","to"],
    ["אוֹהָיוֹ","the Ohio"],
    ["וְזֹאת","and this"],
    ["מִפְּנֵי","because of"],
    ["הָאוֹיֵב","the enemy"],
    ["וּלְמַעַנְכֶם׃","and for your sakes"],
    ["׃",""]
  ]},
  { num: "ב", words: [
    ["וְעוֹד","and again"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["לֹא","not"],
    ["תֵלְכוּ","ye shall go"],
    ["עַד","until"],
    ["אֲשֶׁר",""],
    ["דְּרַשְׁתֶּם","ye have preached"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["בַּמְּקוֹמוֹת","in parts"],
    ["הָהֵם","those"],
    ["וְחִזַּקְתֶּם","and have strengthened up"],
    ["אֶת",""],
    ["הָעֵדָה","the church"],
    ["בְּכׇל","whithersoever"],
    ["מָקוֹם",""],
    ["אֲשֶׁר","it"],
    ["נִמְצֵאת","is found"],
    ["וּבְיֹתֶר","and more especially"],
    ["כִּי","in Colesville, for"],
    ["הִנֵּה","behold"],
    ["מִתְפַּלְּלִים","they pray"],
    ["הֵם",""],
    ["אֵלַי","unto me"],
    ["בֶּאֱמוּנָה","in faith"],
    ["רַבָּה׃","much"],
    ["׃",""]
  ]},
  { num: "ג", words: [
    ["וְעוֹד","and again"],
    ["מִצְוָה","a commandment"],
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לָעֵדָה","unto the church"],
    ["טוֹב","it is expedient"],
    ["בְּעֵינַי","in me"],
    ["כִּי","that"],
    ["יֵאָסְפוּ","they should assemble"],
    ["יַחְדָּו","together"],
    ["בְּאוֹהָיוֹ","at the Ohio"],
    ["לִקְרַאת","against"],
    ["הָעֵת","the time"],
    ["אֲשֶׁר","that"],
    ["יָשׁוּב","shall return"],
    ["עַבְדִּי","my servant"],
    ["אוֹלִיבֶר","Oliver"],
    ["קַאוּדְּרִי","Cowdery"],
    ["אֲלֵיהֶם׃","unto them"],
    ["׃",""]
  ]},
  { num: "ד", words: [
    ["הִנֵּה","behold"],
    ["זֹאת","here is"],
    ["חׇכְמָה","wisdom"],
    ["וְיִבְחַר","and let choose"],
    ["כׇּל","every"],
    ["אִישׁ","man"],
    ["לְעַצְמוֹ","for himself"],
    ["עַד","until"],
    ["בּוֹאִי","I come"],
    ["כֵּן","even so"],
    ["יְהִי",""],
    ["אָמֵן׃","Amen"],
    ["׃",""]
  ]}
];
renderVerseSet(dc37_ch1Verses, 'dc37-ch1-verses');



var dc38_ch1Verses = [
  { num: "א", words: [
    ["כֹּה","thus"],
    ["אָמַר","saith"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהֵיכֶם","your God"],
    ["יֵשׁוּעַ","even Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["אֶהְיֶה","the I AM"],
    ["הַגָּדוֹל","Great"],
    ["הָרִאשׁוֹן","Alpha"],
    ["וְהָאַחֲרוֹן","and Omega"],
    ["הָרֵאשִׁית","the beginning"],
    ["וְהַתַּכְלִית","and the end"],
    ["הוּא","the same"],
    ["אֲשֶׁר","which"],
    ["הִבִּיט","looked"],
    ["עַל","upon"],
    ["מֶרְחֲבֵי","the wide expanse of"],
    ["הַנֶּצַח","eternity"],
    ["וְעַל","and"],
    ["כׇּל","all"],
    ["צִבְאוֹת","the hosts of"],
    ["הַשְּׂרָפִים","the seraphim"],
    ["בַּשָּׁמַיִם","of heaven"],
    ["בְּטֶרֶם","before"],
    ["נִבְרָא","was made"],
    ["הָעוֹלָם׃","the world"],
    ["׃",""]
  ]},
  { num: "ב", words: [
    ["הוּא","the same"],
    ["הַיּוֹדֵעַ","which knoweth"],
    ["כׇּל","all"],
    ["דָּבָר","things"],
    ["כִּי","for"],
    ["כׇל","all"],
    ["דָּבָר","things"],
    ["נֹכַח","are present"],
    ["לְפָנַי׃","before mine eyes"],
    ["׃",""]
  ]},
  { num: "ג", words: [
    ["אֲנִי","I am"],
    ["הוּא","the same"],
    ["אֲשֶׁר","which"],
    ["דִּבַּרְתִּי","spake"],
    ["וַיִּהְיֶה","and was made"],
    ["הָעוֹלָם","the world"],
    ["וְכׇל","and all"],
    ["דָּבָר","things"],
    ["בִּי","by me"],
    ["בָא׃","came"],
    ["׃",""]
  ]},
  { num: "ד", words: [
    ["אֲנִי","I am"],
    ["הוּא","the same"],
    ["אֲשֶׁר","which"],
    ["לָקַחְתִּי","have taken"],
    ["אֶת־צִיּוֹן","the Zion of"],
    ["חֲנוֹךְ","Enoch"],
    ["אֶל","into"],
    ["חֵיקִי","mine own bosom"],
    ["וְאָמֵן","and verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["כׇּל","even as many as"],
    ["הַמַּאֲמִינִים","have believed"],
    ["בִּשְׁמִי","in my name"],
    ["כִּי","for"],
    ["אֲנִי","I am"],
    ["הַמָּשִׁיחַ","Christ"],
    ["וּבִשְׁמִי","and in my own name"],
    ["עַצְמִי",""],
    ["בִּזְכוּת","by the virtue of"],
    ["הַדָּם","the blood"],
    ["אֲשֶׁר","which"],
    ["שָׁפַכְתִּי","I have spilt"],
    ["לִפְנֵי","before"],
    ["הָאָב","the Father"],
    ["בַּעֲדָם׃","have I pleaded for them"],
    ["׃",""]
  ]},
  { num: "ה", words: [
    ["אַךְ","but"],
    ["הִנֵּה","behold"],
    ["שְׁאָר","the residue of"],
    ["הָרְשָׁעִים","the wicked"],
    ["שָׁמַרְתִּי","have I kept"],
    ["בְּכַבְלֵי","in chains of"],
    ["חֹשֶׁךְ","darkness"],
    ["עַד","until"],
    ["מִשְׁפַּט","the judgment of"],
    ["הַיּוֹם","the day"],
    ["הַגָּדוֹל","great"],
    ["אֲשֶׁר","which"],
    ["יָבוֹא","shall come"],
    ["בְּקֵץ","at the end of"],
    ["הָאָרֶץ׃","the earth"],
    ["׃",""]
  ]},
  { num: "ו", words: [
    ["וְכֵן","and even so"],
    ["אֶעֱשֶׂה","will I cause"],
    ["לִשְׁמֹר","to be kept"],
    ["אֶת־הָרְשָׁעִים","the wicked"],
    ["אֲשֶׁר","that"],
    ["לֹא","not"],
    ["יִשְׁמְעוּ","will hear"],
    ["קוֹלִי","my voice"],
    ["כִּי","but"],
    ["אִם",""],
    ["יַקְשׁוּ","harden"],
    ["לִבָּם","their hearts"],
    ["וְהוֹי","and wo"],
    ["הוֹי","wo"],
    ["הוֹי","wo"],
    ["גְּזַר","is their"],
    ["דִּינָם׃","doom"],
    ["׃",""]
  ]},
  { num: "ז", words: [
    ["אַךְ","but"],
    ["הִנֵּה","behold"],
    ["אָמֵן","verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["עֵינַי","that mine eyes"],
    ["עֲלֵיכֶם","are upon you"],
    ["אֲנִי","I am"],
    ["בְּקִרְבְּכֶם","in your midst"],
    ["וְלֹא","and not"],
    ["תוּכְלוּ","ye cannot"],
    ["לִרְאוֹתִי׃","see me"],
    ["׃",""]
  ]},
  { num: "ח", words: [
    ["אַךְ","but"],
    ["קָרוֹב","soon cometh"],
    ["הַיּוֹם","the day"],
    ["אֲשֶׁר","that"],
    ["תִּרְאוּנִי","ye shall see me"],
    ["וְתֵדְעוּ","and know"],
    ["כִּי","that"],
    ["אֲנִי","I"],
    ["הוּא","am"],
    ["כִּי","for"],
    ["מָסָךְ","the veil of"],
    ["הַחֹשֶׁךְ","darkness"],
    ["בִּמְהֵרָה","shall soon"],
    ["יִקָּרַע","be rent"],
    ["וַאֲשֶׁר","and he that"],
    ["לֹא","is not"],
    ["יִטָּהֵר","purified"],
    ["לֹא","not"],
    ["יַעֲמֹד","shall abide"],
    ["בַּיּוֹם","the day"],
    ["הַהוּא׃",""],
    ["׃",""]
  ]},
  { num: "ט", words: [
    ["לָכֵן","wherefore"],
    ["אִזְרוּ","gird up"],
    ["מׇתְנֵיכֶם","your loins"],
    ["וְהָכֹנּוּ","and be prepared"],
    ["הִנֵּה","behold"],
    ["הַמַּמְלָכָה","the kingdom"],
    ["לָכֶם","is yours"],
    ["הִיא",""],
    ["וְהָאוֹיֵב","and the enemy"],
    ["לֹא","not"],
    ["יִגְבַּר׃","shall overcome"],
    ["׃",""]
  ]},
  { num: "י", words: [
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["טְהוֹרִים","ye are clean"],
    ["אַתֶּם",""],
    ["אַךְ","but"],
    ["לֹא","not"],
    ["כֻלְּכֶם","all"],
    ["וְאֵין","and there is none"],
    ["אַחֵר","else"],
    ["אֲשֶׁר","with whom"],
    ["חָפַצְתִּי","I am well pleased"],
    ["בוֹ׃",""],
    ["׃",""]
  ]},
  { num: "יא", words: [
    ["כִּי","for"],
    ["כׇל","all"],
    ["בָּשָׂר","flesh"],
    ["הֻשְׁחַת","is corrupted"],
    ["לְפָנַי","before me"],
    ["וְכֹחוֹת","and the powers of"],
    ["הַחֹשֶׁךְ","darkness"],
    ["שׁוֹלְטִים","prevail"],
    ["עַל","upon"],
    ["הָאָרֶץ","the earth"],
    ["בֵּין","among"],
    ["בְּנֵי","the children of"],
    ["הָאָדָם","men"],
    ["לִפְנֵי","in the presence of"],
    ["כׇּל","all"],
    ["צִבְאוֹת","the hosts of"],
    ["הַשָּׁמָיִם׃","heaven"],
    ["׃",""]
  ]},
  { num: "יב", words: [
    ["וְזֹאת","which causeth"],
    ["לִדְמָמָה","silence"],
    ["לִמְלֹךְ","to reign"],
    ["וְכׇל","and all"],
    ["הַנֶּצַח","eternity"],
    ["כּוֹאֵב","is pained"],
    ["וְהַמַּלְאָכִים","and the angels"],
    ["מְחַכִּים","are waiting"],
    ["לַמִּצְוָה","the command"],
    ["הַגְּדוֹלָה","great"],
    ["לִקְצֹר","to reap down"],
    ["אֶת־הָאָרֶץ","the earth"],
    ["לֶאֱסֹף","to gather"],
    ["אֶת",""],
    ["הַזֻּנִּים","the tares"],
    ["לְמַעַן","that"],
    ["יִשָּׂרְפוּ","they may be burned"],
    ["וְהִנֵּה","and behold"],
    ["הָאוֹיֵב׃","the enemy is combined"],
    ["׃",""]
  ]},
  { num: "יג", words: [
    ["וְעַתָּה","and now"],
    ["אֲנִי","I"],
    ["מַרְאֶה","show"],
    ["לָכֶם","unto you"],
    ["סוֹד","a mystery"],
    ["דָּבָר","a thing"],
    ["הַנַּעֲשֶׂה","which is had"],
    ["בַּחֲדָרִים","in chambers"],
    ["הַסְּתָרִים","secret"],
    ["לְהָבִיא","to bring to pass"],
    ["אֶת־הַשְׁמָדַתְכֶם","your destruction"],
    ["בִּמְרוּצַת","in process of"],
    ["הַיָּמִים","time"],
    ["וְלֹא","and not"],
    ["יְדַעְתֶּם׃","knew it not"],
    ["׃",""]
  ]},
  { num: "יד", words: [
    ["אַךְ","but"],
    ["עַתָּה","now"],
    ["אֲנִי","I"],
    ["מַגִּיד","tell it"],
    ["לָכֶם","unto you"],
    ["וּבְרוּכִים","and ye are blessed"],
    ["אַתֶּם",""],
    ["לֹא","not"],
    ["בִגְלַל","because of"],
    ["עֲוֹנְכֶם","your iniquity"],
    ["וְלֹא","and not"],
    ["בִגְלַל","because of"],
    ["לִבְּכֶם","your hearts of"],
    ["חֲסַר",""],
    ["הָאֱמוּנָה","unbelief"],
    ["כִּי","for"],
    ["אָכֵן","yea"],
    ["מִקְצָתְכֶם","some of you"],
    ["אֲשֵׁמִים","are guilty"],
    ["לְפָנַי","before me"],
    ["אַךְ","but"],
    ["אֲרַחֵם","I will be merciful unto"],
    ["עַל","concerning"],
    ["חֻלְשַׁתְכֶם׃","your weakness"],
    ["׃",""]
  ]},
  { num: "טו", words: [
    ["לָכֵן","therefore"],
    ["הֱיוּ","be ye"],
    ["חֲזָקִים","strong"],
    ["מֵעַתָּה","from henceforth"],
    ["אַל","not"],
    ["תִּירָאוּ","fear"],
    ["כִּי","for"],
    ["הַמַּמְלָכָה","the kingdom"],
    ["לָכֶם","is yours"],
    ["הִיא׃",""],
    ["׃",""]
  ]},
  { num: "טז", words: [
    ["וְלִישׁוּעַתְכֶם","and for your salvation"],
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לָכֶם","unto you"],
    ["מִצְוָה","a commandment"],
    ["כִּי","for"],
    ["שָׁמַעְתִּי","I have heard"],
    ["תְּפִלּוֹתֵיכֶם","your prayers"],
    ["וְהָעֲנִיִּים","and the poor"],
    ["הִתְאוֹנְנוּ","have complained"],
    ["לְפָנַי","have complained before me"],
    ["וְאֶת־הָעֲשִׁירִים","and the rich"],
    ["עָשִׂיתִי","have I made"],
    ["וְכׇל","and all"],
    ["בָּשָׂר","flesh"],
    ["שֶׁלִּי","is mine"],
    ["וְאֵינֶנִּי","and I am no"],
    ["מַכִּיר","respecter of"],
    ["פָּנִים׃","persons"],
    ["׃",""]
  ]},
  { num: "יז", words: [
    ["וְעָשִׂיתִי","and I have made"],
    ["אֶת־הָאָרֶץ","the earth"],
    ["עֲשִׁירָה","rich"],
    ["וְהִנֵּה","and behold"],
    ["הֲדֹם","footstool"],
    ["רַגְלַי","it is my"],
    ["הִיא",""],
    ["לָכֵן","wherefore"],
    ["עוֹד","again"],
    ["אֶעֱמֹד","I will stand"],
    ["עָלֶיהָ׃","upon it"],
    ["׃",""]
  ]},
  { num: "יח", words: [
    ["וַאֲנִי","and I"],
    ["וְרוֹצֶה","hold forth and deign"],
    ["לָתֵת","to give"],
    ["לָכֶם","unto you"],
    ["עֹשֶׁר","riches"],
    ["גָּדוֹל","greater"],
    ["יוֹתֵר",""],
    ["אֶרֶץ","a land of"],
    ["הַבְטָחָה","promise"],
    ["אֶרֶץ","a land"],
    ["זָבַת","flowing with"],
    ["חָלָב","milk"],
    ["וּדְבַשׁ","and honey"],
    ["אֲשֶׁר","upon which"],
    ["לֹא","not"],
    ["תִהְיֶה","there shall be"],
    ["בָּהּ",""],
    ["קְלָלָה","curse"],
    ["בְּבוֹא","when cometh"],
    ["יְהוָה׃","the Lord"],
    ["׃",""]
  ]},
  { num: "יט", words: [
    ["וַאֲנִי","and I"],
    ["אֶתְּנֶנָּה","will give it"],
    ["לָכֶם","unto you"],
    ["לְאֶרֶץ","for the land of"],
    ["נַחֲלַתְכֶם","your inheritance"],
    ["אִם","if"],
    ["תְּבַקְשׁוּהָ","ye seek it"],
    ["בְּכׇל","you seek it with all"],
    ["לְבַבְכֶם׃","your hearts"],
    ["׃",""]
  ]},
  { num: "כ", words: [
    ["וְזֹאת","and this"],
    ["תִּהְיֶה","shall be"],
    ["בְרִיתִי","my covenant"],
    ["אִתְּכֶם","with you"],
    ["תְּקַבְּלוּהָ","ye shall have it"],
    ["לְאֶרֶץ","for the land of"],
    ["נַחֲלַתְכֶם","your inheritance"],
    ["וּלְנַחֲלַת","and for the inheritance of"],
    ["בְּנֵיכֶם","your children"],
    ["לְעוֹלָם","forever"],
    ["כׇּל","while"],
    ["עוֹד",""],
    ["הָאָרֶץ","the earth"],
    ["עֹמֶדֶת","shall stand"],
    ["עוֹד","and ye shall possess it again"],
    ["בַּנֶּצַח","in eternity"],
    ["לֹא","no more"],
    ["לַעֲבֹר","to pass"],
    ["עוֹד׃","away"],
    ["׃",""]
  ]},
  { num: "כא", words: [
    ["אַךְ","but"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["כִּי","that"],
    ["בַזְּמַן","in time"],
    ["לֹא","not"],
    ["יִהְיֶה","ye shall have"],
    ["לָכֶם",""],
    ["מֶלֶךְ","king"],
    ["וְלֹא","nor"],
    ["מוֹשֵׁל","ruler"],
    ["כִּי","for"],
    ["אֲנִי","I"],
    ["אֶהְיֶה","will be"],
    ["מַלְכְּכֶם","your king"],
    ["וְאֶשְׁמֹר","and watch"],
    ["עֲלֵיכֶם׃","over you"],
    ["׃",""]
  ]},
  { num: "כב", words: [
    ["לָכֵן","wherefore"],
    ["שִׁמְעוּ","hear"],
    ["קוֹלִי","my voice"],
    ["וְלֵכוּ","and follow"],
    ["אַחֲרַי","me"],
    ["וְתִהְיוּ","and you shall be"],
    ["עַם","a people"],
    ["חׇפְשִׁי","free"],
    ["וְלֹא","and not"],
    ["יִהְיֶה","ye shall have"],
    ["לָכֶם",""],
    ["חֻקִּים","laws"],
    ["זוּלָתִי","but"],
    ["חֻקַּי","my laws"],
    ["בְּבוֹאִי","when I come"],
    ["כִּי","for"],
    ["אֲנִי","I am"],
    ["מְחֹקֵקְכֶם","your lawgiver"],
    ["וּמִי","and what"],
    ["יַעֲצֹר","can stay"],
    ["יָדִי׃","my hand"],
    ["׃",""]
  ]},
  { num: "כג", words: [
    ["אַךְ","but"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["לַמְּדוּ","teach"],
    ["אִישׁ","one"],
    ["אֶת","and"],
    ["רֵעֵהוּ","another"],
    ["כַּמִּשְׂרָה","according to the office"],
    ["אֲשֶׁר","wherewith"],
    ["מִנִּיתִי","I have appointed"],
    ["אֶתְכֶם׃","you"],
    ["׃",""]
  ]},
  { num: "כד", words: [
    ["וְיַחְשֹׁב","and let esteem"],
    ["כׇּל","every"],
    ["אִישׁ","man"],
    ["אֶת",""],
    ["אָחִיו","his brother"],
    ["כְּנַפְשׁוֹ","as himself"],
    ["וְיַעֲשׂוּ","and practice"],
    ["צֶדֶק","virtue"],
    ["וּקְדֻשָּׁה","and holiness"],
    ["לְפָנָי׃","before me"],
    ["׃",""]
  ]},
  { num: "כה", words: [
    ["וְעוֹד","and again"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["יַחְשֹׁב","let esteem"],
    ["כׇּל","every"],
    ["אִישׁ","man"],
    ["אֶת",""],
    ["אָחִיו","his brother"],
    ["כְּנַפְשׁוֹ׃","as himself"],
    ["׃",""]
  ]},
  { num: "כו", words: [
    ["כִּי","for"],
    ["מִי","what"],
    ["בָכֶם","man among you"],
    ["אֲשֶׁר","having"],
    ["לוֹ",""],
    ["שְׁנֵים","twelve"],
    ["עָשָׂר",""],
    ["בָּנִים","sons"],
    ["וְלֹא","and is no"],
    ["מַכִּיר","respecter"],
    ["פָּנִים","of persons"],
    ["בֵּינֵיהֶם","of them"],
    ["וְהֵם","and they"],
    ["עֹבְדִים","serve"],
    ["אֹתוֹ","him"],
    ["בְּמִשְׁמַעַת","obediently"],
    ["וְאֹמֵר","and he saith"],
    ["לָאֶחָד","unto the one"],
    ["הִלָּבֵשׁ","be thou clothed"],
    ["בְּגָדִים","in robes"],
    ["נֶאֱדָרִים",""],
    ["וּשְׁבָה","and sit"],
    ["הֲלֹם","thou here"],
    ["וְלָאַחֵר","and to the other"],
    ["הִלָּבֵשׁ","be thou clothed"],
    ["סְחָבוֹת","in rags"],
    ["וּשְׁבָה","and sit"],
    ["שָׁם","thou there"],
    ["וּמַבִּיט","and looketh"],
    ["עַל","upon"],
    ["בָּנָיו","his sons"],
    ["וְאֹמֵר","and saith"],
    ["צַדִּיק","I am just"],
    ["אָנֹכִי׃",""],
    ["׃",""]
  ]},
  { num: "כז", words: [
    ["הִנֵּה","behold"],
    ["זֹאת","this"],
    ["נָתַתִּי","I have given"],
    ["לָכֶם","unto you"],
    ["לְמָשָׁל","as a parable"],
    ["וְהִיא","and it is"],
    ["כָּמוֹנִי","even as I am"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["הֱיוּ","be ye"],
    ["אֶחָד","one"],
    ["וְאִם","and if"],
    ["אֵינְכֶם","ye are not"],
    ["אֶחָד","one"],
    ["אֵינְכֶם","ye are not"],
    ["שֶׁלִּי׃","mine"],
    ["׃",""]
  ]},
  { num: "כח", words: [
    ["וְעוֹד","and again"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["הָאוֹיֵב","that the enemy"],
    ["בַּחֲדָרִים","in the chambers"],
    ["הַסְּתָרִים","secret"],
    ["מְבַקֵּשׁ","seeketh"],
    ["נַפְשׁוֹתֵיכֶם׃","your lives"],
    ["׃",""]
  ]},
  { num: "כט", words: [
    ["שֹׁמְעִים","ye hear"],
    ["אַתֶּם",""],
    ["עַל","of"],
    ["מִלְחָמוֹת","wars"],
    ["בַּאֲרָצוֹת","in countries"],
    ["רְחוֹקוֹת","far"],
    ["וְאֹמְרִים","and you say"],
    ["אַתֶּם",""],
    ["בִּמְהֵרָה","soon"],
    ["תִהְיֶינָה","there will be"],
    ["מִלְחָמוֹת","wars"],
    ["גְּדוֹלוֹת","great"],
    ["בַּאֲרָצוֹת","in countries"],
    ["רְחוֹקוֹת","far"],
    ["אַךְ","but"],
    ["לֹא","not"],
    ["יְדַעְתֶּם","ye know"],
    ["לִבּוֹת","the hearts of"],
    ["הָאֲנָשִׁים","men"],
    ["בְּאַרְצְכֶם׃","in your own land"],
    ["׃",""]
  ]},
  { num: "ל", words: [
    ["אֲנִי","I"],
    ["מַגִּיד","tell"],
    ["לָכֶם","you"],
    ["אֶת",""],
    ["הַדְּבָרִים","things"],
    ["הָאֵלֶּה","these"],
    ["בִּגְלַל","because of"],
    ["תְּפִלּוֹתֵיכֶם","your prayers"],
    ["לָכֵן","wherefore"],
    ["אִצְרוּ","treasure up"],
    ["חׇכְמָה","wisdom"],
    ["בִּלְבַבְכֶם","in your bosoms"],
    ["פֶּן","lest"],
    ["רִשְׁעַת","the wickedness of"],
    ["הָאֲנָשִׁים","men"],
    ["תְּגַלֶּה","reveal"],
    ["לָכֶם","unto you"],
    ["אֶת",""],
    ["הַדְּבָרִים","things"],
    ["הָאֵלֶּה","these"],
    ["בְּרִשְׁעָתָם","by their wickedness"],
    ["בְּאֹפֶן","in a manner"],
    ["אֲשֶׁר","which"],
    ["יְדַבֵּר","shall speak"],
    ["בְּאׇזְנֵיכֶם","in your ears"],
    ["בְּקוֹל","with a voice"],
    ["חָזָק","louder"],
    ["מִזֶּה","than that"],
    ["אֲשֶׁר","which"],
    ["הָאָרֶץ","the earth"],
    ["אַךְ","but"],
    ["אִם","if"],
    ["נְכוֹנִים","prepared"],
    ["אַתֶּם","ye are"],
    ["לֹא","not"],
    ["תִּירָאוּ׃","ye shall fear"],
    ["׃",""]
  ]},
  { num: "לא", words: [
    ["וּלְמַעַן","and that"],
    ["תִּמָּלְטוּ","ye might escape"],
    ["מִכֹּחַ","the power of"],
    ["הָאוֹיֵב","the enemy"],
    ["וְתֵאָסְפוּ","and be gathered"],
    ["אֵלַי","me"],
    ["עַם","a people"],
    ["צַדִּיק","righteous"],
    ["בְּלֹא","without"],
    ["מוּם","spot"],
    ["וְתָמִים׃","and blameless"],
    ["׃",""]
  ]},
  { num: "לב", words: [
    ["לָכֵן","therefore"],
    ["בִּגְלַל","because of"],
    ["זֹאת","this cause"],
    ["נָתַתִּי","I gave"],
    ["לָכֶם","unto you"],
    ["הַמִּצְוָה","the commandment"],
    ["לָלֶכֶת","that ye should go"],
    ["אֶל","to"],
    ["אוֹהָיוֹ","the Ohio"],
    ["וְשָׁם","and there"],
    ["אֶתֵּן","I will give"],
    ["לָכֶם","unto you"],
    ["תּוֹרָתִי","my law"],
    ["וְשָׁם","and there"],
    ["תְּלֻבְּשׁוּ","ye shall be endowed"],
    ["כֹחַ","power"],
    ["מִמָּרוֹם׃","from on high"],
    ["׃",""]
  ]},
  { num: "לג", words: [
    ["וּמִשָּׁם","and from thence"],
    ["כׇּל","whosoever"],
    ["אֲשֶׁר",""],
    ["אֶחְפֹּץ","I will"],
    ["יֵצֵא","shall go forth"],
    ["בֵּין","among"],
    ["כׇּל","all"],
    ["הַגּוֹיִם","nations"],
    ["וְיֵאָמֵר","and it shall be told"],
    ["לָהֶם","them"],
    ["מַה","what"],
    ["יַּעֲשׂוּ","they shall do"],
    ["כִּי","for"],
    ["מְלָאכָה","a work"],
    ["גְדוֹלָה","great"],
    ["צְפוּנָה","I have laid up in store"],
    ["לִי",""],
    ["יִשְׂרָאֵל","for Israel"],
    ["יִוָּשַׁע","shall be saved"],
    ["אֶל","and I will lead them"],
    ["אֲשֶׁר","whithersoever"],
    ["אֶחְפֹּץ","I will"],
    ["וְאֵין","and no"],
    ["כֹּחַ","power"],
    ["אֲשֶׁר","shall"],
    ["יַעֲצֹר","stay"],
    ["יָדִי׃","my hand"],
    ["׃",""]
  ]},
  { num: "לד", words: [
    ["וְעַתָּה","and now"],
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לָעֵדָה","unto the church"],
    ["בַּמְּקוֹמוֹת","in parts"],
    ["הָאֵלֶּה","these"],
    ["מִצְוָה","a commandment"],
    ["כִּי","that"],
    ["אֲנָשִׁים","certain men"],
    ["יְמֻנּוּ","shall be appointed"],
    ["מִקִּרְבָּם","among them"],
    ["וְיִמָּנוּ","and they shall be appointed"],
    ["בְקוֹל","by the voice"],
    ["הָעֵדָה׃","of the church"],
    ["׃",""]
  ]},
  { num: "לה", words: [
    ["וְיִפְקְדוּ","and they shall look"],
    ["עַל","to"],
    ["הָעֲנִיִּים","the poor"],
    ["וְהַנְּצָרְכִים","and the needy"],
    ["וְיַעַזְרוּ","and administer to their relief"],
    ["לָהֶם",""],
    ["לְמַעַן","that"],
    ["לֹא","not"],
    ["יִסְבְּלוּ","they shall suffer"],
    ["וְיִשְׁלָחוּם","and send them forth"],
    ["אֶל","to"],
    ["הַמָּקוֹם","the place"],
    ["אֲשֶׁר","which"],
    ["צִוִּיתִים׃","I have commanded them"],
    ["׃",""]
  ]},
  { num: "לו", words: [
    ["וְזֹאת","and this"],
    ["תִּהְיֶה","shall be"],
    ["מְלַאכְתָּם","their work"],
    ["לְנַהֵל","to govern"],
    ["עִנְיְנֵי","the affairs of"],
    ["רְכוּשׁ","the property of"],
    ["הָעֵדָה","church"],
    ["הַזֹּאת׃","this"],
    ["׃",""]
  ]},
  { num: "לז", words: [
    ["וְהָאֲנָשִׁים","and those"],
    ["אֲשֶׁר","that"],
    ["לָהֶם","have"],
    ["אֲדָמוֹת","farms"],
    ["אֲשֶׁר","that"],
    ["לֹא","not"],
    ["יוּכְלוּ","cannot"],
    ["לְהִמָּכֵר","be sold"],
    ["יֵעָזְבוּ","let them be left"],
    ["אוֹ","or"],
    ["יֻשְׂכְּרוּ","rented"],
    ["כַּטּוֹב","as seemeth"],
    ["בְּעֵינֵיהֶם׃","them good"],
    ["׃",""]
  ]},
  { num: "לח", words: [
    ["רְאוּ","see"],
    ["כִּי","that"],
    ["כׇל","all"],
    ["דָּבָר","things"],
    ["יִשָּׁמֵר","are preserved"],
    ["אֲנָשִׁים","and when men"],
    ["בְּכֹחַ","are endowed with power"],
    ["מִמָּרוֹם","from on high"],
    ["וְיִשָּׁלְחוּ","and sent forth"],
    ["כׇּל","all"],
    ["הַדְּבָרִים","things"],
    ["הָאֵלֶּה","these"],
    ["יֵאָסְפוּ","shall be gathered"],
    ["אֶל","unto"],
    ["חֵיק","the bosom of"],
    ["הָעֵדָה׃","the church"],
    ["׃",""]
  ]},
  { num: "לט", words: [
    ["וְאִם","and if"],
    ["תְּבַקְשׁוּ","ye seek"],
    ["אֶת",""],
    ["הָעֹשֶׁר","the riches"],
    ["אֲשֶׁר","which"],
    ["רְצוֹן","it is the will of"],
    ["הָאָב","the Father"],
    ["לָתֵת","to give"],
    ["לָכֶם","unto you"],
    ["תִּהְיוּ","ye shall be"],
    ["עֲשִׁירֵי","the richest of"],
    ["כׇל","all"],
    ["הָעַמִּים","people"],
    ["כִּי","for"],
    ["יִהְיֶה","ye shall have"],
    ["לָכֶם",""],
    ["עֹשֶׁר","the riches of"],
    ["הַנֶּצַח","eternity"],
    ["וְצָרִיךְ","and it must needs be that"],
    ["כִּי",""],
    ["עֹשֶׁר","the riches of"],
    ["הָאָרֶץ","the earth"],
    ["שֶׁלִּי","are mine"],
    ["הוּא",""],
    ["לָתֵת","to give"],
    ["אַךְ","but"],
    ["הִשָּׁמְרוּ","beware"],
    ["מִגַּאֲוָה","of pride"],
    ["פֶּן","lest"],
    ["תִּהְיוּ","ye become"],
    ["כִּנְפִיִּים","as the Nephites"],
    ["הַקַּדְמוֹנִים׃","of old"],
    ["׃",""]
  ]},
  { num: "מ", words: [
    ["וְעוֹד","and again"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לָכֶם","unto you"],
    ["מִצְוָה","a commandment"],
    ["כׇּל","that every"],
    ["אִישׁ","man"],
    ["זָקֵן","both elder"],
    ["כֹּהֵן","priest"],
    ["מוֹרֶה","teacher"],
    ["וְגַם","and also"],
    ["חָבֵר","member"],
    ["יֵלֵךְ","go to"],
    ["בְּכׇל","with all"],
    ["כֹּחוֹ","his might"],
    ["בַּעֲמַל","with the labor of"],
    ["כַּפָּיו","his hands"],
    ["לְהָכִין","to prepare"],
    ["וּלְמַלֵּא","and accomplish"],
    ["אֶת",""],
    ["הַדְּבָרִים","the things"],
    ["אֲשֶׁר","which"],
    ["צִוִּיתִי׃","I have commanded"],
    ["׃",""]
  ]},
  { num: "מא", words: [
    ["וּתְהִי","and let be"],
    ["דְרָשָׁתְכֶם","your preaching"],
    ["קוֹל","the voice of"],
    ["אַזְהָרָה","warning"],
    ["אִישׁ","every man"],
    ["לְרֵעֵהוּ","to his neighbor"],
    ["בְּרֹךְ","in mildness"],
    ["וּבַעֲנָוָה׃","and in meekness"],
    ["׃",""]
  ]},
  { num: "מב", words: [
    ["וּצְאוּ","and go ye out"],
    ["מִקֶּרֶב","from among"],
    ["הָרְשָׁעִים","the wicked"],
    ["הִנָּצְלוּ","save yourselves"],
    ["הִטְהָרוּ","be ye clean"],
    ["נֹשְׂאֵי","that bear"],
    ["כְּלֵי","the vessels of"],
    ["יְהוָה","the Lord"],
    ["כֵּן","even so"],
    ["יְהִי",""],
    ["אָמֵן׃","Amen"],
    ["׃",""]
  ]}
];
renderVerseSet(dc38_ch1Verses, 'dc38-ch1-verses');



var dc39_ch1Verses = [
  { num: "א", words: [
    ["הַאֲזִינוּ","hearken"],
    ["וְשִׁמְעוּ","and listen"],
    ["לְקוֹל","to the voice of"],
    ["הַהֹוֶה","him who is"],
    ["מֵעוֹלָם","from all eternity"],
    ["וְעַד","to"],
    ["עוֹלָם","all eternity"],
    ["אֶהְיֶה","the I AM"],
    ["הַגָּדוֹל","Great"],
    ["יֵשׁוּעַ","even Jesus"],
    ["הַמָּשִׁיחַ׃","Christ"],
    ["׃",""]
  ]},
  { num: "ב", words: [
    ["אוֹר","the light"],
    ["הָעוֹלָם","of the world"],
    ["וְחַיָּיו","and its life"],
    ["אוֹר","a light"],
    ["הַזֹּרֵחַ","which shineth"],
    ["בַּחֹשֶׁךְ","in darkness"],
    ["וְהַחֹשֶׁךְ","and the darkness"],
    ["לֹא","not"],
    ["הִשִּׂיגוֹ׃","comprehendeth it"],
    ["׃",""]
  ]},
  { num: "ג", words: [
    ["הוּא","the same"],
    ["אֲשֶׁר","which"],
    ["בָּא","came"],
    ["בְּמֶחֱצִית","in the meridian of time"],
    ["אֶל","unto"],
    ["שְׁלִי","mine own"],
    ["וּשְׁלִי","and mine own"],
    ["לֹא","not"],
    ["קִבְּלוּנִי׃","received me"],
    ["׃",""]
  ]},
  { num: "ד", words: [
    ["אַךְ","but"],
    ["כׇּל","to as many as"],
    ["אֲשֶׁר",""],
    ["קִבְּלוּנִי","received me"],
    ["נָתַתִּי","gave I"],
    ["לָהֶם","them"],
    ["כֹּחַ","power"],
    ["לִהְיוֹת","to become"],
    ["בָּנַי","my sons"],
    ["וְכֵן","and even so"],
    ["אֶתֵּן","will I give"],
    ["לְכׇל","unto as many as"],
    ["אֲשֶׁר","will receive me"],
    ["כֹּחַ","power"],
    ["לִהְיוֹת","to become"],
    ["בָּנַי׃","my sons"],
    ["׃",""]
  ]},
  { num: "ה", words: [
    ["וְאָמֵן","and verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["הַמְקַבֵּל","he that receiveth"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["מְקַבֵּל","receiveth"],
    ["אֹתִי","me"],
    ["וַאֲשֶׁר","and he that"],
    ["לֹא","not"],
    ["יְקַבֵּל","receiveth"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["לֹא","not"],
    ["יְקַבֵּל","receiveth"],
    ["אֹתִי׃","me"],
    ["׃",""]
  ]},
  { num: "ו", words: [
    ["וְזֹאת","and this is"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["תְּשׁוּבָה","repentance"],
    ["וּטְבִילָה","and baptism"],
    ["בְּמַיִם","by water"],
    ["וְאָז","and then"],
    ["תָּבוֹא","cometh"],
    ["טְבִילַת","the baptism of"],
    ["הָאֵשׁ","fire"],
    ["וְרוּחַ","and the Holy Ghost"],
    ["הַקֹּדֶשׁ",""],
    ["הַמְּנַחֵם","even the Comforter"],
    ["הַמַּרְאֶה","which showeth"],
    ["כׇּל","all"],
    ["דָּבָר","things"],
    ["וּמְלַמֵּד","and teacheth"],
    ["דִּבְרֵי","the things of"],
    ["שָׁלוֹם","peace"],
    ["הַמַּמְלָכָה׃","of the kingdom"],
    ["׃",""]
  ]},
  { num: "ז", words: [
    ["וְעַתָּה","and now"],
    ["הִנֵּה","behold"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְךָ","unto you"],
    ["עַבְדִּי","my servant"],
    ["יַעֲקֹב","James"],
    ["הִבַּטְתִּי","I have looked"],
    ["עַל","upon"],
    ["מַעֲשֶׂיךָ","thy works"],
    ["וַאֲנִי","and I"],
    ["יוֹדֵעַ","know"],
    ["אֹתְךָ׃","thee"],
    ["׃",""]
  ]},
  { num: "ח", words: [
    ["וְאָמֵן","and verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְךָ","unto thee"],
    ["לִבְּךָ","thine heart"],
    ["יָשָׁר","is now right"],
    ["לְפָנַי","before me"],
    ["בָּעֵת","at time"],
    ["הַזֹּאת","this"],
    ["וְהִנֵּה","and behold"],
    ["בְּרָכוֹת","blessings"],
    ["גְּדוֹלוֹת","great"],
    ["עַל","I have bestowed upon"],
    ["רֹאשֶׁךָ׃","thy head"],
    ["׃",""]
  ]},
  { num: "ט", words: [
    ["אַף","nevertheless"],
    ["כִּי","for"],
    ["רָאִיתָ","thou hast seen"],
    ["יָגוֹן","sorrow"],
    ["רַב","great"],
    ["כִּי","for"],
    ["פְּעָמִים","times"],
    ["רַבּוֹת","many"],
    ["בִּגְלַל","because of"],
    ["גַּאֲוָה","pride"],
    ["וּדְאָגוֹת","and the cares of"],
    ["הָעוֹלָם׃","the world thou hast rejected me"],
    ["׃",""]
  ]},
  { num: "י", words: [
    ["אַךְ","but"],
    ["הִנֵּה","behold"],
    ["יְמֵי","the days of"],
    ["גְאֻלָּתְךָ","thy deliverance"],
    ["בָּאוּ","are come"],
    ["אִם","if"],
    ["תִּשְׁמַע","thou wilt hearken to"],
    ["קוֹלִי","my voice"],
    ["הָאֹמֵר","which saith"],
    ["לְךָ","unto thee"],
    ["קוּם","arise"],
    ["וְהִטָּבֵל","and be baptized"],
    ["וּרְחַץ","and wash away"],
    ["חַטֹּאתֶיךָ","your sins"],
    ["קוֹרֵא","calling"],
    ["בִשְׁמִי","on my name"],
    ["וּתְקַבֵּל","and you shall receive"],
    ["רוּחִי","my Spirit"],
    ["וּבְרָכָה","and a blessing"],
    ["גְדוֹלָה","so great"],
    ["אֲשֶׁר","as"],
    ["לֹא","never"],
    ["יָדַעְתָּ","you have known"],
    ["מֵעוֹלָם׃",""],
    ["׃",""]
  ]},
  { num: "יא", words: [
    ["וְאִם","and if"],
    ["תַּעֲשֶׂה","thou do"],
    ["זֹאת","this"],
    ["לִמְלָאכָה","for a work"],
    ["גְדוֹלָה","greater"],
    ["יוֹתֵר","I have prepared thee"],
    ["תִּדְרֹשׁ","thou shalt preach"],
    ["מְלֹא","the fulness of"],
    ["בְשׂוֹרָתִי","my gospel"],
    ["אֲשֶׁר","which"],
    ["שָׁלַחְתִּי","I have sent forth"],
    ["בַּיָּמִים","in days"],
    ["הָאַחֲרוֹנִים","last"],
    ["הָאֵלֶּה","these"],
    ["הַבְּרִית","the covenant"],
    ["אֲשֶׁר","which"],
    ["שָׁלַחְתִּי","I have sent forth"],
    ["לְהָשִׁיב","to recover"],
    ["אֶת־עַמִּי","my people"],
    ["אֲשֶׁר","which"],
    ["מִבֵּית","are of the house of"],
    ["יִשְׂרָאֵל׃","Israel"],
    ["׃",""]
  ]},
  { num: "יב", words: [
    ["וְהָיָה","and it shall come to pass that"],
    ["כֹחַ","power"],
    ["יָנוּחַ","shall rest"],
    ["עָלֶיךָ","upon thee"],
    ["יִהְיֶה","thou shalt have"],
    ["לְךָ",""],
    ["אֱמוּנָה","faith"],
    ["גְדוֹלָה","great"],
    ["וַאֲנִי","and I"],
    ["אֶהְיֶה","will be"],
    ["עִמְּךָ","with thee"],
    ["וְאֵלֵךְ","and go"],
    ["לְפָנֶיךָ׃","before thy face"],
    ["׃",""]
  ]},
  { num: "יג", words: [
    ["נִקְרֵאתָ","thou art called"],
    ["לַעֲבֹד","to labor"],
    ["בְּכַרְמִי","in my vineyard"],
    ["וְלִבְנוֹת","and to build up"],
    ["עֲדָתִי","my church"],
    ["וּלְהוֹצִיא","and to bring forth"],
    ["אֶת־צִיּוֹן","Zion"],
    ["לְמַעַן","that"],
    ["תָּגֵל","it may rejoice"],
    ["עַל","upon"],
    ["הֶהָרִים","the hills"],
    ["וּפָרְחָה׃","and flourish"],
    ["׃",""]
  ]},
  { num: "יד", words: [
    ["הִנֵּה","behold"],
    ["אָמֵן","verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְךָ","unto thee"],
    ["לֹא","not"],
    ["נִקְרֵאתָ","thou art called"],
    ["לָלֶכֶת","to go"],
    ["אֶל","into"],
    ["אַרְצוֹת","the countries"],
    ["הַמִּזְרָח","eastern"],
    ["כִּי","but"],
    ["אִם",""],
    ["נִקְרֵאתָ","thou art called"],
    ["לָלֶכֶת","to go"],
    ["אֶל","to"],
    ["אוֹהָיוֹ׃","the Ohio"],
    ["׃",""]
  ]},
  { num: "טו", words: [
    ["וּכְפִי","and inasmuch"],
    ["אֲשֶׁר","as"],
    ["יֵאָסְפוּ","shall assemble themselves"],
    ["עַמִּי","my people"],
    ["בְּאוֹהָיוֹ","at the Ohio"],
    ["בְּרָכָה","a blessing"],
    ["צְפוּנָה","I have kept in store"],
    ["לִי",""],
    ["אֲשֶׁר","such as"],
    ["אֵינָהּ","is not"],
    ["נוֹדַעַת","known"],
    ["בֵּין","among"],
    ["בְּנֵי","the children of"],
    ["הָאָדָם","men"],
    ["וְתִשָּׁפֵךְ","and it shall be poured forth"],
    ["עַל","upon"],
    ["רָאשֵׁיהֶם","their heads"],
    ["וּמִשָּׁם","and from thence"],
    ["יֵצְאוּ","shall go forth"],
    ["אֲנָשִׁים","men"],
    ["אֶל","into"],
    ["כׇּל","all"],
    ["הַגּוֹיִם׃","nations"],
    ["׃",""]
  ]},
  { num: "טז", words: [
    ["הִנֵּה","behold"],
    ["אָמֵן","verily"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["הָעָם","that the people"],
    ["בְּאוֹהָיוֹ","in Ohio"],
    ["קֹרְאִים","call"],
    ["אֵלַי","upon me"],
    ["בֶּאֱמוּנָה","in faith"],
    ["רַבָּה","much"],
    ["חוֹשְׁבִים","thinking"],
    ["כִּי","that"],
    ["אֶעֱצֹר","I will stay"],
    ["יָדִי","my hand"],
    ["מִמִּשְׁפָּט","in judgment"],
    ["עַל","upon"],
    ["הַגּוֹיִם","the nations"],
    ["אַךְ","but"],
    ["לֹא","not"],
    ["אוּכַל","I cannot"],
    ["לְהַכְחִישׁ","deny"],
    ["דְּבָרִי׃","my word"],
    ["׃",""]
  ]},
  { num: "יז", words: [
    ["לָכֵן","wherefore"],
    ["עֲמְלוּ","lay to"],
    ["בְּכׇל","with all"],
    ["כֹּחֲכֶם","your might"],
    ["וְקִרְאוּ","and call"],
    ["פֹעֲלִים","laborers"],
    ["נֶאֱמָנִים","faithful"],
    ["אֶל","into"],
    ["כַּרְמִי","my vineyard"],
    ["לְמַעַן","that"],
    ["יִזָּמֵר","it may be pruned"],
    ["בַּפַּעַם","for the time"],
    ["הָאַחֲרוֹנָה׃","last"],
    ["׃",""]
  ]},
  { num: "יח", words: [
    ["וּכְפִי","and inasmuch"],
    ["אֲשֶׁר","as"],
    ["יָשׁוּבוּ","they do repent"],
    ["וִיקַבְּלוּ","and receive"],
    ["מְלֹא","the fulness of"],
    ["בְשׂוֹרָתִי","my gospel"],
    ["וְיִתְקַדְּשׁוּ","and become sanctified"],
    ["אֶעֱצֹר","I will stay"],
    ["יָדִי","mine hand"],
    ["מִמִּשְׁפָּט׃","in judgment"],
    ["׃",""]
  ]},
  { num: "יט", words: [
    ["לָכֵן","wherefore"],
    ["צֵא","go forth"],
    ["קְרָא","crying"],
    ["בְקוֹל","with a voice"],
    ["גָּדוֹל","loud"],
    ["לֵאמֹר","saying"],
    ["קָרְבָה","is at hand"],
    ["מַלְכוּת","the kingdom of"],
    ["הַשָּׁמָיִם","heaven"],
    ["קְרָא","crying"],
    ["הוֹשַׁעְנָא","hosanna"],
    ["בָּרוּךְ","blessed be"],
    ["שֵׁם","the name of"],
    ["אֵל","God"],
    ["עֶלְיוֹן׃","the Most High"],
    ["׃",""]
  ]},
  { num: "כ", words: [
    ["צֵא","go forth"],
    ["הַטְבֵּל","baptizing"],
    ["בְּמַיִם","with water"],
    ["הָכֵן","preparing"],
    ["הַדֶּרֶךְ","the way"],
    ["לְפָנַי","before my face"],
    ["לְעֵת","for the time of"],
    ["בּוֹאִי׃","my coming"],
    ["׃",""]
  ]},
  { num: "כא", words: [
    ["כִּי","for"],
    ["קְרוֹבָה","is at hand"],
    ["הָעֵת","the time"],
    ["הַיּוֹם","the day"],
    ["וְהַשָּׁעָה","or the hour"],
    ["לֹא","not"],
    ["יֵדַע","knoweth"],
    ["אִישׁ","no man"],
    ["אַךְ","but"],
    ["בֹּא","surely"],
    ["תָבוֹא׃","it shall come"],
    ["׃",""]
  ]},
  { num: "כב", words: [
    ["וְהַמְקַבֵּל","and he that receiveth"],
    ["אֶת",""],
    ["הַדְּבָרִים","things"],
    ["הָאֵלֶּה","these"],
    ["מְקַבֵּל","receiveth"],
    ["אֹתִי","me"],
    ["וְיֵאָסְפוּ","and they shall be gathered"],
    ["אֵלַי","me"],
    ["בַּזְּמַן","in time and in eternity"],
    ["וּבַנֶּצַח׃","and in eternity"],
    ["׃",""]
  ]},
  { num: "כג", words: [
    ["וְעוֹד","and again"],
    ["יִהְיֶה","it shall come to pass that"],
    ["עַל","on"],
    ["כׇּל","as many"],
    ["אֲשֶׁר","as"],
    ["תַּטְבִּילוּ","ye shall baptize"],
    ["בְמַיִם","with water"],
    ["תָּשִׂימוּ","ye shall lay"],
    ["יְדֵיכֶם","your hands"],
    ["וִיקַבְּלוּ","and they shall receive"],
    ["מַתַּת","the gift of"],
    ["רוּחַ","the Holy Ghost"],
    ["הַקֹּדֶשׁ",""],
    ["וְיִהְיוּ","and shall be"],
    ["מְצַפִּים","looking forth"],
    ["לְאוֹתוֹת","for the signs of"],
    ["בּוֹאִי","my coming"],
    ["וְיֵדְעוּ","and shall know"],
    ["אֹתִי׃","me"],
    ["׃",""]
  ]},
  { num: "כד", words: [
    ["הִנֵּה","behold"],
    ["מְהֵרָה","quickly"],
    ["אָבוֹא","I come"],
    ["כֵּן","even so"],
    ["יְהִי",""],
    ["אָמֵן׃","Amen"],
    ["׃",""]
  ]}
];
renderVerseSet(dc39_ch1Verses, 'dc39-ch1-verses');



var dc40_ch1Verses = [
  { num: "א", words: [
    ["הִנֵּה","behold"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["לֵב","that the heart of"],
    ["עַבְדִּי","my servant"],
    ["יַעֲקֹב","James Covel"],
    ["הָיָה","was"],
    ["יָשָׁר","right"],
    ["לְפָנַי","before me"],
    ["כִּי","for"],
    ["כָרַת","he covenanted"],
    ["בְּרִית",""],
    ["עִמִּי","with me"],
    ["לִשְׁמֹעַ","that he would obey"],
    ["לִדְבָרִי׃","my word"],
    ["׃",""]
  ]},
  { num: "ב", words: [
    ["וַיְקַבֵּל","and he received"],
    ["אֶת־הַדָּבָר","the word"],
    ["בְּשִׂמְחָה","with gladness"],
    ["אַךְ","but"],
    ["מִיָּד","straightway"],
    ["נִסָּהוּ","tempted him"],
    ["הַשָּׂטָן","Satan"],
    ["וּפַחַד","and the fear of"],
    ["הָרְדִיפָה","persecution"],
    ["וּדְאָגוֹת","and the cares of"],
    ["הָעוֹלָם","the world"],
    ["גָּרְמוּ","caused"],
    ["לוֹ","him"],
    ["לִמְאֹס","to reject"],
    ["בַּדָּבָר׃","the word"],
    ["׃",""]
  ]},
  { num: "ג", words: [
    ["לָכֵן","wherefore"],
    ["הֵפֵר","he broke"],
    ["בְּרִיתִי","my covenant"],
    ["וְנִשְׁאָר","and it remaineth"],
    ["לִי","with me"],
    ["לַעֲשׂוֹת","to do"],
    ["בּוֹ","with him"],
    ["כַּטּוֹב","as seemeth me good"],
    ["בְּעֵינַי",""],
    ["אָמֵן׃","Amen"],
    ["׃",""]
  ]}
];
renderVerseSet(dc40_ch1Verses, 'dc40-ch1-verses');



})();
