// dc_verses/dc91_100.js — D&C verse data
(function() {
var dc91_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily,"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the LORD"],
    ["אֲלֵיכֶם","unto you"],
    ["עַל־דְּבַר","concerning"],
    ["הַסְּפָרִים","the"],
    ["הַחִיצוֹנִים","Apocrypha—"],
    ["יֵשׁ","There are"],
    ["דְּבָרִים","things"],
    ["רַבִּים","many"],
    ["בָּהֶם","contained therein"],
    ["אֲשֶׁר","that"],
    ["אֱמֶת","are true,"],
    ["וְרֻבָּם","and the most of them"],
    ["תֻּרְגְּמוּ","it is translated"],
    ["נְכוֹנָה׃","correctly;"]
  ]},
  { num: "ב", words: [
    ["וְיֵשׁ","There are"],
    ["דְּבָרִים","things"],
    ["רַבִּים","many"],
    ["בָּהֶם","contained therein"],
    ["אֲשֶׁר־אֵינָם","that are not"],
    ["אֱמֶת","true,"],
    ["וְהֵם","which are"],
    ["תּוֹסָפוֹת","interpolations"],
    ["מִידֵי","from the hands of"],
    ["בְּנֵי־אָדָם׃","men."]
  ]},
  { num: "ג", words: [
    ["אָמֵן","Verily,"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["כִּי","that"],
    ["אֵין","it is not"],
    ["נָכוֹן","needful"],
    ["אֲשֶׁר","that"],
    ["יְתֻרְגְּמוּ","should be translated"],
    ["הַסְּפָרִים","the"],
    ["הַחִיצוֹנִים׃","Apocrypha."]
  ]},
  { num: "ד", words: [
    ["לָכֵן","Therefore,"],
    ["הַקּוֹרֵא","whoso reads"],
    ["בָּהֶם","it"],
    ["יָבִין","let him understand,"],
    ["כִּי","for"],
    ["הָרוּחַ","the Spirit"],
    ["מְגַלָּה","manifests"],
    ["אֱמֶת׃","truth;"]
  ]},
  { num: "ה", words: [
    ["וְהַנֵּאוֹר","And whoso is enlightened"],
    ["בָּרוּחַ","by the Spirit"],
    ["יוֹעִיל","shall obtain benefit"],
    
    ["מֵהֶם׃","therefrom;"]
  ]},
  { num: "ו", words: [
    ["וַאֲשֶׁר","And whoso"],
    ["לֹא","not"],
    ["יְקַבֵּל","receives"],
    ["בָּרוּחַ","by the Spirit,"],
    ["לֹא","cannot"],
    ["יוֹעִיל","be benefited."],
    ["לָכֵן","Therefore"],
    ["אֵין","it is not"],
    ["נָכוֹן","needful"],
    ["כִּי","that"],
    ["יְתֻרְגַּם","it should be translated."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc91_ch1Verses, 'dc91-ch1-verses');



var dc92_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily,"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the LORD,"],
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לַסֵּדֶר","unto the order"],
    ["הַמְאֻחָד","united"],
    ["הַמְיֻסֶּדֶת","organized"],
    ["כַּמִּצְוָה","agreeable to the commandment"],
    ["אֲשֶׁר־נִתְּנָה","given"],
    ["לְפָנִים","previously,"],
    ["חָזוֹן","a revelation"],
    ["וּמִצְוָה","and commandment"],
    ["עַל־אֹדוֹת","concerning"],
    ["עַבְדִּי","my servant"],
    ["פְרֶדְרִיק","Frederick"],
    ["ג׳","G."],
    ["וִילְיַמְס","Williams,"],
    ["כִּי","that"],
    ["תְּקַבְּלוּהוּ","you shall receive him"],
    ["אֶל־הַסֵּדֶר","into the order."],
    ["אֲשֶׁר","What"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְאֶחָד","unto one"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לַכֹּל׃","unto all."]
  ]},
  { num: "ב", words: [
    ["וְעוֹד","And again,"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְךָ","unto you"],
    ["עַבְדִּי","my servant"],
    ["פְרֶדְרִיק","Frederick"],
    ["ג׳","G."],
    ["וִילְיַמְס","Williams,"],
    ["תִּהְיֶה","you shall be"],
    ["לְאֵבֶר","a member"],
    ["חַי","lively"],
    ["בַּסֵּדֶר","in the order;"],
    ["הַזֹּאת","this"],
    ["וּכְפִי","and inasmuch as"],
    ["תֶּאֱמַן","you are faithful"],
    ["לִשְׁמֹר","in keeping"],
    ["אֶת־כׇּל־הַמִּצְוֹת","all the commandments"],
    ["הָרִאשׁוֹנוֹת","former"],
    ["תְּבֹרַךְ","you shall be blessed"],
    ["לְעוֹלָם","forever."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc92_ch1Verses, 'dc92-ch1-verses');



var dc93_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily,"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the LORD:"],
    ["יִהְיֶה","It shall come to pass"],
    ["כִּי","that"],
    ["כׇל־נֶפֶשׁ","every soul"],
    ["הָעֹזֶבֶת","who forsakes"],
    ["חַטֹּאתֶיהָ","his sins"],
    ["וּבָאָה","and comes"],
    ["אֵלַי","unto me,"],
    ["וְקֹרֵאת","and calls"],
    ["בִּשְׁמִי","on my name,"],
    ["וְשֹׁמַעַת","and hearkens to"],
    ["בְּקוֹלִי","my voice,"],
    ["וְשֹׁמֶרֶת","and keeps"],
    ["מִצְוֹתַי","my commandments,"],
    ["תִּרְאֶה","shall see"],
    ["פָנַי","my face"],
    ["וְתֵדַע","and know"],
    ["כִּי","that"],
    ["אֲנִי","I"],
    ["הוּא׃","am;"]
  ]},
  { num: "ב", words: [
    ["וַאֲנִי","And that I am"],
    ["הָאוֹר","the light"],
    ["הָאֲמִתִּי","true"],
    ["הַמֵּאִיר","that lights"],
    ["לְכׇל־אָדָם","every man"],
    ["הַבָּא","that comes"],
    ["לָעוֹלָם׃","into the world;"]
  ]},
  { num: "ג", words: [
    ["וַאֲנִי","And that I am"],
    ["בָאָב","in the Father,"],
    ["וְהָאָב","and the Father"],
    ["בִּי","in me,"],
    ["וְהָאָב","and the Father"],
    ["וַאֲנִי","and I"],
    ["אֶחָד׃","are one—"]
  ]},
  { num: "ד", words: [
    ["הָאָב","The Father"],
    ["כִּי","because"],
    ["נָתַן","he gave"],
    ["לִי","me"],
    ["מִמְּלֹאוֹ","of his fulness,"],
    ["וְהַבֵּן","and the Son"],
    ["כִּי","because"],
    ["הָיִיתִי","I was"],
    ["בָעוֹלָם","in the world"],
    ["וְעָשִׂיתִי","and made"],
    ["בָשָׂר","flesh"],
    ["מִשְׁכָּנִי","my tabernacle,"],
    ["וְשָׁכַנְתִּי","and dwelt"],
    ["בִּבְנֵי","among the sons of"],
    ["אָדָם׃","men."]
  ]},
  { num: "ה", words: [
    ["הָיִיתִי","I was"],
    ["בָעוֹלָם","in the world"],
    ["וְקִבַּלְתִּי","and received"],
    ["מֵאָבִי","of my Father,"],
    ["וּמַעֲשָׂיו","and his works"],
    ["נִגְלוּ","were manifest"],
    ["לָעֵינָיִם׃","plainly to the eyes."]
  ]},
  { num: "ו", words: [
    ["וְיוֹחָנָן","And John"],
    ["רָאָה","saw"],
    ["וְהֵעִיד","and bore record"],
    ["עַל","of"],
    ["מְלֹא","the fulness of"],
    ["כְּבוֹדִי","my glory,"],
    ["וּמְלֹא","and the fulness of"],
    ["עֵדוּת","the record of"],
    ["יוֹחָנָן","John"],
    ["יִגָּלֶה","is to be revealed."],
    ["אַחֲרֵי־כֵן׃","hereafter"]
  ]},
  { num: "ז", words: [
    ["וְהֵעִיד","And he bore record,"],
    ["לֵאמֹר","saying:"],
    ["רָאִיתִי","I saw"],
    ["כְּבוֹדוֹ","his glory,"],
    ["כִּי","that"],
    ["הָיָה","he was"],
    ["בָּרֵאשִׁית","in the beginning,"],
    ["לִפְנֵי","before"],
    ["הֱיוֹת","was;"],
    ["הָעוֹלָם׃","the world"]
  ]},
  { num: "ח", words: [
    ["לָכֵן","Therefore,"],
    ["בָּרֵאשִׁית","in the beginning"],
    ["הָיָה","was"],
    ["הַדָּבָר","the Word,"],
    ["כִּי","for"],
    ["הוּא","he"],
    ["הָיָה","was"],
    ["הַדָּבָר","the Word,"],
    ["מַלְאַךְ","even the messenger of"],
    ["הַיְשׁוּעָה׃","salvation—"]
  ]},
  { num: "ט", words: [
    ["הָאוֹר","The light"],
    ["וְהַגּוֹאֵל","and the Redeemer"],
    ["לָעוֹלָם","of the world;"],
    ["רוּחַ","the Spirit of"],
    ["הָאֱמֶת","truth,"],
    ["אֲשֶׁר","who"],
    ["בָּא","came"],
    ["לָעוֹלָם","into the world,"],
    ["כִּי","because"],
    ["הָעוֹלָם","the world"],
    ["בְּיָדוֹ","by him"],
    ["נַעֲשָׂה","was made,"],
    ["וּבוֹ","and in him"],
    ["הָיוּ","was"],
    ["חַיֵּי","the life of"],
    ["אָדָם","men"],
    ["וְאוֹר","and the light of"],
    ["אָדָם׃","men."]
  ]},
  { num: "י", words: [
    ["הָעוֹלָמוֹת","The worlds"],
    ["בְּיָדוֹ","by him"],
    ["נַעֲשׂוּ","were made;"],
    ["בְּנֵי","the sons of"],
    ["אָדָם","men"],
    ["בְּיָדוֹ","by him"],
    ["נַעֲשׂוּ","were made;"],
    ["כׇּל־דָּבָר","all things"],
    ["בְּיָדוֹ","by him,"],
    ["וּבוֹ","and through him,"],
    ["וּמִמֶּנּוּ","and of him"],
    ["נַעֲשָׂה׃","were made."]
  ]},
  { num: "יא", words: [
    ["וַאֲנִי","And I,"],
    ["יוֹחָנָן","John,"],
    ["מֵעִיד","bear record"],
    ["כִּי","that"],
    ["רָאִיתִי","I beheld"],
    ["כְּבוֹדוֹ","his glory,"],
    ["כִּכְבוֹד","as the glory of"],
    ["יְחִיד","the Only Begotten"],
    ["מֵאֵת","of"],
    ["הָאָב","the Father,"],
    ["מָלֵא","full of"],
    ["חֶסֶד","grace"],
    ["וֶאֱמֶת","and truth,"],
    ["אָכֵן","even"],
    ["רוּחַ","the Spirit of"],
    ["הָאֱמֶת","truth,"],
    ["אֲשֶׁר","which"],
    ["בָּא","came"],
    ["וְשָׁכַן","and dwelt"],
    ["בַּבָּשָׂר","in the flesh,"],
    ["וְשָׁכַן","and dwelt"],
    ["בְּתוֹכֵנוּ׃","among us."]
  ]},
  { num: "יב", words: [
    ["וַאֲנִי","And I,"],
    ["יוֹחָנָן","John,"],
    ["רָאִיתִי","saw"],
    ["כִּי","that"],
    ["לֹא","not"],
    ["קִבֵּל","he received"],
    ["מִמְּלֹאוֹ","of the fulness"],
    ["בָּרִאשׁוֹנָה","at the first,"],
    ["כִּי","but"],
    ["אִם־קִבֵּל","but received"],
    ["חֶסֶד","grace"],
    ["עַל","for"],
    ["חֶסֶד׃","grace;"]
  ]},
  { num: "יג", words: [
    ["וְלֹא","And not"],
    ["קִבֵּל","he received"],
    ["מִמְּלֹאוֹ","of the fulness"],
    ["בָּרִאשׁוֹנָה","at first,"],
    ["כִּי","but"],
    ["אִם","rather"],
    ["הָלַךְ","continued"],
    ["מֵחֶסֶד","from grace"],
    ["אֶל־חֶסֶד","to grace,"],
    ["עַד","until"],
    ["אֲשֶׁר","that"],
    ["קִבֵּל","he received"],
    ["מְלֹא׃","a fulness;"]
  ]},
  { num: "יד", words: [
    ["וְכֵן","And thus"],
    ["נִקְרָא","he was called"],
    ["בֶן־אֱלֹהִים","the Son of God,"],
    ["כִּי","because"],
    ["לֹא","not"],
    ["קִבֵּל","he received"],
    ["מִמְּלֹאוֹ","of the fulness"],
    ["בָּרִאשׁוֹנָה׃","at the first."]
  ]},
  { num: "טו", words: [["וַאֲנִי","And I,"], ["יוֹחָנָן","John,"], ["מֵעִיד","bear record,"], ["וְהִנֵּה","and lo,"], ["הַשָּׁמַיִם","the heavens"], ["נִפְתָּחוּ","were opened,"], ["וְרוּחַ","and the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["יָרְדָה","descended"], ["עָלָיו","upon him"], ["בִּדְמוּת","in the form of"], ["יוֹנָה","a dove,"], ["וַתָּנַח","and sat"], ["עָלָיו","upon him,"], ["וַיָּבֹא","and there came"], ["קוֹל","a voice"], ["מִן־הַשָּׁמַיִם","out of heaven"], ["לֵאמֹר","saying:"], ["זֶה","This is"], ["בְּנִי","my Son"], ["אֲהוּבִי׃","beloved."]]},
  { num: "טז", words: [
    ["וַאֲנִי","And I,"],
    ["יוֹחָנָן","John,"],
    ["מֵעִיד","bear record"],
    ["כִּי","that"],
    ["קִבֵּל","he received"],
    ["מְלֹא","a fulness of"],
    ["כְּבוֹד","the glory of"],
    ["הָאָב׃","the Father;"]
  ]},
  { num: "יז", words: [
    ["וַיְקַבֵּל","And he received"],
    ["כׇּל־כֹּחַ","all power,"],
    ["בַּשָּׁמַיִם","both in heaven"],
    ["וּבָאָרֶץ","and on earth,"],
    ["וּכְבוֹד","and the glory of"],
    ["הָאָב","the Father"],
    ["הָיָה","was"],
    ["עִמּוֹ","with him,"],
    ["כִּי","for"],
    ["שָׁכַן","he dwelt"],
    ["בּוֹ׃","in him."]
  ]},
  { num: "יח", words: [
    ["וִיהִי","And it shall come to pass,"],
    ["אִם","that if"],
    ["נֶאֱמָנִים","faithful"],
    ["אַתֶּם","you are"],
    ["תְּקַבְּלוּ","you shall receive"],
    ["אֶת־מְלֹא","the fulness of"],
    ["עֵדוּת","the record of"],
    ["יוֹחָנָן׃","John."]
  ]},
  { num: "יט", words: [
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לָכֶם","unto you"],
    ["אֶת־הַדְּבָרִים","the sayings"],
    ["הָאֵלֶּה","these"],
    ["לְמַעַן","that"],
    ["תָּבִינוּ","you may understand"],
    ["וְתֵדְעוּ","and know"],
    ["אֵיךְ","how"],
    ["לְהִשְׁתַּחֲווֹת","to worship,"],
    ["וְתֵדְעוּ","and know"],
    ["אֵת־אֲשֶׁר","what"],
    ["לוֹ","to whom"],
    ["אַתֶּם","you"],
    ["מִשְׁתַּחֲוִים","worship,"],
    ["לְמַעַן","that"],
    ["תָּבֹאוּ","you may come"],
    ["אֶל־הָאָב","unto the Father"],
    ["בִּשְׁמִי","in my name,"],
    ["וּבְעִתּוֹ","and in due time"],
    ["תְּקַבְּלוּ","receive"],
    ["מִמְּלֹאוֹ׃","of his fulness."]
  ]},
  { num: "כ", words: [
    ["כִּי","For"],
    ["אִם","if"],
    ["תִּשְׁמְרוּ","you keep"],
    ["מִצְוֹתַי","my commandments"],
    ["תְּקַבְּלוּ","you shall receive"],
    ["מִמְּלֹאוֹ","of his fulness,"],
    ["וְתִכָּבְדוּ","and be glorified"],
    ["בִי","in me"],
    ["כַּאֲשֶׁר","as"],
    ["אֲנִי","I am"],
    ["בָאָב","in the Father;"],
    ["לָכֵן","therefore,"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["תְּקַבְּלוּ","you shall receive"],
    ["חֶסֶד","grace"],
    ["עַל","for"],
    ["חֶסֶד׃","grace."]
  ]},
  { num: "כא", words: [
    ["וְעַתָּה","And now,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["הָיִיתִי","I was"],
    ["בָּרֵאשִׁית","in the beginning"],
    ["עִם","with"],
    ["הָאָב","the Father,"],
    ["וַאֲנִי","and am"],
    ["הַבְּכוֹר׃","the Firstborn;"]
  ]},
  { num: "כב", words: [["וְכׇל־הַנּוֹלָדִים","And all those who are begotten"], ["בְּיָדִי","through me"], ["שֻׁתָּפִים","are partakers of"], ["בְּאוֹתוֹ","the same"], ["כָּבוֹד","glory,"], ["וְהֵם","and are"], ["כְּנֵסִיַּת","the church of"], ["הַבְּכוֹר׃","the Firstborn."]]},
  { num: "כג", words: [
    ["גַּם","also"],
    ["אַתֶּם","You"],
    ["הֱיִיתֶם","were"],
    ["בָּרֵאשִׁית","in the beginning"],
    ["עִם","with"],
    ["הָאָב","the Father;"],
    ["אֲשֶׁר","that which"],
    ["רוּחַ","is Spirit,"],
    ["הוּא","which is"],
    ["אָכֵן","even"],
    ["רוּחַ","the Spirit of"],
    ["הָאֱמֶת׃","truth;"]
  ]},
  { num: "כד", words: [
    ["וְהָאֱמֶת","And truth"],
    ["הִיא","is"],
    ["דַּעַת","knowledge of"],
    ["הַדְּבָרִים","things"],
    ["כַּאֲשֶׁר","as"],
    ["הֵם","they are,"],
    ["וְכַאֲשֶׁר","and as"],
    ["הָיוּ","they were,"],
    ["וְכַאֲשֶׁר","and as"],
    ["יִהְיוּ׃","they are to come;"]
  ]},
  { num: "כה", words: [
    ["וְכׇל־יוֹתֵר","And whatsoever is more"],
    ["אוֹ","or"],
    ["פָחוֹת","less"],
    ["מִזֶּה","than this"],
    ["רוּחַ","is the spirit of"],
    ["הָרָשָׁע","the wicked"],
    ["הַהוּא","that one,"],
    ["אֲשֶׁר","who"],
    ["כַּזָּב","a liar"],
    ["הוּא","was"],
    ["מֵרֵאשִׁית׃","from the beginning."]
  ]},
  { num: "כו", words: [
    ["רוּחַ","The Spirit of"],
    ["הָאֱמֶת","truth"],
    ["מֵאֱלֹהִים","of God"],
    ["הִיא","is."],
    ["אֲנִי","I am"],
    ["רוּחַ","the Spirit of"],
    ["הָאֱמֶת","truth,"],
    ["וְיוֹחָנָן","and John"],
    ["הֵעִיד","bore record"],
    ["עָלַי","of me,"],
    ["לֵאמֹר","saying:"],
    ["הוּא","He"],
    ["קִבֵּל","received"],
    ["מְלֹא","a fulness of"],
    ["אֱמֶת","truth,"],
    ["אָכֵן","yea,"],
    ["מְלֹא","even of fulness"],
    ["כׇּל־אֱמֶת׃","all truth;"]
  ]},
  { num: "כז", words: [
    ["וְאֵין","And no"],
    ["אִישׁ","man"],
    ["מְקַבֵּל","receives"],
    ["מְלֹא","a fulness"],
    ["אֶלָּא","unless"],
    ["אִם","if"],
    ["שֹׁמֵר","he keeps"],
    ["מִצְוֹתָיו׃","his commandments."]
  ]},
  { num: "כח", words: [
    ["הַשֹּׁמֵר","He that keeps"],
    ["מִצְוֹתָיו","his commandments"],
    ["מְקַבֵּל","receives"],
    ["אֱמֶת","truth"],
    ["וָאוֹר","and light,"],
    ["עַד","until"],
    ["הִכָּבְדוֹ","he is glorified"],
    ["בֶּאֱמֶת","in truth"],
    ["וְיָדַע","and knows"],
    ["כׇּל־דָּבָר׃","all things."]
  ]},
  { num: "כט", words: [
    ["גַּם","also"],
    ["הָאָדָם","Man"],
    ["הָיָה","was"],
    ["בָּרֵאשִׁית","in the beginning"],
    ["עִם","with"],
    ["אֱלֹהִים","God."],
    ["שֵׂכֶל","Intelligence,"],
    ["אוֹ","or"],
    ["אוֹר","the light of"],
    ["הָאֱמֶת","truth,"],
    ["לֹא","not"],
    ["נִבְרָא","was created"],
    ["וְלֹא","or"],
    ["נַעֲשָׂה","made,"],
    ["וְאַף־לֹא","neither indeed"],
    ["יוּכַל׃","can be."]
  ]},
  { num: "ל", words: [
    ["כׇּל־אֱמֶת","All truth"],
    ["עוֹמֶדֶת","is"],
    ["לְעַצְמָהּ","independent"],
    ["בַּגְּבוּל","in that sphere"],
    ["אֲשֶׁר","in which"],
    ["שָׂמָהּ","has placed it"],
    ["אֱלֹהִים","God,"],
    ["לִפְעֹל","to act"],
    ["לְעַצְמָהּ","for itself,"],
    ["וְכֵן","as also"],
    ["כׇּל־שֵׂכֶל","all intelligence;"],
    ["וְאִם־לֹא","otherwise"],
    ["אֵין","there is no"],
    ["קִיּוּם׃","existence."]
  ]},
  { num: "לא", words: [
    ["הִנֵּה","Behold,"],
    ["זֹאת","here is"],
    ["בְּחִירַת","the agency choice of"],
    ["הָאָדָם","man,"],
    ["וְזֹאת","and here is"],
    ["אַשְׁמַת","the condemnation of"],
    ["הָאָדָם","man;"],
    ["כִּי","because"],
    ["הַנּוֹדָע","that which was"],
    ["מֵרֵאשִׁית","from the beginning"],
    ["גָּלוּי","is plainly manifest"],
    ["לָהֶם","unto them,"],
    ["וְהֵם","and they"],
    ["לֹא","not"],
    ["מְקַבְּלִים","receive"],
    ["אֶת־הָאוֹר׃","the light."]
  ]},
  { num: "לב", words: [
    ["וְכׇל־אִישׁ","And every man"],
    ["אֲשֶׁר","whose"],
    ["רוּחוֹ","spirit"],
    ["לֹא","not"],
    ["מְקַבֶּלֶת","receives"],
    ["אֶת־הָאוֹר","the light"],
    ["תַּחַת","under"],
    ["הָאַשְׁמָה","condemnation"],
    ["הוּא׃","is."]
  ]},
  { num: "לג", words: [
    ["כִּי","For"],
    ["הָאָדָם","man"],
    ["רוּחַ","is spirit."],
    ["הוּא","is"],
    ["הַיְסֹדוֹת","The elements"],
    ["הֵם","are"],
    ["נִצְחִיִּים","eternal,"],
    ["וְרוּחַ","and spirit"],
    ["וִיסוֹד","and element"],
    ["מְחֻבָּרִים","inseparably connected,"],
    ["יַחַד","together"],
    ["לֹא","not"],
    ["יִפָּרְדוּ","to be parted,"],
    ["מְקַבְּלִים","receive"],
    ["מְלֹא","a fulness of"],
    ["שִׂמְחָה׃","joy;"]
  ]},
  { num: "לד", words: [
    ["וּבְהִפָּרְדָם","And when separated,"],
    ["אֵין","cannot"],
    ["הָאָדָם","man"],
    ["יָכוֹל","be able to"],
    ["לְקַבֵּל","receive"],
    ["מְלֹא","a fulness of"],
    ["שִׂמְחָה׃","joy."]
  ]},
  { num: "לה", words: [
    ["הַיְסֹדוֹת","The elements"],
    ["מִשְׁכַּן","are the tabernacle of"],
    ["אֱלֹהִים","God;"],
    ["הֵם","they are"],
    ["אָכֵן","yea,"],
    ["הָאָדָם","man"],
    ["מִשְׁכַּן","is the tabernacle of"],
    ["אֱלֹהִים","God,"],
    ["הוּא","he is"],
    ["אַף","even"],
    ["הֵיכָלוֹת","temples;"],
    ["וְכׇל־הֵיכׇל","and whatsoever temple"],
    ["הַמְחֻלָּל","is defiled,"],
    ["יַשְׁמִידֶנּוּ","shall destroy that temple"],
    ["אֱלֹהִים׃","God."]
  ]},
  { num: "לו", words: [
    ["כְּבוֹד","The glory of"],
    ["אֱלֹהִים","God"],
    ["הוּא","is"],
    ["שֵׂכֶל","intelligence,"],
    ["אוֹ","or,"],
    ["בְמִלִּים","in words,"],
    ["אֲחֵרוֹת","other"],
    ["אוֹר","light"],
    ["וֶאֱמֶת׃","and truth."]
  ]},
  { num: "לז", words: [
    ["אוֹר","Light"],
    ["וֶאֱמֶת","and truth"],
    ["עֹזְבִים","forsake"],
    ["אֶת־הָרָע","that evil"],
    ["הַהוּא׃","one."]
  ]},
  { num: "לח", words: [
    ["כׇּל־רוּחַ","Every spirit of"],
    ["אָדָם","man"],
    ["הָיְתָה","was"],
    ["נְקִיָּה","innocent"],
    ["בָּרֵאשִׁית","in the beginning;"],
    ["וֵאלֹהִים","and God"],
    ["גָּאַל","having redeemed"],
    ["אֶת־הָאָדָם","man"],
    ["מִן־הַמַּפָּלָה","from the fall,"],
    ["בְּנֵי","the sons of"],
    ["אָדָם","men"],
    ["חָזְרוּ","became again,"],
    ["לִהְיוֹת","to be"],
    ["בִּימֵי","in the days of"],
    ["יַנְקוּתָם","their infancy"],
    ["נְקִיִּים","innocent"],
    ["לִפְנֵי","before"],
    ["אֱלֹהִים׃","God."]
  ]},
  { num: "לט", words: [
    ["וְהָרָשָׁע","And wicked"],
    ["הַהוּא","that one"],
    ["בָּא","comes"],
    ["וְלֹקֵחַ","and takes away"],
    ["אוֹר","light"],
    ["וֶאֱמֶת","and truth,"],
    ["בְּמֶרִי","through disobedience,"],
    ["מִבְּנֵי","from the children of"],
    ["אָדָם","men,"],
    ["וּבִגְלַל","and because of"],
    ["מָסֹרֶת","the tradition of"],
    ["אֲבוֹתֵיהֶם׃","their fathers."]
  ]},
  { num: "מ", words: [
    ["אֲבָל","But"],
    ["צִוִּיתִי","I have commanded"],
    ["אֶתְכֶם","you"],
    ["לְגַדֵּל","to bring up"],
    ["בְּנֵיכֶם","your children"],
    ["בְּאוֹר","in light"],
    ["וּבֶאֱמֶת׃","and truth."]
  ]},
  { num: "מא", words: [
    ["אֲבָל","But"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְךָ","unto you,"],
    ["עַבְדִּי","my servant"],
    ["פְרֶדְרִיק","Frederick"],
    ["ג׳","G."],
    ["וִילְיַמְס","Williams,"],
    ["הָיִיתָ","you have continued"],
    ["תַּחַת","under"],
    ["הָאַשְׁמָה","condemnation"],
    ["הַזֹּאת׃","this;"]
  ]},
  { num: "מב", words: [
    ["לֹא","not"],
    ["לִמַּדְתָּ","You have taught"],
    ["בָנֶיךָ","your children"],
    ["אוֹר","light"],
    ["וֶאֱמֶת","and truth,"],
    ["כַּמִּצְוֹת","according to the commandments;"],
    ["וְעוֹד","and as yet,"],
    ["לָרָשָׁע","that wicked"],
    ["הַהוּא","one"],
    ["מֶמְשָׁלָה","has power"],
    ["עָלֶיךָ","over you,"],
    ["וְזֶה","and this is"],
    ["סִבַּת","the cause of"],
    ["צָרָתֶךָ׃","your affliction."]
  ]},
  { num: "מג", words: [
    ["וְעַתָּה","And now"],
    ["מִצְוָה","a commandment"],
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לָכֶם","unto you—"],
    ["אִם","if"],
    ["תַּחְפְּצוּ","you will be"],
    ["לְהִנָּצֵל","delivered"],
    ["תַּקְּנוּ","you shall set in order"],
    ["אֶת־בֵּיתְכֶם","your own house,"],
    ["כִּי","for"],
    ["דְבָרִים","there are things"],
    ["רַבִּים","many"],
    ["אֵינָם","that are not"],
    ["נְכוֹנִים","right"],
    ["בְּבֵיתְכֶם׃","in your house."]
  ]},
  { num: "מד", words: [
    ["אָמֵן","Verily,"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְעַבְדִּי","unto my servant"],
    ["סִידְנִי","Sidney"],
    ["רִיגְדּוֹן","Rigdon,"],
    ["בִּדְבָרִים","that in things"],
    ["אֲחָדִים","some"],
    ["לֹא","not"],
    ["שָׁמַר","he has kept"],
    ["אֶת־הַמִּצְוֹת","the commandments"],
    ["עַל","concerning"],
    ["בָּנָיו","his children;"],
    ["לָכֵן","therefore,"],
    ["רִאשׁוֹנָה","first"],
    ["תַּקֵּן","set in order"],
    ["אֶת־בֵּיתֶךָ׃","your house."]
  ]},
  { num: "מה", words: [
    ["אָמֵן","Verily,"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְעַבְדִּי","unto my servant"],
    ["יוֹסֵף","Joseph"],
    ["סְמִית","Smith,"],
    ["הַבֵּן","Jun.,"],
    ["אוֹ","or"],
    ["בְמִלִּים","in words,"],
    ["אֲחֵרוֹת","other"],
    ["אֶקְרָא","I will call"],
    ["לָכֶם","you"],
    ["רֵעִים","friends,"],
    ["כִּי","for"],
    ["רֵעַי","my friends"],
    ["אַתֶּם","you are,"],
    ["וְנַחֲלָה","and an inheritance"],
    ["תִהְיֶה","you shall have"],
    ["לָכֶם","unto you"],
    ["עִמִּי׃","with me—"]
  ]},
  { num: "מו", words: [
    ["קָרָאתִי","I called"],
    ["לָכֶם","you"],
    ["עֲבָדִים","servants"],
    ["לְמַעַן","for sake,"],
    ["הָעוֹלָם","the world's"],
    ["וְאַתֶּם","and you are"],
    ["עֲבָדָיו","their servants"],
    ["לְמַעֲנִי׃","for my sake—"]
  ]},
  { num: "מז", words: [
    ["וְעַתָּה","And now,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְיוֹסֵף","unto Joseph"],
    ["סְמִית","Smith,"],
    ["הַבֵּן","Jun.—"],
    ["לֹא","not"],
    ["שָׁמַרְתָּ","You have kept"],
    ["אֶת־הַמִּצְוֹת","the commandments,"],
    ["וְעָלֶיךָ","and must needs"],
    ["לַעֲמֹד","you stand"],
    ["מוּכָח","rebuked"],
    ["לִפְנֵי","before"],
    ["יְהוָה׃","the Lord;"]
  ]},
  { num: "מח", words: [
    ["מִשְׁפַּחְתְּךָ","Your family"],
    ["שׁוֹב","must needs"],
    ["תָּשׁוּב","repent"],
    ["וְלַעֲזֹב","and forsake"],
    ["דְּבָרִים","things,"],
    ["אֲחָדִים","some"],
    ["וּלְהַקְשִׁיב","and give heed"],
    ["קֶשֶׁב","attentive"],
    ["רַב","more earnest"],
    ["לְדִבְרֶיךָ","unto your sayings,"],
    ["אוֹ","or"],
    ["תוּסַר","be removed"],
    ["מִמְּקוֹמָהּ׃","out of their place."]
  ]},
  { num: "מט", words: [
    ["אֵת־אֲשֶׁר","What"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְאֶחָד","unto one"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לַכֹּל","unto all;"],
    ["הִתְפַּלְּלוּ","pray"],
    ["תָמִיד","always,"],
    ["פֶּן","lest"],
    ["יִהְיֶה","have"],
    ["לָרָשָׁע","that wicked"],
    ["הַהוּא","one"],
    ["מֶמְשָׁלָה","power"],
    ["בָּכֶם","in you,"],
    ["וְהֵסִיר","and remove"],
    ["אֶתְכֶם","you"],
    ["מִמְּקוֹמְכֶם׃","out of your place."]
  ]},
  { num: "נ", words: [["גַּם","also,"], ["עַבְדִּי","My servant"], ["נְיוּאֶל","Newel"], ["ק.","K."], ["וִיטְנִי","Whitney"], ["פָּקִיד","a bishop"], ["כְּנֵסִיָּתִי","of my church,"], ["הִוָּסֵר","has need"], ["יִוָּסֵר","to be chastened,"], ["וִיתַקֵּן","and let him set in order"], ["אֶת־בֵּיתוֹ","his family,"], ["וְלִרְאוֹת","and see"], ["כִּי","that"], ["בְנֵי","the members of"], ["בֵיתוֹ","his house"], ["יִהְיוּ","are"], ["שֹׁקְדִים","diligent"], ["יוֹתֵר","more"], ["וְשָׂמִים","and concerned setting"], ["לֵב","heart"], ["בַּבַּיִת","at home,"], ["וְיִתְפַּלְּלוּ","and pray"], ["תָמִיד","always,"], ["אוֹ","or"], ["יוּסְרוּ","they shall be removed"], ["מִמְּקוֹמָם׃","out of their place."]]},
  { num: "נא", words: [
    ["וְעַתָּה","Now,"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["רֵעַי","my friends,"],
    ["יֵלֵךְ","let go"],
    ["עַבְדִּי","my servant"],
    ["סִידְנִי","Sidney"],
    ["רִיגְדּוֹן","Rigdon"],
    ["לְדַרְכּוֹ","on his journey,"],
    ["וִימַהֵר","and make haste,"],
    ["וְגַם","and also"],
    ["יַשְׁמִיעַ","proclaim"],
    ["שְׁנַת","the year of"],
    ["רָצוֹן","the LORD\'s favor"],
    ["לַיהוָה","of the Lord,"],
    ["וּבְשׂוֹרַת","and the gospel of"],
    ["הַיְשׁוּעָה","salvation,"],
    ["כַּאֲשֶׁר","as"],
    ["אֶתֵּן","I shall give"],
    ["בְּפִיו","him utterance;"],
    ["וּבִתְפִלַּת","and by prayer of"],
    ["אֱמוּנַתְכֶם","your faith"],
    ["בְּלֵב","with consent"],
    ["אֶחָד","one"],
    ["אֶסְעָדֶנּוּ׃","I will uphold him."]
  ]},
  { num: "נב", words: [
    ["וִימַהֲרוּ","And let make haste"],
    ["גַם","also,"],
    ["עֲבָדַי","my servants"],
    ["יוֹסֵף","Joseph"],
    ["סְמִית","Smith,"],
    ["הַבֵּן","Jun.,"],
    ["וּפְרֶדְרִיק","and Frederick"],
    ["ג׳","G."],
    ["וִילְיַמְס","Williams,"],
    ["וְיִנָּתֵן","and it shall be given"],
    ["לָהֶם","them"],
    ["כִּתְפִלַּת","even according to the prayer of"],
    ["אֱמוּנָה","faith;"],
    ["וּכְפִי","and inasmuch as"],
    ["שָׁמְרְכֶם","you keep"],
    ["דְּבָרַי","my sayings"],
    ["לֹא","not"],
    ["תִכָּלְמוּ","you shall be confounded"],
    ["בָעוֹלָם","in world,"],
    ["הַזֶּה","this"],
    ["וְלֹא","nor"],
    ["בָעוֹלָם","in the world"],
    ["הַבָּא׃","to come."]
  ]},
  { num: "נג", words: [["וְאָמֵן","And, verily"], ["אֲנִי","I"], ["אֹמֵר","say"], ["לָכֶם","unto you,"], ["רְצוֹנִי","that it is my will"], ["אֲשֶׁר־תְּמַהֲרוּ","that you should hasten"], ["לְתַרְגֵּם","to translate"], ["אֶת־כִּתְבֵי","the scriptures of"], ["הַקֹּדֶשׁ","the holy"], ["וְלִקְנוֹת","and to obtain"], ["דַּעַת","a knowledge of"], ["תּוֹלְדוֹת","history generations,"], ["וּמְדִינוֹת","and of countries,"], ["וּמַמְלָכוֹת","and of kingdoms,"], ["וְחֻקֵּי","of laws of"], ["אֱלֹהִים","God"], ["וְאָדָם","and man,"], ["וְכׇל־זֹאת","and all this"], ["לִישׁוּעַת","for the salvation of"], ["צִיּוֹן","Zion."], ["אָמֵן׃","Amen."]]}
];
renderVerseSet(dc93_ch1Verses, 'dc93-ch1-verses');



var dc94_ch1Verses = [
  { num: "א", words: [
    ["וְעוֹד","And again,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["רֵעַי","my friends,"],
    ["מִצְוָה","a commandment"],
    ["אֲנִי","I"],
    ["נֹתֵן","give"],
    ["לָכֶם","unto you,"],
    ["לְהָחֵל","that you shall commence"],
    ["מְלֶאכֶת","a work of"],
    ["תׇּכְנִית","laying out plan"],
    ["וְהָכָנַת","and preparing"],
    ["רֵאשִׁית","a beginning"],
    ["וִיסוֹד","and foundation"],
    ["עִיר","of the city of"],
    ["יְתַד","the stake of"],
    ["צִיּוֹן","Zion,"],
    ["פֹּה","here"],
    ["בְּאֶרֶץ","in the land of"],
    ["קִרְטְלַנְד","Kirtland,"],
    ["הָחֵל","beginning"],
    ["מִבֵּיתִי׃","at my house."]
  ]},
  { num: "ב", words: [
    ["וְהִנֵּה","And behold,"],
    ["יֵעָשֶׂה","it must be done"],
    ["כַּתַּבְנִית","according to the pattern"],
    ["אֲשֶׁר","which"],
    ["נָתַתִּי","I have given"],
    ["לָכֶם׃","unto you."]
  ]},
  { num: "ג", words: [["וְהַמִּגְרָשׁ","And let the lot"], ["הָרִאשׁוֹן","first"], ["בַּדָּרוֹם","on the south"], ["יֻקְדַּשׁ","be consecrated"], ["לִי","unto me"], ["לִבְנוֹת","for the building of"], ["בַּיִת","a house"], ["לַנְּשִׂיאוּת","for the presidency,"], ["לַעֲבוֹדַת","for the work of"], ["הַנְּשִׂיאוּת","the presidency,"], ["לְקַבֵּל","in obtaining"], ["חֲזוֹנוֹת","revelations;"], ["וְלַעֲבוֹדַת","and for the work of"], ["עֲבוֹדַת","the ministry of"], ["הַנְּשִׂיאוּת","the presidency,"], ["בְּכׇל־עִנְיְנֵי","in all things pertaining to"], ["הַכְּנֵסִיָּה","the church"], ["וְהַמַּלְכוּת׃","and kingdom."]]},
  { num: "ד", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["יִבָּנֶה","that it shall be built"],
    ["חֲמִשִּׁים","fifty"],
    ["וְחָמֵשׁ","-five"],
    ["עַל","by"],
    ["שִׁשִּׁים","sixty"],
    ["וְחָמֵשׁ","-five"],
    ["אַמָּה","feet"],
    ["בְּרׇחְבּוֹ","in the width thereof"],
    ["וּבְאׇרְכּוֹ","and in the length thereof,"],
    ["בֶּחָצֵר","in the court."],
    ["הַפְּנִימִית׃","inner"]
  ]},
  { num: "ה", words: [
    ["וְיִהְיֶה","And there shall be"],
    ["חָצֵר","a court"],
    ["תַּחְתּוֹן","lower"],
    ["וְחָצֵר","and a court,"],
    ["עֶלְיוֹן","higher"],
    ["כַּתַּבְנִית","according to the pattern"],
    ["אֲשֶׁר","which"],
    ["תִּנָּתֵן","shall be given"],
    ["לָכֶם","unto you"],
    ["אַחֲרֵי־כֵן׃","hereafter."]
  ]},
  { num: "ו", words: [
    ["וְיֻקְדַּשׁ","And it shall be dedicated"],
    ["לַיהוָה","unto the Lord"],
    ["מִיְּסוֹדוֹ","from the foundation thereof,"],
    ["כְּסֵדֶר","according to the order of"],
    ["הַכְּהֻנָּה","the priesthood,"],
    ["כַּתַּבְנִית","according to the pattern"],
    ["אֲשֶׁר","which"],
    ["תִּנָּתֵן","shall be given"],
    ["לָכֶם","unto you"],
    ["אַחֲרֵי־כֵן׃","hereafter."]
  ]},
  { num: "ז", words: [
    ["וְיֻקְדַּשׁ","And it shall be dedicated"],
    ["כֻּלּוֹ","wholly"],
    ["לַיהוָה","unto the Lord"],
    ["לַעֲבוֹדַת","for the work of"],
    ["הַנְּשִׂיאוּת׃","the presidency."]
  ]},
  { num: "ח", words: [
    ["וְלֹא","And not"],
    ["תַנִּיחוּ","you shall suffer"],
    ["דָבָר","thing"],
    ["טָמֵא","any unclean"],
    ["לָבוֹא","to come in"],
    ["בוֹ","unto it;"],
    ["וּכְבוֹדִי","and my glory"],
    ["יִהְיֶה","shall be"],
    ["שָׁם","there,"],
    ["וּפָנַי","and my presence"],
    ["יִהְיֶה","shall be"],
    ["שָׁם׃","there."]
  ]},
  { num: "ט", words: [
    ["אַךְ","But"],
    ["אִם","if"],
    ["יָבוֹא","there shall come"],
    ["בוֹ","into it"],
    ["דָבָר","thing,"],
    ["טָמֵא","any unclean"],
    ["לֹא","not"],
    ["יִהְיֶה","shall be"],
    ["כְבוֹדִי","my glory"],
    ["שָׁם","there;"],
    ["וּפָנַי","and my presence"],
    ["לֹא","not"],
    ["יָבוֹא","shall come"],
    ["בוֹ׃","into it."]
  ]},
  { num: "י", words: [["וְעוֹד","And again,"], ["אָמֵן","verily"], ["אֲנִי","I"], ["אֹמֵר","say"], ["לָכֶם","unto you,"], ["הַמִּגְרָשׁ","the lot"], ["הַשֵּׁנִי","second"], ["בַּדָּרוֹם","on the south"], ["יֻקְדַּשׁ","shall be dedicated"], ["לִי","unto me"], ["לִבְנוֹת","for the building of"], ["לִי","unto me"], ["בַּיִת","a house unto me,"], ["לַעֲבוֹדַת","for the work of"], ["הַכְּתָב","the printing writing"], ["לְתִרְגּוּם","of the translation of"], ["כִּתְבֵי","the scriptures of"], ["הַקֹּדֶשׁ","the holy"], ["וּלְכׇל־אֲשֶׁר","and all things whatsoever"], ["אֲצַוֶּה","I shall command"], ["אֶתְכֶם׃","you."]]},
  { num: "יא", words: [
    ["וְיִהְיֶה","And it shall be"],
    ["חֲמִשִּׁים","fifty"],
    ["וְחָמֵשׁ","-five"],
    ["עַל","by"],
    ["שִׁשִּׁים","sixty"],
    ["וְחָמֵשׁ","-five"],
    ["אַמָּה","feet"],
    ["בְּרׇחְבּוֹ","in the width thereof"],
    ["וּבְאׇרְכּוֹ","and the length thereof,"],
    ["בֶּחָצֵר","in the court;"],
    ["הַפְּנִימִית","inner"],
    ["וְיִהְיֶה","and there shall be"],
    ["חָצֵר","a court"],
    ["תַּחְתּוֹן","lower"],
    ["וְעֶלְיוֹן׃","and a higher."]
  ]},
  { num: "יב", words: [
    ["וְהַבַּיִת","And house"],
    ["הַזֶּה","this"],
    ["יֻקְדַּשׁ","shall be dedicated"],
    ["כֻּלּוֹ","wholly"],
    ["לַיהוָה","unto the Lord"],
    ["מִיְּסוֹדוֹ","from the foundation thereof,"],
    ["לַעֲבוֹדַת","for the work of"],
    ["הַכְּתָב","the printing writing,"],
    ["בְּכׇל־אֲשֶׁר","in all things whatsoever"],
    ["אֲצַוֶּה","I shall command"],
    ["אֶתְכֶם","you,"],
    ["לִהְיוֹת","to be"],
    ["קָדוֹשׁ","holy,"],
    ["וְטָהוֹר","undefiled,"],
    ["כַּתַּבְנִית","according to the pattern"],
    ["בַּכֹּל","in all things"],
    ["כַּאֲשֶׁר","as"],
    ["תִּנָּתֵן","it shall be given"],
    ["לָכֶם׃","unto you."]
  ]},
  { num: "יג", words: [
    ["וּבַמִּגְרָשׁ","And on the lot"],
    ["הַשְּׁלִישִׁי","third"],
    ["יְקַבֵּל","shall receive"],
    ["עַבְדִּי","my servant"],
    ["חִירָם","Hyrum"],
    ["סְמִית","Smith"],
    ["אֶת־נַחֲלָתוֹ׃","his inheritance."]
  ]},
  { num: "יד", words: [
    ["וּבַמִּגְרָשׁ","And on the lots"],
    ["הָרִאשׁוֹן","first"],
    ["וְהַשֵּׁנִי","and second"],
    ["בַּצָּפוֹן","on the north"],
    ["יְקַבְּלוּ","shall receive"],
    ["עֲבָדַי","my servants"],
    ["רֵינוֹלְדְס","Reynolds"],
    ["קָהוּן","Cahoon"],
    ["וְיֶרֶד","and Jared"],
    ["קַרְטֶר","Carter"],
    ["אֶת־נַחֲלָתָם׃","their inheritances—"]
  ]},
  { num: "טו", words: [
    ["לְמַעַן","That"],
    ["יַעֲשׂוּ","they may do"],
    ["אֶת־הַמְּלָאכָה","the work"],
    ["אֲשֶׁר","which"],
    ["מִנִּיתִים","I have appointed unto them,"],
    ["לִהְיוֹת","to be"],
    ["פְּקֻדִים","a committee appointed ones"],
    ["לִבְנוֹת","to build"],
    ["אֶת־בָּתַּי","my houses,"],
    ["כַּמִּצְוָה","according to the commandment,"],
    ["אֲשֶׁר","which"],
    ["צִוִּיתִי","have given"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהִים","God,"],
    ["אֶתְכֶם׃","unto you."]
  ]},
  { num: "טז", words: [
    ["שְׁנֵי","two"],
    ["הַבָּתִּים","houses"],
    ["הָאֵלֶּה","These"],
    ["לֹא","not"],
    ["יִבָּנוּ","are to be built"],
    ["עַד","until"],
    ["אֲשֶׁר","that"],
    ["אֶתֵּן","I give"],
    ["לָכֶם","unto you"],
    ["מִצְוָה","a commandment"],
    ["עֲלֵיהֶם׃","concerning them."]
  ]},
  { num: "יז", words: [
    ["וְעַתָּה","And now"],
    ["אֵינֶנִּי","I not"],
    ["נֹתֵן","give"],
    ["לָכֶם","unto you"],
    ["עוֹד","any more"],
    ["בָּעֵת","at the time."],
    ["הַזֹּאת","this"],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc94_ch1Verses, 'dc94-ch1-verses');



var dc95_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily,"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the LORD"],
    ["אֲלֵיכֶם","unto you"],
    ["אֲשֶׁר","whom"],
    ["אֲנִי","I"],
    ["אֹהֵב","love,"],
    ["וַאֲשֶׁר","and whom"],
    ["אֲנִי","I"],
    ["אֹהֵב","love"],
    ["אֲנִי","I"],
    ["גַם","also"],
    ["מְיַסֵּר","chasten"],
    ["לְמַעַן","that"],
    ["יִסָּלְחוּ","may be forgiven"],
    ["חַטֹּאתֵיהֶם","their sins,"],
    ["כִּי","for"],
    ["בַמּוּסָר","with the chastisement"],
    ["אֲנִי","I"],
    ["מֵכִין","prepare"],
    ["דֶּרֶךְ","a way"],
    ["לְהַצָּלָתָם","for their deliverance"],
    ["מִכׇּל־נִסָּיוֹן","in all things out of temptation,"],
    ["וָאֹהַב","and I have loved"],
    ["אֶתְכֶם׃","you—"]
  ]},
  { num: "ב", words: [
    ["לָכֵן","Wherefore,"],
    ["עֲלֵיכֶם","you must needs"],
    ["לְהִוָּסֵר","be chastened"],
    ["וְלַעֲמֹד","and stand"],
    ["מוּכָחִים","rebuked"],
    ["לְפָנָי׃","before my face;"]
  ]},
  { num: "ג", words: [
    ["כִּי","For"],
    ["חֲטָאתֶם","you have sinned against me"],
    ["חֲטָאָה","a sin,"],
    ["גְדוֹלָה","grievous"],
    ["מְאֹד","very"],
    ["בַּאֲשֶׁר","in that"],
    ["לֹא","not"],
    ["שַׂמְתֶּם","you have considered"],
    ["לֵב","heart"],
    ["אֶל־הַמִּצְוָה","the commandment"],
    ["הַגְּדוֹלָה","great"],
    ["בַּכֹּל","in all things,"],
    ["אֲשֶׁר","that"],
    ["נָתַתִּי","I have given"],
    ["לָכֶם","unto you"],
    ["עַל","concerning"],
    ["בִּנְיַן","the building of"],
    ["בֵּיתִי׃","my house;"]
  ]},
  { num: "ד", words: [
    ["לְהָכִין","For the preparation"],
    ["אֲשֶׁר","wherewith"],
    ["חָפַצְתִּי","I design"],
    ["לְהָכִין","to prepare"],
    ["אֶת־שְׁלִיחַי","my apostles"],
    ["לִזְמֹר","to prune"],
    ["כַּרְמִי","my vineyard"],
    ["לָאַחֲרוֹנָה","for the last time,"],
    ["לְמַעַן","that"],
    ["אוֹצִיא","I may bring to pass"],
    ["אֶת־מַעֲשִׂי","my act,"],
    ["הַזָּר","strange"],
    ["לְמַעַן","that"],
    ["אֶשְׁפֹּךְ","I may pour out"],
    ["אֶת־רוּחִי","my Spirit"],
    ["עַל","upon"],
    ["כׇּל־בָּשָׂר׃","all flesh—"]
  ]},
  { num: "ה", words: [
    ["אֲבָל","But"],
    ["הִנֵּה","behold,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["רַבִּים","that there are many"],
    ["נִסְמְכוּ","who have been ordained"],
    ["בְּתוֹכְכֶם","among you,"],
    ["אֲשֶׁר","whom"],
    ["קָרָאתִי","I have called"],
    ["אַךְ","but"],
    ["מְעַטִּים","few"],
    ["מֵהֶם","of them"],
    ["נִבְחָרִים׃","are chosen."]
  ]},
  { num: "ו", words: [
    ["אֲשֶׁר","They who"],
    ["אֵינָם","are not"],
    ["נִבְחָרִים","chosen"],
    ["חָטְאוּ","have sinned"],
    ["חֲטָאָה","a sin,"],
    ["גְדוֹלָה","grievous"],
    ["מְאֹד","very"],
    ["בַּאֲשֶׁר","in that"],
    ["הֹלְכִים","are walking"],
    ["הֵם","they"],
    ["בַּחֹשֶׁךְ","in darkness"],
    ["בַּצָּהֳרָיִם׃","at noon-day."]
  ]},
  { num: "ז", words: [
    ["וּמִפְּנֵי","And for cause"],
    ["זֹאת","this"],
    ["נָתַתִּי","I gave"],
    ["לָכֶם","unto you"],
    ["מִצְוָה","a commandment"],
    ["לִקְרֹא","that you should call"],
    ["עֲצָרָה","your solemn assembly,"],
    ["לְמַעַן","that"],
    ["יַעֲלוּ","might come up"],
    ["צוֹמְכֶם","your fastings"],
    ["וַאֲנָקַתְכֶם","and your mourning"],
    ["בְּאׇזְנֵי","into the ears of"],
    ["יְהוָה","the Lord"],
    ["צְבָאוֹת","of Sabaoth,"],
    ["אֲשֶׁר","which is"],
    ["פֵּרוּשׁוֹ","by interpretation,"],
    ["בּוֹרֵא","the creator of"],
    ["הַיּוֹם","the day"],
    ["הָרִאשׁוֹן","first,"],
    ["הָרֵאשִׁית","the beginning"],
    ["וְהָאַחֲרִית׃","and the end."]
  ]},
  { num: "ח", words: [
    ["אָכֵן","Yea,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["נָתַתִּי","I gave"],
    ["לָכֶם","unto you"],
    ["מִצְוָה","a commandment"],
    ["לִבְנוֹת","that you should build"],
    ["בַּיִת","a house,"],
    ["אֲשֶׁר","in the which"],
    ["בּוֹ","house"],
    ["חָפַצְתִּי","I design"],
    ["לְהַלְבִּישׁ","to endow"],
    ["אֶת־אֲשֶׁר","those whom"],
    ["בָּחַרְתִּי","I have chosen"],
    ["כֹּחַ","with power"],
    ["מִמָּרוֹם׃","from on high;"]
  ]},
  { num: "ט", words: [
    ["כִּי","For"],
    ["זֹאת","this is"],
    ["הַבְטָחַת","the promise of"],
    ["הָאָב","the Father"],
    ["לָכֶם","unto you;"],
    ["לָכֵן","therefore"],
    ["אֲנִי","I"],
    ["מְצַוֶּה","command"],
    ["אֶתְכֶם","you"],
    ["לְהִשָּׁאֵר","to tarry,"],
    ["כַּאֲשֶׁר","even as"],
    ["שְׁלִיחַי","my apostles"],
    ["בִּירוּשָׁלָיִם׃","at Jerusalem."]
  ]},
  { num: "י", words: [
    ["אַךְ","Nevertheless,"],
    ["עֲבָדַי","my servants"],
    ["חָטְאוּ","sinned"],
    ["חֲטָאָה","a sin;"],
    ["גְדוֹלָה","grievous"],
    ["מְאֹד","very"],
    ["וּמְרִיבוֹת","and contentions"],
    ["הָיוּ","arose"],
    ["בְּבֵית","in the house of"],
    ["הַנְּבִיאִים","the prophets;"],
    ["וְזֶה","which"],
    ["הֵרַע","was grievous"],
    ["לִי","unto me,"],
    ["מְאֹד","very"],
    ["אָמַר","says"],
    ["אֲדוֹנְכֶם","your Lord;"],
    ["לָכֵן","therefore"],
    ["שָׁלַחְתִּים","I sent them forth"],
    ["לְהִוָּסֵר׃","to be chastened."]
  ]},
  { num: "יא", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["רְצוֹנִי","it is my will"],
    ["אֲשֶׁר־תִּבְנוּ","that you should build"],
    ["בָּיִת","a house."],
    ["אִם","If"],
    ["תִּשְׁמְרוּ","you keep"],
    ["מִצְוֹתַי","my commandments"],
    ["יִהְיֶה","you shall have"],
    ["לָכֶם","unto you"],
    ["כֹּחַ","power"],
    ["לִבְנוֹתוֹ׃","to build it."]
  ]},
  { num: "יב", words: [
    ["אִם","If"],
    ["לֹא","not"],
    ["תִשְׁמְרוּ","you keep"],
    ["מִצְוֹתַי","my commandments,"],
    ["לֹא","shall not"],
    ["אַהֲבַת","the love of"],
    ["הָאָב","the Father"],
    ["תַּעֲמֹד","continue"],
    ["עִמָּכֶם","with you,"],
    ["לָכֵן","therefore"],
    ["תֵּלְכוּ","you shall walk"],
    ["בַּחֹשֶׁךְ׃","in darkness."]
  ]},
  { num: "יג", words: [
    ["וְעַתָּה","Now"],
    ["זֹאת","here is"],
    ["חׇכְמָה","wisdom,"],
    ["וְדַעַת","and the mind of"],
    ["יְהוָה","the Lord—"],
    ["יִבָּנֶה","let be built,"],
    ["הַבַּיִת","the house"],
    ["לֹא","not"],
    ["כְדֶרֶךְ","after the manner of"],
    ["הָעוֹלָם","the world,"],
    ["כִּי","for"],
    ["אֵינֶנִּי","I not"],
    ["נֹתֵן","give"],
    ["לָכֶם","unto you"],
    ["לִחְיוֹת","that you shall live"],
    ["כְּדֶרֶךְ","after the manner of"],
    ["הָעוֹלָם׃","the world;"]
  ]},
  { num: "יד", words: [
    ["לָכֵן","Therefore,"],
    ["יִבָּנֶה","let it be built"],
    ["כְּפִי","after the manner"],
    ["אֲשֶׁר","which"],
    ["אַרְאֶה","I shall show"],
    ["לִשְׁלֹשָׁה","unto three"],
    ["מִכֶּם","of you,"],
    ["אֲשֶׁר","whom"],
    ["תְּמַנּוּ","you shall appoint"],
    ["וְתִסְמְכוּ","and ordain"],
    ["לַכֹּחַ","unto power."],
    ["הַזֶּה׃","this"]
  ]},
  { num: "טו", words: [
    ["וּמִדָּתוֹ","And the size thereof"],
    ["תִּהְיֶה","shall be"],
    ["חֲמִשִּׁים","fifty"],
    ["וְחָמֵשׁ","and five"],
    ["אַמָּה","feet"],
    ["בְּרׇחְבּוֹ","in width,"],
    ["וְשִׁשִּׁים","and let it be sixty"],
    ["וְחָמֵשׁ","-five"],
    ["אַמָּה","feet"],
    ["בְּאׇרְכּוֹ","in length,"],
    ["בֶּחָצֵר","in the court"],
    ["הַפְּנִימִית׃","inner thereof."]
  ]},
  { num: "טז", words: [["וְהַחֵלֶק","And let the part"], ["הַתַּחְתּוֹן","lower"], ["בֶּחָצֵר","of the court"], ["הַפְּנִימִי","inner"], ["יֻקְדַּשׁ","be dedicated"], ["לִי","unto me"], ["לְקָרְבַּן","for offering,"], ["סְעוּדַתְכֶם","your sacrament"], ["וְלִדְרָשַׁתְכֶם","and for your preaching,"], ["וּלְצוֹמְכֶם","and your fasting,"], ["וְלִתְפִלַּתְכֶם","and your praying,"], ["וּלְהַעֲלוֹת","and the offering up of"], ["מִשְׁאֲלוֹתֵיכֶם","your desires"], ["הַקְּדוֹשׁוֹת","most holy"], ["לְפָנַי","unto me,"], ["אָמַר","says"], ["אֲדוֹנְכֶם׃","your Lord."]]},
  { num: "יז", words: [
    ["וְהַחֵלֶק","And let the part"],
    ["הָעֶלְיוֹן","higher"],
    ["בֶּחָצֵר","of the court"],
    ["הַפְּנִימִי","inner"],
    ["יֻקְדַּשׁ","be dedicated"],
    ["לִי","unto me"],
    ["לְבֵית","for the house school of"],
    ["שְׁלִיחַי","my apostles,"],
    ["אָמַר","says"],
    ["בֶּן־אַהְמָן","Son Ahman;"],
    ["אוֹ","or,"],
    ["בְמִלִּים","in words,"],
    ["אֲחֵרוֹת","other"],
    ["אַלְפוּס","Alphus;"],
    ["אוֹ","or,"],
    ["בְמִלִּים","in words,"],
    ["אֲחֵרוֹת","other"],
    ["אוֹמֶגוּס","Omegus;"],
    ["אָכֵן","even"],
    ["יֵשׁוּעַ","Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["אֲדוֹנְכֶם","your Lord."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc95_ch1Verses, 'dc95-ch1-verses');



var dc96_ch1Verses = [
  { num: "א", words: [
    ["הִנֵּה","Behold,"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["זֹאת","here is"],
    ["חׇכְמָה","wisdom,"],
    ["לָדַעַת","whereby you may know"],
    ["אֵיךְ","how"],
    ["לִנְהֹג","to act"],
    ["בַּדָּבָר","concerning matter,"],
    ["הַזֶּה","this"],
    ["כִּי","for"],
    ["רָאוּי","it is expedient"],
    ["לְפָנַי","in me"],
    ["אֲשֶׁר־הַיָּתֵד","that stake"],
    ["הַזֶּה","this"],
    ["אֲשֶׁר","that"],
    ["יָסַדְתִּי","I have set"],
    ["לְחֹזֶק","for the strength of"],
    ["צִיּוֹן","Zion"],
    ["יֵחָזֵק׃","should be made strong."]
  ]},
  { num: "ב", words: [
    ["לָכֵן","Therefore,"],
    ["יִפְקֹד","let take charge oversee"],
    ["עַבְדִּי","my servant"],
    ["נְיוּאֶל","Newel"],
    ["ק.","K."],
    ["וִיטְנִי","Whitney"],
    ["אֶת־הַמָּקוֹם","of the place"],
    ["הַנִּקְרָא","which is named"],
    ["בֵינֵיכֶם","among you,"],
    ["אֲשֶׁר","upon which"],
    ["עָלָיו","upon it"],
    ["חָפַצְתִּי","I design"],
    ["לִבְנוֹת","to build"],
    ["אֶת־בֵּיתִי","mine house."],
    ["הַקָּדוֹשׁ׃","holy"]
  ]},
  { num: "ג", words: [
    ["וְעוֹד","And again,"],
    ["יֵחָלֵק","let it be divided"],
    ["לְמִגְרָשׁוֹת","into lots,"],
    ["כְּחׇכְמָה","according to wisdom,"],
    ["לְטוֹבַת","for the benefit of"],
    ["הַמְבַקְשִׁים","those who seek"],
    ["נַחֲלוֹת","inheritances,"],
    ["כַּאֲשֶׁר","as"],
    ["יֵקָבַע","it shall be determined"],
    ["בַּסּוֹד","in council"],
    ["בֵּינֵיכֶם׃","among you."]
  ]},
  { num: "ד", words: [
    ["לָכֵן","Therefore,"],
    ["הִשָּׁמְרוּ","take heed"],
    ["לִרְאוֹת","that you see to"],
    ["לַדָּבָר","matter,"],
    ["הַזֶּה","this"],
    ["וְלַחֵלֶק","and portion"],
    ["הַנָּחוּץ","that necessary"],
    ["לְהוֹעִיל","to benefit"],
    ["לְסִדְרִי","my order,"],
    ["לְהוֹצִיא","for the purpose of bringing forth"],
    ["דְבָרִי","my word"],
    ["לִבְנֵי","to the children of"],
    ["אָדָם׃","men."]
  ]},
  { num: "ה", words: [
    ["כִּי","For"],
    ["הִנֵּה","behold,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["זֶה","this is"],
    ["הָרָאוּי","the expedient"],
    ["בְּיוֹתֵר","most"],
    ["לְפָנַי","in me,"],
    ["אֲשֶׁר־יֵצֵא","that should go forth"],
    ["דְבָרִי","my word"],
    ["לִבְנֵי","unto the children of"],
    ["אָדָם","men,"],
    ["לְהַכְנִיעַ","for the purpose of subduing"],
    ["לְבָבוֹת","the hearts of"],
    ["בְּנֵי","the children of"],
    ["אָדָם","men"],
    ["לְטוֹבַתְכֶם","for your good."],
    ["כֵּן","Even"],
    ["יְהִי","so."],
    ["אָמֵן׃","Amen."]
  ]},
  { num: "ו", words: [["וְעוֹד","And again,"], ["אָמֵן","verily"], ["אֲנִי","I"], ["אֹמֵר","say"], ["לָכֶם","unto you,"], ["חׇכְמָה","it is wisdom"], ["וְרָאוּי","and expedient"], ["לְפָנַי","in me,"], ["אֲשֶׁר־עַבְדִּי","that my servant"], ["ג׳וֹן","John"], ["ג׳וֹנְסוֹן","Johnson"], ["אֲשֶׁר","whose"], ["קִבַּלְתִּי","I have accepted"], ["קָרְבָּנוֹ","offering,"], ["וְשָׁמַעְתִּי","and I have heard,"], ["תְּפִלּוֹתָיו","whose prayers"], ["אֲשֶׁר־לוֹ","unto whom"], ["אֲנִי","I"], ["נֹתֵן","give"], ["הַבְטָחַת","a promise of"], ["חַיֵּי","life"], ["עוֹלָם","eternal"], ["כְּפִי","inasmuch as"], ["שׁוֹמֵר","he keeps"], ["מִצְוֹתַי","my commandments"], ["מֵעַתָּה׃","from henceforth—"]]},
  { num: "ז", words: [
    ["כִּי","For"],
    ["מִזֶּרַע","a descendant of"],
    ["יוֹסֵף","Joseph"],
    ["הוּא","he is"],
    ["וְשֻׁתָּף","and a partaker"],
    ["בְּבִרְכוֹת","of the blessings of"],
    ["הַהַבְטָחָה","the promise"],
    ["אֲשֶׁר","which"],
    ["נִתְּנָה","was made"],
    ["לַאֲבוֹתָיו׃","unto his fathers—"]
  ]},
  { num: "ח", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["רָאוּי","it is expedient"],
    ["לְפָנַי","in me"],
    ["אֲשֶׁר־יִהְיֶה","that he should become"],
    ["לְאֵבֶר","a member"],
    ["בַּסֵּדֶר","of the order,"],
    ["לְמַעַן","that"],
    ["יַעֲזֹר","he may assist"],
    ["לְהוֹצִיא","in bringing forth"],
    ["דְבָרִי","my word"],
    ["לִבְנֵי","unto the children of"],
    ["אָדָם׃","men."]
  ]},
  { num: "ט", words: [
    ["לָכֵן","Therefore"],
    ["תִּסְמְכוּהוּ","you shall ordain him"],
    ["לַבְּרָכָה","unto blessing,"],
    ["הַזֹּאת","this"],
    ["וְיִדְרֹשׁ","and he shall seek"],
    ["הֵיטֵב","diligently"],
    ["לְהָסִיר","to take away"],
    ["אֶת־הַמַּשָּׂאוֹת","incumbrances"],
    ["אֲשֶׁר","that are"],
    ["עַל","upon"],
    ["הַבַּיִת","the house"],
    ["הַנִּקְרָא","named"],
    ["בֵינֵיכֶם","among you,"],
    ["לְמַעַן","that"],
    ["יֵשֵׁב","he may dwell"],
    ["בּוֹ","therein."],
    ["כֵּן","Even"],
    ["יְהִי","so."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc96_ch1Verses, 'dc96-ch1-verses');



var dc97_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["רֵעַי","my friends,"],
    ["מְדַבֵּר","I speak"],
    ["אֲלֵיכֶם","unto you"],
    ["בְּקוֹלִי","with my voice,"],
    ["אָכֵן","even"],
    ["בְּקוֹל","the voice of"],
    ["רוּחִי","my Spirit,"],
    ["לְהַרְאוֹתְכֶם","that I may show unto you"],
    ["רְצוֹנִי","my will"],
    ["עַל","concerning"],
    ["אֲחֵיכֶם","your brethren"],
    ["בְּאֶרֶץ","in the land of"],
    ["צִיּוֹן","Zion,"],
    ["אֲשֶׁר","of whom"],
    ["רַבִּים","many"],
    ["מֵהֶם","of them"],
    ["עֲנָוִים","are humble"],
    ["בֶּאֱמֶת","truly"],
    ["וּמְבַקְּשִׁים","and are seeking"],
    ["הֵיטֵב","diligently"],
    ["לִלְמֹד","to learn"],
    ["חׇכְמָה","wisdom"],
    ["וְלִמְצֹא","and to find"],
    ["אֱמֶת׃","truth."]
  ]},
  { num: "ב", words: [
    ["אָמֵן","Verily,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["אַשְׁרֵי","blessed are"],
    ["אֵלֶּה","such,"],
    ["כִּי","for"],
    ["יַשִּׂיגוּ","they shall obtain;"],
    ["כִּי","for"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["מְרַחֵם","show mercy"],
    ["עַל","unto"],
    ["כׇּל־הָעֲנָוִים","all the meek,"],
    ["וְעַל","and upon"],
    ["כׇּל־אֲשֶׁר","all whomsoever"],
    ["אֶחְפֹּץ","I will,"],
    ["לְמַעַן","that"],
    ["אֶצְדַּק","I may be justified"],
    ["בַּהֲבִיאִי","when I shall bring"],
    ["אוֹתָם","them"],
    ["לַמִּשְׁפָּט׃","unto judgment."]
  ]},
  { num: "ג", words: [
    ["הִנֵּה","Behold,"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["עַל","concerning"],
    ["בֵּית","the school"],
    ["הַמִּדְרָשׁ","of study"],
    ["בְּצִיּוֹן","in Zion,"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["חָפֵץ","am well pleased"],
    
    ["אֲשֶׁר־יִהְיֶה","that there should be"],
    ["בֵּית","a school"],
    ["מִדְרָשׁ","of study"],
    ["בְּצִיּוֹן","in Zion,"],
    ["וְגַם","and also"],
    ["מֵעַבְדִּי","with my servant"],
    ["פַּרְלִי","Parley"],
    ["פּ.","P."],
    ["פְּרֶט","Pratt,"],
    ["כִּי","for"],
    ["בִי","in me"],
    ["הוּא","he"],
    ["שֹׁכֵן׃","abides."]
  ]},
  { num: "ד", words: [
    ["וּכְפִי","And inasmuch as"],
    ["אֲשֶׁר־יוֹסִיף","he continues"],
    ["לִשְׁכֹּן","to abide"],
    ["בִּי","in me"],
    ["יוֹסִיף","he shall continue"],
    ["לִפְקֹד","to preside over"],
    ["אֶת־בֵּית","the school"],
    ["הַמִּדְרָשׁ","of study"],
    ["בְּאֶרֶץ","in the land of"],
    ["צִיּוֹן","Zion"],
    ["עַד","until"],
    ["אֶתֵּן־לוֹ","I shall give unto him"],
    ["מִצְוֹת","commandments"],
    ["אֲחֵרוֹת׃","other"]
  ]},
  { num: "ה", words: [["וַאֲבָרְכֶנּוּ","And I will bless him"], ["בְּרֹב","with a multiplicity of"], ["בְּרָכוֹת","blessings,"], ["לְפָרֵשׁ","in expounding"], ["כׇּל־כִּתְבֵי","all the scriptures of"], ["הַקֹּדֶשׁ","the holy"], ["וְהַסּוֹדוֹת","and mysteries"], ["לְבִנְיַן","to the edification of"], ["בֵּית","the school,"], ["הַמִּדְרָשׁ","of study"], ["וְהַכְּנֵסִיָּה","and of the church"], ["בְּצִיּוֹן׃","in Zion."]]},
  { num: "ו", words: [
    ["וְלִשְׁאָר","And to the residue of"],
    ["בֵּית","the school,"],
    ["הַמִּדְרָשׁ","of study"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["רוֹצֶה","am willing"],
    ["לְרַחֵם","to show mercy;"],
    ["אַךְ","nevertheless,"],
    ["יֵשׁ","there are"],
    ["אֲשֶׁר","those that"],
    ["הִוָּסֵר","must needs"],
    ["יִוָּסְרוּ","be chastened,"],
    ["וּמַעֲשֵׂיהֶם","and their works"],
    ["יִוָּדְעוּ׃","shall be made known."]
  ]},
  { num: "ז", words: [
    ["הַגַּרְזֶן","The ax"],
    ["הוּשַׂם","is laid"],
    ["עַל","at"],
    ["שֹׁרֶשׁ","the root of"],
    ["הָעֵצִים","the trees;"],
    ["וְכׇל־עֵץ","and every tree"],
    ["אֲשֶׁר־אֵינֶנּוּ","that not"],
    ["עֹשֶׂה","brings forth"],
    ["פְּרִי","fruit"],
    ["טוֹב","good"],
    ["יִכָּרֵת","shall be hewn down"],
    ["וְיֻשְׁלַךְ","and cast"],
    ["בָּאֵשׁ","into the fire."],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["דִּבַּרְתִּי׃","have spoken it."]
  ]},
  { num: "ח", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["כׇּל־אֲשֶׁר","all who"],
    ["יוֹדְעִים","know"],
    ["בֵּינֵיהֶם","among them"],
    ["כִּי","that"],
    ["לְבָבָם","their hearts"],
    ["יָשָׁר","are honest,"],
    ["וְנִשְׁבָּר","and are broken,"],
    ["וְרוּחָם","and their spirits"],
    ["נִדְכָּאָה","contrite,"],
    ["וְרוֹצִים","and are willing"],
    ["לִשְׁמֹר","to observe"],
    ["בְּרִיתוֹתֵיהֶם","their covenants"],
    ["בְּקָרְבָּן","by sacrifice—"],
    ["אָכֵן","yea,"],
    ["כׇּל־קָרְבָּן","every sacrifice"],
    ["אֲשֶׁר","which"],
    ["אֲצַוֶּה","shall command—"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["מְקֻבָּלִים","they are accepted"],
    ["לְפָנָי׃","of me."]
  ]},
  { num: "ט", words: [
    ["כִּי","For"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["אֶעֱשֶׂה","will cause make"],
    ["לָהֶם","them"],
    ["לְהָנִיב","to bring forth"],
    ["כְּעֵץ","as a tree"],
    ["מַרְבֶּה","very fruitful"],
    ["פְּרִי","fruitful"],
    ["הַשָּׁתוּל","which is planted"],
    ["בְּאֶרֶץ","in a land"],
    ["טוֹבָה","goodly,"],
    ["עַל","by"],
    ["יְאוֹר","a stream"],
    ["טָהוֹר","pure,"],
    ["הַנּוֹתֵן","that yields"],
    ["פְּרִי","fruit"],
    ["יָקָר","precious"],
    ["לָרֹב׃","much."]
  ]},
  { num: "י", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["רְצוֹנִי","that it is my will"],
    ["אֲשֶׁר־יִבָּנֶה","that should be built"],
    ["לִי","unto me"],
    ["בַּיִת","a house"],
    ["בְּאֶרֶץ","in the land of"],
    ["צִיּוֹן","Zion,"],
    ["כַּתַּבְנִית","like unto the pattern"],
    ["אֲשֶׁר","which"],
    ["נָתַתִּי","I have given"],
    ["לָכֶם׃","you."]
  ]},
  { num: "יא", words: [
    ["אָכֵן","Yea,"],
    ["יִבָּנֶה","let it be built"],
    ["בִּמְהֵרָה","speedily,"],
    ["בְּמַעְשַׂר","by the tithing of"],
    ["עַמִּי׃","my people."]
  ]},
  { num: "יב", words: [
    ["הִנֵּה","Behold,"],
    ["זֶה","this is"],
    ["הַמַּעֲשֵׂר","the tithing"],
    ["וְהַקָּרְבָּן","and the sacrifice"],
    ["אֲשֶׁר","which"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["דּוֹרֵשׁ","require"],
    ["מִיָּדָם","at their hands,"],
    ["לְמַעַן","that"],
    ["יִבָּנֶה","there may be built"],
    ["לִי","unto me"],
    ["בַּיִת","a house"],
    ["לִישׁוּעַת","for the salvation of"],
    ["צִיּוֹן׃","Zion—"]
  ]},
  { num: "יג", words: [
    ["לִמְקוֹם","For a place"],
    ["הוֹדָיָה","of thanksgiving"],
    ["לְכׇל־הַקְּדוֹשִׁים","for all saints,"],
    ["וְלִמְקוֹם","and for a place"],
    ["הוֹרָאָה","of instruction"],
    ["לְכׇל־הַנִּקְרָאִים","for all those who are called"],
    ["לִמְלֶאכֶת","to the work of"],
    ["הָעֲבוֹדָה","the ministry"],
    ["בְּכׇל־מִשְׂרוֹתֵיהֶם׃","in all their several callings and offices;"]
  ]},
  { num: "יד", words: [
    ["לְמַעַן","that"],
    ["יֻשְׁלְמוּ","be made perfect"],
    ["בַּהֲבָנַת","in the understanding of"],
    ["עֲבוֹדָתָם","their ministry"],
    ["בְּלֶקַח","in theory teaching,"],
    ["בְּעִקָּר","in principle,"],
    ["וּבְתוֹרָה","and in doctrine,"],
    ["בְּכׇל־הַנּוֹגֵעַ","in all things pertaining to"],
    ["לְמַלְכוּת","the kingdom of"],
    ["אֱלֹהִים","God"],
    ["בָּאָרֶץ","on the earth"],
    ["אֲשֶׁר","which"],
    ["מַפְתְּחוֹתֶיהָ","keys"],
    ["נִמְסְרוּ","have been conferred"],
    ["לָכֶם׃","unto you"]
  ]},
  { num: "טו", words: [
    ["וּכְפִי","And inasmuch as"],
    ["אֲשֶׁר־יִבְנֶה","build"],
    ["עַמִּי","my people"],
    ["לִי","unto me"],
    ["בַּיִת","a house"],
    ["בְּשֵׁם","in the name of"],
    ["יְהוָה","the Lord,"],
    ["וְלֹא","and not"],
    ["יַנִּיחוּ","do suffer"],
    ["דָבָר","thing"],
    ["טָמֵא","any unclean"],
    ["לָבוֹא","to come"],
    ["בוֹ","into it,"],
    ["וְלֹא","that not"],
    ["יְחֻלָּל","it be defiled,"],
    ["יִשְׁכֹּן","shall rest"],
    ["כְּבוֹדִי","my glory"],
    ["עָלָיו׃","upon it;"]
  ]},
  { num: "טז", words: [
    ["אָכֵן","Yea,"],
    ["פָּנַי","and my presence"],
    ["יִהְיֶה","shall be"],
    ["שָׁם","there,"],
    ["כִּי","for"],
    ["אָבוֹא","I will come"],
    ["בוֹ","into it,"],
    ["וְכׇל־בַּר","and all the pure in"],
    ["לֵבָב","heart"],
    ["הַבָּא","that shall come"],
    ["בוֹ","into it"],
    ["יִרְאֶה","shall see"],
    ["אֱלֹהִים׃","God."]
  ]},
  { num: "יז", words: [
    ["אַךְ","But"],
    ["אִם","if"],
    ["יְחֻלָּל","it be defiled"],
    ["לֹא","not"],
    ["אָבוֹא","I will come"],
    ["בוֹ","into it,"],
    ["וּכְבוֹדִי","and my glory"],
    ["לֹא","not"],
    ["יִהְיֶה","shall be"],
    ["שָׁם","there;"],
    ["כִּי","for"],
    ["לֹא","not"],
    ["אָבוֹא","I will come"],
    ["בְּהֵיכָלוֹת","into temples."],
    ["טְמֵאִים׃","unholy"]
  ]},
  { num: "יח", words: [
    ["וְעַתָּה","And, now,"],
    ["הִנֵּה","behold,"],
    ["אִם","if"],
    ["תַּעֲשֶׂה","do"],
    ["צִיּוֹן","Zion"],
    ["אֶת־הַדְּבָרִים","things"],
    ["הָאֵלֶּה","these"],
    ["תִּצְלַח","she shall prosper,"],
    ["וְתִתְפַּשֵּׁט","and spread herself"],
    ["וְתִהְיֶה","and become"],
    ["נִכְבֶּדֶת","glorious,"],
    ["מְאֹד","very"],
    ["וּגְדוֹלָה","great,"],
    ["מְאֹד","very"],
    ["וְנוֹרָאָה","and terrible."],
    ["מְאֹד׃","very"]
  ]},
  { num: "יט", words: [
    ["וּגוֹיֵי","And the nations of"],
    ["הָאָרֶץ","the earth"],
    ["יְכַבְּדוּהָ","shall honor her,"],
    ["וְיֹאמְרוּ","and shall say:"],
    ["אָכֵן","Surely"],
    ["צִיּוֹן","Zion is"],
    ["עִיר","the city of"],
    ["אֱלֹהֵינוּ","our God,"],
    ["וְאָכֵן","and surely"],
    ["צִיּוֹן","Zion"],
    ["לֹא","not"],
    ["תִפֹּל","cannot fall,"],
    ["וְלֹא","neither"],
    ["תִמּוֹט","be moved"],
    ["מִמְּקוֹמָהּ","out of her place,"],
    ["כִּי","for"],
    ["אֱלֹהִים","God"],
    ["שָׁם","is there,"],
    ["וְיַד","and the hand of"],
    ["יְהוָה","the Lord"],
    ["שָׁם׃","is there;"]
  ]},
  { num: "כ", words: [
    ["וְהוּא","And he"],
    ["נִשְׁבַּע","has sworn"],
    ["בְּכֹחַ","by the power of"],
    ["גְּבוּרָתוֹ","his might"],
    ["לִהְיוֹת","to be"],
    ["יְשׁוּעָתָהּ","her salvation"],
    ["וּמִגְדָּלָהּ","and her tower."],
    ["הַגָּבֹהַּ׃","high"]
  ]},
  { num: "כא", words: [
    ["לָכֵן","Therefore,"],
    ["אָמֵן","verily,"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord,"],
    ["תָּגֵל","let rejoice,"],
    ["צִיּוֹן","Zion"],
    ["כִּי","for"],
    ["זֹאת","this is"],
    ["צִיּוֹן","Zion—"],
    ["בָּרֵי","THE PURE IN"],
    ["לֵבָב","HEART;"],
    ["לָכֵן","therefore,"],
    ["תָּגֵל","let rejoice,"],
    ["צִיּוֹן","Zion"],
    ["וְכׇל־הָרְשָׁעִים","while all the wicked"],
    ["יִסְפְּדוּ׃","shall mourn."]
  ]},
  { num: "כב", words: [
    ["כִּי","For"],
    ["הִנֵּה","behold, and lo,"],
    ["נָקָם","vengeance"],
    ["בָּא","comes"],
    ["בִּמְהֵרָה","speedily"],
    ["עַל","upon"],
    ["הָרְשָׁעִים","the ungodly"],
    ["כַּסּוּפָה","as the whirlwind;"],
    ["וּמִי","and who"],
    ["יִמָּלֵט׃","shall escape it?"]
  ]},
  { num: "כג", words: [
    ["שׁוֹט","The scourge"],
    ["יְהוָה","Lord's"],
    ["יַעֲבֹר","shall pass over"],
    ["לַיְלָה","by night"],
    ["וָיוֹם","and by day,"],
    ["וְשִׁמְעוֹ","and the report thereof"],
    ["יַטְרִיד","shall vex"],
    ["כׇּל־עָם","all people;"],
    ["אָכֵן","yea,"],
    ["לֹא","not"],
    ["יֵעָצֵר","it shall be stayed"],
    ["עַד","until"],
    ["בּוֹא","come;"],
    ["יְהוָה׃","the Lord"]
  ]},
  { num: "כד", words: [
    ["כִּי","For"],
    ["חֲרוֹן","the indignation of"],
    ["יְהוָה","the Lord"],
    ["בָּעַר","is kindled"],
    ["עַל","against"],
    ["תּוֹעֲבוֹתֵיהֶם","their abominations"],
    ["וְכׇל־מַעֲשֵׂיהֶם","and all their works."],
    ["הָרָעִים׃","wicked"]
  ]},
  { num: "כה", words: [
    ["אַךְ","Nevertheless,"],
    ["צִיּוֹן","Zion"],
    ["תִּמָּלֵט","shall escape"],
    ["אִם","if"],
    ["תִּשְׁמֹר","she observe"],
    ["לַעֲשׂוֹת","to do"],
    ["כׇּל־אֲשֶׁר","all things whatsoever"],
    ["צִוִּיתִיהָ׃","I have commanded her."]
  ]},
  { num: "כו", words: [
    ["וְאִם","But if"],
    ["לֹא","not"],
    ["תִשְׁמֹר","she observe"],
    ["לַעֲשׂוֹת","to do"],
    ["כׇּל־אֲשֶׁר","whatsoever"],
    ["צִוִּיתִיהָ","I have commanded her,"],
    ["אֶפְקֹד","I will visit"],
    ["עָלֶיהָ","her"],
    ["כְּכׇל־מַעֲשֶׂיהָ","according to all her works,"],
    ["בְּצָרָה","with affliction"],
    ["קָשָׁה","sore,"],
    ["בְּדֶבֶר","with pestilence,"],
    ["בְּמַגֵּפָה","with plague,"],
    ["בְּחֶרֶב","with sword,"],
    ["בְּנָקָם","with vengeance,"],
    ["בְּאֵשׁ","with fire."],
    ["אֹכֶלֶת׃","devouring"]
  ]},
  { num: "כז", words: [
    ["אַךְ","Nevertheless,"],
    ["תִּקָּרֵא","let it be read"],
    ["זֹאת","this"],
    ["בְּאׇזְנֶיהָ","to her ears,"],
    ["פַּעַם","once"],
    ["אַחַת","this"],
    ["כִּי","that"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["קִבַּלְתִּי","have accepted of"],
    ["קָרְבָּנָהּ","her offering;"],
    ["וְאִם","and if"],
    ["לֹא","not"],
    ["תֶחֱטָא","she sin"],
    ["עוֹד","no more"],
    ["לֹא","none of"],
    ["יָבֹאוּ","shall come"],
    ["עָלֶיהָ","upon her;"],
    ["הַדְּבָרִים","things"],
    ["הָאֵלֶּה׃","these"]
  ]},
  { num: "כח", words: [
    ["וַאֲבָרְכֶנָּה","And I will bless her"],
    ["בִּרְכוֹת","with blessings,"],
    ["וְאַרְבֶּה","and multiply"],
    ["בְּרָכוֹת","a multiplicity of blessings"],
    ["עָלֶיהָ","upon her,"],
    ["וְעַל","and upon"],
    ["דּוֹרוֹתֶיהָ","her generations"],
    ["לְעוֹלָם","forever"],
    ["וָעֶד","and ever,"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהֵיכֶם","your God."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc97_ch1Verses, 'dc97-ch1-verses');



var dc98_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["רֵעַי","my friends,"],
    ["אַל־תִּירָאוּ","fear not,"],
    ["יִנָּחֵם","let be comforted;"],
    ["לְבַבְכֶם","your hearts"],
    ["אָכֵן","yea,"],
    ["שִׂמְחוּ","rejoice"],
    ["תָמִיד","evermore,"],
    ["וּבְכֹל","and in everything"],
    ["הוֹדוּ׃","give thanks;"]
  ]},
  { num: "ב", words: [
    ["קַוּוֹ","Waiting patiently"],
    
    ["לַיהוָה","on the Lord,"],
    ["כִּי","for"],
    ["תְפִלּוֹתֵיכֶם","your prayers"],
    ["בָּאוּ","have entered"],
    ["בְאׇזְנֵי","into the ears of"],
    ["יְהוָה","the Lord"],
    ["צְבָאוֹת","of Sabaoth,"],
    ["וְנִכְתְּבוּ","and are recorded"],
    ["בַּחוֹתָם","with seal"],
    ["וּבָעֵדוּת","and testament—"],
    ["הַזֹּאת","this"],
    ["יְהוָה","the Lord"],
    ["נִשְׁבַּע","has sworn"],
    ["וְגָזַר","and decreed"],
    ["אֲשֶׁר־יִנָּתְנוּ׃","that they shall be granted."]
  ]},
  { num: "ג", words: [
    ["לָכֵן","Therefore,"],
    ["נוֹתֵן","he gives"],
    ["לָכֶם","unto you"],
    ["הַבְטָחָה","promise"],
    ["זֹאת","this"],
    ["בִּבְרִית","with a covenant"],
    ["נֶאֱמָנָה","immutable"],
    ["אֲשֶׁר־יְקֻיָּמוּ","that they shall be fulfilled;"],
    ["וְכׇל־אֲשֶׁר","and all things wherewith"],
    ["עֻנֵּיתֶם","you have been afflicted"],
    ["יַעֲשֶׂה","shall work"],
    ["יַחְדָּו","together"],
    ["לְטוֹבָתְכֶם","for your good,"],
    ["וּלְכָבוֹד","and to glory,"],
    ["שְׁמִי","my name's"],
    ["אָמַר","says"],
    ["יְהוָה׃","the Lord."]
  ]},
  { num: "ד", words: [
    ["וְעַתָּה","And now,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you"],
    ["עַל־דְּבַר","concerning"],
    ["חֻקֵּי","the laws of"],
    ["הָאָרֶץ","the land,"],
    ["רְצוֹנִי","it is my will"],
    ["אֲשֶׁר־עַמִּי","that my people"],
    ["יִשְׁמֹר","should observe"],
    ["לַעֲשׂוֹת","to do"],
    ["כֹּל","all things"],
    ["אֲשֶׁר","whatsoever"],
    ["אֲצַוֵּם׃","I command them."]
  ]},
  { num: "ה", words: [
    ["וְחֹק","And law of"],
    ["הָאָרֶץ","the land"],
    ["הַיְסוֹדִי","which is constitutional,"],
    ["הַתּוֹמֵךְ","supporting"],
    ["בְּעִקַּר","in the principle of"],
    ["הַחֵרוּת","that freedom"],
    ["לִשְׁמֹר","in maintaining"],
    ["זְכֻיּוֹת","rights"],
    ["וִיתָרוֹנוֹת","and privileges,"],
    ["הוּא","belongs"],
    ["לְכׇל־הָאָדָם","to all mankind,"],
    ["וְצָדֵק","and is justifiable"],
    ["לְפָנָי׃","before me."]
  ]},
  { num: "ו", words: [["לָכֵן","Therefore,"], ["אֲנִי","I,"], ["יְהוָה","the Lord,"], ["מַצְדִּיק","justify"], ["אֶתְכֶם","you,"], ["וְאֶת־אֲחֵיכֶם","and your brethren"], ["בִּכְנֵסִיָּתִי","of my church,"], ["לִהְיוֹת","in being"], ["רֵעִים","friends"], ["לַחֹק","to that law"], ["הַיְסוֹדִי","constitutional"], ["בָּאָרֶץ׃","of the land;"]]},
  { num: "ז", words: [
    ["וּבְנוֹגֵעַ","And as pertaining"],
    ["לְחֹק","to law of"],
    ["אָדָם","man,"],
    ["כׇּל־הַיֹּתֵר","whatsoever is more"],
    ["אוֹ","or"],
    ["הַפָּחוֹת","less"],
    ["מִזֶּה","than this,"],
    ["מִן","of"],
    ["הָרָע","evil"],
    ["בָּא׃","comes."]
  ]},
  { num: "ח", words: [
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהִים","God,"],
    ["עֲשִׂיתִיכֶם","make you"],
    ["חׇפְשִׁים","free,"],
    ["לָכֵן","therefore"],
    ["חׇפְשִׁים","free"],
    ["אַתֶּם","you are"],
    ["בֶּאֱמֶת","indeed;"],
    ["וְגַם","and also"],
    ["הַחֹק","the law"],
    ["עֹשֶׂה","makes"],
    ["אֶתְכֶם","you"],
    ["חׇפְשִׁים׃","free."]
  ]},
  { num: "ט", words: [
    ["אַךְ","Nevertheless,"],
    ["בִּמְשֹׁל","when rule"],
    ["רְשָׁעִים","the wicked"],
    ["הָעָם","the people"],
    ["יֶאֱנַח׃","mourn."]
  ]},
  { num: "י", words: [
    ["לָכֵן","Wherefore,"],
    ["אַנְשֵׁי","men of"],
    ["אֱמֶת","honest"],
    ["וַחֲכָמִים","and wise men"],
    ["יְבֻקְּשׁוּ","should be sought for"],
    ["הֵיטֵב","diligently,"],
    ["וְאַנְשֵׁי","and men of"],
    ["טוֹב","good"],
    ["וַחֲכָמִים","and wise men"],
    ["תִּשְׁמְרוּ","you should observe"],
    ["לְהַעֲמִיד","to uphold;"],
    ["וְאִם","otherwise"],
    ["אַיִן","if not"],
    ["כׇּל־הַפָּחוֹת","whatsoever is less"],
    ["מֵאֵלֶּה","than these"],
    ["מִן","of"],
    ["הָרָע","evil"],
    ["בָּא׃","comes."]
  ]},
  { num: "יא", words: [
    ["וַאֲנִי","And I"],
    ["נֹתֵן","give"],
    ["לָכֶם","unto you"],
    ["מִצְוָה","a commandment,"],
    ["לַעֲזֹב","that you shall forsake"],
    ["כׇּל־רָע","all evil"],
    ["וּלְדָבְקָה","and cleave"],
    ["בְכׇל־טוֹב","unto all good,"],
    ["וְלִחְיוֹת","that you shall live"],
    ["בְּכׇל־דָּבָר","by every word"],
    ["הַיֹּצֵא","which proceeds forth"],
    ["מִפִּי","out of the mouth of"],
    ["אֱלֹהִים׃","God."]
  ]},
  { num: "יב", words: [
    ["כִּי","For"],
    ["יִתֵּן","he will give"],
    ["לַנֶּאֱמָנִים","unto the faithful"],
    ["קַו","line"],
    ["לָקָו","upon line,"],
    ["צַו","precept"],
    ["לָצָו","upon precept;"],
    ["וַאֲנַסֶּכֶם","and I will try you and prove you"],
    ["בָּזֹאת׃","herewith."]
  ]},
  { num: "יג", words: [
    ["וְכׇל־הַמַּנִּיחַ","And whoso lays down"],
    ["נַפְשׁוֹ","his life"],
    ["לְמַעֲנִי","in my cause,"],
    ["לְמַעַן","for sake,"],
    ["שְׁמִי","my name's"],
    ["יִמְצָאֶנָּה","shall find it"],
    ["שֵׁנִית","again,"],
    ["אָכֵן","even"],
    ["חַיֵּי","life"],
    ["עוֹלָם׃","eternal."]
  ]},
  { num: "יד", words: [
    ["לָכֵן","Therefore,"],
    ["אַל־תִּירְאוּ","be not afraid"],
    ["מֵאֹיְבֵיכֶם","of your enemies,"],
    ["כִּי","for"],
    ["גָזַרְתִּי","I have decreed"],
    ["בְלִבִּי","in my heart,"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord,"],
    ["לְנַסּוֹתְכֶם","that I will prove you"],
    ["בְּכֹל","in all things,"],
    ["אִם","whether"],
    ["תַּעַמְדוּ","you will abide"],
    ["בִבְרִיתִי","in my covenant,"],
    ["עַד","even unto"],
    ["הַמָּוֶת","death,"],
    ["לְמַעַן","that"],
    ["תִּמָּצְאוּ","you may be found"],
    ["רְאוּיִים׃","worthy."]
  ]},
  { num: "טו", words: [
    ["כִּי","For"],
    ["אִם","if"],
    ["לֹא","not"],
    ["תַעַמְדוּ","you will abide"],
    ["בִבְרִיתִי","in my covenant"],
    ["אֵינְכֶם","you are not"],
    ["רְאוּיִים","worthy"],
    ["לִי׃","of me."]
  ]},
  { num: "טז", words: [
    ["לָכֵן","Therefore,"],
    ["מָאֲסוּ","renounce"],
    ["בַמִּלְחָמָה","war"],
    ["וְקִרְאוּ","and proclaim"],
    ["שָׁלוֹם","peace,"],
    ["וְדִרְשׁוּ","and seek"],
    ["הֵיטֵב","diligently"],
    ["לְהָשִׁיב","to turn"],
    ["לֵב","the hearts of"],
    ["בָּנִים","the children"],
    ["עַל־אֲבוֹתָם","to their fathers,"],
    ["וְלֵב","and the hearts of"],
    ["אָבוֹת","the fathers"],
    ["עַל־בָּנִים׃","to the children;"]
  ]},
  { num: "יז", words: [
    ["וְגַם","And again,"],
    ["לֵב","the hearts of"],
    ["הַיְּהוּדִים","the Jews"],
    ["אֶל־הַנְּבִיאִים","unto the prophets,"],
    ["וְלֵב","and the hearts of"],
    ["הַנְּבִיאִים","prophets"],
    ["אֶל־הַיְּהוּדִים","unto the Jews;"],
    ["פֶּן","lest"],
    ["אָבוֹא","I come"],
    ["וְהִכֵּיתִי","and smite"],
    ["אֶת־הָאָרֶץ","the earth"],
    ["חֵרֶם","with a curse,"],
    ["וְכׇל־בָּשָׂר","and all flesh"],
    ["יִכְלֶה","be consumed"],
    ["לְפָנָי׃","before me."]
  ]},
  { num: "יח", words: [
    ["אַל־יִבָּהֵל","Let not be troubled;"],
    ["לְבַבְכֶם","your hearts"],
    ["כִּי","for"],
    ["בְּבֵית","in house"],
    ["אָבִי","my Father's"],
    ["מְעוֹנוֹת","mansions"],
    ["רַבִּים","are many"],
    ["וַאֲכִין","and I have prepared"],
    ["לָכֶם","for you"],
    ["מָקוֹם","a place;"],
    ["וּבַאֲשֶׁר","and where"],
    ["אָבִי","my Father"],
    ["וָאֲנִי","and I"],
    ["שָׁם","am, there"],
    ["תִּהְיוּ","you shall be"],
    ["גַם","also"],
    ["אַתֶּם׃","you yourselves."]
  ]},
  { num: "יט", words: [["הִנֵּה","Behold,"], ["אֲנִי","I,"], ["יְהוָה","the Lord,"], ["אֵינִי","am not"], ["חָפֵץ","well pleased"], ["מֵרַבִּים","with many"], ["בַּכְּנֵסִיָּה","who are in the church"], ["בְּקִרְטְלַנְד׃","at Kirtland;"]]},
  { num: "כ", words: [
    ["כִּי","For"],
    ["אֵינָם","they do not"],
    ["עוֹזְבִים","forsake"],
    ["חַטֹּאתֵיהֶם","their sins,"],
    ["וְדַרְכֵיהֶם","and their ways,"],
    ["הָרָעִים","wicked"],
    ["גַּאֲוַת","the pride of"],
    ["לְבָבָם","their hearts,"],
    ["וּבִצְעָם","and their covetousness,"],
    ["וְכׇל־תּוֹעֲבוֹתֵיהֶם","and all their detestable things,"],
    ["וְאֵינָם","and not"],
    ["שׁוֹמְרִים","observe"],
    ["אֶת־דִּבְרֵי","the words of"],
    ["הַחׇכְמָה","wisdom"],
    ["וְחַיֵּי","and life of"],
    ["הָעוֹלָם","eternal"],
    ["אֲשֶׁר","which"],
    ["נָתַתִּי","I have given"],
    ["לָהֶם׃","unto them."]
  ]},
  { num: "כא", words: [
    ["אָמֵן","Verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["יְהוָה","the Lord,"],
    ["אֲיַסְּרֵם","will chasten them"],
    ["וְאֶעֱשֶׂה","and will do"],
    ["כִרְצוֹנִי","whatsoever I list,"],
    ["אִם","if"],
    ["לֹא","not"],
    ["יָשׁוּבוּ","they do repent"],
    ["וְיִשְׁמְרוּ","and observe"],
    ["כֹּל","all things"],
    ["אֲשֶׁר","whatsoever"],
    ["אָמַרְתִּי","I have said"],
    ["לָהֶם׃","unto them."]
  ]},
  { num: "כב", words: [
    ["וְעוֹד","And again"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["אִם","if"],
    ["תִּשְׁמְרוּ","you observe"],
    ["לַעֲשׂוֹת","to do"],
    ["כֹּל","all things"],
    ["אֲשֶׁר","whatsoever"],
    ["אֲצַוֶּה","I command you,"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["אָסִיר","will turn away"],
    ["מִכֶּם","from you"],
    ["כׇּל־חֵמָה","all wrath"],
    ["וָזַעַם","and indignation,"],
    ["וְשַׁעֲרֵי","and the gates of"],
    ["שְׁאוֹל","hell"],
    ["לֹא","not"],
    ["יִגְבְּרוּ","shall prevail"],
    ["עֲלֵיכֶם׃","against you."]
  ]},
  { num: "כג", words: [
    ["עַתָּה","Now,"],
    ["אֲדַבֵּר","I speak"],
    ["אֲלֵיכֶם","unto you"],
    ["עַל־אוֹדוֹת","concerning"],
    ["מִשְׁפְּחוֹתֵיכֶם","your families—"],
    ["אִם","if"],
    ["יַכּוּ","will smite"],
    ["אֲנָשִׁים","men"],
    ["אֶתְכֶם","you,"],
    ["אוֹ","or"],
    ["מִשְׁפְּחוֹתֵיכֶם","your families,"],
    ["פַּעַם","once,"],
    ["אַחַת","one"],
    ["וְתִשְׂאוּ","and you bear it"],
    ["בְּאֹרֶךְ","in length patience"],
    ["רוּחַ","of spirit"],
    ["וְלֹא","and not"],
    ["תָשִׁיבוּ","revile"],
    ["חֶרְפָּה","reproach against them,"],
    ["וְלֹא","neither"],
    ["תְבַקְּשׁוּ","seek"],
    ["נָקָם","revenge,"],
    ["תְּשֻׁלְּמוּ׃","you shall be rewarded;"]
  ]},
  { num: "כד", words: [
    ["אַךְ","But"],
    ["אִם","if"],
    ["לֹא","not"],
    ["תִשְׂאוּ","you bear it"],
    ["בְּאֹרֶךְ","in length patience"],
    ["רוּחַ","of spirit,"],
    ["יֵחָשֵׁב","it shall be accounted"],
    ["לָכֶם","unto you"],
    ["כְּמִדָּה","as a measure"],
    ["צֹדֶקֶת","just"],
    ["לָכֶם׃","unto you."]
  ]},
  { num: "כה", words: [
    ["וְעוֹד","And again,"],
    ["אִם","if"],
    ["יַכֶּה","shall smite"],
    ["אֹיִבְכֶם","your enemy"],
    ["אֶתְכֶם","you"],
    ["פַּעַם","time,"],
    ["שֵׁנִית","the second"],
    ["וְלֹא","and not"],
    ["תָשִׁיבוּ","you revile"],
    ["חֶרְפָּה","reproach"],
    ["לְאֹיִבְכֶם","against your enemy,"],
    ["וְתִשְׂאוּ","and bear it"],
    ["בְּאֹרֶךְ","in length patience"],
    ["רוּחַ","of spirit,"],
    ["שְׂכַרְכֶם","your reward"],
    ["מֵאָה","shall be an hundred-"],
    ["שְׁעָרִים׃","fold."]
  ]},
  { num: "כו", words: [
    ["וְעוֹד","And again,"],
    ["אִם","if"],
    ["יַכֶּה","he shall smite"],
    ["אֶתְכֶם","you"],
    ["פַּעַם","time,"],
    ["שְׁלִישִׁית","the third"],
    ["וְתִשְׂאוּ","and you bear it"],
    ["בְּאֹרֶךְ","in length patience"],
    ["רוּחַ","of spirit,"],
    ["יֻכְפַּל","shall be doubled"],
    ["שְׂכַרְכֶם","your reward"],
    ["אַרְבַּע","four-"],
    ["פְּעָמִים׃","fold;"]
  ]},
  { num: "כז", words: [
    ["וְשָׁלֹשׁ","And three"],
    ["הָעֵדֻיּוֹת","testimonies"],
    ["הָאֵלֶּה","these"],
    ["תַּעֲמֹדְנָה","shall stand"],
    ["עַל","against"],
    ["אֹיִבְכֶם","your enemy"],
    ["אִם","if"],
    ["לֹא","not"],
    ["יָשׁוּב","he repent,"],
    ["וְלֹא","and not"],
    ["יִמָּחוּ׃","shall be blotted out."]
  ]},
  { num: "כח", words: [
    ["וְעַתָּה","And now,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["אִם","if"],
    ["יִמָּלֵט","shall escape"],
    ["הָאוֹיֵב","that enemy"],
    ["הַהוּא","same"],
    ["מִנִּקְמָתִי","my vengeance,"],
    ["וְלֹא","that not"],
    ["יוּבָא","he be brought"],
    ["לְמִשְׁפָּט","into judgment"],
    ["לְפָנַי","before me,"],
    ["תִּרְאוּ","then you shall see to it"],
    ["לְהַזְהִיר","that you warn"],
    ["אוֹתוֹ","him"],
    ["בִּשְׁמִי","in my name,"],
    ["אֲשֶׁר־לֹא","that not"],
    ["יָבֹא","he come"],
    ["עוֹד","no more"],
    ["עֲלֵיכֶם","upon you,"],
    ["וְלֹא","neither"],
    ["עַל","upon"],
    ["מִשְׁפַּחְתְּכֶם","your family,"],
    ["אָכֵן","even"],
    ["בְּנֵי","the children of"],
    ["בְנֵיכֶם","your children"],
    ["עַד","unto"],
    ["הַדּוֹר","the generation."],
    ["הַשְּׁלִישִׁי","third"],
    ["וְהָרְבִיעִי׃","and fourth"]
  ]},
  { num: "כט", words: [
    ["וְאָז","And then,"],
    ["אִם","if"],
    ["יָבֹא","he shall come"],
    ["עֲלֵיכֶם","upon you"],
    ["אוֹ","or"],
    ["בְנֵיכֶם","your children,"],
    ["אוֹ","or"],
    ["בְּנֵי","the children of"],
    ["בְנֵיכֶם","your children"],
    ["עַד","unto"],
    ["הַדּוֹר","the generation,"],
    ["הַשְּׁלִישִׁי","third"],
    ["וְהָרְבִיעִי","and fourth"],
    ["הִנְנִי","behold I"],
    ["מָסַרְתִּי","have delivered"],
    ["אֹיִבְכֶם","your enemy"],
    ["בְּיֶדְכֶם׃","into your hands;"]
  ]},
  { num: "ל", words: [
    ["וְאָז","And then"],
    ["אִם","if"],
    ["תַּחְמֹל","you will spare"],
    ["עָלָיו","him,"],
    ["תְּשֻׁלַּם","you shall be rewarded"],
    ["עַל־צִדְקָתֶךָ","for your righteousness;"],
    ["וְגַם","and also"],
    ["בָּנֶיךָ","your children"],
    ["וּבְנֵי","and the children of"],
    ["בָנֶיךָ","your children"],
    ["עַד","unto"],
    ["הַדּוֹר","the generation."],
    ["הַשְּׁלִישִׁי","third"],
    ["וְהָרְבִיעִי׃","and fourth"]
  ]},
  { num: "לא", words: [
    ["אַךְ","Nevertheless,"],
    ["אֹיִבְךָ","your enemy"],
    ["בְיָדֶךָ","is in your hands;"],
    ["וְאִם","and if"],
    ["תְּשַׁלֵּם־לוֹ","you reward him"],
    ["כְּמַעֲשָׂיו","according to his works"],
    ["צָדַקְתָּ","you are justified;"],
    ["אִם","if"],
    ["בִּקֵּשׁ","he has sought"],
    ["נַפְשְׁךָ","your life,"],
    ["וְנַפְשְׁךָ","and your life"],
    ["בְּכַפּוֹ","is in his palm endangered"],
    ["מִמֶּנּוּ","by him,"],
    ["אֹיִבְךָ","your enemy"],
    ["בְיָדֶךָ","is in your hands"],
    ["וְצָדַקְתָּ׃","and you are justified."]
  ]},
  { num: "לב", words: [
    ["הִנֵּה","Behold,"],
    ["זֶה","this is"],
    ["הַחֹק","the law"],
    ["אֲשֶׁר","which"],
    ["נָתַתִּי","I gave"],
    ["לְעַבְדִּי","unto my servant"],
    ["נֶפִי","Nephi,"],
    ["וְלַאֲבוֹתֶיךָ","and your fathers,"],
    ["יוֹסֵף","Joseph,"],
    ["וְיַעֲקֹב","and Jacob,"],
    ["וְיִצְחָק","and Isaac,"],
    ["וְאַבְרָהָם","and Abraham,"],
    ["וּלְכׇל־נְבִיאַי","and all mine prophets"],
    ["וּשְׁלִיחַי","and apostles."],
    ["הַקַּדְמוֹנִים׃","ancient"]
  ]},
  { num: "לג", words: [
    ["וְעוֹד","And again,"],
    ["זֶה","this is"],
    ["הַחֹק","the law"],
    ["אֲשֶׁר","that"],
    ["נָתַתִּי","I gave"],
    ["אֲשֶׁר־לֹא","unto my ancients, that not"],
    ["יֵצְאוּ","they should go out"],
    ["לְמִלְחָמָה","unto battle"],
    ["עַל","against"],
    ["כׇּל־גּוֹי","any nation,"],
    ["מִשְׁפָּחָה","kindred,"],
    ["לָשׁוֹן","tongue,"],
    ["אוֹ","or"],
    ["עָם","people,"],
    ["כִּי","save"],
    ["אִם","that"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["צִוִּיתִים׃","commanded them."]
  ]},
  { num: "לד", words: [
    ["וְאִם","And if"],
    ["גּוֹי","any nation,"],
    ["לָשׁוֹן","tongue,"],
    ["אוֹ","or"],
    ["עָם","people"],
    ["יַכְרִיז","should proclaim"],
    ["מִלְחָמָה","war"],
    ["עֲלֵיהֶם","against them,"],
    ["יָרִימוּ","they should lift"],
    ["תְּחִלָּה","first"],
    ["נֵס","a standard of"],
    ["שָׁלוֹם","peace"],
    ["לָעָם","unto that people,"],
    ["הַהוּא","same"],
    ["לַגּוֹי","nation,"],
    ["אוֹ","or"],
    ["לַלָּשׁוֹן׃","tongue;"]
  ]},
  { num: "לה", words: [
    ["וְאִם","And if"],
    ["הָעָם","people"],
    ["הַהוּא","that"],
    ["לֹא","not"],
    ["קִבֵּל","did accept"],
    ["הַשָּׁלוֹם","the offering of peace,"],
    ["וְלֹא","neither"],
    ["בַפַּעַם","the time"],
    ["הַשֵּׁנִית","second"],
    ["וְלֹא","nor"],
    ["בַשְּׁלִישִׁית","the third,"],
    ["יָבִיאוּ","they should bring"],
    ["הָעֵדֻיּוֹת","testimonies"],
    ["הָאֵלֶּה","these"],
    ["לִפְנֵי","before"],
    ["יְהוָה׃","the Lord;"]
  ]},
  { num: "לו", words: [
    ["אָז","Then"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["אֶתֵּן","would give"],
    ["לָהֶם","unto them"],
    ["מִצְוָה","a commandment,"],
    ["לָצֵאת","in going out"],
    ["לְמִלְחָמָה","to battle"],
    ["עַל","against"],
    ["הַגּוֹי","nation,"],
    ["הַהוּא","that"],
    ["הַלָּשׁוֹן","tongue,"],
    ["אוֹ","or"],
    ["הָעָם׃","people."]
  ]},
  { num: "לז", words: [
    ["וַאֲנִי","and I"],
    ["יְהוָה","the Lord,"],
    ["אֶלָּחֵם","would fight"],
    ["מִלְחֲמוֹתֵיהֶם","their battles,"],
    ["וּמִלְחֲמוֹת","and the battles of"],
    ["בְּנֵיהֶם","their children,"],
    ["וּבְנֵי","and the children of"],
    ["בְנֵיהֶם","their children's,"],
    ["עַד","until"],
    ["הִנָּקְמָם","they had avenged themselves"],
    ["מִכׇּל־אֹיְבֵיהֶם","of all his enemies"],
    ["עַד","until"],
    ["הַדּוֹר","the generation."],
    ["הַשְּׁלִישִׁי","third"],
    ["וְהָרְבִיעִי׃","and fourth"]
  ]},
  { num: "לח", words: [
    ["הִנֵּה","Behold,"],
    ["זֹאת","this is"],
    ["מוֹפֵת","an ensample"],
    ["לְכׇל־הָעַמִּים","unto all people,"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהֵיכֶם","your God,"],
    ["לְהַצְדָּקָה","for justification"],
    ["לְפָנָי׃","before me."]
  ]},
  { num: "לט", words: [
    ["וְעוֹד","And again,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["אִם","if"],
    ["אַחֲרֵי","after"],
    ["בוֹא","has come"],
    ["אֹיִבְכֶם","your enemy"],
    ["עֲלֵיכֶם","upon you"],
    ["בַּפַּעַם","the time"],
    ["הָרִאשׁוֹנָה","first,"],
    ["יָשׁוּב","he repent"],
    ["וּבָא","and come"],
    ["אֲלֵיכֶם","unto you"],
    ["מְבַקֵּשׁ","praying"],
    ["סְלִיחָתְכֶם","your forgiveness,"],
    ["תִּסְלְחוּ","you shall forgive"],
    ["לוֹ","him,"],
    ["וְלֹא","and not"],
    ["זֹאת","this"],
    ["עוֹד","shall hold it any more"],
    ["לְעֵדוּת","as a testimony"],
    ["עַל׃","against your enemy—"]
  ]},
  { num: "מ", words: [
    ["וְכֵן","And so on"],
    ["בַּפַּעַם","unto the time"],
    ["הַשֵּׁנִית","second"],
    ["וְהַשְּׁלִישִׁית","and third;"],
    ["וּבְכׇל־פַּעַם","and as oft as"],
    ["אֲשֶׁר־יָשׁוּב","repents"],
    ["אֹיִבְכֶם","your enemy"],
    ["מִפִּשְׁעוֹ","of the trespass"],
    ["אֲשֶׁר","wherewith"],
    ["פָּשַׁע","he has trespassed"],
    ["בָּכֶם","against you,"],
    ["תִּסְלְחוּ","you shall forgive"],
    ["לוֹ","him,"],
    ["עַד","until"],
    ["שִׁבְעִים","seventy"],
    ["פְּעָמִים","times"],
    ["שֶׁבַע׃","seven."]
  ]},
  { num: "מא", words: [
    ["וְאִם","And if"],
    ["יִפְשַׁע","he trespass"],
    ["בָּכֶם","against you"],
    ["וְלֹא","and not"],
    ["יָשׁוּב","repent"],
    ["בַּפַּעַם","the time,"],
    ["הָרִאשׁוֹנָה","first"],
    ["בְּכׇל","nevertheless"],
    ["זֹאת","this"],
    ["תִּסְלְחוּ","you shall forgive"],
    ["לוֹ׃","him."]
  ]},
  { num: "מב", words: [
    ["וְאִם","And if"],
    ["יִפְשַׁע","he trespass"],
    ["בָּכֶם","against you"],
    ["בַּפַּעַם","the time,"],
    ["הַשֵּׁנִית","second"],
    ["וְלֹא","and not"],
    ["יָשׁוּב","repent,"],
    ["בְּכׇל","nevertheless"],
    ["זֹאת","this"],
    ["תִּסְלְחוּ","you shall forgive"],
    ["לוֹ׃","him."]
  ]},
  { num: "מג", words: [
    ["וְאִם","And if"],
    ["יִפְשַׁע","he trespass"],
    ["בָּכֶם","against you"],
    ["בַּפַּעַם","the time,"],
    ["הַשְּׁלִישִׁית","third"],
    ["וְלֹא","and not"],
    ["יָשׁוּב","repent,"],
    ["גַּם","also"],
    ["תִּסְלְחוּ","you shall forgive"],
    ["לוֹ׃","him."]
  ]},
  { num: "מד", words: [
    ["אַךְ","But"],
    ["אִם","if"],
    ["יִפְשַׁע","he trespass"],
    ["בָּכֶם","against you"],
    ["בַּפַּעַם","the time"],
    ["הָרְבִיעִית","fourth"],
    ["לֹא","not"],
    ["תִסְלְחוּ","you shall forgive"],
    ["לוֹ","him,"],
    ["כִּי","but"],
    ["אִם","rather"],
    ["תָּבִיאוּ","shall bring"],
    ["הָעֵדֻיּוֹת","testimonies"],
    ["הָאֵלֶּה","these"],
    ["לִפְנֵי","before"],
    ["יְהוָה","the Lord;"],
    ["וְלֹא","and not"],
    ["עַד","until"],
    ["יָשׁוּב","they shall be blotted out"],
    ["וִישַׁלֵּם","he repent and reward you"],
    ["לָכֶם","unto you"],
    ["אַרְבַּע","four-"],
    ["פְּעָמִים","fold"],
    ["בְּכֹל","in all things"],
    ["אֲשֶׁר","wherewith"],
    ["פָּשַׁע","he has trespassed"],
    ["בָּכֶם׃","against you."]
  ]},
  { num: "מה", words: [
    ["וְאִם","And if"],
    ["יַעֲשֶׂה","he do"],
    ["כֵן","this,"],
    ["תִּסְלְחוּ","you shall forgive"],
    ["לוֹ","him"],
    ["בְּכׇל־לְבַבְכֶם","with all your heart;"],
    ["וְאִם","and if"],
    ["לֹא","not"],
    ["יַעֲשֶׂה","he do"],
    ["כֵן","this,"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["אֶנְקֹם","will avenge you"],
    ["לָכֶם","unto you"],
    ["מֵאֹיִבְכֶם","of your enemy"],
    ["מֵאָה","an hundred-"],
    ["שְׁעָרִים׃","fold;"]
  ]},
  { num: "מו", words: [
    ["וְעַל","And upon"],
    ["בָּנָיו","his children,"],
    ["וְעַל","and upon"],
    ["בְּנֵי","the children of"],
    ["בָנָיו","his children"],
    ["מִכׇּל־שֹׂנְאַי","of all them that hate me,"],
    ["עַד","unto"],
    ["הַדּוֹר","the generation."],
    ["הַשְּׁלִישִׁי","third"],
    ["וְהָרְבִיעִי׃","and fourth"]
  ]},
  { num: "מז", words: [
    ["אַךְ","But"],
    ["אִם","if"],
    ["יָשׁוּבוּ","shall repent,"],
    ["הַבָּנִים","the children"],
    ["אוֹ","or"],
    ["בְּנֵי","the children of"],
    ["הַבָּנִים","the children,"],
    ["וְשָׁבוּ","and turn"],
    ["אֶל־יְהוָה","to the Lord"],
    ["אֱלֹהֵיהֶם","their God,"],
    ["בְּכׇל־לְבָבָם","with all their hearts"],
    ["וּבְכׇל־כֹּחָם","and with all their might,"],
    ["וּבְכׇל־נַפְשָׁם","mind, and strength,"],
    ["וְשִׁלְּמוּ","and restore"],
    ["אַרְבַּע","four-"],
    ["פְּעָמִים","fold"],
    ["עַל","for"],
    ["כׇּל־פִּשְׁעֵיהֶם","all their trespasses"],
    ["אֲשֶׁר","wherewith"],
    ["פָּשְׁעוּ","they have trespassed,"],
    ["אוֹ","or"],
    ["אֲשֶׁר","wherewith"],
    ["פָּשְׁעוּ","have trespassed"],
    ["אֲבוֹתֵיהֶם","their fathers,"],
    ["אוֹ","or"],
    ["אֲבוֹת","fathers of"],
    ["אֲבוֹתֵיהֶם","their fathers,"],
    ["אָז","then"],
    ["יָשׁוּב׃","indignation shall be turned away;"]
  ]},
  { num: "מח", words: [
    ["וְנָקָם","And vengeance"],
    ["לֹא","not"],
    ["יָבֹא","shall come"],
    ["עוֹד","more"],
    ["עֲלֵיהֶם","upon them,"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord"],
    ["אֱלֹהֵיכֶם","your God,"],
    ["וּפִשְׁעֵיהֶם","and their trespasses"],
    ["לֹא","not"],
    ["יוּבְאוּ","shall be brought"],
    ["עוֹד","any more"],
    ["לְעֵדוּת","as a testimony"],
    ["לִפְנֵי","before"],
    ["יְהוָה","the Lord"],
    ["עֲלֵיהֶם","against them."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc98_ch1Verses, 'dc98-ch1-verses');



var dc99_ch1Verses = [
  { num: "א", words: [
    ["הִנֵּה","Behold,"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord"],
    ["לְעַבְדִּי","unto my servant"],
    ["ג׳וֹן","John"],
    ["מֶרְדּוֹק","Murdock—"],
    ["נִקְרֵאתָ","you are called"],
    ["לָלֶכֶת","to go"],
    ["לְאַרְצוֹת","into the countries of"],
    ["הַמִּזְרָח","the east"],
    ["מִבַּיִת","from house"],
    ["לְבַיִת","to house,"],
    ["מִכְּפָר","from village"],
    ["לִכְפָר","to village,"],
    ["וּמֵעִיר","and from city"],
    ["לָעִיר","to city,"],
    ["לְהַכְרִיז","to proclaim"],
    ["בְּשׂוֹרָתִי","mine gospel"],
    ["הַנִּצְחִית","everlasting"],
    ["לְיוֹשְׁבֵיהֶן","unto the inhabitants thereof,"],
    ["בְּתוֹךְ","in the midst of"],
    ["רְדִיפָה","persecution"],
    ["וְרִשְׁעָה׃","and wickedness."]
  ]},
  { num: "ב", words: [
    ["וְהַמְקַבֵּל","And who receives"],
    ["אֶתְכֶם","you"],
    ["אוֹתִי","me"],
    ["מְקַבֵּל","receives;"],
    ["וְיִהְיֶה","and shall be"],
    ["לְךָ","unto you"],
    ["כֹּחַ","power"],
    ["לְהַכְרִיז","to declare"],
    ["דְּבָרִי","my word"],
    ["בְּהוֹכָחַת","in the demonstration of"],
    ["רוּחַ","the Spirit"],
    ["קָדְשִׁי׃","of my Holy."]
  ]},
  { num: "ג", words: [
    ["וְהַמְקַבֵּל","And who receives"],
    ["אֶתְכֶם","you"],
    ["כְּיֶלֶד","as a child,"],
    ["קָטָן","little"],
    ["מְקַבֵּל","receives"],
    ["מַלְכוּתִי","my kingdom;"],
    ["וְאַשְׁרֵיהֶם","and blessed are they,"],
    ["כִּי","for"],
    ["יַשִּׂיגוּ","they shall obtain"],
    ["רַחֲמִים׃","mercy."]
  ]},
  { num: "ד", words: [
    ["וְהַמֹּאֵס","And whoso rejects"],
    ["אֶתְכֶם","you"],
    ["יִמָּאֵס","shall be rejected"],
    ["מֵאָבִי","of my Father"],
    ["וּמִבֵּיתוֹ","and his house;"],
    ["וּנְעַרְתֶּם","and you shall cleanse"],
    ["רַגְלֵיכֶם","your feet"],
    ["בַּמִּסְתָּרִים","in the secret places"],
    ["בַּדֶּרֶךְ","by the way"],
    ["לְעֵדוּת","for a testimony"],
    ["עֲלֵיהֶם׃","against them."]
  ]},
  { num: "ה", words: [
    ["וְהִנֵּה","And behold, and lo,"],
    ["בָא","come"],
    ["אֲנִי","I"],
    ["מְהֵרָה","quickly"],
    ["לְמִשְׁפָּט","to judgment,"],
    ["לְהוֹכִיחַ","to convince"],
    ["הַכֹּל","all"],
    ["עַל","of"],
    ["מַעֲשֵׂיהֶם","their deeds"],
    ["הָרְשָׁעִים","ungodly"],
    ["אֲשֶׁר","which"],
    ["עָשׂוּ","they have committed"],
    ["נֶגְדִּי","against me,"],
    ["כַּכָּתוּב","as it is written"],
    ["עָלַי","of me"],
    ["בִּמְגִלַּת","in the volume of"],
    ["הַסֵּפֶר׃","the book."]
  ]},
  { num: "ו", words: [
    ["וְעַתָּה","And now,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לְךָ","unto you,"],
    ["אֵין","that it is not"],
    ["רָאוּי","expedient"],
    ["אֲשֶׁר־תֵּלֵךְ","that you should go"],
    ["עַד","until"],
    ["אֲשֶׁר","that"],
    ["יְכֻלְכְּלוּ","are provided for"],
    ["יְלָדֶיךָ","your children,"],
    ["וְיִשָּׁלְחוּ","and sent up"],
    ["בְּטוּב","kindly"],
    ["אֶל־הַפָּקִיד","unto the bishop"],
    ["בְּצִיּוֹן׃","of Zion."]
  ]},
  { num: "ז", words: [
    ["וְאַחֲרֵי","And after"],
    ["שָׁנִים","years"],
    ["אֲחָדוֹת","a few,"],
    ["אִם","if"],
    ["תַּחְפֹּץ","you desire"],
    ["מִמֶּנִּי","of me,"],
    ["תּוּכַל","you may"],
    ["לַעֲלוֹת","go up"],
    ["גַּם","also"],
    ["אַתָּה","you"],
    ["אֶל־הָאָרֶץ","unto the land,"],
    ["הַטּוֹבָה","goodly"],
    ["לָרֶשֶׁת","to possess"],
    ["נַחֲלָתֶךָ׃","your inheritance;"]
  ]},
  { num: "ח", words: [
    ["וְאִם","Otherwise"],
    ["לֹא","not"],
    ["תּוֹסִיף","you shall continue"],
    ["לְהַכְרִיז","proclaiming"],
    ["בְּשׂוֹרָתִי","my gospel"],
    ["עַד","until"],
    ["תִּלָּקַח","you be taken."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc99_ch1Verses, 'dc99-ch1-verses');



var dc100_ch1Verses = [
  { num: "א", words: [
    ["אָמֵן","Verily,"],
    ["כֹּה","thus"],
    ["אָמַר","says"],
    ["יְהוָה","the Lord"],
    ["לָכֶם","unto you,"],
    ["רֵעַי","my friends"],
    ["סִידְנִי","Sidney"],
    ["וְיוֹסֵף","and Joseph,"],
    ["מִשְׁפְּחוֹתֵיכֶם","your families"],
    ["שָׁלוֹם","are well;"],
    ["בְּיָדִי","in my hands"],
    ["הֵם","they are,"],
    ["וְאֶעֱשֶׂה","and I will do"],
    ["לָהֶם","with them"],
    ["כַּטּוֹב","as seems good;"],
    ["בְּעֵינָי","me"],
    ["כִּי","for"],
    ["בִי","in me"],
    ["כׇּל־הַכֹּחַ׃","there is all power."]
  ]},
  { num: "ב", words: [
    ["לָכֵן","Therefore,"],
    ["לְכוּ","follow"],
    ["אַחֲרָי","me,"],
    ["וְשִׁמְעוּ","and listen to"],
    ["לָעֵצָה","the counsel"],
    ["אֲשֶׁר","which"],
    ["אֶתֵּן","I shall give"],
    ["לָכֶם׃","unto you."]
  ]},
  { num: "ג", words: [
    ["הִנֵּה","Behold, and lo,"],
    ["יֶשׁ־לִי","I have"],
    ["עַם","people"],
    ["רַב","much"],
    ["בַּמָּקוֹם","in place,"],
    ["הַזֶּה","this"],
    ["בַּסְּבִיבוֹת","in the regions round about;"],
    ["וּפֶתַח","and a door"],
    ["גָּדוֹל","effectual great"],
    ["יִפָּתַח","shall be opened"],
    ["בַּסְּבִיבוֹת","in the regions round about"],
    ["בָּאָרֶץ","in land."],
    ["הַמִּזְרָחִית","eastern"],
    ["הַזֹּאת׃","this"]
  ]},
  { num: "ד", words: [
    ["לָכֵן","Therefore,"],
    ["אֲנִי","I,"],
    ["יְהוָה","the Lord,"],
    ["הִנַּחְתִּי","have suffered"],
    ["אֶתְכֶם","you"],
    ["לָבוֹא","to come"],
    ["אֶל־הַמָּקוֹם","unto place;"],
    ["הַזֶּה","this"],
    ["כִּי","for"],
    ["כֵן","thus"],
    ["טוֹב","expedient"],
    ["הָיָה","it was"],
    ["בְעֵינַי","in me"],
    ["לִישׁוּעַת","for the salvation of"],
    ["נְפָשׁוֹת׃","souls."]
  ]},
  { num: "ה", words: [
    ["לָכֵן","Therefore,"],
    ["אָמֵן","verily"],
    ["אֲנִי","I"],
    ["אֹמֵר","say"],
    ["לָכֶם","unto you,"],
    ["הָרִימוּ","lift up"],
    ["קוֹלְכֶם","your voices"],
    ["אֶל־הָעָם","unto people;"],
    ["הַזֶּה","this"],
    ["דַּבְּרוּ","speak"],
    ["הַמַּחֲשָׁבוֹת","the thoughts"],
    ["אֲשֶׁר","that"],
    ["אָשִׂים","I shall put"],
    ["בְּלִבְּכֶם","into your hearts,"],
    ["וְלֹא","and not"],
    ["תֵבֹשׁוּ","you shall be confounded"],
    ["לִפְנֵי","before"],
    ["אֲנָשִׁים׃","men;"]
  ]},
  { num: "ו", words: [
    ["כִּי","For"],
    ["יִנָּתֵן","it shall be given"],
    ["לָכֶם","you"],
    ["בַּשָּׁעָה","in the hour"],
    ["הַהִיא","that very,"],
    ["אָכֵן","yea,"],
    ["בָּרֶגַע","in the moment"],
    ["הַהוּא","that very,"],
    ["מַה","what"],
    ["תֹּאמֵרוּ׃","you shall say."]
  ]},
  { num: "ז", words: [
    ["אַךְ","But"],
    ["מִצְוָה","a commandment"],
    ["נוֹתֵן","I give"],
    ["לָכֶם","unto you,"],
    ["אֲשֶׁר־כֹּל","that whatsoever"],
    ["אֲשֶׁר","thing"],
    ["תַּכְרִיזוּ","you shall declare"],
    ["תַּכְרִיזוּ","you shall declare"],
    ["בִשְׁמִי","in my name,"],
    ["בִּכְבֹד","in solemnity of"],
    ["לֵב","heart,"],
    ["בְּרוּחַ","in the spirit of"],
    ["עֲנָוָה","meekness,"],
    ["בְּכׇל־דָּבָר׃","in all things."]
  ]},
  { num: "ח", words: [["וְנוֹתֵן","And I give"], ["לָכֶם","unto you"], ["הַבְטָחָה","promise,"], ["זֹאת","this"], ["אֲשֶׁר־כְּפִי","that inasmuch as"], ["אֲשֶׁר־תַּעֲשׂוּ","you do"], ["כֵן","this,"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["תִּשָּׁפֵךְ","shall be shed forth"], ["לְהָעִיד","in bearing record"], ["עַל","unto"], ["כֹּל","all things"], ["אֲשֶׁר","whatsoever"], ["תֹּאמְרוּ׃","you shall say."]]},
  { num: "ט", words: [
    ["וְטוֹב","And it is expedient"],
    ["בְּעֵינַי","in me"],
    ["אֲשֶׁר־אַתָּה","that you,"],
    ["עַבְדִּי","my servant"],
    ["סִידְנִי","Sidney,"],
    ["תִּהְיֶה","should be"],
    ["לְפֶה","a spokesman"],
    ["לָעָם","unto people;"],
    ["הַזֶּה","this"],
    ["אָכֵן","yea, verily,"],
    ["אֲסַמֵּךְ","I will ordain"],
    ["אוֹתְךָ","you"],
    ["לַמִּשְׂרָה","unto calling,"],
    ["הַזֹּאת","this"],
    ["לִהְיוֹת","even to be"],
    ["לְפֶה","a spokesman"],
    ["לְעַבְדִּי","unto my servant"],
    ["יוֹסֵף׃","Joseph."]
  ]},
  { num: "י", words: [
    ["וְאֶתֵּן","And I will give"],
    ["לוֹ","unto him"],
    ["כֹחַ","power"],
    ["לִהְיוֹת","to be"],
    ["גִּבּוֹר","mighty"],
    ["בְּעֵדוּת׃","in testimony."]
  ]},
  { num: "יא", words: [["וְאֶתֵּן","And I will give"], ["לְךָ","unto you"], ["כֹחַ","power"], ["לִהְיוֹת","to be"], ["גִּבּוֹר","mighty"], ["בְּפָרֵשׁ","in expounding"], ["כׇּל־כִּתְבֵי","all the scriptures of"], ["הַקֹּדֶשׁ","the holy"], ["לְמַעַן","that"], ["תִּהְיֶה","you may be"], ["לוֹ","unto him"], ["לְפֶה","a spokesman,"], ["וְהוּא","and he"], ["יִהְיֶה","shall be"], ["לְךָ","unto you"], ["לְמַגִּיד","a revelator,"], ["לָדַעַת","that you may know"], ["בְּבִטָּחוֹן","the certainty of"], ["כׇּל־הַדְּבָרִים","all things"], ["הַנּוֹגְעִים","pertaining to"], ["לְמַלְכוּתִי","my kingdom"], ["בָּאָרֶץ׃","on the earth."]]},
  { num: "יב", words: [
    ["לָכֵן","Therefore,"],
    ["הוֹסִיפוּ","continue"],
    ["דַּרְכְּכֶם","your journey"],
    ["וְיִשְׂמַח","and let rejoice;"],
    ["לְבַבְכֶם","your hearts"],
    ["כִּי","for"],
    ["הִנֵּה","behold, and lo,"],
    ["אֲנִי","I"],
    ["אִתְּכֶם","am with you"],
    ["עַד","even unto"],
    ["הַקֵּץ׃","the end."]
  ]},
  { num: "יג", words: [
    ["וְעַתָּה","And now"],
    ["נוֹתֵן","I give"],
    ["לָכֶם","unto you"],
    ["דָּבָר","a word"],
    ["עַל־אוֹדוֹת","concerning"],
    ["צִיּוֹן","Zion."],
    ["צִיּוֹן","Zion"],
    ["תִּגָּאֵל","shall be redeemed,"],
    ["אַף","although"],
    ["כִּי","indeed"],
    ["נוֹסְרָה","she is chastened"],
    ["לַמִּצְעָר׃","for a little season."],
    
  ]},
  { num: "יד", words: [["אֲחֵיכֶם","Your brethren,"], ["עֲבָדַי","my servants"], ["אוֹרְסוֹן","Orson"], ["הַיְד","Hyde"], ["וְג׳וֹן","and John"], ["גּוּלְד","and John Gould,"], ["בְּיָדִי","are in my hands;"], ["וּכְפִי","and inasmuch as"], ["אֲשֶׁר־יִשְׁמְרוּ","they keep"], ["מִצְוֹתַי","my commandments"], ["יִוָּשֵׁעוּ׃","they shall be saved."]]},
  { num: "טו", words: [["לָכֵן","Therefore,"], ["יִנָּחֵם","let be comforted;"], ["לְבַבְכֶם","your hearts"], ["כִּי","for"], ["הַכֹּל","all things"], ["יַעֲשֶׂה","shall work"], ["יַחְדָּו","together"], ["לְטוֹבַת","for good to"], ["הַהוֹלְכִים","them that walk"], ["בְּיֹשֶׁר","uprightly,"], ["וּלְקִדּוּשׁ","and to the sanctification of"], ["הַכְּנֵסִיָּה׃","the church."]]},
  { num: "טז", words: [
    ["כִּי","For"],
    ["אָקִים","I will raise up"],
    ["לִי","unto myself"],
    ["עַם","a people"],
    ["טָהוֹר","pure,"],
    ["אֲשֶׁר","that"],
    ["יַעַבְדֵנִי","will serve me"],
    ["בְּצֶדֶק׃","in righteousness;"]
  ]},
  { num: "יז", words: [
    ["וְכׇל־הַקּוֹרֵא","And all that call"],
    ["בְּשֵׁם","upon the name of"],
    ["יְהוָה","the Lord,"],
    ["וְשׁוֹמֵר","and keep"],
    ["מִצְוֹתָיו","his commandments,"],
    ["יִוָּשֵׁעַ","shall be saved."],
    ["כֵּן","Even"],
    ["יְהִי","so."],
    ["אָמֵן׃","Amen."]
  ]}
];
renderVerseSet(dc100_ch1Verses, 'dc100-ch1-verses');



})();
