// dc_verses/dc_intro.js — D&C Introduction verse data
// Hebrew interlinear translation of the Introduction to the Doctrine and Covenants
(function() {
var dcIntro_ch1Verses = [
  // Paragraph 1: The D&C is a collection of divine revelations
  { num:"א", words:[["תּוֹרָה","the-Doctrine"],["וּבְרִיתוֹת","and-Covenants"],["הִיא","is"],["אֹסֶף","a-collection-of"],["גִּלּוּיִים","revelations"],["אֱלֹהִיִּים","divine"],["וְהַכְרָזוֹת","and-declarations"],["מֻשְׁרוֹת","inspired"],["שֶׁנִּתְּנוּ","given"],["לִכְיוּן","for-the-establishment"],["וּלְהַסְדָּרַת","and-regulation-of"],["מַלְכוּת","the-kingdom-of"],["אֱלֹהִים","God"],["עַל","on"],["הָאָרֶץ","the-earth"],["בְּאַחֲרִית","in-the-last"],["הַיָּמִים","days"],["׃",""]] },
  // Paragraph 2: Messages for all mankind
  { num:"ב", words:[["אַף","although"],["שֶׁרֹב","most-of"],["הַסְּעִיפִים","the-sections"],["מְכֻוָּנִים","are-directed"],["לְחַבְרֵי","to-members-of"],["כְּנֶסִיַּת","The-Church-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","Christ"],["שֶׁל","of"],["קְדוֹשֵׁי","Latter-day"],["אַחֲרִית","Saints"],["הַיָּמִים","[Saints]"],["הַמְּסָרִים","the-messages"],["הָאַזְהָרוֹת","warnings"],["וְהַמּוּסָרִים","and-exhortations"],["הֵם","are"],["לְטוֹבַת","for-the-benefit-of"],["כׇּל","all"],["בְּנֵי","mankind"],["הָאָדָם","and-contain"],["וְכוֹלְלִים","an-invitation"],["הַזְמָנָה","to-all"],["לְכׇל","people"],["בְּנֵי","everywhere"],["אָדָם","to-hear"],["בְּכׇל","the-voice-of"],["מָקוֹם","the-Lord"],["לִשְׁמֹעַ","Jesus"],["אֶת","Christ"],["קוֹל","[Christ]"],["יְהוָה","[Christ]"],["יֵשׁוּעַ","[Christ]"],["הַמָּשִׁיחַ","[Christ]"],["׃",""]] },
  // Paragraph 3: Received through Joseph Smith
  { num:"ג", words:[["רֹב","most-of"],["הַגִּלּוּיִים","the-revelations"],["בְּאֹסֶף","in-this-compilation"],["זֶה","were-received"],["נִתְקַבְּלוּ","through"],["עַל","Joseph"],["יְדֵי","Smith"],["יוֹסֵף","Jr"],["סְמִית","the-first"],["בֶּן","prophet"],["הַנָּבִיא","and-president-of"],["הָרִאשׁוֹן","The-Church-of"],["וְנָשִׂיא","Jesus"],["כְּנֶסִיַּת","Christ"],["יֵשׁוּעַ","of"],["הַמָּשִׁיחַ","Latter-day"],["שֶׁל","Saints"],["קְדוֹשֵׁי","others"],["אַחֲרִית","were-issued"],["הַיָּמִים","through"],["אֲחֵרִים","some-of"],["הוּצְאוּ","his"],["עַל","successors"],["יְדֵי","in"],["מִקְצָת","the"],["יוֹרְשָׁיו","Presidency"],["בָּנְשִׂיאוּת","[Presidency]"],["׃",""]] },
  // Paragraph 4: Unique among standard works
  { num:"ד", words:[["סֵפֶר","the-book-of"],["תּוֹרָה","Doctrine"],["וּבְרִיתוֹת","and-Covenants"],["הוּא","is"],["אֶחָד","one-of"],["מֵהַכִּתְבֵי","the-standard-works-of"],["הַקֹּדֶשׁ","the-Church"],["שֶׁל","in-company-with"],["הַכְּנֵסִיָּה","the-Holy"],["יַחַד","Bible"],["עִם","the-Book-of"],["הַמִּקְרָא","Mormon"],["הַקָּדוֹשׁ","and"],["סֵפֶר","the-Pearl-of"],["מוֹרְמוֹן","Great"],["וּפְנִינַת","Price"],["הַמְּחִיר","however"],["הַגָּדוֹל","[however]"],["אוּלָם","the-Doctrine"],["תּוֹרָה","and-Covenants"],["וּבְרִיתוֹת","is-unique"],["מְיֻחָד","because"],["כִּי","it-is-not"],["אֵינוֹ","a-translation-of"],["תַּרְגּוּם","an-ancient"],["שֶׁל","document"],["מִסְמָךְ","but"],["עַתִּיק","is-of"],["אֶלָּא","modern"],["מִמָּקוֹר","origin"],["מוֹדֶרְנִי","[origin]"],["׃",""]] },
  // Paragraph 5: Given by God through His chosen prophets
  { num:"ה", words:[["וְנִתַּן","and-was-given-of"],["מֵאֱלֹהִים","God"],["עַל","through"],["יְדֵי","His"],["נְבִיאָיו","chosen"],["הַנִּבְחָרִים","prophets"],["לְהָשָׁבַת","for-the-restoration-of"],["עֲבוֹדָתוֹ","His-work"],["הַקְּדוֹשָׁה","holy"],["וְלִכְיוּן","and-the-establishment-of"],["מַלְכוּת","the-kingdom-of"],["אֱלֹהִים","God"],["עַל","on"],["הָאָרֶץ","the-earth"],["בַּיָּמִים","in-these"],["הָאֵלֶּה","days"],["׃",""]] },
  // Paragraph 6: The voice of the Lord Jesus Christ
  { num:"ו", words:[["בַּגִּלּוּיִים","in-the-revelations"],["שׁוֹמְעִים","one-hears"],["אֶת","[ACC]"],["הַקּוֹל","the-voice"],["הָרַךְ","the-tender"],["אַךְ","but"],["הַנֶּחֱרָץ","firm"],["שֶׁל","of"],["יְהוָה","the-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","Christ"],["הַמְּדַבֵּר","speaking"],["מֵחָדָשׁ","anew"],["בִּתְקוּפַת","in-the-dispensation-of"],["מְלֹאת","the-fulness-of"],["הַזְּמַנִּים","times"],["וְהַמְּלָאכָה","and-the-work"],["הַנִּפְתַּחַת","that-is-initiated"],["בָּזֹאת","herein"],["הִיא","is"],["מַכְשִׁירָה","preparatory"],["לְבִיאָתוֹ","to-His-coming"],["הַשְּׁנִיָּה","Second"],["׃",""]] },
  // Paragraph 7: Joseph Smith born Dec 23, 1805
  { num:"ז", words:[["יוֹסֵף","Joseph"],["סְמִית","Smith"],["בֶּן","Jr"],["נוֹלַד","was-born"],["בְּעֶשְׂרִים","on-the-twenty-"],["וּשְׁלוֹשָׁה","third-of"],["בְּדֶצֶמְבֶּר","December"],["אֶלֶף","one-thousand"],["שְׁמוֹנֶה","eight"],["מֵאוֹת","hundred"],["וְחָמֵשׁ","and-five"],["בְּשָׁרוֹן","in-Sharon"],["מְחוֹז","County-of"],["וִינְדְזוֹר","Windsor"],["וֶרְמוֹנְט","Vermont"],["בִּנְעוּרָיו","during-his-early-life"],["עָבַר","he-moved"],["עִם","with"],["מִשְׁפַּחְתּוֹ","his-family"],["לְמַנְצֶ׳סְטֶר","to-Manchester"],["שֶׁבְּמַעֲרַב","in-western"],["נְיוּ","New"],["יוֹרְק","York"],["׃",""]] },
  // Paragraph 8: First Vision, spring 1820
  { num:"ח", words:[["בְּאָבִיב","in-the-spring-of"],["שְׁנַת","the-year"],["אֶלֶף","one-thousand"],["שְׁמוֹנֶה","eight"],["מֵאוֹת","hundred"],["וְעֶשְׂרִים","and-twenty"],["בִּהְיוֹתוֹ","when-he-was"],["בֶּן","the-son-of"],["אַרְבַּע","fourteen"],["עֶשְׂרֵה","[fourteen]"],["שָׁנָה","years-of-age"],["חָוָה","he-experienced"],["אֶת","[ACC]"],["חֲזוֹנוֹ","his-vision"],["הָרִאשׁוֹן","first"],["אֲשֶׁר","in-which"],["בּוֹ","he-was-visited"],["נִפְקַד","in-person"],["בֶּאֱלֹהִים","by-God"],["הָאָב","the-Father"],["הַנִּצְחִי","the-Eternal"],["וּבִבְנוֹ","and-His-Son"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","Christ"],["׃",""]] },
  // Paragraph 9: True Church no longer on the earth
  { num:"ט", words:[["נֶאֱמַר","he-was-told"],["לוֹ","[him]"],["בַּחָזוֹן","in-this-vision"],["הַזֶּה","that"],["כִּי","the-true"],["כְּנֶסִיַּת","Church-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","Christ"],["הָאֲמִתִּית","the-true"],["שֶׁנּוּסְדָה","that-had-been-established"],["בִּימֵי","in"],["הַבְּרִית","New-Testament"],["הַחֲדָשָׁה","times"],["וַאֲשֶׁר","and-which-had"],["הִנְהִיגָה","administered"],["אֶת","[ACC]"],["מְלֹאת","the-fulness-of"],["הַבְּשׂוֹרָה","the-gospel"],["אֵינֶנָּה","was-no-longer"],["עוֹד","on"],["עַל","the-earth"],["הָאָרֶץ","[earth]"],["׃",""]] },
  // Paragraph 10: Church organized April 6, 1830
  { num:"י", words:[["בְּשִׁשָּׁה","on-the-sixth-of"],["בְּאַפְּרִיל","April"],["שְׁנַת","the-year"],["אֶלֶף","one-thousand"],["שְׁמוֹנֶה","eight"],["מֵאוֹת","hundred"],["וּשְׁלוֹשִׁים","and-thirty"],["עַל","under"],["פִּי","heavenly"],["הַנְחָיָה","direction"],["שְׁמֵימִית","the-Prophet"],["יִסֵּד","organized"],["הַנָּבִיא","[Prophet]"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["אֶת","[ACC]"],["הַכְּנֵסִיָּה","the-Church"],["וְכָךְ","and-thus"],["כְּנֶסִיַּת","the-true-Church-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","Christ"],["הָאֲמִתִּית","is-once-again"],["פּוֹעֶלֶת","operative"],["שׁוּב","as-an-institution"],["כְּמוּסָד","among"],["בְּקֶרֶב","men"],["בְּנֵי","with"],["אָדָם","authority"],["בְּסַמְכוּת","to-teach"],["לְלַמֵּד","the-gospel"],["אֶת","and"],["הַבְּשׂוֹרָה","administer"],["וּלְנַהֵל","the-ordinances-of"],["אֶת","salvation"],["טַקְסֵי","[salvation]"],["הַיְּשׁוּעָה","[salvation]"],["׃",""]] },
  // Paragraph 11: Revelations received in answer to prayer
  { num:"יא", words:[["הַגִּלּוּיִים","these-revelations"],["הַקְּדוֹשִׁים","sacred"],["הָאֵלֶּה","[these]"],["נִתְקַבְּלוּ","were-received"],["בְּמַעֲנֶה","in-answer"],["לִתְפִלָּה","to-prayer"],["בְּעִתּוֹת","in-times-of"],["צֹרֶךְ","need"],["וְצָמְחוּ","and-came-out-of"],["מִמַּצָּבִים","situations"],["אֲמִתִּיִּים","real-life"],["הַכּוֹלְלִים","involving"],["אֲנָשִׁים","people"],["אֲמִתִּיִּים","real"],["הַנָּבִיא","the-Prophet"],["וַחֲבֵרָיו","and-his-associates"],["בִּקְשׁוּ","sought-for"],["הַדְרָכָה","guidance"],["אֱלֹהִית","divine"],["וְהַגִּלּוּיִים","and-these-revelations"],["הָאֵלֶּה","certify"],["מְאַשְּׁרִים","that"],["כִּי","they-received-it"],["קִבְּלוּהָ","[received]"],["׃",""]] },
  // Paragraph 12: Doctrines of the gospel
  { num:"יב", words:[["בַּגִּלּוּיִים","in-the-revelations"],["תּוֹרוֹת","the-doctrines-of"],["הַבְּשׂוֹרָה","the-gospel"],["מְפֹרָשׁוֹת","are-set-forth"],["עִם","with"],["הֶסְבֵּרִים","explanations"],["עַל","about"],["עִנְיָנִים","matters"],["יְסוֹדִיִּים","fundamental"],["כְּגוֹן","such-as"],["טֶבַע","the-nature-of"],["הָאֱלֹהוּת","the-Godhead"],["מוֹצָא","the-origin-of"],["הָאָדָם","man"],["מְצִיאוּת","the-reality-of"],["הַשָּׂטָן","Satan"],["מַטְּרַת","the-purpose-of"],["הַתְּמוּתָה","mortality"],["הֶכְרַח","the-necessity-for"],["הַצִּיּוּת","obedience"],["הַצֹּרֶךְ","the-need-for"],["בִּתְשׁוּבָה","repentance"],["פְּעֻלּוֹת","the-workings-of"],["רוּחַ","the-Spirit-of"],["הַקֹּדֶשׁ","Holiness"],["׃",""]] },
  // Paragraph 13: Testimony of Jesus Christ
  { num:"יג", words:[["לְבַסּוֹף","finally"],["הָעֵדוּת","the-testimony"],["הַנִּתֶּנֶת","that-is-given-of"],["עַל","Jesus"],["יֵשׁוּעַ","Christ"],["הַמָּשִׁיחַ","His"],["אֱלֹהוּתוֹ","divinity"],["הֲדָרוֹ","His-majesty"],["שְׁלֵמוּתוֹ","His-perfection"],["אַהֲבָתוֹ","His-love"],["וְכֹחַ","and-His"],["גְּאֻלָּתוֹ","redeeming-power"],["עוֹשֶׂה","makes"],["אֶת","[ACC]"],["הַסֵּפֶר","this-book"],["הַזֶּה","of-great"],["בַּעַל","value"],["עֵרֶךְ","to"],["רַב","the-human"],["לְמִשְׁפַּחַת","family"],["הָאָדָם","[family]"],["׃",""]] },
  // Paragraph 14: Testimony of the Twelve Apostles
  { num:"יד", words:[["עֵדוּת","testimony-of"],["שְׁנֵים","the-Twelve"],["עָשָׂר","Apostles"],["הַשְּׁלִיחִים","to"],["עַל","the-truth-of"],["אֲמִתּוּת","the-Book-of"],["סֵפֶר","Doctrine"],["תּוֹרָה","and-Covenants"],["וּבְרִיתוֹת","[Covenants]"],["׃",""]] },
  // Paragraph 15: The Twelve's testimony text
  { num:"טו", words:[["אָנוּ","we"],["לָכֵן","therefore"],["מוּכָנִים","feel-willing"],["לְהָעִיד","to-bear-testimony"],["לְכׇל","to-all"],["הָעוֹלָם","the-world-of"],["שֶׁל","mankind"],["בְּנֵי","to-every"],["אָדָם","creature"],["לְכׇל","upon"],["בְּרִיָּה","the-face-of"],["עַל","the-earth"],["פְּנֵי","that"],["הָאָרֶץ","the-LORD"],["כִּי","has-borne-record"],["הֵעִיד","to"],["יְהוָה","our-souls"],["לְנַפְשׁוֹתֵינוּ","through"],["עַל","the-Holy"],["יְדֵי","Ghost"],["רוּחַ","shed-forth"],["הַקֹּדֶשׁ","upon-us"],["הַנִּשְׁפֶּכֶת","that"],["עָלֵינוּ","these"],["כִּי","commandments"],["הַמִּצְוֹת","were-given"],["הָאֵלֶּה","by"],["נִתְּנוּ","inspiration-of"],["בְּהַשְׁרָאַת","God"],["אֱלֹהִים","and-are"],["וְהֵם","profitable"],["מוֹעִילִים","for-all"],["לְכׇל","men"],["בְּנֵי","and-are"],["אָדָם","verily"],["וְהֵם","true"],["אֱמֶת","[true]"],["אָמֵן","[amen]"],["׃",""]] }
];
renderVerseSet(dcIntro_ch1Verses, 'dc-intro-verses');
})();
