// root_engine.js — auto-generated by tools/build_root_concordance.js from the
// canonical block in bom/bom.html. DO NOT EDIT — edit bom/bom.html and re-run.
// Exposes window.RootEngine.getRoot(hw): the SAME root key the concordance was
// built with, provided Strong's data (window._strongsLookup/_strongsRoots) is loaded.
(function() {
function stripPrefixes(w) {
    // Remove maqaf-joined particles first
    w = w.replace(/^.*־/, '');
    // Common prefixes: vav-conjunctive, article, prepositions
    // וְ וַ וּ (and), הַ הָ (the), בְּ בַּ בִּ (in), לְ לַ לִ (to), מִ מֵ (from), כְּ כַּ (as), שֶׁ (that)
    var prefixes = [
      /^וְ/, /^וַ/, /^וּ/, /^וָ/, /^וֶ/,  // vav conjunctive
      /^הַ/, /^הָ/, /^הֶ/,                 // article
      /^בְּ/, /^בַּ/, /^בִּ/, /^בָּ/, /^בֶּ/, /^בְ/, /^בַ/, /^בִ/, // bet
      /^לְ/, /^לַ/, /^לִ/, /^לָ/, /^לֶ/,  // lamed
      /^מִ/, /^מֵ/, /^מְ/, /^מַ/,          // mem
      /^כְּ/, /^כַּ/, /^כְ/, /^כַ/,        // kaf
      /^שֶׁ/, /^שֶ/                        // she-
    ];
    var stripped = w;
    for (var i = 0; i < prefixes.length; i++) {
      if (prefixes[i].test(stripped) && stripped.replace(prefixes[i], '').length >= 2) {
        stripped = stripped.replace(prefixes[i], '');
        break; // only strip one prefix layer at a time, then retry
      }
    }
    // Try stripping a second prefix (e.g., וְהַ = and + the)
    for (var j = 0; j < prefixes.length; j++) {
      if (prefixes[j].test(stripped) && stripped.replace(prefixes[j], '').length >= 2) {
        stripped = stripped.replace(prefixes[j], '');
        break;
      }
    }
    return stripped;
  }

  // Root family dictionary: maps surface forms to a canonical root key
  // This groups morphologically related words under one root
  // 583 entries across 67 root families (theological, verbal, nominal)
  var rootMap = {
    'חֶסֶד': 'חסד', 'חַסְדּוֹ': 'חסד', 'חֲסָדָיו': 'חסד', 'חֲסָדֶיךָ': 'חסד', 'חַסְדְּךָ': 'חסד', 'חַסְדִּי': 'חסד', 'חֲסִידָה': 'חסד', 'חָסִיד': 'חסד', 'חֲסִידוֹ': 'חסד', 'חֲסִידִים': 'חסד', 'חֲסָדִים': 'חסד', 'הַחֶסֶד': 'חסד', 'רַב־חֶסֶד': 'חסד', 'בְּחֶסֶד': 'חסד', 'לְחֶסֶד': 'חסד',
    'גָּאַל': 'גאל', 'גֹּאֵל': 'גאל', 'גֹּאֲלוֹ': 'גאל', 'גֹּאֲלִי': 'גאל', 'גֹּאֲלָם': 'גאל', 'גְּאֻלָּה': 'גאל', 'הַגְּאֻלָּה': 'גאל', 'גְּאוּלִים': 'גאל', 'גְּאוּלֵי': 'גאל', 'לִגְאֹל': 'גאל', 'נִגְאַל': 'גאל', 'יִגְאַל': 'גאל', 'נִגְאָלִים': 'גאל',
    'יְשׁוּעָה': 'ישע', 'יְשׁוּעַת': 'ישע', 'יוֹשִׁיעַ': 'ישע', 'הוֹשִׁיעַ': 'ישע', 'מוֹשִׁיעַ': 'ישע', 'תְּשׁוּעָה': 'ישע', 'הַיְשׁוּעָה': 'ישע', 'נוֹשַׁע': 'ישע', 'יִוָּשַׁע': 'ישע', 'יִוָּשֵׁעוּ': 'ישע', 'הוֹשַׁעְנָא': 'ישע', 'הוֹשִׁיעֵנוּ': 'ישע', 'תֵּשַׁע': 'ישע', 'תֵּשָׁעוּ': 'ישע',
    // תמם family — to be complete/whole/blameless (31+ occurrences)
    'תָּמִים': 'תמם', 'תָמִים': 'תמם', 'תְּמִימִים': 'תמם', 'תְמִימִים': 'תמם', 'וּתְמִימִים': 'תמם',
    'תְּמִימָה': 'תמם', 'תְמִימָה': 'תמם', 'תָּמָה': 'תמם', 'תָּם': 'תמם',
    'תֹּם': 'תמם', 'תֹּם׃': 'תמם', 'בְּתֹם': 'תמם', 'בְּתֹם־לֵבָב': 'תמם', 'כְּתֹם': 'תמם',
    'תֻּמִּים': 'תמם', 'הַתֻּמִּים': 'תמם', 'וְהַתֻּמִּים': 'תמם',
    'שָׁלוֹם': 'שׁלם', 'שְׁלֵמָה': 'שׁלם', 'שָׁלֵם': 'שׁלם', 'שְׁלֵמוּת': 'שׁלם', 'בִּשְׁלֵמוּת': 'שׁלם', 'הַשָּׁלוֹם': 'שׁלם', 'בְּשָׁלוֹם': 'שׁלם', 'לְשָׁלוֹם': 'שׁלם', 'שֶׁלֶם': 'שׁלם', 'שִׁלֵּם': 'שׁלם', 'שָׁלַם': 'שׁלם', 'מְשַׁלֵּם': 'שׁלם',
    'קֹדֶשׁ': 'קדשׁ', 'קָדוֹשׁ': 'קדשׁ', 'קְדוֹשִׁים': 'קדשׁ', 'מִקְדָּשׁ': 'קדשׁ', 'קִדֵּשׁ': 'קדשׁ', 'קָדְשׁוֹ': 'קדשׁ', 'הַקֹּדֶשׁ': 'קדשׁ', 'קְדוֹשׁוֹ': 'קדשׁ', 'הַקָּדוֹשׁ': 'קדשׁ', 'קְדֻשָּׁה': 'קדשׁ', 'וְקִדַּשְׁתֶּם': 'קדשׁ', 'מְקֻדָּשׁ': 'קדשׁ', 'קָדַשׁ': 'קדשׁ', 'בִּקְדֻשָּׁה': 'קדשׁ',
    'בְּרִית': 'ברית', 'בְּרִיתוֹ': 'ברית', 'בְּרִיתִי': 'ברית', 'בְּרִיתְךָ': 'ברית', 'הַבְּרִית': 'ברית', 'בִּרְיתוֹת': 'ברית', 'בְּרִיתוֹת': 'ברית', 'כָּרַת': 'ברית',
    'כִּפֵּר': 'כפר', 'כַּפָּרָה': 'כפר', 'הַכַּפָּרָה': 'כפר', 'כֹּפֶר': 'כפר', 'יְכַפֵּר': 'כפר', 'כִּפֻּרִים': 'כפר', 'לְכַפֵּר': 'כפר',
    'צַדִּיק': 'צדק', 'צַדִּיקִים': 'צדק', 'צֶדֶק': 'צדק', 'צִדְקָתוֹ': 'צדק', 'צְדָקָה': 'צדק', 'הַצַּדִּיק': 'צדק', 'הַצֶּדֶק': 'צדק', 'בְּצֶדֶק': 'צדק', 'צִדְקָה': 'צדק', 'צִדְקוֹ': 'צדק', 'צִדְקָתָם': 'צדק', 'צִדְקֵנוּ': 'צדק',
    'רָשָׁע': 'רשׁע', 'רְשָׁעִים': 'רשׁע', 'רִשְׁעָה': 'רשׁע', 'הָרְשָׁעִים': 'רשׁע', 'הָרָשָׁע': 'רשׁע', 'רִשְׁעָתוֹ': 'רשׁע', 'רִשְׁעָתָם': 'רשׁע', 'בְּרִשְׁעָה': 'רשׁע',
    'חַטָּאת': 'חטא', 'חֵטְא': 'חטא', 'חָטָא': 'חטא', 'חָטְאוּ': 'חטא', 'חַטָּאִים': 'חטא', 'חֲטָאֵיהֶם': 'חטא', 'חֲטָאֶיךָ': 'חטא', 'חַטֹּאתָם': 'חטא', 'חֲטָאַי': 'חטא', 'חַטָּאתוֹ': 'חטא',
    'עָוֹן': 'עון', 'עֲוֹנוֹת': 'עון', 'עֲוֹנָם': 'עון', 'עֲוֹנוֹתֵיהֶם': 'עון', 'עֲוֹנוֹתֵינוּ': 'עון', 'עֲוֹנוֹתַי': 'עון', 'עֲוֺנָם': 'עון',
    'שָׁב': 'שׁוב', 'שָׁבוּ': 'שׁוב', 'יָשׁוּב': 'שׁוב', 'יָשׁוּבוּ': 'שׁוב', 'שׁוּבוּ': 'שׁוב', 'תָּשׁוּב': 'שׁוב', 'תְּשׁוּבָה': 'שׁוב', 'הֵשִׁיב': 'שׁוב', 'הָשֵׁב': 'שׁוב', 'לָשׁוּב': 'שׁוב',
    'אֱמוּנָה': 'אמן', 'אֱמוּנָתוֹ': 'אמן', 'אֱמוּנָתֵנוּ': 'אמן', 'אֱמוּנָתָם': 'אמן', 'הֶאֱמִין': 'אמן', 'הֶאֱמִינוּ': 'אמן', 'יַאֲמִין': 'אמן', 'יַאֲמִינוּ': 'אמן', 'נֶאֱמָן': 'אמן', 'אָמֵן': 'אמן', 'בֶּאֱמוּנָה': 'אמן', 'הָאֱמוּנָה': 'אמן',
    'טָהוֹר': 'טהר', 'טְהוֹרִים': 'טהר', 'טִהֵר': 'טהר', 'טָהֳרָה': 'טהר', 'טְהָרָה': 'טהר', 'לְטַהֵר': 'טהר', 'יִטְהַר': 'טהר',
    'טָמֵא': 'טמא', 'טְמֵאִים': 'טמא', 'טֻמְאָה': 'טמא', 'טֻמְאָתוֹ': 'טמא', 'טֻמְאָתָם': 'טמא', 'בְּטֻמְאָה': 'טמא', 'וְטֻמְאָתָם': 'טמא',
    'אֱלֹהִים': 'אלהים', 'אֱלֹהֵיהֶם': 'אלהים', 'אֱלֹהָיו': 'אלהים', 'אֱלֹהֵינוּ': 'אלהים', 'אֱלֹהֶיךָ': 'אלהים', 'אֱלֹהַי': 'אלהים', 'אֵלִים': 'אלהים', 'אֱלֹהֵי': 'אלהים', 'הָאֱלֹהִים': 'אלהים',
    'יְהוָה': 'יהוה', 'יהוָה': 'יהוה', 'יָהּ': 'יהוה',
    'אָדוֹן': 'אדן', 'אֲדֹנָי': 'אדן', 'אֲדֹנֵנוּ': 'אדן', 'אֲדֹנֵיהֶם': 'אדן', 'הָאָדוֹן': 'אדן',
    'מָשִׁיחַ': 'משׁח', 'הַמָּשִׁיחַ': 'משׁח', 'מָשַׁח': 'משׁח', 'מְשִׁיחוֹ': 'משׁח', 'מִשְׁחָה': 'משׁח',
    'רוּחַ': 'רוח', 'רוּחוֹ': 'רוח', 'רוּחִי': 'רוח', 'רוּחָם': 'רוח', 'הָרוּחַ': 'רוח', 'בְּרוּחַ': 'רוח', 'רוּחֲךָ': 'רוח',
    'אָמַר': 'אמר', 'אֹמֵר': 'אמר', 'אֹמְרִים': 'אמר', 'יֹּאמַר': 'אמר', 'יֹּאמְרוּ': 'אמר', 'תֹּאמַר': 'אמר', 'אָמְרוּ': 'אמר', 'אָמַרְתִּי': 'אמר', 'אָמַרְתָּ': 'אמר', 'לֵאמֹר': 'אמר', 'נֶאֱמַר': 'אמר', 'יֵאָמֵר': 'אמר',
    'הָיָה': 'היה', 'הָיוּ': 'היה', 'יִהְיֶה': 'היה', 'יִהְיוּ': 'היה', 'תִּהְיֶה': 'היה', 'הֱיוֹת': 'היה', 'הָיִינוּ': 'היה', 'הָיִיתִי': 'היה', 'הָיִיתָ': 'היה', 'הָיְתָה': 'היה', 'נִהְיָה': 'היה',
    'עָשָׂה': 'עשׂה', 'עֹשֶׂה': 'עשׂה', 'עֹשִׂים': 'עשׂה', 'יַעֲשֶׂה': 'עשׂה', 'יַעֲשׂוּ': 'עשׂה', 'עֲשׂוּ': 'עשׂה', 'עָשׂוּ': 'עשׂה', 'עָשִׂיתָ': 'עשׂה', 'עָשִׂיתִי': 'עשׂה', 'תַּעֲשֶׂה': 'עשׂה', 'תַּעֲשׂוּ': 'עשׂה', 'נַעֲשֶׂה': 'עשׂה', 'מַעֲשֵׂה': 'עשׂה', 'מַעֲשֶׂיהָ': 'עשׂה', 'מַעֲשִׂים': 'עשׂה', 'מַעֲשֵׂיהֶם': 'עשׂה',
    'הָלַךְ': 'הלך', 'הֹלֵךְ': 'הלך', 'הֹלְכִים': 'הלך', 'יֵלֵךְ': 'הלך', 'יֵלְכוּ': 'הלך', 'לָלֶכֶת': 'הלך', 'הָלְכוּ': 'הלך', 'תֵּלֵךְ': 'הלך', 'לֵכוּ': 'הלך', 'הֲלִיכָה': 'הלך', 'הִתְהַלֵּךְ': 'הלך', 'הִתְהַלְּכוּ': 'הלך', 'וְהִתְהַלְּכוֹ': 'הלך',
    'נָתַן': 'נתן', 'נֹתֵן': 'נתן', 'נָתְנוּ': 'נתן', 'יִתֵּן': 'נתן', 'נָתַתִּי': 'נתן', 'נָתַתָּ': 'נתן', 'תִּתֵּן': 'נתן', 'תִּתְּנוּ': 'נתן', 'נָתוּן': 'נתן', 'לָתֵת': 'נתן', 'יִנָּתֵן': 'נתן',
    'בָּא': 'בוא', 'בָּאוּ': 'בוא', 'יָבוֹא': 'בוא', 'יָבֹאוּ': 'בוא', 'תָּבוֹא': 'בוא', 'לָבוֹא': 'בוא', 'הֵבִיא': 'בוא', 'הֵבִיאוּ': 'בוא', 'מֵבִיא': 'בוא', 'הוּבָא': 'בוא', 'בּוֹאוּ': 'בוא',
    'יָדַע': 'ידע', 'יוֹדֵעַ': 'ידע', 'יוֹדְעִים': 'ידע', 'יֵדַע': 'ידע', 'יֵדְעוּ': 'ידע', 'דַּעַת': 'ידע', 'דַעְתּוֹ': 'ידע', 'לָדַעַת': 'ידע', 'יָדְעוּ': 'ידע', 'יָדַעְתִּי': 'ידע', 'יָדַעְתָּ': 'ידע', 'הוֹדִיעַ': 'ידע', 'הוֹדַעְתִּי': 'ידע',
    'שָׁמַע': 'שׁמע', 'שֹׁמֵעַ': 'שׁמע', 'שָׁמְעוּ': 'שׁמע', 'יִשְׁמַע': 'שׁמע', 'יִשְׁמְעוּ': 'שׁמע', 'שִׁמְעוּ': 'שׁמע', 'תִּשְׁמְעוּ': 'שׁמע', 'שָׁמַעְתִּי': 'שׁמע', 'שְׁמַע': 'שׁמע', 'לִשְׁמֹעַ': 'שׁמע',
    'רָאָה': 'ראה', 'רֹאֶה': 'ראה', 'רָאוּ': 'ראה', 'יִרְאֶה': 'ראה', 'יִרְאוּ': 'ראה', 'רְאֵה': 'ראה', 'מַרְאֶה': 'ראה', 'רָאִיתִי': 'ראה', 'רָאִינוּ': 'ראה', 'הַרְאֵה': 'ראה', 'לִרְאוֹת': 'ראה', 'יַרְאֶה': 'ראה',
    'דָּבָר': 'דבר', 'דְּבָרִים': 'דבר', 'דִּבֵּר': 'דבר', 'דִּבְרֵי': 'דבר', 'דְּבַר': 'דבר', 'יְדַבֵּר': 'דבר', 'דִּבְּרוּ': 'דבר', 'דִּבַּרְתִּי': 'דבר', 'הַדָּבָר': 'דבר', 'הַדְּבָרִים': 'דבר',
    'קָרָא': 'קרא', 'קֹרֵא': 'קרא', 'קָרְאוּ': 'קרא', 'יִקְרָא': 'קרא', 'נִקְרָא': 'קרא', 'קְרָא': 'קרא', 'לִקְרֹא': 'קרא', 'מִקְרָא': 'קרא',
    'שָׁלַח': 'שׁלח', 'שֹׁלֵחַ': 'שׁלח', 'שָׁלְחוּ': 'שׁלח', 'יִשְׁלַח': 'שׁלח', 'שְׁלָחוֹ': 'שׁלח', 'שָׁלַחְתִּי': 'שׁלח', 'לִשְׁלֹחַ': 'שׁלח', 'מִשְׁלַח': 'שׁלח',
    'לָקַח': 'לקח', 'לֹקֵחַ': 'לקח', 'לָקְחוּ': 'לקח', 'יִקַּח': 'לקח', 'לָקַחַת': 'לקח', 'קַח': 'לקח', 'קְחוּ': 'לקח', 'נִלְקַח': 'לקח',
    'כָּתַב': 'כתב', 'כֹּתֵב': 'כתב', 'כָּתְבוּ': 'כתב', 'כָּתוּב': 'כתב', 'כְּתָבִים': 'כתב', 'יִכְתֹּב': 'כתב', 'כְּתַבְתִּי': 'כתב', 'כָּתַבְתִּי': 'כתב', 'הַכָּתוּב': 'כתב', 'הַכְּתוּבִים': 'כתב',
    'מוֹת': 'מות', 'מָוֶת': 'מות', 'מֵת': 'מות', 'מֵתִים': 'מות', 'יָמוּת': 'מות', 'יָמוּתוּ': 'מות', 'הֵמִית': 'מות', 'הֵמִיתוּ': 'מות', 'הַמָּוֶת': 'מות', 'לָמוּת': 'מות',
    'יָשַׁב': 'ישׁב', 'יוֹשֵׁב': 'ישׁב', 'יוֹשְׁבִים': 'ישׁב', 'יוֹשְׁבֵי': 'ישׁב', 'יָשְׁבוּ': 'ישׁב', 'יֵשֵׁב': 'ישׁב', 'יֵשְׁבוּ': 'ישׁב', 'לָשֶׁבֶת': 'ישׁב', 'מוֹשָׁב': 'ישׁב', 'תֵּשֵׁב': 'ישׁב',
    'שָׁפַט': 'שׁפט', 'שֹׁפֵט': 'שׁפט', 'שֹׁפְטִים': 'שׁפט', 'מִשְׁפָּט': 'שׁפט', 'מִשְׁפָּטִים': 'שׁפט', 'יִשְׁפֹּט': 'שׁפט', 'הַשֹּׁפְטִים': 'שׁפט', 'הַמִּשְׁפָּט': 'שׁפט',
    'לָחַם': 'לחם', 'לֹחֵם': 'לחם', 'לֹחֲמִים': 'לחם', 'נִלְחַם': 'לחם', 'נִלְחֲמוּ': 'לחם', 'מִלְחָמָה': 'לחם', 'מִלְחֲמוֹת': 'לחם', 'הִלָּחֲמוֹ': 'לחם', 'לְהִלָּחֵם': 'לחם',
    'שָׁמַר': 'שׁמר', 'שֹׁמֵר': 'שׁמר', 'שָׁמְרוּ': 'שׁמר', 'יִשְׁמֹר': 'שׁמר', 'יִשְׁמְרוּ': 'שׁמר', 'שִׁמְרוּ': 'שׁמר', 'לִשְׁמֹר': 'שׁמר', 'מִשְׁמֶרֶת': 'שׁמר', 'שֹׁמְרִים': 'שׁמר',
    'עָבַד': 'עבד', 'עֹבֵד': 'עבד', 'עֲבָדִים': 'עבד', 'עֶבֶד': 'עבד', 'עַבְדּוֹ': 'עבד', 'עֲבוֹדָה': 'עבד', 'עַבְדִּי': 'עבד', 'עֲבָדָיו': 'עבד', 'עַבְדְּךָ': 'עבד', 'לַעֲבֹד': 'עבד',
    'נָפַל': 'נפל', 'נֹפֵל': 'נפל', 'נָפְלוּ': 'נפל', 'יִפֹּל': 'נפל', 'יִפְּלוּ': 'נפל', 'נְפִילָה': 'נפל', 'נְפִילָתָם': 'נפל', 'מַפָּלָה': 'נפל',
    'שָׁחַת': 'שׁחת', 'מַשְׁחִית': 'שׁחת', 'שְׁחִיתוּ': 'שׁחת', 'הִשְׁחִית': 'שׁחת', 'הַשְׁחָתָה': 'שׁחת', 'יַשְׁחִית': 'שׁחת', 'נִשְׁחָת': 'שׁחת', 'מָשְׁחָת': 'שׁחת',
    'שָׁמַד': 'שׁמד', 'הִשְׁמִיד': 'שׁמד', 'הֻשְׁמְדוּ': 'שׁמד', 'יַשְׁמִיד': 'שׁמד', 'הַשְׁמָדָה': 'שׁמד', 'יִשָּׁמְדוּ': 'שׁמד', 'לְהַשְׁמִיד': 'שׁמד', 'נִשְׁמָד': 'שׁמד',
    'נֶפֶשׁ': 'נפשׁ', 'נַפְשׁוֹ': 'נפשׁ', 'נַפְשִׁי': 'נפשׁ', 'נַפְשָׁם': 'נפשׁ', 'נַפְשְׁךָ': 'נפשׁ', 'נַפְשׁוֹת': 'נפשׁ', 'נַפְשׁוֹתֵיהֶם': 'נפשׁ', 'נַפְשׁוֹתֵינוּ': 'נפשׁ',
    'לֵב': 'לב', 'לֵבָב': 'לב', 'לִבִּי': 'לב', 'לִבּוֹ': 'לב', 'לִבָּם': 'לב', 'לְבַבְכֶם': 'לב', 'לִבֵּנוּ': 'לב', 'הַלֵּב': 'לב', 'לְבָבוֹ': 'לב', 'לִבְּכֶם': 'לב',
    'עַיִן': 'עין', 'עֵינַי': 'עין', 'עֵינָיו': 'עין', 'עֵינֵיהֶם': 'עין', 'עֵינֶיךָ': 'עין', 'עֵינֵינוּ': 'עין',
    'יָד': 'יד', 'יָדוֹ': 'יד', 'יָדִי': 'יד', 'יְדֵיהֶם': 'יד', 'יָדְךָ': 'יד', 'יָדָם': 'יד', 'יָדַיִם': 'יד', 'יְדֵי': 'יד',
    'פָּנִים': 'פנה', 'פְּנֵי': 'פנה', 'פָּנָיו': 'פנה', 'פָּנַי': 'פנה', 'לִפְנֵי': 'פנה', 'מִפְּנֵי': 'פנה',
    'בָּשָׂר': 'בשׂר', 'בְּשָׂרוֹ': 'בשׂר', 'בְּשָׂרִי': 'בשׂר', 'בְּשָׂרָם': 'בשׂר', 'הַבָּשָׂר': 'בשׂר',
    'מֶלֶךְ': 'מלך', 'מַלְכוּת': 'מלך', 'מָלַךְ': 'מלך', 'מָלְכוּ': 'מלך', 'מְלָכִים': 'מלך', 'מַלְכֵי': 'מלך', 'יִמְלֹךְ': 'מלך', 'הַמֶּלֶךְ': 'מלך', 'מַמְלָכָה': 'מלך', 'הַמַּמְלָכָה': 'מלך',
    'שַׂר': 'שׁרר', 'שָׂרִים': 'שׁרר', 'שָׂרֵי': 'שׁרר', 'שַׂר־שָׁלוֹם': 'שׁרר', 'הַשַּׂר': 'שׁרר', 'מֹשֵׁל': 'שׁרר', 'מוֹשֵׁל': 'שׁרר',
    'כֹּהֵן': 'כהן', 'כֹּהֲנִים': 'כהן', 'כְּהֻנָּה': 'כהן', 'הַכֹּהֵן': 'כהן', 'כֹּהֲנֵי': 'כהן', 'הַכְּהֻנָּה': 'כהן',
    'נָבִיא': 'נביא', 'נְבִיאִים': 'נביא', 'נְבִיאֵי': 'נביא', 'הַנָּבִיא': 'נביא', 'נִבָּא': 'נביא', 'נְבוּאָה': 'נביא', 'הִתְנַבְּאוּ': 'נביא', 'נְבוּאוֹת': 'נביא',
    'אֶרֶץ': 'ארץ', 'אַרְצוֹ': 'ארץ', 'אַרְצָם': 'ארץ', 'אַרְצֵנוּ': 'ארץ', 'אֲרָצוֹת': 'ארץ', 'הָאָרֶץ': 'ארץ',
    'עַם': 'עם', 'עַמִּי': 'עם', 'עַמּוֹ': 'עם', 'עַמָּם': 'עם', 'עַמִּים': 'עם', 'עַמְּךָ': 'עם', 'הָעָם': 'עם',
    'בֵּן': 'בן', 'בְּנוֹ': 'בן', 'בְּנִי': 'בן', 'בָּנָיו': 'בן', 'בָּנִים': 'בן', 'בְּנֵי': 'בן', 'הַבֵּן': 'בן',
    'אָב': 'אב', 'אָבִי': 'אב', 'אָבִיו': 'אב', 'אֲבוֹתָם': 'אב', 'אֲבוֹתֵיהֶם': 'אב', 'אֲבוֹתֵינוּ': 'אב', 'אֲבוֹתַי': 'אב', 'הָאָב': 'אב',
    'תְּפִלָּה': 'תפל', 'תְּפִלּוֹת': 'תפל', 'הִתְפַּלֵּל': 'תפל', 'יִתְפַּלֵּל': 'תפל', 'מִתְפַּלֵּל': 'תפל', 'לְהִתְפַּלֵּל': 'תפל',
    'זֶבַח': 'זבח', 'זְבָחִים': 'זבח', 'זָבַח': 'זבח', 'זִבְחוּ': 'זבח', 'לִזְבֹּחַ': 'זבח', 'מִזְבֵּחַ': 'זבח',
    'שֶׁבַח': 'שׁבח', 'תְּהִלָּה': 'שׁבח', 'הַלֵּל': 'שׁבח', 'הַלְלוּ': 'שׁבח', 'הִלְלוּ': 'שׁבח',
    'צִוָּה': 'צוה', 'צִוָּהוּ': 'צוה', 'מִצְוָה': 'צוה', 'מִצְוֹת': 'צוה', 'מִצְוֹתָיו': 'צוה', 'הַמִּצְוֹת': 'צוה', 'צַו': 'צוה', 'צִוָּנוּ': 'צוה', 'צִוִּיתִי': 'צוה', 'צִוִּיתִיךָ': 'צוה', 'וַיְצַוֵּהוּ': 'צוה', 'יְצַוֵּהוּ': 'צוה', 'יְצַוֶּה': 'צוה',
    'חֹק': 'חקק', 'חֻקִּים': 'חקק', 'חֻקָּיו': 'חקק', 'חֻקּוֹתָיו': 'חקק', 'חֻקֵּי': 'חקק', 'הַחֻקִּים': 'חקק', 'הַחֹק': 'חקק',
    'שָׁבַע': 'שׁבע', 'נִשְׁבַּע': 'שׁבע', 'שְׁבוּעָה': 'שׁבע', 'שְׁבֻעוֹת': 'שׁבע', 'נִשְׁבַּעְתִּי': 'שׁבע', 'הִשָּׁבַע': 'שׁבע',
    'נַחֲלָה': 'נחל', 'נַחֲלָתוֹ': 'נחל', 'נַחֲלָתָם': 'נחל', 'יִנְחַל': 'נחל', 'הִנְחִיל': 'נחל',
    'סֵפֶר': 'ספר', 'סְפָרִים': 'ספר', 'סִפֵּר': 'ספר', 'לְסַפֵּר': 'ספר', 'סוֹפֵר': 'ספר', 'מִסְפַּר': 'ספר',
    'לוּחַ': 'לוח', 'לוּחוֹת': 'לוח', 'הַלּוּחוֹת': 'לוח', 'לוּחֹת': 'לוח',
    // תורה family (law/instruction)
    'תּוֹרָה': 'תורה', 'תּוֹרַת': 'תורה', 'תּוֹרָתוֹ': 'תורה', 'תּוֹרוֹת': 'תורה',
    // אשה family (woman/wife) — feminine construct ה→ת
    'אִשָּׁה': 'אשה', 'אִשְׁתּוֹ': 'אשה', 'אִשְׁתִּי': 'אשה', 'אִשְׁתְּךָ': 'אשה', 'אֵשֶׁת': 'אשה', 'נָשִׁים': 'אשה', 'נְשֵׁי': 'אשה', 'נְשׁוֹת': 'אשה', 'הָאִשָּׁה': 'אשה', 'נְשֵׁיהֶם': 'אשה', 'נְשׁוֹתֵיהֶם': 'אשה', 'לְאִשָּׁה': 'אשה',
    // תחת family (under/instead of) — ת is part of root, not a prefix
    'תַּחְתָּיו': 'תחת', 'תַּחְתָּיו׃': 'תחת', 'תַּחְתֶּיךָ': 'תחת', 'תַּחְתָּם': 'תחת', 'תַּחְתֵּיהֶם': 'תחת', 'תַּחְתֵּיהֶן': 'תחת', 'תַּחְתִּיּוֹת': 'תחת', 'בְּתַחְתִּיּוֹת': 'תחת', 'וְתַחְתִּיתָן': 'תחת', 'בַּתַּחְתִּית': 'תחת', 'תַּחְתָּי': 'תחת', 'תַּחַת': 'תחת', 'וְתַחַת': 'תחת', 'מִתַּחַת': 'תחת', 'מִתָּחַת': 'תחת', 'לְתַחַת': 'תחת', 'וּמִתַּחַת': 'תחת', 'מִתַּחַת׃': 'תחת', 'כִּי־תַחַת': 'תחת', 'תַחְתֹּךְ': 'תחת'
  };

  // Strip Hebrew diacritics (nikkud/cantillation) to get consonantal form
  function stripNikkud(s) {
    return s.replace(/[\u0591-\u05BD\u05BF-\u05C0\u05C3-\u05C7]/g, '');
  }

  // Normalize final Hebrew letters to regular form for root matching
  function normFinals(s) {
    return s.replace(/ך/g,'כ').replace(/ם/g,'מ').replace(/ן/g,'נ').replace(/ף/g,'פ').replace(/ץ/g,'צ');
  }

  // Restore final (sofit) form on the last letter of a root for display
  var sofitMap = {'כ':'ך','מ':'ם','נ':'ן','פ':'ף','צ':'ץ'};
  function toSofit(s) {
    if (!s || s.length === 0) return s;
    var last = s[s.length - 1];
    return sofitMap[last] ? s.slice(0, -1) + sofitMap[last] : s;
  }

  // Extract morphological root (3-letter shoresh) from consonantal form
  function extractRoot(cons) {
    var s = normFinals(cons);
    if (s.length <= 3) return s;
    if (s.length === 0) return cons;

    // --- Pass 1: strip suffixes (longest first) ---
    var sufs = [
      'תיהם','ותיהם','ותינו',
      'יהם','יהן','ותם','ותן','תיו','תיה','תנו',
      'כם','כן','נו','תי','תם','תן','ים','ות','ון','ין','הם','הן',
      'ה','ו','ם','ן','י','ת','כ'
    ];
    var stem = s;
    for (var i = 0; i < sufs.length; i++) {
      if (stem.length > sufs[i].length + 2 && stem.endsWith(sufs[i])) {
        stem = stem.slice(0, -sufs[i].length);
        break;
      }
    }
    if (stem.length === 3) return stem;

    // --- Pass 2: strip verbal prefixes ---
    if (stem.length >= 5 && (stem.slice(0,2) === 'הת' || stem.slice(0,2) === 'מת')) {
      stem = stem.slice(2);
    } else if (stem.length >= 4 && /^[היתאנמ]/.test(stem)) {
      stem = stem.slice(1);
    }
    if (stem.length === 3) return stem;

    // --- Pass 3: doubled middle consonant (Piel/Pual pattern) ---
    if (stem.length === 4 && stem[1] === stem[2]) {
      return stem[0] + stem[1] + stem[3];
    }

    // --- Pass 4: try suffix strip again on shorter stem ---
    for (var j = 0; j < sufs.length; j++) {
      if (stem.length > sufs[j].length + 2 && stem.endsWith(sufs[j])) {
        stem = stem.slice(0, -sufs[j].length);
        break;
      }
    }
    if (stem.length === 3) return stem;

    // --- Pass 5: try prefix strip again ---
    if (stem.length >= 4 && /^[היתאנמ]/.test(stem)) {
      stem = stem.slice(1);
    }
    if (stem.length === 3) return stem;

    if (stem.length === 4 && stem[1] === stem[2]) {
      return stem[0] + stem[1] + stem[3];
    }

    return stem.length > 3 ? stem.slice(0, 3) : stem;
  }

  // Feminine construct fix: ה→ת pattern (אשה→אשת, שנה→שנת, etc.)
  // If a 3-letter root ends in ת, the original root may end in ה
  function fixFemConstruct(root) {
    if (root.length === 3 && root[2] === 'ת') {
      return root.slice(0, 2) + 'ה';
    }
    return root;
  }

  // Get root key for a Hebrew word
  //
  // Cascade, most reliable first. Every step returns either a real Strong's
  // number or a real Hebrew word — never a truncated letter-fragment. The old
  // unconditional extractRoot() fallback is gone: it invented 2-3 letter keys
  // that merged unrelated lexemes (שׁמ swallowed שמר/שמד/שמם/שמע/שם) and split
  // real ones (כָּאָרֶץ became its own key "כאר" instead of joining H0776).
  var _consIdx = null;
  function consIndex() {
    if (_consIdx) return _consIdx;
    _consIdx = {};
    if (!window._strongsLookup) return _consIdx;
    for (var k in _strongsLookup) {
      var c = stripNikkud(k);
      if (!c) continue;
      if (_consIdx[c] === undefined) _consIdx[c] = _strongsLookup[k];
      else if (_consIdx[c] !== _strongsLookup[k]) _consIdx[c] = null; // ambiguous: refuse
    }
    return _consIdx;
  }
  var _rePre = /^(וכש|ומ|וב|ול|וכ|וה|כש|לכ|מה|בה|כה|לה|ו|ה|ב|כ|ל|מ|ש)/;
  var _sufs = ['ותיהם','ותיכם','ותינו','ותיה','ותיו','ותם','ותן','ותי','יהם','יכם',
               'ינו','תיו','נו','כם','הם','הן','תי','יו','יה','ים','ות','ם','ן','ו','ה','י','ך'];
  var _particles = {'את':1,'אל':1,'על':1,'מן':1,'עד':1,'כל':1,'לא':1,'ואת':1,'ואל':1};
  function _clean(s) { return String(s || '').replace(/[׃׀"'`]/g, '').trim(); }
  function _pieces(s) { return _clean(s).split(/[־\s]+/).filter(Boolean); }

  // Resolve ONE whitespace/maqqef-free word to a Strong's number, or '' if none.
  function _strongsFor(w, strict) {
    if (!window._strongsLookup || !window._strongsRoots) return '';
    var CI = consIndex();
    var sNum = _strongsLookup[w] || _strongsLookup[stripPrefixes(w)] ||
               _strongsLookup[stripNikkud(w)] || _strongsLookup[stripNikkud(stripPrefixes(w))] || '';
    if (sNum && _strongsRoots[sNum]) return sNum;
    // A word the corpus glosses as a proper name gets the exact lookups above and
    // nothing more. Fuzzy consonantal matching filed all 422 Book of Mormon
    // נֶפִי tokens under H5297 נֹף — Noph, i.e. Memphis in Egypt.
    if (strict) return '';
    var c = stripNikkud(w);
    if (!c) return '';
    if (CI[c] && _strongsRoots[CI[c]]) return CI[c];          // defective/variant pointing
    var b = c;                                                 // peel prefixes
    for (var p = 0; p < 3; p++) {
      var m = b.match(_rePre);
      if (!m) break;
      b = b.slice(m[1].length);
      if (b.length < 2) break;
      if (CI[b] && _strongsRoots[CI[b]]) return CI[b];
    }
    var bases = [c, b], fin = {'מ':'ם','נ':'ן','צ':'ץ','פ':'ף','כ':'ך'};
    for (var i = 0; i < bases.length; i++) {                   // peel plural/pronominal endings
      for (var j = 0; j < _sufs.length; j++) {
        var s = _sufs[j], B = bases[i];
        if (B.length > s.length + 1 && B.slice(-s.length) === s) {
          var st = B.slice(0, -s.length);
          if (CI[st] && _strongsRoots[CI[st]]) return CI[st];
          var lc = st.slice(-1);                               // segholate plural: ארצ → ארץ
          if (fin[lc] && CI[st.slice(0, -1) + fin[lc]] && _strongsRoots[CI[st.slice(0, -1) + fin[lc]]])
            return CI[st.slice(0, -1) + fin[lc]];
        }
      }
    }
    return '';
  }

  // Consonantal index of Strong's LEMMAS (not surface forms). This is the
  // authority for "is this string a real Hebrew root?" — 6,243 distinct lemmas,
  // exhaustive for biblical Hebrew. Ambiguous skeletons map to null: חנכ is
  // H2596 (train), H2585 (Enoch) and H2583 (encamp) at once, so it cannot be
  // resolved to a number — but it is still a real root, and grouping every חנכ
  // form under the string "חנכ" is correct where guessing a number is not.
  // A Hebrew root is triliteral. Strong's numbers a *lexeme*, so one root is
  // spread over several entries — חנך is H2596 (חָנַךְ, "dedicate"/"train"),
  // H2598 (חֲנֻכָּה, "dedication") and H2599 — and the scorecard showed them as
  // three unrelated roots. Following Strong's own derivation pointer collapses
  // them onto the root they share.
  //
  // Only when that base is exactly three letters. Strong's derivations are
  // 19th-century etymology and some are junk: מָן "manna" points at מָה "what",
  // which is two letters and a different word. Those keep their own lexeme.
  var _baseOf = null;
  function baseRoot(sNum) {
    if (!_baseOf) {
      _baseOf = {};
      if (window._strongsRoots) {
        for (var n in _strongsRoots) {
          var cur = n, seen = {};
          while (_strongsRoots[cur] && _strongsRoots[cur].r &&
                 _strongsRoots[cur].r !== cur && !seen[cur]) {
            seen[cur] = 1; cur = _strongsRoots[cur].r;
          }
          var e = _strongsRoots[cur];
          // Count Hebrew LETTERS, not characters: stripNikkud leaves the shin
          // dot in place, so שָׁלַם measured 4 and every ש root failed the test.
          _baseOf[n] = (e && e.w && (e.w.match(/[\u05D0-\u05EA]/g) || []).length === 3) ? cur : n;
        }
      }
    }
    return _baseOf[sNum] || sNum;
  }

  var _lemIdx = null;
  function lemmaIndex() {
    if (_lemIdx) return _lemIdx;
    _lemIdx = {};
    if (!window._strongsRoots) return _lemIdx;
    for (var n in _strongsRoots) {
      var e = _strongsRoots[n];
      if (!e || !e.w) continue;
      var c = normFinals(stripNikkud(e.w));
      if (c.length < 2) continue;
      if (_lemIdx[c] === undefined) _lemIdx[c] = n;
      else if (_lemIdx[c] !== n) _lemIdx[c] = null;   // ambiguous
    }
    return _lemIdx;
  }

  // Peel affixes off an inflected form and keep the first residue that is a real
  // root. Without this, conjugated verbs Strong's has no surface form for became
  // their own one-occurrence entries — חִנְּכוּנִי ("taught me", Piel + 1cs object
  // suffix) was filed as the root "חנכוני", which is not a word.
  var _mSuf = ['ותיהם','ותינו','ותיכם','וני','ניו','תיו','יהם','יכם','ינו','ני',
               'נו','הו','תי','תם','תן','כם','הם','הן','ים','ות','ם','ן','ו','ה','י','ך'];
  var _mPre = ['וכש','ומ','וב','ול','וכ','וה','כש','ו','ה','ב','כ','ל','מ','ש'];
  function rootByMorphology(w) {
    var LI = lemmaIndex(), c = normFinals(stripNikkud(w));
    if (c.length < 3) return '';
    var cands = [], i, j;
    for (i = 0; i < _mSuf.length; i++) {          // suffix first: it is the
      var sfx = _mSuf[i];                          // stronger signal
      if (c.length > sfx.length + 2 && c.slice(-sfx.length) === sfx) cands.push(c.slice(0, -sfx.length));
    }
    for (i = 0; i < _mPre.length; i++) {
      var pre = _mPre[i];
      if (c.indexOf(pre) === 0 && c.length - pre.length >= 3) {
        var body = c.slice(pre.length);
        cands.push(body);
        for (j = 0; j < _mSuf.length; j++) {
          var s2 = _mSuf[j];
          if (body.length > s2.length + 2 && body.slice(-s2.length) === s2) cands.push(body.slice(0, -s2.length));
        }
      }
    }
    for (i = 0; i < cands.length; i++) {
      var cand = cands[i];
      if (cand.length < 3) continue;
      if (LI[cand] !== undefined) return LI[cand] ? baseRoot(LI[cand]) : cand;
    }
    return '';
  }

  function getRoot(hw) {
    var w = _clean(hw);
    var _head = _pieces(w).pop() || '';
    var isName = !!(window._rootProperNames && window._rootProperNames[normFinals(stripNikkud(_head))]);
    var s = _strongsFor(w, isName);
    if (s) return baseRoot(s);
    if (rootMap[hw]) return rootMap[hw];
    var stripped2 = stripPrefixes(hw);
    if (rootMap[stripped2]) return rootMap[stripped2];
    var ps = _pieces(w);
    if (ps.length > 1) {                                       // maqqef/space compound: use head
      var content = ps.filter(function(p) { return !_particles[stripNikkud(p)]; });
      var order = content.length ? content : ps;
      for (var i = 0; i < order.length; i++) {
        var sp = _strongsFor(order[i], isName);
        if (sp) return baseRoot(sp);
      }
    }
    // Inflected form of a real root? Skip this for words the corpus glosses as
    // proper names — מוֹרוֹנִי would otherwise peel to מור, a real root meaning
    // "to change", and Moroni would be filed under it.
    if (!isName) {
      var byMorph = rootByMorphology(_head || w);
      if (byMorph) return byMorph;
    }

    // Honest fallback: a real word Strong's does not carry (Smith, Rigdon,
    // Sanhedrin, אֵינוֹ...). Key it by its own consonantal form, never a stem.
    var head = ps.filter(function(p) { return !_particles[stripNikkud(p)]; }).pop() || ps.pop() || '';
    var c = stripNikkud(head);
    // The fallback never truncates, so a short result is a genuine short word
    // (לוֹ "to him", לִי "to me"), not a stem fragment. Only reject the empty
    // case and bare single letters.
    if (c.length < 2) return '';
    // A proper name keeps every letter: מוֹרְמוֹן must not shed its מ and become
    // "ורמון" just because וְרַמּוֹן (Rimmon) happens to occur elsewhere.
    if (!isName) {
      var m2 = c.match(_rePre);
      if (m2) {                                                // strip a prefix only if what is
        var rest = c.slice(m2[1].length);                      // left is itself an attested word
        if (rest.length >= 3 && window._rootWordForms && window._rootWordForms[rest]) return rest;
      }
    }
    return c;
  }

  
  window.RootEngine = { getRoot: getRoot, stripPrefixes: stripPrefixes, stripNikkud: stripNikkud, toSofit: toSofit };
})();
