/**
 * root_scorecard.js — the shared word-scorecard engine for all six scripture pages.
 *
 * Fixes two long-standing popup bugs:
 *   1. Counts were per-page: the BOM lazy-loads one book at a time so its popup
 *      counted only the loaded book ("Occurrences: 1"); the OT counted only the
 *      OT, the NT only the NT — nothing communicated.
 *   2. The root key drifted: pages keyed their frequency maps before Strong's
 *      data loaded (heuristic stems) but computed popup roots after (H-numbers),
 *      so the lookup missed entirely.
 *
 * This engine resolves every word through root_engine.js (the canonical
 * getRoot, generated from bom/bom.html with Strong's guaranteed loaded) against
 * root_concordance.js (counts, forms, glosses across OT+NT+BOM+D&C+PGP+JST,
 * generated by tools/build_root_concordance.js). Verse references live in
 * root_concordance_refs.js, loaded only when the references panel opens.
 *
 * Page integration:
 *   RootScorecard.init({ vol: 'bom', base: '../' });
 *   ...popup builds its legacy detail inside <div class="rsc-slot">…</div>...
 *   RootScorecard.fill(slotEl, surfaceHebrew);
 */
(function() {
  'use strict';
  var RSC_V = '5';   // bump when the generated data files change

  var cfg = { vol: '', base: '' };
  var keyIdx = null;         // rootKey -> index, built once
  var pendingFills = [];     // fills requested before data ready
  var loadState = 0;         // 0 idle, 1 loading, 2 ready
  var refsState = 0;
  var refsWaiters = [];

  var PAGES = { ot: 'ot.html', nt: 'nt.html', bom: 'bom/bom.html', dc: 'dc.html', pgp: 'pgp.html', jst: 'jst.html' };
  var VOL_ORDER = ['ot', 'nt', 'bom', 'dc', 'pgp', 'jst'];

  function loadScript(src, cb) {
    var el = document.createElement('script');
    el.src = src; el.async = true;
    el.onload = function() { cb && cb(); };
    el.onerror = function() { console.warn('[RootScorecard] failed to load', src); cb && cb(); };
    document.head.appendChild(el);
  }

  function ensureStrongs(cb) {
    if (window._strongsLookup && window._strongsRoots) { cb(); return; }
    if (typeof window.ensureStrongsData === 'function') { window.ensureStrongsData(cb); return; }
    var n = 0; function done() { if (++n >= 2) cb(); }
    loadScript(cfg.base + 'strongs_lookup.js', done);
    loadScript(cfg.base + 'strongs_roots.js', done);
  }

  function ensure(cb) {
    if (loadState === 2) { cb(); return; }
    pendingFills.ensureCbs = pendingFills.ensureCbs || [];
    pendingFills.ensureCbs.push(cb);
    if (loadState === 1) return;
    loadState = 1;
    ensureStrongs(function() {
      var n = 0;
      function done() {
        if (++n < 2) return;
        if (window._rootConcordance && window.RootEngine) {
          keyIdx = {};
          var keys = window._rootConcordance.keys;
          for (var i = 0; i < keys.length; i++) keyIdx[keys[i]] = i;
          loadState = 2;
        } else {
          loadState = 0;   // allow retry
        }
        var cbs = pendingFills.ensureCbs || [];
        pendingFills.ensureCbs = [];
        cbs.forEach(function(f) { try { f(); } catch (e) {} });
      }
      if (window.RootEngine) { n++; } else loadScript(cfg.base + 'root_engine.js?v=' + RSC_V, done);
      if (window._rootConcordance) { n++; } else loadScript(cfg.base + 'root_concordance.js?v=' + RSC_V, done);
      if (n >= 2) done();
    });
  }

  function ensureRefs(cb) {
    if (refsState === 2 || window._rootConcordanceRefs) { refsState = 2; cb(); return; }
    refsWaiters.push(cb);
    if (refsState === 1) return;
    refsState = 1;
    loadScript(cfg.base + 'root_concordance_refs.js?v=' + RSC_V, function() {
      refsState = window._rootConcordanceRefs ? 2 : 0;
      var w = refsWaiters; refsWaiters = [];
      w.forEach(function(f) { try { f(); } catch (e) {} });
    });
  }

  function esc(s) {
    return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }
  function cleanSurface(s) {
    // sof pasuq + ketiv/qere brackets never reach the root key
    return String(s || '').replace(/[׃\[\]]/g, '').trim();
  }

  function lookup(surface) {
    if (loadState !== 2) return null;
    var s = cleanSurface(surface);
    if (!s) return null;
    var root = window.RootEngine.getRoot(s);
    var idx = keyIdx[root];
    if (idx === undefined) return null;
    return { idx: idx, key: root, entry: window._rootConcordance.roots[idx] };
  }

  function rootDisplay(key) {
    var heb = key, translit = '', meaning = '';
    if (/^H\d+$/.test(key) && window._strongsRoots && window._strongsRoots[key]) {
      var e = window._strongsRoots[key];
      heb = e.w || key; meaning = e.g || '';
      // The site's own transliteration, matching the reader line — not Strong's
      // scholarly one (ʼâçaph): laymen read "asaf", not diacritics.
      if (typeof window.transliterate === 'function') { try { translit = window.transliterate(heb); } catch (eT) {} }
      if (!translit) translit = e.x || '';
      var cons = heb.replace(/[֑-ֽֿ-׀׃-ׇ]/g, '');
      var cur = (window._rootGlossaryData || {})[cons];
      if (cur && cur.meaning) meaning = cur.meaning;
    } else {
      if (window.RootEngine && window.RootEngine.toSofit) heb = window.RootEngine.toSofit(key);
      var cur2 = (window._rootGlossaryData || {})[key];
      if (cur2 && cur2.meaning) meaning = cur2.meaning;
      if (typeof window.transliterate === 'function') { try { translit = window.transliterate(heb); } catch (e2) {} }
    }
    return { heb: heb, translit: translit, meaning: meaning };
  }

  function bookNameFor(vol, chapId) {
    if (vol === 'dc') {
      var md = chapId.match(/^dc(\d+)/);
      if (md) return 'D&C ' + md[1];
      var mo = chapId.match(/^od(\d+)/);
      if (mo) return 'OD ' + mo[1];
      return chapId;
    }
    var list = (window._rootConcordance.books || {})[vol] || [];
    for (var i = 0; i < list.length; i++) {
      if (chapId.indexOf(list[i].p) === 0) return list[i].n;
    }
    return chapId;
  }
  function chapterLabel(vol, chapId) {
    var book = bookNameFor(vol, chapId);
    if (vol === 'dc') return book;                       // D&C 76 (section is the chapter)
    var mf = chapId.match(/fac(\d+)$/);
    if (mf) return book + ' Facsimile ' + mf[1];
    var mc = chapId.match(/ch(\d+)$/);
    return mc ? book + ' ' + mc[1] : book + ' ' + chapId;
  }
  function refHref(vol, chapId, v) {
    var deep = vol === 'bom' ? (chapId + (v ? ':' + v : '')) : (chapId + (v ? '&v=' + v : ''));
    if (vol === cfg.vol) return '#' + deep;
    return cfg.base + PAGES[vol] + '#' + deep;
  }

  // ---------- popup slot ----------
  function detailHtml(found, surface) {
    var entry = found.entry;
    var d = rootDisplay(found.key);
    var conc = window._rootConcordance;
    var total = 0, totalVerses = 0;
    entry.c.forEach(function(n) { total += n; });
    entry.vc.forEach(function(n) { totalVerses += n; });
    var h = '';
    h += '<span class="rsc-root" style="cursor:pointer;text-decoration:underline;color:var(--tap-blue,#2e6da4);">Root ' +
      '<span style="font-family:\'David Libre\',serif">' + esc(d.heb) + '</span>' +
      (d.translit ? ' <span style="font-size:0.85em;opacity:0.7;">(' + esc(d.translit) + ')</span>' : '') +
      '</span> — ' + total + ' uses in ' + totalVerses + ' verses across the scriptures';
    if (d.meaning) h += '<br><span style="font-style:italic;opacity:0.85;font-size:0.9em;">' + esc(d.meaning) + '</span>';
    // per-volume chips
    h += '<div class="rsc-chips">';
    VOL_ORDER.forEach(function(vk, vi) {
      var n = entry.c[vi];
      if (!n) return;
      var label = (conc.volNames || {})[vk] || vk.toUpperCase();
      h += '<span class="rsc-chip' + (vk === cfg.vol ? ' rsc-chip-here' : '') + '">' + esc(label) + ' ' + n + '</span>';
    });
    h += '</div>';
    var forms = Object.keys(entry.f || {});
    if (forms.length > 1) {
      h += '<span>Forms:</span> ' + forms.map(function(f) {
        return '<span style="font-family:\'David Libre\',serif">' + esc(f) + '</span> (' + entry.f[f] + 'x)';
      }).join(', ') + '<br>';
    }
    var glosses = Object.keys(entry.g || {});
    if (glosses.length > 1) {
      h += '<span>Glossed:</span> ' + glosses.slice(0, 4).map(function(g) {
        return '"' + esc(g) + '" (' + entry.g[g] + 'x)';
      }).join(', ') + '<br>';
    }
    h += '<span class="rsc-refs-link" style="cursor:pointer;color:var(--accent,#d4af37);text-decoration:underline;font-size:0.9em;">View all references →</span>';
    return h;
  }

  var fillToken = 0;
  function fill(slotEl, surface, glossText) {
    if (!slotEl) return;
    var token = ++fillToken;
    var doFill = function() {
      if (token !== fillToken) return;                    // a newer popup superseded this one
      if (!document.contains(slotEl)) return;             // popup closed
      if (loadState !== 2) return;                        // load failed; keep legacy content
      var found = lookup(surface);
      if (!found) return;                                 // not in corpus (front matter etc.)
      slotEl.innerHTML = detailHtml(found, surface);
      var rootLink = slotEl.querySelector('.rsc-root');
      if (rootLink && typeof window.openGlossaryAtRoot === 'function') {
        rootLink.addEventListener('click', function(ev) {
          ev.stopPropagation();
          window.openGlossaryAtRoot(found.key);
        });
      }
      var refsLink = slotEl.querySelector('.rsc-refs-link');
      if (refsLink) {
        refsLink.addEventListener('click', function(ev) {
          ev.stopPropagation();
          if (typeof window.closePopup === 'function') { try { window.closePopup(); } catch (e) {} }
          openPanel(found.idx);
        });
      }
    };
    if (loadState === 2) { doFill(); return; }
    ensure(doFill);
  }

  // ---------- references panel ----------
  var panelEl = null;
  function buildPanel() {
    if (panelEl && !document.body.contains(panelEl)) panelEl = null;   // page code may have swept it
    if (panelEl) return panelEl;
    panelEl = document.createElement('div');
    panelEl.id = 'rsc-panel';
    panelEl.innerHTML =
      '<div class="rsc-panel-backdrop"></div>' +
      '<div class="rsc-panel-card" role="dialog" aria-label="All references">' +
        '<div class="rsc-panel-head">' +
          '<div class="rsc-panel-title"></div>' +
          '<button type="button" class="rsc-panel-close" aria-label="Close">×</button>' +
        '</div>' +
        '<div class="rsc-panel-body"></div>' +
      '</div>';
    document.body.appendChild(panelEl);
    panelEl.querySelector('.rsc-panel-backdrop').addEventListener('click', closePanel);
    panelEl.querySelector('.rsc-panel-close').addEventListener('click', closePanel);
    // Same-volume links: navigate via hash and close
    panelEl.addEventListener('click', function(e) {
      var a = e.target.closest ? e.target.closest('a.rsc-ref') : null;
      if (!a) return;
      if (a.getAttribute('href').charAt(0) === '#') closePanel();
      // cross-volume links navigate away naturally
    });
    return panelEl;
  }
  function closePanel() {
    if (panelEl) panelEl.classList.remove('open');
  }
  function openPanel(idx) {
    var conc = window._rootConcordance;
    var entry = conc.roots[idx];
    var d = rootDisplay(conc.keys[idx]);
    var p = buildPanel();
    p.querySelector('.rsc-panel-title').innerHTML =
      '<span style="font-family:\'David Libre\',serif;font-size:1.25em;">' + esc(d.heb) + '</span>' +
      (d.translit ? ' <span style="opacity:0.75;font-size:0.85em;">' + esc(d.translit) + '</span>' : '') +
      (d.meaning ? '<div class="rsc-panel-meaning">' + esc(d.meaning) + '</div>' : '');
    var body = p.querySelector('.rsc-panel-body');
    body.innerHTML = '<div class="rsc-loading">Loading references…</div>';
    p.classList.add('open');
    ensureRefs(function() {
      var refs = (window._rootConcordanceRefs || [])[idx];
      if (!refs) { body.innerHTML = '<div class="rsc-loading">No references found.</div>'; return; }
      var h = '';
      // Order volumes: current volume first, then canonical order
      var order = [cfg.vol].concat(VOL_ORDER.filter(function(v) { return v !== cfg.vol; }));
      if (refs._b) {
        // Too common for verse-level refs: per-book verse counts
        h += '<div class="rsc-note">This root is very common — showing verse counts by book.</div>';
        order.forEach(function(vk) {
          var bObj = refs._b[vk];
          if (!bObj) return;
          var vi = VOL_ORDER.indexOf(vk);
          h += '<div class="rsc-vol"><div class="rsc-vol-title">' + esc((conc.volNames || {})[vk] || vk) +
               ' <span class="rsc-vol-count">' + entry.c[vi] + ' uses · ' + entry.vc[vi] + ' verses</span></div><div class="rsc-books">';
          Object.keys(bObj).forEach(function(bp) {
            var name = vk === 'dc' ? (bp === 'od' ? 'Official Declarations' : 'D&C') : bookNameFor(vk, bp + (bp === 'ch' ? '1' : 'ch1'));
            h += '<span class="rsc-bookcount">' + esc(name) + ' · ' + bObj[bp] + '</span>';
          });
          h += '</div></div>';
        });
      } else {
        order.forEach(function(vk) {
          var chObj = refs[vk];
          if (!chObj) return;
          var vi = VOL_ORDER.indexOf(vk);
          h += '<div class="rsc-vol"><div class="rsc-vol-title">' + esc((conc.volNames || {})[vk] || vk) +
               ' <span class="rsc-vol-count">' + entry.c[vi] + ' uses · ' + entry.vc[vi] + ' verses</span></div>';
          // group chapters by book, preserve corpus order via books table order
          var byBook = {};
          var bookOrder = [];
          Object.keys(chObj).forEach(function(chapId) {
            var bn = bookNameFor(vk, chapId);
            if (!byBook[bn]) { byBook[bn] = []; bookOrder.push(bn); }
            byBook[bn].push(chapId);
          });
          bookOrder.forEach(function(bn) {
            h += '<div class="rsc-book"><span class="rsc-book-name">' + esc(bn) + '</span> ';
            var parts = [];
            byBook[bn].forEach(function(chapId) {
              var mc = chapId.match(/ch(\d+)$/);
              var mf = chapId.match(/fac(\d+)$/);
              var chNum = vk === 'dc' ? '' : (mf ? ('F' + mf[1]) : (mc ? mc[1] : chapId));
              var verses = chObj[chapId];
              var links = verses.map(function(v) {
                return '<a class="rsc-ref" href="' + esc(refHref(vk, chapId, v)) + '">' + v + '</a>';
              }).join(', ');
              parts.push((chNum ? chNum + ':' : '') + links);
            });
            h += parts.join(' · ') + '</div>';
          });
          h += '</div>';
        });
      }
      body.innerHTML = h;
    });
  }

  // ---------- styles ----------
  function injectCss() {
    if (document.getElementById('rsc-style')) return;
    var st = document.createElement('style');
    st.id = 'rsc-style';
    st.textContent =
      '.rsc-chips{display:flex;flex-wrap:wrap;gap:4px;margin:6px 0;direction:ltr;}' +
      '.rsc-chip{display:inline-block;padding:1px 8px;border-radius:10px;font-size:0.78em;' +
        'background:rgba(212,175,55,0.12);border:1px solid rgba(212,175,55,0.4);white-space:nowrap;}' +
      '.rsc-chip-here{background:rgba(212,175,55,0.3);font-weight:700;}' +
      '#rsc-panel{position:fixed;inset:0;z-index:10050;display:none;direction:ltr;}' +
      '#rsc-panel.open{display:block;}' +
      '#rsc-panel .rsc-panel-backdrop{position:absolute;inset:0;background:rgba(0,0,0,0.55);}' +
      '#rsc-panel .rsc-panel-card{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);' +
        'width:min(560px,92vw);max-height:82vh;display:flex;flex-direction:column;' +
        'background:#1e2233;color:#e8e0d0;border:1px solid rgba(244,202,72,0.55);border-radius:12px;' +
        'box-shadow:0 12px 40px rgba(0,0,0,0.5);overflow:hidden;}' +
      'body.dark-mode #rsc-panel .rsc-panel-card{background:#101321;}' +
      '#rsc-panel .rsc-panel-head{display:flex;align-items:flex-start;justify-content:space-between;' +
        'padding:14px 16px 10px;border-bottom:1px solid rgba(244,202,72,0.35);}' +
      '#rsc-panel .rsc-panel-title{color:#f4ca48;line-height:1.3;}' +
      '#rsc-panel .rsc-panel-meaning{color:#e8e0d0;opacity:0.85;font-size:0.85em;font-style:italic;margin-top:2px;}' +
      '#rsc-panel .rsc-panel-close{background:none;border:none;color:#f4ca48;font-size:26px;line-height:1;' +
        'cursor:pointer;padding:0 4px;min-width:44px;min-height:34px;}' +
      '#rsc-panel .rsc-panel-body{overflow-y:auto;-webkit-overflow-scrolling:touch;padding:10px 16px 18px;font-size:0.92em;}' +
      '#rsc-panel .rsc-vol{margin-bottom:14px;}' +
      '#rsc-panel .rsc-vol-title{color:#f4ca48;font-weight:700;margin:8px 0 4px;border-bottom:1px solid rgba(244,202,72,0.25);padding-bottom:2px;}' +
      '#rsc-panel .rsc-vol-count{color:#e8e0d0;opacity:0.7;font-weight:400;font-size:0.85em;}' +
      '#rsc-panel .rsc-book{margin:3px 0;line-height:1.7;}' +
      '#rsc-panel .rsc-book-name{font-weight:700;color:#fff0b8;}' +
      '#rsc-panel a.rsc-ref{color:var(--accent,#d4af37);text-decoration:none;padding:1px 2px;min-height:32px;}' +
      '#rsc-panel a.rsc-ref:hover{text-decoration:underline;}' +
      '#rsc-panel .rsc-books{display:flex;flex-wrap:wrap;gap:6px;}' +
      '#rsc-panel .rsc-bookcount{background:rgba(244,202,72,0.1);border:1px solid rgba(244,202,72,0.3);' +
        'border-radius:8px;padding:2px 8px;font-size:0.85em;}' +
      '#rsc-panel .rsc-note{opacity:0.8;font-style:italic;margin-bottom:8px;}' +
      '#rsc-panel .rsc-loading{opacity:0.7;padding:16px 0;text-align:center;}' +
      /* ── Root Glossary: navy + gold, matching the site chrome ── */
      '#glossary-panel{background:var(--sw-navy,#1e2233) !important;color:#e8e0d0;border-right:2px solid var(--sw-gold,#f4ca48) !important;}' +
      'body.dark-mode #glossary-panel{background:#0a0a0a !important;}' +
      '#glossary-panel .glossary-header{border-bottom:1px solid rgba(244,202,72,0.35) !important;}' +
      '#glossary-panel .glossary-header h3{color:var(--sw-gold,#f4ca48) !important;}' +
      '#glossary-panel .glossary-close{color:var(--sw-gold,#f4ca48) !important;}' +
      '#glossary-panel .glossary-controls input,#glossary-panel .glossary-controls select{' +
        'background:var(--sw-navy-hover,#2a3050) !important;color:#fff0b8 !important;border:1px solid rgba(244,202,72,0.4) !important;}' +
      '#glossary-panel .glossary-controls input::placeholder{color:rgba(244,202,72,0.6);}' +
      '#glossary-panel .glossary-tab{background:var(--sw-navy-hover,#2a3050) !important;color:rgba(244,202,72,0.85) !important;border-color:rgba(244,202,72,0.35) !important;}' +
      '#glossary-panel .glossary-tab.active{background:var(--sw-gold,#f4ca48) !important;color:var(--sw-navy,#1e2233) !important;font-weight:700;}' +
      '#glossary-panel .glossary-entry{background:var(--sw-navy-hover,#2a3050);border:1px solid rgba(244,202,72,0.22);border-radius:10px;margin:6px 10px;padding:10px 12px;}' +
      '#glossary-panel .glossary-entry:hover{border-color:var(--sw-gold,#f4ca48);}' +
      '#glossary-panel .glossary-root{color:var(--sw-gold,#f4ca48) !important;}' +
      '#glossary-panel .glossary-count{color:var(--sw-navy,#1e2233) !important;background:var(--sw-gold,#f4ca48);border-radius:9px;padding:1px 8px;font-weight:700;}' +
      '#glossary-panel .glossary-meaning{color:#e8e0d0 !important;}' +
      '#glossary-panel .glossary-detail{color:rgba(232,224,208,0.85) !important;}' +
      '#glossary-panel .glossary-category-badge{background:rgba(244,202,72,0.15);color:var(--sw-gold,#f4ca48) !important;border:1px solid rgba(244,202,72,0.4);}' +
      '#glossary-panel .glossary-category-header{color:var(--sw-gold,#f4ca48) !important;border-bottom:1px solid rgba(244,202,72,0.3);}' +
      '#glossary-panel .glossary-form-chip{background:rgba(244,202,72,0.12);color:#fff0b8 !important;border:1px solid rgba(244,202,72,0.35);}' +
      '#glossary-panel .glossary-form-chip:hover{background:rgba(244,202,72,0.28);}' +
      '#glossary-panel .glossary-biblical-section{border-top:1px solid rgba(244,202,72,0.25);}' +
      '#glossary-panel .glossary-biblical-ref-key{color:var(--sw-gold,#f4ca48) !important;}' +
      '#glossary-panel .glossary-ref-link{color:var(--sw-gold,#f4ca48) !important;}' +
      '#glossary-panel .glossary-refs-book{color:#fff0b8 !important;}' +
      '#glossary-panel .glossary-highlight-btn{background:var(--sw-gold,#f4ca48) !important;color:var(--sw-navy,#1e2233) !important;border:none;}' +
      /* readable text everywhere on navy */
      '#glossary-panel .glossary-biblical-ref{color:#e8e0d0 !important;}' +
      '#glossary-panel .glossary-biblical-ref-note{color:rgba(232,224,208,0.88) !important;}' +
      '#glossary-panel .glossary-biblical-section{background:rgba(244,202,72,0.06) !important;border-color:rgba(244,202,72,0.25) !important;color:#e8e0d0 !important;}' +
      '#glossary-panel .glossary-biblical-section strong{color:var(--sw-gold,#f4ca48) !important;}' +
      '#glossary-panel .glossary-refs-section{border-top-color:rgba(244,202,72,0.25) !important;color:#e8e0d0 !important;}' +
      '#glossary-panel .glossary-refs-section > strong{color:var(--sw-gold,#f4ca48) !important;}' +
      '#glossary-panel .glossary-controls{color:#e8e0d0 !important;border-bottom-color:rgba(244,202,72,0.3) !important;}' +
      '#glossary-panel .glossary-sort{color:rgba(232,224,208,0.8) !important;}' +
      '#glossary-panel .glossary-detail strong{color:#fff0b8 !important;}' +
      '#glossary-panel .glossary-entry small{color:rgba(232,224,208,0.7);}' +
      '#glossary-panel{scrollbar-color:rgba(244,202,72,0.4) var(--sw-navy,#1e2233);}' +
      '#glossary-panel::-webkit-scrollbar-thumb{background:rgba(244,202,72,0.4);}' +
      '#glossary-panel::-webkit-scrollbar-track{background:var(--sw-navy,#1e2233);}' +
      /* ── Word scorecard popup: same navy + gold as the glossary and panel ── */
      '#word-popup{z-index:9500 !important;background:var(--sw-navy,#1e2233) !important;color:#e8e0d0 !important;' +
        'border:2px solid var(--sw-gold,#f4ca48) !important;box-shadow:0 12px 40px rgba(0,0,0,0.5) !important;}' +
      'body.dark-mode #word-popup{background:#0a0a0a !important;}' +
      '#word-popup .popup-hebrew,#word-popup #popup-hw{color:var(--sw-gold,#f4ca48) !important;}' +
      '#word-popup .popup-translit,#word-popup #popup-translit{color:rgba(232,224,208,0.75) !important;}' +
      '#word-popup .popup-gloss,#word-popup #popup-gl{color:var(--sw-gold-bright,#fff0b8) !important;}' +
      '#word-popup .popup-strong,#word-popup #popup-strong{color:rgba(232,224,208,0.85) !important;}' +
      '#word-popup .popup-detail,#word-popup #popup-detail{color:#e8e0d0 !important;}' +
      '#word-popup .popup-detail strong{color:var(--sw-gold-bright,#fff0b8) !important;}' +
      '#word-popup a{color:var(--sw-gold,#f4ca48) !important;}' +
      '#word-popup .popup-close{color:var(--sw-gold,#f4ca48) !important;}' +
      '#word-popup .popup-dismiss-mobile{background:var(--sw-gold,#f4ca48) !important;color:var(--sw-navy,#1e2233) !important;border:none !important;font-weight:700;}' +
      /* the tappable Root link: light blue for contrast on navy */
      '#word-popup .rsc-root{color:#9cc7f0 !important;}' +
      '#word-popup .rsc-refs-link{color:var(--sw-gold,#f4ca48) !important;}' +
      /* ── Phone sizing: the scorecard inherited a small em base from the popup ── */
      '@media (max-width:600px){' +
        '#word-popup{font-size:17px !important;line-height:1.5 !important;' +
          'width:min(94vw,440px) !important;max-width:94vw !important;' +
          'max-height:80vh !important;overflow-y:auto !important;-webkit-overflow-scrolling:touch;' +
          'padding-bottom:calc(12px + env(safe-area-inset-bottom,0px)) !important;}' +
        '#word-popup .popup-hebrew,#word-popup #popup-hw{font-size:1.6em !important;line-height:1.4 !important;}' +
        '#word-popup .popup-gloss,#word-popup #popup-gl{font-size:1.1em !important;}' +
        '#word-popup .popup-translit,#word-popup #popup-translit{font-size:0.95em !important;}' +
        '.rsc-chips{gap:6px;margin:8px 0;}' +
        '.rsc-chip{font-size:0.95em;padding:5px 11px;border-radius:13px;}' +
        '.rsc-refs-link{font-size:1em !important;display:inline-block;padding:9px 2px;min-height:44px;}' +
        '#rsc-panel .rsc-panel-card{width:96vw;max-height:88vh;}' +
        '#rsc-panel .rsc-panel-body{font-size:17px;line-height:1.55;' +
          'padding-bottom:calc(18px + env(safe-area-inset-bottom,0px));}' +
        '#rsc-panel .rsc-panel-title{font-size:1.15em;}' +
        '#rsc-panel .rsc-panel-meaning{font-size:0.95em;}' +
        '#rsc-panel .rsc-vol-title{font-size:1.05em;}' +
        '#rsc-panel .rsc-vol-count{font-size:0.9em;}' +
        '#rsc-panel a.rsc-ref{display:inline-block;padding:7px 6px;min-height:44px;min-width:34px;}' +
        '#rsc-panel .rsc-panel-close{font-size:32px;min-width:48px;min-height:48px;}' +
      '}';
    document.head.appendChild(st);
  }

  // ---------- glossary backend ----------
  // Entries shaped like the pages' legacy glossaryIndex, but sourced from the
  // cross-volume concordance so EVERY root in the corpus appears with its full
  // count — the glossary exists to justify each Hebrew word's usage.
  var glossaryCache = null;
  function glossaryEntries(excludeSet) {
    if (loadState !== 2) return null;
    if (glossaryCache) return glossaryCache;
    var conc = window._rootConcordance;
    var curated = window._rootGlossaryData || {};
    var out = [];
    for (var i = 0; i < conc.keys.length; i++) {
      var key = conc.keys[i];
      if (excludeSet && excludeSet.has && excludeSet.has(key)) continue;
      var entry = conc.roots[i];
      var total = 0;
      for (var v = 0; v < entry.c.length; v++) total += entry.c[v];
      var d = rootDisplay(key);
      var cons = d.heb.replace(/[֑-ֽֿ-׀׃-ׇ]/g, '');
      var cInfo = curated[cons] || curated[key] || {};
      var meaning = cInfo.meaning || d.meaning;
      if (!meaning) {
        var topG = '', topN = 0;
        for (var g in entry.g) if (entry.g[g] > topN) { topN = entry.g[g]; topG = g; }
        meaning = topG.replace(/^(and |the |to |in |from |as |that |by |for |with |a |an )+/g, '');
      }
      var chips = '<div class="rsc-chips">';
      VOL_ORDER.forEach(function(vk, vi) {
        var n = entry.c[vi];
        if (!n) return;
        chips += '<span class="rsc-chip' + (vk === cfg.vol ? ' rsc-chip-here' : '') + '">' +
          esc((conc.volNames || {})[vk] || vk) + ' ' + n + '</span>';
      });
      chips += '</div><span class="rsc-gloss-refs" data-rsc-idx="' + i +
        '" style="cursor:pointer;color:var(--accent,#d4af37);text-decoration:underline;font-size:0.9em;">View all references →</span>';
      out.push({
        root: key,
        displayHeb: d.heb,
        displayTranslit: d.translit,
        meaning: meaning || '',
        category: cInfo.category || 'Uncategorized',
        count: total,
        forms: entry.f || {},
        glosses: entry.g || {},
        exampleVerse: '',
        verseRefs: {},
        biblicalRefs: cInfo.biblicalRefs || [],
        _rscIdx: i,
        _rscChips: chips
      });
    }
    glossaryCache = out;
    return out;
  }
  // Delegated click: "View all references" inside glossary entries
  document.addEventListener('click', function(e) {
    var el = e.target && e.target.closest ? e.target.closest('.rsc-gloss-refs') : null;
    if (!el) return;
    e.stopPropagation();
    openPanel(parseInt(el.getAttribute('data-rsc-idx'), 10));
  }, true);

  window.RootScorecard = {
    init: function(options) {
      cfg.vol = options.vol || '';
      cfg.base = options.base || '';
      injectCss();
    },
    ensure: ensure,
    ensureRefs: ensureRefs,
    ready: function() { return loadState === 2; },
    lookup: lookup,
    fill: fill,
    glossaryEntries: glossaryEntries,
    openPanel: openPanel,
    closePanel: closePanel
  };
})();
