/**
 * root_scorecard.js — the shared word-scorecard engine for all six scripture pages.
 *
 * Fixes two long-standing popup bugs:
 *   1. Counts were per-page: the BOM lazy-loads one book at a time so its popup
 *      counted only the loaded book ("Occurrences: 1"); the OT counted only the
 *      OT, the NT only the NT — nothing communicated.
 *   2. The root key drifted: pages keyed their frequency maps before Strong's
 *      data loaded (heuristic stems) but computed popup roots after (H-numbers),
 *      so the lookup missed entirely.
 *
 * This engine resolves every word through root_engine.js (the canonical
 * getRoot, generated from bom/bom.html with Strong's guaranteed loaded) against
 * root_concordance.js (counts, forms, glosses across OT+NT+BOM+D&C+PGP+JST,
 * generated by tools/build_root_concordance.js). Verse references live in
 * root_concordance_refs.js, loaded only when the references panel opens.
 *
 * Page integration:
 *   RootScorecard.init({ vol: 'bom', base: '../' });
 *   ...popup builds its legacy detail inside <div class="rsc-slot">…</div>...
 *   RootScorecard.fill(slotEl, surfaceHebrew);
 */
(function() {
  'use strict';
  var RSC_V = '85';   // bump when the generated data files change
  // Transliterated terms — an exception table in the tool, like the received
  // spellings in transliterate(): keyed by bare consonants, so every pointing
  // and any one prefix letter (בְּאָדָם־אוֹנְדִּי־אַהְמָן in a heading) matches.
  // A listed word is not Hebrew: the reader draws a mark beside it, this card
  // says so, the root engine skips it, and tools/build_root_concordance.js
  // parses this same line so the concordance never files Ahman under Haman.
  // ONE LINE, VALID JSON — the builder reads it with JSON.parse.
  var TRANSLIT_TERMS = {"אדםאונדיאהמן":"Adam-ondi-Ahman","אהמן":"Ahman","שדולמק":"Shedolamak"};
  function ttSkel(s) { return String(s || '').replace(/[\u0591-\u05C7]/g, '').replace(/[׃\[\]"'`.,;:?!()*]/g, ''); }
  function ttKey(part) {
    if (TRANSLIT_TERMS[part]) return part;
    if (/^[בכלמוהש]/.test(part) && TRANSLIT_TERMS[part.slice(1)]) return part.slice(1);
    return '';
  }
  // {all: every maqqef-part is a term, parts: [surface parts that are terms]}
  function translitTermParts(surface) {
    var raw = String(surface || '').replace(/[׃\[\]*]/g, '').split(/[־\s]+/).filter(Boolean);
    var whole = ttSkel(raw.join(''));
    if (raw.length > 1 && ttKey(whole)) return { all: true, parts: [raw.join('־')] };
    var parts = [];
    for (var i = 0; i < raw.length; i++) if (ttKey(ttSkel(raw[i]))) parts.push(raw[i]);
    return { all: raw.length > 0 && parts.length === raw.length, parts: parts };
  }
  function isTranslitTerm(surface) { return translitTermParts(surface).parts.length > 0; }
  function ttNoteHtml(surface) {
    var tt = translitTermParts(surface);
    return tt.parts.map(function(p) {
      var name = TRANSLIT_TERMS[ttKey(ttSkel(p.split(/[־\s]+/).join('')))] || '';
      return '<span class="tt-note">' + (name ? '<b>' + esc(name) + '</b> \u2014 ' : '') +
        'transliterated term: carried over from the English as it sounds, not a Hebrew word. It has no Hebrew root and no Strong\u2019s number.</span>';
    }).join('<br>');
  }

  var cfg = { vol: '', base: '' };
  var keyIdx = null;         // rootKey -> index, built once
  var pendingFills = [];     // fills requested before data ready
  var loadState = 0;         // 0 idle, 1 loading, 2 ready
  var refsState = 0;
  var refsWaiters = [];

  var PAGES = { ot: 'ot.html', nt: 'nt.html', bom: 'bom/bom.html', dc: 'dc.html', pgp: 'pgp.html', jst: 'jst.html' };

  /* Warmup: pull the tap-time data in the background so the lazy split never
     costs the reader a slow first word card.

     It used to be an unconditional timer, which quietly undid the lazy split
     it was there to support: ~7 MB of Strong's, roots, glossary and
     concordance downloaded on EVERY page view, whether or not the reader ever
     tapped a word. On a phone on cellular that is the whole point of the split
     spent on nothing.

     Now it waits for a sign the reader is actually reading — a scroll or a
     touch — and stands down entirely on a metered or slow connection, where
     the cost is highest and the benefit (a faster first popup) is worth least.
     Tapping a word still calls ensure() directly, so the data always arrives
     when it is genuinely needed; the warmup only decides whether to be early. */
  (function scheduleWarmup() {
    var done = false;
    function metered() {
      var c = navigator.connection || navigator.mozConnection || navigator.webkitConnection;
      if (!c) return false;
      if (c.saveData) return true;
      return /(^|-)(2g|slow-2g)$/.test(c.effectiveType || '');
    }
    function kick() {
      if (done) return;
      done = true;
      ['scroll', 'touchstart', 'pointerdown', 'keydown'].forEach(function (ev) {
        window.removeEventListener(ev, kick, true);
      });
      if (metered()) return;
      var run = function () { try { ensure(function () {}); } catch (e) {} };
      if ('requestIdleCallback' in window) requestIdleCallback(run, { timeout: 8000 });
      else setTimeout(run, 2000);
    }
    ['scroll', 'touchstart', 'pointerdown', 'keydown'].forEach(function (ev) {
      window.addEventListener(ev, kick, { capture: true, passive: true });
    });
    // A reader who opens a chapter and simply reads without scrolling still
    // gets it, just later than an unconditional 3.5s timer would have.
    setTimeout(kick, 15000);
  })();

  var VOL_ORDER = ['ot', 'nt', 'bom', 'dc', 'pgp', 'jst'];

  function loadScript(src, cb) {
    var el = document.createElement('script');
    el.src = src; el.async = true;
    el.onload = function() { cb && cb(); };
    el.onerror = function() { console.warn('[RootScorecard] failed to load', src); cb && cb(); };
    document.head.appendChild(el);
  }

  function ensureStrongs(cb) {
    // Since 2026-08-30 the five sibling pages no longer load ANY root data
    // eagerly — ~4MB of Strong's/BDB/shoroshim/glossary parses only when a
    // word is first tapped (or in the idle warmup below). Load whatever is
    // missing; each file is guarded by its own global so bom.html (still
    // eager) and warm caches skip straight through.
    if (typeof window.ensureStrongsData === 'function' && !(window._strongsLookup && window._strongsRoots)) {
      window.ensureStrongsData(function () { ensureStrongs(cb); });
      return;
    }
    var need = [];
    if (!window._strongsLookup)   need.push('strongs_lookup.js?v=3');
    if (!window._strongsRoots)    need.push('strongs_roots.js?v=2');
    if (!window._bdbRoots)        need.push('bdb_roots.js?v=4');
    if (!window._rootProperNames) need.push('root_names.js?v=17');
    if (!window._shoroshimRoots)  need.push('shoroshim_roots.js?v=3');
    if (!window._rootGlossaryData) need.push('bom/roots_glossary.js?v=' + RSC_V);
    if (!window._attestedForms)   need.push('attested_forms.js?v=' + RSC_V);   // the Masoretic Text's own parse of every attested form
    if (!need.length) { cb(); return; }
    var n = 0;
    function done() { if (++n >= need.length) cb(); }
    need.forEach(function (f) { loadScript(cfg.base + f, done); });
  }

  function ensure(cb) {
    if (loadState === 2) { cb(); return; }
    pendingFills.ensureCbs = pendingFills.ensureCbs || [];
    pendingFills.ensureCbs.push(cb);
    if (loadState === 1) return;
    loadState = 1;
    ensureStrongs(function() {
      var n = 0;
      function done() {
        if (++n < 2) return;
        if (window._rootConcordance && window.RootEngine) {
          keyIdx = {};
          var keys = window._rootConcordance.keys;
          for (var i = 0; i < keys.length; i++) keyIdx[keys[i]] = i;
          loadState = 2;
        } else {
          loadState = 0;   // allow retry
        }
        var cbs = pendingFills.ensureCbs || [];
        pendingFills.ensureCbs = [];
        cbs.forEach(function(f) { try { f(); } catch (e) {} });
      }
      if (window.RootEngine) { n++; } else loadScript(cfg.base + 'root_engine.js?v=' + RSC_V, done);
      if (window._rootConcordance) { n++; } else loadScript(cfg.base + 'root_concordance.js?v=' + RSC_V, done);
      if (n >= 2) done();
    });
  }

  function ensureRefs(cb) {
    if (refsState === 2 || window._rootConcordanceRefs) { refsState = 2; cb(); return; }
    refsWaiters.push(cb);
    if (refsState === 1) return;
    refsState = 1;
    loadScript(cfg.base + 'root_concordance_refs.js?v=' + RSC_V, function() {
      refsState = window._rootConcordanceRefs ? 2 : 0;
      var w = refsWaiters; refsWaiters = [];
      w.forEach(function(f) { try { f(); } catch (e) {} });
    });
  }

  function esc(s) {
    return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }
  function cleanSurface(s) {
    // sof pasuq + ketiv/qere brackets never reach the root key
    return String(s || '').replace(/[׃\[\]*]/g, '').trim();
  }

  function lookup(surface) {
    if (loadState !== 2) return null;
    var s = cleanSurface(surface);
    if (!s) return null;
    var root = window.RootEngine.getRoot(s);
    var idx = keyIdx[root];
    if (idx === undefined) return null;
    return { idx: idx, key: root, entry: window._rootConcordance.roots[idx] };
  }

  // A maqqef joins two words and each is its own lexeme, so each gets its own
  // scorecard block: רַב־עֳנִי shows רַב "much" and עֳנִי "affliction".
  function lookupAll(surface) {
    if (loadState !== 2) return [];
    var s = cleanSurface(surface);
    if (!s) return [];
    var parts = (window.RootEngine && window.RootEngine.getRoots)
      ? window.RootEngine.getRoots(s) : [{ part: s, root: window.RootEngine.getRoot(s) }];
    var out = [];
    for (var i = 0; i < parts.length; i++) {
      var idx = keyIdx[parts[i].root];
      if (idx === undefined) continue;
      out.push({ part: parts[i].part, idx: idx, key: parts[i].root,
                 entry: window._rootConcordance.roots[idx] });
    }
    return out;
  }

  function _strongsConsIdx() {
    // consonantal lemma -> best Strong's entry (primitive roots first).
    // Built once; used as the meaning fallback for bare-consonant root keys,
    // so a family like נעמ shows a definition even with no curated entry.
    if (window._strongsConsIdxCache) return window._strongsConsIdxCache;
    var idx = {}, S = window._strongsRoots || {};
    var fin = { 'ך':'כ','ם':'מ','ן':'נ','ף':'פ','ץ':'צ' };
    var strip = function (w) { return String(w || '').replace(/[\u0591-\u05C7]/g, '')
                             .replace(/[ךםןףץ]/g, function (c) { return fin[c]; }); };
    for (var n in S) {
      var c = strip(S[n].w);
      if (!c) continue;
      var cur = idx[c];
      if (!cur) { idx[c] = n; continue; }
      var better = (S[n].p && !S[cur].p) ||
                   (!!S[n].p === !!S[cur].p && S[n].g && !S[cur].g);
      if (better) idx[c] = n;
    }
    // Second pass: matres lectionis hide exact matches (אדן vs אָדוֹן), so
    // index the lemmas again with non-initial vav/yod removed. Only consulted
    // when the exact index misses, and only for residues of 3+ letters.
    var idx2 = {};
    for (var n2 in S) {
      var c2 = strip(S[n2].w);
      if (!c2) continue;
      var d = c2.charAt(0) + c2.slice(1).replace(/[וי]/g, '');
      if (d.length < 3 || idx2[d]) continue;
      idx2[d] = idx[c2] || n2;
    }
    window._strongsConsIdxCache = { exact: idx, demater: idx2 };
    return window._strongsConsIdxCache;
  }
  function _strongsForCons(key) {
    var c = _strongsConsIdx();
    var fin = { 'ך':'כ','ם':'מ','ן':'נ','ף':'פ','ץ':'צ' };
    var k = String(key || '').replace(/[ךםןףץ]/g, function (ch) { return fin[ch]; });
    if (c.exact[k]) return c.exact[k];
    var d = k.charAt(0) + k.slice(1).replace(/[וי]/g, '');
    return d.length >= 3 ? c.demater[d] : null;
  }
  function _strongsGloss(num) {
    // Follow the root/usage pointers when an entry has no gloss of its own
    // (Aramaic forms point at their Hebrew twin: H8065 heavens -> H8064).
    var S = window._strongsRoots || {};
    var seen = {};
    while (num && S[num] && !seen[num]) {
      seen[num] = 1;
      if (S[num].g) return S[num].g;
      num = S[num].r || S[num].u;
    }
    return '';
  }
  function rootDisplay(key) {
    var heb = key, translit = '', meaning = '';
    if (/^H\d+$/.test(key) && window._strongsRoots && window._strongsRoots[key]) {
      var e = window._strongsRoots[key];
      heb = e.w || key; meaning = e.g || _strongsGloss(e.r || e.u) || '';
      // The site's own transliteration, matching the reader line — not Strong's
      // scholarly one (ʼâçaph): laymen read "asaf", not diacritics.
      if (typeof window.transliterate === 'function') { try { translit = window.transliterate(heb); } catch (eT) {} }
      if (!translit) translit = e.x || '';
      // Strip the shin/sin dots too (U+05C1-2). The maqqef-preserving range
      // used elsewhere leaves them on, so שׁוּב keyed as 4 characters and never
      // matched the glossary's 3-character שוב — the override silently missed
      // and Strong's crude gloss won. That hid the real meaning of all 418
      // roots containing ש: שׁוּב showed "again" instead of "to return, repent".
      var gd = window._rootGlossaryData || {};
      // Exact key first: an entry stored under the Strong's number belongs to
      // this family unambiguously.
      var cur = gd[key];
      if (!cur) {
        var cons = heb.replace(/[\u0591-\u05BD\u05BF-\u05C7]/g, '');
        // A bare-consonant glossary entry describes the bare-consonant FAMILY.
        // When that family exists separately in the concordance, its meaning
        // must not leak onto a Strong's-keyed homograph: H1319 "gospel" was
        // showing "flesh" because בשר (the flesh family) shares its consonants.
        var rc = window._rootConcordance;
        var claimed = rc && rc.keys && rc.keys.indexOf(cons) >= 0;
        if (!claimed) cur = gd[cons];
      }
      if (cur && cur.meaning) meaning = cur.meaning;
    } else {
      // A bare consonantal root transliterates to nothing readable, so use
      // BDB's vocalised spelling of it where we have one: אבה -> אָבָה, which
      // the site's own transliterate() renders the same way it does the text.
      var _pf = (window._bdbRootForms || {})[key];
      if (_pf) heb = _pf;
      else if (window.RootEngine && window.RootEngine.toSofit) heb = window.RootEngine.toSofit(key);
      var cur2 = (window._rootGlossaryData || {})[key];
      if (cur2 && cur2.meaning) meaning = cur2.meaning;
      if (!meaning || heb === key) {
        // The lemma lookup must run for the DISPLAY even when the glossary
        // already supplied a meaning — gated on meaning alone, a family with
        // a curated meaning skipped straight to the most-frequent form and
        // an inflected surface served as the "root" (וְתוֹעֲבוֹתֵיהֶם for תעב).
        var sNum = _strongsForCons(key);
        if (sNum) {
          if (!meaning) meaning = window._strongsRoots[sNum].g || _strongsGloss(sNum);
          if (heb === key && window._strongsRoots[sNum].w) heb = window._strongsRoots[sNum].w;
        }
      }
      if (heb === key) {
        // Still the unpointed key (a surface word the resolver could not file
        // under a lemma): show the family's own most frequent POINTED form, so
        // the transliteration is a real word and not consonant soup.
        try {
          var rc2 = window._rootConcordance;
          var ix2 = rc2 && rc2.keys ? rc2.keys.indexOf(key) : -1;
          if (ix2 >= 0 && rc2.roots[ix2] && rc2.roots[ix2].f) {
            // Root-closest form, not most-frequent: the most frequent form is
            // often an inflected one wearing a conjunction and suffixes.
            // Fewest consonants wins; frequency only breaks ties.
            var bf = '', bn = -1, bl = 1e9, fmap = rc2.roots[ix2].f;
            for (var fk in fmap) {
              var fl = fk.replace(/[֑-ׇ]/g, '').length;
              if (fl < bl || (fl === bl && fmap[fk] > bn)) { bl = fl; bn = fmap[fk]; bf = fk; }
            }
            if (bf) heb = bf;
          }
        } catch (e3) {}
      }
      if (typeof window.transliterate === 'function') { try { translit = window.transliterate(heb); } catch (e2) {} }
    }
    return { heb: heb, translit: translit, meaning: meaning };
  }

  function bookNameFor(vol, chapId) {
    if (vol === 'dc') {
      var md = chapId.match(/^dc(\d+)/);
      if (md) return 'D&C ' + md[1];
      var mo = chapId.match(/^od(\d+)/);
      if (mo) return 'OD ' + mo[1];
      return chapId;
    }
    var list = (window._rootConcordance.books || {})[vol] || [];
    for (var i = 0; i < list.length; i++) {
      if (chapId.indexOf(list[i].p) === 0) return list[i].n;
    }
    return chapId;
  }
  function chapterLabel(vol, chapId) {
    var book = bookNameFor(vol, chapId);
    if (vol === 'dc') return book;                       // D&C 76 (section is the chapter)
    var mf = chapId.match(/fac(\d+)$/);
    if (mf) return book + ' Facsimile ' + mf[1];
    var mc = chapId.match(/ch(\d+)$/);
    return mc ? book + ' ' + mc[1] : book + ' ' + chapId;
  }
  function refHref(vol, chapId, v) {
    var deep = vol === 'bom' ? (chapId + (v ? ':' + v : '')) : (chapId + (v ? '&v=' + v : ''));
    if (vol === cfg.vol) return '#' + deep;
    return cfg.base + PAGES[vol] + '#' + deep;
  }

  // ---------- the morphology code, read into words ----------
  // OSHB / TAHOT scheme (morphhb/parsing/HebrewMorphologyCodes.html): one
  // language letter, then one code per segment separated by "/": part of
  // speech, then type or stem, then conjugation, person, gender, number, state.
  var MORPH_STEM = { q: 'qal', N: 'niphal', p: 'piel', P: 'pual', h: 'hiphil', H: 'hophal', t: 'hithpael',
    o: 'polel', O: 'polal', r: 'hithpolel', m: 'poel', M: 'poal', k: 'palel', K: 'pulal', Q: 'qal passive',
    l: 'pilpel', L: 'polpal', f: 'hithpalpel', D: 'nithpael', j: 'pealal', i: 'pilel', u: 'hothpaal',
    c: 'tiphil', v: 'hishtaphel', w: 'nithpalel', y: 'nithpoel', z: 'hithpoel' };
  var MORPH_CONJ = { p: 'perfect', q: 'sequential perfect', i: 'imperfect', w: 'sequential imperfect (wayyiqtol)',
    h: 'cohortative', j: 'jussive', v: 'imperative', r: 'participle', s: 'passive participle',
    a: 'infinitive absolute', c: 'infinitive construct' };
  var MORPH_POS = { A: 'adjective', C: 'conjunction', D: 'adverb', N: 'noun', P: 'pronoun', R: 'preposition',
    S: 'suffix', T: 'particle', V: 'verb' };
  var MORPH_TYPE = { A: { a: '', c: 'cardinal', g: 'gentilic', o: 'ordinal' },
    N: { c: '', g: 'gentilic', p: 'proper name' },
    P: { d: 'demonstrative', f: 'indefinite', i: 'interrogative', p: 'personal', r: 'relative' },
    R: { d: 'with the article' },
    S: { d: 'directional he', h: 'paragogic he', n: 'paragogic nun', p: 'pronominal suffix' },
    T: { a: 'affirmation', d: 'definite article', e: 'exhortation', i: 'interrogative', j: 'interjection',
         m: 'demonstrative', n: 'negative', o: 'object marker', r: 'relative' } };
  var MORPH_PGN = { '1': '1st', '2': '2nd', '3': '3rd', m: 'masc.', f: 'fem.', c: 'common', b: 'both',
    s: 'sing.', p: 'plur.', d: 'dual', a: 'absolute', 'c_': 'construct', 'd_': 'determined' };
  function morphSeg(code) {
    if (!code) return '';
    var pos = code.charAt(0), rest = code.slice(1), out = [];
    if (pos === 'V') {
      out.push(MORPH_STEM[rest.charAt(0)] || '');
      out.push(MORPH_CONJ[rest.charAt(1)] || '');
      var pgn = rest.slice(2);
      var f = [];
      for (var i = 0; i < pgn.length; i++) {
        var ch = pgn.charAt(i);
        if (i === 0 && /[123]/.test(ch)) f.push(MORPH_PGN[ch]);
        else if (/[mfcb]/.test(ch) && f.length < 2 && !/plur|sing|dual/.test(f.join(' '))) f.push(MORPH_PGN[ch]);
        else if (/[spd]/.test(ch) && !/plur|sing|dual/.test(f.join(' '))) f.push(MORPH_PGN[ch]);
        else if (/[acd]/.test(ch)) f.push(ch === 'c' ? 'construct' : ch === 'd' ? 'determined' : 'absolute');
      }
      return (out.join(' ') + ' ' + f.join(' ')).replace(/\s+/g, ' ').trim();
    }
    var name = MORPH_POS[pos] || pos, t = (MORPH_TYPE[pos] || {})[rest.charAt(0)];
    var tail = rest.slice(1), g = [];
    if (t !== undefined) { if (t) g.push(t); } else tail = rest;
    for (var k = 0; k < tail.length; k++) {
      var c2 = tail.charAt(k), pos_ = k;
      if (/[123]/.test(c2)) g.push(MORPH_PGN[c2]);
      else if (/[mfcb]/.test(c2) && pos_ <= 1) g.push(MORPH_PGN[c2]);
      else if (/[spd]/.test(c2) && pos_ <= 2) g.push(MORPH_PGN[c2]);
      else if (/[acd]/.test(c2)) g.push(c2 === 'c' ? 'construct' : c2 === 'd' ? 'determined' : 'absolute');
    }
    return (name + ' ' + g.join(' ')).replace(/\s+/g, ' ').trim();
  }
  function morphLabel(code) {
    var segs = String(code || '').replace(/^[HA]/, '').split('/');
    var lang = /^A/.test(code) ? 'Aramaic ' : '';
    return lang + segs.map(morphSeg).filter(Boolean).join(' + ');
  }

  // ---------- popup slot ----------
  function detailHtml(found, surface, glossText) {
    var entry = found.entry;
    var d = rootDisplay(found.key);
    var conc = window._rootConcordance;
    var total = 0, totalVerses = 0;
    entry.c.forEach(function(n) { total += n; });
    entry.vc.forEach(function(n) { totalVerses += n; });
    var h = '';
    h += '<span class="rsc-root" style="cursor:pointer;text-decoration:none;color:var(--tap-blue,var(--here));">Root ' +
      '<span style="font-family:\'David Libre\',serif">' + esc(d.heb) + '</span>' +
      (d.translit ? ' <span style="font-size:0.85em;opacity:0.7;">(' + esc(d.translit) + ')</span>' : '') +
      '</span> — ' + total + ' uses in ' + totalVerses + ' verses across the scriptures';
    if (d.meaning) h += '<br><span style="font-style:italic;opacity:0.85;font-size:0.9em;">' + esc(d.meaning) + '</span>';
    // THE PARSE, where the Masoretic Text attests this exact form: the analysis
    // the OpenScriptures Hebrew Bible / STEPBible give it (attested_forms.js,
    // via RootEngine.parse), read into words, with the source's cut between
    // prefix, stem and suffix. Absent for a form the Tanakh does not have.
    var pz = null;
    try { pz = window.RootEngine && window.RootEngine.parse && window.RootEngine.parse(surface); } catch (e) { pz = null; }
    if (pz && pz.morph) {
      var pl = morphLabel(pz.morph);
      h += '<br><span style="font-size:0.9em;opacity:0.9;"><b>Parse:</b> ' + esc(pl) +
        (pz.segments ? ' · <span style="font-family:\'David Libre\',serif">' + esc(pz.segments.replace(/\//g, ' · ')) + '</span>' : '') +
        (pz.n ? ' <span style="opacity:0.65;">(' + pz.n + 'x in the Tanakh)</span>' : '') + '</span>';
    }
    // per-volume chips
    h += '<div class="rsc-chips">';
    VOL_ORDER.forEach(function(vk, vi) {
      var n = entry.c[vi];
      if (!n) return;
      var label = (conc.volNames || {})[vk] || vk.toUpperCase();
      h += '<span class="rsc-chip' + (vk === cfg.vol ? ' rsc-chip-here' : '') + '">' + esc(label) + ' ' + n + '</span>';
    });
    h += '</div>';
    // The tapped word itself always appears in both lists. The concordance
    // keeps only the six commonest forms and ten commonest glosses per root,
    // so an idiomatic rendering (לְעֵינַיִם "plainly" under עַיִן "eye") used
    // to vanish from the card: the reader saw "plainly" as the definition and
    // a root that admitted only "in the eyes of". Now the form and the gloss
    // of this very token are appended — with their corpus count when the
    // concordance kept them, otherwise marked "here".
    var forms = Object.keys(entry.f || {});
    var hereForm = String(found.part || cleanSurface(surface) || '').replace(/\u05C3$/, '');
    var formItems = forms.map(function(f) {
      return '<span style="font-family:\'David Libre\',serif">' + esc(f) + '</span> (' + entry.f[f] + 'x)';
    });
    if (hereForm && forms.indexOf(hereForm) < 0) {
      formItems.push('<span style="font-family:\'David Libre\',serif">' + esc(hereForm) + '</span> (here)');
    }
    if (formItems.length > 1) h += '<span>Forms:</span> ' + formItems.join(', ') + '<br>';
    var glosses = Object.keys(entry.g || {});
    var shown = glosses.slice(0, 4);
    var hereGloss = String(glossText || '').replace(/^[\s"'.,;:?!()\u2014\u2013-]+|[\s"'.,;:?!()\u2014\u2013-]+$/g, '');
    var glossItems = shown.map(function(g) { return '"' + esc(g) + '" (' + entry.g[g] + 'x)'; });
    if (hereGloss) {
      var lc = hereGloss.toLowerCase(), hit = null;
      for (var gi = 0; gi < glosses.length; gi++) {
        if (glosses[gi].toLowerCase() === lc) { hit = glosses[gi]; break; }
      }
      if (hit && shown.indexOf(hit) < 0) glossItems.push('"' + esc(hit) + '" (' + entry.g[hit] + 'x)');
      else if (!hit) glossItems.push('"' + esc(hereGloss) + '" (here)');
    }
    if (glossItems.length > 1) h += '<span>Glossed:</span> ' + glossItems.join(', ') + '<br>';
    h += '<span class="rsc-refs-link">View all references →</span>';
    return h;
  }

  var fillToken = 0;
  function fill(slotEl, surface, glossText) {
    // Heading-flow tokens keep their sentence punctuation for display; it must
    // never reach the resolver (עֲלֵיהֶם. resolved to nothing and showed a bare
    // "Occurrences: 1").
    surface = String(surface || '').replace(/^[\s.,;:?!()]+|[\s.,;:?!()]+$/g, '');
    if (!slotEl) return;
    var tt = translitTermParts(surface);
    if (tt.all) { slotEl.innerHTML = ttNoteHtml(surface); return; }
    var ttHtml = tt.parts.length ? tt.parts.map(function(p) {
      return '<div class="rsc-block"><div class="rsc-part"><span style="font-family:\'David Libre\',serif">' + esc(p) + '</span></div>' + ttNoteHtml(p) + '</div>';
    }).join('') : '';
    var token = ++fillToken;
    var doFill = function() {
      if (token !== fillToken) return;                    // a newer popup superseded this one
      if (!document.contains(slotEl)) return;             // popup closed
      if (loadState !== 2) return;                        // load failed; keep legacy content
      var all = lookupAll(surface);
      if (!all.length) {
        // No concordance bucket — chapter-heading vocabulary (מילניום,
        // באמצעות...) lives only in the summaries, which the concordance
        // does not walk. The card used to stay bare ("Occurrences: 1", no
        // root — the בְּאוֹרְחָיו report). If the glossary knows the family,
        // render root + meaning without counts; otherwise keep legacy content.
        var s2 = cleanSurface(surface);
        var parts2 = (s2 && window.RootEngine && window.RootEngine.getRoots)
          ? window.RootEngine.getRoots(s2) : [];
        var mini = '';
        for (var pi2 = 0; pi2 < parts2.length; pi2++) {
          var k2 = parts2[pi2].root;
          if (!k2) continue;
          var d2 = rootDisplay(k2);
          if (!d2.meaning) continue;
          // A bare, unpointed family key transliterates to gibberish
          // (מילניום → "mayalanayavam"): show the tapped pointed surface
          // instead whenever the display form carries no nikkud of its own.
          var heb2 = d2.heb, tr2 = d2.translit;
          if (!/[ְ-ׇּׁׂ]/.test(heb2)) {
            heb2 = parts2[pi2].part;
            tr2 = '';
            if (typeof window.transliterate === 'function') { try { tr2 = window.transliterate(heb2); } catch (eT2) {} }
          }
          mini += '<div class="rsc-block">' +
            '<span class="rsc-root"><span style="font-family:\'David Libre\',serif">' + esc(heb2) + '</span>' +
            (tr2 ? ' <span style="font-size:0.85em;opacity:0.7;">(' + esc(tr2) + ')</span>' : '') + '</span>' +
            '<br><span style="font-style:italic;opacity:0.85;font-size:0.9em;">' + esc(d2.meaning) + '</span>' +
            '<div style="font-size:0.8em;opacity:0.6;margin-top:0.3em;">Chapter-heading vocabulary — no verse occurrences</div>' +
            '</div>';
        }
        if (mini || ttHtml) slotEl.innerHTML = mini + ttHtml;
        return;
      }
      var html = '';
      for (var bi = 0; bi < all.length; bi++) {
        html += '<div class="rsc-block" data-rsc-block="' + bi + '">';
        if (all.length > 1) {
          html += '<div class="rsc-part"><span style="font-family:\'David Libre\',serif">' +
                  esc(all[bi].part) + '</span></div>';
        }
        html += detailHtml(all[bi], surface, glossText) + '</div>';
      }
      slotEl.innerHTML = html + ttHtml;
      var blocks = slotEl.querySelectorAll('.rsc-block');
      for (var bj = 0; bj < blocks.length; bj++) {
        (function(blk, found) {
          var rootLink = blk.querySelector('.rsc-root');
          if (rootLink && typeof window.openGlossaryAtRoot === 'function') {
            rootLink.addEventListener('click', function(ev) {
              ev.stopPropagation();
              window.openGlossaryAtRoot(found.key);
            });
          }
          var refsLink = blk.querySelector('.rsc-refs-link');
          if (refsLink) {
            refsLink.addEventListener('click', function(ev) {
              ev.stopPropagation();
              if (typeof window.closePopup === 'function') { try { window.closePopup(); } catch (e) {} }
              openPanel(found.idx);
            });
          }
        })(blocks[bj], all[bj]);
      }
    };
    if (loadState === 2) { doFill(); return; }
    ensure(doFill);
  }

  // ---------- references panel ----------
  var panelEl = null;
  function buildPanel() {
    if (panelEl && !document.body.contains(panelEl)) panelEl = null;   // page code may have swept it
    if (panelEl) return panelEl;
    panelEl = document.createElement('div');
    panelEl.id = 'rsc-panel';
    panelEl.innerHTML =
      '<div class="rsc-panel-backdrop"></div>' +
      '<div class="rsc-panel-card" role="dialog" aria-label="All references">' +
        '<div class="rsc-panel-head">' +
          '<div class="rsc-panel-title"></div>' +
          '<button type="button" class="rsc-panel-close" aria-label="Close">×</button>' +
        '</div>' +
        '<div class="rsc-panel-body"></div>' +
      '</div>';
    document.body.appendChild(panelEl);
    panelEl.querySelector('.rsc-panel-backdrop').addEventListener('click', closePanel);
    panelEl.querySelector('.rsc-panel-close').addEventListener('click', closePanel);
    // Same-volume links: navigate via hash and close
    panelEl.addEventListener('click', function(e) {
      var a = e.target.closest ? e.target.closest('a.rsc-ref') : null;
      if (!a) return;
      if (a.getAttribute('href').charAt(0) === '#') closePanel();
      // cross-volume links navigate away naturally
    });
    return panelEl;
  }
  function closePanel() {
    if (panelEl) panelEl.classList.remove('open');
  }
  // ---------- interlinear rendering of a root's own verses ----------
  // The panel used to list "1 Nephi 2:1, 2 · 3:2 …" as links, so reading a
  // root's verses meant opening each one and losing your place. These render
  // inline, in batches, reusing the loader and renderer from crossrefs_engine.
  // Only list a reference the shared loader can actually fetch. Every volume is
  // in its map, so this now filters out nothing real — it stays as a guard.


  function canRenderRef(book, ch) {
    if (!book || !ch) return false;
    return !!(window.SWVerses && window.SWVerses.has(book, ch));
  }


  function collectVerseRefs(refs, order) {
    var out = [];
    if (!refs || refs._b) return out;              // book-level only: no verse refs stored
    order.forEach(function(vk) {
      var chObj = refs[vk];
      if (!chObj) return;
      Object.keys(chObj).forEach(function(chapId) {
        var m = chapId.match(/ch(\d+)/) || chapId.match(/(\d+)/);
        var ch = m ? parseInt(m[1], 10) : null;
        if (!ch) return;
        var book = bookNameFor(vk, chapId);
        if (!canRenderRef(book, ch)) return;   // keep only verses we can actually draw
        (chObj[chapId] || []).forEach(function(v) {
          out.push({ vol: vk, book: book, ch: ch, v: v });
        });
      });
    });
    return out;
  }

  function renderOneVerse(host, r) {
    if (!window.SWVerses) return;
    var card = document.createElement('div');
    card.className = 'rsc-il-card';
    card.innerHTML = '<div class="rsc-il-ref">' + esc(r.book + ' ' + r.ch + ':' + r.v) + '</div>' +
                     '<div class="rsc-il-body"><span class="rsc-il-load">Loading Hebrew…</span></div>';
    host.appendChild(card);
    window.SWVerses.get(r.book, r.ch, r.v, function(words) {
      var html = window.SWVerses.interlinearHtml(words);
      if (!html) { if (card.parentNode) card.parentNode.removeChild(card); return; }
      card.querySelector('.rsc-il-body').innerHTML = html;
    });
  }

  function appendInterlinearSection(body, refs, order) {
    if (!window.SWVerses) return;
    var list = collectVerseRefs(refs, order);
    if (!list.length) return;
    var wrap = document.createElement('div');
    wrap.className = 'rsc-il-wrap';
    var head = document.createElement('div');
    head.className = 'rsc-vol-title';
    head.textContent = 'The verses (' + list.length + ')';
    wrap.appendChild(head);
    var host = document.createElement('div');
    host.className = 'rsc-il-host';
    wrap.appendChild(host);
    var more = document.createElement('button');
    more.className = 'rsc-il-more';
    wrap.appendChild(more);
    body.insertBefore(wrap, body.firstChild);
    var i = 0, FIRST = 25, BATCH = 25;
    function renderNext() {
      var end = Math.min(i + (i === 0 ? FIRST : BATCH), list.length);
      for (; i < end; i++) renderOneVerse(host, list[i]);
      if (i >= list.length) { more.style.display = 'none'; return; }
      more.textContent = 'Show ' + Math.min(BATCH, list.length - i) + ' more of ' + (list.length - i) + ' remaining';
    }
    more.addEventListener('click', function(ev) { ev.stopPropagation(); renderNext(); });
    renderNext();
  }

  function openPanel(idx) {
    var conc = window._rootConcordance;
    var entry = conc.roots[idx];
    var d = rootDisplay(conc.keys[idx]);
    var p = buildPanel();
    p.querySelector('.rsc-panel-title').innerHTML =
      '<span style="font-family:\'David Libre\',serif;font-size:1.25em;">' + esc(d.heb) + '</span>' +
      (d.translit ? ' <span style="opacity:0.75;font-size:0.85em;">' + esc(d.translit) + '</span>' : '') +
      (d.meaning ? '<div class="rsc-panel-meaning">' + esc(d.meaning) + '</div>' : '');
    var body = p.querySelector('.rsc-panel-body');
    body.innerHTML = '<div class="rsc-loading">Loading references…</div>';
    p.classList.add('open');
    ensureRefs(function() {
      var refs = (window._rootConcordanceRefs || [])[idx];
      if (!refs) { body.innerHTML = '<div class="rsc-loading">No references found.</div>'; return; }
      var h = '';
      // Order volumes: current volume first, then canonical order
      var order = [cfg.vol].concat(VOL_ORDER.filter(function(v) { return v !== cfg.vol; }));
      if (refs._b) {
        // Too common for verse-level refs: per-book verse counts
        h += '<div class="rsc-note">This root is very common — showing verse counts by book.</div>';
        order.forEach(function(vk) {
          var bObj = refs._b[vk];
          if (!bObj) return;
          var vi = VOL_ORDER.indexOf(vk);
          h += '<div class="rsc-vol"><div class="rsc-vol-title">' + esc((conc.volNames || {})[vk] || vk) +
               ' <span class="rsc-vol-count">' + entry.c[vi] + ' uses · ' + entry.vc[vi] + ' verses</span></div><div class="rsc-books">';
          Object.keys(bObj).forEach(function(bp) {
            var name = vk === 'dc' ? (bp === 'od' ? 'Official Declarations' : 'D&C') : bookNameFor(vk, bp + (bp === 'ch' ? '1' : 'ch1'));
            h += '<span class="rsc-bookcount">' + esc(name) + ' · ' + bObj[bp] + '</span>';
          });
          h += '</div></div>';
        });
      } else {
        order.forEach(function(vk) {
          var chObj = refs[vk];
          if (!chObj) return;
          var vi = VOL_ORDER.indexOf(vk);
          h += '<div class="rsc-vol"><div class="rsc-vol-title">' + esc((conc.volNames || {})[vk] || vk) +
               ' <span class="rsc-vol-count">' + entry.c[vi] + ' uses · ' + entry.vc[vi] + ' verses</span></div>';
          // group chapters by book, preserve corpus order via books table order
          var byBook = {};
          var bookOrder = [];
          Object.keys(chObj).forEach(function(chapId) {
            var bn = bookNameFor(vk, chapId);
            if (!byBook[bn]) { byBook[bn] = []; bookOrder.push(bn); }
            byBook[bn].push(chapId);
          });
          bookOrder.forEach(function(bn) {
            h += '<div class="rsc-book"><span class="rsc-book-name">' + esc(bn) + '</span> ';
            var parts = [];
            byBook[bn].forEach(function(chapId) {
              var mc = chapId.match(/ch(\d+)$/);
              var mf = chapId.match(/fac(\d+)$/);
              var chNum = vk === 'dc' ? '' : (mf ? ('F' + mf[1]) : (mc ? mc[1] : chapId));
              var verses = chObj[chapId];
              var links = verses.map(function(v) {
                return '<a class="rsc-ref" href="' + esc(refHref(vk, chapId, v)) + '">' + v + '</a>';
              }).join(', ');
              parts.push((chNum ? chNum + ':' : '') + links);
            });
            h += parts.join(' · ') + '</div>';
          });
          h += '</div>';
        });
      }
      body.innerHTML = h;
      appendInterlinearSection(body, refs, order);
    });
  }

  // ---------- styles ----------
  /* injectCss() removed 2026-09-03 — its 104 rules moved to reader.css,
   for the same reason. */


  // ---------- glossary backend ----------
  // Entries shaped like the pages' legacy glossaryIndex, but sourced from the
  // cross-volume concordance so EVERY root in the corpus appears with its full
  // count — the glossary exists to justify each Hebrew word's usage.
  var glossaryCache = null;
  function glossaryEntries(excludeSet) {
    if (loadState !== 2) return null;
    if (glossaryCache) return glossaryCache;
    var conc = window._rootConcordance;
    var curated = window._rootGlossaryData || {};
    var out = [];
    for (var i = 0; i < conc.keys.length; i++) {
      var key = conc.keys[i];
      if (excludeSet && excludeSet.has && excludeSet.has(key)) continue;
      var entry = conc.roots[i];
      var total = 0;
      for (var v = 0; v < entry.c.length; v++) total += entry.c[v];
      var d = rootDisplay(key);
      var cons = d.heb.replace(/[֑-ֽֿ-׀׃-ׇ]/g, '');
      var cInfo = curated[cons] || curated[key] || {};
      var meaning = cInfo.meaning || d.meaning;
      if (!meaning) {
        var topG = '', topN = 0;
        for (var g in entry.g) if (entry.g[g] > topN) { topN = entry.g[g]; topG = g; }
        meaning = topG.replace(/^(and |the |to |in |from |as |that |by |for |with |a |an )+/g, '');
      }
      var chips = '<div class="rsc-chips">';
      VOL_ORDER.forEach(function(vk, vi) {
        var n = entry.c[vi];
        if (!n) return;
        chips += '<span class="rsc-chip' + (vk === cfg.vol ? ' rsc-chip-here' : '') + '">' +
          esc((conc.volNames || {})[vk] || vk) + ' ' + n + '</span>';
      });
      chips += '</div><span class="rsc-gloss-refs" data-rsc-idx="' + i +
        '">View all references →</span>';
      out.push({
        root: key,
        displayHeb: d.heb,
        displayTranslit: d.translit,
        meaning: meaning || '',
        category: cInfo.category || 'Uncategorized',
        count: total,
        forms: entry.f || {},
        glosses: entry.g || {},
        exampleVerse: '',
        verseRefs: {},
        biblicalRefs: cInfo.biblicalRefs || [],
        _rscIdx: i,
        _rscChips: chips
      });
    }
    glossaryCache = out;
    return out;
  }
  // Delegated click: "View all references" inside glossary entries
  document.addEventListener('click', function(e) {
    var el = e.target && e.target.closest ? e.target.closest('.rsc-gloss-refs') : null;
    if (!el) return;
    e.stopPropagation();
    openPanel(parseInt(el.getAttribute('data-rsc-idx'), 10));
  }, true);

  window.RootScorecard = {
    init: function(options) {
      cfg.vol = options.vol || '';
      cfg.base = options.base || '';
    },
    ensure: ensure,
    ensureRefs: ensureRefs,
    ready: function() { return loadState === 2; },
    lookup: lookup,
    fill: fill,
    glossaryEntries: glossaryEntries,
    isTranslitTerm: isTranslitTerm,
    translitTermParts: translitTermParts,
    ttNoteHtml: ttNoteHtml,
    openPanel: openPanel,
    closePanel: closePanel
  };
})();
