// generated by tools/build_heading_manifests.js — chapter summaries for hag.js
(function(){ var W = window;
  Object.assign(W._otChapterHeadings = W._otChapterHeadings || {}, {"Haggai 1":"Haggai exhorts the people to build the temple.","Haggai 2":"Haggai speaks about the Messiah—The Desire of All Nations will come—The Lord will give peace in His temple."});
  Object.assign(W._otChapterHeadingsHeb = W._otChapterHeadingsHeb || {}, {"Haggai 1":"חגי קורא לעם לבנות את בית המקדש׃","Haggai 2":"חגי מדבר על המשיח רצון כל העמים יבוא יהוה יתן שלום במקדשו׃"});
  Object.assign(W._otHeadingWords = W._otHeadingWords || {}, {"Haggai 1":[["חַגַּי","Haggai"],["קוֹרֵא","one crying"],["לָעָם","to the people"],["לִבְנוֹת","to build"],["אֶת",""],["בֵּית","the house of"],["הַמִּקְדָּשׁ","the sanctuary"],["׃",""]],"Haggai 2":[["חַגַּי","Haggai"],["מְדַבֵּר","speaks"],["עַל","upon"],["הַמָּשִׁיחַ","the Messiah"],["רְצוֹן","the will of"],["כׇּל","all"],["הָעַמִּים","the people"],["יָבוֹא","shall come"],["יְהֹוָה","the LORD"],["יִתֵּן","shall give"],["שָׁלוֹם","peace"],["בְּמִקְדָּשׁוֹ","in His sanctuary"],["׃",""]]});
})();
