# -*- coding: utf-8 -*-
"""D&C 29 Hebrew/English word pairs."""

dc29_ch1Verses = [
("א", [
    ("הַאֲזִינוּ","Listen"),
    ("לְקוֹל","to the voice of"),
    ("יֵשׁוּעַ","Jesus"),
    ("הַמָּשִׁיחַ","Christ"),
    ("גֹּאַלְכֶם","your Redeemer"),
    ("אֲנִי","the Great"),
    ("הוּא","I AM"),
    ("אֲשֶׁר","whose"),
    ("זְרוֹעַ","arm of"),
    ("רַחֲמָיו","mercy"),
    ("כִּפְּרָה","hath atoned"),
    ("עַל","for"),
    ("חַטֹּאתֵיכֶם","your sins"),
]),
("ב", [
    ("אֲשֶׁר","Who"),
    ("יְקַבֵּץ","will gather"),
    ("עַמּוֹ","his people"),
    ("כְּתַרְנְגֹלֶת","even as a hen"),
    ("אֶפְרוֹחֶיהָ","gathereth her chickens"),
    ("תַּחַת","under"),
    ("כְּנָפֶיהָ","her wings"),
    ("כָּל","even as many as"),
    ("אֲשֶׁר","will"),
    ("יִשְׁמְעוּ","hearken"),
    ("לְקוֹלִי","to my voice"),
    ("וְיִכָּנְעוּ","and humble themselves"),
    ("לְפָנַי","before me"),
    ("וְקֹרְאִים","and call"),
    ("אֵלַי","upon me"),
    ("בִּתְפִלָּה","in mighty"),
    ("עַצוּמָה","prayer"),
]),
("ג", [
    ("הִנֵּה","Behold"),
    ("אָמֵן","verily"),
    ("אָמֵן","verily"),
    ("אֲנִי","I"),
    ("אֹמֵר","say"),
    ("לָכֶם","unto"),
    ("כִּי","you"),
    ("בָּעֵת","that"),
    ("הַזֹּאת","at"),
    ("נִסְלְחוּ","this time"),
    ("לָכֶם","your sins"),
    ("חַטֹּאתֵיכֶם","are forgiven"),
    ("לָכֵן","you"),
    ("תְּקַבְּלוּ","therefore"),
    ("אֶת־הַדְּבָרִים","ye receive"),
    ("הָאֵלֶּה","these things"),
    ("אַךְ","but remember"),
    ("זִכְרוּ","to sin"),
    ("לְבִלְתִּי","no"),
    ("חֲטֹא","more"),
    ("עוֹד","lest perils"),
    ("פֶּן","shall"),
    ("יָבֹאוּ","come upon"),
    ("עֲלֵיכֶם","you"),
]),
("ד", [
    ("אָמֵן","Verily"),
    ("אֲנִי","I"),
    ("אֹמֵר","say"),
    ("לָכֶם","unto you"),
    ("כִּי","that"),
    ("נִבְחַרְתֶּם","ye are chosen"),
    ("מִן","out of"),
    ("הָעוֹלָם","the world"),
    ("לְהַשְׁמִיעַ","to declare"),
    ("בְּשׂוֹרָתִי","my gospel"),
    ("בְּקוֹל","with the sound of"),
    ("גִּילָה","rejoicing"),
    ("כְּקוֹל","as with the voice of"),
    ("שׁוֹפָר","a trump"),
]),
("ה", [
    ("הָרִימוּ","Lift up"),
    ("לְבַבְכֶם","your hearts"),
    ("וְשִׂמְחוּ","and be glad"),
    ("כִּי","for"),
    ("בְתוֹכְכֶם","I am"),
    ("אָנֹכִי","in your midst"),
    ("וּמֵלִיץ","and am"),
    ("אֲנִי","your advocate"),
    ("לָכֶם","with"),
    ("לִפְנֵי","the"),
    ("הָאָב","Father"),
    ("וְרְצוֹנוֹ","and it is his"),
    ("הַטּוֹב","good will"),
    ("לָתֵת","to give"),
    ("לָכֶם","you"),
    ("אֶת־הַמַּלְכוּת","the kingdom"),
]),
("ו", [
    ("וְכַכָּתוּב","And"),
    ("כָּל","as it is written"),
    ("אֲשֶׁר","Whatsoever"),
    ("תִּשְׁאֲלוּ","ye shall ask"),
    ("בֶּאֱמוּנָה","in faith"),
    ("מְאֻחָדִים","being united"),
    ("בִּתְפִלָּה","in prayer"),
    ("כְּמִצְוָתִי","according to my command"),
    ("תְּקַבֵּלוּ","ye shall receive"),
]),
("ז", [
    ("וְנִקְרֵאתֶם","And ye are called"),
    ("לְהָבִיא","to bring to pass"),
    ("קִבּוּץ","the gathering"),
    ("בְּחִירַי","of mine elect"),
    ("כִּי","for"),
    ("בְחִירַי","mine elect"),
    ("שֹׁמְעִים","hear"),
    ("קוֹלִי","my voice"),
    ("וְלֹא","and harden"),
    ("יְקַשּׁוּ","not"),
    ("אֶת־לִבָּם","their hearts"),
]),
("ח", [
    ("לָכֵן","Wherefore"),
    ("יָצְאָה","the decree hath gone forth"),
    ("הַגְּזֵרָה","from"),
    ("מֵאֵת","the"),
    ("הָאָב","Father"),
    ("לְהִקָּבֵץ","that"),
    ("אֶל","they shall be gathered"),
    ("מָקוֹם","in unto"),
    ("אֶחָד","one place"),
    ("עַל","upon"),
    ("פְּנֵי","the face of"),
    ("הָאָרֶץ","this"),
    ("הַזֹּאת","land"),
    ("לְהָכִין","to prepare"),
    ("לְבָבָם","their hearts"),
    ("וְלִהְיוֹת","and be prepared"),
    ("מוּכָנִים","in"),
    ("בַּכֹּל","all things"),
    ("לַיּוֹם","against"),
    ("אֲשֶׁר","the day when"),
    ("צָרָה","tribulation and"),
    ("וְשַׁמָּה","desolation"),
    ("יִשָּׁלְחוּ","are sent forth"),
    ("עַל","upon"),
    ("הָרְשָׁעִים","the wicked"),
]),
("ט", [
    ("כִּי","For"),
    ("קָרְבָה","the hour"),
    ("הַשָּׁעָה","is nigh"),
    ("וְהַיּוֹם","and the day"),
    ("מְמַהֵר","soon at hand"),
    ("לָבוֹא","when"),
    ("בְּבַשֵּׁל","the earth"),
    ("הָאָרֶץ","is ripe"),
    ("בָּשְׁלָה","and all"),
    ("הַגֵּאִים","the proud"),
    ("וְעֹשֵׂי","and they that do"),
    ("רִשְׁעָה","wickedly"),
    ("יִהְיוּ","shall be"),
    ("כְקַשׁ","as stubble"),
    ("וּשְׂרַפְתִּים","and I will burn them up"),
    ("נְאֻם","saith"),
    ("יְהוָה","the Lord"),
    ("צְבָאוֹת","of Hosts"),
    ("וְלֹא","that"),
    ("תִהְיֶה","wickedness"),
    ("רִשְׁעָה","shall not be"),
    ("עַל","upon"),
    ("הָאָרֶץ","the earth"),
]),
("י", [
    ("כִּי","For"),
    ("קָרְבָה","the hour"),
    ("הַשָּׁעָה","is nigh"),
    ("וַאֲשֶׁר","and that which"),
    ("דִּבְּרוּ","was spoken"),
    ("שְׁלִיחַי","by mine apostles"),
    ("יִתְמַלֵּא","must be fulfilled"),
    ("כִּי","for"),
    ("כַּאֲשֶׁר","as"),
    ("דִּבְּרוּ","they spoke"),
    ("כֵּן","so"),
    ("יִהְיֶה","shall it come to pass"),
]),
("יא", [
    ("כִּי","For"),
    ("אֶגָּלֶה","I will reveal"),
    ("מִן","myself from"),
    ("הַשָּׁמַיִם","heaven"),
    ("בְּכֹחַ","with power"),
    ("וּבְכָבוֹד","and great"),
    ("גָּדוֹל","glory"),
    ("עִם","with"),
    ("כָּל","all"),
    ("צְבָאָם","the hosts thereof"),
    ("וְאֶשְׁכֹּן","and dwell"),
    ("בְּצֶדֶק","in righteousness"),
    ("עִם","with"),
    ("אֲנָשִׁים","men"),
    ("עַל","on"),
    ("הָאָרֶץ","earth"),
    ("אֶלֶף","a thousand"),
    ("שָׁנִים","years"),
    ("וְהָרְשָׁעִים","and the wicked"),
    ("לֹא","shall"),
    ("יַעֲמֹדוּ","not stand"),
]),
("יב", [
    ("וְעוֹד","And again"),
    ("אָמֵן","verily"),
    ("אָמֵן","verily"),
    ("אֲנִי","I"),
    ("אֹמֵר","say"),
    ("לָכֶם","unto you"),
    ("יָצְאָה","and it hath gone forth"),
    ("גְזֵרָה","in a firm decree"),
    ("נֶאֱמָנָה","by the will of"),
    ("בִּרְצוֹן","the Father"),
    ("הָאָב","that"),
    ("כִּי","mine apostles"),
    ("שְׁלִיחַי","the Twelve"),
    ("שְׁנֵים","which were"),
    ("הֶעָשָׂר","with me"),
    ("אֲשֶׁר","in my ministry"),
    ("הָיוּ","at Jerusalem"),
    ("עָשָׂר","shall stand"),
    ("בְּשֵׁרוּתִי","at"),
    ("בִּירוּשָׁלַיִם","my right hand"),
    ("יַעַמְדוּ","at the day of"),
    ("לִימִינִי","my coming"),
    ("בְּיוֹם","in a pillar of"),
    ("בּוֹאִי","fire"),
    ("בְּעַמּוּד","being clothed with"),
    ("אֵשׁ","robes of"),
    ("לְבוּשֵׁי","righteousness"),
    ("בִּגְדֵי","with crowns"),
    ("צֶדֶק","upon"),
    ("וְעַטְרוֹת","their heads"),
    ("עַל","in glory"),
    ("רָאשָׁם","even as I am"),
    ("בְּכָבוֹד","to judge"),
    ("כָּמוֹנִי","the whole"),
    ("לִשְׁפֹּט","house of"),
    ("אֶת־כָּל","Israel"),
    ("בֵּית","even as many as"),
    ("יִשְׂרָאֵל","have"),
    ("כָּל","loved"),
    ("אֲשֶׁר","me"),
    ("וְשָׁמְרוּ","and kept"),
    ("מִצְוֹתַי","my commandments"),
    ("וְלֹא","and none"),
    ("אֲחֵרִים","else"),
]),
("יג", [
    ("כִּי","For"),
    ("שׁוֹפָר","a trump"),
    ("יִתָּקַע","shall sound"),
    ("אָרֹךְ","both long"),
    ("וְחָזָק","and loud"),
    ("כְּעַל","even as upon"),
    ("הַר","Mount"),
    ("סִינַי","Sinai"),
    ("וְכָל","and all"),
    ("הָאָרֶץ","the earth"),
    ("תִּרְעַשׁ","shall quake"),
    ("וְיָצְאוּ","and they shall come forth"),
    ("אָכֵן","yea even"),
    ("הַמֵּתִים","the dead"),
    ("אֲשֶׁר","which"),
    ("מֵתוּ","died"),
    ("בִּי","in me"),
    ("לְקַבֵּל","to receive"),
    ("עֲטֶרֶת","a crown of"),
    ("צְדָקָה","righteousness"),
    ("וְלִלְבֹּשׁ","and to be clothed upon"),
    ("כָּמוֹנִי","even as I am"),
    ("לִהְיוֹת","to be"),
    ("עִמִּי","with me"),
    ("לְמַעַן","that"),
    ("נִהְיֶה","we may be"),
    ("אֶחָד","one"),
]),
("יד", [
    ("אַךְ","But behold"),
    ("הִנֵּה","I"),
    ("אֲנִי","say"),
    ("אֹמֵר","unto you"),
    ("לָכֶם","that"),
    ("לִפְנֵי","before"),
    ("בוֹא","this great"),
    ("הַיּוֹם","day"),
    ("הַגָּדוֹל","shall come"),
    ("הַזֶּה","the sun"),
    ("יֶחְשַׁךְ","shall be darkened"),
    ("הַשֶּׁמֶשׁ","and the moon"),
    ("וְהַיָּרֵחַ","shall be turned"),
    ("יֵהָפֵךְ","into blood"),
    ("לְדָם","and the stars"),
    ("וְהַכּוֹכָבִים","shall fall"),
    ("יִפְּלוּ","from"),
    ("מִן","heaven"),
    ("הַשָּׁמָיִם","and there shall be"),
    ("וְיִהְיוּ","greater"),
    ("אֹתוֹת","signs in"),
    ("גְּדוֹלוֹת","heaven"),
    ("בַּשָּׁמַיִם","above"),
    ("מִמַּעַל","and in"),
    ("וּבָאָרֶץ","the earth"),
    ("מִתָּחַת","beneath"),
]),
("טו", [
    ("וְיִהְיֶה","And there shall be"),
    ("בְכִי","weeping"),
    ("וּמִסְפֵּד","and wailing"),
    ("בְּצִבְאוֹת","among the hosts of"),
    ("הָאָדָם","men"),
]),
("טז", [
    ("וּבָרָד","And there shall be"),
    ("כָּבֵד","a great"),
    ("יִשָּׁלַח","hailstorm sent forth"),
    ("לְהַשְׁמִיד","to destroy"),
    ("אֶת־יְבוּל","the crops of"),
    ("הָאָרֶץ","the earth"),
]),
("יז", [
    ("וְהָיָה","And it shall come to pass"),
    ("מִפְּנֵי","because of"),
    ("רִשְׁעַת","the wickedness"),
    ("הָעוֹלָם","of the world"),
    ("אֶקַּח","that I will"),
    ("נָקָם","take vengeance"),
    ("מִן","upon"),
    ("הָרְשָׁעִים","the wicked"),
    ("כִּי","for"),
    ("לֹא","they will"),
    ("יָשׁוּבוּ","not repent"),
    ("כִּי","for"),
    ("מָלְאָה","the cup of"),
    ("כּוֹס","mine indignation"),
    ("זַעְמִי","is full"),
    ("כִּי","for behold"),
    ("הִנֵּה","my blood"),
    ("דָמִי","shall not cleanse them"),
    ("לֹא","if they"),
    ("אִם","hear me"),
    ("לֹא","not"),
]),
("יח", [
    ("לָכֵן","Wherefore I the"),
    ("אֲנִי","Lord God will"),
    ("יְהוָה","send forth flies"),
    ("אֱלֹהִים","upon the face"),
    ("אֲשַׁלַּח","of the earth"),
    ("עָרֹב","which shall"),
    ("עַל","take hold"),
    ("פְּנֵי","of the"),
    ("הָאָרֶץ","inhabitants thereof"),
    ("וְיֹאחֲזוּ","and shall"),
    ("בְּיוֹשְׁבֶיהָ","eat their"),
    ("וְיֹאכְלוּ","flesh and"),
    ("בְשָׂרָם","shall cause"),
    ("וְיָבִיאוּ","maggots to"),
    ("רִמָּה","come in"),
    ("עֲלֵיהֶם","upon them"),
]),
("יט", [
    ("וּלְשׁוֹנָם","And their tongues"),
    ("תֵּעָצֵר","shall be stayed"),
    ("לְבִלְתִּי","that they shall"),
    ("דַבֵּר","not utter against"),
    ("נֶגְדִּי","me and their"),
    ("וּבְשָׂרָם","flesh shall fall"),
    ("יִפֹּל","from off their"),
    ("מֵעַל","bones and their"),
    ("עַצְמוֹתָם","eyes from"),
    ("וְעֵינֵיהֶם","their sockets"),
]),
("כ", [
    ("וְהָיָה","And it shall come to pass"),
    ("חַיַּת","that the beasts"),
    ("הַשָּׂדֶה","of the forest"),
    ("וְעוֹף","and the fowls"),
    ("הַשָּׁמַיִם","of the air"),
    ("יֹאכְלוּם","shall devour them up"),
]),
("כא", [
    ("וְהָעֵדָה","And the"),
    ("הַגְּדוֹלָה","great and"),
    ("וְהַתּוֹעֵבָה","abominable church"),
    ("זוֹנַת","which is"),
    ("כָּל","the whore"),
    ("הָאָרֶץ","of all"),
    ("תֻּשְׁלַךְ","the earth"),
    ("בְּאֵשׁ","shall be"),
    ("אֹכֶלֶת","cast down"),
    ("כַּאֲשֶׁר","by devouring"),
    ("נֶאֱמַר","fire according"),
    ("מִפִּי","as it"),
    ("יְחֶזְקֵאל","is spoken"),
    ("הַנָּבִיא","by the"),
    ("אֲשֶׁר","mouth of"),
    ("דִּבֵּר","Ezekiel the"),
    ("עַל","prophet who"),
    ("הַדְּבָרִים","spoke of"),
    ("הָאֵלֶּה","these things"),
    ("אֲשֶׁר","which have"),
    ("לֹא","not come"),
    ("בָאוּ","to pass"),
    ("אַךְ","but surely"),
    ("בּוֹא","must as"),
    ("יָבֹאוּ","I live"),
    ("חַי","for"),
    ("אָנִי","abominations"),
    ("כִּי","shall"),
    ("תוֹעֵבוֹת","not"),
    ("לֹא","reign"),
]),
("כב", [
    ("וְעוֹד","And again"),
    ("אָמֵן","verily verily"),
    ("אָמֵן","I say"),
    ("אֲנִי","unto you"),
    ("אֹמֵר","that when"),
    ("לָכֶם","the thousand"),
    ("כְּתֹם","years are"),
    ("אֶלֶף","ended and"),
    ("שָׁנִים","men again"),
    ("וְהָאֲנָשִׁים","begin to"),
    ("יָחֵלּוּ","deny their"),
    ("שׁוּב","God then"),
    ("לְכַחֵשׁ","will I"),
    ("בֵּאלֹהֵיהֶם","spare"),
    ("אָז","the"),
    ("אָחוּס","earth"),
    ("עַל","but"),
    ("הָאָרֶץ","for"),
    ("רַק","a"),
    ("עֵת","little"),
    ("מְעָט","season"),
]),
("כג", [
    ("וְהַקֵּץ","And the end"),
    ("יָבוֹא","shall come and"),
    ("וְהַשָּׁמַיִם","the heaven and"),
    ("וְהָאָרֶץ","the earth shall"),
    ("יִכָּלוּ","be consumed and"),
    ("וְיַעַבְרוּ","pass away and"),
    ("וְיִהְיוּ","there shall"),
    ("שָׁמַיִם","be a"),
    ("חֲדָשִׁים","new heaven"),
    ("וָאָרֶץ","and a"),
    ("חֲדָשָׁה","new earth"),
]),
("כד", [
    ("כִּי","For all old"),
    ("כָל","things shall"),
    ("הַיְשָׁנוֹת","pass away"),
    ("יַעַבְרוּ","and all"),
    ("וְכֹל","things shall"),
    ("יִהְיֶה","become new"),
    ("חָדָשׁ","even the"),
    ("הַשָּׁמַיִם","heaven and"),
    ("וְהָאָרֶץ","the earth"),
    ("וְכָל","and all"),
    ("מְלוֹאָם","the fulness"),
    ("הֵן","thereof both"),
    ("אָדָם","men and"),
    ("הֵן","beasts the"),
    ("בְּהֵמוֹת","fowls of"),
    ("עוֹף","the air"),
    ("הַשָּׁמַיִם","and the"),
    ("וּדְגֵי","fishes of"),
    ("הַיָּם","the sea"),
]),
("כה", [
    ("וְלֹא","And not"),
    ("יֹאבַד","one hair"),
    ("שַׂעֲרָה","neither mote"),
    ("וְלֹא","shall be lost"),
    ("רֶגֶב","for"),
    ("כִּי","it is"),
    ("מַעֲשֵׂה","the workmanship"),
    ("יָדַי","of mine"),
    ("הֵם","hand"),
]),
("כו", [
    ("אַךְ","But behold"),
    ("הִנֵּה","verily I"),
    ("אָמֵן","say unto"),
    ("אֲנִי","you before"),
    ("אֹמֵר","the earth"),
    ("לָכֶם","shall pass"),
    ("בְּטֶרֶם","away Michael"),
    ("תַּעֲבֹר","mine archangel"),
    ("הָאָרֶץ","shall sound"),
    ("יִתְקַע","his trump"),
    ("מִיכָאֵל","and then"),
    ("שַׂר","shall all"),
    ("מַלְאָכַי","the dead"),
    ("בְּשׁוֹפָרוֹ","awake for"),
    ("וְאָז","their graves"),
    ("יָקִיצוּ","shall be"),
    ("כָל","opened and"),
    ("הַמֵּתִים","they"),
    ("כִּי","shall"),
    ("קִבְרוֹתֵיהֶם","come"),
    ("יִפָּתְחוּ","forth"),
    ("וְיָצְאוּ","yea"),
    ("אָכֵן","even"),
    ("כֻּלָּם","all"),
]),
("כז", [
    ("וְהַצַּדִּיקִים","And the righteous"),
    ("יֵאָסְפוּ","shall be gathered"),
    ("לִימִינִי","on my right hand"),
    ("לְחַיֵּי","unto"),
    ("עוֹלָם","eternal life"),
    ("וְהָרְשָׁעִים","and the wicked"),
    ("לִשְׂמֹאלִי","on my left hand"),
    ("אֵבוֹשׁ","will I be ashamed"),
    ("לְהַכִּירָם","to own"),
    ("לִפְנֵי","before"),
    ("הָאָב","the Father"),
]),
("כח", [
    ("לָכֵן","Wherefore"),
    ("אֹמַר","I will say"),
    ("לָהֶם","unto them"),
    ("סוּרוּ","Depart from"),
    ("מִמֶּנִּי","me"),
    ("אֲרוּרִים","ye cursed"),
    ("אֶל","into"),
    ("אֵשׁ","everlasting fire"),
    ("עוֹלָם","prepared for"),
    ("הַמּוּכָנָה","the devil"),
    ("לַשָּׂטָן","and his angels"),
]),
("כט", [
    ("וְעַתָּה","And now"),
    ("הִנֵּה","behold I"),
    ("אֲנִי","say unto"),
    ("אֹמֵר","you never"),
    ("לָכֶם","at any"),
    ("מֵעוֹלָם","time have"),
    ("לֹא","I declared"),
    ("אָמַרְתִּי","from mine"),
    ("מִפִּי","own mouth"),
    ("כִּי","that they"),
    ("יָשׁוּבוּ","should return"),
    ("כִּי","for where"),
    ("בַאֲשֶׁר","I"),
    ("אֲנִי","am"),
    ("שָׁם","they"),
    ("לֹא","cannot"),
    ("יוּכְלוּ","come"),
    ("לָבוֹא","for"),
    ("כִּי","they"),
    ("אֵין","have"),
    ("לָהֶם","no"),
    ("כֹּחַ","power"),
]),
("ל", [
    ("אַךְ","But remember"),
    ("זִכְרוּ","that"),
    ("כִּי","all my judgments"),
    ("לֹא","are not"),
    ("כָל","given unto"),
    ("מִשְׁפָּטַי","men"),
    ("נִתְּנוּ","and as"),
    ("לִבְנֵי","the words have gone forth"),
    ("אָדָם","out of"),
    ("וְכַאֲשֶׁר","my mouth"),
    ("יָצְאוּ","even so"),
    ("דְבָרִים","shall they be fulfilled"),
    ("מִפִּי","that"),
    ("כֵּן","the first"),
    ("יִתְמַלֵּאוּ","shall be"),
    ("כִּי","last"),
    ("הָרִאשֹׁנִים","and that"),
    ("יִהְיוּ","the last"),
    ("אַחֲרוֹנִים","shall be"),
    ("וְהָאַחֲרוֹנִים","first"),
    ("רִאשֹׁנִים","in all things"),
    ("בְּכָל","whatsoever I"),
    ("אֲשֶׁר","have created"),
    ("בָּרָאתִי","by the word"),
    ("בִּדְבַר","of my"),
    ("כֹּחִי","power"),
    ("הוּא","which is"),
    ("כֹּחַ","the power"),
    ("רוּחִי","of my Spirit"),
]),
("לא", [
    ("כִּי","For"),
    ("בְּכֹחַ","by the power"),
    ("רוּחִי","of my Spirit"),
    ("בְּרָאתִים","created I"),
    ("אָכֵן","them"),
    ("כֹּל","yea"),
    ("הֵן","all things"),
    ("רוּחָנִי","both"),
    ("הֵן","spiritual"),
    ("גַשְׁמִי","and temporal"),
]),
("לב", [
    ("רִאשׁוֹנָה","First"),
    ("רוּחָנִי","spiritual"),
    ("שֵׁנִית","secondly"),
    ("גַשְׁמִי","temporal"),
    ("זֹאת","which is"),
    ("תְּחִלַּת","the beginning"),
    ("מְלַאכְתִּי","of my work"),
    ("וְשׁוּב","and again"),
    ("רִאשׁוֹנָה","first"),
    ("גַשְׁמִי","temporal"),
    ("וְשֵׁנִית","and secondly"),
    ("רוּחָנִי","spiritual"),
    ("זֹאת","which is"),
    ("אַחֲרִית","the last"),
    ("מְלַאכְתִּי","of my work"),
]),
("לג", [
    ("מְדַבֵּר","Speaking unto"),
    ("אֲנִי","you that"),
    ("אֲלֵיכֶם","you may"),
    ("לְמַעַן","naturally understand"),
    ("תָּבִינוּ","but unto"),
    ("בְּדֶרֶךְ","myself my"),
    ("הַטֶּבַע","works have"),
    ("אַךְ","no end"),
    ("לִי","neither beginning"),
    ("אֵין","but it"),
    ("קֵץ","is given"),
    ("לְמַעֲשַׂי","unto you"),
    ("וְלֹא","that ye"),
    ("תְחִלָּה","may understand"),
    ("אַךְ","because ye"),
    ("נִתַּן","have asked"),
    ("לָכֶם","it"),
    ("לְהָבִין","of"),
    ("כִּי","me"),
    ("שְׁאַלְתֶּם","and"),
    ("מִמֶּנִּי","are"),
    ("אַתֶּם","agreed"),
]),
("לד", [
    ("לָכֵן","Wherefore verily"),
    ("אָמֵן","I say"),
    ("אֲנִי","unto you"),
    ("אֹמֵר","that all"),
    ("לָכֶם","things unto"),
    ("כָּל","me are"),
    ("דָּבָר","spiritual and"),
    ("רוּחָנִי","not at"),
    ("הוּא","any time"),
    ("לִי","have I"),
    ("וְלֹא","given unto"),
    ("נָתַתִּי","you a"),
    ("לָכֶם","law which"),
    ("מֵעוֹלָם","was temporal"),
    ("תּוֹרָה","neither any"),
    ("גַשְׁמִית","man nor"),
    ("וְלֹא","the children"),
    ("לְאִישׁ","of"),
    ("וְלֹא","men"),
    ("לִבְנֵי","neither"),
    ("אָדָם","Adam"),
    ("וְלֹא","your"),
    ("לְאָדָם","father"),
    ("אֲבִיכֶם","whom"),
    ("אֲשֶׁר","I"),
    ("בָּרָאתִי","created"),
]),
("לה", [
    ("הִנֵּה","Behold I"),
    ("נָתַתִּי","gave unto"),
    ("לוֹ","him that"),
    ("לִהְיוֹת","he should"),
    ("פּוֹעֵל","be an"),
    ("לְעַצְמוֹ","agent unto"),
    ("וְנָתַתִּי","himself and"),
    ("לוֹ","I gave"),
    ("מִצְוָה","unto him"),
    ("אַךְ","commandment but"),
    ("לֹא","no temporal"),
    ("מִצְוָה","commandment gave"),
    ("גַשְׁמִית","I unto"),
    ("נָתַתִּי","him for"),
    ("לוֹ","my commandments"),
    ("כִּי","are spiritual"),
    ("מִצְוֹתַי","they"),
    ("רוּחָנִיּוֹת","are"),
    ("הֵן","not"),
    ("לֹא","natural"),
    ("טִבְעִיּוֹת","nor"),
    ("וְלֹא","temporal"),
    ("גַשְׁמִיּוֹת","neither"),
    ("וְלֹא","carnal"),
    ("בְשָׂרִיּוֹת","nor"),
    ("וְלֹא","sensual"),
]),
("לו", [
    ("וַיְהִי","And it came"),
    ("אָדָם","to pass that"),
    ("מְנֻסֶּה","Adam being tempted"),
    ("מֵהַשָּׂטָן","of the devil"),
    ("כִּי","for behold"),
    ("הִנֵּה","the devil"),
    ("הַשָּׂטָן","was before"),
    ("הָיָה","Adam for"),
    ("לִפְנֵי","he rebelled"),
    ("אָדָם","against me"),
    ("כִּי","saying Give"),
    ("מָרַד","me thine"),
    ("בִּי","honor which"),
    ("לֵאמֹר","is my"),
    ("תֶּן־לִי","power and"),
    ("כְבוֹדְךָ","also a"),
    ("הוּא","third part"),
    ("כֹחִי","of the"),
    ("וְגַם","hosts of"),
    ("שְׁלִישִׁית","heaven turned"),
    ("צִבְאוֹת","he away"),
    ("הַשָּׁמַיִם","from me"),
    ("הֵסִיר","because of"),
    ("מֵעָלַי","their agency"),
]),
("לז", [
    ("וַיֻּשְׁלְכוּ","And they were"),
    ("וְכֵן","thrust down"),
    ("בָּא","and thus came"),
    ("הַשָּׂטָן","the devil"),
    ("וּמַלְאָכָיו","and his angels"),
]),
("לח", [
    ("וְהִנֵּה","And behold"),
    ("מָקוֹם","there is"),
    ("מוּכָן","a place"),
    ("לָהֶם","prepared for"),
    ("מֵרֵאשִׁית","them"),
    ("הַמָּקוֹם","from the beginning"),
    ("הַהוּא","which place"),
    ("שְׁאוֹל","is hell"),
]),
("לט", [
    ("וְהָיָה","And it"),
    ("צָרִיךְ","must needs"),
    ("שֶׁיְּנַסֶּה","be that"),
    ("הַשָּׂטָן","the devil"),
    ("אֶת־בְּנֵי","should tempt"),
    ("הָאָדָם","the children"),
    ("אוֹ","of men"),
    ("לֹא","or they"),
    ("יוּכְלוּ","could not"),
    ("לִהְיוֹת","be agents"),
    ("פּוֹעֲלִים","unto themselves"),
    ("לְעַצְמָם","for if"),
    ("כִּי","they never"),
    ("אִם","should have"),
    ("לֹא","bitter"),
    ("יִטְעֲמוּ","they"),
    ("מַר","could"),
    ("לְעוֹלָם","not"),
    ("לֹא","know"),
    ("יֵדְעוּ","the"),
    ("מָתוֹק","sweet"),
]),
("מ", [
    ("לָכֵן","Wherefore it"),
    ("וַיְהִי","came to"),
    ("הַשָּׂטָן","pass that"),
    ("נִסָּה","the devil"),
    ("אֶת־אָדָם","tempted Adam"),
    ("וַיֹּאכַל","and he"),
    ("מִן","partook of"),
    ("הַפְּרִי","the forbidden"),
    ("הָאָסוּר","fruit and"),
    ("וַיַּעֲבֹר","transgressed the"),
    ("אֶת־הַמִּצְוָה","commandment wherein"),
    ("בַּאֲשֶׁר","he became"),
    ("נִכְנַע","subject to"),
    ("לִרְצוֹן","the will"),
    ("הַשָּׂטָן","of the"),
    ("כִּי","devil because"),
    ("נָתַן","he yielded"),
    ("לַנִּסָּיוֹן","unto temptation"),
]),
("מא", [
    ("לָכֵן","Wherefore I the"),
    ("אֲנִי","Lord God caused"),
    ("יְהוָה","that he"),
    ("אֱלֹהִים","should be"),
    ("מִגַּן","cast out"),
    ("עֵדֶן","from the"),
    ("מִלְּפָנַי","Garden of"),
    ("מִפְּנֵי","Eden from"),
    ("פִשְׁעוֹ","my presence"),
    ("בַּאֲשֶׁר","because of"),
    ("מֵת","his transgression"),
    ("רוּחָנִית","wherein he"),
    ("הוּא","became spiritually"),
    ("הַמָּוֶת","dead which"),
    ("הָרִאשׁוֹן","is the"),
    ("אָכֵן","first death"),
    ("הַמָּוֶת","even that"),
    ("עַצְמוֹ","same death"),
    ("שֶׁהוּא","which is"),
    ("הַמָּוֶת","the last"),
    ("הָאַחֲרוֹן","death which"),
    ("הָרוּחָנִי","is spiritual"),
    ("אֲשֶׁר","which shall"),
    ("יֵאָמֵר","be pronounced"),
    ("עַל","upon the"),
    ("הָרְשָׁעִים","wicked when"),
    ("כְּאָמְרִי","I shall"),
    ("סוּרוּ","say: Depart"),
    ("אֲרוּרִים","ye cursed"),
]),
("מב", [
    ("אַךְ","But behold I"),
    ("הִנֵּה","say unto you"),
    ("אֲנִי","that I the"),
    ("אֹמֵר","Lord God gave"),
    ("לָכֶם","unto Adam"),
    ("אֲנִי","and unto"),
    ("יְהוָה","his seed"),
    ("אֱלֹהִים","that they"),
    ("נָתַתִּי","should not"),
    ("לְאָדָם","die as"),
    ("וּלְזַרְעוֹ","to the"),
    ("שֶׁלֹּא","temporal death"),
    ("יָמוּתוּ","until I"),
    ("מָוֶת","the Lord"),
    ("גַּשְׁמִי","God should"),
    ("עַד","send forth"),
    ("אֲשַׁלַּח","angels to"),
    ("מַלְאָכִים","declare unto"),
    ("לְהַשְׁמִיעָם","them repentance"),
    ("תְּשׁוּבָה","and redemption"),
    ("וּגְאֻלָּה","through faith"),
    ("בֶּאֱמוּנָה","on the"),
    ("בְּשֵׁם","name of"),
    ("בְּנִי","mine Only"),
    ("יְחִידִי","Begotten Son"),
]),
("מג", [
    ("וְכֵן","And thus did"),
    ("קָבַעְתִּי","I the Lord"),
    ("אֲנִי","God appoint unto"),
    ("יְהוָה","man the"),
    ("אֱלֹהִים","days of"),
    ("לָאָדָם","his probation"),
    ("יְמֵי","that by"),
    ("לְמַעַן","his natural"),
    ("בְּמוֹתוֹ","death he"),
    ("הַטִּבְעִי","might be"),
    ("יָקוּם","raised in"),
    ("בְּאַלְמָוֶת","immortality unto"),
    ("לְחַיֵּי","eternal life"),
    ("עוֹלָם","even as"),
    ("כָּל","many as"),
    ("הַמַּאֲמִינִים","would believe"),
]),
("מד", [
    ("וְאֵלֶּה","And they"),
    ("שֶׁאֵינָם","that believe"),
    ("מַאֲמִינִים","not unto"),
    ("לְחֶרְפַּת","eternal damnation"),
    ("עוֹלָם","for they"),
    ("כִּי","cannot be"),
    ("לֹא","redeemed from"),
    ("יוּכְלוּ","their"),
    ("לְהִגָּאֵל","spiritual"),
    ("מִנְּפִילָתָם","fall"),
    ("הָרוּחָנִית","because"),
    ("כִּי","they"),
    ("לֹא","repent"),
    ("יָשׁוּבוּ","not"),
]),
("מה", [
    ("כִּי","For they"),
    ("אֹהֲבִים","love darkness"),
    ("הֵם","rather than"),
    ("חֹשֶׁךְ","light and"),
    ("מֵאוֹר","their deeds"),
    ("וּמַעֲשֵׂיהֶם","are evil"),
    ("רָעִים","and they"),
    ("וּמְקַבְּלִים","receive their"),
    ("שְׂכָרָם","wages of"),
    ("מֵאֲשֶׁר","whom they"),
    ("בָּחֲרוּ","list to"),
    ("לִשְׁמֹעַ","obey"),
]),
("מו", [
    ("אַךְ","But behold"),
    ("הִנֵּה","I say"),
    ("אֲנִי","unto you"),
    ("אֹמֵר","that little"),
    ("לָכֶם","children are"),
    ("יְלָדִים","redeemed from"),
    ("קְטַנִּים","the foundation"),
    ("נִגְאָלִים","of the"),
    ("מִיסוֹד","world through"),
    ("הָעוֹלָם","mine"),
    ("בְּיַד","Only"),
    ("יְחִידִי","Begotten"),
]),
("מז", [
    ("לָכֵן","Wherefore they"),
    ("לֹא","cannot sin"),
    ("יוּכְלוּ","for power"),
    ("לַחֲטֹא","is not"),
    ("כִּי","given unto"),
    ("לֹא","Satan to"),
    ("נִתַּן","tempt little"),
    ("כֹּחַ","children"),
    ("לַשָּׂטָן","until"),
    ("לְנַסּוֹת","they"),
    ("יְלָדִים","begin"),
    ("קְטַנִּים","to"),
    ("עַד","become"),
    ("יָחֵלּוּ","accountable"),
    ("לִהְיוֹת","before"),
    ("לְפָנַי","me"),
]),
("מח", [
    ("כִּי","For it is"),
    ("נִתָּן","given unto"),
    ("לָהֶם","them"),
    ("כַּאֲשֶׁר","even as"),
    ("אֶחְפֹּץ","I will"),
    ("כִּרְצוֹנִי","according to"),
    ("לְמַעַן","mine own pleasure"),
    ("דְּבָרִים","that great"),
    ("גְּדוֹלִים","things may"),
    ("יִדָּרְשׁוּ","be required"),
    ("מִיַּד","at the hand"),
    ("אֲבוֹתֵיהֶם","of their fathers"),
]),
("מט", [
    ("וְעוֹד","And again"),
    ("אֲנִי","I"),
    ("אֹמֵר","say"),
    ("לָכֶם","unto you"),
    ("מִי","that"),
    ("שֶׁיֵּשׁ","whoso having"),
    ("לוֹ","knowledge"),
    ("דַּעַת","have I"),
    ("הֲלֹא","not"),
    ("צִוִּיתִיו","commanded"),
    ("לָשׁוּב","to repent"),
]),
("נ", [
    ("וּמִי","And he"),
    ("שֶׁאֵין","that hath"),
    ("לוֹ","no understanding"),
    ("בִינָה","it remaineth"),
    ("נִשְׁאָר","in me"),
    ("בִּי","to do"),
    ("לַעֲשׂוֹת","according as"),
    ("כַּכָּתוּב","it is"),
    ("וְעַתָּה","written And"),
    ("לֹא","now I"),
    ("אַשְׁמִיעַ","declare no"),
    ("לָכֶם","more unto"),
    ("עוֹד","you at"),
    ("בָּעֵת","this"),
    ("הַזֹּאת","time"),
    ("אָמֵן","Amen"),
]),
]
