// generated by tools/build_heading_manifests.js — chapter summaries for articles_of_faith.js
(function(){ var W = window;
  Object.assign(W._pgpChapterHeadings = W._pgpChapterHeadings || {}, {"Articles of Faith 1":"We believe in God, the Eternal Father, and in His Son, Jesus Christ, and in the Holy Ghost."});
  Object.assign(W._pgpChapterHeadingsHeb = W._pgpChapterHeadingsHeb || {}, {"Articles of Faith 1":"אנחנו מאמינים באלהים האב הנצחי ובבנו ישוע המשיח וברוח הקדש׃"});
  Object.assign(W._pgpHeadingWords = W._pgpHeadingWords || {}, {"Articles of Faith 1":[["אֲנַחְנוּ","We"],["מַאֲמִינִים","believe"],["בֵּאלֹהִים","in God"],["הָאָב","the Father"],["הַנִּצְחִי","the Eternal"],["וּבִבְנוֹ","and in His Son"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","Christ"],["וּבְרוּחַ","and in the Spirit"],["הַקֹּדֶשׁ","Holy"],["׃",""]]});
})();
