// generated by tools/build_heading_manifests.js — chapter summaries for js_matthew.js
(function(){ var W = window;
  Object.assign(W._pgpChapterHeadings = W._pgpChapterHeadings || {}, {"JS-Matthew 1":"Jesus foretells the impending destruction of Jerusalem—He also discourses on the Second Coming of the Son of Man, and the destruction of the wicked."});
  Object.assign(W._pgpChapterHeadingsHeb = W._pgpChapterHeadingsHeb || {}, {"JS-Matthew 1":"ישוע חוזה את חורבנה הקרב של ירושלים הוא גם דורש על הביאה השנייה של בן האדם ועל השמדת הרשעים׃"});
  Object.assign(W._pgpHeadingWords = W._pgpHeadingWords || {}, {"JS-Matthew 1":[["יֵשׁוּעַ","Jesus"],["חוֹזֵה","the seer of"],["אֶת",""],["חָרְבָּנָהּ","the desolation thereof"],["הַקָּרֵב","the approaching"],["שֶׁל","of"],["יְרוּשָׁלַיִם","Jerusalem"],["הוּא","he"],["גַּם","also"],["דּוֹרֵשׁ","requires"],["עַל","upon"],["הַבִּיאָה","the Coming"],["הַשְּׁנִיָּה","the Second"],["שֶׁל","of"],["בֶּן","the Son of"],["הָאָדָם","men"],["וְעַל","and upon"],["הַשְׁמָדַת","the destruction of"],["הָרְשָׁעִים","the wicked"],["׃",""]]});
})();
