// generated by tools/build_heading_manifests.js — chapter summaries for js_matthew.js
(function(){ var W = window;
  Object.assign(W._pgpChapterHeadings = W._pgpChapterHeadings || {}, {"JS-Matthew 1":"Jesus foretells the impending destruction of Jerusalem—He also discourses on the Second Coming of the Son of Man, and the destruction of the wicked."});
  Object.assign(W._pgpChapterHeadingsHeb = W._pgpChapterHeadingsHeb || {}, {"JS-Matthew 1":"ישוע חוזה את חרבן ירושלים הקרב הוא גם דורש על ביאת בן האדם השניה ועל השמדת הרשעים׃"});
  Object.assign(W._pgpHeadingWords = W._pgpHeadingWords || {}, {"JS-Matthew 1":[["יֵשׁוּעַ","Jesus"],["חוֹזֶה","foretells"],["אֵת",""],["חׇרְבַּן","the destruction of"],["יְרוּשָׁלַיִם","Jerusalem"],["הַקָּרֵב","impending"],["הוּא","he"],["גַּם","also"],["דּוֹרֵשׁ","discourses"],["עַל","on"],["בִּיאַת","the Coming of"],["בֶּן","the Son of"],["הָאָדָם","Man"],["הַשְּׁנִיָּה","Second"],["וְעַל","and on"],["הַשְׁמָדַת","the destruction of"],["הָרְשָׁעִים","the wicked"],["׃",""]]});
})();
