// generated by tools/build_crossref_chunks.js — cross-references for 2jn.js
(function(){ var W = window;
  Object.assign(W._ntCrossrefsData = W._ntCrossrefsData || {}, {"2 John|1|6":[{"marker":"a","text":"beginning","refs":["1 Jn. 2:24"],"category":"cross-ref"}],"2 John|1|8":[{"marker":"a","text":"wrought","category":"trn"}],"2 John|1|10":[{"marker":"a","text":"house","refs":["1 Cor. 5:11"],"category":"cross-ref"}],"2 John|1|11":[{"marker":"a","text":"partaker","refs":["1 Tim. 5:22"],"category":"cross-ref"}]});
  if (typeof W.__swCrossrefsArrived === 'function') W.__swCrossrefsArrived();
})();
