// generated by tools/build_crossref_chunks.js — cross-references for 3jn.js
(function(){ var W = window;
  Object.assign(W._ntCrossrefsData = W._ntCrossrefsData || {}, {"3 John|1|4":[{"marker":"a","text":"children","refs":["1 Jn. 5:21"],"category":"cross-ref"}],"3 John|1|5":[{"marker":"a","text":"brethren","refs":["D&C 84:88 (88–92)"],"category":"cross-ref"}],"3 John|1|10":[{"marker":"a","text":"prating","refs":["Num. 16:3"],"category":"cross-ref"}],"3 John|1|11":[{"marker":"a","text":"good","refs":["Moro. 7:12"],"category":"cross-ref"}],"3 John|1|12":[{"marker":"a","text":"record","category":"trn"}]});
  if (typeof W.__swCrossrefsArrived === 'function') W.__swCrossrefsArrived();
})();
