// pgp_verses/articles_of_faith.js — Articles of Faith verse data
(function() {
var aof_ch1Verses = [
  { num: "א", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["בֵּאלֹהִים","in God"], ["אֲבִי","the Father"], ["עוֹלָם","Eternal"], ["וּבִבְנוֹ","and in his Son"], ["יֵשׁוּעַ","Jesus"], ["הַמָּשִׁיחַ","Christ"], ["וּבְרוּחַ־הַקֹּדֶשׁ","and in the Holy Ghost"], ["׃",""]]},
  { num: "ב", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["כִּי","that"], ["אִישׁ","each man"], ["בְּחֶטְאוֹ","for his own sin"], ["יֵעָנֵשׁ","will be punished"], ["וְלֹא","and not"], ["בְּפֶשַׁע","for the transgression of"], ["אָדָם","Adam"], ["׃",""]]},
  { num: "ג", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["כִּי","that"], ["בְּכַפָּרַת","through the atonement of"], ["הַמָּשִׁיחַ","Christ"], ["יִוָּשַׁע","may be saved"], ["כׇּל־הָאָדָם","all mankind"], ["בִּשְׁמֹר","by obedience"], ["תּוֹרוֹת","to the laws"], ["הַבְּשׂוֹרָה","of the gospel"], ["וְחֻקֹּתֶיהָ","and its ordinances"], ["׃",""]]},
  { num: "ד", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["כִּי","that"], ["עִקְּרֵי","the principles of"], ["הַבְּשׂוֹרָה","the gospel"], ["וְחֻקֹּתֶיהָ","and its ordinances"], ["הָרִאשׁוֹנִים","first"], ["הֵם","are"], ["רִאשׁוֹנָה","first"], ["אֱמוּנָה","Faith"], ["בָּאָדוֹן","in the Lord"], ["יֵשׁוּעַ","Jesus"], ["הַמָּשִׁיחַ","Christ"], ["שְׁנִיָּה","second"], ["תְּשׁוּבָה","Repentance"], ["שְׁלִישִׁית","third"], ["טְבִילָה","Baptism"], ["בַּמַּיִם","by immersion"], ["לִסְלִיחַת","for the remission of"], ["חֲטָאִים","sins"], ["רְבִיעִית","fourth"], ["סְמִיכַת","Laying on of"], ["יָדַיִם","hands"], ["לְמַתַּן","for the gift of"], ["רוּחַ־הַקֹּדֶשׁ","the Holy Ghost"], ["׃",""]]},
  { num: "ה", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["כִּי","that"], ["הִקָּרֵא","must"], ["יִקָּרֵא","be called"], ["אִישׁ","a man"], ["מֵאֵת","of"], ["הָאֱלֹהִים","God"], ["בִּנְבוּאָה","by prophecy"], ["וּבִסְמִיכַת","and by the laying on of"], ["יָדַיִם","hands"], ["מֵאֵלֶּה","by those"], ["אֲשֶׁר","who"], ["בְּיָדָם","have"], ["הַסַּמְכוּת","authority"], ["לִקְרֹא","to preach"], ["אֶת־הַבְּשׂוֹרָה","the gospel"], ["וּלְשָׁרֵת","and to administer"], ["בְּחֻקֹּתֶיהָ","in its ordinances"], ["׃",""]]},
  { num: "ו", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["בַּסֵּדֶר","in the same organization"], ["אֲשֶׁר","that"], ["הָיָה","existed"], ["בַּקְּהִלָּה","in the Church"], ["הָרִאשׁוֹנָה","Primitive"], ["לֵאמֹר","namely"], ["שְׁלִיחִים","apostles"], ["נְבִיאִים","prophets"], ["רוֹעִים","pastors"], ["מוֹרִים","teachers"], ["מְבַשְּׂרִים","evangelists"], ["וְכָהֵנָּה","and so forth"], ["׃",""]]},
  { num: "ז", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["בְּמַתַּן","in the gift of"], ["לְשׁוֹנוֹת","tongues"], ["נְבוּאָה","prophecy"], ["חָזוֹן","revelation"], ["מַרְאוֹת","visions"], ["רְפוּאָה","healing"], ["פִּתְרוֹן","interpretation of"], ["לְשׁוֹנוֹת","tongues"], ["וְכָהֵנָּה","and so forth"], ["׃",""]]},
  { num: "ח", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["כִּי","that"], ["הַמִּקְרָא","the Bible"], ["דְּבַר","the word of"], ["אֱלֹהִים","God"], ["הוּא","it is"], ["כַּאֲשֶׁר","as far as"], ["תֻּרְגַּם","it is translated"], ["נְכוֹנָה","correctly"], ["גַּם","also"], ["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["כִּי","that"], ["סֵפֶר","the book of"], ["מוֹרְמוֹן","Mormon"], ["דְּבַר","is the word of"], ["אֱלֹהִים","God"], ["הוּא","it is"], ["׃",""]]},
  { num: "ט", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["בְּכֹל","all"], ["אֲשֶׁר","that"], ["גִּלָּה","hath revealed"], ["הָאֱלֹהִים","God"], ["בְּכֹל","all"], ["אֲשֶׁר","that"], ["הוּא","he"], ["מְגַלֶּה","doth reveal"], ["עַתָּה","now"], ["וּמַאֲמִינִים","and believe"], ["אֲנַחְנוּ","we"], ["כִּי","that"], ["עוֹד","yet"], ["יְגַלֶּה","he will reveal"], ["דְבָרִים","things"], ["רַבִּים","many"], ["גְּדוֹלִים","great"], ["וְנִכְבָּדִים","and important"], ["עַל־דְּבַר","pertaining"], ["מַלְכוּת","to the kingdom of"], ["הָאֱלֹהִים","God"], ["׃",""]]},
  { num: "י", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["כִּי","that"], ["הִקָּבֵץ","the literal"], ["יִקָּבֵץ","gathering of"], ["יִשְׂרָאֵל","Israel"], ["וְכִי","and that"], ["יוּשְׁבוּ","shall be restored"], ["עֲשֶׂרֶת","the Ten"], ["הַשְּׁבָטִים","Tribes"], ["כִּי","that"], ["צִיּוֹן","Zion"], ["יְרוּשָׁלַיִם","Jerusalem"], ["הַחֲדָשָׁה","the New"], ["תִּבָּנֶה","will be built"], ["עַל־אַדְמַת","upon the continent of"], ["אָמֵרִיקָה","America"], ["כִּי","that"], ["הַמָּשִׁיחַ","Christ"], ["הוּא","personally"], ["יִמְלֹךְ","will reign"], ["עַל־הָאָרֶץ","upon the earth"], ["וְכִי","and that"], ["הָאָרֶץ","the earth"], ["תִּתְחַדֵּשׁ","will be renewed"], ["וְתָשׁוּב","and shall return"], ["לִכְבוֹד","to the glory of"], ["גַּן","the Garden of"], ["עֵדֶן","Eden"], ["׃",""]]},
  { num: "יא", words: [["דּוֹרְשִׁים","claim"], ["אֲנַחְנוּ","we"], ["אֶת־הַזְּכוּת","the privilege"], ["לַעֲבֹד","of worshipping"], ["אֶת־אֵל","God"], ["שַׁדַּי","Almighty"], ["כְּכֹל","according to"], ["אֲשֶׁר","what"], ["יֹאמַר","saith"], ["לִבֵּנוּ","our own conscience"], ["וְנוֹתְנִים","and we allow"], ["לְכׇל־אָדָם","unto all men"], ["אֶת־הַזְּכוּת","the privilege"], ["הַהִיא","same"], ["יַעַבְדוּ","let them worship"], ["אֵיךְ","how"], ["וְאֵיפֹה","where"], ["וְאֵת","or"], ["אֲשֶׁר","what"], ["יַעֲבֹדוּ","they may"], ["׃",""]]},
  { num: "יב", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["בְּהִכָּנַע","in being subject"], ["לִמְלָכִים","to kings"], ["לִנְשִׂיאִים","to presidents"], ["לְמֹשְׁלִים","to rulers"], ["וּלְשׁוֹפְטִים","and to magistrates"], ["בִּשְׁמֹר","in obeying"], ["אֶת־הַתּוֹרָה","the law"], ["בְּכַבְּדָהּ","honoring"], ["וּבְתָמְכָהּ","and sustaining"], ["׃",""]]},
  { num: "יג", words: [["מַאֲמִינִים","believe"], ["אֲנַחְנוּ","we"], ["בִּהְיוֹת","in being"], ["יְשָׁרִים","honest"], ["נֶאֱמָנִים","true"], ["טְהוֹרִים","chaste"], ["גֹּמְלֵי־חֶסֶד","benevolent"], ["וְאַנְשֵׁי־חַיִל","and virtuous"], ["וּלְהֵיטִיב","and in doing good"], ["לְכׇל־אָדָם","to all men"], ["אָכֵן","indeed"], ["נֹאמַר","we may say"], ["כִּי","that"], ["הוֹלְכִים","follow"], ["אֲנַחְנוּ","we"], ["אַחַר","after"], ["עֲצַת","the admonition of"], ["פּוֹלוֹס","Paul"], ["אֶת־כֹּל","all things"], ["נַאֲמִין","we believe"], ["אֶת־כֹּל","all things"], ["נְקַוֶּה","we hope"], ["סָבַלְנוּ","we have endured"], ["דְּבָרִים","things"], ["רַבִּים","many"], ["וּנְקַוֶּה","and hope"], ["לִסְבֹּל","to be able to endure"], ["אֶת־כֹּל","all things"], ["אִם־יֵשׁ","If there is"], ["מַעֲשֵׂה","a deed of"], ["צֶדֶק","virtue"], ["אוֹ","or"], ["נָעִים","lovely"], ["אוֹ","or"], ["אֲשֶׁר","whose"], ["שָׁמְעוֹ","report"], ["טוֹב","is good"], ["אוֹ","or"], ["מַעֲשֵׂה","a deed of"], ["שֶׁבַח","praise"], ["אֶת־אֵלֶּה","after these things"], ["אֲנַחְנוּ","we"], ["מְבַקְּשִׁים","seek"], ["׃",""]]}
];
renderVerseSet(aof_ch1Verses, 'aof-ch1-verses');
})();
