// pgp_verses/js_history.js — JS-History verse data
(function() {
var jsh_ch1Verses = [
  { num: "א", words: [
    ["בִּגְלַל","on-account of"],["הַשְּׁמוּעוֹת","the-diligently(pl.f)"],["הָרַבּוֹת","the-many"],["אֲנָשִׁים","men"],["רָעִים","evil"],["עַל","upon"],["קוּמַת","the height of"],["קְהִילַּת","congregation-of"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["לְקַדִּישֵׁי","for-the holy ones of"],["אַחֲרִית","final-state-of"],["הַיָּמִים","the-days"],["וְהִתְקַדְּמוּתָהּ","and-advance-her"],["וְכֻלָּן","Okln"],["נוֹעֲדוּ","they assembled"],["לְהִלָּחֵם","to-fight"],["בְּשִׁמְעָהּ","in-report-its"],["וּבְהִתְקַדְּמוּתָהּ","and-in-advance-her"],["בָּעוֹלָם","in-the-world"],["הִתְעוֹרַרְתִּי","I-awakened"],["לִכְתֹּב","to-write"],["אֶת","[ACC]"],["הַתּוֹלְדוֹת","the-generations-of"],["הָאֵלֶּה","these"],["כְּדֵי","according to-the sufficiency of"],["לְתַקֵּן","to-repair"],["אֶת","[ACC]"],["דַּעַת","knowledge"],["הָעָם","the-people"],["וְלָתֵת","and-shout"],["לְכָל","to-all"],["מְבַקְשֵׁי","those-who-seek"],["הָאֱמֶת","the-truth"],["אֶת","[ACC]"],["הָעֻבְדּוֹת","the-bondage"],["כְּפִי","according-to"],["שֶׁקָּרוּ","falsehood-his"],["לִי","to-me"],["וְלַקְּהִילָּה,","and-to-the-congregation"],["כְּכָל","like-all"],["שֶׁהֵן","that-here!"],["בְּיָדִי.","into-my-hands"],["׃",""]
  ]},
  { num: "ב", words: [
    ["בַּתּוֹלְדוֹת","in-the-generations-of"],["אֵלֶּה","these"],["אֲסַפֵּר","I count"],["אֶת","[ACC]"],["הַשּׁוֹנִים","the-divers"],["בֶּאֱמֶת","in-truth"],["וּבְצֶדֶק","and-with-righteousness"],["כְּפִי","according-to"],["שֶׁקָּרוּ","falsehood-his"],["אוֹ","or"],["כְּפִי","according-to"],["שֶׁהֵם","that-they"],["עַתָּה,","now"],["בִּשְׁנַת","in-year-of"],["1838","1838"],["הַשָּׁנָה","the-year"],["הַשְּׁמִינִית","the-eighth(f)"],["מֵאָז","since"],["נוֹסְדָה","was-founded(f)"],["הַקְּהִילָּה.","the-congregation"],["׃",""]
  ]},
  { num: "ג", words: [
    ["נוֹלַדְתִּי","was-born"],["בִּשְׁנַת","in-year-of"],["1805,","1805"],["בְּיוֹם","in-day"],["הָעֶשְׂרִים","the-twenty"],["וּשְׁלוֹשָׁה","and-three"],["לְדֶצֶמְבֶּר,","of-December"],["בְּעִיר","in-the-city-of"],["שָׁרוֹן,","Sharon"],["מְחוֹז","the harbor of"],["וִינְדְּסוֹר,","Windsor"],["מְדִינַת","the province of"],["וֶרְמוֹנְט.","Vermont"],["אָבִי","my-father"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["עָזַב","left"],["אֶת","[ACC]"],["וֶרְמוֹנְט","Vermont"],["וְעָבַר","generation"],["לְפַלְמִירָה,","to-Palmyra"],["מְחוֹז","the harbor of"],["אוֹנְטָרְיוֹ","Ontario"],["(עַתָּה","now"],["וֵיין),","Oiin"],["בִּמְדִינַת","in-the-state-of"],["נְיוּ","New"],["יוֹרְק,","York"],["בֶּן","son-of"],["עֶשֶׂר","ten"],["בְּעֵרֶךְ.","in-they are arranging"],["כְּאַרְבַּע","about-four"],["שָׁנִים","years"],["אַחַר","after"],["כָּךְ","so"],["עָבַר","passed"],["עִם","with"],["מִשְׁפַּחְתּוֹ","his-family"],["לְמַנְצֶ׳סְטֶר","to-Manchester"],["בְּאוֹתוֹ","in-him"],["מְחוֹז.","the harbor of"],["׃",""]
  ]},
  { num: "ד", words: [
    ["מִשְׁפַּחְתּוֹ","his-family"],["מָנְתָה","the portion of"],["אַחַת","one"],["עֶשְׂרֵה","and-ten"],["נְפָשׁוֹת:","persons"],["אָבִי","my-father"],["יוֹסֵף","Joseph"],["סְמִית;","Smith"],["אִמִּי","my-mother"],["לוּסִי","Lucy"],["סְמִית,","Smith"],["שֶׁשְּׁמָהּ","that-name-its"],["לִפְנֵי","before"],["הָיָה","was"],["מַק","there-shall-be-stench"],["בַּת","daughter-of"],["שְׁלֹמֹה","Solomon"],["מַק;","rottenness"],["אַחַי","my-brothers"],["אַלְוִין","Alvin"],["(שֶׁמֵּת","that-died"],["בְּתִשְׁעָה","on-day nine"],["עָשָׂר","[compound]"],["לְנוֹבֶמְבֶּר","of-November"],["1823,","1823"],["בִּשְׁנָתוֹ","in-year-its"],["הָעֶשְׂרִים","the-twenty"],["וְשֵׁשׁ),","and-six"],["וְהָירָם,","and-the-it rose"],["וַאֲנִי,","and-ships"],["וּשְׁמוּאֵל","and-Samuel"],["הָרִיסוֹן,","the-Harrison"],["וְוִילְיָם,","and-William"],["וְדוֹן","and-a judgment"],["קָרְלוֹס;","Carlos"],["וַאֲחוֹתַי","and-declaration-my"],["סוֹפְרוֹנְיָה,","Sophronia"],["וְקָתְרִין,","and-Catherine"],["וְלוּסִי.","and-Lucy"],["׃",""]
  ]},
  { num: "ה", words: [
    ["בְּעֵרֶךְ","in-worth-of"],["שְׁנָתַיִם","two-years"],["אַחֲרֵי","after"],["שֶׁעָבַרְנוּ","that-we passed"],["לְמַנְצֶ׳סְטֶר","to-Manchester"],["הִתְעוֹרְרָה","she-awakened"],["בַּמָּקוֹם","in-the-place"],["הִתְרַגְּשׁוּת","excitement"],["בִּלְתִּי","except"],["רְגִילָה","common"],["בְּעִנְיְנֵי","as-pertaining-to-the-things-of"],["דָּת.","the law"],["הִתְחִילָה","she-began"],["עִם","with"],["הַמֶּתוֹדִיסְטִים","the-Methodists"],["וּמְהֵרָה","and-speedily"],["הִתְפַּשְּׁטָה","it-spread"],["בֵּין","among"],["כָּל","all"],["הָעֵדוֹת","the-churches"],["בָּאָרֶץ.","in-the-land"],["כָּל","all"],["הָאָרֶץ","the-land"],["נִרְאֲתָה","it has been seen"],["מֻשְׁפַּעַת,","from-the abundance of"],["וְהָמוֹן","and-a-multitude"],["רַב","great"],["הִצְטָרְפוּ","they-joined"],["לָעֵדוֹת","to-the-churches"],["הַשּׁוֹנוֹת,","the-different"],["וְזֶה","and-this"],["גָּרַם","caused"],["מְהוּמָה","a-movement"],["וּמַחֲלֹקֶת","and-a-great-division"],["לֹא","not"],["קְטַנָּה","small"],["בֵּין","among"],["הָעָם","the-people"],["אֵלֶּה","these"],["צוֹעֲקִים","crying-out"],["\"הִנֵּה","them"],["פֹּה!\"","the-mouth"],["וְאֵלֶּה","and-these"],["\"הִנֵּה","them"],["שָׁם!\"","there"],["אֵלֶּה","these"],["טוֹעֲנִים","claiming"],["לֶאֱמוּנַת","to-faith-of"],["הַמֶּתוֹדִיסְטִים,","the-Methodists"],["אֵלֶּה","these"],["לַפְּרֶסְבִּיטֶרְיָנִים,","to-the-Presbyterians"],["וְאֵלֶּה","and-these"],["לַבַּפְּטִיסְטִים.","to-the-Baptists"],["׃",""]
  ]},
  { num: "ו", words: [
    ["אַף","yea"],["שֶׁהָאַהֲבָה","that-love"],["הָרַבָּה","exceeding"],["הַמִּתְגַּיְּרִים","the-converts"],["בְּעֵת","at-the-time"],["וְהַקִּנְאָה","and-the-jealousy"],["הָרַבָּה","exceeding"],["הַכֹּהֲנִים","the-priests"],["שֶׁהֵקִימוּ","that-they had stationed"],["וְקִדְּמוּ","and-they met"],["אֶת","[ACC]"],["הַמַּחֲזֶה","the-vision"],["הַמֻּפְלָא","the-an extraordinary thing"],["הַזֶּה","this"],["שֶׁל","of"],["רֶגֶשׁ","crowd"],["דָּתִי","the laws of"],["לְמַעַן","that"],["שֶׁכֻּלָּם","that-all of-them"],["\"יִתְגַּיְּרוּ\"","???"],["כְּפִי","according-to"],["שֶׁקָּרְאוּ","that-summon"],["לָזֶה","to-the-this"],["לְאֵיזוֹ","to-which"],["עֵדָה","congregation"],["שֶׁיִּרְצוּ","that-they will be accepted"],["אֲבָל","but/however"],["כַּאֲשֶׁר","as"],["הַמִּתְגַּיְּרִים","the-converts"],["הֵחֵלּוּ","began"],["לָלֶכֶת","to-go"],["אֵלֶּה","these"],["לְכַת","going"],["זוֹ","this"],["וְאֵלֶּה","and-these"],["לְאַחֶרֶת,","belonged to the-other door"],["נִרְאָה","appeared"],["שֶׁרִגְשׁוֹתֵיהֶם","that-to be stormy-their"],["הַטּוֹבִים","the-fertile"],["לִכְאוֹרָה","to-as the-light"],["שֶׁל","of"],["הַכֹּהֲנִים","the-priests"],["וְהַמִּתְגַּיְּרִים","and-the-converts"],["הָיוּ","were"],["מְדֻמִּים","from-blood"],["יוֹתֵר","more"],["מֵאֲמִתִּיִּים.","genuine"],["מַחֲזֶה","vision"],["שֶׁל","of"],["מְבוּכָה","confusion"],["גְּדוֹלָה","great"],["וְרֶגֶשׁ","and-crowd"],["רַע","evil"],["בָּא","came"],["כֹּהֵן","one-priest"],["מִתְוַכֵּחַ","from-you reprove"],["נֶגֶד","against"],["כֹּהֵן","one-priest"],["נֶגֶד","against"],["עַד","until"],["שֶׁכָּל","that-every"],["רִגְשׁוֹתֵיהֶם","to be stormy-their"],["הַטּוֹבִים","the-fertile"],["זֶה","this"],["לָזֶה,","to-the-this"],["אִם","if"],["הָיוּ","were"],["כָּאֵלֶּה,","such"],["אָבְדוּ","were-lost"],["לְגַמְרֵי","utterly"],["בְּמַחֲלֹקֶת","in-a-great-division"],["דְּבָרִים","things"],["וּבְוִכּוּחַ","and-in-discussion"],["עַל","upon"],["דֵּעוֹת.","knowledge"],["׃",""]
  ]},
  { num: "ז", words: [
    ["בָּעֵת","at-this-time"],["הַהִיא","that"],["הָיִיתִי","I-was"],["בִּשְׁנָתִי","in-sleep"],["הַחֲמֵשׁ","the-five"],["עֶשְׂרֵה.","and-ten"],["מִשְׁפַּחַת","family-of"],["אָבִי","my-father"],["נִמְשְׁכָה","had-occupied"],["לֶאֱמוּנַת","to-faith-of"],["הַפְּרֶסְבִּיטֶרְיָנִים,","the-Presbyterians"],["וְאַרְבָּעָה","and-four"],["מֵהֶם","from-them"],["הִצְטָרְפוּ","they-joined"],["לַקְּהִילָּה","to-the-congregation"],["הַהִיא:","that"],["אִמִּי","my-mother"],["לוּסִי,","Lucy"],["וַאֲחַי","and-brother-of"],["הָירָם","the-it rose"],["וּשְׁמוּאֵל","and-Samuel"],["הָרִיסוֹן,","the-Harrison"],["וַאֲחוֹתִי","and-declaration-my"],["סוֹפְרוֹנְיָה.","Sophronia"],["׃",""]
  ]},
  { num: "ח", words: [
    ["בְּעֵת","at-the-time"],["הַהִתְרַגְּשׁוּת","the-excitement"],["הַגְּדוֹלָה","the-great"],["הַזֹּאת","this"],["נִקְרָא","called-was"],["לִבִּי","my-heart"],["לְהִרְהוּר","for-reflection"],["כָּבֵד","heavy"],["וּלְדַאֲגָה","and-to-anxiety"],["גְּדוֹלָה.","great"],["אַף","yea"],["הָיוּ","were"],["עֲמֻקִּים","deep"],["וּלְעִתִּים","and-of-times"],["חַדִּים,","sharp"],["עוֹד","more"],["שָׁמַרְתִּי","I-have-preserved"],["עַצְמִי","myself"],["רָחוֹק","far"],["מִכָּל","above-all"],["הַכִּתּוֹת","the-one which is crushed"],["הָאֵלֶּה,","these"],["אַף","yea"],["שֶׁבָּאתִי","that-I went"],["לַאֲסֵפוֹתֵיהֶם","to-the-their-meetings"],["כְּכָל","like-all"],["שֶׁיָּכֹלְתִּי.","that-have I been able"],["בִּמְרוּצַת","in-the running of"],["הַיָּמִים","the-days"],["נָטָה","He-had-stretched-out"],["לִבִּי","my-heart"],["קְצָת","the part of"],["לַמֶּתוֹדִיסְטִים","to-the-Methodists"],["וְחָשַׁקְתִּי","and-he furnished with bands(I)"],["לְהִצְטָרֵף","to-join"],["אֲלֵיהֶם,","unto-them"],["אֲבָל","but/however"],["כֹּה","thus"],["גְּדוֹלָה","great"],["הָיְתָה","was(f)"],["הַמְּבוּכָה","the-confusion"],["וְהַמַּחֲלֹקֶת","and-the-division"],["בֵּין","among"],["הַכִּתּוֹת","the-one which is crushed"],["עַד","until"],["שֶׁנַּעַר","Shinar"],["צָעִיר","young-man"],["כָּמוֹנִי,","is like-me"],["שֶׁלֹּא","that-there-should-be-no"],["הִכִּיר","he recognized"],["אֲנָשִׁים","men"],["וּדְבָרִים,","and-things-which"],["לֹא","not"],["יָכֹל","was-able"],["לָבוֹא","to-come"],["לְמַסְקָנָה","to-conclusion"],["בְּרוּרָה","plain"],["מִי","who"],["צוֹדֵק","right/correct"],["וּמִי","and-who"],["טוֹעֶה.","erring"],["׃",""]
  ]},
  { num: "ט", words: [
    ["לִבִּי","my-heart"],["הִתְרַגֵּשׁ","to be excited"],["לִפְעָמִים","to-times"],["מְאֹד,","Md)"],["כִּי","that"],["הַצַּעֲקָה","the-outcry"],["וְהַמְּהוּמָה","and-the-confusion"],["הָיוּ","were"],["גְּדוֹלוֹת","great"],["הַפְּרֶסְבִּיטֶרְיָנִים","the-Presbyterians"],["הִתְנַגְּדוּ","they-opposed"],["בְּתֹקֶף","with-boldness"],["לַבַּפְּטִיסְטִים","to-the-Baptists"],["וְלַמֶּתוֹדִיסְטִים,","and-to-the-Methodists"],["וְהִשְׁתַּמְּשׁוּ","and-they-used"],["בְּכָל","with-all"],["כֹּחוֹת","energies-of"],["הַהִגָּיוֹן","the-Higgaion"],["וְהָעָרְמָה","and-the-craftiness"],["לְהוֹכִיחַ","to-convince"],["אֶת","[ACC]"],["אוֹ","or"],["לְפָחוֹת","to-governors"],["לְגָרוֹם","to-cause"],["לָעָם","to-the-people"],["לַחְשֹׁב","devised"],["שֶׁהֵם","that-they"],["טוֹעִים.","erring"],["מִצַּד","on-the-other"],["אַחֵר,","he delayed"],["הַבַּפְּטִיסְטִים","the-Baptists"],["וְהַמֶּתוֹדִיסְטִים","and-the-Methodists"],["גַּם","also"],["הֵם","they"],["קִנְאוּ","certainly(they)"],["בְּשָׁוֶה","in-equal"],["לְהָקִים","to-raise-up"],["אֶת","[ACC]"],["וּלְהַפְרִיךְ","and-to-to refute"],["אֶת","[ACC]"],["כֻּלָּם.","all"],["׃",""]
  ]},
  { num: "י", words: [
    ["בְּתוֹךְ","in-midst-of"],["מִלְחֶמֶת","war-of"],["הַדְּבָרִים","the-things"],["הַזֹּאת","this"],["וּמְהוּמַת","and-panic of"],["הַדֵּעוֹת,","the-knowledge"],["פְּעָמִים","times"],["רַבּוֹת","many"],["אָמַרְתִּי","I-said"],["בְּלִבִּי:","in-my-heart"],["מָה","what"],["לַעֲשׂוֹת?","to-do"],["מִי","who"],["מִכָּל","above-all"],["הַכִּתּוֹת","the-one which is crushed"],["הָאֵלֶּה","these"],["צוֹדֵק,","right"],["אוֹ","or"],["הַאִם","whether"],["כֻּלָּן","all-of-them(f)"],["טוֹעוֹת","erring"],["יַחַד?","oft"],["אִם","if"],["אַחַת","one"],["מֵהֶן","of-them"],["צוֹדֶקֶת,","righteous"],["מִי","who"],["הִיא,","it-is"],["וְאֵיךְ","and-how"],["אֵדַע?","I knew"],["׃",""]
  ]},
  { num: "יא", words: [
    ["בְּעָמְלִי","in-toil-my"],["תַּחַת","under"],["הַקֹּשִׁי","the-hardness-of"],["הַגָּדוֹל","the-great/high"],["הַזֶּה","this"],["שֶׁנִּגְרַם","that-to be caused"],["מִמַּחֲלֹקֶת","from-division"],["כִּתּוֹת","one which is crushed"],["הַדָּת,","the-law"],["יוֹם","day"],["אֶחָד","one"],["קָרָאתִי","called"],["בְּאִגֶּרֶת","in-letter"],["יַעֲקֹב,","Jacob"],["פֶּרֶק","plunder"],["א׳","1st"],["פָּסוּק","verse"],["ה׳,","5th"],["הָאוֹמֵר:","the-say"],["\"אִם","the mother of"],["אֶחָד","one"],["מִכֶּם","from-you"],["חָסֵר","lacking"],["חָכְמָה,","wisdom"],["יִשְׁאַל","asks"],["מֵאֵת","from"],["הָאֱלֹהִים","God"],["הַנּוֹתֵן","the-which-gives"],["לְכֹל","for-all"],["בְּנָדִיבוּת","in-noble deeds"],["וְלֹא","and-not"],["יְגָעֵר,","he rebuked"],["וְיִנָּתֵן","and-shall-be-given"],["לוֹ.\"","to-him"],["׃",""]
  ]},
  { num: "יב", words: [
    ["מֵעוֹלָם","from-everlasting"],["לֹא","not"],["בָּא","came"],["פָּסוּק","verse"],["בְּכֹחַ","by-the-power-of"],["רַב","great"],["יוֹתֵר","more"],["אֶל","to/unto"],["לֵב","heart"],["אָדָם","man"],["מֵאֲשֶׁר","than"],["זֶה","this"],["בָּא","came"],["אֶל","to/unto"],["לִבִּי","my-heart"],["בָּעֵת","at-this-time"],["הַהִיא.","that"],["נִדְמָה","it was destroyed"],["שֶׁנִּכְנַס","that-to enter"],["בְּכֹחַ","by-the-power-of"],["גָּדוֹל","great"],["אֶל","to/unto"],["כָּל","all"],["רֶגֶשׁ","crowd"],["לִבִּי.","heart-my"],["הִרְהַרְתִּי","I-reflected"],["בּוֹ","in-him/it"],["שׁוּב","again"],["וָשׁוּב,","and-will you return?"],["בְּיָדְעִי","in-those who know"],["שֶׁאִם","that-if"],["מִישֶׁהוּ","from-he will lend(they)"],["צָרִיךְ","necessary"],["חָכְמָה","wisdom"],["מֵאֱלֹהִים","from-God"],["אֲנִי","I"],["הוּא.","he/it"],["לֹא","not"],["יָדַעְתִּי","I-know"],["מָה","what"],["לַעֲשׂוֹת,","to-do"],["וְאִם","and-if"],["לֹא","not"],["אֶשָּׂא","I-carry"],["חָכְמָה","wisdom"],["רַבָּה","great(f)"],["יוֹתֵר","more"],["מִמַּה","from-what?"],["שֶּׁהָיְתָה","that-was"],["לִי,","to-me"],["לֹא","not"],["אֵדַע","I-shall-know"],["לְעוֹלָם","forever"],["כִּי","that"],["מוֹרֵי","false-teachers"],["הַדָּת","the-law"],["שֶׁל","of"],["הַכִּתּוֹת","the-one which is crushed"],["הַשּׁוֹנוֹת","the-different"],["הֵבִינוּ","understand"],["אֶת","[ACC]"],["אוֹתָם","them"],["פְּסוּקֵי","verses-of"],["הַכָּתוּב","the-which-is-written"],["כֹּה","thus"],["שׁוֹנֶה","who repeats"],["עַד","until"],["שֶׁאָבַד","that-it has perished"],["כָּל","all"],["בִּטָּחוֹן","is hope"],["לִפְשֹׁט","to-strip"],["אֶת","[ACC]"],["הַשְּׁאֵלָה","the-asked"],["עַל","upon"],["יְדֵי","hands-of"],["פְּנִיָּה","its-face(f)"],["אֶל","to/unto"],["הַמִּקְרָא.","the-Mikra"],["׃",""]
  ]},
  { num: "יג", words: [
    ["לְבַסּוֹף","to-at-the end of"],["בָּאתִי","when-I-came"],["לִמְסַקָּנָה","to-conclusion"],["שֶׁעָלַי","handfuls of"],["לְהִשָּׁאֵר","to-remain"],["בַּחֹשֶׁךְ","in-darkness"],["וּבַמְּבוּכָה,","and-in-the-confusion"],["אוֹ","or"],["לַעֲשׂוֹת","to-do"],["כַּאֲשֶׁר","as"],["יַעֲקֹב","Jacob"],["מוֹרֶה","your-teacher"],["לִשְׁאֹל","to-ask"],["מֵאֵת","from"],["הָאֱלֹהִים.","God"],["הֶחְלַטְתִּי","the-snatch at(I)"],["לִשְׁאֹל","to-ask"],["מֵאֵת","from"],["הָאֱלֹהִים,","God"],["בְּהַסִּיקִי","in-the-Sikh (person)"],["שֶׁאִם","that-if"],["הוּא","he/it"],["נוֹתֵן","grants"],["חָכְמָה","wisdom"],["לַחֲסֵרֶיהָ","to-one lacking of-her"],["וְנוֹתֵן","and-giving"],["בְּנָדִיבוּת","in-noble deeds"],["וְלֹא","and-not"],["יְגָעֵר","he rebuked"],["אוּכַל","am-able"],["לְנַסּוֹת.","to-fled"],["׃",""]
  ]},
  { num: "יד", words: [
    ["לְפִי","according-to"],["הֶחְלָטָתִי","the-snatch at-my"],["לִשְׁאֹל","to-ask"],["מֵאֱלֹהִים,","from-God"],["הָלַכְתִּי","I-went"],["אֶל","to/unto"],["הַיַּעַר","the-forest"],["לְנַסּוֹת.","to-fled"],["הָיָה","was"],["זֶה","this"],["בְּבֹקֶר","in-morning"],["יוֹם","day"],["יָפֶה","fair"],["וּבָהִיר,","and-is brilliant"],["בְּרֵאשִׁית","in-beginning"],["הָאָבִיב","the-Abib"],["שֶׁל","of"],["שְׁנַת","year-of"],["1820.","1820"],["זֹאת","this"],["הָיְתָה","was(f)"],["הַפַּעַם","the-time"],["הָרִאשׁוֹנָה","the-first(f)"],["בְּחַיַּי","in-my-life"],["שֶׁנִּסִּיתִי","that-I have put to the test"],["דָּבָר","things"],["כָּזֶה,","such"],["כִּי","that"],["בְּתוֹךְ","in-midst-of"],["כָּל","all"],["דַּאֲגוֹתַי","so-much-concerned-my"],["עוֹד","more"],["לֹא","not"],["נִסִּיתִי","I have put to the test"],["לְהִתְפַּלֵּל","to-pray"],["בְּקוֹל.","with-a voice"],["׃",""]
  ]},
  { num: "טו", words: [
    ["אַחֲרֵי","after"],["שֶׁבָּאתִי","that-I went"],["אֶל","to/unto"],["הַמָּקוֹם","the-place"],["מֵרֹאשׁ,","from-the-beginning"],["הִבַּטְתִּי","look(I)"],["סָבִיב","round-about"],["וּמָצָאתִי","and-I-found"],["אֶת","[ACC]"],["עַצְמִי","myself"],["לְבַדִּי.","alone"],["כָּרַעְתִּי","as-the-distress-my"],["וְהֵחַלּוֹתִי","and-began(pl.f)-my"],["לְהַעֲלוֹת","puts-up"],["אֶת","[ACC]"],["מִשְׁאֲלוֹת","Mishal(pl)"],["לִבִּי","my-heart"],["אֶל","to/unto"],["הָאֱלֹהִים.","God"],["כִּמְעַט","nearly"],["עָשִׂיתִי","I-made"],["כֵּן,","so/thus"],["וּמִיָּד","and-immediately"],["נֶאֱחַזְתִּי","it was caught(I)"],["בְּכֹחַ","by-the-power-of"],["כָּלְשֶׁהוּ","whatsoever"],["שֶׁכָּבַשׁ","that-tread down"],["אוֹתִי","me"],["לְגַמְרֵי,","utterly"],["וְהָיְתָה","and-shall-be"],["לוֹ","to-him"],["הַשְׁפָּעָה","the-copiousness"],["מַדְהִימָה","amazing"],["עָלַי","I-must"],["לֶאֱסֹר","to-bind"],["אֶת","[ACC]"],["לְשׁוֹנִי","linguistic"],["עַד","until"],["שֶׁלֹּא","that-there-should-be-no"],["יָכֹלְתִּי","I-could"],["לְדַבֵּר.","to-speak"],["חֹשֶׁךְ","darkness"],["כָּבֵד","heavy"],["הִתְאַסֵּף","gathered themselves"],["סְבִיבִי,","surround-me"],["וְנִדְמָה","and-it was destroyed"],["לִי","to-me"],["לְרֶגַע","to-Rg"],["כְּאִלּוּ","as-if"],["נִגְזַרְתִּי","I have been cut off"],["לְאֲבַדּוֹן","to-Abaddon"],["׃",""]
  ]},
  { num: "טז", words: [
    ["אֲבָל","but/however"],["בְּכָל","with-all"],["כֹּחִי","my-strength"],["לִקְרֹא","to-read"],["אֶל","to/unto"],["הָאֱלֹהִים","God"],["לְהַצִּילֵנִי","hath-seen-fit-to-snatch-me"],["מִכֹּחַ","than-the-strength-of"],["הָאוֹיֵב","the-is-an-enemy"],["הַזֶּה","this"],["שֶׁאָחַז","that-it has seized"],["בִּי,","against-Me"],["וּבָרֶגַע","and-in-a moment"],["מַמָּשׁ","actual"],["שֶׁהָיִיתִי","that-I was"],["מוּכָן","prepared"],["לִשְׁקֹעַ","to-subside"],["בְּיֵאוּשׁ","in-despair"],["וּלְהִמָּסֵר","and-to-be-delivered"],["לַאֲבַדּוֹן","to-they-perished"],["לֹא","not"],["לַאֲבַדּוֹן","to-they-perished"],["מְדֻמֶּה","some of-blood-its"],["אֶלָּא","but-rather"],["לְכֹחוֹ","to-his-power"],["שֶׁל","of"],["יְצוּר","creature"],["מַמָּשִׁי","from-the-Mushi"],["מֵעוֹלָם","from-everlasting"],["הַנִּסְתָּר,","the-secret"],["שֶׁהָיָה","who-was"],["לוֹ","to-him"],["כֹּחַ","power"],["מַדְהִים","measurement(pl)"],["כָּזֶה","such"],["שֶׁמֵּעוֹלָם","that-were from-long ago"],["לֹא","not"],["הִרְגַּשְׁתִּי","I-felt"],["בְּשׁוּם","in-any"],["יְצוּר","creature"],["בָּרֶגַע","in-the-Rg"],["הַזֶּה","this"],["שֶׁל","of"],["בֶּהָלָה","sudden terror"],["גְּדוֹלָה","great"],["רָאִיתִי","I-saw"],["עַמּוּד","the pillar of"],["אוֹר","a-light"],["בְּדִיּוּק","precisely"],["מֵעַל","from-upon"],["רֹאשִׁי,","head-my"],["מֵעַל","from-upon"],["לְזֹהַר","to-brightness"],["הַשֶּׁמֶשׁ,","the-sun"],["שֶׁיָּרַד","that-is running down"],["לְאַט","softly"],["עַד","until"],["שֶׁנָּפַל","that-he fell"],["עָלַי.","I-must"],["׃",""]
  ]},
  { num: "יז", words: [
    ["מָצָאתִי","I-found"],["אֶת","[ACC]"],["עַצְמִי","myself"],["מֻצָּל","plucked out"],["מִן","from"],["הָאוֹיֵב","the-is-an-enemy"],["שֶׁאָסַר","that-yoke"],["אוֹתִי.","me"],["נָח","Noah"],["עָלַי,","I-must"],["רָאִיתִי","I-saw"],["שְׁתֵּי","two"],["דְּמוּיוֹת","figures"],["וּכְבוֹדָן","and-glory-of-their"],["אֵין","there-is-no"],["לְתָאֵר,","to-it turns"],["עוֹמְדוֹת","was standing(pl)"],["מֵעָלַי","from-me"],["בָּאֲוִיר.","in-the-air"],["אַחַת","one"],["מֵהֶן","of-them"],["דִּבְּרָה","spoke"],["אֵלַי,","unto-me"],["קוֹרֵאת","calling(f)"],["בִּשְׁמִי,","in-My-name"],["וְאָמְרָה","and-she will say"],["בְּהַצְבִּיעָהּ","in-the-painting"],["אֶל","to/unto"],["הַשְּׁנִיָּה:","the-second(f)"],["\"זֶה","this"],["בְּנִי","my-son"],["אֲהוּבִי.","my-beloved"],["שְׁמַע","hearken"],["לוֹ!\"","to-him"],["׃",""]
  ]},
  { num: "יח", words: [
    ["מַטָּרָתִי","own-purpose"],["בָּלֶכֶת","in-the-departing-of"],["לִשְׁאֹל","to-ask"],["מֵאֵת","from"],["יְהוָה","the-Lord"],["הָיְתָה","was(f)"],["לָדַעַת","to-know"],["אֵיזוֹ","which"],["מִכָּל","above-all"],["הַכִּתּוֹת","the-one which is crushed"],["צוֹדֶקֶת,","righteous"],["כְּדֵי","according to-the sufficiency of"],["שֶׁאֵדַע","that-will I know"],["לְאֵיזוֹ","to-which"],["לְהִצְטָרֵף.","to-join"],["לָכֵן,","therefore"],["עַל","upon"],["עַצְמִי","myself"],["עַד","until"],["שֶׁיָּכֹלְתִּי","that-have I been able"],["לְדַבֵּר,","to-speak"],["שָׁאַלְתִּי","I-inquired-of"],["אֶת","[ACC]"],["הַדְּמוּיוֹת","the-figures"],["הָעוֹמְדוֹת","the-standing(pl)"],["מֵעָלַי","from-me"],["בָּאוֹר","on the-light"],["אֵיזוֹ","which"],["מִכָּל","above-all"],["הַכִּתּוֹת","the-one which is crushed"],["צוֹדֶקֶת","righteous"],["כִּי","that"],["בָּעֵת","at-this-time"],["הַהִיא","that"],["לֹא","not"],["עָלָה","went-up"],["עַל","upon"],["לִבִּי","my-heart"],["שֶׁכֻּלָּן","that-everyone (female)"],["טוֹעוֹת","erring"],["וּלְאֵיזוֹ","and-to-which"],["לְהִצְטָרֵף.","to-join"],["׃",""]
  ]},
  { num: "יט", words: [
    ["נַעֲנֵיתִי","I have been afflicted"],["שֶׁעָלַי","handfuls of"],["שֶׁלֹּא","that-there-should-be-no"],["לְהִצְטָרֵף","to-join"],["לְאַחַת","to-one"],["מֵהֶן,","of-them"],["כִּי","that"],["כֻּלָּן","all-of-them(f)"],["טוֹעוֹת.","erring"],["וְהַדְּמוּת","and-the-likeness-of"],["שֶׁדִּבְּרָה","that-she spoke"],["אֵלַי","to-me"],["אָמְרָה","said"],["שֶׁכָּל","that-every"],["אֱמוּנוֹתֵיהֶן","faithfulness-their"],["תּוֹעֵבָה","abomination"],["בְּעֵינָיו;","in-view-his"],["שֶׁאוֹתָם","take!-their"],["הַמַּאֲמִינִים","the-believers"],["כֻּלָּם","all-of-them"],["מֻשְׁחָתִים;","are about to destroy"],["\"נִגָּשִׁים","taskmasters"],["אֵלַי","to-me"],["בְּשִׂפְתוֹתֵיהֶם","are on-lips-their"],["אֲבָל","but/however"],["לִבָּם","their-hearts"],["רָחוֹק","far"],["מִמֶּנִּי;","from-me"],["מְלַמְּדִים","teaching"],["תּוֹרוֹת","doctrines-of"],["שֶׁהֵן","that-here!"],["מִצְווֹת","the-commandments-of"],["אֲנָשִׁים,","men"],["וְיֵשׁ","and-there-are"],["לָהֶם","unto-them"],["צוּרַת","the-form-of"],["יִרְאַת","the-fear-of"],["אֱלֹהִים","God"],["אֲבָל","but/however"],["כֹּחָהּ","produce-its"],["הֵם","they"],["מַכְחִישִׁים.\"","???"],["׃",""]
  ]},
  { num: "כ", words: [
    ["שׁוּב","again"],["אָסַר","has-forbidden"],["עָלַי","I-must"],["לְהִצְטָרֵף","to-join"],["לְאַחַת","to-one"],["מֵהֶן,","of-them"],["וְדִבְּרִים","and-things-which"],["רַבִּים","many"],["אֲחֵרִים","other"],["אָמַר","said"],["לִי","to-me"],["שֶׁאֵינֶנִּי","that-not-I"],["יָכוֹל","Almighty"],["לִכְתֹּב","to-write"],["בָּעֵת","at-this-time"],["הַזֹּאת.","this"],["לְעַצְמִי,","to-bones-my"],["מָצָאתִי","I-found"],["אֶת","[ACC]"],["עַצְמִי","myself"],["שׁוֹכֵב","lying-down"],["עַל","upon"],["גַּבִּי,","defenses of"],["מַבִּיט","one who looks"],["לַשָּׁמַיִם.","to the-heavens"],["הָלַךְ,","went"],["לֹא","not"],["הָיָה","was"],["לִי","to-me"],["כֹּחַ,","strength"],["אֲבָל","but/however"],["מְהֵרָה","soon"],["הִתְאוֹשַׁשְׁתִּי","I-recovered"],["מְעַט","a-little"],["וְהָלַכְתִּי","and-I will walk"],["הַבַּיְתָה.","the-house-towards"],["עַל","upon"],["הָאָח,","the-fire-pot"],["שָׁאֲלָה","she will ask"],["אִמִּי","my-mother"],["מַה","what"],["קָּרָה.","happened"],["עָנִיתִי:","Niti"],["\"אַל","may not"],["דְּאָגָה,","anxiety"],["הַכֹּל","all-the"],["בְּסֵדֶר,","in-order"],["אֲנִי","I"],["בְּסֵדֶר.\"","in-order"],["אָז","then"],["אָמַרְתִּי","I-said"],["לְאִמִּי:","O-My-nation"],["\"לָמַדְתִּי","having-been-taught"],["לְעַצְמִי","to-myself"],["שֶׁאֱמוּנַת","that-the steadiness of"],["הַפְּרֶסְבִּיטֶרְיָנִים","the-Presbyterians"],["אֵינֶנָּה","is-not"],["אֲמִתִּית.\"","they-were"],["׃",""]
  ]},
  { num: "כא", words: [
    ["יָמִים","days"],["אֲחָדִים","a-few"],["אַחֲרֵי","after"],["הַמַּרְאָה","the-vision"],["הַזֹּאת","this"],["קָרָה","happened"],["שֶׁהָיִיתִי","that-I was"],["בְּחֶבְרַת","in the-joined set"],["אֶחָד","one"],["מִכֹּהֲנֵי","one-of-the-priests-of"],["הַמֶּתוֹדִיסְטִים,","the-Methodists"],["שֶׁהָיָה","who-was"],["פָּעִיל","active"],["מְאוֹד","very"],["בָּהִתְרַגְּשׁוּת","in-the-excitement"],["הַדָּתִית","the-religious"],["בְּדַבְּרִי","when-speak-I"],["אִתּוֹ","with-him"],["עַל","upon"],["עִנְיְנֵי","part-of-the-people"],["דָּת,","the law"],["לָקַחְתִּי","I-have-taken"],["הִזְדַּמְּנוּת","opportunity"],["לְסַפֵּר","to-tell"],["לוֹ","to-him"],["אֶת","[ACC]"],["הַמַּרְאָה","the-vision"],["שֶׁרָאִיתִי.","that-I have seen"],["הִפְתִּיעָה","it-surprised"],["אוֹתִי","me"],["מְאוֹד","very"],["הִתְנַהֲגוּתוֹ","behavior-his"],["הִתְיַחֵס","to relate to"],["לִדְבָרַי","to-my-words"],["לֹא","not"],["רַק","only"],["בְּקַלּוּת","with-ease"],["אֶלָּא","but-rather"],["בְּבוּז","in-contempt"],["גָּדוֹל,","great"],["וְאָמַר","and-says"],["שֶׁהַכֹּל","that-the-all"],["מִן","from"],["הַשָּׂטָן,","the-Adversary"],["שֶׁאֵין","whom-not"],["דְּבָרִים","things"],["כְּמוֹ","as/like"],["מַרְאוֹת","visions-of"],["וְגִלּוּיִים","and-who is uncovered of(pl)"],["בַּיָּמִים","in-the-days"],["הָאֵלֶּה,","these"],["שֶׁכָּל","that-every"],["הַדְּבָרִים","the-things"],["הָאֵלֶּה","these"],["פָּסְקוּ","to cease-his"],["עִם","with"],["הַשְּׁלִיחִים","the-apostles"],["וְלֹא","and-not"],["יִהְיוּ","shall-be"],["עוֹד.","more"],["׃",""]
  ]},
  { num: "כב", words: [
    ["מְהֵרָה","soon"],["גִּלִּיתִי","I have made known"],["שֶׁסִּפּוּרִי","that-narrative"],["עוֹרֵר","it-stirs-up"],["דַּעַת","knowledge"],["רַבָּה","great(f)"],["נֶגְדִּי","before-Me"],["בֵּין","among"],["הַמַּאֲמִינִים,","the-believers"],["וְהָיָה","and-it-shall-come-to-pass"],["סִבַּת","cause-of"],["רְדִיפָה","persecution"],["גְּדוֹלָה","great"],["שֶׁהָלְכָה","that-it went"],["וְגָבְרָה.","and-prevailed-her"],["וְאַף","and-even"],["שֶׁהָיִיתִי","that-I was"],["נַעַר","a-young-man"],["אָלוּם,","Alum"],["רַק","only"],["בֵּין","among"],["אַרְבַּע","four"],["עֶשְׂרֵה","and-ten"],["לַחֲמֵשׁ","to-the-and-nine-years"],["עֶשְׂרֵה","and-ten"],["שָׁנָה,","year"],["וְנְסִיבוֹת","and-circumstances"],["חַיַּי","my-life"],["כָּאֵלֶּה","such"],["שֶׁעָשׂוּ","that-had done"],["אוֹתִי","me"],["לְנַעַר","to-a youth"],["לְלֹא","to-not"],["חָשׁוּב","important"],["בָּעוֹלָם","in-the-world"],["אֲנָשִׁים","men"],["בַּעֲלֵי","they-are"],["מַעֲמָד","position"],["רָם","is-exalted"],["שָׂמוּ","employed"],["לֵב","heart"],["מַסְפִּיק","sufficient"],["לְעוֹרֵר","to-it-stirs-up"],["אֶת","[ACC]"],["דַּעַת","knowledge"],["הַקָּהָל","the-multitude"],["נֶגְדִּי","before-Me"],["וְלִיצֹר","and-to-one who forms"],["רְדִיפָה","persecution"],["מָרָה.","bitter"],["וְזֶה","and-this"],["הָיָה","was"],["מְשֻׁתָּף","common"],["לְכָל","to-all"],["הַכִּתּוֹת","the-one which is crushed"],["כֻּלָּן","all-of-them(f)"],["הִתְאַחֲדוּ","were-united"],["לִרְדֹּף","should-persecute"],["אוֹתִי.","me"],["׃",""]
  ]},
  { num: "כג", words: [
    ["גָּרַם","caused"],["לִי","to-me"],["לְהִרְהוּר","for-reflection"],["כָּבֵד","heavy"],["אָז","then"],["וּפְעָמִים","and-times"],["רַבּוֹת","many"],["מֵאָז:","since"],["כַּמָּה","the-how-many/how-much"],["מוּזָר","Mozr"],["שֶׁנַּעַר","Shinar"],["אָלוּם,","Alum"],["מְעַט","a-little"],["מֵעַל","from-upon"],["אַרְבַּע","four"],["עֶשְׂרֵה","and-ten"],["שָׁנָה,","year"],["שֶׁעוֹד","that-again"],["נֶאֱלָץ","was-compelled"],["לְהַשִּׂיג","obtain"],["פַּרְנָסָה","livelihood"],["דַּלָּה","the loom"],["בַּעֲבוֹדַת","in-work-of"],["יָדָיו,","hands-his"],["יֵחָשֵׁב","it-is-reckoned"],["לְאִישׁ","for-a-man"],["חָשׁוּב","important"],["דַּיּוֹ","ink"],["לִמְשֹׁךְ","to-draw/pull"],["תְּשׂוּמַת","deposited property of"],["לֵב","heart"],["הַגְּדוֹלִים","the-high/great"],["שֶׁל","of"],["הַכִּתּוֹת","the-one which is crushed"],["וּבְאֹפֶן","and-in-manner"],["לִיצֹר","of-Jezer"],["בָּהֶם","in-them"],["רוּחַ","spirit"],["רְדִיפָה","persecution"],["וְגִדּוּף","and-vilification"],["הַמָּרִים","the-bitter things"],["בְּיוֹתֵר.","Biotr"],["אֲבָל","but/however"],["מוּזָר","Mozr"],["אוֹ","or"],["לֹא,","not"],["כֵּן","so/thus"],["הָיָה,","was"],["וְזֶה","and-this"],["הָיָה","was"],["פְּעָמִים","times"],["רַבּוֹת","many"],["סִבַּת","cause-of"],["צַעַר","grief"],["גָּדוֹל","great"],["לִי.","to-me"],["׃",""]
  ]},
  { num: "כד", words: [
    ["אוּלָם","nevertheless"],["הָיְתָה","was(f)"],["זֹאת","this"],["עֻבְדָּה","was making"],["שֶׁרָאִיתִי","that-I have seen"],["מַרְאָה.","the sights of"],["חָשַׁבְתִּי","I-had-supposed"],["מֵאָז","since"],["שֶׁהִרְגַּשְׁתִּי","that-I-felt"],["כְּמוֹ","as/like"],["פָּאוּלוּס","Paulus"],["כַּאֲשֶׁר","as"],["הֵגֵן","Hgn"],["עַל","upon"],["עַצְמוֹ","himself"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["אַגְרִיפָּס","Agrippa"],["וְסִפֵּר","and-he-had-related"],["אֶת","[ACC]"],["מַרְאָתוֹ","craw-its"],["כְּשֶׁרָאָה","as-is dwelling"],["אוֹר","a-light"],["וְשָׁמַע","and-heard"],["קוֹל","the-voice-of"],["אֲבָל","but/however"],["עוֹד","more"],["מְעַטִּים","few"],["הֶאֱמִינוּ","did-they-believe"],["לוֹ.","to-him"],["אֵלֶּה","these"],["אָמְרוּ","they-said"],["שֶׁהוּא","that-He-is"],["וַאֲחֵרִים","and-others"],["אָמְרוּ","they-said"],["שֶׁהוּא","that-He-is"],["מְשֻׁגָּע,","he-is-mad"],["וְלָעֲגוּ","and-Lgo"],["לוֹ","to-him"],["אֲבָל","but/however"],["כָּל","all"],["זֶה","this"],["לֹא","not"],["הָרַס","the-he has torn down"],["אֶת","[ACC]"],["אֲמִתּוּת","truth"],["מַרְאָתוֹ.","craw-its"],["הוּא","he/it"],["רָאָה","saw"],["מַרְאָה,","the sights of"],["הוּא","he/it"],["יָדַע","he-knew"],["וְכָל","and-all"],["הָרְדִיפָה","the-persecution"],["תַּחַת","under"],["הַשָּׁמַיִם","the-heavens"],["לֹא","not"],["יָכְלָה","she-was-able"],["לְשַׁנּוֹת","to-change"],["זֹאת.","this"],["עַד","until"],["מָוֶת,","death"],["עוֹד","more"],["יָדַע","he-knew"],["וְיֵדַע","so-he may know"],["עַד","until"],["נְשִׁימָתוֹ","we-will-that-they will die"],["הָאַחֲרוֹנָה","the-last"],["שֶׁרָאָה","is dwelling"],["אוֹר","a-light"],["וְשָׁמַע","and-heard"],["קוֹל","the-voice-of"],["מְדַבֵּר","speaking"],["אֵלָיו,","unto-him"],["וְכָל","and-all"],["הָעוֹלָם","the-world"],["לֹא","not"],["יָכֹל","was-able"],["לְגָרוֹם","to-cause"],["לוֹ","to-him"],["לַחֲשֹׁב","to-suppose"],["אוֹ","or"],["לְהַאֲמִין","to-believe"],["אַחֶרֶת.","I-should-engrave"],["׃",""]
  ]},
  { num: "כה", words: [
    ["כֵּן","so/thus"],["הָיָה","was"],["עִמִּי.","my-people"],["רָאִיתִי","I-saw"],["בֶּאֱמֶת","in-truth"],["אוֹר,","a-light"],["וּבְתוֹךְ","and-within"],["הָאוֹר","the-light"],["הַהוּא","that"],["רָאִיתִי","I-saw"],["שְׁתֵּי","two"],["דְּמוּיוֹת,","figures"],["וְהֵן","and-here!"],["דִּבְּרוּ","have-spoken"],["אֵלַי","to-me"],["בֶּאֱמֶת.","in-truth"],["וְאַף","and-even"],["עַל","upon"],["אָמְרִי","said-my"],["שֶׁרָאִיתִי","that-I have seen"],["מַרְאָה","vision"],["עוֹד","more"],["אֱמֶת","true"],["הָיָה.","was"],["וּבְעוֹדָם","and-while-they"],["רוֹדְפִים","pursuing"],["וּמְגַדְּפִים","and-revile-against"],["וּמְדַבְּרִים","and-we-talk-of"],["עָלַי","I-must"],["כָּל","all"],["רָע","evil"],["בַּשֶּׁקֶר","in-the-falsehood"],["עַל","upon"],["אָמְרִי","said-my"],["כֵּן,","so/thus"],["הִתְעוֹרַרְתִּי","I-awakened"],["לֹאמַר","saying"],["בְּלִבִּי:","in-my-heart"],["לָמָה","why?"],["רוֹדְפִים","pursuing"],["אוֹתִי","me"],["עַל","upon"],["אֲמִירַת","saying-of"],["הָאֱמֶת?","the-truth"],["רָאִיתִי","I-saw"],["בֶּאֱמֶת","in-truth"],["מַרְאָה,","the sights of"],["וּמִי","and-who"],["אֲנִי","I"],["שֶׁאוּכַל","that-I am able"],["לַעֲמֹד","to-stand"],["נֶגֶד","against"],["הָאֱלֹהִים,","God"],["אוֹ","or"],["לָמָה","why?"],["חוֹשֵׁב","thinking"],["הָעוֹלָם","the-world"],["לְגָרוֹם","to-cause"],["לִי","to-me"],["לְהַכְחִישׁ","the-power-of"],["אֵת","[ACC]"],["אֲשֶׁר","which"],["רָאִיתִי","I-saw"],["בֶּאֱמֶת?","in-truth"],["כִּי","that"],["רָאִיתִי","I-saw"],["מַרְאָה.","the sights of"],["יָדַעְתִּי","I-know"],["זֹאת","this"],["וְיָדַעְתִּי","and-I-know"],["שֶׁאֱלֹהִים","that-these(pl)"],["יָדַע","he-knew"],["זֹאת,","this"],["וְלֹא","and-not"],["יָכֹלְתִּי","I-could"],["וְלֹא","and-not"],["הֵעַזְתִּי","the-Gazites"],["יָדַעְתִּי","I-know"],["שֶׁבַּעֲשׂוֹתִי","that-when-bring about-I"],["כֵן","thus"],["אֶפְגַּע","I will meet"],["בֵּאלֹהִים","in-God"],["וְאָבוֹא","and-I-will-come"],["׃",""]
  ]},
  { num: "כו", words: [
    ["הִשְׂבַּעְתִּי","I will satisfy"],["עַתָּה","now"],["אֶת","[ACC]"],["דַּעְתִּי","my-knowledge"],["בְּנוֹגֵעַ","in-it was touching"],["לָעוֹלָם","to-the-world"],["הַכִּתָּתִי","the-he crushed to pieces-my"],["שֶׁלֹּא","that-there-should-be-no"],["חוֹבָתִי","a debt-my"],["לְהִצְטָרֵף","to-join"],["לְאַחַת","to-one"],["מֵהֶן,","of-them"],["אֶלָּא","but-rather"],["לְהִשָּׁאֵר","to-remain"],["כַּאֲשֶׁר","as"],["הָיִיתִי","I-was"],["עַד","until"],["הוֹרָאָה","instruction"],["מָצָאתִי","I-found"],["אֶת","[ACC]"],["עֵדוּת","testimony"],["יַעֲקֹב","Jacob"],["אֲמִתִּית","they-were"],["שֶׁאָדָם","that-humankind"],["הַחָסֵר","the-lacking"],["חָכְמָה","wisdom"],["יָכוֹל","Almighty"],["לִשְׁאֹל","to-ask"],["מֵאֵת","from"],["הָאֱלֹהִים","God"],["וּלְקַבֵּל","and-to-receive!"],["וְלֹא","and-not"],["יְגֹעַר","he rebuked"],["בּוֹ.","in-Him"],["׃",""]
  ]},
  { num: "כז", words: [
    ["הִמְשַׁכְתִּי","I-continued"],["בַּעֲבוֹדוֹתַי","in-the-serve-my"],["הָרְגִילוֹת","the-regular(pl)"],["בַּחַיִּים","in-the-life"],["עַד","until"],["הָעֶשְׂרִים","the-twenty"],["וְאֶחָד","and-first"],["לְסֶפְּטֶמְבֶּר","of-September"],["1823,","1823"],["כָּל","all"],["הַזְּמַן","the-time"],["סוֹבֵל","suffering"],["רְדִיפָה","persecution"],["קָשָׁה","a-serious"],["מִכָּל","above-all"],["סוּגֵי","types-of"],["הָאֲנָשִׁים,","the-men"],["דָּתִיִּים","religious"],["וְלֹא","and-not"],["דָתִיִּים,","religious"],["כִּי","that"],["הִמְשַׁכְתִּי","I-continued"],["לְהַצְהִיר","to-declare"],["שֶׁרָאִיתִי","that-I have seen"],["מַרְאָה.","the sights of"],["׃",""]
  ]},
  { num: "כח", words: [
    ["בַּזְּמַן","in-the-time"],["שֶׁעָבַר","that-it passed"],["בֵּין","among"],["הַמַּרְאָה","the-vision"],["לִשְׁנַת","to-year-of"],["1823","1823"],["עָלַי","I-must"],["לְהִצְטָרֵף","to-join"],["לְכָל","to-all"],["כַּת","sect"],["דָּתִית,","religious(f)"],["וּבִהְיוֹתִי","and-being"],["צָעִיר","young-man"],["מְאוֹד","very"],["וְנִרְדָּף","and-what was pursued"],["מֵאֵלֶּה","than-these"],["שֶׁהָיוּ","who-were"],["צְרִיכִים","needing"],["לִהְיוֹת","to-be"],["יְדִידַי","my-beloved"],["וּלְהִתְיַחֵס","and-to-to relate to"],["אֵלַי","to-me"],["בְּטוּב","on-the goodness of"],["(וְאִם","and-a-mother"],["חָשְׁבוּ","they-supposed"],["שֶׁאֲנִי","that-I"],["מְרֻמֶּה,","deceit"],["הָיוּ","were"],["צְרִיכִים","needing"],["לְנַסּוֹת","to-fled"],["בְּאֹפֶן","in-a-manner"],["נָאוֹת","the pastures of"],["וְאוֹהֵב","and-a-lover"],["נֶעֱזַבְתִּי","forsaken(I)"],["לְכָל","to-all"],["מִינֵי","kinds-of"],["וּבְהִתְעָרְבִי","and-in-make a wager-my"],["עִם","with"],["כָּל","all"],["מִינֵי","kinds-of"],["חֶבְרָה,","was joined together"],["נָפַלְתִּי","I have fallen"],["פְּעָמִים","times"],["רַבּוֹת","many"],["בִּשְׁגִיאוֹת","in-errors-of"],["שְׁטוּתִיּוֹת","foolishness"],["רַבּוֹת","many"],["וְהֶרְאֵיתִי","and-I-showed"],["אֶת","[ACC]"],["חֻלְשַׁת","weakness-of"],["הַנֹּעַר","the-youth"],["הַטֶּבַע","the-nature"],["הָאֱנוֹשִׁי,","the-human"],["אֲנִי","I"],["לוֹמַר,","say"],["לְפִתּוּיִים","to-temptation(pl)"],["שׁוֹנִים","divers"],["בְּעֵינֵי","in-eyes-of"],["הָאֱלֹהִים.","God"],["בְּהוֹדָאָה","in-gratitude"],["זֹאת,","this"],["אַל","do-not"],["יַחְשֹׁב","he-thinks"],["אֶחָד","one"],["בַּחֲטָאִים","into-transgression"],["גְּדוֹלִים","great"],["אוֹ","or"],["רָעִים","evil"],["נְטִיָּה","inclination"],["לַעֲשׂוֹת","to-do"],["כָּאֵלֶּה","such"],["לֹא","not"],["הָיְתָה","was(f)"],["מֵעוֹלָם","from-everlasting"],["בְּטִבְעִי.","in-natural"],["אֲבָל","but/however"],["אָשַׁמְתִּי","my-guilt"],["בְּקַלּוּת","with-ease"],["רֹאשׁ,","head"],["וְלִפְעָמִים","and-to-times"],["עִם","with"],["חֶבְרָה","company"],["עַלִּיזָה","jubilant"],["וְכַדּוֹמֶה","and-as-the-is like"],["לֹא","not"],["מַתְאִים","from-the-chambers"],["לָאֹפִי","to-anger-my"],["שֶׁצָּרִיךְ","that-opponents-your"],["לִשְׁמֹר","to-keep"],["מִי","who"],["שֶׁנִּקְרָא","that-one who is called"],["מֵאֵת","from"],["הָאֱלֹהִים","God"],["כְּמוֹ","as/like"],["אֲבָל","but/however"],["זֶה","this"],["לֹא","not"],["יֵרָאֶה","He-shall-manifest-Himself"],["מוּזָר","Mozr"],["לְמִי","to-whom"],["אֶת","[ACC]"],["נְעוּרַי","youth-my"],["וּמַכִּיר","and-recognizer-of"],["אֶת","[ACC]"],["טִבְעִי","natural"],["הַשַּׂמֵּחַ","the-happy"],["׃",""]
  ]},
  { num: "כט", words: [
    ["בִּגְלַל","on-account of"],["הַדְּבָרִים","the-things"],["הָאֵלֶּה","these"],["הִרְגַּשְׁתִּי","I-felt"],["פְּעָמִים","times"],["רַבּוֹת","many"],["מְגֹנֶה","blindness"],["עַל","upon"],["חֻלְשׁוֹתַי","weak-my"],["בְּעֶרֶב","in-the evening of"],["הָעֶשְׂרִים","the-twenty"],["וְאֶחָד","and-first"],["לְסֶפְּטֶמְבֶּר","of-September"],["הַנִּזְכָּר,","the-said"],["אַחֲרֵי","after"],["שָׁכַבְתִּי","I lay with"],["עַל","upon"],["מִשְׁכָּבִי","bed-my"],["לַלַּיְלָה,","by-the-night"],["פָּנִיתִי","Pniti"],["לִתְפִלָּה","to-prayer"],["וּתְחִנָּה","and-favor"],["אֶל","to/unto"],["הָאֵל","the-God"],["הַכֹּל","all-the"],["יָכוֹל","Almighty"],["לִסְלִיחָה","to-pardon"],["עַל","upon"],["כָּל","all"],["חֲטָאַי","sins-my"],["וְגַם","and-also"],["לְגִלּוּי","to-who is uncovered of"],["לִי","to-me"],["לְמַעַן","that"],["אֵדַע","I-shall-know"],["אֶת","[ACC]"],["מַצָּבִי","from-the-beauty"],["וּמַעֲמָדִי","and-from-the-standing place-my"],["לְפָנָיו","before-Him"],["כִּי","that"],["הָיָה","was"],["לִי","to-me"],["בִּטָּחוֹן","is hope"],["שָׁלֵם","whole"],["לָשֵׂאת","to-bear"],["גִּלּוּי","who is uncovered of"],["אֱלֹהִי,","God"],["כַּאֲשֶׁר","as"],["קִבַּלְתִּי","I-received"],["לְפָנִים","formerly"],["אֶחָד.","one"],["׃",""]
  ]},
  { num: "ל", words: [
    ["בְּעוֹדִי","while-I-was"],["קוֹרֵא","calling"],["כָּךְ","so"],["אֶל","to/unto"],["הָאֱלֹהִים,","God"],["גִּלִּיתִי","I have made known"],["אוֹר","a-light"],["מוֹפִיעַ","appearing"],["בְּחַדְרִי","in-my-room"],["שֶׁהָלַךְ","that-he came"],["וְגָבַר","and-it prevailed"],["עַד","until"],["שֶׁהֶחָדֶר","that-the-chamber"],["הָיָה","was"],["מֵאִיר","was-lit"],["יוֹתֵר","more"],["מִבַּצָּהֳרַיִם,","from-at-noon"],["וּמִיָּד","and-immediately"],["נִרְאֲתָה","it has been seen"],["דְּמוּת","likeness-of"],["עַל","upon"],["יַד","hand-of"],["מִשְׁכָּבִי,","bed-my"],["עוֹמֶדֶת","Omdt"],["בָּאֲוִיר","in-the-air"],["כִּי","that"],["רַגְלָיו","his-feet"],["לֹא","not"],["נָגְעוּ","touching"],["בָּרִצְפָּה.","in-the-the pavement"],["׃",""]
  ]},
  { num: "לא", words: [
    ["הָיָה","was"],["עָלָיו","upon-him"],["גְּלִימָה","cloak"],["רְפוּיָה","healing"],["לְבָנָה","to-build"],["נֶהְדֶּרֶת","glorious(f)"],["בְּיוֹתֵר,","Biotr"],["לֹבֶן","whiteness"],["מֵעֵבֶר","across"],["לְכָל","to-all"],["דָּבָר","things"],["אַרְצִי","to-the-earth-my"],["שֶׁרָאִיתִי","that-I have seen"],["מֵעוֹלָם","from-everlasting"],["וְלֹא","and-not"],["מַאֲמִין","believing"],["אֲנִי","I"],["שֶׁדָּבָר","that-anything"],["אַרְצִי","to-the-earth-my"],["יָכוֹל","Almighty"],["לְהֵרָאוֹת","appear"],["כֹּה","thus"],["לָבָן","Laban"],["וּבָהִיר.","and-is brilliant"],["יָדָיו","His-hands"],["הָיוּ","were"],["וּזְרוֹעוֹתָיו","and-arms-his"],["גַּם","also"],["מְעַט","a-little"],["מֵעַל","from-upon"],["הַפֶּרֶק;","the-parting of ways"],["וְכֵן","and-thus"],["רַגְלָיו","his-feet"],["גְּלוּיוֹת","who is uncovered of(pl)"],["וְשׁוֹקָיו","and-his-legs"],["מְעַט","a-little"],["מֵעַל","from-upon"],["הַקַּרְסֹל.","the-ankle"],["רֹאשׁוֹ","his-head"],["וְצַוָּארוֹ","and-his-neck"],["גַּם","also"],["הָיוּ","were"],["רָאִיתִי","I-saw"],["שֶׁאֵין","whom-not"],["עָלָיו","upon-him"],["לְבוּשׁ","clothing"],["אַחֵר","other"],["זוּלָתִי","except"],["הַגְּלִימָה","the-cloak"],["הַזֹּאת,","this"],["כִּי","that"],["הָיְתָה","was(f)"],["פְּתוּחָה","open"],["עַד","until"],["שֶׁיָּכֹלְתִּי","that-have I been able"],["לִרְאוֹת","to-see"],["אֶל","to/unto"],["חָזֵהוּ.","his-bosom"],["׃",""]
  ]},
  { num: "לב", words: [
    ["לֹא","not"],["רַק","only"],["גְּלִימָתוֹ","his-cloak"],["הָיְתָה","was(f)"],["לְבָנָה","to-build"],["בְּיוֹתֵר,","Biotr"],["אֶלָּא","but-rather"],["כָּל","all"],["גּוּפוֹ","his-body"],["הָיָה","was"],["נֶהְדָּר","glorious"],["מֵעֵבֶר","across"],["וּפָנָיו","and-his-countenance"],["בֶּאֱמֶת","in-truth"],["כַּבָּרָק.","as-the-lightning"],["הֶחָדֶר","the-chamber"],["הָיָה","was"],["מֵאִיר","was-lit"],["מְאוֹד,","very"],["אֲבָל","but/however"],["לֹא","not"],["כֹּה","thus"],["בָּהִיר","is brilliant"],["כְּסָבִיב","as-round-about"],["גּוּפוֹ.","his-body"],["בְּהַבִּיטִי","as-I-looked"],["עָלָיו","upon-him"],["בָּרִאשׁוֹנָה","at-first"],["פָּחַדְתִּי,","awe of-me"],["אֲבָל","but/however"],["הַפַּחַד","the-fear"],["עָבַר","passed"],["מְהֵרָה.","soon"],["׃",""]
  ]},
  { num: "לג", words: [
    ["קָרָא","called"],["לִי","to-me"],["בִשְׁמִי","in-My-name"],["וְאָמַר","and-says"],["לִי","to-me"],["שֶׁהוּא","that-He-is"],["שָׁלִיחַ","it was sent out"],["שָׁלוּחַ","sent"],["מִלִּפְנֵי","from-the-presence-of"],["הָאֱלֹהִים","God"],["אֵלַי,","unto-me"],["וּשְׁמוֹ","whose-name-was"],["מוֹרוֹנִי;","Moroni"],["שֶׁלֵּאלֹהִים","that-God"],["יֵשׁ","there"],["מְלָאכָה","work"],["לִי","to-me"],["לַעֲשׂוֹת;","to-do"],["וּשְׁמִי","and-name-my"],["יִהְיֶה","shall-be"],["יָדוּעַ","known"],["לְטוֹב","for-good"],["וּלְרַע","and-to-evil"],["בֵּין","among"],["כָּל","all"],["הַגּוֹיִם","the-nations"],["וְהַמִּשְׁפָּחוֹת","and-the-kindreds"],["וְהַלְּשׁוֹנוֹת,","and-the-tongues"],["אוֹ","or"],["שֶׁיְּדֻבַּר","when-it will be spoken"],["עָלָיו","upon-him"],["לְטוֹב","for-good"],["וּלְרַע","and-to-evil"],["בֵּין","among"],["כָּל","all"],["הָעַמִּים.","the-peoples"],["׃",""]
  ]},
  { num: "לד", words: [
    ["אָמַר","said"],["שֶׁיֵּשׁ","that-there-are"],["סֵפֶר","the-book-of"],["טָמוּן,","hidden place"],["כָּתוּב","written"],["עַל","upon"],["לוּחוֹת","plates-of"],["זָהָב,","gold"],["הַמְסַפֵּר","the-tell"],["אֶת","[ACC]"],["תּוֹלְדוֹת","generations-of"],["יוֹשְׁבֵי","the-inhabitants-of"],["הַיַּבֶּשֶׁת","the-dry ground"],["הַזֹּאת","this"],["מִלְּפָנִים","from-before"],["וְאֶת","and-[ACC]"],["הַמָּקוֹר","the-the fountain of"],["שֶׁמִּמֶּנּוּ","that-from-it"],["בָּאוּ.","his-coming"],["גַּם","also"],["אָמַר","said"],["שֶׁמְּלֹא","that-the fullness of"],["הַבְּשׂוֹרָה","the-good-tidings"],["הַנִּצְחִית","the-everlasting(f)"],["בּוֹ,","in-Him"],["כַּאֲשֶׁר","as"],["נִמְסְרָה","delivered"],["מֵאֵת","from"],["הַמּוֹשִׁיעַ","the-Savior"],["לְיוֹשְׁבִים","to-the-inhabitants"],["הַקְּדוּמִים.","the-ancient times"],["׃",""]
  ]},
  { num: "לה", words: [
    ["גַּם","also"],["שֶׁיֵּשׁ","that-there-are"],["שְׁנֵי","two"],["אֲבָנִים","stones"],["בְּמִסְגְּרוֹת","in-rims-of"],["כֶּסֶף,","silver"],["וְהָאֲבָנִים","and-the-stones"],["הָאֵלֶּה","these"],["מְחֻבָּרוֹת","clamps"],["לְחֹשֶׁן,","to-a-breastplate"],["מְהַוּוֹת","what is?(pl)"],["אֵת","[ACC]"],["אֲשֶׁר","which"],["נִקְרָאִים","are-they-called"],["הָאוּרִים","the-Urim"],["וְהַתֻּמִּים,","and-the-Thummim"],["טְמוּנִים","are hidden"],["עִם","with"],["הַלּוּחוֹת;","the-plates"],["הָאֲבָנִים","the-stones"],["הָאֵלֶּה","these"],["הֵם","they"],["אֲשֶׁר","which"],["הִוּוּ","be"],["\"רוֹאִים\"","seeing"],["הַקְּדוּמִים,","the-ancient times"],["וֵאלֹהִים","and-God"],["הֵכִין","prepared"],["אוֹתָם","them"],["לְמַטְּרַת","to-the-purpose-of"],["תִּרְגּוּם","interpreting"],["הַסֵּפֶר.","the-scroll"],["׃",""]
  ]},
  { num: "לו", words: [
    ["אַחֲרֵי","after"],["סַפְּרוֹ","the-book-of-his"],["לִי","to-me"],["אֶת","[ACC]"],["הַדְּבָרִים","the-things"],["הָאֵלֶּה,","these"],["הֵחֵל","began"],["לְצַטֵּט","to-quote"],["אֶת","[ACC]"],["נְבוּאוֹת","prophecies"],["הַתּוֹרָה.","the-law"],["רִאשׁוֹנָה","first"],["צִטֵּט","he-quoted"],["חֵלֶק","part"],["מִפֶּרֶק","from-plunder"],["ג׳","3rd"],["לְמַלְאָכִי,","angels-of"],["וְצִטֵּט","and-he-quoted"],["גַּם","also"],["אֶת","[ACC]"],["הַפֶּרֶק","the-parting of ways"],["הָרְבִיעִי","the-fourth"],["אוֹ","or"],["הָאַחֲרוֹן","the-last"],["שֶׁל","of"],["אוֹתָהּ","her/it(f)"],["נְבוּאָה","prophecy"],["אַף","yea"],["כִּי","that"],["בְּשִׁנּוּי","in-variation"],["קָטָן","small"],["מֵאֵיךְ","from-how"],["שֶׁנִּקְרָא","that-one who is called"],["בַּתַּנַ״ךְ","in-the-Bible"],["שֶׁלָּנוּ.","ours"],["בִּמְקוֹם","at-the-place-of"],["לְצַטֵּט","to-quote"],["אֶת","[ACC]"],["הַפָּסוּק","the-verse"],["הָרִאשׁוֹן","the-first"],["כְּפִי","according-to"],["שֶׁנִּקְרָא","that-one who is called"],["בְּסִפְרֵינוּ,","in-our-records"],["צִטֵּט","he-quoted"],["אוֹתוֹ","him"],["כָּךְ:","so"],["׃",""]
  ]},
  { num: "לז", words: [
    ["\"כִּי","(that"],["הִנֵּה","behold"],["הַיּוֹם","the-day"],["בָּא,","came"],["בֹּעֵר","was burning"],["כַּתַּנּוּר,","like-the-a-furnace"],["וְכָל","and-all"],["זֵדִים","the-proud"],["וְכָל","and-all"],["עֹשֵׂי","doers-of"],["רִשְׁעָה","iniquity"],["יִבְעֲרוּ","they are stupid"],["כַּקַּשׁ;","as-the-stubble"],["כִּי","that"],["הַבָּאִים","to-the-come"],["אָמַר","said"],["יְהוָה","the-Lord"],["צְבָאוֹת,","of-Hosts"],["וְלֹא","and-not"],["יַשְׁאִיר","it will leave"],["לָהֶם","unto-them"],["שֹׁרֶשׁ","the-root-of"],["וְעָנָף.\"","and-branch"],["׃",""]
  ]},
  { num: "לח", words: [
    ["וְעוֹד","and-again"],["צִטֵּט","he-quoted"],["אֶת","[ACC]"],["הַפָּסוּק","the-verse"],["הַחֲמִישִׁי","the-fifth"],["כָּךְ:","so"],["\"הִנֵּה","them"],["אֲגַלֶּה","I-shall-reveal"],["לָכֶם","to-you"],["אֶת","[ACC]"],["הַכְּהֻנָּה","the-priesthood"],["בְּיַד","by-hand-of"],["אֵלִיָּהוּ","Elijah"],["הַנָּבִיא,","the-prophet"],["לִפְנֵי","before"],["בֹּא","come"],["יוֹם","day"],["יְהוָה","the-Lord"],["הַגָּדוֹל","the-great/high"],["וְהַנּוֹרָא.\"","Ohnor"],["׃",""]
  ]},
  { num: "לט", words: [
    ["גַּם","also"],["אֶת","[ACC]"],["הַפָּסוּק","the-verse"],["הַבָּא","that-comes"],["צִטֵּט","he-quoted"],["בְּשֹׁנֶה:","shame"],["\"וְהֵשִׁיב","Ohshib"],["אֶל","to/unto"],["לֵב","heart"],["הַבָּנִים","the-children"],["אֶת","[ACC]"],["הַהַבְטָחוֹת","the-promises"],["אֲשֶׁר","which"],["נֶאֶמְרוּ","spoken"],["לָאָבוֹת,","for-nursing-fathers"],["וְלֵב","and-heart"],["בָּנִים","children"],["יָשׁוּב","repent"],["אֶל","to/unto"],["אֲבוֹתָם.","ancestors-their"],["לוּלֵא","were-it-not-for"],["כֵן,","so/thus"],["הָיְתָה","was(f)"],["כָּל","all"],["הָאָרֶץ","the-land"],["נֶחֱרֶבֶת","desolate"],["כֻּלָּהּ","complete"],["בְּבוֹאוֹ.\"","when-came-he"],["׃",""]
  ]},
  { num: "מ", words: [
    ["נוֹסָף","more"],["עַל","upon"],["אֵלֶּה,","these"],["צִטֵּט","he-quoted"],["אֶת","[ACC]"],["פֶּרֶק","plunder"],["לִישַׁעְיָהוּ","to-Jeshaiah"],["וְאָמַר","and-says"],["שֶׁעוֹמֵד","that-are standing"],["לְהִתְמַלֵּא.","to-¿-will you fill"],["גַּם","also"],["צִטֵּט","he-quoted"],["אֶת","[ACC]"],["מַעֲשֵׂי","works-of"],["הַשְּׁלִיחִים","the-apostles"],["בְּדִיּוּק","precisely"],["כְּפִי","according-to"],["שֶׁהֵם","that-they"],["בַּבְּרִית","the-covenant"],["הַחֲדָשָׁה","the-new"],["שֶׁלָּנוּ.","ours"],["אָמַר","said"],["שֶׁאוֹתוֹ","that-it"],["נָבִיא","a-prophet"],["הָיָה","was"],["הַמָּשִׁיחַ,","the-Messiah"],["אֲבָל","but/however"],["הַיּוֹם","the-day"],["עוֹד","more"],["לֹא","not"],["בָּא","came"],["שֶׁאֵלֶּה","that-these"],["אֲשֶׁר","which"],["לֹא","not"],["יִשְׁמְעוּ","they-hearken"],["לְקוֹלוֹ","to-His-voice"],["יִכָּרְתוּ","they-shall-be-cut-off"],["מִקֶּרֶב","from-the-midst-of"],["הָעָם","the-people"],["אֲבָל","but/however"],["בְּקָרוֹב","soon"],["יָבוֹא.","shall-come"],["׃",""]
  ]},
  { num: "מא", words: [
    ["גַּם","also"],["צִטֵּט","he-quoted"],["אֶת","[ACC]"],["יוֹאֵל","Joel"],["ב׳","2nd"],["מִפָּסוּק","from-a-verse"],["כ״ח","strength"],["עַד","until"],["הַסּוֹף.","the-rushes"],["גַּם","also"],["אָמַר","said"],["שֶׁזֶּה","that-this"],["עוֹד","more"],["לֹא","not"],["הִתְמַלֵּא","¿-will you fill"],["אֲבָל","but/however"],["בְּקָרוֹב","soon"],["יִתְמַלֵּא,","it-shall-be-filled"],["וְאָמַר","and-says"],["עוֹד","more"],["שֶׁמְּלֹא","that-the fullness of"],["הַגּוֹיִם","the-nations"],["קָרוֹב","soon"],["לָבוֹא.","to-come"],["צִטֵּט","he-quoted"],["פְּסוּקִים","verses"],["רַבִּים","many"],["אֲחֵרִים","other"],["וְנָתַן","and-give"],["הֶסְבֵּרִים","the-Sibraim"],["רַבִּים","many"],["שֶׁאֵינֶנִּי","that-not-I"],["יָכוֹל","Almighty"],["לִזְכֹּר","to-remember"],["פֹּה.","the-mouth"],["׃",""]
  ]},
  { num: "מב", words: [
    ["עוֹד","more"],["אָמַר","said"],["לִי:","to-me"],["כַּאֲשֶׁר","as"],["אֶקַּח","I-take"],["אֶת","[ACC]"],["הַלּוּחוֹת","the-plates"],["שֶׁדִּבֶּר","that-he had said"],["עֲלֵיהֶם","upon-them"],["כִּי","that"],["הַזְּמַן","the-time"],["לְקַבְּלָם","obtain-them"],["עוֹד","more"],["לֹא","not"],["הִגִּיעַ","come-has"],["אַל","do-not"],["אַרְאֶה","I-will-show"],["אוֹתָם","them"],["לְאִישׁ,","for-a-man"],["וְלֹא","and-not"],["אֶת","[ACC]"],["הַחֹשֶׁן","the-breastplate"],["עִם","with"],["הָאוּרִים","the-Urim"],["וְהַתֻּמִּים,","and-the-Thummim"],["רַק","only"],["לְמִי","to-whom"],["שֶׁאֲצֻוֶּה","that-I will command"],["לְהַרְאוֹתָם;","to-show-them"],["אִם","if"],["אֶעֱשֶׂה,","will I do"],["אֶשָּׁמֵד.","I-shall-be-destroyed"],["בְּעוֹדוֹ","in-again-his"],["מְדַבֵּר","speaking"],["אִתִּי","with-me"],["עַל","upon"],["הַלּוּחוֹת,","the-plates"],["נִפְתְּחָה","we may open"],["הַמַּרְאָה","the-vision"],["לְדַעְתִּי","to-knowledge-my"],["עַד","until"],["שֶׁיָּכֹלְתִּי","that-have I been able"],["לִרְאוֹת","to-see"],["אֶת","[ACC]"],["הַמָּקוֹם","the-place"],["שֶׁהַלּוּחוֹת","that-the-blackboard(pl)"],["טְמוּנִים,","are hidden"],["וְכֹה","and-thus"],["בְּרוּר","in-emit a fluid"],["וּמְפֹרָשׁ","and-making clear"],["עַד","until"],["שֶׁהִכַּרְתִּי","that-I have cut off"],["אֶת","[ACC]"],["הַמָּקוֹם","the-place"],["שׁוּב","again"],["כַּאֲשֶׁר","as"],["בִּקַּרְתִּי","in-I have dug"],["בּוֹ.","in-Him"],["׃",""]
  ]},
  { num: "מג", words: [
    ["אַחֲרֵי","after"],["הַדִּבּוּר","the-speaking-with"],["הַזֶּה,","this"],["רָאִיתִי","I-saw"],["אֶת","[ACC]"],["הָאוֹר","the-light"],["בַּחֶדֶר","in-the-room"],["מַתְחִיל","from-the-it may be in anguish"],["לְהִתְאַסֵּף","to-gathered themselves"],["מִיָּד","immediately"],["סְבִיב","around"],["גּוּף","the-body-of"],["הַמְדַבֵּר","who-spoke"],["אֵלַי,","unto-me"],["וְהִמְשִׁיךְ","and-he-continued"],["כָּךְ","so"],["עַד","until"],["שֶׁהֶחָדֶר","that-the-chamber"],["נִשְׁאַר","remained"],["חָשׁוּךְ","dark"],["שׁוּב","again"],["חוּץ","except"],["מִסָּבִיב","round-about"],["לוֹ.","to-him"],["מִיָּד","immediately"],["רָאִיתִי","I-saw"],["כְּאִלּוּ","as-if"],["צִנּוֹר","water tunnel"],["נִפְתַּח","be-loosed"],["עַד","until"],["לַשָּׁמַיִם,","to the-heavens"],["וְהוּא","and-He"],["עָלָה","went-up"],["עַד","until"],["שֶׁנֶּעֱלָם","that-hidden"],["כֻּלּוֹ,","finished/ended"],["וְהֶחָדֶר","and-the-room"],["נִשְׁאַר","remained"],["כְּפִי","according-to"],["שֶׁהָיָה","who-was"],["לִפְנֵי","before"],["שֶׁהָאוֹר","that-the-light"],["הַשְּׁמֵימִי","the-heavenly"],["הַזֶּה","this"],["הוֹפִיעַ.","shine forth"],["׃",""]
  ]},
  { num: "מד", words: [
    ["שָׁכַבְתִּי","I lay with"],["וְהִרְהַרְתִּי","and-I-reflected"],["עַל","upon"],["מוּזָרוּת","strangeness"],["הַמַּחֲזֶה,","the-vision"],["מְאוֹד","very"],["עַל","upon"],["מָה","what"],["שֶׁסִּפֵּר","that-is the record of"],["לִי","to-me"],["הַשָּׁלִיחַ","the-send"],["הַמֻּפְלָא","the-an extraordinary thing"],["הַזֶּה,","this"],["וּבְתוֹךְ","and-within"],["פִּתְאֹם","suddenly"],["גִּלִּיתִי","I have made known"],["שֶׁחַדְרִי","that-the chambers of"],["מַתְחִיל","from-the-it may be in anguish"],["שׁוּב","again"],["לְהֵאִיר,","to-illuminate"],["וּבְרֶגַע","and-in-a moment"],["כִּמְעַט","nearly"],["אוֹתוֹ","him"],["שָׁלִיחַ","it was sent out"],["שְׁמֵימִי","heavenly"],["שׁוּב","again"],["עַל","upon"],["יַד","hand-of"],["מִשְׁכָּבִי.","bed-my"],["׃",""]
  ]},
  { num: "מה", words: [
    ["הֵחֵל","began"],["וְשׁוּב","and-again"],["סִפֵּר","he-had-related"],["אֶת","[ACC]"],["אוֹתָם","them"],["דְּבָרִים","things"],["מַמָּשׁ","actual"],["שֶׁסִּפֵּר","that-is the record of"],["בְּבִקּוּרוֹ","in-his-visit"],["הָרִאשׁוֹן,","the-first"],["בְּלִי","without"],["שִׁנּוּי","variation"],["כָּלְשֶׁהוּ.","whatsoever"],["אַחֲרֵי","after"],["עֲשׂוֹתוֹ","working"],["כֵן,","so/thus"],["סִפֵּר","he-had-related"],["לִי","to-me"],["עַל","upon"],["מִשְׁפָּטִים","judgments"],["גְּדוֹלִים","great"],["הַבָּאִים","to-the-come"],["עַל","upon"],["הָאָרֶץ,","the-land"],["עִם","with"],["שְׁמָמוֹת","desolate"],["גְּדוֹלוֹת","great"],["מֵרָעָב","from-hunger"],["וּמֵחֶרֶב","and-from-the-sword-of"],["וּמִדֶּבֶר,","and-from-the pestilence"],["הַכְּבֵדִים","the-grievous"],["הָאֵלֶּה","these"],["יָבֹאוּ","shall-come"],["עַל","upon"],["הָאָרֶץ","the-land"],["בַּדּוֹר","in-the-generation"],["הַזֶּה.","this"],["אַחֲרֵי","after"],["סַפְּרוֹ","the-book-of-his"],["אֶת","[ACC]"],["הַדְּבָרִים","the-things"],["הָאֵלֶּה,","these"],["שׁוּב","again"],["עָלָה","went-up"],["כְּפִי","according-to"],["שֶׁעָשָׂה","that-he had made"],["לְפָנִים.","to the-face"],["׃",""]
  ]},
  { num: "מו", words: [
    ["בָּעֵת","at-this-time"],["הַזֹּאת","this"],["כֹּה","thus"],["עֲמֻקִּים","deep"],["הָיוּ","were"],["בְּדַעְתִּי","in-my-knowing"],["עַד","until"],["שֶׁבָּרְחָה","that-he fled"],["הַשֵּׁנָה","the-year"],["מֵעֵינַי,","from-my-eyes"],["וְשָׁכַבְתִּי","and-I will lie down"],["מֵהַשְׁתָּאוּת","from-amazement"],["מֵאֲשֶׁר","than"],["רָאִיתִי","I-saw"],["וְשָׁמַעְתִּי","and-I-heard"],["גַּם","also"],["יַחַד.","oft"],["אֲבָל","but/however"],["מַה","what"],["הַפְתָּעָתִי","the-suddenly-my"],["כַּאֲשֶׁר","as"],["שׁוּב","again"],["רָאִיתִי","I-saw"],["אֶת","[ACC]"],["אוֹתוֹ","him"],["שָׁלִיחַ","it was sent out"],["עַל","upon"],["יַד","hand-of"],["מִשְׁכָּבִי,","bed-my"],["וְשָׁמַעְתִּי","and-I-heard"],["אוֹתוֹ","him"],["מְחַזֵּר","returned"],["עָלַי","I-must"],["שׁוּב","again"],["אֶת","[ACC]"],["אוֹתָם","them"],["דְּבָרִים","things"],["כְּלִפְנֵי","as-before"],["כֵן.","so/thus"],["וְהוֹסִיף","and-did-more/continued"],["לִי","to-me"],["שֶׁהַשָּׂטָן","that-the-adversary"],["יְנַסֶּה","would-try"],["לְפַתּוֹת","to-persuade"],["אוֹתִי,","me"],["בִּגְלַל","on-account of"],["נְסִיבוֹת","circumstances"],["הָעֹנִי","the-misery"],["שֶׁל","of"],["מִשְׁפַּחַת","family-of"],["אָבִי,","my-father"],["לָקַחַת","to-take"],["אֶת","[ACC]"],["הַלּוּחוֹת","the-plates"],["לְמַטְּרַת","to-the-purpose-of"],["הִתְעַשְּׁרוּת.","becoming rich"],["זֹאת","this"],["אָסַר","has-forbidden"],["עָלַי,","I-must"],["וְאָמַר","and-says"],["שֶׁאָסוּר","that-was imprisoned"],["לִי","to-me"],["לִהְיוֹת","to-be"],["לִי","to-me"],["מַטָּרָה","a target"],["אַחֶרֶת","other"],["בְּקַבָּלַת","in-received-of"],["הַלּוּחוֹת","the-plates"],["אֶלָּא","but-rather"],["לְפָאֵר","Lfr"],["אֶת","[ACC]"],["הָאֱלֹהִים,","God"],["וְאָסוּר","and-bound"],["לְהֻשְׁפַּע","to-to be influenced"],["מִמָּנִיעַ","from-motivation"],["אַחֵר","other"],["מִלְּבַנּוֹת","from-to-build"],["אֶת","[ACC]"],["מַלְכוּתוֹ","His-kingdom"],["אַחֶרֶת","other"],["לֹא","not"],["אוּכַל","am-able"],["לְקַבְּלָם.","obtain-them"],["׃",""]
  ]},
  { num: "מז", words: [
    ["אַחֲרֵי","after"],["הַבִּקּוּר","the-visit"],["הַשְּׁלִישִׁי","the-third"],["הַזֶּה,","this"],["שׁוּב","again"],["עָלָה","went-up"],["לַשָּׁמַיִם","to-the-heavens"],["כְּלִפְנֵי","as-before"],["כֵן,","so/thus"],["וְשׁוּב","and-again"],["נֶעֱזַבְתִּי","forsaken(I)"],["לְהַרְהֵר","to-to think about"],["עַל","upon"],["מוּזָרוּת","strangeness"],["אֲשֶׁר","which"],["זֶה","this"],["עַתָּה","now"],["חָוִיתִי.","I-had-experienced"],["כִּמְעַט","nearly"],["מִיָּד","immediately"],["אַחֲרֵי","after"],["עֲלוֹת","the-ascending-of"],["הַשָּׁלִיחַ","the-send"],["הַשְּׁמֵימִי","the-heavenly"],["מֵעָלַי","from-me"],["בַּפַּעַם","for-the-time"],["הַשְּׁלִישִׁית","the-third"],["קָרָא","called"],["הַתַּרְנְגוֹל,","the-cock"],["וְגִלִּיתִי","and-I will uncover"],["שֶׁהַיּוֹם","that-the-day"],["מִתְקָרֵב","from-you may offer"],["כָּךְ","so"],["שֶׁשִּׂיחוֹתֵינוּ","that-shrub of-our"],["מִלְּאוּ","they-filled"],["אֶת","[ACC]"],["כָּל","all"],["הַלַּיְלָה","the-night"],["הַהוּא.","is-He"],["׃",""]
  ]},
  { num: "מח", words: [
    ["זְמַן","time"],["קָצָר","short"],["אַחֲרֵי","after"],["כֵן","thus"],["קַמְתִּי","I arose"],["מִמִּשְׁכָּבִי","from-bed-my"],["וְכָרָגִיל","and-as-usual"],["הָלַכְתִּי","I-went"],["לַעֲבוֹדוֹת","to-serve(pl)"],["הַיּוֹם","the-day"],["אֲבָל","but/however"],["בְּנַסּוֹתִי","while-attempting"],["לַעֲבֹד","to-till"],["אֲחֵרִים,","other"],["מָצָאתִי","I-found"],["כֹּחִי","my-strength"],["כֹּה","thus"],["עַד","until"],["שֶׁלֹּא","that-there-should-be-no"],["יָכֹלְתִּי","I-could"],["כְּלָל.","general/altogether"],["אָבִי,","my-father"],["שֶׁעָבַד","that-he served"],["אִתִּי,","Ittai"],["גִּלָּה","had-discovered"],["שֶׁמַּשֶּׁהוּ","sun-her(they)"],["לֹא","not"],["כַּשּׁוּרָה","the-right"],["אִתִּי","with-me"],["וְאָמַר","and-says"],["לִי","to-me"],["לָלֶכֶת","to-go"],["הַבַּיְתָה.","the-house-towards"],["הִתְחַלְתִּי","I-began"],["לָלֶכֶת","to-go"],["בְּכַוָּנָה","with-the-intention"],["לָלֶכֶת","to-go"],["הַבַּיְתָה,","the-house-towards"],["אֲבָל","but/however"],["בְּנַסּוֹתִי","while-attempting"],["לַעֲבֹר","cross"],["אֶת","[ACC]"],["הַגָּדֵר","the-fence"],["מִן","from"],["הַשָּׂדֶה","the-field"],["שֶׁהָיִינוּ","that-we are"],["בּוֹ,","in-Him"],["עָזַב","left"],["אוֹתִי","me"],["כֹּחִי","my-strength"],["כֻּלּוֹ","entirely"],["וְנָפַלְתִּי","and-I fall"],["חֲסַר","helpless"],["אוֹנִים","helpless"],["לָאָרֶץ,","earth"],["וּלְרֶגַע","and-to-Rg"],["לֹא","not"],["הָיִיתִי","I-was"],["מוּדָע","a relative"],["לְכָל","to-all"],["דָּבָר.","thing"],["׃",""]
  ]},
  { num: "מט", words: [
    ["הַדָּבָר","the-thing"],["הָרִאשׁוֹן","the-first"],["שֶׁיָּכֹלְתִּי","that-have I been able"],["לִזְכֹּר","to-remember"],["הָיָה","was"],["קוֹל","the-voice-of"],["מְדַבֵּר","speaking"],["אֵלַי,","unto-me"],["קוֹרֵא","calling"],["בִשְׁמִי.","in-My-name"],["הִסְתַּכַּלְתִּי","I-looked"],["לְמַעְלָה","upward"],["וְרָאִיתִי","and-seen"],["אֶת","[ACC]"],["אוֹתוֹ","him"],["שָׁלִיחַ","it was sent out"],["עוֹמֵד","standing"],["מֵעַל","from-upon"],["רֹאשִׁי,","head-my"],["מֻקָּף","surrounded"],["אוֹר","a-light"],["כְּלִפְנֵי","as-before"],["כֵן.","so/thus"],["אָז","then"],["שׁוּב","again"],["סִפֵּר","he-had-related"],["לִי","to-me"],["אֵת","[ACC]"],["כָּל","all"],["אֲשֶׁר","which"],["סִפֵּר","he-had-related"],["לִי","to-me"],["בַּלַּיְלָה","in-the-night"],["הַקּוֹדֵם,","the-previous"],["וְצִוָּה","and-He-has-commanded"],["עָלַי","I-must"],["לָלֶכֶת","to-go"],["אֶל","to/unto"],["אָבִי","my-father"],["וּלְסַפֵּר","and-rehearse"],["לוֹ","to-him"],["אֶת","[ACC]"],["הַמַּרְאָה","the-vision"],["וְאֶת","and-[ACC]"],["הַמִּצְווֹת","the-commandments"],["׃",""]
  ]},
  { num: "נ", words: [
    ["צִיַּתְתִּי.","I-obeyed"],["חָזַרְתִּי","I-returned"],["אֶל","to/unto"],["אָבִי","my-father"],["בַּשָּׂדֶה","in-the-field"],["וְסִפַּרְתִּי","and-the-book-of-my"],["לוֹ","to-him"],["אֶת","[ACC]"],["כָּל","all"],["הָעִנְיָן.","the-task"],["עָנָה","he has testified"],["לִי","to-me"],["שֶׁזֶּה","that-this"],["מֵאֵת","from"],["הָאֱלֹהִים,","God"],["וְאָמַר","and-says"],["לִי","to-me"],["לָלֶכֶת","to-go"],["וְלַעֲשׂוֹת","and-do"],["כַּאֲשֶׁר","as"],["צִוָּה","commanded"],["הַשָּׁלִיחַ.","the-send"],["עָזַבְתִּי","I have abandoned"],["אֶת","[ACC]"],["הַשָּׂדֶה","the-field"],["וְהָלַכְתִּי","and-I will walk"],["אֶל","to/unto"],["הַמָּקוֹם","the-place"],["שֶׁאָמַר","that-I-say"],["לִי","to-me"],["הַשָּׁלִיחַ","the-send"],["שֶׁהַלּוּחוֹת","that-the-blackboard(pl)"],["טְמוּנִים,","are hidden"],["וּבִגְלַל","and-because-of"],["בְּהִירוּת","clarity"],["הַמַּרְאָה","the-vision"],["שֶׁהָיְתָה","that-was"],["לִי","to-me"],["עָלָיו,","upon-him"],["הִכַּרְתִּי","I-recognized"],["אֶת","[ACC]"],["הַמָּקוֹם","the-place"],["בְּרֶגַע","in-the-instant-of"],["בֹּאִי","came-I"],["לְשָׁם.","to-him-who-should-put"],["׃",""]
  ]},
  { num: "נא", words: [
    ["סָמוּךְ","near"],["לִכְפַר","to-the-village-of"],["מַנְצֶ׳סְטֶר,","Manchester"],["מְחוֹז","the harbor of"],["אוֹנְטָרְיוֹ,","Ontario"],["מְדִינַת","the province of"],["נְיוּ","New"],["יוֹרְק,","York"],["עוֹמֵד","standing"],["גִּבְעָה","a-hill"],["בְּגֹדֶל","in-the-greatness"],["נִכְבָּד,","glorious"],["הַגְּבוֹהָה","the-Gbohh"],["בְּיוֹתֵר","exceedingly"],["בַּסְּבִיבָה.","in-the-vicinity"],["בְּצִדָּהּ","in-side-its"],["הַמַּעֲרָבִי","the-west-my"],["שֶׁל","of"],["הַגִּבְעָה","the-hill"],["הַזֹּאת,","this"],["לֹא","not"],["רָחוֹק","far"],["מֵהַפִּסְגָּה,","from-the-Pisgah"],["תַּחַת","under"],["אֶבֶן","stone"],["בְּגֹדֶל","in-the-greatness"],["נִכְבָּד,","glorious"],["שָׁכְבוּ","they-lie"],["הַלּוּחוֹת","the-plates"],["טְמוּנִים","are hidden"],["בְּאַרְגַּז","in-box"],["אֶבֶן.","stone"],["הָאֶבֶן","the-stone"],["הַזֹּאת","this"],["הָיְתָה","was(f)"],["עָבָה","it is thick"],["בְּאֶמְצָעָהּ","in-the-middle-her"],["מִלְמַעְלָה,","from-to-the ascent of"],["וְדַקָּה","and-small"],["יוֹתֵר","more"],["כָּךְ","so"],["שֶׁחֶלְקָהּ","that-portion of land"],["הָאֶמְצָעִי","the-means"],["נִרְאָה","appeared"],["מֵעַל","from-upon"],["הָאֲדָמָה","the-ground"],["אֲבָל","but/however"],["שְׂפָתָהּ","edge-its"],["סָבִיב","round-about"],["הָיְתָה","was(f)"],["מְכֻסָּה","which-was-covered"],["בֶּעָפָר.","in the-dust"],["׃",""]
  ]},
  { num: "נב", words: [
    ["אַחֲרֵי","after"],["הֶעָפָר","the-dust"],["הִשַּׂגְתִּי","I-obtained"],["קָבַעְתִּי","Kv(I)"],["תַּחַת","under"],["שְׂפַת","the-language-of"],["הָאֶבֶן,","the-stone"],["וּבְמַאֲמָץ","and-with-effort"],["קָטָן","small"],["הֲרִימוֹתִי","raise"],["אוֹתָהּ.","her/it(f)"],["הִבַּטְתִּי","look(I)"],["פְּנִימָה","inside"],["וְשָׁם","and-there"],["אָכֵן","yea"],["רָאִיתִי","I-saw"],["אֶת","[ACC]"],["הַלּוּחוֹת,","the-plates"],["אֶת","[ACC]"],["הָאוּרִים","the-Urim"],["וְהַתֻּמִּים,","and-the-Thummim"],["וְאֶת","and-[ACC]"],["הַחֹשֶׁן","the-breastplate"],["כַּאֲשֶׁר","as"],["אָמַר","said"],["הַשָּׁלִיחַ.","the-send"],["הָאַרְגַּז","the-box"],["שֶׁשָּׁכְבוּ","that-they have lain down"],["בּוֹ","in-him/it"],["נַעֲשָׂה","was-done"],["מֵהַנָּחַת","from-the-he was in awe"],["אֲבָנִים","stones"],["יַחַד","oft"],["בְּמִין","in-kind"],["מֶלֶט.","mortar"],["בְּתַחְתִּית","at-the lower part of"],["הָאַרְגַּז","the-box"],["הוּנְחוּ","it has been given rest(they)"],["שְׁתֵּי","two"],["אֲבָנִים","stones"],["לְרֹחַב","to-the breadth of"],["הָאַרְגַּז,","the-box"],["וְעַל","and-upon"],["אֲבָנִים","stones"],["אֵלֶּה","these"],["שָׁכְבוּ","they-lie"],["הַלּוּחוֹת","the-plates"],["וּשְׁאָר","and-remnant"],["הַדְּבָרִים","the-things"],["עִמָּהֶם.","were with-them"],["׃",""]
  ]},
  { num: "נג", words: [
    ["נִסֵּיתִי","I have put to the test"],["לְהוֹצִיאָם","to-lead-them"],["אֲבָל","but/however"],["נֶאֱסַרְתִּי","forbidden-am(I)"],["עַל","upon"],["יְדֵי","hands-of"],["הַשָּׁלִיחַ,","the-send"],["וְשׁוּב","and-again"],["נֶאֱמַר","said"],["לִי","to-me"],["שֶׁהַזְּמַן","that-the-a time"],["לְהוֹצִיאָם","to-lead-them"],["עוֹד","more"],["לֹא","not"],["הִגִּיעַ","come-has"],["וְלֹא","and-not"],["יַגִּיעַ","shall-come"],["עַד","until"],["אַרְבַּע","four"],["שָׁנִים","years"],["מֵעַתָּה.","more than-now"],["אֲבָל","but/however"],["אָמַר","said"],["לִי","to-me"],["שֶׁעָלַי","handfuls of"],["לָבוֹא","to-come"],["אֶל","to/unto"],["הַמָּקוֹם","the-place"],["הַזֶּה","this"],["בְּדִיּוּק","precisely"],["בְּעוֹד","in-yet"],["שָׁנָה","years"],["מֵעַתָּה,","more than-now"],["וְהוּא","and-He"],["יִפְגֹּשׁ","he-will-come in"],["אוֹתִי","me"],["שָׁם,","there"],["וְשֶׁעָלַי","and-handfuls of"],["לְהַמְשִׁיךְ","to-continue"],["לַעֲשׂוֹת","to-do"],["כֵּן","so/thus"],["עַד","until"],["שֶׁיָּבוֹא","who-will come"],["הַזְּמַן","the-time"],["לְקַבֵּל","to-receive"],["אֶת","[ACC]"],["הַלּוּחוֹת.","the-plates"],["׃",""]
  ]},
  { num: "נד", words: [
    ["כַּאֲשֶׁר","as"],["צֻוֵּיתִי,","I-had-been-commanded"],["הָלַכְתִּי","I-went"],["בְּסוֹף","at-the end of"],["כָּל","all"],["שָׁנָה,","year"],["וּבְכָל","and-in-all"],["פַּעַם","once"],["מָצָאתִי","I-found"],["אֶת","[ACC]"],["אוֹתוֹ","him"],["שָׁלִיחַ","it was sent out"],["שָׁם,","there"],["וְקִבַּלְתִּי","and-received"],["הוֹרָאָה","instruction"],["וּמֵידָע","and-from-he taught"],["מִמֶּנּוּ","from-him"],["בְּכָל","with-all"],["אַחַת","one"],["מִפְּגִישׁוֹתֵינוּ","from-of-our-interviews"],["עַל","upon"],["מָה","what"],["שֶׁיְּהוָה","that-Yahweh"],["הוֹלֵךְ","going"],["לַעֲשׂוֹת","to-do"],["וְאֵיךְ","and-how"],["וּבְאֵיזֶה","and-in-which"],["אֹפֶן","manner"],["תִּתְנַהֵל","would-be-conducted"],["מַלְכוּתוֹ","His-kingdom"],["בְּאַחֲרִית","in-latter"],["הַיָּמִים.","the-days"],["׃",""]
  ]},
  { num: "נה", words: [
    ["מֵאַחַר","from-after"],["שֶׁנְּסִיבוֹת","that-circumstances"],["אָבִי","my-father"],["הָעוֹלָמִיּוֹת","the-my-eternity(pl)"],["הָיוּ","were"],["מֻגְבָּלוֹת","limited(pl)"],["מְאוֹד,","very"],["נֶאֱלַצְנוּ","we-were-forced"],["לַעֲבֹד","to-till"],["בְּיָדֵינוּ","with-our-hands"],["לְהִשְׂתַּכֵּר","to-to earn"],["בַּעֲבוֹדַת","in-work-of"],["יוֹם","day"],["וּבְאֹפֶן","and-in-manner"],["אַחֵר","other"],["כְּפִי","according-to"],["לְהַשִּׂיג","obtain"],["הִזְדַּמְּנוּת.","opportunity"],["לִפְעָמִים","to-times"],["הָיִינוּ","we-were"],["בַּבַּיִת","in-the-house"],["וְלִפְעָמִים","and-to-times"],["בַּחוּץ,","on the-outside"],["וּבַעֲבוֹדָה","and-in-their"],["הִצְלַחְנוּ","we-succeeded"],["לְהַשִּׂיג","obtain"],["פַּרְנָסָה","livelihood"],["נוֹחָה.","Nohah"],["׃",""]
  ]},
  { num: "נו", words: [
    ["בִּשְׁנַת","in-year-of"],["1823","1823"],["סָבְלָה","porterage"],["מִשְׁפַּחַת","family-of"],["אָבִי","my-father"],["צָרָה","affliction"],["גְּדוֹלָה","great"],["מִמּוֹת","from-death"],["אָחִי","my-brother"],["הַבְּכוֹר","the-firstborn"],["אַלְוִין.","Alvin"],["בְּאוֹקְטוֹבֶּר","in-October"],["1825","1825"],["נִשְׂכַּרְתִּי","I-was-hired"],["לְזָקֵן","to-the-ancient"],["בְּשֵׁם","in-name-of"],["גֹּ'וֹשִׁיָּה","Josiah"],["סְטוֹאָל","Stoal"],["שֶׁגָּר","the young of"],["בִּמְחוֹז","in-the-county-of"],["צֶ'נָנְגוֹ,","Chenango"],["מְדִינַת","the province of"],["נְיוּ","New"],["יוֹרְק.","York"],["הוּא","he/it"],["שָׁמַע","heard"],["מַשֶּׁהוּ","debt(they)"],["עַל","upon"],["מִכְרֵה","a pit of"],["כֶּסֶף","silver"],["שֶׁפָּתְחוּ","that-they have drawn"],["בְּהַרְמוֹנִי,","in-the-they deceived-me"],["מְחוֹז","the harbor of"],["סָסְקְוֶהָנָה,","Susquehanna"],["מְדִינַת","the province of"],["פֶּנְסִילְבֶנְיָה,","Pennsylvania"],["וְהָיָה","and-it-shall-come-to-pass"],["לִפְנֵי","before"],["שֶׁנִּשְׂכַּרְתִּי","that-I-was-hired"],["לוֹ","to-him"],["חוֹפֵר","digger"],["לְמַעַן","that"],["יַגְלֶה","He-shall-be-revealed"],["אִם","if"],["אֶפְשָׁר","that-you-could-have"],["אֶת","[ACC]"],["הַמִּכְרֶה.","the-a pit of"],["אַחֲרֵי","after"],["שֶׁהָלַכְתִּי","that-I went"],["לָגוּר","to-sojourn"],["אִתּוֹ,","with-him"],["לָקַח","took"],["אוֹתִי","me"],["עִם","with"],["שְׁאָר","the-remnant-of"],["פּוֹעֲלָיו","He-works-his"],["לַחְפֹּר","to-the-moles"],["אֶת","[ACC]"],["מִכְרֵה","a pit of"],["הַכֶּסֶף,","the-silver"],["וּבָזֶה","therefore"],["הִמְשַׁכְתִּי","I-continued"],["לַעֲבֹד","to-till"],["כִּמְעַט","nearly"],["חֹדֶשׁ","a month of"],["בְּלִי","without"],["הַצְלָחָה","success"],["בַּמַּאֲמָץ","in-the-is making firm"],["שֶׁלָּנוּ.","ours"],["לְבַסּוֹף","to-at-the end of"],["שִׁכְנַעְתִּי","I-convinced"],["אֶת","[ACC]"],["הַזָּקֵן","the-elder"],["לְהַפְסִיק","to-stop"],["לַחְפֹּר","to-the-moles"],["אַחֲרָיו.","after-him"],["מִכָּאן","from-here"],["נוֹצַר","it was formed"],["הַסִּפּוּר","the-account-of"],["הָרוֹוֵחַ","the-common"],["שֶׁהָיִיתִי","that-I was"],["\"חוֹפֵר","digger"],["כֶּסֶף.\"","silver"],["׃",""]
  ]},
  { num: "נז", words: [
    ["בִּזְמַן","in-time"],["שֶׁהָיִיתִי","that-I was"],["מוּעֲסָק","employed"],["כָּךְ","so"],["אֵצֶל","beside/near"],["אִישׁ","man/each"],["בְּשֵׁם","in-name-of"],["יִצְחָק","Isaac"],["הֵייל","Hale"],["מֵאוֹתוֹ","from-him"],["מָקוֹם.","the place of"],["שָׁם","there"],["רָאִיתִי","I-saw"],["לָרִאשׁוֹנָה","for-the-first-time"],["אֶת","[ACC]"],["אִשְׁתִּי,","wife-my"],["בִּתּוֹ","daughter-his"],["אֶמָּה","a-nation"],["הֵייל.","Hale"],["בְּיוֹם","in-day"],["הַשְּׁמוֹנָה","the-eight"],["עָשָׂר","[compound]"],["לְיָנוּאָר","of-January"],["1827","1827"],["נִשֵּׂאנוּ,","carried-us"],["בְּעוֹדִי","while-I-was"],["מוּעֲסָק","employed"],["בַּעֲבוֹדַת","in-work-of"],["מִסְטֶר","Mister"],["סְטוֹאָל.","Stoal"],["׃",""]
  ]},
  { num: "נח", words: [
    ["מֵאַחַר","from-after"],["שֶׁהִמְשַׁכְתִּי","that-I-continued"],["לְהַצְהִיר","to-declare"],["שֶׁרָאִיתִי","that-I have seen"],["מַרְאָה,","the sights of"],["הָרְדִיפָה","the-persecution"],["עוֹד","more"],["רָדְפָה","she will pursue"],["אוֹתִי,","me"],["וּמִשְׁפַּחַת","and-the clan of"],["אֲבִי","the-Father-of"],["אִשְׁתִּי","my-wife"],["הִתְנַגְּדָה","she-opposed"],["מְאוֹד","very"],["לָכֵן","therefore"],["נֶאֱלַצְתִּי","I-was-forced"],["לָקַחַת","to-take"],["אוֹתָהּ","her/it(f)"],["לְמָקוֹם","to-place"],["אַחֵר,","he delayed"],["וְכָךְ","and-thus"],["הָלַכְנוּ","we-went"],["וְנִשֵּׂאנוּ","and-carried-us"],["בְּבֵית","in-house-of"],["שׁוֹפֵט","chief-judge"],["טַרְבִּיל","Tarbill"],["בְּסָאוּת","in-South"],["בֵּיינְבְּרִידְג',","Bainbridge"],["מְחוֹז","the harbor of"],["צֶ'נָנְגוֹ,","Chenango"],["מְדִינַת","the province of"],["נְיוּ","New"],["יוֹרְק.","York"],["מִיָּד","immediately"],["אַחֲרֵי","after"],["נִשּׂוּאַי","predicative"],["עָזַבְתִּי","I have abandoned"],["אֶת","[ACC]"],["מִסְטֶר","Mister"],["סְטוֹאָל","Stoal"],["וְהָלַכְתִּי","and-I will walk"],["אֶל","to/unto"],["אָבִי","my-father"],["וְעָבַדְתִּי","and-I will serve"],["אִתּוֹ","with-him"],["בַּשָּׂדֶה","in-the-field"],["בָּעוֹנָה","in-the-cohabitation"],["הַהִיא.","that"],["׃",""]
  ]},
  { num: "נט", words: [
    ["לְבַסּוֹף","to-at-the end of"],["הִגִּיעַ","come-has"],["הַזְּמַן","the-time"],["לְקַבֵּל","to-receive"],["אֶת","[ACC]"],["הַלּוּחוֹת,","the-plates"],["אֶת","[ACC]"],["הָאוּרִים","the-Urim"],["וְהַתֻּמִּים,","and-the-Thummim"],["וְאֶת","and-[ACC]"],["הַחֹשֶׁן.","the-breastpiece"],["בְּיוֹם","in-day"],["הָעֶשְׂרִים","the-twenty"],["וּשְׁנַיִם","and-second"],["לְסֶפְּטֶמְבֶּר","of-September"],["1827,","1827"],["אַחֲרֵי","after"],["שֶׁהָלַכְתִּי","that-I went"],["כָּרָגִיל","as-usual"],["בְּסוֹף","at-the end of"],["שָׁנָה","years"],["נוֹסֶפֶת","additional"],["אֶל","to/unto"],["הַמָּקוֹם","the-place"],["שֶׁהֵם","that-they"],["טְמוּנִים,","are hidden"],["אוֹתוֹ","him"],["שָׁלִיחַ","it was sent out"],["שְׁמֵימִי","heavenly"],["מָסַר","delivered"],["אוֹתָם","them"],["לִי","to-me"],["עִם","with"],["הַמִּצְוָה","the-commandment"],["הַזֹּאת:","this"],["שֶׁאֶהְיֶה","that-I will be"],["אַחֲרַאי","responsible"],["עֲלֵיהֶם;","upon-them"],["שֶׁאִם","that-if"],["אֲשַׁלֵּחַ","I will let go"],["אוֹתָם","them"],["בְּרַשְׁלָנוּת","in-negligence"],["אוֹ","or"],["מִזְּנִיחָה","from-abandonment"],["שֶׁלִּי","which-belongs to-me"],["אֶכָּרֵת;","I-should-hew-down"],["אֲבָל","but/however"],["אִם","if"],["בְּכָל","with-all"],["מַאֲמַצַּי","the efforts of"],["לִשְׁמֹר","to-keep"],["עֲלֵיהֶם","upon-them"],["עַד","until"],["שֶׁהוּא,","that-He-is"],["הַשָּׁלִיחַ,","the-send"],["יִקְרָא","calls"],["לָהֶם","unto-them"],["יִהְיוּ","shall-be"],["׃",""]
  ]},
  { num: "ס", words: [
    ["מְהֵרָה","soon"],["גִּלִּיתִי","I have made known"],["לָמָּה","why"],["קִבַּלְתִּי","I-received"],["הוֹרָאוֹת","instruction"],["קְפֵדָנִיּוֹת","meticulous(pl)"],["כֹּה","thus"],["לִשְׁמֹר","to-keep"],["עֲלֵיהֶם","upon-them"],["וְלָמָּה","and-why"],["הַשָּׁלִיחַ","the-send"],["אָמַר","said"],["שֶׁכַּאֲשֶׁר","that-just-as"],["אֶעֱשֶׂה","I-do"],["אֵת","[ACC]"],["מָה","what"],["שֶׁנִּדְרַשׁ","that-is being required"],["מִמֶּנִּי","from-me"],["הוּא","he/it"],["יִקְרָא","calls"],["לָהֶם.","unto-them"],["כִּי","that"],["בְּרֶגַע","in-the-instant-of"],["שֶׁנּוֹדַע","that-it was known"],["שֶׁיֵּשׁ","that-there-are"],["לִי","to-me"],["אוֹתָם,","them"],["נַעֲשׂוּ","were-done"],["הַמַּאֲמַצִּים","the-efforts"],["הַחֲזָקִים","the-strong"],["בְּיוֹתֵר","exceedingly"],["לָקַחַת","to-take"],["אוֹתָם","them"],["מִמֶּנִּי.","from-me"],["כָּל","all"],["עָרְמָה","craftiness"],["שֶׁיָּכְלָה","that-he will withhold"],["לְהִמָּצֵא","to-actually"],["נֶעֶשְׂתָה","it was done"],["לְמַטָּרָה","to-a target"],["זוֹ.","Ziv"],["הָרְדִיפָה","the-persecution"],["נַעֲשְׂתָה","became"],["מָרָה","bitter"],["וְקָשָׁה","and-hard"],["יוֹתֵר","more"],["מִלְּפָנִים,","from-before"],["וְהָמוֹנִים","and-multitudes"],["הָיוּ","were"],["עֵרִים","cities"],["תָּמִיד","continually"],["לָקַחַת","to-take"],["אוֹתָם","them"],["מִמֶּנִּי","from-me"],["אִם","if"],["אֶפְשָׁר.","that-you-could-have"],["אֲבָל","but/however"],["בְּחָכְמַת","by-the-wisdom-of"],["הָאֱלֹהִים","God"],["נִשְׁאֲרוּ","remained"],["בְּטוּחִים","Btoch(pl)"],["בְּיָדַי","with-my-own-hands"],["עַד","until"],["בָּהֶם","in-them"],["אֵת","[ACC]"],["אֲשֶׁר","which"],["נִדְרַשׁ","was-required"],["מִמֶּנִּי.","from-me"],["כַּאֲשֶׁר,","as/when"],["לְפִי","according-to"],["קָרָא","called"],["לָהֶם","unto-them"],["הַשָּׁלִיחַ,","the-send"],["מָסַרְתִּי","I-did-deliver"],["אוֹתָם","them"],["לוֹ,","to-him"],["וְהֵם","and-they"],["בִּרְשׁוּתוֹ","in-authority-his"],["עַד","until"],["הַיּוֹם","the-day"],["הַזֶּה","this"],["שֶׁהוּא","that-He-is"],["הַיּוֹם","the-day"],["הַשֵּׁנִי","the-second"],["לְמַאי","to-from-where"],["1838.","1838"],["׃",""]
  ]},
  { num: "סא", words: [
    ["אוּלָם","nevertheless"],["הַהִתְרַגְּשׁוּת","the-excitement"],["עוֹד","more"],["וְהַשְּׁמוּעָה","and-the-report"],["בְּאֶלֶף","worth-a-thousand"],["לְשׁוֹנוֹתֶיהָ","tongues-her"],["הָיְתָה","was(f)"],["מוּעֲסֶקֶת","employed(f)"],["כָּל","all"],["הַזְּמַן","the-time"],["שְׁקָרִים","lies"],["עַל","upon"],["מִשְׁפַּחַת","family-of"],["אָבִי","my-father"],["וְעָלַי.","and-leaves of"],["לוּ","if"],["סִפַּרְתִּי","the-book-of-my"],["חֵלֶק","part"],["אֶחָד","one"],["מֵאֶלֶף","from-a-thousand"],["מֵהֶם","from-them"],["הָיָה","was"],["מְמַלֵּא","was overflowing"],["כְּרָכִים.","as-young"],["הָרְדִיפָה","the-persecution"],["נַעֲשְׂתָה","became"],["בִּלְתִּי","except"],["נִסְבֶּלֶת","we-will-Sibboleth"],["עַד","until"],["שֶׁנֶּאֱלַצְתִּי","that-I-was-forced"],["לַעֲזֹב","to-leave"],["אֶת","[ACC]"],["מַנְצֶ'סְטֶר","Manchester"],["וְלָלֶכֶת","and-to-walk"],["עִם","with"],["אִשְׁתִּי","my-wife"],["לִמְחוֹז","to-the harbor of"],["סָסְקְוֶהָנָה,","Susquehanna"],["מְדִינַת","the province of"],["פֶּנְסִילְבֶנְיָה.","Pennsylvania"],["בְּהִתְכּוֹנְנוּתֵנוּ","in-preparing oneself-our"],["לָצֵאת,","to-go forth"],["וּבִהְיוֹתֵנוּ","and-when-were-we"],["עֲנִיִּים","the-poor"],["מְאוֹד,","very"],["וְהָרְדִיפָה","and-the-persecution"],["כֹּה","thus"],["כְּבֵדָה","became-exceedingly-sore"],["עָלֵינוּ","upon-us"],["עַד","until"],["שֶׁלֹּא","that-there-should-be-no"],["הָיָה","was"],["סִכּוּי","chance"],["שֶׁנִּהְיֶה","that-we were"],["אַחֶרֶת","other"],["בְּתוֹךְ","in-midst-of"],["צָרוֹתֵינוּ","our-afflictions"],["מָצָאנוּ","we-have-found"],["יָדִיד","the beloved one of"],["בְּאִישׁ","by-another"],["בְּשֵׁם","in-name-of"],["מַרְטִין","Martin"],["הָרִיס,","the-a-stade"],["שֶׁבָּא","that which-came"],["אֵלֵינוּ","unto-us"],["וְנָתַן","and-give"],["לִי","to-me"],["חֲמִשִּׁים","fifty"],["דּוֹלָר","dollar"],["לְעָזְרֵנוּ","to-the-help-of-our/-us"],["בְּדַרְכֵּנוּ.","in-journey-our"],["מִסְטֶר","Mister"],["הָרִיס","the-a-stade"],["הָיָה","was"],["תּוֹשַׁב","a resident alien of"],["עִירִיַּת","chives"],["פַּלְמִירָה,","Palmyra"],["מְחוֹז","the harbor of"],["וֵיין,","Oiin"],["מְדִינַת","the province of"],["נְיוּ","New"],["יוֹרְק,","York"],["וְאִכָּר","and-a farmer"],["מְכֻבָּד.","honoring"],["׃",""]
  ]},
  { num: "סב", words: [
    ["בְּעֶזְרָה","in-help"],["זוֹ","this"],["בָּעִתָּהּ","in-the-is-her-time"],["יָכֹלְתִּי","I-could"],["לְהַגִּיעַ","to-reach"],["לִמְקוֹם","for-place-of"],["יַעֲדִי","he warned-my"],["בְּפֶנְסִילְבֶנְיָה,","in-Pennsylvania"],["וּמִיָּד","and-immediately"],["אַחֲרֵי","after"],["הַגִּיעִי","the-come-has-my"],["לְשָׁם","to-there"],["הִתְחַלְתִּי","I-began"],["לְהַעְתִּיק","to-move"],["אֶת","[ACC]"],["הָאוֹתִיּוֹת","the-¿-me(pl)"],["מִן","from"],["הַלּוּחוֹת.","the-plates"],["הֶעְתַּקְתִּי","the-arrogance(I)"],["מִסְפָּר","number"],["נִכְבָּד","was-glorious"],["מֵהֶם,","from-them"],["וּבְאֶמְצָעוּת","and-by means of"],["הָאוּרִים","the-Urim"],["וְהַתֻּמִּים","and-the-Thummim"],["תִּרְגַּמְתִּי","I-translated"],["חֵלֶק","part"],["מֵהֶם,","from-them"],["אֲשֶׁר","which"],["עָשִׂיתִי","I-made"],["בֵּין","among"],["זְמַן","time"],["הַגִּיעִי","the-come-has-my"],["לְבֵית","to-house-of"],["אֲבִי","the-Father-of"],["אִשְׁתִּי","my-wife"],["בְּדֶצֶמְבֶּר","in-December"],["וּבֵין","and-between"],["פֶבְרוּאָר","February"],["׃",""]
  ]},
  { num: "סג", words: [
    ["מִתִּישֶׁהוּ","whenever"],["בְּפֶבְרוּאָר","in-February"],["הַזֶּה","this"],["בָּא","came"],["מִסְטֶר","Mister"],["מַרְטִין","Martin"],["הָרִיס","the-a-stade"],["הַנִּזְכָּר","the-said"],["לָקַח","took"],["אֶת","[ACC]"],["הָאוֹתִיּוֹת","the-¿-me(pl)"],["מִן","from"],["הַלּוּחוֹת,","the-plates"],["וְיָצָא","and-shall-come-forth"],["אִתָּם","with-them"],["לְעִיר","to-city"],["נְיוּ","New"],["יוֹרְק.","York"],["לְמָה","why?"],["שֶׁקָּרָה","has-lied"],["לוֹ","to-him"],["אֲפַנֶּה","I may turn"],["לְסִפּוּרוֹ","for-a-record-his"],["שֶׁלּוֹ","Shiloh"],["אֶת","[ACC]"],["הַנְּסִיבוֹת","the-circumstances"],["כַּאֲשֶׁר","as"],["סִפֵּר","he-had-related"],["לִי","to-me"],["אַחֲרֵי","after"],["שׁוּבוֹ,","turn back"],["וְזֶה","and-this"],["כָּךְ:","so"],["׃",""]
  ]},
  { num: "סד", words: [
    ["\"הָלַכְתִּי","I have gone about"],["לְעִיר","to-city"],["נְיוּ","New"],["יוֹרְק","York"],["וְהִצַּגְתִּי","and-to place(I)"],["אֶת","[ACC]"],["הָאוֹתִיּוֹת","the-¿-me(pl)"],["עִם","with"],["לַפְּרוֹפֶסוֹר","to-the-professor"],["צַ'רְלְס","Charles"],["אַנְתּוֹן,","you"],["אִישׁ","man/each"],["מְפֹאָר","magnificent"],["בְּהֶשֵּׂגָיו","in-was-overtaken-his"],["פְּרוֹפֶסוֹר","professor"],["אַנְתּוֹן","you"],["אָמַר","said"],["שֶׁהַתִּרְגּוּם","that-the-translation"],["נָכוֹן","expedient"],["יוֹתֵר","more"],["מִכָּל","above-all"],["מָה","what"],["שֶׁרָאָה","is dwelling"],["מִלְּפָנִים","from-before"],["מְתֻרְגָּם","was translated"],["מִן","from"],["הַמִּצְרִית.","the-Egyptian"],["אָז","then"],["הֶרְאֵיתִי","I-showed"],["לוֹ","to-him"],["אֵלֶּה","these"],["שֶׁעוֹד","that-again"],["לֹא","not"],["תֻּרְגְּמוּ,","translating"],["וְאָמַר","and-says"],["שֶׁהֵם","that-they"],["מִצְרִית","Egyptian"],["וְכַשְׂדִּית","and-Chaldee"],["וְאַשּׁוּרִית","and-Assyrian (language)"],["וְאָמַר","and-says"],["שֶׁהֵם","that-they"],["אוֹתִיּוֹת","me(pl)"],["אֲמִתִּיּוֹת.","truthful"],["נָתַן","gave"],["לִי","to-me"],["תְּעוּדָה","a-certificate"],["הַמְאַשֶּׁרֶת","the-from-I-might-serve"],["לַאֲנָשִׁים","as-men"],["בְּפַלְמִירָה","in-Palmyra"],["שֶׁהֵם","that-they"],["אוֹתִיּוֹת","me(pl)"],["אֲמִתִּיּוֹת","truthful"],["אֵלֶּה","these"],["גַּם","also"],["הוּא","he/it"],["נָכוֹן.","expedient"],["לָקַחְתִּי","I-have-taken"],["אֶת","[ACC]"],["הַתְּעוּדָה","was the-attestation"],["וְשַׂמְתִּי","and-I-make"],["אוֹתָהּ","her/it(f)"],["וְהָיִיתִי","and-I-was"],["רַק","only"],["עוֹזֵב","one who neglects"],["אֶת","[ACC]"],["הַבַּיִת","the-house"],["כַּאֲשֶׁר","as"],["מִסְטֶר","Mister"],["אַנְתּוֹן","you"],["קָרָא","called"],["לִי","to-me"],["בַחֲזָרָה","on the way back"],["וְשָׁאַל","and-he will enquire"],["אֵיךְ","how"],["גִּלָּה","had-discovered"],["הַנַּעַר","the-child"],["שֶׁיֵּשׁ","that-there-are"],["לוּחוֹת","plates-of"],["זָהָב","gold"],["בַּמָּקוֹם","in-the-place"],["שֶׁמָּצָא","that-he found"],["אוֹתָם.","them"],["עָנִיתִי","I am afflicted"],["שֶׁמַּלְאַךְ","that-the angel of"],["אֱלֹהִים","God"],["גִּלָּה","had-discovered"],["לוֹ.","to-him"],["׃",""]
  ]},
  { num: "סה", words: [
    ["\"אָז","then"],["אָמַר","said"],["לִי:","to-me"],["'תֵּן","give"],["לִי","to-me"],["לִרְאוֹת","to-see"],["אֶת","[ACC]"],["הַתְּעוּדָה.'","was the-attestation"],["לָכֵן","therefore"],["הוֹצֵאתִי","I-have-led"],["אוֹתָהּ","her/it(f)"],["מִכִּיסִי","from-a bag-my"],["וְנָתַתִּי","and-I-will-give"],["לוֹ.","to-him"],["הוּא","he/it"],["לָקַח","took"],["אוֹתָהּ","her/it(f)"],["וְקָרַע","and-he will tear"],["אוֹתָהּ","her/it(f)"],["וְאָמַר","and-says"],["שֶׁאֵין","whom-not"],["דָּבָר","things"],["כָּזֶה","such"],["עַכְשָׁו","now"],["כְּשֵׁרוּת","as-freedom"],["מַלְאָכִים,","messengers"],["אָבִיא","I-will-bring"],["לוֹ","to-him"],["אֶת","[ACC]"],["הַלּוּחוֹת","the-plates"],["הוּא","he/it"],["יְתַרְגֵּם","he-will-translate"],["אוֹתָם.","them"],["הוֹדַעְתִּי","I-made-known"],["לוֹ","to-him"],["שֶׁחֵלֶק","that-does a share"],["מִן","from"],["הַלּוּחוֹת","the-plates"],["חָתוּם","which-is-sealed"],["לִי","to-me"],["לְהָבִיא","to-bring"],["אוֹתָם.","them"],["עָנָה:","was replying"],["'לֹא","not"],["אוּכַל","am-able"],["לִקְרֹא","to-read"],["סֵפֶר","the-book-of"],["חָתוּם.'","they will seal it"],["עָזַבְתִּי","I have abandoned"],["אוֹתוֹ","him"],["וְהָלַכְתִּי","and-I will walk"],["לַדּוֹקְטוֹר","to-the-Dr"],["אֲשֶׁר","which"],["אִשֵּׁר","happiness"],["אֵת","[ACC]"],["אֲשֶׁר","which"],["אָמַר","said"],["פְּרוֹפֶסוֹר","professor"],["אַנְתּוֹן","you"],["עַל","upon"],["הָאוֹתִיּוֹת","the-¿-me(pl)"],["וְעַל","and-upon"],["הַתִּרְגּוּם","the-translation"],["גַּם","also"],["יַחַד.\"","oft"],["׃",""]
  ]},
  { num: "סו", words: [
    ["בְּיוֹם","in-day"],["הַחֲמִישִׁי","the-fifth"],["לְאַפְּרִיל","of-April"],["1829","1829"],["בָּא","came"],["אוֹלִיבֶר","Oliver"],["קָאוּדֶרִי","Cowdery"],["לְבֵיתִי.","for-own household-my"],["עַד","until"],["אָז","then"],["לֹא","not"],["רְאִיתִיו","I-saw-him"],["מֵעוֹלָם.","from-everlasting"],["אָמַר","said"],["לִי","to-me"],["שֶׁבְּלַמְּדוֹ","that-in-learn"],["בְּבֵית","in-house-of"],["סֵפֶר","the-book-of"],["בַּשְּׁכוּנָה","in-the-neighborhood"],["שֶׁגָּר","the young of"],["אָבִי,","my-father"],["וְאָבִי","and-my-father"],["הָיָה","was"],["אֶחָד","one"],["הַיְּלָדִים","the-born"],["לַבֵּית","to-the-house-of"],["סֵפֶר,","he-had-related"],["הָלַךְ","went"],["לְהִתְאַכְסֵן","to-to be housed"],["בְּבֵיתוֹ","in-his-house"],["לִתְקוּפָה,","to-course"],["וּבִהְיוֹתוֹ","and-in-his-being"],["שָׁם","there"],["סִפְּרָה","she will count"],["לוֹ","to-him"],["הַמִּשְׁפָּחָה","the-clan"],["אֶת","[ACC]"],["נְסִיבוֹת","circumstances"],["קַבָּלָתִי","I-received"],["אֶת","[ACC]"],["הַלּוּחוֹת,","the-plates"],["וּלְפִיכָךְ","and-therefore"],["בָּא","came"],["לְבָרֵר","to-purge them"],["אֶצְלִי.","was beside-me"],["׃",""]
  ]},
  { num: "סז", words: [
    ["יוֹמַיִם","two-days"],["אַחֲרֵי","after"],["בֹּא","come"],["מִסְטֶר","Mister"],["קָאוּדֶרִי,","Cowdery"],["בְּיוֹם","in-day"],["הַשְּׁבִיעִי","the-seventh"],["לְאַפְּרִיל,","of-April"],["הִתְחַלְתִּי","I-began"],["לְתַרְגֵּם","translate"],["אֶת","[ACC]"],["סֵפֶר","the-book-of"],["מוֹרְמוֹן,","Mormon"],["וְהוּא","and-He"],["הֵחֵל","began"],["לִכְתֹּב","to-write"],["בִּשְׁבִילִי.","in-paths of"],["׃",""]
  ]},
  { num: "סח", words: [
    ["עוֹד","more"],["הִמְשַׁכְנוּ","we-delayed"],["בִּמְלֶאכֶת","with-fine-work-of"],["הַתִּרְגּוּם,","the-translation"],["וּבַחֹדֶשׁ","and-in the-month"],["הַבָּא,","has-come?"],["מַאי","from-where"],["1829,","1829"],["הָלַכְנוּ","we-went"],["יוֹם","day"],["אֶחָד","one"],["לַיַּעַר","the-shall-be-esteemed-as-a-forest"],["לְהִתְפַּלֵּל","to-pray"],["וְלִשְׁאֹל","and-to-Sheol"],["מֵאֵת","from"],["יְהוָה","the-Lord"],["עַל","upon"],["טְבִילָה","baptism"],["לִסְלִיחַת","for-a-remission-of"],["חֲטָאִים,","sinners"],["אֲשֶׁר","which"],["מָצָאנוּ","we-have-found"],["מֻזְכֶּרֶת","which brings to remembrance"],["בְּתִרְגּוּם","in-the-translation"],["הַלּוּחוֹת.","the-plates"],["בְּעוֹדֵנוּ","while-we-are"],["מִתְפַּלְּלִים","those who pray"],["וְקוֹרְאִים","and-calling"],["אֶל","to/unto"],["יְהוָה,","the-Lord"],["יָרַד","came-down"],["שָׁלִיחַ","it was sent out"],["מִן","from"],["הַשָּׁמַיִם","the-heavens"],["בַּעֲנַן","in-the-cloud"],["אוֹר,","a-light"],["וּבְשׂוּמוֹ","and-He-having-set"],["יָדָיו","His-hands"],["עָלֵינוּ","upon-us"],["סָמַךְ","I-ordain"],["אוֹתָנוּ","us"],["וְאָמַר:","and-Emer"],["׃",""]
  ]},
  { num: "סט", words: [
    ["\"עֲלֵיכֶם,","upon-you"],["עַבְדַי","which work"],["חֲבֵרַי,","my-companions"],["בְּשֵׁם","in-name-of"],["הַמָּשִׁיחַ,","the-Messiah"],["אֲנִי","I"],["מַעֲנִיק","bestowing"],["אֶת","[ACC]"],["כְּהֻנַּת","priesthood of"],["אַהֲרֹן,","Aaron"],["הַמַּחֲזִיקָה","the-he-who-endures"],["אֶת","[ACC]"],["מַפְתְּחוֹת","keys-of"],["שֵׁרוּת","freedom"],["הַמַּלְאָכִים","the-angels"],["וּבְשׂוֹרַת","and-good-tidings-of"],["הַתְּשׁוּבָה","the-repentance"],["וּטְבִילָה","and-baptism"],["בִּטְבִילָה","in-baptism"],["לִסְלִיחַת","for-a-remission-of"],["חֲטָאִים;","sinners"],["וְזֹאת","and-this"],["לֹא","not"],["תִלָּקַח","she was taken"],["עוֹד","more"],["מִן","from"],["הָאָרֶץ","the-land"],["עַד","until"],["שֶׁבְּנֵי","that-in-me"],["לֵוִי","Levi"],["יַקְרִיבוּ","they-lay"],["שׁוּב","again"],["קָרְבָּן","victim/sacrifice"],["לַיהוָה","unto-the-Lord"],["בִּצְדָקָה.\"","in-righteousness"],["׃",""]
  ]},
  { num: "ע", words: [
    ["אָמַר","said"],["שֶׁכְּהֻנַּת","that-priesthood of"],["אַהֲרֹן","Aaron"],["הַזֹּאת","this"],["אֵין","there-is-no"],["לָהּ","it"],["כֹּחַ","power"],["סְמִיכַת","ordination-of"],["יָדַיִם","both hands"],["לְמַתַּן","to-gift"],["רוּחַ","spirit"],["הַקֹּדֶשׁ,","the-Holy"],["אֲבָל","but/however"],["זֹאת","this"],["תִּנָּתֵן","it will be given"],["לָנוּ","unto-us"],["אַחַר","after"],["כָּךְ;","so"],["וְצִוָּה","and-He-has-commanded"],["עָלֵינוּ","upon-us"],["לָלֶכֶת","to-go"],["וּלְהִטָּבֵל,","and-to-be-baptized"],["וְנָתַן","and-give"],["לָנוּ","unto-us"],["הוֹרָאוֹת","instruction"],["שֶׁאֲנִי","that-I"],["אַטְבִּיל","Tvil"],["אֶת","[ACC]"],["אוֹלִיבֶר","Oliver"],["קָאוּדֶרִי,","Cowdery"],["וְאַחֲרֵי","and-after"],["כֵן","thus"],["הוּא","he/it"],["אוֹתִי.","me"],["׃",""]
  ]},
  { num: "עא", words: [
    ["בְּהֶתְאֵם","in-accordance"],["הָלַכְנוּ","we-went"],["הִטְבַּלְתִּי","be-baptized(I)"],["אוֹתוֹ","him"],["רִאשׁוֹנָה","first"],["וְאַחַר","and-then"],["כָּךְ","so"],["הוּא","he/it"],["הִטְבִּיל","he-did-baptize"],["אוֹתִי.","me"],["אַחַר","after"],["כָּךְ","so"],["שַׂמְתִּי","have-I-set"],["יָדַי","My-hands"],["עַל","upon"],["רֹאשׁוֹ","his-head"],["וּסְמַכְתִּיו","and-I have sustained-him"],["לִכְהֻנַּת","to-the-priesthood-of"],["אַהֲרֹן,","Aaron"],["וְאַחַר","and-then"],["כָּךְ","so"],["הוּא","he/it"],["שָׂם","set"],["יָדָיו","His-hands"],["עָלַי","I-must"],["וּסְמָכַנִי","and-sustain-me"],["לְאוֹתָהּ","to-her/it(f)"],["כְּהֻנָּה","priesthood"],["כִּי","that"],["כָּךְ","so"],["צֻוֵּינוּ.***","Tsoino"],["׃",""]
  ]},
  { num: "עב", words: [
    ["הַשָּׁלִיחַ","the-send"],["שֶׁבִּקֵּר","that-morning"],["אוֹתָנוּ","us"],["בְּהִזְדַּמְּנוּת","in-opportunity"],["זוֹ","this"],["וְהֶעֱנִיק","and-certainly"],["עָלֵינוּ","upon-us"],["אֶת","[ACC]"],["הַכְּהֻנָּה","the-priesthood"],["הַזֹּאת","this"],["אָמַר","said"],["שֶׁשְּׁמוֹ","that-is name-his"],["יוֹחָנָן,","Johanan"],["אוֹתוֹ","him"],["הַנִּקְרָא","the-called"],["יוֹחָנָן","John"],["הַמַּטְבִּיל","the-one-who-baptizes"],["בַּבְּרִית","the-covenant"],["הַחֲדָשָׁה,","the-new"],["וְשֶׁהוּא","and-that-He-is"],["פָּעַל","it-wrought"],["תַּחַת","under"],["הַנְחָיַת","the-you have guided"],["פֶּטְרוֹס","Peter"],["וְיַעֲקֹב","and-Jacob"],["וְיוֹחָנָן","and-Johanan"],["הַמַּחֲזִיקִים","the-those who take hold"],["אֶת","[ACC]"],["מַפְתְּחוֹת","keys-of"],["כְּהֻנַּת","priesthood of"],["אֲשֶׁר","which"],["כְּהֻנָּה","priesthood"],["זוֹ,","Ziv"],["אָמַר,","I-say"],["תִּנָּתֵן","it will be given"],["לָנוּ","unto-us"],["וְשֶׁאֲנִי","and-that-I"],["אֶקָּרֵא","I will read aloud"],["זָקֵן","the-ancient"],["רִאשׁוֹן","the-first"],["שֶׁל","of"],["הַקְּהִילָּה","the-congregation"],["וְהוּא,","and-he"],["אוֹלִיבֶר","Oliver"],["קָאוּדֶרִי,","Cowdery"],["הַשֵּׁנִי.","the-second"],["הָיָה","was"],["זֶה","this"],["בְּיוֹם","in-day"],["הַחֲמִשָּׁה","the-five"],["עָשָׂר","[compound]"],["לְמַאי","to-from-where"],["1829","1829"],["אֲשֶׁר","which"],["תַּחַת","under"],["יַד","hand-of"],["הַשָּׁלִיחַ","the-send"],["הַזֶּה","this"],["׃",""]
  ]},
  { num: "עג", words: [
    ["מִיָּד","immediately"],["בְּעָלוֹתֵנוּ","as-we-ascended"],["מִן","from"],["הַמַּיִם","the-waters"],["אַחֲרֵי","after"],["בְּרָכוֹת","blessings"],["גְּדוֹלוֹת","great"],["וְנֶהְדָּרוֹת","and-glorious(pl)"],["מֵאָבִינוּ","from-father of-our"],["שֶׁבַּשָּׁמַיִם.","who-is-in-heaven"],["אֶת","[ACC]"],["אוֹלִיבֶר","Oliver"],["קָאוּדֶרִי","Cowdery"],["נָפְלָה","fell"],["עָלָיו","upon-him"],["רוּחַ","spirit"],["הַקֹּדֶשׁ,","the-Holy"],["וְהוּא","and-He"],["קָם","arose"],["וְנִבָּא","and-prophesied"],["דְבָרִים","things"],["רַבִּים","many"],["אֲשֶׁר","which"],["בְּקָרוֹב","soon"],["יִקְרוּ.","they are precious"],["וְשׁוּב,","and-will you return?"],["כְּשֶׁהוּא","as-that-He-is"],["הִטְבִּיל","he-did-baptize"],["אוֹתִי,","me"],["גַּם","also"],["לִי","to-me"],["הָיְתָה","was(f)"],["רוּחַ","spirit"],["הַנְּבוּאָה,","the-prophecy"],["וּבְעָמְדִי","and-in-standing-my"],["נִבֵּאתִי","prophesied"],["עַל","upon"],["קוּמַת","the height of"],["הַקְּהִילָּה","the-congregation"],["הַזֹּאת","this"],["וּדְבָרִים","and-things"],["רַבִּים","many"],["אֲחֵרִים","other"],["הַקְּשׁוּרִים","the-bound(pl)"],["לַקְּהִילָּה","to-the-congregation"],["וּלְדוֹר","and-to-are a generation of"],["הַזֶּה","this"],["שֶׁל","of"],["בְּנֵי","sons-of"],["הָאָדָם.","the-man/Adam"],["הִתְמַלֵּאנוּ","we-were-filled"],["רוּחַ","spirit"],["הַקֹּדֶשׁ","the-Holy"],["בֵּאלֹהֵי","in-the-God"],["יִשְׁעֵנוּ.","depend"],["׃",""]
  ]},
  { num: "עד", words: [
    ["וּבְהֵאִיר","and-in-was-illuminated"],["דַּעְתֵּנוּ","our-knowledge"],["עַתָּה,","now"],["הֵחַלְנוּ","began-our/-us"],["לִרְאוֹת","to-see"],["אֶת","[ACC]"],["הַכְּתוּבִים","the-written"],["נִפְתָּחִים","opened"],["וְאֶת","and-[ACC]"],["הַמַּשְׁמָעוּת","the-meaning"],["הָאֲמִתִּית","the-true"],["וְהַכַּוָּנָה","and-the-intention"],["שֶׁל","of"],["פְּסוּקֵיהֶם","verse-their"],["יוֹתֵר","more"],["נִגְלוּ","manifested-were-they"],["לָנוּ","unto-us"],["בְּאֹפֶן","in-a-manner"],["שֶׁלֹּא","that-there-should-be-no"],["יָכֹלְנוּ","we-were-able"],["לְהַשִּׂיג","obtain"],["לְפָנִים","formerly"],["וְלֹא","and-not"],["חָשַׁבְנוּ","thought-us"],["עָלָיו","upon-him"],["מֵעוֹלָם.","from-everlasting"],["בֵּינְתַיִם","the understanding of(dual)"],["נֶאֱלַצְנוּ","we-were-forced"],["לִשְׁמֹר","to-keep"],["בְּסוֹד","in-the intimacy of"],["אֶת","[ACC]"],["נְסִיבוֹת","circumstances"],["קַבָּלַת","you-received"],["הַכְּהֻנָּה","the-priesthood"],["בִּגְלַל","on-account of"],["רוּחַ","spirit"],["רְדִיפָה","persecution"],["שֶׁכְּבָר","who-already"],["הִתְגַּלְּתָה","it-was-revealed"],["בַּשְּׁכוּנָה.","in-the-neighborhood"],["׃",""]
  ]},
  { num: "עה", words: [
    ["אַסְפְסוּף","rabble"],["מִזְּמַן","from-time"],["לִזְמַן,","for-space-of"],["וְזֶה","and-this"],["גַּם","also"],["מִמַּאֲמִינֵי","from-and-the-true"],["דָת.","the law"],["כַּוָּנוֹתֵיהֶם","as-the-and-the beautiful woman of-their"],["לְהַמְלִיץ","to-the-interpreter"],["אַסְפְסוּף","rabble"],["נֶגְדֵּנוּ","against-us"],["רַק","only"],["נֶעֱצְרוּ","we-will-restraint(they)"],["עַל","upon"],["יְדֵי","hands-of"],["הַשְׁפָּעַת","the-the abundance of"],["מִשְׁפַּחַת","family-of"],["אֲבִי","the-Father-of"],["אִשְׁתִּי","my-wife"],["תַּחַת","under"],["הַשְׁגָּחָה","the-glance"],["אֱלֹהִית","divine(f)"],["אֲשֶׁר","which"],["נַעֲשׂוּ","were-done"],["יְדִידוּתִיִּים","friendly"],["מְאוֹד","very"],["אֵלַי","to-me"],["וְהִתְנַגְּדוּ","and-they-opposed"],["וְהָיוּ","and-they-shall-be"],["מוּכָנִים","prepared"],["לְהַרְשׁוֹת","to-the-authority"],["לִי","to-me"],["לְהַמְשִׁיךְ","to-continue"],["בִּמְלֶאכֶת","with-fine-work-of"],["הַתִּרְגּוּם","the-translation"],["בְּלִי","without"],["הַפְרָעָה.","the-had let it run wild-he"],["לָכֵן","therefore"],["וְהִבְטִיחוּ","and-has-promised(they)"],["לָנוּ","unto-us"],["הֲגָנָה","defense"],["מִכָּל","above-all"],["פְּעֻלָּה","work"],["בִּלְתִּי","except"],["חֻקִּית","legal"],["כְּפִי","according-to"],["יְכָלְתָּם.","was-able-their"],["׃",""]
  ]}
];
renderVerseSet(jsh_ch1Verses, 'jsh-ch1-verses');
})();
