// pgp_verses/pgp_intro.js — Pearl of Great Price Introduction
(function() {
var pgpIntro_ch1Verses = [
  { num:"א", words:[["פְּנִינַת","Pearl-of"],["הַמְּחִיר","the-Price"],["הַגָּדוֹל","the-Great"],["הִיא","is"],["מִבְחָר","a-selection-of"],["חׇמָרִים","materials"],["נִבְחָרִים","choice"],["הַנּוֹגְעִים","touching"],["בְּהַרְבֵּה","upon-many"],["הֵיבֵּטִים","aspects"],["חֲשׁוּבִים","significant"],["שֶׁל","of"],["אֱמוּנַת","the-faith-of"],["וְתוֹרַת","and-doctrine-of"],["כְּנֶסִיַּת","The-Church-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Christ"],["שֶׁל","of"],["קְדוֹשֵׁי","Saints-of"],["אַחֲרִית","the-Latter"],["הַיָּמִים","Days"],["׃",""]] },
  { num:"ב", words:[["חׇמָרִים","materials"],["אֵלֶּה","these"],["תֻּרְגְּמוּ","were-translated"],["וְהוּפְקוּ","and-produced"],["עַל","by"],["יְדֵי","the-hand-of"],["הַנָּבִיא","the-Prophet"],["יוֹסֵף","Joseph"],["סְמִית","Smith,"],["וְרֻבָּם","and-most-of-them"],["פֻּרְסְמוּ","were-published"],["בִּכְתָבֵי","in-the-periodicals-of"],["הָעֵת","the-time"],["שֶׁל","of"],["הַכְּנֵסִיָּה","the-Church"],["בִּימָיו","in-his-days"],["׃",""]] },
  { num:"ג", words:[["הָאֹסֶף","the-collection"],["הָרִאשׁוֹן","the-first"],["שֶׁל","of"],["חׇמָרִים","materials"],["הַנּוֹשֵׂא","carrying"],["אֶת־הַשֵּׁם","the-title"],["פְּנִינַת","Pearl-of"],["הַמְּחִיר","the-Price"],["הַגָּדוֹל","the-Great"],["נַעֲשָׂה","was-made"],["בִּשְׁנַת","in-the-year"],["תרי״א","1851"],["עַל","by"],["יְדֵי","the-hand-of"],["הַזָּקֵן","the-Elder"],["פְרַנְקְלִין","Franklin"],["דִּי","D."],["רִיצַ׳רְדְס","Richards,"],["אָז","then"],["חָבֵר","a-member"],["בְּמוֹעֶצֶת","of-the-Council-of"],["שְׁנֵים","the-Two"],["הֶעָשָׂר","-Ten"],["וּנְשִׂיא","and-president-of"],["הַמִּשְׁלַחַת","the-Mission"],["הַבְּרִיטִית","the-British"],["׃",""]] },
  { num: "ד", words: [["מַטְרָתוֹ","Its-purpose"], ["הָיְתָה","was"], ["לְהָקֵל","to-make-more-readily"], ["אֶת־הַגִּישָׁה","accessible"], ["אֶל־מַאֲמָרִים","articles"], ["חֲשׁוּבִים","important"], ["אֲחָדִים","some"], ["אֲשֶׁר","that"], ["תְּפוּצָתָם","their-circulation"], ["הָיְתָה","had-been"], ["מֻגְבֶּלֶת","limited"], ["בִּימֵי","in-the-time-of"], ["יוֹסֵף","Joseph"], ["סְמִית","Smith."], ["׃",""]]},
  { num:"ה", words:[["וְכַאֲשֶׁר","And-as"],["רָבְתָה","increased"],["חַבְרוּת","membership"],["הַכְּנֵסִיָּה","of-the-Church"],["בְּכׇל־אֵירוֹפָּה","throughout-Europe"],["וְאָמֶרִיקָה","and-America,"],["הָיָה","there-was"],["צֹרֶךְ","a-need"],["לְהַמְצִיא","to-make-available"],["אֶת־הַחֳמָרִים","the-items"],["הָאֵלֶּה","these."],["׃",""]] },
  { num:"ו", words:[["פְּנִינַת","Pearl-of"],["הַמְּחִיר","the-Price"],["הַגָּדוֹל","the-Great"],["זָכְתָה","received"],["לְשִׁמּוּשׁ","use"],["נִרְחָב","wide"],["וּלְאַחַר","and-subsequently"],["מִכֵּן","thereafter"],["הָפְכָה","became"],["לִכְתַב","a-standard-work"],["קֹדֶשׁ","of-scripture"],["שֶׁל","of"],["הַכְּנֵסִיָּה","the-Church"],["עַל","by"],["פִּי","according-to"],["פְּעֻלַּת","the-action-of"],["הַנְּשִׂיאוּת","the-Presidency"],["הָרִאשׁוֹנָה","the-First"],["וְהַכְּנֵס","and-the-conference"],["הַכְּלָלִי","the-general"],["בְּסוֹלְט","in-Salt"],["לֵייק","Lake"],["סִיטִי","City"],["בְּעָשָׂר","on-the-tenth"],["בְּאוֹקְטוֹבֶּר","of-October"],["תר״ם","1880"],["׃",""]] },
  { num:"ז", words:[["תִּקּוּנִים","revisions"],["אֲחָדִים","several"],["נַעֲשׂוּ","have-been-made"],["בַּתְּכָנִים","in-the-contents"],["כְּפִי","as"],["שֶׁדָּרְשׁוּ","have-required"],["צׇרְכֵי","the-needs-of"],["הַכְּנֵסִיָּה","the-Church."],["׃",""]] },
  { num:"ח", words:[["בִּשְׁנַת","In-the-year"],["תרל״ח","1878"],["נוֹסְפוּ","were-added"],["חֲלָקִים","portions"],["מִסֵּפֶר","of-the-book-of"],["מֹשֶׁה","Moses"],["אֲשֶׁר","which"],["לֹא","not"],["נִכְלְלוּ","were-contained"],["בַּמַּהֲדוּרָה","in-the-edition"],["הָרִאשׁוֹנָה","first."],["׃",""]] },
  { num:"ט", words:[["בִּשְׁנַת","In-the-year"],["תרס״ב","1902"],["הֻשְׁמְטוּ","were-omitted"],["חֲלָקִים","certain-parts"],["מִפְּנִינַת","of-the-Pearl-of"],["הַמְּחִיר","the-Price"],["הַגָּדוֹל","the-Great"],["אֲשֶׁר","that"],["כָּפְלוּ","duplicated"],["חֳמָרִים","material"],["שֶׁפֻּרְסְמוּ","also-published"],["גַּם","also"],["בְּתוֹרָה","in-the-Doctrine"],["וּבְרִיתוֹת","and-Covenants."],["׃",""]] },
  { num:"י", words:[["הַחֲלֻקָּה","The-arrangement"],["לִפְרָקִים","into-chapters"],["וְלִפְסוּקִים","and-verses,"],["עִם","with"],["הֶעָרוֹת","footnotes,"],["נַעֲשְׂתָה","was-done"],["בִּשְׁנַת","in-the-year"],["תרס״ב","1902."],["׃",""]] },
  { num:"יא", words:[["הַפִּרְסוּם","The-publication"],["הָרִאשׁוֹן","first"],["בְּעַמּוּדִים","in-pages"],["דּוּ־טוּרִיִּים","double-column,"],["עִם","with"],["מַפְתֵּחַ","index,"],["הָיָה","was"],["בִּשְׁנַת","in-the-year"],["תרפ״א","1921."],["׃",""]] },
  { num:"יב", words:[["וְלֹא","And-no"],["נַעֲשׂוּ","were-made"],["שִׁנּוּיִים","changes"],["אֲחֵרִים","other"],["עַד","until"],["אַפְּרִיל","April"],["תשל״ו","1976,"],["כַּאֲשֶׁר","when"],["נוֹסְפוּ","were-added"],["שְׁנֵי","two"],["דִּבְרֵי","items-of"],["הִתְגַּלּוּת","revelation."],["׃",""]] },
  { num:"יג", words:[["בִּשְׁנַת","In-the-year"],["תשל״ט","1979"],["הוּסְרוּ","were-removed"],["שְׁנֵי","two"],["הַדְּבָרִים","items"],["הָאֵלֶּה","these"],["מִפְּנִינַת","from-the-Pearl-of"],["הַמְּחִיר","the-Price"],["הַגָּדוֹל","the-Great"],["וְהוּשְׂמוּ","and-placed"],["בְּתוֹרָה","in-the-Doctrine"],["וּבְרִיתוֹת","and-Covenants,"],["אֲשֶׁר","where"],["שָׁם","there"],["הֵם","they"],["נִמְצָאִים","now-appear"],["כַּיּוֹם","today"],["כִּפְרָקִים","as-sections"],["קלז","137"],["וקלח","and-138."],["׃",""]] },
  { num:"יד", words:[["וּבַמַּהֲדוּרָה","And-in-the-edition"],["הַזֹּאת","present"],["נַעֲשׂוּ","have-been-made"],["שִׁנּוּיִים","changes"],["אֲחָדִים","some"],["לְהָבִיא","to-bring"],["אֶת־הַכָּתוּב","the-text"],["לִידֵי","into"],["הַתְאָמָה","conformity"],["עִם","with"],["מִסְמָכִים","documents"],["קוֹדְמִים","earlier."],["׃",""]] },
  { num:"טו", words:[["וְאֵלֶּה","And-following-is"],["מָבוֹא","a-introduction"],["קָצָר","brief"],["לַתְּכָנִים","to-the-contents"],["שֶׁלְּפָנֵינוּ","present:"],["׃",""]] },
  { num:"טז", words:[["מִבְחָר","Selections"],["מִסֵּפֶר","from-the-Book-of"],["מֹשֶׁה","Moses."],["קֶטַע","An-extract"],["מִסֵּפֶר","from-the-book-of"],["בְּרֵאשִׁית","Genesis"],["שֶׁל","of"],["תַּרְגּוּם","the-translation-of"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["שֶׁל","of"],["הַמִּקְרָא","the-Bible,"],["אֲשֶׁר","which"],["הֵחֵל","he-began"],["בְּיוּנִי","in-June"],["תק״ץ","1830"],["׃",""]] },
  { num:"יז", words:[["סֵפֶר","the-Book-of"],["אַבְרָהָם","Abraham."],["תַּרְגּוּם","a-translation"],["מֻשְׁרֶה","inspired"],["שֶׁל","of"],["כִּתְבֵי","the-writings-of"],["אַבְרָהָם","Abraham."],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["הֵחֵל","began"],["אֶת־הַתַּרְגּוּם","the-translation"],["בִּשְׁנַת","in-the-year"],["תקצ״ה","1835"],["אַחֲרֵי","after"],["שֶׁהִשִּׂיג","obtaining"],["כַּמָּה","some"],["מְגִלּוֹת","papyri"],["מִצְרִיּוֹת","Egyptian."],["הַתַּרְגּוּם","The-translation"],["פֻּרְסַם","was-published"],["בְּהֶמְשֵׁכִים","serially"],["בְּטַיְמְס","in-the-Times"],["אֶנְד","and"],["סִיזְנְס","Seasons"],["הָחֵל","beginning"],["בְּאֶחָד","on-the-first-of"],["בְּמַרְץ","March"],["1842","1842,"],["בְּנָאבוּ","at-Nauvoo,"],["אִילִינוֹי","Illinois."],["׃",""]] },
  { num:"יח", words:[["יוֹסֵף","Joseph"],["סְמִית","Smith—"],["מַתִּתְיָהוּ","Matthew."],["קֶטַע","An-extract"],["מֵעֵדוּת","from-the-testimony-of"],["מַתִּתְיָהוּ","Matthew"],["בְּתַרְגּוּם","in-the-translation-of"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["שֶׁל","of"],["הַמִּקְרָא","the-Bible."],["רְאֵה","see"],["תּוֹרָה","Doctrine"],["וּבְרִיתוֹת","and-Covenants"],["מה","45:"],["ס-סא","60-61"],["לַצַּו","for-the-injunction"],["הָאֱלֹהִי","divine"],["לְהָחֵל","to-begin"],["אֶת־תַּרְגּוּם","the-translation-of"],["הַבְּרִית","the-Testament"],["הַחֲדָשָׁה","New."],["׃",""]] },
  { num:"יט", words:[["יוֹסֵף","Joseph"],["סְמִית","Smith—"],["הִיסְטוֹרְיָה","History."],["קְטָעִים","Excerpts"],["מֵעֵדוּתוֹ","from-his-testimony"],["וְהִיסְטוֹרְיָתוֹ","and-his-history"],["הָרִשְׁמִית","the-official"],["שֶׁל","of"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["אֲשֶׁר","which"],["הוּא","he"],["וְסוֹפְרָיו","and-his-scribes"],["הֵכִינוּ","prepared"],["בִּשְׁנוֹת","in-the-years"],["תקצ״ח","1838"],["תקצ״ט","1839"],["וַאֲשֶׁר","and-which"],["פֻּרְסְמוּ","were-published"],["בְּהֶמְשֵׁכִים","serially"],["בְּטַיְמְס","in-the-Times"],["אֶנְד","and"],["סִיזְנְס","Seasons"],["בְּנָאבוּ","in-Nauvoo,"],["אִילִינוֹי","Illinois,"],["הָחֵל","beginning"],["בַּחֲמִשָּׁה־עָשָׂר","on-the-fifteenth-of"],["בְּמַרְץ","March"],["1842","1842."],["׃",""]] },
  { num:"כ", words:[["עִקְרֵי","the-Articles-of"],["הָאֱמוּנָה","the-Faith"],["שֶׁל","of"],["כְּנֶסִיַּת","The-Church-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Christ"],["שֶׁל","of"],["קְדוֹשֵׁי","Saints-of"],["אַחֲרִית","the-Latter"],["הַיָּמִים","Days."],["הַצְהָרָה","A-statement"],["שֶׁל","by"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["שֶׁפֻּרְסְמָה","published"],["בְּטַיְמְס","in-the-Times"],["אֶנְד","and"],["סִיזוֹנְס","Seasons"],["בְּאֶחָד","on-the-first-of"],["בְּמַרְס","March"],["תר״ב","1842,"],["בְּלִוּוּי","in-company-with"],["הִיסְטוֹרְיָה","a-history"],["קְצָרָה","short"],["שֶׁל","of"],["הַכְּנֵסִיָּה","the-Church"],["הַיְּדוּעָה","known"],["כְּאִגֶּרֶת","as-the-Letter"],["וֶנְטְוֶרְת","Wentworth."],["׃",""]] }
];
renderVerseSet(pgpIntro_ch1Verses, 'pgp-intro-verses');
})();
