// pgp_verses/pgp_intro.js — Pearl of Great Price Introduction
(function() {
var pgpIntro_ch1Verses = [
  // Paragraph 1: The PGP is a selection of choice materials
  { num:"א", words:[["פְּנִינַת","the-Pearl-of"],["הַמְּחִיר","Great"],["הַגָּדוֹל","Price"],["הִיא","is"],["מִבְחָר","a-selection-of"],["חׇמָרִים","materials"],["נִבְחָרִים","choice"],["הַנּוֹגְעִים","touching"],["בְּהַרְבֵּה","many"],["הֵיבֵּטִים","aspects"],["חֲשׁוּבִים","significant"],["שֶׁל","of"],["אֱמוּנַת","the-faith"],["וְתוֹרַת","and-doctrine-of"],["כְּנֶסִיַּת","The-Church-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","Christ"],["שֶׁל","of"],["קְדוֹשֵׁי","Latter-day"],["אַחֲרִית","Saints"],["הַיָּמִים","[Saints]"],["׃",""]] },
  // Paragraph 2: Translated and produced by Joseph Smith
  { num:"ב", words:[["חׇמָרִים","these-items"],["אֵלֶּה","were"],["תֻּרְגְּמוּ","translated"],["וְהוּפְקוּ","and-produced"],["עַל","by"],["יְדֵי","the"],["הַנָּבִיא","Prophet"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["וְרֻבָּם","and-most"],["פֻּרְסְמוּ","were-published"],["בִּכְתָבֵי","in-the-periodicals-of"],["הָעֵת","the-Church"],["שֶׁל","of"],["הַכְּנֵסִיָּה","his"],["בִּימָיו","day"],["׃",""]] },
  // Paragraph 3: First collection by Franklin D. Richards, 1851
  { num:"ג", words:[["הָאֹסֶף","the-collection"],["הָרִאשׁוֹן","the-first"],["שֶׁל","of"],["חׇמָרִים","materials"],["הַנּוֹשֵׂא","carrying"],["אֶת","[ACC]"],["הַשֵּׁם","the-title"],["פְּנִינַת","Pearl-of"],["הַמְּחִיר","Great"],["הַגָּדוֹל","Price"],["נַעֲשָׂה","was-made"],["בִּשְׁנַת","in-the-year"],["תרי״א","1851"],["עַל","by"],["יְדֵי","Elder"],["הַזָּקֵן","Franklin"],["פְרַנְקְלִין","D"],["דִּי","Richards"],["רִיצַ׳רְדְס","then"],["אָז","a-member-of"],["חָבֵר","the-Council-of"],["בְּמוֹעֶצֶת","the"],["שְׁנֵים","Twelve"],["הֶעָשָׂר","and-president-of"],["וּנְשִׂיא","the-British"],["הַמִּשְׁלַחַת","Mission"],["הַבְּרִיטִית","[Mission]"],["׃",""]] },
  // Paragraph 4: Became a standard work, October 10, 1880
  { num:"ד", words:[["פְּנִינַת","the-Pearl-of"],["הַמְּחִיר","Great"],["הַגָּדוֹל","Price"],["זָכְתָה","received"],["לְשִׁמּוּשׁ","use"],["נִרְחָב","wide"],["וּלְאַחַר","and-subsequently"],["מִכֵּן","became"],["הָפְכָה","a-standard-work-of"],["לִכְתַב","the-Church"],["קֹדֶשׁ","by"],["שֶׁל","action-of"],["הַכְּנֵסִיָּה","the-First"],["עַל","Presidency"],["פִּי","and"],["פְּעֻלַּת","the-general"],["הַנְּשִׂיאוּת","conference"],["הָרִאשׁוֹנָה","in"],["וְהַכְּנֵס","Salt-Lake"],["הַכְּלָלִי","City"],["בְּסוֹלְט","on"],["לֵייק","October"],["סִיטִי","10"],["בְּעָשָׂר","1880"],["בְּאוֹקְטוֹבֶּר","[1880]"],["תר״ם","[1880]"],["׃",""]] },
  // Paragraph 5: Book of Moses description
  { num:"ה", words:[["מִבְחָר","selections"],["מִסֵּפֶר","from-the-Book-of"],["מֹשֶׁה","Moses"],["קֶטַע","an-extract"],["מִסֵּפֶר","from-the-book-of"],["בְּרֵאשִׁית","Genesis"],["שֶׁל","of"],["תַּרְגּוּם","the-translation-of"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["שֶׁל","of"],["הַמִּקְרָא","the-Bible"],["אֲשֶׁר","which"],["הֵחֵל","he-began"],["בְּיוּנִי","in-June"],["תק״ץ","1830"],["׃",""]] },
  // Paragraph 6: Book of Abraham
  { num:"ו", words:[["סֵפֶר","the-Book-of"],["אַבְרָהָם","Abraham"],["תַּרְגּוּם","an-inspired"],["מֻשְׁרֶה","translation-of"],["שֶׁל","the"],["כִּתְבֵי","writings-of"],["אַבְרָהָם","Abraham"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["הֵחֵל","began"],["אֶת","[ACC]"],["הַתַּרְגּוּם","the-translation"],["בִּשְׁנַת","in-the-year"],["תקצ״ה","1835"],["אַחֲרֵי","after"],["שֶׁהִשִּׂיג","obtaining"],["כַּמָּה","some"],["מְגִלּוֹת","papyri"],["מִצְרִיּוֹת","Egyptian"],["׃",""]] },
  // Paragraph 7: Joseph Smith—Matthew
  { num:"ז", words:[["יוֹסֵף","Joseph"],["סְמִית","Smith"],["מַתִּתְיָהוּ","Matthew"],["קֶטַע","an-extract"],["מֵעֵדוּת","from-the-testimony-of"],["מַתִּתְיָהוּ","Matthew"],["בְּתַרְגּוּם","in-the-translation-of"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["שֶׁל","of"],["הַמִּקְרָא","the-Bible"],["׃",""]] },
  // Paragraph 8: Joseph Smith—History
  { num:"ח", words:[["יוֹסֵף","Joseph"],["סְמִית","Smith"],["הִיסְטוֹרְיָה","History"],["קְטָעִים","excerpts"],["מֵעֵדוּתוֹ","from-the-testimony-of"],["וְהִיסְטוֹרְיָתוֹ","and-history-of"],["הָרִשְׁמִית","official"],["שֶׁל","of"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["אֲשֶׁר","which"],["הוּא","he"],["וְסוֹפְרָיו","and-his-scribes"],["הֵכִינוּ","prepared"],["בִּשְׁנוֹת","in-the-years"],["תקצ״ח","1838"],["תקצ״ט","1839"],["׃",""]] },
  // Paragraph 9: Articles of Faith
  { num:"ט", words:[["עִקְרֵי","the-Articles-of"],["הָאֱמוּנָה","Faith"],["שֶׁל","of"],["כְּנֶסִיַּת","The-Church-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","Christ"],["שֶׁל","of"],["קְדוֹשֵׁי","Latter-day"],["אַחֲרִית","Saints"],["הַיָּמִים","[Saints]"],["הַצְהָרָה","a-statement"],["שֶׁל","by"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["שֶׁפֻּרְסְמָה","published"],["בְּטַיְמְס","in-the-Times"],["אֶנְד","and"],["סִיזוֹנְס","Seasons"],["בְּאֶחָד","on-the-first-of"],["בְּמַרְס","March"],["תר״ב","1842"],["בְּלִוּוּי","in-company-with"],["הִיסְטוֹרְיָה","a-short-history-of"],["קְצָרָה","the-Church"],["שֶׁל","popularly"],["הַכְּנֵסִיָּה","known-as"],["הַיְּדוּעָה","the-Wentworth"],["כְּאִגֶּרֶת","Letter"],["וֶנְטְוֶרְת","[Letter]"],["׃",""]] }
];
renderVerseSet(pgpIntro_ch1Verses, 'pgp-intro-verses');
})();
