// pgp_verses/pgp_intro.js — Pearl of Great Price Introduction
(function() {
var pgpIntro_ch1Verses = [
  // Paragraph 1: The PGP is a selection of choice materials
  { num:"א", words:[["פנינת","Pearl-of"],["המחיר","the-Price"],["הגדול","the-Great"],["הִיא","is"],["מִבְחָר","a-selection-of"],["חׇמָרִים","materials"],["נִבְחָרִים","choice"],["הַנּוֹגְעִים","touching"],["בְּהַרְבֵּה","upon-many"],["הֵיבֵּטִים","aspects"],["חֲשׁוּבִים","significant"],["שֶׁל","of"],["אֱמוּנַת","the-faith-of"],["וְתוֹרַת","and-doctrine-of"],["כְּנֶסִיַּת","The-Church-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Christ"],["שֶׁל","of"],["קְדוֹשֵׁי","Saints-of"],["אַחֲרִית","the-Latter"],["הַיָּמִים","Days"],["׃",""]] },
  // Paragraph 2: Translated and produced by Joseph Smith
  { num:"ב", words:[["חׇמָרִים","materials"],["אֵלֶּה","these"],["תֻּרְגְּמוּ","were-translated"],["וְהוּפְקוּ","and-produced"],["עַל","by"],["יְדֵי","the-hand-of"],["הַנָּבִיא","the-Prophet"],["יוֹסֵף","Joseph"],["סְמִית","Smith,"],["וְרֻבָּם","and-most-of-them"],["פֻּרְסְמוּ","were-published"],["בִּכְתָבֵי","in-the-periodicals-of"],["הָעֵת","the-time"],["שֶׁל","of"],["הַכְּנֵסִיָּה","the-Church"],["בִּימָיו","in-his-days"],["׃",""]] },
  // Paragraph 3: First collection by Franklin D. Richards, 1851
  { num: "ג", words: [["הָאֹסֶף","the-collection"], ["הָרִאשׁוֹן","the-first"], ["שֶׁל","of"], ["חׇמָרִים","materials"], ["הַנּוֹשֵׂא","carrying"], ["אֶת־הַשֵּׁם","the-title"], ["פנינת","Pearl-of"], ["המחיר","the-Price"], ["הגדול","the-Great"], ["נַעֲשָׂה","was-made"], ["בִּשְׁנַת","in-the-year"], ["תרי״א","1851"], ["עַל","by"], ["יְדֵי","the-hand-of"], ["הַזָּקֵן","the-Elder"], ["פְרַנְקְלִין","Franklin"], ["דִּי","D."], ["רִיצַ׳רְדְס","Richards,"], ["אָז","then"], ["חָבֵר","a-member"], ["בְּמוֹעֶצֶת","of-the-Council-of"], ["שְׁנֵים","the-Two"], ["הֶעָשָׂר","-Ten"], ["וּנְשִׂיא","and-president-of"], ["הַמִּשְׁלַחַת","the-Mission"], ["הַבְּרִיטִית","the-British"], ["׃",""]]},
  // Paragraph 4: Became a standard work, October 10, 1880
  { num:"ד", words:[["פנינת","Pearl-of"],["המחיר","the-Price"],["הגדול","the-Great"],["זָכְתָה","received"],["לְשִׁמּוּשׁ","use"],["נִרְחָב","wide"],["וּלְאַחַר","and-subsequently"],["מִכֵּן","thereafter"],["הָפְכָה","became"],["לִכְתַב","a-standard-work"],["קֹדֶשׁ","of-scripture"],["שֶׁל","of"],["הַכְּנֵסִיָּה","the-Church"],["עַל","by"],["פִּי","according-to"],["פְּעֻלַּת","the-action-of"],["הַנְּשִׂיאוּת","the-Presidency"],["הָרִאשׁוֹנָה","the-First"],["וְהַכְּנֵס","and-the-conference"],["הַכְּלָלִי","the-general"],["בְּסוֹלְט","in-Salt"],["לֵייק","Lake"],["סִיטִי","City"],["בְּעָשָׂר","on-the-tenth"],["בְּאוֹקְטוֹבֶּר","of-October"],["תר״ם","1880"],["׃",""]] },
  // Paragraph 5: Book of Moses description
  { num:"ה", words:[["מִבְחָר","Selections"],["מִסֵּפֶר","from-the-Book-of"],["מֹשֶׁה","Moses."],["קֶטַע","An-extract"],["מִסֵּפֶר","from-the-book-of"],["בְּרֵאשִׁית","Genesis"],["שֶׁל","of"],["תַּרְגּוּם","the-translation-of"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["שֶׁל","of"],["הַמִּקְרָא","the-Bible,"],["אֲשֶׁר","which"],["הֵחֵל","he-began"],["בְּיוּנִי","in-June"],["תק״ץ","1830"],["׃",""]] },
  // Paragraph 6: Book of Abraham
  { num:"ו", words:[["סֵפֶר","the-Book-of"],["אַבְרָהָם","Abraham."],["תַּרְגּוּם","a-translation"],["מֻשְׁרֶה","inspired"],["שֶׁל","of"],["כִּתְבֵי","the-writings-of"],["אַבְרָהָם","Abraham."],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["הֵחֵל","began"],["אֶת־הַתַּרְגּוּם","the-translation"],["בִּשְׁנַת","in-the-year"],["תקצ״ה","1835"],["אַחֲרֵי","after"],["שֶׁהִשִּׂיג","obtaining"],["כַּמָּה","some"],["מְגִלּוֹת","papyri"],["מִצְרִיּוֹת","Egyptian."],["׃",""]] },
  // Paragraph 7: Joseph Smith—Matthew
  { num:"ז", words:[["יוֹסֵף","Joseph"],["סְמִית","Smith—"],["מַתִּתְיָהוּ","Matthew."],["קֶטַע","An-extract"],["מֵעֵדוּת","from-the-testimony-of"],["מַתִּתְיָהוּ","Matthew"],["בְּתַרְגּוּם","in-the-translation-of"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["שֶׁל","of"],["הַמִּקְרָא","the-Bible."],["׃",""]] },
  // Paragraph 8: Joseph Smith—History
  { num:"ח", words:[["יוֹסֵף","Joseph"],["סְמִית","Smith—"],["הִיסְטוֹרְיָה","History."],["קְטָעִים","Excerpts"],["מֵעֵדוּתוֹ","from-his-testimony"],["וְהִיסְטוֹרְיָתוֹ","and-his-history"],["הָרִשְׁמִית","the-official"],["שֶׁל","of"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["אֲשֶׁר","which"],["הוּא","he"],["וְסוֹפְרָיו","and-his-scribes"],["הֵכִינוּ","prepared"],["בִּשְׁנוֹת","in-the-years"],["תקצ״ח","1838"],["תקצ״ט","1839"],["׃",""]] },
  // Paragraph 9: Articles of Faith
  { num:"ט", words:[["עִקְרֵי","the-Articles-of"],["הָאֱמוּנָה","the-Faith"],["שֶׁל","of"],["כְּנֶסִיַּת","The-Church-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Christ"],["שֶׁל","of"],["קְדוֹשֵׁי","Saints-of"],["אַחֲרִית","the-Latter"],["הַיָּמִים","Days."],["הַצְהָרָה","A-statement"],["שֶׁל","by"],["יוֹסֵף","Joseph"],["סְמִית","Smith"],["שֶׁפֻּרְסְמָה","published"],["בְּטַיְמְס","in-the-Times"],["אֶנְד","and"],["סִיזוֹנְס","Seasons"],["בְּאֶחָד","on-the-first-of"],["בְּמַרְס","March"],["תר״ב","1842,"],["בְּלִוּוּי","in-company-with"],["הִיסְטוֹרְיָה","a-history"],["קְצָרָה","short"],["שֶׁל","of"],["הַכְּנֵסִיָּה","the-Church"],["הַיְּדוּעָה","known"],["כְּאִגֶּרֶת","as-the-Letter"],["וֶנְטְוֶרְת","Wentworth."],["׃",""]] }
];
renderVerseSet(pgpIntro_ch1Verses, 'pgp-intro-verses');
})();
