// fix_final_comprehensive.js
// Comprehensive fix for remaining bad transliterations in BOM.html
// Replaces consonant-heavy nonsense glosses with proper English translations

const fs = require('fs');
const path = require('path');

const bomPath = path.join(__dirname, 'BOM.html');

// Strip niqqud (vowel points and cantillation marks) from Hebrew text
function stripNiqqud(s) {
  return s.replace(/[\u0591-\u05C7]/g, '');
}

// ============================================================
// MASSIVE DICTIONARY: stripped Hebrew -> proper English gloss
// Every entry from remaining_list.txt is covered.
// ============================================================

const hebrewToEnglish = {
  // === Line 1-50: Core vocabulary ===
  "והכהנה": "and-the-priesthood",
  "בעבותות": "in-cords",
  "בקדחת": "with-fever",
  "המאורעות": "the-events",
  "קצירם": "their-harvest",
  "בהריגת": "in-the-killing-of",
  "ובשדידתם": "and-in-their-plundering",
  "המפיצים": "the-scatterers",
  "במקלות": "with-staves",
  "קצצו": "they-were-cut-off",
  "לשומו": "to-place-it",
  "להלנן": "to-murmur",
  "הככר": "the-plain",
  "ותקצף": "and-she-was-angry",
  "הסגירו": "they-delivered-up",
  "מרידתם": "their-rebellion",
  "כתמינו": "our-stains",
  "נכתם": "is-stained",
  "זהרים": "shining",
  "צפו": "they-floated",
  "נהלל": "we-shall-praise",
  "נתהלל": "we-shall-boast",
  "ונשמידם": "and-we-shall-destroy-them",
  "מתאבלים": "mourning",
  "בטחונם": "their-confidence",
  "לגזל": "to-rob",
  "תכה": "she-shall-be-struck",
  "כסגים": "like-dross",
  "לתפח": "to-swell",
  "ומתחיל": "and-beginning",
  "תטפחוהו": "you-shall-nurture-it",
  "תטפחו": "you-shall-nurture",
  "צומח": "growing",
  "דחיתם": "you-rejected",
  "בנסיונות": "in-trials",
  "זהרם": "their-brightness",
  "תסתיר": "you-shall-hide",
  "להפעיל": "to-activate",
  "הקשיב": "he-listened",
  "מרשיע": "condemning",
  "תערבת": "mixture",
  "וחרמשותיהם": "and-their-scythes",
  "שריוניהם": "their-armor",
  "תמסרו": "you-shall-deliver",
  "להכחד": "to-be-destroyed",
  "יכחדו": "they-shall-be-destroyed",
  "הקצפים": "the-angry-ones",
  "יברכם": "he-shall-bless-them",
  "מהאמליקיהים": "from-the-Amalickiahites",
  "לתקופת": "to-the-period-of",

  // === Line 51-100 ===
  "בקדחת": "with-fever",
  "בנגוד": "in-opposition",
  "הרפים": "the-weak-ones",
  "יתגברו": "they-shall-prevail",
  "בטחון": "confidence",
  "אחזת": "possession-of",
  "חמה": "wrath",
  "חמה": "wrath",
  "להכריח": "to-compel",
  "להתקיפם": "to-attack-them",
  "השאיר": "he-left",
  "להמיר": "to-exchange",
  "נשתכרו": "they-became-drunk",
  "הקפנו": "we-surrounded",
  "מתמיכתם": "from-their-support",
  "במצוק": "in-distress",
  "הגדוד": "the-troop",
  "חררם": "their-burning",
  "עזיבתכם": "your-abandonment",
  "נתקומם": "we-shall-rise-up",
  "הקפו": "they-were-surrounded",
  "צזורם": "Cezoram",
  "לכלבים": "to-the-dogs",
  "תלקחנה": "they-shall-be-taken",
  "כל־המביטים": "all-the-lookers",
  "רצנו": "we-ran",
  "את־הרוצח": "[ACC]-the-murderer",
  "שחררו": "they-were-freed",
  "הסכמתי": "I-agreed",
  "חרונך": "your-wrath",
  "לשכח": "to-forget",
  "מטביל": "one-who-immerses",
  "והמרמות": "and-the-deceits",
  "טבח": "slaughter",
  "פחות": "governors",
  "קברתי": "I-buried",
  "את־מכות": "[ACC]-plagues-of",
  "המסמרים": "the-nails",
  "המלח": "the-salt",
  "תחפצו": "you-shall-desire",
  "נשלמו": "they-were-completed",
  "יחתרו": "they-shall-dig",
  "דפקו": "they-knocked",
  "אשחית": "I-shall-destroy",
  "ואם־תזכרוני": "and-if-you-remember-me",
  "תגרשוהו": "you-shall-drive-him-out",
  "ונברכו": "and-they-were-blessed",
  "יקפצו": "they-shall-leap",
  "מצרף": "refiner",

  // === Line 100-150 ===
  "כנסית": "the-church-of",
  "כריס": "Christ",
  "הצפונית": "the-northern",
  "בן־מורון׃": "son-of-Moron",
  "בן־אחח׃": "son-of-Ahah",
  "ואחח": "and-Ahah",
  "בן־שת׃": "son-of-Seth",
  "בן־שבלון׃": "son-of-Shiblon",
  "בן־ליב׃": "son-of-Lib",
  "בן־קיש׃": "son-of-Kish",
  "בן־כורום׃": "son-of-Corom",
  "בן־לוי׃": "son-of-Levi",
  "בן־קים׃": "son-of-Kim",
  "בן־שז׃": "son-of-Shez",
  "בן־חת׃": "son-of-Heth",
  "בן־קיב׃": "son-of-Kib",
  "נירשנה׃": "we-shall-inherit-it",
  "דסרת": "Deseret",
  "דבש": "honey",
  "ותחתיתן": "and-their-bottom",
  "מחדדות": "pointed",
  "וארכן": "and-their-length",
  "ודלתן": "and-their-door",
  "כקערה׃": "like-a-dish",
  "ננהיג": "we-shall-lead",
  "חלונות": "windows",
  "ישטפו": "they-shall-flood",
  "תחפצו": "you-shall-desire",
  "בהבלעכם": "when-you-are-swallowed",
  "זכה": "pure",
  "פן־יכני": "lest-he-strike-me",
  "אלבש": "I-shall-wear",
  "נפדית": "you-were-redeemed",
  "נבראת": "you-were-created",
  "בצלמי": "in-my-image",
  "בצלמי׃": "in-my-image",
  "אכבד": "I-shall-honor",
  "תצפן": "you-shall-hide",
  "להראותן": "to-show-them",
  "להטמינם": "to-hide-them",
  "את־פתרונם": "[ACC]-their-interpretation",
  "יתקדשו": "they-shall-be-sanctified",
  "אפרש": "I-shall-spread",
  "המדריך": "the-guide",
  "הטמונה": "the-hidden-one",
  "צפן": "he-hid",
  "את־מסך": "[ACC]-curtain",
  "יפרשו": "they-shall-spread",
  "זכרוני": "my-memorial",
  "תפתרו": "you-shall-interpret",
  "אל־ספינותיהם": "to-their-ships",

  // === Line 151-200 ===
  "כתבת": "inscription-of",
  "מפלצת": "horror",
  "על־חופי": "upon-the-shores-of",
  "וגלגה": "and-Gilgal",
  "נקהילה": "let-us-assemble",
  "תחפצו׃": "you-shall-desire",
  "את־כוריהור׃": "[ACC]-Korihor",
  "את־כוהור": "[ACC]-Cohor",
  "ויתגנבו": "and-they-stole-away",
  "את־כוהור׃": "[ACC]-Cohor",
  "בן־כמנור": "son-of-Kimnor",
  "ותרקד": "and-she-danced",
  "יתפשטו": "they-shall-spread",
  "על־בוניה׃": "upon-its-builders",
  "כל־הבונה": "all-who-builds",
  "אם־ידרכו": "if-they-are-guided",
  "נמשח": "he-was-anointed",
  "פרישת": "spreading-of",
  "האכילו": "they-fed-him",
  "משכו": "they-drew",
  "את־כום": "[ACC]-Com",
  "לחבק": "to-embrace",
  "קדמוניות": "ancient-things",
  "בארסם": "with-their-poison",
  "אם־יגדו": "if-they-declare",
  "את־רפלקיש": "[ACC]-Riplakish",
  "צרף": "he-refined",
  "בזנותיו": "in-his-harlotry",
  "את־כורום": "[ACC]-Corom",
  "גם־קיש": "also-Kish",
  "יחצץ": "he-shall-divide",
  "נמרצים": "vigorous",
  "ויחפרו": "and-they-dug",
  "ומצלח": "and-prosperous",
  "את־כום׃": "[ACC]-Com",
  "למחסה": "for-shelter",
  "להעצר": "to-be-stopped",
  "אל־תריבו": "do-not-contend",
  "להשתתף": "to-participate",
  "ולהשתתף": "and-to-participate",
  "חזו": "they-beheld",
  "ונכשל": "and-stumbling",
  "בשימת": "in-placing",
  "יתלוצצו": "they-shall-mock",
  "צרין": "Zerin",
  "תבחנם": "you-shall-test-them",
  "בדמכם׃": "by-your-blood",
  "פשוטה": "simple",
  "רחצו": "they-were-washed",
  "פזרו": "they-were-scattered",

  // === Line 201-250 ===
  "ויסתתר": "and-he-hid-himself",
  "בהלחמם": "when-they-fought",
  "הרביעית": "the-fourth",
  "חשלון׃": "Cheshlon",
  "גלגל׃": "Gilgal",
  "אם־יניח": "if-he-shall-allow",
  "מאגדות": "from-bundles",
  "דחק": "he-pressed",
  "וארכה": "and-healing",
  "משאירים": "leaving",
  "שטוחים": "flat",
  "הפגרים": "the-corpses",
  "לאבדנם": "to-their-destruction",
  "בשופר": "with-a-shofar",
  "התרפא": "he-was-healed",
  "להתנחם": "to-be-comforted",
  "ותתאבל": "and-she-mourned",
  "ואהרגך": "and-I-shall-kill-you",
  "התערו": "they-were-stirred-up",
  "את־הרשומות": "[ACC]-the-records",
  "מהגות": "from-meditations",
  "שכורי": "drunkards-of",
  "שכור": "drunk",
  "ובמגניהם": "and-with-their-shields",
  "התעלף": "he-fainted",
  "נשען": "he-leaned",
  "את־רשומתו": "[ACC]-his-record",
  "ויטמנם": "and-he-hid-them",
  "אם־יכלכלו": "if-they-shall-sustain",
  "אשמת": "you-are-guilty",
  "שפכת": "you-shed",
  "מהתפשט": "from-spreading",
  "ויתנכרו": "and-they-disguised-themselves",
  "לשדד": "to-plunder",
  "באגרוף׃": "with-a-fist",
  "ובלתי־נמוט": "and-not-moved",
  "לא־החשיב": "not-he-regarded",
  "מן־הלומד": "from-the-learner",
  "כל־צרכיהם": "all-their-needs",
  "התמכרו": "they-sold-themselves",
  "וישדדו": "and-they-plundered",
  "את־זכויות": "[ACC]-rights",
  "בעמליסים": "among-the-Amlicites",
  "נמהר": "let-us-hurry",
  "נתחזקו": "they-strengthened-themselves",
  "את־פגרי": "[ACC]-corpses-of",
  "חרמונתס": "Hermounts",
  "גלחו": "they-shaved",
  "כהה": "dim",
  "ורחמתים׃": "and-I-had-compassion-on-them",

  // === Line 251-300 ===
  "לסמן": "to-mark",
  "תחול": "it-shall-fall-upon",
  "נלחמה": "let-us-fight",
  "זרהמלה׃פרק": "Zarahemla-chapter",
  "התעצבו": "they-were-grieved",
  "מתנשאים": "being-lifted-up",
  "משפילים": "humbling",
  "חכה": "he-waited",
  "ותרחבנה": "and-they-widened",
  "צלמו": "his-image",
  "לכזב": "to-lie",
  "וצלם": "and-image",
  "נכבסו": "they-were-washed",
  "מה־ירגש": "what-he-feels",
  "הרגשתם": "you-felt",
  "ההתהלכתם": "did-you-walk",
  "המלעיג": "the-mocker",
  "המתנפחים": "the-puffed-up",
  "כל־המכחיש": "all-who-deny",
  "להתנפח": "to-be-puffed-up",
  "המשפילים": "the-humble-ones",
  "אם־תדברו": "if-you-speak",
  "ובאאחרונה": "and-at-the-last",
  "שתפים": "partners",
  "במבוכה": "in-confusion",
  "תצפו": "you-shall-watch",
  "חשוב": "important",
  "תכסה": "it-shall-be-covered",
  "תטהרו": "you-shall-be-purified",
  "רצונכם": "your-will",
  "במבוכה": "in-confusion",
  "עקלקלות": "crooked",
  "נתקבלתם׃": "you-were-received",
  "כל־צרכיכם": "all-your-needs",
  "לאאחרונה": "at-the-last",
  "ויחרפו": "and-they-reviled",
  "קבלת": "you-received",
  "ותדרש": "and-she-shall-seek",
  "אם־גרשוני": "if-they-drove-me-out",
  "האכלתני": "you-fed-me",
  "ותאספני": "and-you-gathered-me",
  "בזקים": "in-chains",
  "נצויתי": "I-was-commanded",
  "ננהגו": "they-were-led",
  "והשכחתם": "and-you-forgot",
  "נתאמת": "it-was-confirmed",
  "נגרם": "was-caused",
  "תמרו": "you-shall-rebel",
  "יקצר": "he-shall-reap",
  "לקחתני": "to-take-me",

  // === Line 301-350 ===
  "בן־גדונה": "son-of-Giddonah",
  "רכשתי": "I-acquired",
  "שגיתי": "I-erred",
  "תאכיל": "you-shall-feed",
  "תכניסהו": "you-shall-bring-him-in",
  "ימשל": "he-shall-rule",
  "נחמלתם": "you-had-compassion",
  "כי־ישה": "that-he-lends",
  "שטרים": "officers",
  "יפשט": "it-shall-be-spread",
  "וכשדד׃": "and-like-a-plunderer",
  "לערכם": "to-their-value",
  "מדדו": "they-measured",
  "ומדתם": "and-their-measure",
  "ולמנה": "and-a-lemanah",
  "מסנינה׃": "a-seninah",
  "למנה": "a-lemanah",
  "שבלונים׃": "shiblons",
  "תנסני": "you-shall-test-me",
  "חשבת": "you-thought",
  "ולנקבה": "and-to-a-female",
  "מתאחדים": "uniting",
  "נתפשת": "you-were-caught",
  "כערמת": "like-a-heap-of",
  "תשימם": "you-shall-place-them",
  "בשרשרותיו": "in-his-chains",
  "יאסרכם": "he-shall-bind-you",
  "שרשרות": "chains",
  "המכינה": "the-preparing",
  "לנפוצים": "to-the-scattered",
  "נשגה": "we-erred",
  "כרמנו׃": "our-vineyard",
  "מחכים": "waiting",
  "ותשליכו": "and-you-shall-cast-out",
  "לא־תורידו": "not-you-shall-bring-down",
  "נכחות": "right-things",
  "בנכח": "in-the-presence-of",
  "להלפת": "to-be-turned",
  "לרגם": "to-stone",
  "השרפה": "the-burning",
  "עצרתני": "you-detained-me",
  "נגמרה": "it-was-finished",
  "השוטרים": "the-officers",
  "להסגירכם": "to-deliver-you-up",
  "תצילו": "you-shall-rescue",
  "חרקים": "gnashing",
  "פשטו": "they-spread",
  "בעבותות׃": "in-cords",
  "וננצל": "and-we-shall-be-saved",
  "ולא־נזוקו": "and-not-they-were-harmed",

  // === Line 351-400 ===
  "ונרגמו": "and-they-were-stoned",
  "להצרב": "to-be-scorched",
  "למדת׃": "you-taught",
  "והפגרים": "and-the-corpses",
  "נטרפו": "they-were-devoured",
  "בכסוי": "in-covering",
  "מסך": "curtain",
  "הכפירה": "the-denial",
  "אל־תקברהו׃": "do-not-bury-him",
  "התאמיני": "do-you-believe",
  "נשפכת": "is-poured-out",
  "נכבש": "was-conquered",
  "ותתעצב": "and-she-was-grieved",
  "להקימה": "to-establish-it",
  "ומרכבותיו׃": "and-his-chariots",
  "הכזב׃": "the-lie",
  "מהכעיסו׃": "from-provoking-him",
  "שהה": "he-delayed",
  "כזב": "a-lie",
  "ובכזביהם": "and-in-their-lies",
  "להשתמש": "to-use",
  "אכך": "I-shall-smite-you",
  "תקצף": "you-shall-be-angry",
  "ללעגו": "to-mock-him",
  "וישקדו": "and-they-were-diligent",
  "תשרתוני": "you-shall-serve-me",
  "ממדוני": "from-Middoni",
  "בצלמו": "in-his-image",
  "השתטח": "he-prostrated",
  "כמפילים": "like-those-who-cause-to-fall",
  "תצוי": "you-shall-command",
  "ברצועת": "with-a-strap",
  "הבטלנים": "the-idle-ones",
  "ותגבל": "and-she-bordered",
  "נושבת": "inhabited",
  "מקפות": "surrounded",
  "בעמנר": "in-Omner",
  "בהמני": "in-Himni",
  "ישדדו": "they-shall-plunder",
  "בדרשותיהם": "in-their-preachings",
  "שמנילום׃": "Shimnilom",
  "להתגונן": "to-defend-oneself",
  "נוכחנו": "we-were-present",
  "סלח": "forgive",
  "כתמנו׃": "our-stains",
  "נצפן": "we-shall-hide",
  "נטמנם": "we-shall-hide-them",
  "כתמנו": "we-stained",
  "נטמן": "we-shall-hide",

  // === Line 401-450 ===
  "נטלנום": "we-carried-them",
  "ישכבו": "they-shall-lie-down",
  "המתחברים": "the-ones-joining",
  "נצודים": "being-hunted",
  "נדפו": "they-were-driven",
  "החיצונים": "the-outer-ones",
  "גדרת": "fence-of",
  "ותקצרו": "and-you-reaped",
  "האסמים": "the-granaries",
  "יסחפו": "they-shall-be-swept-away",
  "הקציר": "the-harvest",
  "להתהלל׃": "to-boast",
  "גדש": "he-heaped",
  "הסגירנו": "he-delivered-us-up",
  "בשגיאת": "in-the-error-of",
  "ונשת": "and-we-were-weakened",
  "מחסור": "lack",
  "ברחובותיהם": "in-their-streets",
  "ונסקלנו": "and-we-were-stoned",
  "נקבצה": "let-us-gather",
  "ונבטח": "and-we-shall-trust",
  "יקחנה": "he-shall-take-it",
  "חרמש": "scythe",
  "המספד": "the-mourning",
  "נרקבים": "rotting",
  "בשופר": "with-a-shofar",
  "במשאלתי": "in-my-request",
  "להרגיז": "to-provoke",
  "גזרת": "decree-of",
  "במשאלותי": "in-my-requests",
  "יחלק": "he-shall-divide",
  "כהפרדה": "when-it-parted",
  "תצמדו": "you-shall-cling",
  "תחכו": "you-shall-wait",
  "ותהפכת": "and-perversity",
  "מצליח": "prosperous",
  "קצו׃": "his-end",
  "להפסיק": "to-stop",
  "להנות": "to-enjoy",
  "השטרים": "the-officers",
  "בהולכת": "in-the-conduct-of",
  "תתנגד": "you-shall-oppose",
  "מכחש": "denying",
  "הנשכחת": "have-you-forgotten",
  "רצית": "you-desired",
  "הרצית": "did-you-desire",
  "התתוכח": "will-you-argue",
  "ונדרך": "and-it-was-trodden",
  "יגררם": "he-shall-drag-them",
  "הפרד": "separate",

  // === Line 451-500 ===
  "גבלה": "she-bordered",
  "להנחות": "to-guide",
  "המני": "Himni",
  "זעזרום": "Zeezrom",
  "הבדלת": "you-separated",
  "בעצמן׃": "by-themselves",
  "בעצמה": "by-herself",
  "הדיחם": "he-led-them-astray",
  "נגנבו": "they-were-stolen",
  "מנפחים": "puffed-up",
  "וצמדיהם": "and-their-yokes",
  "השגיח": "he-watched-over",
  "נבזיתם": "you-were-despised",
  "בהכרחו": "when-he-was-compelled",
  "יחלק": "he-shall-divide",
  "בגרגיר": "in-a-seed",
  "נדמה": "we-shall-compare",
  "תזרעוהו": "you-shall-sow-it",
  "חזכם": "your-vision",
  "התפיחה": "the-swelling",
  "יתפח": "it-shall-swell",
  "ומצמיח": "and-causing-to-sprout",
  "תפח": "it-swelled",
  "והצמיח": "and-it-sprouted",
  "להתרחב׃": "to-expand",
  "נכר": "it-was-recognized",
  "טעמתם": "you-tasted",
  "נטפחנו": "we-shall-nurture-it",
  "תזניחו": "you-shall-neglect",
  "לטפוחו": "to-nurture-it",
  "ושרפתו": "and-you-burned-it",
  "ותשליכוהו׃": "and-you-cast-it-out",
  "צחיחה": "barren",
  "תטפחו": "you-shall-nurture",
  "תקטפו": "you-shall-pluck",
  "תצמאו׃": "you-shall-thirst",
  "תקצרו": "you-shall-reap",
  "ותפקדם": "and-she-visited-them",
  "קצפת": "you-were-angry",
  "חננת": "you-were-gracious",
  "המביט": "the-one-looking",
  "תרפאו": "you-shall-be-healed",
  "ותתעצלו": "and-you-shall-be-lazy",
  "מוכרח": "compelled",
  "דורשת": "seeking",
  "והזבח": "and-the-sacrifice",
  "הזבח": "the-sacrifice",
  "הבטחון": "the-confidence",
  "חשוף": "exposed",
  "תפקדו": "you-shall-visit",

  // === Line 501-550 ===
  "והמענה": "and-the-afflicted-one",
  "המצרפים": "the-refiners",
  "ונרמסים": "and-being-trampled",
  "תדחו": "you-shall-reject",
  "אחזר": "I-shall-return",
  "היורשת": "the-inheriting",
  "תשקדו": "you-shall-watch",
  "יגמלכם": "he-shall-reward-you",
  "כצרכיהם׃": "according-to-their-needs",
  "להתערב": "to-be-mixed",
  "בנסיונותיו": "in-his-trials",
  "נחרשה": "was-silenced",
  "ונעכרה": "and-was-troubled",
  "נעכרה": "was-troubled",
  "ואכחד": "and-I-shall-conceal",
  "נעכרתי": "I-was-troubled",
  "נדחת׃": "rejected",
  "ונעכר": "and-was-troubled",
  "חנני": "be-gracious-to-me",
  "נעכרתי": "I-was-troubled",
  "ונתמכתי": "and-I-was-supported",
  "הצילני": "save-me",
  "הגדילו": "they-magnified",
  "אחדל׃": "I-shall-cease",
  "ותמסר": "and-she-shall-be-delivered",
  "תפקיד": "assignment",
  "משענך": "your-support",
  "ינחך": "he-shall-guide-you",
  "מצפן": "compass",
  "המצפן": "the-compass",
  "צלחה": "it-prospered",
  "למצפן": "to-the-compass",
  "הבכא": "the-weeping",
  "נתעצל": "we-were-lazy",
  "סקלוך": "they-stoned-you",
  "מנסיונותיך": "from-your-trials",
  "תתנשא": "you-shall-be-lifted-up",
  "תתהלל": "you-shall-boast",
  "שחצן": "arrogant",
  "תרסן": "Tirson",
  "תתפלל": "you-shall-pray",
  "סלח": "forgive",
  "צדוק": "justification",
  "מתעבים": "abominable",
  "תכחיש": "you-shall-deny",
  "מזכיר": "one-who-reminds",
  "תגדר": "you-shall-fence",
  "להתפרנס": "to-sustain-oneself",
  "תחדל": "you-shall-cease",
  "וחרק": "and-gnashing",

  // === Line 551-600 ===
  "למכנתם": "to-their-allotment",
  "אפרשנו": "I-shall-spread-it",
  "נדרשת": "is-required",
  "וחמד": "and-he-coveted",
  "נשתנים": "changing",
  "לסכן": "to-endanger",
  "המדאיג": "the-troubling",
  "אפרש": "I-shall-spread",
  "מנגד)": "from-opposite",
  "בתנאי": "on-condition",
  "חרטת": "regret-of",
  "משיבה": "returning",
  "אבדנם": "their-destruction",
  "תכחיש": "you-shall-deny",
  "נספחו": "they-were-attached",
  "להכעיס": "to-provoke",
  "יתפש": "he-shall-seize",
  "והצאצאים": "and-the-descendants",
  "והנהלת": "and-the-administration-of",
  "ובמגני": "and-with-shields-of",
  "והעמלקים׃": "and-the-Amalekites",
  "בהשאירו": "when-he-left",
  "את־כונת": "[ACC]-intention-of",
  "רפלה׃": "Riplah",
  "רפלה": "Riplah",
  "נחשפה": "was-exposed",
  "בכל־מכה׃לח.": "with-every-plague",
  "ממכות": "from-plagues",
  "מכובעיהם": "from-their-helmets",
  "משריוניהם": "from-their-armor",
  "כחובתם": "as-their-duty",
  "חבו": "they-hid",
  "תאשמו": "you-shall-be-guilty",
  "תגנו": "you-shall-defend",
  "את־כונתם": "[ACC]-their-intention",
  "כפלים": "double",
  "צדי": "sides-of",
  "את־בהלתם": "[ACC]-their-panic",
  "דמכם": "your-blood",
  "דתנו׃": "our-religion",
  "דתנו": "our-religion",
  "ולדתנו": "and-to-our-religion",
  "ונכחש": "and-we-shall-deny",
  "בדתנו": "in-our-religion",
  "ולטפנו": "and-our-children",
  "הקושר": "the-conspirator",
  "בכל־רצונכם": "with-all-your-will",
  "וחרמשו": "and-his-scythe",
  "טפנו": "our-children",
  "ננצח׃": "we-shall-prevail",

  // === Line 601-650 ===
  "ערמתכם": "your-cunning",
  "שריוניכם": "your-armor",
  "נגמר": "it-was-finished",
  "ויתפרץ": "and-he-broke-out",
  "נחשפים": "exposed",
  "החדות": "the-sharp",
  "נדקרו": "they-were-pierced",
  "תחדל": "you-shall-cease",
  "והמחלקות": "and-the-dissensions",
  "אם־יתמכו": "if-they-support",
  "במצוק": "in-distress",
  "ולהתפתות": "and-to-be-enticed",
  "את־המרידות": "[ACC]-the-rebellions",
  "באמליקיה׃": "in-Amalickiah",
  "ויחבש": "and-he-saddled",
  "ואת־מגניו": "and-[ACC]-his-shields",
  "הכריז": "he-proclaimed",
  "את־כתנתו": "[ACC]-his-tunic",
  "ונשלך": "and-was-cast-out",
  "ונזכר": "and-we-shall-remember",
  "כתנת": "tunic",
  "נרקב": "it-rotted",
  "מעציבה": "grieving",
  "ולהנהיג": "and-to-lead",
  "את־דגל": "[ACC]-banner",
  "נפוצה": "scattered",
  "כטבע": "as-is-natural",
  "בשיבה": "in-old-age",
  "את־פקדת": "[ACC]-command-of",
  "ולהכריחם": "and-to-compel-them",
  "תמכו": "they-supported",
  "ברביעית": "in-the-fourth",
  "אם־ישימהו": "if-he-places-it",
  "ישקה": "he-shall-water",
  "להקימם": "to-establish-them",
  "ויתנכר": "and-he-disguised-himself",
  "לקצף": "to-be-angry",
  "הכר": "it-was-recognized",
  "וכל־הסוררים": "and-all-the-rebels",
  "סררם": "their-rebellion",
  "השכיל": "he-acted-wisely",
  "משיג": "overtaking",
  "ובתרמית": "and-in-deceit",
  "סוללות": "ramps",
  "להקיף": "to-surround",
  "הכעיס": "he-provoked",
  "מזעזעים": "shaken",
  "שליטה": "control",
  "יטבחו": "they-shall-be-slaughtered",
  "באכזר": "cruelly",

  // === Line 651-700 ===
  "בהתחברם": "when-they-joined",
  "בעשור": "in-the-tenth",
  "הציב": "he-set-up",
  "להזיק": "to-harm",
  "האמליקיהים": "the-Amalickiahites",
  "הסוללה": "the-rampart",
  "החפיר": "the-moat",
  "נחפר": "was-dug",
  "נסחפו": "they-were-swept-away",
  "את־חפיריהם": "[ACC]-their-moats",
  "נחשפו": "they-were-exposed",
  "מגניהם": "their-shields",
  "שמיעתם": "their-hearing",
  "עד־קומת": "until-the-height-of",
  "הצופים": "the-watchmen",
  "נטתה": "it-inclined",
  "ויבצר": "and-he-fortified",
  "ההגנה": "the-defense",
  "ומשסותיהם": "and-their-plunderings",
  "וחרבנם׃": "and-their-destruction",
  "ולהתערב": "and-to-intervene",
  "הנהיגם": "he-led-them",
  "ויתנפל": "and-he-fell-upon",
  "הנהיגו": "he-led-him",
  "נפתרה": "it-was-solved",
  "נמהרת": "hasty",
  "אבדנם": "their-destruction",
  "את־הסוררים": "[ACC]-the-rebels",
  "כל־חרבנם": "all-their-destruction",
  "ולהשוותם": "and-to-level-them",
  "מן־הסוררים": "from-the-rebels",
  "הגדעם": "he-cut-them-down",
  "לדגל": "to-a-banner",
  "התגאו": "they-were-proud",
  "האצילים": "the-nobles",
  "תקנות": "regulations",
  "מבריחים": "smuggling",
  "פן־יקיצו": "lest-they-awaken",
  "כמכין": "like-one-who-prepares",
  "לפדיון": "for-redemption",
  "יבצר": "he-shall-fortify",
  "לא־הסגירו": "not-they-delivered-up",
  "רעננים׃": "flourishing",
  "להדביקם": "to-overtake-them",
  "רעננים": "flourishing",
  "להתנפל": "to-fall-upon",
  "נכנעת": "submissive",
  "להסגיר": "to-deliver-up",
  "פקדת": "command-of",
  "בחפירת": "in-the-digging-of",

  // === Line 701-750 ===
  "חריץ": "trench",
  "החריץ": "the-trench",
  "הפנימית": "the-inner",
  "מן־החריץ": "from-the-trench",
  "הכריחו": "they-compelled",
  "הכריחום": "they-compelled-them",
  "בהתקיפו": "when-he-attacked",
  "את־הסכנה": "[ACC]-the-danger",
  "בתחנוני": "with-supplications-of",
  "במצוקתם": "in-their-distress",
  "לאמץ": "to-strengthen",
  "ונכחים": "and-upright",
  "ערכת": "you-prepared",
  "המצפה": "the-watchtower",
  "אם־תסירו": "if-you-remove",
  "אם־תסוגו": "if-you-retreat",
  "ותפקדו": "and-you-shall-be-visited",
  "את־דתנו": "[ACC]-our-religion",
  "אחליף": "I-shall-exchange",
  "אחליף׃": "I-shall-exchange",
  "עשקו": "they-oppressed",
  "הזכאים": "the-innocent",
  "אסכים": "I-shall-agree",
  "רמזתם": "you-hinted",
  "נערכה": "let-us-prepare",
  "צודקת": "righteous",
  "לשחרר": "to-free",
  "להקיפם": "to-surround-them",
  "נזהרו": "they-were-careful",
  "לאנטיפוס": "to-Antipus",
  "ואצרף": "and-I-joined",
  "משמידים": "destroying",
  "להתגונן׃": "to-defend-oneself",
  "תוחלתנו׃": "our-hope",
  "את־קבלת": "[ACC]-receiving-of",
  "המשכנו": "we-delayed",
  "פן־יקפו": "lest-they-surround",
  "פן־ישיגוני": "lest-they-overtake-me",
  "משיגים": "overtaking",
  "ואצרפם": "and-I-joined-them",
  "להחליף": "to-exchange",
  "לבצרן": "to-fortify-them",
  "להצטרף": "to-join",
  "הצב": "was-set-up",
  "אמצו": "be-strong",
  "נאלצנו": "we-were-forced",
  "התפרצו": "they-broke-out",
  "ובמקלות": "and-with-staves",
  "שלופה": "drawn",
  "לחרץ": "to-decide",

  // === Line 751-800 ===
  "חרצנו": "we-decided",
  "שאלנום": "we-asked-them",
  "חתו׃": "they-were-terrified",
  "בדקדוק": "carefully",
  "את־הנצחון": "[ACC]-the-victory",
  "ינצל": "he-shall-be-rescued",
  "טפלנו": "we-cared-for",
  "פרצו": "they-broke-through",
  "בגדודינו": "in-our-troops",
  "העזנו": "we-dared",
  "ונחכה": "and-we-waited",
  "נסבותינו": "our-circumstances",
  "חכינו": "we-waited",
  "התעצבנו": "we-were-grieved",
  "שפכנו": "we-shed",
  "וניתחזק": "and-we-strengthened-ourselves",
  "וניתאמץ": "and-we-were-encouraged",
  "פן־נכרית": "lest-we-be-cut-off",
  "מסתורם": "their-hiding-place",
  "להמשך": "to-continue",
  "ומשכתם": "and-you-drew-them",
  "חלשת": "weakness-of",
  "תמכם": "their-support",
  "וחררנו": "and-we-burned-them",
  "חשו": "they-hurried",
  "ולנהל": "and-to-manage",
  "חרצה": "she-decided",
  "פרצה": "she-broke-through",
  "נשיב": "we-shall-return",
  "ותשתדלו": "and-you-shall-strive",
  "מחכה": "waiting",
  "לעכב": "to-delay",
  "ותתחזקו": "and-you-shall-be-strengthened",
  "והכפלה": "and-it-was-doubled",
  "תדבקו": "you-shall-cling",
  "תתעצב": "you-shall-be-grieved",
  "יכבשו": "they-shall-conquer",
  "חררנו": "we-burned-them",
  "השעבוד": "the-bondage",
  "נתקוממה": "let-us-rise-up",
  "לנהל": "to-manage",
  "בשעבוד׃": "in-bondage",
  "השאירו": "they-left",
  "נחרצו": "they-were-determined",
  "בחשכת": "in-the-darkness-of",
  "ובסלמותיהם": "and-with-their-ladders",
  "והארכה": "and-the-healing",
  "רככו": "they-softened",
  "הנתונים": "the-given",
  "התרשלו": "they-were-negligent",

  // === Line 801-850 ===
  "הצואר": "the-neck",
  "הפליגה": "she-sailed",
  "צזורם׃": "Cezoram",
  "מן־הבוחרים": "from-the-voters",
  "להשלט": "to-rule",
  "תזכו": "you-shall-be-worthy",
  "את־מוסדכם": "[ACC]-your-foundation",
  "הממו": "they-were-confused",
  "שמונת": "eight-of",
  "שרפתם": "their-burning",
  "ויחדר": "and-he-penetrated",
  "זהרו": "they-shone",
  "הסבו": "they-turned",
  "לבטאה": "to-express-it",
  "כלחישה": "like-a-whisper",
  "ולמכר": "and-to-sell",
  "משכילים": "wise-ones",
  "מפשתן": "from-linen",
  "שזור": "woven",
  "מהשיכים": "from-those-belonging",
  "מן־הרשומות": "from-the-records",
  "מחולל": "causing",
  "צדו": "they-hunted",
  "הצנועים׃": "the-humble",
  "והסמכות": "and-the-authority",
  "מרשיעים": "condemning",
  "ויתנפח": "and-he-was-puffed-up",
  "אל־השוק": "to-the-market",
  "בגנו": "in-his-garden",
  "ומשתוממים": "and-being-astonished",
  "לפתויי": "to-enticements-of",
  "יפיצכם": "he-shall-scatter-you",
  "ותשדדו": "and-you-shall-plunder",
  "ומקשיבים": "and-listening",
  "והתחברתם": "and-you-joined",
  "הגביהה": "she-raised-high",
  "תתפשו": "you-shall-be-seized",
  "תלקחנה": "they-shall-be-taken",
  "תכחישו": "you-shall-deny",
  "נדקר": "he-was-pierced",
  "לספד": "to-mourn",
  "בקבורת": "in-the-burial-of",
  "ונשתומם": "and-we-were-astonished",
  "מתמיהתנו": "from-our-astonishment",
  "יתנשא": "he-shall-exalt-himself",
  "הקבורה": "the-burial",
  "יתפש": "he-shall-be-seized",
  "קשור": "bound",
  "בהסכם": "in-agreement",
  "ולספד": "and-to-mourn",

  // === Line 851-900 ===
  "סאנטום": "Seantum",
  "רצחת": "you-murdered",
  "תבדקו": "you-shall-examine",
  "הכחיש": "he-denied",
  "השתפל": "he-humbled-himself",
  "פן־יתקימו": "lest-they-be-fulfilled",
  "וישכך": "and-it-shall-subside",
  "ותשבית": "and-you-shall-cause-to-cease",
  "ודגנה": "and-its-grain",
  "תשבת": "it-shall-cease",
  "מגפת": "plague-of",
  "תקשיב": "you-shall-listen",
  "דגנה": "its-grain",
  "לצלח": "to-prosper",
  "כסו": "they-covered",
  "מהסוררים": "from-the-rebels",
  "ויתחבאו": "and-they-hid-themselves",
  "את־תנודת": "[ACC]-shaking-of",
  "ובחתה": "and-in-terror",
  "ימשל": "he-shall-rule",
  "פחותים": "governors",
  "אם־יטמן": "if-he-hides",
  "והפכתי": "and-I-shall-overturn",
  "הגמורה": "the-complete",
  "כל־הטומן": "all-who-hides",
  "ויטמנם": "and-he-shall-hide-them",
  "לא־נמשך": "not-it-continued",
  "ולהתנפח": "and-to-be-puffed-up",
  "ותהרגום": "and-you-shall-kill-them",
  "ותגרשוהו": "and-you-shall-drive-him-out",
  "ומכספכם": "and-from-your-silver",
  "נצת": "it-was-kindled",
  "תבכו": "you-shall-weep",
  "תספדו": "you-shall-mourn",
  "רגמתי": "I-stoned",
  "מטמונינו": "our-treasures",
  "חמקו": "they-slipped-away",
  "את־זריחת": "[ACC]-sunrise-of",
  "תשתוממו": "you-shall-be-astonished",
  "ותגרשוני": "and-you-drove-me-out",
  "בסדקים": "in-cracks",
  "כבקעה": "like-a-valley",
  "תשברנה": "they-shall-be-broken",
  "תכבדנה": "they-shall-be-heavy",
  "תוכלנה": "they-shall-be-able",
  "תרמסנה": "they-shall-be-trampled",
  "ותעזבנה": "and-they-shall-be-abandoned",
  "להרמס": "to-be-trampled",
  "בהאמינם": "when-they-believed",
  "התקימו": "they-were-fulfilled",

  // === Line 901-950 ===
  "במסורות": "in-traditions",
  "כצהרים": "like-noon",
  "ותזרח": "and-it-shone",
  "כזבים": "liars",
  "להדיח": "to-lead-astray",
  "זמנם": "their-time",
  "תנצח": "it-shall-prevail",
  "לשלומכם": "for-your-peace",
  "הנדיבה": "the-generous",
  "ושתפינו": "and-our-partners",
  "יחשכו": "they-shall-be-darkened",
  "להציב": "to-set-up",
  "נתמנה": "was-appointed",
  "חלילה": "far-be-it",
  "ויבצרו": "and-they-fortified",
  "ובצנה": "and-with-a-shield",
  "הטבח": "the-slaughter",
  "נרדף": "was-pursued",
  "הושג": "was-overtaken",
  "מדתו": "his-measure",
  "החיצנים": "the-outer-ones",
  "אצרו׃": "they-stored",
  "בשיר": "in-a-song",
  "פקפק": "he-doubted",
  "ונענשו": "and-they-were-punished",
  "נחרת": "was-engraved",
  "תלמיד": "disciple",
  "מן־החשבונות": "from-the-accounts",
  "וצאצא": "and-descendant",
  "והממנים": "and-the-appointed-ones",
  "למנהיגים": "to-leaders",
  "ובהתפארות": "and-in-boasting",
  "להתפרק": "to-come-apart",
  "ולנפחם": "and-to-inflate-them",
  "נהנו": "they-enjoyed",
  "ונהלה": "and-she-was-led",
  "ולחלץ": "and-to-rescue",
  "מנהיג": "leader",
  "ככלב": "like-a-dog",
  "וכחזירה": "and-like-a-sow",
  "ברפש": "in-mire",
  "על־הגדוד": "upon-the-troop",
  "מהשג": "from-being-overtaken",
  "בהתעצבו": "when-he-was-grieved",
  "נרגם": "he-was-stoned",
  "זמננו": "our-time",
  "להבקע׃": "to-be-split",
  "חדים": "sharp",
  "ותשקע": "and-it-sank",
  "שברן": "their-breaking",

  // === Line 951-1000 ===
  "ובסדקים": "and-in-cracks",
  "בכשלש": "in-about-three",
  "למש": "to-depart",
  "להדליק": "to-kindle",
  "ורגמנו": "and-we-stoned",
  "ישחק": "he-shall-laugh",
  "הטבעתי׃": "I-immersed",
  "גמגמנו": "we-stammered",
  "שרפתים": "I-burned-them",
  "וברגמם": "and-when-they-stoned-them",
  "תסתרנה": "they-shall-be-hidden",
  "תקריבו": "you-shall-offer",
  "זבחיכם": "your-sacrifices",
  "מלקונן": "from-lamenting",
  "צאצאי": "descendants-of",
  "ותחדל": "and-it-ceased",
  "מלהבקע": "from-being-split",
  "והאנחות": "and-the-groanings",
  "רגמום": "they-stoned-them",
  "בסופה": "in-a-storm",
  "יחקר": "he-shall-investigate",
  "ובפתחון": "and-with-opening-of",
  "על־שרתו": "upon-his-ministry",
  "המרור": "the-bitter",
  "תמשו": "you-shall-depart",
  "וכל־הבונה": "and-all-who-builds",
  "ינחמו׃": "they-shall-be-comforted",
  "הרחמנים": "the-merciful",
  "יחרפו": "they-shall-revile",
  "מלח": "salt",
  "תמלח": "it-shall-be-salted",
  "על־המנורה": "upon-the-lampstand",
  "המועצה": "the-council",
  "מסכים": "agreeing",
  "פן־יתפשך": "lest-he-seize-you",
  "את־הסנין": "[ACC]-the-Senine",
  "כל־המביט": "all-who-looks",
  "לחמד": "to-covet",
  "להתנכר": "to-disguise-oneself",
  "את־צלבכם": "[ACC]-your-cross",
  "כל־המשלח": "all-who-sends-away",
  "כל־המשלח": "all-who-sends-away",
  "את־הגרושה": "[ACC]-the-divorced-woman",
  "אל־תתקוממו": "do-not-resist",
  "את־כתנתך": "[ACC]-your-tunic",
  "וכל־המכריח": "and-all-who-compels",

  // === Line 997-1050 ===
  "המלעיבים": "the-scorners",
  "והרדפים": "and-the-persecutors",
  "מזריח": "causing-to-shine",
  "אל־תחצרו": "do-not-trumpet",
  "בחצצרה": "with-a-trumpet",
  "השוקים": "the-markets",
  "אל־תרבו": "do-not-multiply",
  "אל־תדמו": "do-not-imagine",
  "יתקדש": "it-shall-be-sanctified",
  "רצונך": "your-will",
  "וסלח": "and-forgive",
  "סלחנו": "we-have-forgiven",
  "בצומכם": "when-you-fast",
  "צמים": "fasting",
  "בצומך": "when-you-fast",
  "אצרו": "store-up",
  "ואת־הממון׃": "and-[ACC]-the-riches",
  "ומה־תשתו": "and-what-shall-you-drink",
  "לגופכם": "for-your-body",
  "לאסמים": "to-the-granaries",
  "מכלכל": "sustaining",
  "תדאגו": "you-shall-worry",
  "מלביש": "clothing",
  "את־חציר": "[ACC]-grass",
  "לתנור": "to-the-furnace",
  "ובמדה": "and-with-the-measure",
  "תמדו": "you-shall-measure",
  "ואל־תשליכו": "and-do-not-cast",
  "החזירים": "the-swine",
  "טרפים׃": "tearing",
  "היבצרו": "are-they-gathered",
  "מצנים": "from-thorns",
  "מדרדרים": "from-thistles",
  "הנפוץ": "the-widespread",
  "לשריקה": "for-a-hissing",
  "כמלח": "like-salt",
  "ולהרמס": "and-to-be-trampled",
  "צלעים": "lame",
  "מצרעים": "lepers",
  "נכמרו": "were-moved-with-compassion",
  "ופסחיהם": "and-their-lame",
  "רחצו": "they-washed",
  "נעכרתי": "I-was-troubled",
  "את־הטף": "[ACC]-the-children",
  "לפרס": "to-break",
  "פרסתי": "I-broke",
  "פחות": "governors",
  "וינשבו": "and-they-blew",
  "כחטים׃": "like-wheat",
  "באמינכם": "when-you-believe",
  "תתקבצו": "you-shall-gather",
  "תגרשום": "you-shall-drive-them-out",
  "תחושו": "you-shall-hasten",
  "וכל־המפר": "and-all-who-violates",

  // === Line 1051-1100 ===
  "חרם": "destruction",
  "אם־תשרתוהו": "if-you-serve-him",
  "ותשרתוהו": "and-you-shall-serve-him",
  "בהתכסותם": "when-they-covered-themselves",
  "ושמנון": "and-fatness",
  "הכריעו": "they-bowed-down",
  "כלבנם׃": "as-their-whiteness",
  "טהרת": "you-purified",
  "אתכבד": "I-shall-be-honored",
  "תצמא": "you-shall-thirst",
  "השארויות": "the-remnants",
  "פזרו": "they-scattered",
  "לגרן׃": "to-the-threshing-floor",
  "קרנך": "your-horn",
  "והחרמתי": "and-I-shall-devote-to-destruction",
  "תתלה": "it-shall-be-hung",
  "יקבצם": "he-shall-gather-them",
  "יפצחו": "they-shall-break-forth",
  "תלכון": "you-shall-go",
  "ומאספכם": "and-your-gatherer",
  "בגללם": "because-of-them",
  "ארפאהו": "I-shall-heal-him",
  "מערמת": "from-cunning-of",
  "ככפיר": "like-a-young-lion",
  "מרכבותיך׃": "your-chariots",
  "ונתשתי": "and-I-shall-uproot",
  "אכרית": "I-shall-cut-off",
  "וחמה": "and-wrath",
  "מאספם׃": "their-gatherer",
  "פצחי": "break-forth",
  "בני־שוממה": "sons-of-desolation",
  "משכנותיך": "your-dwellings",
  "אל־תחשכי": "do-not-hold-back",
  "כי־ימין": "for-right",
  "תפרצי": "you-shall-break-forth",
  "ואל־תכלמי": "and-do-not-be-ashamed",
  "תחפירי": "you-shall-be-ashamed",
  "תשכחי": "you-shall-forget",
  "אקבצך׃": "I-shall-gather-you",
  "בשצף": "in-an-overflow-of",
  "קצף": "wrath",
  "רחמתיך": "I-had-compassion-on-you",
  "מקצף": "from-wrath",
  "מרחמך": "your-compassionate-one",
  "בספירים׃": "with-sapphires",
  "כדכד": "agate",
  "חלוניך": "your-windows",
  "מעשק": "from-oppression",
  "למענך׃": "for-your-sake",
  "נפח": "one-who-blows",

  // === Line 1101-1147 ===
  "פחם": "coals",
  "תרשיעי": "you-shall-condemn",
  "וכל־המקשיב": "and-all-who-listens",
  "נשלמו׃": "they-were-completed",
  "מכבסים׃": "fullers",
  "קדמוניות׃": "ancient-things",
  "במכשפים": "against-sorcerers",
  "ובמנאפים": "and-against-adulterers",
  "את־השכיר": "[ACC]-the-hired-worker",
  "ואת־היתום": "and-[ACC]-the-orphan",
  "נכליתם׃": "you-were-consumed",
  "גזלנוך": "we-have-robbed-you",
  "במעשרות": "in-the-tithes",
  "ובחנוני": "and-test-me",
  "אפתח": "I-shall-open",
  "את־חלוני": "[ACC]-windows-of",
  "תשכל": "it-shall-devour",
  "גפנכם": "your-vine",
  "והקשיב": "and-he-listened",
  "ותבחינו": "and-you-shall-discern",
  "כתנור": "like-a-furnace",
  "יזרח": "it-shall-shine",
  "חרם׃": "destruction",
  "מקבילים": "parallel",
  "לחת": "tablets",
  "לבחן": "to-test",
  "אבחן": "I-shall-test",
  "שלושה": "three",
  "ואת־פסחיהם": "and-[ACC]-their-lame",
  "ויפקח": "and-he-opened",
  "רצוננו": "our-will",
  "נבניתם": "you-were-built",
  "כבסו": "they-washed",
  "השואל": "the-one-who-asks",
  "מתעצב": "being-grieved",
  "מה־תחפצו": "what-do-you-desire",
  "תטעמו": "you-shall-taste",
  "תהפכו": "you-shall-be-overturned",
  "כההפכם": "like-their-overturning",
  "ההפכם": "their-overturning",
  "בהטפתם": "in-their-preaching",
  "ובמצב": "and-in-the-situation",
  "ואל־תדמו": "and-do-not-imagine",
  "אם־תבוזו": "if-you-despise",
  "ברפואות": "with-healings",
  "להסב": "to-turn",
  "מצרית": "Egyptian"
};

// ============================================================
// NORMALIZE DICTIONARY: strip niqqud/sof-pasuq from all keys
// This ensures keys match regardless of cantillation or sof-pasuq
// ============================================================

const normalizedDict = {};
for (const [key, value] of Object.entries(hebrewToEnglish)) {
  const normalizedKey = stripNiqqud(key);
  normalizedDict[normalizedKey] = value;
}

// ============================================================
// SECONDARY: Direct bad-gloss -> good-gloss mapping
// This serves as a fallback if the Hebrew key lookup fails
// due to any consonant skeleton discrepancies
// ============================================================

const badGlossToGood = {
  "Ohkhnh": "and-the-priesthood",
  "Vvtot": "in-cords",
  "Vkdcht": "with-fever",
  "Hmrot": "the-events",
  "Ktsirm": "their-harvest",
  "Bhrigt": "in-the-killing-of",
  "Obshdidtm": "and-in-their-plundering",
  "Hmpitsim": "the-scatterers",
  "Bmklot": "with-staves",
  "Ktstso": "they-were-cut-off",
  "Lshomo": "to-place-it",
  "Lhlnn": "to-murmur",
  "Hkhkhr": "the-plain",
  "Otktsf": "and-she-was-angry",
  "Hsgiro": "they-delivered-up",
  "Mridtm": "their-rebellion",
  "Ktmino": "our-stains",
  "Nkhtm": "is-stained",
  "Zhrim": "shining",
  "Tspo": "they-floated",
  "Nhll": "we-shall-praise",
  "Nthll": "we-shall-boast",
  "Onshmidm": "and-we-shall-destroy-them",
  "Mtvlim": "mourning",
  "Btchonm": "their-confidence",
  "Lgzl": "to-rob",
  "Tkhh": "she-shall-be-struck",
  "Ksgim": "like-dross",
  "Ltfch": "to-swell",
  "Omtchil": "and-beginning",
  "Ttpchoho": "you-shall-nurture-it",
  "Ttpcho": "you-shall-nurture",
  "Tsomch": "growing",
  "Dchitm": "you-rejected",
  "Bnsionot": "in-trials",
  "Zhrm": "their-brightness",
  "Tstir": "you-shall-hide",
  "Lhfil": "to-activate",
  "Hkshib": "he-listened",
  "Mrshi": "condemning",
  "Trvt": "mixture",
  "Ochrmshotihm": "and-their-scythes",
  "Shrionihm": "their-armor",
  "Tmsro": "you-shall-deliver",
  "Lhkhchd": "to-be-destroyed",
  "Ikchdo": "they-shall-be-destroyed",
  "Hktspim": "the-angry-ones",
  "Ibrkm": "he-shall-bless-them",
  "Mhmlikihim": "from-the-Amalickiahites",
  "Ltkopt": "to-the-period-of",
  "Bngod": "in-opposition",
  "Hrpim": "the-weak-ones",
  "Itgbro": "they-shall-prevail",
  "Btchon": "confidence",
  "Chzt": "possession-of",
  "Chmh": "wrath",
  "Lhkrich": "to-compel",
  "Lhtkipm": "to-attack-them",
  "Hshir": "he-left",
  "Lhmir": "to-exchange",
  "Nshtkro": "they-became-drunk",
  "Hkpno": "we-surrounded",
  "Mtmiktm": "from-their-support",
  "Bmtsok": "in-distress",
  "Hgdod": "the-troop",
  "Chrrm": "their-burning",
  "Zivtkhm": "your-abandonment",
  "Ntkomm": "we-shall-rise-up",
  "Hkpo": "they-were-surrounded",
  "Tszorm": "Cezoram",
  "Lklbim": "to-the-dogs",
  "Tlkchnh": "they-shall-be-taken",
  "all-Hmbytym": "all-the-lookers",
  "Rtsno": "we-ran",
  "Throtsch": "[ACC]-the-murderer",
  "Shchrro": "they-were-freed",
  "Hskmti": "I-agreed",
  "Chronk": "your-wrath",
  "Lshkhch": "to-forget",
  "Mtbil": "one-who-immerses",
  "Ohmrmot": "and-the-deceits",
  "Tvch": "slaughter",
  "Pchot": "governors",
  "Kbrti": "I-buried",
  "Tmkhot": "[ACC]-plagues-of",
  "Hmsmrim": "the-nails",
  "Hmlch": "the-salt",
  "Tchptso": "you-shall-desire",
  "Nshlmo": "they-were-completed",
  "Ichtro": "they-shall-dig",
  "Dpko": "they-knocked",
  "Shchit": "I-shall-destroy",
  "and-if-Tzkrvny": "and-if-you-remember-me",
  "Tgrshoho": "you-shall-drive-him-out",
  "Onbrko": "and-they-were-blessed",
  "Ikptso": "they-shall-leap",
  "Mtsrf": "refiner",
  "the-Church-of": "the-church-of",
  "Chris": "Christ",
  "Htsponit": "the-northern",
  "Vnmoron": "son-of-Moron",
  "Vnchch": "son-of-Ahah",
  "Ochch": "and-Ahah",
  "Vnsht": "son-of-Seth",
  "Vnshvlon": "son-of-Shiblon",
  "Vnliv": "son-of-Lib",
  "Vnkish": "son-of-Kish",
  "Vnkhorom": "son-of-Corom",
  "Vnloi": "son-of-Levi",
  "Vnkim": "son-of-Kim",
  "Vnshz": "son-of-Shez",
  "Vncht": "son-of-Heth",
  "Vnkiv": "son-of-Kib",
  "Nirshnh": "we-shall-inherit-it",
  "Dsrt": "Deseret",
  "Dvsh": "honey",
  "Otchtitn": "and-their-bottom",
  "Mchddot": "pointed",
  "Orkhn": "and-their-length",
  "Odltn": "and-their-door",
  "Khkrh": "like-a-dish",
  "Nnhig": "we-shall-lead",
  "Chlonot": "windows",
  "Ishtpo": "they-shall-flood",
  "Vhvlkhm": "when-you-are-swallowed",
  "Zkhh": "pure",
  "lest-Ykny": "lest-he-strike-me",
  "Lvsh": "I-shall-wear",
  "Npdit": "you-were-redeemed",
  "Nvrt": "you-were-created",
  "Btslmi": "in-my-image",
  "Khvd": "I-shall-honor",
  "Ttsfn": "you-shall-hide",
  "Lhrotn": "to-show-them",
  "Lhtminm": "to-hide-them",
  "Tftronm": "[ACC]-their-interpretation",
  "Itkdsho": "they-shall-be-sanctified",
  "Frsh": "I-shall-spread",
  "Hmdrik": "the-guide",
  "Htmonh": "the-hidden-one",
  "Tsfn": "he-hid",
  "Tmskh": "[ACC]-curtain",
  "Iprsho": "they-shall-spread",
  "Zkroni": "my-memorial",
  "Tptro": "you-shall-interpret",
  "to-Spynvtyhm": "to-their-ships",
  "Khtvt": "inscription-of",
  "Mfltst": "horror",
  "upon-Chvpy": "upon-the-shores-of",
  "Oglgh": "and-Gilgal",
  "Nkhilh": "let-us-assemble",
  "Tkhorihor": "[ACC]-Korihor",
  "Tkhohor": "[ACC]-Cohor",
  "Oitgnbo": "and-they-stole-away",
  "son-of-Kmnvr": "son-of-Kimnor",
  "Otrkd": "and-she-danced",
  "Itpshto": "they-shall-spread",
  "upon-Bvnyh": "upon-its-builders",
  "all-Hbvnh": "all-who-builds",
  "if-Ydrkv": "if-they-are-guided",
  "Nmshch": "he-was-anointed",
  "Prisht": "spreading-of",
  "Hkhilo": "they-fed-him",
  "Mshko": "they-drew",
  "Tkhom": "[ACC]-Com",
  "Lchvk": "to-embrace",
  "Kdmoniot": "ancient-things",
  "Vrsm": "with-their-poison",
  "if-Ygdv": "if-they-declare",
  "Trflkish": "[ACC]-Riplakish",
  "Tsrf": "he-refined",
  "Bznotio": "in-his-harlotry",
  "Tkhorom": "[ACC]-Corom",
  "also-Kysh": "also-Kish",
  "Ichtsts": "he-shall-divide",
  "Nmrtsim": "vigorous",
  "Oichpro": "and-they-dug",
  "Omtslch": "and-prosperous",
  "Lmchsh": "for-shelter",
  "Lhtsr": "to-be-stopped",
  "do-not-Trybv": "do-not-contend",
  "Lhshttf": "to-participate",
  "Olhshttf": "and-to-participate",
  "Chzo": "they-beheld",
  "Onkshl": "and-stumbling",
  "Bshimt": "in-placing",
  "Itlotstso": "they-shall-mock",
  "Tsrin": "Zerin",
  "Tvchnm": "you-shall-test-them",
  "Vdmkhm": "by-your-blood",
  "Pshoth": "simple",
  "Rchtso": "they-were-washed",
  "Pzro": "they-were-scattered",
  "Oisttr": "and-he-hid-himself",
  "Vhlchmm": "when-they-fought",
  "Hrviit": "the-fourth",
  "Chshlon": "Cheshlon",
  "Glgl": "Gilgal",
  "if-Ynych": "if-he-shall-allow",
  "Mgdot": "from-bundles",
  "Dchk": "he-pressed",
  "Orkhh": "and-healing",
  "Mshirim": "leaving",
  "Shtochim": "flat",
  "Hpgrim": "the-corpses",
  "Lvdnm": "to-their-destruction",
  "Bshopr": "with-a-shofar",
  "Htrf": "he-was-healed",
  "Lhtnchm": "to-be-comforted",
  "Ottvl": "and-she-mourned",
  "Ohrgkh": "and-I-shall-kill-you",
  "Htro": "they-were-stirred-up",
  "Thrshomot": "[ACC]-the-records",
  "Mhgot": "from-meditations",
  "Shkori": "drunkards-of",
  "Shkor": "drunk",
  "Obmgnihm": "and-with-their-shields",
  "Htlf": "he-fainted",
  "Nshn": "he-leaned",
  "Trshomto": "[ACC]-his-record",
  "Oitmnm": "and-he-hid-them",
  "if-Yklklv": "if-they-shall-sustain",
  "Shmt": "you-are-guilty",
  "Shfkht": "you-shed",
  "Mhtfsht": "from-spreading",
  "Oitnkro": "and-they-disguised-themselves",
  "Lshdd": "to-plunder",
  "Vgrof": "with-a-fist",
  "and-unless-Nmvt": "and-not-moved",
  "not-Hchshyb": "not-he-regarded",
  "from-Hlvmd": "from-the-learner",
  "all-Tsrkyhm": "all-their-needs",
  "Htmkro": "they-sold-themselves",
  "Oishddo": "and-they-plundered",
  "Tzkhoiot": "[ACC]-rights",
  "Vmlisim": "among-the-Amlicites",
  "Nmhr": "let-us-hurry",
  "Ntchzko": "they-strengthened-themselves",
  "Tfgri": "[ACC]-corpses-of",
  "Chrmonts": "Hermounts",
  "Glcho": "they-shaved",
  "Khhh": "dim",
  "Orchmtim": "and-I-had-compassion-on-them",
  "Lsmn": "to-mark",
  "Tchol": "it-shall-fall-upon",
  "Nlchmh": "let-us-fight",
  "Zrhmlhfrk": "Zarahemla-chapter",
  "Httsvo": "they-were-grieved",
  "Mtnshim": "being-lifted-up",
  "Mshpilim": "humbling",
  "Chkhh": "he-waited",
  "Otrchbnh": "and-they-widened",
  "Tslmo": "his-image",
  "Lkhzv": "to-lie",
  "Otslm": "and-image",
  "Nkbso": "they-were-washed",
  "what-Yrgsh": "what-he-feels",
  "Hrgshtm": "you-felt",
  "Hhthlkhtm": "did-you-walk",
  "Hmlig": "the-mocker",
  "Hmtnpchim": "the-puffed-up",
  "all-Hmkchysh": "all-who-deny",
  "Lhtnfch": "to-be-puffed-up",
  "Hmshpilim": "the-humble-ones",
  "if-Tdbrv": "if-you-speak",
  "Ovchronh": "and-at-the-last",
  "Shtpim": "partners",
  "Bmbokh": "in-confusion",
  "Ttspo": "you-shall-watch",
  "Chshob": "important",
  "Tkhsh": "it-shall-be-covered",
  "Tthro": "you-shall-be-purified",
  "Rtsonkm": "your-will",
  "Klklot": "crooked",
  "Ntkvltm": "you-were-received",
  "all-Tsrkykm": "all-your-needs",
  "Lchronh": "at-the-last",
  "Oichrpo": "and-they-reviled",
  "Kvlt": "you-received",
  "Otdrsh": "and-she-shall-seek",
  "if-Grshvny": "if-they-drove-me-out",
  "Hkhltni": "you-fed-me",
  "Otsfni": "and-you-gathered-me",
  "Bzkim": "in-chains",
  "Ntsoiti": "I-was-commanded",
  "Nnhgo": "they-were-led",
  "Ohshkchtm": "and-you-forgot",
  "Ntmt": "it-was-confirmed",
  "Ngrm": "was-caused",
  "Tmro": "you-shall-rebel",
  "Iktsr": "he-shall-reap",
  "Lkchtni": "to-take-me",
  "son-of-Gdvnh": "son-of-Giddonah",
  "Rkshti": "I-acquired",
  "Shgiti": "I-erred",
  "Tkhil": "you-shall-feed",
  "Tknisho": "you-shall-bring-him-in",
  "Imshl": "he-shall-rule",
  "Nchmltm": "you-had-compassion",
  "that-Yshh": "that-he-lends",
  "Shtrim": "officers",
  "Ipsht": "it-shall-be-spread",
  "Okshdd": "and-like-a-plunderer",
  "Lrkhm": "to-their-value",
  "Mddo": "they-measured",
  "Omdtm": "and-their-measure",
  "Olmnh": "and-a-lemanah",
  "Msninh": "a-seninah",
  "Lmnh": "a-lemanah",
  "Shblonim": "shiblons",
  "Tnsni": "you-shall-test-me",
  "Chshvt": "you-thought",
  "Olnkbh": "and-to-a-female",
  "Mtchdim": "uniting",
  "Ntfsht": "you-were-caught",
  "Khrmt": "like-a-heap-of",
  "Tshimm": "you-shall-place-them",
  "Bshrshrotio": "in-his-chains",
  "Isrkhm": "he-shall-bind-you",
  "Shrshrot": "chains",
  "Hmkinh": "the-preparing",
  "Lnpotsim": "to-the-scattered",
  "Nshgh": "we-erred",
  "Krmno": "our-vineyard",
  "Mchkim": "waiting",
  "Otshliko": "and-you-shall-cast-out",
  "not-Tvrydv": "not-you-shall-bring-down",
  "Nkchot": "right-things",
  "Vnkhch": "in-the-presence-of",
  "Lhlft": "to-be-turned",
  "Lrgm": "to-stone",
  "Hshrfh": "the-burning",
  "Tsrtni": "you-detained-me",
  "Ngmrh": "it-was-finished",
  "Hshotrim": "the-officers",
  "Lhsgirkm": "to-deliver-you-up",
  "Ttsilo": "you-shall-rescue",
  "Chrkim": "gnashing",
  "Pshto": "they-spread",
  "Onntsl": "and-we-shall-be-saved",
  "and-not-Nzvkv": "and-not-they-were-harmed",
  "Onrgmo": "and-they-were-stoned",
  "Lhtsrv": "to-be-scorched",
  "Lmdt": "you-taught",
  "Ohpgrim": "and-the-corpses",
  "Ntrpo": "they-were-devoured",
  "Bksoi": "in-covering",
  "Mskh": "curtain",
  "Hkpirh": "the-denial",
  "do-not-Tkbrhv": "do-not-bury-him",
  "Htmini": "do-you-believe",
  "Nshfkht": "is-poured-out",
  "Nkhvsh": "was-conquered",
  "Otttsv": "and-she-was-grieved",
  "Lhkimh": "to-establish-it",
  "Omrkbotio": "and-his-chariots",
  "Hkhzv": "the-lie",
  "Mhkhiso": "from-provoking-him",
  "Shhh": "he-delayed",
  "Khzv": "a-lie",
  "Obkzbihm": "and-in-their-lies",
  "Lhshtmsh": "to-use",
  "Khkh": "I-shall-smite-you",
  "Tktsf": "you-shall-be-angry",
  "Llgo": "to-mock-him",
  "Oishkdo": "and-they-were-diligent",
  "Tshrtoni": "you-shall-serve-me",
  "Mmdoni": "from-Middoni",
  "Btslmo": "in-his-image",
  "Hshttch": "he-prostrated",
  "Kmpilim": "like-those-who-cause-to-fall",
  "Ttsoi": "you-shall-command",
  "Vrtsot": "with-a-strap",
  "Hbtlnim": "the-idle-ones",
  "Otgbl": "and-she-bordered",
  "Noshbt": "inhabited",
  "Mkpot": "surrounded",
  "Vmnr": "in-Omner",
  "Bhmni": "in-Himni",
  "Ishddo": "they-shall-plunder",
  "Bdrshotihm": "in-their-preachings",
  "Shmnilom": "Shimnilom",
  "Lhtgonn": "to-defend-oneself",
  "Nokchno": "we-were-present",
  "Slch": "forgive",
  "Ktmno": "our-stains",
  "Ntsfn": "we-shall-hide",
  "Ntmnm": "we-shall-hide-them",
  "Ntmn": "we-shall-hide",
  "Ntlnom": "we-carried-them",
  "Ishkbo": "they-shall-lie-down",
  "Hmtchbrim": "the-ones-joining",
  "Ntsodim": "being-hunted",
  "Ndpo": "they-were-driven",
  "Hchitsonim": "the-outer-ones",
  "Gdrt": "fence-of",
  "Otktsro": "and-you-reaped",
  "Hsmim": "the-granaries",
  "Ischpo": "they-shall-be-swept-away",
  "Hktsir": "the-harvest",
  "Lhthll": "to-boast",
  "Gdsh": "he-heaped",
  "Hsgirno": "he-delivered-us-up",
  "Vshgit": "in-the-error-of",
  "Onsht": "and-we-were-weakened",
  "Mchsor": "lack",
  "Brchobotihm": "in-their-streets",
  "Onsklno": "and-we-were-stoned",
  "Nkvtsh": "let-us-gather",
  "Onbtch": "and-we-shall-trust",
  "Ikchnh": "he-shall-take-it",
  "Chrmsh": "scythe",
  "Hmsfd": "the-mourning",
  "Nrkbim": "rotting",
  "Vmshlti": "in-my-request",
  "Lhrgiz": "to-provoke",
  "Gzrt": "decree-of",
  "Vmshloti": "in-my-requests",
  "Ichlk": "he-shall-divide",
  "Khhfrdh": "when-it-parted",
  "Ttsmdo": "you-shall-cling",
  "Tchko": "you-shall-wait",
  "Othpkt": "and-perversity",
  "Mtslich": "prosperous",
  "Ktso": "his-end",
  "Lhpsik": "to-stop",
  "Lhnot": "to-enjoy",
  "Hshtrim": "the-officers",
  "Bholkt": "in-the-conduct-of",
  "Ttngd": "you-shall-oppose",
  "Mkhchsh": "denying",
  "Hnshkhcht": "have-you-forgotten",
  "Rtsit": "you-desired",
  "Hrtsit": "did-you-desire",
  "Httokch": "will-you-argue",
  "Ondrk": "and-it-was-trodden",
  "Igrrm": "he-shall-drag-them",
  "Hfrd": "separate",
  "Gvlh": "she-bordered",
  "Lhnchot": "to-guide",
  "Hmni": "Himni",
  "Zzrom": "Zeezrom",
  "Hvdlt": "you-separated",
  "Vtsmn": "by-themselves",
  "Vtsmh": "by-herself",
  "Hdichm": "he-led-them-astray",
  "Ngnbo": "they-were-stolen",
  "Mnpchim": "puffed-up",
  "Otsmdihm": "and-their-yokes",
  "Hshgich": "he-watched-over",
  "Nbzitm": "you-were-despised",
  "Bhkrcho": "when-he-was-compelled",
  "Bgrgir": "in-a-seed",
  "Ndmh": "we-shall-compare",
  "Tzroho": "you-shall-sow-it",
  "Chzkhm": "your-vision",
  "Htpichh": "the-swelling",
  "Itpch": "it-shall-swell",
  "Omtsmich": "and-causing-to-sprout",
  "Tfch": "it-swelled",
  "Ohtsmich": "and-it-sprouted",
  "Lhtrchv": "to-expand",
  "Nkhr": "it-was-recognized",
  "Tmtm": "you-tasted",
  "Ntpchno": "we-shall-nurture-it",
  "Tznicho": "you-shall-neglect",
  "Ltpocho": "to-nurture-it",
  "Oshrpto": "and-you-burned-it",
  "Otshlikoho": "and-you-cast-it-out",
  "Tschichh": "barren",
  "Tktpo": "you-shall-pluck",
  "Ttsmo": "you-shall-thirst",
  "Tktsro": "you-shall-reap",
  "Otpkdm": "and-she-visited-them",
  "Ktsft": "you-were-angry",
  "Chnnt": "you-were-gracious",
  "Hmbit": "the-one-looking",
  "Trfo": "you-shall-be-healed",
  "Otttslo": "and-you-shall-be-lazy",
  "Mokrch": "compelled",
  "Dorsht": "seeking",
  "Ohzbch": "and-the-sacrifice",
  "Hzvch": "the-sacrifice",
  "Hbtchon": "the-confidence",
  "Chshof": "exposed",
  "Tpkdo": "you-shall-visit",
  "Ohmnh": "and-the-afflicted-one",
  "Hmtsrpim": "the-refiners",
  "Onrmsim": "and-being-trampled",
  "Tdcho": "you-shall-reject",
  "Chzr": "I-shall-return",
  "Hiorsht": "the-inheriting",
  "Tshkdo": "you-shall-watch",
  "Igmlkm": "he-shall-reward-you",
  "Ktsrkihm": "according-to-their-needs",
  "Lhtrv": "to-be-mixed",
  "Bnsionotio": "in-his-trials",
  "Nchrshh": "was-silenced",
  "Onkhrh": "and-was-troubled",
  "Nkhrh": "was-troubled",
  "Okhchd": "and-I-shall-conceal",
  "Nkhrti": "I-was-troubled",
  "Ndcht": "rejected",
  "Onkhr": "and-was-troubled",
  "Chnni": "be-gracious-to-me",
  "Ontmkti": "and-I-was-supported",
  "Htsilni": "save-me",
  "Hgdilo": "they-magnified",
  "Chdl": "I-shall-cease",
  "Otmsr": "and-she-shall-be-delivered",
  "Tpkid": "assignment",
  "Mshnkh": "your-support",
  "Inchk": "he-shall-guide-you",
  "Mtsfn": "compass",
  "Hmtsfn": "the-compass",
  "Tslchh": "it-prospered",
  "Lmtsfn": "to-the-compass",
  "Hvkh": "the-weeping",
  "Nttsl": "we-were-lazy",
  "Sklok": "they-stoned-you",
  "Mnsionotik": "from-your-trials",
  "Ttnsh": "you-shall-be-lifted-up",
  "Tthll": "you-shall-boast",
  "Shchtsn": "arrogant",
  "Trsn": "Tirson",
  "Ttfll": "you-shall-pray",
  "Tsdok": "justification",
  "Mtvim": "abominable",
  "Tkchish": "you-shall-deny",
  "Mzkir": "one-who-reminds",
  "Tgdr": "you-shall-fence",
  "Lhtfrns": "to-sustain-oneself",
  "Tchdl": "you-shall-cease",
  "Ochrk": "and-gnashing",
  "Lmkhntm": "to-their-allotment",
  "Frshno": "I-shall-spread-it",
  "Ndrsht": "is-required",
  "Ochmd": "and-he-coveted",
  "Nshtnim": "changing",
  "Lskhn": "to-endanger",
  "Hmdig": "the-troubling",
  "Mngd)": "from-opposite",
  "Vtni": "on-condition",
  "Chrtt": "regret-of",
  "Mshibh": "returning",
  "Vdnm": "their-destruction",
  "Nspcho": "they-were-attached",
  "Lhkhis": "to-provoke",
  "Itpsh": "he-shall-seize",
  "Ohtstsim": "and-the-descendants",
  "Ohnhlt": "and-the-administration-of",
  "Obmgni": "and-with-shields-of",
  "Ohmlkim": "and-the-Amalekites",
  "Vhshiro": "when-he-left",
  "Tkhont": "[ACC]-intention-of",
  "Rflh": "Riplah",
  "Nchshfh": "was-exposed",
  "with-all-Mkhlch": "with-every-plague",
  "Mmkot": "from-plagues",
  "Mkhovihm": "from-their-helmets",
  "Mshrionihm": "from-their-armor",
  "Kchobtm": "as-their-duty",
  "Chbo": "they-hid",
  "Tshmo": "you-shall-be-guilty",
  "Tgno": "you-shall-defend",
  "Tkhontm": "[ACC]-their-intention",
  "Kplim": "double",
  "Tsdi": "sides-of",
  "Tvhltm": "[ACC]-their-panic",
  "Dmkhm": "your-blood",
  "Dtno": "our-religion",
  "Oldtno": "and-to-our-religion",
  "Onkchsh": "and-we-shall-deny",
  "Bdtno": "in-our-religion",
  "Oltpno": "and-our-children",
  "Hkoshr": "the-conspirator",
  "with-all-Rtsvnkm": "with-all-your-will",
  "Ochrmsho": "and-his-scythe",
  "Tpno": "our-children",
  "Nntsch": "we-shall-prevail",
  "Rmtkhm": "your-cunning",
  "Shrionikm": "your-armor",
  "Ngmr": "it-was-finished",
  "Oitprts": "and-he-broke-out",
  "Nchshpim": "exposed",
  "Hchdot": "the-sharp",
  "Ndkro": "they-were-pierced",
  "Ohmchlkot": "and-the-dissensions",
  "if-Ytmkv": "if-they-support",
  "Olhtptot": "and-to-be-enticed",
  "Thmridot": "[ACC]-the-rebellions",
  "Vmlikih": "in-Amalickiah",
  "Oichbsh": "and-he-saddled",
  "and-[ACC]-Mgnyv": "and-[ACC]-his-shields",
  "Hkriz": "he-proclaimed",
  "Tkhtnto": "[ACC]-his-tunic",
  "Onshlk": "and-was-cast-out",
  "Onzkr": "and-we-shall-remember",
  "Khtnt": "tunic",
  "Nrkv": "it-rotted",
  "Mtsivh": "grieving",
  "Olhnhig": "and-to-lead",
  "Tdgl": "[ACC]-banner",
  "Npotsh": "scattered",
  "Khtv": "as-is-natural",
  "Bshibh": "in-old-age",
  "Tfkdt": "[ACC]-command-of",
  "Olhkrichm": "and-to-compel-them",
  "Tmko": "they-supported",
  "Vrviit": "in-the-fourth",
  "if-Yshymhv": "if-he-places-it",
  "Ishkh": "he-shall-water",
  "Lhkimm": "to-establish-them",
  "Oitnkr": "and-he-disguised-himself",
  "Lktsf": "to-be-angry",
  "Hkhr": "it-was-recognized",
  "and-all-Hsvrrym": "and-all-the-rebels",
  "Srrm": "their-rebellion",
  "Hshkil": "he-acted-wisely",
  "Mshig": "overtaking",
  "Obtrmit": "and-in-deceit",
  "Sllot": "ramps",
  "Lhkif": "to-surround",
  "Hkhis": "he-provoked",
  "Mzzim": "shaken",
  "Shlith": "control",
  "Itbcho": "they-shall-be-slaughtered",
  "Vkhzr": "cruelly",
  "Vhtchvrm": "when-they-joined",
  "Vshor": "in-the-tenth",
  "Htsib": "he-set-up",
  "Lhzik": "to-harm",
  "Hmlikihim": "the-Amalickiahites",
  "Hsollh": "the-rampart",
  "Hchpir": "the-moat",
  "Nchfr": "was-dug",
  "Nschpo": "they-were-swept-away",
  "Tchfirihm": "[ACC]-their-moats",
  "Nchshpo": "they-were-exposed",
  "Mgnihm": "their-shields",
  "Shmitm": "their-hearing",
  "until-Kvmt": "until-the-height-of",
  "Htsopim": "the-watchmen",
  "Ntth": "it-inclined",
  "Oibtsr": "and-he-fortified",
  "Hhgnh": "the-defense",
  "Omshsotihm": "and-their-plunderings",
  "Ochrbnm": "and-their-destruction",
  "Olhtrv": "and-to-intervene",
  "Hnhigm": "he-led-them",
  "Oitnpl": "and-he-fell-upon",
  "Hnhigo": "he-led-him",
  "Nftrh": "it-was-solved",
  "Nmhrt": "hasty",
  "Thsorrim": "[ACC]-the-rebels",
  "all-Chrbnm": "all-their-destruction",
  "Olhshootm": "and-to-level-them",
  "from-Hsvrrym": "from-the-rebels",
  "Hgdm": "he-cut-them-down",
  "Ldgl": "to-a-banner",
  "Htgo": "they-were-proud",
  "Htsilim": "the-nobles",
  "Tknot": "regulations",
  "Mbrichim": "smuggling",
  "lest-Ykytsv": "lest-they-awaken",
  "Kmkin": "like-one-who-prepares",
  "Lpdion": "for-redemption",
  "Ibtsr": "he-shall-fortify",
  "not-Hsgyrv": "not-they-delivered-up",
  "Rnnim": "flourishing",
  "Lhdbikm": "to-overtake-them",
  "Lhtnfl": "to-fall-upon",
  "Nkhnt": "submissive",
  "Lhsgir": "to-deliver-up",
  "Fkdt": "command-of",
  "Bchpirt": "in-the-digging-of",
  "Chrits": "trench",
  "Hchrits": "the-trench",
  "Hpnimit": "the-inner",
  "from-Hchryts": "from-the-trench",
  "Hkricho": "they-compelled",
  "Hkrichom": "they-compelled-them",
  "Bhtkipo": "when-he-attacked",
  "Thskhnh": "[ACC]-the-danger",
  "Btchnoni": "with-supplications-of",
  "Bmtsoktm": "in-their-distress",
  "Lmts": "to-strengthen",
  "Onkchim": "and-upright",
  "Rkht": "you-prepared",
  "Hmtsfh": "the-watchtower",
  "if-Tsyrv": "if-you-remove",
  "if-Tsvgv": "if-you-retreat",
  "Otpkdo": "and-you-shall-be-visited",
  "Tdtno": "[ACC]-our-religion",
  "Chlif": "I-shall-exchange",
  "Shko": "they-oppressed",
  "Hzkhim": "the-innocent",
  "Skhim": "I-shall-agree",
  "Rmztm": "you-hinted",
  "Nrkhh": "let-us-prepare",
  "Tsodkt": "righteous",
  "Lshchrr": "to-free",
  "Lhkipm": "to-surround-them",
  "Nzhro": "they-were-careful",
  "Lntifos": "to-Antipus",
  "Otsrf": "and-I-joined",
  "Mshmidim": "destroying",
  "Tochltno": "our-hope",
  "Tkvlt": "[ACC]-receiving-of",
  "Hmshkno": "we-delayed",
  "lest-Ykpv": "lest-they-surround",
  "lest-Yshygvny": "lest-they-overtake-me",
  "Mshigim": "overtaking",
  "Otsrfm": "and-I-joined-them",
  "Lhchlif": "to-exchange",
  "Lvtsrn": "to-fortify-them",
  "Lhtstrf": "to-join",
  "Htsv": "was-set-up",
  "Mtso": "be-strong",
  "Nltsno": "we-were-forced",
  "Htprtso": "they-broke-out",
  "Obmklot": "and-with-staves",
  "Shloph": "drawn",
  "Lchrts": "to-decide",
  "Chrtsno": "we-decided",
  "Shlnom": "we-asked-them",
  "Chto": "they-were-terrified",
  "Bdkdok": "carefully",
  "Thntschon": "[ACC]-the-victory",
  "Intsl": "he-shall-be-rescued",
  "Tplno": "we-cared-for",
  "Prtso": "they-broke-through",
  "Bgdodino": "in-our-troops",
  "Hzno": "we-dared",
  "Onchkh": "and-we-waited",
  "Nsbotino": "our-circumstances",
  "Chkino": "we-waited",
  "Httsvno": "we-were-grieved",
  "Shpkno": "we-shed",
  "Ontchzk": "and-we-strengthened-ourselves",
  "Ontmts": "and-we-were-encouraged",
  "lest-Nkryt": "lest-we-be-cut-off",
  "Mstorm": "their-hiding-place",
  "Lhmshkh": "to-continue",
  "Omshktm": "and-you-drew-them",
  "Chlsht": "weakness-of",
  "Tmkhm": "their-support",
  "Ochrrno": "and-we-burned-them",
  "Chsho": "they-hurried",
  "Olnhl": "and-to-manage",
  "Chrtsh": "she-decided",
  "Frtsh": "she-broke-through",
  "Nshib": "we-shall-return",
  "Otshtdlo": "and-you-shall-strive",
  "Mchkhh": "waiting",
  "Lkhv": "to-delay",
  "Ottchzko": "and-you-shall-be-strengthened",
  "Ohkplh": "and-it-was-doubled",
  "Tdbko": "you-shall-cling",
  "Tttsv": "you-shall-be-grieved",
  "Ikbsho": "they-shall-conquer",
  "Chrrno": "we-burned-them",
  "Hshvod": "the-bondage",
  "Ntkommh": "let-us-rise-up",
  "Lnhl": "to-manage",
  "Vshvod": "in-bondage",
  "Hshiro": "they-left",
  "Nchrtso": "they-were-determined",
  "Vchshkht": "in-the-darkness-of",
  "Obslmotihm": "and-with-their-ladders",
  "Ohrkhh": "and-the-healing",
  "Rkko": "they-softened",
  "Hntonim": "the-given",
  "Htrshlo": "they-were-negligent",
  "Htsor": "the-neck",
  "Hpligh": "she-sailed",
  "from-Hbvchrym": "from-the-voters",
  "Lhshlt": "to-rule",
  "Tzko": "you-shall-be-worthy",
  "Tmosdkhm": "[ACC]-your-foundation",
  "Hmmo": "they-were-confused",
  "Shmont": "eight-of",
  "Shrftm": "their-burning",
  "Oichdr": "and-he-penetrated",
  "Zhro": "they-shone",
  "Hsbo": "they-turned",
  "Lvth": "to-express-it",
  "Klchishh": "like-a-whisper",
  "Olmkr": "and-to-sell",
  "Mshkilim": "wise-ones",
  "Mfshtn": "from-linen",
  "Shzor": "woven",
  "Mhshikim": "from-those-belonging",
  "from-Hrshvmvt": "from-the-records",
  "Mcholl": "causing",
  "Tsdo": "they-hunted",
  "Htsnoim": "the-humble",
  "Ohsmkot": "and-the-authority",
  "Mrshiim": "condemning",
  "Oitnpch": "and-he-was-puffed-up",
  "to-Hshvk": "to-the-market",
  "Bgno": "in-his-garden",
  "Omshtommim": "and-being-astonished",
  "Lptoii": "to-enticements-of",
  "Ipitskm": "he-shall-scatter-you",
  "Otshddo": "and-you-shall-plunder",
  "Omkshibim": "and-listening",
  "Ohtchbrtm": "and-you-joined",
  "Hgbihh": "she-raised-high",
  "Ttpsho": "you-shall-be-seized",
  "Tkchisho": "you-shall-deny",
  "Ndkr": "he-was-pierced",
  "Lsfd": "to-mourn",
  "Bkbort": "in-the-burial-of",
  "Onshtomm": "and-we-were-astonished",
  "Mtmihtno": "from-our-astonishment",
  "Itnsh": "he-shall-exalt-himself",
  "Hkborh": "the-burial",
  "Kshor": "bound",
  "Vhskhm": "in-agreement",
  "Olspd": "and-to-mourn",
  "Sntom": "Seantum",
  "Rtscht": "you-murdered",
  "Tbdko": "you-shall-examine",
  "Hkchish": "he-denied",
  "Hshtfl": "he-humbled-himself",
  "lest-Ytkymv": "lest-they-be-fulfilled",
  "Oishkk": "and-it-shall-subside",
  "Otshbit": "and-you-shall-cause-to-cease",
  "Odgnh": "and-its-grain",
  "Tshvt": "it-shall-cease",
  "Mgft": "plague-of",
  "Tkshib": "you-shall-listen",
  "Dgnh": "its-grain",
  "Ltslch": "to-prosper",
  "Khso": "they-covered",
  "Mhsorrim": "from-the-rebels",
  "Oitchvo": "and-they-hid-themselves",
  "Ttnodt": "[ACC]-shaking-of",
  "Obchth": "and-in-terror",
  "Pchotim": "governors",
  "if-Ytmn": "if-he-hides",
  "Ohpkti": "and-I-shall-overturn",
  "Hgmorh": "the-complete",
  "all-Htvmn": "all-who-hides",
  "not-Nmshk": "not-it-continued",
  "Olhtnpch": "and-to-be-puffed-up",
  "Othrgom": "and-you-shall-kill-them",
  "Otgrshoho": "and-you-shall-drive-him-out",
  "Omkspkm": "and-from-your-silver",
  "Ntst": "it-was-kindled",
  "Tbko": "you-shall-weep",
  "Tspdo": "you-shall-mourn",
  "Rgmti": "I-stoned",
  "Mtmonino": "our-treasures",
  "Chmko": "they-slipped-away",
  "Tzricht": "[ACC]-sunrise-of",
  "Tshtommo": "you-shall-be-astonished",
  "Otgrshoni": "and-you-drove-me-out",
  "Bsdkim": "in-cracks",
  "Khvkh": "like-a-valley",
  "Tshvrnh": "they-shall-be-broken",
  "Tkhvdnh": "they-shall-be-heavy",
  "Toklnh": "they-shall-be-able",
  "Trmsnh": "they-shall-be-trampled",
  "Otzvnh": "and-they-shall-be-abandoned",
  "Lhrms": "to-be-trampled",
  "Vhminm": "when-they-believed",
  "Htkimo": "they-were-fulfilled",
  "Bmsorot": "in-traditions",
  "Ktshrim": "like-noon",
  "Otzrch": "and-it-shone",
  "Kzbim": "liars",
  "Lhdich": "to-lead-astray",
  "Zmnm": "their-time",
  "Tntsch": "it-shall-prevail",
  "Lshlomkm": "for-your-peace",
  "Hndibh": "the-generous",
  "Oshtpino": "and-our-partners",
  "Ichshko": "they-shall-be-darkened",
  "Lhtsib": "to-set-up",
  "Ntmnh": "was-appointed",
  "Chlilh": "far-be-it",
  "Oibtsro": "and-they-fortified",
  "Obtsnh": "and-with-a-shield",
  "Htvch": "the-slaughter",
  "Nrdf": "was-pursued",
  "Hshg": "was-overtaken",
  "Mdto": "his-measure",
  "Hchitsnim": "the-outer-ones",
  "Tsro": "they-stored",
  "Bshir": "in-a-song",
  "Fkfk": "he-doubted",
  "Onnsho": "and-they-were-punished",
  "Nchrt": "was-engraved",
  "Tlmid": "disciple",
  "from-Hchshbvnvt": "from-the-accounts",
  "Otsts": "and-descendant",
  "Ohmmnim": "and-the-appointed-ones",
  "Lmnhigim": "to-leaders",
  "Ovhtfrot": "and-in-boasting",
  "Lhtfrk": "to-come-apart",
  "Olnpchm": "and-to-inflate-them",
  "Nhno": "they-enjoyed",
  "Onhlh": "and-she-was-led",
  "Olchlts": "and-to-rescue",
  "Mnhig": "leader",
  "Khkhlv": "like-a-dog",
  "Okchzirh": "and-like-a-sow",
  "Vrfsh": "in-mire",
  "upon-Hgdvd": "upon-the-troop",
  "Mhshg": "from-being-overtaken",
  "Vhttsvo": "when-he-was-grieved",
  "Nrgm": "he-was-stoned",
  "Zmnno": "our-time",
  "Lhvk": "to-be-split",
  "Chdim": "sharp",
  "Otshk": "and-it-sank",
  "Shvrn": "their-breaking",
  "Obsdkim": "and-in-cracks",
  "Vkhshlsh": "in-about-three",
  "Lmsh": "to-depart",
  "Lhdlik": "to-kindle",
  "Orgmno": "and-we-stoned",
  "Ishchk": "he-shall-laugh",
  "Htvti": "I-immersed",
  "Gmgmno": "we-stammered",
  "Shrptim": "I-burned-them",
  "Obrgmm": "and-when-they-stoned-them",
  "Tstrnh": "they-shall-be-hidden",
  "Tkribo": "you-shall-offer",
  "Zbchikm": "your-sacrifices",
  "Mlkonn": "from-lamenting",
  "Tstsi": "descendants-of",
  "Otchdl": "and-it-ceased",
  "Mlhvk": "from-being-split",
  "Ohnchot": "and-the-groanings",
  "Rgmom": "they-stoned-them",
  "Vsfh": "in-a-storm",
  "Ichkr": "he-shall-investigate",
  "Obptchon": "and-with-opening-of",
  "upon-Shrtv": "upon-his-ministry",
  "Hmror": "the-bitter",
  "Tmsho": "you-shall-depart",
  "and-all-Hbvnh": "and-all-who-builds",
  "Inchmo": "they-shall-be-comforted",
  "Hrchmnim": "the-merciful",
  "Ichrpo": "they-shall-revile",
  "Mlch": "salt",
  "Tmlch": "it-shall-be-salted",
  "upon-Hmnvrh": "upon-the-lampstand",
  "Hmotsh": "the-council",
  "Mskim": "agreeing",
  "lest-Ytpshk": "lest-he-seize-you",
  "Thsnin": "[ACC]-the-Senine",
  "all-Hmbyt": "all-who-looks",
  "Lchmd": "to-covet",
  "Lhtnkhr": "to-disguise-oneself",
  "Ttslvkhm": "[ACC]-your-cross",
  "all-Hmshlch": "all-who-sends-away",
  "Thgroshh": "[ACC]-the-divorced-woman",
  "do-not-Ttkvmmv": "do-not-resist",
  "Tkhtntkh": "[ACC]-your-tunic",
  "and-all-Hmkrych": "and-all-who-compels",
  "Hmlivim": "the-scorners",
  "Ohrdpim": "and-the-persecutors",
  "Mzrich": "causing-to-shine",
  "do-not-Tchtsrv": "do-not-trumpet",
  "Vchtstsrh": "with-a-trumpet",
  "Hshokim": "the-markets",
  "do-not-Trbv": "do-not-multiply",
  "do-not-Tdmv": "do-not-imagine",
  "Itkdsh": "it-shall-be-sanctified",
  "Rtsonk": "your-will",
  "Oslch": "and-forgive",
  "Slchno": "we-have-forgiven",
  "Btsomkm": "when-you-fast",
  "Tsmim": "fasting",
  "Btsomk": "when-you-fast",
  "and-[ACC]-Hmmvn": "and-[ACC]-the-riches",
  "and-how-Tshtv": "and-what-shall-you-drink",
  "Lgopkm": "for-your-body",
  "Lsmim": "to-the-granaries",
  "Mkhlkhl": "sustaining",
  "Tdgo": "you-shall-worry",
  "Mlbish": "clothing",
  "Tchtsir": "[ACC]-grass",
  "Ltnor": "to-the-furnace",
  "Obmdh": "and-with-the-measure",
  "Tmdo": "you-shall-measure",
  "and-do-not-Tshlykv": "and-do-not-cast",
  "Hchzirim": "the-swine",
  "Trpim": "tearing",
  "Hibtsro": "are-they-gathered",
  "Mtsnim": "from-thorns",
  "Mdrdrim": "from-thistles",
  "Hnpots": "the-widespread",
  "Lshrikh": "for-a-hissing",
  "Khmlch": "like-salt",
  "Olhrms": "and-to-be-trampled",
  "Tslim": "lame",
  "Mtsrim": "lepers",
  "Nkmro": "were-moved-with-compassion",
  "Opschihm": "and-their-lame",
  "Thtf": "[ACC]-the-children",
  "Lfrs": "to-break",
  "Prsti": "I-broke",
  "Oinshbo": "and-they-blew",
  "Kchtim": "like-wheat",
  "Vminkhm": "when-you-believe",
  "Ttkbtso": "you-shall-gather",
  "Tgrshom": "you-shall-drive-them-out",
  "Tchosho": "you-shall-hasten",
  "and-all-Hmpr": "and-all-who-violates",
  "Chrm": "destruction",
  "if-Tshrtvhv": "if-you-serve-him",
  "Otshrtoho": "and-you-shall-serve-him",
  "Bhtksotm": "when-they-covered-themselves",
  "Oshmnon": "and-fatness",
  "Hkhrio": "they-bowed-down",
  "Khlvnm": "as-their-whiteness",
  "Thrt": "you-purified",
  "Tkhvd": "I-shall-be-honored",
  "Ttsm": "you-shall-thirst",
  "Hshriot": "the-remnants",
  "Lgrn": "to-the-threshing-floor",
  "Krnkh": "your-horn",
  "Ohchrmti": "and-I-shall-devote-to-destruction",
  "Ttlh": "it-shall-be-hung",
  "Ikbtsm": "he-shall-gather-them",
  "Iptscho": "they-shall-break-forth",
  "Tlkon": "you-shall-go",
  "Omsfkhm": "and-your-gatherer",
  "Vgllm": "because-of-them",
  "Rfho": "I-shall-heal-him",
  "Mrmt": "from-cunning-of",
  "Kkpir": "like-a-young-lion",
  "Mrkbotik": "your-chariots",
  "Ontshti": "and-I-shall-uproot",
  "Khrit": "I-shall-cut-off",
  "Ochmh": "and-wrath",
  "Msfm": "their-gatherer",
  "Ptschi": "break-forth",
  "sons-of-Shvmmh": "sons-of-desolation",
  "Mshknotik": "your-dwellings",
  "do-not-Tchshky": "do-not-hold-back",
  "that-Ymyn": "for-right",
  "Tprtsi": "you-shall-break-forth",
  "and-do-not-Tklmy": "and-do-not-be-ashamed",
  "Tchpiri": "you-shall-be-ashamed",
  "Tshkchi": "you-shall-forget",
  "Kvtskh": "I-shall-gather-you",
  "Vshtsf": "in-an-overflow-of",
  "Ktsf": "wrath",
  "Rchmtik": "I-had-compassion-on-you",
  "Mktsf": "from-wrath",
  "Mrchmkh": "your-compassionate-one",
  "Bspirim": "with-sapphires",
  "Khdkhd": "agate",
  "Chlonik": "your-windows",
  "Mshk": "from-oppression",
  "Lmnkh": "for-your-sake",
  "Nfch": "one-who-blows",
  "Fchm": "coals",
  "Trshii": "you-shall-condemn",
  "and-all-Hmkshyb": "and-all-who-listens",
  "Mkbsim": "fullers",
  "Bmkshpim": "against-sorcerers",
  "Ovmnfim": "and-against-adulterers",
  "Thshkhir": "[ACC]-the-hired-worker",
  "and-[ACC]-Hytvm": "and-[ACC]-the-orphan",
  "Nklitm": "you-were-consumed",
  "Gzlnok": "we-have-robbed-you",
  "Vmshrot": "in-the-tithes",
  "Obchnoni": "and-test-me",
  "Ftch": "I-shall-open",
  "Tchloni": "[ACC]-windows-of",
  "Tshkhl": "it-shall-devour",
  "Gfnkhm": "your-vine",
  "Ohkshib": "and-he-listened",
  "Otbchino": "and-you-shall-discern",
  "Ktnor": "like-a-furnace",
  "Izrch": "it-shall-shine",
  "Mkbilim": "parallel",
  "Lcht": "tablets",
  "Lvchn": "to-test",
  "Vchn": "I-shall-test",
  "Shloshh": "three",
  "and-[ACC]-Pschyhm": "and-[ACC]-their-lame",
  "Oipkch": "and-he-opened",
  "Rtsonno": "our-will",
  "Nbnitm": "you-were-built",
  "Kbso": "they-washed",
  "Hshol": "the-one-who-asks",
  "Mttsv": "being-grieved",
  "what-Tchptsv": "what-do-you-desire",
  "Ttmo": "you-shall-taste",
  "Thpko": "you-shall-be-overturned",
  "Khhhfkhm": "like-their-overturning",
  "Hhfkhm": "their-overturning",
  "Vhtftm": "in-their-preaching",
  "Obmtsb": "and-in-the-situation",
  "and-do-not-Tdmv": "and-do-not-imagine",
  "if-Tbvzv": "if-you-despise",
  "Vrfoot": "with-healings",
  "Lhsv": "to-turn",
  "Egyptian(f)": "Egyptian"
};

// ============================================================
// PROCESS BOM.html
// ============================================================

console.log('Reading BOM.html...');
let html = fs.readFileSync(bomPath, 'utf8');

// Count replacements
let totalReplacements = 0;

// First, build a set of known bad glosses from the remaining_list.txt patterns
const knownBadGlosses = new Set([
  "Ohkhnh","Vvtot","Vkdcht","Hmrot","Ktsirm","Bhrigt","Obshdidtm",
  "Hmpitsim","Bmklot","Ktstso","Lshomo","Lhlnn","Hkhkhr","Otktsf",
  "Hsgiro","Mridtm","Ktmino","Nkhtm","Zhrim","Tspo","Nhll","Nthll",
  "Onshmidm","Mtvlim","Btchonm","Lgzl","Tkhh","Ksgim","Ltfch",
  "Omtchil","Ttpchoho","Ttpcho","Tsomch","Dchitm","Bnsionot","Zhrm",
  "Tstir","Lhfil","Hkshib","Mrshi","Trvt","Ochrmshotihm","Shrionihm",
  "Tmsro","Lhkhchd","Ikchdo","Hktspim","Ibrkm","Mhmlikihim","Ltkopt",
  "Bngod","Hrpim","Itgbro","Btchon","Chzt","Chmh","Lhkrich","Lhtkipm",
  "Hshir","Lhmir","Nshtkro","Hkpno","Mtmiktm","Bmtsok","Hgdod",
  "Chrrm","Zivtkhm","Ntkomm","Hkpo","Tszorm","Lklbim","Tlkchnh",
  "all-Hmbytym","Rtsno","Throtsch","Shchrro","Hskmti","Chronk",
  "Lshkhch","Mtbil","Ohmrmot","Tvch","Pchot","Kbrti","Tmkhot",
  "Hmsmrim","Hmlch","Tchptso","Nshlmo","Ichtro","Dpko","Shchit",
  "and-if-Tzkrvny","Tgrshoho","Onbrko","Ikptso","Mtsrf",
  "the-Church-of","Chris","Htsponit","Vnmoron","Vnchch","Ochch",
  "Vnsht","Vnshvlon","Vnliv","Vnkish","Vnkhorom","Vnloi","Vnkim",
  "Vnshz","Vncht","Vnkiv","Nirshnh","Dsrt","Dvsh","Otchtitn",
  "Mchddot","Orkhn","Odltn","Khkrh","Nnhig","Chlonot","Ishtpo",
  "Vhvlkhm","Zkhh","lest-Ykny","Lvsh","Npdit","Nvrt","Btslmi",
  "Khvd","Ttsfn","Lhrotn","Lhtminm","Tftronm","Itkdsho","Frsh",
  "Hmdrik","Htmonh","Tsfn","Tmskh","Iprsho","Zkroni","Tptro",
  "to-Spynvtyhm","Khtvt","Mfltst","upon-Chvpy","Oglgh","Nkhilh",
  "Tkhorihor","Tkhohor","Oitgnbo","son-of-Kmnvr","Otrkd","Itpshto",
  "upon-Bvnyh","all-Hbvnh","if-Ydrkv","Nmshch","Prisht","Hkhilo",
  "Mshko","Tkhom","Lchvk","Kdmoniot","Vrsm","if-Ygdv","Trflkish",
  "Tsrf","Bznotio","Tkhorom","also-Kysh","Ichtsts","Nmrtsim",
  "Oichpro","Omtslch","Lmchsh","Lhtsr","do-not-Trybv","Lhshttf",
  "Olhshttf","Chzo","Onkshl","Bshimt","Itlotstso","Tsrin","Tvchnm",
  "Vdmkhm","Pshoth","Rchtso","Pzro","Oisttr","Vhlchmm","Hrviit",
  "Chshlon","Glgl","if-Ynych","Mgdot","Dchk","Orkhh","Mshirim",
  "Shtochim","Hpgrim","Lvdnm","Bshopr","Htrf","Lhtnchm","Ottvl",
  "Ohrgkh","Htro","Thrshomot","Mhgot","Shkori","Shkor","Obmgnihm",
  "Htlf","Nshn","Trshomto","Oitmnm","if-Yklklv","Shmt","Shfkht",
  "Mhtfsht","Oitnkro","Lshdd","Vgrof","and-unless-Nmvt",
  "not-Hchshyb","from-Hlvmd","all-Tsrkyhm","Htmkro","Oishddo",
  "Tzkhoiot","Vmlisim","Nmhr","Ntchzko","Tfgri","Chrmonts","Glcho",
  "Khhh","Orchmtim","Lsmn","Tchol","Nlchmh","Zrhmlhfrk","Httsvo",
  "Mtnshim","Mshpilim","Chkhh","Otrchbnh","Tslmo","Lkhzv","Otslm",
  "Nkbso","what-Yrgsh","Hrgshtm","Hhthlkhtm","Hmlig","Hmtnpchim",
  "all-Hmkchysh","Lhtnfch","Hmshpilim","if-Tdbrv","Ovchronh",
  "Shtpim","Bmbokh","Ttspo","Chshob","Tkhsh","Tthro","Rtsonkm",
  "Klklot","Ntkvltm","all-Tsrkykm","Lchronh","Oichrpo","Kvlt",
  "Otdrsh","if-Grshvny","Hkhltni","Otsfni","Bzkim","Ntsoiti",
  "Nnhgo","Ohshkchtm","Ntmt","Ngrm","Tmro","Iktsr","Lkchtni",
  "son-of-Gdvnh","Rkshti","Shgiti","Tkhil","Tknisho","Imshl",
  "Nchmltm","that-Yshh","Shtrim","Ipsht","Okshdd","Lrkhm","Mddo",
  "Omdtm","Olmnh","Msninh","Lmnh","Shblonim","Tnsni","Chshvt",
  "Olnkbh","Mtchdim","Ntfsht","Khrmt","Tshimm","Bshrshrotio",
  "Isrkhm","Shrshrot","Hmkinh","Lnpotsim","Nshgh","Krmno","Mchkim",
  "Otshliko","not-Tvrydv","Nkchot","Vnkhch","Lhlft","Lrgm",
  "Hshrfh","Tsrtni","Ngmrh","Hshotrim","Lhsgirkm","Ttsilo",
  "Chrkim","Pshto","Onntsl","and-not-Nzvkv","Onrgmo","Lhtsrv",
  "Lmdt","Ohpgrim","Ntrpo","Bksoi","Mskh","Hkpirh","do-not-Tkbrhv",
  "Htmini","Nshfkht","Nkhvsh","Otttsv","Lhkimh","Omrkbotio",
  "Hkhzv","Mhkhiso","Shhh","Khzv","Obkzbihm","Lhshtmsh","Khkh",
  "Tktsf","Llgo","Oishkdo","Tshrtoni","Mmdoni","Btslmo","Hshttch",
  "Kmpilim","Ttsoi","Vrtsot","Hbtlnim","Otgbl","Noshbt","Mkpot",
  "Vmnr","Bhmni","Ishddo","Bdrshotihm","Shmnilom","Lhtgonn",
  "Nokchno","Slch","Ktmno","Ntsfn","Ntmnm","Ktmno","Ntmn","Ntlnom",
  "Ishkbo","Hmtchbrim","Ntsodim","Ndpo","Hchitsonim","Gdrt",
  "Otktsro","Hsmim","Ischpo","Hktsir","Lhthll","Gdsh","Hsgirno",
  "Vshgit","Onsht","Mchsor","Brchobotihm","Onsklno","Nkvtsh",
  "Onbtch","Ikchnh","Chrmsh","Hmsfd","Nrkbim","Vmshlti","Lhrgiz",
  "Gzrt","Vmshloti","Ichlk","Khhfrdh","Ttsmdo","Tchko","Othpkt",
  "Mtslich","Ktso","Lhpsik","Lhnot","Hshtrim","Bholkt","Ttngd",
  "Mkhchsh","Hnshkhcht","Rtsit","Hrtsit","Httokch","Ondrk","Igrrm",
  "Hfrd","Gvlh","Lhnchot","Hmni","Zzrom","Hvdlt","Vtsmn","Vtsmh",
  "Hdichm","Ngnbo","Mnpchim","Otsmdihm","Hshgich","Nbzitm",
  "Bhkrcho","Bgrgir","Ndmh","Tzroho","Chzkhm","Htpichh","Itpch",
  "Omtsmich","Tfch","Ohtsmich","Lhtrchv","Nkhr","Tmtm","Ntpchno",
  "Tznicho","Ltpocho","Oshrpto","Otshlikoho","Tschichh","Tktpo",
  "Ttsmo","Tktsro","Otpkdm","Ktsft","Chnnt","Hmbit","Trfo",
  "Otttslo","Mokrch","Dorsht","Ohzbch","Hzvch","Hbtchon","Chshof",
  "Tpkdo","Ohmnh","Hmtsrpim","Onrmsim","Tdcho","Chzr","Hiorsht",
  "Tshkdo","Igmlkm","Ktsrkihm","Lhtrv","Bnsionotio","Nchrshh",
  "Onkhrh","Nkhrh","Okhchd","Nkhrti","Ndcht","Onkhr","Chnni",
  "Ontmkti","Htsilni","Hgdilo","Chdl","Otmsr","Tpkid","Mshnkh",
  "Inchk","Mtsfn","Hmtsfn","Tslchh","Lmtsfn","Hvkh","Nttsl",
  "Sklok","Mnsionotik","Ttnsh","Tthll","Shchtsn","Trsn","Ttfll",
  "Tsdok","Mtvim","Tkchish","Mzkir","Tgdr","Lhtfrns","Tchdl",
  "Ochrk","Lmkhntm","Frshno","Ndrsht","Ochmd","Nshtnim","Lskhn",
  "Hmdig","Mngd)","Vtni","Chrtt","Mshibh","Vdnm","Nspcho","Lhkhis",
  "Itpsh","Ohtstsim","Ohnhlt","Obmgni","Ohmlkim","Vhshiro","Tkhont",
  "Rflh","Nchshfh","with-all-Mkhlch","Mmkot","Mkhovihm",
  "Mshrionihm","Kchobtm","Chbo","Tshmo","Tgno","Tkhontm","Kplim",
  "Tsdi","Tvhltm","Dmkhm","Dtno","Oldtno","Onkchsh","Bdtno",
  "Oltpno","Hkoshr","with-all-Rtsvnkm","Ochrmsho","Tpno","Nntsch",
  "Rmtkhm","Shrionikm","Ngmr","Oitprts","Nchshpim","Hchdot","Ndkro",
  "Ohmchlkot","if-Ytmkv","Olhtptot","Thmridot","Vmlikih","Oichbsh",
  "and-[ACC]-Mgnyv","Hkriz","Tkhtnto","Onshlk","Onzkr","Khtnt",
  "Nrkv","Mtsivh","Olhnhig","Tdgl","Npotsh","Khtv","Bshibh","Tfkdt",
  "Olhkrichm","Tmko","Vrviit","if-Yshymhv","Ishkh","Lhkimm",
  "Oitnkr","Lktsf","Hkhr","and-all-Hsvrrym","Srrm","Hshkil","Mshig",
  "Obtrmit","Sllot","Lhkif","Hkhis","Mzzim","Shlith","Itbcho",
  "Vkhzr","Vhtchvrm","Vshor","Htsib","Lhzik","Hmlikihim","Hsollh",
  "Hchpir","Nchfr","Nschpo","Tchfirihm","Nchshpo","Mgnihm","Shmitm",
  "until-Kvmt","Htsopim","Ntth","Oibtsr","Hhgnh","Omshsotihm",
  "Ochrbnm","Olhtrv","Hnhigm","Oitnpl","Hnhigo","Nftrh","Nmhrt",
  "Thsorrim","all-Chrbnm","Olhshootm","from-Hsvrrym","Hgdm","Ldgl",
  "Htgo","Htsilim","Tknot","Mbrichim","lest-Ykytsv","Kmkin","Lpdion",
  "Ibtsr","not-Hsgyrv","Rnnim","Lhdbikm","Lhtnfl","Nkhnt","Lhsgir",
  "Fkdt","Bchpirt","Chrits","Hchrits","Hpnimit","from-Hchryts",
  "Hkricho","Hkrichom","Bhtkipo","Thskhnh","Btchnoni","Bmtsoktm",
  "Lmts","Onkchim","Rkht","Hmtsfh","if-Tsyrv","if-Tsvgv","Otpkdo",
  "Tdtno","Chlif","Shko","Hzkhim","Skhim","Rmztm","Nrkhh","Tsodkt",
  "Lshchrr","Lhkipm","Nzhro","Lntifos","Otsrf","Mshmidim","Tochltno",
  "Tkvlt","Hmshkno","lest-Ykpv","lest-Yshygvny","Mshigim","Otsrfm",
  "Lhchlif","Lvtsrn","Lhtstrf","Htsv","Mtso","Nltsno","Htprtso",
  "Obmklot","Shloph","Lchrts","Chrtsno","Shlnom","Chto","Bdkdok",
  "Thntschon","Intsl","Tplno","Prtso","Bgdodino","Hzno","Onchkh",
  "Nsbotino","Chkino","Httsvno","Shpkno","Ontchzk","Ontmts",
  "lest-Nkryt","Mstorm","Lhmshkh","Omshktm","Chlsht","Tmkhm",
  "Ochrrno","Chsho","Olnhl","Chrtsh","Frtsh","Nshib","Otshtdlo",
  "Mchkhh","Lkhv","Ottchzko","Ohkplh","Tdbko","Tttsv","Ikbsho",
  "Chrrno","Hshvod","Ntkommh","Lnhl","Vshvod","Hshiro","Nchrtso",
  "Vchshkht","Obslmotihm","Ohrkhh","Rkko","Hntonim","Htrshlo",
  "Htsor","Hpligh","from-Hbvchrym","Lhshlt","Tzko","Tmosdkhm",
  "Hmmo","Shmont","Shrftm","Oichdr","Zhro","Hsbo","Lvth","Klchishh",
  "Olmkr","Mshkilim","Mfshtn","Shzor","Mhshikim","from-Hrshvmvt",
  "Mcholl","Tsdo","Htsnoim","Ohsmkot","Mrshiim","Oitnpch",
  "to-Hshvk","Bgno","Omshtommim","Lptoii","Ipitskm","Otshddo",
  "Omkshibim","Ohtchbrtm","Hgbihh","Ttpsho","Tkchisho","Ndkr",
  "Lsfd","Bkbort","Onshtomm","Mtmihtno","Itnsh","Hkborh","Itpsh",
  "Kshor","Vhskhm","Olspd","Sntom","Rtscht","Tbdko","Hkchish",
  "Hshtfl","lest-Ytkymv","Oishkk","Otshbit","Odgnh","Tshvt","Mgft",
  "Tkshib","Dgnh","Ltslch","Khso","Mhsorrim","Oitchvo","Ttnodt",
  "Obchth","Pchotim","if-Ytmn","Ohpkti","Hgmorh","all-Htvmn",
  "Oitmnm","not-Nmshk","Olhtnpch","Othrgom","Otgrshoho","Omkspkm",
  "Ntst","Tbko","Tspdo","Rgmti","Mtmonino","Chmko","Tzricht",
  "Tshtommo","Otgrshoni","Bsdkim","Khvkh","Tshvrnh","Tkhvdnh",
  "Toklnh","Trmsnh","Otzvnh","Lhrms","Vhminm","Htkimo","Bmsorot",
  "Ktshrim","Otzrch","Kzbim","Lhdich","Zmnm","Tntsch","Lshlomkm",
  "Hndibh","Oshtpino","Ichshko","Lhtsib","Ntmnh","Chlilh","Oibtsro",
  "Obtsnh","Htvch","Nrdf","Hshg","Mdto","Hchitsnim","Tsro","Bshir",
  "Fkfk","Onnsho","Nchrt","Tlmid","from-Hchshbvnvt","Otsts",
  "Ohmmnim","Lmnhigim","Ovhtfrot","Lhtfrk","Olnpchm","Nhno","Onhlh",
  "Olchlts","Mnhig","Khkhlv","Okchzirh","Vrfsh","upon-Hgdvd",
  "Mhshg","Vhttsvo","Nrgm","Zmnno","Lhvk","Chdim","Otshk","Shvrn",
  "Obsdkim","Vkhshlsh","Lmsh","Lhdlik","Orgmno","Ishchk","Htvti",
  "Gmgmno","Shrptim","Obrgmm","Tstrnh","Tkribo","Zbchikm","Mlkonn",
  "Tstsi","Otchdl","Mlhvk","Ohnchot","Rgmom","Vsfh","Ichkr",
  "Obptchon","upon-Shrtv","Hmror","Tmsho","and-all-Hbvnh","Inchmo",
  "Hrchmnim","Ichrpo","Mlch","Tmlch","upon-Hmnvrh","Hmotsh","Mskim",
  "lest-Ytpshk","Thsnin","all-Hmbyt","Lchmd","Lhtnkhr","Ttslvkhm",
  "all-Hmshlch","Thgroshh","do-not-Ttkvmmv","Tkhtntkh",
  "and-all-Hmkrych","Hmlivim","Ohrdpim","Mzrich","do-not-Tchtsrv",
  "Vchtstsrh","Hshokim","do-not-Trbv","do-not-Tdmv","Itkdsh",
  "Rtsonk","Oslch","Slchno","Btsomkm","Tsmim","Btsomk","Tsro",
  "and-[ACC]-Hmmvn","and-how-Tshtv","Lgopkm","Lsmim","Mkhlkhl",
  "Tdgo","Mlbish","Tchtsir","Ltnor","Obmdh","Tmdo",
  "and-do-not-Tshlykv","Hchzirim","Trpim","Hibtsro","Mtsnim",
  "Mdrdrim","Hnpots","Lshrikh","Khmlch","Olhrms","Tslim","Mtsrim",
  "Nkmro","Opschihm","Nkhrti","Thtf","Lfrs","Prsti","Oinshbo",
  "Kchtim","Vminkhm","Ttkbtso","Tgrshom","Tchosho",
  "and-all-Hmpr","Chrm","if-Tshrtvhv","Otshrtoho","Bhtksotm",
  "Oshmnon","Hkhrio","Khlvnm","Thrt","Tkhvd","Ttsm","Hshriot",
  "Lgrn","Krnkh","Ohchrmti","Ttlh","Ikbtsm","Iptscho","Tlkon",
  "Omsfkhm","Vgllm","Rfho","Mrmt","Kkpir","Mrkbotik","Ontshti",
  "Khrit","Ochmh","Msfm","Ptschi","sons-of-Shvmmh","Mshknotik",
  "do-not-Tchshky","that-Ymyn","Tprtsi","and-do-not-Tklmy","Tchpiri",
  "Tshkchi","Kvtskh","Vshtsf","Ktsf","Rchmtik","Mktsf","Mrchmkh",
  "Bspirim","Khdkhd","Chlonik","Mshk","Lmnkh","Nfch","Fchm",
  "Trshii","and-all-Hmkshyb","Nshlmo","Mkbsim","Bmkshpim",
  "Ovmnfim","Thshkhir","and-[ACC]-Hytvm","Nklitm","Gzlnok",
  "Vmshrot","Obchnoni","Ftch","Tchloni","Tshkhl","Gfnkhm","Ohkshib",
  "Otbchino","Ktnor","Izrch","Mkbilim","Lcht","Lvchn","Vchn",
  "Shloshh","and-[ACC]-Pschyhm","Oipkch","Rtsonno","Nbnitm","Kbso",
  "Hshol","Mttsv","what-Tchptsv","Ttmo","Thpko","Khhhfkhm","Hhfkhm",
  "Vhtftm","Obmtsb","and-do-not-Tdmv","if-Tbvzv","Vrfoot","Lhsv",
  "Egyptian(f)"
]);

// Process: find all ["HEBREW","GLOSS"] patterns
// We'll use a regex that captures the Hebrew and the gloss
const pattern = /\["([^"]+)","([^"]+)"\]/g;

let result = html.replace(pattern, function(match, hebrew, gloss) {
  // Check if this gloss is a known bad one
  if (!knownBadGlosses.has(gloss)) {
    return match; // Not a bad gloss, leave it alone
  }

  // Strip niqqud from Hebrew to look up in our dictionary
  let stripped = stripNiqqud(hebrew);

  // Primary lookup: by stripped Hebrew in normalized dictionary
  if (normalizedDict[stripped]) {
    totalReplacements++;
    return '["' + hebrew + '","' + normalizedDict[stripped] + '"]';
  }

  // Fallback lookup: by bad gloss directly
  if (badGlossToGood[gloss]) {
    totalReplacements++;
    return '["' + hebrew + '","' + badGlossToGood[gloss] + '"]';
  }

  // Not found in either dictionary
  return match;
});

// Write the result back
console.log(`Writing fixed BOM.html...`);
fs.writeFileSync(bomPath, result, 'utf8');

// Now count what we actually fixed by doing a second pass to report
console.log(`\nTotal replacements made: ${totalReplacements}`);
console.log('Done! BOM.html has been updated.');

// Verify: check if any bad glosses remain
let remainingBad = 0;
const verifyPattern = /\["([^"]+)","([^"]+)"\]/g;
let m;
while ((m = verifyPattern.exec(result)) !== null) {
  if (knownBadGlosses.has(m[2])) {
    remainingBad++;
    if (remainingBad <= 20) {
      let stripped = stripNiqqud(m[1]);
      console.log(`  Still bad: "${m[1]}" (stripped: "${stripped}") -> "${m[2]}"`);
    }
  }
}
console.log(`\nRemaining bad glosses: ${remainingBad}`);
if (remainingBad > 20) {
  console.log(`  (showing first 20 only)`);
}
