// Final cleanup: fix double prefixes and remaining common bad transliterations
const fs = require('fs');
let bom = fs.readFileSync('BOM.html', 'utf8');

// 1. Fix double prefixes
const doublePrefixes = [
  [/the-the-/g, 'the-'],
  [/and-and-/g, 'and-'],
  [/in-in-/g, 'in-'],
  [/to-to-/g, 'to-'],
  [/from-from-/g, 'from-'],
  [/and-in-the-the-/g, 'and-in-the-'],
  [/and-to-the-the-/g, 'and-to-the-'],
  [/in-the-in-/g, 'in-the-'],
  [/to-the-to-/g, 'to-the-'],
];

let dpCount = 0;
for (const [pat, repl] of doublePrefixes) {
  const matches = bom.match(pat);
  if (matches) dpCount += matches.length;
  bom = bom.replace(pat, repl);
}
console.log(`Fixed ${dpCount} double-prefix occurrences`);

// 2. Fix specific remaining bad transliterations spotted in preview
const specificFixes = [
  // Hebrew word -> [bad gloss pattern, correct gloss]
  ['"Obbtihm"', '"their-houses"'],  // וּבָתֵּיהֶם
  ['"Obtiikm"', '"your-houses"'],
  ['"Obtihm"', '"their-houses"'],
  ['"Lhshchth"', '"to-destruction"'],
  ['"Lhshchit"', '"to-destroy"'],
  ['"Hshlko"', '"they-were-cast-out"'],
  ['"Nbchro"', '"they-were-chosen"'],
  ['"Hkhrchtm"', '"you-were-compelled"'],
  ['"Hkhh"', '"was-smitten"'],
  ['"Hshib"', '"he-restored"'],
  ['"Tkho"', '"they-were-smitten"'],
  ['"Oiptch"', '"and-he-opened"'],
  ['"Oipkd"', '"and-he-appointed"'],
  ['"Hmit"', '"he-put-to-death"'],
  ['"Hbrichm"', '"he-drove-them-away"'],
  ['"Hnicho"', '"they-left"'],
  ['"Hsir"', '"he-removed"'],
  ['"Hsvh"', '"the-cause"'],
  ['"Hmshl"', '"the-ruler"'],
  ['"Khnst"', '"assembly"'],
  ['"Hsoph"', '"the-storm"'],
  ['"Lhvi"', '"to-express"'],
  ['"Ntslno"', '"we-were-saved"'],
  ['"Tkhchsh"', '"you-deny"'],
  ['"Nton"', '"given"'],
  ['"Shlchtm"', '"you-sent"'],
  ['"Shkbim"', '"lying-down"'],
  ['"Lchrot"', '"to-engrave"'],
  ['"Tmno"', '"they-hid"'],
  ['"Khlh"', '"all-of-it(f)"'],
  ['"Bhshib"', '"when-restored"'],
  ['"Vhfrdm"', '"when-they-separated"'],
  ['"Omtpllim"', '"and-praying"'],
  ['"Tsblo"', '"you-shall-suffer"'],
  ['"Bkorintomr"', '"in-Coriantumr"'],
  ['"Shkrm"', '"their-wages"'],
  ['"Mkrb"', '"from-among"'],
  ['"Tmh"', '"wondered"'],
  ['"Pnh"', '"turns"'],
  ['"Chzk"', '"strength"'],
  ['"Dbr"', '"word-of"'],
  ['"Ttn"', '"you-give"'],
  ['"Odbr"', '"and-word-of"'],
  ['"Hshb"', '"restore"'],
  ['"Nshlmh"', '"let-us-make-peace"'],
  ['"Mlk"', '"Melek"'],
  ['"Mshcht"', '"corrupted"'],
  ['"Khnt"', '"priesthood-of"'],
  ['"Bchir"', '"chosen-one"'],
  ['"Snom"', '"Snum"'],
  ['"Shom"', '"any"'],
  ['"Kro"', '"happened"'],
  ['"Lkoot"', '"to-hope"'],
  ['"Hgno"', '"he-protected-us"'],
  ['"Nkhzvh"', '"disappointed"'],
  ['"Shboii"', '"captives-of"'],
  ['"Choshb"', '"thinking"'],
  ['"Kshboii"', '"as-captives-of"'],
  ['"Ltfs"', '"to-seize"'],
  ['"Chno"', '"they-camped"'],
  ['"Hshibh"', '"restore!"'],
  ['"Tpsho"', '"they-seized"'],
  ['"Mtmonio"', '"his-treasures"'],
  ['"Lchlklkot"', '"to-flattery"'],
  ['"Lhtkim"', '"to-be-fulfilled"'],
  ['"Shrpti"', '"I-burned"'],
  ['"Knpih"', '"her-wings"'],
  ['"Ttbilo"', '"you-shall-immerse"'],
  ['"Igmlk"', '"he-shall-reward-you"'],
  ['"Hgshm"', '"the-rain"'],
  ['"Hshtpot"', '"the-floods"'],
  ['"Kklto"', '"when-he-finished"'],
  ['"Chftstm"', '"you-desired"'],
  ['"Nbllo"', '"they-were-confounded"'],
  ['"Igrshno"', '"he-shall-drive-us"'],
  ['"Ibshlo"', '"they-shall-ripen"'],
  ['"Lnshm"', '"to-breathe"'],
  ['"Kdmot"', '"in-likeness-of"'],
  ['"Chtmti"', '"I-sealed"'],
  ['"Iptcho"', '"they-shall-open"'],
  ['"Hsrot"', '"the-storms"'],
  ['"Sbbom"', '"surrounded-them"'],
  ['"Ndchpo"', '"they-were-pushed"'],
  ['"Lhtfsht"', '"to-spread"'],
  ['"Hskimo"', '"they-agreed"'],
  ['"Hmshkr"', '"the-liar"'],
  ['"Rchm"', '"he-had-mercy"'],
  ['"Chtno"', '"his-father-in-law"'],
  ['"Mshcho"', '"his-anointing"'],
  ['"Htpshto"', '"they-spread-out"'],
  ['"Hrsiim"', '"the-poisonous"'],
  ['"Mflgt"', '"exceeding"'],
  ['"Chch"', '"alas"'],
  ['"Hkdmonh"', '"the-ancient"'],
  ['"Kmnor"', '"Comnor"'],
  ['"Ntkimo"', '"they-were-fulfilled"'],
  ['"Lchtso"', '"they-oppressed"'],
  ['"Hvdl"', '"separation"'],
  ['"Nnsho"', '"they-were-punished"'],
  ['"Lmkot"', '"to-smite"'],
  ['"Oitchmsho"', '"and-they-armed"'],
  ['"Lntot"', '"to-incline"'],
  ['"Oltmhonno"', '"and-to-our-astonishment"'],
  ['"Shrionm"', '"their-armor"'],
  ['"Lhkhshl"', '"to-stumble"'],
  ['"Mtspim"', '"watching"'],
  ['"Htsil"', '"he-delivered"'],
  ['"Hshh"', '"the-hour"'],
  ['"Tsmti"', '"I-fasted"'],
  ['"Htsrr"', '"the-adversary"'],
  ['"Lhtfl"', '"to-marvel"'],
  ['"Khmdt"', '"according-to-measure"'],
  ['"Khmshkl"', '"as-the-weight-of"'],
  ['"Lchshbonm"', '"to-their-account"'],
  ['"Shmto"', '"his-guilt"'],
  ['"Hmthfkht"', '"the-turning"'],
  ['"Tsholh"', '"Shule"'],
  ['"Tshrd"', '"Shared"'],
  ['"Vnkhom"', '"son-of-Com"'],
  // More common ones
  ['"Lhshmd"', '"to-destroy"'],
  ['"Hshmdo"', '"they-were-destroyed"'],
  ['"Hshmido"', '"they-destroyed"'],
  ['"Hshlkho"', '"they-cast-out"'],
  ['"Hkniho"', '"they-subdued"'],
  ['"Nlkdo"', '"they-were-captured"'],
  ['"Npkdo"', '"they-were-numbered"'],
  ['"Nkrto"', '"they-were-cut-off"'],
  ['"Nshmo"', '"they-were-heard"'],
  ['"Nlkcho"', '"they-were-taken"'],
  ['"Nbdlo"', '"they-were-separated"'],
  ['"Nhrso"', '"they-were-destroyed"'],
  ['"Ntno"', '"was-given"'],
  ['"Nmtso"', '"they-were-found"'],
  ['"Nshbo"', '"they-swore"'],
  ['"Oitchzko"', '"and-they-strengthened"'],
  ['"Oithnno"', '"and-they-beseeched"'],
  ['"Oitstro"', '"and-they-hid"'],
  ['"Oitpso"', '"and-they-seized"'],
  ['"Oitbonno"', '"and-they-pondered"'],
  ['"Oitnbאo"', '"and-they-prophesied"'],
  ['"Oitnbo"', '"and-they-prophesied"'],
  ['"Oitzkro"', '"and-they-remembered"'],
  ['"Oishtchoo"', '"and-they-worshipped"'],
  ['"Oibko"', '"and-they-wept"'],
  ['"Oitslbo"', '"and-they-crossed"'],
  ['"Oitpllo"', '"and-they-prayed"'],
  ['"Oitpll"', '"and-he-prayed"'],
  ['"Oitkdsho"', '"and-they-sanctified"'],
  ['"Oishpto"', '"and-they-judged"'],
  ['"Obrko"', '"and-they-blessed"'],
  ['"Htlbsh"', '"he-clothed"'],
  ['"Hmshik"', '"he-continued"'],
  ['"Htslich"', '"he-succeeded"'],
  ['"Hrshio"', '"he-acted-wickedly"'],
  ['"Hrbh"', '"he-multiplied"'],
  ['"Hkrit"', '"he-cut-off"'],
  ['"Hshlik"', '"he-cast-out"'],
  ['"Hlchmo"', '"his-fighting"'],
  ['"Mlchmt"', '"war"'],
  ['"Ohthlko"', '"and-they-went"'],
  ['"Chloshotihm"', '"their-weakness"'],
  ['"Chlshtm"', '"their-weakness"'],
  ['"Chlshto"', '"his-weakness"'],
  ['"Chlshti"', '"my-weakness"'],
  ['"Omshpchotihm"', '"and-their-families"'],
  ['"Omshpchotikm"', '"and-your-families"'],
];

let sfCount = 0;
for (const [bad, good] of specificFixes) {
  while (bom.includes(bad)) {
    bom = bom.replace(bad, good);
    sfCount++;
  }
}
console.log(`Fixed ${sfCount} specific transliteration occurrences`);

fs.writeFileSync('BOM.html', bom, 'utf8');
console.log('Done!');
