// generated by tools/build_crossref_chunks.js — _bomInverseXrefsData for jarom
(function(){ var W = window;
  Object.assign(W._bomInverseXrefsData = W._bomInverseXrefsData || {}, {"Jarom|1|5":[{"displayRef":"Ex. 35:2","sourceKey":"Exodus|35|2","anchorText":"sabbath","marker":"c","volumeTag":"OT","dedupeId":"Exodus|35|2|c|sabbath"}],"Jarom|1|9":[{"displayRef":"Josh. 1:7","sourceKey":"Joshua|1|7","anchorText":"prosper","marker":"b","volumeTag":"OT","dedupeId":"Joshua|1|7|b|prosper"},{"displayRef":"Ps. 122:6","sourceKey":"Psalms|122|6","anchorText":"prosper","marker":"a","volumeTag":"OT","dedupeId":"Psalms|122|6|a|prosper"}]});
  if (typeof W.__swCrossrefsArrived === 'function') W.__swCrossrefsArrived();
})();
