// generated by tools/build_heading_manifests.js — chapter summaries for phm.js
(function(){ var W = window;
  Object.assign(W._ntChapterHeadings = W._ntChapterHeadings || {}, {"Philemon 1":"The gospel changes a servant into a brother."});
  Object.assign(W._ntChapterHeadingsHeb = W._ntChapterHeadingsHeb || {}, {"Philemon 1":"הבשורה משנה משרת לאח"});
  Object.assign(W._ntHeadingWords = W._ntHeadingWords || {}, {"Philemon 1":[["הַבְּשׂוֹרָה","the gospel"],["מִשְׁנֶה","double"],["מְשָׁרֵת","a minister"],["לְאָח","to-a-brother"],["׃",""]]});
})();
