// ot_verses/amo.js — Amos verse data
(function() {
var amo_ch1Verses = [
  { num:"א", words:[["דִּבְרֵי","account-of"],["עָמוֹס","Amos"],["אֲשֶׁר־הָיָה","whose-was"],["בַנֹּקְדִים","among the-sheep-tenders"],["מִתְּקוֹעַ","from-Tekoa"],["אֲשֶׁר","which"],["חָזָה","saw"],["עַל־יִשְׂרָאֵל","upon-Israel"],["בִּימֵי","in-days-of"],["עֻזִּיָּה","Uzziah"],["מֶלֶךְ־יְהוּדָה","king-of-Judah"],["וּבִימֵי","and-in-the-days-of"],["יָרׇבְעָם","Jeroboam"],["בֶּן־יוֹאָשׁ","son-of-Joash"],["מֶלֶךְ","the-king-of"],["יִשְׂרָאֵל","Israel"],["שְׁנָתַיִם","two-years"],["לִפְנֵי","before"],["הָרָעַשׁ","the-earthquake"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמַר","and-said"],["יְהֹוָה","the-LORD"],["מִצִּיּוֹן","out-of-Zion"],["יִשְׁאָג","he will roar"],["וּמִירוּשָׁלַ͏ִם","and-from-Jerusalem"],["יִתֵּן","shall-give"],["קוֹלוֹ","His-voice"],["וְאָבְלוּ","and-mourn"],["נְאוֹת","the pastures of"],["הָרֹעִים","the-shepherds"],["וְיָבֵשׁ","and-it is dry"],["רֹאשׁ","the-head-of"],["הַכַּרְמֶל","the-Carmel"],["׃",""]] },
  { num:"ג", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["עַל־שְׁלֹשָׁה","upon-three"],["פִּשְׁעֵי","transgressions-of"],["דַמֶּשֶׂק","Damascus"],["וְעַל־אַרְבָּעָה","and-upon-four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will bring back-him"],["עַל־דּוּשָׁם","upon-threshed-they"],["בַּחֲרֻצוֹת","with-the threshing sledges of"],["הַבַּרְזֶל","the-iron"],["אֶת־הַגִּלְעָד","[ACC]-the-Gilead"],["׃",""]] },
  { num:"ד", words:[["וְשִׁלַּחְתִּי","and-I will send"],["אֵשׁ","fire"],["בְּבֵית","in-house-of"],["חֲזָאֵל","Hazael"],["וְאָכְלָה","and-shall-devour"],["אַרְמְנוֹת","the fortresses of"],["בֶּן־הֲדָד","son-of-Hadad"],["׃",""]] },
  { num:"ה", words:[["וְשָׁבַרְתִּי","and-I will break"],["בְּרִיחַ","a bar"],["דַּמֶּשֶׂק","Damascus"],["וְהִכְרַתִּי","and-cut-off"],["יוֹשֵׁב","sitting"],["מִבִּקְעַת־אָוֶן","from-the Valley of-iniquity"],["וְתוֹמֵךְ","and-a holder of"],["שֵׁבֶט","the-rod-of"],["מִבֵּית","from-house-of"],["עֶדֶן","Eden"],["וְגָלוּ","and-they will go into exile"],["עַם־אֲרָם","people-Aram"],["קִירָה","Kir-towards"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ו", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["עַל־שְׁלֹשָׁה","upon-three"],["פִּשְׁעֵי","transgressions-of"],["עַזָּה","exceedingly"],["וְעַל־אַרְבָּעָה","and-upon-four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will bring back-him"],["עַל־הַגְלוֹתָם","upon-carried away into exile-they"],["גָּלוּת","the exiles of"],["שְׁלֵמָה","complete/perfect"],["לְהַסְגִּיר","to-deliver-up"],["לֶאֱדוֹם","of-Edom"],["׃",""]] },
  { num:"ז", words:[["וְשִׁלַּחְתִּי","and-I will send"],["אֵשׁ","fire"],["בְּחוֹמַת","in-the-walls-of"],["עַזָּה","exceedingly"],["וְאָכְלָה","and-shall-devour"],["אַרְמְנֹתֶיהָ","fortresses-its"],["׃",""]] },
  { num:"ח", words:[["וְהִכְרַתִּי","and-cut-off"],["יוֹשֵׁב","sitting"],["מֵאַשְׁדּוֹד","from-Ashdod"],["וְתוֹמֵךְ","and-a holder of"],["שֵׁבֶט","the-rod-of"],["מֵאַשְׁקְלוֹן","from-Ashkelon"],["וַהֲשִׁיבוֹתִי","and-I will turn"],["יָדִי","my-hand"],["עַל־עֶקְרוֹן","upon-Ekron"],["וְאָבְדוּ","and-were-lost"],["שְׁאֵרִית","remnant-of"],["פְּלִשְׁתִּים","Philistines"],["אָמַר","said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["׃",""]] },
  { num:"ט", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["עַל־שְׁלֹשָׁה","upon-three"],["פִּשְׁעֵי־צֹר","transgressions-of-a flint"],["וְעַל־אַרְבָּעָה","and-upon-four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will bring back-him"],["עַל־הַסְגִּירָם","upon-delivered up-they"],["גָּלוּת","the exiles of"],["שְׁלֵמָה","complete/perfect"],["לֶאֱדוֹם","of-Edom"],["וְלֹא","and-not"],["זָכְרוּ","they-remembered"],["בְּרִית","covenant-of"],["אַחִים","brothers"],["׃",""]] },
  { num:"י", words:[["וְשִׁלַּחְתִּי","and-I will send"],["אֵשׁ","fire"],["בְּחוֹמַת","in-the-walls-of"],["צֹר","a flint"],["וְאָכְלָה","and-shall-devour"],["אַרְמְנוֹתֶיהָ","palaces-its"],["׃",""]] },
  { num:"יא", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["עַל־שְׁלֹשָׁה","upon-three"],["פִּשְׁעֵי","transgressions-of"],["אֱדוֹם","Edom"],["וְעַל־אַרְבָּעָה","and-upon-four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will bring back-him"],["עַל־רׇדְפוֹ","upon-pursued-he"],["בַחֶרֶב","by-the-sword"],["אָחִיו","another"],["וְשִׁחֵת","and-he spoiled"],["רַחֲמָיו","His-mercy"],["וַיִּטְרֹף","and-it tore"],["לָעַד","forever"],["אַפּוֹ","His-wrath"],["וְעֶבְרָתוֹ","and-fury-his"],["שְׁמָרָהֿ","he kept-it"],["נֶצַח","eternal"],["׃",""]] },
  { num:"יב", words:[["וְשִׁלַּחְתִּי","and-I will send"],["אֵשׁ","fire"],["בְּתֵימָן","in-Teman"],["וְאָכְלָה","and-shall-devour"],["אַרְמְנוֹת","the fortresses of"],["בׇּצְרָה","sheep fold"],["׃",""]] },
  { num:"יג", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["עַל־שְׁלֹשָׁה","upon-three"],["פִּשְׁעֵי","transgressions-of"],["בְנֵי־עַמּוֹן","sons-of-Ammon"],["וְעַל־אַרְבָּעָה","and-upon-four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will bring back-him"],["עַל־בִּקְעָם","upon-ripped open-they"],["הָרוֹת","with-the-child"],["הַגִּלְעָד","the-Gilead"],["לְמַעַן","in-order-that"],["הַרְחִיב","to enlarge"],["אֶת־גְּבוּלָם","[ACC]-territory-their"],["׃",""]] },
  { num:"יד", words:[["וְהִצַּתִּי","and-I will kindle"],["אֵשׁ","fire"],["בְּחוֹמַת","in-the-walls-of"],["רַבָּה","much"],["וְאָכְלָה","and-shall-devour"],["אַרְמְנוֹתֶיהָ","palaces-its"],["בִּתְרוּעָה","with-shouting"],["בְּיוֹם","in-day-of"],["מִלְחָמָה","war"],["בְּסַעַר","with-a storm"],["בְּיוֹם","in-day-of"],["סוּפָה","a storm-wind"],["׃",""]] },
  { num:"טו", words:[["וְהָלַךְ","and-go"],["מַלְכָּם","their-king"],["בַּגּוֹלָה","in the-exile"],["הוּא","it"],["וְשָׂרָיו","and-their-princes"],["יַחְדָּו","together"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["׃",""]] },
];
renderVerseSet(amo_ch1Verses, 'amo-ch1-verses');

var amo_ch2Verses = [
  { num:"א", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["עַל־שְׁלֹשָׁה","upon-three"],["פִּשְׁעֵי","transgressions-of"],["מוֹאָב","Moab"],["וְעַל־אַרְבָּעָה","and-upon-four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will bring back-him"],["עַל־שׇׂרְפוֹ","upon-burned-he"],["עַצְמוֹת","the bones of"],["מֶלֶךְ־אֱדוֹם","king-of-Edom"],["לַשִּׂיד","into-the-lime"],["׃",""]] },
  { num:"ב", words:[["וְשִׁלַּחְתִּי־אֵשׁ","and-I will send-fire"],["בְּמוֹאָב","against-Moab"],["וְאָכְלָה","and-shall-devour"],["אַרְמְנוֹת","the fortresses of"],["הַקְּרִיּוֹת","the-Kerioth"],["וּמֵת","and-he will die"],["בְּשָׁאוֹן","in-uproar"],["מוֹאָב","Moab"],["בִּתְרוּעָה","with-shouting"],["בְּקוֹל","the-voice-of"],["שׁוֹפָר","a ram's horn"],["׃",""]] },
  { num:"ג", words:[["וְהִכְרַתִּי","and-cut-off"],["שׁוֹפֵט","the-judge"],["מִקִּרְבָּהּ","from-her-midst"],["וְכׇל־שָׂרֶיהָ","and-all-princes-its"],["אֶהֱרוֹג","I will kill"],["עִמּוֹ","with-him"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ד", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["עַל־שְׁלֹשָׁה","upon-three"],["פִּשְׁעֵי","transgressions-of"],["יְהוּדָה","Judah"],["וְעַל־אַרְבָּעָה","and-upon-four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will bring back-him"],["עַל־מׇאֳסָם","upon-their-rejecting"],["אֶת־תּוֹרַת","[ACC] the-law-of"],["יְהֹוָה","the-LORD"],["וְחֻקָּיו","and-statutes-his"],["לֹא","not"],["שָׁמָרוּ","they kept"],["וַיַּתְעוּם","and-they have misled-them"],["כִּזְבֵיהֶם","lies-their"],["אֲשֶׁר־הָלְכוּ","whose-went"],["אֲבוֹתָם","their-fathers"],["אַחֲרֵיהֶם","after-them"],["׃",""]] },
  { num:"ה", words:[["וְשִׁלַּחְתִּי","and-I will send"],["אֵשׁ","fire"],["בִּיהוּדָה","through-Judah"],["וְאָכְלָה","and-shall-devour"],["אַרְמְנוֹת","the fortresses of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["׃",""]] },
  { num:"ו", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["עַל־שְׁלֹשָׁה","upon-three"],["פִּשְׁעֵי","transgressions-of"],["יִשְׂרָאֵל","Israel"],["וְעַל־אַרְבָּעָה","and-upon-four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will bring back-him"],["עַל־מִכְרָם","upon-price-their"],["בַּכֶּסֶף","in-the-silver"],["צַדִּיק","righteous"],["וְאֶבְיוֹן","and-needy"],["בַּעֲבוּר","because-of"],["נַעֲלָיִם","a pair of sandals"],["׃",""]] },
  { num:"ז", words:[["הַשֹּׁאֲפִים","the-those-who trample"],["עַל־עֲפַר־אֶרֶץ","upon-ore-land-of"],["בְּרֹאשׁ","in-the-gall-of"],["דַּלִּים","the-poor"],["וְדֶרֶךְ","and-the-way-of"],["עֲנָוִים","the-meek"],["יַטּוּ","they-shall-turn"],["וְאִישׁ","and-the-man-of"],["וְאָבִיו","and-father-his"],["יֵלְכוּ","they-should-travel"],["אֶל־הַנַּעֲרָה","to-the-young woman"],["לְמַעַן","in-order-that"],["חַלֵּל","to profane"],["אֶת־שֵׁם","ACC-name-of"],["קׇדְשִׁי","the holy things of"],["׃",""]] },
  { num:"ח", words:[["וְעַל־בְּגָדִים","and-upon-garments"],["חֲבֻלִים","taken in pledge"],["יַטּוּ","they-shall-turn"],["אֵצֶל","near"],["כׇּל־מִזְבֵּחַ","all-an altar"],["וְיֵין","and-wine of"],["עֲנוּשִׁים","fines"],["יִשְׁתּוּ","they-drink"],["בֵּית","the-house-of"],["אֱלֹהֵיהֶם","their-God"],["׃",""]] },
  { num:"ט", words:[["וְאָנֹכִי","yet-I"],["הִשְׁמַדְתִּי","I destroyed"],["אֶת־הָאֱמֹרִי","[ACC]-the-Amorites"],["מִפְּנֵיהֶם","from-before-them"],["אֲשֶׁר","which"],["כְּגֹבַהּ","according to-the haughtiness of"],["אֲרָזִים","cedars"],["גׇּבְהוֹ","tall of-his"],["וְחָסֹן","and-is strong"],["הוּא","it"],["כָּאַלּוֹנִים","like-oaks"],["וָאַשְׁמִיד","and-I destroyed"],["פִּרְיוֹ","was-his-fruit"],["מִמַּעַל","above"],["וְשׇׁרָשָׁיו","and-roots-its"],["מִתָּחַת","beneath"],["׃",""]] },
  { num:"י", words:[["וְאָנֹכִי","yet-I"],["הֶעֱלֵיתִי","I brought up"],["אֶתְכֶם","you"],["מֵאֶרֶץ","from-land-of"],["מִצְרָיִם","Egypt"],["וָאוֹלֵךְ","and-I made walk"],["אֶתְכֶם","you"],["בַּמִּדְבָּר","in-the-wilderness"],["אַרְבָּעִים","forty"],["שָׁנָה","year"],["לָרֶשֶׁת","to-possess"],["אֶת־אֶרֶץ","ACC-land-of"],["הָאֱמֹרִי","the-Amorites"],["׃",""]] },
  { num:"יא", words:[["וָאָקִים","and-I raised up"],["מִבְּנֵיכֶם","some of-sons-your"],["לִנְבִיאִים","to-prophets"],["וּמִבַּחוּרֵיכֶם","and-some of-young men-your"],["לִנְזִרִים","to-Nazirites"],["הַאַף","¿-also"],["אֵין־זֹאת","there-is-no-this"],["בְּנֵי","the-sons-of"],["יִשְׂרָאֵל","Israel"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"יב", words:[["וַתַּשְׁקוּ","and-you made drink"],["אֶת־הַנְּזִרִים","[ACC]-the-Nazirites"],["יָיִן","wine"],["וְעַל־הַנְּבִיאִים","and-upon-the-prophets"],["צִוִּיתֶם","you commanded"],["לֵאמֹר","saying"],["לֹא","not"],["תִּנָּבְאוּ","you must prophesy"],["׃",""]] },
  { num:"יג", words:[["הִנֵּה","behold"],["אָנֹכִי","I"],["מֵעִיק","am about to make totter"],["תַּחְתֵּיכֶם","under-you"],["כַּאֲשֶׁר","when/as"],["תָּעִיק","it totters"],["הָעֲגָלָה","the-a-cart"],["הַמְלֵאָה","the-full produce"],["לָהּ","it"],["עָמִיר","cut grain"],["׃",""]] },
  { num:"יד", words:[["וְאָבַד","and-lost"],["מָנוֹס","deliverance"],["מִקָּל","from-a swift person"],["וְחָזָק","and-mighty"],["לֹא־יְאַמֵּץ","not-he will make firm"],["כֹּחוֹ","His-power"],["וְגִבּוֹר","and-mighty"],["לֹא־יְמַלֵּט","not-he delivers"],["נַפְשׁוֹ","his-soul"],["׃",""]] },
  { num:"טו", words:[["וְתֹפֵשׂ","and-one who wields"],["הַקֶּשֶׁת","the-a-bow"],["לֹא","not"],["יַעֲמֹד","shall-stand"],["וְקַל","and-a person swift"],["בְּרַגְלָיו","his-feet"],["לֹא","not"],["יְמַלֵּט","he delivers"],["וְרֹכֵב","and-the rider of"],["הַסּוּס","the-horses"],["לֹא","not"],["יְמַלֵּט","he delivers"],["נַפְשׁוֹ","his-soul"],["׃",""]] },
  { num:"טז", words:[["וְאַמִּיץ","and-strong of"],["לִבּוֹ","his-heart"],["בַּגִּבּוֹרִים","among the-mighty ones"],["עָרוֹם","certainly"],["יָנוּס","flee"],["בַּיּוֹם־הַהוּא","in-the-day-that"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
];
renderVerseSet(amo_ch2Verses, 'amo-ch2-verses');

var amo_ch3Verses = [
  { num:"א", words:[["שִׁמְעוּ","hear"],["אֶת־הַדָּבָר","[ACC]-the-word"],["הַזֶּה","this"],["אֲשֶׁר","which"],["דִּבֶּר","spoke"],["יְהֹוָה","the-LORD"],["עֲלֵיכֶם","over-you"],["בְּנֵי","the-sons-of"],["יִשְׂרָאֵל","Israel"],["עַל","upon"],["כׇּל־הַמִּשְׁפָּחָה","all-the-clan"],["אֲשֶׁר","which"],["הֶעֱלֵיתִי","I brought up"],["מֵאֶרֶץ","from-land-of"],["מִצְרַיִם","Egypt"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ב", words:[["רַק","only"],["אֶתְכֶם","you"],["יָדַעְתִּי","I-know"],["מִכֹּל","of-all"],["מִשְׁפְּחוֹת","kindreds-of"],["הָאֲדָמָה","the-earth"],["עַל־כֵּן","therefore"],["אֶפְקֹד","will-I-visit-them"],["עֲלֵיכֶם","over-you"],["אֵת","[ACC]"],["כׇּל־עֲוֺנֹתֵיכֶם","all-iniquities-your"],["׃",""]] },
  { num:"ג", words:[["הֲיֵלְכוּ","¿-do they walk"],["שְׁנַיִם","years"],["יַחְדָּו","together"],["בִּלְתִּי","except"],["אִם־נוֹעָדוּ","if-they have met by appointment"],["׃",""]] },
  { num:"ד", words:[["הֲיִשְׁאַג","¿-does it roar"],["אַרְיֵה","a lion"],["בַּיַּעַר","in-the-forest"],["וְטֶרֶף","and-he-tears"],["אֵין","there-is-no"],["לוֹ","him"],["הֲיִתֵּן","¿-does it give forth"],["כְּפִיר","a young lion of"],["קוֹלוֹ","His-voice"],["מִמְּעֹנָתוֹ","from-den-its"],["בִּלְתִּי","except"],["אִם־לָכָד","if-it has caught something"],["׃",""]] },
  { num:"ה", words:[["הֲתִפֹּל","¿-does it fall"],["צִפּוֹר","bird"],["עַל־פַּח","upon-a snare"],["הָאָרֶץ","the-earth"],["וּמוֹקֵשׁ","and-is a snare"],["אֵין","there-is-no"],["לָהּ","it"],["הֲיַעֲלֶה־פַּח","¿-does it go up-a snare"],["מִן־הָאֲדָמָה","from-the-ground"],["וְלָכוֹד","and-surely"],["לֹא","not"],["יִלְכּוֹד","it catches something"],["׃",""]] },
  { num:"ו", words:[["אִם־יִתָּקַע","if-it will be blown"],["שׁוֹפָר","a ram's horn"],["בְּעִיר","in-the-city-of"],["וְעָם","and-people"],["לֹא","not"],["יֶחֱרָדוּ","they tremble"],["אִם־תִּהְיֶה","if-shall-be"],["רָעָה","evil"],["בְּעִיר","in-the-city-of"],["וַיהֹוָה","and-Yahweh"],["לֹא","not"],["עָשָׂה","he-made"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["לֹא","not"],["יַעֲשֶׂה","he-shall-do"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["דָּבָר","things"],["כִּי","because"],["אִם־גָּלָה","if-are-gone-into-captivity"],["סוֹדוֹ","His-counsel"],["אֶל־עֲבָדָיו","to-His-servants"],["הַנְּבִיאִים","the-prophets"],["׃",""]] },
  { num:"ח", words:[["אַרְיֵה","a lion"],["שָׁאָג","it has roared"],["מִי","who"],["לֹא","not"],["יִירָא","it will fear"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["דִּבֶּר","spoke"],["מִי","who"],["לֹא","not"],["יִנָּבֵא","he prophesies"],["׃",""]] },
  { num:"ט", words:[["הַשְׁמִיעוּ","tell"],["עַל־אַרְמְנוֹת","upon-the fortresses of"],["בְּאַשְׁדּוֹד","in-Ashdod"],["וְעַל־אַרְמְנוֹת","and-upon-the fortresses of"],["בְּאֶרֶץ","in-land-of"],["מִצְרָיִם","Egypt"],["וְאִמְרוּ","and-say"],["הֵאָסְפוּ","gather yourselves"],["עַל־הָרֵי","upon-the mountains of"],["שֹׁמְרוֹן","Samaria"],["וּרְאוּ","and-see"],["מְהוּמֹת","disturbances"],["רַבּוֹת","many"],["בְּתוֹכָהּ","in-its-midst"],["וַעֲשׁוּקִים","and-oppression"],["בְּקִרְבָּהּ","in-inner being-her"],["׃",""]] },
  { num:"י", words:[["וְלֹא־יָדְעוּ","and-not-they-knew"],["עֲשׂוֹת־נְכֹחָה","do-straightforwardness"],["נְאֻם־יְהֹוָה","says-the-LORD"],["הָאוֹצְרִים","the-those-who store up"],["חָמָס","violence"],["וָשֹׁד","and-havoc"],["בְּאַרְמְנוֹתֵיהֶם","in-fortresses-their"],["׃",""]] },
  { num:"יא", words:[["לָכֵן","therefore"],["כֹּה","thus"],["אָמַר","said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["צַר","narrow/enemy"],["וּסְבִיב","and-around"],["הָאָרֶץ","the-earth"],["וְהוֹרִיד","and-lead-down"],["מִמֵּךְ","from-you"],["עֻזֵּךְ","your-strength"],["וְנָבֹזּוּ","and-they will be plundered"],["אַרְמְנוֹתָיִךְ","fortresses-your"],["׃",""]] },
  { num:"יב", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["כַּאֲשֶׁר","when/as"],["יַצִּיל","shall-deliver"],["הָרֹעֶה","the-shepherd"],["מִפִּי","from-mouth-of"],["הָאֲרִי","the-lion"],["שְׁתֵּי","two"],["כְרָעַיִם","legs"],["אוֹ","or"],["בְדַל־אֹזֶן","a piece of-an-ear"],["כֵּן","thus"],["יִנָּצְלוּ","need-not-fear"],["בְּנֵי","the-sons-of"],["יִשְׂרָאֵל","Israel"],["הַיֹּשְׁבִים","the-inhabitants"],["בְּשֹׁמְרוֹן","in-Samaria"],["בִּפְאַת","with-a corner of"],["מִטָּה","a bed"],["וּבִדְמֶשֶׁק","and-with-silk of"],["עָרֶשׂ","a couch"],["׃",""]] },
  { num:"יג", words:[["שִׁמְעוּ","hear"],["וְהָעִידוּ","and-the-testified-his"],["בְּבֵית","in-house-of"],["יַעֲקֹב","Jacob"],["נְאֻם־אֲדֹנָי","says-Lord"],["יֱהֹוִה","Yahweh"],["אֱלֹהֵי","the-God-of"],["הַצְּבָאוֹת","the-of-Hosts"],["׃",""]] },
  { num:"יד", words:[["כִּי","because"],["בְּיוֹם","in-day-of"],["פׇּקְדִי","enroll-my"],["פִשְׁעֵי־יִשְׂרָאֵל","the transgressions of-Israel"],["עָלָיו","upon-him"],["וּפָקַדְתִּי","I-will-visit-them"],["עַל־מִזְבְּחוֹת","upon-altars"],["בֵּית־אֵל","Bethel"],["וְנִגְדְּעוּ","and-they will be cut down"],["קַרְנוֹת","the horns of"],["הַמִּזְבֵּחַ","the-altar"],["וְנָפְלוּ","and-fall-shall-they"],["לָאָרֶץ","to-the-ground"],["׃",""]] },
  { num:"טו", words:[["וְהִכֵּיתִי","and-I-was-smitten"],["בֵית־הַחֹרֶף","house-of-the-winter"],["עַל־בֵּית","to-the-house-of"],["הַקָּיִץ","the-summer"],["וְאָבְדוּ","and-were-lost"],["בָּתֵּי","in-twain"],["הַשֵּׁן","the-Shen"],["וְסָפוּ","and-people will snatch away"],["בָּתִּים","buildings"],["רַבִּים","many"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
];
renderVerseSet(amo_ch3Verses, 'amo-ch3-verses');

var amo_ch4Verses = [
  { num:"א", words:[["שִׁמְעוּ","hear"],["הַדָּבָר","the-thing"],["הַזֶּה","this"],["פָּרוֹת","cows"],["הַבָּשָׁן","the-Bashan"],["אֲשֶׁר","which"],["בְּהַר","while-on-the-mount-of"],["שֹׁמְרוֹן","Samaria"],["הָעֹשְׁקוֹת","the-who-oppress"],["דַּלִּים","the-poor"],["הָרֹצְצוֹת","the-who-crush"],["אֶבְיוֹנִים","beggars"],["הָאֹמְרֹת","the-who-say"],["לַאֲדֹנֵיהֶם","to-master-their"],["הָבִיאָה","bring-!"],["וְנִשְׁתֶּה","and-drink"],["׃",""]] },
  { num:"ב", words:[["נִשְׁבַּע","swore"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["בְּקׇדְשׁוֹ","in the-holy place-his"],["כִּי","because"],["הִנֵּה","behold"],["יָמִים","days"],["בָּאִים","come"],["עֲלֵיכֶם","over-you"],["וְנִשָּׂא","and-exalted"],["אֶתְכֶם","you"],["בְּצִנּוֹת","with-barbs"],["וְאַחֲרִיתְכֶן","and-posterity-your"],["בְּסִירוֹת","with-hooks of"],["דּוּגָה","fishing"],["׃",""]] },
  { num:"ג", words:[["וּפְרָצִים","and-breaches"],["תֵּצֶאנָה","you will go out"],["אִשָּׁה","a-woman"],["נֶגְדָּהּ","before-herself"],["וְהִשְׁלַכְתֶּנָה","and-you will throw"],["הַהַרְמוֹנָה","Harmon-towards"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"ד", words:[["בֹּאוּ","come"],["בֵית־אֵל","house-of-God"],["וּפִשְׁעוּ","and-transgress"],["הַגִּלְגָּל","the-Gilgal"],["הַרְבּוּ","increase"],["לִפְשֹׁעַ","to-transgress"],["וְהָבִיאוּ","and-bring"],["לַבֹּקֶר","to the-morning"],["זִבְחֵיכֶם","your-sacrifices"],["לִשְׁלֹשֶׁת","to-three"],["יָמִים","days"],["מַעְשְׂרֹתֵיכֶם","tithes-your"],["׃",""]] },
  { num:"ה", words:[["וְקַטֵּר","and-will you make smoke?"],["מֵחָמֵץ","from-a thing leavened"],["תּוֹדָה","thanksgiving"],["וְקִרְאוּ","and-call"],["נְדָבוֹת","voluntariness"],["הַשְׁמִיעוּ","tell"],["כִּי","because"],["כֵן","thus"],["אֲהַבְתֶּם","you love"],["בְּנֵי","the-sons-of"],["יִשְׂרָאֵל","Israel"],["נְאֻם","says"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["׃",""]] },
  { num:"ו", words:[["וְגַם־אֲנִי","and-also-I"],["נָתַתִּי","I-gave"],["לָכֶם","to-you"],["נִקְיוֹן","cleanness of"],["שִׁנַּיִם","years"],["בְּכׇל־עָרֵיכֶם","in-all-cities-of-you"],["וְחֹסֶר","and-the-lack-of"],["לֶחֶם","bread"],["בְּכֹל","in-all"],["מְקוֹמֹתֵיכֶם","places-your"],["וְלֹא־שַׁבְתֶּם","and-not-repent"],["עָדַי","to-me"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"ז", words:[["וְגַם","and-also"],["אָנֹכִי","I"],["מָנַעְתִּי","I withheld them"],["מִכֶּם","from-you"],["אֶת־הַגֶּשֶׁם","[ACC]-the-rain"],["בְּעוֹד","in-yet"],["שְׁלֹשָׁה","three"],["חֳדָשִׁים","months"],["לַקָּצִיר","were to the-harvest"],["וְהִמְטַרְתִּי","and-I sent rain"],["עַל־עִיר","upon-city-of"],["אֶחָת","one"],["וְעַל־עִיר","and-upon-city-of"],["אַחַת","one"],["לֹא","not"],["אַמְטִיר","I will rain down"],["חֶלְקָה","portion of land"],["אַחַת","one"],["תִּמָּטֵר","it was rained on"],["וְחֶלְקָה","and-a portion of ground"],["אֲשֶׁר־לֹא־תַמְטִיר","whose-not-it sent rain"],["עָלֶיהָ","upon-it"],["תִּיבָשׁ","it will wither"],["׃",""]] },
  { num:"ח", words:[["וְנָעוּ","and-they will tremble"],["שְׁתַּיִם","two"],["שָׁלֹשׁ","for-the-space-of-three"],["עָרִים","large-cities"],["אֶל־עִיר","unto-city-of"],["אַחַת","one"],["לִשְׁתּוֹת","to-drink"],["מַיִם","water"],["וְלֹא","and-not"],["יִשְׂבָּעוּ","they will be satisfied"],["וְלֹא־שַׁבְתֶּם","and-not-repent"],["עָדַי","to-me"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"ט", words:[["הִכֵּיתִי","I-was-smitten"],["אֶתְכֶם","you"],["בַּשִּׁדָּפוֹן","with-the-blight"],["וּבַיֵּרָקוֹן","and-with-the-mildew"],["הַרְבּוֹת","to increase"],["גַּנּוֹתֵיכֶם","gardens-your"],["וְכַרְמֵיכֶם","and-vineyards-your"],["וּתְאֵנֵיכֶם","and-fig trees-your"],["וְזֵיתֵיכֶם","and-olive groves-your"],["יֹאכַל","he-shall-eat"],["הַגָּזָם","the-locusts"],["וְלֹא־שַׁבְתֶּם","and-not-repent"],["עָדַי","to-me"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"י", words:[["שִׁלַּחְתִּי","I have sent"],["בָכֶם","over-you"],["דֶּבֶר","a pestilence"],["בְּדֶרֶךְ","after-the-manner-of"],["מִצְרַיִם","Egypt"],["הָרַגְתִּי","the-I-slew"],["בַחֶרֶב","by-the-sword"],["בַּחוּרֵיכֶם","young men-your"],["עִם","with"],["שְׁבִי","captive"],["סוּסֵיכֶם","horses-your"],["וָאַעֲלֶה","and-I offered up"],["בְּאֹשׁ","the stench of"],["מַחֲנֵיכֶם","camp-your"],["וּבְאַפְּכֶם","in-nose-your"],["וְלֹא־שַׁבְתֶּם","and-not-repent"],["עָדַי","to-me"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"יא", words:[["הָפַכְתִּי","I overthrew"],["בָכֶם","over-you"],["כְּמַהְפֵּכַת","as-the-overthrow-of"],["אֱלֹהִים","God"],["אֶת־סְדֹם","[ACC]-Sodom"],["וְאֶת־עֲמֹרָה","and-[ACC]-Gomorrah"],["וַתִּהְיוּ","and-have-been"],["כְּאוּד","like-a piece of firewood"],["מֻצָּל","plucked out"],["מִשְּׂרֵפָה","from-burning"],["וְלֹא־שַׁבְתֶּם","and-not-repent"],["עָדַי","to-me"],["נאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"יב", words:[["לָכֵן","therefore"],["כֹּה","thus"],["אֶעֱשֶׂה־לְּךָ","I-do-have-you"],["יִשְׂרָאֵל","Israel"],["עֵקֶב","for"],["כִּי־זֹאת","because-this"],["אֶעֱשֶׂה־לָּךְ","I-do-to-you"],["הִכּוֹן","be prepared"],["לִקְרַאת־אֱלֹהֶיךָ","to-meet-your-God"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"יג", words:[["כִּי","because"],["הִנֵּה","behold"],["יוֹצֵר","potter"],["הָרִים","mountains"],["וּבֹרֵא","and-one who created"],["רוּחַ","the-spirit-of"],["וּמַגִּיד","and-tells"],["לְאָדָם","to-man"],["מַה־שֵּׂחוֹ","what-is thought-his"],["עֹשֵׂה","that-doeth"],["שַׁחַר","dawn"],["עֵיפָה","were Ephah"],["וְדֹרֵךְ","and-one who treads"],["עַל־בָּמֳתֵי","upon-upon-small-numbers"],["אָרֶץ","the-earth"],["יְהֹוָה","the-LORD"],["אֱלֹהֵי־צְבָאוֹת","God-of-of-Hosts"],["שְׁמוֹ","His-name"],["׃",""]] },
];
renderVerseSet(amo_ch4Verses, 'amo-ch4-verses');

var amo_ch5Verses = [
  { num:"א", words:[["שִׁמְעוּ","hear"],["אֶת־הַדָּבָר","[ACC]-the-word"],["הַזֶּה","this"],["אֲשֶׁר","which"],["אָנֹכִי","I"],["נֹשֵׂא","bearing"],["עֲלֵיכֶם","over-you"],["קִינָה","a lamentation"],["בֵּית","the-house-of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"ב", words:[["נָפְלָה","fell"],["לֹא־תוֹסִיף","not-Tosif"],["קוּם","arise"],["בְּתוּלַת","virgin-of"],["יִשְׂרָאֵל","Israel"],["נִטְּשָׁה","she has been abandoned"],["עַל־אַדְמָתָהּ","upon-own land-her"],["אֵין","there-is-no"],["מְקִימָהּ","is one who raises up-her"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["כֹה","thus"],["אָמַר","said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["הָעִיר","the-city"],["הַיֹּצֵאת","the-who-will come out"],["אֶלֶף","thousand"],["תַּשְׁאִיר","it will have left"],["מֵאָה","a-hundredth"],["וְהַיּוֹצֵאת","and-the-which-goes out"],["מֵאָה","a-hundredth"],["תַּשְׁאִיר","it will have left"],["עֲשָׂרָה","ten"],["לְבֵית","to-house-of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["כֹה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["לְבֵית","to-house-of"],["יִשְׂרָאֵל","Israel"],["דִּרְשׁוּנִי","seek-me"],["וִחְיוּ","and-live"],["׃",""]] },
  { num:"ה", words:[["וְאַל־תִּדְרְשׁוּ","and-do-not-you seek"],["בֵּית־אֵל","Bethel"],["וְהַגִּלְגָּל","and-the-Gilgal"],["לֹא","not"],["תָבֹאוּ","ye-would-come"],["וּבְאֵר","and-the-lake-of"],["שֶׁבַע","seven"],["לֹא","not"],["תַעֲבֹרוּ","you must pass over"],["כִּי","because"],["הַגִּלְגָּל","the-Gilgal"],["גָּלֹה","certainly"],["יִגְלֶה","he uncovers"],["וּבֵית־אֵל","and-house-of-God"],["יִהְיֶה","shall-be"],["לְאָוֶן","trouble"],["׃",""]] },
  { num:"ו", words:[["דִּרְשׁוּ","seek"],["אֶת־יְהֹוָה","[ACC]-the-LORD"],["וִחְיוּ","and-live"],["פֶּן־יִצְלַח","lest-shall-prosper"],["כָּאֵשׁ","like-fire"],["בֵּית","the-house-of"],["יוֹסֵף","Joseph"],["וְאָכְלָה","and-shall-devour"],["וְאֵין־מְכַבֶּה","and-has-no-will be one who extinguishes"],["לְבֵית־אֵל","to-house-of-God"],["׃",""]] },
  { num:"ז", words:[["הַהֹפְכִים","O those-who turn"],["לְלַעֲנָה","into-wormwood"],["מִשְׁפָּט","judgment"],["וּצְדָקָה","and-righteousness"],["לָאָרֶץ","to-the-ground"],["הִנִּיחוּ","they-left/placed"],["׃",""]] },
  { num:"ח", words:[["עֹשֵׂה","that-doeth"],["כִימָה","Pleiades"],["וּכְסִיל","and-Kesil"],["וְהֹפֵךְ","and-the one who turns"],["לַבֹּקֶר","to the-morning"],["צַלְמָוֶת","the-shadow-of-death"],["וְיוֹם","and-day"],["לַיְלָה","night"],["הֶחְשִׁיךְ","he makes dark"],["הַקּוֹרֵא","the-calling"],["לְמֵי־הַיָּם","to-the-waters-of-the-sea"],["וַיִּשְׁפְּכֵם","and-he poured out-them"],["עַל־פְּנֵי","upon-the-face-of"],["הָאָרֶץ","the-earth"],["יְהֹוָה","the-LORD"],["שְׁמוֹ","His-name"],["׃",""]] },
  { num:"ט", words:[["הַמַּבְלִיג","the-who causes to flash"],["שֹׁד","desolation"],["עַל־עָז","upon-mighty"],["וְשֹׁד","and-desolation"],["עַל־מִבְצָר","upon-fortification"],["יָבוֹא","shall-come"],["׃",""]] },
  { num:"י", words:[["שָׂנְאוּ","they hated"],["בַשַּׁעַר","by-the-gate"],["מוֹכִיחַ","is an arbiter"],["וְדֹבֵר","and-speaking"],["תָּמִים","intent"],["יְתָעֵבוּ","they abhor"],["׃",""]] },
  { num:"יא", words:[["לָכֵן","therefore"],["יַעַן","because"],["בּוֹשַׁסְכֶם","trample-you"],["עַל־דָּל","upon-the poor"],["וּמַשְׂאַת־בַּר","and-a portion of-olive-tree"],["תִּקְחוּ","you will take"],["מִמֶּנּוּ","from-him"],["בָּתֵּי","in-twain"],["גָזִית","hewn stone"],["בְּנִיתֶם","you-built"],["וְלֹא־תֵשְׁבוּ","and-not-you-shall-dwell"],["בָם","in-them"],["כַּרְמֵי־חֶמֶד","the vineyards of-delight"],["נְטַעְתֶּם","you had planted"],["וְלֹא","and-not"],["תִשְׁתּוּ","you will drink"],["אֶת־יֵינָם","[ACC]-their-wine"],["׃",""]] },
  { num:"יב", words:[["כִּי","because"],["יָדַעְתִּי","I-know"],["רַבִּים","many"],["פִּשְׁעֵיכֶם","your-crimes"],["וַעֲצֻמִים","and-mighty"],["חַטֹּאתֵיכֶם","your-sins"],["צֹרְרֵי","O opposers of"],["צַדִּיק","righteous"],["לֹקְחֵי","who were about to take"],["כֹפֶר","a ransom"],["וְאֶבְיוֹנִים","and-the-needy"],["בַּשַּׁעַר","by-the-gate"],["הִטּוּ","they-turned"],["׃",""]] },
  { num:"יג", words:[["לָכֵן","therefore"],["הַמַּשְׂכִּיל","the-prudent person"],["בָּעֵת","at-the-time"],["הַהִיא","that"],["יִדֹּם","it may be silent"],["כִּי","because"],["עֵת","time"],["רָעָה","evil"],["הִיא","it"],["׃",""]] },
  { num:"יד", words:[["דִּרְשׁוּ־טוֹב","seek-good"],["וְאַל־רָע","and-do-not-evil"],["לְמַעַן","in-order-that"],["תִּחְיוּ","you may live"],["וִיהִי־כֵן","and-may-be-thus"],["יְהֹוָה","the-LORD"],["אֱלֹהֵי־צְבָאוֹת","God-of-of-Hosts"],["אִתְּכֶם","with-you"],["כַּאֲשֶׁר","when/as"],["אֲמַרְתֶּם","you-have-said"],["׃",""]] },
  { num:"טו", words:[["שִׂנְאוּ־רָע","hate-evil"],["וְאֶהֱבוּ","and-love"],["טוֹב","good"],["וְהַצִּיגוּ","and-the-set up"],["בַשַּׁעַר","by-the-gate"],["מִשְׁפָּט","judgment"],["אוּלַי","perhaps"],["יֶחֱנַן","he will show favor to"],["יְהֹוָה","the-LORD"],["אֱלֹהֵי־צְבָאוֹת","God-of-of-Hosts"],["שְׁאֵרִית","remnant-of"],["יוֹסֵף","Joseph"],["׃",""]] },
  { num:"טז", words:[["לָכֵן","therefore"],["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["אֱלֹהֵי","the-God-of"],["צְבָאוֹת","of-Hosts"],["אֲדֹנָי","Lord"],["בְּכׇל־רְחֹבוֹת","in-all-Rehoboth"],["מִסְפֵּד","a lament"],["וּבְכׇל־חוּצוֹת","and-in-all-the-streets"],["יֹאמְרוּ","shall-say"],["הוֹ־הוֹ","O-O"],["וְקָרְאוּ","and-called-upon"],["אִכָּר","a farmer"],["אֶל־אֵבֶל","to-a-great-mourning"],["וּמִסְפֵּד","and-lamentation"],["אֶל־יוֹדְעֵי","to-knowers-of"],["נֶהִי","wailing"],["׃",""]] },
  { num:"יז", words:[["וּבְכׇל־כְּרָמִים","and-in-all-vineyards"],["מִסְפֵּד","a lament"],["כִּי־אֶעֱבֹר","because-let me pass"],["בְּקִרְבְּךָ","in-midst-your"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"יח", words:[["הוֹי","O"],["הַמִּתְאַוִּים","the-who-craved"],["אֶת־יוֹם","[ACC]-the-day-of"],["יְהֹוָה","the-LORD"],["לָמָּה־זֶּה","why-Zh"],["לָכֶם","to-you"],["יוֹם","day"],["יְהֹוָה","the-LORD"],["הוּא־חֹשֶׁךְ","it-is-darkness"],["וְלֹא־אוֹר","and-not-light"],["׃",""]] },
  { num:"יט", words:[["כַּאֲשֶׁר","when/as"],["יָנוּס","flee"],["אִישׁ","man-of"],["מִפְּנֵי","because-of"],["הָאֲרִי","the-lion"],["וּפְגָעוֹ","and-it meets-him"],["הַדֹּב","the-bear"],["וּבָא","and-come"],["הַבַּיִת","the-house"],["וְסָמַךְ","and-he will lay"],["יָדוֹ","his-hand"],["עַל־הַקִּיר","upon-the-wall"],["וּנְשָׁכוֹ","and-it bites-him"],["הַנָּחָשׁ","the-serpent"],["׃",""]] },
  { num:"כ", words:[["הֲלֹא־חֹשֶׁךְ","do-not-darkness"],["יוֹם","day"],["יְהֹוָה","the-LORD"],["וְלֹא־אוֹר","and-not-light"],["וְאָפֵל","and-gloomy"],["וְלֹא־נֹגַהּ","and-not-light"],["לוֹ","him"],["׃",""]] },
  { num:"כא", words:[["שָׂנֵאתִי","I hate"],["מָאַסְתִּי","I-rejected"],["חַגֵּיכֶם","feasts-your"],["וְלֹא","and-not"],["אָרִיחַ","I will smell"],["בְּעַצְּרֹתֵיכֶם","in-assemblies-your"],["׃",""]] },
  { num:"כב", words:[["כִּי","because"],["אִם־תַּעֲלוּ־לִי","if-go-up-to-me"],["עֹלוֹת","burnt-offerings"],["וּמִנְחֹתֵיכֶם","and-grain offerings-your"],["לֹא","not"],["אֶרְצֶה","I will accept"],["וְשֶׁלֶם","and-the peace offering of"],["מְרִיאֵיכֶם","fatlings-your"],["לֹא","not"],["אַבִּיט","I will look"],["׃",""]] },
  { num:"כג", words:[["הָסֵר","the-departing"],["מֵעָלַי","from-me"],["הֲמוֹן","multitude-of"],["שִׁרֶיךָ","songs-your"],["וְזִמְרַת","and-the music of"],["נְבָלֶיךָ","your-harps"],["לֹא","not"],["אֶשְׁמָע","I heard"],["׃",""]] },
  { num:"כד", words:[["וְיִגַּל","and-it may roll on"],["כַּמַּיִם","as-the-waters"],["מִשְׁפָּט","judgment"],["וּצְדָקָה","and-righteousness"],["כְּנַחַל","is like-a torrent"],["אֵיתָן","firm"],["׃",""]] },
  { num:"כה", words:[["הַזְּבָחִים","the-sacrifices"],["וּמִנְחָה","and-a grain offering"],["הִגַּשְׁתֶּם־לִי","did you bring near-to-me"],["בַמִּדְבָּר","in-the-wilderness"],["אַרְבָּעִים","forty"],["שָׁנָה","year"],["בֵּית","the-house-of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"כו", words:[["וּנְשָׂאתֶם","and-you will carry"],["אֵת","[ACC]"],["סִכּוּת","Sikkuth"],["מַלְכְּכֶם","your-king"],["וְאֵת","and-[ACC]"],["כִּיּוּן","Kiyyun"],["צַלְמֵיכֶם","images-your"],["כּוֹכַב","the star of"],["אֱלֹהֵיכֶם","your-God"],["אֲשֶׁר","which"],["עֲשִׂיתֶם","you-have-done"],["לָכֶם","to-you"],["׃",""]] },
  { num:"כז", words:[["וְהִגְלֵיתִי","and-I will send into exile"],["אֶתְכֶם","you"],["מֵהָלְאָה","from-beyond"],["לְדַמָּשֶׂק","of-Damascus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["אֱלֹהֵי־צְבָאוֹת","God-of-of-Hosts"],["שְׁמוֹ","His-name"],["׃",""]] },
];
renderVerseSet(amo_ch5Verses, 'amo-ch5-verses');

var amo_ch6Verses = [
  { num:"א", words:[["הוֹי","O"],["הַשַּׁאֲנַנִּים","the-self-confident people"],["בְּצִיּוֹן","in-Zion"],["וְהַבֹּטְחִים","and-the-those-who trust"],["בְּהַר","while-on-the-mount-of"],["שֹׁמְרוֹן","Samaria"],["נְקֻבֵי","the distinguished people of"],["רֵאשִׁית","the-beginning-of"],["הַגּוֹיִם","the-nations"],["וּבָאוּ","and-it-comes"],["לָהֶם","to-them"],["בֵּית","the-house-of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"ב", words:[["עִבְרוּ","pass over"],["כַלְנֵה","Calneh"],["וּרְאוּ","and-see"],["וּלְכוּ","and-go"],["מִשָּׁם","from-there"],["חֲמַת","the-wrath-of"],["רַבָּה","much"],["וּרְדוּ","and-rule"],["גַת־פְּלִשְׁתִּים","Gath-Philistines"],["הֲטוֹבִים","¿-are they good"],["מִן־הַמַּמְלָכוֹת","from-the-kingdoms"],["הָאֵלֶּה","these"],["אִם־רַב","if-great"],["גְּבוּלָם","their-territory"],["מִגְּבֻלְכֶם","more than-territory-your"],["׃",""]] },
  { num:"ג", words:[["הַמְנַדִּים","those-who push away"],["לְיוֹם","to-day"],["רָע","evil"],["וַתַּגִּשׁוּן","and-she brought them near(they)"],["שֶׁבֶת","remaining"],["חָמָס","violence"],["׃",""]] },
  { num:"ד", words:[["הַשֹּׁכְבִים","the-those-who lie"],["עַל־מִטּוֹת","upon-couches of"],["שֵׁן","their-teeth"],["וּסְרֻחִים","and-people sprawled out"],["עַל־עַרְשׂוֹתָם","upon-couches-their"],["וְאֹכְלִים","and-those who eat"],["כָּרִים","lambs"],["מִצֹּאן","upon-the-flocks-of"],["וַעֲגָלִים","and-calves"],["מִתּוֹךְ","from-midst-of"],["מַרְבֵּק","the-stall"],["׃",""]] },
  { num:"ה", words:[["הַפֹּרְטִים","the-those-who improvise"],["עַל־פִּי","according-to"],["הַנָּבֶל","the-lyre"],["כְּדָוִיד","like-David"],["חָשְׁבוּ","they-supposed"],["לָהֶם","to-them"],["כְּלֵי־שִׁיר","weapons-of-a song"],["׃",""]] },
  { num:"ו", words:[["הַשֹּׁתִים","the-drink-of-it"],["בְּמִזְרְקֵי","in-bowls of"],["יַיִן","wine"],["וְרֵאשִׁית","and-firstfruit-of"],["שְׁמָנִים","fat things"],["יִמְשָׁחוּ","they smear"],["וְלֹא","and-not"],["נֶחְלוּ","they have wearied themselves"],["עַל־שֵׁבֶר","upon-the ruin of"],["יוֹסֵף","Joseph"],["׃",""]] },
  { num:"ז", words:[["לָכֵן","therefore"],["עַתָּה","now"],["יִגְלוּ","they will go into exile"],["בְּרֹאשׁ","in-the-gall-of"],["גֹּלִים","those who go into exile"],["וְסָר","then-shall-depart"],["מִרְזַח","the revelry of"],["סְרוּחִים","sprawled out people"],["׃",""]] },
  { num:"ח", words:[["נִשְׁבַּע","swore"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["בְּנַפְשׁוֹ","in-His-soul"],["נְאֻם־יְהֹוָה","says-the-LORD"],["אֱלֹהֵי","the-God-of"],["צְבָאוֹת","of-Hosts"],["מְתָאֵב","am loathing"],["אָנֹכִי","I"],["אֶת־גְּאוֹן","[ACC]-the-pride-of"],["יַעֲקֹב","Jacob"],["וְאַרְמְנֹתָיו","and-fortresses-his"],["שָׂנֵאתִי","I hate"],["וְהִסְגַּרְתִּי","and-I will deliver up"],["עִיר","the-city-of"],["וּמְלֹאָהּ","and-what fills-it"],["׃",""]] },
  { num:"ט", words:[["וְהָיָה","and-be"],["אִם־יִוָּתְרוּ","if-they will remain"],["עֲשָׂרָה","ten"],["אֲנָשִׁים","men"],["בְּבַיִת","to-house"],["אֶחָד","one"],["וָמֵתוּ","and-they will die"],["׃",""]] },
  { num:"י", words:[["וּנְשָׂאוֹ","and-He-shall-lift-it-up"],["דּוֹדוֹ","Dodo"],["וּמְסָרְפוֹ","and-the one who burns-him"],["לְהוֹצִיא","to-bring-out"],["עֲצָמִים","the bones"],["מִן־הַבַּיִת","from-the-house"],["וְאָמַר","and-said"],["לַאֲשֶׁר","unto-him-who"],["בְּיַרְכְּתֵי","in-the-sides-of"],["הַבַּיִת","the-house"],["הַעוֹד","¿-still"],["עִמָּךְ","your-people"],["וְאָמַר","and-said"],["אָפֶס","nothing"],["וְאָמַר","and-said"],["הָס","hush!"],["כִּי","because"],["לֹא","not"],["לְהַזְכִּיר","to-bring-to-remembrance"],["בְּשֵׁם","by-name"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"יא", words:[["כִּי־הִנֵּה","because-behold"],["יְהֹוָה","the-LORD"],["מְצַוֶּה","command"],["וְהִכָּה","and-was-smitten"],["הַבַּיִת","the-house"],["הַגָּדוֹל","the-great"],["רְסִיסִים","fragments"],["וְהַבַּיִת","and-the-house"],["הַקָּטֹן","the-small"],["בְּקִעִים","rubble"],["׃",""]] },
  { num:"יב", words:[["הַיְרֻצוּן","¿-do they run-!"],["בַּסֶּלַע","in the-rock"],["סוּסִים","horses"],["אִם־יַחֲרוֹשׁ","if-it will plow"],["בַּבְּקָרִים","with-the-oxen"],["כִּי־הֲפַכְתֶּם","because-you have turned"],["לְרֹאשׁ","the-head-of"],["מִשְׁפָּט","judgment"],["וּפְרִי","and-all-manner-of-fruit"],["צְדָקָה","a-state-of-righteousness"],["לְלַעֲנָה","into-wormwood"],["׃",""]] },
  { num:"יג", words:[["הַשְּׂמֵחִים","the-joy"],["לְלֹא","to-not"],["דָבָר","[thing]"],["הָאֹמְרִים","the-ones-saying"],["הֲלוֹא","art-not"],["בְחׇזְקֵנוּ","a strong one-us"],["לָקַחְנוּ","we-took"],["לָנוּ","us"],["קַרְנָיִם","Karnaim"],["׃",""]] },
  { num:"יד", words:[["כִּי","because"],["הִנְנִי","behold-I"],["מֵקִים","about to establish"],["עֲלֵיכֶם","over-you"],["בֵּית","the-house-of"],["יִשְׂרָאֵל","Israel"],["נְאֻם־יְהֹוָה","says-the-LORD"],["אֱלֹהֵי","the-God-of"],["הַצְּבָאוֹת","the-of-Hosts"],["גּוֹי","nation"],["וְלָחֲצוּ","and-they will oppress"],["אֶתְכֶם","you"],["מִלְּבוֹא","from-Lebo"],["חֲמָת","Hamath"],["עַד־נַחַל","until-a-river-of"],["הָעֲרָבָה","the-desert plain"],["׃",""]] },
];
renderVerseSet(amo_ch6Verses, 'amo-ch6-verses');

var amo_ch7Verses = [
  { num:"א", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown-me"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["וְהִנֵּה","and-behold"],["יוֹצֵר","potter"],["גֹּבַי","locusts"],["בִּתְחִלַּת","in-the-commencement-of"],["עֲלוֹת","the-ascending-of"],["הַלָּקֶשׁ","the-spring-crop"],["וְהִנֵּה־לֶקֶשׁ","and-behold-a spring-crop"],["אַחַר","after"],["גִּזֵּי","the mowings of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ב", words:[["וְהָיָה","and-be"],["אִם־כִּלָּה","if-all-of-it(f)"],["לֶאֱכוֹל","to-eat"],["אֶת־עֵשֶׂב","[ACC]-plants"],["הָאָרֶץ","the-earth"],["וָאֹמַר","and-I-said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["סְלַח־נָא","forgive-I-pray"],["מִי","who"],["יָקוּם","he-shall-rise"],["יַעֲקֹב","Jacob"],["כִּי","because"],["קָטֹן","little-are"],["הוּא","it"],["׃",""]] },
  { num:"ג", words:[["נִחַם","comforted"],["יְהֹוָה","the-LORD"],["עַל־זֹאת","upon-this"],["לֹא","not"],["תִהְיֶה","be"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ד", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown-me"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["וְהִנֵּה","and-behold"],["קֹרֵא","I-call"],["לָרִב","to-contest a lawsuit"],["בָּאֵשׁ","by-fire"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["וַתֹּאכַל","and-she ate"],["אֶת־תְּהוֹם","[ACC]-gulf"],["רַבָּה","much"],["וְאָכְלָה","and-shall-devour"],["אֶת־הַחֵלֶק","[ACC]-the-part-of"],["׃",""]] },
  { num:"ה", words:[["וָאֹמַר","and-I-said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["חֲדַל־נָא","cease-I-pray"],["מִי","who"],["יָקוּם","he-shall-rise"],["יַעֲקֹב","Jacob"],["כִּי","because"],["קָטֹן","little-are"],["הוּא","it"],["׃",""]] },
  { num:"ו", words:[["נִחַם","comforted"],["יְהֹוָה","the-LORD"],["עַל־זֹאת","upon-this"],["גַּם־הִיא","also-it-is"],["לֹא","not"],["תִהְיֶה","be"],["אָמַר","said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["׃",""]] },
  { num:"ז", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown-me"],["וְהִנֵּה","and-behold"],["אֲדֹנָי","Lord"],["נִצָּב","stands-up"],["עַל־חוֹמַת","upon-the-walls-of"],["אֲנָךְ","tin"],["וּבְיָדוֹ","and-in-his-hand"],["אֲנָךְ","tin"],["׃",""]] },
  { num:"ח", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["אֵלַי","to-me"],["מָה־אַתָּה","what-you"],["רֹאֶה","I-perceive"],["עָמוֹס","Amos"],["וָאֹמַר","and-I-said"],["אֲנָךְ","tin"],["וַיֹּאמֶר","and-said"],["אֲדֹנָי","Lord"],["הִנְנִי","behold-I"],["שָׂם","set"],["אֲנָךְ","tin"],["בְּקֶרֶב","among"],["עַמִּי","my-people"],["יִשְׂרָאֵל","Israel"],["לֹא־אוֹסִיף","not-more"],["עוֹד","any-more"],["עֲבוֹר","to pass on"],["לוֹ","him"],["׃",""]] },
  { num:"ט", words:[["וְנָשַׁמּוּ","and-they will be desolate"],["בָּמוֹת","Bamoth"],["יִשְׂחָק","he laughs"],["וּמִקְדְּשֵׁי","and-the sanctuaries of"],["יִשְׂרָאֵל","Israel"],["יֶחֱרָבוּ","they will become desolate"],["וְקַמְתִּי","for-I-will-rise-up"],["עַל־בֵּית","to-the-house-of"],["יָרׇבְעָם","Jeroboam"],["בֶּחָרֶב","by-the-sword"],["׃",""]] },
  { num:"י", words:[["וַיִּשְׁלַח","and-sent"],["אֲמַצְיָה","Amaziah"],["כֹּהֵן","one-priest"],["בֵּית־אֵל","Bethel"],["אֶל־יָרׇבְעָם","to-Jeroboam"],["מֶלֶךְ־יִשְׂרָאֵל","king-of-Israel"],["לֵאמֹר","saying"],["קָשַׁר","he has conspired"],["עָלֶיךָ","upon-you(f)"],["עָמוֹס","Amos"],["בְּקֶרֶב","among"],["בֵּית","the-house-of"],["יִשְׂרָאֵל","Israel"],["לֹא־תוּכַל","not-can"],["הָאָרֶץ","the-earth"],["לְהָכִיל","to-contain"],["אֶת־כׇּל־דְּבָרָיו","[ACC]-all-of-his-words"],["׃",""]] },
  { num:"יא", words:[["כִּי־כֹה","because-thus"],["אָמַר","said"],["עָמוֹס","Amos"],["בַּחֶרֶב","with-the-sword"],["יָמוּת","who-shall-die"],["יָרׇבְעָם","Jeroboam"],["וְיִשְׂרָאֵל","though-Israel"],["גָּלֹה","certainly"],["יִגְלֶה","he uncovers"],["מֵעַל","from-upon"],["אַדְמָתוֹ","land-his"],["׃",""]] },
  { num:"יב", words:[["וַיֹּאמֶר","and-said"],["אֲמַצְיָה","Amaziah"],["אֶל־עָמוֹס","to-Amos"],["חֹזֶה","a-seer"],["לֵךְ","go"],["בְּרַח־לְךָ","flee-for-you"],["אֶל־אֶרֶץ","to-land-of"],["יְהוּדָה","Judah"],["וֶאֱכׇל־שָׁם","and-eat-there-is"],["לֶחֶם","bread"],["וְשָׁם","and-there"],["תִּנָּבֵא","you-shall-prophesy"],["׃",""]] },
  { num:"יג", words:[["וּבֵית־אֵל","and-house-of-God"],["לֹא־תוֹסִיף","not-Tosif"],["עוֹד","any-more"],["לְהִנָּבֵא","to-prophesy"],["כִּי","because"],["מִקְדַּשׁ־מֶלֶךְ","the sanctuary of-king-of"],["הוּא","it"],["וּבֵית","and-house-of"],["מַמְלָכָה","kingdom"],["הוּא","it"],["׃",""]] },
  { num:"יד", words:[["וַיַּעַן","and-he-answered"],["עָמוֹס","Amos"],["וַיֹּאמֶר","and-said"],["אֶל־אֲמַצְיָה","to-Amaziah"],["לֹא־נָבִיא","not-a-prophet"],["אָנֹכִי","I"],["וְלֹא","and-not"],["בֶן־נָבִיא","Bn-a-prophet"],["אָנֹכִי","I"],["כִּי־בוֹקֵר","because-was a herdsman"],["אָנֹכִי","I"],["וּבוֹלֵס","and-a fig picker of"],["שִׁקְמִים","the-sycamores"],["׃",""]] },
  { num:"טו", words:[["וַיִּקָּחֵנִי","and-he took-me"],["יְהֹוָה","the-LORD"],["מֵאַחֲרֵי","from-after"],["הַצֹּאן","the-flock"],["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["יְהֹוָה","the-LORD"],["לֵךְ","go"],["הִנָּבֵא","and-prophesy"],["אֶל־עַמִּי","unto-my-people"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"טז", words:[["וְעַתָּה","and-now"],["שְׁמַע","hearken"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["אַתָּה","you"],["אֹמֵר","say"],["לֹא","not"],["תִנָּבֵא","you must prophesy"],["עַל־יִשְׂרָאֵל","upon-Israel"],["וְלֹא","and-not"],["תַטִּיף","you must prophesy"],["עַל־בֵּית","to-the-house-of"],["יִשְׂחָק","he laughs"],["׃",""]] },
  { num:"יז", words:[["לָכֵן","therefore"],["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["אִשְׁתְּךָ","was wife-your"],["בָּעִיר","in-the-city"],["תִּזְנֶה","she will be a prostitute"],["וּבָנֶיךָ","and-your-sons"],["וּבְנֹתֶיךָ","and-daughters-your"],["בַּחֶרֶב","with-the-sword"],["יִפֹּלוּ","they-must-fall"],["וְאַדְמָתְךָ","and-land-your"],["בַּחֶבֶל","with-rope"],["תְּחֻלָּק","it will be divided"],["וְאַתָּה","for-you"],["עַל־אֲדָמָה","upon-ground/earth"],["טְמֵאָה","filthy"],["תָּמוּת","to-death"],["וְיִשְׂרָאֵל","though-Israel"],["גָּלֹה","certainly"],["יִגְלֶה","he uncovers"],["מֵעַל","from-upon"],["אַדְמָתוֹ","land-his"],["׃",""]] },
];
renderVerseSet(amo_ch7Verses, 'amo-ch7-verses');

var amo_ch8Verses = [
  { num:"א", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown-me"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["וְהִנֵּה","and-behold"],["כְּלוּב","Kelub"],["קָיִץ","summer"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמֶר","and-said"],["מָה־אַתָּה","what-you"],["רֹאֶה","I-perceive"],["עָמוֹס","Amos"],["וָאֹמַר","and-I-said"],["כְּלוּב","Kelub"],["קָיִץ","summer"],["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["אֵלַי","to-me"],["בָּא","came"],["הַקֵּץ","the-end"],["אֶל־עַמִּי","unto-my-people"],["יִשְׂרָאֵל","Israel"],["לֹא־אוֹסִיף","not-more"],["עוֹד","any-more"],["עֲבוֹר","to pass on"],["לוֹ","him"],["׃",""]] },
  { num:"ג", words:[["וְהֵילִילוּ","and-wail"],["שִׁירוֹת","songs of"],["הֵיכָל","a-spacious-palace"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["נְאֻם","says"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["רַב","great"],["הַפֶּגֶר","the-corpses"],["בְּכׇל־מָקוֹם","in-all-place"],["הִשְׁלִיךְ","cast"],["הָס","hush!"],["׃",""]] },
  { num:"ד", words:[["שִׁמְעוּ־זֹאת","hear-this"],["הַשֹּׁאֲפִים","the-those-who trample"],["אֶבְיוֹן","a needy person"],["וְלַשְׁבִּית","and-to-put an end to"],["(ענוי)","a-never-ending-torment"],["[עֲנִיֵּי־]אָרֶץ","the poor people of-I run"],["׃",""]] },
  { num:"ה", words:[["לֵאמֹר","saying"],["מָתַי","when"],["יַעֲבֹר","pass-away"],["הַחֹדֶשׁ","the-month"],["וְנַשְׁבִּירָה","so-we may sell grain"],["שֶּׁבֶר","grain"],["וְהַשַּׁבָּת","and-the-sabbath"],["וְנִפְתְּחָה־בָּר","so-we may open-wild"],["לְהַקְטִין","to-make small"],["אֵיפָה","an-ephah"],["וּלְהַגְדִּיל","and-to-make great"],["שֶׁקֶל","shekels of"],["וּלְעַוֵּת","and-to-falsify"],["מֹאזְנֵי","balances of"],["מִרְמָה","deceit"],["׃",""]] },
  { num:"ו", words:[["לִקְנוֹת","to-recover"],["בַּכֶּסֶף","in-the-silver"],["דַּלִּים","the-poor"],["וְאֶבְיוֹן","and-needy"],["בַּעֲבוּר","because-of"],["נַעֲלָיִם","a pair of sandals"],["וּמַפַּל","and-refuse of"],["בַּר","olive-tree"],["נַשְׁבִּיר","we will sell grain"],["׃",""]] },
  { num:"ז", words:[["נִשְׁבַּע","swore"],["יְהֹוָה","the-LORD"],["בִּגְאוֹן","in-the-pride-of"],["יַעֲקֹב","Jacob"],["אִם־אֶשְׁכַּח","if-I will forget"],["לָנֶצַח","forever"],["כׇּל־מַעֲשֵׂיהֶם","all-of-their-proceedings"],["׃",""]] },
  { num:"ח", words:[["הַעַל","bring up"],["זֹאת","this"],["לֹא־תִרְגַּז","not-will it tremble"],["הָאָרֶץ","the-earth"],["וְאָבַל","and-he will mourn"],["כׇּל־יוֹשֵׁב","all-sitting"],["בָּהּ","in-it(f)"],["וְעָלְתָה","and-she will go up"],["כָאֹר","like the-light"],["כֻּלָּהּ","all-of-it(f)"],["וְנִגְרְשָׁה","and-it will be tossed"],["(ונשקה)","and-she kisses"],["[וְנִשְׁקְעָה]","and-it will sink"],["כִּיאוֹר","like-the River"],["מִצְרָיִם","Egypt"],["׃",""]] },
  { num:"ט", words:[["וְהָיָה","and-be"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["נְאֻם","says"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["וְהֵבֵאתִי","and-have-brought"],["הַשֶּׁמֶשׁ","the-sun"],["בַּצׇּהֳרָיִם","at-the-noon"],["וְהַחֲשַׁכְתִּי","and-the-I will make dark"],["לָאָרֶץ","to-the-ground"],["בְּיוֹם","in-day-of"],["אוֹר","light"],["׃",""]] },
  { num:"י", words:[["וְהָפַכְתִּי","and-I-shall-overturn"],["חַגֵּיכֶם","feasts-your"],["לְאֵבֶל","mourning"],["וְכׇל־שִׁירֵיכֶם","and-all-songs-your"],["לְקִינָה","for-lamentation"],["וְהַעֲלֵיתִי","and-I will bring up"],["עַל־כׇּל־מׇתְנַיִם","upon-all-the hips"],["שָׂק","sackcloth"],["וְעַל־כׇּל־רֹאשׁ","and-upon-all-head-of"],["קׇרְחָה","baldness"],["וְשַׂמְתִּיהָ","I-will-also-make-it"],["כְּאֵבֶל","like-the mourning of"],["יָחִיד","am solitary"],["וְאַחֲרִיתָהּ","and-end-her"],["כְּיוֹם","as-the-day-of"],["מָר","bitter"],["׃",""]] },
  { num:"יא", words:[["הִנֵּה","behold"],["יָמִים","days"],["בָּאִים","come"],["נְאֻם","says"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["וְהִשְׁלַחְתִּי","and-I will send"],["רָעָב","hungry"],["בָּאָרֶץ","in-the-land"],["לֹא־רָעָב","not-hungry"],["לַלֶּחֶם","to the-bread"],["וְלֹא־צָמָא","and-not-thirst"],["לַמַּיִם","the-waters"],["כִּי","because"],["אִם־לִשְׁמֹעַ","rather-to-hearken"],["אֵת","[ACC]"],["דִּבְרֵי","account-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"יב", words:[["וְנָעוּ","and-they will tremble"],["מִיָּם","from-the-sea/west"],["עַד־יָם","until-the-sea"],["וּמִצָּפוֹן","and-from-north"],["וְעַד־מִזְרָח","and-unto-east"],["יְשׁוֹטְטוּ","they will rove about"],["לְבַקֵּשׁ","to-seek"],["אֶת־דְּבַר־יְהֹוָה","[ACC]-the-word-of-the-Lord"],["וְלֹא","and-not"],["יִמְצָאוּ","they-find"],["׃",""]] },
  { num:"יג", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["תִּתְעַלַּפְנָה","they will become faint"],["הַבְּתוּלֹת","the-virgins"],["הַיָּפוֹת","the-fair"],["וְהַבַּחוּרִים","and-the-young men"],["בַּצָּמָא","by-the-thirst"],["׃",""]] },
  { num:"יד", words:[["הַנִּשְׁבָּעִים","the-who-swear"],["בְּאַשְׁמַת","by-the guilt of"],["שֹׁמְרוֹן","Samaria"],["וְאָמְרוּ","shall-say"],["חֵי","by the life of"],["אֱלֹהֶיךָ","your-God"],["דָּן","Dan"],["וְחֵי","and-he will live"],["דֶּרֶךְ","through"],["בְּאֵר־שָׁבַע","Beer-Sheba"],["וְנָפְלוּ","and-fall-shall-they"],["וְלֹא־יָקוּמוּ","and-not-they-shall-stand"],["עוֹד","any-more"],["׃",""]] },
];
renderVerseSet(amo_ch8Verses, 'amo-ch8-verses');

var amo_ch9Verses = [
  { num:"א", words:[["רָאִיתִי","I-saw"],["אֶת־אֲדֹנָי","[ACC]-the-Lord"],["נִצָּב","stands-up"],["עַל־הַמִּזְבֵּחַ","upon-the-altar"],["וַיֹּאמֶר","and-said"],["הַךְ","strike"],["הַכַּפְתּוֹר","the-capital"],["וְיִרְעֲשׁוּ","so-they may shake"],["הַסִּפִּים","the-door"],["וּבְצַעַם","and-break off-them"],["בְּרֹאשׁ","in-the-gall-of"],["כֻּלָּם","all-of-them"],["וְאַחֲרִיתָם","and-posterity-their"],["בַּחֶרֶב","with-the-sword"],["אֶהֱרֹג","I-will-slew"],["לֹא־יָנוּס","not-flee"],["לָהֶם","to-them"],["נָס","fled"],["וְלֹא־יִמָּלֵט","and-not-shall-be-delivered"],["לָהֶם","to-them"],["פָּלִיט","an escapee"],["׃",""]] },
  { num:"ב", words:[["אִם־יַחְתְּרוּ","if-they-shall-dig"],["בִשְׁאוֹל","in-Sheol"],["מִשָּׁם","from-there"],["יָדִי","my-hand"],["תִקָּחֵם","it will take-them"],["וְאִם־יַעֲלוּ","and-if-they-go-up"],["הַשָּׁמַיִם","the-heavens"],["מִשָּׁם","from-there"],["אוֹרִידֵם","I will bring down-them"],["׃",""]] },
  { num:"ג", words:[["וְאִם־יֵחָבְאוּ","and-if-they will hide themselves"],["בְּרֹאשׁ","in-the-gall-of"],["הַכַּרְמֶל","the-Carmel"],["מִשָּׁם","from-there"],["אֲחַפֵּשׂ","I will search for them"],["וּלְקַחְתִּים","and-I will take-them"],["וְאִם־יִסָּתְרוּ","and-if-shall-be-hidden"],["מִנֶּגֶד","from-before"],["עֵינַי","my-eyes"],["בְּקַרְקַע","on-the floor of"],["הַיָּם","the-sea"],["מִשָּׁם","from-there"],["אֲצַוֶּה","I-will-command"],["אֶת־הַנָּחָשׁ","[ACC]-the-serpent"],["וּנְשָׁכָם","and-it will bite-them"],["׃",""]] },
  { num:"ד", words:[["וְאִם־יֵלְכוּ","and-if-they-should-travel"],["בַשְּׁבִי","in-the-captivity"],["לִפְנֵי","before"],["אֹיְבֵיהֶם","their-enemies"],["מִשָּׁם","from-there"],["אֲצַוֶּה","I-will-command"],["אֶת־הַחֶרֶב","[ACC]-the-sword"],["וַהֲרָגָתַם","and-it will kill-them"],["וְשַׂמְתִּי","and-I-make"],["עֵינִי","my-eye"],["עֲלֵיהֶם","against-them"],["לְרָעָה","for-evil"],["וְלֹא","and-not"],["לְטוֹבָה","of-great-worth"],["׃",""]] },
  { num:"ה", words:[["וַאדֹנָי","and-my-Lord"],["יֱהֹוִה","Yahweh"],["הַצְּבָאוֹת","the-of-Hosts"],["הַנּוֹגֵעַ","the-which-bordered"],["בָּאָרֶץ","in-the-land"],["וַתָּמוֹג","and-it melted"],["וְאָבְלוּ","and-mourn"],["כׇּל־יוֹשְׁבֵי","all-the-inhabitants-of"],["בָהּ","in-her"],["וְעָלְתָה","and-she will go up"],["כַיְאֹר","like the-River"],["כֻּלָּהּ","all-of-it(f)"],["וְשָׁקְעָה","and-it sinks"],["כִּיאֹר","like-the River"],["מִצְרָיִם","Egypt"],["׃",""]] },
  { num:"ו", words:[["הַבּוֹנֶה","the-who-builds"],["בַשָּׁמַיִם","will be in the-heavens"],["מַעֲלוֹתָו","from-himself"],["וַאֲגֻדָּתוֹ","and-vault-his"],["עַל־אֶרֶץ","concerning-the-land-of"],["יְסָדָהּ","he-founded-it"],["הַקֹּרֵא","the-partridge"],["לְמֵי־הַיָּם","to-the-waters-of-the-sea"],["וַיִּשְׁפְּכֵם","and-he poured out-them"],["עַל־פְּנֵי","upon-the-face-of"],["הָאָרֶץ","the-earth"],["יְהֹוָה","the-LORD"],["שְׁמוֹ","His-name"],["׃",""]] },
  { num:"ז", words:[["הֲלוֹא","art-not"],["כִבְנֵי","like-the sons of"],["כֻשִׁיִּים","the Cushites"],["אַתֶּם","you-are"],["לִי","to-me"],["בְּנֵי","the-sons-of"],["יִשְׂרָאֵל","Israel"],["נְאֻם־יְהֹוָה","says-the-LORD"],["הֲלוֹא","art-not"],["אֶת־יִשְׂרָאֵל","[ACC]-Israel"],["הֶעֱלֵיתִי","I brought up"],["מֵאֶרֶץ","from-land-of"],["מִצְרַיִם","Egypt"],["וּפְלִשְׁתִּיִּים","and-the Philistines"],["מִכַּפְתּוֹר","from-Caphtor"],["וַאֲרָם","and-Aram"],["מִקִּיר","will be from-the wall of"],["׃",""]] },
  { num:"ח", words:[["הִנֵּה","behold"],["עֵינֵי","the-eyes-of"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["בַּמַּמְלָכָה","in-the-kingdom"],["הַחַטָּאָה","the-sinful"],["וְהִשְׁמַדְתִּי","and-I will destroy"],["אֹתָהּ","it"],["מֵעַל","from-upon"],["פְּנֵי","face-of"],["הָאֲדָמָה","the-earth"],["אֶפֶס","save"],["כִּי","because"],["לֹא","not"],["הַשְׁמֵיד","certainly"],["אַשְׁמִיד","I-destroy"],["אֶת־בֵּית","[ACC]-house-of"],["יַעֲקֹב","Jacob"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"ט", words:[["כִּי־הִנֵּה","because-behold"],["אָנֹכִי","I"],["מְצַוֶּה","command"],["וַהֲנִעוֹתִי","and-I will shake"],["בְכׇל־הַגּוֹיִם","in-all-the-nations"],["אֶת־בֵּית","[ACC]-house-of"],["יִשְׂרָאֵל","Israel"],["כַּאֲשֶׁר","when/as"],["יִנּוֹעַ","it is shaken"],["בַּכְּבָרָה","in-the-sieve"],["וְלֹא־יִפּוֹל","and-not-shall-fall"],["צְרוֹר","the bag of"],["אָרֶץ","the-earth"],["׃",""]] },
  { num:"י", words:[["בַּחֶרֶב","with-the-sword"],["יָמוּתוּ","shall-die"],["כֹּל","all"],["חַטָּאֵי","the sinners of"],["עַמִּי","my-people"],["הָאֹמְרִים","the-ones-saying"],["לֹא־תַגִּישׁ","not-it will bring near"],["וְתַקְדִּים","and-it may meet"],["בַּעֲדֵינוּ","through-us"],["הָרָעָה","the-evil"],["׃",""]] },
  { num:"יא", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["אָקִים","shall-I-raise-up"],["אֶת־סֻכַּת","[ACC]-the booth of"],["דָּוִיד","David"],["הַנֹּפֶלֶת","the-falling"],["וְגָדַרְתִּי","and-I will wall up"],["אֶת־פִּרְצֵיהֶן","[ACC]-breaches-their"],["וַהֲרִסֹתָיו","and-ruins-his"],["אָקִים","shall-I-raise-up"],["וּבְנִיתִיהָ","and-I will rebuild-it"],["כִּימֵי","as-days-of"],["עוֹלָם","eternal"],["׃",""]] },
  { num:"יב", words:[["לְמַעַן","in-order-that"],["יִירְשׁוּ","they-possess"],["אֶת־שְׁאֵרִית","[ACC]-remnant-of"],["אֱדוֹם","Edom"],["וְכׇל־הַגּוֹיִם","and-all-the-nations"],["אֲשֶׁר־נִקְרָא","whose-called-was"],["שְׁמִי","my-name"],["עֲלֵיהֶם","against-them"],["נְאֻם־יְהֹוָה","says-the-LORD"],["עֹשֶׂה","do"],["זֹּאת","this(f)"],["׃",""]] },
  { num:"יג", words:[["הִנֵּה","behold"],["יָמִים","days"],["בָּאִים","come"],["נְאֻם־יְהֹוָה","says-the-LORD"],["וְנִגַּשׁ","and-he will draw near"],["חוֹרֵשׁ","the plowman"],["בַּקֹּצֵר","the-reaper"],["וְדֹרֵךְ","and-one who treads"],["עֲנָבִים","grapes"],["בְּמֹשֵׁךְ","the sower of"],["הַזָּרַע","the-offspring"],["וְהִטִּיפוּ","and-they will drip"],["הֶהָרִים","the-mountains"],["עָסִיס","sweet wine"],["וְכׇל־הַגְּבָעוֹת","and-all-the-hills"],["תִּתְמוֹגַגְנָה","they will flow with it"],["׃",""]] },
  { num:"יד", words:[["וְשַׁבְתִּי","and-I will return"],["אֶת־שְׁבוּת","[ACC]-the-captivity-of"],["עַמִּי","my-people"],["יִשְׂרָאֵל","Israel"],["וּבָנוּ","and-against-us"],["עָרִים","large-cities"],["נְשַׁמּוֹת","breath(pl.f)"],["וְיָשָׁבוּ","and-they will dwell in them"],["וְנָטְעוּ","and-they will plant"],["כְרָמִים","vineyards"],["וְשָׁתוּ","and-they-have-drunk"],["אֶת־יֵינָם","[ACC]-their-wine"],["וְעָשׂוּ","and-they-did-work"],["גַנּוֹת","gardens"],["וְאָכְלוּ","and-did-partake"],["אֶת־פְּרִיהֶם","[ACC]-fruit-their"],["׃",""]] },
  { num:"טו", words:[["וּנְטַעְתִּים","and-I will plant-them"],["עַל־אַדְמָתָם","in-their-own-land"],["וְלֹא","and-not"],["יִנָּתְשׁוּ","are they plucked up"],["עוֹד","any-more"],["מֵעַל","from-upon"],["אַדְמָתָם","their-ground"],["אֲשֶׁר","which"],["נָתַתִּי","I-gave"],["לָהֶם","to-them"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["אֱלֹהֶיךָ","your-God"],["׃",""]] },
];
renderVerseSet(amo_ch9Verses, 'amo-ch9-verses');

})();
