// ot_verses/amo.js — Amos verse data
(function() {
var amo_ch1Verses = [
  { num:"א", words:[["דִּבְרֵי","the words of"],["עָמוֹס","Amos"],["אֲשֶׁר־הָיָה","which was"],["בַנֹּקְדִים","among the herdmen"],["מִתְּקוֹעַ","from Tekoa"],["אֲשֶׁר","which"],["חָזָה","saw"],["עַל־יִשְׂרָאֵל","upon Israel"],["בִּימֵי","in the days of"],["עֻזִּיָּה","Uzziah"],["מֶלֶךְ־יְהוּדָה","king of Judah"],["וּבִימֵי","and in the days of"],["יָרׇבְעָם","Jeroboam"],["בֶּן־יוֹאָשׁ","son of Joash"],["מֶלֶךְ","the king of"],["יִשְׂרָאֵל","Israel"],["שְׁנָתַיִם","two years"],["לִפְנֵי","before"],["הָרָעַשׁ","the earthquake"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמַר","and said"],["יְהֹוָה","the LORD"],["מִצִּיּוֹן","out of Zion"],["יִשְׁאָג","he will roar"],["וּמִירוּשָׁלַ͏ִם","and from Jerusalem"],["יִתֵּן","shall give"],["קוֹלוֹ","His voice"],["וְאָבְלוּ","and mourn"],["נְאוֹת","the pastures of"],["הָרֹעִים","the shepherds"],["וְיָבֵשׁ","shall wither"],["רֹאשׁ","the top of"],["הַכַּרְמֶל","Carmel"],["׃",""]] },
  { num:"ג", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["עַל־שְׁלֹשָׁה","upon three"],["פִּשְׁעֵי","transgressions of"],["דַמֶּשֶׂק","Damascus"],["וְעַל־אַרְבָּעָה","and upon four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will turn it back"],["עַל־דּוּשָׁם","upon threshed they"],["בַּחֲרֻצוֹת","with the threshing sledges of"],["הַבַּרְזֶל","the iron"],["אֶת־הַגִּלְעָד","Gilead"],["׃",""]] },
  { num:"ד", words:[["וְשִׁלַּחְתִּי","and I will send"],["אֵשׁ","fire"],["בְּבֵית","in the house of"],["חֲזָאֵל","Hazael"],["וְאָכְלָה","and shall devour"],["אַרְמְנוֹת","the fortresses of"],["בֶּן־הֲדָד","son of Hadad"],["׃",""]] },
  { num:"ה", words:[["וְשָׁבַרְתִּי","and I will break"],["בְּרִיחַ","a bar"],["דַּמֶּשֶׂק","Damascus"],["וְהִכְרַתִּי","and cut off"],["יוֹשֵׁב","sitting"],["מִבִּקְעַת־אָוֶן","from the plain of Aven"],["וְתוֹמֵךְ","and him that holdeth"],["שֵׁבֶט","the sceptre"],["מִבֵּית","from the house of"],["עֶדֶן","Eden"],["וְגָלוּ","and they will go into exile"],["עַם־אֲרָם","people Syria"],["קִירָה","to Kir"],["אָמַר","said"],["יְהֹוָה","the LORD"],["׃",""]] },
  { num:"ו", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["עַל־שְׁלֹשָׁה","upon three"],["פִּשְׁעֵי","transgressions of"],["עַזָּה","Gaza"],["וְעַל־אַרְבָּעָה","and upon four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will turn it back"],["עַל־הַגְלוֹתָם","upon carried away into exile they"],["גָּלוּת","the exiles of"],["שְׁלֵמָה","complete"],["לְהַסְגִּיר","to deliver up"],["לֶאֱדוֹם","of Edom"],["׃",""]] },
  { num:"ז", words:[["וְשִׁלַּחְתִּי","and I will send"],["אֵשׁ","fire"],["בְּחוֹמַת","in the walls of"],["עַזָּה","Gaza"],["וְאָכְלָה","and shall devour"],["אַרְמְנֹתֶיהָ","its fortresses"],["׃",""]] },
  { num:"ח", words:[["וְהִכְרַתִּי","and cut off"],["יוֹשֵׁב","sitting"],["מֵאַשְׁדּוֹד","from Ashdod"],["וְתוֹמֵךְ","and him that holdeth"],["שֵׁבֶט","the sceptre"],["מֵאַשְׁקְלוֹן","from Ashkelon"],["וַהֲשִׁיבוֹתִי","and I will turn"],["יָדִי","my hand"],["עַל־עֶקְרוֹן","upon Ekron"],["וְאָבְדוּ","and were lost"],["שְׁאֵרִית","remnant of"],["פְּלִשְׁתִּים","Philistines"],["אָמַר","said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["׃",""]] },
  { num:"ט", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["עַל־שְׁלֹשָׁה","upon three"],["פִּשְׁעֵי־צֹר","transgressions of Tyre"],["וְעַל־אַרְבָּעָה","and upon four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will turn it back"],["עַל־הַסְגִּירָם","upon delivered up they"],["גָּלוּת","the exiles of"],["שְׁלֵמָה","complete"],["לֶאֱדוֹם","of Edom"],["וְלֹא","and not"],["זָכְרוּ","they remembered"],["בְּרִית","covenant of"],["אַחִים","brothers"],["׃",""]] },
  { num:"י", words:[["וְשִׁלַּחְתִּי","and I will send"],["אֵשׁ","fire"],["בְּחוֹמַת","in the walls of"],["צֹר","Tyre"],["וְאָכְלָה","and shall devour"],["אַרְמְנוֹתֶיהָ","its palaces"],["׃",""]] },
  { num:"יא", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["עַל־שְׁלֹשָׁה","upon three"],["פִּשְׁעֵי","transgressions of"],["אֱדוֹם","Edom"],["וְעַל־אַרְבָּעָה","and upon four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will turn it back"],["עַל־רׇדְפוֹ","upon pursued he"],["בַחֶרֶב","by the sword"],["אָחִיו","his brother"],["וְשִׁחֵת","and he spoiled"],["רַחֲמָיו","his pity"],["וַיִּטְרֹף","and it tore"],["לָעַד","forever"],["אַפּוֹ","his anger"],["וְעֶבְרָתוֹ","and his fury"],["שְׁמָרָהֿ","he kept it"],["נֶצַח","eternal"],["׃",""]] },
  { num:"יב", words:[["וְשִׁלַּחְתִּי","and I will send"],["אֵשׁ","fire"],["בְּתֵימָן","in Teman"],["וְאָכְלָה","and shall devour"],["אַרְמְנוֹת","the fortresses of"],["בׇּצְרָה","Bozrah"],["׃",""]] },
  { num:"יג", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["עַל־שְׁלֹשָׁה","upon three"],["פִּשְׁעֵי","transgressions of"],["בְנֵי־עַמּוֹן","sons of Ammon"],["וְעַל־אַרְבָּעָה","and upon four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will turn it back"],["עַל־בִּקְעָם","upon ripped open they"],["הָרוֹת","with the child"],["הַגִּלְעָד","Gilead"],["לְמַעַן","in order that"],["הַרְחִיב","to enlarge"],["אֶת־גְּבוּלָם","their territory"],["׃",""]] },
  { num:"יד", words:[["וְהִצַּתִּי","and I will kindle"],["אֵשׁ","fire"],["בְּחוֹמַת","in the walls of"],["רַבָּה","Rabbah"],["וְאָכְלָה","and shall devour"],["אַרְמְנוֹתֶיהָ","its palaces"],["בִּתְרוּעָה","with shouting"],["בְּיוֹם","in the day of"],["מִלְחָמָה","war"],["בְּסַעַר","with a storm"],["בְּיוֹם","in the day of"],["סוּפָה","a storm wind"],["׃",""]] },
  { num:"טו", words:[["וְהָלַךְ","and go"],["מַלְכָּם","their king"],["בַּגּוֹלָה","in the exile"],["הוּא","he"],["וְשָׂרָיו","and their princes"],["יַחְדָּו","together"],["אָמַר","said"],["יְהֹוָה","the LORD"],["׃",""]] },
];
renderVerseSet(amo_ch1Verses, 'amo-ch1-verses');

var amo_ch2Verses = [
  { num:"א", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["עַל־שְׁלֹשָׁה","upon three"],["פִּשְׁעֵי","transgressions of"],["מוֹאָב","Moab"],["וְעַל־אַרְבָּעָה","and upon four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will turn it back"],["עַל־שׇׂרְפוֹ","upon burned he"],["עַצְמוֹת","the bones of"],["מֶלֶךְ־אֱדוֹם","king of Edom"],["לַשִּׂיד","into the lime"],["׃",""]] },
  { num:"ב", words:[["וְשִׁלַּחְתִּי־אֵשׁ","and I will send fire"],["בְּמוֹאָב","against Moab"],["וְאָכְלָה","and shall devour"],["אַרְמְנוֹת","the fortresses of"],["הַקְּרִיּוֹת","the Kerioth"],["וּמֵת","and he will die"],["בְּשָׁאוֹן","in uproar"],["מוֹאָב","Moab"],["בִּתְרוּעָה","with shouting"],["בְּקוֹל","the voice of"],["שׁוֹפָר","a ram's horn"],["׃",""]] },
  { num:"ג", words:[["וְהִכְרַתִּי","and cut off"],["שׁוֹפֵט","the judge"],["מִקִּרְבָּהּ","from her midst"],["וְכׇל־שָׂרֶיהָ","and all its princes"],["אֶהֱרוֹג","I will kill"],["עִמּוֹ","with him"],["אָמַר","said"],["יְהֹוָה","the LORD"],["׃",""]] },
  { num:"ד", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["עַל־שְׁלֹשָׁה","upon three"],["פִּשְׁעֵי","transgressions of"],["יְהוּדָה","Judah"],["וְעַל־אַרְבָּעָה","and upon four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will turn it back"],["עַל־מׇאֳסָם","upon their rejecting"],["אֶת־תּוֹרַת","the law of"],["יְהֹוָה","the LORD"],["וְחֻקָּיו","and his statutes"],["לֹא","not"],["שָׁמָרוּ","they kept"],["וַיַּתְעוּם","and they have misled them"],["כִּזְבֵיהֶם","their lies"],["אֲשֶׁר־הָלְכוּ","which went"],["אֲבוֹתָם","their fathers"],["אַחֲרֵיהֶם","after them"],["׃",""]] },
  { num:"ה", words:[["וְשִׁלַּחְתִּי","and I will send"],["אֵשׁ","fire"],["בִּיהוּדָה","through Judah"],["וְאָכְלָה","and shall devour"],["אַרְמְנוֹת","the fortresses of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["׃",""]] },
  { num:"ו", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["עַל־שְׁלֹשָׁה","upon three"],["פִּשְׁעֵי","transgressions of"],["יִשְׂרָאֵל","Israel"],["וְעַל־אַרְבָּעָה","and upon four"],["לֹא","not"],["אֲשִׁיבֶנּוּ","I will turn it back"],["עַל־מִכְרָם","because they sold"],["בַּכֶּסֶף","in the silver"],["צַדִּיק","righteous"],["וְאֶבְיוֹן","and the poor"],["בַּעֲבוּר","because of"],["נַעֲלָיִם","a pair of sandals"],["׃",""]] },
  { num:"ז", words:[["הַשֹּׁאֲפִים","that pant after"],["עַל־עֲפַר־אֶרֶץ","upon the dust of the earth"],["בְּרֹאשׁ","on the head of"],["דַּלִּים","the poor"],["וְדֶרֶךְ","and the way of"],["עֲנָוִים","the meek"],["יַטּוּ","they shall turn"],["וְאִישׁ","and a man"],["וְאָבִיו","and his father"],["יֵלְכוּ","they should travel"],["אֶל־הַנַּעֲרָה","to the young woman"],["לְמַעַן","in order that"],["חַלֵּל","to profane"],["אֶת־שֵׁם","name of"],["קׇדְשִׁי","my holiness"],["׃",""]] },
  { num:"ח", words:[["וְעַל־בְּגָדִים","and upon garments"],["חֲבֻלִים","taken in pledge"],["יַטּוּ","they lay themselves down"],["אֵצֶל","near"],["כׇּל־מִזְבֵּחַ","all an altar"],["וְיֵין","and wine of"],["עֲנוּשִׁים","fines"],["יִשְׁתּוּ","they drink"],["בֵּית","in the house of"],["אֱלֹהֵיהֶם","their gods"],["׃",""]] },
  { num:"ט", words:[["וְאָנֹכִי","yet I"],["הִשְׁמַדְתִּי","I destroyed"],["אֶת־הָאֱמֹרִי","the Amorite"],["מִפְּנֵיהֶם","from before them"],["אֲשֶׁר","which"],["כְּגֹבַהּ","according to the haughtiness of"],["אֲרָזִים","cedars"],["גׇּבְהוֹ","his height"],["וְחָסֹן","and is strong"],["הוּא","he"],["כָּאַלּוֹנִים","like oaks"],["וָאַשְׁמִיד","and I destroyed"],["פִּרְיוֹ","his fruit"],["מִמַּעַל","above"],["וְשׇׁרָשָׁיו","and its roots"],["מִתָּחַת","beneath"],["׃",""]] },
  { num:"י", words:[["וְאָנֹכִי","yet I"],["הֶעֱלֵיתִי","I brought up"],["אֶתְכֶם","you"],["מֵאֶרֶץ","from the land of"],["מִצְרָיִם","Egypt"],["וָאוֹלֵךְ","and I made walk"],["אֶתְכֶם","you"],["בַּמִּדְבָּר","in the wilderness"],["אַרְבָּעִים","forty"],["שָׁנָה","years"],["לָרֶשֶׁת","to possess"],["אֶת־אֶרֶץ","land of"],["הָאֱמֹרִי","the Amorite"],["׃",""]] },
  { num:"יא", words:[["וָאָקִים","and I raised up"],["מִבְּנֵיכֶם","some of your sons"],["לִנְבִיאִים","to prophets"],["וּמִבַּחוּרֵיכֶם","and some of your young men"],["לִנְזִרִים","to Nazarites"],["הַאַף","is it also"],["אֵין־זֹאת","there is no this"],["בְּנֵי","the sons of"],["יִשְׂרָאֵל","Israel"],["נְאֻם־יְהֹוָה","says the LORD"],["׃",""]] },
  { num:"יב", words:[["וַתַּשְׁקוּ","and you made drink"],["אֶת־הַנְּזִרִים","the Nazarites"],["יָיִן","wine"],["וְעַל־הַנְּבִיאִים","and upon the prophets"],["צִוִּיתֶם","you commanded"],["לֵאמֹר","saying"],["לֹא","not"],["תִּנָּבְאוּ","you shall prophesy"],["׃",""]] },
  { num:"יג", words:[["הִנֵּה","behold"],["אָנֹכִי","I"],["מֵעִיק","am pressed"],["תַּחְתֵּיכֶם","under you"],["כַּאֲשֶׁר","as"],["תָּעִיק","is pressed"],["הָעֲגָלָה","the cart"],["הַמְלֵאָה","that is full"],["לָהּ","to her"],["עָמִיר","cut grain"],["׃",""]] },
  { num:"יד", words:[["וְאָבַד","and lost"],["מָנוֹס","deliverance"],["מִקָּל","from the swift"],["וְחָזָק","and mighty"],["לֹא־יְאַמֵּץ","not he will make firm"],["כֹּחוֹ","his strength"],["וְגִבּוֹר","and mighty"],["לֹא־יְמַלֵּט","not he delivers"],["נַפְשׁוֹ","his soul"],["׃",""]] },
  { num:"טו", words:[["וְתֹפֵשׂ","and one who wields"],["הַקֶּשֶׁת","the bow"],["לֹא","not"],["יַעֲמֹד","shall stand"],["וְקַל","and a person swift"],["בְּרַגְלָיו","his feet"],["לֹא","not"],["יְמַלֵּט","he delivers"],["וְרֹכֵב","and the rider of"],["הַסּוּס","the horses"],["לֹא","not"],["יְמַלֵּט","he delivers"],["נַפְשׁוֹ","his soul"],["׃",""]] },
  { num:"טז", words:[["וְאַמִּיץ","and strong of"],["לִבּוֹ","his heart"],["בַּגִּבּוֹרִים","among the mighty ones"],["עָרוֹם","naked"],["יָנוּס","flee"],["בַּיּוֹם־הַהוּא","in the day that"],["נְאֻם־יְהֹוָה","says the LORD"],["׃",""]] },
];
renderVerseSet(amo_ch2Verses, 'amo-ch2-verses');

var amo_ch3Verses = [
  { num:"א", words:[["שִׁמְעוּ","hear"],["אֶת־הַדָּבָר","the word"],["הַזֶּה","this"],["אֲשֶׁר","which"],["דִּבֶּר","spoke"],["יְהֹוָה","the LORD"],["עֲלֵיכֶם","over you"],["בְּנֵי","the sons of"],["יִשְׂרָאֵל","Israel"],["עַל","upon"],["כׇּל־הַמִּשְׁפָּחָה","all the family"],["אֲשֶׁר","which"],["הֶעֱלֵיתִי","I brought up"],["מֵאֶרֶץ","from the land of"],["מִצְרַיִם","Egypt"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ב", words:[["רַק","only"],["אֶתְכֶם","you"],["יָדַעְתִּי","I know"],["מִכֹּל","of all"],["מִשְׁפְּחוֹת","families of"],["הָאֲדָמָה","the earth"],["עַל־כֵּן","therefore"],["אֶפְקֹד","I will punish"],["עֲלֵיכֶם","over you"],["אֵת־כׇּל־עֲוֺנֹתֵיכֶם","all your iniquities"],["׃",""]] },
  { num:"ג", words:[["הֲיֵלְכוּ","do they walk"],["שְׁנַיִם","two"],["יַחְדָּו","together"],["בִּלְתִּי","except"],["אִם־נוֹעָדוּ","if they have met by appointment"],["׃",""]] },
  { num:"ד", words:[["הֲיִשְׁאַג","does it roar"],["אַרְיֵה","a lion"],["בַּיַּעַר","in the forest"],["וְטֶרֶף","and he tears"],["אֵין","there is no"],["לוֹ","to him"],["הֲיִתֵּן","does it give forth"],["כְּפִיר","a young lion of"],["קוֹלוֹ","his voice"],["מִמְּעֹנָתוֹ","from its den"],["בִּלְתִּי","except"],["אִם־לָכָד","if it has caught something"],["׃",""]] },
  { num:"ה", words:[["הֲתִפֹּל","does it fall"],["צִפּוֹר","bird"],["עַל־פַּח","upon a snare"],["הָאָרֶץ","the earth"],["וּמוֹקֵשׁ","and is a snare"],["אֵין","there is no"],["לָהּ","to her"],["הֲיַעֲלֶה־פַּח","does it go up a snare"],["מִן־הָאֲדָמָה","from the ground"],["וְלָכוֹד","and taken"],["לֹא","not"],["יִלְכּוֹד","it catches something"],["׃",""]] },
  { num:"ו", words:[["אִם־יִתָּקַע","if it will be blown"],["שׁוֹפָר","a ram's horn"],["בְּעִיר","in a city"],["וְעָם","and people"],["לֹא","not"],["יֶחֱרָדוּ","they tremble"],["אִם־תִּהְיֶה","if shall be"],["רָעָה","evil"],["בְּעִיר","in a city"],["וַיהֹוָה","and the LORD"],["לֹא","not"],["עָשָׂה","he did"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["לֹא","not"],["יַעֲשֶׂה","he shall do"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["דָּבָר","a thing"],["כִּי","because"],["אִם־גָּלָה","but he revealeth"],["סוֹדוֹ","His counsel"],["אֶל־עֲבָדָיו","to his servants"],["הַנְּבִיאִים","the prophets"],["׃",""]] },
  { num:"ח", words:[["אַרְיֵה","a lion"],["שָׁאָג","it has roared"],["מִי","who"],["לֹא","not"],["יִירָא","it will fear"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["דִּבֶּר","spoke"],["מִי","who"],["לֹא","not"],["יִנָּבֵא","he prophesies"],["׃",""]] },
  { num:"ט", words:[["הַשְׁמִיעוּ","tell"],["עַל־אַרְמְנוֹת","upon the fortresses of"],["בְּאַשְׁדּוֹד","in Ashdod"],["וְעַל־אַרְמְנוֹת","and upon the fortresses of"],["בְּאֶרֶץ","in the land of"],["מִצְרָיִם","Egypt"],["וְאִמְרוּ","and say"],["הֵאָסְפוּ","gather yourselves"],["עַל־הָרֵי","upon the mountains of"],["שֹׁמְרוֹן","Samaria"],["וּרְאוּ","and see"],["מְהוּמֹת","disturbances"],["רַבּוֹת","many"],["בְּתוֹכָהּ","in its midst"],["וַעֲשׁוּקִים","and oppression"],["בְּקִרְבָּהּ","in the midst thereof"],["׃",""]] },
  { num:"י", words:[["וְלֹא־יָדְעוּ","and not they knew"],["עֲשׂוֹת־נְכֹחָה","to do right"],["נְאֻם־יְהֹוָה","says the LORD"],["הָאוֹצְרִים","the ones who store up"],["חָמָס","violence"],["וָשֹׁד","and havoc"],["בְּאַרְמְנוֹתֵיהֶם","in their fortresses"],["׃",""]] },
  { num:"יא", words:[["לָכֵן","therefore"],["כֹּה","thus"],["אָמַר","said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["צַר","an adversary"],["וּסְבִיב","and around"],["הָאָרֶץ","the land"],["וְהוֹרִיד","and lead down"],["מִמֵּךְ","from you"],["עֻזֵּךְ","your strength"],["וְנָבֹזּוּ","and they will be plundered"],["אַרְמְנוֹתָיִךְ","your fortresses"],["׃",""]] },
  { num:"יב", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["כַּאֲשֶׁר","as"],["יַצִּיל","shall deliver"],["הָרֹעֶה","the shepherd"],["מִפִּי","from the mouth of"],["הָאֲרִי","the lion"],["שְׁתֵּי","two"],["כְרָעַיִם","legs"],["אוֹ","or"],["בְדַל־אֹזֶן","a piece of an ear"],["כֵּן","thus"],["יִנָּצְלוּ","shall be taken out"],["בְּנֵי","the sons of"],["יִשְׂרָאֵל","Israel"],["הַיֹּשְׁבִים","the inhabitants"],["בְּשֹׁמְרוֹן","in Samaria"],["בִּפְאַת","with a corner of"],["מִטָּה","a bed"],["וּבִדְמֶשֶׁק","and in Damascus"],["עָרֶשׂ","a couch"],["׃",""]] },
  { num:"יג", words:[["שִׁמְעוּ","hear"],["וְהָעִידוּ","and testify"],["בְּבֵית","in the house of"],["יַעֲקֹב","Jacob"],["נְאֻם־אֲדֹנָי","says Lord"],["יֱהֹוִה","GOD"],["אֱלֹהֵי","the God of"],["הַצְּבָאוֹת","of hosts"],["׃",""]] },
  { num:"יד", words:[["כִּי","that"],["בְּיוֹם","in the day of"],["פׇּקְדִי","I shall visit"],["פִשְׁעֵי־יִשְׂרָאֵל","the transgressions of Israel"],["עָלָיו","upon him"],["וּפָקַדְתִּי","I will also visit"],["עַל־מִזְבְּחוֹת","upon altars"],["בֵּית־אֵל","Beth-el"],["וְנִגְדְּעוּ","and they will be cut down"],["קַרְנוֹת","the horns of"],["הַמִּזְבֵּחַ","the altar"],["וְנָפְלוּ","and they shall fall"],["לָאָרֶץ","to the ground"],["׃",""]] },
  { num:"טו", words:[["וְהִכֵּיתִי","and I will smite"],["בֵית־הַחֹרֶף","house of the winter"],["עַל־בֵּית","to the house of"],["הַקָּיִץ","the summer"],["וְאָבְדוּ","and were lost"],["בָּתֵּי","the houses of"],["הַשֵּׁן","ivory"],["וְסָפוּ","shall have an end"],["בָּתִּים","houses"],["רַבִּים","many"],["נְאֻם־יְהֹוָה","says the LORD"],["׃",""]] },
];
renderVerseSet(amo_ch3Verses, 'amo-ch3-verses');

var amo_ch4Verses = [
  { num:"א", words:[["שִׁמְעוּ","hear"],["הַדָּבָר","the word"],["הַזֶּה","this"],["פָּרוֹת","cows"],["הַבָּשָׁן","Bashan"],["אֲשֶׁר","which"],["בְּהַר","on the mount of"],["שֹׁמְרוֹן","Samaria"],["הָעֹשְׁקוֹת","those who oppress"],["דַּלִּים","the poor"],["הָרֹצְצוֹת","those who crush"],["אֶבְיוֹנִים","needy"],["הָאֹמְרֹת","the one who say"],["לַאֲדֹנֵיהֶם","to their master"],["הָבִיאָה","bring"],["וְנִשְׁתֶּה","and drink"],["׃",""]] },
  { num:"ב", words:[["נִשְׁבַּע","swore"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["בְּקׇדְשׁוֹ","by his holiness"],["כִּי","that"],["הִנֵּה","behold"],["יָמִים","days"],["בָּאִים","come"],["עֲלֵיכֶם","over you"],["וְנִשָּׂא","and he will take you away"],["אֶתְכֶם","you"],["בְּצִנּוֹת","with hooks"],["וְאַחֲרִיתְכֶן","and your posterity"],["בְּסִירוֹת","with hooks of"],["דּוּגָה","fishing"],["׃",""]] },
  { num:"ג", words:[["וּפְרָצִים","and breaches"],["תֵּצֶאנָה","you will go out"],["אִשָּׁה","a woman"],["נֶגְדָּהּ","before herself"],["וְהִשְׁלַכְתֶּנָה","and you will throw"],["הַהַרְמוֹנָה","into the palace"],["נְאֻם־יְהֹוָה","says the LORD"],["׃",""]] },
  { num:"ד", words:[["בֹּאוּ","come"],["בֵית־אֵל","Beth-el"],["וּפִשְׁעוּ","and transgress"],["הַגִּלְגָּל","Gilgal"],["הַרְבּוּ","increase"],["לִפְשֹׁעַ","to transgress"],["וְהָבִיאוּ","and bring"],["לַבֹּקֶר","every morning"],["זִבְחֵיכֶם","your sacrifices"],["לִשְׁלֹשֶׁת","to three"],["יָמִים","days"],["מַעְשְׂרֹתֵיכֶם","your tithes"],["׃",""]] },
  { num:"ה", words:[["וְקַטֵּר","and offer"],["מֵחָמֵץ","from a thing leavened"],["תּוֹדָה","thanksgiving"],["וְקִרְאוּ","and call"],["נְדָבוֹת","free offerings"],["הַשְׁמִיעוּ","tell"],["כִּי","for"],["כֵן","thus"],["אֲהַבְתֶּם","you love"],["בְּנֵי","the sons of"],["יִשְׂרָאֵל","Israel"],["נְאֻם","says"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["׃",""]] },
  { num:"ו", words:[["וְגַם־אֲנִי","and also I"],["נָתַתִּי","I gave"],["לָכֶם","to you"],["נִקְיוֹן","cleanness of"],["שִׁנַּיִם","teeth"],["בְּכׇל־עָרֵיכֶם","in all cities of you"],["וְחֹסֶר","and the lack of"],["לֶחֶם","bread"],["בְּכֹל","in all"],["מְקוֹמֹתֵיכֶם","your places"],["וְלֹא־שַׁבְתֶּם","and not return"],["עָדַי","to me"],["נְאֻם־יְהֹוָה","says the LORD"],["׃",""]] },
  { num:"ז", words:[["וְגַם","and also"],["אָנֹכִי","I"],["מָנַעְתִּי","I have withholden"],["מִכֶּם","from you"],["אֶת־הַגֶּשֶׁם","the rain"],["בְּעוֹד","in yet"],["שְׁלֹשָׁה","three"],["חֳדָשִׁים","months"],["לַקָּצִיר","were to the harvest"],["וְהִמְטַרְתִּי","and I sent rain"],["עַל־עִיר","upon the city of"],["אֶחָת","one"],["וְעַל־עִיר","and upon the city of"],["אַחַת","one"],["לֹא","not"],["אַמְטִיר","I will rain down"],["חֶלְקָה","portion of land"],["אַחַת","one"],["תִּמָּטֵר","it was rained on"],["וְחֶלְקָה","and a portion of ground"],["אֲשֶׁר־לֹא־תַמְטִיר","which not it sent rain"],["עָלֶיהָ","upon it"],["תִּיבָשׁ","it will wither"],["׃",""]] },
  { num:"ח", words:[["וְנָעוּ","and wandered"],["שְׁתַּיִם","two"],["שָׁלֹשׁ","three"],["עָרִים","cities"],["אֶל־עִיר","unto the city of"],["אַחַת","one"],["לִשְׁתּוֹת","to drink"],["מַיִם","water"],["וְלֹא","and not"],["יִשְׂבָּעוּ","they will be satisfied"],["וְלֹא־שַׁבְתֶּם","and not return"],["עָדַי","to me"],["נְאֻם־יְהֹוָה","says the LORD"],["׃",""]] },
  { num:"ט", words:[["הִכֵּיתִי","I have smitten"],["אֶתְכֶם","you"],["בַּשִּׁדָּפוֹן","with the blight"],["וּבַיֵּרָקוֹן","and with the mildew"],["הַרְבּוֹת","when increased"],["גַּנּוֹתֵיכֶם","your gardens"],["וְכַרְמֵיכֶם","and your vineyards"],["וּתְאֵנֵיכֶם","and your fig trees"],["וְזֵיתֵיכֶם","and your olive groves"],["יֹאכַל","he shall eat"],["הַגָּזָם","the palmerworm"],["וְלֹא־שַׁבְתֶּם","and not return"],["עָדַי","to me"],["נְאֻם־יְהֹוָה","says the LORD"],["׃",""]] },
  { num:"י", words:[["שִׁלַּחְתִּי","I have sent"],["בָכֶם","over you"],["דֶּבֶר","a pestilence"],["בְּדֶרֶךְ","by the way of"],["מִצְרַיִם","Egypt"],["הָרַגְתִּי","I slew"],["בַחֶרֶב","by the sword"],["בַּחוּרֵיכֶם","your young men"],["עִם","with"],["שְׁבִי","the captivity of"],["סוּסֵיכֶם","your horses"],["וָאַעֲלֶה","and I offered up"],["בְּאֹשׁ","the stench of"],["מַחֲנֵיכֶם","your camp"],["וּבְאַפְּכֶם","unto your nostrils"],["וְלֹא־שַׁבְתֶּם","and not return"],["עָדַי","to me"],["נְאֻם־יְהֹוָה","says the LORD"],["׃",""]] },
  { num:"יא", words:[["הָפַכְתִּי","I overthrew"],["בָכֶם","over you"],["כְּמַהְפֵּכַת","as the overthrow of"],["אֱלֹהִים","God"],["אֶת־סְדֹם","Sodom"],["וְאֶת־עֲמֹרָה","and Gomorrah"],["וַתִּהְיוּ","and have been"],["כְּאוּד","like a piece of firewood"],["מֻצָּל","plucked out"],["מִשְּׂרֵפָה","from burning"],["וְלֹא־שַׁבְתֶּם","and not return"],["עָדַי","to me"],["נאֻם־יְהֹוָה","says the LORD"],["׃",""]] },
  { num:"יב", words:[["לָכֵן","therefore"],["כֹּה","thus"],["אֶעֱשֶׂה־לְּךָ","will I do to you"],["יִשְׂרָאֵל","Israel"],["עֵקֶב","because"],["כִּי־זֹאת","because this"],["אֶעֱשֶׂה־לָּךְ","I will do to you"],["הִכּוֹן","be prepared"],["לִקְרַאת־אֱלֹהֶיךָ","to meet your God"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"יג", words:[["כִּי","for"],["הִנֵּה","behold"],["יוֹצֵר","he that formeth"],["הָרִים","mountains"],["וּבֹרֵא","and one who created"],["רוּחַ","the wind"],["וּמַגִּיד","and tells"],["לְאָדָם","to man"],["מַה־שֵּׂחוֹ","what is his thought"],["עֹשֵׂה","that does"],["שַׁחַר","dawn"],["עֵיפָה","darkness"],["וְדֹרֵךְ","and one who treads"],["עַל־בָּמֳתֵי","upon the high places of"],["אָרֶץ","the earth"],["יְהֹוָה","the LORD"],["אֱלֹהֵי־צְבָאוֹת","God of Hosts"],["שְׁמוֹ","his name"],["׃",""]] },
];
renderVerseSet(amo_ch4Verses, 'amo-ch4-verses');

var amo_ch5Verses = [
  { num:"א", words:[["שִׁמְעוּ","hear"],["אֶת־הַדָּבָר","the word"],["הַזֶּה","this"],["אֲשֶׁר","which"],["אָנֹכִי","I"],["נֹשֵׂא","bearing"],["עֲלֵיכֶם","over you"],["קִינָה","a lamentation"],["בֵּית","the house of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"ב", words:[["נָפְלָה","fell"],["לֹא־תוֹסִיף","she shall no more"],["קוּם","arise"],["בְּתוּלַת","virgin of"],["יִשְׂרָאֵל","Israel"],["נִטְּשָׁה","she has been abandoned"],["עַל־אַדְמָתָהּ","upon her own land"],["אֵין","there is no"],["מְקִימָהּ","to raise her up"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["כֹה","thus"],["אָמַר","said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["הָעִיר","the city"],["הַיֹּצֵאת","the one who will come out"],["אֶלֶף","thousand"],["תַּשְׁאִיר","it will have left"],["מֵאָה","a hundred"],["וְהַיּוֹצֵאת","and the one which goes out"],["מֵאָה","a hundred"],["תַּשְׁאִיר","it will have left"],["עֲשָׂרָה","ten"],["לְבֵית","to the house of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"ד", words:[["כִּי","for"],["כֹה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["לְבֵית","to the house of"],["יִשְׂרָאֵל","Israel"],["דִּרְשׁוּנִי","seek me"],["וִחְיוּ","and live"],["׃",""]] },
  { num:"ה", words:[["וְאַל־תִּדְרְשׁוּ","and do not seek"],["בֵּית־אֵל","Beth-el"],["וְהַגִּלְגָּל","and Gilgal"],["לֹא","not"],["תָבֹאוּ","you come"],["וּבְאֵר","and Beer-"],["שֶׁבַע","sheba"],["לֹא","not"],["תַעֲבֹרוּ","you shall pass over"],["כִּי","for"],["הַגִּלְגָּל","Gilgal"],["גָּלֹה","surely"],["יִגְלֶה","shall go into captivity"],["וּבֵית־אֵל","and Beth-el"],["יִהְיֶה","shall be"],["לְאָוֶן","to nought"],["׃",""]] },
  { num:"ו", words:[["דִּרְשׁוּ","seek"],["אֶת־יְהֹוָה","the LORD"],["וִחְיוּ","and live"],["פֶּן־יִצְלַח","lest he break out"],["כָּאֵשׁ","like fire"],["בֵּית","the house of"],["יוֹסֵף","Joseph"],["וְאָכְלָה","and shall devour"],["וְאֵין־מְכַבֶּה","and there be none to quench"],["לְבֵית־אֵל","to Beth-el"],["׃",""]] },
  { num:"ז", words:[["הַהֹפְכִים","O those who turn"],["לְלַעֲנָה","into wormwood"],["מִשְׁפָּט","judgment"],["וּצְדָקָה","and righteousness"],["לָאָרֶץ","in the earth"],["הִנִּיחוּ","leave off"],["׃",""]] },
  { num:"ח", words:[["עֹשֵׂה","that maketh"],["כִימָה","the seven stars"],["וּכְסִיל","and Orion"],["וְהֹפֵךְ","and the one who turns"],["לַבֹּקֶר","to the morning"],["צַלְמָוֶת","the shadow of death"],["וְיוֹם","and day"],["לַיְלָה","night"],["הֶחְשִׁיךְ","he makes dark"],["הַקּוֹרֵא","that calleth"],["לְמֵי־הַיָּם","to the waters of the sea"],["וַיִּשְׁפְּכֵם","and he poured out them"],["עַל־פְּנֵי","upon the face of"],["הָאָרֶץ","the earth"],["יְהֹוָה","the LORD"],["שְׁמוֹ","his name"],["׃",""]] },
  { num:"ט", words:[["הַמַּבְלִיג","that strengtheneth"],["שֹׁד","the spoiled"],["עַל־עָז","upon mighty"],["וְשֹׁד","and desolation"],["עַל־מִבְצָר","upon fortification"],["יָבוֹא","shall come"],["׃",""]] },
  { num:"י", words:[["שָׂנְאוּ","they hated"],["בַשַּׁעַר","by the gate"],["מוֹכִיחַ","him that rebuketh"],["וְדֹבֵר","and speaking"],["תָּמִים","uprightly"],["יְתָעֵבוּ","they abhor"],["׃",""]] },
  { num:"יא", words:[["לָכֵן","therefore"],["יַעַן","because"],["בּוֹשַׁסְכֶם","your treading is"],["עַל־דָּל","upon the poor"],["וּמַשְׂאַת־בַּר","and burdens of wheat"],["תִּקְחוּ","you will take"],["מִמֶּנּוּ","from him"],["בָּתֵּי","the houses of"],["גָזִית","hewn stone"],["בְּנִיתֶם","you built"],["וְלֹא־תֵשְׁבוּ","and not you shall dwell"],["בָם","in them"],["כַּרְמֵי־חֶמֶד","the vineyards of delight"],["נְטַעְתֶּם","you had planted"],["וְלֹא","and not"],["תִשְׁתּוּ","you will drink"],["אֶת־יֵינָם","their wine"],["׃",""]] },
  { num:"יב", words:[["כִּי","for"],["יָדַעְתִּי","I know"],["רַבִּים","many"],["פִּשְׁעֵיכֶם","your transgressions"],["וַעֲצֻמִים","and mighty"],["חַטֹּאתֵיכֶם","your sins"],["צֹרְרֵי","they afflict"],["צַדִּיק","righteous"],["לֹקְחֵי","they take"],["כֹפֶר","a ransom"],["וְאֶבְיוֹנִים","and the needy"],["בַּשַּׁעַר","by the gate"],["הִטּוּ","they turned"],["׃",""]] },
  { num:"יג", words:[["לָכֵן","therefore"],["הַמַּשְׂכִּיל","the prudent person"],["בָּעֵת","at the time"],["הַהִיא","that"],["יִדֹּם","it may be silent"],["כִּי","for"],["עֵת","time"],["רָעָה","evil"],["הִיא","it is"],["׃",""]] },
  { num:"יד", words:[["דִּרְשׁוּ־טוֹב","seek good"],["וְאַל־רָע","and do not evil"],["לְמַעַן","in order that"],["תִּחְיוּ","you may live"],["וִיהִי־כֵן","and may be thus"],["יְהֹוָה","the LORD"],["אֱלֹהֵי־צְבָאוֹת","God of Hosts"],["אִתְּכֶם","with you"],["כַּאֲשֶׁר","as"],["אֲמַרְתֶּם","you have said"],["׃",""]] },
  { num:"טו", words:[["שִׂנְאוּ־רָע","hate evil"],["וְאֶהֱבוּ","and love"],["טוֹב","good"],["וְהַצִּיגוּ","and establish"],["בַשַּׁעַר","by the gate"],["מִשְׁפָּט","judgment"],["אוּלַי","perhaps"],["יֶחֱנַן","will show favor to"],["יְהֹוָה","the LORD"],["אֱלֹהֵי־צְבָאוֹת","God of Hosts"],["שְׁאֵרִית","remnant of"],["יוֹסֵף","Joseph"],["׃",""]] },
  { num:"טז", words:[["לָכֵן","therefore"],["כֹּה־אָמַר","thus says"],["יְהֹוָה","the LORD"],["אֱלֹהֵי","the God of"],["צְבָאוֹת","Hosts"],["אֲדֹנָי","Lord"],["בְּכׇל־רְחֹבוֹת","in all streets"],["מִסְפֵּד","a lament"],["וּבְכׇל־חוּצוֹת","and in all the streets"],["יֹאמְרוּ","shall say"],["הוֹ־הוֹ","Alas alas"],["וְקָרְאוּ","and called upon"],["אִכָּר","a farmer"],["אֶל־אֵבֶל","to a great mourning"],["וּמִסְפֵּד","and lamentation"],["אֶל־יוֹדְעֵי","to knowers of"],["נֶהִי","wailing"],["׃",""]] },
  { num:"יז", words:[["וּבְכׇל־כְּרָמִים","and in all vineyards"],["מִסְפֵּד","a lament"],["כִּי־אֶעֱבֹר","because let me pass"],["בְּקִרְבְּךָ","in your midst"],["אָמַר","said"],["יְהֹוָה","the LORD"],["׃",""]] },
  { num:"יח", words:[["הוֹי","O"],["הַמִּתְאַוִּים","those who craved"],["אֶת־יוֹם","the day of"],["יְהֹוָה","the LORD"],["לָמָּה־זֶּה","why this"],["לָכֶם","to you"],["יוֹם","day"],["יְהֹוָה","the LORD"],["הוּא־חֹשֶׁךְ","it is darkness"],["וְלֹא־אוֹר","and not light"],["׃",""]] },
  { num:"יט", words:[["כַּאֲשֶׁר","as"],["יָנוּס","flee"],["אִישׁ","a man"],["מִפְּנֵי","because of"],["הָאֲרִי","the lion"],["וּפְגָעוֹ","and it meets him"],["הַדֹּב","the bear"],["וּבָא","and come"],["הַבַּיִת","the house"],["וְסָמַךְ","and shall lay"],["יָדוֹ","his hand"],["עַל־הַקִּיר","upon the wall"],["וּנְשָׁכוֹ","and it bites him"],["הַנָּחָשׁ","the serpent"],["׃",""]] },
  { num:"כ", words:[["הֲלֹא־חֹשֶׁךְ","is it not darkness"],["יוֹם","day"],["יְהֹוָה","the LORD"],["וְלֹא־אוֹר","and not light"],["וְאָפֵל","and gloomy"],["וְלֹא־נֹגַהּ","and not light"],["לוֹ","to him"],["׃",""]] },
  { num:"כא", words:[["שָׂנֵאתִי","I hate"],["מָאַסְתִּי","I rejected"],["חַגֵּיכֶם","your feasts"],["וְלֹא","and not"],["אָרִיחַ","I will smell"],["בְּעַצְּרֹתֵיכֶם","in your assemblies"],["׃",""]] },
  { num:"כב", words:[["כִּי","because"],["אִם־תַּעֲלוּ־לִי","if go up to me"],["עֹלוֹת","burnt offerings"],["וּמִנְחֹתֵיכֶם","and your grain offerings"],["לֹא","not"],["אֶרְצֶה","I will accept"],["וְשֶׁלֶם","and the peace offering of"],["מְרִיאֵיכֶם","your fatlings"],["לֹא","not"],["אַבִּיט","I will look"],["׃",""]] },
  { num:"כג", words:[["הָסֵר","take away"],["מֵעָלַי","from me"],["הֲמוֹן","multitude of"],["שִׁרֶיךָ","your songs"],["וְזִמְרַת","and the music of"],["נְבָלֶיךָ","your harps"],["לֹא","not"],["אֶשְׁמָע","I will hear"],["׃",""]] },
  { num:"כד", words:[["וְיִגַּל","and it may roll on"],["כַּמַּיִם","as the waters"],["מִשְׁפָּט","judgment"],["וּצְדָקָה","and righteousness"],["כְּנַחַל","is like a torrent"],["אֵיתָן","firm"],["׃",""]] },
  { num:"כה", words:[["הַזְּבָחִים","the sacrifices"],["וּמִנְחָה","and a grain offering"],["הִגַּשְׁתֶּם־לִי","did you bring near to me"],["בַמִּדְבָּר","in the wilderness"],["אַרְבָּעִים","forty"],["שָׁנָה","years"],["בֵּית","the house of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"כו", words:[["וּנְשָׂאתֶם","and you will carry"],["אֵת־סִכּוּת","Sikkuth"],["מַלְכְּכֶם","your king"],["וְאֵת","and"],["כִּיּוּן","Kiyyun"],["צַלְמֵיכֶם","your images"],["כּוֹכַב","the star of"],["אֱלֹהֵיכֶם","your god"],["אֲשֶׁר","which"],["עֲשִׂיתֶם","you have done"],["לָכֶם","to you"],["׃",""]] },
  { num:"כז", words:[["וְהִגְלֵיתִי","and I will send into exile"],["אֶתְכֶם","you"],["מֵהָלְאָה","from beyond"],["לְדַמָּשֶׂק","of Damascus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["אֱלֹהֵי־צְבָאוֹת","God of Hosts"],["שְׁמוֹ","his name"],["׃",""]] },
];
renderVerseSet(amo_ch5Verses, 'amo-ch5-verses');

var amo_ch6Verses = [
  { num:"א", words:[["הוֹי","O"],["הַשַּׁאֲנַנִּים","the self confident people"],["בְּצִיּוֹן","in Zion"],["וְהַבֹּטְחִים","and the ones who trust"],["בְּהַר","on the mount of"],["שֹׁמְרוֹן","Samaria"],["נְקֻבֵי","which are named"],["רֵאשִׁית","the beginning of"],["הַגּוֹיִם","the nations"],["וּבָאוּ","and it comes"],["לָהֶם","to them"],["בֵּית","the house of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"ב", words:[["עִבְרוּ","pass over"],["כַלְנֵה","Calneh"],["וּרְאוּ","and see"],["וּלְכוּ","and go"],["מִשָּׁם","from there"],["חֲמַת","Hamath"],["רַבָּה","the great"],["וּרְדוּ","and go down"],["גַת־פְּלִשְׁתִּים","Gath of the Philistines"],["הֲטוֹבִים","are they good"],["מִן־הַמַּמְלָכוֹת","from the kingdoms"],["הָאֵלֶּה","these"],["אִם־רַב","if great"],["גְּבוּלָם","their territory"],["מִגְּבֻלְכֶם","than your border"],["׃",""]] },
  { num:"ג", words:[["הַמְנַדִּים","those who push away"],["לְיוֹם","to day"],["רָע","evil"],["וַתַּגִּשׁוּן","and you brought near"],["שֶׁבֶת","remaining"],["חָמָס","violence"],["׃",""]] },
  { num:"ד", words:[["הַשֹּׁכְבִים","the ones who lie"],["עַל־מִטּוֹת","upon couches of"],["שֵׁן","ivory"],["וּסְרֻחִים","and people sprawled out"],["עַל־עַרְשׂוֹתָם","upon their couches"],["וְאֹכְלִים","and those who eat"],["כָּרִים","lambs"],["מִצֹּאן","out of the flock"],["וַעֲגָלִים","and calves"],["מִתּוֹךְ","from the midst of"],["מַרְבֵּק","the stall"],["׃",""]] },
  { num:"ה", words:[["הַפֹּרְטִים","the ones who improvise"],["עַל־פִּי","according to"],["הַנָּבֶל","the lyre"],["כְּדָוִיד","like David"],["חָשְׁבוּ","they supposed"],["לָהֶם","to them"],["כְּלֵי־שִׁיר","instruments of song"],["׃",""]] },
  { num:"ו", words:[["הַשֹּׁתִים","that drink"],["בְּמִזְרְקֵי","in bowls of"],["יַיִן","wine"],["וְרֵאשִׁית","and firstfruit of"],["שְׁמָנִים","fat things"],["יִמְשָׁחוּ","they smear"],["וְלֹא","and not"],["נֶחְלוּ","they are grieved"],["עַל־שֵׁבֶר","upon the ruin of"],["יוֹסֵף","Joseph"],["׃",""]] },
  { num:"ז", words:[["לָכֵן","therefore"],["עַתָּה","now"],["יִגְלוּ","they will go into exile"],["בְּרֹאשׁ","in the top of"],["גֹּלִים","those who go into exile"],["וְסָר","then shall depart"],["מִרְזַח","the revelry of"],["סְרוּחִים","sprawled out people"],["׃",""]] },
  { num:"ח", words:[["נִשְׁבַּע","swore"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["בְּנַפְשׁוֹ","in His soul"],["נְאֻם־יְהֹוָה","says the LORD"],["אֱלֹהֵי","the God of"],["צְבָאוֹת","Hosts"],["מְתָאֵב","am loathing"],["אָנֹכִי","I"],["אֶת־גְּאוֹן","the pride of"],["יַעֲקֹב","Jacob"],["וְאַרְמְנֹתָיו","and his fortresses"],["שָׂנֵאתִי","I hate"],["וְהִסְגַּרְתִּי","and I will deliver up"],["עִיר","the city of"],["וּמְלֹאָהּ","and what fills it"],["׃",""]] },
  { num:"ט", words:[["וְהָיָה","and be"],["אִם־יִוָּתְרוּ","if they will remain"],["עֲשָׂרָה","ten"],["אֲנָשִׁים","men"],["בְּבַיִת","to house"],["אֶחָד","one"],["וָמֵתוּ","and they will die"],["׃",""]] },
  { num:"י", words:[["וּנְשָׂאוֹ","and shall take him up"],["דּוֹדוֹ","his uncle"],["וּמְסָרְפוֹ","and the one who burns him"],["לְהוֹצִיא","to bring out"],["עֲצָמִים","the bones"],["מִן־הַבַּיִת","from the house"],["וְאָמַר","and said"],["לַאֲשֶׁר","unto him who"],["בְּיַרְכְּתֵי","in the sides of"],["הַבַּיִת","the house"],["הַעוֹד","still"],["עִמָּךְ","with you"],["וְאָמַר","and said"],["אָפֶס","nothing"],["וְאָמַר","and said"],["הָס","hush!"],["כִּי","for"],["לֹא","not"],["לְהַזְכִּיר","to bring to remembrance"],["בְּשֵׁם","in the name of"],["יְהֹוָה","the LORD"],["׃",""]] },
  { num:"יא", words:[["כִּי־הִנֵּה","because behold"],["יְהֹוָה","the LORD"],["מְצַוֶּה","command"],["וְהִכָּה","and was smitten"],["הַבַּיִת","the house"],["הַגָּדוֹל","the great"],["רְסִיסִים","fragments"],["וְהַבַּיִת","and the house"],["הַקָּטֹן","the small"],["בְּקִעִים","rubble"],["׃",""]] },
  { num:"יב", words:[["הַיְרֻצוּן","do they run"],["בַּסֶּלַע","in the rock"],["סוּסִים","horses"],["אִם־יַחֲרוֹשׁ","if it will plow"],["בַּבְּקָרִים","with the oxen"],["כִּי־הֲפַכְתֶּם","because you have turned"],["לְרֹאשׁ","into gall"],["מִשְׁפָּט","judgment"],["וּפְרִי","and the fruit of"],["צְדָקָה","a state of righteousness"],["לְלַעֲנָה","into wormwood"],["׃",""]] },
  { num:"יג", words:[["הַשְּׂמֵחִים","ye which rejoice"],["לְלֹא","to not"],["דָבָר","a thing"],["הָאֹמְרִים","the ones saying"],["הֲלוֹא","is it not"],["בְחׇזְקֵנוּ","by our own strength"],["לָקַחְנוּ","we took"],["לָנוּ","to us"],["קַרְנָיִם","horns"],["׃",""]] },
  { num:"יד", words:[["כִּי","for"],["הִנְנִי","behold I"],["מֵקִים","about to establish"],["עֲלֵיכֶם","over you"],["בֵּית","the house of"],["יִשְׂרָאֵל","Israel"],["נְאֻם־יְהֹוָה","says the LORD"],["אֱלֹהֵי","the God of"],["הַצְּבָאוֹת","of hosts"],["גּוֹי","nation"],["וְלָחֲצוּ","and they will oppress"],["אֶתְכֶם","you"],["מִלְּבוֹא","from the entering in of"],["חֲמָת","Hamath"],["עַד־נַחַל","until a river of"],["הָעֲרָבָה","the Arabah"],["׃",""]] },
];
renderVerseSet(amo_ch6Verses, 'amo-ch6-verses');

var amo_ch7Verses = [
  { num:"א", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown me"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["וְהִנֵּה","and behold"],["יוֹצֵר","he formed"],["גֹּבַי","grasshoppers"],["בִּתְחִלַּת","in the commencement of"],["עֲלוֹת","the ascending of"],["הַלָּקֶשׁ","the spring crop"],["וְהִנֵּה־לֶקֶשׁ","and behold a spring crop"],["אַחַר","after"],["גִּזֵּי","the mowings of"],["הַמֶּלֶךְ","the king"],["׃",""]] },
  { num:"ב", words:[["וְהָיָה","and be"],["אִם־כִּלָּה","when they had made an end"],["לֶאֱכוֹל","to eat"],["אֶת־עֵשֶׂב","plants"],["הָאָרֶץ","the land"],["וָאֹמַר","and I said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["סְלַח־נָא","forgive I pray"],["מִי","who"],["יָקוּם","he shall rise"],["יַעֲקֹב","Jacob"],["כִּי","for"],["קָטֹן","little are"],["הוּא","he"],["׃",""]] },
  { num:"ג", words:[["נִחַם","repented"],["יְהֹוָה","the LORD"],["עַל־זֹאת","upon this"],["לֹא","not"],["תִהְיֶה","be"],["אָמַר","said"],["יְהֹוָה","the LORD"],["׃",""]] },
  { num:"ד", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown me"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["וְהִנֵּה","and behold"],["קֹרֵא","called"],["לָרִב","to contend"],["בָּאֵשׁ","by fire"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["וַתֹּאכַל","and it consumed"],["אֶת־תְּהוֹם","gulf"],["רַבָּה","the great"],["וְאָכְלָה","and shall devour"],["אֶת־הַחֵלֶק","a part"],["׃",""]] },
  { num:"ה", words:[["וָאֹמַר","and I said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["חֲדַל־נָא","cease I pray"],["מִי","who"],["יָקוּם","he shall rise"],["יַעֲקֹב","Jacob"],["כִּי","for"],["קָטֹן","little are"],["הוּא","he"],["׃",""]] },
  { num:"ו", words:[["נִחַם","repented"],["יְהֹוָה","the LORD"],["עַל־זֹאת","upon this"],["גַּם־הִיא","also it is"],["לֹא","not"],["תִהְיֶה","be"],["אָמַר","said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["׃",""]] },
  { num:"ז", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown me"],["וְהִנֵּה","and behold"],["אֲדֹנָי","Lord"],["נִצָּב","stands up"],["עַל־חוֹמַת","upon the walls of"],["אֲנָךְ","a plumbline"],["וּבְיָדוֹ","and in his hand"],["אֲנָךְ","a plumbline"],["׃",""]] },
  { num:"ח", words:[["וַיֹּאמֶר","and said"],["יְהֹוָה","the LORD"],["אֵלַי","to me"],["מָה־אַתָּה","what you"],["רֹאֶה","seest thou"],["עָמוֹס","Amos"],["וָאֹמַר","and I said"],["אֲנָךְ","a plumbline"],["וַיֹּאמֶר","and said"],["אֲדֹנָי","Lord"],["הִנְנִי","behold I"],["שָׂם","set"],["אֲנָךְ","a plumbline"],["בְּקֶרֶב","among"],["עַמִּי","my people"],["יִשְׂרָאֵל","Israel"],["לֹא־אוֹסִיף","not more"],["עוֹד","any more"],["עֲבוֹר","to pass on"],["לוֹ","to him"],["׃",""]] },
  { num:"ט", words:[["וְנָשַׁמּוּ","and they will be desolate"],["בָּמוֹת","the high places of"],["יִשְׂחָק","Isaac"],["וּמִקְדְּשֵׁי","and the sanctuaries of"],["יִשְׂרָאֵל","Israel"],["יֶחֱרָבוּ","they will become desolate"],["וְקַמְתִּי","for I will rise up"],["עַל־בֵּית","to the house of"],["יָרׇבְעָם","Jeroboam"],["בֶּחָרֶב","by the sword"],["׃",""]] },
  { num:"י", words:[["וַיִּשְׁלַח","and sent"],["אֲמַצְיָה","Amaziah"],["כֹּהֵן","a priest"],["בֵּית־אֵל","Beth-el"],["אֶל־יָרׇבְעָם","to Jeroboam"],["מֶלֶךְ־יִשְׂרָאֵל","king of Israel"],["לֵאמֹר","saying"],["קָשַׁר","he has conspired"],["עָלֶיךָ","upon you"],["עָמוֹס","Amos"],["בְּקֶרֶב","among"],["בֵּית","the house of"],["יִשְׂרָאֵל","Israel"],["לֹא־תוּכַל","not can"],["הָאָרֶץ","the earth"],["לְהָכִיל","to contain"],["אֶת־כׇּל־דְּבָרָיו","all of his words"],["׃",""]] },
  { num:"יא", words:[["כִּי־כֹה","because thus"],["אָמַר","said"],["עָמוֹס","Amos"],["בַּחֶרֶב","with the sword"],["יָמוּת","he shall die"],["יָרׇבְעָם","Jeroboam"],["וְיִשְׂרָאֵל","and Israel"],["גָּלֹה","surely"],["יִגְלֶה","shall be led away captive"],["מֵעַל","from upon"],["אַדְמָתוֹ","his land"],["׃",""]] },
  { num:"יב", words:[["וַיֹּאמֶר","and said"],["אֲמַצְיָה","Amaziah"],["אֶל־עָמוֹס","to Amos"],["חֹזֶה","a seer"],["לֵךְ","go"],["בְּרַח־לְךָ","flee for you"],["אֶל־אֶרֶץ","to the land of"],["יְהוּדָה","Judah"],["וֶאֱכׇל־שָׁם","and eat there"],["לֶחֶם","bread"],["וְשָׁם","and there"],["תִּנָּבֵא","you shall prophesy"],["׃",""]] },
  { num:"יג", words:[["וּבֵית־אֵל","and Beth-el"],["לֹא־תוֹסִיף","not again"],["עוֹד","any more"],["לְהִנָּבֵא","to prophesy"],["כִּי","for"],["מִקְדַּשׁ־מֶלֶךְ","the sanctuary of king of"],["הוּא","he"],["וּבֵית","and house of"],["מַמְלָכָה","kingdom"],["הוּא","he"],["׃",""]] },
  { num:"יד", words:[["וַיַּעַן","and he answered"],["עָמוֹס","Amos"],["וַיֹּאמֶר","and said"],["אֶל־אֲמַצְיָה","to Amaziah"],["לֹא־נָבִיא","not a prophet"],["אָנֹכִי","I"],["וְלֹא","and not"],["בֶן־נָבִיא","son of a prophet"],["אָנֹכִי","I"],["כִּי־בוֹקֵר","because was a herdsman"],["אָנֹכִי","I"],["וּבוֹלֵס","and a gatherer of"],["שִׁקְמִים","the sycamores"],["׃",""]] },
  { num:"טו", words:[["וַיִּקָּחֵנִי","and took me"],["יְהֹוָה","the LORD"],["מֵאַחֲרֵי","from after"],["הַצֹּאן","the flock"],["וַיֹּאמֶר","and said"],["אֵלַי","to me"],["יְהֹוָה","the LORD"],["לֵךְ","go"],["הִנָּבֵא","and prophesy"],["אֶל־עַמִּי","unto my people"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"טז", words:[["וְעַתָּה","and now"],["שְׁמַע","hearken"],["דְּבַר־יְהֹוָה","the word of the LORD"],["אַתָּה","you"],["אֹמֵר","say"],["לֹא","not"],["תִנָּבֵא","you shall prophesy"],["עַל־יִשְׂרָאֵל","upon Israel"],["וְלֹא","and not"],["תַטִּיף","drop your word"],["עַל־בֵּית","to the house of"],["יִשְׂחָק","Isaac"],["׃",""]] },
  { num:"יז", words:[["לָכֵן","therefore"],["כֹּה־אָמַר","thus says"],["יְהֹוָה","the LORD"],["אִשְׁתְּךָ","your wife"],["בָּעִיר","in the city"],["תִּזְנֶה","she will be a prostitute"],["וּבָנֶיךָ","and your sons"],["וּבְנֹתֶיךָ","and your daughters"],["בַּחֶרֶב","with the sword"],["יִפֹּלוּ","they must fall"],["וְאַדְמָתְךָ","and your land"],["בַּחֶבֶל","with rope"],["תְּחֻלָּק","it will be divided"],["וְאַתָּה","and you"],["עַל־אֲדָמָה","upon ground"],["טְמֵאָה","unclean"],["תָּמוּת","you shall die"],["וְיִשְׂרָאֵל","though Israel"],["גָּלֹה","surely"],["יִגְלֶה","shall be led away captive"],["מֵעַל","from upon"],["אַדְמָתוֹ","his land"],["׃",""]] },
];
renderVerseSet(amo_ch7Verses, 'amo-ch7-verses');

var amo_ch8Verses = [
  { num:"א", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown me"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["וְהִנֵּה","and behold"],["כְּלוּב","a basket of"],["קָיִץ","summer"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמֶר","and said"],["מָה־אַתָּה","what you"],["רֹאֶה","seest thou"],["עָמוֹס","Amos"],["וָאֹמַר","and I said"],["כְּלוּב","a basket of"],["קָיִץ","summer"],["וַיֹּאמֶר","and said"],["יְהֹוָה","the LORD"],["אֵלַי","to me"],["בָּא","came"],["הַקֵּץ","the end"],["אֶל־עַמִּי","unto my people"],["יִשְׂרָאֵל","Israel"],["לֹא־אוֹסִיף","not more"],["עוֹד","any more"],["עֲבוֹר","to pass on"],["לוֹ","to him"],["׃",""]] },
  { num:"ג", words:[["וְהֵילִילוּ","and wail"],["שִׁירוֹת","songs of"],["הֵיכׇל","the temple"],["בַּיּוֹם","in the day"],["הַהוּא","that"],["נְאֻם","says"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["רַב","great"],["הַפֶּגֶר","the corpses"],["בְּכׇל־מָקוֹם","in all place"],["הִשְׁלִיךְ","they shall cast them forth"],["הָס","hush!"],["׃",""]] },
  { num:"ד", words:[["שִׁמְעוּ־זֹאת","hear this"],["הַשֹּׁאֲפִים","the ones who trample"],["אֶבְיוֹן","a needy person"],["וְלַשְׁבִּית","and to put an end to"],["(ענוי)",""],["[עֲנִיֵּי־]אָרֶץ","the poor of the land"],["׃",""]] },
  { num:"ה", words:[["לֵאמֹר","saying"],["מָתַי","when"],["יַעֲבֹר","pass away"],["הַחֹדֶשׁ","the month"],["וְנַשְׁבִּירָה","so we may sell grain"],["שֶּׁבֶר","grain"],["וְהַשַּׁבָּת","and the sabbath"],["וְנִפְתְּחָה־בָּר","that we may set forth wheat"],["לְהַקְטִין","to make small"],["אֵיפָה","an ephah"],["וּלְהַגְדִּיל","and to make great"],["שֶׁקֶל","shekels of"],["וּלְעַוֵּת","and to falsify"],["מֹאזְנֵי","balances of"],["מִרְמָה","deceit"],["׃",""]] },
  { num:"ו", words:[["לִקְנוֹת","that we may buy"],["בַּכֶּסֶף","in the silver"],["דַּלִּים","the poor"],["וְאֶבְיוֹן","and needy"],["בַּעֲבוּר","because of"],["נַעֲלָיִם","a pair of sandals"],["וּמַפַּל","and refuse of"],["בַּר","grain"],["נַשְׁבִּיר","we will sell grain"],["׃",""]] },
  { num:"ז", words:[["נִשְׁבַּע","swore"],["יְהֹוָה","the LORD"],["בִּגְאוֹן","in the pride of"],["יַעֲקֹב","Jacob"],["אִם־אֶשְׁכַּח","if I will forget"],["לָנֶצַח","forever"],["כׇּל־מַעֲשֵׂיהֶם","all of their proceedings"],["׃",""]] },
  { num:"ח", words:[["הַעַל","shall not for this"],["זֹאת","this"],["לֹא־תִרְגַּז","not will it tremble"],["הָאָרֶץ","the earth"],["וְאָבַל","and he will mourn"],["כׇּל־יוֹשֵׁב","all sitting"],["בָּהּ","in it"],["וְעָלְתָה","and she will go up"],["כָאֹר","as a flood"],["כֻּלָּהּ","all of it"],["וְנִגְרְשָׁה","and it will be tossed"],["(ונשקה)",""],["[וְנִשְׁקְעָה]","and it will sink"],["כִּיאוֹר","like the River"],["מִצְרָיִם","Egypt"],["׃",""]] },
  { num:"ט", words:[["וְהָיָה","and be"],["בַּיּוֹם","in the day"],["הַהוּא","that"],["נְאֻם","says"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["וְהֵבֵאתִי","and have brought"],["הַשֶּׁמֶשׁ","the sun"],["בַּצׇּהֳרָיִם","at the noon"],["וְהַחֲשַׁכְתִּי","and I will darken"],["לָאָרֶץ","to the ground"],["בְּיוֹם","in the day of"],["אוֹר","light"],["׃",""]] },
  { num:"י", words:[["וְהָפַכְתִּי","and I shall overturn"],["חַגֵּיכֶם","your feasts"],["לְאֵבֶל","mourning"],["וְכׇל־שִׁירֵיכֶם","and all your songs"],["לְקִינָה","for lamentation"],["וְהַעֲלֵיתִי","and I will bring up"],["עַל־כׇּל־מׇתְנַיִם","upon all the hips"],["שָׂק","sackcloth"],["וְעַל־כׇּל־רֹאשׁ","and upon all head of"],["קׇרְחָה","baldness"],["וְשַׂמְתִּיהָ","I will also make it"],["כְּאֵבֶל","like the mourning of"],["יָחִיד","an only son"],["וְאַחֲרִיתָהּ","and her end"],["כְּיוֹם","as the day of"],["מָר","bitter"],["׃",""]] },
  { num:"יא", words:[["הִנֵּה","behold"],["יָמִים","days"],["בָּאִים","come"],["נְאֻם","says"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["וְהִשְׁלַחְתִּי","and I will send"],["רָעָב","a famine"],["בָּאָרֶץ","in the land"],["לֹא־רָעָב","not a famine"],["לַלֶּחֶם","to the bread"],["וְלֹא־צָמָא","and not thirst"],["לַמַּיִם","the waters"],["כִּי","because"],["אִם־לִשְׁמֹעַ","rather to hearken"],["אֵת־דִּבְרֵי","the words of"],["יְהֹוָה","the LORD"],["׃",""]] },
  { num:"יב", words:[["וְנָעוּ","and they shall wander"],["מִיָּם","from the sea"],["עַד־יָם","until the sea"],["וּמִצָּפוֹן","and from north"],["וְעַד־מִזְרָח","and unto east"],["יְשׁוֹטְטוּ","they will rove about"],["לְבַקֵּשׁ","to seek"],["אֶת־דְּבַר־יְהֹוָה","the word of the LORD"],["וְלֹא","and not"],["יִמְצָאוּ","they find"],["׃",""]] },
  { num:"יג", words:[["בַּיּוֹם","in the day"],["הַהוּא","that"],["תִּתְעַלַּפְנָה","they will become faint"],["הַבְּתוּלֹת","the virgins"],["הַיָּפוֹת","the fair"],["וְהַבַּחוּרִים","and the young men"],["בַּצָּמָא","by the thirst"],["׃",""]] },
  { num:"יד", words:[["הַנִּשְׁבָּעִים","those who swear"],["בְּאַשְׁמַת","by the guilt of"],["שֹׁמְרוֹן","Samaria"],["וְאָמְרוּ","shall say"],["חֵי","by the life of"],["אֱלֹהֶיךָ","your god"],["דָּן","Dan"],["וְחֵי","and liveth"],["דֶּרֶךְ","the way of"],["בְּאֵר־שָׁבַע","Beer-sheba"],["וְנָפְלוּ","and they shall fall"],["וְלֹא־יָקוּמוּ","and not they shall stand"],["עוֹד","any more"],["׃",""]] },
];
renderVerseSet(amo_ch8Verses, 'amo-ch8-verses');

var amo_ch9Verses = [
  { num:"א", words:[["רָאִיתִי","I saw"],["אֶת־אֲדֹנָי","the Lord"],["נִצָּב","stands up"],["עַל־הַמִּזְבֵּחַ","upon the altar"],["וַיֹּאמֶר","and said"],["הַךְ","strike"],["הַכַּפְתּוֹר","the lintel"],["וְיִרְעֲשׁוּ","so they may shake"],["הַסִּפִּים","the posts"],["וּבְצַעַם","and break off them"],["בְּרֹאשׁ","in the top of"],["כֻּלָּם","all of them"],["וְאַחֲרִיתָם","and their posterity"],["בַּחֶרֶב","with the sword"],["אֶהֱרֹג","I will slay"],["לֹא־יָנוּס","not flee"],["לָהֶם","to them"],["נָס","fled"],["וְלֹא־יִמָּלֵט","and not shall be delivered"],["לָהֶם","to them"],["פָּלִיט","an escapee"],["׃",""]] },
  { num:"ב", words:[["אִם־יַחְתְּרוּ","if they shall dig"],["בִשְׁאוֹל","in Sheol"],["מִשָּׁם","from there"],["יָדִי","my hand"],["תִקָּחֵם","it will take them"],["וְאִם־יַעֲלוּ","and if they go up"],["הַשָּׁמַיִם","the heavens"],["מִשָּׁם","from there"],["אוֹרִידֵם","I will bring down them"],["׃",""]] },
  { num:"ג", words:[["וְאִם־יֵחָבְאוּ","and if they will hide themselves"],["בְּרֹאשׁ","in the top of"],["הַכַּרְמֶל","Carmel"],["מִשָּׁם","from there"],["אֲחַפֵּשׂ","I will search for them"],["וּלְקַחְתִּים","and I will take them"],["וְאִם־יִסָּתְרוּ","and if shall be hidden"],["מִנֶּגֶד","from before"],["עֵינַי","my eyes"],["בְּקַרְקַע","on the floor of"],["הַיָּם","the sea"],["מִשָּׁם","from there"],["אֲצַוֶּה","I will command"],["אֶת־הַנָּחָשׁ","the serpent"],["וּנְשָׁכָם","and it will bite them"],["׃",""]] },
  { num:"ד", words:[["וְאִם־יֵלְכוּ","and if they should travel"],["בַשְּׁבִי","in the captivity"],["לִפְנֵי","before"],["אֹיְבֵיהֶם","their enemies"],["מִשָּׁם","from there"],["אֲצַוֶּה","I will command"],["אֶת־הַחֶרֶב","the sword"],["וַהֲרָגָתַם","and it will kill them"],["וְשַׂמְתִּי","and I make"],["עֵינִי","my eye"],["עֲלֵיהֶם","upon them"],["לְרָעָה","for evil"],["וְלֹא","and not"],["לְטוֹבָה","for good"],["׃",""]] },
  { num:"ה", words:[["וַאדֹנָי","and my Lord"],["יֱהֹוִה","GOD"],["הַצְּבָאוֹת","of hosts"],["הַנּוֹגֵעַ","the one who touches"],["בָּאָרֶץ","in the land"],["וַתָּמוֹג","and it melted"],["וְאָבְלוּ","and mourn"],["כׇּל־יוֹשְׁבֵי","all the inhabitants of"],["בָהּ","in it"],["וְעָלְתָה","and she will go up"],["כַיְאֹר","like a flood"],["כֻּלָּהּ","all of it"],["וְשָׁקְעָה","and it sinks"],["כִּיאֹר","like the River"],["מִצְרָיִם","Egypt"],["׃",""]] },
  { num:"ו", words:[["הַבּוֹנֶה","the one who builds"],["בַשָּׁמַיִם","in the heavens"],["מַעֲלוֹתָו","his stories"],["וַאֲגֻדָּתוֹ","and his vault"],["עַל־אֶרֶץ","concerning the land of"],["יְסָדָהּ","he founded it"],["הַקֹּרֵא","he that calleth"],["לְמֵי־הַיָּם","to the waters of the sea"],["וַיִּשְׁפְּכֵם","and he poured out them"],["עַל־פְּנֵי","upon the face of"],["הָאָרֶץ","the earth"],["יְהֹוָה","the LORD"],["שְׁמוֹ","his name"],["׃",""]] },
  { num:"ז", words:[["הֲלוֹא","is it not"],["כִבְנֵי","like the sons of"],["כֻשִׁיִּים","the Cushites"],["אַתֶּם","you are"],["לִי","to me"],["בְּנֵי","the sons of"],["יִשְׂרָאֵל","Israel"],["נְאֻם־יְהֹוָה","says the LORD"],["הֲלוֹא","is it not"],["אֶת־יִשְׂרָאֵל","Israel"],["הֶעֱלֵיתִי","I brought up"],["מֵאֶרֶץ","from the land of"],["מִצְרַיִם","Egypt"],["וּפְלִשְׁתִּיִּים","and the Philistines"],["מִכַּפְתּוֹר","from Caphtor"],["וַאֲרָם","and Syria"],["מִקִּיר","from Kir"],["׃",""]] },
  { num:"ח", words:[["הִנֵּה","behold"],["עֵינֵי","the eyes of"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["בַּמַּמְלָכָה","in the kingdom"],["הַחַטָּאָה","the sinful"],["וְהִשְׁמַדְתִּי","and I will destroy"],["אֹתָהּ","it"],["מֵעַל","from upon"],["פְּנֵי","face of"],["הָאֲדָמָה","the earth"],["אֶפֶס","saving that"],["כִּי","that"],["לֹא","not"],["הַשְׁמֵיד","surely"],["אַשְׁמִיד","I destroy"],["אֶת־בֵּית","house of"],["יַעֲקֹב","Jacob"],["נְאֻם־יְהֹוָה","says the LORD"],["׃",""]] },
  { num:"ט", words:[["כִּי־הִנֵּה","because behold"],["אָנֹכִי","I"],["מְצַוֶּה","command"],["וַהֲנִעוֹתִי","and I will shake"],["בְכׇל־הַגּוֹיִם","in all the nations"],["אֶת־בֵּית","house of"],["יִשְׂרָאֵל","Israel"],["כַּאֲשֶׁר","as"],["יִנּוֹעַ","it is shaken"],["בַּכְּבָרָה","in the sieve"],["וְלֹא־יִפּוֹל","and not shall fall"],["צְרוֹר","the least grain"],["אָרֶץ","the earth"],["׃",""]] },
  { num:"י", words:[["בַּחֶרֶב","with the sword"],["יָמוּתוּ","shall die"],["כֹּל","all"],["חַטָּאֵי","the sinners of"],["עַמִּי","my people"],["הָאֹמְרִים","the ones saying"],["לֹא־תַגִּישׁ","not it will bring near"],["וְתַקְדִּים","nor prevent"],["בַּעֲדֵינוּ","through us"],["הָרָעָה","the evil"],["׃",""]] },
  { num:"יא", words:[["בַּיּוֹם","in the day"],["הַהוּא","that"],["אָקִים","shall I raise up"],["אֶת־סֻכַּת","the booth of"],["דָּוִיד","David"],["הַנֹּפֶלֶת","the falling"],["וְגָדַרְתִּי","and close up"],["אֶת־פִּרְצֵיהֶן","their breaches"],["וַהֲרִסֹתָיו","and his ruins"],["אָקִים","shall I raise up"],["וּבְנִיתִיהָ","and I will rebuild it"],["כִּימֵי","as days of"],["עוֹלָם","eternal"],["׃",""]] },
  { num:"יב", words:[["לְמַעַן","in order that"],["יִירְשׁוּ","they possess"],["אֶת־שְׁאֵרִית","remnant of"],["אֱדוֹם","Edom"],["וְכׇל־הַגּוֹיִם","and all the nations"],["אֲשֶׁר־נִקְרָא","which called was"],["שְׁמִי","my name"],["עֲלֵיהֶם","upon them"],["נְאֻם־יְהֹוָה","says the LORD"],["עֹשֶׂה","do"],["זֹּאת","this"],["׃",""]] },
  { num:"יג", words:[["הִנֵּה","behold"],["יָמִים","days"],["בָּאִים","come"],["נְאֻם־יְהֹוָה","says the LORD"],["וְנִגַּשׁ","and he will draw near"],["חוֹרֵשׁ","the plowman"],["בַּקֹּצֵר","the reaper"],["וְדֹרֵךְ","and one who treads"],["עֲנָבִים","grapes"],["בְּמֹשֵׁךְ","him that soweth"],["הַזָּרַע","the offspring"],["וְהִטִּיפוּ","and they will drip"],["הֶהָרִים","the mountains"],["עָסִיס","sweet wine"],["וְכׇל־הַגְּבָעוֹת","and all the hills"],["תִּתְמוֹגַגְנָה","shall melt"],["׃",""]] },
  { num:"יד", words:[["וְשַׁבְתִּי","and I will return"],["אֶת־שְׁבוּת","the captivity of"],["עַמִּי","my people"],["יִשְׂרָאֵל","Israel"],["וּבָנוּ","and they shall build"],["עָרִים","cities"],["נְשַׁמּוֹת","the waste"],["וְיָשָׁבוּ","and they will dwell in them"],["וְנָטְעוּ","and they will plant"],["כְרָמִים","vineyards"],["וְשָׁתוּ","and they have drunk"],["אֶת־יֵינָם","their wine"],["וְעָשׂוּ","and they did work"],["גַנּוֹת","gardens"],["וְאָכְלוּ","and eat"],["אֶת־פְּרִיהֶם","their fruit"],["׃",""]] },
  { num:"טו", words:[["וּנְטַעְתִּים","and I will plant them"],["עַל־אַדְמָתָם","in their own land"],["וְלֹא","and not"],["יִנָּתְשׁוּ","are they plucked up"],["עוֹד","any more"],["מֵעַל","from upon"],["אַדְמָתָם","their land"],["אֲשֶׁר","which"],["נָתַתִּי","I gave"],["לָהֶם","to them"],["אָמַר","said"],["יְהֹוָה","the LORD"],["אֱלֹהֶיךָ","your God"],["׃",""]] },
];
renderVerseSet(amo_ch9Verses, 'amo-ch9-verses');

})();
