// ot_verses/est.js — Esther verse data
(function() {
var est_ch1Verses = [
  { num:"א", words:[["וַיְהִי","and-it-came-to-pass"],["בִּימֵי","in-days-of"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["הוּא","it-is"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["הַמֹּלֵךְ","the-who-reigned"],["מֵהֹדּוּ","from-India"],["וְעַד־כּוּשׁ","and-unto-Cush"],["שֶׁבַע","seven"],["וְעֶשְׂרִים","and-twenty"],["וּמֵאָה","and-one hundred"],["מְדִינָה","provinces"],["׃",""]] },
  { num:"ב", words:[["בַּיָּמִים","in-the-days"],["הָהֵם","those"],["כְּשֶׁבֶת","when-sat"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["עַל","upon"],["כִּסֵּא","throne"],["מַלְכוּתוֹ","His-kingdom"],["אֲשֶׁר","which"],["בְּשׁוּשַׁן","in-Susa"],["הַבִּירָה","the-temple"],["׃",""]] },
  { num:"ג", words:[["בִּשְׁנַת","in-year-of"],["שָׁלוֹשׁ","three"],["לְמׇלְכוֹ","of-reigning-his"],["עָשָׂה","he-did"],["מִשְׁתֶּה","feast"],["לְכׇל־שָׂרָיו","to-all-commanders-his"],["וַעֲבָדָיו","and-servants-his"],["חֵיל","the army of"],["פָּרַס","Persia"],["וּמָדַי","and-Madai"],["הַפַּרְתְּמִים","the-nobles"],["וְשָׂרֵי","and-captains-of"],["הַמְּדִינוֹת","the-provinces"],["לְפָנָיו","before-him"],["׃",""]] },
  { num:"ד", words:[["בְּהַרְאֹתוֹ","when-showed-he"],["אֶת־עֹשֶׁר","[ACC]-riches"],["כְּבוֹד","the-glory-of"],["מַלְכוּתוֹ","His-kingdom"],["וְאֶת־יְקָר","and-[ACC]-the honor of"],["תִּפְאֶרֶת","the-beauty-of"],["גְּדוּלָּתוֹ","greatness-his"],["יָמִים","days"],["רַבִּים","many"],["שְׁמוֹנִים","eighty"],["וּמְאַת","and-one hundred"],["יוֹם","day"],["׃",""]] },
  { num:"ה", words:[["וּבִמְלוֹאת","and-when-were completed"],["הַיָּמִים","the-days"],["הָאֵלֶּה","these"],["עָשָׂה","he-did"],["הַמֶּלֶךְ","the-king"],["לְכׇל־הָעָם","to-all-the-people"],["הַנִּמְצְאִים","the-who-were found"],["בְּשׁוּשַׁן","in-Susa"],["הַבִּירָה","the-temple"],["לְמִגָּדוֹל","from-great"],["וְעַד־קָטָן","down-to-the-least"],["מִשְׁתֶּה","feast"],["שִׁבְעַת","seven-of"],["יָמִים","days"],["בַּחֲצַר","in-the courtyard of"],["גִּנַּת","the garden of"],["בִּיתַן","the palace of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ו", words:[["חוּר","Hur"],["כַּרְפַּס","cotton"],["וּתְכֵלֶת","and-violet stuff"],["אָחוּז","knit"],["בְּחַבְלֵי־בוּץ","with-the-bands-of-fine linen"],["וְאַרְגָּמָן","and-scarlets"],["עַל־גְּלִילֵי","upon-rods of"],["כֶסֶף","silver/money"],["וְעַמּוּדֵי","and-the pillars of"],["שֵׁשׁ","six"],["מִטּוֹת","couches of"],["זָהָב","gold"],["וָכֶסֶף","and-with-silver"],["עַל","upon"],["רִצְפַת","a pavement of"],["בַּהַט־וָשֵׁשׁ","porphyry-and-six"],["וְדַר","and-mother-of-pearl"],["וְסֹחָרֶת","and-paving stone"],["׃",""]] },
  { num:"ז", words:[["וְהַשְׁקוֹת","and-they gave to drink"],["בִּכְלֵי","with-their-arms"],["זָהָב","gold"],["וְכֵלִים","and-utensils"],["מִכֵּלִים","from-vessels"],["שׁוֹנִים","divers"],["וְיֵין","and-wine of"],["מַלְכוּת","the-reign-of"],["רָב","much"],["כְּיַד","according to-the hand of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ח", words:[["וְהַשְּׁתִיָּה","and-the-drinking"],["כַדָּת","was according to the-law"],["אֵין","there-is-no"],["אֹנֵס","was one who compelled"],["כִּי־כֵן","because-thus"],["יִסַּד","he-shall-be-founded"],["הַמֶּלֶךְ","the-king"],["עַל","upon"],["כׇּל־רַב","all-great"],["בֵּיתוֹ","his-house"],["לַעֲשׂוֹת","to-do"],["כִּרְצוֹן","according-to-the-desires-of"],["אִישׁ־וָאִישׁ","man-of-and-man"],["׃",""]] },
  { num:"ט", words:[["גַּם","also"],["וַשְׁתִּי","Vashti"],["הַמַּלְכָּה","the-queen"],["עָשְׂתָה","did(f)"],["מִשְׁתֵּה","a feast of"],["נָשִׁים","women"],["בֵּית","the-house-of"],["הַמַּלְכוּת","the-kingdom"],["אֲשֶׁר","which"],["לַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["׃",""]] },
  { num:"י", words:[["בַּיּוֹם","in-the-day"],["הַשְּׁבִיעִי","the-seventh"],["כְּטוֹב","like-good"],["לֵב־הַמֶּלֶךְ","heart-the-king"],["בַּיָּיִן","by the-wine"],["אָמַר","said"],["לִמְהוּמָן","to-Mehuman"],["בִּזְּתָא","Biztha"],["חַרְבוֹנָא","Harbona"],["בִּגְתָא","Bigtha"],["וַאֲבַגְתָא","and-Abagtha"],["זֵתַר","Zethar"],["וְכַרְכַּס","and-Carcas"],["שִׁבְעַת","seven-of"],["הַסָּרִיסִים","the-court-officials"],["הַמְשָׁרְתִים","[compound]"],["אֶת־פְּנֵי","ACC-face-of"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["׃",""]] },
  { num:"יא", words:[["לְהָבִיא","to-bring-about"],["אֶת־וַשְׁתִּי","[ACC]-Vashti"],["הַמַּלְכָּה","the-queen"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["בְּכֶתֶר","with-a crown of"],["מַלְכוּת","the-reign-of"],["לְהַרְאוֹת","to-exercise"],["הָעַמִּים","the-people"],["וְהַשָּׂרִים","and-the-princes"],["אֶת־יׇפְיָהּ","[ACC]-beauty-her"],["כִּי־טוֹבַת","because-the-welfare-of"],["מַרְאֶה","appearance"],["הִיא","it-is"],["׃",""]] },
  { num:"יב", words:[["וַתְּמָאֵן","and-she-refused"],["הַמַּלְכָּה","the-queen"],["וַשְׁתִּי","Vashti"],["לָבוֹא","to-come"],["בִּדְבַר","of-the-promise-of"],["הַמֶּלֶךְ","the-king"],["אֲשֶׁר","which"],["בְּיַד","in-hand-of"],["הַסָּרִיסִים","the-court-officials"],["וַיִּקְצֹף","but-the-king-was-more-wroth"],["הַמֶּלֶךְ","the-king"],["מְאֹד","exceedingly"],["וַחֲמָתוֹ","and-rage-his"],["בָּעֲרָה","it burned"],["בוֹ","in-Him"],["׃",""]] },
  { num:"יג", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["לַחֲכָמִים","the-wise men"],["יֹדְעֵי","knowing"],["הָעִתִּים","the-times"],["כִּי־כֵן","because-thus"],["דְּבַר","the-word-of"],["הַמֶּלֶךְ","the-king"],["לִפְנֵי","before"],["כׇּל־יֹדְעֵי","all-knowing"],["דָּת","law"],["וָדִין","and-judgment"],["׃",""]] },
  { num:"יד", words:[["וְהַקָּרֹב","and-the-ones close"],["אֵלָיו","to-him"],["כַּרְשְׁנָא","were Carshena"],["שֵׁתָר","Shethar"],["אַדְמָתָא","Admatha"],["תַרְשִׁישׁ","Tarshish"],["מֶרֶס","Meres"],["מַרְסְנָא","Marsena"],["מְמוּכָן","Memucan"],["שִׁבְעַת","seven-of"],["שָׂרֵי","captains-of"],["פָּרַס","Persia"],["וּמָדַי","and-Madai"],["רֹאֵי","who saw"],["פְּנֵי","face-of"],["הַמֶּלֶךְ","the-king"],["הַיֹּשְׁבִים","the-inhabitants"],["רִאשֹׁנָה","first"],["בַּמַּלְכוּת","into-the-kingdom"],["׃",""]] },
  { num:"טו", words:[["כְּדָת","according to-the law"],["מַה־לַּעֲשׂוֹת","what-more-could-be-done"],["בַּמַּלְכָּה","with the-queen"],["וַשְׁתִּי","Vashti"],["עַל","upon"],["אֲשֶׁר","which"],["לֹא־עָשְׂתָה","not-did(f)"],["אֶת־מַאֲמַר","[ACC]-the command of"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["בְּיַד","in-hand-of"],["הַסָּרִיסִים","the-court-officials"],["׃",""]] },
  { num:"טז", words:[["וַיֹּאמֶר","and-said"],["[מְמוּכָן]","Memucan"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["וְהַשָּׂרִים","and-the-princes"],["לֹא","not"],["עַל־הַמֶּלֶךְ","upon-the-king"],["לְבַדּוֹ","alone"],["עָוְתָה","she did wrong"],["וַשְׁתִּי","Vashti"],["הַמַּלְכָּה","the-queen"],["כִּי","because"],["עַל־כׇּל־הַשָּׂרִים","upon-all-the-princes"],["וְעַל־כׇּל־הָעַמִּים","and-upon-all-the-people"],["אֲשֶׁר","which"],["בְּכׇל־מְדִינוֹת","in-all-the provinces of"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["׃",""]] },
  { num:"יז", words:[["כִּי־יֵצֵא","because-he-go-forth"],["דְבַר־הַמַּלְכָּה","spoke-the-queen"],["עַל־כׇּל־הַנָּשִׁים","upon-all-that-the-women"],["לְהַבְזוֹת","to-make despicable"],["בַּעְלֵיהֶן","their-husbands"],["בְּעֵינֵיהֶן","in-view-their"],["בְּאׇמְרָם","when-said-their"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["אָמַר","said"],["לְהָבִיא","to-bring-about"],["אֶת־וַשְׁתִּי","[ACC]-Vashti"],["הַמַּלְכָּה","the-queen"],["לְפָנָיו","before-him"],["וְלֹא־בָאָה","and-not-entered-into"],["׃",""]] },
  { num:"יח", words:[["וְהַיּוֹם","and-the-day"],["הַזֶּה","this"],["תֹּאמַרְנָה","shall-say(f)"],["שָׂרוֹת","noble ladies"],["פָּרַס־וּמָדַי","Persia-and-Madai"],["אֲשֶׁר","which"],["שָׁמְעוּ","they-heard"],["אֶת־דְּבַר","ACC-word-of"],["הַמַּלְכָּה","the-queen"],["לְכֹל","for-all"],["שָׂרֵי","captains-of"],["הַמֶּלֶךְ","the-king"],["וּכְדַי","and-will be as-enough of"],["בִּזָּיוֹן","contempt"],["וָקָצֶף","and-anger"],["׃",""]] },
  { num:"יט", words:[["אִם־עַל־הַמֶּלֶךְ","[compound]-upon-the-king"],["טוֹב","good"],["יֵצֵא","he-go-forth"],["דְבַר־מַלְכוּת","spoke-the-reign-of"],["מִלְּפָנָיו","from-before-him"],["וְיִכָּתֵב","and-let it be written"],["בְּדָתֵי","in-the laws of"],["פָרַס־וּמָדַי","Persia-and-Madai"],["וְלֹא","and-not"],["יַעֲבוֹר","it will pass away"],["אֲשֶׁר","which"],["לֹא־תָבוֹא","there-shall-not-come"],["וַשְׁתִּי","Vashti"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["וּמַלְכוּתָהּ","and-queenhood-her"],["יִתֵּן","shall-give"],["הַמֶּלֶךְ","the-king"],["לִרְעוּתָהּ","to-fellow woman-her"],["הַטּוֹבָה","the-good"],["מִמֶּנָּה","from-he-appointed"],["׃",""]] },
  { num:"כ", words:[["וְנִשְׁמַע","and-it will be heard"],["פִּתְגָם","decree"],["הַמֶּלֶךְ","the-king"],["אֲשֶׁר־יַעֲשֶׂה","whose-he-shall-do"],["בְּכׇל־מַלְכוּתוֹ","in-all-His-kingdom"],["כִּי","because"],["רַבָּה","much"],["הִיא","it-is"],["וְכׇל־הַנָּשִׁים","and-all-that-the-women"],["יִתְּנוּ","they-should-impart"],["יְקָר","the honor of"],["לְבַעְלֵיהֶן","to-husbands-their"],["לְמִגָּדוֹל","from-great"],["וְעַד־קָטָן","down-to-the-least"],["׃",""]] },
  { num:"כא", words:[["וַיִּיטַב","and-it was good"],["הַדָּבָר","the-thing"],["בְּעֵינֵי","in-the-eyes-of"],["הַמֶּלֶךְ","the-king"],["וְהַשָּׂרִים","and-the-princes"],["וַיַּעַשׂ","and-did"],["הַמֶּלֶךְ","the-king"],["כִּדְבַר","according-to-the-word-of"],["מְמוּכָן","Memucan"],["׃",""]] },
  { num:"כב", words:[["וַיִּשְׁלַח","and-sent"],["סְפָרִים","records"],["אֶל־כׇּל־מְדִינוֹת","to-all-the provinces of"],["הַמֶּלֶךְ","the-king"],["אֶל־מְדִינָה","to-provinces"],["וּמְדִינָה","and-province"],["כִּכְתָבָהּ","according to-writing-its"],["וְאֶל־עַם","and-people"],["וָעָם","and-people"],["כִּלְשׁוֹנוֹ","according to-language-its"],["לִהְיוֹת","to-be"],["כׇּל־אִישׁ","all-man/each"],["שֹׂרֵר","ruler"],["בְּבֵיתוֹ","in-his-house"],["וּמְדַבֵּר","and-speaking"],["כִּלְשׁוֹן","according to-the language of"],["עַמּוֹ","his-people"],["׃",""]] },
];
renderVerseSet(est_ch1Verses, 'est-ch1-verses');

var est_ch2Verses = [
  { num:"א", words:[["אַחַר","after"],["הַדְּבָרִים","the-things"],["הָאֵלֶּה","these"],["כְּשֹׁךְ","when-subsided"],["חֲמַת","the-wrath-of"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["זָכַר","remembered"],["אֶת־וַשְׁתִּי","[ACC]-Vashti"],["וְאֵת","and-[ACC]"],["אֲשֶׁר־עָשָׂתָה","whose-she had prepared"],["וְאֵת","and-[ACC]"],["אֲשֶׁר־נִגְזַר","whose-He-was-cut-off"],["עָלֶיהָ","upon-it"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמְרוּ","and-they-said"],["נַעֲרֵי־הַמֶּלֶךְ","the young men of-the-king"],["מְשָׁרְתָיו","servants-his"],["יְבַקְשׁוּ","seek"],["לַמֶּלֶךְ","the-king"],["נְעָרוֹת","young women"],["בְּתוּלוֹת","virgins"],["טוֹבוֹת","good"],["מַרְאֶה","appearance"],["׃",""]] },
  { num:"ג", words:[["וְיַפְקֵד","and-let him appoint"],["הַמֶּלֶךְ","the-king"],["פְּקִידִים","were overseers"],["בְּכׇל־מְדִינוֹת","in-all-the provinces of"],["מַלְכוּתוֹ","His-kingdom"],["וְיִקְבְּצוּ","and-let them gather"],["אֶת־כׇּל־נַעֲרָה־בְתוּלָה","[ACC]-all-a young woman-a virgin"],["טוֹבַת","the-welfare-of"],["מַרְאֶה","appearance"],["אֶל־שׁוּשַׁן","to-lilies"],["הַבִּירָה","the-temple"],["אֶל־בֵּית","to-the-house-of"],["הַנָּשִׁים","that-the-women"],["אֶל־יַד","to-hand-of"],["הֵגֶא","Hegai"],["סְרִיס","an official of"],["הַמֶּלֶךְ","the-king"],["שֹׁמֵר","who keeps"],["הַנָּשִׁים","that-the-women"],["וְנָתוֹן","and-given"],["תַּמְרֻקֵיהֶן","soap-their"],["׃",""]] },
  { num:"ד", words:[["וְהַנַּעֲרָה","and-the-young woman"],["אֲשֶׁר","which"],["תִּיטַב","she will be good"],["בְּעֵינֵי","in-the-eyes-of"],["הַמֶּלֶךְ","the-king"],["תִּמְלֹךְ","will you reign"],["תַּחַת","under"],["וַשְׁתִּי","Vashti"],["וַיִּיטַב","and-it was good"],["הַדָּבָר","the-thing"],["בְּעֵינֵי","in-the-eyes-of"],["הַמֶּלֶךְ","the-king"],["וַיַּעַשׂ","and-did"],["כֵּן","thus"],["׃",""]] },
  { num:"ה", words:[["אִישׁ","man-of"],["יְהוּדִי","Jew"],["הָיָה","was"],["בְּשׁוּשַׁן","in-Susa"],["הַבִּירָה","the-temple"],["וּשְׁמוֹ","and-his-name"],["מׇרְדֳּכַי","Mordecai"],["בֶּן","son-of"],["יָאִיר","shall-shine"],["בֶּן־שִׁמְעִי","son-of-was Shimei"],["בֶּן־קִישׁ","son-of-Kish"],["אִישׁ","man-of"],["יְמִינִי","jaminites"],["׃",""]] },
  { num:"ו", words:[["אֲשֶׁר","which"],["הׇגְלָה","the-heap"],["מִירוּשָׁלַיִם","from-Jerusalem"],["עִם־הַגֹּלָה","with-the-exile"],["אֲשֶׁר","which"],["הׇגְלְתָה","it has been taken into exile"],["עִם","with"],["יְכׇנְיָה","Jeconiah"],["מֶלֶךְ־יְהוּדָה","king-of-Judah"],["אֲשֶׁר","which"],["הֶגְלָה","he had taken into exile"],["נְבוּכַדְנֶצַּר","Nebuchadnezzar"],["מֶלֶךְ","the-king-of"],["בָּבֶל","Babylon"],["׃",""]] },
  { num:"ז", words:[["וַיְהִי","and-it-came-to-pass"],["אֹמֵן","raising"],["אֶת־הֲדַסָּה","[ACC]-Hadassah"],["הִיא","it-is"],["אֶסְתֵּר","Esther"],["בַּת־דֹּדוֹ","daughter-of-uncle-his"],["כִּי","because"],["אֵין","there-is-no"],["לָהּ","it"],["אָב","father"],["וָאֵם","and-a-mother"],["וְהַנַּעֲרָה","and-the-young woman"],["יְפַת־תֹּאַר","fair-of-form"],["וְטוֹבַת","and-the-welfare-of"],["מַרְאֶה","appearance"],["וּבְמוֹת","and-at-the death of"],["אָבִיהָ","father-of"],["וְאִמָּהּ","and-mother-her"],["לְקָחָהּ","he has taken-her"],["מׇרְדֳּכַי","Mordecai"],["לוֹ","him"],["לְבַת","to-the daughter of"],["׃",""]] },
  { num:"ח", words:[["וַיְהִי","and-it-came-to-pass"],["בְּהִשָּׁמַע","when-were heard"],["דְּבַר־הַמֶּלֶךְ","word-of-the-king"],["וְדָתוֹ","and-orders-his"],["וּבְהִקָּבֵץ","and-when-were gathered"],["נְעָרוֹת","young women"],["רַבּוֹת","many"],["אֶל־שׁוּשַׁן","to-lilies"],["הַבִּירָה","the-temple"],["אֶל־יַד","to-hand-of"],["הֵגָי","Hegai"],["וַתִּלָּקַח","and-she was taken"],["אֶסְתֵּר","Esther"],["אֶל־בֵּית","to-the-house-of"],["הַמֶּלֶךְ","the-king"],["אֶל־יַד","to-hand-of"],["הֵגַי","Hegai"],["שֹׁמֵר","who keeps"],["הַנָּשִׁים","that-the-women"],["׃",""]] },
  { num:"ט", words:[["וַתִּיטַב","and-she was good"],["הַנַּעֲרָה","the-young woman"],["בְעֵינָיו","with-their-eyes"],["וַתִּשָּׂא","Otsh"],["חֶסֶד","mercy"],["לְפָנָיו","before-him"],["וַיְבַהֵל","and-he hastened"],["אֶת־תַּמְרוּקֶיהָ","[ACC]-rubbings-her"],["וְאֶת־מָנוֹתֶהָ","and-[ACC]-portions-her"],["לָתֵת","to-give"],["לָהּ","it"],["וְאֵת","and-[ACC]"],["שֶׁבַע","seven"],["הַנְּעָרוֹת","the-servant girls"],["הָרְאֻיוֹת","the-chosen"],["לָתֶת־לָהּ","that-I-might-it"],["מִבֵּית","from-house-of"],["הַמֶּלֶךְ","the-king"],["וַיְשַׁנֶּהָ","and-he moved-her"],["וְאֶת־נַעֲרוֹתֶיהָ","and-[ACC]-servant girls-her"],["לְטוֹב","for-good"],["בֵּית","the-house-of"],["הַנָּשִׁים","that-the-women"],["׃",""]] },
  { num:"י", words:[["לֹא־הִגִּידָה","not-she told"],["אֶסְתֵּר","Esther"],["אֶת־עַמָּהּ","[ACC]-people-its"],["וְאֶת־מוֹלַדְתָּהּ","and-[ACC]-kindred-her"],["כִּי","because"],["מׇרְדֳּכַי","Mordecai"],["צִוָּה","commanded"],["עָלֶיהָ","upon-it"],["אֲשֶׁר","which"],["לֹא־תַגִּיד","not-she will tell"],["׃",""]] },
  { num:"יא", words:[["וּבְכׇל־יוֹם","and-in-all-day"],["וָיוֹם","and-day"],["מׇרְדֳּכַי","Mordecai"],["מִתְהַלֵּךְ","walking"],["לִפְנֵי","before"],["חֲצַר","the courtyard of"],["בֵּית־הַנָּשִׁים","house-of-that-the-women"],["לָדַעַת","to-know"],["אֶת־שְׁלוֹם","[ACC]-an-everlasting"],["אֶסְתֵּר","Esther"],["וּמַה־יֵּעָשֶׂה","yea-and-what-will it be done"],["בָּהּ","in-it(f)"],["׃",""]] },
  { num:"יב", words:[["וּבְהַגִּיעַ","and-when-arrived"],["תֹּר","the turn of"],["נַעֲרָה","a young woman"],["וְנַעֲרָה","and-Naarah"],["לָבוֹא","to-come"],["אֶל־הַמֶּלֶךְ","unto-the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["מִקֵּץ","after"],["הֱיוֹת","have"],["לָהּ","it"],["כְּדָת","according to-the law"],["הַנָּשִׁים","that-the-women"],["שְׁנֵים","two"],["עָשָׂר","[compound]"],["חֹדֶשׁ","a month of"],["כִּי","because"],["כֵּן","thus"],["יִמְלְאוּ","they were completed"],["יְמֵי","the-days-of"],["מְרוּקֵיהֶן","rubbings-their"],["שִׁשָּׁה","she-rejoiced"],["חֳדָשִׁים","months"],["בְּשֶׁמֶן","with-oil"],["הַמֹּר","the-myrrh"],["וְשִׁשָּׁה","and-six"],["חֳדָשִׁים","months"],["בַּבְּשָׂמִים","with-the-balsam oil"],["וּבְתַמְרוּקֵי","and-with-the rubbings of"],["הַנָּשִׁים","that-the-women"],["׃",""]] },
  { num:"יג", words:[["וּבָזֶה","and-in-this"],["הַנַּעֲרָה","the-young woman"],["בָּאָה","comes"],["אֶל־הַמֶּלֶךְ","unto-the-king"],["אֵת","[ACC]"],["כׇּל־אֲשֶׁר","all-whose"],["תֹּאמַר","you-say"],["יִנָּתֵן","given-be-shall"],["לָהּ","it"],["לָבוֹא","to-come"],["עִמָּהּ","with-her"],["מִבֵּית","from-house-of"],["הַנָּשִׁים","that-the-women"],["עַד־בֵּית","until-house-of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"יד", words:[["בָּעֶרֶב","in-the-evening"],["הִיא","it-is"],["בָאָה","entered-into"],["וּבַבֹּקֶר","and-in-the-morning"],["הִיא","it-is"],["שָׁבָה","she-returned"],["אֶל־בֵּית","to-the-house-of"],["הַנָּשִׁים","that-the-women"],["שֵׁנִי","second"],["אֶל־יַד","to-hand-of"],["שַׁעַשְׁגַז","Shaashgaz"],["סְרִיס","an official of"],["הַמֶּלֶךְ","the-king"],["שֹׁמֵר","who keeps"],["הַפִּילַגְשִׁים","the-concubines"],["לֹא־תָבוֹא","there-shall-not-come"],["עוֹד","any-more"],["אֶל־הַמֶּלֶךְ","unto-the-king"],["כִּי","because"],["אִם־חָפֵץ","[compound]-desire/precious"],["בָּהּ","in-it(f)"],["הַמֶּלֶךְ","the-king"],["וְנִקְרְאָה","and-she was summoned"],["בְשֵׁם","in-name-of"],["׃",""]] },
  { num:"טו", words:[["וּבְהַגִּיעַ","and-when-arrived"],["תֹּר־אֶסְתֵּר","the turn of-Esther"],["בַּת־אֲבִיחַיִל","daughter-of-Abihail"],["דֹּד","the uncle of"],["מׇרְדֳּכַי","Mordecai"],["אֲשֶׁר","which"],["לָקַח־לוֹ","took-him"],["לְבַת","to-the daughter of"],["לָבוֹא","to-come"],["אֶל־הַמֶּלֶךְ","unto-the-king"],["לֹא","not"],["בִקְשָׁה","she requested"],["דָּבָר","things"],["כִּי","because"],["אִם","[compound]"],["אֶת־אֲשֶׁר","ACC-that-which"],["יֹאמַר","He-says"],["הֵגַי","Hegai"],["סְרִיס־הַמֶּלֶךְ","an official of-the-king"],["שֹׁמֵר","who keeps"],["הַנָּשִׁים","that-the-women"],["וַתְּהִי","and-was"],["אֶסְתֵּר","Esther"],["נֹשֵׂאת","bearing"],["חֵן","favor"],["בְּעֵינֵי","in-the-eyes-of"],["כׇּל־רֹאֶיהָ","all-those who saw-her"],["׃",""]] },
  { num:"טז", words:[["וַתִּלָּקַח","and-she was taken"],["אֶסְתֵּר","Esther"],["אֶל־הַמֶּלֶךְ","unto-the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["אֶל־בֵּית","to-the-house-of"],["מַלְכוּתוֹ","His-kingdom"],["בַּחֹדֶשׁ","in-the-month"],["הָעֲשִׂירִי","the-rich-my"],["הוּא־חֹדֶשׁ","it-is-a month of"],["טֵבֵת","Tebeth"],["בִּשְׁנַת־שֶׁבַע","in-year-of-seven"],["לְמַלְכוּתוֹ","for-royalty-his"],["׃",""]] },
  { num:"יז", words:[["וַיֶּאֱהַב","and-he loved"],["הַמֶּלֶךְ","the-king"],["אֶת־אֶסְתֵּר","[ACC]-Esther"],["מִכׇּל־הַנָּשִׁים","from-all-that-the-women"],["וַתִּשָּׂא־חֵן","Otsh-favor"],["וָחֶסֶד","and-covenant loyalty"],["לְפָנָיו","before-him"],["מִכׇּל־הַבְּתוּלוֹת","from-all-the-virgins"],["וַיָּשֶׂם","and-made-He"],["כֶּתֶר־מַלְכוּת","a crown of-the-reign-of"],["בְּרֹאשָׁהּ","on-head-her"],["וַיַּמְלִיכֶהָ","and-he made queen-her"],["תַּחַת","under"],["וַשְׁתִּי","Vashti"],["׃",""]] },
  { num:"יח", words:[["וַיַּעַשׂ","and-did"],["הַמֶּלֶךְ","the-king"],["מִשְׁתֶּה","feast"],["גָדוֹל","great"],["לְכׇל־שָׂרָיו","to-all-commanders-his"],["וַעֲבָדָיו","and-servants-his"],["אֵת","[ACC]"],["מִשְׁתֵּה","a feast of"],["אֶסְתֵּר","Esther"],["וַהֲנָחָה","and-a holiday"],["לַמְּדִינוֹת","for the-provinces"],["עָשָׂה","he-did"],["וַיִּתֵּן","and-gave"],["מַשְׂאֵת","tribute"],["כְּיַד","according to-the hand of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"יט", words:[["וּבְהִקָּבֵץ","and-when-were gathered"],["בְּתוּלוֹת","virgins"],["שֵׁנִית","again"],["וּמׇרְדֳּכַי","and-Mordecai"],["יֹשֵׁב","who-dwell-in"],["בְּשַׁעַר־הַמֶּלֶךְ","in-the gate of-the-king"],["׃",""]] },
  { num:"כ", words:[["אֵין","there-is-no"],["אֶסְתֵּר","Esther"],["מַגֶּדֶת","was telling"],["מוֹלַדְתָּהּ","kindred-her"],["וְאֶת־עַמָּהּ","and-[ACC]-people-its"],["כַּאֲשֶׁר","when/as"],["צִוָּה","commanded"],["עָלֶיהָ","upon-it"],["מׇרְדֳּכָי","Mordecai"],["וְאֶת־מַאֲמַר","and-[ACC]-the command of"],["מׇרְדֳּכַי","Mordecai"],["אֶסְתֵּר","Esther"],["עֹשָׂה","is making"],["כַּאֲשֶׁר","when/as"],["הָיְתָה","was"],["בְאׇמְנָה","in-surely"],["אִתּוֹ","with-him"],["׃",""]] },
  { num:"כא", words:[["בַּיָּמִים","in-the-days"],["הָהֵם","those"],["וּמׇרְדֳּכַי","and-Mordecai"],["יוֹשֵׁב","sitting"],["בְּשַׁעַר־הַמֶּלֶךְ","in-the gate of-the-king"],["קָצַף","was-angry"],["בִּגְתָן","Bigthan"],["וָתֶרֶשׁ","and-Teresh"],["שְׁנֵי־סָרִיסֵי","two-the eunuchs of"],["הַמֶּלֶךְ","the-king"],["מִשֹּׁמְרֵי","from-the guards of"],["הַסַּף","the-threshold"],["וַיְבַקְשׁוּ","and-desired-of-him"],["לִשְׁלֹחַ","lay"],["יָד","hands"],["בַּמֶּלֶךְ","in-the-reigned"],["אֲחַשְׁוֵרֹשׁ","Ahasuerus"],["׃",""]] },
  { num:"כב", words:[["וַיִּוָּדַע","they-were-discovered-unto"],["הַדָּבָר","the-thing"],["לְמׇרְדֳּכַי","to-Mordecai"],["וַיַּגֵּד","and-it-shall-be-told"],["לְאֶסְתֵּר","to-Esther"],["הַמַּלְכָּה","the-queen"],["וַתֹּאמֶר","and-said"],["אֶסְתֵּר","Esther"],["לַמֶּלֶךְ","the-king"],["בְּשֵׁם","by-name"],["מׇרְדֳּכָי","Mordecai"],["׃",""]] },
  { num:"כג", words:[["וַיְבֻקַּשׁ","and-it was sought"],["הַדָּבָר","the-thing"],["וַיִּמָּצֵא","and-it was found"],["וַיִּתָּלוּ","and-they were hanged"],["שְׁנֵיהֶם","the-two"],["עַל־עֵץ","upon-a-tree"],["וַיִּכָּתֵב","and-written-was-it"],["בְּסֵפֶר","in-a-book"],["דִּבְרֵי","account-of"],["הַיָּמִים","the-days"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
];
renderVerseSet(est_ch2Verses, 'est-ch2-verses');

var est_ch3Verses = [
  { num:"א", words:[["אַחַר","after"],["הַדְּבָרִים","the-things"],["הָאֵלֶּה","these"],["גִּדַּל","he made great"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["אֶת־הָמָן","[ACC]-Haman"],["בֶּן־הַמְּדָתָא","the-son-of-Hammedatha"],["הָאֲגָגִי","the-Agagite"],["וַיְנַשְּׂאֵהוּ","and-he exalted-him"],["וַיָּשֶׂם","and-made-He"],["אֶת־כִּסְאוֹ","[ACC]-his-throne"],["מֵעַל","from-upon"],["כׇּל־הַשָּׂרִים","all-the-princes"],["אֲשֶׁר","which"],["אִתּוֹ","with-him"],["׃",""]] },
  { num:"ב", words:[["וְכׇל־עַבְדֵי","and-all-servants-of"],["הַמֶּלֶךְ","the-king"],["אֲשֶׁר־בְּשַׁעַר","whose-in-the gate of"],["הַמֶּלֶךְ","the-king"],["כֹּרְעִים","were kneeling"],["וּמִשְׁתַּחֲוִים","and-worshipping"],["לְהָמָן","to-Haman"],["כִּי־כֵן","because-thus"],["צִוָּה־לוֹ","commanded-him"],["הַמֶּלֶךְ","the-king"],["וּמׇרְדֳּכַי","and-Mordecai"],["לֹא","not"],["יִכְרַע","he will bow down"],["וְלֹא","and-not"],["יִשְׁתַּחֲוֶה","he bowed down"],["׃",""]] },
  { num:"ג", words:[["וַיֹּאמְרוּ","and-they-said"],["עַבְדֵי","servants-of"],["הַמֶּלֶךְ","the-king"],["אֲשֶׁר־בְּשַׁעַר","whose-in-the gate of"],["הַמֶּלֶךְ","the-king"],["לְמׇרְדֳּכָי","for-Mordecai"],["מַדּוּעַ","why"],["אַתָּה","you"],["עוֹבֵר","passing along"],["אֵת","[ACC]"],["מִצְוַת","the-commandments-of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ד", words:[["וַיְהִי","and-it-came-to-pass"],["(באמרם)","because-will say-they"],["[כְּאׇמְרָם]","just as-spoke-they"],["אֵלָיו","to-him"],["יוֹם","day"],["וָיוֹם","and-day"],["וְלֹא","and-not"],["שָׁמַע","heard"],["אֲלֵיהֶם","to-them"],["וַיַּגִּידוּ","and-did-declare"],["לְהָמָן","to-Haman"],["לִרְאוֹת","to-see"],["הֲיַעַמְדוּ","¿-will they stand"],["דִּבְרֵי","account-of"],["מׇרְדֳּכַי","Mordecai"],["כִּי־הִגִּיד","because-declared"],["לָהֶם","to-them"],["אֲשֶׁר־הוּא","whose-it-is"],["יְהוּדִי","Jew"],["׃",""]] },
  { num:"ה", words:[["וַיַּרְא","and-saw"],["הָמָן","Haman"],["כִּי־אֵין","because-there-is-no"],["מׇרְדֳּכַי","Mordecai"],["כֹּרֵעַ","was kneeling"],["וּמִשְׁתַּחֲוֶה","and-bowing down"],["לוֹ","him"],["וַיִּמָּלֵא","and-was-filled"],["הָמָן","Haman"],["חֵמָה","wrath"],["׃",""]] },
  { num:"ו", words:[["וַיִּבֶז","and-he despised"],["בְּעֵינָיו","in-His-eyes"],["לִשְׁלֹחַ","lay"],["יָד","hands"],["בְּמׇרְדֳּכַי","in-Mordecai"],["לְבַדּוֹ","alone"],["כִּי־הִגִּידוּ","because-they-declare"],["לוֹ","him"],["אֶת־עַם","ACC-people-of"],["מׇרְדֳּכָי","Mordecai"],["וַיְבַקֵּשׁ","and-requested"],["הָמָן","Haman"],["לְהַשְׁמִיד","to-destroy"],["אֶת־כׇּל־הַיְּהוּדִים","[ACC]-all-the-Jews"],["אֲשֶׁר","which"],["בְּכׇל־מַלְכוּת","in-all-the-reign-of"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["עַם","people"],["מׇרְדֳּכָי","Mordecai"],["׃",""]] },
  { num:"ז", words:[["בַּחֹדֶשׁ","in-the-month"],["הָרִאשׁוֹן","the-first"],["הוּא־חֹדֶשׁ","it-is-a month of"],["נִיסָן","Nisan"],["בִּשְׁנַת","in-year-of"],["שְׁתֵּים","two"],["עֶשְׂרֵה","and-ten"],["לַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["הִפִּיל","the-Lord-caused"],["פּוּר","Pur"],["הוּא","it-is"],["הַגּוֹרָל","the-lot"],["לִפְנֵי","before"],["הָמָן","Haman"],["מִיּוֹם","from-the-day"],["לְיוֹם","to-day"],["וּמֵחֹדֶשׁ","and-from-month"],["לְחֹדֶשׁ","to-month"],["שְׁנֵים־עָשָׂר","two-[compound]"],["הוּא־חֹדֶשׁ","it-is-a month of"],["אֲדָר","Adar"],["׃",""]] },
  { num:"ח", words:[["וַיֹּאמֶר","and-said"],["הָמָן","Haman"],["לַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["יֶשְׁנוֹ","there-he"],["עַם־אֶחָד","people-one"],["מְפֻזָּר","scattered"],["וּמְפֹרָד","and-separated"],["בֵּין","among"],["הָעַמִּים","the-people"],["בְּכֹל","in-all"],["מְדִינוֹת","the provinces of"],["מַלְכוּתֶךָ","kingdom-your"],["וְדָתֵיהֶם","and-laws-their"],["שֹׁנוֹת","different"],["מִכׇּל־עָם","from-all-a-people"],["וְאֶת־דָּתֵי","and-[ACC]-the laws of"],["הַמֶּלֶךְ","the-king"],["אֵינָם","they-are-not"],["עֹשִׂים","which-act"],["וְלַמֶּלֶךְ","and-to the-king"],["אֵין־שֹׁוֶה","there-is-no-is appropriate"],["לְהַנִּיחָם","to-let remain-them"],["׃",""]] },
  { num:"ט", words:[["אִם־עַל־הַמֶּלֶךְ","[compound]-upon-the-king"],["טוֹב","good"],["יִכָּתֵב","be-engraved"],["לְאַבְּדָם","to-destroy-them"],["וַעֲשֶׂרֶת","and-ten"],["אֲלָפִים","two-thousand"],["כִּכַּר־כֶּסֶף","the valley of-money"],["אֶשְׁקוֹל","I will weigh out"],["עַל־יְדֵי","by-means-of"],["עֹשֵׂי","Shi"],["הַמְּלָאכָה","the-task"],["לְהָבִיא","to-bring-about"],["אֶל־גִּנְזֵי","to-the treasures of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"י", words:[["וַיָּסַר","for-he-put-down"],["הַמֶּלֶךְ","the-king"],["אֶת־טַבַּעְתּוֹ","[ACC]-signet-ring-his"],["מֵעַל","from-upon"],["יָדוֹ","his-hand"],["וַיִּתְּנָהּ","and-he gave-it"],["לְהָמָן","to-Haman"],["בֶּן־הַמְּדָתָא","the-son-of-Hammedatha"],["הָאֲגָגִי","the-Agagite"],["צֹרֵר","the opposer of"],["הַיְּהוּדִים","the-Jews"],["׃",""]] },
  { num:"יא", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["לְהָמָן","to-Haman"],["הַכֶּסֶף","the-money"],["נָתוּן","given"],["לָךְ","[compound]"],["וְהָעָם","and-the-this-people"],["לַעֲשׂוֹת","to-do"],["בּוֹ","against-him"],["כַּטּוֹב","as-the-seems-you-good"],["בְּעֵינֶיךָ","in-your-eyes"],["׃",""]] },
  { num:"יב", words:[["וַיִּקָּרְאוּ","and-they-were-called"],["סֹפְרֵי","the scribes of"],["הַמֶּלֶךְ","the-king"],["בַּחֹדֶשׁ","in-the-month"],["הָרִאשׁוֹן","the-first"],["בִּשְׁלוֹשָׁה","was among-three"],["עָשָׂר","[compound]"],["יוֹם","day"],["בּוֹ","against-him"],["וַיִּכָּתֵב","and-written-was-it"],["כְּכׇל־אֲשֶׁר־צִוָּה","as-all-whose-commanded"],["הָמָן","Haman"],["אֶל","to"],["אֲחַשְׁדַּרְפְּנֵי־הַמֶּלֶךְ","the satraps of-the-king"],["וְאֶל־הַפַּחוֹת","and-the-governors"],["אֲשֶׁר","which"],["עַל־מְדִינָה","upon-provinces"],["וּמְדִינָה","and-province"],["וְאֶל־שָׂרֵי","and-captains-of"],["עַם","people"],["וָעָם","and-people"],["מְדִינָה","provinces"],["וּמְדִינָה","and-province"],["כִּכְתָבָהּ","according to-writing-its"],["וְעַם","and-the-people-of"],["וָעָם","and-people"],["כִּלְשׁוֹנוֹ","according to-language-its"],["בְּשֵׁם","by-name"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרֹשׁ","Ahasuerus"],["נִכְתָּב","has-been-written"],["וְנֶחְתָּם","and-it was sealed"],["בְּטַבַּעַת","with-the signet-ring of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"יג", words:[["וְנִשְׁלוֹחַ","and-they were sent"],["סְפָרִים","records"],["בְּיַד","in-hand-of"],["הָרָצִים","the-runners"],["אֶל־כׇּל־מְדִינוֹת","to-all-the provinces of"],["הַמֶּלֶךְ","the-king"],["לְהַשְׁמִיד","to-destroy"],["לַהֲרֹג","slay"],["וּלְאַבֵּד","and-to-destroy"],["אֶת־כׇּל־הַיְּהוּדִים","[ACC]-all-the-Jews"],["מִנַּעַר","from-young man"],["וְעַד־זָקֵן","and-unto-the-ancient"],["טַף","little ones"],["וְנָשִׁים","and-carrying"],["בְּיוֹם","in-day-of"],["אֶחָד","one"],["בִּשְׁלוֹשָׁה","was among-three"],["עָשָׂר","[compound]"],["לְחֹדֶשׁ","to-month"],["שְׁנֵים־עָשָׂר","two-[compound]"],["הוּא־חֹדֶשׁ","it-is-a month of"],["אֲדָר","Adar"],["וּשְׁלָלָם","and-may-be-their-prey"],["לָבוֹז","to-take as plunder"],["׃",""]] },
  { num:"יד", words:[["פַּתְשֶׁגֶן","copy of"],["הַכְּתָב","the-writing"],["לְהִנָּתֵן","was to-be given"],["דָּת","law"],["בְּכׇל־מְדִינָה","in-all-provinces"],["וּמְדִינָה","and-province"],["גָּלוּי","open"],["לְכׇל־הָעַמִּים","to-all-the-people"],["לִהְיוֹת","to-be"],["עֲתִדִים","ready"],["לַיּוֹם","that-the-day"],["הַזֶּה","this"],["׃",""]] },
  { num:"טו", words:[["הָרָצִים","the-runners"],["יָצְאוּ","went-forth"],["דְחוּפִים","being hasty"],["בִּדְבַר","of-the-promise-of"],["הַמֶּלֶךְ","the-king"],["וְהַדָּת","and-the-law"],["נִתְּנָה","was-given(f)"],["בְּשׁוּשַׁן","in-Susa"],["הַבִּירָה","the-temple"],["וְהַמֶּלֶךְ","and-the-king"],["וְהָמָן","and-Haman"],["יָשְׁבוּ","had-been-peopled"],["לִשְׁתּוֹת","to-drink"],["וְהָעִיר","and-the-city"],["שׁוּשָׁן","Susa"],["נָבוֹכָה","it was in confusion"],["׃",""]] },
];
renderVerseSet(est_ch3Verses, 'est-ch3-verses');

var est_ch4Verses = [
  { num:"א", words:[["וּמׇרְדֳּכַי","and-Mordecai"],["יָדַע","he-knew"],["אֶת־כׇּל־אֲשֶׁר","[ACC]-all-which"],["נַעֲשָׂה","was-done"],["וַיִּקְרַע","and-he tore"],["מׇרְדֳּכַי","Mordecai"],["אֶת־בְּגָדָיו","[ACC]-garments-of-his"],["וַיִּלְבַּשׁ","and-he was clothed"],["שַׂק","sackcloth"],["וָאֵפֶר","and-ashes"],["וַיֵּצֵא","and-went-out"],["בְּתוֹךְ","among"],["הָעִיר","the-city"],["וַיִּזְעַק","and-cried-out"],["זְעָקָה","a cry"],["גְדוֹלָה","great"],["וּמָרָה","and-bitter"],["׃",""]] },
  { num:"ב", words:[["וַיָּבוֹא","and-he came"],["עַד","until"],["לִפְנֵי","before"],["שַׁעַר־הַמֶּלֶךְ","gate-of-the-king"],["כִּי","because"],["אֵין","there-is-no"],["לָבוֹא","to-come"],["אֶל־שַׁעַר","to-gate-of"],["הַמֶּלֶךְ","the-king"],["בִּלְבוּשׁ","in-clothing of"],["שָׂק","sackcloth"],["׃",""]] },
  { num:"ג", words:[["וּבְכׇל־מְדִינָה","and-in-all-provinces"],["וּמְדִינָה","and-province"],["מְקוֹם","the-place"],["אֲשֶׁר","which"],["דְּבַר־הַמֶּלֶךְ","word-of-the-king"],["וְדָתוֹ","and-orders-his"],["מַגִּיעַ","was reaching"],["אֵבֶל","a-great-mourning"],["גָּדוֹל","great"],["לַיְּהוּדִים","to-the-Jews"],["וְצוֹם","and-fasting"],["וּבְכִי","and-weeping"],["וּמִסְפֵּד","and-lamentation"],["שַׂק","sackcloth"],["וָאֵפֶר","and-ashes"],["יֻצַּע","is-spread"],["לָרַבִּים","by-many people"],["׃",""]] },
  { num:"ד", words:[["(ותבואינה)","and-they may come"],["[וַתָּבוֹאנָה]","so-they may come"],["נַעֲרוֹת","the maids of"],["אֶסְתֵּר","Esther"],["וְסָרִיסֶיהָ","and-eunuchs-her"],["וַיַּגִּידוּ","and-did-declare"],["לָהּ","it"],["וַתִּתְחַלְחַל","and-she agonized"],["הַמַּלְכָּה","the-queen"],["מְאֹד","exceedingly"],["וַתִּשְׁלַח","and-she-sent"],["בְּגָדִים","garments"],["לְהַלְבִּישׁ","clothing"],["אֶת־מׇרְדֳּכַי","[ACC]-Mordecai"],["וּלְהָסִיר","and-to-remove"],["שַׂקּוֹ","sack-his"],["מֵעָלָיו","from-with-him"],["וְלֹא","and-not"],["קִבֵּל","received"],["׃",""]] },
  { num:"ה", words:[["וַתִּקְרָא","and-she called"],["אֶסְתֵּר","Esther"],["לַהֲתָךְ","Hathach"],["מִסָּרִיסֵי","one of-the eunuchs of"],["הַמֶּלֶךְ","the-king"],["אֲשֶׁר","which"],["הֶעֱמִיד","established"],["לְפָנֶיהָ","to-face-of"],["וַתְּצַוֵּהוּ","and-she commanded-him"],["עַל־מׇרְדֳּכָי","upon-Mordecai"],["לָדַעַת","to-know"],["מַה־זֶּה","what-is this?"],["וְעַל־מַה־זֶּה","and-upon-what-Zh"],["׃",""]] },
  { num:"ו", words:[["וַיֵּצֵא","and-went-out"],["הֲתָךְ","Hathach"],["אֶל־מׇרְדֳּכָי","to-Mordecai"],["אֶל־רְחוֹב","to-Rehob"],["הָעִיר","the-city"],["אֲשֶׁר","which"],["לִפְנֵי","before"],["שַׁעַר־הַמֶּלֶךְ","gate-of-the-king"],["׃",""]] },
  { num:"ז", words:[["וַיַּגֶּד־לוֹ","and-told-to-him"],["מׇרְדֳּכַי","Mordecai"],["אֵת","[ACC]"],["כׇּל־אֲשֶׁר","all-whose"],["קָרָהוּ","it had happened to-him"],["וְאֵת","and-[ACC]"],["פָּרָשַׁת","the exact amount of"],["הַכֶּסֶף","the-money"],["אֲשֶׁר","which"],["אָמַר","said"],["הָמָן","Haman"],["לִשְׁקוֹל","to-weigh out"],["עַל־גִּנְזֵי","upon-the treasures of"],["הַמֶּלֶךְ","the-king"],["[בַּיְּהוּדִים]","on the-Jews"],["לְאַבְּדָם","to-destroy-them"],["׃",""]] },
  { num:"ח", words:[["וְאֶת־פַּתְשֶׁגֶן","and-[ACC]-copy of"],["כְּתָב־הַדָּת","writing-the-law"],["אֲשֶׁר־נִתַּן","whose-was-given"],["בְּשׁוּשָׁן","in-Susa"],["לְהַשְׁמִידָם","to-destroy-them"],["נָתַן","was-given"],["לוֹ","him"],["לְהַרְאוֹת","to-exercise"],["אֶת־אֶסְתֵּר","[ACC]-Esther"],["וּלְהַגִּיד","and-that-they-might-impart"],["לָהּ","it"],["וּלְצַוּוֹת","and-to-command"],["עָלֶיהָ","upon-it"],["לָבוֹא","to-come"],["אֶל־הַמֶּלֶךְ","unto-the-king"],["לְהִתְחַנֶּן־לוֹ","to-seek favor-him"],["וּלְבַקֵּשׁ","and-ask"],["מִלְּפָנָיו","from-before-him"],["עַל־עַמָּהּ","upon-people-its"],["׃",""]] },
  { num:"ט", words:[["וַיָּבוֹא","and-he came"],["הֲתָךְ","Hathach"],["וַיַּגֵּד","and-it-shall-be-told"],["לְאֶסְתֵּר","to-Esther"],["אֵת","[ACC]"],["דִּבְרֵי","account-of"],["מׇרְדֳּכָי","Mordecai"],["׃",""]] },
  { num:"י", words:[["וַתֹּאמֶר","and-said"],["אֶסְתֵּר","Esther"],["לַהֲתָךְ","Hathach"],["וַתְּצַוֵּהוּ","and-she commanded-him"],["אֶל־מׇרְדֳּכָי","to-Mordecai"],["׃",""]] },
  { num:"יא", words:[["כׇּל־עַבְדֵי","all-servants-of"],["הַמֶּלֶךְ","the-king"],["וְעַם־מְדִינוֹת","and-the-people-of-the provinces of"],["הַמֶּלֶךְ","the-king"],["יֹדְעִים","knowing"],["אֲשֶׁר","which"],["כׇּל־אִישׁ","all-man/each"],["וְאִשָּׁה","and-everyone fem"],["אֲשֶׁר","which"],["יָבוֹא־אֶל־הַמֶּלֶךְ","shall-come-to-the-king"],["אֶל־הֶחָצֵר","to-the-courtyard"],["הַפְּנִימִית","the-inner"],["אֲשֶׁר","which"],["לֹא־יִקָּרֵא","shall-never-be-renowned"],["אַחַת","one"],["דָּתוֹ","law-his"],["לְהָמִית","that-he-might-be-slain"],["לְבַד","alone"],["מֵאֲשֶׁר","than-that"],["יוֹשִׁיט־לוֹ","he extends-him"],["הַמֶּלֶךְ","the-king"],["אֶת־שַׁרְבִיט","[ACC]-the scepter of"],["הַזָּהָב","the-gold"],["וְחָיָה","and-he will live"],["וַאֲנִי","and-I"],["לֹא","not"],["נִקְרֵאתִי","I-was-called"],["לָבוֹא","to-come"],["אֶל־הַמֶּלֶךְ","unto-the-king"],["זֶה","this"],["שְׁלוֹשִׁים","thirty warriors"],["יוֹם","day"],["׃",""]] },
  { num:"יב", words:[["וַיַּגִּידוּ","and-did-declare"],["לְמׇרְדֳּכָי","for-Mordecai"],["אֵת","[ACC]"],["דִּבְרֵי","account-of"],["אֶסְתֵּר","Esther"],["׃",""]] },
  { num:"יג", words:[["וַיֹּאמֶר","and-said"],["מׇרְדֳּכַי","Mordecai"],["לְהָשִׁיב","to-he-restored"],["אֶל־אֶסְתֵּר","to-Esther"],["אַל־תְּדַמִּי","do-not-you imagine"],["בְנַפְשֵׁךְ","in-self-your"],["לְהִמָּלֵט","to-the-cement"],["בֵּית־הַמֶּלֶךְ","house-of-the-king"],["מִכׇּל־הַיְּהוּדִים","from-all-the-Jews"],["׃",""]] },
  { num:"יד", words:[["כִּי","because"],["אִם־הַחֲרֵשׁ","the-[compound]-certainly if"],["תַּחֲרִישִׁי","you will keep quiet"],["בָּעֵת","at-the-time"],["הַזֹּאת","is-this"],["רֶוַח","relief"],["וְהַצָּלָה","and-the-deliverance"],["יַעֲמוֹד","it will arise"],["לַיְּהוּדִים","to-the-Jews"],["מִמָּקוֹם","from-place"],["אַחֵר","other"],["וְאַתְּ","and-you"],["וּבֵית־אָבִיךְ","and-house-of-father-your"],["תֹּאבֵדוּ","you-must-perish"],["וּמִי","and-whoso"],["יוֹדֵעַ","knows"],["אִם־לְעֵת","[compound]-to-time"],["כָּזֹאת","such"],["הִגַּעַתְּ","you have reached"],["לַמַּלְכוּת","the-queenhood"],["׃",""]] },
  { num:"טו", words:[["וַתֹּאמֶר","and-said"],["אֶסְתֵּר","Esther"],["לְהָשִׁיב","to-he-restored"],["אֶל־מׇרְדֳּכָי","to-Mordecai"],["׃",""]] },
  { num:"טז", words:[["לֵךְ","go"],["כְּנוֹס","gather"],["אֶת־כׇּל־הַיְּהוּדִים","[ACC]-all-the-Jews"],["הַנִּמְצְאִים","the-who-were found"],["בְּשׁוּשָׁן","in-Susa"],["וְצוּמוּ","and-fast"],["עָלַי","I-must"],["וְאַל־תֹּאכְלוּ","and-do-not-you eat"],["וְאַל־תִּשְׁתּוּ","and-do-not-you drink"],["שְׁלֹשֶׁת","three-of"],["יָמִים","days"],["לַיְלָה","night"],["וָיוֹם","and-day"],["גַּם־אֲנִי","also-I"],["וְנַעֲרֹתַי","and-maids-my"],["אָצוּם","I will fast"],["כֵּן","thus"],["וּבְכֵן","and-in-such"],["אָבוֹא","I-will-come"],["אֶל־הַמֶּלֶךְ","unto-the-king"],["אֲשֶׁר","which"],["לֹא־כַדָּת","not-was according to the-law"],["וְכַאֲשֶׁר","and-as"],["אָבַדְתִּי","perished"],["אָבָדְתִּי","I have perished"],["׃",""]] },
  { num:"יז", words:[["וַיַּעֲבֹר","and-overcame"],["מׇרְדֳּכָי","Mordecai"],["וַיַּעַשׂ","and-did"],["כְּכֹל","according-to-all"],["אֲשֶׁר־צִוְּתָה","whose-she had commanded"],["עָלָיו","upon-him"],["אֶסְתֵּר","Esther"],["׃",""]] },
];
renderVerseSet(est_ch4Verses, 'est-ch4-verses');

var est_ch5Verses = [
  { num:"א", words:[["וַיְהִי","and-it-came-to-pass"],["בַּיּוֹם","in-the-day"],["הַשְּׁלִישִׁי","the-third"],["וַתִּלְבַּשׁ","and-she put on"],["אֶסְתֵּר","Esther"],["מַלְכוּת","the-reign-of"],["וַתַּעֲמֹד","and-shall-stand"],["בַּחֲצַר","in-the courtyard of"],["בֵּית־הַמֶּלֶךְ","house-of-the-king"],["הַפְּנִימִית","the-inner"],["נֹכַח","opposite to"],["בֵּית","the-house-of"],["הַמֶּלֶךְ","the-king"],["וְהַמֶּלֶךְ","and-the-king"],["יוֹשֵׁב","sitting"],["עַל־כִּסֵּא","upon-throne"],["מַלְכוּתוֹ","His-kingdom"],["בְּבֵית","in-house-of"],["הַמַּלְכוּת","the-kingdom"],["נֹכַח","opposite to"],["פֶּתַח","door-of"],["הַבָּיִת","the-house"],["׃",""]] },
  { num:"ב", words:[["וַיְהִי","and-it-came-to-pass"],["כִרְאוֹת","when-saw"],["הַמֶּלֶךְ","the-king"],["אֶת־אֶסְתֵּר","[ACC]-Esther"],["הַמַּלְכָּה","the-queen"],["עֹמֶדֶת","standing(f)"],["בֶּחָצֵר","in the-court"],["נָשְׂאָה","she bore"],["חֵן","favor"],["בְּעֵינָיו","in-His-eyes"],["וַיּוֹשֶׁט","and-he extended"],["הַמֶּלֶךְ","the-king"],["לְאֶסְתֵּר","to-Esther"],["אֶת־שַׁרְבִיט","[ACC]-the scepter of"],["הַזָּהָב","the-gold"],["אֲשֶׁר","which"],["בְּיָדוֹ","in-his-hand"],["וַתִּקְרַב","and-it drew near"],["אֶסְתֵּר","Esther"],["וַתִּגַּע","and-it touched"],["בְּרֹאשׁ","in-the-gall-of"],["הַשַּׁרְבִיט","the-scepter"],["׃",""]] },
  { num:"ג", words:[["וַיֹּאמֶר","and-said"],["לָהּ","it"],["הַמֶּלֶךְ","the-king"],["מַה־לָּךְ","what-to-you"],["אֶסְתֵּר","Esther"],["הַמַּלְכָּה","the-queen"],["וּמַה־בַּקָּשָׁתֵךְ","the-yea-and-what-is request-your"],["עַד־חֲצִי","until-half"],["הַמַּלְכוּת","the-kingdom"],["וְיִנָּתֵן","and-shall-be-delivered"],["לָךְ","[compound]"],["׃",""]] },
  { num:"ד", words:[["וַתֹּאמֶר","and-said"],["אֶסְתֵּר","Esther"],["אִם־עַל־הַמֶּלֶךְ","[compound]-upon-the-king"],["טוֹב","good"],["יָבוֹא","shall-come"],["הַמֶּלֶךְ","the-king"],["וְהָמָן","and-Haman"],["הַיּוֹם","the-day"],["אֶל־הַמִּשְׁתֶּה","to-the-feast"],["אֲשֶׁר־עָשִׂיתִי","whose-I-made"],["לוֹ","him"],["׃",""]] },
  { num:"ה", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["מַהֲרוּ","hurry"],["אֶת־הָמָן","[ACC]-Haman"],["לַעֲשׂוֹת","to-do"],["אֶת־דְּבַר","ACC-word-of"],["אֶסְתֵּר","Esther"],["וַיָּבֹא","and-came"],["הַמֶּלֶךְ","the-king"],["וְהָמָן","and-Haman"],["אֶל־הַמִּשְׁתֶּה","to-the-feast"],["אֲשֶׁר־עָשְׂתָה","whose-did(f)"],["אֶסְתֵּר","Esther"],["׃",""]] },
  { num:"ו", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["לְאֶסְתֵּר","to-Esther"],["בְּמִשְׁתֵּה","at-the feast of"],["הַיַּיִן","the-wine"],["מַה־שְּׁאֵלָתֵךְ","what-is petition-your"],["וְיִנָּתֵן","and-shall-be-delivered"],["לָךְ","[compound]"],["וּמַה־בַּקָּשָׁתֵךְ","the-yea-and-what-is request-your"],["עַד־חֲצִי","until-half"],["הַמַּלְכוּת","the-kingdom"],["וְתֵעָשׂ","and-it may be done"],["׃",""]] },
  { num:"ז", words:[["וַתַּעַן","and-she answered"],["אֶסְתֵּר","Esther"],["וַתֹּאמַר","and-she said"],["שְׁאֵלָתִי","petition-my"],["וּבַקָּשָׁתִי","and-the-request-my"],["׃",""]] },
  { num:"ח", words:[["אִם־מָצָאתִי","[compound]-I-found"],["חֵן","favor"],["בְּעֵינֵי","in-the-eyes-of"],["הַמֶּלֶךְ","the-king"],["וְאִם־עַל־הַמֶּלֶךְ","and-if-upon-the-king"],["טוֹב","good"],["לָתֵת","to-give"],["אֶת־שְׁאֵלָתִי","[ACC]-petition-my"],["וְלַעֲשׂוֹת","and-do"],["אֶת־בַּקָּשָׁתִי","[ACC]-the-I-have-sought"],["יָבוֹא","shall-come"],["הַמֶּלֶךְ","the-king"],["וְהָמָן","and-Haman"],["אֶל־הַמִּשְׁתֶּה","to-the-feast"],["אֲשֶׁר","which"],["אֶעֱשֶׂה","I-do"],["לָהֶם","to-them"],["וּמָחָר","and-on-the-morrow"],["אֶעֱשֶׂה","I-do"],["כִּדְבַר","according-to-the-word-of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ט", words:[["וַיֵּצֵא","and-went-out"],["הָמָן","Haman"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["שָׂמֵחַ","happy"],["וְטוֹב","and-better"],["לֵב","heart"],["וְכִרְאוֹת","and-when-saw"],["הָמָן","Haman"],["אֶת־מׇרְדֳּכַי","[ACC]-Mordecai"],["בְּשַׁעַר","in-the gate of"],["הַמֶּלֶךְ","the-king"],["וְלֹא־קָם","and-not-arose"],["וְלֹא־זָע","and-not-he trembled"],["מִמֶּנּוּ","from-him"],["וַיִּמָּלֵא","and-was-filled"],["הָמָן","Haman"],["עַל־מׇרְדֳּכַי","upon-Mordecai"],["חֵמָה","wrath"],["׃",""]] },
  { num:"י", words:[["וַיִּתְאַפַּק","and-he restrained himself"],["הָמָן","Haman"],["וַיָּבוֹא","and-he came"],["אֶל־בֵּיתוֹ","to-his-house"],["וַיִּשְׁלַח","and-sent"],["וַיָּבֵא","and-he-brought"],["אֶת־אֹהֲבָיו","[ACC]-friends-his"],["וְאֶת־זֶרֶשׁ","and-[ACC]-Zeresh"],["אִשְׁתּוֹ","his-wife"],["׃",""]] },
  { num:"יא", words:[["וַיְסַפֵּר","and-he-also-rehearsed"],["לָהֶם","to-them"],["הָמָן","Haman"],["אֶת־כְּבוֹד","[ACC]-the-glory-of"],["עׇשְׁרוֹ","tithe-his"],["וְרֹב","and-most-of"],["בָּנָיו","his-sons"],["וְאֵת","and-[ACC]"],["כׇּל־אֲשֶׁר","all-whose"],["גִּדְּלוֹ","he had made great-him"],["הַמֶּלֶךְ","the-king"],["וְאֵת","and-[ACC]"],["אֲשֶׁר","which"],["נִשְּׂאוֹ","he had exalted-him"],["עַל־הַשָּׂרִים","upon-the-princes"],["וְעַבְדֵי","and-the-servants-of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"יב", words:[["וַיֹּאמֶר","and-said"],["הָמָן","Haman"],["אַף","yea"],["לֹא־הֵבִיאָה","not-causes"],["אֶסְתֵּר","Esther"],["הַמַּלְכָּה","the-queen"],["עִם־הַמֶּלֶךְ","with-the-king"],["אֶל־הַמִּשְׁתֶּה","to-the-feast"],["אֲשֶׁר־עָשָׂתָה","whose-she had prepared"],["כִּי","because"],["אִם־אוֹתִי","[compound]-me"],["וְגַם־לְמָחָר","and-also-on-the-morrow"],["אֲנִי","I"],["קָרוּא־לָהּ","am invited-it"],["עִם־הַמֶּלֶךְ","with-the-king"],["׃",""]] },
  { num:"יג", words:[["וְכׇל־זֶה","and-all-this"],["אֵינֶנּוּ","it-is-not"],["שֹׁוֶה","is appropriate"],["לִי","to-me"],["בְּכׇל־עֵת","in-all-time"],["אֲשֶׁר","which"],["אֲנִי","I"],["רֹאֶה","I-perceive"],["אֶת־מׇרְדֳּכַי","[ACC]-Mordecai"],["הַיְּהוּדִי","the-Jew"],["יוֹשֵׁב","sitting"],["בְּשַׁעַר","in-the gate of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"יד", words:[["וַתֹּאמֶר","and-said"],["לוֹ","him"],["זֶרֶשׁ","Zeresh"],["אִשְׁתּוֹ","his-wife"],["וְכׇל־אֹהֲבָיו","and-all-friends-his"],["יַעֲשׂוּ־עֵץ","shall-yield-a-tree"],["גָּבֹהַּ","height"],["חֲמִשִּׁים","fifty"],["אַמָּה","Mh"],["וּבַבֹּקֶר","and-in-the-morning"],["אֱמֹר","say!"],["לַמֶּלֶךְ","the-king"],["וְיִתְלוּ","so-people may hang"],["אֶת־מׇרְדֳּכַי","[ACC]-Mordecai"],["עָלָיו","upon-him"],["וּבֹא־עִם־הַמֶּלֶךְ","and-go-with-the-king"],["אֶל־הַמִּשְׁתֶּה","to-the-feast"],["שָׂמֵחַ","happy"],["וַיִּיטַב","and-it was good"],["הַדָּבָר","the-thing"],["לִפְנֵי","before"],["הָמָן","Haman"],["וַיַּעַשׂ","and-did"],["הָעֵץ","the-tree"],["׃",""]] },
];
renderVerseSet(est_ch5Verses, 'est-ch5-verses');

var est_ch6Verses = [
  { num:"א", words:[["בַּלַּיְלָה","in-the-night"],["הַהוּא","that"],["נָדְדָה","fled"],["שְׁנַת","year-of"],["הַמֶּלֶךְ","the-king"],["וַיֹּאמֶר","and-said"],["לְהָבִיא","to-bring-about"],["אֶת־סֵפֶר","book-of"],["הַזִּכְרֹנוֹת","the-reminders"],["דִּבְרֵי","account-of"],["הַיָּמִים","the-days"],["וַיִּהְיוּ","and-they-were"],["נִקְרָאִים","are-called"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ב", words:[["וַיִּמָּצֵא","and-it was found"],["כָתוּב","written"],["אֲשֶׁר","which"],["הִגִּיד","declared"],["מׇרְדֳּכַי","Mordecai"],["עַל־בִּגְתָנָא","upon-Bigthana"],["וָתֶרֶשׁ","and-Teresh"],["שְׁנֵי","two"],["סָרִיסֵי","the eunuchs of"],["הַמֶּלֶךְ","the-king"],["מִשֹּׁמְרֵי","from-the guards of"],["הַסַּף","the-threshold"],["אֲשֶׁר","which"],["בִּקְשׁוּ","sought"],["לִשְׁלֹחַ","lay"],["יָד","hands"],["בַּמֶּלֶךְ","in-the-reigned"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["׃",""]] },
  { num:"ג", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["מַה־נַּעֲשָׂה","what-has it been done"],["יְקָר","the honor of"],["וּגְדוּלָּה","and-greatness"],["לְמׇרְדֳּכַי","to-Mordecai"],["עַל־זֶה","upon-this"],["וַיֹּאמְרוּ","and-they-said"],["נַעֲרֵי","the young men of"],["הַמֶּלֶךְ","the-king"],["מְשָׁרְתָיו","servants-his"],["לֹא־נַעֲשָׂה","not-was-done"],["עִמּוֹ","with-him"],["דָּבָר","things"],["׃",""]] },
  { num:"ד", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["מִי","who"],["בֶחָצֵר","is in the-court"],["וְהָמָן","and-Haman"],["בָּא","came"],["לַחֲצַר","to-the court of"],["בֵּית־הַמֶּלֶךְ","house-of-the-king"],["הַחִיצוֹנָה","the-outer"],["לֵאמֹר","saying"],["לַמֶּלֶךְ","the-king"],["לִתְלוֹת","to-hang"],["אֶת־מׇרְדֳּכַי","[ACC]-Mordecai"],["עַל־הָעֵץ","upon-the-tree"],["אֲשֶׁר־הֵכִין","whose-prepared"],["לוֹ","him"],["׃",""]] },
  { num:"ה", words:[["וַיֹּאמְרוּ","and-they-said"],["נַעֲרֵי","the young men of"],["הַמֶּלֶךְ","the-king"],["אֵלָיו","to-him"],["הִנֵּה","behold"],["הָמָן","Haman"],["עֹמֵד","standing"],["בֶּחָצֵר","in the-court"],["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["יָבוֹא","shall-come"],["׃",""]] },
  { num:"ו", words:[["וַיָּבוֹא","and-he came"],["הָמָן","Haman"],["וַיֹּאמֶר","and-said"],["לוֹ","him"],["הַמֶּלֶךְ","the-king"],["מַה־לַּעֲשׂוֹת","what-more-could-be-done"],["בָּאִישׁ","the-man"],["אֲשֶׁר","which"],["הַמֶּלֶךְ","the-king"],["חָפֵץ","desire/precious"],["בִּיקָרוֹ","in-honor-his"],["וַיֹּאמֶר","and-said"],["הָמָן","Haman"],["בְּלִבּוֹ","in-his-heart"],["לְמִי","to-whom"],["יַחְפֹּץ","delights"],["הַמֶּלֶךְ","the-king"],["לַעֲשׂוֹת","to-do"],["יְקָר","the honor of"],["יוֹתֵר","more"],["מִמֶּנִּי","from-me"],["׃",""]] },
  { num:"ז", words:[["וַיֹּאמֶר","and-said"],["הָמָן","Haman"],["אֶל־הַמֶּלֶךְ","unto-the-king"],["אִישׁ","man-of"],["אֲשֶׁר","which"],["הַמֶּלֶךְ","the-king"],["חָפֵץ","desire/precious"],["בִּיקָרוֹ","in-honor-his"],["׃",""]] },
  { num:"ח", words:[["יָבִיאוּ","they-shall-bring"],["לְבוּשׁ","clothing"],["מַלְכוּת","the-reign-of"],["אֲשֶׁר","which"],["לָבַשׁ־בּוֹ","he wore-against-him"],["הַמֶּלֶךְ","the-king"],["וְסוּס","and-horses"],["אֲשֶׁר","which"],["רָכַב","he has ridden"],["עָלָיו","upon-him"],["הַמֶּלֶךְ","the-king"],["וַאֲשֶׁר","and-whom"],["נִתַּן","was-given"],["כֶּתֶר","a crown of"],["מַלְכוּת","the-reign-of"],["בְּרֹאשׁוֹ","at-its-head"],["׃",""]] },
  { num:"ט", words:[["וְנָתוֹן","and-given"],["הַלְּבוּשׁ","the-clothing"],["וְהַסּוּס","and-the-horse"],["עַל־יַד־אִישׁ","upon-hand-of-man-of"],["מִשָּׂרֵי","from-my-princes"],["הַמֶּלֶךְ","the-king"],["הַפַּרְתְּמִים","the-nobles"],["וְהִלְבִּישׁוּ","and-they will clothe"],["אֶת־הָאִישׁ","[ACC]-the-man"],["אֲשֶׁר","which"],["הַמֶּלֶךְ","the-king"],["חָפֵץ","desire/precious"],["בִּיקָרוֹ","in-honor-his"],["וְהִרְכִּיבֻהוּ","and-they will make ride-him"],["עַל־הַסּוּס","upon-the-horses"],["בִּרְחוֹב","in-the open square of"],["הָעִיר","the-city"],["וְקָרְאוּ","and-called-upon"],["לְפָנָיו","before-him"],["כָּכָה","thus"],["יֵעָשֶׂה","shall-be-done"],["לָאִישׁ","be-unto-that-man"],["אֲשֶׁר","which"],["הַמֶּלֶךְ","the-king"],["חָפֵץ","desire/precious"],["בִּיקָרוֹ","in-honor-his"],["׃",""]] },
  { num:"י", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["לְהָמָן","to-Haman"],["מַהֵר","Maher-"],["קַח","take"],["אֶת־הַלְּבוּשׁ","[ACC]-the-clothing"],["וְאֶת־הַסּוּס","and-[ACC]-the-horses"],["כַּאֲשֶׁר","when/as"],["דִּבַּרְתָּ","thou-hast-spoken"],["וַעֲשֵׂה־כֵן","and-do-thus"],["לְמׇרְדֳּכַי","to-Mordecai"],["הַיְּהוּדִי","the-Jew"],["הַיּוֹשֵׁב","the-one-sitting"],["בְּשַׁעַר","in-the gate of"],["הַמֶּלֶךְ","the-king"],["אַל־תַּפֵּל","do-not-you make fall"],["דָּבָר","things"],["מִכֹּל","of-all"],["אֲשֶׁר","which"],["דִּבַּרְתָּ","thou-hast-spoken"],["׃",""]] },
  { num:"יא", words:[["וַיִּקַּח","and-took"],["הָמָן","Haman"],["אֶת־הַלְּבוּשׁ","[ACC]-the-clothing"],["וְאֶת־הַסּוּס","and-[ACC]-the-horses"],["וַיַּלְבֵּשׁ","and-he clothed"],["אֶת־מׇרְדֳּכָי","[ACC]-Mordecai"],["וַיַּרְכִּיבֵהוּ","and-he made ride-him"],["בִּרְחוֹב","in-the open square of"],["הָעִיר","the-city"],["וַיִּקְרָא","and-called"],["לְפָנָיו","before-him"],["כָּכָה","thus"],["יֵעָשֶׂה","shall-be-done"],["לָאִישׁ","be-unto-that-man"],["אֲשֶׁר","which"],["הַמֶּלֶךְ","the-king"],["חָפֵץ","desire/precious"],["בִּיקָרוֹ","in-honor-his"],["׃",""]] },
  { num:"יב", words:[["וַיָּשׇׁב","and-he will turn"],["מׇרְדֳּכַי","Mordecai"],["אֶל־שַׁעַר","to-gate-of"],["הַמֶּלֶךְ","the-king"],["וְהָמָן","and-Haman"],["נִדְחַף","he hurried himself"],["אֶל־בֵּיתוֹ","to-his-house"],["אָבֵל","mourning"],["וַחֲפוּי","and-covered of"],["רֹאשׁ","head-of"],["׃",""]] },
  { num:"יג", words:[["וַיְסַפֵּר","and-he-also-rehearsed"],["הָמָן","Haman"],["לְזֶרֶשׁ","to-Zeresh"],["אִשְׁתּוֹ","his-wife"],["וּלְכׇל־אֹהֲבָיו","and-to-all-friends-his"],["אֵת","[ACC]"],["כׇּל־אֲשֶׁר","all-whose"],["קָרָהוּ","it had happened to-him"],["וַיֹּאמְרוּ","and-they-said"],["לוֹ","him"],["חֲכָמָיו","their-wise"],["וְזֶרֶשׁ","and-Zeresh"],["אִשְׁתּוֹ","his-wife"],["אִם","[compound]"],["מִזֶּרַע","from-seed-of"],["הַיְּהוּדִים","the-Jews"],["מׇרְדֳּכַי","Mordecai"],["אֲשֶׁר","which"],["הַחִלּוֹתָ","you have begun"],["לִנְפֹּל","to-fall-upon"],["לְפָנָיו","before-him"],["לֹא־תוּכַל","not-can"],["לוֹ","him"],["כִּי־נָפוֹל","because-fallen"],["תִּפּוֹל","tumble"],["לְפָנָיו","before-him"],["׃",""]] },
  { num:"יד", words:[["עוֹדָם","are-yet"],["מְדַבְּרִים","we-speak"],["עִמּוֹ","with-him"],["וְסָרִיסֵי","and-the eunuchs of"],["הַמֶּלֶךְ","the-king"],["הִגִּיעוּ","they-arrived"],["וַיַּבְהִלוּ","and-they made haste"],["לְהָבִיא","to-bring-about"],["אֶת־הָמָן","[ACC]-Haman"],["אֶל־הַמִּשְׁתֶּה","to-the-feast"],["אֲשֶׁר־עָשְׂתָה","whose-did(f)"],["אֶסְתֵּר","Esther"],["׃",""]] },
];
renderVerseSet(est_ch6Verses, 'est-ch6-verses');

var est_ch7Verses = [
  { num:"א", words:[["וַיָּבֹא","and-came"],["הַמֶּלֶךְ","the-king"],["וְהָמָן","and-Haman"],["לִשְׁתּוֹת","to-drink"],["עִם־אֶסְתֵּר","with-Esther"],["הַמַּלְכָּה","the-queen"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["לְאֶסְתֵּר","to-Esther"],["גַּם","also"],["בַּיּוֹם","in-the-day"],["הַשֵּׁנִי","the-second"],["בְּמִשְׁתֵּה","at-the feast of"],["הַיַּיִן","the-wine"],["מַה־שְּׁאֵלָתֵךְ","what-is petition-your"],["אֶסְתֵּר","Esther"],["הַמַּלְכָּה","the-queen"],["וְתִנָּתֵן","so-it may be given"],["לָךְ","[compound]"],["וּמַה־בַּקָּשָׁתֵךְ","the-yea-and-what-is request-your"],["עַד־חֲצִי","until-half"],["הַמַּלְכוּת","the-kingdom"],["וְתֵעָשׂ","and-it may be done"],["׃",""]] },
  { num:"ג", words:[["וַתַּעַן","and-she answered"],["אֶסְתֵּר","Esther"],["הַמַּלְכָּה","the-queen"],["וַתֹּאמַר","and-she said"],["אִם־מָצָאתִי","[compound]-I-found"],["חֵן","favor"],["בְּעֵינֶיךָ","in-your-eyes"],["הַמֶּלֶךְ","the-king"],["וְאִם־עַל־הַמֶּלֶךְ","and-if-upon-the-king"],["טוֹב","good"],["תִּנָּתֶן־לִי","let it be given-to-me"],["נַפְשִׁי","my-life"],["בִּשְׁאֵלָתִי","for-petition-my"],["וְעַמִּי","and-my-people"],["בְּבַקָּשָׁתִי","for-request-my"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["נִמְכַּרְנוּ","we have been sold"],["אֲנִי","I"],["וְעַמִּי","and-my-people"],["לְהַשְׁמִיד","to-destroy"],["לַהֲרוֹג","to-kill"],["וּלְאַבֵּד","and-to-destroy"],["וְאִלּוּ","and-if"],["לַעֲבָדִים","for-servants"],["וְלִשְׁפָחוֹת","and-for-handmaids"],["נִמְכַּרְנוּ","we have been sold"],["הֶחֱרַשְׁתִּי","I kept quiet"],["כִּי","because"],["אֵין","there-is-no"],["הַצָּר","the-narrow/enemy"],["שֹׁוֶה","is appropriate"],["בְּנֵזֶק","for-the injury of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ה", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["וַיֹּאמֶר","and-said"],["לְאֶסְתֵּר","to-Esther"],["הַמַּלְכָּה","the-queen"],["מִי","who"],["הוּא","it-is"],["זֶה","this"],["וְאֵי־זֶה","and-where?-this"],["הוּא","it-is"],["אֲשֶׁר־מְלָאוֹ","whose-it has filled-him"],["לִבּוֹ","his-heart"],["לַעֲשׂוֹת","to-do"],["כֵּן","thus"],["׃",""]] },
  { num:"ו", words:[["וַתֹּאמֶר","and-said"],["אֶסְתֵּר","Esther"],["אִישׁ","man-of"],["צַר","narrow/enemy"],["וְאוֹיֵב","and-is-an-enemy"],["הָמָן","Haman"],["הָרָע","that-which-is-evil"],["הַזֶּה","this"],["וְהָמָן","and-Haman"],["נִבְעַת","he was terrified"],["מִלִּפְנֵי","from-presence-of"],["הַמֶּלֶךְ","the-king"],["וְהַמַּלְכָּה","and-the-queen"],["׃",""]] },
  { num:"ז", words:[["וְהַמֶּלֶךְ","and-the-king"],["קָם","arose"],["בַּחֲמָתוֹ","in-his-wrath"],["מִמִּשְׁתֵּה","from-the feast of"],["הַיַּיִן","the-wine"],["אֶל־גִּנַּת","to-the garden of"],["הַבִּיתָן","the-palace"],["וְהָמָן","and-Haman"],["עָמַד","stood"],["לְבַקֵּשׁ","to-seek"],["עַל־נַפְשׁוֹ","upon-his-soul"],["מֵאֶסְתֵּר","from-Esther"],["הַמַּלְכָּה","the-queen"],["כִּי","because"],["רָאָה","he-saw"],["כִּי־כָלְתָה","because-finished"],["אֵלָיו","to-him"],["הָרָעָה","the-evil"],["מֵאֵת","from"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ח", words:[["וְהַמֶּלֶךְ","and-the-king"],["שָׁב","returned/repented"],["מִגִּנַּת","from-the garden of"],["הַבִּיתָן","the-palace"],["אֶל־בֵּית","to-the-house-of"],["מִשְׁתֵּה","a feast of"],["הַיַּיִן","the-wine"],["וְהָמָן","and-Haman"],["נֹפֵל","flowing"],["עַל־הַמִּטָּה","upon-the-bed"],["אֲשֶׁר","which"],["אֶסְתֵּר","Esther"],["עָלֶיהָ","upon-it"],["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["הֲגַם","¿-also"],["לִכְבּוֹשׁ","gain-power-over"],["אֶת־הַמַּלְכָּה","[ACC]-the-queen"],["עִמִּי","with-me"],["בַּבָּיִת","in the-house"],["הַדָּבָר","the-thing"],["יָצָא","he-went-forth"],["מִפִּי","from-mouth-of"],["הַמֶּלֶךְ","the-king"],["וּפְנֵי","and-the-faces-of"],["הָמָן","Haman"],["חָפוּ","they covered"],["׃",""]] },
  { num:"ט", words:[["וַיֹּאמֶר","and-said"],["חַרְבוֹנָה","Harbona"],["אֶחָד","one"],["מִן־הַסָּרִיסִים","from-the-court-officials"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["גַּם","also"],["הִנֵּה־הָעֵץ","behold-the-tree"],["אֲשֶׁר־עָשָׂה","which-did"],["הָמָן","Haman"],["לְמׇרְדֳּכַי","to-Mordecai"],["אֲשֶׁר","which"],["דִּבֶּר־טוֹב","spoke-good"],["עַל־הַמֶּלֶךְ","upon-the-king"],["עֹמֵד","standing"],["בְּבֵית","in-house-of"],["הָמָן","Haman"],["גָּבֹהַּ","height"],["חֲמִשִּׁים","fifty"],["אַמָּה","Mh"],["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["תְּלֻהוּ","hang-him"],["עָלָיו","upon-him"],["׃",""]] },
  { num:"י", words:[["וַיִּתְלוּ","and-they hanged them"],["אֶת־הָמָן","[ACC]-Haman"],["עַל־הָעֵץ","upon-the-tree"],["אֲשֶׁר־הֵכִין","whose-prepared"],["לְמׇרְדֳּכָי","for-Mordecai"],["וַחֲמַת","and-wrath-of"],["הַמֶּלֶךְ","the-king"],["שָׁכָכָה","it subsided"],["׃",""]] },
];
renderVerseSet(est_ch7Verses, 'est-ch7-verses');

var est_ch8Verses = [
  { num:"א", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["נָתַן","was-given"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["לְאֶסְתֵּר","to-Esther"],["הַמַּלְכָּה","the-queen"],["אֶת־בֵּית","[ACC]-house-of"],["הָמָן","Haman"],["צֹרֵר","the opposer of"],["(היהודיים)","(the-Jews)"],["[הַיְּהוּדִים]","the-Jews"],["וּמׇרְדֳּכַי","and-Mordecai"],["בָּא","came"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["כִּי־הִגִּידָה","because-she told"],["אֶסְתֵּר","Esther"],["מַה","what"],["הוּא־לָהּ","it-is-it"],["׃",""]] },
  { num:"ב", words:[["וַיָּסַר","for-he-put-down"],["הַמֶּלֶךְ","the-king"],["אֶת־טַבַּעְתּוֹ","[ACC]-signet-ring-his"],["אֲשֶׁר","which"],["הֶעֱבִיר","he brought in"],["מֵהָמָן","from-Haman"],["וַיִּתְּנָהּ","and-he gave-it"],["לְמׇרְדֳּכָי","for-Mordecai"],["וַתָּשֶׂם","and-she put"],["אֶסְתֵּר","Esther"],["אֶת־מׇרְדֳּכַי","[ACC]-Mordecai"],["עַל־בֵּית","to-the-house-of"],["הָמָן","Haman"],["׃",""]] },
  { num:"ג", words:[["וַתּוֹסֶף","and-it repeated"],["אֶסְתֵּר","Esther"],["וַתְּדַבֵּר","and-she-spoke"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["וַתִּפֹּל","and-she-shall-fall"],["לִפְנֵי","before"],["רַגְלָיו","His-feet"],["וַתֵּבְךְּ","and-she wept"],["וַתִּתְחַנֶּן־לוֹ","and-she sought favor-him"],["לְהַעֲבִיר","cause-to-pass"],["אֶת־רָעַת","[ACC]-the evil of"],["הָמָן","Haman"],["הָאֲגָגִי","the-Agagite"],["וְאֵת","and-[ACC]"],["מַחֲשַׁבְתּוֹ","plan-his"],["אֲשֶׁר","which"],["חָשַׁב","he-thought"],["עַל־הַיְּהוּדִים","upon-the-Jews"],["׃",""]] },
  { num:"ד", words:[["וַיּוֹשֶׁט","and-he extended"],["הַמֶּלֶךְ","the-king"],["לְאֶסְתֵּר","to-Esther"],["אֵת","[ACC]"],["שַׁרְבִט","the scepter of"],["הַזָּהָב","the-gold"],["וַתָּקׇם","and-you fulfilled"],["אֶסְתֵּר","Esther"],["וַתַּעֲמֹד","and-shall-stand"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ה", words:[["וַתֹּאמֶר","and-said"],["אִם־עַל־הַמֶּלֶךְ","[compound]-upon-the-king"],["טוֹב","good"],["וְאִם־מָצָאתִי","and-if-I-found"],["חֵן","favor"],["לְפָנָיו","before-him"],["וְכָשֵׁר","and-it is proper"],["הַדָּבָר","the-thing"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["וְטוֹבָה","and-am good"],["אֲנִי","I"],["בְּעֵינָיו","in-His-eyes"],["יִכָּתֵב","be-engraved"],["לְהָשִׁיב","to-he-restored"],["אֶת־הַסְּפָרִים","[ACC]-the-records"],["מַחֲשֶׁבֶת","fine"],["הָמָן","Haman"],["בֶּן־הַמְּדָתָא","the-son-of-Hammedatha"],["הָאֲגָגִי","the-Agagite"],["אֲשֶׁר","which"],["כָּתַב","he-wrote"],["לְאַבֵּד","to-lose"],["אֶת־הַיְּהוּדִים","[ACC]-the-Jews"],["אֲשֶׁר","which"],["בְּכׇל־מְדִינוֹת","in-all-the provinces of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ו", words:[["כִּי","because"],["אֵיכָכָה","how?"],["אוּכַל","I-could"],["וְרָאִיתִי","and-seen"],["בָּרָעָה","on the-evil"],["אֲשֶׁר־יִמְצָא","whose-shall-find"],["אֶת־עַמִּי","[ACC]-my-people"],["וְאֵיכָכָה","and-how?"],["אוּכַל","I-could"],["וְרָאִיתִי","and-seen"],["בְּאׇבְדַן","in-perishing"],["מוֹלַדְתִּי","kindred-my"],["׃",""]] },
  { num:"ז", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרֹשׁ","Ahasuerus"],["לְאֶסְתֵּר","to-Esther"],["הַמַּלְכָּה","the-queen"],["וּלְמׇרְדֳּכַי","and-to-Mordecai"],["הַיְּהוּדִי","the-Jew"],["הִנֵּה","behold"],["בֵית־הָמָן","house-of-Haman"],["נָתַתִּי","I-gave"],["לְאֶסְתֵּר","to-Esther"],["וְאֹתוֹ","and-him"],["תָּלוּ","they have hanged"],["עַל־הָעֵץ","upon-the-tree"],["עַל","upon"],["אֲשֶׁר־שָׁלַח","whose-sent"],["יָדוֹ","his-hand"],["[בַּיְּהוּדִים]","on the-Jews"],["׃",""]] },
  { num:"ח", words:[["וְאַתֶּם","and-will-you"],["כִּתְבוּ","they-wrote"],["עַל־הַיְּהוּדִים","upon-the-Jews"],["כַּטּוֹב","as-the-seems-you-good"],["בְּעֵינֵיכֶם","in-view-your"],["בְּשֵׁם","by-name"],["הַמֶּלֶךְ","the-king"],["וְחִתְמוּ","and-seal it"],["בְּטַבַּעַת","with-the signet-ring of"],["הַמֶּלֶךְ","the-king"],["כִּי־כְתָב","because-is writing"],["אֲשֶׁר־נִכְתָּב","whose-has-been-written"],["בְּשֵׁם־הַמֶּלֶךְ","by-name-the-king"],["וְנַחְתּוֹם","and-it is sealed"],["בְּטַבַּעַת","with-the signet-ring of"],["הַמֶּלֶךְ","the-king"],["אֵין","there-is-no"],["לְהָשִׁיב","to-he-restored"],["׃",""]] },
  { num:"ט", words:[["וַיִּקָּרְאוּ","and-they-were-called"],["סֹפְרֵי־הַמֶּלֶךְ","the scribes of-the-king"],["בָּעֵת־הַהִיא","at-the-time-that"],["בַּחֹדֶשׁ","in-the-month"],["הַשְּׁלִישִׁי","the-third"],["הוּא־חֹדֶשׁ","it-is-a month of"],["סִיוָן","Sivan"],["בִּשְׁלוֹשָׁה","was among-three"],["וְעֶשְׂרִים","and-twenty"],["בּוֹ","against-him"],["וַיִּכָּתֵב","and-written-was-it"],["כְּכׇל־אֲשֶׁר־צִוָּה","as-all-whose-commanded"],["מׇרְדֳּכַי","Mordecai"],["אֶל־הַיְּהוּדִים","unto-the-Jews"],["וְאֶל","and"],["הָאֲחַשְׁדַּרְפְּנִים־וְהַפַּחוֹת","the-satraps-and-the-governors"],["וְשָׂרֵי","and-captains-of"],["הַמְּדִינוֹת","the-provinces"],["אֲשֶׁר","which"],["מֵהֹדּוּ","from-India"],["וְעַד־כּוּשׁ","and-unto-Cush"],["שֶׁבַע","seven"],["וְעֶשְׂרִים","and-twenty"],["וּמֵאָה","and-one hundred"],["מְדִינָה","provinces"],["מְדִינָה","provinces"],["וּמְדִינָה","and-province"],["כִּכְתָבָהּ","according to-writing-its"],["וְעַם","and-the-people-of"],["וָעָם","and-people"],["כִּלְשֹׁנוֹ","according to-language-its"],["וְאֶל־הַיְּהוּדִים","and-the-Jews"],["כִּכְתָבָם","according to-writing-their"],["וְכִלְשׁוֹנָם","and-according to-language-their"],["׃",""]] },
  { num:"י", words:[["וַיִּכְתֹּב","and-he-wrote"],["בְּשֵׁם","by-name"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרֹשׁ","Ahasuerus"],["וַיַּחְתֹּם","having-sealed"],["בְּטַבַּעַת","with-the signet-ring of"],["הַמֶּלֶךְ","the-king"],["וַיִּשְׁלַח","and-sent"],["סְפָרִים","records"],["בְּיַד","in-hand-of"],["הָרָצִים","the-runners"],["בַּסּוּסִים","for the-horses"],["רֹכְבֵי","O riders of"],["הָרֶכֶשׁ","the-steeds"],["הָאֲחַשְׁתְּרָנִים","the-royal"],["בְּנֵי","the-sons-of"],["הָרַמָּכִים","the-mares"],["׃",""]] },
  { num:"יא", words:[["אֲשֶׁר","which"],["נָתַן","was-given"],["הַמֶּלֶךְ","the-king"],["לַיְּהוּדִים","to-the-Jews"],["אֲשֶׁר","which"],["בְּכׇל־עִיר־וָעִיר","in-all-city-of-and-a city"],["לְהִקָּהֵל","to-gather"],["וְלַעֲמֹד","and-to-stand"],["עַל־נַפְשָׁם","upon-their-soul"],["לְהַשְׁמִיד","to-destroy"],["אשכנז","Ashkenaz"],["לַהֲרֹג)","to-kill"],["וּלְאַבֵּד","and-to-destroy"],["אֶת־כׇּל־חֵיל","[ACC]-all-the army of"],["עַם","people"],["וּמְדִינָה","and-province"],["הַצָּרִים","the-which-attacks"],["אֹתָם","them"],["טַף","little ones"],["וְנָשִׁים","and-carrying"],["וּשְׁלָלָם","and-may-be-their-prey"],["לָבוֹז","to-take as plunder"],["׃",""]] },
  { num:"יב", words:[["בְּיוֹם","in-day-of"],["אֶחָד","one"],["בְּכׇל־מְדִינוֹת","in-all-the provinces of"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["בִּשְׁלוֹשָׁה","was among-three"],["עָשָׂר","[compound]"],["לְחֹדֶשׁ","to-month"],["שְׁנֵים־עָשָׂר","two-[compound]"],["הוּא־חֹדֶשׁ","it-is-a month of"],["אֲדָר","Adar"],["׃",""]] },
  { num:"יג", words:[["פַּתְשֶׁגֶן","copy of"],["הַכְּתָב","the-writing"],["לְהִנָּתֵן","was to-be given"],["דָּת","law"],["בְּכׇל־מְדִינָה","in-all-provinces"],["וּמְדִינָה","and-province"],["גָּלוּי","open"],["לְכׇל־הָעַמִּים","to-all-the-people"],["וְלִהְיוֹת","and-to-be"],["(היהודיים)","(the-Jews)"],["[הַיְּהוּדִים]","the-Jews"],["(עתודים)","goats"],["[עֲתִידִים]","are-about"],["לַיּוֹם","that-the-day"],["הַזֶּה","this"],["לְהִנָּקֵם","to-take-vengeance"],["מֵאֹיְבֵיהֶם","from-enemies-their"],["׃",""]] },
  { num:"יד", words:[["הָרָצִים","the-runners"],["רֹכְבֵי","O riders of"],["הָרֶכֶשׁ","the-steeds"],["הָאֲחַשְׁתְּרָנִים","the-royal"],["יָצְאוּ","went-forth"],["מְבֹהָלִים","hastened"],["וּדְחוּפִים","and-hurried"],["בִּדְבַר","of-the-promise-of"],["הַמֶּלֶךְ","the-king"],["וְהַדָּת","and-the-law"],["נִתְּנָה","was-given(f)"],["בְּשׁוּשַׁן","in-Susa"],["הַבִּירָה","the-temple"],["׃",""]] },
  { num:"טו", words:[["וּמׇרְדֳּכַי","and-Mordecai"],["יָצָא","he-went-forth"],["מִלִּפְנֵי","from-presence-of"],["הַמֶּלֶךְ","the-king"],["בִּלְבוּשׁ","in-clothing of"],["מַלְכוּת","the-reign-of"],["תְּכֵלֶת","violet stuff"],["וָחוּר","and-white cloth"],["וַעֲטֶרֶת","and-a crown of"],["זָהָב","gold"],["גְּדוֹלָה","great"],["וְתַכְרִיךְ","and-a robe of"],["בּוּץ","fine linen"],["וְאַרְגָּמָן","and-scarlets"],["וְהָעִיר","and-the-city"],["שׁוּשָׁן","Susa"],["צָהֲלָה","it shouted for joy"],["וְשָׂמֵחָה","and-it rejoiced"],["׃",""]] },
  { num:"טז", words:[["לַיְּהוּדִים","to-the-Jews"],["הָיְתָה","was"],["אוֹרָה","light"],["וְשִׂמְחָה","and-happiness"],["וְשָׂשֹׂן","and-joy"],["וִיקָר","and-honor"],["׃",""]] },
  { num:"יז", words:[["וּבְכׇל־מְדִינָה","and-in-all-provinces"],["וּמְדִינָה","and-province"],["וּבְכׇל־עִיר","and-in-all-city-of"],["וָעִיר","and-a city"],["מְקוֹם","the-place"],["אֲשֶׁר","which"],["דְּבַר־הַמֶּלֶךְ","word-of-the-king"],["וְדָתוֹ","and-orders-his"],["מַגִּיעַ","was reaching"],["שִׂמְחָה","joy"],["וְשָׂשׂוֹן","and-joy"],["לַיְּהוּדִים","to-the-Jews"],["מִשְׁתֶּה","feast"],["וְיוֹם","and-day"],["טוֹב","good"],["וְרַבִּים","and-many"],["מֵעַמֵּי","from-the peoples of"],["הָאָרֶץ","the-earth"],["מִתְיַהֲדִים","were becoming Jews"],["כִּי־נָפַל","that-fell"],["פַּחַד־הַיְּהוּדִים","dread-the-Jews"],["עֲלֵיהֶם","against-them"],["׃",""]] },
];
renderVerseSet(est_ch8Verses, 'est-ch8-verses');

var est_ch9Verses = [
  { num:"א", words:[["וּבִשְׁנֵים","and-in-two plus"],["עָשָׂר","[compound]"],["חֹדֶשׁ","a month of"],["הוּא־חֹדֶשׁ","it-is-a month of"],["אֲדָר","Adar"],["בִּשְׁלוֹשָׁה","was among-three"],["עָשָׂר","[compound]"],["יוֹם","day"],["בּוֹ","against-him"],["אֲשֶׁר","which"],["הִגִּיעַ","come-has"],["דְּבַר־הַמֶּלֶךְ","word-of-the-king"],["וְדָתוֹ","and-orders-his"],["לְהֵעָשׂוֹת","to-be-acted-upon"],["בַּיּוֹם","in-the-day"],["אֲשֶׁר","which"],["שִׂבְּרוּ","they had hoped"],["אֹיְבֵי","the enemies of"],["הַיְּהוּדִים","the-Jews"],["לִשְׁלוֹט","to-domineer"],["בָּהֶם","in-them"],["וְנַהֲפוֹךְ","and-it was reversed"],["הוּא","it-is"],["אֲשֶׁר","which"],["יִשְׁלְטוּ","they domineered"],["הַיְּהוּדִים","the-Jews"],["הֵמָּה","they-are"],["בְּשֹׂנְאֵיהֶם","over-those who hated-them"],["׃",""]] },
  { num:"ב", words:[["נִקְהֲלוּ","gathered"],["הַיְּהוּדִים","the-Jews"],["בְּעָרֵיהֶם","in-their-cities"],["בְּכׇל־מְדִינוֹת","in-all-the provinces of"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["לִשְׁלֹחַ","lay"],["יָד","hands"],["בִּמְבַקְשֵׁי","on-those seeking"],["רָעָתָם","their-wickedness"],["וְאִישׁ","and-the-man-of"],["לֹא־עָמַד","not-stood"],["אשכנז","Ashkenaz"],["בִּפְנֵיהֶם)","in-faces-their"],["כִּי־נָפַל","that-fell"],["פַּחְדָּם","their-fears"],["עַל־כׇּל־הָעַמִּים","upon-all-the-people"],["׃",""]] },
  { num:"ג", words:[["וְכׇל־שָׂרֵי","and-all-captains-of"],["הַמְּדִינוֹת","the-provinces"],["וְהָאֲחַשְׁדַּרְפְּנִים","and-the-satraps"],["וְהַפַּחוֹת","and-the-governors"],["וְעֹשֵׂי","and-those-doing"],["הַמְּלָאכָה","the-task"],["אֲשֶׁר","which"],["לַמֶּלֶךְ","the-king"],["מְנַשְּׂאִים","were supporting"],["אֶת־הַיְּהוּדִים","[ACC]-the-Jews"],["כִּי־נָפַל","that-fell"],["פַּחַד־מׇרְדֳּכַי","dread-Mordecai"],["עֲלֵיהֶם","against-them"],["׃",""]] },
  { num:"ד", words:[["כִּי־גָדוֹל","for-great-is"],["מׇרְדֳּכַי","Mordecai"],["בְּבֵית","in-house-of"],["הַמֶּלֶךְ","the-king"],["וְשׇׁמְעוֹ","and-hear-his"],["הוֹלֵךְ","going"],["בְּכׇל־הַמְּדִינוֹת","in-all-the-provinces"],["כִּי־הָאִישׁ","because-the-man"],["מׇרְדֳּכַי","Mordecai"],["הוֹלֵךְ","going"],["וְגָדוֹל","and-great"],["׃",""]] },
  { num:"ה", words:[["וַיַּכּוּ","and-scourged"],["הַיְּהוּדִים","the-Jews"],["בְּכׇל־אֹיְבֵיהֶם","in-all-their-enemies"],["מַכַּת־חֶרֶב","with-a-continual-the-sword-of"],["וְהֶרֶג","and-slaughter"],["וְאַבְדָן","and-destruction"],["וַיַּעֲשׂוּ","and-they-did"],["בְשֹׂנְאֵיהֶם","over-those who hated-them"],["כִּרְצוֹנָם","according-to-their-desires"],["׃",""]] },
  { num:"ו", words:[["וּבְשׁוּשַׁן","and-in-Susa"],["הַבִּירָה","the-temple"],["הָרְגוּ","had-slain"],["הַיְּהוּדִים","the-Jews"],["וְאַבֵּד","and-they destroyed"],["חֲמֵשׁ","five"],["מֵאוֹת","hundred"],["אִישׁ","man-of"],["׃",""]] },
  { num:"ז", words:[["וְאֵת","and-[ACC]"],["פַּרְשַׁנְדָּתָא","Parshandatha"],["וְאֵת","and-[ACC]"],["דַּלְפוֹן","Dalphon"],["וְאֵת","and-[ACC]"],["אַסְפָּתָא","Aspatha"],["׃",""]] },
  { num:"ח", words:[["וְאֵת","and-[ACC]"],["פּוֹרָתָא","Poratha"],["וְאֵת","and-[ACC]"],["אֲדַלְיָא","Adalia"],["וְאֵת","and-[ACC]"],["אֲרִידָתָא","Aridatha"],["׃",""]] },
  { num:"ט", words:[["וְאֵת","and-[ACC]"],["פַּרְמַשְׁתָּא","Parmashta"],["וְאֵת","and-[ACC]"],["אֲרִיסַי","Arisai"],["וְאֵת","and-[ACC]"],["אחרים","other"],["אֲרִידַי","arid"],["וכך","and-thus"],["כתוב","they will write"],["רבות)","many"],["וְאֵת","and-[ACC]"],["וַיְזָתָא","Vaizatha"],["׃",""]] },
  { num:"י", words:[["עֲשֶׂרֶת","ten"],["בְּנֵי","the-sons-of"],["הָמָן","Haman"],["בֶּן־הַמְּדָתָא","the-son-of-Hammedatha"],["צֹרֵר","the opposer of"],["הַיְּהוּדִים","the-Jews"],["הָרָגוּ","they killed"],["וּבַבִּזָּה","and-by-the-plunder"],["לֹא","not"],["שָׁלְחוּ","they-sent-forth"],["אֶת־יָדָם","[ACC]-them"],["׃",""]] },
  { num:"יא", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["בָּא","came"],["מִסְפַּר","so-many-of"],["הַהֲרוּגִים","those-killed"],["בְּשׁוּשַׁן","in-Susa"],["הַבִּירָה","the-temple"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"יב", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["לְאֶסְתֵּר","to-Esther"],["הַמַּלְכָּה","the-queen"],["בְּשׁוּשַׁן","in-Susa"],["הַבִּירָה","the-temple"],["הָרְגוּ","had-slain"],["הַיְּהוּדִים","the-Jews"],["וְאַבֵּד","and-they destroyed"],["חֲמֵשׁ","five"],["מֵאוֹת","hundred"],["אִישׁ","man-of"],["וְאֵת","and-[ACC]"],["עֲשֶׂרֶת","ten"],["בְּנֵי־הָמָן","sons-of-Haman"],["בִּשְׁאָר","with-the rest of"],["מְדִינוֹת","the provinces of"],["הַמֶּלֶךְ","the-king"],["מֶה","what"],["עָשׂוּ","they-did"],["וּמַה־שְּׁאֵלָתֵךְ","yea-and-what-is petition-your"],["וְיִנָּתֵן","and-shall-be-delivered"],["לָךְ","[compound]"],["וּמַה־בַּקָּשָׁתֵךְ","the-yea-and-what-is request-your"],["עוֹד","any-more"],["וְתֵעָשׂ","and-it may be done"],["׃",""]] },
  { num:"יג", words:[["וַתֹּאמֶר","and-said"],["אֶסְתֵּר","Esther"],["אִם־עַל־הַמֶּלֶךְ","[compound]-upon-the-king"],["טוֹב","good"],["יִנָּתֵן","given-be-shall"],["גַּם־מָחָר","also-on-the-morrow"],["לַיְּהוּדִים","to-the-Jews"],["אֲשֶׁר","which"],["בְּשׁוּשָׁן","in-Susa"],["לַעֲשׂוֹת","to-do"],["כְּדָת","according to-the law"],["הַיּוֹם","the-day"],["וְאֵת","and-[ACC]"],["עֲשֶׂרֶת","ten"],["בְּנֵי־הָמָן","sons-of-Haman"],["יִתְלוּ","let them hang"],["עַל־הָעֵץ","upon-the-tree"],["׃",""]] },
  { num:"יד", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["לְהֵעָשׂוֹת","to-be-acted-upon"],["כֵּן","thus"],["וַתִּנָּתֵן","and-it was given"],["דָּת","law"],["בְּשׁוּשָׁן","in-Susa"],["וְאֵת","and-[ACC]"],["עֲשֶׂרֶת","ten"],["בְּנֵי־הָמָן","sons-of-Haman"],["תָּלוּ","they have hanged"],["׃",""]] },
  { num:"טו", words:[["וַיִּקָּהֲלוּ","and-gathered"],["(היהודיים)","(the-Jews)"],["[הַיְּהוּדִים]","the-Jews"],["אֲשֶׁר־בְּשׁוּשָׁן","whose-in-Susa"],["גַּם","also"],["בְּיוֹם","in-day-of"],["אַרְבָּעָה","four"],["עָשָׂר","[compound]"],["לְחֹדֶשׁ","to-month"],["אֲדָר","Adar"],["וַיַּהַרְגוּ","and-slew"],["בְשׁוּשָׁן","in-Susa"],["שְׁלֹשׁ","three"],["מֵאוֹת","hundred"],["אִישׁ","man-of"],["וּבַבִּזָּה","and-by-the-plunder"],["לֹא","not"],["שָׁלְחוּ","they-sent-forth"],["אֶת־יָדָם","[ACC]-them"],["׃",""]] },
  { num:"טז", words:[["וּשְׁאָר","and-remnant"],["הַיְּהוּדִים","the-Jews"],["אֲשֶׁר","which"],["בִּמְדִינוֹת","were in-the provinces of"],["הַמֶּלֶךְ","the-king"],["נִקְהֲלוּ","gathered"],["וְעָמֹד","and-they made a stand"],["עַל־נַפְשָׁם","upon-their-soul"],["וְנוֹחַ","and-they had rest"],["מֵאֹיְבֵיהֶם","from-enemies-their"],["וְהָרוֹג","and-the-kill"],["בְּשֹׂנְאֵיהֶם","over-those who hated-them"],["חֲמִשָּׁה","fifteen"],["וְשִׁבְעִים","and-seventy"],["אָלֶף","thousand"],["וּבַבִּזָּה","and-by-the-plunder"],["לֹא","not"],["שָׁלְחוּ","they-sent-forth"],["אֶת־יָדָם","[ACC]-them"],["׃",""]] },
  { num:"יז", words:[["בְּיוֹם־שְׁלוֹשָׁה","in-day-of-three"],["עָשָׂר","[compound]"],["לְחֹדֶשׁ","to-month"],["אֲדָר","Adar"],["וְנוֹחַ","and-they had rest"],["בְּאַרְבָּעָה","in-four"],["עָשָׂר","[compound]"],["בּוֹ","against-him"],["וְעָשֹׂה","and-they made"],["אֹתוֹ","him"],["יוֹם","day"],["מִשְׁתֶּה","feast"],["וְשִׂמְחָה","and-happiness"],["׃",""]] },
  { num:"יח", words:[["[וְהַיְּהוּדִים]","and-the-Jews"],["אֲשֶׁר־בְּשׁוּשָׁן","whose-in-Susa"],["נִקְהֲלוּ","gathered"],["בִּשְׁלוֹשָׁה","was among-three"],["עָשָׂר","[compound]"],["בּוֹ","against-him"],["וּבְאַרְבָּעָה","and-on-day four-"],["עָשָׂר","[compound]"],["בּוֹ","against-him"],["וְנוֹחַ","and-they had rest"],["בַּחֲמִשָּׁה","for-five"],["עָשָׂר","[compound]"],["בּוֹ","against-him"],["וְעָשֹׂה","and-they made"],["אֹתוֹ","him"],["יוֹם","day"],["מִשְׁתֶּה","feast"],["וְשִׂמְחָה","and-happiness"],["׃",""]] },
  { num:"יט", words:[["עַל־כֵּן","therefore"],["הַיְּהוּדִים","the-Jews"],["[הַפְּרָזִים]","the-rural villagers"],["הַיֹּשְׁבִים","the-inhabitants"],["בְּעָרֵי","in-the cities of"],["הַפְּרָזוֹת","the-open regions"],["עֹשִׂים","which-act"],["אֵת","[ACC]"],["יוֹם","day"],["אַרְבָּעָה","four"],["עָשָׂר","[compound]"],["לְחֹדֶשׁ","to-month"],["אֲדָר","Adar"],["שִׂמְחָה","joy"],["וּמִשְׁתֶּה","and-drink"],["וְיוֹם","and-day"],["טוֹב","good"],["וּמִשְׁלֹחַ","and-presentation"],["מָנוֹת","portions"],["אִישׁ","man-of"],["לְרֵעֵהוּ","another"],["׃",""]] },
  { num:"כ", words:[["וַיִּכְתֹּב","and-he-wrote"],["מׇרְדֳּכַי","Mordecai"],["אֶת־הַדְּבָרִים","[ACC]-the-words"],["הָאֵלֶּה","these"],["וַיִּשְׁלַח","and-sent"],["סְפָרִים","records"],["אֶל־כׇּל־הַיְּהוּדִים","to-all-the-Jews"],["אֲשֶׁר","which"],["בְּכׇל־מְדִינוֹת","in-all-the provinces of"],["הַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["הַקְּרוֹבִים","near-the"],["וְהָרְחוֹקִים","and-the-far"],["׃",""]] },
  { num:"כא", words:[["לְקַיֵּם","to-fulfill"],["עֲלֵיהֶם","against-them"],["לִהְיוֹת","to-be"],["עֹשִׂים","which-act"],["אֵת","[ACC]"],["יוֹם","day"],["אַרְבָּעָה","four"],["עָשָׂר","[compound]"],["לְחֹדֶשׁ","to-month"],["אֲדָר","Adar"],["וְאֵת","and-[ACC]"],["יוֹם־חֲמִשָּׁה","day-fifteen"],["עָשָׂר","[compound]"],["בּוֹ","against-him"],["בְּכׇל־שָׁנָה","in-all-year"],["וְשָׁנָה","and-a year"],["׃",""]] },
  { num:"כב", words:[["כַּיָּמִים","like the-days"],["אֲשֶׁר־נָחוּ","whose-they had rest"],["בָהֶם","among-them"],["הַיְּהוּדִים","the-Jews"],["מֵאֹיְבֵיהֶם","from-enemies-their"],["וְהַחֹדֶשׁ","and-the-month"],["אֲשֶׁר","which"],["נֶהְפַּךְ","it was changed"],["לָהֶם","to-them"],["מִיָּגוֹן","from-sorrow"],["לְשִׂמְחָה","to-their-joy"],["וּמֵאֵבֶל","and-from-mourning"],["לְיוֹם","to-day"],["טוֹב","good"],["לַעֲשׂוֹת","to-do"],["אוֹתָם","them"],["יְמֵי","the-days-of"],["מִשְׁתֶּה","feast"],["וְשִׂמְחָה","and-happiness"],["וּמִשְׁלֹחַ","and-presentation"],["מָנוֹת","portions"],["אִישׁ","man-of"],["לְרֵעֵהוּ","another"],["וּמַתָּנוֹת","and-gifts"],["לָאֶבְיֹנִים","to-the-needy people"],["׃",""]] },
  { num:"כג", words:[["וְקִבֵּל","and-he accepted"],["הַיְּהוּדִים","the-Jews"],["אֵת","[ACC]"],["אֲשֶׁר־הֵחֵלּוּ","whose-began"],["לַעֲשׂוֹת","to-do"],["וְאֵת","and-[ACC]"],["אֲשֶׁר־כָּתַב","whose-he-wrote"],["מׇרְדֳּכַי","Mordecai"],["אֲלֵיהֶם","to-them"],["׃",""]] },
  { num:"כד", words:[["כִּי","because"],["הָמָן","Haman"],["בֶּן־הַמְּדָתָא","the-son-of-Hammedatha"],["הָאֲגָגִי","the-Agagite"],["צֹרֵר","the opposer of"],["כׇּל־הַיְּהוּדִים","all-the-Jews"],["חָשַׁב","he-thought"],["עַל־הַיְּהוּדִים","upon-the-Jews"],["לְאַבְּדָם","to-destroy-them"],["וְהִפִּל","and-to be knocked over"],["פּוּר","Pur"],["הוּא","it-is"],["הַגּוֹרָל","the-lot"],["לְהֻמָּם","to-disturb-them"],["וּלְאַבְּדָם","and-to-destroy-them"],["׃",""]] },
  { num:"כה", words:[["וּבְבֹאָהּ","and-when-came-it"],["לִפְנֵי","before"],["הַמֶּלֶךְ","the-king"],["אָמַר","said"],["עִם־הַסֵּפֶר","with-the-book"],["יָשׁוּב","repent"],["מַחֲשַׁבְתּוֹ","plan-his"],["הָרָעָה","the-evil"],["אֲשֶׁר־חָשַׁב","whose-he-thought"],["עַל־הַיְּהוּדִים","upon-the-Jews"],["עַל־רֹאשׁוֹ","upon-his-head"],["וְתָלוּ","and-people will hang"],["אֹתוֹ","him"],["וְאֶת־בָּנָיו","and-[ACC]-his-sons"],["עַל־הָעֵץ","upon-the-tree"],["׃",""]] },
  { num:"כו", words:[["עַל־כֵּן","therefore"],["קָרְאוּ","called-upon"],["לַיָּמִים","for-the-days"],["הָאֵלֶּה","these"],["פוּרִים","Purim"],["עַל־שֵׁם","upon-the-name-of"],["הַפּוּר","the-Pur"],["עַל־כֵּן","therefore"],["עַל־כׇּל־דִּבְרֵי","upon-all-account-of"],["הָאִגֶּרֶת","the-epistle"],["הַזֹּאת","is-this"],["וּמָה־רָאוּ","and-what-saw"],["עַל־כָּכָה","upon-thus"],["וּמָה","and-what"],["הִגִּיעַ","come-has"],["אֲלֵיהֶם","to-them"],["׃",""]] },
  { num:"כז", words:[["קִיְּמוּ","they imposed"],["(וקבל)","and-received"],["[וְקִבְּלוּ]","and-receive"],["הַיְּהוּדִים","the-Jews"],["עֲלֵיהֶם","against-them"],["וְעַל־זַרְעָם","and-upon-their-seed"],["וְעַל","and-upon"],["כׇּל־הַנִּלְוִים","all-the-who-joined themselves"],["עֲלֵיהֶם","against-them"],["וְלֹא","and-not"],["יַעֲבוֹר","it will pass away"],["לִהְיוֹת","to-be"],["עֹשִׂים","which-act"],["אֵת","[ACC]"],["שְׁנֵי","two"],["הַיָּמִים","the-days"],["הָאֵלֶּה","these"],["כִּכְתָבָם","according to-writing-their"],["וְכִזְמַנָּם","and-according to-appointed time-their"],["בְּכׇל־שָׁנָה","in-all-year"],["וְשָׁנָה","and-a year"],["׃",""]] },
  { num:"כח", words:[["וְהַיָּמִים","and-the-days"],["הָאֵלֶּה","these"],["נִזְכָּרִים","recorded-are"],["וְנַעֲשִׂים","and-are-acted-upon"],["בְּכׇל־דּוֹר","in-all-generation"],["וָדוֹר","to-generation"],["מִשְׁפָּחָה","kindred"],["וּמִשְׁפָּחָה","kindred"],["מְדִינָה","provinces"],["וּמְדִינָה","and-province"],["וְעִיר","and-the-city-of"],["וָעִיר","and-a city"],["וִימֵי","and-the days of"],["הַפּוּרִים","the-Purim"],["הָאֵלֶּה","these"],["לֹא","not"],["יַעַבְרוּ","they-shall-pass"],["מִתּוֹךְ","from-midst-of"],["הַיְּהוּדִים","the-Jews"],["וְזִכְרָם","and-remembrance-their"],["לֹא־יָסוּף","not-it will cease"],["מִזַּרְעָם","of-their-seed"],["׃",""]] },
  { num:"כט", words:[["וַתִּכְתֹּב","and-she wrote"],["אֶסְתֵּר","Esther"],["הַמַּלְכָּה","the-queen"],["בַת־אֲבִיחַיִל","the daughter of-Abihail"],["וּמׇרְדֳּכַי","and-Mordecai"],["הַיְּהוּדִי","the-Jew"],["אֶת־כׇּל־תֹּקֶף","[ACC]-all-authority"],["לְקַיֵּם","to-fulfill"],["אֵת","[ACC]"],["אִגֶּרֶת","letter"],["הַפֻּרִים","the-Purim"],["הַזֹּאת","is-this"],["הַשֵּׁנִית","the-second"],["׃",""]] },
  { num:"ל", words:[["וַיִּשְׁלַח","and-sent"],["סְפָרִים","records"],["אֶל־כׇּל־הַיְּהוּדִים","to-all-the-Jews"],["אֶל־שֶׁבַע","to-seven"],["וְעֶשְׂרִים","and-twenty"],["וּמֵאָה","and-one hundred"],["מְדִינָה","provinces"],["מַלְכוּת","the-reign-of"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["דִּבְרֵי","account-of"],["שָׁלוֹם","peace"],["וֶאֱמֶת","and-true"],["׃",""]] },
  { num:"לא", words:[["לְקַיֵּם","to-fulfill"],["אֶת־יְמֵי","[ACC]-the-days-of"],["הַפֻּרִים","the-Purim"],["הָאֵלֶּה","these"],["בִּזְמַנֵּיהֶם","at-appointed times-their"],["כַּאֲשֶׁר","when/as"],["קִיַּם","he had imposed"],["עֲלֵיהֶם","against-them"],["מׇרְדֳּכַי","Mordecai"],["הַיְּהוּדִי","the-Jew"],["וְאֶסְתֵּר","and-Esther"],["הַמַּלְכָּה","the-queen"],["וְכַאֲשֶׁר","and-as"],["קִיְּמוּ","they imposed"],["עַל־נַפְשָׁם","upon-their-soul"],["וְעַל־זַרְעָם","and-upon-their-seed"],["דִּבְרֵי","account-of"],["וְזַעֲקָתָם","and-their-cry"],["׃",""]] },
  { num:"לב", words:[["וּמַאֲמַר","and-the command of"],["אֶסְתֵּר","Esther"],["קִיַּם","he had imposed"],["דִּבְרֵי","account-of"],["הַפֻּרִים","the-Purim"],["הָאֵלֶּה","these"],["וְנִכְתָּב","and-it was written"],["בַּסֵּפֶר","in-the-book"],["׃",""]] },
];
renderVerseSet(est_ch9Verses, 'est-ch9-verses');

var est_ch10Verses = [
  { num:"א", words:[["וַיָּשֶׂם","and-made-He"],["הַמֶּלֶךְ","the-king"],["[אֲחַשְׁוֵרוֹשׁ]","Ahasuerus"],["מַס","the-tribute-of"],["עַל־הָאָרֶץ","upon-the-land"],["וְאִיֵּי","and-the islands of"],["הַיָּם","the-sea"],["׃",""]] },
  { num:"ב", words:[["וְכׇל־מַעֲשֵׂה","and-all-work-of"],["תׇקְפּוֹ","power-his"],["וּגְבוּרָתוֹ","and-His-power"],["וּפָרָשַׁת","and-the full account of"],["גְּדֻלַּת","the-greatness-of"],["מׇרְדֳּכַי","Mordecai"],["אֲשֶׁר","which"],["גִּדְּלוֹ","he had made great-him"],["הַמֶּלֶךְ","the-king"],["הֲלוֹא־הֵם","art-not-they"],["כְּתוּבִים","there-are-written"],["עַל־סֵפֶר","upon-a-book"],["דִּבְרֵי","account-of"],["הַיָּמִים","the-days"],["לְמַלְכֵי","to-the kings of"],["מָדַי","Media"],["וּפָרָס","and-Persia"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["מׇרְדֳּכַי","Mordecai"],["הַיְּהוּדִי","the-Jew"],["מִשְׁנֶה","double"],["לַמֶּלֶךְ","the-king"],["אֲחַשְׁוֵרוֹשׁ","Ahasuerus"],["וְגָדוֹל","and-great"],["לַיְּהוּדִים","to-the-Jews"],["וְרָצוּי","and-was acceptable"],["לְרֹב","for-most-part-of"],["אֶחָיו","his-elder"],["דֹּרֵשׁ","seeking"],["טוֹב","good"],["לְעַמּוֹ","for-His-people"],["וְדֹבֵר","and-speaking"],["שָׁלוֹם","peace"],["לְכׇל־זַרְעוֹ","to-all-his-seed"],["׃",""]] },
];
renderVerseSet(est_ch10Verses, 'est-ch10-verses');

})();
