// ot_verses/hab.js — Habakkuk verse data
(function() {
var hab_ch1Verses = [
  { num:"א", words:[["הַמַּשָּׂא","the-burdens"],["אֲשֶׁר","whose"],["חָזָה","saw"],["חֲבַקּוּק","Habakkuk"],["הַנָּבִיא","the-prophet"],["׃",""]] },
  { num:"ב", words:[["עַד־אָנָה","until-whither"],["יְהֹוָה","the-LORD"],["שִׁוַּעְתִּי","I cried for help"],["וְלֹא","and-not"],["תִשְׁמָע","you will listen"],["אֶזְעַק","I-shall-cry"],["אֵלֶיךָ","to-you(f)"],["חָמָס","violence"],["וְלֹא","and-not"],["תוֹשִׁיעַ","you will deliver"],["׃",""]] },
  { num:"ג", words:[["לָמָּה","why"],["תַרְאֵנִי","do you make see-me"],["אָוֶן","iniquity"],["וְעָמָל","and-Amal"],["תַּבִּיט","you look"],["וְשֹׁד","and-desolation"],["וְחָמָס","and-violence"],["לְנֶגְדִּי","to-before-me"],["וַיְהִי","and-it-came-to-pass"],["רִיב","contention"],["וּמָדוֹן","and-contention"],["יִשָּׂא","takes-away"],["׃",""]] },
  { num:"ד", words:[["עַל־כֵּן","therefore"],["תָּפוּג","it grows numb"],["תּוֹרָה","Torah/law"],["וְלֹא־יֵצֵא","and-not-he-go-forth"],["לָנֶצַח","forever"],["מִשְׁפָּט","judgment"],["כִּי","because"],["רָשָׁע","wicked"],["מַכְתִּיר","is surrounding"],["אֶת־הַצַּדִּיק","[ACC]-the-righteous"],["עַל־כֵּן","therefore"],["יֵצֵא","he-go-forth"],["מִשְׁפָּט","judgment"],["מְעֻקָּל","perverted"],["׃",""]] },
  { num:"ה", words:[["רְאוּ","behold"],["בַגּוֹיִם","by-the-nations"],["וְהַבִּיטוּ","and-look"],["וְהִתַּמְּהוּ","and-be astounded"],["תְּמָהוּ","be astonished"],["כִּי־פֹעַל","because-the work of"],["פֹּעֵל","worketh"],["בִּימֵיכֶם","in-days-your"],["לֹא","not"],["תַאֲמִינוּ","will-you-believe"],["כִּי","because"],["יְסֻפָּר","it will be recounted"],["׃",""]] },
  { num:"ו", words:[["כִּי־הִנְנִי","because-behold-I"],["מֵקִים","about to establish"],["אֶת־הַכַּשְׂדִּים","[ACC]-the-Chaldeans"],["הַגּוֹי","the-nation"],["הַמַּר","the-bitter"],["וְהַנִּמְהָר","and-impetuous"],["הַהוֹלֵךְ","which-goes"],["לְמֶרְחֲבֵי־אֶרֶץ","to-the expanses of-land-of"],["לָרֶשֶׁת","to-possess"],["מִשְׁכָּנוֹת","dwelling place"],["לֹּא־לוֹ","In--him"],["׃",""]] },
  { num:"ז", words:[["אָיֹם","is terrifying"],["וְנוֹרָא","and-terrible"],["הוּא","it-is"],["מִמֶּנּוּ","from-him"],["מִשְׁפָּטוֹ","seat"],["וּשְׂאֵתוֹ","and-dignity-its"],["יֵצֵא","he-go-forth"],["׃",""]] },
  { num:"ח", words:[["וְקַלּוּ","and-they are swift"],["מִנְּמֵרִים","more than-leopards"],["סוּסָיו","their-horses"],["וְחַדּוּ","and-they are keen"],["מִזְּאֵבֵי","more than-wolves of"],["עֶרֶב","evening"],["וּפָשׁוּ","and-they paw the ground"],["פָּרָשָׁיו","horsemen-its"],["וּפָרָשָׁיו","and-horsemen-his"],["מֵרָחוֹק","from-far"],["יָבֹאוּ","come"],["יָעֻפוּ","they fly"],["כְּנֶשֶׁר","like-an eagle"],["חָשׁ","hash-"],["לֶאֱכוֹל","to-eat"],["׃",""]] },
  { num:"ט", words:[["כֻּלֹּה","all of-it"],["לְחָמָס","for-violence"],["יָבוֹא","shall-come"],["מְגַמַּת","the totality of"],["פְּנֵיהֶם","their-faces"],["קָדִימָה","forward"],["וַיֶּאֱסֹף","and-it-came-to-pass-that-Alma-and-his-people"],["כַּחוֹל","like the-sand"],["שֶׁבִי","that-against-Me"],["׃",""]] },
  { num:"י", words:[["וְהוּא","and-it"],["בַּמְּלָכִים","in-kings"],["יִתְקַלָּס","it derides"],["וְרֹזְנִים","and-rulers"],["מִשְׂחָק","are laughter"],["לוֹ","him"],["הוּא","it-is"],["לְכׇל־מִבְצָר","to-all-fortification"],["יִשְׂחָק","he laughs"],["וַיִּצְבֹּר","and-he stored up"],["עָפָר","the-earth"],["וַיִּלְכְּדָהּ","and-he captured-it"],["׃",""]] },
  { num:"יא", words:[["אָז","then"],["חָלַף","it has passed away"],["רוּחַ","spirit-of"],["וַיַּעֲבֹר","and-overcame"],["וְאָשֵׁם","and-he will be guilty"],["זוּ","which"],["כֹחוֹ","his-power"],["לֵאלֹהוֹ","becomes-god-his"],["׃",""]] },
  { num:"יב", words:[["הֲלוֹא","art-not"],["אַתָּה","you"],["מִקֶּדֶם","of-old"],["יְהֹוָה","the-LORD"],["אֱלֹהַי","my-God"],["קְדֹשִׁי","holy one-my"],["לֹא","not"],["נָמוּת","we-die"],["יְהֹוָה","the-LORD"],["לְמִשְׁפָּט","to-judgment"],["שַׂמְתּוֹ","you have appointed-it"],["וְצוּר","and-the-rock-of"],["לְהוֹכִיחַ","to-he-reproved"],["יְסַדְתּוֹ","you have established-it"],["׃",""]] },
  { num:"יג", words:[["טְהוֹר","you are too pure of"],["עֵינַיִם","by-the-eyes-of"],["מֵרְאוֹת","from-seeing"],["רָע","evil"],["וְהַבִּיט","and-to look"],["אֶל־עָמָל","to-grievousness"],["לֹא","not"],["תוּכָל","you are able"],["לָמָּה","why"],["תַבִּיט","you-shall-look"],["בּוֹגְדִים","betrayers"],["תַּחֲרִישׁ","are you silent?"],["בְּבַלַּע","when-swallows up"],["רָשָׁע","wicked"],["צַדִּיק","righteous"],["מִמֶּנּוּ","from-him"],["׃",""]] },
  { num:"יד", words:[["וַתַּעֲשֶׂה","and-you have made"],["אָדָם","man"],["כִּדְגֵי","like-the fish of"],["הַיָּם","the-sea"],["כְּרֶמֶשׂ","like-creeping things"],["לֹא־מֹשֵׁל","not-ruler"],["בּוֹ","against-him"],["׃",""]] },
  { num:"טו", words:[["כֻּלֹּה","all of-it"],["בְּחַכָּה","with-a fish hook"],["הֵעֲלָה","he brings up"],["יְגֹרֵהוּ","he drags away-it"],["בְחֶרְמוֹ","in-net-his"],["וְיַאַסְפֵהוּ","and-he gathers-it"],["בְּמִכְמַרְתּוֹ","in-fishing net-his"],["עַל־כֵּן","therefore"],["יִשְׂמַח","rejoices"],["וְיָגִיל","and-he may be glad"],["׃",""]] },
  { num:"טז", words:[["עַל־כֵּן","therefore"],["יְזַבֵּחַ","he sacrifices"],["לְחֶרְמוֹ","to-net-his"],["וִיקַטֵּר","so-he may make smoke"],["לְמִכְמַרְתּוֹ","to-fishing net-his"],["כִּי","because"],["בָהֵמָּה","by-them"],["שָׁמֵן","stout person"],["חֶלְקוֹ","his-part"],["וּמַאֲכָלוֹ","and-food-his"],["בְּרִאָה","is fat"],["׃",""]] },
  { num:"יז", words:[["הַעַל","bring up"],["כֵּן","thus"],["יָרִיק","will he empty"],["חֶרְמוֹ","net-his"],["וְתָמִיד","and-continually"],["לַהֲרֹג","slay"],["גּוֹיִם","nations/gentiles"],["לֹא","not"],["יַחְמוֹל","it relents"],["׃",""]] },
];
renderVerseSet(hab_ch1Verses, 'hab-ch1-verses');

var hab_ch2Verses = [
  { num:"א", words:[["עַל־מִשְׁמַרְתִּי","upon-duty-my"],["אֶעֱמֹדָה","I will stand"],["וְאֶתְיַצְּבָה","and-I will take my stand"],["עַל־מָצוֹר","upon-siege works"],["וַאֲצַפֶּה","so-I may watch"],["לִרְאוֹת","to-see"],["מַה־יְדַבֶּר־בִּי","what-may he speak-against-me"],["וּמָה","and-what"],["אָשִׁיב","recall"],["עַל־תּוֹכַחְתִּי","upon-rebuke-my"],["׃",""]] },
  { num:"ב", words:[["וַיַּעֲנֵנִי","and-he answered-me"],["יְהֹוָה","the-LORD"],["וַיֹּאמֶר","and-said"],["כְּתֹב","write!"],["חָזוֹן","revelation"],["וּבָאֵר","and-make it clear"],["עַל־הַלֻּחוֹת","upon-the-plates"],["לְמַעַן","in-order-that"],["יָרוּץ","he runs"],["קוֹרֵא","calling"],["בוֹ","in-Him"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["עוֹד","any-more"],["חָזוֹן","revelation"],["לַמּוֹעֵד","to the-time"],["וְיָפֵחַ","and-it will pant"],["לַקֵּץ","to the-end"],["וְלֹא","and-not"],["יְכַזֵּב","does-lie"],["אִם־יִתְמַהְמָהּ","[compound]-it will delay"],["חַכֵּה־לוֹ","wait-him"],["כִּי־בֹא","because-came"],["יָבֹא","shall-come"],["לֹא","not"],["יְאַחֵר","he-delays"],["׃",""]] },
  { num:"ד", words:[["הִנֵּה","behold"],["עֻפְּלָה","it is swollen"],["לֹא־יָשְׁרָה","not-she is pleasing"],["נַפְשׁוֹ","his-soul"],["בּוֹ","against-him"],["וְצַדִּיק","and-righteous"],["בֶּאֱמוּנָתוֹ","through-faith"],["יִחְיֶה","he-shall-live"],["׃",""]] },
  { num:"ה", words:[["וְאַף","and-yet"],["כִּי־הַיַּיִן","because-wine"],["בֹּגֵד","deal treacherously"],["גֶּבֶר","a man"],["יָהִיר","arrogant"],["וְלֹא","and-not"],["יִנְוֶה","he stays at home"],["אֲשֶׁר","whose"],["הִרְחִיב","he-broadened"],["כִּשְׁאוֹל","like-Sheol"],["נַפְשׁוֹ","his-soul"],["וְהוּא","and-it"],["כַמָּוֶת","like-death"],["וְלֹא","and-not"],["יִשְׂבָּע","he is satisfied"],["וַיֶּאֱסֹף","and-it-came-to-pass-that-Alma-and-his-people"],["אֵלָיו","to-him"],["כׇּל־הַגּוֹיִם","all-the-nations"],["וַיִּקְבֹּץ","and-he gathered"],["אֵלָיו","to-him"],["כׇּל־הָעַמִּים","all-the-people"],["׃",""]] },
  { num:"ו", words:[["הֲלוֹא־אֵלֶּה","art-not-these"],["כֻלָּם","all-of-them"],["עָלָיו","upon-him"],["מָשָׁל","ruler"],["יִשָּׂאוּ","take-in-vain"],["וּמְלִיצָה","and-an enigma"],["חִידוֹת","riddles"],["לוֹ","him"],["וְיֹאמַר","and-shall-say"],["הוֹי","O"],["הַמַּרְבֶּה","the-one who made much"],["לֹּא־לוֹ","In--him"],["עַד־מָתַי","until-when"],["וּמַכְבִּיד","and-one who makes heavy"],["עָלָיו","upon-him"],["עַבְטִיט","pledges"],["׃",""]] },
  { num:"ז", words:[["הֲלוֹא","art-not"],["פֶתַע","suddenly"],["יָקוּמוּ","they-shall-stand"],["נֹשְׁכֶיךָ","those who pay interest to-you"],["וְיִקְצוּ","and-may they awake?"],["מְזַעְזְעֶיךָ","those who will make tremble-you"],["וְהָיִיתָ","you-were"],["לִמְשִׁסּוֹת","plunder"],["לָמוֹ","for-them"],["׃",""]] },
  { num:"ח", words:[["כִּי־אַתָּה","that-you"],["שַׁלּוֹתָ","you have plundered"],["גּוֹיִם","nations/gentiles"],["רַבִּים","many"],["יְשׇׁלּוּךָ","they will plunder-you"],["כׇּל־יֶתֶר","all-the-remainder-of"],["עַמִּים","peoples"],["מִדְּמֵי","from-the blood of"],["אָדָם","man"],["וַחֲמַס־אֶרֶץ","and-the violence of-land-of"],["קִרְיָה","a town"],["וְכׇל־יֹשְׁבֵי","and-all-inhabitants-of"],["בָהּ","in-her"],["׃",""]] },
  { num:"ט", words:[["הוֹי","O"],["בֹּצֵעַ","one who gains unjustly"],["בֶּצַע","gain/profit"],["רָע","evil"],["לְבֵיתוֹ","to-his-house"],["לָשׂוּם","to-the-any/put"],["בַּמָּרוֹם","on the-height"],["קִנּוֹ","nest-its"],["לְהִנָּצֵל","to-deliver-themselves"],["מִכַּף־רָע","from-the-wrist-evil"],["׃",""]] },
  { num:"י", words:[["יָעַצְתָּ","you have planned"],["בֹּשֶׁת","bosheth"],["לְבֵיתֶךָ","to-house-your"],["קְצוֹת־עַמִּים","the-ends-of-peoples"],["רַבִּים","many"],["וְחוֹטֵא","and-sinful"],["נַפְשֶׁךָ","your-soul"],["׃",""]] },
  { num:"יא", words:[["כִּי־אֶבֶן","because-stone"],["מִקִּיר","will be from-the wall of"],["תִּזְעָק","it will cry out"],["וְכָפִיס","and-a rafter"],["מֵעֵץ","from-tree-of"],["יַעֲנֶנָּה","let him answer-him"],["׃",""]] },
  { num:"יב", words:[["הוֹי","O"],["בֹּנֶה","building"],["עִיר","city-of"],["בְּדָמִים","blood"],["וְכוֹנֵן","and-give attention"],["קִרְיָה","a town"],["בְּעַוְלָה","with-injustice"],["׃",""]] },
  { num:"יג", words:[["הֲלוֹא","art-not"],["הִנֵּה","behold"],["מֵאֵת","from"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["וְיִיגְעוּ","so-they may labor"],["עַמִּים","peoples"],["בְּדֵי־אֵשׁ","in-the sufficiency of-fire"],["וּלְאֻמִּים","and-Leummites"],["בְּדֵי־רִיק","in-the sufficiency of-Rik"],["יִעָפוּ","they grow weary"],["׃",""]] },
  { num:"יד", words:[["כִּי","because"],["תִּמָּלֵא","shall-be-filled"],["הָאָרֶץ","the-earth"],["לָדַעַת","to-know"],["אֶת־כְּבוֹד","[ACC]-the-glory-of"],["יְהֹוָה","the-LORD"],["כַּמַּיִם","as-the-waters"],["יְכַסּוּ","which they cover"],["עַל־יָם","upon-the-sea"],["׃",""]] },
  { num:"טו", words:[["הוֹי","O"],["מַשְׁקֵה","the cup bearer of"],["רֵעֵהוּ","his-fellow"],["מְסַפֵּחַ","you are pouring out"],["חֲמָתְךָ","anger-your"],["וְאַף","and-yet"],["שַׁכֵּר","you make them drunk"],["לְמַעַן","in-order-that"],["הַבִּיט","to look"],["עַל־מְעוֹרֵיהֶם","upon-nakedness-their"],["׃",""]] },
  { num:"טז", words:[["שָׂבַעְתָּ","you are satisfied"],["קָלוֹן","shame"],["מִכָּבוֹד","from-honor"],["שְׁתֵה","drink"],["גַם־אַתָּה","also-you"],["וְהֵעָרֵל","and-be counted as uncircumcised"],["תִּסּוֹב","it turns"],["עָלֶיךָ","upon-you(f)"],["כּוֹס","the-cup-of"],["יְמִין","right-hand"],["יְהֹוָה","the-LORD"],["וְקִיקָלוֹן","and-disgrace"],["עַל־כְּבוֹדֶךָ","upon-glory-your"],["׃",""]] },
  { num:"יז", words:[["כִּי","because"],["חֲמַס","the violence of"],["לְבָנוֹן","Lebanon"],["יְכַסֶּךָּ","it will cover-you"],["וְשֹׁד","and-desolation"],["בְּהֵמוֹת","animals"],["יְחִיתַן","it will terrify-them"],["מִדְּמֵי","from-the blood of"],["אָדָם","man"],["וַחֲמַס־אֶרֶץ","and-the violence of-land-of"],["קִרְיָה","a town"],["וְכׇל־יֹשְׁבֵי","and-all-inhabitants-of"],["בָהּ","in-her"],["׃",""]] },
  { num:"יח", words:[["מָה־הוֹעִיל","what-unprofitable"],["פֶּסֶל","an image of"],["כִּי","because"],["פְסָלוֹ","he has carved-it"],["יֹצְרוֹ","the one who formed-him"],["מַסֵּכָה","molten metal"],["וּמוֹרֶה","and-teacher(f)"],["שָּׁקֶר","falsehood"],["כִּי","because"],["בָטַח","trust"],["יֹצֵר","the former of"],["יִצְרוֹ","intention-its"],["עָלָיו","upon-him"],["לַעֲשׂוֹת","to-do"],["אֱלִילִים","idols"],["אִלְּמִים","mute"],["׃",""]] },
  { num:"יט", words:[["הוֹי","O"],["אֹמֵר","say"],["לָעֵץ","unto-the-tree"],["הָקִיצָה","awake"],["עוּרִי","awake"],["לְאֶבֶן","to-a stone of"],["דּוּמָם","silence"],["הוּא","it-is"],["יוֹרֶה","teaches"],["הִנֵּה־הוּא","behold-it-is"],["תָּפוּשׂ","is sheathed"],["זָהָב","gold"],["וָכֶסֶף","and-with-silver"],["וְכׇל־רוּחַ","and-all-spirit-of"],["אֵין","there-is-no"],["בְּקִרְבּוֹ","in-the-midst-of-him"],["׃",""]] },
  { num:"כ", words:[["וַיהֹוָה","and-Yahweh"],["בְּהֵיכַל","in-the temple of"],["קׇדְשׁוֹ","holy-his"],["הַס","hush!"],["מִפָּנָיו","from-before-him"],["כׇּל־הָאָרֶץ","all-the-earth"],["׃",""]] },
];
renderVerseSet(hab_ch2Verses, 'hab-ch2-verses');

var hab_ch3Verses = [
  { num:"א", words:[["תְּפִלָּה","prayer"],["לַחֲבַקּוּק","of-Habakkuk"],["הַנָּבִיא","the-prophet"],["עַל","upon"],["שִׁגְיֹנוֹת","shiggionoth"],["׃",""]] },
  { num:"ב", words:[["יְהֹוָה","the-LORD"],["שָׁמַעְתִּי","heard"],["שִׁמְעֲךָ","report-your"],["יָרֵאתִי","I-fear"],["יְהֹוָה","the-LORD"],["פׇּעׇלְךָ","one who does-your"],["בְּקֶרֶב","among"],["שָׁנִים","years"],["חַיֵּיהוּ","restore-it"],["בְּקֶרֶב","among"],["שָׁנִים","years"],["תּוֹדִיעַ","you-shall-make-known"],["בְּרֹגֶז","to-the raging of"],["רַחֵם","he-had-mercy"],["תִּזְכּוֹר","it remembers"],["׃",""]] },
  { num:"ג", words:[["אֱלוֹהַּ","Loh"],["מִתֵּימָן","from-the south"],["יָבוֹא","shall-come"],["וְקָדוֹשׁ","and-holy"],["מֵהַר־פָּארָן","from-the mountain of-Paran"],["סֶלָה","Selah"],["כִּסָּה","He-has-covered"],["שָׁמַיִם","the-heavens"],["הוֹדוֹ","splendor-his"],["וּתְהִלָּתוֹ","and-praise-his"],["מָלְאָה","is-also-full-of"],["הָאָרֶץ","the-earth"],["׃",""]] },
  { num:"ד", words:[["וְנֹגַהּ","and-the-shining-of"],["כָּאוֹר","like the-light"],["תִּהְיֶה","shall-be"],["קַרְנַיִם","Karnaim"],["מִיָּדוֹ","from-His-hand"],["לוֹ","him"],["וְשָׁם","and-there"],["חֶבְיוֹן","the hiding place of"],["עֻזֹּה","strength-its"],["׃",""]] },
  { num:"ה", words:[["לְפָנָיו","before-him"],["יֵלֶךְ","let him go"],["דָּבֶר","pestilence"],["וְיֵצֵא","and-shall-go-forth"],["רֶשֶׁף","plague"],["לְרַגְלָיו","at-His-feet"],["׃",""]] },
  { num:"ו", words:[["עָמַד","stood"],["וַיְמֹדֶד","and-he shook"],["אֶרֶץ","land-of"],["רָאָה","he-saw"],["וַיַּתֵּר","and-he-permitted"],["גּוֹיִם","nations/gentiles"],["וַיִּתְפֹּצְצוּ","and-they have been shattered"],["הַרְרֵי־עַד","the mountains of-until"],["שַׁחוּ","they bow"],["גִּבְעוֹת","the hills of"],["עוֹלָם","eternal"],["הֲלִיכוֹת","the processions of"],["עוֹלָם","eternal"],["לוֹ","him"],["׃",""]] },
  { num:"ז", words:[["תַּחַת","under"],["אָוֶן","iniquity"],["רָאִיתִי","I-saw"],["אׇהֳלֵי","would-that"],["כוּשָׁן","Cushan"],["יִרְגְּזוּן","they tremble-!"],["יְרִיעוֹת","Jerioth"],["אֶרֶץ","land-of"],["מִדְיָן","Midian"],["׃",""]] },
  { num:"ח", words:[["הֲבִנְהָרִים","¿-on-rivers"],["חָרָה","burned"],["יְהֹוָה","the-LORD"],["אִם","[compound]"],["בַּנְּהָרִים","on the-rivers"],["אַפֶּךָ","anger-your"],["אִם־בַּיָּם","[compound]-in-the-sea"],["עֶבְרָתֶךָ","fury-your"],["כִּי","because"],["תִרְכַּב","you will ride"],["עַל־סוּסֶיךָ","upon-your-horses"],["מַרְכְּבֹתֶיךָ","chariots-your"],["יְשׁוּעָה","salvation"],["׃",""]] },
  { num:"ט", words:[["עֶרְיָה","nakedness"],["תֵעוֹר","it is made bare"],["קַשְׁתֶּךָ","bow-your"],["שְׁבֻעוֹת","promises-of"],["מַטּוֹת","the tribes of"],["אֹמֶר","utterance"],["סֶלָה","Selah"],["נְהָרוֹת","their-rivers"],["תְּבַקַּע־אָרֶץ","you split open-the-earth"],["׃",""]] },
  { num:"י", words:[["רָאוּךָ","they saw-you"],["יָחִילוּ","they endure"],["הָרִים","mountains"],["זֶרֶם","a downpour of"],["מַיִם","water"],["עָבָר","it passed on"],["נָתַן","was-given"],["תְּהוֹם","gulf"],["קוֹלוֹ","His-voice"],["רוֹם","height"],["יָדֵיהוּ","hands-its"],["נָשָׂא","bore"],["׃",""]] },
  { num:"יא", words:[["שֶׁמֶשׁ","the-sun-of"],["יָרֵחַ","moon"],["עָמַד","stood"],["זְבֻלָה","a lofty abode"],["לְאוֹר","to-light"],["חִצֶּיךָ","arrows-your"],["יְהַלֵּכוּ","they will walk"],["לְנֹגַהּ","to-the brightness of"],["בְּרַק","the lightning of"],["חֲנִיתֶךָ","spear-your"],["׃",""]] },
  { num:"יב", words:[["בְּזַעַם","in-the indignation of"],["תִּצְעַד־אָרֶץ","you march-the-earth"],["בְּאַף","in-anger"],["תָּדוּשׁ","you will thresh"],["גּוֹיִם","nations/gentiles"],["׃",""]] },
  { num:"יג", words:[["יָצָאתָ","you came out"],["לְיֵשַׁע","for-the salvation of"],["עַמֶּךָ","your-people"],["לְיֵשַׁע","for-the salvation of"],["אֶת־מְשִׁיחֶךָ","[ACC]-anointed-your"],["מָחַצְתָּ","you have shattered"],["רֹּאשׁ","a head"],["מִבֵּית","from-house-of"],["רָשָׁע","wicked"],["עָרוֹת","reeds"],["יְסוֹד","foundation"],["עַד־צַוָּאר","reaching-even-to-the-neck"],["סֶלָה","Selah"],["׃",""]] },
  { num:"יד", words:[["נָקַבְתָּ","you pierced"],["בְמַטָּיו","with-own arrows-his"],["רֹאשׁ","head-of"],["פְּרָזָו","chieftain"],["יִסְעֲרוּ","they storm"],["לַהֲפִיצֵנִי","to-scatter-me"],["עֲלִיצֻתָם","exultation-their"],["כְּמוֹ־לֶאֱכֹל","as/like-to-eat"],["עָנִי","poor"],["בַּמִּסְתָּר","in-hiding place"],["׃",""]] },
  { num:"טו", words:[["דָּרַכְתָּ","you trod"],["בַיָּם","in-the-sea"],["סוּסֶיךָ","your-horses"],["חֹמֶר","clay"],["מַיִם","water"],["רַבִּים","many"],["׃",""]] },
  { num:"טז", words:[["שָׁמַעְתִּי","heard"],["וַתִּרְגַּז","and-it quaked"],["בִּטְנִי","belly-my"],["לְקוֹל","to-voice-of"],["צָלְלוּ","shade(they)"],["שְׂפָתַי","my-lips"],["יָבוֹא","shall-come"],["רָקָב","rottenness"],["בַּעֲצָמַי","in-bones-my"],["וְתַחְתַּי","and-under-me"],["אֶרְגָּז","I trembled"],["אֲשֶׁר","whose"],["אָנוּחַ","to-rest"],["לְיוֹם","to-day"],["צָרָה","affliction"],["לַעֲלוֹת","to-ascend"],["לְעַם","a-people"],["יְגוּדֶנּוּ","it will attack-him"],["׃",""]] },
  { num:"יז", words:[["כִּי־תְאֵנָה","because-a fig tree"],["לֹא־תִפְרָח","not-it buds"],["וְאֵין","and-has-no"],["יְבוּל","the produce of"],["בַּגְּפָנִים","on the-vines"],["כִּחֵשׁ","he lied"],["מַעֲשֵׂה־זַיִת","work-of-the-olive-tree"],["וּשְׁדֵמוֹת","and-fields"],["לֹא־עָשָׂה","not-he-did"],["אֹכֶל","food"],["גָּזַר","decreed"],["מִמִּכְלָה","from-the fold"],["צֹאן","flocks"],["וְאֵין","and-has-no"],["בָּקָר","of-the-herd"],["בָּרְפָתִים","is in the-stalls"],["׃",""]] },
  { num:"יח", words:[["וַאֲנִי","and-I"],["בַּיהֹוָה","is in-Yahweh"],["אֶעְלוֹזָה","I will exult"],["אָגִילָה","I will rejoice"],["בֵּאלֹהֵי","in-the-God"],["יִשְׁעִי","My-salvation"],["׃",""]] },
  { num:"יט", words:[["יֱהֹוִה","Yahweh"],["אֲדֹנָי","Lord"],["חֵילִי","wealth-my"],["וַיָּשֶׂם","and-made-He"],["רַגְלַי","feet-of"],["כָּאַיָּלוֹת","like-does"],["וְעַל","and-upon"],["בָּמוֹתַי","high places-my"],["יַדְרִכֵנִי","he makes tread-me"],["לַמְנַצֵּחַ","to the-choirmaster"],["בִּנְגִינוֹתָי","with-stringed instruments-my"],["׃",""]] },
];
renderVerseSet(hab_ch3Verses, 'hab-ch3-verses');

})();
