// ot_verses/hag.js — Haggai verse data
(function() {
var hag_ch1Verses = [
  { num:"א", words:[["בִּשְׁנַת","in-year-of"],["שְׁתַּיִם","two"],["לְדָרְיָוֶשׁ","to-Darius"],["הַמֶּלֶךְ","the-king"],["בַּחֹדֶשׁ","in-the-month"],["הַשִּׁשִּׁי","the-sixth"],["בְּיוֹם","in-day-of"],["אֶחָד","one"],["לַחֹדֶשׁ","of-the-month"],["הָיָה","was"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["בְּיַד־חַגַּי","in-hand-of-Haggai"],["הַנָּבִיא","the-prophet"],["אֶל־זְרֻבָּבֶל","to-Zerubbabel"],["בֶּן־שְׁאַלְתִּיאֵל","son-of-Shealtiel"],["פַּחַת","the governor of"],["יְהוּדָה","Judah"],["וְאֶל־יְהוֹשֻׁעַ","and-Joshua"],["בֶּן־יְהוֹצָדָק","son-of-Jehozadak"],["הַכֹּהֵן","the-priest"],["הַגָּדוֹל","the-great"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ב", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["לֵאמֹר","saying"],["הָעָם","the-people"],["הַזֶּה","this"],["אָמְרוּ","they-said"],["לֹא","not"],["עֶת־בֹּא","the time of-come"],["עֶת־בֵּית","the time of-house-of"],["יְהֹוָה","the-LORD"],["לְהִבָּנוֹת","to-be-laid"],["׃",""]] },
  { num:"ג", words:[["וַיְהִי","and-it-came-to-pass"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["בְּיַד־חַגַּי","in-hand-of-Haggai"],["הַנָּבִיא","the-prophet"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ד", words:[["הַעֵת","¿-a time"],["לָכֶם","to-you"],["אַתֶּם","you-are"],["לָשֶׁבֶת","to-dwell"],["בְּבָתֵּיכֶם","is-in-your-houses"],["סְפוּנִים","covered"],["וְהַבַּיִת","and-the-house"],["הַזֶּה","this"],["חָרֵב","is desolate"],["׃",""]] },
  { num:"ה", words:[["וְעַתָּה","and-now"],["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["שִׂימוּ","give"],["לְבַבְכֶם","your-hearts"],["עַל־דַּרְכֵיכֶם","upon-roads-your"],["׃",""]] },
  { num:"ו", words:[["זְרַעְתֶּם","you have sown"],["הַרְבֵּה","much"],["וְהָבֵא","and-you have brought"],["מְעָט","a-little"],["אָכוֹל","continuously"],["וְאֵין־לְשׇׂבְעָה","and-there-is-no-???"],["שָׁתוֹ","certainly"],["וְאֵין־לְשׇׁכְרָה","and-there-is-no-???"],["לָבוֹשׁ","you have dressed"],["וְאֵין־לְחֹם","and-has-no-to-be warm"],["לוֹ","him"],["וְהַמִּשְׂתַּכֵּר","and-the-one who earns wages"],["מִשְׂתַּכֵּר","is earning wages"],["אֶל־צְרוֹר","to-the bag of"],["נָקוּב","pierced"],["׃",""]] },
  { num:"ז", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["שִׂימוּ","give"],["לְבַבְכֶם","your-hearts"],["עַל־דַּרְכֵיכֶם","upon-roads-your"],["׃",""]] },
  { num:"ח", words:[["עֲלוּ","go-up"],["הָהָר","the-mountain"],["וַהֲבֵאתֶם","and-have-brought"],["עֵץ","a-tree"],["וּבְנוּ","and-build!(pl)"],["הַבָּיִת","the-house"],["וְאֶרְצֶה־בּוֹ","so-I may take pleasure-against-him"],["(ואכבד)","yet-glorious-shall-I-be"],["[וְאֶכָּבְדָה]","so-let me be honored"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ט", words:[["פָּנֹה","you turned to look"],["אֶל־הַרְבֵּה","to-much"],["וְהִנֵּה","and-behold"],["לִמְעָט","and-the few"],["וַהֲבֵאתֶם","and-have-brought"],["הַבַּיִת","the-house"],["וְנָפַחְתִּי","and-I will blow"],["בוֹ","in-Him"],["יַעַן","because"],["מֶה","what"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["יַעַן","because"],["בֵּיתִי","my-house"],["אֲשֶׁר־הוּא","whose-it-is"],["חָרֵב","is desolate"],["וְאַתֶּם","and-will-you"],["רָצִים","who ran"],["אִישׁ","man-of"],["לְבֵיתוֹ","to-his-house"],["׃",""]] },
  { num:"י", words:[["עַל־כֵּן","therefore"],["עֲלֵיכֶם","over-you"],["כָּלְאוּ","they have withheld"],["שָׁמַיִם","the-heavens"],["מִטָּל","from-the dew"],["וְהָאָרֶץ","and-the-earth"],["כָּלְאָה","it has withheld"],["יְבוּלָהּ","produce-its"],["׃",""]] },
  { num:"יא", words:[["וָאֶקְרָא","and-I-called"],["חֹרֶב","heat"],["עַל־הָאָרֶץ","upon-the-land"],["וְעַל־הֶהָרִים","and-upon-the-mountains"],["וְעַל־הַדָּגָן","and-upon-the-grain"],["וְעַל־הַתִּירוֹשׁ","and-upon-the-new wine"],["וְעַל־הַיִּצְהָר","and-upon-the-fresh oil"],["וְעַל","and-upon"],["אֲשֶׁר","whose"],["תּוֹצִיא","you will bring out"],["הָאֲדָמָה","the-earth"],["וְעַל־הָאָדָם","and-upon-man"],["וְעַל־הַבְּהֵמָה","and-upon-the-livestock"],["וְעַל","and-upon"],["כׇּל־יְגִיעַ","all-the product of"],["כַּפָּיִם","palms"],["׃",""]] },
  { num:"יב", words:[["וַיִּשְׁמַע","and-he-obeyed"],["זְרֻבָּבֶל","Zerubbabel"],["בֶּן־שַׁלְתִּיאֵל","son-of-Shealtiel"],["וִיהוֹשֻׁעַ","and-Joshua"],["בֶּן־יְהוֹצָדָק","son-of-Jehozadak"],["הַכֹּהֵן","the-priest"],["הַגָּדוֹל","the-great"],["וְכֹל","and-the-whole"],["שְׁאֵרִית","remnant-of"],["הָעָם","the-people"],["בְּקוֹל","the-voice-of"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיהֶם","their-God"],["וְעַל־דִּבְרֵי","and-upon-account-of"],["חַגַּי","Haggai"],["הַנָּבִיא","the-prophet"],["כַּאֲשֶׁר","when/as"],["שְׁלָחוֹ","he had sent-him"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיהֶם","their-God"],["וַיִּירְאוּ","and-they-feared"],["הָעָם","the-people"],["מִפְּנֵי","because-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"יג", words:[["וַיֹּאמֶר","and-said"],["חַגַּי","Haggai"],["מַלְאַךְ","angel-of"],["יְהֹוָה","the-LORD"],["בְּמַלְאֲכוּת","by-the message of"],["יְהֹוָה","the-LORD"],["לָעָם","to-the-people"],["לֵאמֹר","saying"],["אֲנִי","I"],["אִתְּכֶם","with-you"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"יד", words:[["וַיָּעַר","and-he stirred up"],["יְהֹוָה","the-LORD"],["אֶת־רוּחַ","[ACC]-the-Spirit-of"],["זְרֻבָּבֶל","Zerubbabel"],["בֶּן־שַׁלְתִּיאֵל","son-of-Shealtiel"],["פַּחַת","the governor of"],["יְהוּדָה","Judah"],["וְאֶת־רוּחַ","and-[ACC]-spirit-of"],["יְהוֹשֻׁעַ","Joshua"],["בֶּן־יְהוֹצָדָק","son-of-Jehozadak"],["הַכֹּהֵן","the-priest"],["הַגָּדוֹל","the-great"],["וְאֶת־רוּחַ","and-[ACC]-spirit-of"],["כֹּל","all"],["שְׁאֵרִית","remnant-of"],["הָעָם","the-people"],["וַיָּבֹאוּ","and-they-came"],["וַיַּעֲשׂוּ","and-they-did"],["מְלָאכָה","a-work"],["בְּבֵית־יְהֹוָה","in-house-of-the-LORD"],["צְבָאוֹת","of-Hosts"],["אֱלֹהֵיהֶם","their-God"],["׃",""]] },
  { num:"טו", words:[["בְּיוֹם","in-day-of"],["עֶשְׂרִים","twenty"],["וְאַרְבָּעָה","and-four"],["לַחֹדֶשׁ","of-the-month"],["בַּשִּׁשִּׁי","in the-sixth month"],["בִּשְׁנַת","in-year-of"],["שְׁתַּיִם","two"],["לְדָרְיָוֶשׁ","to-Darius"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
];
renderVerseSet(hag_ch1Verses, 'hag-ch1-verses');

var hag_ch2Verses = [
  { num:"א", words:[["בַּשְּׁבִיעִי","in the-seventh month"],["בְּעֶשְׂרִים","on-the-twenty"],["וְאֶחָד","and-one"],["לַחֹדֶשׁ","of-the-month"],["הָיָה","was"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["בְּיַד־חַגַּי","in-hand-of-Haggai"],["הַנָּבִיא","the-prophet"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ב", words:[["אֱמׇר־נָא","I-say-I-pray"],["אֶל־זְרֻבָּבֶל","to-Zerubbabel"],["בֶּן־שַׁלְתִּיאֵל","son-of-Shealtiel"],["פַּחַת","the governor of"],["יְהוּדָה","Judah"],["וְאֶל־יְהוֹשֻׁעַ","and-Joshua"],["בֶּן־יְהוֹצָדָק","son-of-Jehozadak"],["הַכֹּהֵן","the-priest"],["הַגָּדוֹל","the-great"],["וְאֶל־שְׁאֵרִית","and-remnant-of"],["הָעָם","the-people"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ג", words:[["מִי","who"],["בָכֶם","over-you"],["הַנִּשְׁאָר","those-remaining"],["אֲשֶׁר","whose"],["רָאָה","he-saw"],["אֶת־הַבַּיִת","[ACC]-the-house"],["הַזֶּה","this"],["בִּכְבוֹדוֹ","in-his-glory"],["הָרִאשׁוֹן","the-first"],["וּמָה","and-what"],["אַתֶּם","you-are"],["רֹאִים","see"],["אֹתוֹ","him"],["עַתָּה","now"],["הֲלוֹא","art-not"],["כָמֹהוּ","like-him"],["כְּאַיִן","as-nothing"],["בְּעֵינֵיכֶם","in-view-your"],["׃",""]] },
  { num:"ד", words:[["וְעַתָּה","and-now"],["חֲזַק","be strong"],["זְרֻבָּבֶל","Zerubbabel"],["נְאֻם־יְהֹוָה","says-the-LORD"],["וַחֲזַק","and-be strong"],["יְהוֹשֻׁעַ","Joshua"],["בֶּן־יְהוֹצָדָק","son-of-Jehozadak"],["הַכֹּהֵן","the-priest"],["הַגָּדוֹל","the-great"],["וַחֲזַק","and-be strong"],["כׇּל־עַם","all-people"],["הָאָרֶץ","the-earth"],["נְאֻם־יְהֹוָה","says-the-LORD"],["וַעֲשׂוּ","and-do!(pl)"],["כִּי־אֲנִי","that-I-am"],["אִתְּכֶם","with-you"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"ה", words:[["אֶת־הַדָּבָר","[ACC]-the-word"],["אֲשֶׁר־כָּרַתִּי","whose-I-cut"],["אִתְּכֶם","with-you"],["בְּצֵאתְכֶם","when-came out-you"],["מִמִּצְרַיִם","out-of-Egypt"],["וְרוּחִי","and-my-spirit"],["עֹמֶדֶת","standing(f)"],["בְּתוֹכְכֶם","among-you"],["אַל־תִּירָאוּ","fear-not"],["׃",""]] },
  { num:"ו", words:[["כִּי","because"],["כֹה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["עוֹד","any-more"],["אַחַת","one"],["מְעַט","somewhat"],["הִיא","it-is"],["וַאֲנִי","and-I"],["מַרְעִישׁ","shake"],["אֶת־הַשָּׁמַיִם","the-heavens"],["וְאֶת־הָאָרֶץ","and-[ACC]-the-land"],["וְאֶת־הַיָּם","and-[ACC]-the-sea"],["וְאֶת־הֶחָרָבָה","and-[ACC]-the-dry ground"],["׃",""]] },
  { num:"ז", words:[["וְהִרְעַשְׁתִּי","and-I will shake"],["אֶת־כׇּל־הַגּוֹיִם","[ACC]-all-the-nations"],["וּבָאוּ","and-it-comes"],["חֶמְדַּת","desirable thing of"],["כׇּל־הַגּוֹיִם","all-the-nations"],["וּמִלֵּאתִי","and-I will confirm"],["אֶת־הַבַּיִת","[ACC]-the-house"],["הַזֶּה","this"],["כָּבוֹד","glorious"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"ח", words:[["לִי","to-me"],["הַכֶּסֶף","the-money"],["וְלִי","and-they-are-Mine"],["הַזָּהָב","the-gold"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"ט", words:[["גָּדוֹל","great"],["יִהְיֶה","he-shall-be"],["כְּבוֹד","the-glory-of"],["הַבַּיִת","the-house"],["הַזֶּה","this"],["הָאַחֲרוֹן","the-last"],["מִן־הָרִאשׁוֹן","from-the-first"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["וּבַמָּקוֹם","and-in the-place"],["הַזֶּה","this"],["אֶתֵּן","shall-give"],["שָׁלוֹם","peace"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"י", words:[["בְּעֶשְׂרִים","on-the-twenty"],["וְאַרְבָּעָה","and-four"],["לַתְּשִׁיעִי","of the-ninth month"],["בִּשְׁנַת","in-year-of"],["שְׁתַּיִם","two"],["לְדָרְיָוֶשׁ","to-Darius"],["הָיָה","was"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["אֶל־חַגַּי","to-Haggai"],["הַנָּבִיא","the-prophet"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"יא", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["שְׁאַל־נָא","ask-I-pray"],["אֶת־הַכֹּהֲנִים","[ACC]-the-priests"],["תּוֹרָה","a-Bible"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"יב", words:[["הֵן","yea"],["יִשָּׂא־אִישׁ","takes-away-man-of"],["בְּשַׂר־קֹדֶשׁ","the-flesh-holy"],["בִּכְנַף","on-the skirt of"],["בִּגְדוֹ","clothing-his"],["וְנָגַע","and-he will touch"],["בִּכְנָפוֹ","with-skirt-his"],["אֶל־הַלֶּחֶם","to-this-bread"],["וְאֶל־הַנָּזִיד","and-the-cooked food"],["וְאֶל־הַיַּיִן","and-wine"],["וְאֶל־שֶׁמֶן","and-oil"],["וְאֶל־כׇּל־מַאֲכָל","and-all-food"],["הֲיִקְדָּשׁ","¿-will it become holy"],["וַיַּעֲנוּ","and-they-answered"],["הַכֹּהֲנִים","the-priests"],["וַיֹּאמְרוּ","and-they-said"],["לֹא","not"],["׃",""]] },
  { num:"יג", words:[["וַיֹּאמֶר","and-said"],["חַגַּי","Haggai"],["אִם־יִגַּע","[compound]-he will touch"],["טְמֵא־נֶפֶשׁ","thing unclean of-soul"],["בְּכׇל־אֵלֶּה","in-all-these"],["הֲיִטְמָא","¿-will it become unclean"],["וַיַּעֲנוּ","and-they-answered"],["הַכֹּהֲנִים","the-priests"],["וַיֹּאמְרוּ","and-they-said"],["יִטְמָא","he-shall-be-unclean"],["׃",""]] },
  { num:"יד", words:[["וַיַּעַן","and-he-answered"],["חַגַּי","Haggai"],["וַיֹּאמֶר","and-said"],["כֵּן","thus"],["הָעָם־הַזֶּה","this-people"],["וְכֵן־הַגּוֹי","and-so-the-nation"],["הַזֶּה","this"],["לְפָנַי","before-me"],["נְאֻם־יְהֹוָה","says-the-LORD"],["וְכֵן","and-so"],["כׇּל־מַעֲשֵׂה","all-work-of"],["יְדֵיהֶם","their-hands"],["וַאֲשֶׁר","and-whom"],["יַקְרִיבוּ","they-lay"],["שָׁם","there-is"],["טָמֵא","unclean"],["הוּא","it-is"],["׃",""]] },
  { num:"טו", words:[["וְעַתָּה","and-now"],["שִׂימוּ־נָא","give-I-pray"],["לְבַבְכֶם","your-hearts"],["מִן־הַיּוֹם","from-the-day"],["הַזֶּה","this"],["וָמָעְלָה","and-up--wards"],["מִטֶּרֶם","from-before"],["שׂוּם־אֶבֶן","put-stone"],["אֶל־אֶבֶן","to-stone"],["בְּהֵיכַל","in-the temple of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"טז", words:[["מִהְיוֹתָם","from-when were-they"],["בָּא","came"],["אֶל־עֲרֵמַת","to-is a heap of"],["עֶשְׂרִים","twenty"],["וְהָיְתָה","and-it-be"],["עֲשָׂרָה","ten"],["בָּא","came"],["אֶל־הַיֶּקֶב","to-the-wine vat"],["לַחְשֹׂף","to-draw"],["חֲמִשִּׁים","fifty"],["פּוּרָה","the winepress"],["וְהָיְתָה","and-it-be"],["עֶשְׂרִים","twenty"],["׃",""]] },
  { num:"יז", words:[["הִכֵּיתִי","I-was-smitten"],["אֶתְכֶם","you"],["בַּשִּׁדָּפוֹן","with-blight"],["וּבַיֵּרָקוֹן","and-with-mildew"],["וּבַבָּרָד","and-with-hail"],["אֵת","[ACC]"],["כׇּל־מַעֲשֵׂה","all-work-of"],["יְדֵיכֶם","your-hands"],["וְאֵין־אֶתְכֶם","and-has-no-you"],["אֵלַי","to-me"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"יח", words:[["שִׂימוּ־נָא","give-I-pray"],["לְבַבְכֶם","your-hearts"],["מִן־הַיּוֹם","from-the-day"],["הַזֶּה","this"],["וָמָעְלָה","and-up--wards"],["מִיּוֹם","from-the-day"],["עֶשְׂרִים","twenty"],["וְאַרְבָּעָה","and-four"],["לַתְּשִׁיעִי","of the-ninth month"],["לְמִן־הַיּוֹם","from-the-day"],["אֲשֶׁר־יֻסַּד","whose-it was founded"],["הֵיכַל־יְהֹוָה","the-temple-of-the-LORD"],["שִׂימוּ","give"],["לְבַבְכֶם","your-hearts"],["׃",""]] },
  { num:"יט", words:[["הַעוֹד","¿-still"],["הַזֶּרַע","the-seed"],["בַּמְּגוּרָה","in the-granary"],["וְעַד־הַגֶּפֶן","and-unto-the-vine"],["וְהַתְּאֵנָה","and-the-fig tree"],["וְהָרִמּוֹן","and-the-pomegranate"],["וְעֵץ","and-tree-of"],["הַזַּיִת","the-olive-tree"],["לֹא","not"],["נָשָׂא","bore"],["מִן־הַיּוֹם","from-the-day"],["הַזֶּה","this"],["אֲבָרֵךְ","I will bless"],["׃",""]] },
  { num:"כ", words:[["וַיְהִי","and-it-came-to-pass"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["שֵׁנִית","again"],["אֶל־חַגַּי","to-Haggai"],["בְּעֶשְׂרִים","on-the-twenty"],["וְאַרְבָּעָה","and-four"],["לַחֹדֶשׁ","of-the-month"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"כא", words:[["אֱמֹר","say!"],["אֶל־זְרֻבָּבֶל","to-Zerubbabel"],["פַּחַת־יְהוּדָה","the governor of-Judah"],["לֵאמֹר","saying"],["אֲנִי","I"],["מַרְעִישׁ","shake"],["אֶת־הַשָּׁמַיִם","the-heavens"],["וְאֶת־הָאָרֶץ","and-[ACC]-the-land"],["׃",""]] },
  { num:"כב", words:[["וְהָפַכְתִּי","and-I-shall-overturn"],["כִּסֵּא","throne"],["מַמְלָכוֹת","kingdoms"],["וְהִשְׁמַדְתִּי","and-I will destroy"],["חֹזֶק","strength"],["מַמְלְכוֹת","the-reigns-of"],["הַגּוֹיִם","the-nations"],["וְהָפַכְתִּי","and-I-shall-overturn"],["מֶרְכָּבָה","a chariot"],["וְרֹכְבֶיהָ","and-riders-its"],["וְיָרְדוּ","and-they-came-down"],["סוּסִים","horses"],["וְרֹכְבֵיהֶם","and-riders-their"],["אִישׁ","man-of"],["בְּחֶרֶב","with-the-sword-of"],["אָחִיו","another"],["׃",""]] },
  { num:"כג", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["נְאֻם־יְהֹוָה","says-the-LORD"],["צְבָאוֹת","of-Hosts"],["אֶקָּחֲךָ","let me take-you"],["זְרֻבָּבֶל","Zerubbabel"],["בֶּן־שְׁאַלְתִּיאֵל","son-of-Shealtiel"],["עַבְדִּי","thou-art-My-servant"],["נְאֻם־יְהֹוָה","says-the-LORD"],["וְשַׂמְתִּיךָ","then-I-set-you"],["כַּחוֹתָם","like-seal"],["כִּי־בְךָ","because-in-You"],["בָחַרְתִּי","I chose"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
];
renderVerseSet(hag_ch2Verses, 'hag-ch2-verses');

})();
