// ot_verses/joe.js — Joel verse data
(function() {
var joe_ch1Verses = [
  { num:"א", words:[["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["אֲשֶׁר","which"],["הָיָה","was"],["אֶל־יוֹאֵל","to-Joel"],["בֶּן־פְּתוּאֵל","son-of-Pethuel"],["׃",""]] },
  { num:"ב", words:[["שִׁמְעוּ־זֹאת","hear-this"],["הַזְּקֵנִים","the-you-old-men"],["וְהַאֲזִינוּ","and-listen"],["כֹּל","all"],["יוֹשְׁבֵי","the-inhabitants-of"],["הָאָרֶץ","the-earth"],["הֶהָיְתָה","¿-has it happened"],["זֹּאת","this(f)"],["בִּימֵיכֶם","in-days-your"],["וְאִם","and-if"],["בִּימֵי","in-days-of"],["אֲבֹתֵיכֶם","your-fathers"],["׃",""]] },
  { num:"ג", words:[["עָלֶיהָ","upon-it"],["לִבְנֵיכֶם","your-children"],["סַפֵּרוּ","recount"],["וּבְנֵיכֶם","and-your-children"],["לִבְנֵיהֶם","to-their-children"],["וּבְנֵיהֶם","and-their-children"],["לְדוֹר","to-generation"],["אַחֵר","other"],["׃",""]] },
  { num:"ד", words:[["יֶתֶר","the-remainder-of"],["הַגָּזָם","the-locusts"],["אָכַל","ate"],["הָאַרְבֶּה","the-locusts"],["וְיֶתֶר","and-the-remainder-of-them"],["הָאַרְבֶּה","the-locusts"],["אָכַל","ate"],["הַיָּלֶק","the-locusts"],["וְיֶתֶר","and-the-remainder-of-them"],["הַיֶּלֶק","the-locusts"],["אָכַל","ate"],["הֶחָסִיל","locusts"],["׃",""]] },
  { num:"ה", words:[["הָקִיצוּ","awake"],["שִׁכּוֹרִים","drunken"],["וּבְכוּ","and-weep"],["וְהֵילִלוּ","and-wail"],["כׇּל־שֹׁתֵי","all-drinkers of"],["יָיִן","wine"],["עַל־עָסִיס","upon-sweet wine"],["כִּי","because"],["נִכְרַת","broken-off"],["מִפִּיכֶם","from-mouth-your"],["׃",""]] },
  { num:"ו", words:[["כִּי־גוֹי","because-nation"],["עָלָה","ascended"],["עַל־אַרְצִי","upon-to-the-earth-my"],["עָצוּם","mighty"],["וְאֵין","and-has-no"],["מִסְפָּר","number"],["שִׁנָּיו","teeth-its"],["שִׁנֵּי","the teeth of"],["אַרְיֵה","a lion"],["וּמְתַלְּעוֹת","and-the fangs of"],["לָבִיא","to-bring"],["לוֹ","him"],["׃",""]] },
  { num:"ז", words:[["שָׂם","set"],["גַּפְנִי","vines-my"],["לְשַׁמָּה","desolate"],["וּתְאֵנָתִי","and-fig trees-my"],["לִקְצָפָה","into-a stump"],["חָשֹׂף","completely"],["חֲשָׂפָהּ","it has stripped bare-it"],["וְהִשְׁלִיךְ","and-he will throw"],["הִלְבִּינוּ","they have become white"],["שָׂרִיגֶיהָ","branches-its"],["׃",""]] },
  { num:"ח", words:[["אֱלִי","wail"],["כִּבְתוּלָה","like-a virgin"],["חֲגֻרַת־שַׂק","girded of-sackcloth"],["עַל־בַּעַל","upon-in-the-yoke"],["נְעוּרֶיהָ","youth-her"],["׃",""]] },
  { num:"ט", words:[["הׇכְרַת","cuts off"],["מִנְחָה","as-a-present"],["וָנֶסֶךְ","and-drink offering"],["מִבֵּית","from-house-of"],["יְהֹוָה","the-LORD"],["אָבְלוּ","they are in mourning"],["הַכֹּהֲנִים","the-priests"],["מְשָׁרְתֵי","ministers-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"י", words:[["שֻׁדַּד","which it was devastated"],["שָׂדֶה","field"],["אָבְלָה","it has dried up"],["אֲדָמָה","ground/earth"],["כִּי","because"],["שֻׁדַּד","which it was devastated"],["דָּגָן","grain"],["הוֹבִישׁ","he dried up"],["תִּירוֹשׁ","the new wine"],["אֻמְלַל","am frail"],["יִצְהָר","Izhar"],["׃",""]] },
  { num:"יא", words:[["הֹבִישׁוּ","they have been put to shame"],["אִכָּרִים","farmers"],["הֵילִילוּ","howl"],["כֹּרְמִים","O vinedressers"],["עַל־חִטָּה","upon-wheat"],["וְעַל־שְׂעֹרָה","and-upon-barley"],["כִּי","because"],["אָבַד","perished"],["קְצִיר","the harvest of"],["שָׂדֶה","field"],["׃",""]] },
  { num:"יב", words:[["הַגֶּפֶן","the-vine"],["הוֹבִישָׁה","it has dried up"],["וְהַתְּאֵנָה","and-the-fig tree"],["אֻמְלָלָה","she languishes"],["רִמּוֹן","Rimmon"],["גַּם־תָּמָר","also-Tamar"],["וְתַפּוּחַ","and-Tappuah"],["כׇּל־עֲצֵי","all-the-trees-of"],["הַשָּׂדֶה","the-field"],["יָבֵשׁוּ","they have dried up"],["כִּי־הֹבִישׁ","because-he will be ashamed"],["שָׂשׂוֹן","joy"],["מִן־בְּנֵי","from-sons-of"],["אָדָם","man"],["׃",""]] },
  { num:"יג", words:[["חִגְרוּ","gird on"],["וְסִפְדוּ","and-mourn"],["הַכֹּהֲנִים","the-priests"],["הֵילִילוּ","howl"],["מְשָׁרְתֵי","ministers-of"],["מִזְבֵּחַ","an altar"],["בֹּאוּ","come"],["לִינוּ","lodge"],["בַשַּׂקִּים","in-the-sackcloth"],["מְשָׁרְתֵי","ministers-of"],["אֱלֹהָי","my-God"],["כִּי","because"],["נִמְנַע","Nmn"],["מִבֵּית","from-house-of"],["אֱלֹהֵיכֶם","your-God"],["מִנְחָה","as-a-present"],["וָנָסֶךְ","and-drink offering"],["׃",""]] },
  { num:"יד", words:[["קַדְּשׁוּ־צוֹם","consecrate-fasting"],["קִרְאוּ","call"],["עֲצָרָה","an assembly"],["אִסְפוּ","gather"],["זְקֵנִים","elders"],["כֹּל","all"],["יֹשְׁבֵי","inhabitants-of"],["הָאָרֶץ","the-earth"],["בֵּית","the-house-of"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיכֶם","your-God"],["וְזַעֲקוּ","and-cry out"],["אֶל־יְהֹוָה","to-the-Lord"],["׃",""]] },
  { num:"טו", words:[["אֲהָהּ","alas!"],["לַיּוֹם","that-the-day"],["כִּי","because"],["קָרוֹב","soon"],["יוֹם","day"],["יְהֹוָה","the-LORD"],["וּכְשֹׁד","and-like-devastation"],["מִשַּׁדַּי","from-the-Almighty"],["יָבוֹא","shall-come"],["׃",""]] },
  { num:"טז", words:[["הֲלוֹא","art-not"],["נֶגֶד","against"],["עֵינֵינוּ","our-eyes"],["אֹכֶל","food"],["נִכְרָת","let us make"],["מִבֵּית","from-house-of"],["אֱלֹהֵינוּ","our-God"],["שִׂמְחָה","joy"],["וָגִיל","and-rejoicing"],["׃",""]] },
  { num:"יז", words:[["עָבְשׁוּ","they have shriveled"],["פְרֻדוֹת","the seeds"],["תַּחַת","under"],["נָשַׁמּוּ","they are appalled"],["אֹצָרוֹת","the storehouses"],["נֶהֶרְסוּ","they-were-destroyed"],["מַמְּגֻרוֹת","the granaries"],["כִּי","because"],["הֹבִישׁ","he will be ashamed"],["דָּגָן","grain"],["׃",""]] },
  { num:"יח", words:[["מַה־נֶּאֶנְחָה","what-it has groaned"],["בְהֵמָה","animals"],["נָבֹכוּ","they have wandered in confusion"],["עֶדְרֵי","flock-my"],["בָקָר","herd"],["כִּי","because"],["אֵין","there-is-no"],["מִרְעֶה","pasture"],["לָהֶם","to-them"],["גַּם־עֶדְרֵי","also-flock-my"],["הַצֹּאן","the-flock"],["נֶאְשָׁמוּ","they have suffered"],["׃",""]] },
  { num:"יט", words:[["אֵלֶיךָ","to-you(f)"],["יְהֹוָה","the-LORD"],["אֶקְרָא","I-read"],["כִּי","because"],["אֵשׁ","fire"],["אָכְלָה","it consumed"],["נְאוֹת","the pastures of"],["מִדְבָּר","wilderness-of"],["וְלֶהָבָה","and-flame"],["לִהֲטָה","it has set ablaze"],["כׇּל־עֲצֵי","all-the-trees-of"],["הַשָּׂדֶה","the-field"],["׃",""]] },
  { num:"כ", words:[["גַּם־בַּהֲמוֹת","also-the animals of"],["שָׂדֶה","field"],["תַּעֲרוֹג","it pants"],["אֵלֶיךָ","to-you(f)"],["כִּי","because"],["יָבְשׁוּ","did-they-wither"],["אֲפִיקֵי","are tubes of"],["מָיִם","water"],["וְאֵשׁ","and-fire"],["אָכְלָה","it consumed"],["נְאוֹת","the pastures of"],["הַמִּדְבָּר","the-wilderness"],["׃",""]] },
];
renderVerseSet(joe_ch1Verses, 'joe-ch1-verses');

var joe_ch2Verses = [
  { num:"א", words:[["תִּקְעוּ","strike"],["שׁוֹפָר","a ram's horn"],["בְּצִיּוֹן","in-Zion"],["וְהָרִיעוּ","and-the-sound a battle signal"],["בְּהַר","while-on-the-mount-of"],["קׇדְשִׁי","the holy things of"],["יִרְגְּזוּ","they trembled"],["כֹּל","all"],["יֹשְׁבֵי","inhabitants-of"],["הָאָרֶץ","the-earth"],["כִּי־בָא","that-came"],["יוֹם־יְהֹוָה","the-day-of-the-LORD"],["כִּי","because"],["קָרוֹב","soon"],["׃",""]] },
  { num:"ב", words:[["יוֹם","day"],["חֹשֶׁךְ","darkness"],["וַאֲפֵלָה","and-darkness"],["יוֹם","day"],["עָנָן","a-cloud"],["וַעֲרָפֶל","and-vapor-of-darkness"],["כְּשַׁחַר","like-the dawn"],["פָּרֻשׂ","spread out"],["עַל־הֶהָרִים","upon-the-mountains"],["עַם","people"],["רַב","great"],["וְעָצוּם","and-mighty"],["כָּמֹהוּ","like-him"],["לֹא","not"],["נִהְיָה","has it occurred"],["מִן־הָעוֹלָם","from-the-world"],["וְאַחֲרָיו","and-after-it"],["לֹא","not"],["יוֹסֵף","Joseph"],["עַד־שְׁנֵי","until-two"],["דּוֹר","generation"],["וָדוֹר","to-generation"],["׃",""]] },
  { num:"ג", words:[["לְפָנָיו","before-him"],["אָכְלָה","it consumed"],["אֵשׁ","fire"],["וְאַחֲרָיו","and-after-it"],["תְּלַהֵט","it kindles"],["לֶהָבָה","a-flame"],["כְּגַן־עֵדֶן","like-the garden of-Eden"],["הָאָרֶץ","the-earth"],["לְפָנָיו","before-him"],["וְאַחֲרָיו","and-after-it"],["מִדְבַּר","the wilderness of"],["שְׁמָמָה","desolate"],["וְגַם־פְּלֵיטָה","and-also-the escaped remnant"],["לֹא־הָיְתָה","not-was(f)"],["לּוֹ","upon-him"],["׃",""]] },
  { num:"ד", words:[["כְּמַרְאֵה","as-the-appearance-of"],["סוּסִים","horses"],["מַרְאֵהוּ","from-saw-his"],["וּכְפָרָשִׁים","and-like-horsemen"],["כֵּן","thus"],["יְרוּצוּן","they run-!"],["׃",""]] },
  { num:"ה", words:[["כְּקוֹל","as-it-were-with-a-voice-of"],["מַרְכָּבוֹת","Marcaboth"],["עַל־רָאשֵׁי","upon-the-heads-of"],["הֶהָרִים","the-mountains"],["יְרַקֵּדוּן","they leap about-!"],["כְּקוֹל","as-it-were-with-a-voice-of"],["לַהַב","the blade of"],["אֵשׁ","fire"],["אֹכְלָה","consuming"],["קָשׁ","stubble"],["כְּעַם","as-the-people-of"],["עָצוּם","mighty"],["עֱרוּךְ","deployed of"],["מִלְחָמָה","war"],["׃",""]] },
  { num:"ו", words:[["מִפָּנָיו","from-before-him"],["יָחִילוּ","they endure"],["עַמִּים","peoples"],["כׇּל־פָּנִים","all-face"],["קִבְּצוּ","gathered-his"],["פָארוּר","a glow"],["׃",""]] },
  { num:"ז", words:[["כְּגִבּוֹרִים","like-warriors"],["יְרֻצוּן","they run-!"],["כְּאַנְשֵׁי","like-men of"],["מִלְחָמָה","war"],["יַעֲלוּ","they-go-up"],["חוֹמָה","a wall"],["וְאִישׁ","and-the-man-of"],["בִּדְרָכָיו","in-His-ways"],["יֵלֵכוּן","they will walk-!"],["וְלֹא","and-not"],["יְעַבְּטוּן","they exchange-!"],["אֹרְחוֹתָם","paths-their"],["׃",""]] },
  { num:"ח", words:[["וְאִישׁ","and-the-man-of"],["אָחִיו","another"],["לֹא","not"],["יִדְחָקוּן","they crowd-!"],["גֶּבֶר","a man"],["בִּמְסִלָּתוֹ","on-track-its"],["יֵלֵכוּן","they will walk-!"],["וּבְעַד","and-for"],["הַשֶּׁלַח","the-Shelah"],["יִפֹּלוּ","they-must-fall"],["לֹא","not"],["יִבְצָעוּ","they stop"],["׃",""]] },
  { num:"ט", words:[["בָּעִיר","in-the-city"],["יָשֹׁקּוּ","they rush"],["בַּחוֹמָה","the-wall"],["יְרֻצוּן","they run-!"],["בַּבָּתִּים","in the-houses"],["יַעֲלוּ","they-go-up"],["בְּעַד","on-behalf-of"],["הַחַלּוֹנִים","the-windows"],["יָבֹאוּ","come"],["כַּגַּנָּב","like-the-thief"],["׃",""]] },
  { num:"י", words:[["לְפָנָיו","before-him"],["רָגְזָה","is-moved"],["אֶרֶץ","the-land-of"],["רָעֲשׁוּ","they shake"],["שָׁמָיִם","heavenly"],["שֶׁמֶשׁ","the-sun-of"],["וְיָרֵחַ","and-moon"],["קָדָרוּ","they become dark"],["וְכוֹכָבִים","and-the stars"],["אָסְפוּ","were-they-gathering"],["נׇגְהָם","the brightness-their"],["׃",""]] },
  { num:"יא", words:[["וַיהֹוָה","and-Yahweh"],["נָתַן","was-given"],["קוֹלוֹ","His-voice"],["לִפְנֵי","before"],["חֵילוֹ","army-his"],["כִּי","because"],["רַב","great"],["מְאֹד","exceedingly"],["מַחֲנֵהוּ","camp-his"],["כִּי","because"],["עָצוּם","mighty"],["עֹשֵׂה","that-doeth"],["דְבָרוֹ","word-his"],["כִּי־גָדוֹל","for-great-is"],["יוֹם־יְהֹוָה","the-day-of-the-LORD"],["וְנוֹרָא","and-terrible"],["מְאֹד","exceedingly"],["וּמִי","and-whoso"],["יְכִילֶנּוּ","will he endure-it"],["׃",""]] },
  { num:"יב", words:[["וְגַם־עַתָּה","and-also-now"],["נְאֻם־יְהֹוָה","says-the-LORD"],["שֻׁבוּ","go back"],["עָדַי","to-me"],["בְּכׇל־לְבַבְכֶם","in-all-your-hearts"],["וּבְצוֹם","and-with-fasting"],["וּבִבְכִי","and-in-the weeping of"],["וּבְמִסְפֵּד","and-with-wailing"],["׃",""]] },
  { num:"יג", words:[["וְקִרְעוּ","and-tear"],["לְבַבְכֶם","your-hearts"],["וְאַל־בִּגְדֵיכֶם","and-do-not-clothing-your(pl)"],["וְשׁוּבוּ","and-return"],["אֶל־יְהֹוָה","to-the-Lord"],["אֱלֹהֵיכֶם","your-God"],["כִּי־חַנּוּן","because-merciful"],["וְרַחוּם","and-merciful"],["הוּא","it"],["אֶרֶךְ","long of"],["אַפַּיִם","with-face"],["וְרַב־חֶסֶד","and-great-mercy"],["וְנִחָם","and-relenting"],["עַל־הָרָעָה","upon-the-evil"],["׃",""]] },
  { num:"יד", words:[["מִי","who"],["יוֹדֵעַ","knows"],["יָשׁוּב","repent"],["וְנִחָם","and-relenting"],["וְהִשְׁאִיר","and-he will leave"],["אַחֲרָיו","after-him"],["בְּרָכָה","a-blessing"],["מִנְחָה","as-a-present"],["וָנֶסֶךְ","and-drink offering"],["לַיהֹוָה","to-Yahweh"],["אֱלֹהֵיכֶם","your-God"],["׃",""]] },
  { num:"טו", words:[["תִּקְעוּ","strike"],["שׁוֹפָר","a ram's horn"],["בְּצִיּוֹן","in-Zion"],["קַדְּשׁוּ־צוֹם","consecrate-fasting"],["קִרְאוּ","call"],["עֲצָרָה","an assembly"],["׃",""]] },
  { num:"טז", words:[["אִסְפוּ־עָם","gather-a-people"],["קַדְּשׁוּ","consecrate"],["קָהָל","worship"],["קִבְצוּ","gather"],["זְקֵנִים","elders"],["אִסְפוּ","gather"],["עוֹלָלִים","infants"],["וְיֹנְקֵי","and-suckling-children of"],["שָׁדָיִם","breasts"],["יֵצֵא","he-go-forth"],["חָתָן","a son-in-law"],["מֵחֶדְרוֹ","from-room-his"],["וְכַלָּה","and-the bride"],["מֵחֻפָּתָהּ","from-chamber-her"],["׃",""]] },
  { num:"יז", words:[["בֵּין","among"],["הָאוּלָם","the-porch"],["וְלַמִּזְבֵּחַ","and-the-altar"],["יִבְכּוּ","they will weep for"],["הַכֹּהֲנִים","the-priests"],["מְשָׁרְתֵי","ministers-of"],["יְהֹוָה","the-LORD"],["וְיֹאמְרוּ","and-shall-say"],["חוּסָה","have-mercy"],["יְהֹוָה","the-LORD"],["עַל־עַמֶּךָ","upon-your-people"],["וְאַל־תִּתֵּן","and-do-not-you-give"],["נַחֲלָתְךָ","your-inheritance"],["לְחֶרְפָּה","for-reproach"],["לִמְשׇׁל־בָּם","to-the-saying-in-them"],["גּוֹיִם","nations/gentiles"],["לָמָּה","why"],["יֹאמְרוּ","shall-say"],["בָעַמִּים","among-the-peoples"],["אַיֵּה","where-is"],["אֱלֹהֵיהֶם","their-God"],["׃",""]] },
  { num:"יח", words:[["וַיְקַנֵּא","and-he became jealous"],["יְהֹוָה","the-LORD"],["לְאַרְצוֹ","to-own land-his"],["וַיַּחְמֹל","and-he-had-compassion"],["עַל־עַמּוֹ","upon-his-people"],["׃",""]] },
  { num:"יט", words:[["וַיַּעַן","and-he-answered"],["יְהֹוָה","the-LORD"],["וַיֹּאמֶר","and-said"],["לְעַמּוֹ","for-His-people"],["הִנְנִי","behold-I"],["שֹׁלֵחַ","sent"],["לָכֶם","to-you"],["אֶת־הַדָּגָן","[ACC]-the-grain"],["וְהַתִּירוֹשׁ","and-the-new wine"],["וְהַיִּצְהָר","and-the-fresh oil"],["וּשְׂבַעְתֶּם","and-you will be satisfied"],["אֹתוֹ","him"],["וְלֹא־אֶתֵּן","and-not-shall-give"],["אֶתְכֶם","you"],["עוֹד","any-more"],["חֶרְפָּה","reproach"],["בַּגּוֹיִם","by-the-nations"],["׃",""]] },
  { num:"כ", words:[["וְאֶת־הַצְּפוֹנִי","and-[ACC]-the-Zephonites"],["אַרְחִיק","I want to be far away"],["מֵעֲלֵיכֶם","from-upon-you"],["וְהִדַּחְתִּיו","and-I will drive away-it"],["אֶל־אֶרֶץ","to-land-of"],["צִיָּה","dry"],["וּשְׁמָמָה","and-desolation"],["אֶת־פָּנָיו","[ACC]-His-face"],["אֶל־הַיָּם","to-the-sea"],["הַקַּדְמֹנִי","the-Kadmonites"],["וְסֹפוֹ","and-end-its"],["אֶל־הַיָּם","to-the-sea"],["הָאַחֲרוֹן","the-last"],["וְעָלָה","and-he-shall-come-up"],["בׇאְשׁוֹ","by-fire-his"],["וְתַעַל","and-it will go up"],["צַחֲנָתוֹ","foul smell-its"],["כִּי","because"],["הִגְדִּיל","he did great things"],["לַעֲשׂוֹת","to-do"],["׃",""]] },
  { num:"כא", words:[["אַל־תִּירְאִי","do-not-you-should-be-afraid"],["אֲדָמָה","ground/earth"],["גִּילִי","rejoicing-my"],["וּשְׂמָחִי","and-rejoice"],["כִּי־הִגְדִּיל","because-he did great things"],["יְהֹוָה","the-LORD"],["לַעֲשׂוֹת","to-do"],["׃",""]] },
  { num:"כב", words:[["אַל־תִּירְאוּ","fear-not"],["בַּהֲמוֹת","the animals of"],["שָׂדַי","the field"],["כִּי","because"],["דָשְׁאוּ","they are green"],["נְאוֹת","the pastures of"],["מִדְבָּר","wilderness-of"],["כִּי־עֵץ","because-a-tree"],["נָשָׂא","bore"],["פִרְיוֹ","its-fruit"],["תְּאֵנָה","a fig tree"],["וָגֶפֶן","and-the vine"],["נָתְנוּ","they-gave"],["חֵילָם","their-forces"],["׃",""]] },
  { num:"כג", words:[["וּבְנֵי","and-sons-of"],["צִיּוֹן","Zion"],["גִּילוּ","be glad"],["וְשִׂמְחוּ","and-rejoice"],["בַּיהֹוָה","is in-Yahweh"],["אֱלֹהֵיכֶם","your-God"],["כִּי־נָתַן","because-was-given"],["לָכֶם","to-you"],["אֶת־הַמּוֹרֶה","[ACC]-the-teacher(f)"],["לִצְדָקָה","for-righteousness"],["וַיּוֹרֶד","and-he-brought-down"],["לָכֶם","to-you"],["גֶּשֶׁם","rain"],["מוֹרֶה","teacher(f)"],["וּמַלְקוֹשׁ","and-spring rain"],["בָּרִאשׁוֹן","in the-first month"],["׃",""]] },
  { num:"כד", words:[["וּמָלְאוּ","and-were-fulfilled"],["הַגֳּרָנוֹת","the-threshing floors"],["בָּר","wild"],["וְהֵשִׁיקוּ","and-they will overflow"],["הַיְקָבִים","the-wine-vats"],["תִּירוֹשׁ","the new wine"],["וְיִצְהָר","and-Izhar"],["׃",""]] },
  { num:"כה", words:[["וְשִׁלַּמְתִּי","and-I will repay"],["לָכֶם","to-you"],["אֶת־הַשָּׁנִים","[ACC]-the-years"],["אֲשֶׁר","which"],["אָכַל","ate"],["הָאַרְבֶּה","the-locusts"],["הַיֶּלֶק","the-locusts"],["וְהֶחָסִיל","and-the-locusts"],["וְהַגָּזָם","and-the-locusts"],["חֵילִי","wealth-my"],["הַגָּדוֹל","the-great"],["אֲשֶׁר","which"],["שִׁלַּחְתִּי","I have sent"],["בָּכֶם","in-you"],["׃",""]] },
  { num:"כו", words:[["וַאֲכַלְתֶּם","and-you-shall-eat"],["אָכוֹל","continuously"],["וְשָׂבוֹעַ","and-we have been satisfied"],["וְהִלַּלְתֶּם","and-you will praise"],["אֶת־שֵׁם","ACC-name-of"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיכֶם","your-God"],["אֲשֶׁר־עָשָׂה","which-did"],["עִמָּכֶם","with-you"],["לְהַפְלִיא","wondrously"],["וְלֹא־יֵבֹשׁוּ","and-not-ashamed-shall-be"],["עַמִּי","my-people"],["לְעוֹלָם","forever"],["׃",""]] },
  { num:"כז", words:[["וִידַעְתֶּם","and-you-shall-know"],["כִּי","because"],["בְקֶרֶב","in-battle"],["יִשְׂרָאֵל","Israel"],["אָנִי","I"],["וַאֲנִי","and-I"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיכֶם","your-God"],["וְאֵין","and-has-no"],["עוֹד","any-more"],["וְלֹא־יֵבֹשׁוּ","and-not-ashamed-shall-be"],["עַמִּי","my-people"],["לְעוֹלָם","forever"],["׃",""]] },
];
renderVerseSet(joe_ch2Verses, 'joe-ch2-verses');

var joe_ch3Verses = [
  { num:"א", words:[["וְהָיָה","and-be"],["אַחֲרֵי־כֵן","hereafter"],["אֶשְׁפּוֹךְ","I will pour out"],["אֶת־רוּחִי","[ACC]-again"],["עַל־כׇּל־בָּשָׂר","upon-all-the-flesh"],["וְנִבְּאוּ","and-prophesied"],["בְּנֵיכֶם","your-children"],["וּבְנוֹתֵיכֶם","and-daughters-your"],["זִקְנֵיכֶם","elders-your"],["חֲלֹמוֹת","dreams"],["יַחֲלֹמוּן","they will dream-!"],["בַּחוּרֵיכֶם","young men-your"],["חֶזְיֹנוֹת","visions"],["יִרְאוּ","shall-see"],["׃",""]] },
  { num:"ב", words:[["וְגַם","and-also"],["עַל־הָעֲבָדִים","upon-the-servants"],["וְעַל־הַשְּׁפָחוֹת","and-upon-the-maidservants"],["בַּיָּמִים","in-the-days"],["הָהֵמָּה","those"],["אֶשְׁפּוֹךְ","I will pour out"],["אֶת־רוּחִי","[ACC]-again"],["׃",""]] },
  { num:"ג", words:[["וְנָתַתִּי","and-I-will-give"],["מוֹפְתִים","wonders"],["בַּשָּׁמַיִם","in-the-heavens"],["וּבָאָרֶץ","and-in-the-earth"],["דָּם","blood"],["וָאֵשׁ","and-fire"],["וְתִימְרוֹת","and-pillars-of"],["עָשָׁן","smoke"],["׃",""]] },
  { num:"ד", words:[["הַשֶּׁמֶשׁ","the-sun"],["יֵהָפֵךְ","it will be turned over"],["לְחֹשֶׁךְ","to-darkness"],["וְהַיָּרֵחַ","and-the-moon"],["לְדָם","for-blood"],["לִפְנֵי","before"],["בּוֹא","coming-of"],["יוֹם","day"],["יְהֹוָה","the-LORD"],["הַגָּדוֹל","the-great"],["וְהַנּוֹרָא","and-the-awesome"],["׃",""]] },
  { num:"ה", words:[["וְהָיָה","and-be"],["כֹּל","all"],["אֲשֶׁר־יִקְרָא","whose-calls"],["בְּשֵׁם","by-name"],["יְהֹוָה","the-LORD"],["יִמָּלֵט","shall-be-delivered"],["כִּי","because"],["בְּהַר־צִיּוֹן","while-on-the-mount-of-Zion"],["וּבִירוּשָׁלַ͏ִם","and-in-Jerusalem"],["תִּהְיֶה","shall-be"],["פְלֵיטָה","an escape"],["כַּאֲשֶׁר","when/as"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["וּבַשְּׂרִידִים","and-among the-survivors"],["אֲשֶׁר","which"],["יְהֹוָה","the-LORD"],["קֹרֵא","I-call"],["׃",""]] },
];
renderVerseSet(joe_ch3Verses, 'joe-ch3-verses');

var joe_ch4Verses = [
  { num:"א", words:[["כִּי","because"],["הִנֵּה","behold"],["בַּיָּמִים","in-the-days"],["הָהֵמָּה","those"],["וּבָעֵת","and-at-that-time"],["הַהִיא","that"],["אֲשֶׁר","which"],["(אשוב)","I-return"],["[אָשִׁיב]","I will return"],["אֶת־שְׁבוּת","[ACC]-the-captivity-of"],["יְהוּדָה","Judah"],["וִירוּשָׁלָ͏ִם","and-Jerusalem"],["׃",""]] },
  { num:"ב", words:[["וְקִבַּצְתִּי","and-gathered-my"],["אֶת־כׇּל־הַגּוֹיִם","[ACC]-all-the-nations"],["וְהוֹרַדְתִּים","and-I will bring down-them"],["אֶל־עֵמֶק","to-the-valley-of"],["יְהוֹשָׁפָט","Jehoshaphat"],["וְנִשְׁפַּטְתִּי","and-I will enter into judgment"],["עִמָּם","with-them"],["שָׁם","there"],["עַל־עַמִּי","upon-My-people"],["וְנַחֲלָתִי","and-inheritance-my"],["יִשְׂרָאֵל","Israel"],["אֲשֶׁר","which"],["פִּזְּרוּ","they-scattered"],["בַגּוֹיִם","by-the-nations"],["וְאֶת־אַרְצִי","and-[ACC]-to-the-earth-my"],["חִלֵּקוּ","they have divided up"],["׃",""]] },
  { num:"ג", words:[["וְאֶל־עַמִּי","and-toward-my-people"],["יַדּוּ","they have cast"],["גוֹרָל","a lot"],["וַיִּתְּנוּ","and-they-gave"],["הַיֶּלֶד","the-a-child"],["בַּזּוֹנָה","for the-prostitute"],["וְהַיַּלְדָּה","and-the-girl"],["מָכְרוּ","they sold"],["בַיַּיִן","for-the-wine"],["וַיִּשְׁתּוּ","and-they-did-drink"],["׃",""]] },
  { num:"ד", words:[["וְגַם","and-also"],["מָה־אַתֶּם","what-you-are"],["לִי","to-me"],["צֹר","a flint"],["וְצִידוֹן","and-Sidon"],["וְכֹל","and-the-whole"],["גְּלִילוֹת","the territories of"],["פְּלָשֶׁת","Philistia"],["הַגְּמוּל","the-¿-recompense"],["אַתֶּם","you-are"],["מְשַׁלְּמִים","repaying"],["עָלָי","against-me"],["וְאִם־גֹּמְלִים","and-if-are repaying"],["אַתֶּם","you-are"],["עָלַי","I-must"],["קַל","swiftly"],["מְהֵרָה","soon"],["אָשִׁיב","recall"],["גְּמֻלְכֶם","recompense-your"],["בְּרֹאשְׁכֶם","on-head-your"],["׃",""]] },
  { num:"ה", words:[["אֲשֶׁר־כַּסְפִּי","whose-silver-my"],["וּזְהָבִי","and-gold-my"],["לְקַחְתֶּם","to-take-their"],["וּמַחֲמַדַּי","and-desirable things-my"],["הַטֹּבִים","the-good"],["הֲבֵאתֶם","have you brought"],["לְהֵיכְלֵיכֶם","to-own temples-your"],["׃",""]] },
  { num:"ו", words:[["וּבְנֵי","and-sons-of"],["יְהוּדָה","Judah"],["וּבְנֵי","and-sons-of"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["מְכַרְתֶּם","you sold"],["לִבְנֵי","unto-the-children-of"],["הַיְּוָנִים","the-Greeks"],["לְמַעַן","in-order-that"],["הַרְחִיקָם","to remove far away-them"],["מֵעַל","from-upon"],["גְּבוּלָם","their-territory"],["׃",""]] },
  { num:"ז", words:[["הִנְנִי","behold-I"],["מְעִירָם","am about to rouse-them"],["מִן־הַמָּקוֹם","from-the-place"],["אֲשֶׁר־מְכַרְתֶּם","whose-you sold"],["אֹתָם","them"],["שָׁמָּה","there"],["וַהֲשִׁבֹתִי","I-will-return"],["גְמֻלְכֶם","recompense-your"],["בְּרֹאשְׁכֶם","on-head-your"],["׃",""]] },
  { num:"ח", words:[["וּמָכַרְתִּי","and-I will sell"],["אֶת־בְּנֵיכֶם","[ACC]-your-children"],["וְאֶת־בְּנוֹתֵיכֶם","and-[ACC]-daughters-your"],["בְּיַד","in-hand-of"],["בְּנֵי","the-sons-of"],["יְהוּדָה","Judah"],["וּמְכָרוּם","and-they will sell-them"],["לִשְׁבָאיִם","to-the Sabeans"],["אֶל־גּוֹי","against-nation"],["רָחוֹק","far"],["כִּי","because"],["יְהֹוָה","the-LORD"],["דִּבֵּר","spoke"],["׃",""]] },
  { num:"ט", words:[["קִרְאוּ־זֹאת","call-this"],["בַּגּוֹיִם","by-the-nations"],["קַדְּשׁוּ","consecrate"],["מִלְחָמָה","war"],["הָעִירוּ","the-arouse"],["הַגִּבּוֹרִים","the-mighty men"],["יִגְּשׁוּ","let them approach"],["יַעֲלוּ","they-go-up"],["כֹּל","all"],["אַנְשֵׁי","the-men-of"],["הַמִּלְחָמָה","the-battle"],["׃",""]] },
  { num:"י", words:[["כֹּתּוּ","beat"],["אִתֵּיכֶם","plowshares-your"],["לַחֲרָבוֹת","into-swords"],["וּמַזְמְרֹתֵיכֶם","and-pruning knives-your"],["לִרְמָחִים","into-spears"],["הַחַלָּשׁ","the-weak"],["יֹאמַר","He-says"],["גִּבּוֹר","mighty"],["אָנִי","I"],["׃",""]] },
  { num:"יא", words:[["עוּשׁוּ","hurry"],["וָבֹאוּ","and-come"],["כׇל־הַגּוֹיִם","all-the-nations"],["מִסָּבִיב","round-about"],["וְנִקְבָּצוּ","and-they will gather"],["שָׁמָּה","there"],["הַנְחַת","bring down"],["יְהֹוָה","the-LORD"],["גִּבּוֹרֶיךָ","warriors-your"],["׃",""]] },
  { num:"יב", words:[["יֵעוֹרוּ","they-shall-awake"],["וְיַעֲלוּ","and-they-go-up"],["הַגּוֹיִם","the-nations"],["אֶל־עֵמֶק","to-the-valley-of"],["יְהוֹשָׁפָט","Jehoshaphat"],["כִּי","because"],["שָׁם","there"],["אֵשֵׁב","I will remain"],["לִשְׁפֹּט","to-judge"],["אֶת־כׇּל־הַגּוֹיִם","[ACC]-all-the-nations"],["מִסָּבִיב","round-about"],["׃",""]] },
  { num:"יג", words:[["שִׁלְחוּ","send"],["מַגָּל","sickle"],["כִּי","because"],["בָשַׁל","it has grown ripe"],["קָצִיר","harvest"],["בֹּאוּ","come"],["רְדוּ","Rdo"],["כִּי־מָלְאָה","for-the-earth-shall-be-full-of"],["גַּת","Gath"],["הֵשִׁיקוּ","they are overflowing"],["הַיְקָבִים","the-wine-vats"],["כִּי","because"],["רַבָּה","much"],["רָעָתָם","their-wickedness"],["׃",""]] },
  { num:"יד", words:[["הֲמוֹנִים","multitudes"],["הֲמוֹנִים","multitudes"],["בְּעֵמֶק","in-the-valley-of"],["הֶחָרוּץ","decision"],["כִּי","because"],["קָרוֹב","soon"],["יוֹם","day"],["יְהֹוָה","the-LORD"],["בְּעֵמֶק","in-the-valley-of"],["הֶחָרוּץ","decision"],["׃",""]] },
  { num:"טו", words:[["שֶׁמֶשׁ","the-sun-of"],["וְיָרֵחַ","and-moon"],["קָדָרוּ","they become dark"],["וְכוֹכָבִים","and-the stars"],["אָסְפוּ","were-they-gathering"],["נׇגְהָם","the brightness-their"],["׃",""]] },
  { num:"טז", words:[["וַיהֹוָה","and-Yahweh"],["מִצִּיּוֹן","out-of-Zion"],["יִשְׁאָג","he will roar"],["וּמִירוּשָׁלַ͏ִם","and-from-Jerusalem"],["יִתֵּן","shall-give"],["קוֹלוֹ","His-voice"],["וְרָעֲשׁוּ","and-they will shake"],["שָׁמַיִם","the-heavens"],["וָאָרֶץ","and-earth"],["וַיהֹוָה","and-Yahweh"],["מַחֲסֶה","is a refuge"],["לְעַמּוֹ","for-His-people"],["וּמָעוֹז","and-is the refuge of"],["לִבְנֵי","unto-the-children-of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"יז", words:[["וִידַעְתֶּם","and-you-shall-know"],["כִּי","because"],["אֲנִי","I"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיכֶם","your-God"],["שֹׁכֵן","dwells"],["בְּצִיּוֹן","in-Zion"],["הַר־קׇדְשִׁי","mountain-the holy things of"],["וְהָיְתָה","and-it-be"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["קֹדֶשׁ","holy"],["וְזָרִים","and-strangers"],["לֹא־יַעַבְרוּ־בָהּ","not-they-shall-pass-in-her"],["עוֹד","any-more"],["׃",""]] },
  { num:"יח", words:[["וְהָיָה","and-be"],["בַיּוֹם","by-the-day"],["הַהוּא","that"],["יִטְּפוּ","they will drip"],["הֶהָרִים","the-mountains"],["עָסִיס","sweet wine"],["וְהַגְּבָעוֹת","and-the-hills"],["תֵּלַכְנָה","as-they-go"],["חָלָב","milk"],["וְכׇל־אֲפִיקֵי","and-all-are tubes of"],["יְהוּדָה","Judah"],["יֵלְכוּ","they-should-travel"],["מָיִם","water"],["וּמַעְיָן","and-a spring"],["מִבֵּית","from-house-of"],["יְהֹוָה","the-LORD"],["יֵצֵא","he-go-forth"],["וְהִשְׁקָה","and-it watered"],["אֶת־נַחַל","[ACC]-a-river-of"],["הַשִּׁטִּים","the-shittim"],["׃",""]] },
  { num:"יט", words:[["מִצְרַיִם","Egypt"],["לִשְׁמָמָה","to-desolate"],["תִהְיֶה","be"],["וֶאֱדוֹם","and-Edom"],["לְמִדְבַּר","to-the wilderness of"],["שְׁמָמָה","desolate"],["תִּהְיֶה","shall-be"],["מֵחֲמַס","from-the violence of"],["בְּנֵי","the-sons-of"],["יְהוּדָה","Judah"],["אֲשֶׁר־שָׁפְכוּ","whose-did-pour-out"],["דָם־נָקִיא","blood-innocent"],["בְּאַרְצָם","in-their-land"],["׃",""]] },
  { num:"כ", words:[["וִיהוּדָה","and-Judah"],["לְעוֹלָם","forever"],["תֵּשֵׁב","shall-sit"],["וִירוּשָׁלַ͏ִם","and-Jerusalem"],["לְדוֹר","to-generation"],["וָדוֹר","to-generation"],["׃",""]] },
  { num:"כא", words:[["וְנִקֵּיתִי","and-am-rid"],["דָּמָם","their-blood"],["לֹא־נִקֵּיתִי","not-I will be free"],["וַיהֹוָה","and-Yahweh"],["שֹׁכֵן","dwells"],["בְּצִיּוֹן","in-Zion"],["׃",""]] },
];
renderVerseSet(joe_ch4Verses, 'joe-ch4-verses');

})();
