// ot_verses/joe.js — Joel verse data
(function() {
var joe_ch1Verses = [
  { num:"א", words:[["דְּבַר־יְהֹוָה","the word of the LORD"],["אֲשֶׁר","which"],["הָיָה","was"],["אֶל־יוֹאֵל","to Joel"],["בֶּן־פְּתוּאֵל","son of Pethuel"],["׃",""]] },
  { num:"ב", words:[["שִׁמְעוּ־זֹאת","hear this"],["הַזְּקֵנִים","the elders"],["וְהַאֲזִינוּ","and listen"],["כֹּל","all"],["יוֹשְׁבֵי","the inhabitants of"],["הָאָרֶץ","the land"],["הֶהָיְתָה","has it happened"],["זֹּאת","this"],["בִּימֵיכֶם","in your days"],["וְאִם","and if"],["בִּימֵי","in the days of"],["אֲבֹתֵיכֶם","your fathers"],["׃",""]] },
  { num:"ג", words:[["עָלֶיהָ","upon it"],["לִבְנֵיכֶם","your sons"],["סַפֵּרוּ","recount"],["וּבְנֵיכֶם","and your sons"],["לִבְנֵיהֶם","to their sons"],["וּבְנֵיהֶם","and their sons"],["לְדוֹר","to generation"],["אַחֵר","other"],["׃",""]] },
  { num:"ד", words:[["יֶתֶר","the remainder of"],["הַגָּזָם","the palmerworm"],["אָכַל","ate"],["הָאַרְבֶּה","the locust"],["וְיֶתֶר","and the rest of"],["הָאַרְבֶּה","the locust"],["אָכַל","ate"],["הַיָּלֶק","the cankerworm"],["וְיֶתֶר","and the rest of"],["הַיֶּלֶק","the cankerworm"],["אָכַל","ate"],["הֶחָסִיל","the caterpiller"],["׃",""]] },
  { num:"ה", words:[["הָקִיצוּ","awake"],["שִׁכּוֹרִים","drunken"],["וּבְכוּ","and weep"],["וְהֵילִלוּ","and wail"],["כׇּל־שֹׁתֵי","all drinkers of"],["יָיִן","wine"],["עַל־עָסִיס","because of the new wine"],["כִּי","because"],["נִכְרַת","was cut off"],["מִפִּיכֶם","from your mouth"],["׃",""]] },
  { num:"ו", words:[["כִּי־גוֹי","because nation"],["עָלָה","ascended"],["עַל־אַרְצִי","upon my land"],["עָצוּם","mighty"],["וְאֵין","and there is no"],["מִסְפָּר","number"],["שִׁנָּיו","its teeth"],["שִׁנֵּי","the teeth of"],["אַרְיֵה","a lion"],["וּמְתַלְּעוֹת","and the fangs of"],["לָבִיא","a great lion"],["לוֹ","to him"],["׃",""]] },
  { num:"ז", words:[["שָׂם","set"],["גַּפְנִי","my vines"],["לְשַׁמָּה","desolate"],["וּתְאֵנָתִי","and my fig trees"],["לִקְצָפָה","and barked"],["חָשֹׂף","surely"],["חֲשָׂפָהּ","it has stripped bare it"],["וְהִשְׁלִיךְ","and cast it away"],["הִלְבִּינוּ","they have become white"],["שָׂרִיגֶיהָ","its branches"],["׃",""]] },
  { num:"ח", words:[["אֱלִי","wail"],["כִּבְתוּלָה","like a virgin"],["חֲגֻרַת־שַׂק","girded of sackcloth"],["עַל־בַּעַל","for the husband of"],["נְעוּרֶיהָ","her youth"],["׃",""]] },
  { num:"ט", words:[["הׇכְרַת","is cut off"],["מִנְחָה","a grain offering"],["וָנֶסֶךְ","and drink offering"],["מִבֵּית","from the house of"],["יְהֹוָה","the LORD"],["אָבְלוּ","they are in mourning"],["הַכֹּהֲנִים","the priests"],["מְשָׁרְתֵי","ministers of"],["יְהֹוָה","the LORD"],["׃",""]] },
  { num:"י", words:[["שֻׁדַּד","which it was devastated"],["שָׂדֶה","field"],["אָבְלָה","it has dried up"],["אֲדָמָה","ground"],["כִּי","for"],["שֻׁדַּד","which it was devastated"],["דָּגָן","grain"],["הוֹבִישׁ","is dried up"],["תִּירוֹשׁ","the new wine"],["אֻמְלַל","languisheth"],["יִצְהָר","fresh oil"],["׃",""]] },
  { num:"יא", words:[["הֹבִישׁוּ","be you ashamed"],["אִכָּרִים","farmers"],["הֵילִילוּ","howl"],["כֹּרְמִים","O vinedressers"],["עַל־חִטָּה","upon wheat"],["וְעַל־שְׂעֹרָה","and upon barley"],["כִּי","because"],["אָבַד","perished"],["קְצִיר","the harvest of"],["שָׂדֶה","field"],["׃",""]] },
  { num:"יב", words:[["הַגֶּפֶן","the vine"],["הוֹבִישָׁה","it has dried up"],["וְהַתְּאֵנָה","and the fig tree"],["אֻמְלָלָה","she languishes"],["רִמּוֹן","the pomegranate tree"],["גַּם־תָּמָר","also the palm tree"],["וְתַפּוּחַ","and the apple tree"],["כׇּל־עֲצֵי","all the trees of"],["הַשָּׂדֶה","the field"],["יָבֵשׁוּ","they have dried up"],["כִּי־הֹבִישׁ","because is withered"],["שָׂשׂוֹן","joy"],["מִן־בְּנֵי","from the sons of"],["אָדָם","man"],["׃",""]] },
  { num:"יג", words:[["חִגְרוּ","gird on"],["וְסִפְדוּ","and mourn"],["הַכֹּהֲנִים","the priests"],["הֵילִילוּ","howl"],["מְשָׁרְתֵי","ministers of"],["מִזְבֵּחַ","the altar"],["בֹּאוּ","come"],["לִינוּ","lodge"],["בַשַּׂקִּים","in the sackcloth"],["מְשָׁרְתֵי","ministers of"],["אֱלֹהָי","my God"],["כִּי","for"],["נִמְנַע","is withheld"],["מִבֵּית","from the house of"],["אֱלֹהֵיכֶם","your God"],["מִנְחָה","a grain offering"],["וָנָסֶךְ","and drink offering"],["׃",""]] },
  { num:"יד", words:[["קַדְּשׁוּ־צוֹם","consecrate fasting"],["קִרְאוּ","call"],["עֲצָרָה","an assembly"],["אִסְפוּ","gather"],["זְקֵנִים","elders"],["כֹּל","all"],["יֹשְׁבֵי","inhabitants of"],["הָאָרֶץ","the earth"],["בֵּית","the house of"],["יְהֹוָה","the LORD"],["אֱלֹהֵיכֶם","your God"],["וְזַעֲקוּ","and cry out"],["אֶל־יְהֹוָה","to the LORD"],["׃",""]] },
  { num:"טו", words:[["אֲהָהּ","alas!"],["לַיּוֹם","that the day"],["כִּי","because"],["קָרוֹב","soon"],["יוֹם","day"],["יְהֹוָה","the LORD"],["וּכְשֹׁד","and like devastation"],["מִשַּׁדַּי","from the Almighty"],["יָבוֹא","shall come"],["׃",""]] },
  { num:"טז", words:[["הֲלוֹא","is it not"],["נֶגֶד","against"],["עֵינֵינוּ","our eyes"],["אֹכֶל","food"],["נִכְרָת","is cut off"],["מִבֵּית","from the house of"],["אֱלֹהֵינוּ","our God"],["שִׂמְחָה","joy"],["וָגִיל","and rejoicing"],["׃",""]] },
  { num:"יז", words:[["עָבְשׁוּ","is rotten"],["פְרֻדוֹת","the seeds"],["תַּחַת","under"],["מֶגְרְפֹתֵיהֶם","their clods"],["נָשַׁמּוּ","they are appalled"],["אֹצָרוֹת","the storehouses"],["נֶהֶרְסוּ","they were destroyed"],["מַמְּגֻרוֹת","the granaries"],["כִּי","for"],["הֹבִישׁ","is withered"],["דָּגָן","grain"],["׃",""]] },
  { num:"יח", words:[["מַה־נֶּאֶנְחָה","what it has groaned"],["בְהֵמָה","animals"],["נָבֹכוּ","they have wandered in confusion"],["עֶדְרֵי","the herds of"],["בָקָר","herd"],["כִּי","because"],["אֵין","there is no"],["מִרְעֶה","pasture"],["לָהֶם","to them"],["גַּם־עֶדְרֵי","also the flocks of"],["הַצֹּאן","the flock"],["נֶאְשָׁמוּ","are made desolate"],["׃",""]] },
  { num:"יט", words:[["אֵלֶיךָ","to you"],["יְהֹוָה","the LORD"],["אֶקְרָא","I will cry"],["כִּי","for"],["אֵשׁ","fire"],["אָכְלָה","it consumed"],["נְאוֹת","the pastures of"],["מִדְבָּר","wilderness of"],["וְלֶהָבָה","and flame"],["לִהֲטָה","it has set ablaze"],["כׇּל־עֲצֵי","all the trees of"],["הַשָּׂדֶה","the field"],["׃",""]] },
  { num:"כ", words:[["גַּם־בַּהֲמוֹת","also the animals of"],["שָׂדֶה","field"],["תַּעֲרוֹג","it pants"],["אֵלֶיךָ","to you"],["כִּי","for"],["יָבְשׁוּ","are dried up"],["אֲפִיקֵי","the rivers of"],["מָיִם","water"],["וְאֵשׁ","and fire"],["אָכְלָה","it consumed"],["נְאוֹת","the pastures of"],["הַמִּדְבָּר","the wilderness"],["׃",""]] },
];
renderVerseSet(joe_ch1Verses, 'joe-ch1-verses');

var joe_ch2Verses = [
  { num:"א", words:[["תִּקְעוּ","strike"],["שׁוֹפָר","a ram's horn"],["בְּצִיּוֹן","in Zion"],["וְהָרִיעוּ","and the sound a battle signal"],["בְּהַר","on the mount of"],["קׇדְשִׁי","my holiness"],["יִרְגְּזוּ","let tremble"],["כֹּל","all"],["יֹשְׁבֵי","inhabitants of"],["הָאָרֶץ","the land"],["כִּי־בָא","that came"],["יוֹם־יְהֹוָה","the day of the LORD"],["כִּי","because"],["קָרוֹב","soon"],["׃",""]] },
  { num:"ב", words:[["יוֹם","day"],["חֹשֶׁךְ","darkness"],["וַאֲפֵלָה","and darkness"],["יוֹם","day"],["עָנָן","a cloud"],["וַעֲרָפֶל","and vapor of darkness"],["כְּשַׁחַר","like the dawn"],["פָּרֻשׂ","spread out"],["עַל־הֶהָרִים","upon the mountains"],["עַם","people"],["רַב","great"],["וְעָצוּם","and mighty"],["כָּמֹהוּ","like it"],["לֹא","not"],["נִהְיָה","has it occurred"],["מִן־הָעוֹלָם","from the world"],["וְאַחֲרָיו","and after it"],["לֹא","not"],["יוֹסֵף","shall be again"],["עַד־שְׁנֵי","even to the years of"],["דּוֹר","generation"],["וָדוֹר","to generation"],["׃",""]] },
  { num:"ג", words:[["לְפָנָיו","before him"],["אָכְלָה","it consumed"],["אֵשׁ","fire"],["וְאַחֲרָיו","and after it"],["תְּלַהֵט","it kindles"],["לֶהָבָה","a flame"],["כְּגַן־עֵדֶן","like the garden of Eden"],["הָאָרֶץ","the land"],["לְפָנָיו","before him"],["וְאַחֲרָיו","and after it"],["מִדְבַּר","the wilderness of"],["שְׁמָמָה","desolate"],["וְגַם־פְּלֵיטָה","and also the escaped remnant"],["לֹא־הָיְתָה","not was"],["לּוֹ","to him"],["׃",""]] },
  { num:"ד", words:[["כְּמַרְאֵה","as the appearance of"],["סוּסִים","horses"],["מַרְאֵהוּ","is their appearance"],["וּכְפָרָשִׁים","and like horsemen"],["כֵּן","thus"],["יְרוּצוּן","they run"],["׃",""]] },
  { num:"ה", words:[["כְּקוֹל","like the noise of"],["מַרְכָּבוֹת","chariots"],["עַל־רָאשֵׁי","upon the heads of"],["הֶהָרִים","the mountains"],["יְרַקֵּדוּן","they leap about"],["כְּקוֹל","like the noise of"],["לַהַב","a flame of"],["אֵשׁ","fire"],["אֹכְלָה","consuming"],["קָשׁ","stubble"],["כְּעַם","as the people of"],["עָצוּם","mighty"],["עֱרוּךְ","deployed of"],["מִלְחָמָה","war"],["׃",""]] },
  { num:"ו", words:[["מִפָּנָיו","from before him"],["יָחִילוּ","shall be much pained"],["עַמִּים","peoples"],["כׇּל־פָּנִים","all face"],["קִבְּצוּ","shall gather"],["פָארוּר","blackness"],["׃",""]] },
  { num:"ז", words:[["כְּגִבּוֹרִים","like warriors"],["יְרֻצוּן","they run"],["כְּאַנְשֵׁי","like men of"],["מִלְחָמָה","war"],["יַעֲלוּ","they go up"],["חוֹמָה","a wall"],["וְאִישׁ","and a man"],["בִּדְרָכָיו","in his ways"],["יֵלֵכוּן","they will walk"],["וְלֹא","and not"],["יְעַבְּטוּן","they break their ranks"],["אֹרְחוֹתָם","their paths"],["׃",""]] },
  { num:"ח", words:[["וְאִישׁ","and a man"],["אָחִיו","his brother"],["לֹא","not"],["יִדְחָקוּן","they crowd"],["גֶּבֶר","a man"],["בִּמְסִלָּתוֹ","on its track"],["יֵלֵכוּן","they will walk"],["וּבְעַד","and for"],["הַשֶּׁלַח","the sword"],["יִפֹּלוּ","they must fall"],["לֹא","not"],["יִבְצָעוּ","they be wounded"],["׃",""]] },
  { num:"ט", words:[["בָּעִיר","in the city"],["יָשֹׁקּוּ","they rush"],["בַּחוֹמָה","the wall"],["יְרֻצוּן","they run"],["בַּבָּתִּים","in the houses"],["יַעֲלוּ","they go up"],["בְּעַד","through"],["הַחַלּוֹנִים","the windows"],["יָבֹאוּ","come"],["כַּגַּנָּב","like the thief"],["׃",""]] },
  { num:"י", words:[["לְפָנָיו","before him"],["רָגְזָה","is moved"],["אֶרֶץ","the earth"],["רָעֲשׁוּ","they shake"],["שָׁמָיִם","the heavens"],["שֶׁמֶשׁ","the sun"],["וְיָרֵחַ","and moon"],["קָדָרוּ","they become dark"],["וְכוֹכָבִים","and the stars"],["אָסְפוּ","shall withdraw"],["נׇגְהָם","their shining"],["׃",""]] },
  { num:"יא", words:[["וַיהֹוָה","and the LORD"],["נָתַן","gave"],["קוֹלוֹ","His voice"],["לִפְנֵי","before"],["חֵילוֹ","his army"],["כִּי","because"],["רַב","great"],["מְאֹד","exceedingly"],["מַחֲנֵהוּ","his camp"],["כִּי","because"],["עָצוּם","mighty"],["עֹשֵׂה","that executeth"],["דְבָרוֹ","his word"],["כִּי־גָדוֹל","for great is"],["יוֹם־יְהֹוָה","the day of the LORD"],["וְנוֹרָא","and terrible"],["מְאֹד","exceedingly"],["וּמִי","and whoso"],["יְכִילֶנּוּ","will he endure it"],["׃",""]] },
  { num:"יב", words:[["וְגַם־עַתָּה","and also now"],["נְאֻם־יְהֹוָה","says the LORD"],["שֻׁבוּ","go back"],["עָדַי","to me"],["בְּכׇל־לְבַבְכֶם","in all your hearts"],["וּבְצוֹם","and with fasting"],["וּבִבְכִי","and in the weeping of"],["וּבְמִסְפֵּד","and with wailing"],["׃",""]] },
  { num:"יג", words:[["וְקִרְעוּ","and tear"],["לְבַבְכֶם","your hearts"],["וְאַל־בִּגְדֵיכֶם","and not your garments"],["וְשׁוּבוּ","and return"],["אֶל־יְהֹוָה","to the LORD"],["אֱלֹהֵיכֶם","your God"],["כִּי־חַנּוּן","because merciful"],["וְרַחוּם","and merciful"],["הוּא","he"],["אֶרֶךְ","slow to"],["אַפַּיִם","anger"],["וְרַב־חֶסֶד","and great mercy"],["וְנִחָם","and relenting"],["עַל־הָרָעָה","upon the evil"],["׃",""]] },
  { num:"יד", words:[["מִי","who"],["יוֹדֵעַ","knows"],["יָשׁוּב","he shall return"],["וְנִחָם","and relenting"],["וְהִשְׁאִיר","and he will leave"],["אַחֲרָיו","after him"],["בְּרָכָה","a blessing"],["מִנְחָה","a grain offering"],["וָנֶסֶךְ","and drink offering"],["לַיהֹוָה","to the LORD"],["אֱלֹהֵיכֶם","your God"],["׃",""]] },
  { num:"טו", words:[["תִּקְעוּ","strike"],["שׁוֹפָר","a ram's horn"],["בְּצִיּוֹן","in Zion"],["קַדְּשׁוּ־צוֹם","consecrate fasting"],["קִרְאוּ","call"],["עֲצָרָה","an assembly"],["׃",""]] },
  { num:"טז", words:[["אִסְפוּ־עָם","gather a people"],["קַדְּשׁוּ","consecrate"],["קָהָל","the congregation"],["קִבְצוּ","gather"],["זְקֵנִים","elders"],["אִסְפוּ","gather"],["עוֹלָלִים","infants"],["וְיֹנְקֵי","and suckling children of"],["שָׁדָיִם","breasts"],["יֵצֵא","he go forth"],["חָתָן","a son in law"],["מֵחֶדְרוֹ","from his room"],["וְכַלָּה","and the bride"],["מֵחֻפָּתָהּ","from her chamber"],["׃",""]] },
  { num:"יז", words:[["בֵּין","among"],["הָאוּלָם","the porch"],["וְלַמִּזְבֵּחַ","and the altar"],["יִבְכּוּ","they will weep for"],["הַכֹּהֲנִים","the priests"],["מְשָׁרְתֵי","ministers of"],["יְהֹוָה","the LORD"],["וְיֹאמְרוּ","and shall say"],["חוּסָה","have mercy"],["יְהֹוָה","the LORD"],["עַל־עַמֶּךָ","upon your people"],["וְאַל־תִּתֵּן","and do not give"],["נַחֲלָתְךָ","your inheritance"],["לְחֶרְפָּה","for reproach"],["לִמְשׇׁל־בָּם","that they should rule over them"],["גּוֹיִם","nations"],["לָמָּה","why"],["יֹאמְרוּ","shall say"],["בָעַמִּים","among the peoples"],["אַיֵּה","where is"],["אֱלֹהֵיהֶם","their God"],["׃",""]] },
  { num:"יח", words:[["וַיְקַנֵּא","and became jealous"],["יְהֹוָה","the LORD"],["לְאַרְצוֹ","to his own land"],["וַיַּחְמֹל","and he had compassion"],["עַל־עַמּוֹ","upon his people"],["׃",""]] },
  { num:"יט", words:[["וַיַּעַן","and answered"],["יְהֹוָה","the LORD"],["וַיֹּאמֶר","and said"],["לְעַמּוֹ","for His people"],["הִנְנִי","behold I"],["שֹׁלֵחַ","sent"],["לָכֶם","to you"],["אֶת־הַדָּגָן","the grain"],["וְהַתִּירוֹשׁ","and the new wine"],["וְהַיִּצְהָר","and the fresh oil"],["וּשְׂבַעְתֶּם","and you will be satisfied"],["אֹתוֹ","him"],["וְלֹא־אֶתֵּן","and not shall give"],["אֶתְכֶם","you"],["עוֹד","any more"],["חֶרְפָּה","reproach"],["בַּגּוֹיִם","among the nations"],["׃",""]] },
  { num:"כ", words:[["וְאֶת־הַצְּפוֹנִי","and the northern army"],["אַרְחִיק","I want to be far away"],["מֵעֲלֵיכֶם","from upon you"],["וְהִדַּחְתִּיו","and I will drive away it"],["אֶל־אֶרֶץ","to the land of"],["צִיָּה","dry"],["וּשְׁמָמָה","and desolation"],["אֶת־פָּנָיו","its face"],["אֶל־הַיָּם","to the sea"],["הַקַּדְמֹנִי","the east"],["וְסֹפוֹ","and its end"],["אֶל־הַיָּם","to the sea"],["הָאַחֲרוֹן","the last"],["וְעָלָה","and he shall come up"],["בׇאְשׁוֹ","his stink"],["וְתַעַל","and it will go up"],["צַחֲנָתוֹ","its foul smell"],["כִּי","because"],["הִגְדִּיל","he did great things"],["לַעֲשׂוֹת","to do"],["׃",""]] },
  { num:"כא", words:[["אַל־תִּירְאִי","do not should be afraid"],["אֲדָמָה","ground"],["גִּילִי","be glad"],["וּשְׂמָחִי","and rejoice"],["כִּי־הִגְדִּיל","because did great things"],["יְהֹוָה","the LORD"],["לַעֲשׂוֹת","to do"],["׃",""]] },
  { num:"כב", words:[["אַל־תִּירְאוּ","fear not"],["בַּהֲמוֹת","the animals of"],["שָׂדַי","the field"],["כִּי","because"],["דָשְׁאוּ","they are green"],["נְאוֹת","the pastures of"],["מִדְבָּר","wilderness of"],["כִּי־עֵץ","because a tree"],["נָשָׂא","bore"],["פִרְיוֹ","its fruit"],["תְּאֵנָה","a fig tree"],["וָגֶפֶן","and the vine"],["נָתְנוּ","they gave"],["חֵילָם","their forces"],["׃",""]] },
  { num:"כג", words:[["וּבְנֵי","and sons of"],["צִיּוֹן","Zion"],["גִּילוּ","be glad"],["וְשִׂמְחוּ","and rejoice"],["בַּיהֹוָה","in the LORD"],["אֱלֹהֵיכֶם","your God"],["כִּי־נָתַן","because gave"],["לָכֶם","to you"],["אֶת־הַמּוֹרֶה","the former rain"],["לִצְדָקָה","for righteousness"],["וַיּוֹרֶד","and he brought down"],["לָכֶם","to you"],["גֶּשֶׁם","rain"],["מוֹרֶה","former rain"],["וּמַלְקוֹשׁ","and spring rain"],["בָּרִאשׁוֹן","in the first month"],["׃",""]] },
  { num:"כד", words:[["וּמָלְאוּ","and were fulfilled"],["הַגֳּרָנוֹת","the threshing floors"],["בָּר","grain"],["וְהֵשִׁיקוּ","and they will overflow"],["הַיְקָבִים","the wine vats"],["תִּירוֹשׁ","the new wine"],["וְיִצְהָר","and fresh oil"],["׃",""]] },
  { num:"כה", words:[["וְשִׁלַּמְתִּי","and I will repay"],["לָכֶם","to you"],["אֶת־הַשָּׁנִים","the years"],["אֲשֶׁר","which"],["אָכַל","ate"],["הָאַרְבֶּה","the locust"],["הַיֶּלֶק","the cankerworm"],["וְהֶחָסִיל","and the caterpiller"],["וְהַגָּזָם","and the palmerworm"],["חֵילִי","my army"],["הַגָּדוֹל","the great"],["אֲשֶׁר","which"],["שִׁלַּחְתִּי","I have sent"],["בָּכֶם","in you"],["׃",""]] },
  { num:"כו", words:[["וַאֲכַלְתֶּם","and you shall eat"],["אָכוֹל","in plenty"],["וְשָׂבוֹעַ","and be satisfied"],["וְהִלַּלְתֶּם","and you will praise"],["אֶת־שֵׁם","name of"],["יְהֹוָה","the LORD"],["אֱלֹהֵיכֶם","your God"],["אֲשֶׁר־עָשָׂה","which did"],["עִמָּכֶם","with you"],["לְהַפְלִיא","wondrously"],["וְלֹא־יֵבֹשׁוּ","and not ashamed shall be"],["עַמִּי","my people"],["לְעוֹלָם","forever"],["׃",""]] },
  { num:"כז", words:[["וִידַעְתֶּם","and you shall know"],["כִּי","that"],["בְקֶרֶב","in the midst of"],["יִשְׂרָאֵל","Israel"],["אָנִי","I"],["וַאֲנִי","and I"],["יְהֹוָה","the LORD"],["אֱלֹהֵיכֶם","your God"],["וְאֵין","and there is no"],["עוֹד","any more"],["וְלֹא־יֵבֹשׁוּ","and not ashamed shall be"],["עַמִּי","my people"],["לְעוֹלָם","forever"],["׃",""]] },
];
renderVerseSet(joe_ch2Verses, 'joe-ch2-verses');

var joe_ch3Verses = [
  { num:"א", words:[["וְהָיָה","and be"],["אַחֲרֵי־כֵן","hereafter"],["אֶשְׁפּוֹךְ","I will pour out"],["אֶת־רוּחִי","my spirit"],["עַל־כׇּל־בָּשָׂר","upon all the flesh"],["וְנִבְּאוּ","and shall prophesy"],["בְּנֵיכֶם","your sons"],["וּבְנוֹתֵיכֶם","and your daughters"],["זִקְנֵיכֶם","your old men"],["חֲלֹמוֹת","dreams"],["יַחֲלֹמוּן","they will dream"],["בַּחוּרֵיכֶם","your young men"],["חֶזְיֹנוֹת","visions"],["יִרְאוּ","shall see"],["׃",""]] },
  { num:"ב", words:[["וְגַם","and also"],["עַל־הָעֲבָדִים","upon the servants"],["וְעַל־הַשְּׁפָחוֹת","and upon the maidservants"],["בַּיָּמִים","in the days"],["הָהֵמָּה","those"],["אֶשְׁפּוֹךְ","I will pour out"],["אֶת־רוּחִי","my spirit"],["׃",""]] },
  { num:"ג", words:[["וְנָתַתִּי","and I will give"],["מוֹפְתִים","wonders"],["בַּשָּׁמַיִם","in the heavens"],["וּבָאָרֶץ","and in the earth"],["דָּם","blood"],["וָאֵשׁ","and fire"],["וְתִימְרוֹת","and pillars of"],["עָשָׁן","smoke"],["׃",""]] },
  { num:"ד", words:[["הַשֶּׁמֶשׁ","the sun"],["יֵהָפֵךְ","it will be turned over"],["לְחֹשֶׁךְ","to darkness"],["וְהַיָּרֵחַ","and the moon"],["לְדָם","for blood"],["לִפְנֵי","before"],["בּוֹא","coming of"],["יוֹם","day"],["יְהֹוָה","the LORD"],["הַגָּדוֹל","the great"],["וְהַנּוֹרָא","and the awesome"],["׃",""]] },
  { num:"ה", words:[["וְהָיָה","and be"],["כֹּל","all"],["אֲשֶׁר־יִקְרָא","which calls"],["בְּשֵׁם","in the name of"],["יְהֹוָה","the LORD"],["יִמָּלֵט","shall be delivered"],["כִּי","for"],["בְּהַר־צִיּוֹן","on the mount of Zion"],["וּבִירוּשָׁלַ͏ִם","and in Jerusalem"],["תִּהְיֶה","shall be"],["פְלֵיטָה","an escape"],["כַּאֲשֶׁר","as"],["אָמַר","said"],["יְהֹוָה","the LORD"],["וּבַשְּׂרִידִים","and among the survivors"],["אֲשֶׁר","which"],["יְהֹוָה","the LORD"],["קֹרֵא","shall call"],["׃",""]] },
];
renderVerseSet(joe_ch3Verses, 'joe-ch3-verses');

var joe_ch4Verses = [
  { num:"א", words:[["כִּי","for"],["הִנֵּה","behold"],["בַּיָּמִים","in the days"],["הָהֵמָּה","those"],["וּבָעֵת","and at that time"],["הַהִיא","that"],["אֲשֶׁר","which"],["(אשוב)",""],["[אָשִׁיב]","I will return"],["אֶת־שְׁבוּת","the captivity of"],["יְהוּדָה","Judah"],["וִירוּשָׁלָ͏ִם","and Jerusalem"],["׃",""]] },
  { num:"ב", words:[["וְקִבַּצְתִּי","and I will gather"],["אֶת־כׇּל־הַגּוֹיִם","all the nations"],["וְהוֹרַדְתִּים","and I will bring down them"],["אֶל־עֵמֶק","to the valley of"],["יְהוֹשָׁפָט","Jehoshaphat"],["וְנִשְׁפַּטְתִּי","and I will enter into judgment"],["עִמָּם","with them"],["שָׁם","there"],["עַל־עַמִּי","upon My people"],["וְנַחֲלָתִי","and my inheritance"],["יִשְׂרָאֵל","Israel"],["אֲשֶׁר","which"],["פִּזְּרוּ","they scattered"],["בַגּוֹיִם","among the nations"],["וְאֶת־אַרְצִי","and my land"],["חִלֵּקוּ","they have divided up"],["׃",""]] },
  { num:"ג", words:[["וְאֶל־עַמִּי","and for my people"],["יַדּוּ","they have cast"],["גוֹרָל","a lot"],["וַיִּתְּנוּ","and they gave"],["הַיֶּלֶד","the child"],["בַּזּוֹנָה","for the prostitute"],["וְהַיַּלְדָּה","and the girl"],["מָכְרוּ","they sold"],["בַיַּיִן","for the wine"],["וַיִּשְׁתּוּ","and they did drink"],["׃",""]] },
  { num:"ד", words:[["וְגַם","and also"],["מָה־אַתֶּם","what you are"],["לִי","to me"],["צֹר","Tyre"],["וְצִידוֹן","and Zidon"],["וְכֹל","and all"],["גְּלִילוֹת","the territories of"],["פְּלָשֶׁת","Philistia"],["הַגְּמוּל","recompense"],["אַתֶּם","you are"],["מְשַׁלְּמִים","repaying"],["עָלָי","unto me"],["וְאִם־גֹּמְלִים","and if are repaying"],["אַתֶּם","you are"],["עָלַי","upon me"],["קַל","swiftly"],["מְהֵרָה","soon"],["אָשִׁיב","I will return"],["גְּמֻלְכֶם","your recompense"],["בְּרֹאשְׁכֶם","on your head"],["׃",""]] },
  { num:"ה", words:[["אֲשֶׁר־כַּסְפִּי","which my silver"],["וּזְהָבִי","and my gold"],["לְקַחְתֶּם","you have taken"],["וּמַחֲמַדַּי","and my desirable things"],["הַטֹּבִים","the good"],["הֲבֵאתֶם","have you brought"],["לְהֵיכְלֵיכֶם","to your own temples"],["׃",""]] },
  { num:"ו", words:[["וּבְנֵי","and sons of"],["יְהוּדָה","Judah"],["וּבְנֵי","and sons of"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["מְכַרְתֶּם","you sold"],["לִבְנֵי","unto the sons of"],["הַיְּוָנִים","the Greeks"],["לְמַעַן","in order that"],["הַרְחִיקָם","to remove far away them"],["מֵעַל","from upon"],["גְּבוּלָם","their territory"],["׃",""]] },
  { num:"ז", words:[["הִנְנִי","behold I"],["מְעִירָם","am about to rouse them"],["מִן־הַמָּקוֹם","from the place"],["אֲשֶׁר־מְכַרְתֶּם","which you sold"],["אֹתָם","them"],["שָׁמָּה","there"],["וַהֲשִׁבֹתִי","I will return"],["גְמֻלְכֶם","your recompense"],["בְּרֹאשְׁכֶם","on your head"],["׃",""]] },
  { num:"ח", words:[["וּמָכַרְתִּי","and I will sell"],["אֶת־בְּנֵיכֶם","your sons"],["וְאֶת־בְּנוֹתֵיכֶם","and your daughters"],["בְּיַד","in the hand of"],["בְּנֵי","the sons of"],["יְהוּדָה","Judah"],["וּמְכָרוּם","and they will sell them"],["לִשְׁבָאיִם","to the Sabeans"],["אֶל־גּוֹי","against nation"],["רָחוֹק","far"],["כִּי","for"],["יְהֹוָה","the LORD"],["דִּבֵּר","spoke"],["׃",""]] },
  { num:"ט", words:[["קִרְאוּ־זֹאת","call this"],["בַּגּוֹיִם","among the nations"],["קַדְּשׁוּ","consecrate"],["מִלְחָמָה","war"],["הָעִירוּ","wake up"],["הַגִּבּוֹרִים","the mighty men"],["יִגְּשׁוּ","let them approach"],["יַעֲלוּ","they go up"],["כֹּל","all"],["אַנְשֵׁי","the men of"],["הַמִּלְחָמָה","the battle"],["׃",""]] },
  { num:"י", words:[["כֹּתּוּ","beat"],["אִתֵּיכֶם","your plowshares"],["לַחֲרָבוֹת","into swords"],["וּמַזְמְרֹתֵיכֶם","and your pruning knives"],["לִרְמָחִים","into spears"],["הַחַלָּשׁ","the weak"],["יֹאמַר","he says"],["גִּבּוֹר","mighty"],["אָנִי","I"],["׃",""]] },
  { num:"יא", words:[["עוּשׁוּ","hurry"],["וָבֹאוּ","and come"],["כׇל־הַגּוֹיִם","all the nations"],["מִסָּבִיב","all around"],["וְנִקְבָּצוּ","and they will gather"],["שָׁמָּה","there"],["הַנְחַת","bring down"],["יְהֹוָה","the LORD"],["גִּבּוֹרֶיךָ","your warriors"],["׃",""]] },
  { num:"יב", words:[["יֵעוֹרוּ","they shall awake"],["וְיַעֲלוּ","and they go up"],["הַגּוֹיִם","the nations"],["אֶל־עֵמֶק","to the valley of"],["יְהוֹשָׁפָט","Jehoshaphat"],["כִּי","for"],["שָׁם","there"],["אֵשֵׁב","I will remain"],["לִשְׁפֹּט","to judge"],["אֶת־כׇּל־הַגּוֹיִם","all the nations"],["מִסָּבִיב","all around"],["׃",""]] },
  { num:"יג", words:[["שִׁלְחוּ","send"],["מַגָּל","sickle"],["כִּי","because"],["בָשַׁל","it has grown ripe"],["קָצִיר","harvest"],["בֹּאוּ","come"],["רְדוּ","go down"],["כִּי־מָלְאָה","for is full"],["גַּת","the winepress"],["הֵשִׁיקוּ","they are overflowing"],["הַיְקָבִים","the wine vats"],["כִּי","because"],["רַבָּה","much"],["רָעָתָם","their wickedness"],["׃",""]] },
  { num:"יד", words:[["הֲמוֹנִים","multitudes"],["הֲמוֹנִים","multitudes"],["בְּעֵמֶק","in the valley of"],["הֶחָרוּץ","decision"],["כִּי","for"],["קָרוֹב","soon"],["יוֹם","day"],["יְהֹוָה","the LORD"],["בְּעֵמֶק","in the valley of"],["הֶחָרוּץ","decision"],["׃",""]] },
  { num:"טו", words:[["שֶׁמֶשׁ","the sun"],["וְיָרֵחַ","and moon"],["קָדָרוּ","they become dark"],["וְכוֹכָבִים","and the stars"],["אָסְפוּ","shall withdraw"],["נׇגְהָם","their shining"],["׃",""]] },
  { num:"טז", words:[["וַיהֹוָה","and the LORD"],["מִצִּיּוֹן","out of Zion"],["יִשְׁאָג","he will roar"],["וּמִירוּשָׁלַ͏ִם","and from Jerusalem"],["יִתֵּן","shall give"],["קוֹלוֹ","His voice"],["וְרָעֲשׁוּ","and they will shake"],["שָׁמַיִם","the heavens"],["וָאָרֶץ","and earth"],["וַיהֹוָה","and the LORD"],["מַחֲסֶה","will be the hope"],["לְעַמּוֹ","for His people"],["וּמָעוֹז","and is the refuge of"],["לִבְנֵי","unto the sons of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"יז", words:[["וִידַעְתֶּם","and you shall know"],["כִּי","that"],["אֲנִי","I"],["יְהֹוָה","the LORD"],["אֱלֹהֵיכֶם","your God"],["שֹׁכֵן","dwells"],["בְּצִיּוֹן","in Zion"],["הַר־קׇדְשִׁי","my holy mountain"],["וְהָיְתָה","and it be"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["קֹדֶשׁ","holy"],["וְזָרִים","and strangers"],["לֹא־יַעַבְרוּ־בָהּ","not they shall pass in her"],["עוֹד","any more"],["׃",""]] },
  { num:"יח", words:[["וְהָיָה","and be"],["בַיּוֹם","by the day"],["הַהוּא","that"],["יִטְּפוּ","they will drip"],["הֶהָרִים","the mountains"],["עָסִיס","sweet wine"],["וְהַגְּבָעוֹת","and the hills"],["תֵּלַכְנָה","shall flow"],["חָלָב","milk"],["וְכׇל־אֲפִיקֵי","and all the rivers of"],["יְהוּדָה","Judah"],["יֵלְכוּ","shall flow"],["מָיִם","water"],["וּמַעְיָן","and a spring"],["מִבֵּית","from the house of"],["יְהֹוָה","the LORD"],["יֵצֵא","he go forth"],["וְהִשְׁקָה","and it watered"],["אֶת־נַחַל","a river of"],["הַשִּׁטִּים","Shittim"],["׃",""]] },
  { num:"יט", words:[["מִצְרַיִם","Egypt"],["לִשְׁמָמָה","a desolation"],["תִהְיֶה","be"],["וֶאֱדוֹם","and Edom"],["לְמִדְבַּר","to the wilderness of"],["שְׁמָמָה","desolate"],["תִּהְיֶה","shall be"],["מֵחֲמַס","for the violence against"],["בְּנֵי","the sons of"],["יְהוּדָה","Judah"],["אֲשֶׁר־שָׁפְכוּ","which did pour out"],["דָם־נָקִיא","blood innocent"],["בְּאַרְצָם","in their land"],["׃",""]] },
  { num:"כ", words:[["וִיהוּדָה","and Judah"],["לְעוֹלָם","forever"],["תֵּשֵׁב","shall sit"],["וִירוּשָׁלַ͏ִם","and Jerusalem"],["לְדוֹר","to generation"],["וָדוֹר","to generation"],["׃",""]] },
  { num:"כא", words:[["וְנִקֵּיתִי","and I will cleanse"],["דָּמָם","their blood"],["לֹא־נִקֵּיתִי","I have not cleansed"],["וַיהֹוָה","and the LORD"],["שֹׁכֵן","dwells"],["בְּצִיּוֹן","in Zion"],["׃",""]] },
];
renderVerseSet(joe_ch4Verses, 'joe-ch4-verses');

})();
