// ot_verses/jon.js — Jonah verse data
(function() {
var jon_ch1Verses = [
  { num:"א", words:[["וַיְהִי","and-it-came-to-pass"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["אֶל־יוֹנָה","to-a-dove"],["בֶן־אֲמִתַּי","Bn-Amittai"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ב", words:[["קוּם","arise"],["לֵךְ","go"],["אֶל־נִינְוֵה","to-Nineveh"],["הָעִיר","the-city"],["הַגְּדוֹלָה","the-great"],["וּקְרָא","and-call"],["עָלֶיהָ","upon-it"],["כִּי־עָלְתָה","because-has-surpassed"],["רָעָתָם","their-wickedness"],["לְפָנָי","before-Me"],["׃",""]] },
  { num:"ג", words:[["וַיָּקׇם","and-he-arose"],["יוֹנָה","a-dove"],["לִבְרֹחַ","to-flee"],["תַּרְשִׁישָׁה","Tarshish-towards"],["מִלִּפְנֵי","from-presence-of"],["יְהֹוָה","the-LORD"],["וַיֵּרֶד","and-he-descended"],["יָפוֹ","Joppa"],["וַיִּמְצָא","and-found"],["אֳנִיָּה","a-ship"],["בָּאָה","comes"],["תַרְשִׁישׁ","Tarshish"],["וַיִּתֵּן","and-gave"],["שְׂכָרָהּ","fare-its"],["וַיֵּרֶד","and-he-descended"],["בָּהּ","in-it(f)"],["לָבוֹא","to-come"],["עִמָּהֶם","with-them"],["תַּרְשִׁישָׁה","Tarshish-towards"],["מִלִּפְנֵי","from-presence-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ד", words:[["וַיהֹוָה","and-the-LORD"],["הֵטִיל","he threw"],["רוּחַ־גְּדוֹלָה","spirit-of-great"],["אֶל־הַיָּם","to-the-sea"],["וַיְהִי","and-it-came-to-pass"],["סַעַר־גָּדוֹל","storm-great"],["בַּיָּם","in-the-sea"],["וְהָאֳנִיָּה","and-the-ship"],["חִשְּׁבָה","it thought"],["לְהִשָּׁבֵר","to-be broken"],["׃",""]] },
  { num:"ה", words:[["וַיִּירְאוּ","and-they-feared"],["הַמַּלָּחִים","the-sailors"],["וַיִּזְעֲקוּ","and-they-did-cry"],["אִישׁ","a-man"],["אֶל־אֱלֹהָיו","unto-their-God"],["וַיָּטִלוּ","and-they threw"],["אֶת־הַכֵּלִים","[ACC]-the-tools"],["אֲשֶׁר","which"],["בָּאֳנִיָּה","in-the-a-ship"],["אֶל־הַיָּם","to-the-sea"],["לְהָקֵל","to-ease"],["מֵעֲלֵיהֶם","from-off-them"],["וְיוֹנָה","and-a-dove"],["יָרַד","came-down"],["אֶל־יַרְכְּתֵי","to-the remotest parts of"],["הַסְּפִינָה","the-ship"],["וַיִּשְׁכַּב","and-would-lie-down"],["וַיֵּרָדַם","and-he had fallen fast asleep"],["׃",""]] },
  { num:"ו", words:[["וַיִּקְרַב","and-he drew near"],["אֵלָיו","to-him"],["רַב","great"],["הַחֹבֵל","the-sailors"],["וַיֹּאמֶר","and-said"],["לוֹ","him"],["מַה־לְּךָ","what-have-you"],["נִרְדָּם","was sleeping"],["קוּם","arise"],["קְרָא","call"],["אֶל־אֱלֹהֶיךָ","to-your-God"],["אוּלַי","perhaps"],["יִתְעַשֵּׁת","he will give thought"],["הָאֱלֹהִים","the-God"],["לָנוּ","us"],["וְלֹא","and-not"],["נֹאבֵד","perish"],["׃",""]] },
  { num:"ז", words:[["וַיֹּאמְרוּ","and-they-said"],["אִישׁ","a-man"],["אֶל־רֵעֵהוּ","to-the-other"],["לְכוּ","go"],["וְנַפִּילָה","so-let us cast"],["גוֹרָלוֹת","lots"],["וְנֵדְעָה","so-let us know"],["בְּשֶׁלְּמִי","by-which-of-whom?"],["הָרָעָה","the-evil"],["הַזֹּאת","this"],["לָנוּ","us"],["וַיַּפִּלוּ","and-they cast"],["גּוֹרָלוֹת","lots"],["וַיִּפֹּל","and-fell"],["הַגּוֹרָל","the-lot"],["עַל־יוֹנָה","upon-a-dove"],["׃",""]] },
  { num:"ח", words:[["וַיֹּאמְרוּ","and-they-said"],["אֵלָיו","to-him"],["הַגִּידָה־נָּא","tell-!-now"],["לָנוּ","us"],["בַּאֲשֶׁר","because"],["לְמִי־הָרָעָה","to-whom-the-evil"],["הַזֹּאת","this"],["לָנוּ","us"],["מַה־מְּלַאכְתְּךָ","what-is occupation-your"],["וּמֵאַיִן","and-from-where?"],["תָּבוֹא","come-shall"],["מָה","what"],["אַרְצֶךָ","to-the-earth-your"],["וְאֵי־מִזֶּה","and-where?-than-this"],["עַם","people"],["אָתָּה","you-are"],["׃",""]] },
  { num:"ט", words:[["וַיֹּאמֶר","and-said"],["אֲלֵיהֶם","to-them"],["עִבְרִי","Hebrew"],["אָנֹכִי","I"],["וְאֶת־יְהֹוָה","and-[ACC]-the-LORD"],["אֱלֹהֵי","the-God-of"],["הַשָּׁמַיִם","the-heavens"],["אֲנִי","I"],["יָרֵא","he-feared"],["אֲשֶׁר־עָשָׂה","which-did"],["אֶת־הַיָּם","[ACC]-the-sea"],["וְאֶת־הַיַּבָּשָׁה","and-[ACC]-the-dry ground"],["׃",""]] },
  { num:"י", words:[["וַיִּירְאוּ","and-they-feared"],["הָאֲנָשִׁים","the-men"],["יִרְאָה","He-shall-manifest-Himself"],["גְדוֹלָה","great"],["וַיֹּאמְרוּ","and-they-said"],["אֵלָיו","to-him"],["מַה־זֹּאת","what-this"],["עָשִׂיתָ","you-did"],["כִּי־יָדְעוּ","because-they-knew"],["הָאֲנָשִׁים","the-men"],["כִּי־מִלִּפְנֵי","because-from-presence-of"],["יְהֹוָה","the-LORD"],["הוּא","he"],["בֹרֵחַ","was fleeing"],["כִּי","because"],["הִגִּיד","declared"],["לָהֶם","to-them"],["׃",""]] },
  { num:"יא", words:[["וַיֹּאמְרוּ","and-they-said"],["אֵלָיו","to-him"],["מַה־נַּעֲשֶׂה","what-shall-we-do"],["לָּךְ","to-you"],["וְיִשְׁתֹּק","so-it may be calm"],["הַיָּם","the-sea"],["מֵעָלֵינוּ","from-upon-us"],["כִּי","because"],["הַיָּם","the-sea"],["הוֹלֵךְ","going"],["וְסֹעֵר","and-storming"],["׃",""]] },
  { num:"יב", words:[["וַיֹּאמֶר","and-said"],["אֲלֵיהֶם","to-them"],["שָׂאוּנִי","bear with-me"],["וַהֲטִילֻנִי","and-throw-me"],["אֶל־הַיָּם","to-the-sea"],["וְיִשְׁתֹּק","so-it may be calm"],["הַיָּם","the-sea"],["מֵעֲלֵיכֶם","from-upon-you"],["כִּי","because"],["יוֹדֵעַ","knows"],["אָנִי","I"],["כִּי","because"],["בְשֶׁלִּי","by-which-to-me"],["הַסַּעַר","the-storm"],["הַגָּדוֹל","the-great"],["הַזֶּה","this"],["עֲלֵיכֶם","over-you"],["׃",""]] },
  { num:"יג", words:[["וַיַּחְתְּרוּ","and-they rowed"],["הָאֲנָשִׁים","the-men"],["לְהָשִׁיב","to-he-restored"],["אֶל־הַיַּבָּשָׁה","to-the-dry ground"],["וְלֹא","and-not"],["יָכֹלוּ","they were able"],["כִּי","because"],["הַיָּם","the-sea"],["הוֹלֵךְ","going"],["וְסֹעֵר","and-storming"],["עֲלֵיהֶם","upon-them"],["׃",""]] },
  { num:"יד", words:[["וַיִּקְרְאוּ","and-they-called"],["אֶל־יְהֹוָה","to-the-Lord"],["וַיֹּאמְרוּ","and-they-said"],["אָנָּה","I beg you"],["יְהֹוָה","the-LORD"],["אַל־נָא","do-not-I-pray"],["נֹאבְדָה","let us perish"],["בְּנֶפֶשׁ","the corpse of"],["הָאִישׁ","the-man"],["הַזֶּה","this"],["וְאַל־תִּתֵּן","and-do-not-you-give"],["עָלֵינוּ","over-us"],["דָּם","blood"],["נָקִיא","innocent"],["כִּי־אַתָּה","that-you"],["יְהֹוָה","the-LORD"],["כַּאֲשֶׁר","when/as"],["חָפַצְתָּ","you-desired"],["עָשִׂיתָ","you-did"],["׃",""]] },
  { num:"טו", words:[["וַיִּשְׂאוּ","and-lifted"],["אֶת־יוֹנָה","[ACC]-a-dove"],["וַיְטִלֻהוּ","and-they threw-him"],["אֶל־הַיָּם","to-the-sea"],["וַיַּעֲמֹד","and-stood"],["הַיָּם","the-sea"],["מִזַּעְפּוֹ","from-storming-its"],["׃",""]] },
  { num:"טז", words:[["וַיִּירְאוּ","and-they-feared"],["הָאֲנָשִׁים","the-men"],["יִרְאָה","He-shall-manifest-Himself"],["גְדוֹלָה","great"],["אֶת־יְהֹוָה","[ACC]-the-LORD"],["וַיִּזְבְּחוּ־זֶבַח","and-sacrificed-sacrifice"],["לַיהֹוָה","to-the-LORD"],["וַיִּדְּרוּ","and-they vowed"],["נְדָרִים","the vows"],["׃",""]] },
];
renderVerseSet(jon_ch1Verses, 'jon-ch1-verses');

var jon_ch2Verses = [
  { num:"א", words:[["וַיְמַן","and-he assigned"],["יְהֹוָה","the-LORD"],["דָּג","Dg"],["גָּדוֹל","great"],["לִבְלֹעַ","to-swallow-up"],["אֶת־יוֹנָה","[ACC]-a-dove"],["וַיְהִי","and-it-came-to-pass"],["יוֹנָה","a-dove"],["בִּמְעֵי","in-the inward parts of"],["הַדָּג","the-fish"],["שְׁלֹשָׁה","three"],["יָמִים","days"],["וּשְׁלֹשָׁה","and-three"],["לֵילוֹת","nights"],["׃",""]] },
  { num:"ב", words:[["וַיִּתְפַּלֵּל","and-he-prayed"],["יוֹנָה","a-dove"],["אֶל־יְהֹוָה","to-the-Lord"],["אֱלֹהָיו","his-God"],["מִמְּעֵי","from-bowels-of"],["הַדָּגָה","the-fish"],["׃",""]] },
  { num:"ג", words:[["וַיֹּאמֶר","and-said"],["קָרָאתִי","called"],["מִצָּרָה","from-trouble"],["לִי","to-me"],["אֶל־יְהֹוָה","to-the-Lord"],["וַיַּעֲנֵנִי","and-he answered-me"],["מִבֶּטֶן","from-the-womb"],["שְׁאוֹל","Sheol"],["שִׁוַּעְתִּי","I cried for help"],["שָׁמַעְתָּ","you-have-hitherto-listened-to"],["קוֹלִי","my-voice"],["׃",""]] },
  { num:"ד", words:[["וַתַּשְׁלִיכֵנִי","and-you have thrown away-me"],["מְצוּלָה","the deep"],["בִּלְבַב","in-the-hearts-of"],["יַמִּים","seas"],["וְנָהָר","and-a river"],["יְסֹבְבֵנִי","it surrounds-me"],["כׇּל־מִשְׁבָּרֶיךָ","all-breakers-your"],["וְגַלֶּיךָ","and-waves-your"],["עָלַי","I-must"],["עָבָרוּ","they have passed"],["׃",""]] },
  { num:"ה", words:[["וַאֲנִי","and-I"],["אָמַרְתִּי","I-said"],["נִגְרַשְׁתִּי","I have been driven away"],["מִנֶּגֶד","from-before"],["עֵינֶיךָ","your-eyes"],["אַךְ","but"],["אוֹסִיף","more"],["לְהַבִּיט","to-look"],["אֶל־הֵיכַל","to-the-temple-of"],["קׇדְשֶׁךָ","your-holiness"],["׃",""]] },
  { num:"ו", words:[["אֲפָפוּנִי","they encompassed-me"],["מַיִם","water"],["עַד־נֶפֶשׁ","until-soul"],["תְּהוֹם","gulf"],["יְסֹבְבֵנִי","it surrounds-me"],["סוּף","reeds"],["חָבוּשׁ","is wrapped round"],["לְרֹאשִׁי","my-head"],["׃",""]] },
  { num:"ז", words:[["לְקִצְבֵי","to-extremities of"],["הָרִים","mountains"],["יָרַדְתִּי","I went down"],["הָאָרֶץ","the-earth"],["בְּרִחֶיהָ","bars-its"],["בַעֲדִי","for-me"],["לְעוֹלָם","forever"],["וַתַּעַל","and-she-went-up"],["מִשַּׁחַת","from-destruction"],["חַיַּי","my-life"],["יְהֹוָה","the-LORD"],["אֱלֹהָי","my-God"],["׃",""]] },
  { num:"ח", words:[["בְּהִתְעַטֵּף","when-faints away"],["עָלַי","I-must"],["נַפְשִׁי","my-life"],["אֶת־יְהֹוָה","[ACC]-the-LORD"],["זָכָרְתִּי","I remember"],["וַתָּבוֹא","and-she went"],["אֵלֶיךָ","to-you"],["תְּפִלָּתִי","my-prayer"],["אֶל־הֵיכַל","to-the-temple-of"],["קׇדְשֶׁךָ","your-holiness"],["׃",""]] },
  { num:"ט", words:[["מְשַׁמְּרִים","those who pay regard"],["הַבְלֵי־שָׁוְא","vanities-of-falsehood"],["חַסְדָּם","loyalty-their"],["יַעֲזֹבוּ","they abandon"],["׃",""]] },
  { num:"י", words:[["וַאֲנִי","and-I"],["בְּקוֹל","the-voice-of"],["תּוֹדָה","thanksgiving"],["אֶזְבְּחָה־לָּךְ","I will sacrifice-to-you"],["אֲשֶׁר","which"],["נָדַרְתִּי","I vowed"],["אֲשַׁלֵּמָה","I will fulfill"],["יְשׁוּעָתָה","is deliverance"],["לַיהֹוָה","to-the-LORD"],["׃",""]] },
  { num:"יא", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["לַדָּג","to the-fish"],["וַיָּקֵא","and-it vomited up"],["אֶת־יוֹנָה","[ACC]-a-dove"],["אֶל־הַיַּבָּשָׁה","to-the-dry ground"],["׃",""]] },
];
renderVerseSet(jon_ch2Verses, 'jon-ch2-verses');

var jon_ch3Verses = [
  { num:"א", words:[["וַיְהִי","and-it-came-to-pass"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["אֶל־יוֹנָה","to-a-dove"],["שֵׁנִית","again"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ב", words:[["קוּם","arise"],["לֵךְ","go"],["אֶל־נִינְוֵה","to-Nineveh"],["הָעִיר","the-city"],["הַגְּדוֹלָה","the-great"],["וּקְרָא","and-call"],["אֵלֶיהָ","to-her"],["אֶת־הַקְּרִיאָה","[ACC]-the-a-proclamation"],["אֲשֶׁר","which"],["אָנֹכִי","I"],["דֹּבֵר","speaks"],["אֵלֶיךָ","to-you"],["׃",""]] },
  { num:"ג", words:[["וַיָּקׇם","and-he-arose"],["יוֹנָה","a-dove"],["וַיֵּלֶךְ","and-went"],["אֶל־נִינְוֵה","to-Nineveh"],["כִּדְבַר","according-to-the-word-of"],["יְהֹוָה","the-LORD"],["וְנִינְוֵה","and-Nineveh"],["הָיְתָה","was"],["עִיר־גְּדוֹלָה","city-of-great"],["לֵאלֹהִים","God"],["מַהֲלַךְ","journey-of"],["שְׁלֹשֶׁת","three-of"],["יָמִים","days"],["׃",""]] },
  { num:"ד", words:[["וַיָּחֶל","and-began"],["יוֹנָה","a-dove"],["לָבוֹא","to-come"],["בָעִיר","in the-city"],["מַהֲלַךְ","journey-of"],["יוֹם","day"],["אֶחָד","one"],["וַיִּקְרָא","and-called"],["וַיֹּאמַר","and-said"],["עוֹד","any-more"],["אַרְבָּעִים","forty"],["יוֹם","day"],["וְנִינְוֵה","and-Nineveh"],["נֶהְפָּכֶת","is about to be overturned"],["׃",""]] },
  { num:"ה", words:[["וַיַּאֲמִינוּ","and-believed"],["אַנְשֵׁי","the-men-of"],["נִינְוֵה","Nineveh"],["בֵּאלֹהִים","in-God"],["וַיִּקְרְאוּ־צוֹם","and-they-called-fasting"],["וַיִּלְבְּשׁוּ","and-put-on"],["שַׂקִּים","sacks"],["מִגְּדוֹלָם","from-great-their"],["וְעַד־קְטַנָּם","and-unto-insignificant-their"],["׃",""]] },
  { num:"ו", words:[["וַיִּגַּע","and-he-touched"],["הַדָּבָר","the-thing"],["אֶל־מֶלֶךְ","to-the-king-of"],["נִינְוֵה","Nineveh"],["וַיָּקׇם","and-he-arose"],["מִכִּסְאוֹ","from-his-throne"],["וַיַּעֲבֵר","and-he made to pass"],["אַדַּרְתּוֹ","cloak-his"],["מֵעָלָיו","from-with-him"],["וַיְכַס","Oiks"],["שַׂק","sackcloth"],["וַיֵּשֶׁב","and-he-dwelt"],["עַל־הָאֵפֶר","upon-the-ashes"],["׃",""]] },
  { num:"ז", words:[["וַיַּזְעֵק","and-he summoned"],["וַיֹּאמֶר","and-said"],["בְּנִינְוֵה","in-Nineveh"],["מִטַּעַם","from-the decree of"],["הַמֶּלֶךְ","the-king"],["וּגְדֹלָיו","and-great people-his"],["לֵאמֹר","saying"],["הָאָדָם","the-man"],["וְהַבְּהֵמָה","and-the-livestock"],["הַבָּקָר","the-herd"],["וְהַצֹּאן","and-the-flock"],["אַל־יִטְעֲמוּ","do-not-they-shall-taste"],["מְאוּמָה","anything"],["אַל־יִרְעוּ","do-not-they-feed"],["וּמַיִם","and-water"],["אַל־יִשְׁתּוּ","do-not-they-drink"],["׃",""]] },
  { num:"ח", words:[["וְיִתְכַּסּוּ","and-they may cover themselves"],["שַׂקִּים","sacks"],["הָאָדָם","the-man"],["וְהַבְּהֵמָה","and-the-livestock"],["וְיִקְרְאוּ","and-they-shall-call"],["אֶל־אֱלֹהִים","unto-God"],["בְּחׇזְקָה","mightily"],["וְיָשֻׁבוּ","so-they may turn back"],["אִישׁ","a-man"],["מִדַּרְכּוֹ","from-his-way"],["הָרָעָה","the-evil"],["וּמִן־הֶחָמָס","and-from-violence"],["אֲשֶׁר","which"],["בְּכַפֵּיהֶם","is in-hands-their"],["׃",""]] },
  { num:"ט", words:[["מִי־יוֹדֵעַ","who-knows"],["יָשׁוּב","repent"],["וְנִחַם","and-he will be comforted"],["הָאֱלֹהִים","the-God"],["וְשָׁב","and-repenteth"],["מֵחֲרוֹן","from-the burning of"],["אַפּוֹ","His-wrath"],["וְלֹא","and-not"],["נֹאבֵד","perish"],["׃",""]] },
  { num:"י", words:[["וַיַּרְא","and-saw"],["הָאֱלֹהִים","the-God"],["אֶת־מַעֲשֵׂיהֶם","[ACC]-their-works"],["כִּי־שָׁבוּ","because-repented"],["מִדַּרְכָּם","from-way-their"],["הָרָעָה","the-evil"],["וַיִּנָּחֶם","and-he regretted"],["הָאֱלֹהִים","the-God"],["עַל־הָרָעָה","upon-the-evil"],["אֲשֶׁר־דִּבֶּר","whose-spoke"],["לַעֲשׂוֹת־לָהֶם","to-do-to-them"],["וְלֹא","and-not"],["עָשָׂה","he-did"],["׃",""]] },
];
renderVerseSet(jon_ch3Verses, 'jon-ch3-verses');

var jon_ch4Verses = [
  { num:"א", words:[["וַיֵּרַע","were-displeased-with"],["אֶל־יוֹנָה","to-a-dove"],["רָעָה","evil"],["גְדוֹלָה","great"],["וַיִּחַר","and-burned"],["לוֹ","him"],["׃",""]] },
  { num:"ב", words:[["וַיִּתְפַּלֵּל","and-he-prayed"],["אֶל־יְהֹוָה","to-the-Lord"],["וַיֹּאמַר","and-said"],["אָנָּה","I beg you"],["יְהֹוָה","the-LORD"],["הֲלוֹא־זֶה","art-not-this"],["דְבָרִי","My-word"],["עַד־הֱיוֹתִי","until-being-I"],["עַל־אַדְמָתִי","upon-land-my"],["עַל־כֵּן","therefore"],["קִדַּמְתִּי","I am early"],["לִבְרֹחַ","to-flee"],["תַּרְשִׁישָׁה","Tarshish-towards"],["כִּי","because"],["יָדַעְתִּי","I-know"],["כִּי","because"],["אַתָּה","you"],["אֵל־חַנּוּן","God-merciful"],["וְרַחוּם","and-merciful"],["אֶרֶךְ","long of"],["אַפַּיִם","with-face"],["וְרַב־חֶסֶד","and-great-mercy"],["וְנִחָם","and-relenting"],["עַל־הָרָעָה","upon-the-evil"],["׃",""]] },
  { num:"ג", words:[["וְעַתָּה","and-now"],["יְהֹוָה","the-LORD"],["קַח־נָא","take-I-pray"],["אֶת־נַפְשִׁי","[ACC]-my-soul"],["מִמֶּנִּי","from-me"],["כִּי","because"],["טוֹב","good"],["מוֹתִי","death-my"],["מֵחַיָּי","more than-life-my"],["׃",""]] },
  { num:"ד", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["הַהֵיטֵב","¿-rightly"],["חָרָה","burned"],["לָךְ","to-you"],["׃",""]] },
  { num:"ה", words:[["וַיֵּצֵא","and-went-out"],["יוֹנָה","a-dove"],["מִן־הָעִיר","from-the-city"],["וַיֵּשֶׁב","and-he-dwelt"],["מִקֶּדֶם","of-old"],["לָעִיר","to-the-city-of"],["וַיַּעַשׂ","and-he-made"],["לוֹ","him"],["שָׁם","there"],["סֻכָּה","a shelter"],["וַיֵּשֶׁב","and-he-dwelt"],["תַּחְתֶּיהָ","in place-its"],["בַּצֵּל","in the-shade"],["עַד","until"],["אֲשֶׁר","which"],["יִרְאֶה","He-shall-manifest-Himself"],["מַה־יִּהְיֶה","what-he-shall-be"],["בָּעִיר","in-the-city"],["׃",""]] },
  { num:"ו", words:[["וַיְמַן","and-he assigned"],["יְהֹוָה־אֱלֹהִים","the-LORD-God"],["קִיקָיוֹן","a plant"],["וַיַּעַל","and-he-ascended"],["מֵעַל","from-upon"],["לְיוֹנָה","Jonah"],["לִהְיוֹת","to-be"],["צֵל","is-a-shadow-of"],["עַל־רֹאשׁוֹ","upon-his-head"],["לְהַצִּיל","to-deliver"],["לוֹ","him"],["מֵרָעָתוֹ","from-evil-its"],["וַיִּשְׂמַח","and-his-father-rejoiced"],["יוֹנָה","a-dove"],["עַל־הַקִּיקָיוֹן","upon-the-plant"],["שִׂמְחָה","joy"],["גְדוֹלָה","great"],["׃",""]] },
  { num:"ז", words:[["וַיְמַן","and-he assigned"],["הָאֱלֹהִים","the-God"],["תּוֹלַעַת","the scarlet stuff of"],["בַּעֲלוֹת","in-the-ascending-of"],["הַשַּׁחַר","the-light"],["לַמׇּחֳרָת","to-the-tomorrow-of"],["וַתַּךְ","and-it attacked"],["אֶת־הַקִּיקָיוֹן","[ACC]-the-plant"],["וַיִּיבָשׁ","and-it withered"],["׃",""]] },
  { num:"ח", words:[["וַיְהִי","and-it-came-to-pass"],["כִּזְרֹחַ","when-rises"],["הַשֶּׁמֶשׁ","the-sun"],["וַיְמַן","and-he assigned"],["אֱלֹהִים","God"],["רוּחַ","the-spirit-of"],["קָדִים","the-east"],["חֲרִישִׁית","hot"],["וַתַּךְ","and-it attacked"],["הַשֶּׁמֶשׁ","the-sun"],["עַל־רֹאשׁ","upon-the-heads-of"],["יוֹנָה","a-dove"],["וַיִּתְעַלָּף","and-he became faint"],["וַיִּשְׁאַל","and-asked"],["אֶת־נַפְשׁוֹ","his-life"],["לָמוּת","to-perish"],["וַיֹּאמֶר","and-said"],["טוֹב","good"],["מוֹתִי","death-my"],["מֵחַיָּי","more than-life-my"],["׃",""]] },
  { num:"ט", words:[["וַיֹּאמֶר","and-said"],["אֱלֹהִים","God"],["אֶל־יוֹנָה","to-a-dove"],["הַהֵיטֵב","¿-rightly"],["חָרָה־לְךָ","burned-for-you"],["עַל־הַקִּיקָיוֹן","upon-the-plant"],["וַיֹּאמֶר","and-said"],["הֵיטֵב","well/diligently"],["חָרָה־לִי","burned-to-me"],["עַד־מָוֶת","until-death"],["׃",""]] },
  { num:"י", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["אַתָּה","you"],["חַסְתָּ","you had compassion"],["עַל־הַקִּיקָיוֹן","upon-the-plant"],["אֲשֶׁר","which"],["לֹא־עָמַלְתָּ","not-you had toiled"],["בּוֹ","against-him"],["וְלֹא","and-not"],["גִדַּלְתּוֹ","you had made grow-it"],["שֶׁבִּן־לַיְלָה","that-a son of-night"],["הָיָה","was"],["וּבִן־לַיְלָה","and-a son of-night"],["אָבָד","did he perish"],["׃",""]] },
  { num:"יא", words:[["וַאֲנִי","and-I"],["לֹא","not"],["אָחוּס","I-will-spare-it"],["עַל־נִינְוֵה","upon-Nineveh"],["הָעִיר","the-city"],["הַגְּדוֹלָה","the-great"],["אֲשֶׁר","which"],["יֶשׁ־בָּהּ","has-in-it(f)"],["הַרְבֵּה","much"],["מִשְׁתֵּים־עֶשְׂרֵה","more than-two plus-and-ten"],["רִבּוֹ","ten thousand"],["אָדָם","man"],["אֲשֶׁר","which"],["לֹא־יָדַע","not-he-knew"],["בֵּין־יְמִינוֹ","among-right hand-his"],["לִשְׂמֹאלוֹ","is to-left hand-his"],["וּבְהֵמָה","and-of-beasts"],["רַבָּה","much"],["׃",""]] },
];
renderVerseSet(jon_ch4Verses, 'jon-ch4-verses');

})();
