// ot_verses/mal.js — Malachi verse data
(function() {
var mal_ch1Verses = [
  { num:"א", words:[["מַשָּׂא","the burden of"],["דְבַר־יְהֹוָה","the word of the LORD"],["אֶל־יִשְׂרָאֵל","to Israel"],["בְּיַד","in the hand of"],["מַלְאָכִי","Malachi"],["׃",""]] },
  { num:"ב", words:[["אָהַבְתִּי","I have loved"],["אֶתְכֶם","you"],["אָמַר","said"],["יְהֹוָה","the LORD"],["וַאֲמַרְתֶּם","and you shall say"],["בַּמָּה","wherein"],["אֲהַבְתָּנוּ","have you loved us"],["הֲלוֹא־אָח","is it not a brother"],["עֵשָׂו","Esau"],["לְיַעֲקֹב","to Jacob"],["נְאֻם־יְהֹוָה","says the LORD"],["וָאֹהַב","and I loved"],["אֶת־יַעֲקֹב","Jacob"],["׃",""]] },
  { num:"ג", words:[["וְאֶת־עֵשָׂו","and Esau"],["שָׂנֵאתִי","I hated"],["וָאָשִׂים","and I set"],["אֶת־הָרָיו","its mountains"],["שְׁמָמָה","desolate"],["וְאֶת־נַחֲלָתוֹ","and his inheritance"],["לְתַנּוֹת","for the dragons of"],["מִדְבָּר","the wilderness"],["׃",""]] },
  { num:"ד", words:[["כִּי־תֹאמַר","that you say"],["אֱדוֹם","Edom"],["רֻשַּׁשְׁנוּ","we have been shattered"],["וְנָשׁוּב","and we may return"],["וְנִבְנֶה","so we may rebuild"],["חֳרָבוֹת","the desolate places"],["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["הֵמָּה","they"],["יִבְנוּ","they build"],["וַאֲנִי","and I"],["אֶהֱרוֹס","I will tear down"],["וְקָרְאוּ","and they shall call"],["לָהֶם","to them"],["גְּבוּל","border of"],["רִשְׁעָה","iniquity"],["וְהָעָם","and the people"],["אֲשֶׁר־זָעַם","against whom is indignant"],["יְהֹוָה","the LORD"],["עַד־עוֹלָם","forever"],["׃",""]] },
  { num:"ה", words:[["וְעֵינֵיכֶם","and your eyes"],["תִּרְאֶינָה","shall see"],["וְאַתֶּם","and you"],["תֹּאמְרוּ","you say"],["יִגְדַּל","shall be magnified"],["יְהֹוָה","the LORD"],["מֵעַל","from beyond"],["לִגְבוּל","to the border of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"ו", words:[["בֵּן","a son"],["יְכַבֵּד","he honors"],["אָב","father"],["וְעֶבֶד","and the servant of"],["אֲדֹנָיו","his master"],["וְאִם־אָב","and if father"],["אָנִי","I"],["אַיֵּה","where is"],["כְבוֹדִי","my honor"],["וְאִם־אֲדוֹנִים","and if a master"],["אָנִי","I"],["אַיֵּה","where is"],["מוֹרָאִי","my fear"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["לָכֶם","to you"],["הַכֹּהֲנִים","the priests"],["בּוֹזֵי","despisers of"],["שְׁמִי","my name"],["וַאֲמַרְתֶּם","and you shall say"],["בַּמֶּה","wherein"],["בָזִינוּ","have we despised"],["אֶת־שְׁמֶךָ","your name"],["׃",""]] },
  { num:"ז", words:[["מַגִּישִׁים","you are bringing near"],["עַל־מִזְבְּחִי","upon my altar"],["לֶחֶם","bread"],["מְגֹאָל","defiled"],["וַאֲמַרְתֶּם","and you shall say"],["בַּמֶּה","wherein"],["גֵאַלְנוּךָ","have we defiled you"],["בֶּאֱמׇרְכֶם","when you said"],["שֻׁלְחַן","the table of"],["יְהֹוָה","the LORD"],["נִבְזֶה","is contemptible"],["הוּא","it"],["׃",""]] },
  { num:"ח", words:[["וְכִי־תַגִּישׁוּן","and that you bring near"],["עִוֵּר","the blind"],["לִזְבֹּחַ","to offer"],["אֵין","there is no"],["רָע","evil"],["וְכִי","and that"],["תַגִּישׁוּ","you bring near"],["פִּסֵּחַ","lame"],["וְחֹלֶה","and a sick animal"],["אֵין","there is no"],["רָע","evil"],["הַקְרִיבֵהוּ","bring near it"],["נָא","I pray"],["לְפֶחָתֶךָ","to your governor"],["הֲיִרְצְךָ","will he be pleased with you"],["אוֹ","or"],["הֲיִשָּׂא","will he lift up"],["פָנֶיךָ","your face"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"ט", words:[["וְעַתָּה","and now"],["חַלּוּ־נָא","entreat I pray"],["פְנֵי־אֵל","the face of God"],["וִיחׇנֵּנוּ","so he may show favor to us"],["מִיֶּדְכֶם","from you"],["הָיְתָה","was"],["זֹּאת","this"],["הֲיִשָּׂא","will he lift up"],["מִכֶּם","from you"],["פָּנִים","persons"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"י", words:[["מִי","who"],["גַם־בָּכֶם","also in you"],["וְיִסְגֹּר","so he may shut"],["דְּלָתַיִם","gates"],["וְלֹא־תָאִירוּ","and ye kindle not"],["מִזְבְּחִי","my altar"],["חִנָּם","for nought"],["אֵין־לִי","I have no"],["חֵפֶץ","desire"],["בָּכֶם","in you"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["וּמִנְחָה","and a grain offering"],["לֹא־אֶרְצֶה","not I will accept"],["מִיֶּדְכֶם","from you"],["׃",""]] },
  { num:"יא", words:[["כִּי","because"],["מִמִּזְרַח־שֶׁמֶשׁ","from the rising of the sun"],["וְעַד־מְבוֹאוֹ","and unto its setting"],["גָּדוֹל","great"],["שְׁמִי","my name"],["בַּגּוֹיִם","among the nations"],["וּבְכׇל־מָקוֹם","and in every place"],["מֻקְטָר","incense"],["מֻגָּשׁ","is being brought near"],["לִשְׁמִי","to my name"],["וּמִנְחָה","and a grain offering"],["טְהוֹרָה","is pure"],["כִּי־גָדוֹל","for great is"],["שְׁמִי","my name"],["בַּגּוֹיִם","among the nations"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"יב", words:[["וְאַתֶּם","and you"],["מְחַלְּלִים","are profaning"],["אוֹתוֹ","him"],["בֶּאֱמׇרְכֶם","when you said"],["שֻׁלְחַן","the table of"],["אֲדֹנָי","the Lord"],["מְגֹאָל","defiled"],["הוּא","it"],["וְנִיבוֹ","and its fruit"],["נִבְזֶה","is contemptible"],["אׇכְלוֹ","his food"],["׃",""]] },
  { num:"יג", words:[["וַאֲמַרְתֶּם","and you shall say"],["הִנֵּה","behold"],["מַתְּלָאָה","what weariness"],["וְהִפַּחְתֶּם","and you sniff at"],["אוֹתוֹ","him"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["וַהֲבֵאתֶם","and you have brought"],["גָּזוּל","that which was torn"],["וְאֶת־הַפִּסֵּחַ","and the lame animal"],["וְאֶת־הַחוֹלֶה","and the sick"],["וַהֲבֵאתֶם","and you have brought"],["אֶת־הַמִּנְחָה","the grain offering"],["הַאֶרְצֶה","will I accept"],["אוֹתָהּ","it"],["מִיֶּדְכֶם","from you"],["אָמַר","said"],["יְהֹוָה","the LORD"],["׃",""]] },
  { num:"יד", words:[["וְאָרוּר","and cursed"],["נוֹכֵל","one who deals deceptively"],["וְיֵשׁ","and there was"],["בְּעֶדְרוֹ","in his flock"],["זָכָר","male"],["וְנֹדֵר","and one who makes a vow"],["וְזֹבֵחַ","and one who sacrifices"],["מׇשְׁחָת","a corrupt thing"],["לַאדֹנָי","to the Lord"],["כִּי","for"],["מֶלֶךְ","a king"],["גָּדוֹל","great"],["אָנִי","I"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["וּשְׁמִי","and my name"],["נוֹרָא","dreadful"],["בַגּוֹיִם","among the nations"],["׃",""]] },
];
renderVerseSet(mal_ch1Verses, 'mal-ch1-verses');

var mal_ch2Verses = [
  { num:"א", words:[["וְעַתָּה","and now"],["אֲלֵיכֶם","unto you"],["הַמִּצְוָה","the commandment"],["הַזֹּאת","this"],["הַכֹּהֲנִים","the priests"],["׃",""]] },
  { num:"ב", words:[["אִם־לֹא","if not"],["תִשְׁמְעוּ","you hearken"],["וְאִם־לֹא","and if not"],["תָשִׂימוּ","set"],["עַל־לֵב","upon heart"],["לָתֵת","to give"],["כָּבוֹד","glory"],["לִשְׁמִי","to my name"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["וְשִׁלַּחְתִּי","and I will send"],["בָכֶם","among you"],["אֶת־הַמְּאֵרָה","the curse"],["וְאָרוֹתִי","and I will curse"],["אֶת־בִּרְכוֹתֵיכֶם","your blessings"],["וְגַם","and also"],["אָרוֹתִיהָ","I have cursed it"],["כִּי","because"],["אֵינְכֶם","you are not"],["שָׂמִים","who put"],["עַל־לֵב","upon heart"],["׃",""]] },
  { num:"ג", words:[["הִנְנִי","behold I"],["גֹעֵר","am about to rebuke"],["לָכֶם","to you"],["אֶת־הַזֶּרַע","the seed"],["וְזֵרִיתִי","and I will disperse"],["פֶרֶשׁ","dung"],["עַל־פְּנֵיכֶם","upon the face of you"],["פֶּרֶשׁ","even the dung of"],["חַגֵּיכֶם","your feasts"],["וְנָשָׂא","and one shall take away"],["אֶתְכֶם","you"],["אֵלָיו","to him"],["׃",""]] },
  { num:"ד", words:[["וִידַעְתֶּם","and you shall know"],["כִּי","that"],["שִׁלַּחְתִּי","I have sent"],["אֲלֵיכֶם","unto you"],["אֵת־הַמִּצְוָה","the commandment"],["הַזֹּאת","this"],["לִהְיוֹת","to be"],["בְּרִיתִי","my covenant"],["אֶת־לֵוִי","with Levi"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"ה", words:[["בְּרִיתִי","my covenant"],["הָיְתָה","was"],["אִתּוֹ","with him"],["הַחַיִּים","the life"],["וְהַשָּׁלוֹם","and the peace"],["וָאֶתְּנֵם־לוֹ","and I gave them him"],["מוֹרָא","fear"],["וַיִּירָאֵנִי","and he feared me"],["וּמִפְּנֵי","and because of"],["שְׁמִי","my name"],["נִחַת","he was in awe"],["הוּא","he"],["׃",""]] },
  { num:"ו", words:[["תּוֹרַת","the law of"],["אֱמֶת","truth"],["הָיְתָה","was"],["בְּפִיהוּ","in his mouth"],["וְעַוְלָה","and injustice"],["לֹא־נִמְצָא","not was found"],["בִשְׂפָתָיו","on his lips"],["בְּשָׁלוֹם","in peace"],["וּבְמִישׁוֹר","and in uprightness"],["הָלַךְ","went"],["אִתִּי","with me"],["וְרַבִּים","and many"],["הֵשִׁיב","he turned away"],["מֵעָוֺן","from iniquity"],["׃",""]] },
  { num:"ז", words:[["כִּי־שִׂפְתֵי","because the lips of"],["כֹהֵן","a priest"],["יִשְׁמְרוּ־דַעַת","keep knowledge"],["וְתוֹרָה","and the Law"],["יְבַקְשׁוּ","seek"],["מִפִּיהוּ","from his mouth"],["כִּי","because"],["מַלְאַךְ","the messenger of"],["יְהֹוָה־צְבָאוֹת","the LORD of Hosts"],["הוּא","he"],["׃",""]] },
  { num:"ח", words:[["וְאַתֶּם","and you"],["סַרְתֶּם","you turned aside"],["מִן־הַדֶּרֶךְ","out of the way"],["הִכְשַׁלְתֶּם","you have caused to stumble"],["רַבִּים","many"],["בַּתּוֹרָה","by the Law"],["שִׁחַתֶּם","you have corrupted"],["בְּרִית","covenant of"],["הַלֵּוִי","the Levite"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"ט", words:[["וְגַם־אֲנִי","and also I"],["נָתַתִּי","I gave"],["אֶתְכֶם","you"],["נִבְזִים","contemptible"],["וּשְׁפָלִים","and low"],["לְכׇל־הָעָם","to all the people"],["כְּפִי","according to"],["אֲשֶׁר","which"],["אֵינְכֶם","you are not"],["שֹׁמְרִים","the ones who keep"],["אֶת־דְּרָכַי","my ways"],["וְנֹשְׂאִים","and you are lifting up"],["פָּנִים","persons"],["בַּתּוֹרָה","by the Law"],["׃",""]] },
  { num:"י", words:[["הֲלוֹא","is it not"],["אָב","father"],["אֶחָד","one"],["לְכֻלָּנוּ","to all of us"],["הֲלוֹא","is it not"],["אֵל","God"],["אֶחָד","one"],["בְּרָאָנוּ","did he create us"],["מַדּוּעַ","why"],["נִבְגַּד","do we deal treacherously"],["אִישׁ","a man"],["בְּאָחִיו","with another"],["לְחַלֵּל","by profaning"],["בְּרִית","covenant of"],["אֲבֹתֵינוּ","our fathers"],["׃",""]] },
  { num:"יא", words:[["בָּגְדָה","she deals treacherously"],["יְהוּדָה","Judah"],["וְתוֹעֵבָה","and abominable"],["נֶעֶשְׂתָה","it was done"],["בְיִשְׂרָאֵל","in Israel"],["וּבִירוּשָׁלָ͏ִם","and in Jerusalem"],["כִּי","for"],["חִלֵּל","he has profaned"],["יְהוּדָה","Judah"],["קֹדֶשׁ","the holiness of"],["יְהֹוָה","the LORD"],["אֲשֶׁר","which"],["אָהֵב","he loves"],["וּבָעַל","and it has married"],["בַּת־אֵל","the daughter of a god"],["נֵכָר","foreign"],["׃",""]] },
  { num:"יב", words:[["יַכְרֵת","may he cut off"],["יְהֹוָה","the LORD"],["לָאִישׁ","to the man"],["אֲשֶׁר","which"],["יַעֲשֶׂנָּה","he will do it"],["עֵר","the one who is awake"],["וְעֹנֶה","and one who answers"],["מֵאׇהֳלֵי","from the tents of"],["יַעֲקֹב","Jacob"],["וּמַגִּישׁ","and one who brings near"],["מִנְחָה","a grain offering"],["לַיהֹוָה","to the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"יג", words:[["וְזֹאת","and this"],["שֵׁנִית","again"],["תַּעֲשׂוּ","you do"],["כַּסּוֹת","covering"],["דִּמְעָה","tears"],["אֶת־מִזְבַּח","the altar of"],["יְהֹוָה","the LORD"],["בְּכִי","weeping"],["וַאֲנָקָה","and groaning"],["מֵאֵין","without"],["עוֹד","any more"],["פְּנוֹת","to face"],["אֶל־הַמִּנְחָה","to the grain offering"],["וְלָקַחַת","or to receive"],["רָצוֹן","favor"],["מִיֶּדְכֶם","from you"],["׃",""]] },
  { num:"יד", words:[["וַאֲמַרְתֶּם","and you shall say"],["עַל־מָה","upon what"],["עַל","upon"],["כִּי־יְהֹוָה","for the LORD"],["הֵעִיד","he testified"],["בֵּינְךָ","between you"],["וּבֵין","and between"],["אֵשֶׁת","the wife of"],["נְעוּרֶיךָ","your youth"],["אֲשֶׁר","which"],["אַתָּה","you"],["בָּגַדְתָּה","you have dealt treacherously"],["בָּהּ","in it"],["וְהִיא","and she"],["חֲבֶרְתְּךָ","your companion"],["וְאֵשֶׁת","and the wife of"],["בְּרִיתֶךָ","your covenant"],["׃",""]] },
  { num:"טו", words:[["וְלֹא־אֶחָד","and not one"],["עָשָׂה","he did"],["וּשְׁאָר","and remnant"],["רוּחַ","the spirit of"],["לוֹ","to him"],["וּמָה","and what"],["הָאֶחָד","the one"],["מְבַקֵּשׁ","seeking"],["זֶרַע","seed"],["אֱלֹהִים","of God"],["וְנִשְׁמַרְתֶּם","and you will take heed"],["בְּרוּחֲכֶם","in your spirit"],["וּבְאֵשֶׁת","and on the wife of"],["נְעוּרֶיךָ","your youth"],["אַל־יִבְגֹּד","let none deal treacherously"],["׃",""]] },
  { num:"טז", words:[["כִּי־שָׂנֵא","for he hates"],["שַׁלַּח","putting away"],["אָמַר","said"],["יְהֹוָה","the LORD"],["אֱלֹהֵי","the God of"],["יִשְׂרָאֵל","Israel"],["וְכִסָּה","and it will cover"],["חָמָס","violence"],["עַל־לְבוּשׁוֹ","upon its clothing"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["וְנִשְׁמַרְתֶּם","and you will take heed"],["בְּרוּחֲכֶם","in your spirit"],["וְלֹא","and not"],["תִבְגֹּדוּ","you shall act treacherously"],["׃",""]] },
  { num:"יז", words:[["הוֹגַעְתֶּם","you have wearied"],["יְהֹוָה","the LORD"],["בְּדִבְרֵיכֶם","with your words"],["וַאֲמַרְתֶּם","and you shall say"],["בַּמָּה","wherein"],["הוֹגָעְנוּ","did we weary him"],["בֶּאֱמׇרְכֶם","when you said"],["כׇּל־עֹשֵׂה","all that does"],["רָע","evil"],["טוֹב","good"],["בְּעֵינֵי","in the eyes of"],["יְהֹוָה","the LORD"],["וּבָהֶם","and among them"],["הוּא","he"],["חָפֵץ","desire"],["אוֹ","or"],["אַיֵּה","where is"],["אֱלֹהֵי","the God of"],["הַמִּשְׁפָּט","the judgment"],["׃",""]] },
];
renderVerseSet(mal_ch2Verses, 'mal-ch2-verses');

var mal_ch3Verses = [
  { num:"א", words:[["הִנְנִי","behold I"],["שֹׁלֵחַ","sent"],["מַלְאָכִי","My messenger"],["וּפִנָּה־דֶרֶךְ","and he shall prepare the way"],["לְפָנָי","before Me"],["וּפִתְאֹם","and suddenly"],["יָבוֹא","shall come"],["אֶל־הֵיכָלוֹ","to his temple"],["הָאָדוֹן","the Lord"],["אֲשֶׁר־אַתֶּם","which you are"],["מְבַקְשִׁים","seek"],["וּמַלְאַךְ","and the messenger of"],["הַבְּרִית","the covenant"],["אֲשֶׁר־אַתֶּם","which you are"],["חֲפֵצִים","willing"],["הִנֵּה־בָא","behold he comes"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"ב", words:[["וּמִי","and who"],["מְכַלְכֵּל","can endure"],["אֶת־יוֹם","the day of"],["בּוֹאוֹ","His coming"],["וּמִי","and who"],["הָעֹמֵד","the one who stands"],["בְּהֵרָאוֹתוֹ","when He appears"],["כִּי־הוּא","for He is"],["כְּאֵשׁ","like the fire of"],["מְצָרֵף","refiner"],["וּכְבֹרִית","and like the soap of"],["מְכַבְּסִים","fullers"],["׃",""]] },
  { num:"ג", words:[["וְיָשַׁב","and he shall sit"],["מְצָרֵף","refiner"],["וּמְטַהֵר","and purifier of"],["כֶּסֶף","silver"],["וְטִהַר","and he shall purify"],["אֶת־בְּנֵי־לֵוִי","sons of Levi"],["וְזִקַּק","and refine"],["אֹתָם","them"],["כַּזָּהָב","as the gold"],["וְכַכָּסֶף","and like the silver"],["וְהָיוּ","then they shall be"],["לַיהֹוָה","to the LORD"],["מַגִּישֵׁי","bringing near"],["מִנְחָה","a grain offering"],["בִּצְדָקָה","in righteousness"],["׃",""]] },
  { num:"ד", words:[["וְעָרְבָה","and it will be pleasing"],["לַיהֹוָה","to the LORD"],["מִנְחַת","grain offering of"],["יְהוּדָה","Judah"],["וִירוּשָׁלָ͏ִם","and Jerusalem"],["כִּימֵי","as days of"],["עוֹלָם","eternal"],["וּכְשָׁנִים","and as years"],["קַדְמֹנִיֹּת","former"],["׃",""]] },
  { num:"ה", words:[["וְקָרַבְתִּי","and I will draw near"],["אֲלֵיכֶם","unto you"],["לַמִּשְׁפָּט","to the judgment"],["וְהָיִיתִי","and I was"],["עֵד","witness"],["מְמַהֵר","hastening"],["בַּמְכַשְּׁפִים","against sorcerers"],["וּבַמְנָאֲפִים","and against adulterers"],["וּבַנִּשְׁבָּעִים","and against those who swear"],["לַשָּׁקֶר","to the falsehood"],["וּבְעֹשְׁקֵי","and on those who defraud"],["שְׂכַר־שָׂכִיר","the wages of a hired worker"],["אַלְמָנָה","a widow"],["וְיָתוֹם","and a fatherless one"],["וּמַטֵּי־גֵר","and those who thrust aside a sojourner"],["וְלֹא","and not"],["יְרֵאוּנִי","they shall fear me"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"ו", words:[["כִּי","for"],["אֲנִי","I"],["יְהֹוָה","the LORD"],["לֹא","not"],["שָׁנִיתִי","I have changed"],["וְאַתֶּם","and you"],["בְּנֵי־יַעֲקֹב","sons of Jacob"],["לֹא","not"],["כְלִיתֶם","you have come to an end"],["׃",""]] },
  { num:"ז", words:[["לְמִימֵי","from days of"],["אֲבֹתֵיכֶם","your fathers"],["סַרְתֶּם","you turned aside"],["מֵחֻקַּי","from my statutes"],["וְלֹא","and not"],["שְׁמַרְתֶּם","you have kept"],["שׁוּבוּ","return"],["אֵלַי","to me"],["וְאָשׁוּבָה","and I shall return"],["אֲלֵיכֶם","unto you"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["וַאֲמַרְתֶּם","and you shall say"],["בַּמֶּה","wherein"],["נָשׁוּב","return"],["׃",""]] },
  { num:"ח", words:[["הֲיִקְבַּע","will rob"],["אָדָם","man"],["אֱלֹהִים","God"],["כִּי","because"],["אַתֶּם","you are"],["קֹבְעִים","are robbing"],["אֹתִי","me"],["וַאֲמַרְתֶּם","and you shall say"],["בַּמֶּה","wherein"],["קְבַעֲנוּךָ","have we robbed you"],["הַמַּעֲשֵׂר","the tithe"],["וְהַתְּרוּמָה","and the offering"],["׃",""]] },
  { num:"ט", words:[["בַּמְּאֵרָה","with the curse"],["אַתֶּם","you are"],["נֵאָרִים","are cursed"],["וְאֹתִי","and me"],["אַתֶּם","you are"],["קֹבְעִים","are robbing"],["הַגּוֹי","the nation"],["כֻּלּוֹ","entirely"],["׃",""]] },
  { num:"י", words:[["הָבִיאוּ","bring"],["אֶת־כׇּל־הַמַּעֲשֵׂר","all the tithe"],["אֶל־בֵּית","to the house of"],["הָאוֹצָר","the treasury"],["וִיהִי","and may be"],["טֶרֶף","food"],["בְּבֵיתִי","in my house"],["וּבְחָנוּנִי","and test me"],["נָא","I pray"],["בָּזֹאת","in this"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["אִם־לֹא","if not"],["אֶפְתַּח","I shall open"],["לָכֶם","to you"],["אֵת־אֲרֻבּוֹת","windows"],["הַשָּׁמַיִם","the heavens"],["וַהֲרִיקֹתִי","and I will pour out"],["לָכֶם","to you"],["בְּרָכָה","a blessing"],["עַד־בְּלִי־דָי","until there is not enough"],["׃",""]] },
  { num:"יא", words:[["וְגָעַרְתִּי","and I shall rebuke"],["לָכֶם","to you"],["בָּאֹכֵל","the devourer"],["וְלֹא־יַשְׁחִת","and not he ruins"],["לָכֶם","to you"],["אֶת־פְּרִי","fruit"],["הָאֲדָמָה","the earth"],["וְלֹא־תְשַׁכֵּל","and shall not cast her fruit"],["לָכֶם","to you"],["הַגֶּפֶן","the vine"],["בַּשָּׂדֶה","in the field"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"יב", words:[["וְאִשְּׁרוּ","and they will call blessed"],["אֶתְכֶם","you"],["כׇּל־הַגּוֹיִם","all the nations"],["כִּי־תִהְיוּ","for ye shall be"],["אַתֶּם","you are"],["אֶרֶץ","the land of"],["חֵפֶץ","desire"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"יג", words:[["חָזְקוּ","have been stout"],["עָלַי","upon me"],["דִּבְרֵיכֶם","your words"],["אָמַר","said"],["יְהֹוָה","the LORD"],["וַאֲמַרְתֶּם","and you shall say"],["מַה־נִּדְבַּרְנוּ","what have we spoken together"],["עָלֶיךָ","upon you"],["׃",""]] },
  { num:"יד", words:[["אֲמַרְתֶּם","you have said"],["שָׁוְא","falsehood"],["עֲבֹד","to serve"],["אֱלֹהִים","God"],["וּמַה־בֶּצַע","yea and what gain"],["כִּי","that"],["שָׁמַרְנוּ","we kept"],["מִשְׁמַרְתּוֹ","His charge"],["וְכִי","and that"],["הָלַכְנוּ","we went"],["קְדֹרַנִּית","mournfully"],["מִפְּנֵי","because of"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"טו", words:[["וְעַתָּה","and now"],["אֲנַחְנוּ","we"],["מְאַשְּׁרִים","call blessed"],["זֵדִים","the proud"],["גַּם־נִבְנוּ","yea they are set up"],["עֹשֵׂי","doers of"],["רִשְׁעָה","iniquity"],["גַּם","also"],["בָּחֲנוּ","they tested"],["אֱלֹהִים","God"],["וַיִּמָּלֵטוּ","and they have escaped"],["׃",""]] },
  { num:"טז", words:[["אָז","then"],["נִדְבְּרוּ","they spoke"],["יִרְאֵי","those who fear"],["יְהֹוָה","the LORD"],["אִישׁ","a man"],["אֶל־רֵעֵהוּ","to his neighbor"],["וַיַּקְשֵׁב","and paid attention"],["יְהֹוָה","the LORD"],["וַיִּשְׁמָע","and he heard"],["וַיִּכָּתֵב","and there was written"],["סֵפֶר","a book"],["זִכָּרוֹן","remembrance"],["לְפָנָיו","before him"],["לְיִרְאֵי","for those who fear"],["יְהֹוָה","the LORD"],["וּלְחֹשְׁבֵי","and of those who esteemed"],["שְׁמוֹ","his name"],["׃",""]] },
  { num:"יז", words:[["וְהָיוּ","then they shall be"],["לִי","to me"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["לַיּוֹם","in the day"],["אֲשֶׁר","which"],["אֲנִי","I"],["עֹשֶׂה","do"],["סְגֻלָּה","a treasure"],["וְחָמַלְתִּי","and I will spare"],["עֲלֵיהֶם","upon them"],["כַּאֲשֶׁר","as"],["יַחְמֹל","spares"],["אִישׁ","a man"],["עַל־בְּנוֹ","upon his son"],["הָעֹבֵד","that serves"],["אֹתוֹ","him"],["׃",""]] },
  { num:"יח", words:[["וְשַׁבְתֶּם","and you will return"],["וּרְאִיתֶם","and you saw"],["בֵּין","among"],["צַדִּיק","righteous"],["לְרָשָׁע","wicked"],["בֵּין","among"],["עֹבֵד","him that serves"],["אֱלֹהִים","God"],["לַאֲשֶׁר","unto him who"],["לֹא","not"],["עֲבָדוֹ","served him"],["׃",""]] },
  { num:"יט", words:[["כִּי־הִנֵּה","because behold"],["הַיּוֹם","the day"],["בָּא","came"],["בֹּעֵר","was burning"],["כַּתַּנּוּר","like the furnace"],["וְהָיוּ","then they shall be"],["כׇל־זֵדִים","all the proud"],["וְכׇל־עֹשֵׂה","and all that does"],["רִשְׁעָה","iniquity"],["קַשׁ","stubble"],["וְלִהַט","and it will set ablaze"],["אֹתָם","them"],["הַיּוֹם","the day"],["הַבָּא","that comes"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["אֲשֶׁר","which"],["לֹא־יַעֲזֹב","not he shall forsake"],["לָהֶם","to them"],["שֹׁרֶשׁ","the root of"],["וְעָנָף","and branch"],["׃",""]] },
  { num:"כ", words:[["וְזָרְחָה","and it will rise"],["לָכֶם","to you"],["יִרְאֵי","those who fear"],["שְׁמִי","my name"],["שֶׁמֶשׁ","the sun of"],["צְדָקָה","righteousness"],["וּמַרְפֵּא","with healing"],["בִּכְנָפֶיהָ","in its wings"],["וִיצָאתֶם","and ye shall go forth"],["וּפִשְׁתֶּם","and ye shall grow up"],["כְּעֶגְלֵי","as calves of"],["מַרְבֵּק","the stall"],["׃",""]] },
  { num:"כא", words:[["וְעַסּוֹתֶם","and you shall trample"],["רְשָׁעִים","wicked men"],["כִּי־יִהְיוּ","because shall be"],["אֵפֶר","ashes"],["תַּחַת","under"],["כַּפּוֹת","the soles"],["רַגְלֵיכֶם","your foot"],["בַּיּוֹם","in the day"],["אֲשֶׁר","which"],["אֲנִי","I"],["עֹשֶׂה","do"],["אָמַר","said"],["יְהֹוָה","the LORD"],["צְבָאוֹת","of Hosts"],["׃",""]] },
  { num:"כב", words:[["זִכְרוּ","remember"],["תּוֹרַת","the law of"],["מֹשֶׁה","Moses"],["עַבְדִּי","my servant"],["אֲשֶׁר","which"],["צִוִּיתִי","have I commanded"],["אוֹתוֹ","him"],["בְחֹרֵב","in Horeb"],["עַל־כׇּל־יִשְׂרָאֵל","upon all Israel"],["חֻקִּים","laws"],["וּמִשְׁפָּטִים","and judgments"],["׃",""]] },
  { num:"כג", words:[["הִנֵּה","behold"],["אָנֹכִי","I"],["שֹׁלֵחַ","sent"],["לָכֶם","to you"],["אֵת־אֵלִיָּה","Elijah"],["הַנָּבִיא","the prophet"],["לִפְנֵי","before"],["בּוֹא","coming of"],["יוֹם","day"],["יְהֹוָה","the LORD"],["הַגָּדוֹל","the great"],["וְהַנּוֹרָא","and the awesome"],["׃",""]] },
  { num:"כד", words:[["וְהֵשִׁיב","and he shall turn"],["לֵב־אָבוֹת","the heart of the fathers"],["עַל־בָּנִים","upon sons"],["וְלֵב","and heart"],["בָּנִים","sons"],["עַל־אֲבוֹתָם","of their fathers"],["פֶּן־אָבוֹא","lest I will come"],["וְהִכֵּיתִי","and I will smite"],["אֶת־הָאָרֶץ","the earth"],["חֵרֶם","with utter destruction"],["׃",""]] },
];
renderVerseSet(mal_ch3Verses, 'mal-ch3-verses');

})();
