// ot_verses/mic.js — Micah verse data
(function() {
var mic_ch1Verses = [
  { num:"א", words:[["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["אֲשֶׁר","which"],["הָיָה","was"],["אֶל־מִיכָה","to-Micah"],["הַמֹּרַשְׁתִּי","the-Morasthite"],["בִּימֵי","in-days-of"],["יוֹתָם","Jotham"],["אָחָז","Ahaz"],["יְחִזְקִיָּה","Hezekiah"],["מַלְכֵי","Melchi"],["יְהוּדָה","Judah"],["אֲשֶׁר־חָזָה","whose-saw"],["עַל־שֹׁמְרוֹן","upon-Samaria"],["וִירוּשָׁלָ͏ִם","and-Jerusalem"],["׃",""]] },
  { num:"ב", words:[["שִׁמְעוּ","hear"],["עַמִּים","peoples"],["כֻּלָּם","all-of-them"],["הַקְשִׁיבִי","cause-it-to-be-heard"],["אֶרֶץ","the-land-of"],["וּמְלֹאָהּ","and-what fills-it"],["וִיהִי","and-may-be"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["בָּכֶם","in-you"],["לְעֵד","is-a-witness"],["אֲדֹנָי","Lord"],["מֵהֵיכַל","from-the temple of"],["קׇדְשׁוֹ","his-holy"],["׃",""]] },
  { num:"ג", words:[["כִּי־הִנֵּה","because-behold"],["יְהֹוָה","the-LORD"],["יֹצֵא","was going out"],["מִמְּקוֹמוֹ","from-place-its"],["וְיָרַד","and-go-down"],["וְדָרַךְ","and-he will tread"],["עַל־[בָּמֳתֵי]","upon-upon-small-numbers"],["(במותי)","at-death-my"],["אָרֶץ","the-earth"],["׃",""]] },
  { num:"ד", words:[["וְנָמַסּוּ","and-they will melt away"],["הֶהָרִים","the-mountains"],["תַּחְתָּיו","in-his-stead"],["וְהָעֲמָקִים","and-the-valleys"],["יִתְבַּקָּעוּ","they will be cleft"],["כַּדּוֹנַג","like-the-wax"],["מִפְּנֵי","because-of"],["הָאֵשׁ","the-flames"],["כְּמַיִם","like-waters"],["מֻגָּרִים","poured out"],["בְּמוֹרָד","on-a slope"],["׃",""]] },
  { num:"ה", words:[["בְּפֶשַׁע","into-transgression"],["יַעֲקֹב","Jacob"],["כׇּל־זֹאת","all-this"],["וּבְחַטֹּאות","and-for-the sins of"],["בֵּית","the-house-of"],["יִשְׂרָאֵל","Israel"],["מִי־פֶשַׁע","who-transgression"],["יַעֲקֹב","Jacob"],["הֲלוֹא","art-not"],["שֹׁמְרוֹן","Samaria"],["וּמִי","and-whoso"],["בָּמוֹת","Bamoth"],["יְהוּדָה","Judah"],["הֲלוֹא","art-not"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["׃",""]] },
  { num:"ו", words:[["וְשַׂמְתִּי","and-I-make"],["שֹׁמְרוֹן","Samaria"],["לְעִי","into-the heap of ruins of"],["הַשָּׂדֶה","the-field"],["לְמַטָּעֵי","into-a planting place of"],["כָרֶם","a vineyard"],["וְהִגַּרְתִּי","and-I will pour down"],["לַגַּי","to the-valley"],["אֲבָנֶיהָ","stones-its"],["וִיסֹדֶיהָ","and-foundations-its"],["אֲגַלֶּה","I-will-reveal"],["׃",""]] },
  { num:"ז", words:[["וְכׇל־פְּסִילֶיהָ","and-all-images-its"],["יֻכַּתּוּ","they are crushed to pieces"],["וְכׇל־אֶתְנַנֶּיהָ","and-all-hire-its"],["יִשָּׂרְפוּ","burned-shall-they-be"],["בָאֵשׁ","in-fire"],["וְכׇל־עֲצַבֶּיהָ","and-all-images-its"],["אָשִׂים","shall-I-put"],["שְׁמָמָה","desolate"],["כִּי","because"],["מֵאֶתְנַן","from-the hire of"],["זוֹנָה","harlot"],["קִבָּצָה","it gathered them"],["וְעַד־אֶתְנַן","and-unto-the price of"],["זוֹנָה","harlot"],["יָשׁוּבוּ","repent"],["׃",""]] },
  { num:"ח", words:[["עַל־זֹאת","upon-this"],["אֶסְפְּדָה","I will lament"],["וְאֵילִילָה","and-I will wail"],["אֵילְכָה","I will go"],["(שילל)","nude"],["[שׁוֹלָל]","barefoot"],["וְעָרוֹם","and-naked"],["אֶעֱשֶׂה","I-do"],["מִסְפֵּד","a lament"],["כַּתַּנִּים","like-the-jackals"],["וְאֵבֶל","and-a mourning"],["כִּבְנוֹת","like-the daughters of"],["יַעֲנָה","the-owl"],["׃",""]] },
  { num:"ט", words:[["כִּי","because"],["אֲנוּשָׁה","incurable"],["מַכּוֹתֶיהָ","wounds-its"],["כִּי־בָאָה","because-entered-into"],["עַד־יְהוּדָה","until-Judah"],["נָגַע","has-touched"],["עַד־שַׁעַר","until-gate-of"],["עַמִּי","my-people"],["עַד־יְרוּשָׁלָ͏ִם","until-Jerusalem"],["׃",""]] },
  { num:"י", words:[["בְּגַת","in-Gath"],["אַל־תַּגִּידוּ","do-not-you will tell"],["בָּכוֹ","certainly"],["אַל־תִּבְכּוּ","do-not-you-shall-weep"],["בְּבֵית","in-house-of"],["לְעַפְרָה","Leaphrah"],["עָפָר","the-earth"],["[הִתְפַּלָּשִׁי]","roll"],["׃",""]] },
  { num:"יא", words:[["עִבְרִי","Hebrew"],["לָכֶם","to-you"],["יוֹשֶׁבֶת","O-inhabitant-of"],["שָׁפִיר","Shaphir"],["עֶרְיָה־בֹשֶׁת","nakedness-shame"],["לֹא","not"],["יָצְאָה","went-forth"],["יוֹשֶׁבֶת","O-inhabitant-of"],["צַאֲנָן","Zaanan"],["מִסְפַּד","wailing of"],["בֵּית","the-house-of"],["הָאֵצֶל","the-Ezel"],["יִקַּח","take-upon-him"],["מִכֶּם","from-you"],["עֶמְדָּתוֹ","standing ground-its"],["׃",""]] },
  { num:"יב", words:[["כִּי־חָלָה","because-he became sick"],["לְטוֹב","for-good"],["יוֹשֶׁבֶת","O-inhabitant-of"],["מָרוֹת","Maroth"],["כִּי־יָרַד","because-came-down"],["רָע","evil"],["מֵאֵת","from"],["יְהֹוָה","the-LORD"],["לְשַׁעַר","to-O-gate"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["׃",""]] },
  { num:"יג", words:[["רְתֹם","harness"],["הַמֶּרְכָּבָה","the-chariot"],["לָרֶכֶשׁ","to the-steed"],["יוֹשֶׁבֶת","O-inhabitant-of"],["לָכִישׁ","Lachish"],["רֵאשִׁית","the-beginning-of"],["חַטָּאת","sin"],["הִיא","it"],["לְבַת־צִיּוֹן","to-the daughter of-Zion"],["כִּי־בָךְ","because-you"],["נִמְצְאוּ","they-were-found"],["פִּשְׁעֵי","transgressions-of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"יד", words:[["לָכֵן","therefore"],["תִּתְּנִי","you give"],["שִׁלּוּחִים","parting gifts"],["עַל","upon"],["מוֹרֶשֶׁת","Moresheth"],["גַּת","Gath"],["בָּתֵּי","in-twain"],["אַכְזִיב","Aczib"],["לְאַכְזָב","will become-a deceitful thing"],["לְמַלְכֵי","to-the kings of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"טו", words:[["עֹד","again"],["הַיֹּרֵשׁ","the-one who dispossesses"],["אָבִי","my-father"],["לָךְ","[compound]"],["יוֹשֶׁבֶת","O-inhabitant-of"],["מָרֵשָׁה","Mareshah"],["עַד־עֲדֻלָּם","until-Adullam"],["יָבוֹא","shall-come"],["כְּבוֹד","the-glory-of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"טז", words:[["קׇרְחִי","frost-my"],["וָגֹזִּי","and-shear"],["עַל־בְּנֵי","upon-sons-of"],["תַּעֲנוּגָיִךְ","delights-your"],["הַרְחִבִי","make large"],["קׇרְחָתֵךְ","baldness-your"],["כַּנֶּשֶׁר","like-the-eagle"],["כִּי","because"],["גָלוּ","they uncovered"],["מִמֵּךְ","from-you"],["׃",""]] },
];
renderVerseSet(mic_ch1Verses, 'mic-ch1-verses');

var mic_ch2Verses = [
  { num:"א", words:[["הוֹי","O"],["חֹשְׁבֵי־אָוֶן","those who plot-iniquity"],["וּפֹעֲלֵי","and-those who do"],["רָע","evil"],["עַל־מִשְׁכְּבוֹתָם","upon-beds-their"],["בְּאוֹר","in-light-of"],["הַבֹּקֶר","the-of-the-herd"],["יַעֲשׂוּהָ","they do-it"],["כִּי","because"],["יֶשׁ־לְאֵל","has-in-their"],["יָדָם","them"],["׃",""]] },
  { num:"ב", words:[["וְחָמְדוּ","and-they desire"],["שָׂדוֹת","fields"],["וְגָזָלוּ","and-they seize them"],["וּבָתִּים","and-the-houses"],["וְנָשָׂאוּ","and-they take them"],["וְעָשְׁקוּ","and-they oppress"],["גֶּבֶר","a man"],["וּבֵיתוֹ","and-his-house"],["וְאִישׁ","and-the-man-of"],["וְנַחֲלָתוֹ","and-inheritance-his"],["׃",""]] },
  { num:"ג", words:[["לָכֵן","therefore"],["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["הִנְנִי","behold-I"],["חֹשֵׁב","curious"],["עַל־הַמִּשְׁפָּחָה","upon-the-clan"],["הַזֹּאת","is-this"],["רָעָה","evil"],["אֲשֶׁר","which"],["לֹא־תָמִישׁוּ","not-you will remove"],["מִשָּׁם","from-there"],["צַוְּארֹתֵיכֶם","necks-your"],["וְלֹא","and-not"],["תֵלְכוּ","go"],["רוֹמָה","Rome"],["כִּי","because"],["עֵת","time"],["רָעָה","evil"],["הִיא","it"],["׃",""]] },
  { num:"ד", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["יִשָּׂא","takes-away"],["עֲלֵיכֶם","over-you"],["מָשָׁל","ruler"],["וְנָהָה","and-he will wail"],["נְהִי","wailing"],["נִהְיָה","has it occurred"],["אָמַר","said"],["שָׁדוֹד","utterly"],["נְשַׁדֻּנוּ","we are devastated"],["חֵלֶק","part"],["עַמִּי","my-people"],["יָמִיר","he will exchange"],["אֵיךְ","how"],["יָמִישׁ","it departed"],["לִי","to-me"],["לְשׁוֹבֵב","to-bring"],["שָׂדֵינוּ","fields-our"],["יְחַלֵּק","he-shall-divide"],["׃",""]] },
  { num:"ה", words:[["לָכֵן","therefore"],["לֹא־יִהְיֶה","there-would-be-no"],["לְךָ","for-you"],["מַשְׁלִיךְ","the one who throws"],["חֶבֶל","the region of"],["בְּגוֹרָל","by-lot"],["בִּקְהַל","in-the assembly of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ו", words:[["אַל־תַּטִּפוּ","do-not-you prophesy"],["יַטִּיפוּן","they prophesy-!"],["לֹא־יַטִּפוּ","not-they will prophesy"],["לָאֵלֶּה","to-such"],["לֹא","not"],["יִסַּג","it will be turned back"],["כְּלִמּוֹת","ignominies"],["׃",""]] },
  { num:"ז", words:[["הֶאָמוּר","¿-is it said"],["בֵּית־יַעֲקֹב","the-house-of-Jacob"],["הֲקָצַר","¿-is it short"],["רוּחַ","the-spirit-of"],["יְהֹוָה","the-LORD"],["אִם־אֵלֶּה","[compound]-these"],["מַעֲלָלָיו","deeds-his"],["הֲלוֹא","art-not"],["דְבָרַי","my-words"],["יֵיטִיבוּ","do they do good"],["עִם","with"],["הַיָּשָׁר","the-straight"],["הֹלֵךְ","going"],["׃",""]] },
  { num:"ח", words:[["וְאֶתְמוּל","and-yesterday"],["עַמִּי","my-people"],["לְאוֹיֵב","the-enemy-of"],["יְקוֹמֵם","he raises up"],["מִמּוּל","from-in front of"],["שַׂלְמָה","a garment"],["אֶדֶר","a mantle"],["תַּפְשִׁטוּן","you strip off-!"],["מֵעֹבְרִים","from-those who pass by"],["בֶּטַח","security"],["שׁוּבֵי","those who return of"],["מִלְחָמָה","war"],["׃",""]] },
  { num:"ט", words:[["נְשֵׁי","the-wives-and"],["עַמִּי","my-people"],["תְּגָרְשׁוּן","you drive out-!"],["מִבֵּית","from-house-of"],["תַּעֲנֻגֶיהָ","delights-her"],["מֵעַל","from-upon"],["עֹלָלֶיהָ","children-her"],["תִּקְחוּ","you will take"],["הֲדָרִי","glory-my"],["לְעוֹלָם","forever"],["׃",""]] },
  { num:"י", words:[["קוּמוּ","arise"],["וּלְכוּ","and-go"],["כִּי","because"],["לֹא־זֹאת","not-this"],["הַמְּנוּחָה","the-resting place"],["בַּעֲבוּר","because-of"],["טָמְאָה","it has become unclean"],["תְּחַבֵּל","it will destroy"],["וְחֶבֶל","and-a portion"],["נִמְרָץ","will be grievous"],["׃",""]] },
  { num:"יא", words:[["לוּ־אִישׁ","if-man-of"],["הֹלֵךְ","going"],["רוּחַ","the-spirit-of"],["וָשֶׁקֶר","and-falsehood"],["כִּזֵּב","he told a lie"],["אַטִּף","I will prophesy"],["לְךָ","for-you"],["לַיַּיִן","of-the-wine"],["וְלַשֵּׁכָר","and-of-the-strong drink"],["וְהָיָה","and-be"],["מַטִּיף","preaching"],["הָעָם","the-people"],["הַזֶּה","this"],["׃",""]] },
  { num:"יב", words:[["אָסֹף","surely"],["אֶאֱסֹף","I will gather"],["יַעֲקֹב","Jacob"],["כֻּלָּךְ","all of-you"],["קַבֵּץ","gathered"],["אֲקַבֵּץ","I-will-gathered"],["שְׁאֵרִית","remnant-of"],["יִשְׂרָאֵל","Israel"],["יַחַד","oft"],["אֲשִׂימֶנּוּ","I will make-him"],["כְּצֹאן","like-sheep of"],["בׇּצְרָה","sheep fold"],["כְּעֵדֶר","as-a-wild-flock"],["בְּתוֹךְ","among"],["הַדׇּבְרוֹ","the-thing-his"],["תְּהִימֶנָה","they will be distraught"],["מֵאָדָם","for-man"],["׃",""]] },
  { num:"יג", words:[["עָלָה","ascended"],["הַפֹּרֵץ","the-one who breaks through"],["לִפְנֵיהֶם","down-before-them"],["פָּרְצוּ","they-broke-through"],["וַיַּעֲבֹרוּ","and-they passed over"],["שַׁעַר","the-gate-of"],["וַיֵּצְאוּ","and-they-departed"],["בוֹ","in-Him"],["וַיַּעֲבֹר","and-overcame"],["מַלְכָּם","their-king"],["לִפְנֵיהֶם","down-before-them"],["וַיהֹוָה","and-Yahweh"],["בְּרֹאשָׁם","at-their-head"],["׃",""]] },
];
renderVerseSet(mic_ch2Verses, 'mic-ch2-verses');

var mic_ch3Verses = [
  { num:"א", words:[["וָאֹמַר","and-I-said"],["שִׁמְעוּ־נָא","hear-you-now"],["רָאשֵׁי","the-heads-of"],["יַעֲקֹב","Jacob"],["וּקְצִינֵי","and-O rulers of"],["בֵּית","the-house-of"],["יִשְׂרָאֵל","Israel"],["הֲלוֹא","art-not"],["לָכֶם","to-you"],["לָדַעַת","to-know"],["אֶת־הַמִּשְׁפָּט","[ACC]-the-judgment"],["׃",""]] },
  { num:"ב", words:[["שֹׂנְאֵי","who hate"],["טוֹב","good"],["וְאֹהֲבֵי","and-those who love"],["(רעה)","evil"],["[רָע]","evil"],["גֹּזְלֵי","tearers away of"],["עוֹרָם","their-skins"],["מֵעֲלֵיהֶם","from-off-them"],["וּשְׁאֵרָם","and-flesh-their"],["מֵעַל","from-upon"],["עַצְמוֹתָם","bones-their"],["׃",""]] },
  { num:"ג", words:[["וַאֲשֶׁר","and-whom"],["אָכְלוּ","did-partake"],["שְׁאֵר","relative of"],["עַמִּי","my-people"],["וְעוֹרָם","and-their-skins"],["מֵעֲלֵיהֶם","from-off-them"],["הִפְשִׁיטוּ","they have stripped off"],["וְאֶת־עַצְמֹתֵיהֶם","and-[ACC]-bones-their"],["פִּצֵּחוּ","they have broken in pieces"],["וּפָרְשׂוּ","and-they will spread out"],["כַּאֲשֶׁר","when/as"],["בַּסִּיר","is in the-pot"],["וּכְבָשָׂר","and-like-meat"],["בְּתוֹךְ","among"],["קַלָּחַת","a caldron"],["׃",""]] },
  { num:"ד", words:[["אָז","then"],["יִזְעֲקוּ","when-they-shall-cry"],["אֶל־יְהֹוָה","to-the-Lord"],["וְלֹא","and-not"],["יַעֲנֶה","he will answer"],["אוֹתָם","them"],["וְיַסְתֵּר","and-he may hide"],["פָּנָיו","His-face"],["מֵהֶם","of-them"],["בָּעֵת","at-the-time"],["הַהִיא","that"],["כַּאֲשֶׁר","when/as"],["הֵרֵעוּ","the-evil-his"],["מַעַלְלֵיהֶם","their-doings"],["׃",""]] },
  { num:"ה", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["עַל־הַנְּבִיאִים","upon-the-prophets"],["הַמַּתְעִים","the-who-mislead"],["אֶת־עַמִּי","[ACC]-my-people"],["הַנֹּשְׁכִים","the-who-bite"],["בְּשִׁנֵּיהֶם","with-teeth-their"],["וְקָרְאוּ","and-called-upon"],["שָׁלוֹם","peace"],["וַאֲשֶׁר","and-whom"],["לֹא־יִתֵּן","shall-not-permit"],["עַל־פִּיהֶם","upon-his-mouth"],["וְקִדְּשׁוּ","and-they consecrate"],["עָלָיו","upon-him"],["מִלְחָמָה","war"],["׃",""]] },
  { num:"ו", words:[["לָכֵן","therefore"],["לַיְלָה","night"],["לָכֶם","to-you"],["מֵחָזוֹן","from-vision"],["וְחָשְׁכָה","and-it will grow dark"],["לָכֶם","to-you"],["מִקְּסֹם","from-divining"],["וּבָאָה","and-comes"],["הַשֶּׁמֶשׁ","the-sun"],["עַל־הַנְּבִיאִים","upon-the-prophets"],["וְקָדַר","and-it will be dark"],["עֲלֵיהֶם","against-them"],["הַיּוֹם","the-day"],["׃",""]] },
  { num:"ז", words:[["וּבֹשׁוּ","and-they will be ashamed"],["הַחֹזִים","the-seers"],["וְחָפְרוּ","and-they will be abashed"],["הַקֹּסְמִים","the-those-who divine"],["וְעָטוּ","and-they will cover"],["עַל־שָׂפָם","upon-a moustache"],["כֻּלָּם","all-of-them"],["כִּי","because"],["אֵין","there-is-no"],["מַעֲנֵה","the answer of"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"ח", words:[["וְאוּלָם","nevertheless"],["אָנֹכִי","I"],["מָלֵאתִי","filled-am-I"],["כֹחַ","power-of"],["אֶת־רוּחַ","[ACC]-the-Spirit-of"],["יְהֹוָה","the-LORD"],["וּמִשְׁפָּט","and-judgment"],["וּגְבוּרָה","and-might"],["לְהַגִּיד","to-declare"],["לְיַעֲקֹב","to-Jacob"],["פִּשְׁעוֹ","transgression-his"],["וּלְיִשְׂרָאֵל","and-for-Israel"],["חַטָּאתוֹ","the-crime"],["׃",""]] },
  { num:"ט", words:[["שִׁמְעוּ־נָא","hear-you-now"],["זֹאת","this"],["רָאשֵׁי","the-heads-of"],["בֵּית","the-house-of"],["יַעֲקֹב","Jacob"],["וּקְצִינֵי","and-O rulers of"],["בֵּית","the-house-of"],["יִשְׂרָאֵל","Israel"],["הַמְתַעֲבִים","the-one who abhors(pl)"],["מִשְׁפָּט","judgment"],["וְאֵת","and-[ACC]"],["כׇּל־הַיְשָׁרָה","all-the-right"],["יְעַקֵּשׁוּ","they make crooked"],["׃",""]] },
  { num:"י", words:[["בֹּנֶה","building"],["צִיּוֹן","Zion"],["בְּדָמִים","blood"],["וִירוּשָׁלַ͏ִם","and-Jerusalem"],["בְּעַוְלָה","with-injustice"],["׃",""]] },
  { num:"יא", words:[["רָאשֶׁיהָ","chiefs-its"],["בְּשֹׁחַד","for-a bribe"],["יִשְׁפֹּטוּ","they vindicate"],["וְכֹהֲנֶיהָ","and-priests-its"],["בִּמְחִיר","for-a price"],["יוֹרוּ","shall-teach"],["וּנְבִיאֶיהָ","and-prophets-its"],["בְּכֶסֶף","in-money"],["יִקְסֹמוּ","they divine"],["וְעַל־יְהֹוָה","and-upon-the-LORD"],["יִשָּׁעֵנוּ","they depend"],["לֵאמֹר","saying"],["הֲלוֹא","art-not"],["יְהֹוָה","the-LORD"],["בְּקִרְבֵּנוּ","among-us"],["לֹא־תָבוֹא","there-shall-not-come"],["עָלֵינוּ","over-us"],["רָעָה","evil"],["׃",""]] },
  { num:"יב", words:[["לָכֵן","therefore"],["בִּגְלַלְכֶם","because-of-you"],["צִיּוֹן","Zion"],["שָׂדֶה","field"],["תֵחָרֵשׁ","it will be plowed"],["וִירוּשָׁלַ͏ִם","and-Jerusalem"],["עִיִּין","heaps of ruins"],["תִּהְיֶה","shall-be"],["וְהַר","and-the mountain of"],["הַבַּיִת","the-house"],["לְבָמוֹת","high places of"],["יָעַר","the forest"],["׃",""]] },
];
renderVerseSet(mic_ch3Verses, 'mic-ch3-verses');

var mic_ch4Verses = [
  { num:"א", words:[["וְהָיָה","and-be"],["בְּאַחֲרִית","in-latter"],["הַיָּמִים","the-days"],["יִהְיֶה","shall-be"],["הַר","mountain"],["בֵּית־יְהֹוָה","the-house-of-the-LORD"],["נָכוֹן","expedient"],["בְּרֹאשׁ","in-the-gall-of"],["הֶהָרִים","the-mountains"],["וְנִשָּׂא","and-exalted"],["הוּא","it"],["מִגְּבָעוֹת","above-the-hills"],["וְנָהֲרוּ","and-shall-flow"],["עָלָיו","upon-him"],["עַמִּים","peoples"],["׃",""]] },
  { num:"ב", words:[["וְהָלְכוּ","and-they-shall-depart"],["גּוֹיִם","nations/gentiles"],["רַבִּים","many"],["וְאָמְרוּ","shall-say"],["לְכוּ","go"],["וְנַעֲלֶה","and-let-us-go-up"],["אֶל־הַר־יְהֹוָה","to-mountain-the-LORD"],["וְאֶל־בֵּית","and-house-of"],["אֱלֹהֵי","the-God-of"],["יַעֲקֹב","Jacob"],["וְיוֹרֵנוּ","and-He-will-teach-us"],["מִדְּרָכָיו","of-His-ways"],["וְנֵלְכָה","and-we-will-walk"],["בְּאֹרְחֹתָיו","in-His-paths"],["כִּי","because"],["מִצִּיּוֹן","out-of-Zion"],["תֵּצֵא","shall-go-forth"],["תוֹרָה","Torah/law"],["וּדְבַר־יְהֹוָה","and-the-word-of-the-LORD"],["מִירוּשָׁלָ͏ִם","were more than-Jerusalem"],["׃",""]] },
  { num:"ג", words:[["וְשָׁפַט","but-with-righteousness-shall-he-judge"],["בֵּין","among"],["עַמִּים","peoples"],["רַבִּים","many"],["וְהוֹכִיחַ","and-he-reproved"],["לְגוֹיִם","for-other-nations"],["עֲצֻמִים","mighty"],["עַד־רָחוֹק","until-far"],["וְכִתְּתוּ","and-they-shall-beat"],["חַרְבֹתֵיהֶם","swords-their"],["לְאִתִּים","into-plowshares"],["וַחֲנִיתֹתֵיהֶם","and-spears-their"],["לְמַזְמֵרוֹת","into-pruning-hooks"],["לֹא־יִשְׂאוּ","not-shall-lift-up"],["גּוֹי","nation"],["אֶל־גּוֹי","against-nation"],["חֶרֶב","the-sword-of"],["וְלֹא־יִלְמְדוּן","and-not-they will learn-!"],["עוֹד","any-more"],["מִלְחָמָה","war"],["׃",""]] },
  { num:"ד", words:[["וְיָשְׁבוּ","and-they-were-settled"],["אִישׁ","man-of"],["תַּחַת","under"],["גַּפְנוֹ","own vine-his"],["וְתַחַת","and-under"],["תְּאֵנָתוֹ","own fig tree-his"],["וְאֵין","and-has-no"],["מַחֲרִיד","will be one who terrifies"],["כִּי־פִי","because-Pi"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["דִּבֵּר","spoke"],["׃",""]] },
  { num:"ה", words:[["כִּי","because"],["כׇּל־הָעַמִּים","all-the-people"],["יֵלְכוּ","they-should-travel"],["אִישׁ","man-of"],["בְּשֵׁם","by-name"],["אֱלֹהָיו","their-God"],["וַאֲנַחְנוּ","and-we-are"],["נֵלֵךְ","we-should-go"],["בְּשֵׁם־יְהֹוָה","by-name-the-LORD"],["אֱלֹהֵינוּ","our-God"],["לְעוֹלָם","forever"],["וָעֶד","and-ever"],["׃",""]] },
  { num:"ו", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["נְאֻם־יְהֹוָה","says-the-LORD"],["אֹסְפָה","I will gather"],["הַצֹּלֵעָה","the-one who is lame"],["וְהַנִּדָּחָה","and-the-one who is outcast"],["אֲקַבֵּצָה","I will assemble"],["וַאֲשֶׁר","and-whom"],["הֲרֵעֹתִי","I have done harm to"],["׃",""]] },
  { num:"ז", words:[["וְשַׂמְתִּי","and-I-make"],["אֶת־הַצֹּלֵעָה","[ACC]-the-one who is lame"],["לִשְׁאֵרִית","for-remnant-of"],["וְהַנַּהֲלָאָה","and-the-one who was straying"],["לְגוֹי","unto-one-nation"],["עָצוּם","mighty"],["וּמָלַךְ","and-your-God-reigns"],["יְהֹוָה","the-LORD"],["עֲלֵיהֶם","against-them"],["בְּהַר","while-on-the-mount-of"],["צִיּוֹן","Zion"],["מֵעַתָּה","from-this-time"],["וְעַד־עוֹלָם","and-forever"],["׃",""]] },
  { num:"ח", words:[["וְאַתָּה","for-you"],["מִגְדַּל־עֵדֶר","Migdal-Eder"],["עֹפֶל","the hill"],["בַּת־צִיּוֹן","the-daughter-of-Zion"],["עָדֶיךָ","to-you"],["תֵּאתֶה","it will come"],["וּבָאָה","and-comes"],["הַמֶּמְשָׁלָה","the-government"],["הָרִאשֹׁנָה","the-first"],["מַמְלֶכֶת","the-kingdom-of"],["לְבַת","to-the daughter of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["׃",""]] },
  { num:"ט", words:[["עַתָּה","now"],["לָמָּה","why"],["תָרִיעִי","do you shout"],["רֵעַ","a friend"],["הֲמֶלֶךְ","¿-a king"],["אֵין־בָּךְ","there-is-no-in-You"],["אִם־יוֹעֲצֵךְ","[compound]-counselor-your"],["אָבָד","did he perish"],["כִּי־הֶחֱזִיקֵךְ","because-it has taken hold of-you"],["חִיל","anguish"],["כַּיּוֹלֵדָה","as-the-a-woman-in-travail"],["׃",""]] },
  { num:"י", words:[["חוּלִי","tremble"],["וָגֹחִי","and-burst forth"],["בַּת־צִיּוֹן","the-daughter-of-Zion"],["כַּיּוֹלֵדָה","as-the-a-woman-in-travail"],["כִּי־עַתָּה","because-now"],["תֵצְאִי","you will go out"],["מִקִּרְיָה","from-the town"],["וְשָׁכַנְתְּ","and-you will dwell"],["בַּשָּׂדֶה","in-the-field"],["וּבָאת","and-you will go"],["עַד־בָּבֶל","until-Babylon"],["שָׁם","there"],["תִּנָּצֵלִי","you will be delivered"],["שָׁם","there"],["יִגְאָלֵךְ","he will redeem-you"],["יְהֹוָה","the-LORD"],["מִכַּף","from-the-wrist"],["אֹיְבָיִךְ","your-enemies"],["׃",""]] },
  { num:"יא", words:[["וְעַתָּה","and-now"],["נֶאֶסְפוּ","gathered"],["עָלַיִךְ","upon-you(f)"],["גּוֹיִם","nations/gentiles"],["רַבִּים","many"],["הָאֹמְרִים","the-ones-saying"],["תֶּחֱנָף","let her be polluted"],["וְתַחַז","and-let it look"],["בְּצִיּוֹן","in-Zion"],["עֵינֵינוּ","our-eyes"],["׃",""]] },
  { num:"יב", words:[["וְהֵמָּה","and-they-are"],["לֹא","not"],["יָדְעוּ","they-knew"],["מַחְשְׁבוֹת","purposes-of"],["יְהֹוָה","the-LORD"],["וְלֹא","and-not"],["הֵבִינוּ","understand"],["עֲצָתוֹ","His-counsel"],["כִּי","because"],["קִבְּצָם","he has gathered-them"],["כֶּעָמִיר","like-cut grain"],["גֹּרְנָה","the threshing floor-towards"],["׃",""]] },
  { num:"יג", words:[["קוּמִי","stand-up"],["וָדוֹשִׁי","and-thresh"],["בַת־צִיּוֹן","the daughter of-Zion"],["כִּי־קַרְנֵךְ","because-horn-your"],["אָשִׂים","shall-I-put"],["בַּרְזֶל","iron"],["וּפַרְסֹתַיִךְ","and-hooves-your"],["אָשִׂים","shall-I-put"],["נְחוּשָׁה","brass"],["וַהֲדִקּוֹת","and-you will crush"],["עַמִּים","peoples"],["רַבִּים","many"],["וְהַחֲרַמְתִּי","and-the-I-shall-devote-to-destruction"],["לַיהֹוָה","to-Yahweh"],["בִּצְעָם","gain-their"],["וְחֵילָם","and-their-forces"],["לַאֲדוֹן","to-the-master-of"],["כׇּל־הָאָרֶץ","all-the-earth"],["׃",""]] },
  { num:"יד", words:[["עַתָּה","now"],["תִּתְגֹּדְדִי","you will cut yourself"],["בַת־גְּדוּד","the daughter of-troop"],["מָצוֹר","siege works"],["שָׂם","set"],["עָלֵינוּ","over-us"],["בַּשֵּׁבֶט","with-the-rod"],["יַכּוּ","shall-they-smite"],["עַל־הַלְּחִי","upon-the-cheek"],["אֵת","[ACC]"],["שֹׁפֵט","judge"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
];
renderVerseSet(mic_ch4Verses, 'mic-ch4-verses');

var mic_ch5Verses = [
  { num:"א", words:[["וְאַתָּה","for-you"],["בֵּית־לֶחֶם","Bethlehem"],["אֶפְרָתָה","Ephrathah"],["צָעִיר","young-man"],["לִהְיוֹת","to-be"],["בְּאַלְפֵי","among-the families of"],["יְהוּדָה","Judah"],["מִמְּךָ","from-you"],["לִי","to-me"],["יֵצֵא","he-go-forth"],["לִהְיוֹת","to-be"],["מוֹשֵׁל","ruler"],["בְּיִשְׂרָאֵל","Israel"],["וּמוֹצָאֹתָיו","and-origins-his"],["מִקֶּדֶם","of-old"],["מִימֵי","from-the-days-of"],["עוֹלָם","eternal"],["׃",""]] },
  { num:"ב", words:[["לָכֵן","therefore"],["יִתְּנֵם","he-shall-give-them"],["עַד־עֵת","until-the-own-due-time-of"],["יוֹלֵדָה","a woman who gives birth"],["יָלָדָה","she-bore"],["וְיֶתֶר","and-the-remainder-of-them"],["אֶחָיו","his-elder"],["יְשׁוּבוּן","they will turn back-!"],["עַל־בְּנֵי","upon-sons-of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"ג", words:[["וְעָמַד","and-it stood"],["וְרָעָה","and-Shepherd"],["בְּעֹז","with-boldness"],["יְהֹוָה","the-LORD"],["בִּגְאוֹן","in-the-pride-of"],["שֵׁם","the-name-of"],["יְהֹוָה","the-LORD"],["אֱלֹהָיו","their-God"],["וְיָשָׁבוּ","and-they will dwell in them"],["כִּי־עַתָּה","because-now"],["יִגְדַּל","shall-grow"],["עַד־אַפְסֵי־אָרֶץ","until-the-ends-of-the-earth"],["׃",""]] },
  { num:"ד", words:[["וְהָיָה","and-be"],["זֶה","this"],["שָׁלוֹם","peace"],["אַשּׁוּר","Assyria"],["כִּי־יָבוֹא","because-shall-come"],["בְאַרְצֵנוּ","in-land-our"],["וְכִי","and-that"],["יִדְרֹךְ","may he bend"],["בְּאַרְמְנוֹתֵינוּ","in-fortresses-our"],["וַהֲקֵמֹנוּ","and-we will raise up"],["עָלָיו","upon-him"],["שִׁבְעָה","seven"],["רֹעִים","pasturing"],["וּשְׁמֹנָה","and-eight"],["נְסִיכֵי","the princes of"],["אָדָם","man"],["׃",""]] },
  { num:"ה", words:[["וְרָעוּ","and-shall-feed"],["אֶת־אֶרֶץ","ACC-land-of"],["אַשּׁוּר","Assyria"],["בַּחֶרֶב","with-the-sword"],["וְאֶת־אֶרֶץ","and-[ACC]-land-of"],["נִמְרֹד","Nimrod"],["בִּפְתָחֶיהָ","at-entrances-its"],["וְהִצִּיל","and-preserved-them"],["מֵאַשּׁוּר","from-Assyria"],["כִּי־יָבוֹא","because-shall-come"],["בְאַרְצֵנוּ","in-land-our"],["וְכִי","and-that"],["יִדְרֹךְ","may he bend"],["בִּגְבוּלֵנוּ","in-territory-our"],["׃",""]] },
  { num:"ו", words:[["וְהָיָה","and-be"],["שְׁאֵרִית","remnant-of"],["יַעֲקֹב","Jacob"],["בְּקֶרֶב","among"],["עַמִּים","peoples"],["רַבִּים","many"],["כְּטַל","as-dew"],["מֵאֵת","from"],["יְהֹוָה","the-LORD"],["כִּרְבִיבִים","like-copious showers"],["עֲלֵי־עֵשֶׂב","on-herb"],["אֲשֶׁר","which"],["לֹא־יְקַוֶּה","not-hopes"],["לְאִישׁ","for-a-man"],["וְלֹא","and-not"],["יְיַחֵל","it waits"],["לִבְנֵי","unto-the-children-of"],["אָדָם","man"],["׃",""]] },
  { num:"ז", words:[["וְהָיָה","and-be"],["שְׁאֵרִית","remnant-of"],["יַעֲקֹב","Jacob"],["בַּגּוֹיִם","by-the-nations"],["בְּקֶרֶב","among"],["עַמִּים","peoples"],["רַבִּים","many"],["כְּאַרְיֵה","as-a-lion"],["בְּבַהֲמוֹת","in-herds"],["יַעַר","Ir"],["כִּכְפִיר","like-a-young-lion"],["בְּעֶדְרֵי־צֹאן","in-flock-my-flocks"],["אֲשֶׁר","which"],["אִם־עָבַר","if-passed"],["וְרָמַס","and-trampled"],["וְטָרַף","and-he-tears"],["וְאֵין","and-has-no"],["מַצִּיל","shall-deliver-them"],["׃",""]] },
  { num:"ח", words:[["תָּרֹם","it-shall-be-exalted"],["יָדְךָ","your-hand"],["עַל־צָרֶיךָ","upon-necessary"],["וְכׇל־אֹיְבֶיךָ","and-all-enemies-your"],["יִכָּרֵתוּ","cut-off"],["׃",""]] },
  { num:"ט", words:[["וְהָיָה","and-be"],["בַיּוֹם־הַהוּא","in-that-the-day"],["נְאֻם־יְהֹוָה","says-the-LORD"],["וְהִכְרַתִּי","and-cut-off"],["סוּסֶיךָ","your-horses"],["מִקִּרְבֶּךָ","from-battle-your"],["וְהַאֲבַדְתִּי","and-the-perished"],["מַרְכְּבֹתֶיךָ","chariots-your"],["׃",""]] },
  { num:"י", words:[["וְהִכְרַתִּי","and-cut-off"],["עָרֵי","cities-of"],["אַרְצֶךָ","to-the-earth-your"],["וְהָרַסְתִּי","and-the-he-destroyed-my"],["כׇּל־מִבְצָרֶיךָ","all-fortifications-your"],["׃",""]] },
  { num:"יא", words:[["וְהִכְרַתִּי","and-cut-off"],["כְשָׁפִים","sorceries"],["מִיָּדֶךָ","from-your-hand"],["וּמְעוֹנְנִים","and-soothsayers"],["לֹא","not"],["יִהְיוּ־לָךְ","shall-be-[compound]"],["׃",""]] },
  { num:"יב", words:[["וְהִכְרַתִּי","and-cut-off"],["פְסִילֶיךָ","your-idols"],["וּמַצֵּבוֹתֶיךָ","and-his-state-of-your"],["מִקִּרְבֶּךָ","from-battle-your"],["וְלֹא־תִשְׁתַּחֲוֶה","and-not-bow-down"],["עוֹד","any-more"],["לְמַעֲשֵׂה","unto-the-work-of"],["יָדֶיךָ","your-hands"],["׃",""]] },
  { num:"יג", words:[["וְנָתַשְׁתִּי","and-I-shall-uproot"],["אֲשֵׁירֶיךָ","your-Asherim"],["מִקִּרְבֶּךָ","from-battle-your"],["וְהִשְׁמַדְתִּי","and-I will destroy"],["עָרֶיךָ","cities-your"],["׃",""]] },
  { num:"יד", words:[["וְעָשִׂיתִי","and-I-work"],["בְּאַף","in-anger"],["וּבְחֵמָה","and-in-rage"],["נָקָם","vengeance"],["אֶת־הַגּוֹיִם","[ACC]-the-nations"],["אֲשֶׁר","which"],["לֹא","not"],["שָׁמֵעוּ","they listened"],["׃",""]] },
];
renderVerseSet(mic_ch5Verses, 'mic-ch5-verses');

var mic_ch6Verses = [
  { num:"א", words:[["שִׁמְעוּ־נָא","hear-you-now"],["אֵת","[ACC]"],["אֲשֶׁר־יְהֹוָה","whose-the-LORD"],["אֹמֵר","say"],["קוּם","arise"],["רִיב","contention"],["אֶת־הֶהָרִים","[ACC]-the-mountains"],["וְתִשְׁמַעְנָה","so-they may hear"],["הַגְּבָעוֹת","the-hills"],["קוֹלֶךָ","voice-your"],["׃",""]] },
  { num:"ב", words:[["שִׁמְעוּ","hear"],["הָרִים","mountains"],["אֶת־רִיב","[ACC]-contention"],["יְהֹוָה","the-LORD"],["וְהָאֵתָנִים","and-the-O-enduring ones"],["מוֹסְדֵי","the foundations of"],["אָרֶץ","the-earth"],["כִּי","because"],["רִיב","contention"],["לַיהֹוָה","to-Yahweh"],["עִם־עַמּוֹ","with-his-people"],["וְעִם־יִשְׂרָאֵל","and-with-Israel"],["יִתְוַכָּח","he will argue"],["׃",""]] },
  { num:"ג", words:[["עַמִּי","my-people"],["מֶה־עָשִׂיתִי","what-I-made"],["לְךָ","for-you"],["וּמָה","and-what"],["הֶלְאֵתִיךָ","have I made weary-you"],["עֲנֵה","answer"],["בִי","against-Me"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["הֶעֱלִתִיךָ","I brought up-you"],["מֵאֶרֶץ","from-land-of"],["מִצְרַיִם","Egypt"],["וּמִבֵּית","and-of-house-of"],["עֲבָדִים","bondage"],["פְּדִיתִיךָ","I ransomed-you"],["וָאֶשְׁלַח","and-stretched-forth-I"],["לְפָנֶיךָ","before-you"],["אֶת־מֹשֶׁה","[ACC]-Moses"],["אַהֲרֹן","Aaron"],["וּמִרְיָם","and-Mary"],["׃",""]] },
  { num:"ה", words:[["עַמִּי","my-people"],["זְכׇר־נָא","I-remember-I-pray"],["מַה־יָּעַץ","what-has he planned"],["בָּלָק","Balak"],["מֶלֶךְ","the-king-of"],["מוֹאָב","Moab"],["וּמֶה־עָנָה","and-what-he has testified"],["אֹתוֹ","him"],["בִּלְעָם","Balaam"],["בֶּן־בְּעוֹר","son-of-Beor"],["מִן־הַשִּׁטִּים","from-the-shittim"],["עַד־הַגִּלְגָּל","the-until-Gilgal"],["לְמַעַן","in-order-that"],["דַּעַת","true-knowledge"],["צִדְקוֹת","the righteousness of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ו", words:[["בַּמָּה","the-how?"],["אֲקַדֵּם","will I come to meet"],["יְהֹוָה","the-LORD"],["אִכַּף","will I bend myself down?"],["לֵאלֹהֵי","to-God-of"],["מָרוֹם","the-heights/above"],["הַאֲקַדְּמֶנּוּ","¿-will I come to meet-him"],["בְעוֹלוֹת","with-burnt offerings"],["בַּעֲגָלִים","with-calves"],["בְּנֵי","the-sons-of"],["שָׁנָה","year"],["׃",""]] },
  { num:"ז", words:[["הֲיִרְצֶה","¿-will he take pleasure"],["יְהֹוָה","the-LORD"],["בְּאַלְפֵי","among-the families of"],["אֵילִים","rams"],["בְּרִבְבוֹת","in-tens of thousands of"],["נַחֲלֵי־שָׁמֶן","a-river-of-my-the-anointing"],["הַאֶתֵּן","¿-will I give"],["בְּכוֹרִי","my-firstborn"],["פִּשְׁעִי","is transgression-my"],["פְּרִי","fruit"],["בִטְנִי","womb-my"],["חַטַּאת","sin-offering"],["נַפְשִׁי","my-life"],["׃",""]] },
  { num:"ח", words:[["הִגִּיד","declared"],["לְךָ","for-you"],["אָדָם","man"],["מַה־טּוֹב","what-is good"],["וּמָה־יְהֹוָה","and-what-the-LORD"],["דּוֹרֵשׁ","requires"],["מִמְּךָ","from-you"],["כִּי","because"],["אִם־עֲשׂוֹת","[compound]-do"],["מִשְׁפָּט","judgment"],["וְאַהֲבַת","and-you-shall-love"],["חֶסֶד","mercy"],["וְהַצְנֵעַ","and-to be modest"],["לֶכֶת","departing-of"],["עִם־אֱלֹהֶיךָ","with-your-God"],["׃",""]] },
  { num:"ט", words:[["קוֹל","the-voice-of"],["יְהֹוָה","the-LORD"],["לָעִיר","to-the-city-of"],["יִקְרָא","calls"],["וְתוּשִׁיָּה","and-sound wisdom"],["יִרְאֶה","He-shall-manifest-Himself"],["שְׁמֶךָ","your-name"],["שִׁמְעוּ","hear"],["מַטֶּה","the-staff"],["וּמִי","and-whoso"],["יְעָדָהּ","he designated-her"],["׃",""]] },
  { num:"י", words:[["עוֹד","any-more"],["הַאִשׁ","¿-are there"],["בֵּית","the-house-of"],["רָשָׁע","wicked"],["אֹצְרוֹת","the treasures of"],["רֶשַׁע","wickedness"],["וְאֵיפַת","and-an ephah of"],["רָזוֹן","leanness"],["זְעוּמָה","accursed"],["׃",""]] },
  { num:"יא", words:[["הַאֶזְכֶּה","¿-will I be clear"],["בְּמֹאזְנֵי","with-balances of"],["רֶשַׁע","wickedness"],["וּבְכִיס","and-with-a bag of"],["אַבְנֵי","stones-of"],["מִרְמָה","deceit"],["׃",""]] },
  { num:"יב", words:[["אֲשֶׁר","which"],["עֲשִׁירֶיהָ","rich people-its"],["מָלְאוּ","had-come"],["חָמָס","violence"],["וְיֹשְׁבֶיהָ","and-its-inhabitants"],["דִּבְּרוּ־שָׁקֶר","have-spoken-false"],["וּלְשׁוֹנָם","and-words"],["רְמִיָּה","deceit"],["בְּפִיהֶם","in-their-mouths"],["׃",""]] },
  { num:"יג", words:[["וְגַם־אֲנִי","and-also-I"],["הֶחֱלֵיתִי","I will make sick"],["הַכּוֹתֶךָ","the-by striking-you"],["הַשְׁמֵם","I will make desolate you"],["עַל־חַטֹּאתֶךָ","upon-sins-your"],["׃",""]] },
  { num:"יד", words:[["אַתָּה","you"],["תֹאכַל","you must eat"],["וְלֹא","and-not"],["תִשְׂבָּע","you will be satisfied"],["וְיֶשְׁחֲךָ","and-emptiness-your"],["בְּקִרְבֶּךָ","in-midst-your"],["וְתַסֵּג","and-you will carry away"],["וְלֹא","and-not"],["תַפְלִיט","you will bring to safety"],["וַאֲשֶׁר","and-whom"],["תְּפַלֵּט","it calves"],["לַחֶרֶב","to the-sword"],["אֶתֵּן","shall-give"],["׃",""]] },
  { num:"טו", words:[["אַתָּה","you"],["תִזְרַע","you will sow"],["וְלֹא","and-not"],["תִקְצוֹר","you will harvest"],["אַתָּה","you"],["תִדְרֹךְ־זַיִת","you will tread-the-olive-tree"],["וְלֹא־תָסוּךְ","and-not-you will anoint yourself"],["שֶׁמֶן","oil"],["וְתִירוֹשׁ","and-new wine"],["וְלֹא","and-not"],["תִשְׁתֶּה־יָּיִן","you will drink-wine"],["׃",""]] },
  { num:"טז", words:[["וְיִשְׁתַּמֵּר","so-may be kept"],["חֻקּוֹת","the-decrees-of"],["עׇמְרִי","Omer-my"],["וְכֹל","and-the-whole"],["מַעֲשֵׂה","work-of"],["בֵית־אַחְאָב","house-of-Ahab"],["וַתֵּלְכוּ","and-you-walk"],["בְּמֹעֲצוֹתָם","in-schemes-their"],["לְמַעַן","in-order-that"],["תִּתִּי","to give-I"],["אֹתְךָ","you"],["לְשַׁמָּה","desolate"],["וְיֹשְׁבֶיהָ","and-its-inhabitants"],["לִשְׁרֵקָה","a-hissing"],["וְחֶרְפַּת","and-the-reproach-of"],["עַמִּי","my-people"],["תִּשָּׂאוּ","you will bear"],["׃",""]] },
];
renderVerseSet(mic_ch6Verses, 'mic-ch6-verses');

var mic_ch7Verses = [
  { num:"א", words:[["אַלְלַי","woe!"],["לִי","to-me"],["כִּי","because"],["הָיִיתִי","I-was"],["כְּאׇסְפֵּי־קַיִץ","like-gathering of-summer fruit"],["כְּעֹלְלֹת","like-gleanings of"],["בָּצִיר","grape harvest"],["אֵין־אֶשְׁכּוֹל","there-is-no-Eshcol"],["לֶאֱכוֹל","to-eat"],["בִּכּוּרָה","early figs"],["אִוְּתָה","it has desired"],["נַפְשִׁי","my-life"],["׃",""]] },
  { num:"ב", words:[["אָבַד","perished"],["חָסִיד","goodly"],["מִן־הָאָרֶץ","from-the-land"],["וְיָשָׁר","and-upright"],["בָּאָדָם","in-man"],["אָיִן","not"],["כֻּלָּם","all-of-them"],["לְדָמִים","for-blood"],["יֶאֱרֹבוּ","they lie in wait"],["אִישׁ","man-of"],["אֶת־אָחִיהוּ","[ACC]-brother-his"],["יָצוּדוּ","they-shall-hunt"],["חֵרֶם","destruction"],["׃",""]] },
  { num:"ג", words:[["עַל־הָרַע","upon-the-bad"],["כַּפַּיִם","the-palms-of-My-hands"],["לְהֵיטִיב","to-do good"],["הַשַּׂר","the-leader"],["שֹׁאֵל","ask"],["וְהַשֹּׁפֵט","and-the-judged"],["בַּשִּׁלּוּם","in-the-an-everlasting"],["וְהַגָּדוֹל","and-the-great"],["דֹּבֵר","speaks"],["הַוַּת","the craving of"],["נַפְשׁוֹ","his-soul"],["הוּא","it"],["וַיְעַבְּתוּהָ","and-they weave-it"],["׃",""]] },
  { num:"ד", words:[["טוֹבָם","good person-their"],["כְּחֵדֶק","is like-a thorn-bush"],["יָשָׁר","straight"],["מִמְּסוּכָה","more than-a thorn hedge"],["יוֹם","day"],["מְצַפֶּיךָ","watchmen-your"],["פְּקֻדָּתְךָ","punishment-your"],["בָאָה","entered-into"],["עַתָּה","now"],["תִהְיֶה","be"],["מְבוּכָתָם","confusion-their"],["׃",""]] },
  { num:"ה", words:[["אַל־תַּאֲמִינוּ","do-not-believe-them"],["בְרֵעַ","in-a neighbor"],["אַל־תִּבְטְחוּ","do-not-trust"],["בְּאַלּוּף","in-a close friend"],["מִשֹּׁכֶבֶת","from-she who lies of"],["חֵיקֶךָ","bosom-your"],["שְׁמֹר","watch"],["פִּתְחֵי־פִיךָ","into-the-gates-of-is mouth-your"],["׃",""]] },
  { num:"ו", words:[["כִּי־בֵן","because-Bn"],["מְנַבֵּל","is treating with contempt"],["אָב","father"],["בַּת","the-daughter-of"],["קָמָה","arose"],["בְאִמָּהּ","on-mother-her"],["כַּלָּה","O bride"],["בַּחֲמֹתָהּ","on-mother-in-law-her"],["אֹיְבֵי","the enemies of"],["אִישׁ","man-of"],["אַנְשֵׁי","the-men-of"],["בֵיתוֹ","his-house"],["׃",""]] },
  { num:"ז", words:[["וַאֲנִי","and-I"],["בַּיהֹוָה","is in-Yahweh"],["אֲצַפֶּה","I-will-watched"],["אוֹחִילָה","I am waiting"],["לֵאלֹהֵי","to-God-of"],["יִשְׁעִי","My-salvation"],["יִשְׁמָעֵנִי","will he listen to-me"],["אֱלֹהָי","my-God"],["׃",""]] },
  { num:"ח", words:[["אַל־תִּשְׂמְחִי","rejoice-not"],["אֹיַבְתִּי","O enemy-my"],["לִי","to-me"],["כִּי","because"],["נָפַלְתִּי","I have fallen"],["קָמְתִּי","I will arise"],["כִּי־אֵשֵׁב","because-I will remain"],["בַּחֹשֶׁךְ","in-the-darkness"],["יְהֹוָה","the-LORD"],["אוֹר","light"],["לִי","to-me"],["׃",""]] },
  { num:"ט", words:[["זַעַף","the rage of"],["יְהֹוָה","the-LORD"],["אֶשָּׂא","I-carry"],["כִּי","because"],["חָטָאתִי","have I sinned"],["לוֹ","him"],["עַד","until"],["אֲשֶׁר","which"],["יָרִיב","who-pleads-the-cause-of"],["רִיבִי","case-my"],["וְעָשָׂה","and-done"],["מִשְׁפָּטִי","my-judgment"],["יוֹצִיאֵנִי","he will bring out-me"],["לָאוֹר","to-light"],["אֶרְאֶה","I-shall-see"],["בְּצִדְקָתוֹ","for-righteousness-his"],["׃",""]] },
  { num:"י", words:[["וְתֵרֶא","and-she will see"],["אֹיַבְתִּי","O enemy-my"],["וּתְכַסֶּהָ","and-it will cover-her"],["בוּשָׁה","shame"],["הָאֹמְרָה","the-who-says"],["אֵלַי","to-me"],["אַיּוֹ","where is?-he"],["יְהֹוָה","the-LORD"],["אֱלֹהָיִךְ","your-God"],["עֵינַי","my-eyes"],["תִּרְאֶינָּה","they will look"],["בָּהּ","in-it(f)"],["עַתָּה","now"],["תִּהְיֶה","shall-be"],["לְמִרְמָס","trodden-down"],["כְּטִיט","like-the mud of"],["חוּצוֹת","the-streets"],["׃",""]] },
  { num:"יא", words:[["יוֹם","day"],["לִבְנוֹת","white"],["גְּדֵרָיִךְ","walls-your"],["יוֹם","day"],["הַהוּא","that"],["יִרְחַק־חֹק","it will be too far-law"],["׃",""]] },
  { num:"יב", words:[["יוֹם","day"],["הוּא","it"],["וְעָדֶיךָ","and-to-you"],["יָבוֹא","shall-come"],["לְמִנִּי","from"],["אַשּׁוּר","Assyria"],["וְעָרֵי","and-the cities of"],["מָצוֹר","siege works"],["וּלְמִנִּי","and-from"],["מָצוֹר","siege works"],["וְעַד־נָהָר","and-unto-the-river"],["וְיָם","and-the sea"],["מִיָּם","from-the-sea/west"],["וְהַר","and-the mountain of"],["הָהָר","the-mountain"],["׃",""]] },
  { num:"יג", words:[["וְהָיְתָה","and-it-be"],["הָאָרֶץ","the-earth"],["לִשְׁמָמָה","to-desolate"],["עַל־יֹשְׁבֶיהָ","upon-its-inhabitants"],["מִפְּרִי","of-fruit-of"],["מַעַלְלֵיהֶם","their-doings"],["׃",""]] },
  { num:"יד", words:[["רְעֵה","shepherd"],["עַמְּךָ","your-people"],["בְשִׁבְטֶךָ","with-rod-your"],["צֹאן","flocks"],["נַחֲלָתֶךָ","inheritance-your"],["שֹׁכְנִי","the one who dwelt"],["לְבָדָד","which-alone"],["יַעַר","Ir"],["בְּתוֹךְ","among"],["כַּרְמֶל","new corn"],["יִרְעוּ","they-feed"],["בָשָׁן","Bashan"],["וְגִלְעָד","and-Gilead"],["כִּימֵי","as-days-of"],["עוֹלָם","eternal"],["׃",""]] },
  { num:"טו", words:[["כִּימֵי","as-days-of"],["צֵאתְךָ","coming out-you"],["מֵאֶרֶץ","from-land-of"],["מִצְרָיִם","Egypt"],["אַרְאֶנּוּ","I will let look-him"],["נִפְלָאוֹת","wonders"],["׃",""]] },
  { num:"טז", words:[["יִרְאוּ","shall-see"],["גוֹיִם","nations"],["וְיֵבֹשׁוּ","and-they may be ashamed"],["מִכֹּל","of-all"],["גְּבוּרָתָם","strength-their"],["יָשִׂימוּ","set-at"],["יָד","hands"],["עַל־פֶּה","upon-Ph"],["אׇזְנֵיהֶם","the ears of-them"],["תֶּחֱרַשְׁנָה","they will be deaf"],["׃",""]] },
  { num:"יז", words:[["יְלַחֲכוּ","shall-lick"],["עָפָר","the-earth"],["כַּנָּחָשׁ","the-is like-snake"],["כְּזֹחֲלֵי","like-things which crawl of"],["אֶרֶץ","the-land-of"],["יִרְגְּזוּ","they trembled"],["מִמִּסְגְּרֹתֵיהֶם","from-strongholds-their"],["אֶל־יְהֹוָה","to-the-Lord"],["אֱלֹהֵינוּ","our-God"],["יִפְחָדוּ","they will be in dread"],["וְיִרְאוּ","and-contemplate"],["מִמֶּךָּ","from-you"],["׃",""]] },
  { num:"יח", words:[["מִי־אֵל","who-God"],["כָּמוֹךָ","like-you"],["נֹשֵׂא","bearing"],["עָוֺן","iniquity"],["וְעֹבֵר","and-who passes"],["עַל־פֶּשַׁע","upon-the-transgression-of"],["לִשְׁאֵרִית","for-remnant-of"],["נַחֲלָתוֹ","inheritance-of-his"],["לֹא־הֶחֱזִיק","not-he-withheld"],["לָעַד","forever"],["אַפּוֹ","His-wrath"],["כִּי־חָפֵץ","because-desire/precious"],["חֶסֶד","mercy"],["הוּא","it"],["׃",""]] },
  { num:"יט", words:[["יָשׁוּב","repent"],["יְרַחֲמֵנוּ","he will have compassion on-us"],["יִכְבֹּשׁ","he will subdue"],["עֲוֺנֹתֵינוּ","the-iniquities-of-our"],["וְתַשְׁלִיךְ","so-you may cast"],["בִּמְצֻלוֹת","in-the depths of"],["יָם","the-sea"],["כׇּל־חַטֹּאותָם","all-sins-their"],["׃",""]] },
  { num:"כ", words:[["תִּתֵּן","you-shall-give"],["אֱמֶת","truth"],["לְיַעֲקֹב","to-Jacob"],["חֶסֶד","mercy"],["לְאַבְרָהָם","unto-Abraham"],["אֲשֶׁר־נִשְׁבַּעְתָּ","whose-you swore"],["לַאֲבֹתֵינוּ","to-ancestors-our"],["מִימֵי","from-the-days-of"],["קֶדֶם","old"],["׃",""]] },
];
renderVerseSet(mic_ch7Verses, 'mic-ch7-verses');

})();
