// ot_verses/nah.js — Nahum verse data
(function() {
var nah_ch1Verses = [
  { num:"א", words:[["מַשָּׂא","the-burden-of"],["נִינְוֵה","Nineveh"],["סֵפֶר","a-book"],["חֲזוֹן","a-vision"],["נַחוּם","Nahum"],["הָאֶלְקֹשִׁי","the-Elkoshite"],["׃",""]] },
  { num:"ב", words:[["אֵל","God"],["קַנּוֹא","jealous"],["וְנֹקֵם","and-avenging yourself"],["יְהֹוָה","the-LORD"],["נֹקֵם","is avenging"],["יְהֹוָה","the-LORD"],["וּבַעַל","and-in-upon"],["חֵמָה","wrath"],["נֹקֵם","is avenging"],["יְהֹוָה","the-LORD"],["לְצָרָיו","to-foes-his"],["וְנוֹטֵר","and-is maintaining"],["הוּא","it-is"],["לְאֹיְבָיו","to-enemies-his"],["׃",""]] },
  { num:"ג", words:[["יְהֹוָה","the-LORD"],["אֶרֶךְ","long of"],["אַפַּיִם","with-face"],["(וגדול)","and-becoming great"],["[וּגְדׇל־]כֹּחַ","and-great of-strength"],["וְנַקֵּה","and-certainly"],["לֹא","not"],["יְנַקֶּה","hold-him-guiltless"],["יְהֹוָה","the-LORD"],["בְּסוּפָה","in-the-storm"],["וּבִשְׂעָרָה","and-in-storm"],["דַּרְכּוֹ","his-way"],["וְעָנָן","and-cloud"],["אֲבַק","the dust of"],["רַגְלָיו","His-feet"],["׃",""]] },
  { num:"ד", words:[["גּוֹעֵר","he is rebuking"],["בַּיָּם","in-the-sea"],["וַיַּבְּשֵׁהוּ","and-he made dry-it"],["וְכׇל־הַנְּהָרוֹת","and-all-the-rivers"],["הֶחֱרִיב","it laid waste"],["אֻמְלַל","am frail"],["בָּשָׁן","Bashan"],["וְכַרְמֶל","and-new corn"],["וּפֶרַח","and-the blossom of"],["לְבָנוֹן","Lebanon"],["אֻמְלָל","miserable"],["׃",""]] },
  { num:"ה", words:[["הָרִים","mountains"],["רָעֲשׁוּ","they shake"],["מִמֶּנּוּ","from-him"],["וְהַגְּבָעוֹת","and-the-hills"],["הִתְמֹגָגוּ","they melt"],["וַתִּשָּׂא","Otsh"],["הָאָרֶץ","the-earth"],["מִפָּנָיו","from-before-him"],["וְתֵבֵל","and-the world"],["וְכׇל־יוֹשְׁבֵי","and-all-the-inhabitants-of"],["בָהּ","in-her"],["׃",""]] },
  { num:"ו", words:[["לִפְנֵי","before"],["זַעְמוֹ","His-indignation"],["מִי","who"],["יַעֲמוֹד","it will arise"],["וּמִי","and-whoso"],["יָקוּם","he-shall-rise"],["בַּחֲרוֹן","in-the-fierce"],["אַפּוֹ","His-wrath"],["חֲמָתוֹ","His-fury"],["נִתְּכָה","it has been poured out"],["כָאֵשׁ","as-the-fire"],["וְהַצֻּרִים","and-the-rocks"],["נִתְּצוּ","they had been pulled down"],["מִמֶּנּוּ","from-him"],["׃",""]] },
  { num:"ז", words:[["טוֹב","good"],["יְהֹוָה","the-LORD"],["לְמָעוֹז","Lmoz"],["בְּיוֹם","in-day-of"],["צָרָה","affliction"],["וְיֹדֵעַ","and-the one who knows"],["חֹסֵי","those who take refuge"],["בוֹ","in-Him"],["׃",""]] },
  { num:"ח", words:[["וּבְשֶׁטֶף","and-with-a flood"],["עֹבֵר","that-passes-away"],["כָּלָה","all-of-it(f)"],["יַעֲשֶׂה","he-shall-do"],["מְקוֹמָהּ","place-its"],["וְאֹיְבָיו","and-enemies-his"],["יְרַדֶּף־חֹשֶׁךְ","he will pursue-darkness"],["׃",""]] },
  { num:"ט", words:[["מַה־תְּחַשְּׁבוּן","what-you will plot-!"],["אֶל־יְהֹוָה","to-the-Lord"],["כָּלָה","all-of-it(f)"],["הוּא","it-is"],["עֹשֶׂה","do"],["לֹא־תָקוּם","not-stand"],["פַּעֲמַיִם","two times"],["צָרָה","affliction"],["׃",""]] },
  { num:"י", words:[["כִּי","because"],["עַד־סִירִים","until-thorns"],["סְבֻכִים","interwoven"],["וּכְסׇבְאָם","and-like-drink-their"],["סְבוּאִים","drunkards"],["אֻכְּלוּ","they have been consumed"],["כְּקַשׁ","as-stubble"],["יָבֵשׁ","it-has-withered-away"],["מָלֵא","full-of"],["׃",""]] },
  { num:"יא", words:[["מִמֵּךְ","from-you"],["יָצָא","he-went-forth"],["חֹשֵׁב","curious"],["עַל־יְהֹוָה","upon-the-LORD"],["רָעָה","evil"],["יֹעֵץ","a counselor of"],["בְּלִיָּעַל","worthlessness"],["׃",""]] },
  { num:"יב", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["אִם־שְׁלֵמִים","[compound]-perfect"],["וְכֵן","and-so"],["רַבִּים","many"],["וְכֵן","and-so"],["וְעָבָר","and-it will pass over"],["וְעִנִּתִךְ","and-I have afflicted-you"],["לֹא","not"],["אֲעַנֵּךְ","I will afflict-you"],["עוֹד","any-more"],["׃",""]] },
  { num:"יג", words:[["וְעַתָּה","and-now"],["אֶשְׁבֹּר","I will break"],["מֹטֵהוּ","yoke-bar-his"],["מֵעָלָיִךְ","from-with-you"],["וּמוֹסְרֹתַיִךְ","and-fetters-your"],["אֲנַתֵּק","I-burst"],["׃",""]] },
  { num:"יד", words:[["וְצִוָּה","and-He-has-commanded"],["עָלֶיךָ","upon-you(f)"],["יְהֹוָה","the-LORD"],["לֹא־יִזָּרַע","not-he-will-seed"],["מִשִּׁמְךָ","from-name-your"],["עוֹד","any-more"],["מִבֵּית","from-house-of"],["אֱלֹהֶיךָ","your-God"],["אַכְרִית","I-shall-cut-off"],["פֶּסֶל","an image of"],["וּמַסֵּכָה","and-a molten image"],["אָשִׂים","shall-I-put"],["קִבְרֶךָ","grave-your"],["כִּי","because"],["קַלּוֹתָ","you are insignificant"],["׃",""]] },
];
renderVerseSet(nah_ch1Verses, 'nah-ch1-verses');

var nah_ch2Verses = [
  { num:"א", words:[["הִנֵּה","behold"],["עַל־הֶהָרִים","upon-the-mountains"],["רַגְלֵי","feet-of"],["מְבַשֵּׂר","that-brings"],["מַשְׁמִיעַ","good-tidings"],["שָׁלוֹם","peace"],["חׇגִּי","celebrate a festival"],["יְהוּדָה","Judah"],["חַגַּיִךְ","festivals-your"],["שַׁלְּמִי","pay"],["נְדָרָיִךְ","vows-your"],["כִּי","because"],["לֹא","not"],["יוֹסִיף","He-shall-set"],["עוֹד","any-more"],["(לעבור)","to-pass over"],["[לַעֲבׇר־]בָּךְ","to-pass-in-you"],["בְּלִיַּעַל","worthlessness"],["כֻּלֹּה","all of-it"],["נִכְרָת","let us make"],["׃",""]] },
  { num:"ב", words:[["עָלָה","ascended"],["מֵפִיץ","a war-club"],["עַל־פָּנַיִךְ","upon-face-your"],["נָצוֹר","guard"],["מְצוּרָה","fortification"],["צַפֵּה־דֶרֶךְ","watch-any-other-way"],["חַזֵּק","encourage"],["מׇתְנַיִם","the hips"],["אַמֵּץ","make strong"],["כֹּחַ","power"],["מְאֹד","exceedingly"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["שָׁב","returned/repented"],["יְהֹוָה","the-LORD"],["אֶת־גְּאוֹן","[ACC]-the-pride-of"],["יַעֲקֹב","Jacob"],["כִּגְאוֹן","like-the majesty of"],["יִשְׂרָאֵל","Israel"],["כִּי","because"],["בְקָקוּם","they have laid waste to-them"],["בֹּקְקִים","those who lay waste"],["וּזְמֹרֵיהֶם","and-branches-their"],["שִׁחֵתוּ","they have dealt corruptly"],["׃",""]] },
  { num:"ד", words:[["מָגֵן","a-protector"],["גִּבֹּרֵיהוּ","warriors-his"],["מְאׇדָּם","from-man"],["אַנְשֵׁי־חַיִל","the-men-of-might"],["מְתֻלָּעִים","are clothed in scarlet"],["בְּאֵשׁ־פְּלָדֹת","in-fire-???"],["הָרֶכֶב","the-chariots"],["בְּיוֹם","in-day-of"],["הֲכִינוֹ","prepares-he"],["וְהַבְּרֹשִׁים","and-the-cypresses"],["הׇרְעָלוּ","they have been made to quiver"],["׃",""]] },
  { num:"ה", words:[["בַּחוּצוֹת","will be in the-streets"],["יִתְהוֹלְלוּ","they drive madly"],["הָרֶכֶב","the-chariots"],["יִשְׁתַּקְשְׁקוּן","they rush around-!"],["בָּרְחֹבוֹת","in the-open places"],["מַרְאֵיהֶן","was appearance-their"],["כַּלַּפִּידִים","as-the-torches"],["כַּבְּרָקִים","like-the-lightning flashes"],["יְרוֹצֵצוּ","they run around"],["׃",""]] },
  { num:"ו", words:[["יִזְכֹּר","shall-remember"],["אַדִּירָיו","nobles-his"],["יִכָּשְׁלוּ","they-might-stumble"],["[בַּהֲלִיכָתָם]","on-journey-their"],["יְמַהֲרוּ","make-haste-shall"],["חוֹמָתָהּ","wall-its"],["וְהֻכַן","and-it is prepared"],["הַסֹּכֵךְ","the-one which covers"],["׃",""]] },
  { num:"ז", words:[["שַׁעֲרֵי","the-gates-of"],["הַנְּהָרוֹת","the-rivers"],["נִפְתָּחוּ","they were opened"],["וְהַהֵיכָל","and-the-temple"],["נָמוֹג","you-are-dissolved"],["׃",""]] },
  { num:"ח", words:[["וְהֻצַּב","and-it has been fixed"],["גֻּלְּתָה","it was uncovered"],["הֹעֲלָתָה","it was taken away"],["וְאַמְהֹתֶיהָ","and-maidservants-its"],["מְנַהֲגוֹת","are moaning"],["כְּקוֹל","as-it-were-with-a-voice-of"],["יוֹנִים","are doves"],["מְתֹפְפֹת","they are beating"],["עַל־לִבְבֵהֶן","upon-hearts-their"],["׃",""]] },
  { num:"ט", words:[["וְנִינְוֵה","and-Nineveh"],["כִבְרֵכַת־מַיִם","was like-a pool of-water"],["מִימֵי","from-the-days-of"],["הִיא","it-is"],["וְהֵמָּה","and-they-are"],["נָסִים","fled"],["עִמְדוּ","stand"],["עֲמֹדוּ","stop"],["וְאֵין","and-has-no"],["מַפְנֶה","is one who turns back"],["׃",""]] },
  { num:"י", words:[["בֹּזּוּ","plunder"],["כֶסֶף","silver/money"],["בֹּזּוּ","plunder"],["זָהָב","gold"],["וְאֵין","and-has-no"],["קֵצֶה","end"],["לַתְּכוּנָה","to the-supply"],["כָּבֹד","abundance"],["מִכֹּל","of-all"],["כְּלִי","the-ball"],["חֶמְדָּה","of-delight"],["׃",""]] },
  { num:"יא", words:[["בּוּקָה","emptiness"],["וּמְבוּקָה","and-emptiness"],["וּמְבֻלָּקָה","and-devastation"],["וְלֵב","and-heart"],["נָמֵס","it has melted"],["וּפִק","and-are tottering"],["בִּרְכַּיִם","knees"],["וְחַלְחָלָה","and-anguish"],["בְּכׇל־מׇתְנַיִם","on-all-loins"],["וּפְנֵי","and-the-faces-of"],["כֻלָּם","all-of-them"],["קִבְּצוּ","gathered-his"],["פָארוּר","a glow"],["׃",""]] },
  { num:"יב", words:[["אַיֵּה","where-is"],["מְעוֹן","Meon"],["אֲרָיוֹת","lions"],["וּמִרְעֶה","and-pasture"],["הוּא","it-is"],["לַכְּפִרִים","for-the-young lions"],["אֲשֶׁר","which"],["הָלַךְ","went"],["אַרְיֵה","a lion"],["לָבִיא","to-bring"],["שָׁם","there"],["גּוּר","sojourn"],["אַרְיֵה","a lion"],["וְאֵין","and-has-no"],["מַחֲרִיד","will be one who terrifies"],["׃",""]] },
  { num:"יג", words:[["אַרְיֵה","a lion"],["טֹרֵף","O one who tears"],["בְּדֵי","in-the sufficiency of"],["גֹרוֹתָיו","cubs-its"],["וּמְחַנֵּק","and-was strangling"],["לְלִבְאֹתָיו","for-lionesses-its"],["וַיְמַלֵּא־טֶרֶף","and-satisfied-the-prey"],["חֹרָיו","hole-its"],["וּמְעֹנֹתָיו","and-dens-its"],["טְרֵפָה","a torn animal"],["׃",""]] },
  { num:"יד", words:[["הִנְנִי","behold-I"],["אֵלַיִךְ","into-you"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["וְהִבְעַרְתִּי","and-I will burn"],["בֶעָשָׁן","in-smoke"],["רִכְבָּהּ","chariotry-its"],["וּכְפִירַיִךְ","and-young lions-your"],["תֹּאכַל","you will eat"],["חָרֶב","a-sword"],["וְהִכְרַתִּי","and-cut-off"],["מֵאֶרֶץ","from-land-of"],["טַרְפֵּךְ","prey-your"],["וְלֹא־יִשָּׁמַע","and-not-it will be heard"],["עוֹד","any-more"],["קוֹל","the-voice-of"],["מַלְאָכֵכֵה","messengers-your"],["׃",""]] },
];
renderVerseSet(nah_ch2Verses, 'nah-ch2-verses');

var nah_ch3Verses = [
  { num:"א", words:[["הוֹי","O"],["עִיר","city-of"],["דָּמִים","blood"],["כֻּלָּהּ","all-of-it(f)"],["כַּחַשׁ","lying"],["פֶּרֶק","plunder"],["מְלֵאָה","full"],["לֹא","not"],["יָמִישׁ","it departed"],["טָרֶף","prey"],["׃",""]] },
  { num:"ב", words:[["קוֹל","the-voice-of"],["שׁוֹט","a-scourge"],["וְקוֹל","the-voice-of-the-people"],["רַעַשׁ","an earthquake"],["אוֹפָן","a wheel"],["וְסוּס","and-horses"],["דֹּהֵר","galloping"],["וּמֶרְכָּבָה","and-a chariot"],["מְרַקֵּדָה","jolting"],["׃",""]] },
  { num:"ג", words:[["פָּרָשׁ","a horseman"],["מַעֲלֶה","brings-up"],["וְלַהַב","and-a flame"],["חֶרֶב","the-sword-of"],["וּבְרַק","and-the flash of"],["חֲנִית","daggers"],["וְרֹב","and-most-of"],["חָלָל","one slain"],["וְכֹבֶד","and-is heaviness of"],["פָּגֶר","corpses"],["וְאֵין","and-has-no"],["קֵצֶה","end"],["לַגְּוִיָּה","to the-bodies"],["(יכשלו)","they will stumble"],["[וְכָשְׁלוּ]","and-shall-stumble"],["בִּגְוִיָּתָם","over-bodies-their"],["׃",""]] },
  { num:"ד", words:[["מֵרֹב","from-multitude-of"],["זְנוּנֵי","the prostitutions of"],["זוֹנָה","harlot"],["טוֹבַת","the-welfare-of"],["חֵן","favor"],["בַּעֲלַת","Baalath"],["כְּשָׁפִים","sorceries"],["הַמֹּכֶרֶת","the-who-sells"],["גּוֹיִם","nations/gentiles"],["בִּזְנוּנֶיהָ","by-prostitution-her"],["וּמִשְׁפָּחוֹת","and-clans"],["בִּכְשָׁפֶיהָ","by-sorceries-her"],["׃",""]] },
  { num:"ה", words:[["הִנְנִי","behold-I"],["אֵלַיִךְ","into-you"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["וְגִלֵּיתִי","and-I will uncover"],["שׁוּלַיִךְ","skirts-your"],["עַל־פָּנָיִךְ","upon-face-your"],["וְהַרְאֵיתִי","and-I will show"],["גוֹיִם","nations"],["מַעְרֵךְ","nakedness-your"],["וּמַמְלָכוֹת","and-kingdoms"],["קְלוֹנֵךְ","shame-your"],["׃",""]] },
  { num:"ו", words:[["וְהִשְׁלַכְתִּי","and-I will cast out"],["עָלַיִךְ","upon-you(f)"],["שִׁקֻּצִים","detestable things"],["וְנִבַּלְתִּיךְ","and-I will treat with contempt-you"],["וְשַׂמְתִּיךְ","and-I will make-you"],["כְּרֹאִי","like-a spectacle"],["׃",""]] },
  { num:"ז", words:[["וְהָיָה","and-be"],["כׇל־רֹאַיִךְ","all-those who see-you"],["יִדּוֹד","he will flee"],["מִמֵּךְ","from-you"],["וְאָמַר","and-said"],["שׇׁדְּדָה","destroyer"],["נִינְוֵה","Nineveh"],["מִי","who"],["יָנוּד","it sways"],["לָהּ","it"],["מֵאַיִן","whence"],["אֲבַקֵּשׁ","I-require"],["מְנַחֲמִים","comforters"],["לָךְ","[compound]"],["׃",""]] },
  { num:"ח", words:[["הֲתֵיטְבִי","¿-have you been made good"],["מִנֹּא","from-Thebes"],["אָמוֹן","Amon"],["הַיֹּשְׁבָה","that-the-was dwelling"],["בַּיְאֹרִים","among the-canals"],["מַיִם","water"],["סָבִיב","round-about"],["לָהּ","it"],["אֲשֶׁר־חֵיל","whose-the army of"],["יָם","the-sea"],["מִיָּם","from-the-sea/west"],["חוֹמָתָהּ","wall-its"],["׃",""]] },
  { num:"ט", words:[["כּוּשׁ","Cush"],["עׇצְמָה","powerfulness"],["וּמִצְרַיִם","and-Mizraim"],["וְאֵין","and-has-no"],["קֵצֶה","end"],["פּוּט","Put"],["וְלוּבִים","and-the Libyans"],["הָיוּ","were"],["בְּעֶזְרָתֵךְ","help-your"],["׃",""]] },
  { num:"י", words:[["גַּם־הִיא","also-it-is"],["לַגֹּלָה","to-the-exile"],["הָלְכָה","the-you-have"],["בַשֶּׁבִי","into-the-bondage"],["גַּם","also"],["עֹלָלֶיהָ","children-her"],["יְרֻטְּשׁוּ","shall-be-dashed-to-pieces"],["בְּרֹאשׁ","in-the-gall-of"],["כׇּל־חוּצוֹת","all-the-streets"],["וְעַל־נִכְבַּדֶּיהָ","and-upon-honored people-its"],["יַדּוּ","they have cast"],["גוֹרָל","a lot"],["וְכׇל־גְּדוֹלֶיהָ","and-all-great people-its"],["רֻתְּקוּ","they were bound"],["בַזִּקִּים","with-the-fetters"],["׃",""]] },
  { num:"יא", words:[["גַּם־אַתְּ","also-ACC"],["תִּשְׁכְּרִי","you will become drunk"],["תְּהִי","let it be"],["נַעֲלָמָה","hidden"],["גַּם־אַתְּ","also-ACC"],["תְּבַקְשִׁי","you will seek"],["מָעוֹז","stronghold"],["מֵאוֹיֵב","from-an enemy"],["׃",""]] },
  { num:"יב", words:[["כׇּל־מִבְצָרַיִךְ","all-fortifications-your"],["תְּאֵנִים","figs"],["עִם־בִּכּוּרִים","with-the-firstfruits"],["אִם־יִנּוֹעוּ","[compound]-they will be shaken"],["וְנָפְלוּ","and-fall-shall-they"],["עַל־פִּי","according-to"],["אוֹכֵל","he-eats"],["׃",""]] },
  { num:"יג", words:[["הִנֵּה","behold"],["עַמֵּךְ","people-your"],["נָשִׁים","women"],["בְּקִרְבֵּךְ","in-your-midst"],["לְאֹיְבַיִךְ","to-enemies-your"],["פָּתוֹחַ","certainly"],["נִפְתְּחוּ","opened-his"],["שַׁעֲרֵי","the-gates-of"],["אַרְצֵךְ","your-land"],["אָכְלָה","it consumed"],["אֵשׁ","fire"],["בְּרִיחָיִךְ","bars-your"],["׃",""]] },
  { num:"יד", words:[["מֵי","the-waters-of"],["מָצוֹר","siege works"],["שַׁאֲבִי־לָךְ","draw-[compound]"],["חַזְּקִי","strengthen"],["מִבְצָרָיִךְ","strongholds-your"],["בֹּאִי","came-I"],["בַטִּיט","in the-clay"],["וְרִמְסִי","and-trample"],["בַחֹמֶר","on the-mortar"],["הַחֲזִיקִי","the-take hold of"],["מַלְבֵּן","a brick mold"],["׃",""]] },
  { num:"טו", words:[["שָׁם","there"],["תֹּאכְלֵךְ","it will consume-you"],["אֵשׁ","fire"],["תַּכְרִיתֵךְ","it will cut off-you"],["חֶרֶב","the-sword-of"],["תֹּאכְלֵךְ","it will consume-you"],["כַּיָּלֶק","like the-locust"],["הִתְכַּבֵּד","make yourself numerous"],["כַּיֶּלֶק","like-the-locust"],["הִתְכַּבְּדִי","make yourself numerous"],["כָּאַרְבֶּה","like-locusts"],["׃",""]] },
  { num:"טז", words:[["הִרְבֵּית","you have multiplied"],["רֹכְלַיִךְ","were traders-your"],["מִכּוֹכְבֵי","than-stars-of"],["הַשָּׁמָיִם","the-heavens"],["יֶלֶק","a locust"],["פָּשַׁט","it attacks"],["וַיָּעֹף","and-he flew"],["׃",""]] },
  { num:"יז", words:[["מִנְּזָרַיִךְ","courtiers-your"],["כָּאַרְבֶּה","like-locusts"],["וְטַפְסְרַיִךְ","and-officials-your"],["כְּגוֹב","are like-a locust of"],["גֹּבָי","locusts"],["הַחוֹנִים","the-which-encamp"],["בַּגְּדֵרוֹת","among the-walls"],["בְּיוֹם","in-day-of"],["קָרָה","happened"],["שֶׁמֶשׁ","the-sun-of"],["זָרְחָה","it has risen"],["וְנוֹדַד","and-it flees"],["וְלֹא־נוֹדַע","and-not-it-became-known"],["מְקוֹמוֹ","its-own-place"],["אַיָּם","where are?-they"],["׃",""]] },
  { num:"יח", words:[["נָמוּ","they slumbered"],["רֹעֶיךָ","herdsmen-your"],["מֶלֶךְ","the-king-of"],["אַשּׁוּר","Assyria"],["יִשְׁכְּנוּ","they-may-dwell"],["אַדִּירֶיךָ","nobles-your"],["נָפֹשׁוּ","they are scattered"],["עַמְּךָ","your-people"],["עַל־הֶהָרִים","upon-the-mountains"],["וְאֵין","and-has-no"],["מְקַבֵּץ","gathers"],["׃",""]] },
  { num:"יט", words:[["אֵין־כֵּהָה","there-is-no-it has become dull"],["לְשִׁבְרֶךָ","for-fracture-your"],["נַחְלָה","the wadi of-towards"],["מַכָּתֶךָ","wound-your"],["כֹּל","all"],["שֹׁמְעֵי","who listen to"],["שִׁמְעֲךָ","report-your"],["תָּקְעוּ","they gave a blast"],["כַף","the sole of"],["עָלֶיךָ","upon-you(f)"],["כִּי","because"],["עַל־מִי","to-whom"],["לֹא־עָבְרָה","not-had-passed-away"],["רָעָתְךָ","evil-your"],["תָּמִיד","continually"],["׃",""]] },
];
renderVerseSet(nah_ch3Verses, 'nah-ch3-verses');

})();
