// ot_verses/oba.js — Obadiah verse data
(function() {
var oba_ch1Verses = [
  { num:"א", words:[["חֲזוֹן","a-vision"],["עֹבַדְיָה","Obadiah"],["כֹּה־אָמַר","thus-says"],["אֲדֹנָי","Lord"],["יֱהֹוִה","GOD"],["לֶאֱדוֹם","of-Edom"],["שְׁמוּעָה","a report"],["שָׁמַעְנוּ","did-we-heed"],["מֵאֵת","from"],["יְהֹוָה","the-LORD"],["וְצִיר","and-an envoy of"],["בַּגּוֹיִם","by-the-nations"],["שֻׁלָּח","he has been sent"],["קוּמוּ","arise"],["וְנָקוּמָה","so-let us arise"],["עָלֶיהָ","upon-it"],["לַמִּלְחָמָה","to-the-war"],["׃",""]] },
  { num:"ב", words:[["הִנֵּה","behold"],["קָטֹן","little-are"],["נְתַתִּיךָ","I-give-you"],["בַּגּוֹיִם","by-the-nations"],["בָּזוּי","despised"],["אַתָּה","you"],["מְאֹד","exceedingly"],["׃",""]] },
  { num:"ג", words:[["זְדוֹן","the-pride-of"],["לִבְּךָ","your-heart"],["הִשִּׁיאֶךָ","it has deceived-you"],["שֹׁכְנִי","the one who dwelt"],["בְחַגְוֵי־סֶלַע","in-clefts of-the rock of"],["מְרוֹם","the heights of"],["שִׁבְתּוֹ","that-his-daughter"],["אֹמֵר","say"],["בְּלִבּוֹ","in-his-heart"],["מִי","who"],["יוֹרִדֵנִי","will he bring down-me"],["אָרֶץ","the-earth"],["׃",""]] },
  { num:"ד", words:[["אִם־תַּגְבִּיהַּ","if-you will make high"],["כַּנֶּשֶׁר","like-the-eagle"],["וְאִם־בֵּין","and-if-among"],["כּוֹכָבִים","stars"],["שִׂים","put"],["קִנֶּךָ","your-nest"],["מִשָּׁם","from-there"],["אוֹרִידְךָ","I will bring down-you"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"ה", words:[["אִם־גַּנָּבִים","if-a-thief"],["בָּאוּ־לְךָ","came-for-you"],["אִם־שׁוֹדְדֵי","if-robbers-of"],["לַיְלָה","night"],["אֵיךְ","how"],["נִדְמֵיתָה","you will be destroyed"],["הֲלוֹא","art-not"],["יִגְנְבוּ","they-shall-steal"],["דַּיָּם","sufficiently"],["אִם־בֹּצְרִים","if-grape gatherers"],["בָּאוּ","came"],["לָךְ","to-you"],["הֲלוֹא","art-not"],["יַשְׁאִירוּ","they-shall-leave"],["עֹלֵלוֹת","gleanings"],["׃",""]] },
  { num:"ו", words:[["אֵיךְ","how"],["נֶחְפְּשׂוּ","they will be plundered"],["עֵשָׂו","Esau"],["נִבְעוּ","they will be searched out"],["מַצְפֻּנָיו","its-hidden treasures"],["׃",""]] },
  { num:"ז", words:[["עַד־הַגְּבוּל","until-the-border-of"],["שִׁלְּחוּךָ","they will send away-you"],["כֹּל","all"],["אַנְשֵׁי","the-men-of"],["בְרִיתֶךָ","your-covenant"],["הִשִּׁיאוּךָ","they will deceive-you"],["יָכְלוּ","could-they"],["לְךָ","for-you"],["אַנְשֵׁי","the-men-of"],["שְׁלֹמֶךָ","your-peace"],["לַחְמְךָ","your-food"],["יָשִׂימוּ","set-at"],["מָזוֹר","the wound"],["תַּחְתֶּיךָ","beneath-you"],["אֵין","there-is-no"],["תְּבוּנָה","is understanding"],["בּוֹ","in it"],["׃",""]] },
  { num:"ח", words:[["הֲלוֹא","art-not"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["נְאֻם־יְהֹוָה","says-the-LORD"],["וְהַאֲבַדְתִּי","and-the-perished"],["חֲכָמִים","wise"],["מֵאֱדוֹם","from-Edom"],["וּתְבוּנָה","and-understanding"],["מֵהַר","from-the mountain of"],["עֵשָׂו","Esau"],["׃",""]] },
  { num:"ט", words:[["וְחַתּוּ","and-they will be dismayed"],["גִבּוֹרֶיךָ","your-warriors"],["תֵּימָן","Teman"],["לְמַעַן","in-order-that"],["יִכָּרֶת־אִישׁ","he may be cut off-man-of"],["מֵהַר","from-the mountain of"],["עֵשָׂו","Esau"],["מִקָּטֶל","from-slaughter"],["׃",""]] },
  { num:"י", words:[["מֵחֲמַס","from-the violence of"],["אָחִיךָ","your-brother"],["יַעֲקֹב","Jacob"],["תְּכַסְּךָ","it will cover-you"],["בוּשָׁה","shame"],["וְנִכְרַתָּ","and-you will be cut off"],["לְעוֹלָם","forever"],["׃",""]] },
  { num:"יא", words:[["בְּיוֹם","in-the-day-of"],["עֲמׇדְךָ","they made a stand-your"],["מִנֶּגֶד","from-before"],["בְּיוֹם","in-the-day-of"],["שְׁבוֹת","took captive"],["זָרִים","strangers"],["חֵילוֹ","his-army"],["וְנׇכְרִים","and-misfortune"],["בָּאוּ","came"],["שְׁעָרָו","shudder"],["וְעַל־יְרוּשָׁלַ͏ִם","and-on-Jerusalem"],["יַדּוּ","they have cast"],["גוֹרָל","a lot"],["גַּם־אַתָּה","are-you-also"],["כְּאַחַד","as-one"],["מֵהֶם","of-them"],["׃",""]] },
  { num:"יב", words:[["וְאַל־תֵּרֶא","and-do-not-you see"],["בְיוֹם־אָחִיךָ","on-the day of-your-brother"],["בְּיוֹם","in-the-day-of"],["נׇכְרוֹ","his-recognized"],["וְאַל־תִּשְׂמַח","and-do-not-may-rejoice"],["לִבְנֵי־יְהוּדָה","unto-the-sons-of-Judah"],["בְּיוֹם","in-the-day-of"],["אׇבְדָם","their-perished"],["וְאַל־תַּגְדֵּל","and-do-not-you make big"],["פִּיךָ","your mouth"],["בְּיוֹם","in-the-day-of"],["צָרָה","affliction"],["׃",""]] },
  { num:"יג", words:[["אַל־תָּבוֹא","do-not-come-shall"],["בְשַׁעַר־עַמִּי","in-the gate of-my-people"],["בְּיוֹם","in-the-day-of"],["אֵידָם","their-disaster"],["אַל־תֵּרֶא","do-not-you see"],["גַם־אַתָּה","also-you"],["בְּרָעָתוֹ","by-his-wickedness"],["בְּיוֹם","in-the-day-of"],["אֵידוֹ","his-disaster"],["וְאַל־תִּשְׁלַחְנָה","and-do-not-they stretched out"],["בְחֵילוֹ","on-his-wealth"],["בְּיוֹם","in-the-day-of"],["אֵידוֹ","his-disaster"],["׃",""]] },
  { num:"יד", words:[["וְאַל־תַּעֲמֹד","and-do-not-shall-stand"],["עַל־הַפֶּרֶק","upon-the-parting of ways"],["לְהַכְרִית","to-cut-off"],["אֶת־פְּלִיטָיו","his-fugitives"],["וְאַל־תַּסְגֵּר","and-do-not-you deliver up"],["שְׂרִידָיו","his-survivors"],["בְּיוֹם","in-the-day-of"],["צָרָה","affliction"],["׃",""]] },
  { num:"טו", words:[["כִּי־קָרוֹב","because-soon"],["יוֹם־יְהֹוָה","the-day-of-the-LORD"],["עַל־כׇּל־הַגּוֹיִם","upon-all-the-nations"],["כַּאֲשֶׁר","as"],["עָשִׂיתָ","you-did"],["יֵעָשֶׂה","shall-be-done"],["לָּךְ","to-you"],["גְּמֻלְךָ","your-recompense"],["יָשׁוּב","he shall return"],["בְּרֹאשֶׁךָ","on-your-head"],["׃",""]] },
  { num:"טז", words:[["כִּי","because"],["כַּאֲשֶׁר","as"],["שְׁתִיתֶם","you drank"],["עַל־הַר","against-mount"],["קׇדְשִׁי","my holiness"],["יִשְׁתּוּ","they-drink"],["כׇל־הַגּוֹיִם","all-the-nations"],["תָּמִיד","continually"],["וְשָׁתוּ","and-they-have-drunk"],["וְלָעוּ","and-they will swallow"],["וְהָיוּ","then-they-shall-be"],["כְּלוֹא","like-not"],["הָיוּ","were"],["׃",""]] },
  { num:"יז", words:[["וּבְהַר","and-in-the hill country of"],["צִיּוֹן","Zion"],["תִּהְיֶה","shall-be"],["פְלֵיטָה","an escape"],["וְהָיָה","and-be"],["קֹדֶשׁ","holy"],["וְיָרְשׁוּ","and-possess"],["בֵּית","the-house-of"],["יַעֲקֹב","Jacob"],["אֵת־מוֹרָשֵׁיהֶם","their-possessions"],["׃",""]] },
  { num:"יח", words:[["וְהָיָה","and-be"],["בֵית־יַעֲקֹב","house-of-Jacob"],["אֵשׁ","fire"],["וּבֵית","and-house-of"],["יוֹסֵף","Joseph"],["לֶהָבָה","a-flame"],["וּבֵית","and-house-of"],["עֵשָׂו","Esau"],["לְקַשׁ","into-chaff"],["וְדָלְקוּ","and-they will burn"],["בָהֶם","among-them"],["וַאֲכָלוּם","and-they will consume-them"],["וְלֹא־יִהְיֶה","and-shall-have-no-more"],["שָׂרִיד","a survivor"],["לְבֵית","to-the-house-of"],["עֵשָׂו","Esau"],["כִּי","because"],["יְהֹוָה","the-LORD"],["דִּבֵּר","spoke"],["׃",""]] },
  { num:"יט", words:[["וְיָרְשׁוּ","and-possess"],["הַנֶּגֶב","the-south"],["אֶת־הַר","mountain"],["עֵשָׂו","Esau"],["וְהַשְּׁפֵלָה","and-the-Shephelah"],["אֶת־פְּלִשְׁתִּים","Philistines"],["וְיָרְשׁוּ","and-possess"],["אֶת־שְׂדֵה","the-field-of"],["אֶפְרַיִם","Ephraim"],["וְאֵת","and"],["שְׂדֵה","the-field-of"],["שֹׁמְרוֹן","Samaria"],["וּבִנְיָמִן","and-Benjamin"],["אֶת־הַגִּלְעָד","the-Gilead"],["׃",""]] },
  { num:"כ", words:[["וְגָלֻת","and-the exiles of"],["הַחֵל־הַזֶּה","the-fortress-this"],["לִבְנֵי","unto-the-sons-of"],["יִשְׂרָאֵל","Israel"],["אֲשֶׁר־כְּנַעֲנִים","which-merchants"],["עַד־צָרְפַת","until-Zarephath"],["וְגָלֻת","and-the exiles of"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["אֲשֶׁר","which"],["בִּסְפָרַד","are in-Sepharad"],["יִרְשׁוּ","they will take possession of"],["אֵת־עָרֵי","cities-of"],["הַנֶּגֶב","the-south"],["׃",""]] },
  { num:"כא", words:[["וְעָלוּ","and-they will go up"],["מוֹשִׁעִים","deliverers"],["בְּהַר","on-the-mount-of"],["צִיּוֹן","Zion"],["לִשְׁפֹּט","to-judge"],["אֶת־הַר","mountain"],["עֵשָׂו","Esau"],["וְהָיְתָה","and-it-be"],["לַיהֹוָה","to-the-LORD"],["הַמְּלוּכָה","the-capital"],["׃",""]] },
];
renderVerseSet(oba_ch1Verses, 'oba-ch1-verses');

})();
