// ot_verses/sos.js — Song of Songs verse data
(function() {
var sos_ch1Verses = [
  { num:"א", words:[["שִׁיר","a song"],["הַשִּׁירִים","the-songs"],["אֲשֶׁר","which"],["לִשְׁלֹמֹה","to-Solomon"],["׃",""]] },
  { num:"ב", words:[["יִשָּׁקֵנִי","let him kiss-me"],["מִנְּשִׁיקוֹת","from-the kisses of"],["פִּיהוּ","His-mouth"],["כִּי־טוֹבִים","because-good"],["דֹּדֶיךָ","love-your"],["מִיָּיִן","from-wine"],["׃",""]] },
  { num:"ג", words:[["לְרֵיחַ","to-an odor of"],["שְׁמָנֶיךָ","oils-your"],["טוֹבִים","good"],["שֶׁמֶן","oil"],["תּוּרַק","which it is poured out"],["שְׁמֶךָ","your-name"],["עַל־כֵּן","therefore"],["עֲלָמוֹת","alamoth"],["אֲהֵבוּךָ","they love-you"],["׃",""]] },
  { num:"ד", words:[["מׇשְׁכֵנִי","draw-me"],["אַחֲרֶיךָ","after-you"],["נָּרוּצָה","let us run"],["הֱבִיאַנִי","he has brought-me"],["הַמֶּלֶךְ","the-king"],["חֲדָרָיו","chambers-his"],["נָגִילָה","we-do-rejoice"],["וְנִשְׂמְחָה","and-rejoice-with"],["בָּךְ","in-You"],["נַזְכִּירָה","let us bring to remembrance"],["דֹדֶיךָ","love-your"],["מִיַּיִן","from-wine"],["מֵישָׁרִים","uprightness"],["אֲהֵבוּךָ","they love-you"],["׃",""]] },
  { num:"ה", words:[["שְׁחוֹרָה","am black"],["אֲנִי","I"],["וְנָאוָה","and-lovely"],["בְּנוֹת","the-daughters-of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["כְּאׇהֳלֵי","like-the tents of"],["קֵדָר","Kedar"],["כִּירִיעוֹת","like-the tent curtains of"],["שְׁלֹמֹה","Solomon"],["׃",""]] },
  { num:"ו", words:[["אַל־תִּרְאוּנִי","do-not-you-shall-show-me"],["שֶׁאֲנִי","that-I"],["שְׁחַרְחֹרֶת","am blackish"],["שֶׁשְּׁזָפַתְנִי","on whom-has looked on-me"],["הַשָּׁמֶשׁ","the-sun"],["בְּנֵי","the-sons-of"],["אִמִּי","my-mother"],["נִחֲרוּ־בִי","they were angry-against-Me"],["שָׂמֻנִי","they made-me"],["נֹטֵרָה","one who keeps"],["אֶת־הַכְּרָמִים","[ACC]-the-vineyards"],["כַּרְמִי","my-vineyard"],["שֶׁלִּי","which-belongs to-me"],["לֹא","not"],["נָטָרְתִּי","I have kept"],["׃",""]] },
  { num:"ז", words:[["הַגִּידָה","tell-!"],["לִּי","to-me"],["שֶׁאָהֲבָה","O whom-it loves"],["נַפְשִׁי","my-life"],["אֵיכָה","how?!"],["תִרְעֶה","you will shepherd"],["אֵיכָה","how?!"],["תַּרְבִּיץ","will you make them lie down"],["בַּצׇּהֳרָיִם","at-the-noon"],["שַׁלָּמָה","which-to-why?"],["אֶהְיֶה","I-may-be"],["כְּעֹטְיָה","like-a veiled woman"],["עַל","upon"],["עֶדְרֵי","flock-my"],["חֲבֵרֶיךָ","companions-your"],["׃",""]] },
  { num:"ח", words:[["אִם־לֹא","if-not"],["תֵדְעִי","you know"],["לָךְ","[compound]"],["הַיָּפָה","the-beautiful"],["בַּנָּשִׁים","among the-women"],["צְאִי־לָךְ","go out-[compound]"],["בְּעִקְבֵי","in-the footprints of"],["הַצֹּאן","the-flock"],["וּרְעִי","and-pasture"],["אֶת־גְּדִיֹּתַיִךְ","[ACC]-young goats-your"],["עַל","upon"],["מִשְׁכְּנוֹת","from-dwelt(f)(pl.f)"],["הָרֹעִים","the-shepherds"],["׃",""]] },
  { num:"ט", words:[["לְסֻסָתִי","to-mare-my"],["בְּרִכְבֵי","among-the chariots of"],["פַרְעֹה","Pharaoh"],["דִּמִּיתִיךְ","I liken-you"],["רַעְיָתִי","O friend-my"],["׃",""]] },
  { num:"י", words:[["נָאווּ","they are beautiful"],["לְחָיַיִךְ","cheeks-your"],["בַּתֹּרִים","with-the-strings of jewels"],["צַוָּארֵךְ","your-neck"],["בַּחֲרוּזִים","with-strings of beads"],["׃",""]] },
  { num:"יא", words:[["תּוֹרֵי","necklaces of"],["זָהָב","gold"],["נַעֲשֶׂה־לָּךְ","let-us-make-to-you"],["עִם","with"],["נְקֻדּוֹת","beads of"],["הַכָּסֶף","the-money"],["׃",""]] },
  { num:"יב", words:[["עַד־שֶׁהַמֶּלֶךְ","until-that-the-king"],["בִּמְסִבּוֹ","was at-table-his"],["נִרְדִּי","nard-my"],["נָתַן","was-given"],["רֵיחוֹ","odor-its"],["׃",""]] },
  { num:"יג", words:[["צְרוֹר","the bag of"],["הַמֹּר","the-myrrh"],["דּוֹדִי","my-beloved"],["לִי","to-me"],["בֵּין","among"],["שָׁדַי","breasts-my"],["יָלִין","it will remain overnight"],["׃",""]] },
  { num:"יד", words:[["אֶשְׁכֹּל","Eshcol"],["הַכֹּפֶר","the-henna blossom"],["דּוֹדִי","my-beloved"],["לִי","to-me"],["בְּכַרְמֵי","in-my-vineyard"],["עֵין","the-eye-of"],["גֶּדִי","Gedi"],["׃",""]] },
  { num:"טו", words:[["הִנָּךְ","here-you"],["יָפָה","yea-even-a-very-beautiful"],["רַעְיָתִי","O friend-my"],["הִנָּךְ","here-you"],["יָפָה","yea-even-a-very-beautiful"],["עֵינַיִךְ","your-eyes"],["יוֹנִים","are doves"],["׃",""]] },
  { num:"טז", words:[["הִנְּךָ","you"],["יָפֶה","fair"],["דוֹדִי","O lover-my"],["אַף","yea"],["נָעִים","delightsome"],["אַף־עַרְשֵׂנוּ","yea-bed-our"],["רַעֲנָנָה","it will grow luxuriant"],["׃",""]] },
  { num:"יז", words:[["קֹרוֹת","the beams of"],["בָּתֵּינוּ","houses-our"],["אֲרָזִים","cedars"],["[רַהִיטֵנוּ]","rafters-our"],["בְּרוֹתִים","are cypress"],["׃",""]] },
];
renderVerseSet(sos_ch1Verses, 'sos-ch1-verses');

var sos_ch2Verses = [
  { num:"א", words:[["אֲנִי","I"],["חֲבַצֶּלֶת","am the crocus of"],["הַשָּׁרוֹן","the-Sharon"],["שׁוֹשַׁנַּת","lily of"],["הָעֲמָקִים","the-valleys"],["׃",""]] },
  { num:"ב", words:[["כְּשׁוֹשַׁנָּה","like-a lily"],["בֵּין","among"],["הַחוֹחִים","the-thorns"],["כֵּן","thus"],["רַעְיָתִי","O friend-my"],["בֵּין","among"],["הַבָּנוֹת","the-daughters"],["׃",""]] },
  { num:"ג", words:[["כְּתַפּוּחַ","like-an apple tree"],["בַּעֲצֵי","with-the wood of"],["הַיַּעַר","the-forest"],["כֵּן","thus"],["דּוֹדִי","my-beloved"],["בֵּין","among"],["הַבָּנִים","the-children"],["בְּצִלּוֹ","in-shade-his"],["חִמַּדְתִּי","I desired"],["וְיָשַׁבְתִּי","and-I sat"],["וּפִרְיוֹ","and-its-fruit"],["מָתוֹק","sweet"],["לְחִכִּי","to-palate-my"],["׃",""]] },
  { num:"ד", words:[["הֱבִיאַנִי","he has brought-me"],["אֶל־בֵּית","to-the-house-of"],["הַיָּיִן","the-wine"],["וְדִגְלוֹ","and-standard-his"],["עָלַי","I-must"],["אַהֲבָה","love"],["׃",""]] },
  { num:"ה", words:[["סַמְּכוּנִי","sustain-me"],["בָּאֲשִׁישׁוֹת","with-raisin-cakes"],["רַפְּדוּנִי","refresh-me"],["בַּתַּפּוּחִים","with-the-apples"],["כִּי־חוֹלַת","because-am weak of"],["אַהֲבָה","love"],["אָנִי","I"],["׃",""]] },
  { num:"ו", words:[["שְׂמֹאלוֹ","left hand-his"],["תַּחַת","under"],["לְרֹאשִׁי","my-head"],["וִימִינוֹ","and-right hand-his"],["תְּחַבְּקֵנִי","it embraces-me"],["׃",""]] },
  { num:"ז", words:[["הִשְׁבַּעְתִּי","I adjure"],["אֶתְכֶם","you"],["בְּנוֹת","the-daughters-of"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["בִּצְבָאוֹת","by-gazelles"],["אוֹ","or"],["בְּאַיְלוֹת","by-the does of"],["הַשָּׂדֶה","the-field"],["אִם־תָּעִירוּ","[compound]-you will awaken"],["וְאִם־תְּעוֹרְרוּ","and-if-you will arouse"],["אֶת־הָאַהֲבָה","[ACC]-the-love"],["עַד","until"],["שֶׁתֶּחְפָּץ","that-it will please"],["׃",""]] },
  { num:"ח", words:[["קוֹל","the-voice-of"],["דּוֹדִי","my-beloved"],["הִנֵּה־זֶה","behold-this"],["בָּא","came"],["מְדַלֵּג","is leaping"],["עַל־הֶהָרִים","upon-the-mountains"],["מְקַפֵּץ","is bounding"],["עַל־הַגְּבָעוֹת","upon-the-hills"],["׃",""]] },
  { num:"ט", words:[["דּוֹמֶה","is like"],["דוֹדִי","O lover-my"],["לִצְבִי","beautiful"],["אוֹ","or"],["לְעֹפֶר","the fawn of"],["הָאַיָּלִים","the-deer"],["הִנֵּה־זֶה","behold-this"],["עוֹמֵד","standing"],["אַחַר","after"],["כׇּתְלֵנוּ","the wall of-us"],["מַשְׁגִּיחַ","is gazing"],["מִן־הַחַלֹּנוֹת","from-the-windows"],["מֵצִיץ","is peering"],["מִן־הַחֲרַכִּים","from-the-lattices"],["׃",""]] },
  { num:"י", words:[["עָנָה","he has testified"],["דוֹדִי","O lover-my"],["וְאָמַר","and-said"],["לִי","to-me"],["קוּמִי","stand-up"],["לָךְ","[compound]"],["רַעְיָתִי","O friend-my"],["יָפָתִי","beautiful one-my"],["וּלְכִי־לָךְ","and-go-[compound]"],["׃",""]] },
  { num:"יא", words:[["כִּי־הִנֵּה","because-behold"],["הַסְּתָו","the-winter"],["עָבָר","it passed on"],["הַגֶּשֶׁם","the-rain"],["חָלַף","it has passed away"],["הָלַךְ","went"],["לוֹ","him"],["׃",""]] },
  { num:"יב", words:[["הַנִּצָּנִים","the-blossoms"],["נִרְאוּ","we-will-they-saw"],["בָאָרֶץ","in-the-land"],["עֵת","time"],["הַזָּמִיר","the-pruning"],["הִגִּיעַ","come-has"],["וְקוֹל","the-voice-of-the-people"],["הַתּוֹר","the-turtle-dove"],["נִשְׁמַע","was-heard"],["בְּאַרְצֵנוּ","in-our-own-land"],["׃",""]] },
  { num:"יג", words:[["הַתְּאֵנָה","the-fig tree"],["חָנְטָה","it has ripened"],["פַגֶּיהָ","early figs-its"],["וְהַגְּפָנִים","and-the-vines"],["סְמָדַר","blossom"],["נָתְנוּ","they-gave"],["רֵיחַ","smell"],["קוּמִי","stand-up"],["(לכי)","go"],["[לָךְ]","unto-you"],["רַעְיָתִי","O friend-my"],["יָפָתִי","beautiful one-my"],["וּלְכִי־לָךְ","and-go-[compound]"],["׃",""]] },
  { num:"יד", words:[["יוֹנָתִי","O dove-my"],["בְּחַגְוֵי","in-the clefts of"],["הַסֶּלַע","the-rock"],["בְּסֵתֶר","in-the cover of"],["הַמַּדְרֵגָה","the-steep place"],["הַרְאִינִי","let see-me"],["אֶת־מַרְאַיִךְ","[ACC]-form-your"],["הַשְׁמִיעִנִי","make hear-me"],["אֶת־קוֹלֵךְ","[ACC]-your-voice"],["כִּי־קוֹלֵךְ","because-your-voice"],["עָרֵב","is sweet"],["וּמַרְאֵיךְ","and-form-your"],["נָאוֶה","is suitable"],["׃",""]] },
  { num:"טו", words:[["אֶחֱזוּ־לָנוּ","seize-us"],["שֻׁעָלִים","foxes"],["שֻׁעָלִים","foxes"],["קְטַנִּים","little"],["מְחַבְּלִים","which ruin"],["כְּרָמִים","vineyards"],["וּכְרָמֵינוּ","and-vineyards-our"],["סְמָדַר","blossom"],["׃",""]] },
  { num:"טז", words:[["דּוֹדִי","my-beloved"],["לִי","to-me"],["וַאֲנִי","and-I"],["לוֹ","him"],["הָרֹעֶה","the-shepherd"],["בַּשּׁוֹשַׁנִּים","among the-lilies"],["׃",""]] },
  { num:"יז", words:[["עַד","until"],["שֶׁיָּפוּחַ","that-will breathe"],["הַיּוֹם","the-day"],["וְנָסוּ","and-they will flee"],["הַצְּלָלִים","the-shadows"],["סֹב","going round"],["דְּמֵה־לְךָ","be like-for-you"],["דוֹדִי","O lover-my"],["לִצְבִי","beautiful"],["אוֹ","or"],["לְעֹפֶר","the fawn of"],["הָאַיָּלִים","the-deer"],["עַל־הָרֵי","upon-the mountains of"],["בָתֶר","ravines"],["׃",""]] },
];
renderVerseSet(sos_ch2Verses, 'sos-ch2-verses');

var sos_ch3Verses = [
  { num:"א", words:[["עַל־מִשְׁכָּבִי","upon-bed-my"],["בַּלֵּילוֹת","in the-nights"],["בִּקַּשְׁתִּי","I-have-sought"],["אֵת","[ACC]"],["שֶׁאָהֲבָה","O whom-it loves"],["נַפְשִׁי","my-life"],["בִּקַּשְׁתִּיו","I sought-him"],["וְלֹא","and-not"],["מְצָאתִיו","I found-him"],["׃",""]] },
  { num:"ב", words:[["אָקוּמָה","let me arise"],["נָּא","now"],["וַאֲסוֹבְבָה","and-I will go around"],["בָעִיר","in the-city"],["בַּשְּׁוָקִים","in the-streets"],["וּבָרְחֹבוֹת","and-in the-open places"],["אֲבַקְשָׁה","I will seek"],["אֵת","[ACC]"],["שֶׁאָהֲבָה","O whom-it loves"],["נַפְשִׁי","my-life"],["בִּקַּשְׁתִּיו","I sought-him"],["וְלֹא","and-not"],["מְצָאתִיו","I found-him"],["׃",""]] },
  { num:"ג", words:[["מְצָאוּנִי","have they come upon-me"],["הַשֹּׁמְרִים","the-those-who watched"],["הַסֹּבְבִים","the-who-go around"],["בָּעִיר","in-the-city"],["אֵת","[ACC]"],["שֶׁאָהֲבָה","O whom-it loves"],["נַפְשִׁי","my-life"],["רְאִיתֶם","you-saw"],["׃",""]] },
  { num:"ד", words:[["כִּמְעַט","nearly"],["שֶׁעָבַרְתִּי","that-I had passed away"],["מֵהֶם","of-them"],["עַד","until"],["שֶׁמָּצָאתִי","that-I found"],["אֵת","[ACC]"],["שֶׁאָהֲבָה","O whom-it loves"],["נַפְשִׁי","my-life"],["אֲחַזְתִּיו","I grasped-him"],["וְלֹא","and-not"],["אַרְפֶּנּוּ","I let go-him"],["עַד־שֶׁהֲבֵיאתִיו","until-that-I had brought-him"],["אֶל־בֵּית","to-the-house-of"],["אִמִּי","my-mother"],["וְאֶל־חֶדֶר","and-a room"],["הוֹרָתִי","the one who conceived-me"],["׃",""]] },
  { num:"ה", words:[["הִשְׁבַּעְתִּי","I adjure"],["אֶתְכֶם","you"],["בְּנוֹת","the-daughters-of"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["בִּצְבָאוֹת","by-gazelles"],["אוֹ","or"],["בְּאַיְלוֹת","by-the does of"],["הַשָּׂדֶה","the-field"],["אִם־תָּעִירוּ","[compound]-you will awaken"],["וְאִם־תְּעוֹרְרוּ","and-if-you will arouse"],["אֶת־הָאַהֲבָה","[ACC]-the-love"],["עַד","until"],["שֶׁתֶּחְפָּץ","that-it will please"],["׃",""]] },
  { num:"ו", words:[["מִי","who"],["זֹאת","this"],["עֹלָה","a-burnt-offering"],["מִן־הַמִּדְבָּר","from-the-wilderness"],["כְּתִימְרוֹת","like-columns of"],["עָשָׁן","smoke"],["מְקֻטֶּרֶת","who is perfumed of"],["מֹר","are myrrh"],["וּלְבוֹנָה","and-frankincense"],["מִכֹּל","of-all"],["אַבְקַת","the scent-powder of"],["רוֹכֵל","a trader"],["׃",""]] },
  { num:"ז", words:[["הִנֵּה","behold"],["מִטָּתוֹ","bed-his"],["שֶׁלִּשְׁלֹמֹה","which-belongs to-Solomon"],["שִׁשִּׁים","sixty"],["גִּבֹּרִים","were warriors"],["סָבִיב","round-about"],["לָהּ","it"],["מִגִּבֹּרֵי","some of-the warriors of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"ח", words:[["כֻּלָּם","all-of-them"],["אֲחֻזֵי","are grasped of"],["חֶרֶב","the-sword-of"],["מְלֻמְּדֵי","trained of"],["מִלְחָמָה","war"],["אִישׁ","man-of"],["חַרְבּוֹ","his-sword"],["עַל־יְרֵכוֹ","upon-thigh-his"],["מִפַּחַד","from-fear"],["בַּלֵּילוֹת","in the-nights"],["׃",""]] },
  { num:"ט", words:[["אַפִּרְיוֹן","a litter"],["עָשָׂה","he-did"],["לוֹ","him"],["הַמֶּלֶךְ","the-king"],["שְׁלֹמֹה","Solomon"],["מֵעֲצֵי","from-the wood of"],["הַלְּבָנוֹן","the-Lebanon"],["׃",""]] },
  { num:"י", words:[["עַמּוּדָיו","pillars-its"],["עָשָׂה","he-did"],["כֶסֶף","silver/money"],["רְפִידָתוֹ","back-its"],["זָהָב","gold"],["מֶרְכָּבוֹ","seat-its"],["אַרְגָּמָן","purple cloth"],["תּוֹכוֹ","the middle of-it"],["רָצוּף","was fitted out"],["אַהֲבָה","love"],["מִבְּנוֹת","the-daughters-of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["׃",""]] },
  { num:"יא", words:[["וּרְאֶינָה","and-look"],["בְּנוֹת","the-daughters-of"],["צִיּוֹן","Zion"],["בַּמֶּלֶךְ","in-the-reigned"],["שְׁלֹמֹה","Solomon"],["בָּעֲטָרָה","on the-crown"],["שֶׁעִטְּרָה־לּוֹ","that-crowned-upon-him"],["אִמּוֹ","His-mother"],["בְּיוֹם","in-day-of"],["חֲתֻנָּתוֹ","wedding-his"],["וּבְיוֹם","and-in-day-of"],["שִׂמְחַת","joy-of"],["לִבּוֹ","his-heart"],["׃",""]] },
];
renderVerseSet(sos_ch3Verses, 'sos-ch3-verses');

var sos_ch4Verses = [
  { num:"א", words:[["הִנָּךְ","here-you"],["יָפָה","yea-even-a-very-beautiful"],["רַעְיָתִי","O friend-my"],["הִנָּךְ","here-you"],["יָפָה","yea-even-a-very-beautiful"],["עֵינַיִךְ","your-eyes"],["יוֹנִים","are doves"],["מִבַּעַד","from-in-the-until"],["לְצַמָּתֵךְ","to-veil-your"],["שַׂעְרֵךְ","hair-your"],["כְּעֵדֶר","as-a-wild-flock"],["הָעִזִּים","the-goats"],["שֶׁגָּלְשׁוּ","that-have descended"],["מֵהַר","from-the mountain of"],["גִּלְעָד","Gilead"],["׃",""]] },
  { num:"ב", words:[["שִׁנַּיִךְ","teeth-your"],["כְּעֵדֶר","as-a-wild-flock"],["הַקְּצוּבוֹת","the-shorn ewes"],["שֶׁעָלוּ","that-have come up"],["מִן־הָרַחְצָה","from-the-washing"],["שֶׁכֻּלָּם","that-all of-them"],["מַתְאִימוֹת","are bearing twins"],["וְשַׁכֻּלָה","and-is one deprived of offspring"],["אֵין","there-is-no"],["בָּהֶם","in-them"],["׃",""]] },
  { num:"ג", words:[["כְּחוּט","are like-the thread of"],["הַשָּׁנִי","the-scarlet thread"],["שִׂפְתוֹתַיִךְ","lips-your"],["וּמִדְבָּרֵךְ","and-from-word-your"],["נָאוֶה","is suitable"],["כְּפֶלַח","like-a mill-stone"],["הָרִמּוֹן","the-Rimmon"],["רַקָּתֵךְ","temple-your"],["מִבַּעַד","from-in-the-until"],["לְצַמָּתֵךְ","to-veil-your"],["׃",""]] },
  { num:"ד", words:[["כְּמִגְדַּל","is like-the tower of"],["דָּוִיד","David"],["צַוָּארֵךְ","your-neck"],["בָּנוּי","built"],["לְתַלְפִּיּוֹת","to-layers"],["אֶלֶף","thousand"],["הַמָּגֵן","the-shield"],["תָּלוּי","one who is hanged"],["עָלָיו","upon-him"],["כֹּל","all"],["שִׁלְטֵי","the shields of"],["הַגִּבֹּרִים","were the-mighty men"],["׃",""]] },
  { num:"ה", words:[["שְׁנֵי","two"],["שָׁדַיִךְ","breasts-your"],["כִּשְׁנֵי","as-two"],["עֳפָרִים","fawns"],["תְּאוֹמֵי","twins of"],["צְבִיָּה","a gazelle"],["הָרוֹעִים","the-which-graze"],["בַּשּׁוֹשַׁנִּים","among the-lilies"],["׃",""]] },
  { num:"ו", words:[["עַד","until"],["שֶׁיָּפוּחַ","that-will breathe"],["הַיּוֹם","the-day"],["וְנָסוּ","and-they will flee"],["הַצְּלָלִים","the-shadows"],["אֵלֶךְ","I walked"],["לִי","to-me"],["אֶל־הַר","to-the-mountain-of"],["הַמּוֹר","the-myrrh"],["וְאֶל־גִּבְעַת","and-hill-of"],["הַלְּבוֹנָה","the-frankincense"],["׃",""]] },
  { num:"ז", words:[["כֻּלָּךְ","all of-you"],["יָפָה","yea-even-a-very-beautiful"],["רַעְיָתִי","O friend-my"],["וּמוּם","and-is blemish"],["אֵין","there-is-no"],["בָּךְ","in-You"],["׃",""]] },
  { num:"ח", words:[["אִתִּי","with-me"],["מִלְּבָנוֹן","from-Lebanon"],["כַּלָּה","O bride"],["אִתִּי","with-me"],["מִלְּבָנוֹן","from-Lebanon"],["תָּבוֹאִי","you go"],["תָּשׁוּרִי","you will come down"],["מֵרֹאשׁ","from-the-beginning"],["אֲמָנָה","are Amana"],["מֵרֹאשׁ","from-the-beginning"],["שְׂנִיר","Senir"],["וְחֶרְמוֹן","and-Hermon"],["מִמְּעֹנוֹת","from-the dens of"],["אֲרָיוֹת","lions"],["מֵהַרְרֵי","from-the mountains of"],["נְמֵרִים","leopards"],["׃",""]] },
  { num:"ט", words:[["לִבַּבְתִּנִי","you have stolen heart-my"],["אֲחֹתִי","are sister-my"],["כַלָּה","bride"],["לִבַּבְתִּנִי","you have stolen heart-my"],["(באחד)","by-the-one"],["[בְּאַחַת]","at-one"],["מֵעֵינַיִךְ","from-eyes-your"],["בְּאַחַד","in-one"],["עֲנָק","Anak"],["מִצַּוְּרֹנָיִךְ","from-necklaces-your"],["׃",""]] },
  { num:"י", words:[["מַה־יָּפוּ","what-they are beautiful"],["דֹדַיִךְ","love-your"],["אֲחֹתִי","are sister-my"],["כַלָּה","bride"],["מַה־טֹּבוּ","what-they are good"],["דֹדַיִךְ","love-your"],["מִיַּיִן","from-wine"],["וְרֵיחַ","and-the odor of"],["שְׁמָנַיִךְ","oils-your"],["מִכׇּל־בְּשָׂמִים","from-all-spices"],["׃",""]] },
  { num:"יא", words:[["נֹפֶת","honey"],["תִּטֹּפְנָה","they drip"],["שִׂפְתוֹתַיִךְ","lips-your"],["כַּלָּה","O bride"],["דְּבַשׁ","honey"],["וְחָלָב","and-milk"],["תַּחַת","under"],["לְשׁוֹנֵךְ","tongue-your"],["וְרֵיחַ","and-the odor of"],["שַׂלְמֹתַיִךְ","garments-your"],["כְּרֵיחַ","is like-the smell of"],["לְבָנוֹן","Lebanon"],["׃",""]] },
  { num:"יב", words:[["גַּן","tarry"],["נָעוּל","locked"],["אֲחֹתִי","are sister-my"],["כַלָּה","bride"],["גַּל","a heap of"],["נָעוּל","locked"],["מַעְיָן","spring/fountain"],["חָתוּם","shall-be-sealed"],["׃",""]] },
  { num:"יג", words:[["שְׁלָחַיִךְ","shoots-your"],["פַּרְדֵּס","are a garden of"],["רִמּוֹנִים","pomegranates"],["עִם","with"],["פְּרִי","fruit"],["מְגָדִים","choice"],["כְּפָרִים","henna plants"],["עִם־נְרָדִים","with-nard plants"],["׃",""]] },
  { num:"יד", words:[["נֵרְדְּ","nard"],["וְכַרְכֹּם","and-saffron"],["קָנֶה","reeds"],["וְקִנָּמוֹן","and-cinnamon"],["עִם","with"],["כׇּל־עֲצֵי","all-the-trees-of"],["לְבוֹנָה","frankincense"],["מֹר","are myrrh"],["וַאֲהָלוֹת","and-aloes"],["עִם","with"],["כׇּל־רָאשֵׁי","all-the-heads-of"],["בְשָׂמִים","spices"],["׃",""]] },
  { num:"טו", words:[["מַעְיַן","a-fountain-of"],["גַּנִּים","Gannim"],["בְּאֵר","Beer"],["מַיִם","water"],["חַיִּים","living"],["וְנֹזְלִים","and-streams"],["מִן־לְבָנוֹן","from-Lebanon"],["׃",""]] },
  { num:"טז", words:[["עוּרִי","awake"],["צָפוֹן","the-north"],["וּבוֹאִי","and-come"],["תֵימָן","the south"],["הָפִיחִי","make breathe"],["גַנִּי","garden-my"],["יִזְּלוּ","they flow"],["בְשָׂמָיו","spices-its"],["יָבֹא","shall-come"],["דוֹדִי","O lover-my"],["לְגַנּוֹ","to-garden-his"],["וְיֹאכַל","also-and-devour"],["פְּרִי","fruit"],["מְגָדָיו","choice-its"],["׃",""]] },
];
renderVerseSet(sos_ch4Verses, 'sos-ch4-verses');

var sos_ch5Verses = [
  { num:"א", words:[["בָּאתִי","when-I-came"],["לְגַנִּי","to-garden-my"],["אֲחֹתִי","are sister-my"],["כַלָּה","bride"],["אָרִיתִי","I have gathered"],["מוֹרִי","myrrh-my"],["עִם־בְּשָׂמִי","with-spice-my"],["אָכַלְתִּי","I-ate"],["יַעְרִי","honeycomb-my"],["עִם־דִּבְשִׁי","with-honey-my"],["שָׁתִיתִי","I drank"],["יֵינִי","wine-my"],["עִם־חֲלָבִי","with-milk-my"],["אִכְלוּ","eat"],["רֵעִים","friends"],["שְׁתוּ","drink"],["וְשִׁכְרוּ","and-become drunk"],["דּוֹדִים","O lovers"],["׃",""]] },
  { num:"ב", words:[["אֲנִי","I"],["יְשֵׁנָה","was sleeping"],["וְלִבִּי","and-my-heart"],["עֵר","Er"],["קוֹל","the-voice-of"],["דּוֹדִי","my-beloved"],["דוֹפֵק","knocking"],["פִּתְחִי־לִי","open-to-me"],["אֲחֹתִי","are sister-my"],["רַעְיָתִי","O friend-my"],["יוֹנָתִי","O dove-my"],["תַמָּתִי","perfect one-my"],["שֶׁרֹּאשִׁי","that-head-my"],["נִמְלָא־טָל","filled-was-dew"],["קְוֻצּוֹתַי","locks-my"],["רְסִיסֵי","dewdrops of"],["לָיְלָה","night"],["׃",""]] },
  { num:"ג", words:[["פָּשַׁטְתִּי","I have taken off"],["אֶת־כֻּתׇּנְתִּי","[ACC]-tunic-my"],["אֵיכָכָה","how?"],["אֶלְבָּשֶׁנָּה","will I put on-it"],["רָחַצְתִּי","I have washed"],["אֶת־רַגְלַי","[ACC]-feet-of"],["אֵיכָכָה","how?"],["אֲטַנְּפֵם","will I dirty-them"],["׃",""]] },
  { num:"ד", words:[["דּוֹדִי","my-beloved"],["שָׁלַח","sent"],["יָדוֹ","his-hand"],["מִן־הַחֹר","from-the-hole"],["וּמֵעַי","and-inward parts-my"],["הָמוּ","they were in a tumult"],["עָלָיו","upon-him"],["׃",""]] },
  { num:"ה", words:[["קַמְתִּי","I arose"],["אֲנִי","I"],["לִפְתֹּחַ","opened"],["לְדוֹדִי","to-lover-my"],["וְיָדַי","and-hands-my"],["נָטְפוּ־מוֹר","they dropped-myrrh"],["וְאֶצְבְּעֹתַי","and-fingers-my"],["מוֹר","myrrh"],["עֹבֵר","that-passes-away"],["עַל","upon"],["כַּפּוֹת","the-soles"],["הַמַּנְעוּל","the-bolt"],["׃",""]] },
  { num:"ו", words:[["פָּתַחְתִּי","I open"],["אֲנִי","I"],["לְדוֹדִי","to-lover-my"],["וְדוֹדִי","and-lover-my"],["חָמַק","he had turned away"],["עָבָר","it passed on"],["נַפְשִׁי","my-life"],["יָצְאָה","went-forth"],["בְדַבְּרוֹ","when-turned aside-he"],["בִּקַּשְׁתִּיהוּ","I sought-him"],["וְלֹא","and-not"],["מְצָאתִיהוּ","I found-him"],["קְרָאתִיו","I-called-him"],["וְלֹא","and-not"],["עָנָנִי","he has answered-me"],["׃",""]] },
  { num:"ז", words:[["מְצָאֻנִי","they found-me"],["הַשֹּׁמְרִים","the-those-who watched"],["הַסֹּבְבִים","the-who-go around"],["בָּעִיר","in-the-city"],["הִכּוּנִי","they struck-me"],["פְצָעוּנִי","they bruised-me"],["נָשְׂאוּ","took"],["אֶת־רְדִידִי","[ACC]-garment-my"],["מֵעָלַי","from-me"],["שֹׁמְרֵי","have-kept"],["הַחֹמוֹת","the-walls"],["׃",""]] },
  { num:"ח", words:[["הִשְׁבַּעְתִּי","I adjure"],["אֶתְכֶם","you"],["בְּנוֹת","the-daughters-of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["אִם־תִּמְצְאוּ","[compound]-you-will-they-found"],["אֶת־דּוֹדִי","[ACC]-my-beloved"],["מַה־תַּגִּידוּ","what-you will tell"],["לוֹ","him"],["שֶׁחוֹלַת","that-am weak of"],["אַהֲבָה","love"],["אָנִי","I"],["׃",""]] },
  { num:"ט", words:[["מַה־דּוֹדֵךְ","what-lover-your"],["מִדּוֹד","more than-a lover"],["הַיָּפָה","the-beautiful"],["בַּנָּשִׁים","among the-women"],["מַה־דּוֹדֵךְ","what-lover-your"],["מִדּוֹד","more than-a lover"],["שֶׁכָּכָה","that-thus"],["הִשְׁבַּעְתָּנוּ","you made swear-us"],["׃",""]] },
  { num:"י", words:[["דּוֹדִי","my-beloved"],["צַח","is dazzling"],["וְאָדוֹם","and-ruddy"],["דָּגוּל","is conspicuous"],["מֵרְבָבָה","more than-ten thousand"],["׃",""]] },
  { num:"יא", words:[["רֹאשׁוֹ","his-head"],["כֶּתֶם","is gold of"],["פָּז","pure gold"],["קְוֻצּוֹתָיו","locks-his"],["תַּלְתַּלִּים","are curls"],["שְׁחֹרוֹת","black"],["כָּעוֹרֵב","like-raven"],["׃",""]] },
  { num:"יב", words:[["עֵינָיו","their-eyes"],["כְּיוֹנִים","are like-doves"],["עַל־אֲפִיקֵי","upon-are tubes of"],["מָיִם","water"],["רֹחֲצוֹת","washing"],["בֶּחָלָב","in-milk"],["יֹשְׁבוֹת","were dwelling"],["עַל־מִלֵּאת","upon-fullness"],["׃",""]] },
  { num:"יג", words:[["לְחָיָו","cheeks-his"],["כַּעֲרוּגַת","are like-the bed of"],["הַבֹּשֶׂם","the-spice"],["מִגְדְּלוֹת","towers of"],["מֶרְקָחִים","aromatic herbs"],["שִׂפְתוֹתָיו","lips-his"],["שׁוֹשַׁנִּים","Shoshannim"],["נֹטְפוֹת","dripping"],["מוֹר","myrrh"],["עֹבֵר","that-passes-away"],["׃",""]] },
  { num:"יד", words:[["יָדָיו","his-hands"],["גְּלִילֵי","rods of"],["זָהָב","gold"],["מְמֻלָּאִים","filled"],["בַּתַּרְשִׁישׁ","with-the-chrysolite"],["מֵעָיו","his-bowels"],["עֶשֶׁת","are a plate of"],["שֵׁן","their-teeth"],["מְעֻלֶּפֶת","covered"],["סַפִּירִים","sapphires"],["׃",""]] },
  { num:"טו", words:[["שׁוֹקָיו","legs-his"],["עַמּוּדֵי","pillars of"],["שֵׁשׁ","six"],["מְיֻסָּדִים","founded"],["עַל־אַדְנֵי־פָז","upon-bases of-pure gold"],["מַרְאֵהוּ","from-saw-his"],["כַּלְּבָנוֹן","like-the-Lebanon"],["בָּחוּר","a-chosen-man"],["כָּאֲרָזִים","like-cedars"],["׃",""]] },
  { num:"טז", words:[["חִכּוֹ","his-mouth"],["מַמְתַקִּים","sweet things"],["וְכֻלּוֹ","and-all of-it"],["מַחֲמַדִּים","is desirableness"],["זֶה","this"],["דוֹדִי","O lover-my"],["וְזֶה","and-this"],["רֵעִי","companions-of"],["בְּנוֹת","the-daughters-of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["׃",""]] },
];
renderVerseSet(sos_ch5Verses, 'sos-ch5-verses');

var sos_ch6Verses = [
  { num:"א", words:[["אָנָה","whither"],["הָלַךְ","went"],["דּוֹדֵךְ","lover-your"],["הַיָּפָה","the-beautiful"],["בַּנָּשִׁים","among the-women"],["אָנָה","whither"],["פָּנָה","turned"],["דוֹדֵךְ","lover-your"],["וּנְבַקְשֶׁנּוּ","so-we may seek-him"],["עִמָּךְ","your-people"],["׃",""]] },
  { num:"ב", words:[["דּוֹדִי","my-beloved"],["יָרַד","came-down"],["לְגַנּוֹ","to-garden-his"],["לַעֲרֻגוֹת","to-the-the beds of"],["הַבֹּשֶׂם","the-spice"],["לִרְעוֹת","to-tend"],["בַּגַּנִּים","in the-gardens"],["וְלִלְקֹט","and-to-gather"],["שׁוֹשַׁנִּים","Shoshannim"],["׃",""]] },
  { num:"ג", words:[["אֲנִי","I"],["לְדוֹדִי","to-lover-my"],["וְדוֹדִי","and-lover-my"],["לִי","to-me"],["הָרֹעֶה","the-shepherd"],["בַּשּׁוֹשַׁנִּים","among the-lilies"],["׃",""]] },
  { num:"ד", words:[["יָפָה","yea-even-a-very-beautiful"],["אַתְּ","ACC"],["רַעְיָתִי","O friend-my"],["כְּתִרְצָה","like-Tirzah"],["נָאוָה","is fitting"],["כִּירוּשָׁלָ͏ִם","like-Jerusalem"],["אֲיֻמָּה","majestic"],["כַּנִּדְגָּלוֹת","like-the-hosts with banners"],["׃",""]] },
  { num:"ה", words:[["הָסֵבִּי","turn"],["עֵינַיִךְ","your-eyes"],["מִנֶּגְדִּי","from-before-me"],["שֶׁהֵם","that-they"],["הִרְהִיבֻנִי","they have confused-me"],["שַׂעְרֵךְ","hair-your"],["כְּעֵדֶר","as-a-wild-flock"],["הָעִזִּים","the-goats"],["שֶׁגָּלְשׁוּ","that-have descended"],["מִן־הַגִּלְעָד","from-the-Gilead"],["׃",""]] },
  { num:"ו", words:[["שִׁנַּיִךְ","teeth-your"],["כְּעֵדֶר","as-a-wild-flock"],["הָרְחֵלִים","the-ewes"],["שֶׁעָלוּ","that-have come up"],["מִן־הָרַחְצָה","from-the-washing"],["שֶׁכֻּלָּם","that-all of-them"],["מַתְאִימוֹת","are bearing twins"],["וְשַׁכֻּלָה","and-is one deprived of offspring"],["אֵין","there-is-no"],["בָּהֶם","in-them"],["׃",""]] },
  { num:"ז", words:[["כְּפֶלַח","like-a mill-stone"],["הָרִמּוֹן","the-Rimmon"],["רַקָּתֵךְ","temple-your"],["מִבַּעַד","from-in-the-until"],["לְצַמָּתֵךְ","to-veil-your"],["׃",""]] },
  { num:"ח", words:[["שִׁשִּׁים","sixty"],["הֵמָּה","they-are"],["מְלָכוֹת","queens"],["וּשְׁמֹנִים","and-eighty"],["פִּילַגְשִׁים","concubines"],["וַעֲלָמוֹת","and-young women"],["אֵין","there-is-no"],["מִסְפָּר","number"],["׃",""]] },
  { num:"ט", words:[["אַחַת","one"],["הִיא","it-is"],["יוֹנָתִי","O dove-my"],["תַמָּתִי","perfect one-my"],["אַחַת","one"],["הִיא","it-is"],["לְאִמָּהּ","of-mother-her"],["בָּרָה","Barah"],["הִיא","it-is"],["לְיוֹלַדְתָּהּ","of-the one who bore-her"],["רָאוּהָ","they saw-her"],["בָנוֹת","daughters"],["וַיְאַשְּׁרוּהָ","and-they called blessed-her"],["מְלָכוֹת","queens"],["וּפִילַגְשִׁים","and-concubines"],["וַיְהַלְלוּהָ","and-they praised-her"],["׃",""]] },
  { num:"י", words:[["מִי־זֹאת","who-this"],["הַנִּשְׁקָפָה","is the-one who looks down"],["כְּמוֹ־שָׁחַר","as/like-light"],["יָפָה","yea-even-a-very-beautiful"],["כַלְּבָנָה","like the-full moon"],["בָּרָה","Barah"],["כַּחַמָּה","like the-sun"],["אֲיֻמָּה","majestic"],["כַּנִּדְגָּלוֹת","like-the-hosts with banners"],["׃",""]] },
  { num:"יא", words:[["אֶל־גִּנַּת","to-the garden of"],["אֱגוֹז","nuts"],["יָרַדְתִּי","I went down"],["לִרְאוֹת","to-see"],["בְּאִבֵּי","on-the green shoots of"],["הַנָּחַל","the-river"],["לִרְאוֹת","to-see"],["הֲפָרְחָה","¿-had it budded"],["הַגֶּפֶן","the-vine"],["הֵנֵצוּ","had they bloomed?"],["הָרִמֹּנִים","the-pomegranates"],["׃",""]] },
  { num:"יב", words:[["לֹא","not"],["יָדַעְתִּי","I-know"],["נַפְשִׁי","my-life"],["שָׂמַתְנִי","it set-me"],["מַרְכְּבוֹת","the chariots of"],["עַמִּי","my-people"],["נָדִיב","willing person"],["׃",""]] },
];
renderVerseSet(sos_ch6Verses, 'sos-ch6-verses');

var sos_ch7Verses = [
  { num:"א", words:[["שׁוּבִי","return(f)"],["שׁוּבִי","return(f)"],["הַשּׁוּלַמִּית","the-O-Shulammite woman"],["שׁוּבִי","return(f)"],["שׁוּבִי","return(f)"],["וְנֶחֱזֶה־בָּךְ","so-we may look-in-You"],["מַה־תֶּחֱזוּ","what-will you look"],["בַּשּׁוּלַמִּית","on the-Shulammite woman"],["כִּמְחֹלַת","like-the dance of"],["הַמַּחֲנָיִם","the-two groups"],["׃",""]] },
  { num:"ב", words:[["מַה־יָּפוּ","what-they are beautiful"],["פְעָמַיִךְ","feet-your"],["בַּנְּעָלִים","the-dry-shod"],["בַּת־נָדִיב","daughter-of-willing person"],["חַמּוּקֵי","the curves of"],["יְרֵכַיִךְ","thighs-your"],["כְּמוֹ","as/like"],["חֲלָאִים","jewels"],["מַעֲשֵׂה","work-of"],["יְדֵי","hands-of"],["אׇמָּן","amen"],["׃",""]] },
  { num:"ג", words:[["שׇׁרְרֵךְ","navel-your"],["אַגַּן","is the bowl of"],["הַסַּהַר","the-roundness"],["אַל־יֶחְסַר","do-not-fail"],["הַמָּזֶג","the-mixed wine"],["בִּטְנֵךְ","belly-your"],["עֲרֵמַת","is a heap of"],["חִטִּים","wheat"],["סוּגָה","fenced around"],["בַּשּׁוֹשַׁנִּים","among the-lilies"],["׃",""]] },
  { num:"ד", words:[["שְׁנֵי","two"],["שָׁדַיִךְ","breasts-your"],["כִּשְׁנֵי","as-two"],["עֳפָרִים","fawns"],["תׇּאֳמֵי","twins of"],["צְבִיָּה","a gazelle"],["׃",""]] },
  { num:"ה", words:[["צַוָּארֵךְ","your-neck"],["כְּמִגְדַּל","is like-the tower of"],["הַשֵּׁן","the-Shen"],["עֵינַיִךְ","your-eyes"],["בְּרֵכוֹת","pools of"],["בְּחֶשְׁבּוֹן","in-account"],["עַל־שַׁעַר","upon-gate-of"],["בַּת־רַבִּים","daughter-of-many"],["אַפֵּךְ","nose-your"],["כְּמִגְדַּל","is like-the tower of"],["הַלְּבָנוֹן","the-Lebanon"],["צוֹפֶה","is watching"],["פְּנֵי","face-of"],["דַמָּשֶׂק","Damascus"],["׃",""]] },
  { num:"ו", words:[["רֹאשֵׁךְ","head-your"],["עָלַיִךְ","upon-you(f)"],["כַּכַּרְמֶל","the-is like-Carmel"],["וְדַלַּת","and-the hair of"],["רֹאשֵׁךְ","head-your"],["כָּאַרְגָּמָן","is like-purple wool"],["מֶלֶךְ","the-king-of"],["אָסוּר","bound"],["בָּרְהָטִים","by the-tresses"],["׃",""]] },
  { num:"ז", words:[["מַה־יָּפִית","what-you are beautiful"],["וּמַה־נָּעַמְתְּ","yea-and-what-you are lovely"],["אַהֲבָה","love"],["בַּתַּעֲנוּגִים","with-the-delights"],["׃",""]] },
  { num:"ח", words:[["זֹאת","this"],["קוֹמָתֵךְ","stature-your"],["דָּמְתָה","it is like"],["לְתָמָר","to-Tamar"],["וְשָׁדַיִךְ","and-breasts-your"],["לְאַשְׁכֹּלוֹת","clusters"],["׃",""]] },
  { num:"ט", words:[["אָמַרְתִּי","I-said"],["אֶעֱלֶה","I-will-ascend"],["בְתָמָר","on-the palm tree"],["אֹחֲזָה","I will take hold"],["בְּסַנְסִנָּיו","on-fruit-stalks-its"],["וְיִהְיוּ־נָא","and-they-were-I-pray"],["שָׁדַיִךְ","breasts-your"],["כְּאֶשְׁכְּלוֹת","like-the clusters of"],["הַגֶּפֶן","the-vine"],["וְרֵיחַ","and-the odor of"],["אַפֵּךְ","nose-your"],["כַּתַּפּוּחִים","like-the-apples"],["׃",""]] },
  { num:"י", words:[["וְחִכֵּךְ","and-mouth-your"],["כְּיֵין","like-the wine of"],["הַטּוֹב","the-good"],["הוֹלֵךְ","going"],["לְדוֹדִי","to-lover-my"],["לְמֵישָׁרִים","to-smoothness"],["דּוֹבֵב","which flows gently"],["שִׂפְתֵי","the lips of"],["יְשֵׁנִים","he-will-years"],["׃",""]] },
  { num:"יא", words:[["אֲנִי","I"],["לְדוֹדִי","to-lover-my"],["וְעָלַי","and-I-must"],["תְּשׁוּקָתוֹ","desire-its"],["׃",""]] },
  { num:"יב", words:[["לְכָה","you-have"],["דוֹדִי","O lover-my"],["נֵצֵא","let-us-go-forth"],["הַשָּׂדֶה","the-field"],["נָלִינָה","let us pass the night"],["בַּכְּפָרִים","in-the-atonement"],["׃",""]] },
  { num:"יג", words:[["נַשְׁכִּימָה","let us rise early"],["לַכְּרָמִים","to the-vineyards"],["נִרְאֶה","we-see"],["אִם־פָּרְחָה","[compound]-it has budded"],["הַגֶּפֶן","the-vine"],["פִּתַּח","it has opened"],["הַסְּמָדַר","the-blossom"],["הֵנֵצוּ","had they bloomed?"],["הָרִמּוֹנִים","the-pomegranates"],["שָׁם","there"],["אֶתֵּן","shall-give"],["אֶת־דֹּדַי","[ACC]-love-my"],["לָךְ","[compound]"],["׃",""]] },
  { num:"יד", words:[["הַדּוּדָאִים","the-mandrakes"],["נָתְנוּ־רֵיחַ","they-gave-smell"],["וְעַל־פְּתָחֵינוּ","and-upon-doorway-our"],["כׇּל־מְגָדִים","all-choice"],["חֲדָשִׁים","new-ones"],["גַּם־יְשָׁנִים","also-old"],["דּוֹדִי","my-beloved"],["צָפַנְתִּי","I have treasured up"],["לָךְ","[compound]"],["׃",""]] },
];
renderVerseSet(sos_ch7Verses, 'sos-ch7-verses');

var sos_ch8Verses = [
  { num:"א", words:[["מִי","who"],["יִתֶּנְךָ","he will make-you"],["כְּאָח","like-a brother"],["לִי","to-me"],["יוֹנֵק","the-nursing-child"],["שְׁדֵי","the breasts of"],["אִמִּי","my-mother"],["אֶמְצָאֲךָ","I will find-you"],["בַחוּץ","on the-outside"],["אֶשָּׁקְךָ","I will give to drink-you"],["גַּם","also"],["לֹא־יָבֻזוּ","not-they-despise"],["לִי","to-me"],["׃",""]] },
  { num:"ב", words:[["אֶנְהָגְךָ","I will lead-you"],["אֲבִיאֲךָ","I will bring-you"],["אֶל־בֵּית","to-the-house-of"],["אִמִּי","my-mother"],["תְּלַמְּדֵנִי","who she taught-me"],["אַשְׁקְךָ","I will give to drink-you"],["מִיַּיִן","from-wine"],["הָרֶקַח","the-spice"],["מֵעֲסִיס","some of-the juice of"],["רִמֹּנִי","pomegranate-my"],["׃",""]] },
  { num:"ג", words:[["שְׂמֹאלוֹ","left hand-his"],["תַּחַת","under"],["רֹאשִׁי","head-my"],["וִימִינוֹ","and-right hand-his"],["תְּחַבְּקֵנִי","it embraces-me"],["׃",""]] },
  { num:"ד", words:[["הִשְׁבַּעְתִּי","I adjure"],["אֶתְכֶם","you"],["בְּנוֹת","the-daughters-of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["מַה־תָּעִירוּ","what-you will awaken"],["וּמַה־תְּעֹרְרוּ","yea-and-what-will you arouse"],["אֶת־הָאַהֲבָה","[ACC]-the-love"],["עַד","until"],["שֶׁתֶּחְפָּץ","that-it will please"],["׃",""]] },
  { num:"ה", words:[["מִי","who"],["זֹאת","this"],["עֹלָה","a-burnt-offering"],["מִן־הַמִּדְבָּר","from-the-wilderness"],["מִתְרַפֶּקֶת","leaning herself"],["עַל־דּוֹדָהּ","upon-lover-her"],["תַּחַת","under"],["הַתַּפּוּחַ","the-apple tree"],["עוֹרַרְתִּיךָ","I aroused-you"],["שָׁמָּה","there"],["חִבְּלַתְךָ","she was in labor with-you"],["אִמֶּךָ","your-mother"],["שָׁמָּה","there"],["חִבְּלָה","she was in labor"],["יְלָדַתְךָ","bore-you"],["׃",""]] },
  { num:"ו", words:[["שִׂימֵנִי","put-me"],["כַחוֹתָם","like-seal"],["עַל־לִבֶּךָ","upon-heart-your"],["כַּחוֹתָם","like-seal"],["עַל־זְרוֹעֶךָ","upon-arm-your"],["כִּי־עַזָּה","because-exceedingly"],["כַמָּוֶת","like-the-death"],["אַהֲבָה","love"],["קָשָׁה","hard"],["כִשְׁאוֹל","like-Sheol"],["קִנְאָה","jealousy"],["רְשָׁפֶיהָ","flashes-its"],["רִשְׁפֵּי","are flashes of"],["אֵשׁ","fire"],["שַׁלְהֶבֶתְיָה","a flame of-the Lord"],["׃",""]] },
  { num:"ז", words:[["מַיִם","water"],["רַבִּים","many"],["לֹא","not"],["יוּכְלוּ","could-they"],["לְכַבּוֹת","to-extinguish"],["אֶת־הָאַהֲבָה","[ACC]-the-love"],["וּנְהָרוֹת","and-rivers"],["לֹא","not"],["יִשְׁטְפוּהָ","they-would-overrun-it"],["אִם־יִתֵּן","[compound]-shall-give"],["אִישׁ","man-of"],["אֶת־כׇּל־הוֹן","[ACC]-all-wealth"],["בֵּיתוֹ","his-house"],["בָּאַהֲבָה","for-love"],["בּוֹז","certainly"],["יָבוּזוּ","people despise"],["לוֹ","him"],["׃",""]] },
  { num:"ח", words:[["אָחוֹת","a sister"],["לָנוּ","us"],["קְטַנָּה","sin"],["וְשָׁדַיִם","and-breasts"],["אֵין","there-is-no"],["לָהּ","it"],["מַה־נַּעֲשֶׂה","what-shall-we-do"],["לַאֲחֹתֵנוּ","for-sister-our"],["בַּיּוֹם","in-the-day"],["שֶׁיְּדֻבַּר־בָּהּ","when-it will be spoken-in-it(f)"],["׃",""]] },
  { num:"ט", words:[["אִם־חוֹמָה","[compound]-a wall"],["הִיא","it-is"],["נִבְנֶה","we-will-build"],["עָלֶיהָ","upon-it"],["טִירַת","a battlement of"],["כָּסֶף","silverlings"],["וְאִם־דֶּלֶת","and-if-is a door"],["הִיא","it-is"],["נָצוּר","we will shut up"],["עָלֶיהָ","upon-it"],["לוּחַ","the tablet of"],["אָרֶז","cedar"],["׃",""]] },
  { num:"י", words:[["אֲנִי","I"],["חוֹמָה","a wall"],["וְשָׁדַי","and-breasts-my"],["כַּמִּגְדָּלוֹת","the-are like-towers"],["אָז","then"],["הָיִיתִי","I-was"],["בְעֵינָיו","with-their-eyes"],["כְּמוֹצְאֵת","like-one who finds"],["שָׁלוֹם","peace"],["׃",""]] },
  { num:"יא", words:[["כֶּרֶם","a-vineyard"],["הָיָה","was"],["לִשְׁלֹמֹה","to-Solomon"],["בְּבַעַל","at-Baal"],["הָמוֹן","a-multitude"],["נָתַן","was-given"],["אֶת־הַכֶּרֶם","[ACC]-the-vineyard"],["לַנֹּטְרִים","to-the-those who keep"],["אִישׁ","man-of"],["יָבִא","he will bring"],["בְּפִרְיוֹ","for-fruit-its"],["אֶלֶף","thousand"],["כָּסֶף","silverlings"],["׃",""]] },
  { num:"יב", words:[["כַּרְמִי","my-vineyard"],["שֶׁלִּי","which-belongs to-me"],["לְפָנָי","before-Me"],["הָאֶלֶף","the-one thousand"],["לְךָ","for-you"],["שְׁלֹמֹה","Solomon"],["וּמָאתַיִם","and-two hundred"],["לְנֹטְרִים","belong to-those who keep"],["אֶת־פִּרְיוֹ","[ACC]-was-his-fruit"],["׃",""]] },
  { num:"יג", words:[["הַיּוֹשֶׁבֶת","the-O-inhabitant-of"],["בַּגַּנִּים","in the-gardens"],["חֲבֵרִים","united"],["מַקְשִׁיבִים","are listening"],["לְקוֹלֵךְ","for-voice-your"],["הַשְׁמִיעִנִי","make hear-me"],["׃",""]] },
  { num:"יד", words:[["בְּרַח","flee"],["דּוֹדִי","my-beloved"],["וּדְמֵה־לְךָ","and-be like-for-you"],["לִצְבִי","beautiful"],["אוֹ","or"],["לְעֹפֶר","the fawn of"],["הָאַיָּלִים","the-deer"],["עַל","upon"],["הָרֵי","the mountains of"],["בְשָׂמִים","spices"],["׃",""]] },
];
renderVerseSet(sos_ch8Verses, 'sos-ch8-verses');

})();
