// ot_verses/zec.js — Zechariah verse data
(function() {
var zec_ch1Verses = [
  { num:"א", words:[["בַּחֹדֶשׁ","in-the-month"],["הַשְּׁמִינִי","the-eighth"],["בִּשְׁנַת","in-year-of"],["שְׁתַּיִם","two"],["לְדָרְיָוֶשׁ","to-Darius"],["הָיָה","was"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["אֶל־זְכַרְיָה","to-Zechariah"],["בֶּן־בֶּרֶכְיָה","son-of-Berekiah"],["בֶּן־עִדּוֹ","son-of-Iddo"],["הַנָּבִיא","the-prophet"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ב", words:[["קָצַף","was-angry"],["יְהֹוָה","the-LORD"],["עַל־אֲבוֹתֵיכֶם","upon-our-fathers"],["קָצֶף","anger"],["׃",""]] },
  { num:"ג", words:[["וְאָמַרְתָּ","and-say"],["אֲלֵהֶם","unto-them"],["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["שׁוּבוּ","return/repent"],["אֵלַי","to-me"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["וְאָשׁוּב","and-I-return"],["אֲלֵיכֶם","unto-you"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"ד", words:[["אַל־תִּהְיוּ","do-not-you-be"],["כַאֲבֹתֵיכֶם","like-ancestors-your"],["אֲשֶׁר","which"],["קָרְאוּ־אֲלֵיהֶם","called-upon-to-them"],["הַנְּבִיאִים","the-prophets"],["הָרִאשֹׁנִים","the-his-first"],["לֵאמֹר","saying"],["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["שׁוּבוּ","return/repent"],["נָא","I-pray"],["מִדַּרְכֵיכֶם","from-your-ways"],["הָרָעִים","evil"],["[וּמַעַלְלֵיכֶם]","and-deeds-your"],["הָרָעִים","evil"],["וְלֹא","and-not"],["שָׁמְעוּ","they-heard"],["וְלֹא־הִקְשִׁיבוּ","and-not-hearken-unto"],["אֵלַי","to-me"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"ה", words:[["אֲבוֹתֵיכֶם","our-fathers"],["אַיֵּה־הֵם","where-is-they"],["וְהַנְּבִאִים","and-the-prophets"],["הַלְעוֹלָם","¿-to-forever"],["יִחְיוּ","they-shall-live"],["׃",""]] },
  { num:"ו", words:[["אַךְ","but"],["דְּבָרַי","my-words"],["וְחֻקַּי","and-statutes-my"],["אֲשֶׁר","which"],["צִוִּיתִי","have-I-commanded"],["אֶת־עֲבָדַי","[ACC]-the-servants-of"],["הַנְּבִיאִים","the-prophets"],["הֲלוֹא","art-not"],["הִשִּׂיגוּ","have-obtained"],["אֲבֹתֵיכֶם","fathers-your"],["וַיָּשׁוּבוּ","and-they-returned"],["וַיֹּאמְרוּ","and-they-said"],["כַּאֲשֶׁר","when/as"],["זָמַם","Zmm"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["לַעֲשׂוֹת","to-do"],["לָנוּ","us"],["כִּדְרָכֵינוּ","according to-ways-our"],["וּכְמַעֲלָלֵינוּ","and-according to-deeds-our"],["כֵּן","thus"],["עָשָׂה","he-did"],["אִתָּנוּ","with-us"],["׃",""]] },
  { num:"ז", words:[["בְּיוֹם","in-day-of"],["עֶשְׂרִים","twenty"],["וְאַרְבָּעָה","and-four"],["לְעַשְׁתֵּי־עָשָׂר","will belong to-one plus-[compound]"],["חֹדֶשׁ","a month of"],["הוּא־חֹדֶשׁ","it-is-a month of"],["שְׁבָט","Shebat"],["בִּשְׁנַת","in-year-of"],["שְׁתַּיִם","two"],["לְדָרְיָוֶשׁ","to-Darius"],["הָיָה","was"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["אֶל־זְכַרְיָה","to-Zechariah"],["בֶּן־בֶּרֶכְיָהוּ","son-of-Berekiah"],["בֶּן־עִדּוֹא","son-of-Iddo"],["הַנָּבִיא","the-prophet"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ח", words:[["רָאִיתִי","I-saw"],["הַלַּיְלָה","the-night"],["וְהִנֵּה־אִישׁ","and-behold-man-of"],["רֹכֵב","was riding"],["עַל־סוּס","upon-a horse"],["אָדֹם","man"],["וְהוּא","and-it"],["עֹמֵד","standing"],["בֵּין","among"],["הַהֲדַסִּים","the-myrtle trees"],["אֲשֶׁר","which"],["בַּמְּצֻלָה","were in the-hollow"],["וְאַחֲרָיו","and-after-it"],["סוּסִים","horses"],["אֲדֻמִּים","red"],["שְׂרֻקִּים","sorrel"],["וּלְבָנִים","and-white"],["׃",""]] },
  { num:"ט", words:[["וָאֹמַר","and-I-said"],["מָה־אֵלֶּה","what-these"],["אֲדֹנִי","my-Lord"],["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["הַמַּלְאָךְ","the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["אֲנִי","I"],["אַרְאֶךָּ","I will show-you"],["מָה־הֵמָּה","what-they-are"],["אֵלֶּה","these"],["׃",""]] },
  { num:"י", words:[["וַיַּעַן","and-he-answered"],["הָאִישׁ","the-man"],["הָעֹמֵד","the-who-stands"],["בֵּין־הַהֲדַסִּים","among-the-myrtle trees"],["וַיֹּאמַר","and-said"],["אֵלֶּה","these"],["אֲשֶׁר","which"],["שָׁלַח","sent"],["יְהֹוָה","the-LORD"],["לְהִתְהַלֵּךְ","to-walk"],["בָּאָרֶץ","in-the-land"],["׃",""]] },
  { num:"יא", words:[["וַיַּעֲנוּ","and-they-answered"],["אֶת־מַלְאַךְ","[ACC]-angel-of"],["יְהֹוָה","the-LORD"],["הָעֹמֵד","the-who-stands"],["בֵּין","among"],["הַהֲדַסִּים","the-myrtle trees"],["וַיֹּאמְרוּ","and-they-said"],["הִתְהַלַּכְנוּ","which we went about"],["בָאָרֶץ","in-the-land"],["וְהִנֵּה","and-behold"],["כׇל־הָאָרֶץ","all-the-earth"],["יֹשֶׁבֶת","sat"],["וְשֹׁקָטֶת","and-is undisturbed"],["׃",""]] },
  { num:"יב", words:[["וַיַּעַן","and-he-answered"],["מַלְאַךְ־יְהֹוָה","angel-of-the-LORD"],["וַיֹּאמַר","and-said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["עַד־מָתַי","until-when"],["אַתָּה","you"],["לֹא־תְרַחֵם","not-will you have compassion on"],["אֶת־יְרוּשָׁלַ͏ִם","[ACC]-Jerusalem"],["וְאֵת","and-[ACC]"],["עָרֵי","cities-of"],["יְהוּדָה","Judah"],["אֲשֶׁר","which"],["זָעַמְתָּה","you have been indignant"],["זֶה","this"],["שִׁבְעִים","seventy"],["שָׁנָה","year"],["׃",""]] },
  { num:"יג", words:[["וַיַּעַן","and-he-answered"],["יְהֹוָה","the-LORD"],["אֶת־הַמַּלְאָךְ","[ACC]-the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["דְּבָרִים","things"],["טוֹבִים","good"],["דְּבָרִים","things"],["נִחֻמִים","comfort"],["׃",""]] },
  { num:"יד", words:[["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["הַמַּלְאָךְ","the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["קְרָא","call"],["לֵאמֹר","saying"],["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["קִנֵּאתִי","I have been zealous"],["לִירוּשָׁלַ͏ִם","to-Jerusalem"],["וּלְצִיּוֹן","and-for-Zion"],["קִנְאָה","jealousy"],["גְדוֹלָה","great"],["׃",""]] },
  { num:"טו", words:[["וְקֶצֶף","and-anger"],["גָּדוֹל","great"],["אֲנִי","I"],["קֹצֵף","am angry"],["עַל־הַגּוֹיִם","upon-the-nations"],["הַשַּׁאֲנַנִּים","the-self-confident people"],["אֲשֶׁר","which"],["אֲנִי","I"],["קָצַפְתִּי","I was angry"],["מְּעָט","a little"],["וְהֵמָּה","and-they-are"],["עָזְרוּ","they helped"],["לְרָעָה","for-evil"],["׃",""]] },
  { num:"טז", words:[["לָכֵן","therefore"],["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["שַׁבְתִּי","I-have-repented"],["לִירוּשָׁלַ͏ִם","to-Jerusalem"],["בְּרַחֲמִים","in-mercies"],["בֵּיתִי","my-house"],["יִבָּנֶה","it will be rebuilt"],["בָּהּ","in-it(f)"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["(וקוה)","and-he-hoped"],["[וְקָו]","and-a measuring-line"],["יִנָּטֶה","it will be stretched out"],["עַל־יְרוּשָׁלָ͏ִם","upon-Jerusalem"],["׃",""]] },
  { num:"יז", words:[["עוֹד","any-more"],["קְרָא","call"],["לֵאמֹר","saying"],["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["עוֹד","any-more"],["עָרַי","cities-my"],["מִטּוֹב","from-good"],["וְנִחַם","and-he will be comforted"],["יְהֹוָה","the-LORD"],["עוֹד","any-more"],["אֶת־צִיּוֹן","[ACC]-Zion"],["וּבָחַר","and-will-yet-choose"],["עוֹד","any-more"],["בִּירוּשָׁלָ͏ִם","is in-Jerusalem"],["׃",""]] },
];
renderVerseSet(zec_ch1Verses, 'zec-ch1-verses');

var zec_ch2Verses = [
  { num:"א", words:[["וָאֶשָּׂא","and-I-took-up"],["אֶת־עֵינַי","[ACC]-my-eyes"],["וָאֵרֶא","and-I-saw"],["וְהִנֵּה","and-behold"],["אַרְבַּע","four"],["קְרָנוֹת","horns"],["׃",""]] },
  { num:"ב", words:[["וָאֹמַר","and-I-said"],["אֶל־הַמַּלְאָךְ","to-the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["מָה־אֵלֶּה","what-these"],["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["אֵלֶּה","these"],["הַקְּרָנוֹת","the-horns"],["אֲשֶׁר","which"],["זֵרוּ","they scattered"],["אֶת־יְהוּדָה","[ACC]-Judah"],["אֶת־יִשְׂרָאֵל","[ACC]-Israel"],["וִירוּשָׁלָ͏ִם","and-Jerusalem"],["׃",""]] },
  { num:"ג", words:[["וַיַּרְאֵנִי","and-showed-me"],["יְהֹוָה","the-LORD"],["אַרְבָּעָה","four"],["חָרָשִׁים","craftsmen"],["׃",""]] },
  { num:"ד", words:[["וָאֹמַר","and-I-said"],["מָה","what"],["אֵלֶּה","these"],["בָאִים","are about to come"],["לַעֲשׂוֹת","to-do"],["וַיֹּאמֶר","and-said"],["לֵאמֹר","saying"],["אֵלֶּה","these"],["הַקְּרָנוֹת","the-horns"],["אֲשֶׁר־זֵרוּ","whose-they scattered"],["אֶת־יְהוּדָה","[ACC]-Judah"],["כְּפִי־אִישׁ","according-to-man-of"],["לֹא־נָשָׂא","not-bore"],["רֹאשׁוֹ","his-head"],["וַיָּבֹאוּ","and-they-came"],["אֵלֶּה","these"],["לְהַחֲרִיד","to-make tremble"],["אֹתָם","them"],["לְיַדּוֹת","to-throw down"],["אֶת־קַרְנוֹת","[ACC]-the horns of"],["הַגּוֹיִם","the-nations"],["הַנֹּשְׂאִים","the-who-endured"],["קֶרֶן","the horn of"],["אֶל־אֶרֶץ","to-land-of"],["יְהוּדָה","Judah"],["לְזָרוֹתָהּ","to-scatter-it"],["׃",""]] },
  { num:"ה", words:[["וָאֶשָּׂא","and-I-took-up"],["עֵינַי","my-eyes"],["וָאֵרֶא","and-I-saw"],["וְהִנֵּה־אִישׁ","and-behold-man-of"],["וּבְיָדוֹ","and-in-his-hand"],["חֶבֶל","the region of"],["מִדָּה","size"],["׃",""]] },
  { num:"ו", words:[["וָאֹמַר","and-I-said"],["אָנָה","whither"],["אַתָּה","you"],["הֹלֵךְ","going"],["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["לָמֹד","certainly if"],["אֶת־יְרוּשָׁלַ͏ִם","[ACC]-Jerusalem"],["לִרְאוֹת","to-see"],["כַּמָּה־רׇחְבָּהּ","the-how-many?-breadth-its"],["וְכַמָּה","and-the-how-much?"],["אׇרְכָּהּ","is length-its"],["׃",""]] },
  { num:"ז", words:[["וְהִנֵּה","and-behold"],["הַמַּלְאָךְ","the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["יֹצֵא","was going out"],["וּמַלְאָךְ","and-a messenger"],["אַחֵר","other"],["יֹצֵא","was going out"],["לִקְרָאתוֹ","to-you-called-his"],["׃",""]] },
  { num:"ח", words:[["וַיֹּאמֶר","and-said"],["אֵלָו","to-him"],["רֻץ","run"],["דַּבֵּר","to-speak"],["אֶל־הַנַּעַר","to-the-child"],["הַלָּז","the-this"],["לֵאמֹר","saying"],["פְּרָזוֹת","villages"],["תֵּשֵׁב","shall-sit"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["מֵרֹב","from-multitude-of"],["אָדָם","man"],["וּבְהֵמָה","and-of-beasts"],["בְּתוֹכָהּ","in-its-midst"],["׃",""]] },
  { num:"ט", words:[["וַאֲנִי","and-I"],["אֶהְיֶה־לָּהּ","I-may-be-to-her"],["נְאֻם־יְהֹוָה","says-the-LORD"],["חוֹמַת","the-walls-of"],["אֵשׁ","fire"],["סָבִיב","round-about"],["וּלְכָבוֹד","and-glorious"],["אֶהְיֶה","I-may-be"],["בְתוֹכָהּ","in-the midst of-it"],["׃",""]] },
  { num:"י", words:[["הוֹי","O"],["הוֹי","O"],["וְנֻסוּ","flee"],["מֵאֶרֶץ","from-land-of"],["צָפוֹן","the-north"],["נְאֻם־יְהֹוָה","says-the-LORD"],["כִּי","because"],["כְּאַרְבַּע","about-four"],["רוּחוֹת","spirits-of"],["הַשָּׁמַיִם","the-heavens"],["פֵּרַשְׂתִּי","I have spread out"],["אֶתְכֶם","you"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"יא", words:[["הוֹי","O"],["צִיּוֹן","Zion"],["הִמָּלְטִי","escape"],["יוֹשֶׁבֶת","O-inhabitant-of"],["בַּת־בָּבֶל","daughter-of-Babylon"],["׃",""]] },
  { num:"יב", words:[["כִּי","because"],["כֹה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["אַחַר","after"],["כָּבוֹד","glorious"],["שְׁלָחַנִי","sent-me"],["אֶל־הַגּוֹיִם","unto-the-nations"],["הַשֹּׁלְלִים","the-who-plundered"],["אֶתְכֶם","you"],["כִּי","because"],["הַנֹּגֵעַ","the-who--ever touches"],["בָּכֶם","in-you"],["נֹגֵעַ","one who has touched"],["בְּבָבַת","the pupil of"],["עֵינוֹ","His-all-searching-eye"],["׃",""]] },
  { num:"יג", words:[["כִּי","because"],["הִנְנִי","behold-I"],["מֵנִיף","waving"],["אֶת־יָדִי","[ACC]-my-hand"],["עֲלֵיהֶם","against-them"],["וְהָיוּ","then-they-shall-be"],["שָׁלָל","the-spoil"],["לְעַבְדֵיהֶם","for-own slaves-their"],["וִידַעְתֶּם","and-you-shall-know"],["כִּי־יְהֹוָה","for-the-LORD"],["צְבָאוֹת","of-Hosts"],["שְׁלָחָנִי","has-sent-me"],["׃",""]] },
  { num:"יד", words:[["רׇנִּי","cry out"],["וְשִׂמְחִי","and-rejoice"],["בַּת־צִיּוֹן","the-daughter-of-Zion"],["כִּי","because"],["הִנְנִי־בָא","behold-I-came"],["וְשָׁכַנְתִּי","and-I will dwell"],["בְתוֹכֵךְ","in-the midst of-you"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"טו", words:[["וְנִלְווּ","and-they will join themselves"],["גוֹיִם","nations"],["רַבִּים","many"],["אֶל־יְהֹוָה","to-the-Lord"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["וְהָיוּ","then-they-shall-be"],["לִי","to-me"],["לְעָם","people"],["וְשָׁכַנְתִּי","and-I will dwell"],["בְתוֹכֵךְ","in-the midst of-you"],["וְיָדַעַתְּ","and-you-shall-know"],["כִּי־יְהֹוָה","for-the-LORD"],["צְבָאוֹת","of-Hosts"],["שְׁלָחַנִי","sent-me"],["אֵלָיִךְ","to-you"],["׃",""]] },
  { num:"טז", words:[["וְנָחַל","and-he will inherit"],["יְהֹוָה","the-LORD"],["אֶת־יְהוּדָה","[ACC]-Judah"],["חֶלְקוֹ","his-part"],["עַל","upon"],["אַדְמַת","the-land-of"],["הַקֹּדֶשׁ","the-Holy"],["וּבָחַר","and-will-yet-choose"],["עוֹד","any-more"],["בִּירוּשָׁלָ͏ִם","is in-Jerusalem"],["׃",""]] },
  { num:"יז", words:[["הַס","hush!"],["כׇּל־בָּשָׂר","all-the-flesh"],["מִפְּנֵי","because-of"],["יְהֹוָה","the-LORD"],["כִּי","because"],["נֵעוֹר","he has roused himself"],["מִמְּעוֹן","from-the habitation of"],["קׇדְשׁוֹ","holy-his"],["׃",""]] },
];
renderVerseSet(zec_ch2Verses, 'zec-ch2-verses');

var zec_ch3Verses = [
  { num:"א", words:[["וַיַּרְאֵנִי","and-showed-me"],["אֶת־יְהוֹשֻׁעַ","[ACC]-Joshua"],["הַכֹּהֵן","the-priest"],["הַגָּדוֹל","the-great"],["עֹמֵד","standing"],["לִפְנֵי","before"],["מַלְאַךְ","angel-of"],["יְהֹוָה","the-LORD"],["וְהַשָּׂטָן","and-the-Adversary"],["עֹמֵד","standing"],["עַל־יְמִינוֹ","upon-right hand-his"],["לְשִׂטְנוֹ","to-accuse-him"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["אֶל־הַשָּׂטָן","to/unto-the-Adversary"],["יִגְעַר","may he rebuke"],["יְהֹוָה","the-LORD"],["בְּךָ","in-You"],["הַשָּׂטָן","the-Adversary"],["וְיִגְעַר","and-may he rebuke"],["יְהֹוָה","the-LORD"],["בְּךָ","in-You"],["הַבֹּחֵר","the-who-has chosen"],["בִּירוּשָׁלָ͏ִם","is in-Jerusalem"],["הֲלוֹא","art-not"],["זֶה","this"],["אוּד","a piece of firewood"],["מֻצָּל","plucked out"],["מֵאֵשׁ","from-a fire"],["׃",""]] },
  { num:"ג", words:[["וִיהוֹשֻׁעַ","and-Joshua"],["הָיָה","was"],["לָבֻשׁ","is clothed"],["בְּגָדִים","garments"],["צוֹאִים","filthy"],["וְעֹמֵד","and-stands"],["לִפְנֵי","before"],["הַמַּלְאָךְ","the-angel"],["׃",""]] },
  { num:"ד", words:[["וַיַּעַן","and-he-answered"],["וַיֹּאמֶר","and-said"],["אֶל־הָעֹמְדִים","to-the-ones-standing"],["לְפָנָיו","before-him"],["לֵאמֹר","saying"],["הָסִירוּ","remove"],["הַבְּגָדִים","the-garments"],["הַצֹּאִים","the-filthy"],["מֵעָלָיו","from-with-him"],["וַיֹּאמֶר","and-said"],["אֵלָיו","to-him"],["רְאֵה","behold"],["הֶעֱבַרְתִּי","I have taken away"],["מֵעָלֶיךָ","from-upon-you(f)"],["עֲוֺנֶךָ","iniquity-your"],["וְהַלְבֵּשׁ","and-I will clothe"],["אֹתְךָ","you"],["מַחֲלָצוֹת","robes"],["׃",""]] },
  { num:"ה", words:[["וָאֹמַר","and-I-said"],["יָשִׂימוּ","set-at"],["צָנִיף","a turban"],["טָהוֹר","pure"],["עַל־רֹאשׁוֹ","upon-his-head"],["וַיָּשִׂימוּ","and-began-to-put"],["הַצָּנִיף","the-turban"],["הַטָּהוֹר","the-pure"],["עַל־רֹאשׁוֹ","upon-his-head"],["וַיַּלְבִּשֻׁהוּ","and-they clothed-him"],["בְּגָדִים","garments"],["וּמַלְאַךְ","and-angel-of"],["יְהֹוָה","the-LORD"],["עֹמֵד","standing"],["׃",""]] },
  { num:"ו", words:[["וַיָּעַד","and-witnesses"],["מַלְאַךְ","angel-of"],["יְהֹוָה","the-LORD"],["בִּיהוֹשֻׁעַ","Joshua"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ז", words:[["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["אִם־בִּדְרָכַי","[compound]-in-ways-my"],["תֵּלֵךְ","should-go"],["וְאִם","and-if"],["אֶת־מִשְׁמַרְתִּי","[ACC]-duty-my"],["תִשְׁמֹר","you-will-kept"],["וְגַם־אַתָּה","and-also-you"],["תָּדִין","you will govern"],["אֶת־בֵּיתִי","[ACC]-my-house"],["וְגַם","and-also"],["תִּשְׁמֹר","you-keep"],["אֶת־חֲצֵרָי","[ACC]-courts-my"],["וְנָתַתִּי","and-I-will-give"],["לְךָ","for-you"],["מַהְלְכִים","goings"],["בֵּין","among"],["הָעֹמְדִים","the-ones-standing"],["הָאֵלֶּה","these"],["׃",""]] },
  { num:"ח", words:[["שְׁמַע־נָא","hearken-I-pray"],["יְהוֹשֻׁעַ","Joshua"],["הַכֹּהֵן","the-priest"],["הַגָּדוֹל","the-great"],["אַתָּה","you"],["וְרֵעֶיךָ","and-companions-your"],["הַיֹּשְׁבִים","the-inhabitants"],["לְפָנֶיךָ","before-you"],["כִּי־אַנְשֵׁי","because-the-men-of"],["מוֹפֵת","a-miracle"],["הֵמָּה","they-are"],["כִּי־הִנְנִי","because-behold-I"],["מֵבִיא","brings"],["אֶת־עַבְדִּי","[ACC]-My-servant"],["צֶמַח","the-branch-of"],["׃",""]] },
  { num:"ט", words:[["כִּי","because"],["הִנֵּה","behold"],["הָאֶבֶן","the-stone"],["אֲשֶׁר","which"],["נָתַתִּי","I-gave"],["לִפְנֵי","before"],["יְהוֹשֻׁעַ","Joshua"],["עַל־אֶבֶן","upon-stone"],["אַחַת","one"],["שִׁבְעָה","seven"],["עֵינָיִם","eyes"],["הִנְנִי","behold-I"],["מְפַתֵּחַ","am about to engrave"],["פִּתֻּחָהּ","engraving-its"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["וּמַשְׁתִּי","and-I will remove"],["אֶת־עֲוֺן","[ACC]-the-iniquity-of"],["הָאָרֶץ־הַהִיא","the-earth-that"],["בְּיוֹם","in-day-of"],["אֶחָד","one"],["׃",""]] },
  { num:"י", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["תִּקְרְאוּ","ye-shall-call-upon"],["אִישׁ","man-of"],["לְרֵעֵהוּ","another"],["אֶל־תַּחַת","to-under"],["גֶּפֶן","vines"],["וְאֶל־תַּחַת","and-under"],["תְּאֵנָה","a fig tree"],["׃",""]] },
];
renderVerseSet(zec_ch3Verses, 'zec-ch3-verses');

var zec_ch4Verses = [
  { num:"א", words:[["וַיָּשׇׁב","and-he will turn"],["הַמַּלְאָךְ","the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["וַיְעִירֵנִי","and-he roused-me"],["כְּאִישׁ","as-a-man"],["אֲשֶׁר־יֵעוֹר","whose-it will be roused"],["מִשְּׁנָתוֹ","from-sleep-his"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["מָה","what"],["אַתָּה","you"],["רֹאֶה","I-perceive"],["(ויאמר)","and-it-is-said"],["[וָאֹמַר]","and-Emer"],["רָאִיתִי","I-saw"],["וְהִנֵּה","and-behold"],["מְנוֹרַת","a lampstand of"],["זָהָב","gold"],["כֻּלָּהּ","all-of-it(f)"],["וְגֻלָּהּ","and-a bowl"],["עַל־רֹאשָׁהּ","upon-top-its"],["וְשִׁבְעָה","and-satisfied"],["נֵרֹתֶיהָ","lamps-its"],["עָלֶיהָ","upon-it"],["שִׁבְעָה","seven"],["וְשִׁבְעָה","and-satisfied"],["מוּצָקוֹת","pipes"],["לַנֵּרוֹת","belong to the-lamps"],["אֲשֶׁר","which"],["עַל־רֹאשָׁהּ","upon-top-its"],["׃",""]] },
  { num:"ג", words:[["וּשְׁנַיִם","and-second"],["זֵיתִים","olive trees"],["עָלֶיהָ","upon-it"],["אֶחָד","one"],["מִימִין","from-the right of"],["הַגֻּלָּה","the-bowl"],["וְאֶחָד","and-one"],["עַל־שְׂמֹאלָהּ","upon-left side-its"],["׃",""]] },
  { num:"ד", words:[["וָאַעַן","and-I-answered"],["וָאֹמַר","and-I-said"],["אֶל־הַמַּלְאָךְ","to-the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["לֵאמֹר","saying"],["מָה־אֵלֶּה","what-these"],["אֲדֹנִי","my-Lord"],["׃",""]] },
  { num:"ה", words:[["וַיַּעַן","and-he-answered"],["הַמַּלְאָךְ","the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["הֲלוֹא","art-not"],["יָדַעְתָּ","you-know"],["מָה־הֵמָּה","what-they-are"],["אֵלֶּה","these"],["וָאֹמַר","and-I-said"],["לֹא","not"],["אֲדֹנִי","my-Lord"],["׃",""]] },
  { num:"ו", words:[["וַיַּעַן","and-he-answered"],["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["לֵאמֹר","saying"],["זֶה","this"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["אֶל־זְרֻבָּבֶל","to-Zerubbabel"],["לֵאמֹר","saying"],["לֹא","not"],["בְחַיִל","with-an army"],["וְלֹא","and-not"],["בְכֹחַ","with-power"],["כִּי","because"],["אִם־בְּרוּחִי","[compound]-by-spirit-my"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"ז", words:[["מִי־אַתָּה","who-you"],["הַר־הַגָּדוֹל","mountain-the-great"],["לִפְנֵי","before"],["זְרֻבָּבֶל","Zerubbabel"],["לְמִישֹׁר","level ground"],["וְהוֹצִיא","and-it-has-brought-forth"],["אֶת־הָאֶבֶן","[ACC]-the-stone"],["הָרֹאשָׁהֿ","the-chief"],["תְּשֻׁאוֹת","the crashes of"],["חֵן","favor"],["חֵן","favor"],["לָהּ","it"],["׃",""]] },
  { num:"ח", words:[["וַיְהִי","and-it-came-to-pass"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["אֵלַי","to-me"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ט", words:[["יְדֵי","hands-of"],["זְרֻבָּבֶל","Zerubbabel"],["יִסְּדוּ","they have founded"],["הַבַּיִת","the-house"],["הַזֶּה","this"],["וְיָדָיו","and-hands-his"],["תְּבַצַּעְנָה","they will finish it"],["וְיָדַעְתָּ","and-you-know"],["כִּי־יְהֹוָה","for-the-LORD"],["צְבָאוֹת","of-Hosts"],["שְׁלָחַנִי","sent-me"],["אֲלֵיכֶם","unto-you"],["׃",""]] },
  { num:"י", words:[["כִּי","because"],["מִי","who"],["בַז","spoil"],["לְיוֹם","to-day"],["קְטַנּוֹת","small"],["וְשָׂמְחוּ","and-they-rejoiced"],["וְרָאוּ","and-behold"],["אֶת־הָאֶבֶן","[ACC]-the-stone"],["הַבְּדִיל","the-tin"],["בְּיַד","in-hand-of"],["זְרֻבָּבֶל","Zerubbabel"],["שִׁבְעָה־אֵלֶּה","seven-these"],["עֵינֵי","the-eyes-of"],["יְהֹוָה","the-LORD"],["הֵמָּה","they-are"],["מְשׁוֹטְטִים","are roving about"],["בְּכׇל־הָאָרֶץ","in-all-the-land"],["׃",""]] },
  { num:"יא", words:[["וָאַעַן","and-I-answered"],["וָאֹמַר","and-I-said"],["אֵלָיו","to-him"],["מַה־שְּׁנֵי","what-are the two"],["הַזֵּיתִים","the-olive trees"],["הָאֵלֶּה","these"],["עַל־יְמִין","upon-right-hand"],["הַמְּנוֹרָה","the-lampstand"],["וְעַל־שְׂמֹאולָהּ","and-upon-left side-its"],["׃",""]] },
  { num:"יב", words:[["וָאַעַן","and-I-answered"],["שֵׁנִית","again"],["וָאֹמַר","and-I-said"],["אֵלָיו","to-him"],["מַה־שְׁתֵּי","what-two"],["שִׁבְּלֵי","the clusters of"],["הַזֵּיתִים","the-olive trees"],["אֲשֶׁר","which"],["בְּיַד","in-hand-of"],["שְׁנֵי","two"],["צַנְתְּרוֹת","the pipes of"],["הַזָּהָב","the-gold"],["הַמְרִיקִים","which-are pouring out"],["מֵעֲלֵיהֶם","from-off-them"],["הַזָּהָב","the-gold"],["׃",""]] },
  { num:"יג", words:[["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["לֵאמֹר","saying"],["הֲלוֹא","art-not"],["יָדַעְתָּ","you-know"],["מָה־אֵלֶּה","what-these"],["וָאֹמַר","and-I-said"],["לֹא","not"],["אֲדֹנִי","my-Lord"],["׃",""]] },
  { num:"יד", words:[["וַיֹּאמֶר","and-said"],["אֵלֶּה","these"],["שְׁנֵי","two"],["בְנֵי־הַיִּצְהָר","sons-of-the-fresh oil"],["הָעֹמְדִים","the-ones-standing"],["עַל־אֲדוֹן","upon-the-master-of"],["כׇּל־הָאָרֶץ","all-the-earth"],["׃",""]] },
];
renderVerseSet(zec_ch4Verses, 'zec-ch4-verses');

var zec_ch5Verses = [
  { num:"א", words:[["וָאָשׁוּב","and-returned"],["וָאֶשָּׂא","and-I-took-up"],["עֵינַי","my-eyes"],["וָאֶרְאֶה","and-I-saw"],["וְהִנֵּה","and-behold"],["מְגִלָּה","a scroll"],["עָפָה","flying"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["מָה","what"],["אַתָּה","you"],["רֹאֶה","I-perceive"],["וָאֹמַר","and-I-said"],["אֲנִי","I"],["רֹאֶה","I-perceive"],["מְגִלָּה","a scroll"],["עָפָה","flying"],["אׇרְכָּהּ","is length-its"],["עֶשְׂרִים","twenty"],["בָּאַמָּה","by the-cubit"],["וְרׇחְבָּהּ","and-breadth-its"],["עֶשֶׂר","ten"],["בָּאַמָּה","by the-cubit"],["׃",""]] },
  { num:"ג", words:[["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["זֹאת","this"],["הָאָלָה","the-curse"],["הַיּוֹצֵאת","the-which-is about to go forth"],["עַל־פְּנֵי","upon-the-face-of"],["כׇל־הָאָרֶץ","all-the-earth"],["כִּי","because"],["כׇל־הַגֹּנֵב","all-the-one who steals"],["מִזֶּה","than-this"],["כָּמוֹהָ","like-her"],["נִקָּה","he will be purged"],["וְכׇל־הַנִּשְׁבָּע","and-all-the-one who swears an oath"],["מִזֶּה","than-this"],["כָּמוֹהָ","like-her"],["נִקָּה","he will be purged"],["׃",""]] },
  { num:"ד", words:[["הוֹצֵאתִיהָ","I will send forth-it"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["וּבָאָה","and-comes"],["אֶל־בֵּית","to-the-house-of"],["הַגַּנָּב","the-thief"],["וְאֶל־בֵּית","and-house-of"],["הַנִּשְׁבָּע","the-one who swears an oath"],["בִּשְׁמִי","My-name"],["לַשָּׁקֶר","to-the-falsehood"],["וְלָנֶה","and-it will lodge"],["בְּתוֹךְ","among"],["בֵּיתוֹ","his-house"],["וְכִלַּתּוּ","and-it will destroy-it"],["וְאֶת־עֵצָיו","and-[ACC]-wood-its"],["וְאֶת־אֲבָנָיו","and-[ACC]-stones-its"],["׃",""]] },
  { num:"ה", words:[["וַיֵּצֵא","and-went-out"],["הַמַּלְאָךְ","the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["שָׂא","lift-up"],["נָא","I-pray"],["עֵינֶיךָ","your-eyes"],["וּרְאֵה","and-behold"],["מָה","what"],["הַיּוֹצֵאת","the-which-is about to go forth"],["הַזֹּאת","is-this"],["׃",""]] },
  { num:"ו", words:[["וָאֹמַר","and-I-said"],["מַה־הִיא","what-it-is"],["וַיֹּאמֶר","and-said"],["זֹאת","this"],["הָאֵיפָה","the-an-ephah"],["הַיּוֹצֵאת","the-which-is about to go forth"],["וַיֹּאמֶר","and-said"],["זֹאת","this"],["עֵינָם","their-eye"],["בְּכׇל־הָאָרֶץ","in-all-the-land"],["׃",""]] },
  { num:"ז", words:[["וְהִנֵּה","and-behold"],["כִּכַּר","the valley of"],["עֹפֶרֶת","lead"],["נִשֵּׂאת","really"],["וְזֹאת","and-this"],["אִשָּׁה","a-woman"],["אַחַת","one"],["יוֹשֶׁבֶת","O-inhabitant-of"],["בְּתוֹךְ","among"],["הָאֵיפָה","the-an-ephah"],["׃",""]] },
  { num:"ח", words:[["וַיֹּאמֶר","and-said"],["זֹאת","this"],["הָרִשְׁעָה","the-wickedness"],["וַיַּשְׁלֵךְ","and-he-cast"],["אֹתָהּ","it"],["אֶל־תּוֹךְ","down-into"],["הָאֵיפָה","the-an-ephah"],["וַיַּשְׁלֵךְ","and-he-cast"],["אֶת־אֶבֶן","[ACC]-stone"],["הָעוֹפֶרֶת","the-lead"],["אֶל־פִּיהָ","to-mouth-its"],["׃",""]] },
  { num:"ט", words:[["וָאֶשָּׂא","and-I-took-up"],["עֵינַי","my-eyes"],["וָאֵרֶא","and-I-saw"],["וְהִנֵּה","and-behold"],["שְׁתַּיִם","two"],["נָשִׁים","women"],["יוֹצְאוֹת","were going forth"],["וְרוּחַ","and-spirit-of"],["בְּכַנְפֵיהֶם","with-wings-their"],["וְלָהֵנָּה","and-belonged to-them"],["כְנָפַיִם","wings"],["כְּכַנְפֵי","like-the wings of"],["הַחֲסִידָה","the-stork"],["וַתִּשֶּׂאנָה","and-they raised"],["אֶת־הָאֵיפָה","[ACC]-the-an-ephah"],["בֵּין","among"],["הָאָרֶץ","the-earth"],["וּבֵין","and-between"],["הַשָּׁמָיִם","the-heavens"],["׃",""]] },
  { num:"י", words:[["וָאֹמַר","and-I-said"],["אֶל־הַמַּלְאָךְ","to-the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["אָנָה","whither"],["הֵמָּה","they-are"],["מוֹלִכוֹת","taking"],["אֶת־הָאֵיפָה","[ACC]-the-an-ephah"],["׃",""]] },
  { num:"יא", words:[["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["לִבְנוֹת־לָהֿ","white-for-it"],["בַיִת","house"],["בְּאֶרֶץ","in-land-of"],["שִׁנְעָר","Shinar"],["וְהוּכַן","and-it will be established"],["וְהֻנִּיחָה","and-it will be placed"],["שָּׁם","there"],["עַל־מְכֻנָתָהּ","upon-on own stand-its"],["׃",""]] },
];
renderVerseSet(zec_ch5Verses, 'zec-ch5-verses');

var zec_ch6Verses = [
  { num:"א", words:[["וָאָשֻׁב","and-I returned"],["וָאֶשָּׂא","and-I-took-up"],["עֵינַי","my-eyes"],["וָאֶרְאֶה","and-I-saw"],["וְהִנֵּה","and-behold"],["אַרְבַּע","four"],["מַרְכָּבוֹת","Marcaboth"],["יֹצְאוֹת","coming out"],["מִבֵּין","from-between"],["שְׁנֵי","two"],["הֶהָרִים","the-mountains"],["וְהֶהָרִים","and-the-mountains"],["הָרֵי","the mountains of"],["נְחֹשֶׁת","brass"],["׃",""]] },
  { num:"ב", words:[["בַּמֶּרְכָּבָה","in the-chariot"],["הָרִאשֹׁנָה","the-first"],["סוּסִים","horses"],["אֲדֻמִּים","red"],["וּבַמֶּרְכָּבָה","and-were with the-chariot"],["הַשֵּׁנִית","the-second"],["סוּסִים","horses"],["שְׁחֹרִים","black"],["׃",""]] },
  { num:"ג", words:[["וּבַמֶּרְכָּבָה","and-were with the-chariot"],["הַשְּׁלִשִׁית","the-third"],["סוּסִים","horses"],["לְבָנִים","white"],["וּבַמֶּרְכָּבָה","and-were with the-chariot"],["הָרְבִעִית","the-fourth"],["סוּסִים","horses"],["בְּרֻדִּים","dappled"],["אֲמֻצִּים","strong"],["׃",""]] },
  { num:"ד", words:[["וָאַעַן","and-I-answered"],["וָאֹמַר","and-I-said"],["אֶל־הַמַּלְאָךְ","to-the-angel"],["הַדֹּבֵר","the-who-spoke"],["בִּי","against-me"],["מָה־אֵלֶּה","what-these"],["אֲדֹנִי","my-Lord"],["׃",""]] },
  { num:"ה", words:[["וַיַּעַן","and-he-answered"],["הַמַּלְאָךְ","the-angel"],["וַיֹּאמֶר","and-said"],["אֵלָי","unto-me"],["אֵלֶּה","these"],["אַרְבַּע","four"],["רוּחוֹת","spirits-of"],["הַשָּׁמַיִם","the-heavens"],["יוֹצְאוֹת","were going forth"],["מֵהִתְיַצֵּב","from-standing"],["עַל־אֲדוֹן","upon-the-master-of"],["כׇּל־הָאָרֶץ","all-the-earth"],["׃",""]] },
  { num:"ו", words:[["אֲשֶׁר־בָּהּ","whose-in-it(f)"],["הַסּוּסִים","the-horses"],["הַשְּׁחֹרִים","the-black"],["יֹצְאִים","departed"],["אֶל־אֶרֶץ","to-land-of"],["צָפוֹן","the-north"],["וְהַלְּבָנִים","and-the-white horses"],["יָצְאוּ","went-forth"],["אֶל־אַחֲרֵיהֶם","to-after-them"],["וְהַבְּרֻדִּים","and-the-dappled horses"],["יָצְאוּ","went-forth"],["אֶל־אֶרֶץ","to-land-of"],["הַתֵּימָן","the-south"],["׃",""]] },
  { num:"ז", words:[["וְהָאֲמֻצִּים","and-the-strong horses"],["יָצְאוּ","went-forth"],["וַיְבַקְשׁוּ","and-desired-of-him"],["לָלֶכֶת","to-go"],["לְהִתְהַלֵּךְ","to-walk"],["בָּאָרֶץ","in-the-land"],["וַיֹּאמֶר","and-said"],["לְכוּ","go"],["הִתְהַלְּכוּ","they walked about"],["בָאָרֶץ","in-the-land"],["וַתִּתְהַלַּכְנָה","and-they went about"],["בָּאָרֶץ","in-the-land"],["׃",""]] },
  { num:"ח", words:[["וַיַּזְעֵק","and-he summoned"],["אֹתִי","me"],["וַיְדַבֵּר","and-he-spoke"],["אֵלַי","to-me"],["לֵאמֹר","saying"],["רְאֵה","behold"],["הַיּוֹצְאִים","the-going-out"],["אֶל־אֶרֶץ","to-land-of"],["צָפוֹן","the-north"],["הֵנִיחוּ","they have caused to rest"],["אֶת־רוּחִי","[ACC]-again"],["בְּאֶרֶץ","in-land-of"],["צָפוֹן","the-north"],["׃",""]] },
  { num:"ט", words:[["וַיְהִי","and-it-came-to-pass"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["אֵלַי","to-me"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"י", words:[["לָקוֹחַ","take"],["מֵאֵת","from"],["הַגּוֹלָה","the-exiles"],["מֵחֶלְדַּי","from-Heldai"],["וּמֵאֵת","and-from-with"],["טוֹבִיָּה","Tobiah"],["וּמֵאֵת","and-from-with"],["יְדַעְיָה","Jedaiah"],["וּבָאתָ","and-in-ACC"],["אַתָּה","you"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["וּבָאתָ","and-in-ACC"],["בֵּית","house-of"],["יֹאשִׁיָּה","Josiah"],["בֶן־צְפַנְיָה","Bn-Zephaniah"],["אֲשֶׁר־בָּאוּ","whose-came"],["מִבָּבֶל","from-Babylon"],["׃",""]] },
  { num:"יא", words:[["וְלָקַחְתָּ","and-you will take"],["כֶסֶף־וְזָהָב","silver/money-and-gold"],["וְעָשִׂיתָ","and-do"],["עֲטָרוֹת","Ataroth"],["וְשַׂמְתָּ","and-you will put"],["בְּרֹאשׁ","in-the-gall-of"],["יְהוֹשֻׁעַ","Joshua"],["בֶּן־יְהוֹצָדָק","son-of-Jehozadak"],["הַכֹּהֵן","the-priest"],["הַגָּדוֹל","the-great"],["׃",""]] },
  { num:"יב", words:[["וְאָמַרְתָּ","and-say"],["אֵלָיו","to-him"],["לֵאמֹר","saying"],["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["לֵאמֹר","saying"],["הִנֵּה־אִישׁ","behold-man-of"],["צֶמַח","the-branch-of"],["שְׁמוֹ","His-name"],["וּמִתַּחְתָּיו","and-from-under-him"],["יִצְמָח","was sprouting"],["וּבָנָה","and-he will rebuild"],["אֶת־הֵיכַל","[ACC]-the-temple-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"יג", words:[["וְהוּא","and-it"],["יִבְנֶה","he will build"],["אֶת־הֵיכַל","[ACC]-the-temple-of"],["יְהֹוָה","the-LORD"],["וְהוּא־יִשָּׂא","and-it-takes-away"],["הוֹד","splendor"],["וְיָשַׁב","and-dwelt/sat"],["וּמָשַׁל","and-he will have dominion"],["עַל־כִּסְאוֹ","upon-His-throne"],["וְהָיָה","and-be"],["כֹהֵן","their-high-priest"],["עַל־כִּסְאוֹ","upon-His-throne"],["וַעֲצַת","and-the-plan-of"],["שָׁלוֹם","peace"],["תִּהְיֶה","shall-be"],["בֵּין","among"],["שְׁנֵיהֶם","the-two"],["׃",""]] },
  { num:"יד", words:[["וְהָעֲטָרֹת","and-the-crown"],["תִּהְיֶה","shall-be"],["לְחֵלֶם","to-Helem"],["וּלְטוֹבִיָּה","and-to-Tobiah"],["וְלִידַעְיָה","and-to-Jedaiah"],["וּלְחֵן","and-to-Hen"],["בֶּן־צְפַנְיָה","son-of-Zephaniah"],["לְזִכָּרוֹן","in-remembrance"],["בְּהֵיכַל","in-the temple of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"טו", words:[["וּרְחוֹקִים","and-distant ones"],["יָבֹאוּ","come"],["וּבָנוּ","and-against-us"],["בְּהֵיכַל","in-the temple of"],["יְהֹוָה","the-LORD"],["וִידַעְתֶּם","and-you-shall-know"],["כִּי־יְהֹוָה","for-the-LORD"],["צְבָאוֹת","of-Hosts"],["שְׁלָחַנִי","sent-me"],["אֲלֵיכֶם","unto-you"],["וְהָיָה","and-be"],["אִם־שָׁמוֹעַ","[compound]-He-will"],["תִּשְׁמְעוּן","you will hear-!"],["בְּקוֹל","the-voice-of"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיכֶם","your-God"],["׃",""]] },
];
renderVerseSet(zec_ch6Verses, 'zec-ch6-verses');

var zec_ch7Verses = [
  { num:"א", words:[["וַיְהִי","and-it-came-to-pass"],["בִּשְׁנַת","in-year-of"],["אַרְבַּע","four"],["לְדָרְיָוֶשׁ","to-Darius"],["הַמֶּלֶךְ","the-king"],["הָיָה","was"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["אֶל־זְכַרְיָה","to-Zechariah"],["בְּאַרְבָּעָה","in-four"],["לַחֹדֶשׁ","of-the-month"],["הַתְּשִׁעִי","the-ninth"],["בְּכִסְלֵו","in-Kislev"],["׃",""]] },
  { num:"ב", words:[["וַיִּשְׁלַח","and-he-sent"],["בֵּית־אֵל","Bethel"],["שַׂרְאֶצֶר","Sharezer"],["וְרֶגֶם","and-Regem-"],["מֶלֶךְ","king-of"],["וַאֲנָשָׁיו","and-his-men"],["לְחַלּוֹת","to-entreat"],["אֶת־פְּנֵי","ACC-face-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ג", words:[["לֵאמֹר","saying"],["אֶל־הַכֹּהֲנִים","to-the-priests"],["אֲשֶׁר","which"],["לְבֵית־יְהֹוָה","to-house-of-the-LORD"],["צְבָאוֹת","of-Hosts"],["וְאֶל־הַנְּבִיאִים","and-the-prophets"],["לֵאמֹר","saying"],["הַאֶבְכֶּה","¿-will I weep"],["בַּחֹדֶשׁ","in-the-month"],["הַחֲמִשִׁי","the-fifth"],["הִנָּזֵר","will I consecrate myself?"],["כַּאֲשֶׁר","when/as"],["עָשִׂיתִי","I-made"],["זֶה","this"],["כַּמֶּה","the-how-many?"],["שָׁנִים","years"],["׃",""]] },
  { num:"ד", words:[["וַיְהִי","and-it-came-to-pass"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["צְבָאוֹת","of-Hosts"],["אֵלַי","to-me"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ה", words:[["אֱמֹר","say!"],["אֶל־כׇּל־עַם","to-all-people"],["הָאָרֶץ","the-earth"],["וְאֶל־הַכֹּהֲנִים","and-the-priests"],["לֵאמֹר","saying"],["כִּי־צַמְתֶּם","because-you fasted"],["וְסָפוֹד","and-you mourned"],["בַּחֲמִישִׁי","in the-fifth month"],["וּבַשְּׁבִיעִי","and-in the-seventh month"],["וְזֶה","and-this"],["שִׁבְעִים","seventy"],["שָׁנָה","year"],["הֲצוֹם","¿-really"],["צַמְתֻּנִי","did you fast for-me"],["אָנִי","I"],["׃",""]] },
  { num:"ו", words:[["וְכִי","and-that"],["תֹאכְלוּ","you must eat"],["וְכִי","and-that"],["תִשְׁתּוּ","you will drink"],["הֲלוֹא","art-not"],["אַתֶּם","you-are"],["הָאֹכְלִים","the-partake-of-it"],["וְאַתֶּם","and-will-you"],["הַשֹּׁתִים","the-drink-of-it"],["׃",""]] },
  { num:"ז", words:[["הֲלוֹא","art-not"],["אֶת־הַדְּבָרִים","[ACC]-the-words"],["אֲשֶׁר","which"],["קָרָא","called"],["יְהֹוָה","the-LORD"],["בְּיַד","in-hand-of"],["הַנְּבִיאִים","the-prophets"],["הָרִאשֹׁנִים","the-his-first"],["בִּהְיוֹת","while-was"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["יֹשֶׁבֶת","sat"],["וּשְׁלֵוָה","and-at ease"],["וְעָרֶיהָ","and-cities-its"],["סְבִיבֹתֶיהָ","was around-it"],["וְהַנֶּגֶב","and-the-Negev"],["וְהַשְּׁפֵלָה","and-the-Shephelah"],["יֹשֵׁב","who-dwell-in"],["׃",""]] },
  { num:"ח", words:[["וַיְהִי","and-it-came-to-pass"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["אֶל־זְכַרְיָה","to-Zechariah"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ט", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["לֵאמֹר","saying"],["מִשְׁפַּט","judgment"],["אֱמֶת","truth"],["שְׁפֹטוּ","judge"],["וְחֶסֶד","and-lovingkindness-of"],["וְרַחֲמִים","and-compassion"],["עֲשׂוּ","do"],["אִישׁ","man-of"],["אֶת־אָחִיו","[ACC] another"],["׃",""]] },
  { num:"י", words:[["וְאַלְמָנָה","and-a widow"],["וְיָתוֹם","and-a fatherless one"],["גֵּר","am a sojourner"],["וְעָנִי","and-afflicted"],["אַל־תַּעֲשֹׁקוּ","do-not-you oppress"],["וְרָעַת","and-the harm of"],["אִישׁ","man-of"],["אָחִיו","another"],["אַל־תַּחְשְׁבוּ","you-need-not-suppose"],["בִּלְבַבְכֶם","in-your-hearts"],["׃",""]] },
  { num:"יא", words:[["וַיְמָאֲנוּ","and-refused-they"],["לְהַקְשִׁיב","to-give-heed"],["וַיִּתְּנוּ","and-they-gave"],["כָתֵף","a shoulder"],["סֹרָרֶת","stubborn"],["וְאׇזְנֵיהֶם","and-the ears of-them"],["הִכְבִּידוּ","were-laden"],["מִשְּׁמוֹעַ","for-hearing"],["׃",""]] },
  { num:"יב", words:[["וְלִבָּם","having-their-hearts"],["שָׂמוּ","employed"],["שָׁמִיר","briars"],["מִשְּׁמוֹעַ","for-hearing"],["אֶת־הַתּוֹרָה","[ACC]-the-law"],["וְאֶת־הַדְּבָרִים","and-[ACC]-the-words"],["אֲשֶׁר","which"],["שָׁלַח","sent"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["בְּרוּחוֹ","in-His-Spirit"],["בְּיַד","in-hand-of"],["הַנְּבִיאִים","the-prophets"],["הָרִאשֹׁנִים","the-his-first"],["וַיְהִי","and-it-came-to-pass"],["קֶצֶף","wrath"],["גָּדוֹל","great"],["מֵאֵת","from"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"יג", words:[["וַיְהִי","and-it-came-to-pass"],["כַאֲשֶׁר־קָרָא","as/when-called"],["וְלֹא","and-not"],["שָׁמֵעוּ","they listened"],["כֵּן","thus"],["יִקְרְאוּ","they-shall-call"],["וְלֹא","and-not"],["אֶשְׁמָע","I heard"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"יד", words:[["וְאֵסָעֲרֵם","and-I will storm away-them"],["עַל","upon"],["כׇּל־הַגּוֹיִם","all-the-nations"],["אֲשֶׁר","which"],["לֹא־יְדָעוּם","not-they had known-them"],["וְהָאָרֶץ","and-the-earth"],["נָשַׁמָּה","it has been made desolate"],["אַחֲרֵיהֶם","after-them"],["מֵעֹבֵר","from-one who passes by"],["וּמִשָּׁב","and-from-one who returns"],["וַיָּשִׂימוּ","and-began-to-put"],["אֶרֶץ־חֶמְדָּה","land-of-of-delight"],["לְשַׁמָּה","desolate"],["׃",""]] },
];
renderVerseSet(zec_ch7Verses, 'zec-ch7-verses');

var zec_ch8Verses = [
  { num:"א", words:[["וַיְהִי","and-it-came-to-pass"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["צְבָאוֹת","of-Hosts"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ב", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["קִנֵּאתִי","I have been zealous"],["לְצִיּוֹן","unto-Zion"],["קִנְאָה","jealousy"],["גְדוֹלָה","great"],["וְחֵמָה","and-wrath"],["גְדוֹלָה","great"],["קִנֵּאתִי","I have been zealous"],["לָהּ","it"],["׃",""]] },
  { num:"ג", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["שַׁבְתִּי","I-have-repented"],["אֶל־צִיּוֹן","to/unto-Zion"],["וְשָׁכַנְתִּי","and-I will dwell"],["בְּתוֹךְ","among"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["וְנִקְרְאָה","and-she was summoned"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["עִיר","city-of"],["הָאֱמֶת","the-true"],["וְהַר־יְהֹוָה","and-the mountain of-the-LORD"],["צְבָאוֹת","of-Hosts"],["הַר","mountain"],["הַקֹּדֶשׁ","the-Holy"],["׃",""]] },
  { num:"ד", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["עֹד","again"],["יֵשְׁבוּ","dwell-shall"],["זְקֵנִים","elders"],["וּזְקֵנוֹת","and-old women"],["בִּרְחֹבוֹת","in-the open places of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["וְאִישׁ","and-the-man-of"],["מִשְׁעַנְתּוֹ","staff-his"],["בְּיָדוֹ","in-his-hand"],["מֵרֹב","from-multitude-of"],["יָמִים","days"],["׃",""]] },
  { num:"ה", words:[["וּרְחֹבוֹת","and-the open places of"],["הָעִיר","the-city"],["יִמָּלְאוּ","may-be-fulfilled"],["יְלָדִים","little-children"],["וִילָדוֹת","and-girls"],["מְשַׂחֲקִים","were playing"],["בִּרְחֹבֹתֶיהָ","in-open places-its"],["׃",""]] },
  { num:"ו", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["כִּי","because"],["יִפָּלֵא","that"],["בְּעֵינֵי","in-the-eyes-of"],["שְׁאֵרִית","remnant-of"],["הָעָם","the-people"],["הַזֶּה","this"],["בַּיָּמִים","in-the-days"],["הָהֵם","those"],["גַּם־בְּעֵינַי","also-in-my-eyes"],["יִפָּלֵא","that"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"ז", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["הִנְנִי","behold-I"],["מוֹשִׁיעַ","Savior"],["אֶת־עַמִּי","[ACC]-my-people"],["מֵאֶרֶץ","from-land-of"],["מִזְרָח","east"],["וּמֵאֶרֶץ","and-from-land-of"],["מְבוֹא","from-the-coming-of"],["הַשָּׁמֶשׁ","the-sun"],["׃",""]] },
  { num:"ח", words:[["וְהֵבֵאתִי","and-have-brought"],["אֹתָם","them"],["וְשָׁכְנוּ","and-shall-dwell"],["בְּתוֹךְ","among"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["וְהָיוּ־לִי","then-they-shall-be-to-me"],["לְעָם","people"],["וַאֲנִי","and-I"],["אֶהְיֶה","I-may-be"],["לָהֶם","to-them"],["לֵאלֹהִים","God"],["בֶּאֱמֶת","in-truth"],["וּבִצְדָקָה","and-with-righteousness"],["׃",""]] },
  { num:"ט", words:[["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["תֶּחֱזַקְנָה","they will be strong"],["יְדֵיכֶם","your-hands"],["הַשֹּׁמְעִים","the-you-who-hear"],["בַּיָּמִים","in-the-days"],["הָאֵלֶּה","these"],["אֵת","[ACC]"],["הַדְּבָרִים","the-things"],["הָאֵלֶּה","these"],["מִפִּי","from-mouth-of"],["הַנְּבִיאִים","the-prophets"],["אֲשֶׁר","which"],["בְּיוֹם","in-day-of"],["יֻסַּד","it was founded"],["בֵּית־יְהֹוָה","the-house-of-the-LORD"],["צְבָאוֹת","of-Hosts"],["הַהֵיכָל","the-temple"],["לְהִבָּנוֹת","to-be-laid"],["׃",""]] },
  { num:"י", words:[["כִּי","because"],["לִפְנֵי","before"],["הַיָּמִים","the-days"],["הָהֵם","those"],["שְׂכַר","reward"],["הָאָדָם","the-man"],["לֹא","not"],["נִהְיָה","has it occurred"],["וּשְׂכַר","and-the wages of"],["הַבְּהֵמָה","the-livestock"],["אֵינֶנָּה","is-not"],["וְלַיּוֹצֵא","and-belonged to the-one who went out"],["וְלַבָּא","and-to the-one who came in"],["אֵין־שָׁלוֹם","there-is-no-peace"],["מִן־הַצָּר","from-the-narrow/enemy"],["וַאֲשַׁלַּח","so-I may send"],["אֶת־כׇּל־הָאָדָם","[ACC]-all-the-man"],["אִישׁ","man-of"],["בְּרֵעֵהוּ","with-another"],["׃",""]] },
  { num:"יא", words:[["וְעַתָּה","and-now"],["לֹא","not"],["כַיָּמִים","like the-days"],["הָרִאשֹׁנִים","the-his-first"],["אֲנִי","I"],["לִשְׁאֵרִית","for-remnant-of"],["הָעָם","the-people"],["הַזֶּה","this"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"יב", words:[["כִּי־זֶרַע","because-seed"],["הַשָּׁלוֹם","the-peace"],["הַגֶּפֶן","the-vine"],["תִּתֵּן","you-shall-give"],["פִּרְיָהּ","its-fruit"],["וְהָאָרֶץ","and-the-earth"],["תִּתֵּן","you-shall-give"],["אֶת־יְבוּלָהּ","[ACC]-produce-its"],["וְהַשָּׁמַיִם","and-the-heavens"],["יִתְּנוּ","they-should-impart"],["טַלָּם","dew-their"],["וְהִנְחַלְתִּי","and-I will give as an inheritance"],["אֶת־שְׁאֵרִית","[ACC]-remnant-of"],["הָעָם","the-people"],["הַזֶּה","this"],["אֶת־כׇּל־אֵלֶּה","[ACC]-all-these"],["׃",""]] },
  { num:"יג", words:[["וְהָיָה","and-be"],["כַּאֲשֶׁר","when/as"],["הֱיִיתֶם","because-you-have-been"],["קְלָלָה","a-curse"],["בַּגּוֹיִם","by-the-nations"],["בֵּית","house-of"],["יְהוּדָה","Judah"],["וּבֵית","and-house-of"],["יִשְׂרָאֵל","Israel"],["כֵּן","thus"],["אוֹשִׁיעַ","will-save"],["אֶתְכֶם","you"],["וִהְיִיתֶם","and-you-become"],["בְּרָכָה","a-blessing"],["אַל־תִּירָאוּ","fear-not"],["תֶּחֱזַקְנָה","they will be strong"],["יְדֵיכֶם","your-hands"],["׃",""]] },
  { num:"יד", words:[["כִּי","because"],["כֹה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["כַּאֲשֶׁר","when/as"],["זָמַמְתִּי","I planned"],["לְהָרַע","to-injure"],["לָכֶם","to-you"],["בְּהַקְצִיף","when-provoked to anger"],["אֲבֹתֵיכֶם","fathers-your"],["אֹתִי","me"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["וְלֹא","and-not"],["נִחָמְתִּי","I relented"],["׃",""]] },
  { num:"טו", words:[["כֵּן","thus"],["שַׁבְתִּי","I-have-repented"],["זָמַמְתִּי","I planned"],["בַּיָּמִים","in-the-days"],["הָאֵלֶּה","these"],["לְהֵיטִיב","to-do good"],["אֶת־יְרוּשָׁלַ͏ִם","[ACC]-Jerusalem"],["וְאֶת־בֵּית","and-[ACC]-house-of"],["יְהוּדָה","Judah"],["אַל־תִּירָאוּ","fear-not"],["׃",""]] },
  { num:"טז", words:[["אֵלֶּה","these"],["הַדְּבָרִים","the-things"],["אֲשֶׁר","which"],["תַּעֲשׂוּ","you-do"],["דַּבְּרוּ","speak"],["אֱמֶת","truth"],["אִישׁ","man-of"],["אֶת־רֵעֵהוּ","[ACC]-another"],["אֱמֶת","truth"],["וּמִשְׁפַּט","and-judgment"],["שָׁלוֹם","peace"],["שִׁפְטוּ","judge-you"],["בְּשַׁעֲרֵיכֶם","is in-gates-your"],["׃",""]] },
  { num:"יז", words:[["וְאִישׁ","and-the-man-of"],["אֶת־רָעַת","[ACC]-the evil of"],["רֵעֵהוּ","his-fellow"],["אַל־תַּחְשְׁבוּ","you-need-not-suppose"],["בִּלְבַבְכֶם","in-your-hearts"],["וּשְׁבֻעַת","and-an oath of"],["שֶׁקֶר","false"],["אַל־תֶּאֱהָבוּ","do-not-you love"],["כִּי","because"],["אֶת־כׇּל־אֵלֶּה","[ACC]-all-these"],["אֲשֶׁר","which"],["שָׂנֵאתִי","I hate"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"יח", words:[["וַיְהִי","and-it-came-to-pass"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["צְבָאוֹת","of-Hosts"],["אֵלַי","to-me"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"יט", words:[["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["צוֹם","fasting"],["הָרְבִיעִי","the-fourth"],["וְצוֹם","and-fasting"],["הַחֲמִישִׁי","the-fifth"],["וְצוֹם","and-fasting"],["הַשְּׁבִיעִי","the-seventh"],["וְצוֹם","and-fasting"],["הָעֲשִׂירִי","the-rich-my"],["יִהְיֶה","he-shall-be"],["לְבֵית־יְהוּדָה","to-house-of-Judah"],["לְשָׂשׂוֹן","to-rejoice"],["וּלְשִׂמְחָה","and-for-joy"],["וּלְמֹעֲדִים","and-appointed feasts"],["טוֹבִים","good"],["וְהָאֱמֶת","and-the-true"],["וְהַשָּׁלוֹם","and-the-peace"],["אֱהָבוּ","love"],["׃",""]] },
  { num:"כ", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["עֹד","again"],["אֲשֶׁר","which"],["יָבֹאוּ","come"],["עַמִּים","peoples"],["וְיֹשְׁבֵי","and-the inhabitants of"],["עָרִים","large-cities"],["רַבּוֹת","many"],["׃",""]] },
  { num:"כא", words:[["וְהָלְכוּ","and-they-shall-depart"],["יוֹשְׁבֵי","the-inhabitants-of"],["אַחַת","one"],["אֶל־אַחַת","to-one"],["לֵאמֹר","saying"],["נֵלְכָה","let-us-go"],["הָלוֹךְ","along"],["לְחַלּוֹת","to-entreat"],["אֶת־פְּנֵי","ACC-face-of"],["יְהֹוָה","the-LORD"],["וּלְבַקֵּשׁ","and-ask"],["אֶת־יְהֹוָה","[ACC]-the-LORD"],["צְבָאוֹת","of-Hosts"],["אֵלְכָה","I-will-go"],["גַּם־אָנִי","also-I"],["׃",""]] },
  { num:"כב", words:[["וּבָאוּ","and-it-comes"],["עַמִּים","peoples"],["רַבִּים","many"],["וְגוֹיִם","and-nations"],["עֲצוּמִים","mighty"],["לְבַקֵּשׁ","to-seek"],["אֶת־יְהֹוָה","[ACC]-the-LORD"],["צְבָאוֹת","of-Hosts"],["בִּירוּשָׁלָ͏ִם","is in-Jerusalem"],["וּלְחַלּוֹת","and-to-entreat"],["אֶת־פְּנֵי","ACC-face-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"כג", words:[["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["בַּיָּמִים","in-the-days"],["הָהֵמָּה","those"],["אֲשֶׁר","which"],["יַחֲזִיקוּ","they-hold-out"],["עֲשָׂרָה","ten"],["אֲנָשִׁים","men"],["מִכֹּל","of-all"],["לְשֹׁנוֹת","to-different"],["הַגּוֹיִם","the-nations"],["וְהֶחֱזִיקוּ","and-shall-take-hold"],["בִּכְנַף","on-the skirt of"],["אִישׁ","man-of"],["יְהוּדִי","Jew"],["לֵאמֹר","saying"],["נֵלְכָה","let-us-go"],["עִמָּכֶם","with-you"],["כִּי","because"],["שָׁמַעְנוּ","did-we-heed"],["אֱלֹהִים","God"],["עִמָּכֶם","with-you"],["׃",""]] },
];
renderVerseSet(zec_ch8Verses, 'zec-ch8-verses');

var zec_ch9Verses = [
  { num:"א", words:[["מַשָּׂא","the-burden-of"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["בְּאֶרֶץ","in-land-of"],["חַדְרָךְ","Hadrach"],["וְדַמֶּשֶׂק","and-Damascus"],["מְנֻחָתוֹ","his-rest"],["כִּי","because"],["לַיהֹוָה","to-Yahweh"],["עֵין","the-eye-of"],["אָדָם","man"],["וְכֹל","and-the-whole"],["שִׁבְטֵי","tribes-of"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"ב", words:[["וְגַם־חֲמָת","and-also-Hamath"],["תִּגְבׇּל־בָּהּ","which it borders-in-it(f)"],["צֹר","a flint"],["וְצִידוֹן","and-Sidon"],["כִּי","because"],["חָכְמָה","wisdom"],["מְאֹד","exceedingly"],["׃",""]] },
  { num:"ג", words:[["וַתִּבֶן","and-she built"],["צֹר","a flint"],["מָצוֹר","siege works"],["לָהּ","it"],["וַתִּצְבׇּר־כֶּסֶף","and-it heaped up-money"],["כֶּעָפָר","like the-dust"],["וְחָרוּץ","and-a moat"],["כְּטִיט","like-the mud of"],["חוּצוֹת","the-streets"],["׃",""]] },
  { num:"ד", words:[["הִנֵּה","behold"],["אֲדֹנָי","Lord"],["יוֹרִשֶׁנָּה","it will take possession of-it"],["וְהִכָּה","and-was-smitten"],["בַיָּם","in-the-sea"],["חֵילָהּ","wealth-its"],["וְהִיא","and-she-was"],["בָּאֵשׁ","by-fire"],["תֵּאָכֵל","it will be eaten"],["׃",""]] },
  { num:"ה", words:[["תֵּרֶא","you see"],["אַשְׁקְלוֹן","Ashkelon"],["וְתִירָא","so-it may be afraid"],["וְעַזָּה","and-Gaza"],["וְתָחִיל","so-it may be in anguish"],["מְאֹד","exceedingly"],["וְעֶקְרוֹן","and-Ekron"],["כִּי־הֹבִישׁ","because-he will be ashamed"],["מֶבָּטָהּ","object of confidence-its"],["וְאָבַד","and-lost"],["מֶלֶךְ","king-of"],["מֵעַזָּה","from-Gaza"],["וְאַשְׁקְלוֹן","and-Ashkelon"],["לֹא","not"],["תֵשֵׁב","you will dwell"],["׃",""]] },
  { num:"ו", words:[["וְיָשַׁב","and-dwelt/sat"],["מַמְזֵר","a bastard"],["בְּאַשְׁדּוֹד","in-Ashdod"],["וְהִכְרַתִּי","and-cut-off"],["גְּאוֹן","the-pride-of"],["פְּלִשְׁתִּים","Philistines"],["׃",""]] },
  { num:"ז", words:[["וַהֲסִרֹתִי","and-I will remove"],["דָמָיו","blood-its"],["מִפִּיו","from-his-mouth"],["וְשִׁקֻּצָיו","and-detestable things-its"],["מִבֵּין","from-between"],["שִׁנָּיו","teeth-its"],["וְנִשְׁאַר","and-it will be left"],["גַּם־הוּא","also-he"],["לֵאלֹהֵינוּ","of-our-God"],["וְהָיָה","and-be"],["כְּאַלֻּף","like-a chief"],["בִּיהוּדָה","through-Judah"],["וְעֶקְרוֹן","and-Ekron"],["כִּיבוּסִי","will be like-a Jebusite"],["׃",""]] },
  { num:"ח", words:[["וְחָנִיתִי","and-I will encamp"],["לְבֵיתִי","for-own household-my"],["מִצָּבָה","a guard"],["מֵעֹבֵר","from-one who passes by"],["וּמִשָּׁב","and-from-one who returns"],["וְלֹא־יַעֲבֹר","and-not-pass-away"],["עֲלֵיהֶם","against-them"],["עוֹד","any-more"],["נֹגֵשׂ","the-oppressor"],["כִּי","because"],["עַתָּה","now"],["רָאִיתִי","I-saw"],["בְעֵינָי","in-view-my"],["׃",""]] },
  { num:"ט", words:[["גִּילִי","rejoicing-my"],["מְאֹד","exceedingly"],["בַּת־צִיּוֹן","the-daughter-of-Zion"],["הָרִיעִי","the-shout for joy"],["בַּת","daughter-of"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["הִנֵּה","behold"],["מַלְכֵּךְ","king-your"],["יָבוֹא","shall-come"],["לָךְ","[compound]"],["צַדִּיק","righteous"],["וְנוֹשָׁע","and-victorious"],["הוּא","it-is"],["עָנִי","poor"],["וְרֹכֵב","and-the rider of"],["עַל־חֲמוֹר","upon-a-donkey"],["וְעַל־עַיִר","and-upon-a male donkey"],["בֶּן־אֲתֹנוֹת","son-of-female donkeys"],["׃",""]] },
  { num:"י", words:[["וְהִכְרַתִּי־רֶכֶב","and-cut-off-chariotry"],["מֵאֶפְרַיִם","of-Ephraim"],["וְסוּס","and-horses"],["מִירוּשָׁלַ͏ִם","were more than-Jerusalem"],["וְנִכְרְתָה","and-broken-off"],["קֶשֶׁת","a-bow"],["מִלְחָמָה","war"],["וְדִבֶּר","and-spoke"],["שָׁלוֹם","peace"],["לַגּוֹיִם","to-the-nations"],["וּמׇשְׁלוֹ","and-he will have dominion-his"],["מִיָּם","from-the-sea/west"],["עַד־יָם","until-the-sea"],["וּמִנָּהָר","and-from-the river"],["עַד־אַפְסֵי־אָרֶץ","until-the-ends-of-the-earth"],["׃",""]] },
  { num:"יא", words:[["גַּם־אַתְּ","also-ACC"],["בְּדַם־בְּרִיתֵךְ","in-blood-of-covenant-your"],["שִׁלַּחְתִּי","I have sent"],["אֲסִירַיִךְ","prisoners-your"],["מִבּוֹר","from-the Cistern of"],["אֵין","there-is-no"],["מַיִם","water"],["בּוֹ","against-him"],["׃",""]] },
  { num:"יב", words:[["שׁוּבוּ","return/repent"],["לְבִצָּרוֹן","to-the stronghold"],["אֲסִירֵי","the prisoners of"],["הַתִּקְוָה","the-hope"],["גַּם־הַיּוֹם","also-the-day"],["מַגִּיד","declare"],["מִשְׁנֶה","double"],["אָשִׁיב","recall"],["לָךְ","[compound]"],["׃",""]] },
  { num:"יג", words:[["כִּי־דָרַכְתִּי","because-I will bend"],["לִי","to-me"],["יְהוּדָה","Judah"],["קֶשֶׁת","a-bow"],["מִלֵּאתִי","I filled"],["אֶפְרַיִם","Ephraim"],["וְעוֹרַרְתִּי","and-I will rouse"],["בָנַיִךְ","your-sons"],["צִיּוֹן","Zion"],["עַל־בָּנַיִךְ","upon-your-children"],["יָוָן","Javan"],["וְשַׂמְתִּיךְ","and-I will make-you"],["כְּחֶרֶב","as-sharp"],["גִּבּוֹר","mighty"],["׃",""]] },
  { num:"יד", words:[["וַיהֹוָה","and-Yahweh"],["עֲלֵיהֶם","against-them"],["יֵרָאֶה","He-shall-manifest-Himself"],["וְיָצָא","and-shall-come-forth"],["כַבָּרָק","like-the-lightning"],["חִצּוֹ","arrow-his"],["וַאדֹנָי","and-my-Lord"],["יֱהֹוִה","Yahweh"],["בַּשּׁוֹפָר","with-the-a-shofar"],["יִתְקָע","he will give a blast"],["וְהָלַךְ","and-go"],["בְּסַעֲרוֹת","in-the storm winds of"],["תֵּימָן","Teman"],["׃",""]] },
  { num:"טו", words:[["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["יָגֵן","he will defend"],["עֲלֵיהֶם","against-them"],["וְאָכְלוּ","and-did-partake"],["וְכָבְשׁוּ","and-they will subdue"],["אַבְנֵי־קֶלַע","stones-of-a sling"],["וְשָׁתוּ","and-they-have-drunk"],["הָמוּ","they were in a tumult"],["כְּמוֹ־יָיִן","as/like-wine"],["וּמָלְאוּ","and-were-fulfilled"],["כַּמִּזְרָק","like-the-bowl"],["כְּזָוִיּוֹת","like-the corners of"],["מִזְבֵּחַ","an altar"],["׃",""]] },
  { num:"טז", words:[["וְהוֹשִׁיעָם","and-he delivered-them"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיהֶם","their-God"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["כְּצֹאן","like-sheep of"],["עַמּוֹ","his-people"],["כִּי","because"],["אַבְנֵי־נֵזֶר","stones-of-the crown of"],["מִתְנוֹסְסוֹת","will display themselves"],["עַל־אַדְמָתוֹ","upon-land-his"],["׃",""]] },
  { num:"יז", words:[["כִּי","because"],["מַה־טּוּבוֹ","what-will be goodness-its"],["וּמַה־יׇּפְיוֹ","and-what?-will be beauty-its"],["דָּגָן","grain"],["בַּחוּרִים","Bahurim"],["וְתִירוֹשׁ","and-new wine"],["יְנוֹבֵב","it will cause to thrive"],["בְּתֻלוֹת","young women"],["׃",""]] },
];
renderVerseSet(zec_ch9Verses, 'zec-ch9-verses');

var zec_ch10Verses = [
  { num:"א", words:[["שַׁאֲלוּ","they-asked"],["מֵיְהֹוָה","from-the-LORD"],["מָטָר","rain"],["בְּעֵת","in-time"],["מַלְקוֹשׁ","spring rain"],["יְהֹוָה","the-LORD"],["עֹשֶׂה","do"],["חֲזִיזִים","thunder-clouds"],["וּמְטַר־גֶּשֶׁם","and-rain of-rain"],["יִתֵּן","shall-give"],["לָהֶם","to-them"],["לְאִישׁ","for-a-man"],["עֵשֶׂב","herb"],["בַּשָּׂדֶה","in-the-field"],["׃",""]] },
  { num:"ב", words:[["כִּי","because"],["הַתְּרָפִים","the-teraphim"],["דִּבְּרוּ־אָוֶן","have-spoken-iniquity"],["וְהַקּוֹסְמִים","and-the-diviners"],["חָזוּ","they-beheld"],["שֶׁקֶר","false"],["וַחֲלֹמוֹת","and-dreams"],["הַשָּׁוְא","the-vanity"],["יְדַבֵּרוּ","will they speak"],["הֶבֶל","the-vanities"],["יְנַחֵמוּן","they comfort-!"],["עַל־כֵּן","therefore"],["נָסְעוּ","did-they-progress"],["כְמוֹ־צֹאן","like-flocks"],["יַעֲנוּ","shall-speak"],["כִּי־אֵין","because-there-is-no"],["רֹעֶה","shepherd"],["׃",""]] },
  { num:"ג", words:[["עַל־הָרֹעִים","upon-the-shepherds"],["חָרָה","burned"],["אַפִּי","My-anger"],["וְעַל־הָעַתּוּדִים","and-upon-the-leaders"],["אֶפְקוֹד","I will visit judgment"],["כִּי־פָקַד","that-He-visited"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["אֶת־עֶדְרוֹ","[ACC]-dig-about"],["אֶת־בֵּית","[ACC]-house-of"],["יְהוּדָה","Judah"],["וְשָׂם","and-makes"],["אוֹתָם","them"],["כְּסוּס","like-a horse"],["הוֹדוֹ","splendor-his"],["בַּמִּלְחָמָה","in-the-battle"],["׃",""]] },
  { num:"ד", words:[["מִמֶּנּוּ","from-him"],["פִנָּה","a corner"],["מִמֶּנּוּ","from-him"],["יָתֵד","a tent peg"],["מִמֶּנּוּ","from-him"],["קֶשֶׁת","a-bow"],["מִלְחָמָה","war"],["מִמֶּנּוּ","from-him"],["יֵצֵא","he-go-forth"],["כׇל־נוֹגֵשׂ","all-a driver"],["יַחְדָּו","together"],["׃",""]] },
  { num:"ה", words:[["וְהָיוּ","then-they-shall-be"],["כְגִבֹּרִים","like-warriors"],["בּוֹסִים","treading down"],["בְּטִיט","in-the mud of"],["חוּצוֹת","the-streets"],["בַּמִּלְחָמָה","in-the-battle"],["וְנִלְחֲמוּ","and-they will fight"],["כִּי","because"],["יְהֹוָה","the-LORD"],["עִמָּם","with-them"],["וְהֹבִישׁוּ","and-they will put to shame"],["רֹכְבֵי","O riders of"],["סוּסִים","horses"],["׃",""]] },
  { num:"ו", words:[["וְגִבַּרְתִּי","and-I will make strong"],["אֶת־בֵּית","[ACC]-house-of"],["יְהוּדָה","Judah"],["וְאֶת־בֵּית","and-[ACC]-house-of"],["יוֹסֵף","Joseph"],["אוֹשִׁיעַ","will-save"],["וְהוֹשְׁבוֹתִים","and-I will restore-them"],["כִּי","because"],["רִחַמְתִּים","I have compassion on-them"],["וְהָיוּ","then-they-shall-be"],["כַּאֲשֶׁר","when/as"],["לֹא־זְנַחְתִּים","not-I had rejected-them"],["כִּי","because"],["אֲנִי","I"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיהֶם","their-God"],["וְאֶעֱנֵם","and-I will answer-them"],["׃",""]] },
  { num:"ז", words:[["וְהָיוּ","then-they-shall-be"],["כְגִבּוֹר","like-a warrior"],["אֶפְרַיִם","Ephraim"],["וְשָׂמַח","and-he will be glad"],["לִבָּם","their-hearts"],["כְּמוֹ־יָיִן","as/like-wine"],["וּבְנֵיהֶם","and-their-children"],["יִרְאוּ","shall-see"],["וְשָׂמֵחוּ","and-they will be glad"],["יָגֵל","may it rejoice"],["לִבָּם","their-hearts"],["בַּיהֹוָה","is in-Yahweh"],["׃",""]] },
  { num:"ח", words:[["אֶשְׁרְקָה","I will whistle"],["לָהֶם","to-them"],["וַאֲקַבְּצֵם","and-I will gather-them"],["כִּי","because"],["פְדִיתִים","I have redeemed-them"],["וְרָבוּ","and-they-shall-contend"],["כְּמוֹ","as/like"],["רָבוּ","they-had-multiplied"],["׃",""]] },
  { num:"ט", words:[["וְאֶזְרָעֵם","and-I will sow-them"],["בָּעַמִּים","among the-peoples"],["וּבַמֶּרְחַקִּים","and-in the-distant places"],["יִזְכְּרוּנִי","they-remember-Me"],["וְחָיוּ","and-they will live"],["אֶת־בְּנֵיהֶם","[ACC]-their-children"],["וָשָׁבוּ","and-they will return"],["׃",""]] },
  { num:"י", words:[["מֵאֶרֶץ","from-land-of"],["מִצְרַיִם","Egypt"],["וּמֵאַשּׁוּר","and-from-Assyria"],["אֲקַבְּצֵם","I-gather-them"],["וְאֶל־אֶרֶץ","and-unto-the-earth"],["גִּלְעָד","Gilead"],["וּלְבָנוֹן","and-Lebanon"],["אֲבִיאֵם","I will bring-them"],["וְלֹא","and-not"],["יִמָּצֵא","found"],["לָהֶם","to-them"],["׃",""]] },
  { num:"יא", words:[["וְעָבַר","generation"],["בַּיָּם","in-the-sea"],["צָרָה","affliction"],["וְהִכָּה","and-was-smitten"],["בַיָּם","in-the-sea"],["גַּלִּים","heaps"],["וְהֹבִישׁוּ","and-they will put to shame"],["כֹּל","all"],["מְצוּלוֹת","depths-of"],["יְאֹר","the River"],["וְהוּרַד","and-it was taken down"],["גְּאוֹן","the-pride-of"],["אַשּׁוּר","Assyria"],["וְשֵׁבֶט","and-a rod"],["מִצְרַיִם","Egypt"],["יָסוּר","shall-be-taken-away"],["׃",""]] },
  { num:"יב", words:[["וְגִבַּרְתִּים","and-I will make strong-them"],["בַּיהֹוָה","is in-Yahweh"],["וּבִשְׁמוֹ","and-in-his-name"],["יִתְהַלָּכוּ","they went about"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["׃",""]] },
];
renderVerseSet(zec_ch10Verses, 'zec-ch10-verses');

var zec_ch11Verses = [
  { num:"א", words:[["פְּתַח","open"],["לְבָנוֹן","Lebanon"],["דְּלָתֶיךָ","doors-your"],["וְתֹאכַל","and-let it consume"],["אֵשׁ","fire"],["בַּאֲרָזֶיךָ","cedars-your"],["׃",""]] },
  { num:"ב", words:[["הֵילֵל","O-Lucifer"],["בְּרוֹשׁ","cypresses"],["כִּי־נָפַל","that-fell"],["אֶרֶז","cedar"],["אֲשֶׁר","which"],["אַדִּרִים","majestic trees"],["שֻׁדָּדוּ","they have been devastated"],["הֵילִילוּ","howl"],["אַלּוֹנֵי","the oaks of"],["בָשָׁן","Bashan"],["כִּי","because"],["יָרַד","came-down"],["יַעַר","Ir"],["[הַבָּצִיר]","of the-vintage"],["׃",""]] },
  { num:"ג", words:[["קוֹל","the-voice-of"],["יִלְלַת","wailing-of"],["הָרֹעִים","the-shepherds"],["כִּי","because"],["שֻׁדְּדָה","it has been devastated"],["אַדַּרְתָּם","splendor-their"],["קוֹל","the-voice-of"],["שַׁאֲגַת","the roaring of"],["כְּפִירִים","young lions"],["כִּי","because"],["שֻׁדַּד","which it was devastated"],["גְּאוֹן","the-pride-of"],["הַיַּרְדֵּן","the-Jordan"],["׃",""]] },
  { num:"ד", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["אֱלֹהָי","my-God"],["רְעֵה","shepherd"],["אֶת־צֹאן","[ACC]-flocks"],["הַהֲרֵגָה","slaughter"],["׃",""]] },
  { num:"ה", words:[["אֲשֶׁר","which"],["קֹנֵיהֶן","those who buy-them"],["יַהַרְגֻן","they will kill-them"],["וְלֹא","and-not"],["יֶאְשָׁמוּ","they will be held guilty"],["וּמֹכְרֵיהֶן","and-those who sell-them"],["יֹאמַר","He-says"],["בָּרוּךְ","blessed"],["יְהֹוָה","the-LORD"],["וַאעְשִׁר","so-I may gain riches"],["וְרֹעֵיהֶם","and-shepherds-their"],["לֹא","not"],["יַחְמוֹל","it relents"],["עֲלֵיהֶן","them"],["׃",""]] },
  { num:"ו", words:[["כִּי","because"],["לֹא","not"],["אֶחְמוֹל","I will show pity"],["עוֹד","any-more"],["עַל־יֹשְׁבֵי","upon-inhabitants-of"],["הָאָרֶץ","the-earth"],["נְאֻם־יְהֹוָה","says-the-LORD"],["וְהִנֵּה","and-behold"],["אָנֹכִי","I"],["מַמְצִיא","am about to deliver"],["אֶת־הָאָדָם","[ACC]-the-man"],["אִישׁ","man-of"],["בְּיַד־רֵעֵהוּ","in-hand-of-his-fellow"],["וּבְיַד","and-by-the-hand-of"],["מַלְכּוֹ","king-its"],["וְכִתְּתוּ","and-they-shall-beat"],["אֶת־הָאָרֶץ","[ACC]-the-earth"],["וְלֹא","and-not"],["אַצִּיל","I will deliver it"],["מִיָּדָם","out-of-their-hands"],["׃",""]] },
  { num:"ז", words:[["וָאֶרְעֶה","and-I shepherded"],["אֶת־צֹאן","[ACC]-flocks"],["הַהֲרֵגָה","slaughter"],["לָכֵן","therefore"],["עֲנִיֵּי","from-the-poor-of"],["הַצֹּאן","the-flock"],["וָאֶקַּח־לִי","and-I-took-to-me"],["שְׁנֵי","two"],["מַקְלוֹת","staffs"],["לְאַחַד","to-one"],["קָרָאתִי","called"],["נֹעַם","the kindness of"],["וּלְאַחַד","and-one"],["קָרָאתִי","called"],["חֹבְלִים","Union"],["וָאֶרְעֶה","and-I shepherded"],["אֶת־הַצֹּאן","[ACC]-the-flock"],["׃",""]] },
  { num:"ח", words:[["וָאַכְחִד","and-I annihilated"],["אֶת־שְׁלֹשֶׁת","[ACC]-three-of"],["הָרֹעִים","the-shepherds"],["בְּיֶרַח","in-the month of"],["אֶחָד","one"],["וַתִּקְצַר","and-it became short"],["נַפְשִׁי","my-life"],["בָּהֶם","in-them"],["וְגַם־נַפְשָׁם","and-also-their-soul"],["בָּחֲלָה","it loathed"],["בִי","against-Me"],["׃",""]] },
  { num:"ט", words:[["וָאֹמַר","and-I-said"],["לֹא","not"],["אֶרְעֶה","I will tend"],["אֶתְכֶם","you"],["הַמֵּתָה","the-one which dies"],["תָמוּת","you-will-death"],["וְהַנִּכְחֶדֶת","and-the-one which is being destroyed"],["תִּכָּחֵד","let it be destroyed"],["וְהַנִּשְׁאָרוֹת","and-the-those-which survive"],["תֹּאכַלְנָה","will they eat"],["אִשָּׁה","a-woman"],["אֶת־בְּשַׂר","[ACC]-the-flesh"],["רְעוּתָהּ","neighbor fem-her"],["׃",""]] },
  { num:"י", words:[["וָאֶקַּח","and-I-took"],["אֶת־מַקְלִי","[ACC]-staff-my"],["אֶת־נֹעַם","[ACC]-the kindness of"],["וָאֶגְדַּע","and-I cut up"],["אֹתוֹ","him"],["לְהָפֵיר","to-break"],["אֶת־בְּרִיתִי","[ACC]-My-covenants"],["אֲשֶׁר","which"],["כָּרַתִּי","I-cut"],["אֶת־כׇּל־הָעַמִּים","[ACC]-all-the-people"],["׃",""]] },
  { num:"יא", words:[["וַתֻּפַר","and-it was broken"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["וַיֵּדְעוּ","and-they-knew"],["כֵן","thus"],["עֲנִיֵּי","from-the-poor-of"],["הַצֹּאן","the-flock"],["הַשֹּׁמְרִים","the-those-who watched"],["אֹתִי","me"],["כִּי","because"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["הוּא","it-is"],["׃",""]] },
  { num:"יב", words:[["וָאֹמַר","and-I-said"],["אֲלֵיהֶם","to-them"],["אִם־טוֹב","if-good"],["בְּעֵינֵיכֶם","in-view-your"],["הָבוּ","give"],["שְׂכָרִי","reward-my"],["וְאִם־לֹא","and-if-not"],["חֲדָלוּ","refrain"],["וַיִּשְׁקְלוּ","and-they weighed out"],["אֶת־שְׂכָרִי","[ACC]-reward-my"],["שְׁלֹשִׁים","thirty"],["כָּסֶף","silverlings"],["׃",""]] },
  { num:"יג", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["אֵלַי","to-me"],["הַשְׁלִיכֵהוּ","throw-it"],["אֶל־הַיּוֹצֵר","to-the-potter"],["אֶדֶר","a mantle"],["הַיְקָר","the-value"],["אֲשֶׁר","which"],["יָקַרְתִּי","I was valued"],["מֵעֲלֵיהֶם","from-off-them"],["וָאֶקְחָה","and-I took-!"],["שְׁלֹשִׁים","thirty"],["הַכֶּסֶף","the-money"],["וָאַשְׁלִיךְ","and-I threw"],["אֹתוֹ","him"],["בֵּית","house-of"],["יְהֹוָה","the-LORD"],["אֶל־הַיּוֹצֵר","to-the-potter"],["׃",""]] },
  { num:"יד", words:[["וָאֶגְדַּע","and-I cut up"],["אֶת־מַקְלִי","[ACC]-staff-my"],["הַשֵּׁנִי","the-second"],["אֵת","[ACC]"],["הַחֹבְלִים","the-Union"],["לְהָפֵר","to-break"],["אֶת־הָאַחֲוָה","[ACC]-the-brotherhood"],["בֵּין","among"],["יְהוּדָה","Judah"],["וּבֵין","and-between"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"טו", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["אֵלָי","unto-me"],["עוֹד","any-more"],["קַח־לְךָ","take-for-yourself"],["כְּלִי","the-ball"],["רֹעֶה","shepherd"],["אֱוִלִי","foolish"],["׃",""]] },
  { num:"טז", words:[["כִּי","because"],["הִנֵּה־אָנֹכִי","behold-I"],["מֵקִים","about to establish"],["רֹעֶה","shepherd"],["בָּאָרֶץ","in-the-land"],["הַנִּכְחָדוֹת","the-those-which are being destroyed"],["לֹא־יִפְקֹד","not-He-shall-visit"],["הַנַּעַר","the-child"],["לֹא־יְבַקֵּשׁ","not-he-should-look-for"],["וְהַנִּשְׁבֶּרֶת","and-the-broken horn"],["לֹא","not"],["יְרַפֵּא","he will have him healed"],["הַנִּצָּבָה","the-one which stands firm"],["לֹא","not"],["יְכַלְכֵּל","he maintains"],["וּבְשַׂר","and-the meat of"],["הַבְּרִיאָה","the-creation"],["יֹאכַל","he-shall-eat"],["וּפַרְסֵיהֶן","and-hooves-their"],["יְפָרֵק","he will tear off"],["׃",""]] },
  { num:"יז", words:[["הוֹי","O"],["רֹעִי","is shepherd-my"],["הָאֱלִיל","the-idols"],["עֹזְבִי","who abandons"],["הַצֹּאן","the-flock"],["חֶרֶב","the-sword-of"],["עַל־זְרוֹעוֹ","upon-His-arm"],["וְעַל־עֵין","and-upon-the-eye-of"],["יְמִינוֹ","right hand-his"],["זְרֹעוֹ","his-arm"],["יָבוֹשׁ","totally"],["תִּיבָשׁ","it will wither"],["וְעֵין","and-En"],["יְמִינוֹ","right hand-his"],["כָּהֹה","certainly"],["תִכְהֶה","it will grow dim"],["׃",""]] },
];
renderVerseSet(zec_ch11Verses, 'zec-ch11-verses');

var zec_ch12Verses = [
  { num:"א", words:[["מַשָּׂא","the-burden-of"],["דְבַר־יְהֹוָה","the-word-of-the-Lord"],["עַל־יִשְׂרָאֵל","upon-Israel"],["נְאֻם־יְהֹוָה","says-the-LORD"],["נֹטֶה","am holding out"],["שָׁמַיִם","the-heavens"],["וְיֹסֵד","and-he-shall-be-founded"],["אָרֶץ","the-earth"],["וְיֹצֵר","and-who formed"],["רוּחַ־אָדָם","spirit-of-man"],["בְּקִרְבּוֹ","in-the-midst-of-him"],["׃",""]] },
  { num:"ב", words:[["הִנֵּה","behold"],["אָנֹכִי","I"],["שָׂם","set"],["אֶת־יְרוּשָׁלַ͏ִם","[ACC]-Jerusalem"],["סַף־רַעַל","Saph-Rl"],["לְכׇל־הָעַמִּים","to-all-the-people"],["סָבִיב","round-about"],["וְגַם","and-also"],["עַל־יְהוּדָה","upon-Judah"],["יִהְיֶה","he-shall-be"],["בַמָּצוֹר","in-the-state of siege"],["עַל־יְרוּשָׁלָ͏ִם","upon-Jerusalem"],["׃",""]] },
  { num:"ג", words:[["וְהָיָה","and-be"],["בַיּוֹם־הַהוּא","in-that-the-day"],["אָשִׂים","shall-I-put"],["אֶת־יְרוּשָׁלַ͏ִם","[ACC]-Jerusalem"],["אֶבֶן","stone"],["מַעֲמָסָה","burden"],["לְכׇל־הָעַמִּים","to-all-the-people"],["כׇּל־עֹמְסֶיהָ","all-those who carry-it"],["שָׂרוֹט","severely"],["יִשָּׂרֵטוּ","they will injure themselves"],["וְנֶאֶסְפוּ","and-gathered"],["עָלֶיהָ","upon-it"],["כֹּל","all"],["גּוֹיֵי","nations-of"],["הָאָרֶץ","the-earth"],["׃",""]] },
  { num:"ד", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["נְאֻם־יְהֹוָה","says-the-LORD"],["אַכֶּה","I-will-smite"],["כׇל־סוּס","all-a horse"],["בַּתִּמָּהוֹן","with-the-bewilderment"],["וְרֹכְבוֹ","and-rider-its"],["בַּשִּׁגָּעוֹן","with-the-madness"],["וְעַל־בֵּית","and-upon-the-house-of"],["יְהוּדָה","Judah"],["אֶפְקַח","I will open"],["אֶת־עֵינַי","[ACC]-my-eyes"],["וְכֹל","and-the-whole"],["סוּס","a horse"],["הָעַמִּים","the-people"],["אַכֶּה","I-will-smite"],["בַּעִוָּרוֹן","with-blindness"],["׃",""]] },
  { num:"ה", words:[["וְאָמְרוּ","shall-say"],["אַלֻּפֵי","the chiefs of"],["יְהוּדָה","Judah"],["בְּלִבָּם","in-their-heart"],["אַמְצָה","are strength"],["לִי","to-me"],["יֹשְׁבֵי","inhabitants-of"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["בַּיהֹוָה","is in-Yahweh"],["צְבָאוֹת","of-Hosts"],["אֱלֹהֵיהֶם","their-God"],["׃",""]] },
  { num:"ו", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["אָשִׂים","shall-I-put"],["אֶת־אַלֻּפֵי","[ACC]-the chiefs of"],["יְהוּדָה","Judah"],["כְּכִיּוֹר","like-a pot of"],["אֵשׁ","fire"],["בְּעֵצִים","among-wood"],["וּכְלַפִּיד","and-like-a torch of"],["אֵשׁ","fire"],["בְּעָמִיר","among-cut grain"],["וְאָכְלוּ","and-did-partake"],["עַל־יָמִין","upon-right-hand"],["וְעַל־שְׂמֹאול","and-upon-the left side of"],["אֶת־כׇּל־הָעַמִּים","[ACC]-all-the-people"],["סָבִיב","round-about"],["וְיָשְׁבָה","and-she will dwell"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["עוֹד","any-more"],["תַּחְתֶּיהָ","in place-its"],["בִּירוּשָׁלָ͏ִם","is in-Jerusalem"],["׃",""]] },
  { num:"ז", words:[["וְהוֹשִׁעַ","and-Hoshea"],["יְהֹוָה","the-LORD"],["אֶת־אׇהֳלֵי","[ACC]-would-that"],["יְהוּדָה","Judah"],["בָּרִאשֹׁנָה","at the-former time"],["לְמַעַן","in-order-that"],["לֹא־תִגְדַּל","not-is-greater"],["תִּפְאֶרֶת","the-beauty-of"],["בֵּית־דָּוִיד","house-of-David"],["וְתִפְאֶרֶת","and-splendor"],["יֹשֵׁב","who-dwell-in"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["עַל־יְהוּדָה","upon-Judah"],["׃",""]] },
  { num:"ח", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["יָגֵן","he will defend"],["יְהֹוָה","the-LORD"],["בְּעַד","on-behalf-of"],["יוֹשֵׁב","sitting"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["וְהָיָה","and-be"],["הַנִּכְשָׁל","the-one who stumbles"],["בָּהֶם","in-them"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["כְּדָוִיד","like-David"],["וּבֵית","and-house-of"],["דָּוִיד","David"],["כֵּאלֹהִים","as-God"],["כְּמַלְאַךְ","like-an angel of"],["יְהֹוָה","the-LORD"],["לִפְנֵיהֶם","down-before-them"],["׃",""]] },
  { num:"ט", words:[["וְהָיָה","and-be"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["אֲבַקֵּשׁ","I-require"],["לְהַשְׁמִיד","to-destroy"],["אֶת־כׇּל־הַגּוֹיִם","[ACC]-all-the-nations"],["הַבָּאִים","to-the-come"],["עַל־יְרוּשָׁלָ͏ִם","upon-Jerusalem"],["׃",""]] },
  { num:"י", words:[["וְשָׁפַכְתִּי","and-have-I-shed"],["עַל־בֵּית","to-the-house-of"],["דָּוִיד","David"],["וְעַל","and-upon"],["יוֹשֵׁב","sitting"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["רוּחַ","spirit-of"],["חֵן","favor"],["וְתַחֲנוּנִים","and-supplication"],["וְהִבִּיטוּ","and-they-regarded"],["אֵלַי","to-me"],["אֵת","[ACC]"],["אֲשֶׁר־דָּקָרוּ","whose-they have pierced through"],["וְסָפְדוּ","and-they will mourn"],["עָלָיו","upon-him"],["כְּמִסְפֵּד","like-mourning"],["עַל־הַיָּחִיד","upon-the-Only-Begotten"],["וְהָמֵר","and-they will show bitterness"],["עָלָיו","upon-him"],["כְּהָמֵר","as-shows bitterness"],["עַל־הַבְּכוֹר","upon-the-elder"],["׃",""]] },
  { num:"יא", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["יִגְדַּל","shall-grow"],["הַמִּסְפֵּד","the-mourning"],["בִּירוּשָׁלַ͏ִם","is in-Jerusalem"],["כְּמִסְפַּד","like-the mourning of"],["הֲדַד־רִמּוֹן","Hadad-Rimmon"],["בְּבִקְעַת","in-the valley of"],["מְגִדּוֹן","Megiddo"],["׃",""]] },
  { num:"יב", words:[["וְסָפְדָה","and-it will mourn"],["הָאָרֶץ","the-earth"],["מִשְׁפָּחוֹת","kindreds"],["מִשְׁפָּחוֹת","kindreds"],["לְבָד","alone"],["מִשְׁפַּחַת","family-of"],["בֵּית־דָּוִיד","house-of-David"],["לְבָד","alone"],["וּנְשֵׁיהֶם","and-their-wives"],["לְבָד","alone"],["מִשְׁפַּחַת","family-of"],["בֵּית־נָתָן","house-of-Nathan"],["לְבָד","alone"],["וּנְשֵׁיהֶם","and-their-wives"],["לְבָד","alone"],["׃",""]] },
  { num:"יג", words:[["מִשְׁפַּחַת","family-of"],["בֵּית־לֵוִי","house-of-Levi"],["לְבָד","alone"],["וּנְשֵׁיהֶם","and-their-wives"],["לְבָד","alone"],["מִשְׁפַּחַת","family-of"],["הַשִּׁמְעִי","the-Shimeites"],["לְבָד","alone"],["וּנְשֵׁיהֶם","and-their-wives"],["לְבָד","alone"],["׃",""]] },
  { num:"יד", words:[["כֹּל","all"],["הַמִּשְׁפָּחוֹת","the-kindreds"],["הַנִּשְׁאָרוֹת","the-which-remain"],["מִשְׁפָּחֹת","clans"],["מִשְׁפָּחֹת","clans"],["לְבָד","alone"],["וּנְשֵׁיהֶם","and-their-wives"],["לְבָד","alone"],["׃",""]] },
];
renderVerseSet(zec_ch12Verses, 'zec-ch12-verses');

var zec_ch13Verses = [
  { num:"א", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["יִהְיֶה","he-shall-be"],["מָקוֹר","a fountain"],["נִפְתָּח","opened"],["לְבֵית","to-house-of"],["דָּוִיד","David"],["וּלְיֹשְׁבֵי","and-for-the inhabitants of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["לְחַטַּאת","the sin of"],["וּלְנִדָּה","and-for-impurity"],["׃",""]] },
  { num:"ב", words:[["וְהָיָה","and-be"],["בַיּוֹם","by-the-day"],["הַהוּא","that"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["אַכְרִית","I-shall-cut-off"],["אֶת־שְׁמוֹת","[ACC]-the-names-of"],["הָעֲצַבִּים","the-idols"],["מִן־הָאָרֶץ","from-the-land"],["וְלֹא","and-not"],["יִזָּכְרוּ","remembered"],["עוֹד","any-more"],["וְגַם","and-also"],["אֶת־הַנְּבִיאִים","ACC-the-prophets"],["וְאֶת־רוּחַ","and-[ACC]-spirit-of"],["הַטֻּמְאָה","of-the-filthiness"],["אַעֲבִיר","I will cause to pass by"],["מִן־הָאָרֶץ","from-the-land"],["׃",""]] },
  { num:"ג", words:[["וְהָיָה","and-be"],["כִּי־יִנָּבֵא","because-he prophesies"],["אִישׁ","man-of"],["עוֹד","any-more"],["וְאָמְרוּ","shall-say"],["אֵלָיו","to-him"],["אָבִיו","his-father"],["וְאִמּוֹ","and-mother-his"],["יֹלְדָיו","who begot-him"],["לֹא","not"],["תִחְיֶה","you will live"],["כִּי","because"],["שֶׁקֶר","false"],["דִּבַּרְתָּ","thou-hast-spoken"],["בְּשֵׁם","by-name"],["יְהֹוָה","the-LORD"],["וּדְקָרֻהוּ","and-they will pierce through-him"],["אָבִיהוּ","father-his"],["וְאִמּוֹ","and-mother-his"],["יֹלְדָיו","who begot-him"],["בְּהִנָּבְאוֹ","when-prophecies-he"],["׃",""]] },
  { num:"ד", words:[["וְהָיָה","and-be"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["יֵבֹשׁוּ","ashamed-shall-be"],["הַנְּבִיאִים","the-prophets"],["אִישׁ","man-of"],["מֵחֶזְיֹנוֹ","from-vision-his"],["בְּהִנָּבְאֹתוֹ","when-prophecies-he"],["וְלֹא","and-not"],["יִלְבְּשׁוּ","may they be clothed"],["אַדֶּרֶת","cloak of"],["שֵׂעָר","hair"],["לְמַעַן","in-order-that"],["כַּחֵשׁ","to deceive"],["׃",""]] },
  { num:"ה", words:[["וְאָמַר","and-said"],["לֹא","not"],["נָבִיא","a-prophet"],["אָנֹכִי","I"],["אִישׁ־עֹבֵד","man-of-served"],["אֲדָמָה","ground/earth"],["אָנֹכִי","I"],["כִּי","because"],["אָדָם","man"],["הִקְנַנִי","he sold-me"],["מִנְּעוּרָי","since-youth-my"],["׃",""]] },
  { num:"ו", words:[["וְאָמַר","and-said"],["אֵלָיו","to-him"],["מָה","what"],["הַמַּכּוֹת","are the-wounds"],["הָאֵלֶּה","these"],["בֵּין","among"],["יָדֶיךָ","hands-your"],["וְאָמַר","and-said"],["אֲשֶׁר","which"],["הֻכֵּיתִי","I-was-smitten"],["בֵּית","house-of"],["מְאַהֲבָי","lovers-my"],["׃",""]] },
  { num:"ז", words:[["חֶרֶב","the-sword-of"],["עוּרִי","awake"],["עַל־רֹעִי","upon-is shepherd-my"],["וְעַל־גֶּבֶר","and-upon-a man"],["עֲמִיתִי","community-my"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["הַךְ","strike"],["אֶת־הָרֹעֶה","[ACC]-the-shepherd"],["וּתְפוּצֶיןָ","and-they may be scattered"],["הַצֹּאן","the-flock"],["וַהֲשִׁבֹתִי","I-will-return"],["יָדִי","my-hand"],["עַל־הַצֹּעֲרִים","upon-the-little ones"],["׃",""]] },
  { num:"ח", words:[["וְהָיָה","and-be"],["בְכׇל־הָאָרֶץ","in-all-the-earth"],["נְאֻם־יְהֹוָה","says-the-LORD"],["פִּי־שְׁנַיִם","mouth-of-years"],["בָּהּ","in-it(f)"],["יִכָּרְתוּ","they-shall-be-cut-off"],["יִגְוָעוּ","they-shall-perish"],["וְהַשְּׁלִשִׁית","and-the-third"],["יִוָּתֶר","it will be left"],["בָּהּ","in-it(f)"],["׃",""]] },
  { num:"ט", words:[["וְהֵבֵאתִי","and-have-brought"],["אֶת־הַשְּׁלִשִׁית","[ACC]-the-third"],["בָּאֵשׁ","by-fire"],["וּצְרַפְתִּים","and-I will refine-them"],["כִּצְרֹף","as-refines"],["אֶת־הַכֶּסֶף","[ACC]-the-money"],["וּבְחַנְתִּים","and-I will test-them"],["כִּבְחֹן","as-tests"],["אֶת־הַזָּהָב","[ACC]-the-gold"],["הוּא","it-is"],["יִקְרָא","calls"],["בִשְׁמִי","me-by-name"],["וַאֲנִי","and-I"],["אֶעֱנֶה","I-will-answered"],["אֹתוֹ","him"],["אָמַרְתִּי","I-said"],["עַמִּי","my-people"],["הוּא","it-is"],["וְהוּא","and-it"],["יֹאמַר","He-says"],["יְהֹוָה","the-LORD"],["אֱלֹהָי","my-God"],["׃",""]] },
];
renderVerseSet(zec_ch13Verses, 'zec-ch13-verses');

var zec_ch14Verses = [
  { num:"א", words:[["הִנֵּה","behold"],["יוֹם־בָּא","day-came"],["לַיהֹוָה","to-Yahweh"],["וְחֻלַּק","and-it will be divided"],["שְׁלָלֵךְ","plunder-your"],["בְּקִרְבֵּךְ","in-your-midst"],["׃",""]] },
  { num:"ב", words:[["וְאָסַפְתִּי","and-I will gather"],["אֶת־כׇּל־הַגּוֹיִם","[ACC]-all-the-nations"],["אֶל־יְרוּשָׁלַ͏ִם","to-Jerusalem"],["לַמִּלְחָמָה","to-the-war"],["וְנִלְכְּדָה","and-it will be captured"],["הָעִיר","the-city"],["וְנָשַׁסּוּ","and-they will be plundered"],["הַבָּתִּים","the-houses"],["וְהַנָּשִׁים","and-the-women"],["[תִּשָּׁכַבְנָה]","they will be lain with"],["וְיָצָא","and-shall-come-forth"],["חֲצִי","half"],["הָעִיר","the-city"],["בַּגּוֹלָה","in the-exile"],["וְיֶתֶר","and-the-remainder-of-them"],["הָעָם","the-people"],["לֹא","not"],["יִכָּרֵת","he-shall-be-cut-off"],["מִן־הָעִיר","from-the-city"],["׃",""]] },
  { num:"ג", words:[["וְיָצָא","and-shall-come-forth"],["יְהֹוָה","the-LORD"],["וְנִלְחַם","and-fought"],["בַּגּוֹיִם","by-the-nations"],["הָהֵם","those"],["כְּיוֹם","as-the-day-of"],["הִלָּחֲמוֹ","having-fought"],["בְּיוֹם","in-day-of"],["קְרָב","battle"],["׃",""]] },
  { num:"ד", words:[["וְעָמְדוּ","and-shall-stand"],["רַגְלָיו","His-feet"],["בַּיּוֹם־הַהוּא","in-the-day-that"],["עַל־הַר","against-mount"],["הַזֵּיתִים","the-olive trees"],["אֲשֶׁר","which"],["עַל־פְּנֵי","upon-the-face-of"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["מִקֶּדֶם","of-old"],["וְנִבְקַע","and-it will be split open"],["הַר","mountain"],["הַזֵּיתִים","the-olive trees"],["מֵחֶצְיוֹ","from-middle-its"],["מִזְרָחָה","east--ward"],["וָיָמָּה","and-west--ward"],["גֵּיא","Ge"],["גְּדוֹלָה","great"],["מְאֹד","exceedingly"],["וּמָשׁ","and-it will depart"],["חֲצִי","half"],["הָהָר","the-mountain"],["צָפוֹנָה","northward"],["וְחֶצְיוֹ־נֶגְבָּה","and-half of-it-southward"],["׃",""]] },
  { num:"ה", words:[["וְנַסְתֶּם","and-you will flee"],["גֵּיא־הָרַי","the-Ge-My-mountains"],["כִּי־יַגִּיעַ","because-shall-come"],["גֵּי־הָרִים","the valley of-mountains"],["אֶל־אָצַל","to-Azel"],["וְנַסְתֶּם","and-you will flee"],["כַּאֲשֶׁר","when/as"],["נַסְתֶּם","you fled"],["מִפְּנֵי","because-of"],["הָרַעַשׁ","the-earthquake"],["בִּימֵי","in-days-of"],["עֻזִּיָּה","Uzziah"],["מֶלֶךְ־יְהוּדָה","king-of-Judah"],["וּבָא","and-come"],["יְהֹוָה","the-LORD"],["אֱלֹהַי","my-God"],["כׇּל־קְדֹשִׁים","all-holy"],["עִמָּךְ","your-people"],["׃",""]] },
  { num:"ו", words:[["וְהָיָה","and-be"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["לֹא־יִהְיֶה","there-would-be-no"],["אוֹר","light"],["יְקָרוֹת","precious"],["[וְקִפָּאוֹן]","and-frost"],["׃",""]] },
  { num:"ז", words:[["וְהָיָה","and-be"],["יוֹם־אֶחָד","day-one"],["הוּא","it-is"],["יִוָּדַע","shall-be-known"],["לַיהֹוָה","to-Yahweh"],["לֹא־יוֹם","not-day"],["וְלֹא־לָיְלָה","and-not-night"],["וְהָיָה","and-be"],["לְעֵת־עֶרֶב","to-time-evening"],["יִהְיֶה־אוֹר","he-shall-be-light"],["׃",""]] },
  { num:"ח", words:[["וְהָיָה","and-be"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["יֵצְאוּ","go-forth"],["מַיִם־חַיִּים","water-living"],["מִירוּשָׁלַ͏ִם","were more than-Jerusalem"],["חֶצְיָם","half of-them"],["אֶל־הַיָּם","to-the-sea"],["הַקַּדְמוֹנִי","the-old"],["וְחֶצְיָם","and-half of-them"],["אֶל־הַיָּם","to-the-sea"],["הָאַחֲרוֹן","the-last"],["בַּקַּיִץ","in the-summer"],["וּבָחֹרֶף","and-in the-winter"],["יִהְיֶה","he-shall-be"],["׃",""]] },
  { num:"ט", words:[["וְהָיָה","and-be"],["יְהֹוָה","the-LORD"],["לְמֶלֶךְ","king"],["עַל־כׇּל־הָאָרֶץ","upon-all-the-earth"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["יִהְיֶה","he-shall-be"],["יְהֹוָה","the-LORD"],["אֶחָד","one"],["וּשְׁמוֹ","and-his-name"],["אֶחָד","one"],["׃",""]] },
  { num:"י", words:[["יִסּוֹב","it will change"],["כׇּל־הָאָרֶץ","all-the-earth"],["כָּעֲרָבָה","like-desert plain"],["מִגֶּבַע","from-Geba"],["לְרִמּוֹן","to-Rimmon"],["נֶגֶב","south"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["וְרָאֲמָה","and-it will rise"],["וְיָשְׁבָה","and-she will dwell"],["תַחְתֶּיהָ","in place-its"],["לְמִשַּׁעַר","from-the gate of"],["בִּנְיָמִן","Benjamin"],["עַד־מְקוֹם","until-place-of"],["שַׁעַר","gate-of"],["הָרִאשׁוֹן","the-first"],["עַד־שַׁעַר","until-gate-of"],["הַפִּנִּים","the-corners"],["וּמִגְדַּל","and-Migdal"],["חֲנַנְאֵל","Hananel"],["עַד","until"],["יִקְבֵי","the wine-presses of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"יא", words:[["וְיָשְׁבוּ","and-they-were-settled"],["בָהּ","in-her"],["וְחֵרֶם","and-total destruction"],["לֹא","not"],["יִהְיֶה־עוֹד","he-shall-be-any-more"],["וְיָשְׁבָה","and-she will dwell"],["יְרוּשָׁלַ͏ִם","Jerusalem"],["לָבֶטַח","in-safety"],["׃",""]] },
  { num:"יב", words:[["וְזֹאת","and-this"],["תִּהְיֶה","shall-be"],["הַמַּגֵּפָה","the-plague"],["אֲשֶׁר","which"],["יִגֹּף","it will strike"],["יְהֹוָה","the-LORD"],["אֶת־כׇּל־הָעַמִּים","[ACC]-all-the-people"],["אֲשֶׁר","which"],["צָבְאוּ","they served"],["עַל־יְרוּשָׁלָ͏ִם","upon-Jerusalem"],["הָמֵק","he will cause to rot"],["בְּשָׂרוֹ","his-skin"],["וְהוּא","and-it"],["עֹמֵד","standing"],["עַל־רַגְלָיו","upon-his-feet"],["וְעֵינָיו","and-eyes-his"],["תִּמַּקְנָה","they will rot"],["בְחֹרֵיהֶן","in-sockets-their"],["וּלְשׁוֹנוֹ","and-tongue-his"],["תִּמַּק","it will rot"],["בְּפִיהֶם","in-their-mouths"],["׃",""]] },
  { num:"יג", words:[["וְהָיָה","and-be"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["תִּהְיֶה","shall-be"],["מְהוּמַת־יְהֹוָה","panic of-the-LORD"],["רַבָּה","much"],["בָּהֶם","in-them"],["וְהֶחֱזִיקוּ","and-shall-take-hold"],["אִישׁ","man-of"],["יַד","hand-of"],["רֵעֵהוּ","his-fellow"],["וְעָלְתָה","and-she will go up"],["יָדוֹ","his-hand"],["עַל־יַד","beside"],["רֵעֵהוּ","his-fellow"],["׃",""]] },
  { num:"יד", words:[["וְגַם־יְהוּדָה","and-also-Judah"],["תִּלָּחֵם","it will fight"],["בִּירוּשָׁלָ͏ִם","is in-Jerusalem"],["וְאֻסַּף","and-it will be gathered"],["חֵיל","the army of"],["כׇּל־הַגּוֹיִם","all-the-nations"],["סָבִיב","round-about"],["זָהָב","gold"],["וָכֶסֶף","and-with-silver"],["וּבְגָדִים","and-garments"],["לָרֹב","in-abundance"],["מְאֹד","exceedingly"],["׃",""]] },
  { num:"טו", words:[["וְכֵן","and-so"],["תִּהְיֶה","shall-be"],["מַגֵּפַת","plague-of"],["הַסּוּס","the-horses"],["הַפֶּרֶד","the-mule"],["הַגָּמָל","the-camel"],["וְהַחֲמוֹר","and-the-ass"],["וְכׇל־הַבְּהֵמָה","and-all-the-livestock"],["אֲשֶׁר","which"],["יִהְיֶה","he-shall-be"],["בַּמַּחֲנוֹת","in the-camps"],["הָהֵמָּה","those"],["כַּמַּגֵּפָה","like the-plague"],["הַזֹּאת","is-this"],["׃",""]] },
  { num:"טז", words:[["וְהָיָה","and-be"],["כׇּל־הַנּוֹתָר","all-the-what is left over"],["מִכׇּל־הַגּוֹיִם","from-all-the-nations"],["הַבָּאִים","to-the-come"],["עַל־יְרוּשָׁלָ͏ִם","upon-Jerusalem"],["וְעָלוּ","and-they will go up"],["מִדֵּי","more than-sufficiency of"],["שָׁנָה","year"],["בְשָׁנָה","to-year"],["לְהִשְׁתַּחֲוֺת","to-bow down"],["לְמֶלֶךְ","king"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["וְלָחֹג","and-to-celebrate a festival"],["אֶת־חַג","[ACC]-festival of"],["הַסֻּכּוֹת","the-booths"],["׃",""]] },
  { num:"יז", words:[["וְהָיָה","and-be"],["אֲשֶׁר","which"],["לֹא־יַעֲלֶה","no-comes-up"],["מֵאֵת","from"],["מִשְׁפְּחוֹת","kindreds-of"],["הָאָרֶץ","the-earth"],["אֶל־יְרוּשָׁלַ͏ִם","to-Jerusalem"],["לְהִשְׁתַּחֲוֺת","to-bow down"],["לְמֶלֶךְ","king"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["וְלֹא","and-not"],["עֲלֵיהֶם","against-them"],["יִהְיֶה","he-shall-be"],["הַגָּשֶׁם","the-rain"],["׃",""]] },
  { num:"יח", words:[["וְאִם־מִשְׁפַּחַת","and-if-family-of"],["מִצְרַיִם","Egypt"],["לֹא־תַעֲלֶה","not-you-will-ascend"],["וְלֹא","and-not"],["בָאָה","entered-into"],["וְלֹא","and-not"],["עֲלֵיהֶם","against-them"],["תִּהְיֶה","shall-be"],["הַמַּגֵּפָה","the-plague"],["אֲשֶׁר","which"],["יִגֹּף","it will strike"],["יְהֹוָה","the-LORD"],["אֶת־הַגּוֹיִם","[ACC]-the-nations"],["אֲשֶׁר","which"],["לֹא","not"],["יַעֲלוּ","they-go-up"],["לָחֹג","to-celebrate a festival"],["אֶת־חַג","[ACC]-festival of"],["הַסֻּכּוֹת","the-booths"],["׃",""]] },
  { num:"יט", words:[["זֹאת","this"],["תִּהְיֶה","shall-be"],["חַטַּאת","sin-offering"],["מִצְרָיִם","Egypt"],["וְחַטַּאת","and-the sin of"],["כׇּל־הַגּוֹיִם","all-the-nations"],["אֲשֶׁר","which"],["לֹא","not"],["יַעֲלוּ","they-go-up"],["לָחֹג","to-celebrate a festival"],["אֶת־חַג","[ACC]-festival of"],["הַסֻּכּוֹת","the-booths"],["׃",""]] },
  { num:"כ", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["יִהְיֶה","he-shall-be"],["עַל־מְצִלּוֹת","upon-the bells of"],["הַסּוּס","the-horses"],["קֹדֶשׁ","holy"],["לַיהֹוָה","to-Yahweh"],["וְהָיָה","and-be"],["הַסִּירוֹת","the-pots"],["בְּבֵית","in-house-of"],["יְהֹוָה","the-LORD"],["כַּמִּזְרָקִים","will be like the-bowls"],["לִפְנֵי","before"],["הַמִּזְבֵּחַ","the-altar"],["׃",""]] },
  { num:"כא", words:[["וְהָיָה","and-be"],["כׇּל־סִיר","all-the pot of"],["בִּירוּשָׁלַ͏ִם","is in-Jerusalem"],["וּבִיהוּדָה","and-Judah"],["קֹדֶשׁ","holy"],["לַיהֹוָה","to-Yahweh"],["צְבָאוֹת","of-Hosts"],["וּבָאוּ","and-it-comes"],["כׇּל־הַזֹּבְחִים","all-the-who-sacrificed"],["וְלָקְחוּ","and-they will take"],["מֵהֶם","of-them"],["וּבִשְּׁלוּ","and-they boiled"],["בָהֶם","among-them"],["וְלֹא־יִהְיֶה","and-shall-have-no-more"],["כְנַעֲנִי","a Canaanite"],["עוֹד","any-more"],["בְּבֵית־יְהֹוָה","in-house-of-the-LORD"],["צְבָאוֹת","of-Hosts"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["׃",""]] },
];
renderVerseSet(zec_ch14Verses, 'zec-ch14-verses');

})();
