// ot_verses/zep.js — Zephaniah verse data
(function() {
var zep_ch1Verses = [
  { num:"א", words:[["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["אֲשֶׁר","which"],["הָיָה","was"],["אֶל־צְפַנְיָה","to-Zephaniah"],["בֶּן־כּוּשִׁי","son-of-a Cushite"],["בֶן־גְּדַלְיָה","Bn-Gedaliah"],["בֶּן־אֲמַרְיָה","son-of-Amariah"],["בֶּן־חִזְקִיָּה","son-of-Hezekiah"],["בִּימֵי","in-days-of"],["יֹאשִׁיָּהוּ","Josiah"],["בֶן־אָמוֹן","Bn-Amon"],["מֶלֶךְ","king-of"],["יְהוּדָה","Judah"],["׃",""]] },
  { num:"ב", words:[["אָסֹף","surely"],["אָסֵף","I will bring to an end"],["כֹּל","all"],["מֵעַל","from-upon"],["פְּנֵי","face-of"],["הָאֲדָמָה","the-earth"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"ג", words:[["אָסֵף","I will bring to an end"],["אָדָם","man"],["וּבְהֵמָה","and-of-beasts"],["אָסֵף","I will bring to an end"],["עוֹף־הַשָּׁמַיִם","bird/fowl-the-heavens"],["וּדְגֵי","and-the fish of"],["הַיָּם","the-sea"],["וְהַמַּכְשֵׁלוֹת","and-the-stumbling-blocks"],["אֶת־הָרְשָׁעִים","ACC-the-wicked"],["וְהִכְרַתִּי","and-cut-off"],["אֶת־הָאָדָם","[ACC]-the-man"],["מֵעַל","from-upon"],["פְּנֵי","face-of"],["הָאֲדָמָה","the-earth"],["נְאֻם־יְהֹוָה","says-the-LORD"],["׃",""]] },
  { num:"ד", words:[["וְנָטִיתִי","and-I will stretch out"],["יָדִי","my-hand"],["עַל־יְהוּדָה","upon-Judah"],["וְעַל","and-upon"],["כׇּל־יוֹשְׁבֵי","all-the-inhabitants-of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["וְהִכְרַתִּי","and-cut-off"],["מִן־הַמָּקוֹם","from-the-place"],["הַזֶּה","this"],["אֶת־שְׁאָר","[ACC]-the-remnant-of"],["הַבַּעַל","the-Baal"],["אֶת־שֵׁם","ACC-name-of"],["הַכְּמָרִים","the-pagan priests"],["עִם־הַכֹּהֲנִים","with-the-priests"],["׃",""]] },
  { num:"ה", words:[["וְאֶת־הַמִּשְׁתַּחֲוִים","and-[ACC]-the-those-who bow down"],["עַל־הַגַּגּוֹת","upon-the-housetops"],["לִצְבָא","to-the host of"],["הַשָּׁמָיִם","the-heavens"],["וְאֶת־הַמִּשְׁתַּחֲוִים","and-[ACC]-the-those-who bow down"],["הַנִּשְׁבָּעִים","the-who-swear"],["לַיהֹוָה","to-Yahweh"],["וְהַנִּשְׁבָּעִים","and-the-those-who swear an oath"],["בְּמַלְכָּם","in-their-king"],["׃",""]] },
  { num:"ו", words:[["וְאֶת־הַנְּסוֹגִים","and-[ACC]-the-those-who have turned back"],["מֵאַחֲרֵי","from-after"],["יְהֹוָה","the-LORD"],["וַאֲשֶׁר","and-whom"],["לֹא־בִקְשׁוּ","not-they-sought"],["אֶת־יְהֹוָה","[ACC]-the-LORD"],["וְלֹא","and-not"],["דְרָשֻׁהוּ","they have sought-him"],["׃",""]] },
  { num:"ז", words:[["הַס","hush!"],["מִפְּנֵי","because-of"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["כִּי","because"],["קָרוֹב","soon"],["יוֹם","day"],["יְהֹוָה","the-LORD"],["כִּי־הֵכִין","because-prepared"],["יְהֹוָה","the-LORD"],["זֶבַח","sacrifice"],["הִקְדִּישׁ","he consecrated"],["קְרֻאָיו","invited ones-his"],["׃",""]] },
  { num:"ח", words:[["וְהָיָה","and-be"],["בְּיוֹם","in-day-of"],["זֶבַח","sacrifice"],["יְהֹוָה","the-LORD"],["וּפָקַדְתִּי","I-will-visit-them"],["עַל־הַשָּׂרִים","upon-the-princes"],["וְעַל־בְּנֵי","and-upon-sons-of"],["הַמֶּלֶךְ","the-king"],["וְעַל","and-upon"],["כׇּל־הַלֹּבְשִׁים","all-the-those-who are clothed"],["מַלְבּוּשׁ","clothing"],["נׇכְרִי","strange"],["׃",""]] },
  { num:"ט", words:[["וּפָקַדְתִּי","I-will-visit-them"],["עַל","upon"],["כׇּל־הַדּוֹלֵג","all-the-one who leaps"],["עַל־הַמִּפְתָּן","upon-the-threshold"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["הַמְמַלְאִים","those-who filled"],["בֵּית","house-of"],["אֲדֹנֵיהֶם","master-their"],["חָמָס","violence"],["וּמִרְמָה","and-deception"],["׃",""]] },
  { num:"י", words:[["וְהָיָה","and-be"],["בַיּוֹם","by-the-day"],["הַהוּא","that"],["נְאֻם־יְהֹוָה","says-the-LORD"],["קוֹל","voice-of"],["צְעָקָה","a-cry"],["מִשַּׁעַר","from-gate"],["הַדָּגִים","the-fish"],["וִילָלָה","and-wailing"],["מִן־הַמִּשְׁנֶה","from-the-second"],["וְשֶׁבֶר","and-destruction"],["גָּדוֹל","great"],["מֵהַגְּבָעוֹת","from-the-hills"],["׃",""]] },
  { num:"יא", words:[["הֵילִילוּ","howl"],["יֹשְׁבֵי","inhabitants-of"],["הַמַּכְתֵּשׁ","the-deep hollow"],["כִּי","because"],["נִדְמָה","it was destroyed"],["כׇּל־עַם","all-people"],["כְּנַעַן","Canaan"],["נִכְרְתוּ","they-were-cut-off"],["כׇּל־נְטִילֵי","all-the weighers of"],["כָסֶף","silver"],["׃",""]] },
  { num:"יב", words:[["וְהָיָה","and-be"],["בָּעֵת","at-the-time"],["הַהִיא","that"],["אֲחַפֵּשׂ","I will search for them"],["אֶת־יְרוּשָׁלַ͏ִם","[ACC]-Jerusalem"],["בַּנֵּרוֹת","with-the-lamps"],["וּפָקַדְתִּי","I-will-visit-them"],["עַל־הָאֲנָשִׁים","upon-the-men"],["הַקֹּפְאִים","the-who-are thickening"],["עַל־שִׁמְרֵיהֶם","upon-lees-their"],["הָאֹמְרִים","the-ones-saying"],["בִּלְבָבָם","in-their-hearts"],["לֹא־יֵיטִיב","not-he will do good"],["יְהֹוָה","the-LORD"],["וְלֹא","and-not"],["יָרֵעַ","he will do harm"],["׃",""]] },
  { num:"יג", words:[["וְהָיָה","and-be"],["חֵילָם","their-forces"],["לִמְשִׁסָּה","to-plunder"],["וּבָתֵּיהֶם","and-their-houses"],["לִשְׁמָמָה","to-desolate"],["וּבָנוּ","and-against-us"],["בָתִּים","houses"],["וְלֹא","and-not"],["יֵשֵׁבוּ","they sit"],["וְנָטְעוּ","and-they will plant"],["כְרָמִים","vineyards"],["וְלֹא","and-not"],["יִשְׁתּוּ","they-drink"],["אֶת־יֵינָם","[ACC]-their-wine"],["׃",""]] },
  { num:"יד", words:[["קָרוֹב","soon"],["יוֹם־יְהֹוָה","the-day-of-the-LORD"],["הַגָּדוֹל","the-great"],["קָרוֹב","soon"],["וּמַהֵר","and-hurrying"],["מְאֹד","exceedingly"],["קוֹל","voice-of"],["יוֹם","day"],["יְהֹוָה","the-LORD"],["מַר","bitter"],["צֹרֵחַ","is shouting out"],["שָׁם","there"],["גִּבּוֹר","mighty"],["׃",""]] },
  { num:"טו", words:[["יוֹם","day"],["עֶבְרָה","fury"],["הַיּוֹם","the-day"],["הַהוּא","that"],["יוֹם","day"],["צָרָה","affliction"],["וּמְצוּקָה","and-distress"],["יוֹם","day"],["שֹׁאָה","devastation"],["וּמְשׁוֹאָה","and-desolation"],["יוֹם","day"],["חֹשֶׁךְ","darkness"],["וַאֲפֵלָה","and-darkness"],["יוֹם","day"],["עָנָן","a-cloud"],["וַעֲרָפֶל","and-vapor-of-darkness"],["׃",""]] },
  { num:"טז", words:[["יוֹם","day"],["שׁוֹפָר","a ram's horn"],["וּתְרוּעָה","and-the battle-cry"],["עַל","upon"],["הֶעָרִים","the-cities"],["הַבְּצֻרוֹת","the-fortified"],["וְעַל","and-upon"],["הַפִּנּוֹת","the-corners"],["הַגְּבֹהוֹת","the-high"],["׃",""]] },
  { num:"יז", words:[["וַהֲצֵרֹתִי","and-I will cause distress"],["לָאָדָם","for-man"],["וְהָלְכוּ","and-they-shall-depart"],["כַּעִוְרִים","like-blind people"],["כִּי","because"],["לַיהֹוָה","to-Yahweh"],["חָטָאוּ","they sinned"],["וְשֻׁפַּךְ","and-it will be poured out"],["דָּמָם","their-blood"],["כֶּעָפָר","like the-dust"],["וּלְחֻמָם","and-bowels-their"],["כַּגְּלָלִים","like-the-dung"],["׃",""]] },
  { num:"יח", words:[["גַּם־כַּסְפָּם","also-their-silver"],["גַּם־זְהָבָם","also-their-gold"],["לֹא־יוּכַל","not-can"],["לְהַצִּילָם","that-He-would-deliver-them"],["בְּיוֹם","in-day-of"],["עֶבְרַת","the fury of"],["יְהֹוָה","the-LORD"],["וּבְאֵשׁ","and-in-the fire of"],["קִנְאָתוֹ","jealousy-his"],["תֵּאָכֵל","it will be eaten"],["כׇּל־הָאָרֶץ","all-the-earth"],["כִּי־כָלָה","because-all-of-it(f)"],["אַךְ־נִבְהָלָה","but-a terrible thing"],["יַעֲשֶׂה","he-shall-do"],["אֵת","[ACC]"],["כׇּל־יֹשְׁבֵי","all-inhabitants-of"],["הָאָרֶץ","the-earth"],["׃",""]] },
];
renderVerseSet(zep_ch1Verses, 'zep-ch1-verses');

var zep_ch2Verses = [
  { num:"א", words:[["הִתְקוֹשְׁשׁוּ","gather yourselves together"],["וָקוֹשּׁוּ","and-gather together"],["הַגּוֹי","the-nation"],["לֹא","not"],["נִכְסָף","ashamed"],["׃",""]] },
  { num:"ב", words:[["בְּטֶרֶם","before"],["לֶדֶת","the bringing forth of"],["חֹק","law"],["כְּמֹץ","like-chaff"],["עָבַר","passed"],["יוֹם","day"],["בְּטֶרֶם","before"],["לֹא־יָבוֹא","not-shall-come"],["עֲלֵיכֶם","over-you"],["חֲרוֹן","fierce"],["אַף־יְהֹוָה","the-anger-of-the-LORD"],["בְּטֶרֶם","before"],["לֹא־יָבוֹא","not-shall-come"],["עֲלֵיכֶם","over-you"],["יוֹם","day"],["אַף־יְהֹוָה","the-anger-of-the-LORD"],["׃",""]] },
  { num:"ג", words:[["בַּקְּשׁוּ","seek"],["אֶת־יְהֹוָה","[ACC]-the-LORD"],["כׇּל־עַנְוֵי","all-the humble people of"],["הָאָרֶץ","the-earth"],["אֲשֶׁר","which"],["מִשְׁפָּטוֹ","seat"],["פָּעָלוּ","they have done"],["בַּקְּשׁוּ־צֶדֶק","seek-righteousness"],["בַּקְּשׁוּ","seek"],["עֲנָוָה","humility"],["אוּלַי","perhaps"],["תִּסָּתְרוּ","you will be hidden"],["בְּיוֹם","in-day-of"],["אַף־יְהֹוָה","the-anger-of-the-LORD"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["עַזָּה","exceedingly"],["עֲזוּבָה","a-forsaking"],["תִהְיֶה","be"],["וְאַשְׁקְלוֹן","and-Ashkelon"],["לִשְׁמָמָה","to-desolate"],["אַשְׁדּוֹד","Ashdod"],["בַּצׇּהֳרַיִם","in-the-a roof(dual)"],["יְגָרְשׁוּהָ","people will drive out-it"],["וְעֶקְרוֹן","and-Ekron"],["תֵּעָקֵר","it will be plucked up"],["׃",""]] },
  { num:"ה", words:[["הוֹי","O"],["יֹשְׁבֵי","inhabitants-of"],["חֶבֶל","the region of"],["הַיָּם","the-sea"],["גּוֹי","nation"],["כְּרֵתִים","the Kerethites"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["עֲלֵיכֶם","over-you"],["כְּנַעַן","Canaan"],["אֶרֶץ","land-of"],["פְּלִשְׁתִּים","Philistines"],["וְהַאֲבַדְתִּיךְ","and-I will destroy-you"],["מֵאֵין","without"],["יוֹשֵׁב","sitting"],["׃",""]] },
  { num:"ו", words:[["וְהָיְתָה","and-it-be"],["חֶבֶל","the region of"],["הַיָּם","the-sea"],["נְוֺת","pastures of"],["כְּרֹת","made"],["רֹעִים","pasturing"],["וְגִדְרוֹת","and-folds of"],["צֹאן","flocks"],["׃",""]] },
  { num:"ז", words:[["וְהָיָה","and-be"],["חֶבֶל","the region of"],["לִשְׁאֵרִית","for-remnant-of"],["בֵּית","house-of"],["יְהוּדָה","Judah"],["עֲלֵיהֶם","against-them"],["יִרְעוּן","they will graze-!"],["בְּבָתֵּי","in"],["אַשְׁקְלוֹן","Ashkelon"],["בָּעֶרֶב","in-the-evening"],["יִרְבָּצוּן","they lie down-!"],["כִּי","because"],["יִפְקְדֵם","visit-shall(pl)"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיהֶם","their-God"],["וְשָׁב","and-repenteth"],["(שבותם)","captivity-their"],["[שְׁבִיתָם]","captivity-their"],["׃",""]] },
  { num:"ח", words:[["שָׁמַעְתִּי","heard"],["חֶרְפַּת","the-shame-of"],["מוֹאָב","Moab"],["בְּנֵי","sons-of"],["עַמּוֹן","Ammon"],["אֲשֶׁר","which"],["חֵרְפוּ","they have reproached"],["אֶת־עַמִּי","[ACC]-my-people"],["וַיַּגְדִּילוּ","and-they have magnified themselves"],["עַל־גְּבוּלָם","upon-territory-their"],["׃",""]] },
  { num:"ט", words:[["לָכֵן","therefore"],["חַי־אָנִי","living-I"],["נְאֻם","says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["אֱלֹהֵי","God-of"],["יִשְׂרָאֵל","Israel"],["כִּי־מוֹאָב","because-Moab"],["כִּסְדֹם","as-Sodom"],["תִּהְיֶה","shall-be"],["וּבְנֵי","and-sons-of"],["עַמּוֹן","Ammon"],["כַּעֲמֹרָה","like-Gomorrah"],["מִמְשַׁק","a place possessed of"],["חָרוּל","nettles"],["וּמִכְרֵה־מֶלַח","and-a pit of-salt"],["וּשְׁמָמָה","and-desolation"],["עַד־עוֹלָם","forever"],["שְׁאֵרִית","remnant-of"],["עַמִּי","my-people"],["יְבׇזּוּם","they will plunder-them"],["וְיֶתֶר","and-the-remainder-of-them"],["גּוֹיִ","my-back"],["יִנְחָלוּם","they will take possession of-them"],["׃",""]] },
  { num:"י", words:[["זֹאת","this"],["לָהֶם","to-them"],["תַּחַת","under"],["גְּאוֹנָם","pride-their"],["כִּי","because"],["חֵרְפוּ","they have reproached"],["וַיַּגְדִּלוּ","and-they magnified themselves"],["עַל־עַם","over-people-of"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["׃",""]] },
  { num:"יא", words:[["נוֹרָא","awful"],["יְהֹוָה","the-LORD"],["עֲלֵיהֶם","against-them"],["כִּי","because"],["רָזָה","lean"],["אֵת","[ACC]"],["כׇּל־אֱלֹהֵי","all-God-of"],["הָאָרֶץ","the-earth"],["וְיִשְׁתַּחֲווּ־לוֹ","and-they-worshipped-him"],["אִישׁ","man-of"],["מִמְּקוֹמוֹ","from-place-its"],["כֹּל","all"],["אִיֵּי","the-isles-of"],["הַגּוֹיִם","the-nations"],["׃",""]] },
  { num:"יב", words:[["גַּם־אַתֶּם","also-you"],["כּוּשִׁים","the Cushites"],["חַלְלֵי","slain-of"],["חַרְבִּי","sword-my"],["הֵמָּה","they-are"],["׃",""]] },
  { num:"יג", words:[["וְיֵט","and-he may stretch out"],["יָדוֹ","his-hand"],["עַל־צָפוֹן","upon-the-north"],["וִיאַבֵּד","so-it may destroy"],["אֶת־אַשּׁוּר","[ACC]-Assyria"],["וְיָשֵׂם","and-may he appoint"],["אֶת־נִינְוֵה","[ACC]-Nineveh"],["לִשְׁמָמָה","to-desolate"],["צִיָּה","dry"],["כַּמִּדְבָּר","as-the-a-wilderness"],["׃",""]] },
  { num:"יד", words:[["וְרָבְצוּ","and-they will lie down"],["בְתוֹכָהּ","in-the midst of-it"],["עֲדָרִים","flocks"],["כׇּל־חַיְתוֹ־גוֹי","all-living creature of-nation"],["גַּם־קָאַת","also-desert owl"],["גַּם־קִפֹּד","also-the-bittern"],["בְּכַפְתֹּרֶיהָ","on-capitals-its"],["יָלִינוּ","they spent the night"],["קוֹל","voice-of"],["יְשׁוֹרֵר","it will sing"],["בַּחַלּוֹן","in the-window"],["חֹרֶב","heat"],["בַּסַּף","is in the-basin"],["כִּי","because"],["אַרְזָהֿ","cedar-work"],["עֵרָה","it uncovered"],["׃",""]] },
  { num:"טו", words:[["זֹאת","this"],["הָעִיר","the-city"],["הָעַלִּיזָה","the-jubilant"],["הַיּוֹשֶׁבֶת","the-O-inhabitant-of"],["לָבֶטַח","in-safety"],["הָאֹמְרָה","the-who-says"],["בִּלְבָבָהּ","in-heart-her"],["אֲנִי","I"],["וְאַפְסִי","and-only-I"],["עוֹד","any-more"],["אֵיךְ","how"],["הָיְתָה","was"],["לְשַׁמָּה","desolate"],["מַרְבֵּץ","a resting place"],["לַחַיָּה","to-Lehi"],["כֹּל","all"],["עוֹבֵר","passing along"],["עָלֶיהָ","upon-it"],["יִשְׁרֹק","shall-hiss-forth"],["יָנִיעַ","he will shake"],["יָדוֹ","his-hand"],["׃",""]] },
];
renderVerseSet(zep_ch2Verses, 'zep-ch2-verses');

var zep_ch3Verses = [
  { num:"א", words:[["הוֹי","O"],["מֹרְאָה","the filthy one"],["וְנִגְאָלָה","and-the defiled one"],["הָעִיר","the-city"],["הַיּוֹנָה","the-dove"],["׃",""]] },
  { num:"ב", words:[["לֹא","not"],["שָׁמְעָה","she-heard"],["בְּקוֹל","the-voice-of"],["לֹא","not"],["לָקְחָה","taken-upon-them"],["מוּסָר","discipline"],["בַּיהֹוָה","is in-Yahweh"],["לֹא","not"],["בָטָחָה","it has trusted"],["אֶל־אֱלֹהֶיהָ","to-gods-her"],["לֹא","not"],["קָרֵבָה","it has drawn near"],["׃",""]] },
  { num:"ג", words:[["שָׂרֶיהָ","princes-its"],["בְקִרְבָּהּ","in-midst-its"],["אֲרָיוֹת","lions"],["שֹׁאֲגִים","are roaring"],["שֹׁפְטֶיהָ","judges-its"],["זְאֵבֵי","are wolves of"],["עֶרֶב","evening"],["לֹא","not"],["גָרְמוּ","they gnaw"],["לַבֹּקֶר","to the-morning"],["׃",""]] },
  { num:"ד", words:[["נְבִיאֶיהָ","prophets-its"],["פֹּחֲזִים","are insolent"],["אַנְשֵׁי","the-men-of"],["בֹּגְדוֹת","treacheri"],["כֹּהֲנֶיהָ","having-their-priests"],["חִלְּלוּ־קֹדֶשׁ","profaned-holy"],["חָמְסוּ","they have done violence to"],["תּוֹרָה","Torah/law"],["׃",""]] },
  { num:"ה", words:[["יְהֹוָה","the-LORD"],["צַדִּיק","righteous"],["בְּקִרְבָּהּ","in-inner being-her"],["לֹא","not"],["יַעֲשֶׂה","he-shall-do"],["עַוְלָה","injustice"],["בַּבֹּקֶר","in-the-morning"],["בַּבֹּקֶר","in-the-morning"],["מִשְׁפָּטוֹ","seat"],["יִתֵּן","shall-give"],["לָאוֹר","to-light"],["לֹא","not"],["נֶעְדָּר","was missing"],["וְלֹא־יוֹדֵעַ","and-not-knows"],["עַוָּל","an evil-doer"],["בֹּשֶׁת","bosheth"],["׃",""]] },
  { num:"ו", words:[["הִכְרַתִּי","I have cut off"],["גוֹיִם","nations"],["נָשַׁמּוּ","they are appalled"],["פִּנּוֹתָם","corners-their"],["הֶחֱרַבְתִּי","I have made desolate"],["חוּצוֹתָם","streets-their"],["מִבְּלִי","without"],["עוֹבֵר","passing along"],["נִצְדּוּ","they have been laid waste"],["עָרֵיהֶם","their-cities"],["מִבְּלִי־אִישׁ","without-man-of"],["מֵאֵין","without"],["יוֹשֵׁב","sitting"],["׃",""]] },
  { num:"ז", words:[["אָמַרְתִּי","I-said"],["אַךְ־תִּירְאִי","but-you be afraid"],["אוֹתִי","me"],["תִּקְחִי","you will accept"],["מוּסָר","discipline"],["וְלֹא־יִכָּרֵת","and-not-he-shall-be-cut-off"],["מְעוֹנָהּ","dwelling-its"],["כֹּל","all"],["אֲשֶׁר־פָּקַדְתִּי","whose-I-exhorted"],["עָלֶיהָ","upon-it"],["אָכֵן","surely"],["הִשְׁכִּימוּ","they rose early"],["הִשְׁחִיתוּ","destroyed"],["כֹּל","all"],["עֲלִילוֹתָם","deeds-their"],["׃",""]] },
  { num:"ח", words:[["לָכֵן","therefore"],["חַכּוּ־לִי","wait-to-me"],["נְאֻם־יְהֹוָה","says-the-LORD"],["לְיוֹם","to-day"],["קוּמִי","stand-up"],["לְעַד","for-booty"],["כִּי","because"],["מִשְׁפָּטִי","my-judgment"],["לֶאֱסֹף","to-be-gathered"],["גּוֹיִם","nations/gentiles"],["לְקׇבְצִי","to-assemble-I"],["מַמְלָכוֹת","kingdoms"],["לִשְׁפֹּךְ","to-shed"],["עֲלֵיהֶם","against-them"],["זַעְמִי","is-My-indignation"],["כֹּל","all"],["חֲרוֹן","fierce"],["אַפִּי","My-anger"],["כִּי","because"],["בְּאֵשׁ","with-fire"],["קִנְאָתִי","zeal-my"],["תֵּאָכֵל","it will be eaten"],["כׇּל־הָאָרֶץ","all-the-earth"],["׃",""]] },
  { num:"ט", words:[["כִּי־אָז","because-then"],["אֶהְפֹּךְ","I will restore"],["אֶל־עַמִּים","to-peoples"],["שָׂפָה","language"],["בְרוּרָה","purified"],["לִקְרֹא","to-read"],["כֻלָּם","all-of-them"],["בְּשֵׁם","by-name"],["יְהֹוָה","the-LORD"],["לְעׇבְדוֹ","to-the-servant-of-his"],["שְׁכֶם","the shoulder of"],["אֶחָד","one"],["׃",""]] },
  { num:"י", words:[["מֵעֵבֶר","across"],["לְנַהֲרֵי־כוּשׁ","of-the rivers of-Cush"],["עֲתָרַי","worshippers-my"],["בַּת־פּוּצַי","daughter-of-scattered ones-my"],["יוֹבִלוּן","they will bring-!"],["מִנְחָתִי","gift-my"],["׃",""]] },
  { num:"יא", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["לֹא","not"],["תֵבוֹשִׁי","be-confounded"],["מִכֹּל","of-all"],["עֲלִילֹתַיִךְ","practices-your"],["אֲשֶׁר","which"],["פָּשַׁעַתְּ","you have transgressed"],["בִּי","against-me"],["כִּי־אָז","because-then"],["אָסִיר","Sir"],["מִקִּרְבֵּךְ","from-midst-your"],["עַלִּיזֵי","the exultant ones of"],["גַּאֲוָתֵךְ","pride-your"],["וְלֹא־תוֹסִפִי","and-not-you will repeat"],["לְגׇבְהָה","to-tall of"],["עוֹד","any-more"],["בְּהַר","while-on-the-mount-of"],["קׇדְשִׁי","the holy things of"],["׃",""]] },
  { num:"יב", words:[["וְהִשְׁאַרְתִּי","and-I will leave"],["בְקִרְבֵּךְ","in-midst-your"],["עַם","people"],["עָנִי","poor"],["וָדָל","and-poor"],["וְחָסוּ","and-they will take refuge"],["בְּשֵׁם","by-name"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"יג", words:[["שְׁאֵרִית","remnant-of"],["יִשְׂרָאֵל","Israel"],["לֹא־יַעֲשׂוּ","not-shall-yield"],["עַוְלָה","injustice"],["וְלֹא־יְדַבְּרוּ","and-not-they-shall-speak"],["כָזָב","falsehood"],["וְלֹא־יִמָּצֵא","and-not-found"],["בְּפִיהֶם","in-their-mouths"],["לְשׁוֹן","the-language-of"],["תַּרְמִית","deceitfulness"],["כִּי־הֵמָּה","because-they-are"],["יִרְעוּ","they-feed"],["וְרָבְצוּ","and-they will lie down"],["וְאֵין","and-has-no"],["מַחֲרִיד","will be one who terrifies"],["׃",""]] },
  { num:"יד", words:[["רׇנִּי","cry out"],["בַּת־צִיּוֹן","the-daughter-of-Zion"],["הָרִיעוּ","the-shout"],["יִשְׂרָאֵל","Israel"],["שִׂמְחִי","rejoice"],["וְעׇלְזִי","and-he-who-rejoices-my"],["בְּכׇל־לֵב","in-all-heart"],["בַּת","daughter-of"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["׃",""]] },
  { num:"טו", words:[["הֵסִיר","he-removed"],["יְהֹוָה","the-LORD"],["מִשְׁפָּטַיִךְ","judgments-your"],["פִּנָּה","corner"],["אֹיְבֵךְ","enemy-your"],["מֶלֶךְ","king-of"],["יִשְׂרָאֵל","Israel"],["יְהֹוָה","the-LORD"],["בְּקִרְבֵּךְ","in-your-midst"],["לֹא־תִירְאִי","not-you-shall-fear(f)"],["רָע","evil"],["עוֹד","any-more"],["׃",""]] },
  { num:"טז", words:[["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["יֵאָמֵר","it-is-said"],["לִירוּשָׁלַ͏ִם","to-Jerusalem"],["אַל־תִּירָאִי","do-not-you be afraid"],["צִיּוֹן","Zion"],["אַל־יִרְפּוּ","do-not-they drop"],["יָדָיִךְ","hands-your"],["׃",""]] },
  { num:"יז", words:[["יְהֹוָה","the-LORD"],["אֱלֹהַיִךְ","God-your"],["בְּקִרְבֵּךְ","in-your-midst"],["גִּבּוֹר","mighty"],["יוֹשִׁיעַ","he-shall-save"],["יָשִׂישׂ","he will rejoice"],["עָלַיִךְ","upon-you(f)"],["בְּשִׂמְחָה","with-joy"],["יַחֲרִישׁ","he will keep silent"],["בְּאַהֲבָתוֹ","in-love-his"],["יָגִיל","he rejoices"],["עָלַיִךְ","upon-you(f)"],["בְּרִנָּה","with-singing"],["׃",""]] },
  { num:"יח", words:[["נוּגֵי","those grieved"],["מִמּוֹעֵד","from-the-appointed-time"],["אָסַפְתִּי","collected"],["מִמֵּךְ","from-you"],["הָיוּ","were"],["מַשְׂאֵת","tribute"],["עָלֶיהָ","upon-it"],["חֶרְפָּה","reproach"],["׃",""]] },
  { num:"יט", words:[["הִנְנִי","behold-I"],["עֹשֶׂה","do"],["אֶת־כׇּל־מְעַנַּיִךְ","[ACC]-all-those who afflicted-you"],["בָּעֵת","at-the-time"],["הַהִיא","that"],["וְהוֹשַׁעְתִּי","and-I have saved"],["אֶת־הַצֹּלֵעָה","[ACC]-the-one who is lame"],["וְהַנִּדָּחָה","and-the-one who is outcast"],["אֲקַבֵּץ","I-will-gathered"],["וְשַׂמְתִּים","and-I will make-them"],["לִתְהִלָּה","to-praise"],["וּלְשֵׁם","and-to-Shem"],["בְּכׇל־הָאָרֶץ","in-all-the-land"],["בׇּשְׁתָּם","shame-their"],["׃",""]] },
  { num:"כ", words:[["בָּעֵת","at-the-time"],["הַהִיא","that"],["אָבִיא","I-will-bring"],["אֶתְכֶם","you"],["וּבָעֵת","and-at-that-time"],["קַבְּצִי","to gather-I"],["אֶתְכֶם","you"],["כִּי־אֶתֵּן","because-shall-give"],["אֶתְכֶם","you"],["לְשֵׁם","to-the name of"],["וְלִתְהִלָּה","and-praise"],["בְּכֹל","in-all"],["עַמֵּי","the peoples of"],["הָאָרֶץ","the-earth"],["בְּשׁוּבִי","when-return-I"],["אֶת־שְׁבוּתֵיכֶם","[ACC]-captiviti-your"],["לְעֵינֵיכֶם","to-eyes-your"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["׃",""]] },
];
renderVerseSet(zep_ch3Verses, 'zep-ch3-verses');

})();
