// verses/4nephi.js — 4 Nephi verse data
(function() {
var fn_ch1Verses = [
  { num: "א", words: [["וַיְהִי","and it came to pass"], ["כַּאֲשֶׁר","when"], ["עָבְרָה","had passed away"], ["הַשָּׁנָה","the year"], ["הַשְּׁלֹשִׁים","thirty"], ["וְאַרְבַּע","and four"], ["וְגַם","and also"], ["הַשְּׁלֹשִׁים","the thirty"], ["וְחָמֵשׁ","and five"], ["וְהִנֵּה","and behold"], ["הֵקִימוּ","they established"], ["תַּלְמִידֵי","the disciples of"], ["יֵשׁוּעַ","Jesus"], ["אֶת־קְהִלַּת","the church of"], ["הַמָּשִׁיחַ","Christ"], ["בְּכׇל־הָאֲרָצוֹת","in all the lands"], ["מִסָּבִיב","round about"], ["וְכׇל־הַבָּאִים","and all who came"], ["אֲלֵיהֶם","unto them"], ["וְהַשָּׁבִים","and those who repented"], ["בֶּאֱמֶת","in truth"], ["מֵחַטֹּאתֵיהֶם","of their sins"], ["נִטְבְּלוּ","were baptized"], ["בְּשֵׁם","in the name of"], ["יֵשׁוּעַ","Jesus"], ["וְגַם־קִבְּלוּ","and did also receive"], ["אֶת־רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"]]},
  { num: "ב", words: [
    ["וַיְהִי","and it came to pass"],["בַּשָּׁנָה","in the year"],["הַשְּׁלֹשִׁים","thirty"],["וָשֵׁשׁ","and sixth"],["וַיָּשׁוּבוּ","and were converted"],["כׇל־הָעָם","all the people"],["אֶל־יְהוָה","unto the Lord"],["עַל־כׇּל־פְּנֵי","upon all the face of"],["הָאֲדָמָה","the land"],["גַּם־הַנֶּפִיִּים","both Nephites"],["גַּם־הַלָּמָנִים","and Lamanites"],["וְלֹא־הָיוּ","and there were no"],["מְרִיבוֹת","contentions"],["וּמַחֲלֹקוֹת","and disputations"],["בֵּינֵיהֶם","among them"],["וַיַּעַשׂ","and did"],["כׇּל־אִישׁ","every man"],["צְדָקָה","righteousness"],["עִם־רֵעֵהוּ","with his neighbor"]
  ]},
  { num: "ג", words: [["וַיְהִי","and there was"], ["כׇל־דָּבָר","all things"], ["מְשֻׁתָּף","common"], ["בֵּינֵיהֶם","among them"], ["וְעַל־כֵּן","wherefore"], ["לֹא־הָיוּ","there were not"], ["עֲשִׁירִים","rich"], ["וַעֲנִיִּים","and poor"], ["עֲבָדִים","bond"], ["וּבְנֵי־חוֹרִין","and free"], ["כִּי","but"], ["הָיוּ","they were"], ["כֻלָּם","all"], ["בְּנֵי־חוֹרִין","made free"], ["וְנוֹחֲלֵי","and partakers of"], ["מַתַּת","the gift of"], ["שָׁמָיִם","heaven"]]},
  { num: "ד", words: [
    ["וַיְהִי","and it came to pass"],["כַּאֲשֶׁר","when"],["עָבְרָה","had passed away"],["גַּם","also"],["הַשָּׁנָה","the year"],["הַשְּׁלֹשִׁים","thirty"],["וָשֶׁבַע","and seventh"],["וַיְהִי","and it came to pass"],["עוֹד","there was still"],["שָׁלוֹם","peace"],["בָּאָרֶץ","in the land"]
  ]},
  { num: "ה", words: [["וַיַּעֲשׂוּ","and they wrought"], ["תַּלְמִידֵי","the disciples of"], ["יֵשׁוּעַ","Jesus"], ["מַעֲשִׂים","works"], ["גְּדוֹלִים","great"], ["וְנִפְלָאִים","and marvelous"], ["עַד־אֲשֶׁר","insomuch that"], ["רִפְּאוּ","they healed"], ["אֶת־הַחוֹלִים","the sick"], ["וְהֵקִימוּ","and they raised"], ["אֶת־הַמֵּתִים","the dead"], ["וְהֱקִימוּ","and they caused"], ["פִּסְחִים","the lame"], ["לָלֶכֶת","to walk"], ["וְנָתְנוּ","and gave"], ["לַעִוְרִים","unto the blind"], ["לִרְאוֹת","to see"], ["וְלַחֵרְשִׁים","and unto the deaf"], ["לִשְׁמֹעַ","to hear"], ["וְעָשׂוּ","and they did"], ["כׇל־מִינֵי","all manner of"], ["נִפְלָאוֹת","miracles"], ["בִּבְנֵי","among the children of"], ["הָאָדָם","men"], ["וְלֹא־עָשׂוּ","and they did not do"], ["נֵס","a miracle"], ["כִּי־אִם","save it were"], ["בְּשֵׁם","in the name of"], ["יֵשׁוּעַ","Jesus"]]},
  { num: "ו", words: [["וְכֵן","and thus did"], ["עָבְרָה","pass away"], ["הַשָּׁנָה","the year"], ["הַשְּׁלֹשִׁים","thirty"], ["וּשְׁמֹנֶה","and eight"], ["וְגַם","and also"], ["הַשְּׁלֹשִׁים","the thirty"], ["וָתֵשַׁע","and nine"], ["וְהָאַרְבָּעִים","and the forty"], ["וְאַחַת","and one"], ["וְהָאַרְבָּעִים","and the forty"], ["וּשְׁתַּיִם","and two"], ["אַף","yea"], ["עַד־אֲשֶׁר","until"], ["עָבְרוּ","passed"], ["אַרְבָּעִים","forty"], ["וָתֵשַׁע","and nine"], ["שָׁנִים","years"], ["וְגַם","and also"], ["הַחֲמִשִּׁים","the fifty"], ["וְאַחַת","and one"], ["וְהַחֲמִשִּׁים","and the fifty"], ["וּשְׁתַּיִם","and two"], ["אַף","yea"], ["עַד־אֲשֶׁר","until"], ["עָבְרוּ","passed"], ["חֲמִשִּׁים","fifty"], ["וָתֵשַׁע","and nine"], ["שָׁנִים","years"]]},
  { num: "ז", words: [["וַיַּצְלִיחֵם","and he prospered them"], ["יְהוָה","the Lord"], ["מְאֹד","exceedingly"], ["בָּאָרֶץ","in the land"], ["עַד־אֲשֶׁר","insomuch that"], ["בָּנוּ","they did build"], ["עָרִים","cities"], ["חֲדָשׁוֹת","new"], ["תַּחַת","in place of"], ["הֶעָרִים","the cities"], ["הַשְּׂרוּפוֹת","which had been burned"]]},
  { num: "ח", words: [
    ["וְגַם","and also"],["אֶת־זָרַחֶמְלָה","Zarahemla"],["הָעִיר","the city"],["הַגְּדוֹלָה","the great"],["בָּנוּ","they built"],["מֵחָדָשׁ","again"]
  ]},
  { num: "ט", words: [
    ["אַךְ","but"],["עָרִים","cities"],["רַבּוֹת","many"],["אֲשֶׁר","which"],["שָׁקְעוּ","had sunken"],["וַיַּעֲלוּ","and came up"],["מַיִם","waters"],["תַּחְתֵּיהֶן","in their stead"],["לֹא־יָכְלוּ","could not"],["לְהִבָּנוֹת","be built"],["מֵחָדָשׁ","again"]
  ]},
  { num: "י", words: [["וְעַתָּה","and now"], ["הִנֵּה","behold"], ["וַיֶּחֱזַק","and waxed strong"], ["עַם־נֶפִי","the people of Nephi"], ["וַיִּרְבּוּ","and they did multiply"], ["מְאֹד","exceedingly"], ["מְהֵרָה","fast"], ["וַיִּהְיוּ","and they became"], ["לְעַם","a people"], ["יָפֶה","fair"], ["וְנָעִים","and delightsome"], ["מְאֹד","exceedingly"]]},
  { num: "יא", words: [
    ["וַיִּנָּשְׂאוּ","and they were married"],["וְנִתְּנוּ","and given"],["בִּנְשׂוּאִים","in marriage"],["וַיְבָרְכֵם","and he blessed them"],["יְהוָה","the Lord"],["כְּרֹב","according to the multitude of"],["הַהַבְטָחוֹת","the promises"],["אֲשֶׁר","which"],["הִבְטִיחַ","he had promised"],["לָהֶם","unto them"]
  ]},
  { num: "יב", words: [["וְלֹא־הָלְכוּ","and they did not walk"], ["עוֹד","any more"], ["אַחֲרֵי","after"], ["חֻקּוֹת","the statutes of"], ["תּוֹרַת","the law of"], ["מֹשֶׁה","Moses"], ["וּמִשְׁפָּטֶיהָ","and its judgments"], ["כִּי־אִם","but"], ["הָלְכוּ","they walked"], ["אַחֲרֵי","after"], ["הַמִּצְוֹת","the commandments"], ["אֲשֶׁר","which"], ["קִבְּלוּ","they had received"], ["מֵאֲדֹנֵיהֶם","from their Lord"], ["וֵאלֹהֵיהֶם","and their God"], ["וַיַּתְמִידוּ","and they continued"], ["בְּצוֹם","in fasting"], ["וּתְפִלָּה","and prayer"], ["וּלְהִקָּהֵל","and to gather"], ["יַחַד","together"], ["תָּמִיד","oft"], ["גַּם־לְהִתְפַּלֵּל","also to pray"], ["גַּם־לִשְׁמֹעַ","also to hear"], ["דְּבַר־יְהוָה","the word of the Lord"]]},
  { num: "יג", words: [["וַיְהִי","and it came to pass"], ["כִּי־לֹא","that not"], ["הָיְתָה","there was"], ["מְרִיבָה","contention"], ["בֵּין","among"], ["כׇּל־הָעָם","all the people"], ["בְּכׇל־הָאָרֶץ","in all the land"], ["אַךְ","but"], ["נַעֲשׂוּ","were wrought"], ["נִפְלָאוֹת","miracles"], ["גְּדוֹלוֹת","mighty"], ["בְּקֶרֶב","among"], ["תַּלְמִידֵי","the disciples of"], ["יֵשׁוּעַ","Jesus"]]},
  { num: "יד", words: [["וַיְהִי","and it came to pass"], ["כַּאֲשֶׁר","when"], ["עָבְרָה","had passed away"], ["הַשָּׁנָה","the year"], ["הַשִּׁבְעִים","the seventy"], ["וְאַחַת","and one"], ["וְגַם","and also"], ["הַשִּׁבְעִים","the seventy"], ["וּשְׁתַּיִם","and two"], ["אַף","yea"], ["עַד־אֲשֶׁר","until"], ["עָבְרָה","had passed away"], ["הַשָּׁנָה","the year"], ["הַשִּׁבְעִים","the seventy"], ["וָתֵשַׁע","and nine"], ["אַף","yea"], ["עַד־אֲשֶׁר","until"], ["עָבְרוּ","passed"], ["מֵאָה","one hundred"], ["שָׁנָה","years"], ["וְהָלְכוּ","and had gone"], ["כׇל־תַּלְמִידֵי","all the disciples of"], ["יֵשׁוּעַ","Jesus"], ["אֲשֶׁר","whom"], ["בָּחַר","he had chosen"], ["אֶל־גַּן־עֵדֶן","unto paradise"], ["מִלְּבַד","save it were"], ["הַשְּׁלֹשָׁה","the three"], ["אֲשֶׁר","who"], ["יִשָּׁאֲרוּ","should tarry"], ["וַיִּמָּשְׁחוּ","and there were ordained"], ["תַּלְמִידִים","disciples"], ["אֲחֵרִים","other"], ["תַּחְתֵּיהֶם","in their stead"], ["וְגַם","and also"], ["עָבְרוּ","passed"], ["רַבִּים","many"], ["מֵהַדּוֹר הַהוּא","of that generation"]]},
  { num: "טו", words: [["וַיְהִי","and it came to pass"], ["כִּי־לֹא","that not"], ["הָיְתָה","there was"], ["מְרִיבָה","contention"], ["בָּאָרֶץ","in the land"], ["מִפְּנֵי","because of"], ["אַהֲבַת","love of"], ["אֱלֹהִים","God"], ["אֲשֶׁר","which"], ["שָׁכְנָה","did dwell"], ["בִּלְבַב","in the hearts of"], ["הָעָם","the people"]]},
  { num: "טז", words: [["וְלֹא־הָיוּ","and there were no"], ["קִנְאוֹת","envyings"], ["וּמְרִיבוֹת","nor strifes"], ["וּמְהוּמוֹת","nor tumults"], ["וּזְנוּת","nor whoredoms"], ["וְכָזָב","nor lyings"], ["וְדָמִים","nor murders"], ["וְכׇל־מִינֵי","nor any manner of"], ["זִמָּה","lasciviousness"], ["וּבֶאֱמֶת","and surely"], ["לֹא־הָיָה","there could not be"], ["עַם","a people"], ["מְאֻשָּׁר","happier"], ["מֵהֶם","than them"], ["מִכׇּל־הָעַמִּים","among all the peoples"], ["אֲשֶׁר","which"], ["בָּרָא","created"], ["אֱלֹהִים","God"]]},
  { num: "יז", words: [["לֹא־הָיוּ","there were not"], ["שׁוֹדְדִים","robbers"], ["וְרוֹצְחִים","nor murderers"], ["וְגַם","and also"], ["לֹא־הָיוּ","there were not"], ["לָמָנִים","Lamanites"], ["וְלֹא","nor"], ["כׇל־מִינֵי","any manner of"], ["עַמִּים","peoples"], ["כִּי","but"], ["הָיוּ","were"], ["לְאֶחָד","in one"], ["בְּנֵי","the children of"], ["הַמָּשִׁיחַ","Christ"], ["וְיוֹרְשֵׁי","and heirs of"], ["מַלְכוּתוֹ","his kingdom"]]},
  { num: "יח", words: [["וּמַה־מְאֻשָּׁרִים","and how blessed"], ["הָיוּ","were they"], ["כִּי","for"], ["בֵרְכָם","he blessed them"], ["יְהוָה","the Lord"], ["בְּכׇל־מַעֲשֵׂיהֶם","in all their doings"], ["אַף","yea"], ["בֹּרְכוּ","they were blessed"], ["וַיַּצְלִיחוּ","and prospered"], ["עַד־אֲשֶׁר","until"], ["עָבְרוּ","had passed away"], ["מֵאָה","one hundred"], ["וָעֶשֶׂר","and ten"], ["שָׁנִים","years"], ["וַיַּעֲבֹר","and passed away"], ["הַדּוֹר","the generation"], ["הָרִאשׁוֹן","the first"], ["מִימֵי","from the days of"], ["הַמָּשִׁיחַ","Christ"], ["וְלֹא־הָיְתָה","and was not"], ["מְרִיבָה","contention"], ["בְּכׇל־הָאָרֶץ","in all the land"]]},
  { num: "יט", words: [["וַיָּמׇת","and died"], ["נֶפִי","Nephi"], ["אֲשֶׁר־שָׁמַר","who kept"], ["אֶת־הַסֵּפֶר","the record"], ["הָאַחֲרוֹן הַזֶּה","this last"], ["וַיִּשְׁמְרֵהוּ","and he kept it"], ["עַל־לוּחוֹת","upon plates of"], ["נֶפִי","Nephi"], ["וַיִּשְׁמֹר","and kept"], ["אָמוֹס","Amos"], ["בְּנוֹ","his son"], ["תַּחְתָּיו","in his stead"], ["וְגַם־הוּא","and also he"], ["שָׁמַר","kept"], ["אוֹתוֹ","it"], ["עַל־לוּחוֹת","upon the plates of"], ["נֶפִי","Nephi"]]},
  { num: "כ", words: [["וַיִּשְׁמְרֵהוּ","and he kept it"], ["שְׁמוֹנִים","eighty"], ["וְאַרְבַּע","and four"], ["שָׁנָה","years"], ["וַיְהִי","and there was"], ["עוֹד","still"], ["שָׁלוֹם","peace"], ["בָּאָרֶץ","in the land"], ["זוּלָת","save it were"], ["חֵלֶק","a part"], ["קָטָן","a small"], ["מִן־הָעָם","of the people"], ["אֲשֶׁר","which"], ["מָרְדוּ","had revolted"], ["בַּקְּהִלָּה","from the church"], ["וַיִּקְרְאוּ","and called"], ["לָהֶם","unto them"], ["שֵׁם","the name of"], ["לָמָנִים","Lamanites"], ["וְעַל־כֵּן","wherefore"], ["הֵחֵלּוּ","began"], ["לִהְיוֹת","to be"], ["לָמָנִים","Lamanites"], ["בָּאָרֶץ","in the land"], ["שֵׁנִית","again"]]},
  { num: "כא", words: [
    ["וַיְהִי","and it came to pass"],["כִּי־מֵת","that died"],["גַּם־אָמוֹס","also Amos"],["וַתִּהְיֶינָה","and it was"],["מֵאָה","one hundred"],["תִשְׁעִים","and ninety"],["וְאַרְבַּע","and four"],["שָׁנִים","years"],["לְבוֹא","from the coming of"],["הַמָּשִׁיחַ","Christ"],["וַיִּשְׁמֹר","and kept"],["אָמוֹס","Amos"],["בְּנוֹ","his son"],["אֶת־הַסֵּפֶר","the record"],["תַּחְתָּיו","in his stead"],["וְגַם־הוּא","and also he"],["שָׁמַר","kept"],["אוֹתוֹ","it"],["עַל־לוּחוֹת","upon plates of"],["נֶפִי","Nephi"],["וַיִּכָּתֵב","and was written"],["גַּם־בְּסֵפֶר","also in the book of"],["נֶפִי","Nephi"],["אֲשֶׁר","which"],["הוּא","is"],["הַסֵּפֶר הַזֶּה","this book"]
  ]},
  { num: "כב", words: [["וַיְהִי","and it came to pass"], ["כַּאֲשֶׁר","when"], ["עָבְרוּ","passed"], ["מָאתַיִם","two hundred"], ["שָׁנָה","years"], ["וְעָבַר","and had passed away"], ["כׇּל־הַדּוֹר","all the generation"], ["הַשֵּׁנִי","the second"], ["מִלְּבַד","save it were"], ["מְעַטִּים","a few"]]},
  { num: "כג", words: [["וְעַתָּה","and now"], ["חָפֵץ","would"], ["אֲנִי","I"], ["מוֹרְמוֹן","Mormon"], ["כִּי","that"], ["תֵדְעוּ","ye should know"], ["כִּי","that"], ["רָבוּ","they multiplied"], ["הָעָם","the people"], ["עַד־אֲשֶׁר","insomuch that"], ["נָפוֹצוּ","they spread"], ["עַל־כׇּל־פְּנֵי","upon all the face of"], ["הָאָרֶץ","the land"], ["וַיַּעֲשִׁירוּ","and became rich"], ["מְאֹד","exceedingly"], ["מֵרֹב","because of the multitude of"], ["הַצְלָחָתָם","their prosperity"], ["בַּמָּשִׁיחַ","in Christ"]]},
  { num: "כד", words: [["וְעַתָּה","and now"], ["בַּשָּׁנָה","in the year"], ["הַמָּאתַיִם","the two hundred"], ["וְאַחַת","and one"], ["הֵחֵלּוּ","began"], ["לִהְיוֹת","to be"], ["בֵּינֵיהֶם","among them"], ["אֲנָשִׁים","men"], ["גְּבֵהֵי","high of"], ["לֵב","heart"], ["לִלְבֹּשׁ","to wear"], ["בְּגָדִים","garments"], ["יְקָרִים","costly"], ["וְכׇל־מִינֵי","and all manner of"], ["פְּנִינִים","fine pearls"], ["וּמַחֲמַדֵּי","and the fine things of"], ["הָעוֹלָם","the world"]]},
  { num: "כה", words: [
    ["וּמֵהָעֵת הַהִיא","and from that time forth"],["וָהָלְאָה","and onward"],["לֹא־הָיוּ","there were not"],["עוֹד","any more"],["רְכוּשָׁם","their goods"],["וְקִנְיָנָם","and their substance"],["מְשֻׁתָּפִים","common"],["בֵּינֵיהֶם","among them"]
  ]},
  { num: "כו", words: [["וַיָּחֵלּוּ","and they began"], ["לְהִתְחַלֵּק","to be divided"], ["לְמַעֲמָדוֹת","into classes"], ["וַיָּחֵלּוּ","and they began"], ["לְהָקִים","to build up"], ["לָהֶם","unto them"], ["קְהִלּוֹת","churches"], ["לְמַעַן","to get"], ["בֶּצַע","gain"], ["וַיָּחֵלּוּ","and they began"], ["לְהִתְכַּחֵשׁ","to deny"], ["לִקְהִלַּת","the church of"], ["הַמָּשִׁיחַ","Christ"], ["הָאֲמִתִּית","the true"]]},
  { num: "כז", words: [["וַיְהִי","and it came to pass"], ["כַּאֲשֶׁר","that when"], ["עָבְרוּ","passed"], ["מָאתַיִם","two hundred"], ["וָעֶשֶׂר","and ten"], ["שָׁנִים","years"], ["וַתִּהְיֶינָה","and there were"], ["קְהִלּוֹת","churches"], ["רַבּוֹת","many"], ["בָּאָרֶץ","in the land"], ["אַף","yea"], ["הָיוּ","there were"], ["קְהִלּוֹת","churches"], ["רַבּוֹת","many"], ["אֲשֶׁר","which"], ["הִתְיַמְּרוּ","professed"], ["לָדַעַת","to know"], ["אֶת־הַמָּשִׁיחַ","Christ"], ["וְאַךְ","and yet"], ["כִּחֲשׁוּ","they did deny"], ["בְּרֹב","in the more parts of"], ["בְּשׂוֹרָתוֹ","his gospel"], ["עַד־אֲשֶׁר","insomuch that"], ["קִבְּלוּ","they received"], ["כׇּל־מִינֵי","all manner of"], ["רֶשַׁע","wickedness"], ["וַיִּתְּנוּ","and did administer"], ["אֶת־הַקֹּדֶשׁ","that which was sacred"], ["לַאֲשֶׁר","unto him who"], ["נֶאֱסַר","was forbidden"], ["עָלָיו","upon him"], ["בְּלִי","without"], ["טׇהֳרָה","purity"]]},
  { num: "כח", words: [["וַתִּרֶב","and increased"], ["הַקְּהִלָּה הַזֹּאת","this church"], ["מְאֹד","exceedingly"], ["מִפְּנֵי","because of"], ["הָעָוֹן","iniquity"], ["וּמִפְּנֵי","and because of"], ["כֹּחַ","the power of"], ["הַשָּׂטָן","Satan"], ["אֲשֶׁר","which"], ["תָּפַשׂ","did get hold upon"], ["אֶת־לִבָּם","their hearts"]]},
  { num: "כט", words: [
    ["וְעוֹד","and again"],["הָיְתָה","there was"],["קְהִלָּה","a church"],["אַחֶרֶת","another"],["אֲשֶׁר","which"],["כִּחֲשָׁה","denied"],["בַּמָּשִׁיחַ","in Christ"],["וַיִּרְדְּפוּ","and they did persecute"],["אֶת־קְהִלַּת","the church of"],["הַמָּשִׁיחַ","Christ"],["הָאֲמִתִּית","the true"],["בַּעֲבוּר","because of"],["עַנְוָתָם","their humility"],["וֶאֱמוּנָתָם","and their belief"],["בַּמָּשִׁיחַ","in Christ"],["וַיִּבְזוּ","and did despise"],["אוֹתָם","them"],["מִפְּנֵי","because of"],["הַנִּפְלָאוֹת","the miracles"],["הָרַבּוֹת","the many"],["אֲשֶׁר","which"],["נַעֲשׂוּ","were wrought"],["בְּקִרְבָּם","among them"]
  ]},
  { num: "ל", words: [["וְעַל־כֵּן","wherefore"], ["שָׁלְטוּ","they exercised"], ["בִּשְׂרָרָה","power"], ["וּבְמֶמְשָׁלָה","and authority"], ["עַל־תַּלְמִידֵי","upon the disciples of"], ["יֵשׁוּעַ","Jesus"], ["אֲשֶׁר","who"], ["נִשְׁאֲרוּ","did tarry"], ["אִתָּם","with them"], ["וַיַּשְׁלִיכוּם","and they cast them"], ["לַכֶּלֶא","into prison"], ["אַךְ","but"], ["בְּכֹחַ","by the power of"], ["דְּבַר־אֱלֹהִים","the word of God"], ["אֲשֶׁר","which"], ["הָיָה","was"], ["בָּם","in them"], ["נִבְקְעוּ","were rent"], ["בָּתֵּי","the houses of"], ["הַכֶּלֶא","the prison"], ["לִשְׁנַיִם","in twain"], ["וַיֵּצְאוּ","and they went forth"], ["לַעֲשׂוֹת","to do"], ["נִפְלָאוֹת","miracles"], ["גְּדוֹלוֹת","mighty"], ["בְּקִרְבָּם","among them"]]},
  { num: "לא", words: [["וּבְכׇל־זֹאת","and in all this"], ["וְאַף־גַּם־זֹאת","and notwithstanding"], ["כׇל־הַנִּפְלָאוֹת הָאֵלֶּה","all these miracles"], ["הִקְשׁוּ","hardened"], ["הָעָם","the people"], ["אֶת־לִבָּם","their hearts"], ["וַיְבַקְשׁוּ","and they sought"], ["לַהֲרֹג","to slay"], ["אוֹתָם","them"], ["כַּאֲשֶׁר","even as"], ["בִּקְשׁוּ","sought"], ["הַיְּהוּדִים","the Jews"], ["בִּירוּשָׁלַיִם","at Jerusalem"], ["לַהֲרֹג","to slay"], ["אֶת־יֵשׁוּעַ","Jesus"], ["כִּדְבָרוֹ","according to his word"]]},
  { num: "לב", words: [["וַיַּשְׁלִיכוּם","and they cast them"], ["לְתוֹךְ","into"], ["כִּבְשְׁנֵי","furnaces of"], ["אֵשׁ","fire"], ["וַיֵּצְאוּ","and came forth"], ["בְּלִי","without"], ["כׇל","any"], ["נֶזֶק","harm"]]},
  { num: "לג", words: [["וַיַּשְׁלִיכוּם","and they cast them"], ["גַּם","also"], ["לִמְאֻרוֹת","into dens of"], ["חַיּוֹת","beasts"], ["רָעוֹת","wild"], ["וַיְשַׂחֲקוּ","and they did play"], ["עִם־הַחַיּוֹת","with the beasts"], ["הָרָעוֹת","the wild"], ["כְּיֶלֶד","even as a child"], ["עִם־כֶּבֶשׂ","with a lamb"], ["וַיֵּצְאוּ","and did come forth"], ["מִתּוֹכָם","from among them"], ["בְּלִי","without"], ["כׇל","any"], ["נֶזֶק","harm"]]},
  { num: "לד", words: [["וּבְכׇל־זֹאת","and in all this"], ["הִקְשׁוּ","hardened"], ["הָעָם","the people"], ["אֶת־לִבָּם","their hearts"], ["כִּי","for"], ["הוֹבִילוּם","led them"], ["כֹּהֲנִים","priests"], ["וּנְבִיאֵי","and prophets of"], ["שֶׁקֶר","falsehood"], ["רַבִּים","many"], ["לְהָקִים","to build up"], ["קְהִלּוֹת","churches"], ["רַבּוֹת","many"], ["וְלַעֲשׂוֹת","and to do"], ["כׇּל־מִינֵי","all manner of"], ["עָוֹן","iniquity"], ["וַיַּכּוּ","and they smote"], ["אֶת־עַם","the people of"], ["יֵשׁוּעַ","Jesus"], ["וְעַם","and the people of"], ["יֵשׁוּעַ","Jesus"], ["לֹא","not"], ["הֵשִׁיבוּ","they returned"], ["מַכָּה","a smiting"], ["וְכֵן","and thus"], ["הָלְכוּ","they went"], ["וְדָלְלוּ","and dwindled"], ["בְּמַעַל","in unbelief"], ["וּבְרֶשַׁע","and wickedness"], ["מִשָּׁנָה","from year"], ["לְשָׁנָה","to year"], ["עַד־אֲשֶׁר","until"], ["עָבְרוּ","passed"], ["מָאתַיִם","two hundred"], ["וּשְׁלֹשִׁים","and thirty"], ["שָׁנָה","years"]]},
  { num: "לה", words: [["וַיְהִי","and it came to pass"], ["בַּשָּׁנָה הַזֹּאת","in this year"], ["אַף","yea"], ["בַּשָּׁנָה","in the year"], ["הַמָּאתַיִם","the two hundred"], ["וּשְׁלֹשִׁים","and thirty"], ["וְאַחַת","and one"], ["וַתְּהִי","and there was"], ["מַחֲלֹקֶת","a division"], ["גְּדוֹלָה","great"], ["בֵּין","among"], ["הָעָם","the people"]]},
  { num: "לו", words: [["וַיְהִי","and it came to pass"], ["בַּשָּׁנָה הַזֹּאת","in this year"], ["וַיָּקׇם","and there arose"], ["עַם","a people"], ["אֲשֶׁר","which"], ["נִקְרְאוּ","were called"], ["נֶפִיִּים","Nephites"], ["וְהֵם","and they"], ["הָיוּ","were"], ["מַאֲמִינֵי","believers of"], ["אֱמֶת","truth"], ["בַּמָּשִׁיחַ","in Christ"], ["וּבֵינֵיהֶם","and among them"], ["הָיוּ","were"], ["אֲשֶׁר","those who"], ["נִקְרְאוּ","were called"], ["בְּפִי","by the mouth of"], ["הַלָּמָנִים","the Lamanites"], ["יַעֲקֹבִים","Jacobites"], ["וְיוֹסֵפִים","and Josephites"], ["וְזוֹרָמִים","and Zoramites"]]},
  { num: "לז", words: [
    ["עַל־כֵּן","therefore"],["נִקְרְאוּ","were called"],["מַאֲמִינֵי","believers in"],["הַמָּשִׁיחַ","Christ"],["הָאֲמִתִּיִּים","the true"],["וְעוֹבְדֵי","and worshippers of"],["הַמָּשִׁיחַ","Christ"],["הָאֲמִתִּיִּים","the true"],["וּבֵינֵיהֶם","and among them"],["שְׁלֹשֶׁת","three"],["תַּלְמִידֵי","the disciples of"],["יֵשׁוּעַ","Jesus"],["אֲשֶׁר","which"],["יִשָּׁאֲרוּ","should tarry"],["נֶפִיִּים","Nephites"],["וְיַעֲקֹבִים","Jacobites"],["וְיוֹסֵפִים","and Josephites"],["וְזוֹרָמִים","and Zoramites"]
  ]},
  { num: "לח", words: [["וַיְהִי","and it came to pass"], ["כִּי־אֵלֶּה","that these"], ["אֲשֶׁר","which"], ["מָאֲסוּ","rejected"], ["אֶת־הַבְּשׂוֹרָה","the gospel"], ["נִקְרְאוּ","were called"], ["לָמָנִים","Lamanites"], ["וּלְמוּאֵלִים","and Lemuelites"], ["וְיִשְׁמְעֵאלִים","and Ishmaelites"], ["וְלֹא","and not"], ["דָלְלוּ","they dwindled"], ["בְּמַעַל","in unbelief"], ["כִּי","but"], ["מָרְדוּ","did rebel"], ["בִּרְצוֹנָם","wilfully"], ["בִּבְשׂוֹרַת","against the gospel of"], ["הַמָּשִׁיחַ","Christ"], ["וַיְלַמְּדוּ","and they taught"], ["אֶת־בְּנֵיהֶם","their children"], ["לְבִלְתִּי","not to"], ["הַאֲמִין","believe"], ["כַּאֲשֶׁר","even as"], ["דָּלְלוּ","did dwindle"], ["אֲבוֹתֵיהֶם","their fathers"], ["מֵרֵאשִׁית","from the beginning"]]},
  { num: "לט", words: [["וַיְהִי","and it was"], ["כֵן","thus"], ["מִפְּנֵי","because of"], ["רֶשַׁע","wickedness"], ["וְתוֹעֲבַת","and the abominations of"], ["אֲבוֹתֵיהֶם","their fathers"], ["כַּאֲשֶׁר","even as"], ["הָיָה","was"], ["מֵרֵאשִׁית","from the beginning"], ["וַיְלֻמְּדוּ","and they were taught"], ["לִשְׂנֹא","to hate"], ["אֶת־בְּנֵי","the children of"], ["אֱלֹהִים","God"], ["כַּאֲשֶׁר","even as"], ["לֻמְּדוּ","were taught"], ["הַלָּמָנִים","the Lamanites"], ["לִשְׂנֹא","to hate"], ["אֶת־בְּנֵי","the children of"], ["נֶפִי","Nephi"], ["מֵרֵאשִׁית","from the beginning"]]},
  { num: "מ", words: [
    ["וַיְהִי","and it came to pass"],["כַּאֲשֶׁר","when"],["עָבְרוּ","passed"],["מָאתַיִם","two hundred"],["אַרְבָּעִים","forty"],["וְאַרְבַּע","and four"],["שָׁנִים","years"],["וְכֵן","and thus"],["הָיוּ","were"],["עִנְיְנֵי","the affairs of"],["הָעָם","the people"],["וַיֶּחֱזַק","and waxed strong"],["חֵלֶק","part of"],["הָעָם","the people"],["הָרָשָׁע","the wicked"],["וַיִּרְבּוּ","and they did multiply"],["מְאֹד","exceedingly"],["יוֹתֵר","more"],["מֵעַם","than the people of"],["אֱלֹהִים","God"]
  ]},
  { num: "מא", words: [["וַיּוֹסִיפוּ","and they continued"], ["לִבְנוֹת","to build up"], ["לָהֶם","unto them"], ["קְהִלּוֹת","churches"], ["וּלְעַטְּרָן","and to adorn them"], ["בְּכׇל־מִינֵי","with all manner of"], ["חֲפָצִים","things"], ["יְקָרִים","precious"], ["וְכֵן","and thus"], ["עָבְרוּ","did pass away"], ["מָאתַיִם","two hundred"], ["וַחֲמִשִּׁים","and fifty"], ["שָׁנָה","years"], ["וְגַם","and also"], ["מָאתַיִם","two hundred"], ["וְשִׁשִּׁים","and sixty"], ["שָׁנָה","years"]]},
  { num: "מב", words: [["וַיָּחֶל","and began"], ["חֵלֶק","part of"], ["הָעָם","the people"], ["הָרָשָׁע","the wicked"], ["לִבְנוֹת","to build up"], ["שֵׁנִית","again"], ["אֶת־שְׁבוּעוֹת","the oaths"], ["וּקְשָׁרֵי","and combinations of"], ["גָּדִיאַנְטוֹן","Gadianton"], ["הַנִּסְתָּרִים","the secret"]]},
  { num: "מג", words: [["וְגַם","and also"], ["הֵחֵלּוּ","began"], ["הָעָם","the people"], ["אֲשֶׁר","which"], ["נִקְרְאוּ","were called"], ["עַם־נֶפִי","the people of Nephi"], ["לְהִתְגָּאוֹת","to be proud"], ["בִּלְבָבָם","in their hearts"], ["מִפְּנֵי","because of"], ["עׇשְׁרָם","their riches"], ["הָרַב","the exceeding"], ["וַיִּהְיוּ","and they were"], ["לְהַבְלֵי־שָׁוְא","vain"], ["כַּאֲחֵיהֶם","like unto their brethren"], ["הַלָּמָנִים","the Lamanites"]]},
  { num: "מד", words: [
    ["וּמֵהָעֵת הַזֹּאת","and from this time"],["הֵחֵלּוּ","began"],["הַתַּלְמִידִים","the disciples"],["לְהִתְאַבֵּל","to sorrow"],["עַל־חַטֹּאת","for the sins of"],["הָעוֹלָם","the world"]
  ]},
  { num: "מה", words: [["וַיְהִי","and it came to pass"], ["כַּאֲשֶׁר","that when"], ["עָבְרוּ","passed"], ["שְׁלֹשׁ","three"], ["מֵאוֹת","hundred"], ["שָׁנָה","years"], ["וַיִּהְיוּ","and they were"], ["גַם־עַם","also the people of"], ["נֶפִי","Nephi"], ["גַּם־הַלָּמָנִים","and the Lamanites"], ["רְשָׁעִים","wicked"], ["מְאֹד","exceedingly"], ["זֶה","one"], ["כָּזֶה","like unto another"]]},
  { num: "מו", words: [["וַיִּתְפַּשְּׁטוּ","and they did spread"], ["שׁוֹדְדֵי","the robbers of"], ["גָּדִיאַנְטוֹן","Gadianton"], ["עַל־כׇּל־פְּנֵי","upon all the face of"], ["הָאָרֶץ","the land"], ["וְלֹא־הָיוּ","and there were no"], ["צַדִּיקִים","righteous"], ["זוּלָת","save it were"], ["תַּלְמִידֵי","the disciples of"], ["יֵשׁוּעַ","Jesus"], ["וַיִּצְבְּרוּ","and they did lay up in store"], ["זָהָב","gold"], ["וָכֶסֶף","and silver"], ["לָרֹב","in abundance"], ["וַיִּסְחֲרוּ","and did traffic"], ["בְּכׇל־מִינֵי","in all manner of"], ["מִסְחָר","traffic"]]},
  { num: "מז", words: [["וַיְהִי","and it came to pass"], ["כַּאֲשֶׁר","when"], ["עָבְרוּ","passed"], ["שְׁלֹשׁ","three"], ["מֵאוֹת","hundred"], ["וְחָמֵשׁ","and five"], ["שָׁנִים","years"], ["וְהָעָם","and the people"], ["עוֹדָם","did still remain"], ["בְּרִשְׁעָתָם","in their wickedness"], ["וַיָּמׇת","and died"], ["אָמוֹס","Amos"], ["וַיִּשְׁמֹר","and kept"], ["עַמָּרוֹן","Ammaron"], ["אָחִיו","his brother"], ["אֶת־הַסֵּפֶר","the record"], ["תַּחְתָּיו","in his stead"]]},
  { num: "מח", words: [["וַיְהִי","and it came to pass"], ["כַּאֲשֶׁר","that when"], ["עָבְרוּ","passed"], ["שְׁלֹשׁ","three"], ["מֵאוֹת","hundred"], ["וְעֶשְׂרִים","and twenty"], ["שָׁנָה","years"], ["וְעַמָּרוֹן","and Ammaron"], ["עַל־פִּי","by the mouth of"], ["רוּחַ","the Spirit"], ["הַקֹּדֶשׁ","the Holy"], ["הִטְמִין","did hide up"], ["אֶת־הַסְּפָרִים","the records"], ["הַקְּדוֹשִׁים","the sacred"], ["אַף","yea"], ["אֶת־כׇּל־הַסְּפָרִים","all the records"], ["הַקְּדוֹשִׁים","the sacred"], ["אֲשֶׁר","which"], ["נִמְסְרוּ","had been handed down"], ["מִדּוֹר","from generation"], ["לְדוֹר","to generation"], ["אֲשֶׁר","which"], ["הָיוּ","were"], ["קְדוֹשִׁים","sacred"], ["עַד","unto"], ["הַשָּׁנָה","the year"], ["הַשְּׁלֹשׁ","three"], ["מֵאוֹת","hundred"], ["וְעֶשְׂרִים","and twentieth"], ["לְבוֹא","from the coming of"], ["הַמָּשִׁיחַ","Christ"]]},
  { num: "מט", words: [["וַיַּטְמִינֵם","and he did hide them up"], ["לַיהוָה","unto the Lord"], ["לְמַעַן","that"], ["יָבוֹאוּ","they might come"], ["שֵׁנִית","again"], ["אֶל־שְׁאֵרִית","unto the remnant of"], ["בֵּית־יַעֲקֹב","the house of Jacob"], ["כְּפִי","according to"], ["נְבוּאוֹת","the prophecies"], ["וְהַבְטָחוֹת","and the promises of"], ["יְהוָה","the Lord"], ["וְכֵן","and thus"], ["תַּם","is the end of"], ["סֵפֶר","the record of"], ["עַמָּרוֹן","Ammaron"]]}
];
renderVerseSet(fn_ch1Verses, '4n-ch1-verses');
})();
