// verses/frontmatter.js — Front Matter verse data
(function() {
var frontIntro = [

  // מבוא המתרגם - Translator's Introduction
  
  { num:"א", words:[
    ["הַתַּרְגּוּם","the translation"],
    ["הָעִבְרִי","the Hebrew"],
    ["הַזֶּה","this"],
    ["שֶׁל","of"],
    ["סֵפֶר","the book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["נַעֲשָׂה","was made"],
    ["כְּמַעֲשֶׂה","as a work"],
    ["עַצְמָאִי","independent"],
    ["לְמַטָּרוֹת","for purposes"],
    ["לְשׁוֹנִיּוֹת","linguistic"],
    ["לִמּוּדִיּוֹת","educational"],
    ["וְרוּחָנִיּוֹת","and spiritual"],
  ], english:"This Hebrew translation of the Book of Mormon is an independent work undertaken for linguistic, educational, and devotional purposes."},
  { num:"ב", words:[
    ["אֵין","is not"],
    ["הוּא","it"],
    ["הוֹצָאָה","a publication"],
    ["רִשְׁמִית","official"],
    ["שֶׁל","of"],
    ["כְּנֵסִיַּת","the church of"],
    ["יֵשׁוּעַ","Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["לִקְדוֹשֵׁי","of the Saints of"],
    ["הַיָּמִים","the Days"],
    ["הָאַחֲרוֹנִים","the Latter"],
    ["וְאֵין","and is not"],
    ["הוּא","it"],
    ["נִתְמָךְ","endorsed"],
    ["עַל־יָדָהּ","by it"],
  ], english:"It is not an official publication of The Church of Jesus Christ of Latter-day Saints, nor is it endorsed by that institution."},
  { num:"ג", words:[
    ["מַטָּרַת","the purpose of"],
    ["הַתַּרְגּוּם","the translation"],
    ["הִיא","is"],
    ["לְהַצִּיג","to present"],
    ["אֶת־טֶקְסְט","the text of"],
    ["סֵפֶר","the Book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["בִּדְמוּת","in the form of"],
    ["לְשׁוֹן","the language of"],
    ["הַמִּקְרָא","the Bible"],
    ["בִּסְגְנוֹן","in style"],
    ["בְּאוֹצַר","in treasury of"],
    ["הַמִּלִּים","words"],
    ["וּבְמִשְׁקַל","and in the register of"],
    ["הַלָּשׁוֹן","the language"],
    ["וּבְיוֹתֵר","and especially"],
    ["עַל־פִּי","upon"],
    ["לְשׁוֹן","the language of"],
    ["הַמִּקְרָא","the Bible"],
    ["הָעִבְרִי","the Hebrew"],
  ], english:"The aim of this translation is to present the text of the Book of Mormon in a form that reflects the style, vocabulary, and register of Biblical Hebrew, drawing especially upon the language of the Hebrew Bible."},
  { num:"ד", words:[
    ["הַמְתַרְגֵּם","the translator"],
    ["שָׁאַף","aspired"],
    ["לְאַזֵּן","to balance"],
    ["בֵּין","between"],
    ["בְּהִירוּת","clarity"],
    ["לְנֶאֱמָנוּת","to faithfulness"],
    ["לַטֶּקְסְט","to the text"],
    ["בִּבְחִירַת","in choosing"],
    ["לָשׁוֹן","a tone"],
    ["רִשְׁמִית","formal"],
    ["וּכְתוּבִית","and scriptural"],
    ["עַל־פְּנֵי","rather than"],
    ["סִגְנוֹן","an idiom"],
    ["עִבְרִי","Hebrew"],
    ["מוֹדֶרְנִי","modern"],
    ["וְעִם־זֶה","while yet"],
    ["קָרִיא","readable"],
    ["לְתַלְמִידֵי","to students of"],
    ["לְשׁוֹן","the language of"],
    ["הַמִּקְרָא","the Bible"],
    ["וּלְקוֹרְאֶיהָ","and to its readers"],
  ], english:"The translator has sought to balance clarity with fidelity, favoring a formal and scriptural tone rather than a modern idiom, while remaining readable to students and readers of Biblical Hebrew."},
  { num:"ה", words:[
    ["הַתַּרְגּוּם","the translation"],
    ["הֻכַּן","was prepared"],
    ["בִּידֵי","by the hands of"],
    ["כְּרִיס","Chris"],
    ["לַאמְבּ","Lambe"],
    ["בַּעַל","holder of"],
    ["תְּעוּדָה","a certificate"],
    ["לִמּוּדִית","academic"],
    ["מִתְקַדֶּמֶת","graduate"],
    ["בְּלָשׁוֹן","in the language of"],
    ["הַמִּקְרָא","the Bible"],
  ], english:"This work was produced by Chris Lambe, who holds a graduate certificate in Biblical Hebrew."},
  { num:"ו", words:[
    ["הוּא","it"],
    ["מְשַׁקֵּף","reflects"],
    ["לִמּוּד","study"],
    ["אִישִׁי","personal"],
    ["שִׁקוּל","judgment of"],
    ["דַּעַת","mind"],
    ["לְשׁוֹנִי","linguistic"],
    ["וְעִיּוּן","and study"],
    ["מַתְמִיד","sustained"],
    ["בִּכְתָבֵי","in the writings of"],
    ["הַקֹּדֶשׁ","the Holy"],
  ], english:"It reflects personal study, linguistic judgment, and sustained engagement with the Hebrew Scriptures."},
  { num:"ז", words:[
    ["אַף","although"],
    ["שֶׁנֶּעֶשְׂתָה","was made"],
    ["הַשְׁתַּדְּלוּת","effort"],
    ["לְדִיּוּק","for precision"],
    ["מִרְבִּי","utmost"],
    ["תַּרְגּוּם","translation"],
    ["זֶה","this"],
    ["כְּכׇל","like every"],
    ["מַעֲשֵׂה","work of"],
    ["אָדָם","man"],
    ["כָּפוּף","is subject"],
    ["לִמְגַבְּלוֹת","to limitations"],
    ["וְלִשְׁגִיאוֹת","and to errors"],
    ["אֶפְשָׁרִיּוֹת","possible"],
  ], english:"While care has been taken in the rendering of the text, this translation, like all human efforts, is subject to limitation and possible error."},
  { num:"ח", words:[
    ["אֵין","there is not"],
    ["בַּתַּרְגּוּם","in the translation"],
    ["זֶה","this"],
    ["טְעָנָה","a claim"],
    ["לְמָקוֹר","to a source"],
    ["עִבְרִי","Hebrew"],
    ["עַתִּיק","ancient"],
  ], english:"No claim is made that this translation represents an ancient Hebrew original."},
  { num:"ט", words:[
    ["כִּי־אִם","rather"],
    ["זֶהוּ","it is"],
    ["נִסָּיוֹן","an attempt"],
    ["לְהַעֲבִיר","to convey"],
    ["אֶת־הַטֶּקְסְט","the text"],
    ["הָאַנְגְּלִי","the English"],
    ["שֶׁל","of"],
    ["סֵפֶר","the Book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["לְתוֹךְ","into"],
    ["מִבְּנֵי","the structures of"],
    ["הַלָּשׁוֹן","the language"],
    ["וְהַנִּיב","and the idiom"],
    ["הָעִבְרִי","the Hebrew"],
    ["הַמִּקְרָאִי","the biblical"],
    ["לְמַעַן","in order to"],
    ["הֶאָרַת","the illumining of"],
    ["תֹּכֶן","the content of"],
    ["הַסֵּפֶר","the book"],
    ["נוֹשְׂאָיו","its themes"],
    ["וְאֹפְיוֹ","and its character"],
    ["הַכְּתוּבִי","the scriptural"],
    ["לְקוֹרְאֵי","for readers of"],
    ["עִבְרִית","Hebrew"],
    ["וּלְתַלְמִידֵי","and for students of"],
    ["כִּתְבֵי","the writings of"],
    ["הַקֹּדֶשׁ","the holy"],
  ], english:"Rather, it is an attempt to express the English text of the Book of Mormon through the structures and idioms of Biblical Hebrew, in order to illuminate its content, themes, and scriptural character for Hebrew readers and students of scripture."},
  { num:"י", words:[
    ["הַקּוֹרְאִים","the readers"],
    ["מֻזְמָנִים","are invited"],
    ["לְגֶשֶׁת","to approach"],
    ["אֶל","unto"],
    ["הַתַּרְגּוּם","the translation"],
    ["בְּשִׁקוּל","with judgment of"],
    ["דַּעַת","mind"],
    ["בְּכָבוֹד","with reverence"],
    ["וּבְעִיּוּן","and with study"],
    ["מְדֻקְדָּק","careful"],
    ["וּלְהַעֲרִיךְ","and to evaluate"],
    ["אוֹתוֹ","it"],
    ["עַל־יְדֵי","by means of"],
    ["לִמּוּד","study"],
    ["מַעֲמִיק","deep"],
    ["וְהִתְעַסְּקוּת","and engagement"],
    ["בַּטֶּקְסְט","in the text"],
  ], english:"Readers are invited to approach this work with discernment, reverence, and thoughtful comparison, and to assess its value through careful study and engagement with the text."},
];
var frontTitle = [

  // ספר מורמון - Title Page
  
  { num:"א", words:[
    ["דִּבְרֵי־סֵפֶר","the words of a record"],
    ["כְּתוּבִים","written"],
    ["בְּיַד־מוֹרְמוֹן","by the hand of Mormon"],
    ["עַל־לוּחוֹת","upon plates"],
    ["הַלְּקוּחוֹת","taken"],
    ["מִלּוּחוֹת","from the plates of"],
    ["נֶפִי","Nephi"],
  ], english:"An account written by the hand of Mormon upon plates taken from the plates of Nephi."},
  { num:"ב", words:[
    ["לָכֵן","therefore"],
    ["הוּא","it is"],
    ["קִצּוּר","an abridgment of"],
    ["דִּבְרֵי","the record of"],
    ["יְמֵי","the days of"],
    ["עַם־נֶפִי","the people of Nephi"],
    ["וְגַם־הַלָּמָנִים","and also the Lamanites"],
  ], english:"Wherefore, it is an abridgment of the record of the people of Nephi, and also of the Lamanites—"},
  { num:"ג", words:[
    ["נִכְתַּב","written"],
    ["לַלָּמָנִים","to the Lamanites"],
    ["אֲשֶׁר","who"],
    ["הֵם","they"],
    ["שְׁאֵרִית","a remnant of"],
    ["בֵּית־יִשְׂרָאֵל","the house of Israel"],
    ["וְגַם־לַיְּהוּדִי","and also to the Jew"],
    ["וְלַגּוֹי","and to the Gentile"],
  ], english:"Written to the Lamanites, who are a remnant of the house of Israel; and also to Jew and Gentile—"},
  { num:"ד", words:[
    ["נִכְתַּב","written"],
    ["עַל־פִּי","according to"],
    ["מִצְוָה","commandment"],
    ["וְגַם־בְּרוּחַ","and also by the spirit of"],
    ["הַנְּבוּאָה","prophecy"],
    ["וְהֶחָזוֹן","and of revelation"],
  ], english:"Written by way of commandment, and also by the spirit of prophecy and of revelation—"},
  { num:"ה", words:[
    ["נִכְתַּב","written"],
    ["וְנֶחְתַּם","and sealed"],
    ["וְנִטְמַן","and hid up"],
    ["לַיהוָה","unto the Lord"],
    ["לְמַעַן","that"],
    ["לֹא","not"],
    ["יֻשְׁמְדוּ","they be destroyed"],
  ], english:"Written and sealed up, and hid up unto the Lord, that they might not be destroyed—"},
  { num:"ו", words:[
    ["לָצֵאת","to come forth"],
    ["בְּמַתַּת־אֵל","by the gift of God"],
    ["וּבִגְבוּרָתוֹ","and by His power"],
    ["לְפִתְרוֹנוֹ","unto its interpretation"],
  ], english:"To come forth by the gift and power of God unto the interpretation thereof—"},
  { num:"ז", words:[
    ["נֶחְתַּם","sealed"],
    ["בְּיַד־מוֹרוֹנִי","by the hand of Moroni"],
    ["וְנִטְמַן","and hid up"],
    ["לַיהוָה","unto the Lord"],
    ["לָצֵאת","to come forth"],
    ["בְּעִתּוֹ","in its time"],
    ["עַל־יְדֵי","by way of"],
    ["הַגּוֹי","the Gentile"],
    ["וּפִתְרוֹנוֹ","the interpretation thereof"],
    ["בְּמַתַּת","by the gift of"],
    ["אֱלֹהִים","God"],
  ], english:"Sealed by the hand of Moroni, and hid up unto the Lord, to come forth in due time by way of the Gentile—the interpretation thereof by the gift of God."},
  { num:"ח", words:[
    ["וְגַם","and also"],
    ["קִצּוּר","an abridgment"],
    ["מִסֵּפֶר","from the book of"],
    ["עֵתֶר","Ether"],
    ["אֲשֶׁר","which"],
    ["הוּא","it is"],
    ["דִּבְרֵי","a record of"],
    ["יְמֵי","the days of"],
    ["עַם־יֶרֶד","the people of Jared"],
    ["אֲשֶׁר","who"],
    ["נָפֹצוּ","were scattered"],
    ["בְּעֵת","in the time"],
    ["בָּלַל","confounded"],
    ["יְהוָה","the Lord"],
    ["שְׂפַת","the language of"],
    ["הָעָם","the people"],
    ["בִּבְנוֹתָם","when they built"],
    ["מִגְדָּל","a tower"],
    ["לַעֲלוֹת","to ascend"],
    ["הַשָּׁמָיְמָה","to heaven"],
  ], english:"An abridgment taken from the Book of Ether also, which is a record of the people of Jared, who were scattered at the time the Lord confounded the language of the people, when they were building a tower to get to heaven—"},
  { num:"ט", words:[
    ["לְמַעַן","that"],
    ["הַרְאוֹת","to show"],
    ["לִשְׁאֵרִית","unto the remnant of"],
    ["בֵּית־יִשְׂרָאֵל","the house of Israel"],
    ["אֵת־הַגְּדֹלוֹת","the great things"],
    ["אֲשֶׁר־עָשָׂה","which did"],
    ["יְהוָה","the Lord"],
    ["לַאֲבוֹתֵיהֶם","for their fathers"],
  ], english:"Which is to show unto the remnant of the house of Israel what great things the Lord hath done for their fathers;"},
  { num:"י", words:[
    ["וּלְמַעַן","and that"],
    ["יֵדְעוּ","they may know"],
    ["בְּרִיתוֹת","the covenants of"],
    ["יְהוָה","the Lord"],
    ["כִּי־לֹא","that not"],
    ["נִזְנְחוּ","they are cast off"],
    ["לָנֶצַח","forever"],
  ], english:"and that they may know the covenants of the Lord, that they are not cast off forever—"},
  { num:"יא", words:[
    ["וְגַם","and also"],
    ["לְהוֹכִיחַ","to convince"],
    ["לַיְּהוּדִי","the Jew"],
    ["וְלַגּוֹי","and the Gentile"],
    ["כִּי","that"],
    ["יֵשׁוּעַ","Jesus"],
    ["הוּא","is"],
    ["הַמָּשִׁיחַ","the Christ"],
    ["אֱלֹהֵי","the God of"],
    ["עוֹלָם","eternity"],
    ["הַנִּגְלֶה","manifesting himself"],
    ["לְכׇל־הַגּוֹיִם","unto all the nations"],
  ], english:"And also to the convincing of the Jew and Gentile that Jesus is the Christ, the Eternal God, manifesting himself unto all nations—"},
  { num:"יב", words:[
    ["וְעַתָּה","and now"],
    ["אִם־יֵשׁ","if there are"],
    ["שְׁגִיאוֹת","errors"],
    ["הֵנָּה","they are"],
    ["שְׁגִיאוֹת","the mistakes of"],
    ["אֱנוֹשׁ","men"],
    ["לָכֵן","therefore"],
    ["אַל־תַּרְשִׁיעוּ","do not condemn"],
    ["דִּבְרֵי","the words of"],
    ["אֱלֹהִים","God"],
    ["לְמַעַן","that"],
    ["תִּמָּצְאוּ","you may be found"],
    ["נְקִיִּים","spotless"],
    ["לִפְנֵי","before"],
    ["כִּסֵּא־מִשְׁפַּט","the judgment-seat of"],
    ["הַמָּשִׁיחַ","Christ"],
  ], english:"And now, if there are faults they are the mistakes of men; wherefore, condemn not the things of God, that ye may be found spotless at the judgment-seat of Christ."},
  { num:"יג", words:[
    ["תֻּרְגַּם","translated"],
    ["בְּיַד־יוֹסֵף","by the hand of Joseph"],
    ["סְמִית","Smith"],
    ["הַצָּעִיר","the younger"],
  ], english:"Translated by Joseph Smith, Jun."},
];
var frontIntroduction = [

  // מבוא - Introduction
  
  { num:"א", words:[
    ["סֵפֶר","the book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["הוּא","is"],
    ["סֵפֶר","a volume of"],
    ["דִּבְרֵי","the writings of"],
    ["הַקֹּדֶשׁ","holy"],
    ["כְּתַנַ״ךְ","comparable to the Bible"],
    ["וְהוּא","and it is"],
    ["זִכְרוֹן","a record of"],
    ["דִּבְרֵי","the dealings of"],
    ["יְהוָה","the Lord"],
    ["עִם־יֹשְׁבֵי","with the inhabitants of"],
    ["אֶרֶץ","the land of"],
    ["אַמֶרִיקָה","America"],
    ["מִקֶּדֶם","ancient"],
    ["וּבוֹ","and in it is"],
    ["מְלוֹא","the fullness of"],
    ["בְּשׂוֹרַת","the gospel of"],
    ["עוֹלָמִים","the everlasting"],
  ], english:"The Book of Mormon is a volume of holy scripture comparable to the Bible. It is a record of God’s dealings with ancient inhabitants of the Americas and contains the fulness of the everlasting gospel."},
  { num:"ב", words:[
    ["כָּתְבוּ","wrote"],
    ["הַסֵּפֶר","the book"],
    ["נְבִיאֵי","prophets of"],
    ["קֶדֶם","old"],
    ["רַבִּים","many"],
    ["בְּרוּחַ","in the Spirit"],
    ["הַנְּבוּאָה","the prophecy"],
    ["וְהֶחָזוֹן","and revelation"],
    ["וְדִבְרֵיהֶם","and their words"],
    ["חֲקוּקִים","engraved"],
    ["עַל־לוּחוֹת","on plates of"],
    ["זָהָב","gold"],
    ["נֶעְתְּקוּ","were quoted"],
    ["וְקֻצְּרוּ","and abridged"],
    ["בְּיַד־מוֹרְמוֹן","by the hand of Mormon"],
    ["הַנָּבִיא","the prophet"],
    ["וְסוֹפֵר","and historian of"],
    ["דִּבְרֵי","the chronicles of"],
    ["הַיָּמִים","the days"],
  ], english:"The book was written by many ancient prophets by the spirit of prophecy and revelation. Their words, written on gold plates, were quoted and abridged by a prophet-historian named Mormon."},
  { num:"ג", words:[
    ["וְהַסֵּפֶר","and the record"],
    ["מְסַפֵּר","gives an account of"],
    ["קוֹרוֹת","the history of"],
    ["שְׁתֵּי","two"],
    ["מַמְלָכוֹת","civilizations"],
    ["גְּדוֹלוֹת","great"],
  ], english:"The record gives an account of two great civilizations."},
  { num:"ד", words:[
    ["הָאַחַת","the one"],
    ["יָצְאָה","went forth"],
    ["מִירוּשָׁלַיִם","from Jerusalem"],
    ["בִּשְׁנַת","in the year of"],
    ["שֵׁשׁ","six"],
    ["מֵאוֹת","hundred"],
    ["לִפְנֵי","before"],
    ["מְשִׁיחֵנוּ","our Messiah"],
    ["וַתֵּחָלֵק","and was divided"],
    ["לִשְׁנֵי","into two"],
    ["עַמִּים","peoples"],
    ["הֵם","they"],
    ["הַנֶּפִיִּים","the Nephites"],
    ["וְהַלָּמָנִים","and the Lamanites"],
  ], english:"One came from Jerusalem in 600 B.C. and afterward separated into two nations, known as the Nephites and the Lamanites."},
  { num:"ה", words:[
    ["וְהָאַחֶרֶת","and the other"],
    ["קָדְמָה","came earlier"],
    ["לָבוֹא","to come"],
    ["בְּעֵת","in the time"],
    ["בָּלַל","confounded"],
    ["יְהוָה","the Lord"],
    ["שְׂפַת","the language of"],
    ["יוֹשְׁבֵי","the inhabitants of"],
    ["מִגְדַּל","the Tower of"],
    ["בָּבֶל","Babel"],
    ["וְהֵם","and they are"],
    ["הַיָּרֶדִים","the Jaredites"],
  ], english:"The other came much earlier when the Lord confounded the tongues at the Tower of Babel. This group is known as the Jaredites."},
  { num:"ו", words:[
    ["וַיְהִי","and it came to pass"],
    ["אַחֲרֵי","after"],
    ["אַלְפֵי","thousands of"],
    ["שָׁנִים","years"],
    ["וַיִּשָּׁמְדוּ","and were destroyed"],
    ["כֻלָּם","all of them"],
    ["זוּלַת","except"],
    ["הַלָּמָנִים","the Lamanites"],
    ["אֲשֶׁר","who"],
    ["הֵם","they"],
    ["מֵאֲבוֹת","among the ancestors of"],
    ["יוֹשְׁבֵי","the inhabitants of"],
    ["אַמֶרִיקָה","America"],
    ["הַקַּדְמוֹנִים","the ancient"],
  ], english:"After thousands of years, all were destroyed except the Lamanites, and they are among the ancestors of the American Indians."},
  { num:"ז", words:[
    ["רֹאשׁ","the chief of"],
    ["הַמַּעֲשִׂים","the events"],
    ["הַכְּתוּבִים","recorded"],
    ["בַּסֵּפֶר","in the book"],
    ["הַזֶּה","this"],
    ["הוּא","is"],
    ["שֵׁרוּת","the ministry of"],
    ["הָאָדוֹן","the Lord"],
    ["יֵשׁוּעַ","Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["בְּעַצְמוֹ","personal"],
    ["בְּקֶרֶב","among"],
    ["הַנֶּפִיִּים","the Nephites"],
    ["מְעַט","soon"],
    ["אַחֲרֵי","after"],
    ["קוּמוֹ","His resurrection"],
    ["מִן־הַמֵּתִים","from the dead"],
  ], english:"The crowning event recorded in the Book of Mormon is the personal ministry of the Lord Jesus Christ among the Nephites soon after His resurrection."},
  { num:"ח", words:[
    ["וְהַסֵּפֶר","and the book"],
    ["מְבָאֵר","puts forth"],
    ["תּוֹרַת","the doctrines of"],
    ["הַבְּשׂוֹרָה","the gospel"],
    ["וּמַרְאֶה","and outlines"],
    ["אֶת־עֲצַת","the plan of"],
    ["הַיְשׁוּעָה","salvation"],
    ["וּמַגִּיד","and tells"],
    ["לִבְנֵי־אָדָם","men"],
    ["מַה־יַּעֲשׂוּ","what they must do"],
    ["לִמְצֹא","to gain"],
    ["שָׁלוֹם","peace"],
    ["בַּחַיִּים","in the life"],
    ["הָאֵלֶּה","this"],
    ["וּתְשׁוּעַת","and salvation"],
    ["עוֹלָמִים","eternal"],
    ["בַּחַיִּים","in the life"],
    ["הַבָּאִים","to come"],
  ], english:"It puts forth the doctrines of the gospel, outlines the plan of salvation, and tells men what they must do to gain peace in this life and eternal salvation in the life to come."},
  { num:"ט", words:[
    ["וַיְהִי","and it came to pass"],
    ["כַּאֲשֶׁר","when"],
    ["כִּלָּה","completed"],
    ["מוֹרְמוֹן","Mormon"],
    ["לִכְתֹּב","to write"],
    ["וַיִּתֵּן","and he gave"],
    ["אֶת־הַסֵּפֶר","the book"],
    ["לְמוֹרוֹנִי","to Moroni"],
    ["בְּנוֹ","his son"],
    ["וַיּוֹסֶף","and added"],
    ["מוֹרוֹנִי","Moroni"],
    ["דְּבָרִים","words"],
    ["מְעַטִּים","a few"],
    ["מִשֶּׁלּוֹ","of his own"],
    ["וַיִּטְמֹן","and hid up"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["בְּגִבְעַת","in the Hill"],
    ["כּוּמוֹרָה","Cumorah"],
  ], english:"After Mormon completed his writings, he delivered the account to his son Moroni, who added a few words of his own and hid up the plates in the Hill Cumorah."},
  { num:"י", words:[
    ["וַיְהִי","and it came to pass"],
    ["בְּעֶשְׂרִים","on the twenty"],
    ["וְאֶחָד","and first"],
    ["לַחֹדֶשׁ","of the month"],
    ["הַתְּשִׁיעִי","the ninth"],
    ["בִּשְׁנַת","in the year of"],
    ["אֶלֶף","one thousand"],
    ["וּשְׁמֹנֶה","and eight"],
    ["מֵאוֹת","hundred"],
    ["וְעֶשְׂרִים","and twenty"],
    ["וְשָׁלֹשׁ","and three"],
    ["וַיֵּרָא","and appeared"],
    ["מוֹרוֹנִי","Moroni"],
    ["הַהוּא","the same"],
    ["בִּכְבוֹדוֹ","glorified"],
    ["אַחֲרֵי","after"],
    ["תְחִיָּתוֹ","his resurrection"],
    ["אֶל־יוֹסֵף","unto Joseph"],
    ["סְמִית","Smith"],
    ["הַנָּבִיא","the prophet"],
    ["וַיּוֹרֵהוּ","and instructed him"],
    ["עַל־דְּבַר","upon the matter of"],
    ["הַסֵּפֶר","the book"],
    ["הָעַתִּיק","the ancient"],
    ["וְעַל־תַּרְגּוּמוֹ","and upon its translation"],
    ["לִשְׂפַת","into the language of"],
    ["הָאַנְגְּלִית","the English"],
  ], english:"On September 21, 1823, the same Moroni, then a glorified, resurrected being, appeared to the Prophet Joseph Smith and instructed him relative to the ancient record and its destined translation into the English language."},
  { num:"יא", words:[
    ["וַיְהִי","and it came to pass"],
    ["בְּמוֹעֵד","in due time"],
    ["נִתְּנוּ","were given"],
    ["הַלּוּחוֹת","the plates"],
    ["לְיוֹסֵף","to Joseph"],
    ["סְמִית","Smith"],
    ["וַיְתַרְגְּמֵם","and he translated them"],
    ["בְּמַתַּת־אֵל","by the gift of God"],
    ["וּבִגְבוּרָתוֹ","and by His power"],
  ], english:"In due course the plates were delivered to Joseph Smith, who translated them by the gift and power of God."},
  { num:"יב", words:[
    ["וְעַתָּה","and now"],
    ["יָצָא","has gone forth"],
    ["הַסֵּפֶר","the book"],
    ["בִּלְשׁוֹנוֹת","in tongues"],
    ["רַבּוֹת","many"],
    ["לִהְיוֹת","to be"],
    ["עֵד","a witness"],
    ["חָדָשׁ","new"],
    ["וְנוֹסָף","and additional"],
    ["כִּי","that"],
    ["יֵשׁוּעַ","Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["הוּא","is"],
    ["בֶּן־אֵל","the Son of God"],
    ["חַי","the living"],
    ["וְכִי","and that"],
    ["כׇּל־הַבָּאִים","all who come"],
    ["אֵלָיו","unto Him"],
    ["וְשֹׁמְרִים","and obey"],
    ["אֶת־תּוֹרוֹת","the laws of"],
    ["בְּשׂוֹרָתוֹ","His gospel"],
    ["וְחֻקּוֹתֶיהָ","and its ordinances"],
    ["יִוָּשֵׁעוּ","may be saved"],
  ], english:"The record is now published in many languages as a new and additional witness that Jesus Christ is the Son of the living God and that all who will come unto Him and obey the laws and ordinances of His gospel may be saved."},
  { num:"יג", words:[
    ["וְכֹה","and thus"],
    ["אָמַר","said"],
    ["יוֹסֵף","Joseph"],
    ["סְמִית","Smith"],
    ["הַנָּבִיא","the prophet"],
    ["עַל־הַסֵּפֶר","concerning the record"],
    ["הַזֶּה","this"],
    ["הִגַּדְתִּי","I told"],
    ["לָאַחִים","to the brethren"],
    ["כִּי","that"],
    ["סֵפֶר","the book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["הוּא","is"],
    ["הַסֵּפֶר","the book"],
    ["הַנָּכוֹן","the most correct"],
    ["מִכׇּל־סְפָרֵי","of any book on"],
    ["הָאָרֶץ","the earth"],
    ["וְאֶבֶן","and the stone of"],
    ["הָרֹאשָׁה","the head"],
    ["לֶאֱמוּנָתֵנוּ","of our religion"],
    ["וְכִי","and that"],
    ["יִקְרַב","would get nearer"],
    ["אָדָם","a man"],
    ["אֶל־הָאֱלֹהִים","to God"],
    ["בִּשְׁמִירַת","by abiding by"],
    ["מִצְוֹתָיו","its precepts"],
    ["יוֹתֵר","more"],
    ["מִכׇּל־סֵפֶר","than any book"],
    ["אַחֵר","other"],
  ], english:"Concerning this record the Prophet Joseph Smith said: “I told the brethren that the Book of Mormon was the most correct of any book on earth, and the keystone of our religion, and a man would get nearer to God by abiding by its precepts, than by any other book.”"},
  { num:"יד", words:[
    ["וּמִלְּבַד","in addition to"],
    ["יוֹסֵף","Joseph"],
    ["סְמִית","Smith"],
    ["נָתַן","gave"],
    ["יְהוָה","the Lord"],
    ["לְאַחַד","to eleven"],
    ["עָשָׂר","ten"],
    ["אֲנָשִׁים","men"],
    ["אֲחֵרִים","others"],
    ["לִרְאוֹת","to see"],
    ["אֶת־לוּחוֹת","the plates of"],
    ["הַזָּהָב","the gold"],
    ["בְּעֵינֵיהֶם","for themselves"],
    ["לִהְיוֹת","to be"],
    ["עֵדִים","witnesses"],
    ["מְיֻחָדִים","special"],
    ["לֶאֱמֶת","of the truth of"],
    ["הַסֵּפֶר","the book"],
    ["וּקְדֻשָּׁתוֹ","and its divinity"],
  ], english:"In addition to Joseph Smith, the Lord provided for eleven others to see the gold plates for themselves and to be special witnesses of the truth and divinity of the Book of Mormon."},
  { num:"טו", words:[
    ["וְעֵדוּתָם","and their testimony"],
    ["הַכְּתוּבָה","the written"],
    ["נִתְּנָה","are included"],
    ["בָּזֶה","herewith"],
    ["כְּעֵדוּת","as the Testimony of"],
    ["שְׁלֹשָׁה","three"],
    ["עֵדִים","witnesses"],
    ["וְעֵדוּת","and the testimony of"],
    ["שְׁמֹנָה","eight"],
    ["עֵדִים","witnesses"],
  ], english:"Their written testimonies are included herewith as “The Testimony of Three Witnesses” and “The Testimony of Eight Witnesses.”"},
  { num:"טז", words:[
    ["וְעַתָּה","and now"],
    ["קֹרְאִים","invite"],
    ["אֲנַחְנוּ","we"],
    ["לְכׇל־בְּנֵי","unto all the children of"],
    ["אָדָם","man"],
    ["בְּכׇל־מָקוֹם","everywhere"],
    ["לִקְרֹא","to read"],
    ["אֶת־סֵפֶר","the book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["וְלַהֲגוֹת","and to ponder"],
    ["בִּלְבָבָם","in their hearts"],
    ["אֶת־הַדְּבָרִים","the message"],
    ["הַכְּתוּבִים","contained"],
    ["בּוֹ","in it"],
    ["וְאַחַר","and then"],
    ["לִשְׁאֹל","to ask"],
    ["מֵאֵת","of"],
    ["הָאֱלֹהִים","God"],
    ["אֲבִי","the Father of"],
    ["הָעוֹלָמִים","the eternities"],
    ["בְּשֵׁם","in the name of"],
    ["הַמָּשִׁיחַ","Christ"],
    ["אִם","if"],
    ["אֱמֶת","true"],
    ["הַסֵּפֶר","the book"],
  ], english:"We invite all men everywhere to read the Book of Mormon, to ponder in their hearts the message it contains, and then to ask God, the Eternal Father, in the name of Christ if the book is true."},
  { num:"יז", words:[
    ["וְכׇל־הַהֹלְכִים","and all who pursue"],
    ["בַּדֶּרֶךְ","the course"],
    ["הַזֹּאת","this"],
    ["וְשׁוֹאֲלִים","and ask"],
    ["בֶּאֱמוּנָה","in faith"],
    ["יִזְכּוּ","will gain"],
    ["לְעֵדוּת","a testimony of"],
    ["אֲמִתּוֹ","its truth"],
    ["וּקְדֻשָּׁתוֹ","and its divinity"],
    ["בְּכֹחַ","by the power of"],
    ["רוּחַ","the Spirit of"],
    ["הַקֹּדֶשׁ","the Holy"],
  ], english:"Those who pursue this course and ask in faith will gain a testimony of its truth and divinity by the power of the Holy Ghost. (See Moroni 10:3–5.)"},
  { num:"יח", words:[
    ["וְכׇל־הַזּוֹכִים","and all who gain"],
    ["לְעֵדוּת","the testimony of"],
    ["אֱלֹהִים","God"],
    ["הַזֹּאת","this"],
    ["מֵרוּחַ","from the Spirit of"],
    ["הַקֹּדֶשׁ","the Holy"],
    ["יֵדְעוּ","they shall know"],
    ["גַם־בַּכֹּחַ","also by the power"],
    ["הַהוּא","the same"],
    ["כִּי","that"],
    ["יֵשׁוּעַ","Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["הוּא","is"],
    ["מוֹשִׁיעַ","the Savior of"],
    ["הָעוֹלָם","the world"],
    ["וְכִי","and that"],
    ["יוֹסֵף","Joseph"],
    ["סְמִית","Smith"],
    ["נְבִיאוֹ","His prophet"],
    ["וְחוֹזֵהוּ","and His revelator"],
    ["בַּיָּמִים","in the days"],
    ["הָאַחֲרוֹנִים","the latter"],
    ["הָאֵלֶּה","these"],
    ["וְכִי","and that"],
    ["עֲדַת","the Church of"],
    ["יֵשׁוּעַ","Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["לִקְדוֹשֵׁי","of the Saints of"],
    ["הַיָּמִים","the Days"],
    ["הָאַחֲרוֹנִים","the Latter"],
    ["הִיא","is"],
    ["מַמְלֶכֶת","the kingdom of"],
    ["יְהוָה","the Lord"],
    ["אֲשֶׁר","which"],
    ["הוּקְמָה","established"],
    ["שֵׁנִית","once again"],
    ["עַל־הָאָרֶץ","upon the earth"],
    ["לְהָכִין","preparatory to"],
    ["לְבִיאַת","the coming of"],
    ["הַמָּשִׁיחַ","the Messiah"],
    ["הַשֵּׁנִית","the second"],
  ], english:"Those who gain this divine witness from the Holy Spirit will also come to know by the same power that Jesus Christ is the Savior of the world, that Joseph Smith is His revelator and prophet in these last days, and that The Church of Jesus Christ of Latter-day Saints is the Lord’s kingdom once again established on the earth, preparatory to the Second Coming of the Messiah."},
];
var frontThreeWit = [

  // עדות שלשת העדים
  
  { num:"א", words:[
    ["יִוָּדַע","be it known"],
    ["לְכׇל־הַגּוֹיִם","unto all the nations"],
    ["וְהַמִּשְׁפָּחוֹת","and the kindreds"],
    ["וְהַלְּשׁוֹנוֹת","and the tongues"],
    ["וְהָעַמִּים","and the peoples"],
    ["אֲשֶׁר","which"],
    ["יַגִּיעַ","shall come"],
    ["אֲלֵיהֶם","unto them"],
    ["הַמַּעֲשֶׂה","the work"],
    ["הַזֶּה","this"],
  ], english:"Be it known unto all nations, kindreds, tongues, and people, unto whom this work shall come:"},
  { num:"ב", words:[
    ["כִּי","for"],
    ["אֲנַחְנוּ","we"],
    ["בְּחֶסֶד","by the grace of"],
    ["אֱלֹהִים","God"],
    ["הָאָב","the Father"],
    ["וַאֲדֹנֵנוּ","and our Lord"],
    ["יֵשׁוּעַ","Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["רָאִינוּ","we have seen"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["אֲשֶׁר","which"],
    ["בָּם","in them is"],
    ["הַזִּכָּרוֹן","the record"],
    ["הַזֶּה","this"],
    ["וְהוּא","and it is"],
    ["דִּבְרֵי","the record of"],
    ["יְמֵי","the days of"],
    ["עַם־נֶפִי","the people of Nephi"],
    ["וְגַם־הַלָּמָנִים","and also the Lamanites"],
    ["אֲחֵיהֶם","their brethren"],
    ["וְגַם","and also"],
    ["עַם־יֶרֶד","the people of Jared"],
    ["אֲשֶׁר־בָּאוּ","who came"],
    ["מִן־הַמִּגְדָּל","from the tower"],
    ["אֲשֶׁר","which"],
    ["דֻּבַּר","was spoken"],
    ["בּוֹ","of it"],
  ], english:"That we, through the grace of God the Father, and our Lord Jesus Christ, have seen the plates which contain this record, which is a record of the people of Nephi, and also of the Lamanites, their brethren, and also of the people of Jared, who came from the tower of which hath been spoken."},
  { num:"ג", words:[
    ["וְגַם־יָדַעְנוּ","and also we know"],
    ["כִּי","that"],
    ["תֻרְגְּמוּ","they were translated"],
    ["בְּמַתַּת־אֵל","by the gift of God"],
    ["וּבִגְבוּרָתוֹ","and by His power"],
    ["כִּי","for"],
    ["קוֹלוֹ","His voice"],
    ["הִגִּיד","declared"],
    ["לָנוּ","unto us"],
    ["זֹאת","this"],
    ["וְעַל־כֵּן","and therefore"],
    ["יָדַעְנוּ","we know"],
    ["לְבֶטַח","of a surety"],
    ["כִּי","that"],
    ["אֱמֶת","true"],
    ["הַמַּעֲשֶׂה","the work"],
  ], english:"And we also know that they have been translated by the gift and power of God, for his voice hath declared it unto us; wherefore we know of a surety that the work is true."},
  { num:"ד", words:[
    ["וְגַם","and also"],
    ["מְעִידִים","testify"],
    ["אֲנַחְנוּ","we"],
    ["כִּי","that"],
    ["רָאִינוּ","we have seen"],
    ["אֶת־הַמִּכְתָּב","the engravings"],
    ["אֲשֶׁר","which"],
    ["עַל־הַלּוּחוֹת","upon the plates"],
    ["וְהֵם","and they"],
    ["הָרְאוּ","have been shown"],
    ["לָנוּ","unto us"],
    ["בְּכֹחַ","by the power of"],
    ["אֱלֹהִים","God"],
    ["וְלֹא","and not"],
    ["בְּכֹחַ","by the power of"],
    ["אָדָם","man"],
  ], english:"And we also testify that we have seen the engravings which are upon the plates; and they have been shown unto us by the power of God, and not of man."},
  { num:"ה", words:[
    ["וּמַגִּידִים","and declare"],
    ["אֲנַחְנוּ","we"],
    ["בְּדִבְרֵי","with the words of"],
    ["יִרְאָה","soberness"],
    ["כִּי","that"],
    ["מַלְאַךְ","an angel of"],
    ["אֱלֹהִים","God"],
    ["יָרַד","came down"],
    ["מִן־הַשָּׁמַיִם","from the heavens"],
    ["וַיָּבֵא","and he brought"],
    ["וַיָּשֶׂם","and laid"],
    ["לְפָנֵינוּ","before us"],
    ["וַנַּבִּיט","and we beheld"],
    ["וַנֵּרֶא","and we saw"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["וְאֶת־הַמִּכְתָּב","and the engravings"],
    ["אֲשֶׁר","which"],
    ["עֲלֵיהֶם","upon them"],
  ], english:"And we declare with words of soberness, that an angel of God came down from heaven, and he brought and laid before our eyes, that we beheld and saw the plates, and the engravings thereon;"},
  { num:"ו", words:[
    ["וְיָדַעְנוּ","and we know"],
    ["כִּי","that"],
    ["בְּחֶסֶד","by the grace of"],
    ["אֱלֹהִים","God"],
    ["הָאָב","the Father"],
    ["וַאֲדֹנֵנוּ","and our Lord"],
    ["יֵשׁוּעַ","Jesus"],
    ["הַמָּשִׁיחַ","Christ"],
    ["רָאִינוּ","we saw"],
    ["וּמְעִידִים","and bear record"],
    ["כִּי","that"],
    ["אֱמֶת","true"],
    ["הַדְּבָרִים","the things"],
    ["הָאֵלֶּה","these"],
    ["וְנִפְלָאִים","and marvelous"],
    ["הֵם","they"],
    ["בְּעֵינֵינוּ","in our eyes"],
  ], english:"and we know that it is by the grace of God the Father, and our Lord Jesus Christ, that we beheld and bear record that these things are true. And it is marvelous in our eyes."},
  { num:"ז", words:[
    ["אָכֵן","nevertheless"],
    ["קוֹל־יְהוָה","the voice of the Lord"],
    ["צִוָּה","commanded"],
    ["עָלֵינוּ","upon us"],
    ["לְהָעִיד","to bear witness"],
    ["עָלָיו","of it"],
    ["וְלָכֵן","and therefore"],
    ["לִשְׁמֹעַ","to be obedient"],
    ["בְּקוֹל","unto the voice of"],
    ["מִצְוֹת־אֱלֹהִים","the commandments of God"],
    ["מְעִידִים","testify"],
    ["אֲנַחְנוּ","we"],
    ["עַל־הַדְּבָרִים","upon the things"],
    ["הָאֵלֶּה","these"],
  ], english:"Nevertheless, the voice of the Lord commanded us that we should bear record of it; wherefore, to be obedient unto the commandments of God, we bear testimony of these things."},
  { num:"ח", words:[
    ["וְיָדַעְנוּ","and we know"],
    ["כִּי־אִם","that if"],
    ["נֶאֱמָנִים","we are faithful"],
    ["בַּמָּשִׁיחַ","in Christ"],
    ["נְנַקֶּה","we shall rid"],
    ["בְּגָדֵינוּ","our garments"],
    ["מִדַּם","of the blood of"],
    ["כׇּל־אָדָם","all men"],
    ["וְנִמָּצֵא","and be found"],
    ["טְהוֹרִים","spotless"],
    ["לִפְנֵי","before"],
    ["כִּסֵּא־מִשְׁפַּט","the judgment-seat of"],
    ["הַמָּשִׁיחַ","Christ"],
    ["וְנֵשֵׁב","and dwell"],
    ["עִמּוֹ","with Him"],
    ["לָנֶצַח","forever"],
    ["בַּשָּׁמָיִם","in the heavens"],
  ], english:"And we know that if we are faithful in Christ, we shall rid our garments of the blood of all men, and be found spotless before the judgment-seat of Christ, and shall dwell with him eternally in the heavens."},
  { num:"ט", words:[
    ["וְהַכָּבוֹד","and the honor"],
    ["לָאָב","unto the Father"],
    ["וְלַבֵּן","and to the Son"],
    ["וּלְרוּחַ","and to the Ghost of"],
    ["הַקֹּדֶשׁ","the Holy"],
    ["אֲשֶׁר","who"],
    ["הֵם","they"],
    ["אֵל","God"],
    ["אֶחָד","one"],
    ["אָמֵן","amen"],
  ], english:"And the honor be to the Father, and to the Son, and to the Holy Ghost, which is one God. Amen. — Oliver Cowdery, David Whitmer, Martin Harris"},
];
var frontEightWit = [

  // עדות שמונה עדים
  
  { num:"א", words:[
    ["יִוָּדַע","be it known"],
    ["לְכׇל־הַגּוֹיִם","unto all the nations"],
    ["וְהַמִּשְׁפָּחוֹת","and the kindreds"],
    ["וְהַלְּשׁוֹנוֹת","and the tongues"],
    ["וְהָעַמִּים","and the peoples"],
    ["אֲשֶׁר","which"],
    ["יַגִּיעַ","shall come"],
    ["אֲלֵיהֶם","unto them"],
    ["הַמַּעֲשֶׂה","the work"],
    ["הַזֶּה","this"],
  ], english:"Be it known unto all nations, kindreds, tongues, and people, unto whom this work shall come:"},
  { num:"ב", words:[
    ["כִּי","for"],
    ["יוֹסֵף","Joseph"],
    ["סְמִית","Smith"],
    ["הַצָּעִיר","the younger"],
    ["הַמְתַרְגֵּם","the translator of"],
    ["אֶת־הַמַּעֲשֶׂה","the work"],
    ["הַזֶּה","this"],
    ["הֶרְאָה","has shown"],
    ["לָנוּ","unto us"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["אֲשֶׁר","which"],
    ["דֻּבַּר","were spoken"],
    ["בָּהֶם","in them"],
    ["וּמַרְאֵיהֶם","and their appearance"],
    ["כְּמַרְאֵה","as the appearance of"],
    ["זָהָב","gold"],
  ], english:"That Joseph Smith, Jun., the translator of this work, has shown unto us the plates of which hath been spoken, which have the appearance of gold;"},
  { num:"ג", words:[
    ["וְכׇל־הַדַּפִּים","and all the leaves"],
    ["אֲשֶׁר","which"],
    ["תִּרְגֵּם","translated"],
    ["סְמִית","Smith"],
    ["הַנִּזְכָּר","the said"],
    ["מָשַׁשְׁנוּ","we have handled"],
    ["בְּיָדֵינוּ","in our hands"],
    ["וְגַם","and also"],
    ["רָאִינוּ","we saw"],
    ["אֶת־הַמִּכְתָּב","the engravings"],
    ["אֲשֶׁר","which"],
    ["עֲלֵיהֶם","upon them"],
    ["וְכֻלָּם","and all"],
    ["כְּמַעֲשֵׂה","as the work of"],
    ["קֶדֶם","old"],
    ["וּמְלֶאכֶת","and workmanship"],
    ["מַחֲשָׁבֶת","curious"],
  ], english:"and as many of the leaves as the said Smith has translated we did handle with our hands; and we also saw the engravings thereon, all of which has the appearance of ancient work, and of curious workmanship."},
  { num:"ד", words:[
    ["וְעַל־זֹאת","and upon this"],
    ["מְעִידִים","testify"],
    ["אֲנַחְנוּ","we"],
    ["בְּדִבְרֵי","with the words of"],
    ["יִרְאָה","soberness"],
    ["כִּי","that"],
    ["סְמִית","Smith"],
    ["הַנִּזְכָּר","the said"],
    ["הֶרְאָה","has shown"],
    ["לָנוּ","unto us"],
    ["כִּי","for"],
    ["רָאִינוּ","we saw"],
    ["וְהֵרַמְנוּ","and we hefted"],
    ["וְיָדַעְנוּ","and we know"],
    ["לְבֶטַח","of a surety"],
    ["כִּי","that"],
    ["סְמִית","Smith"],
    ["הַנִּזְכָּר","the said"],
    ["הִשִּׂיג","has obtained"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["אֲשֶׁר","which"],
    ["דִּבַּרְנוּ","we have spoken of"],
  ], english:"And this we bear record with words of soberness, that the said Smith has shown unto us, for we have seen and hefted, and know of a surety that the said Smith has got the plates of which we have spoken."},
  { num:"ה", words:[
    ["וְנֹתְנִים","and give"],
    ["אֲנַחְנוּ","we"],
    ["אֶת־שְׁמוֹתֵינוּ","our names"],
    ["לָעוֹלָם","unto the world"],
    ["לְהָעִיד","to witness"],
    ["לָעוֹלָם","unto the world"],
    ["אֶת־אֲשֶׁר","that which"],
    ["רָאִינוּ","we have seen"],
    ["וְלֹא","and not"],
    ["נְכַזֵּב","do we lie"],
    ["וֵאלֹהִים","and God"],
    ["עֵד","is witness"],
    ["בָּזֶה","herein"],
  ], english:"And we give our names unto the world, to witness unto the world that which we have seen. And we lie not, God bearing witness of it. — Christian Whitmer, Jacob Whitmer, Peter Whitmer, Jun., John Whitmer, Hiram Page, Joseph Smith, Sen., Hyrum Smith, Samuel H. Smith"},
];
renderVerseSet(frontIntro, 'front-translator-verses');
renderVerseSet(frontTitle, 'front-titlepage-verses');
renderVerseSet(frontIntroduction, 'front-introduction-verses');
renderVerseSet(frontThreeWit, 'front-three-verses');
renderVerseSet(frontEightWit, 'front-eight-verses');
var frontJST = [
  { num:"א", words:[
    ["אֵלֶּה","these are"],
    ["דִּבְרֵי","the words of"],
    ["יוֹסֵף","Joseph"],
    ["סְמִית","Smith"],
    ["הַנָּבִיא","the prophet"],
    ["עַל־דְּבַר","upon the matter of"],
    ["הִגָּלוֹת","the coming forth of"],
    ["סֵפֶר","the book of"],
    ["מוֹרְמוֹן","Mormon"],
  ], english:"The Prophet Joseph Smith’s own words about the coming forth of the Book of Mormon are:"},
  { num:"ב", words:[
    ["וַיְהִי","and it came to pass"],
    ["בָּעֶרֶב","in the evening"],
    ["בְּעֶשְׂרִים","on the twenty"],
    ["וְאֶחָד","and first"],
    ["לַחֹדֶשׁ","of the month"],
    ["הַתְּשִׁיעִי","the ninth"],
    ["וָאֶפְנֶה","and I turned"],
    ["לִתְפִלָּה","to prayer"],
    ["וְתַחֲנוּנִים","and supplication"],
    ["אֶל־אֵל","unto God"],
    ["שַׁדַּי","Almighty"],
  ], english:"“On the evening of the … twenty-first of September [1823] … I betook myself to prayer and supplication to Almighty God. …"},
  { num:"ג", words:[
    ["וַיְהִי","and it came to pass"],
    ["בְּהִתְפַּלְלִי","as I prayed"],
    ["אֶל־אֱלֹהִים","unto God"],
    ["וָאֵרֶא","and I saw"],
    ["אוֹר","a light"],
    ["נִרְאֶה","appearing"],
    ["בְּחַדְרִי","in my room"],
    ["וַיֵּלֶךְ","and it continued"],
    ["הָאוֹר","the light"],
    ["וְאוֹר","to increase"],
    ["עַד־כִּי","until"],
    ["הֵאִיר","was lighter"],
    ["הַחֶדֶר","the room"],
    ["מִצׇּהֳרַיִם","than at noonday"],
    ["וְהִנֵּה","and behold"],
    ["אִישׁ","a personage"],
    ["עֹמֵד","standing"],
    ["לְיַד־מִטָּתִי","at my bedside"],
    ["וְרַגְלָיו","for his feet"],
    ["לֹא־נָגְעוּ","did not touch"],
    ["בָּאָרֶץ","the floor"],
  ], english:"“While I was thus in the act of calling upon God, I discovered a light appearing in my room, which continued to increase until the room was lighter than at noonday, when immediately a personage appeared at my bedside, standing in the air, for his feet did not touch the floor."},
  { num:"ד", words:[
    ["וְעָלָיו","and upon him"],
    ["מְעִיל","a robe"],
    ["רָחָב","loose"],
    ["לָבָן","white"],
    ["מִכֹּל","beyond all"],
    ["אֲשֶׁר","that which"],
    ["רָאִיתִי","I had seen"],
    ["עַל־הָאָרֶץ","upon the earth"],
    ["וְלֹא־אַאֲמִין","and not I believe"],
    ["כִּי","that"],
    ["יוּכַל","could"],
    ["דָּבָר","thing"],
    ["עַל־הָאָרֶץ","upon the earth"],
    ["לְהֵרָאוֹת","to appear"],
    ["כֹּה","so"],
    ["לָבָן","white"],
    ["וּמַזְהִיר","and brilliant"],
  ], english:"“He had on a loose robe of most exquisite whiteness. It was a whiteness beyond anything earthly I had ever seen; nor do I believe that any earthly thing could be made to appear so exceedingly white and brilliant."},
  { num:"ה", words:[
    ["יָדָיו","his hands"],
    ["עֲרֻמּוֹת","naked"],
    ["וּזְרֹעוֹתָיו","and his arms"],
    ["עַד־לְמַעְלָה","a little above"],
    ["מִכַּף־יָדוֹ","the wrist"],
    ["וְכֵן","and also"],
    ["רַגְלָיו","his feet"],
    ["עֲרֻמּוֹת","naked"],
    ["וְשׁוֹקָיו","and his legs"],
    ["עַד־לְמַעְלָה","a little above"],
    ["מֵהַקַּרְסֻלַּיִם","the ankles"],
    ["רֹאשׁוֹ","his head"],
    ["וְצַוָּארוֹ","and his neck"],
    ["חֲשׂוּפִים","were bare"],
  ], english:"His hands were naked, and his arms also, a little above the wrist; so, also, were his feet naked, as were his legs, a little above the ankles. His head and neck were also bare."},
  { num:"ו", words:[
    ["וָאֵרֶא","and I saw"],
    ["כִּי","that"],
    ["אֵין","there was not"],
    ["עָלָיו","upon him"],
    ["בֶּגֶד","clothing"],
    ["זוּלַת","except"],
    ["הַמְּעִיל","the robe"],
    ["הַזֶּה","this"],
    ["כִּי","for"],
    ["פָתוּחַ","open"],
    ["הָיָה","it was"],
    ["וָאֵרֶא","and I saw"],
    ["אֶת־חָזֵהוּ","into his bosom"],
  ], english:"I could discover that he had no other clothing on but this robe, as it was open, so that I could see into his bosom."},
  { num:"ז", words:[
    ["וְלֹא","and not"],
    ["רַק","only"],
    ["מְעִילוֹ","his robe"],
    ["הָיָה","was"],
    ["לָבָן","white"],
    ["מְאֹד","exceedingly"],
    ["כִּי","but"],
    ["גַם־כׇּל־גּוּפוֹ","also all his person"],
    ["נִכְבָּד","was glorious"],
    ["מִלְּתָאֵר","beyond description"],
    ["וּפָנָיו","and his countenance"],
    ["כְּבָרָק","as lightning"],
    ["וְהַחֶדֶר","and the room"],
    ["מֵאִיר","was light"],
    ["מְאֹד","exceedingly"],
    ["אַךְ","but"],
    ["לֹא","not"],
    ["כְּאוֹר","as the light"],
    ["אֲשֶׁר","which was"],
    ["סְבִיבוֹתָיו","around him"],
  ], english:"“Not only was his robe exceedingly white, but his whole person was glorious beyond description, and his countenance truly like lightning. The room was exceedingly light, but not so very bright as immediately around his person."},
  { num:"ח", words:[
    ["וַיְהִי","and it came to pass"],
    ["כַּאֲשֶׁר","when"],
    ["רְאִיתִיו","I saw him"],
    ["בָּרִאשׁוֹנָה","at first"],
    ["וָאִירָא","and I feared"],
    ["אַךְ","but"],
    ["חִישׁ","quickly"],
    ["סָר","departed"],
    ["הַפַּחַד","the fear"],
    ["מִמֶּנִּי","from me"],
  ], english:"When I first looked upon him, I was afraid; but the fear soon left me."},
  { num:"ט", words:[
    ["וַיִּקְרָא","and called"],
    ["בִשְׁמִי","me by name"],
    ["וַיֹּאמֶר","and said"],
    ["אֵלַי","unto me"],
    ["כִּי","that"],
    ["מַלְאָךְ","an angel"],
    ["הוּא","he was"],
    ["שָׁלוּחַ","sent"],
    ["מִלִּפְנֵי","from the presence of"],
    ["אֱלֹהִים","God"],
    ["אֵלַי","unto me"],
    ["וּשְׁמוֹ","and his name"],
    ["מוֹרוֹנִי","Moroni"],
  ], english:"“He called me by name, and said unto me that he was a messenger sent from the presence of God to me, and that his name was Moroni;"},
  { num:"י", words:[
    ["וְכִי","and that"],
    ["יֵשׁ","there was"],
    ["לֵאלֹהִים","for God"],
    ["מְלָאכָה","a work"],
    ["לִי","for me"],
    ["לַעֲשׂוֹת","to do"],
    ["וְכִי","and that"],
    ["יִהְיֶה","shall be"],
    ["שְׁמִי","my name"],
    ["לְטוֹב","for good"],
    ["וּלְרָע","and for evil"],
    ["בְּכׇל־הַגּוֹיִם","among all the nations"],
    ["וְהַמִּשְׁפָּחוֹת","and the kindreds"],
    ["וְהַלְּשׁוֹנוֹת","and the tongues"],
    ["אוֹ","or"],
    ["כִּי","that"],
    ["יְדַבְּרוּ","they would speak"],
    ["בִּי","of me"],
    ["לְטוֹב","for good"],
    ["וּלְרָע","and for evil"],
    ["בְּכׇל־הָעַמִּים","among all the peoples"],
  ], english:"that God had a work for me to do; and that my name should be had for good and evil among all nations, kindreds, and tongues, or that it should be both good and evil spoken of among all people."},
  { num:"יא", words:[
    ["וַיֹּאמֶר","and he said"],
    ["כִּי־יֵשׁ","that there was"],
    ["סֵפֶר","a book"],
    ["טָמוּן","deposited"],
    ["כָּתוּב","written"],
    ["עַל־לוּחוֹת","upon plates of"],
    ["זָהָב","gold"],
    ["וּבוֹ","and in it"],
    ["דִּבְרֵי","the record of"],
    ["יְמֵי","the days of"],
    ["יוֹשְׁבֵי","the inhabitants of"],
    ["הָאָרֶץ","the land"],
    ["הַזֹּאת","this"],
    ["מִקֶּדֶם","from of old"],
    ["וּמְקוֹר","and the source of"],
    ["מוֹצָאָם","their origin"],
  ], english:"“He said there was a book deposited, written upon gold plates, giving an account of the former inhabitants of this continent, and the source from whence they sprang."},
  { num:"יב", words:[
    ["וַיֹּאמֶר","and he said"],
    ["גַּם־כִּי","also that"],
    ["בוֹ","in it"],
    ["מְלוֹא","the fullness of"],
    ["בְּשׂוֹרַת","the gospel of"],
    ["עוֹלָמִים","the everlasting"],
    ["כַּאֲשֶׁר","as"],
    ["נִתְּנָה","was delivered"],
    ["מֵאֵת","by"],
    ["הַמּוֹשִׁיעַ","the Savior"],
    ["לְיוֹשְׁבֵי","unto the inhabitants of"],
    ["הָאָרֶץ","the land"],
    ["הַקַּדְמוֹנִים","the ancient"],
  ], english:"He also said that the fulness of the everlasting Gospel was contained in it, as delivered by the Savior to the ancient inhabitants;"},
  { num:"יג", words:[
    ["וַיֹּאמֶר","and he said"],
    ["גַּם־כִּי","also that"],
    ["יֵשׁ","there were"],
    ["שְׁנֵי","two"],
    ["אֲבָנִים","stones"],
    ["בְּקַשְׁתוֹת","in bows of"],
    ["כֶּסֶף","silver"],
    ["וְהָאֲבָנִים","and the stones"],
    ["הָאֵלֶּה","these"],
    ["צְמוּדוֹת","fastened"],
    ["לְחֹשֶׁן","to a breastplate"],
    ["וְהֵם","and they"],
    ["הַנִּקְרָאִים","what is called"],
    ["אוּרִים","Urim"],
    ["וְתֻמִּים","and Thummim"],
    ["וְנִטְמְנוּ","deposited"],
    ["עִם־הַלּוּחוֹת","with the plates"],
  ], english:"“Also, that there were two stones in silver bows—and these stones, fastened to a breastplate, constituted what is called the Urim and Thummim—deposited with the plates;"},
  { num:"יד", words:[
    ["וַאֲשֶׁר","and whoever"],
    ["אָחַז","possessed"],
    ["בָּאֲבָנִים","the stones"],
    ["הָאֵלֶּה","these"],
    ["וַיִּשְׁתַּמֵּשׁ","and used"],
    ["בָּהֶן","them"],
    ["הוּא","he was"],
    ["אֲשֶׁר","that which"],
    ["נִקְרָא","was called"],
    ["רֹאֶה","a seer"],
    ["בִּימֵי","in the days of"],
    ["קֶדֶם","old"],
    ["וַאֲשֶׁר","and that"],
    ["הֱכִינָם","had prepared them"],
    ["אֱלֹהִים","God"],
    ["לְתַרְגֵּם","to translate"],
    ["אֶת־הַסֵּפֶר","the book"],
  ], english:"and the possession and use of these stones were what constituted ‘seers’ in ancient or former times; and that God had prepared them for the purpose of translating the book. …"},
  { num:"טו", words:[
    ["וַיּוֹסֶף","and again"],
    ["לֵאמֹר","he told me"],
    ["כִּי","that"],
    ["בְּהַשִּׂיגִי","when I obtained"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["אֲשֶׁר־דִּבֶּר","which he spoke"],
    ["בָּם","in them"],
    ["כִּי־עוֹד","that yet"],
    ["לֹא־מָלְאוּ","not had come"],
    ["הַיָּמִים","the days"],
    ["לְקַחְתָּם","to take them"],
    ["לֹא־אַרְאֵם","not should I show them"],
    ["לְאִישׁ","to any man"],
  ], english:"“Again, he told me, that when I got those plates of which he had spoken—for the time that they should be obtained was not yet fulfilled—I should not show them to any person;"},
  { num:"טז", words:[
    ["וְגַם","and also"],
    ["לֹא","not"],
    ["אֶת־הַחֹשֶׁן","the breastplate"],
    ["עִם־הָאוּרִים","with the Urim"],
    ["וְהַתֻּמִּים","and the Thummim"],
    ["זוּלַת","except"],
    ["לַאֲשֶׁר","unto those"],
    ["אֲצֻוֶּה","I should be commanded"],
    ["לְהַרְאוֹתָם","to show them"],
    ["וְאִם־אֶעֱשֶׂה","and if I do"],
    ["כֵן","so"],
    ["אָשָׁמֵד","I shall be destroyed"],
  ], english:"neither the breastplate with the Urim and Thummim; only to those to whom I should be commanded to show them; if I did I should be destroyed."},
  { num:"יז", words:[
    ["וַיְהִי","and it came to pass"],
    ["בְּדַבְּרוֹ","as he spoke"],
    ["עִמִּי","with me"],
    ["עַל־הַלּוּחוֹת","upon the plates"],
    ["וַיִּפָּתַח","and was opened"],
    ["חֲזוֹן","a vision"],
    ["לְעֵינַי","to my mind"],
    ["וָאֵרֶא","and I saw"],
    ["אֶת־הַמָּקוֹם","the place"],
    ["אֲשֶׁר","which"],
    ["נִטְמְנוּ","were deposited"],
    ["הַלּוּחוֹת","the plates"],
    ["וָאֵרֶא","and I saw"],
    ["בְּבֵרוּר","plainly"],
    ["עַד־כִּי","until"],
    ["הִכַּרְתִּי","I recognized"],
    ["אֶת־הַמָּקוֹם","the place"],
    ["בְּבוֹאִי","when I came"],
    ["שָׁמָּה","there"],
  ], english:"While he was conversing with me about the plates, the vision was opened to my mind that I could see the place where the plates were deposited, and that so clearly and distinctly that I knew the place again when I visited it."},
  { num:"יח", words:[
    ["וַיְהִי","and it came to pass"],
    ["אַחֲרֵי","after"],
    ["הַדְּבָרִים","the things"],
    ["הָאֵלֶּה","these"],
    ["וָאֵרֶא","and I saw"],
    ["אֶת־הָאוֹר","the light"],
    ["בַּחֶדֶר","in the room"],
    ["מִתְכַּנֵּס","gathering"],
    ["סְבִיב","around"],
    ["הָאִישׁ","the person of him"],
    ["הַדֹּבֵר","who had been speaking"],
    ["אֵלַי","to me"],
    ["וַיִּתְכַּנֵּס","and it gathered"],
    ["עַד־כִּי","until"],
    ["חָשַׁךְ","was left dark"],
    ["הַחֶדֶר","the room"],
    ["זוּלַת","except"],
    ["סְבִיבוֹתָיו","around him"],
  ], english:"“After this communication, I saw the light in the room begin to gather immediately around the person of him who had been speaking to me, and it continued to do so until the room was again left dark, except just around him;"},
  { num:"יט", words:[
    ["וּפִתְאֹם","and suddenly"],
    ["רָאִיתִי","I saw"],
    ["כְּצִנּוֹר","as a conduit"],
    ["נִפְתָּח","opened"],
    ["יָשָׁר","straight"],
    ["הַשָּׁמַיְמָה","unto the heavens"],
    ["וַיַּעַל","and he ascended"],
    ["בּוֹ","in it"],
    ["עַד־כִּי","until"],
    ["נֶעְלַם","he disappeared"],
    ["כֻּלּוֹ","entirely"],
    ["וַיִּשָּׁאֵר","and remained"],
    ["הַחֶדֶר","the room"],
    ["כַּאֲשֶׁר","as"],
    ["הָיָה","it was"],
    ["לִפְנֵי","before"],
    ["הוֹפִיעַ","appeared"],
    ["אוֹר","the light of"],
    ["הַשָּׁמַיִם","the heavens"],
  ], english:"when, instantly I saw, as it were, a conduit open right up into heaven, and he ascended till he entirely disappeared, and the room was left as it had been before this heavenly light had made its appearance."},
  { num:"כ", words:[
    ["וָאֶשְׁכַּב","and I lay"],
    ["הוֹגֶה","pondering"],
    ["בְּפֶלֶא","at the wonder of"],
    ["הַמַּרְאֶה","the vision"],
    ["וּמִשְׁתּוֹמֵם","and marveling"],
    ["מְאֹד","greatly"],
    ["עַל־כׇּל־אֲשֶׁר","upon all which"],
    ["הֻגַּד","it was declared"],
    ["לִי","to me"],
    ["מִפִּי","from the mouth of"],
    ["הַמַּלְאָךְ","the angel"],
    ["הַנִּפְלָא","the wondrous"],
    ["הַזֶּה","this"],
  ], english:"“I lay musing on the singularity of the scene, and marveling greatly at what had been told to me by this extraordinary messenger;"},
  { num:"כא", words:[
    ["וַיְהִי","and it came to pass"],
    ["בְּתוֹךְ","in the midst of"],
    ["הֲגִיגִי","my musing"],
    ["וּפִתְאֹם","and suddenly"],
    ["רָאִיתִי","I saw"],
    ["כִּי־חַדְרִי","that my room"],
    ["מֵחֵל","began"],
    ["לְהֵאוֹר","to light up"],
    ["שֵׁנִית","again"],
    ["וּכְרֶגַע","and in an instant"],
    ["וְהִנֵּה","and behold"],
    ["אוֹתוֹ","the same"],
    ["מַלְאַךְ","angel of"],
    ["שָׁמַיִם","the heavens"],
    ["עוֹמֵד","standing"],
    ["שֵׁנִית","again"],
    ["לְיַד־מִטָּתִי","beside my bed"],
  ], english:"when, in the midst of my meditation, I suddenly discovered that my room was again beginning to get lighted, and in an instant, as it were, the same heavenly messenger was again by my bedside."},
  { num:"כב", words:[
    ["וַיָּחֶל","and he commenced"],
    ["וַיְסַפֵּר","and related"],
    ["שֵׁנִית","again"],
    ["אֶת־כׇּל־הַדְּבָרִים","all the things"],
    ["אֲשֶׁר־דִּבֶּר","which he had spoken"],
    ["בְּבִקּוּרוֹ","in his visit"],
    ["הָרִאשׁוֹן","the first"],
    ["בְּלִי","without"],
    ["שִׁנּוּי","variation"],
  ], english:"“He commenced, and again related the very same things which he had done at his first visit, without the least variation;"},
  { num:"כג", words:[
    ["וּבְכַלּוֹתוֹ","and when he finished"],
    ["הוֹדִיעַ","made known"],
    ["לִי","me"],
    ["עַל־מִשְׁפָּטִים","upon judgments"],
    ["גְּדוֹלִים","great"],
    ["הַבָּאִים","which were coming"],
    ["עַל־הָאָרֶץ","upon the earth"],
    ["בְּרָעָב","by famine"],
    ["וּבְחֶרֶב","and with sword"],
    ["וּבְדֶבֶר","and with pestilence"],
    ["וְכִי","and that"],
    ["הַמִּשְׁפָּטִים","the judgments"],
    ["הַכְּבֵדִים","the grievous"],
    ["הָאֵלֶּה","these"],
    ["יָבוֹאוּ","would come"],
    ["בַּדּוֹר","in the generation"],
    ["הַזֶּה","this"],
  ], english:"which having done, he informed me of great judgments which were coming upon the earth, with great desolations by famine, sword, and pestilence; and that these grievous judgments would come on the earth in this generation."},
  { num:"כד", words:[
    ["וַיְהִי","and it came to pass"],
    ["כַּאֲשֶׁר","when"],
    ["כִּלָּה","he finished"],
    ["לְדַבֵּר","speaking"],
    ["וַיַּעַל","and he ascended"],
    ["שֵׁנִית","again"],
    ["כַּאֲשֶׁר","as"],
    ["עָשָׂה","he did"],
    ["בָּרִאשׁוֹנָה","at first"],
  ], english:"Having related these things, he again ascended as he had done before."},
  { num:"כה", words:[
    ["וּבָעֵת","and at that time"],
    ["הַהִיא","that"],
    ["כֹּה","so"],
    ["עָמְקוּ","deep were"],
    ["הַדְּבָרִים","the things"],
    ["בְּלִבִּי","in my heart"],
    ["עַד־כִּי","until"],
    ["נָדְדָה","fled"],
    ["שְׁנָתִי","sleep"],
    ["מֵעֵינַי","from my eyes"],
    ["וָאֶשְׁכַּב","and I lay"],
    ["מִשְׁתּוֹמֵם","overwhelmed"],
    ["עַל־אֲשֶׁר","upon which"],
    ["רָאִיתִי","I had seen"],
    ["וְשָׁמָעְתִּי","and heard"],
  ], english:"“By this time, so deep were the impressions made on my mind, that sleep had fled from my eyes, and I lay overwhelmed in astonishment at what I had both seen and heard."},
  { num:"כו", words:[
    ["אַךְ","but"],
    ["מַה־גָּדְלָה","how great was"],
    ["תְּמִיהָתִי","my surprise"],
    ["בִּרְאוֹתִי","when I beheld"],
    ["שֵׁנִית","again"],
    ["אֶת־הַמַּלְאָךְ","the same angel"],
    ["הַהוּא","that"],
    ["לְיַד־מִטָּתִי","beside my bed"],
    ["וָאֶשְׁמַע","and I heard"],
    ["אוֹתוֹ","him"],
    ["חוֹזֵר","rehearse"],
    ["וּמְשַׁנֶּה","and repeat"],
    ["אֶת־כׇּל־הַדְּבָרִים","all the things"],
    ["כְּמִקֹּדֶם","as before"],
  ], english:"But what was my surprise when again I beheld the same messenger at my bedside, and heard him rehearse or repeat over again to me the same things as before;"},
  { num:"כז", words:[
    ["וַיּוֹסֶף","and added"],
    ["לְהַזְהִירֵנִי","a caution to me"],
    ["לֵאמֹר","saying"],
    ["כִּי","that"],
    ["הַשָּׂטָן","the Adversary"],
    ["יְנַסֶּה","he would try"],
    ["לְפַתּוֹתֵנִי","to tempt me"],
    ["בַּעֲבוּר","because of"],
    ["דַּלּוּת","the poverty of"],
    ["בֵּית","the house of"],
    ["אָבִי","my father"],
    ["לָקַחַת","to take"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["לְמַעַן","that"],
    ["הֵעָשֵׁר","getting rich"],
  ], english:"and added a caution to me, telling me that Satan would try to tempt me (in consequence of the indigent circumstances of my father’s family), to get the plates for the purpose of getting rich."},
  { num:"כח", words:[
    ["וַיֶּאֱסֹר","and he forbade"],
    ["עָלַי","me"],
    ["זֹאת","this"],
    ["וַיֹּאמֶר","and said"],
    ["כִּי־אִם","that only"],
    ["לְכַבֵּד","to glorify"],
    ["אֶת־הָאֱלֹהִים","God"],
    ["בִּלְבָד","alone"],
    ["אָקַח","should I take"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["וּלְבִנְיַן","and for the building of"],
    ["מַלְכוּתוֹ","His kingdom"],
    ["לְבַד","only"],
    ["וְאִם־לֹא","and if not"],
    ["לֹא","not"],
    ["אוּכַל","I could"],
    ["לְקַבְּלָם","obtain them"],
  ], english:"This he forbade me, saying that I must have no other object in view in getting the plates but to glorify God, and must not be influenced by any other motive than that of building his kingdom; otherwise I could not get them."},
  { num:"כט", words:[
    ["וַיְהִי","and it came to pass"],
    ["אַחֲרֵי","after"],
    ["הַבִּקּוּר","the visit"],
    ["הַשְּׁלִישִׁי","the third"],
    ["וַיַּעַל","and he ascended"],
    ["הַשָּׁמַיְמָה","into the heavens"],
    ["כְּבָרִאשׁוֹנָה","as before"],
    ["וָאִוָּתֵר","and I was left"],
    ["שֵׁנִית","again"],
    ["לַהֲגוֹת","to ponder"],
    ["בְּפֶלֶא","at the wonder of"],
    ["הַדָּבָר","the thing"],
    ["אֲשֶׁר","which"],
    ["זֶה","this"],
    ["עַתָּה","now"],
    ["חָוִיתִי","I had experienced"],
  ], english:"“After this third visit, he again ascended into heaven as before, and I was again left to ponder on the strangeness of what I had just experienced;"},
  { num:"ל", words:[
    ["וַיְהִי","and it came to pass"],
    ["כִּמְעַט","nearly"],
    ["אַחֲרֵי","after"],
    ["עֲלוֹת","the ascending of"],
    ["מַלְאַךְ","angel of"],
    ["הַשָּׁמַיִם","the heavens"],
    ["מֵעָלַי","from me"],
    ["בַּפַּעַם","the time"],
    ["הַשְּׁלִישִׁית","the third"],
    ["וַיִּקְרָא","and crowed"],
    ["הַתַּרְנְגוֹל","the cock"],
    ["וָאֵדַע","and I found"],
    ["כִּי","that"],
    ["הַיּוֹם","the day"],
    ["קָרֵב","draws near"],
    ["וְכִי","and that"],
    ["הַשִּׂיחָה","the conversation"],
    ["נִמְשְׁכָה","had occupied"],
    ["כׇּל־הַלַּיְלָה","all the night"],
    ["הַהוּא","that"],
  ], english:"when almost immediately after the heavenly messenger had ascended from me for the third time, the cock crowed, and I found that day was approaching, so that our interviews must have occupied the whole of that night."},
  { num:"לא", words:[
    ["וָאָקוּם","and I arose"],
    ["מִמִּטָּתִי","from my bed"],
    ["וָאֵלֶךְ","and went"],
    ["כְּדַרְכִּי","as usual"],
    ["לַעֲבוֹדַת","to the labors of"],
    ["הַיּוֹם","the day"],
    ["אַךְ","but"],
    ["בְּנַסּוֹתִי","when I attempted"],
    ["לַעֲבֹד","to work"],
    ["כִּבְכׇל־יוֹם","as at other times"],
    ["וָאֶמְצָא","and I found"],
    ["אֶת־כֹּחִי","my strength"],
    ["אָזַל","so exhausted"],
    ["עַד־בִּלְתִּי","to the point of no"],
    ["יְכֹלֶת","ability"],
  ], english:"“I shortly after arose from my bed, and, as usual, went to the necessary labors of the day; but, in attempting to work as at other times, I found my strength so exhausted as to render me entirely unable."},
  { num:"לב", words:[
    ["וְאָבִי","and my father"],
    ["הָעֹבֵד","who was laboring"],
    ["עִמִּי","with me"],
    ["רָאָה","saw"],
    ["כִּי","that"],
    ["דָּבָר־מָה","something"],
    ["אֵינֶנּוּ","was not"],
    ["כַּשּׁוּרָה","right"],
    ["וַיֹּאמֶר","and told"],
    ["אֵלַי","me"],
    ["לָלֶכֶת","to go"],
    ["הַבַּיְתָה","home"],
  ], english:"My father, who was laboring along with me, discovered something to be wrong with me, and told me to go home."},
  { num:"לג", words:[
    ["וָאֵצֵא","and I started"],
    ["בְּכַוָּנָה","with the intention"],
    ["לָלֶכֶת","to go"],
    ["אֶל־הַבַּיִת","to the house"],
    ["אַךְ","but"],
    ["בְּנַסּוֹתִי","in attempting"],
    ["לַעֲבֹר","to cross"],
    ["אֶת־הַגָּדֵר","the fence"],
    ["מִן־הַשָּׂדֶה","out of the field"],
    ["אֲשֶׁר","which"],
    ["הָיִינוּ","we were"],
    ["בּוֹ","in it"],
    ["כָּלָה","failed"],
    ["כֹּחִי","my strength"],
    ["כֻּלּוֹ","entirely"],
    ["וָאֶפֹּל","and I fell"],
    ["אַרְצָה","to the ground"],
    ["חֲסַר","helpless"],
    ["אוֹנִים","strength"],
    ["וּלְעֵת־מָה","and for a time"],
    ["לֹא־יָדַעְתִּי","I knew not"],
    ["מְאוּמָה","anything"],
  ], english:"I started with the intention of going to the house; but, in attempting to cross the fence out of the field where we were, my strength entirely failed me, and I fell helpless on the ground, and for a time was quite unconscious of anything."},
  { num:"לד", words:[
    ["הַדָּבָר","the thing"],
    ["הָרִאשׁוֹן","the first"],
    ["אֲשֶׁר","that"],
    ["אֶזְכֹּר","I can recollect"],
    ["הוּא","was"],
    ["קוֹל","a voice"],
    ["הַקּוֹרֵא","calling"],
    ["אֵלַי","unto me"],
    ["בִּשְׁמִי","by name"],
    ["וָאֶשָּׂא","and I lifted"],
    ["עֵינַי","my eyes"],
    ["וָאֵרֶא","and beheld"],
    ["אֶת־אוֹתוֹ","the same"],
    ["הַמַּלְאָךְ","the angel"],
    ["עוֹמֵד","standing"],
    ["מֵעַל","over"],
    ["לְרֹאשִׁי","my head"],
    ["מֻקָּף","surrounded"],
    ["אוֹר","with light"],
    ["כְּבָרִאשׁוֹנָה","as before"],
  ], english:"“The first thing that I can recollect was a voice speaking unto me, calling me by name. I looked up, and beheld the same messenger standing over my head, surrounded by light as before."},
  { num:"לה", words:[
    ["וַיַּחְזֹר","and again he"],
    ["וַיְסַפֵּר","related"],
    ["לִי","unto me"],
    ["אֶת־כׇּל־אֲשֶׁר","all that"],
    ["סִפֵּר","he had related"],
    ["לִי","to me"],
    ["בַּלַּיְלָה","the night"],
    ["הַקּוֹדֵם","the previous"],
    ["וַיְצַוֵּנִי","and commanded me"],
    ["לָלֶכֶת","to go"],
    ["אֶל־אָבִי","to my father"],
    ["וּלְהַגִּיד","and tell"],
    ["לוֹ","him"],
    ["אֶת־הַחָזוֹן","the vision"],
    ["וְהַמִּצְוֹת","and the commandments"],
    ["אֲשֶׁר","which"],
    ["קִבַּלְתִּי","I had received"],
  ], english:"He then again related unto me all that he had related to me the previous night, and commanded me to go to my father and tell him of the vision and commandments which I had received."},
  { num:"לו", words:[
    ["וָאֶשְׁמַע","and I obeyed"],
    ["וָאָשׁוּב","and returned"],
    ["אֶל־אָבִי","to my father"],
    ["בַּשָּׂדֶה","in the field"],
    ["וָאֲסַפֵּר","and rehearsed"],
    ["לוֹ","to him"],
    ["אֶת־כׇּל","all"],
    ["הַדָּבָר","the thing"],
    ["וַיַּעַן","and he answered"],
    ["וַיֹּאמֶר","and said"],
    ["אֵלַי","unto me"],
    ["כִּי","that"],
    ["מֵאֱלֹהִים","from God"],
    ["הוּא","it was"],
    ["וַיֹּאמֶר","and told"],
    ["אֵלַי","me"],
    ["לָלֶכֶת","to go"],
    ["וְלַעֲשׂוֹת","and do"],
    ["כַּאֲשֶׁר","as"],
    ["צִוָּה","commanded"],
    ["הַמַּלְאָךְ","the angel"],
  ], english:"“I obeyed; I returned to my father in the field, and rehearsed the whole matter to him. He replied to me that it was of God, and told me to go and do as commanded by the messenger."},
  { num:"לז", words:[
    ["וָאֵצֵא","and I left"],
    ["מִן־הַשָּׂדֶה","from the field"],
    ["וָאֵלֵךְ","and went"],
    ["אֶל־הַמָּקוֹם","to the place"],
    ["אֲשֶׁר","which"],
    ["אָמַר","said"],
    ["אֵלַי","me"],
    ["הַמַּלְאָךְ","the angel"],
    ["כִּי","that"],
    ["שָׁם","there"],
    ["נִטְמְנוּ","were deposited"],
    ["הַלּוּחוֹת","the plates"],
    ["וּמֵרֹב","and because of"],
    ["בֵּרוּר","the distinctness of"],
    ["הֶחָזוֹן","the vision"],
    ["אֲשֶׁר","which"],
    ["רָאִיתִי","I had seen"],
    ["הִכַּרְתִּי","I recognized"],
    ["אֶת־הַמָּקוֹם","the place"],
    ["בְּרֶגַע","in the instant of"],
    ["בּוֹאִי","my arriving"],
    ["שָׁמָּה","there"],
  ], english:"I left the field, and went to the place where the messenger had told me the plates were deposited; and owing to the distinctness of the vision which I had had concerning it, I knew the place the instant that I arrived there."},
  { num:"לח", words:[
    ["קָרוֹב","near"],
    ["לִכְפַר","to the village of"],
    ["מַנְצֶ׳סְטֶר","Manchester"],
    ["בִּמְחוֹז","in the county of"],
    ["אוֹנְטָרִיוֹ","Ontario"],
    ["בִּמְדִינַת","in the state of"],
    ["נְיוֹ־יוֹרְק","New York"],
    ["עוֹמֶדֶת","stands"],
    ["גִּבְעָה","a hill"],
    ["גְדוֹלָה","great"],
    ["וְהִיא","and it is"],
    ["הַגְּבֹהָה","the highest"],
    ["מִכׇּל־הַגְּבָעוֹת","of all the hills"],
    ["בַּסְּבִיבָה","in the vicinity"],
  ], english:"“Convenient to the village of Manchester, Ontario county, New York, stands a hill of considerable size, and the most elevated of any in the neighborhood."},
  { num:"לט", words:[
    ["בְּצַד","on the side"],
    ["מַעֲרָב","west of"],
    ["הַגִּבְעָה","the hill"],
    ["לֹא־רָחוֹק","not far"],
    ["מֵרֹאשָׁהּ","from its top"],
    ["תַּחַת","under"],
    ["אֶבֶן","a stone"],
    ["גְּדוֹלָה","great"],
    ["נִטְמְנוּ","were deposited"],
    ["הַלּוּחוֹת","the plates"],
    ["בְּתֵבַת","in a box of"],
    ["אֶבֶן","stone"],
    ["הָאֶבֶן","the stone"],
    ["הַזֹּאת","this"],
    ["עָבָה","was thick"],
    ["וַעֲגֻלָּה","and rounding"],
    ["בְּתוֹכָהּ","in the middle"],
    ["מִלְמָעְלָה","on the upper side"],
    ["וְדַקָּה","and thinner"],
    ["אֶל־שְׂפָתֶיהָ","towards the edges"],
    ["עַד־כִּי","so that"],
    ["נִרְאָה","was visible"],
    ["תּוֹכָהּ","the middle part of it"],
    ["מֵעַל","above"],
    ["לָאָרֶץ","the ground"],
    ["אַךְ","but"],
    ["שְׂפָתָהּ","the edge"],
    ["סָבִיב","all around"],
    ["מְכֻסָּה","was covered"],
    ["עָפָר","with earth"],
  ], english:"On the west side of this hill, not far from the top, under a stone of considerable size, lay the plates, deposited in a stone box. This stone was thick and rounding in the middle on the upper side, and thinner towards the edges, so that the middle part of it was visible above the ground, but the edge all around was covered with earth."},
  { num:"מ", words:[
    ["וַיְהִי","and it came to pass"],
    ["כַּאֲשֶׁר","when"],
    ["הֲסִירוֹתִי","I had removed"],
    ["אֶת־הֶעָפָר","the earth"],
    ["וָאַשִּׂיג","and obtained"],
    ["מוֹט","a lever"],
    ["וָאָשִׂים","and placed it"],
    ["תַּחַת","under"],
    ["שׁוּלֵי","the edge of"],
    ["הָאֶבֶן","the stone"],
    ["וּבְמַאֲמָץ","and with effort"],
    ["מְעַט","a little"],
    ["הֵרַמְתִּיהָ","I raised it"],
    ["וָאַבֵּט","and I looked in"],
    ["פְּנִימָה","inside"],
    ["וְהִנֵּה","and behold"],
    ["רָאִיתִי","I saw"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["וְהָאוּרִים","and the Urim"],
    ["וְהַתֻּמִּים","and the Thummim"],
    ["וְהַחֹשֶׁן","and the breastplate"],
    ["כַּאֲשֶׁר","as"],
    ["אָמַר","said"],
    ["הַמַּלְאָךְ","the angel"],
    ["וְהַתֵּבָה","and the box"],
    ["אֲשֶׁר","in which"],
    ["שָׁכְבוּ","they lay"],
    ["בָּהּ","in it"],
    ["עֲשׂוּיָה","was formed"],
    ["מֵאֲבָנִים","of stones"],
    ["מְחֻבָּרוֹת","laid together"],
    ["בְּמִין","in some kind of"],
    ["טִיט","cement"],
    ["וּבְתַחְתִּית","and in the bottom of"],
    ["הַתֵּבָה","the box"],
    ["הוּנְחוּ","were laid"],
    ["שְׁתֵּי","two"],
    ["אֲבָנִים","stones"],
    ["לְרָחְבָּהּ","crossways of it"],
    ["וַעֲלֵיהֶן","and on them"],
    ["שָׁכְבוּ","lay"],
    ["הַלּוּחוֹת","the plates"],
    ["וְהַדְּבָרִים","and the things"],
    ["הָאֲחֵרִים","the other"],
    ["עִמָּהֶם","with them"],
  ], english:"“Having removed the earth, I obtained a lever, which I got fixed under the edge of the stone, and with a little exertion raised it up. I looked in, and there indeed did I behold the plates, the Urim and Thummim, and the breastplate, as stated by the messenger. The box in which they lay was formed by laying stones together in some kind of cement. In the bottom of the box were laid two stones crossways of the box, and on these stones lay the plates and the other things with them."},
  { num:"מא", words:[
    ["וָאֲנַסֶּה","and I made an attempt"],
    ["לְהוֹצִיאָם","to take them out"],
    ["אַךְ","but"],
    ["הַמַּלְאָךְ","the angel"],
    ["מְנָעַנִי","forbade me"],
    ["וַיּוֹדִיעֵנִי","and informed me"],
    ["שֵׁנִית","again"],
    ["כִּי־עוֹד","that yet"],
    ["לֹא־הִגִּיעָה","not had come"],
    ["הָעֵת","the time"],
    ["לְהוֹצִיאָם","to bring them forth"],
    ["וְלֹא","and would not"],
    ["תַגִּיעַ","come"],
    ["עַד","until"],
    ["אַרְבַּע","four"],
    ["שָׁנִים","years"],
    ["מֵהַיּוֹם","from the day"],
    ["הַזֶּה","this"],
  ], english:"“I made an attempt to take them out, but was forbidden by the messenger, and was again informed that the time for bringing them forth had not yet arrived, neither would it, until four years from that time;"},
  { num:"מב", words:[
    ["אַךְ","but"],
    ["אָמַר","said"],
    ["אֵלַי","me"],
    ["לָבוֹא","to come"],
    ["אֶל־הַמָּקוֹם","to the place"],
    ["הַזֶּה","this"],
    ["בְּדִיּוּק","precisely"],
    ["בְּעוֹד","in one"],
    ["שָׁנָה","year"],
    ["וְהוּא","and he"],
    ["יִפְגְּשֵׁנִי","he would meet me"],
    ["שָׁם","there"],
    ["וְכִי","and that"],
    ["אֶעֱשֶׂה","I do"],
    ["כֵּן","so"],
    ["עַד","until"],
    ["הַגִּיעַ","should come"],
    ["הָעֵת","the time"],
    ["לְקַבֵּל","to obtain"],
    ["אֶת־הַלּוּחוֹת","the plates"],
  ], english:"but he told me that I should come to that place precisely in one year from that time, and that he would there meet with me, and that I should continue to do so until the time should come for obtaining the plates."},
  { num:"מג", words:[
    ["וַיְהִי","and it came to pass"],
    ["כַּאֲשֶׁר","as"],
    ["צֻוֵּיתִי","I had been commanded"],
    ["הָלַכְתִּי","I went"],
    ["בְּתֹם","at the end of"],
    ["כׇּל־שָׁנָה","each year"],
    ["וּבְכׇל־פַּעַם","and at each time"],
    ["מָצָאתִי","I found"],
    ["שָׁם","there"],
    ["אֶת־אוֹתוֹ","the same"],
    ["הַמַּלְאָךְ","the angel"],
    ["וָאֲקַבֵּל","and received"],
    ["מִמֶּנּוּ","from him"],
    ["הוֹרָאוֹת","instruction"],
    ["וְדַעַת","and intelligence"],
    ["בְּכׇל־פְּגִישׁוֹתֵינוּ","at each of our interviews"],
    ["עַל־דְּבַר","respecting"],
    ["אֲשֶׁר","which"],
    ["יַעֲשֶׂה","was going to do"],
    ["יְהוָה","the Lord"],
    ["וְאֵיךְ","and how"],
    ["וּבְאֵיזֶה","and in which"],
    ["אֹפֶן","manner"],
    ["תִּתְנַהֵל","was to be conducted"],
    ["מַלְכוּתוֹ","His kingdom"],
    ["בַּיָּמִים","in the days"],
    ["הָאַחֲרוֹנִים","the latter"],
  ], english:"“Accordingly, as I had been commanded, I went at the end of each year, and at each time I found the same messenger there, and received instruction and intelligence from him at each of our interviews, respecting what the Lord was going to do, and how and in what manner his kingdom was to be conducted in the last days. …"},
  { num:"מד", words:[
    ["וַיְהִי","and it came to pass"],
    ["כַּאֲשֶׁר","when"],
    ["הִגִּיעָה","had come"],
    ["הָעֵת","the time"],
    ["לְקַבֵּל","to obtain"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["וְאֶת־הָאוּרִים","and the Urim"],
    ["וְהַתֻּמִּים","and the Thummim"],
    ["וְאֶת","and"],
    ["הַחֹשֶׁן","the breastplate"],
    ["בְּיוֹם","on the day of"],
    ["עֶשְׂרִים","the twenty"],
    ["וּשְׁנַיִם","and second"],
    ["לַחֹדֶשׁ","of the month"],
    ["הַתְּשִׁיעִי","the ninth"],
    ["בִּשְׁנַת","in the year"],
    ["אֶלֶף","one thousand"],
    ["וּשְׁמֹנֶה","and eight"],
    ["מֵאוֹת","hundred"],
    ["וְעֶשְׂרִים","and twenty"],
    ["וָשֶׁבַע","and seven"],
    ["הָלַכְתִּי","I went"],
    ["כְּמִנְהָגִי","as usual"],
    ["אֶל־הַמָּקוֹם","to the place"],
    ["אֲשֶׁר","which"],
    ["נִטְמְנוּ","they were deposited"],
    ["בוֹ","in it"],
    ["וַיִּתְּנֵם","delivered them up"],
    ["אֵלַי","unto me"],
    ["אוֹתוֹ","the same"],
    ["מַלְאַךְ","angel of"],
    ["הַשָּׁמַיִם","the heavens"],
    ["וַיְצַוֵּנִי","with this charge"],
    ["לֵאמֹר","saying"],
    ["כִּי","that"],
    ["עָלַי","I should be responsible"],
    ["לְשׇׁמְרָם","for them"],
    ["וְכִי","and that"],
    ["אִם־אַנִּיחֵם","if I should let them go"],
    ["בְּלִי־מִשְׁמָר","carelessly"],
    ["אוֹ","or"],
    ["בְּרִפְיוֹן","through neglect of"],
    ["יָדַי","mine"],
    ["אֶכָּרֵת","I should be cut off"],
    ["אַךְ","but"],
    ["אִם־אֶשְׁקֹד","if I would use all my endeavors"],
    ["בְּכׇל־כֹּחִי","with all my might"],
    ["לְשׇׁמְרָם","to preserve them"],
    ["עַד","until"],
    ["אֲשֶׁר","when"],
    ["יִדְרְשֵׁם","should call for them"],
    ["הַמַּלְאָךְ","the messenger"],
    ["יִשָּׁמְרוּ","they should be protected"],
  ], english:"“At length the time arrived for obtaining the plates, the Urim and Thummim, and the breastplate. On the twenty-second day of September, one thousand eight hundred and twenty-seven, having gone as usual at the end of another year to the place where they were deposited, the same heavenly messenger delivered them up to me with this charge: that I should be responsible for them; that if I should let them go carelessly, or through any neglect of mine, I should be cut off; but that if I would use all my endeavors to preserve them, until he, the messenger, should call for them, they should be protected."},
  { num:"מה", words:[
    ["מְהֵרָה","soon"],
    ["נוֹדַע","it became known"],
    ["לִי","to me"],
    ["הַטַּעַם","the reason"],
    ["אֲשֶׁר","which"],
    ["בִּגְלָלוֹ","for which"],
    ["קִבַּלְתִּי","I had received"],
    ["צַוִּים","commands"],
    ["כֹּה","so"],
    ["חֲמוּרִים","strict"],
    ["לְשׇׁמְרָם","to keep them safe"],
    ["וְלָמָּה","and why"],
    ["אָמַר","said"],
    ["הַמַּלְאָךְ","the angel"],
    ["כִּי","that"],
    ["כַּאֲשֶׁר","when"],
    ["אֶעֱשֶׂה","I do"],
    ["אֶת־אֲשֶׁר","which"],
    ["נִדְרַשׁ","was required"],
    ["מִיָּדִי","at my hand"],
    ["יָבוֹא","he would come"],
    ["לְקַחְתָּם","for them"],
  ], english:"“I soon found out the reason why I had received such strict charges to keep them safe, and why it was that the messenger had said that when I had done what was required at my hand, he would call for them."},
  { num:"מו", words:[
    ["כִּי","for"],
    ["כַּאֲשֶׁר","when"],
    ["נוֹדַע","was it known"],
    ["כִּי","that"],
    ["הֵם","they were"],
    ["בְּיָדִי","in my hand"],
    ["הֵחֵלּוּ","began"],
    ["מַאֲמָצִים","efforts"],
    ["כְּבֵדִים","strenuous"],
    ["לְקַחְתָּם","to get them"],
    ["מִמֶּנִּי","from me"],
    ["כׇּל־תַּחְבּוּלָה","every stratagem"],
    ["אֲשֶׁר","that"],
    ["יָכְלוּ","could be"],
    ["לַחְשֹׁב","devised"],
    ["הוּשְׂמָה","was resorted to"],
    ["לַמַּטָּרָה","for the purpose"],
    ["הַזֹּאת","this"],
  ], english:"For no sooner was it known that I had them, than the most strenuous exertions were used to get them from me. Every stratagem that could be invented was resorted to for that purpose."},
  { num:"מז", words:[
    ["הָרְדִיפָה","the persecution"],
    ["נַעֲשְׂתָה","became"],
    ["מָרָה","bitter"],
    ["וַחֲזָקָה","and severe"],
    ["מִבָּרִאשׁוֹנָה","than before"],
    ["וַהֲמוֹנִים","and multitudes"],
    ["הָיוּ","were"],
    ["עַל־הַמִּשְׁמָר","on the alert"],
    ["תָּמִיד","continually"],
    ["לְקַחְתָּם","to get them"],
    ["מִמֶּנִּי","from me"],
    ["אִם־יוּכְלוּ","if they could"],
    ["אַךְ","but"],
    ["בְּחׇכְמַת","by the wisdom of"],
    ["אֱלֹהִים","God"],
    ["נִשְׁמְרוּ","were preserved"],
    ["בְּיָדַי","in my hands"],
    ["עַד־אֲשֶׁר","until"],
    ["הִשְׁלַמְתִּי","I had accomplished"],
    ["בָּהֶם","by them"],
    ["אֶת־אֲשֶׁר","which"],
    ["נִדְרַשׁ","was required"],
    ["מִיָּדִי","at my hand"],
  ], english:"The persecution became more bitter and severe than before, and multitudes were on the alert continually to get them from me if possible. But by the wisdom of God, they remained safe in my hands, until I had accomplished by them what was required at my hand."},
  { num:"מח", words:[
    ["וַיְהִי","and it came to pass"],
    ["כַּאֲשֶׁר","when"],
    ["בָּא","came"],
    ["הַמַּלְאָךְ","the angel"],
    ["כַּאֲשֶׁר","according to what"],
    ["נוֹעַד","was arranged"],
    ["לְקַחְתָּם","to call for them"],
    ["וָאֶתְּנֵם","and I delivered them up"],
    ["לוֹ","to him"],
    ["וְהֵם","and they are"],
    ["בְּמִשְׁמַרְתּוֹ","in his charge"],
    ["עַד־הַיּוֹם","until the day"],
    ["הַזֶּה","this"],
    ["הַיּוֹם","the day"],
    ["הַשֵּׁנִי","the second"],
    ["לַחֹדֶשׁ","of the month"],
    ["הַחֲמִישִׁי","the fifth"],
    ["בִּשְׁנַת","in the year"],
    ["אֶלֶף","one thousand"],
    ["וּשְׁמֹנֶה","and eight"],
    ["מֵאוֹת","hundred"],
    ["וּשְׁלֹשִׁים","and thirty"],
    ["וּשְׁמֹנֶה","and eight"],
  ], english:"When, according to arrangements, the messenger called for them, I delivered them up to him; and he has them in his charge until this day, being the second day of May, one thousand eight hundred and thirty-eight.”"},
  { num:"מט", words:[
    ["לְסִפּוּר","for an account"],
    ["מָלֵא","more complete"],
    ["רְאֵה","see"],
    ["דִּבְרֵי","the words of"],
    ["יוֹסֵף","Joseph"],
    ["סְמִית","Smith"],
    ["בְּסֵפֶר","in the book of"],
    ["הַפְּנִינָה","the Pearl of"],
    ["הַיְקָרָה","of Great Price"],
  ], english:"For a more complete account, see Joseph Smith—History in the Pearl of Great Price."},
  { num:"נ", words:[
    ["וְהַסֵּפֶר","and the book"],
    ["הָעַתִּיק","the ancient"],
    ["הַזֶּה","this"],
    ["אֲשֶׁר","which"],
    ["הוּצָא","was brought forth"],
    ["מִן־הָאֲדָמָה","from the earth"],
    ["כְּקוֹל","as the voice of"],
    ["עַם","a people"],
    ["מְדַבֵּר","speaking"],
    ["מֵעָפָר","from the dust"],
    ["וְתֻרְגַּם","and translated"],
    ["בִּלְשׁוֹן","into the language of"],
    ["יָמֵינוּ","our day"],
    ["בְּמַתַּת־אֵל","by the gift of God"],
    ["וּבִגְבוּרָתוֹ","and by His power"],
    ["כַּאֲשֶׁר","as"],
    ["הוּעַד","attested"],
    ["בְּעֵדוּת","by the testimony of"],
    ["אֱלֹהִים","God"],
    ["הוּבָא","was brought"],
    ["לָרִאשׁוֹנָה","first"],
    ["לָעוֹלָם","to the world"],
    ["בִּשְׁנַת","in the year"],
    ["אֶלֶף","one thousand"],
    ["וּשְׁמֹנֶה","and eight"],
    ["מֵאוֹת","hundred"],
    ["וּשְׁלֹשִׁים","and thirty"],
    ["כְּסֵפֶר","as the Book of"],
    ["מוֹרְמוֹן","Mormon"],
  ], english:"The ancient record thus brought forth from the earth as the voice of a people speaking from the dust, and translated into modern speech by the gift and power of God as attested by Divine affirmation, was first published to the world in the year 1830 as The Book of Mormon."},
];
var frontBrief = [
  { num:"א", words:[
    ["סֵפֶר","the book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["הוּא","is"],
    ["סֵפֶר","a record"],
    ["קֹדֶשׁ","sacred"],
    ["לְעַמֵּי","for the peoples of"],
    ["אַמֶרִיקָה","America"],
    ["הַקַּדְמוֹנִים","the ancient"],
    ["וְנֶחְקַק","and was engraved"],
    ["עַל־לוּחוֹת","upon plates of"],
    ["מַתֶּכֶת","metal"],
  ], english:"The Book of Mormon is a sacred record of peoples in ancient America and was engraved upon metal plates."},
  { num:"ב", words:[
    ["וְאֵלֶּה","and these are"],
    ["הַמְּקוֹרוֹת","the sources"],
    ["אֲשֶׁר","which"],
    ["מֵהֶם","from them"],
    ["נֶאֱסַף","was compiled"],
    ["הַסֵּפֶר","the book"],
  ], english:"Sources from which this record was compiled include the following:"},
  { num:"ג", words:[
    ["לוּחוֹת","the plates of"],
    ["נֶפִי","Nephi"],
    ["אֲשֶׁר","which"],
    ["הָיוּ","were of"],
    ["שְׁנֵי","two"],
    ["מִינִים","kinds"],
    ["הַקְּטַנִּים","the small"],
    ["וְהַגְּדוֹלִים","and the large"],
    ["הַקְּטַנִּים","the small"],
    ["הֻקְדְּשׁוּ","were devoted"],
    ["לְדִבְרֵי","unto the words of"],
    ["הָרוּחַ","the spirit"],
    ["וְלַעֲבֹדַת","and to the ministry of"],
    ["הַנְּבִיאִים","the prophets"],
    ["וְתוֹרָתָם","and their doctrines"],
    ["וְהַגְּדוֹלִים","and the large"],
    ["הָכִילוּ","contained"],
    ["בְּרֻבָּם","mostly"],
    ["דִּבְרֵי","a history of"],
    ["הַיָּמִים","the days"],
  ], english:"The Plates of Nephi, which were of two kinds: the small plates and the large plates. The former were more particularly devoted to spiritual matters and the ministry and teachings of the prophets, while the latter were occupied mostly by a secular history of the peoples concerned (1 Nephi 9:2–4)."},
  { num:"ד", words:[
    ["אַךְ","however"],
    ["מִימֵי","from the days of"],
    ["מוֹשִׁיָּה","Mosiah"],
    ["וָהָלְאָה","and onward"],
    ["נִכְתְּבוּ","were written"],
    ["בַּלּוּחוֹת","in the plates"],
    ["הַגְּדוֹלִים","the large"],
    ["גַּם","also"],
    ["דִּבְרֵי","items of"],
    ["רוּחַ","spiritual"],
    ["נִכְבָּדִים","of major importance"],
  ], english:"From the time of Mosiah, however, the large plates also included items of major spiritual importance."},
  { num:"ה", words:[
    ["לוּחוֹת","the plates of"],
    ["מוֹרְמוֹן","Mormon"],
    ["אֲשֶׁר","which"],
    ["קִצֵּר","abridged"],
    ["מוֹרְמוֹן","Mormon"],
    ["מִלּוּחוֹת","from the plates of"],
    ["נֶפִי","Nephi"],
    ["הַגְּדוֹלִים","the large"],
    ["וַיּוֹסֶף","and added"],
    ["עֲלֵיהֶם","to them"],
    ["דְּבָרִים","commentaries"],
    ["רַבִּים","many"],
    ["וְגַם","and also"],
    ["כָּתַב","wrote"],
    ["מוֹרְמוֹן","Mormon"],
    ["עוֹד","a continuation of"],
    ["דִּבְרֵי","the history of"],
    ["יָמִים","the days"],
    ["וַיּוֹסֶף","and added"],
    ["מוֹרוֹנִי","Moroni"],
    ["בְנוֹ","his son"],
    ["עֲלֵיהֶם","to them"],
  ], english:"The Plates of Mormon, which consist of an abridgment by Mormon from the large plates of Nephi, with many commentaries. These plates also contained a continuation of the history by Mormon and additions by his son Moroni."},
  { num:"ו", words:[
    ["לוּחוֹת","the plates of"],
    ["עֵתֶר","Ether"],
    ["וּבָהֶם","and in them"],
    ["דִּבְרֵי","the history of"],
    ["יְמֵי","the days of"],
    ["הַיָּרֶדִים","the Jaredites"],
    ["מוֹרוֹנִי","Moroni"],
    ["קִצֵּר","abridged"],
    ["אֶת־הַדְּבָרִים","the records"],
    ["הָאֵלֶּה","these"],
    ["וַיּוֹסֶף","and inserted"],
    ["מִשֶּׁלּוֹ","comments of his own"],
    ["וַיִּקְרָא","and called"],
    ["לָהֶם","them"],
    ["סֵפֶר","the book of"],
    ["עֵתֶר","Ether"],
  ], english:"The Plates of Ether, which present a history of the Jaredites. This record was abridged by Moroni, who inserted comments of his own and incorporated the record with the general history under the title “Book of Ether.”"},
  { num:"ז", words:[
    ["לוּחוֹת","the plates of"],
    ["הַנְּחֹשֶׁת","the brass"],
    ["אֲשֶׁר","which"],
    ["הֵבִיא","brought"],
    ["עַם","the people of"],
    ["לֶחִי","Lehi"],
    ["מִירוּשָׁלַיִם","from Jerusalem"],
    ["בִּשְׁנַת","in the year"],
    ["שֵׁשׁ","six"],
    ["מֵאוֹת","hundred"],
    ["לִפְנֵי","before"],
    ["בּוֹא","the coming of"],
    ["הַמָּשִׁיחַ","the Messiah"],
    ["בָּהֶם","in them"],
    ["הָיוּ","were"],
    ["חֲמֵשֶׁת","the five"],
    ["חֻמְשֵׁי","books of"],
    ["מֹשֶׁה","Moses"],
    ["וְדִבְרֵי","and the history of"],
    ["יְמֵי","the days of"],
    ["הַיְּהוּדִים","the Jews"],
    ["מֵרֵאשִׁית","from the beginning"],
    ["וְעַד","and unto"],
    ["רֵאשִׁית","the beginning of"],
    ["מְלֹךְ","the reign of"],
    ["צִדְקִיָּהוּ","Zedekiah"],
    ["מֶלֶךְ","the king of"],
    ["יְהוּדָה","Judah"],
    ["וּנְבוּאוֹת","and the prophecies of"],
    ["הַנְּבִיאִים","the prophets"],
    ["הַקְּדוֹשִׁים","the holy"],
  ], english:"The Plates of Brass brought by the people of Lehi from Jerusalem in 600 B.C. These contained “the five books of Moses, … and also a record of the Jews from the beginning, … down to the commencement of the reign of Zedekiah, king of Judah; and also the prophecies of the holy prophets” (1 Nephi 5:11–13)."},
  { num:"ח", words:[
    ["דְּבָרִים","quotations"],
    ["רַבִּים","many"],
    ["מִלּוּחוֹת","from plates"],
    ["אֵלֶּה","these"],
    ["מִדִּבְרֵי","from the words of"],
    ["יְשַׁעְיָהוּ","Isaiah"],
    ["וּנְבִיאִים","and prophets"],
    ["אֲחֵרִים","other"],
    ["מִן־הַמִּקְרָא","biblical"],
    ["וּמִזּוּלָתוֹ","and nonbiblical"],
    ["נִמְצָאִים","are found"],
    ["בְּסֵפֶר","in the book of"],
    ["מוֹרְמוֹן","Mormon"],
  ], english:"Many quotations from these plates, citing Isaiah and other biblical and nonbiblical prophets, appear in the Book of Mormon."},
  { num:"ט", words:[
    ["סֵפֶר","the book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["בּוֹ","in it"],
    ["חֲמִשָּׁה","fifteen"],
    ["עָשָׂר","ten"],
    ["חֲלָקִים","parts"],
    ["הַנִּקְרָאִים","known"],
    ["כֻּלָּם","all"],
    ["חוּץ","except"],
    ["מֵאֶחָד","one"],
    ["סְפָרִים","as books"],
    ["וּמְכֻנִּים","and designated"],
    ["עַל־פִּי","for the most"],
    ["רֹב","part"],
    ["עַל־שֵׁם","upon the name of"],
    ["כּוֹתְבָם","their writer"],
    ["הָרִאשׁוֹן","the principal"],
  ], english:"The Book of Mormon comprises fifteen main parts or divisions, known, with one exception, as books, usually designated by the name of their principal author."},
  { num:"י", words:[
    ["הַחֵלֶק","the portion"],
    ["הָרִאשׁוֹן","the first"],
    ["שֵׁשֶׁת","the six"],
    ["הַסְּפָרִים","books"],
    ["הָרִאשׁוֹנִים","the first"],
    ["עַד","ending with"],
    ["סֵפֶר","the book of"],
    ["עׇמְנִי","Omni"],
    ["הוּא","is"],
    ["תַּרְגּוּם","a translation"],
    ["מִלּוּחוֹת","from the plates of"],
    ["נֶפִי","Nephi"],
    ["הַקְּטַנִּים","the small"],
  ], english:"The first portion (the first six books, ending with Omni) is a translation from the small plates of Nephi."},
  { num:"יא", words:[
    ["וּבֵין","and between"],
    ["סֵפֶר","the book of"],
    ["עׇמְנִי","Omni"],
    ["לְסֵפֶר","and the book of"],
    ["מוֹשִׁיָּה","Mosiah"],
    ["בָּאִים","is"],
    ["דְּבָרִים","an insert"],
    ["הַנִּקְרָאִים","called"],
    ["דִּבְרֵי","the Words of"],
    ["מוֹרְמוֹן","Mormon"],
  ], english:"Between the books of Omni and Mosiah is an insert called the Words of Mormon."},
  { num:"יב", words:[
    ["וְהַדְּבָרִים","and the insert"],
    ["הָאֵלֶּה","this"],
    ["מְחַבְּרִים","connects"],
    ["אֶת־הַדְּבָרִים","the record"],
    ["הַחֲקוּקִים","engraved"],
    ["עַל־הַלּוּחוֹת","on the plates"],
    ["הַקְּטַנִּים","the small"],
    ["עִם־קִצּוּר","with the abridgment of"],
    ["מוֹרְמוֹן","Mormon"],
    ["מִן־הַלּוּחוֹת","of the plates"],
    ["הַגְּדוֹלִים","the large"],
  ], english:"This insert connects the record engraved on the small plates with Mormon’s abridgment of the large plates."},
  { num:"יג", words:[
    ["וְהַחֵלֶק","and the portion"],
    ["הָאָרֹךְ","the longest"],
    ["מִכֻּלָּם","of all"],
    ["מִסֵּפֶר","from the book of"],
    ["מוֹשִׁיָּה","Mosiah"],
    ["עַד","through"],
    ["הַפֶּרֶק","the chapter"],
    ["הַשְּׁבִיעִי","the seventh"],
    ["בְּסֵפֶר","of the book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["הוּא","is"],
    ["תַּרְגּוּם","a translation of"],
    ["קִצּוּר","the abridgment of"],
    ["מוֹרְמוֹן","Mormon"],
    ["מִלּוּחוֹת","from the plates of"],
    ["נֶפִי","Nephi"],
    ["הַגְּדוֹלִים","the large"],
  ], english:"The longest portion, from Mosiah through Mormon chapter 7, is a translation of Mormon’s abridgment of the large plates of Nephi."},
  { num:"יד", words:[
    ["וְהַחֵלֶק","and the portion"],
    ["הָאַחֲרוֹן","the concluding"],
    ["מִן־הַפֶּרֶק","from the chapter"],
    ["הַשְּׁמִינִי","the eighth"],
    ["בְּסֵפֶר","of the book of"],
    ["מוֹרְמוֹן","Mormon"],
    ["וְעַד","to"],
    ["סוֹף","the end of"],
    ["הַסֵּפֶר","the volume"],
    ["נֶחְקַק","was engraved"],
    ["בְּיַד","by the hand of"],
    ["מוֹרוֹנִי","Moroni"],
    ["בֶּן־מוֹרְמוֹן","the son of Mormon"],
    ["אֲשֶׁר","who"],
    ["אַחֲרֵי","after"],
    ["כַלּוֹתוֹ","finishing"],
    ["אֶת־דִּבְרֵי","the record of"],
    ["יְמֵי","the life of"],
    ["אָבִיו","his father"],
    ["קִצֵּר","made an abridgment of"],
    ["אֶת־דִּבְרֵי","the record of"],
    ["הַיָּרֶדִים","the Jaredites"],
    ["הוּא","as"],
    ["סֵפֶר","the book of"],
    ["עֵתֶר","Ether"],
    ["וְאַחַר","and later"],
    ["הוֹסִיף","added"],
    ["אֶת־הַחֲלָקִים","the parts"],
    ["הַנִּקְרָאִים","known as"],
    ["סֵפֶר","the book of"],
    ["מוֹרוֹנִי","Moroni"],
  ], english:"The concluding portion, from Mormon chapter 8 to the end of the volume, was engraved by Mormon’s son Moroni, who, after finishing the record of his father’s life, made an abridgment of the Jaredite record (as the book of Ether) and later added the parts known as the book of Moroni."},
  { num:"טו", words:[
    ["בִּשְׁנַת","in the year"],
    ["אַרְבַּע","four"],
    ["מֵאוֹת","hundred"],
    ["וְעֶשְׂרִים","and twenty"],
    ["וְאַחַת","and one"],
    ["אַחֲרֵי","after"],
    ["בּוֹא","the coming of"],
    ["הַמָּשִׁיחַ","the Messiah"],
    ["אוֹ","or"],
    ["סָמוּךְ","near"],
    ["לָהּ","to it"],
    ["חָתַם","sealed up"],
    ["מוֹרוֹנִי","Moroni"],
    ["אַחֲרוֹן","the last of"],
    ["נְבִיאֵי","the prophets of"],
    ["הַנֶּפִיִּים","the Nephites"],
    ["וְסוֹפְרֵיהֶם","and historians"],
    ["אֶת־סֵפֶר","the book of"],
    ["הַקֹּדֶשׁ","sacred"],
    ["וַיִּטְמְנֵהוּ","and hid it up"],
    ["לַיהוָה","unto the Lord"],
    ["לְהִגָּלוֹת","to be brought forth"],
    ["בְּאַחֲרִית","in the latter"],
    ["הַיָּמִים","the days"],
    ["כַּאֲשֶׁר","as"],
    ["דִּבֶּר","spoke"],
    ["אֱלֹהִים","God"],
    ["בְּיַד","by the hand of"],
    ["נְבִיאָיו","His prophets"],
    ["הַקְּדוֹשִׁים","the holy"],
  ], english:"In or about the year A.D. 421, Moroni, the last of the Nephite prophet-historians, sealed the sacred record and hid it up unto the Lord, to be brought forth in the latter days, as predicted by the voice of God through His ancient prophets."},
  { num:"טז", words:[
    ["בִּשְׁנַת","in the year"],
    ["אֶלֶף","one thousand"],
    ["וּשְׁמֹנֶה","and eight"],
    ["מֵאוֹת","hundred"],
    ["וְעֶשְׂרִים","and twenty"],
    ["וְשָׁלֹשׁ","and three"],
    ["בָּא","visited"],
    ["מוֹרוֹנִי","Moroni"],
    ["זֶה","this same"],
    ["אֲשֶׁר","who"],
    ["קָם","had risen"],
    ["מִן־הַמֵּתִים","from the dead"],
    ["אֶל־יוֹסֵף","unto Joseph"],
    ["סְמִית","Smith"],
    ["הַנָּבִיא","the prophet"],
    ["וּמִיָּמִים","and subsequently"],
    ["מָסַר","delivered"],
    ["לוֹ","to him"],
    ["אֶת־הַלּוּחוֹת","the plates"],
    ["הַחֲקוּקִים","the engraved"],
  ], english:"In A.D. 1823, this same Moroni, then a resurrected personage, visited the Prophet Joseph Smith and subsequently delivered the engraved plates to him."},
];
renderVerseSet(frontJST, 'front-js-verses');
renderVerseSet(frontBrief, 'front-brief-verses');
})();
