// verses/moroni.js — Moroni verse data
(function() {
var mr_ch1Verses = [
  { num: "א", words: [
    ["וְעַתָּה","and now"],["אֲנִי","I"],["מוֹרוֹנִי","Moroni"],["אַחֲרֵי","after"],["כַּלּוֹתִי","I had finished"],["לְקַצֵּר","abridging"],["אֶת־דִּבְרֵי","the account of"],["עַם־יֶרֶד","the people of Jared"],["חָשַׁבְתִּי","I had supposed"],["לֹא","not"],["לִכְתֹּב","to write"],["עוֹד","more"],["וְהִנֵּה","but behold"],["עוֹד","yet"],["לֹא","not"],["אָבַדְתִּי","I have perished"],["וְלֹא","and not"],["אֶתְוַדַּע","I make myself known"],["אֶל־הַלָּמָנִים","to the Lamanites"],["פֶּן","lest"],["יַשְׁמִידוּנִי","they should destroy me"], ["׃",""]
  ]},
  { num: "ב", words: [
    ["כִּי","for"],["הִנֵּה","behold"],["מִלְחֲמוֹתֵיהֶם","their wars"],["אַכְזָרִיּוֹת","fierce"],["מְאֹד","exceedingly"],["בֵּינֵיהֶם","among themselves"],["וּמִשִּׂנְאָתָם","and because of their hatred"],["יָמִיתוּ","they put to death"],["כׇּל־נֶפִי","every Nephite"],["אֲשֶׁר","who"],["לֹא־יְכַחֵשׁ","will not deny"],["בַּמָּשִׁיחַ","in Christ"], ["׃",""]
  ]},
  { num: "ג", words: [
    ["וַאֲנִי","and I"],["מוֹרוֹנִי","Moroni"],["לֹא","not"],["אֲכַחֵשׁ","I shall deny"],["בַּמָּשִׁיחַ","in Christ"],["לָכֵן","therefore"],["אָנוּד","I wander"],["בְּכׇל־אֲשֶׁר","wherever"],["אוּכַל","I am able"],["לְמַעַן","for the sake of"],["חַיַּי","my life"], ["׃",""]
  ]},
  { num: "ד", words: [["עַל־כֵּן","therefore"], ["אֶכְתֹּב","I write"], ["דְּבָרִים","things"], ["אֲחָדִים","a few"], ["עוֹד","more"], ["לְהֵפֶךְ","contrary to"], ["מֵאֲשֶׁר","that which"], ["חָשַׁבְתִּי","I had supposed"], ["כִּי","for"], ["חָשַׁבְתִּי","I had supposed"], ["לֹא","not"], ["לִכְתֹּב","to write"], ["עוֹד","any more"], ["דָּבָר","thing"], ["וְהִנֵּה","but behold"], ["אֶכְתֹּב","I write"], ["דְּבָרִים","things"], ["אֲחָדִים","a few"], ["אוּלַי","perhaps"], ["יוֹעִילוּ","they may be of worth"], ["לְאַחַי","unto my brethren"], ["הַלָּמָנִים","the Lamanites"], ["בְּיוֹם","in a day"], ["יָבוֹא","that shall come"], ["כִּרְצוֹן","according to the will of"], ["יְהוָה","the Lord"], ["׃",""]]}
];
renderVerseSet(mr_ch1Verses, 'mr-ch1-verses');
var mr_ch2Verses = [
  { num: "א", words: [
    ["דִּבְרֵי","the words of"],["הַמָּשִׁיחַ","Christ"],["אֲשֶׁר־דִּבֶּר","which He spoke"],["אֶל־תַּלְמִידָיו","unto His disciples"],["שְׁנֵים־הֶעָשָׂר","the twelve"],["אֲשֶׁר","whom"],["בָּחַר","He chose"],["בְּסׇמְכוֹ","as He laid"],["אֶת־יָדָיו","His hands"],["עֲלֵיהֶם","upon them"], ["׃",""]
  ]},
  { num: "ב", words: [["וַיִּקְרָא","and He called"], ["לָהֶם","them"], ["בְּשֵׁמוֹת","by name"], ["לֵאמֹר","saying"], ["תִּקְרְאוּ","you shall call"], ["אֶל־הָאָב","upon the Father"], ["בִּשְׁמִי","in My name"], ["בִּתְפִלָּה","in prayer"], ["חֲזָקָה","mighty"], ["וְאַחֲרֵי","and after"], ["אֲשֶׁר","that"], ["תַּעֲשׂוּ","you do"], ["זֹאת","this"], ["יִהְיֶה","there shall be"], ["לָכֶם","to you"], ["כֹּחַ","power"], ["אֲשֶׁר","that"], ["לְמִי","to him"], ["אֲשֶׁר","upon whom"], ["תִּסְמְכוּ","you shall lay"], ["יְדֵיכֶם","your hands"], ["עָלָיו","upon him"], ["תִּתְּנוּ","you shall give"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["וּבִשְׁמִי","and in My name"], ["תִּתְּנוּהָ","shall you give it"], ["כִּי־כֵן","for thus"], ["יַעֲשׂוּ","do"], ["שְׁלִיחַי","My apostles"], ["׃",""]]},
  { num: "ג", words: [
    ["וְעַתָּה","now"],["דִּבֶּר","spoke"],["הַמָּשִׁיחַ","Christ"],["אֶת־הַדְּבָרִים","the words"], ["הָאֵלֶּה","these"],["אֲלֵיהֶם","unto them"],["בְּעֵת","at the time of"],["הֵרָאוֹתוֹ","His appearing"],["הָרִאשׁוֹנָה","first"],["וְהֶהָמוֹן","and the multitude"],["לֹא־שָׁמְעוּ","heard it not"],["אַךְ","but"],["הַתַּלְמִידִים","the disciples"],["שָׁמְעוּ","heard"],["וְעַל־כׇּל־אֲשֶׁר","and on as many as"],["סָמְכוּ","they laid"],["יְדֵיהֶם","their hands"],["נָפְלָה","fell"],["רוּחַ","the Spirit of"],["הַקֹּדֶשׁ","the Holy"], ["׃",""]
  ]}
];
renderVerseSet(mr_ch2Verses, 'mr-ch2-verses');
var mr_ch3Verses = [
  { num: "א", words: [["הַדֶּרֶךְ","the manner"], ["אֲשֶׁר","which"], ["הַתַּלְמִידִים","the disciples"], ["הַנִּקְרָאִים","who were called"], ["זִקְנֵי","the elders of"], ["הַקָּהָל","the church"], ["הִסְמִיכוּ","ordained"], ["כֹּהֲנִים","priests"], ["וּמוֹרִים","and teachers"], ["׃",""]]},
  { num: "ב", words: [
    ["אַחֲרֵי","after"],["אֲשֶׁר","that"],["הִתְפַּלְלוּ","they prayed"],["אֶל־הָאָב","unto the Father"],["בְּשֵׁם","in the name of"],["הַמָּשִׁיחַ","Christ"],["סָמְכוּ","they laid"],["אֶת־יְדֵיהֶם","their hands"],["עֲלֵיהֶם","upon them"],["וַיֹּאמְרוּ","and said"], ["׃",""]
  ]},
  { num: "ג", words: [
    ["בְּשֵׁם","in the name of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","Christ"],["סֹמֵךְ","ordain"],["אֲנִי","I"],["אֹתְךָ","you"],["לִהְיוֹת","to be"],["כֹּהֵן","a priest"],["אוֹ","or"],["אִם־יִהְיֶה","if he shall be"],["מוֹרֶה","a teacher"],["סֹמֵךְ","ordain"],["אֲנִי","I"],["אֹתְךָ","you"],["לִהְיוֹת","to be"],["מוֹרֶה","a teacher"],["לִדְרֹשׁ","to preach"],["לָשׁוּב","repentance"],["וְנִסְלְחוּ","and remission of"],["חֲטָאִים","sins"],["דֶּרֶךְ","through"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","Christ"],["בַּעֲמִידַת","by the endurance of"],["הָאֱמוּנָה","faith"],["בִּשְׁמוֹ","on His name"],["עַד־הַקֵּץ","to the end"],["אָמֵן","amen"], ["׃",""]
  ]},
  { num: "ד", words: [
    ["וּבַדֶּרֶךְ","and after manner"], ["הַזֹּאת","this"],["סָמְכוּ","they ordained"],["כֹּהֲנִים","priests"],["וּמוֹרִים","and teachers"],["כְּפִי","according to"],["מַתְּנוֹת","the gifts of"],["הָאֱלֹהִים","God"],["וּקְרִיאוֹתָיו","and His callings"],["לִבְנֵי־אָדָם","unto men"],["וַיִּסְמְכוּ","and they ordained"],["אוֹתָם","them"],["בְּכֹחַ","by the power of"],["רוּחַ","the Spirit of"],["הַקֹּדֶשׁ","the Holy"],["אֲשֶׁר","which"],["הָיָה","was"],["בָּם","in them"], ["׃",""]
  ]}
];
renderVerseSet(mr_ch3Verses, 'mr-ch3-verses');
var mr_ch4Verses = [
  { num: "א", words: [["דֶּרֶךְ","the manner of"], ["זִקְנֵיהֶם","their elders"], ["וְכֹהֲנֵיהֶם","and priests"], ["בְּתִתָּם","in administering"], ["אֶת־בְּשַׂר","the flesh of"], ["הַמָּשִׁיחַ","Christ"], ["וְדָמוֹ","and His blood"], ["לַקָּהָל","unto the church"], ["וַיִּתְּנוּ","and they administered"], ["אוֹתוֹ","it"], ["כְּפִי","according to"], ["מִצְוֹת","the commandments of"], ["הַמָּשִׁיחַ","Christ"], ["עַל־כֵּן","therefore"], ["יָדַעְנוּ","we know"], ["כִּי","that"], ["אֱמֶת","true"], ["הַדֶּרֶךְ","the manner"], ["וְהַזָּקֵן","and the elder"], ["אוֹ","or"], ["הַכֹּהֵן","the priest"], ["נָתַן","administered"], ["אוֹתוֹ","it"], ["׃",""]]},
  { num: "ב", words: [["וַיִּכְרְעוּ","and they did kneel down"], ["עִם־הַקָּהָל","with the church"], ["וַיִּתְפַּלְלוּ","and they prayed"], ["אֶל־הָאָב","unto the Father"], ["בְּשֵׁם","in the name of"], ["הַמָּשִׁיחַ","Christ"], ["לֵאמֹר","saying"], ["׃",""]]},
  { num: "ג", words: [["אֱלֹהִים","O God"], ["אָבִינוּ","our Father"], ["אֲשֶׁר־לְעוֹלָם","the Eternal"], ["נְבַקֵּשׁ","we ask"], ["מִמְּךָ","of you"], ["בְּשֵׁם","in the name of"], ["בִּנְךָ","your Son"], ["יֵשׁוּעַ","Jesus"], ["הַמָּשִׁיחַ","Christ"], ["לְבָרֵךְ","to bless"], ["וּלְקַדֵּשׁ","and sanctify"], ["אֶת־הַלֶּחֶם","the bread"], ["הַזֶּה","this"], ["לְנַפְשׁוֹת","to the souls of"], ["כׇּל־הָאֹכְלִים","all who partake"], ["מִמֶּנּוּ","of it"], ["לְמַעַן","that"], ["יֹאכְלוּ","they may eat"], ["לְזִכְרוֹן","in remembrance of"], ["גְּוִיַּת","the body of"], ["בִּנְךָ","your Son"], ["וְיָעִידוּ","and witness"], ["לְךָ","unto you"], ["אֱלֹהִים","O God"], ["אָבִינוּ","our Father"], ["אֲשֶׁר־לְעוֹלָם","the Eternal"], ["כִּי","that"], ["נְכוֹנִים","willing"], ["הֵם","they are"], ["לָשֵׂאת","to bear"], ["עֲלֵיהֶם","upon them"], ["אֶת־שֵׁם","the name of"], ["בִּנְךָ","your Son"], ["וְלִזְכֹּר","and to remember"], ["אוֹתוֹ","him"], ["תָּמִיד","always"], ["וְלִשְׁמֹר","and to keep"], ["אֶת־מִצְוֹתָיו","his commandments"], ["אֲשֶׁר־נָתַן","which he hath given"], ["לָהֶם","unto them"], ["לְמַעַן","that"], ["יִהְיֶה","shall be"], ["רוּחוֹ","His Spirit"], ["אִתָּם","with them"], ["תָּמִיד","always"], ["אָמֵן","amen"], ["׃",""]]}
];
renderVerseSet(mr_ch4Verses, 'mr-ch4-verses');
var mr_ch5Verses = [
  { num: "א", words: [["דֶּרֶךְ","the manner of"], ["תֵּת","administering"], ["הַיַּיִן","the wine"], ["הִנֵּה","behold"], ["לָקְחוּ","they took"], ["אֶת־הַכּוֹס","the cup"], ["וַיֹּאמְרוּ","and said"], ["׃",""]]},
  { num: "ב", words: [["אֱלֹהִים","O God"], ["אָבִינוּ","our Father"], ["אֲשֶׁר־לְעוֹלָם","the Eternal"], ["נְבַקֵּשׁ","we ask"], ["מִמְּךָ","of you"], ["בְּשֵׁם","in the name of"], ["בִּנְךָ","your Son"], ["יֵשׁוּעַ","Jesus"], ["הַמָּשִׁיחַ","Christ"], ["לְבָרֵךְ","to bless"], ["וּלְקַדֵּשׁ","and sanctify"], ["אֶת־הַיַּיִן","the wine"], ["הַזֶּה","this"], ["לְנַפְשׁוֹת","to the souls of"], ["כׇּל־הַשֹּׁתִים","all who drink"], ["מִמֶּנּוּ","of it"], ["לְמַעַן","that"], ["יַעֲשׂוּ","they may do"], ["זֹאת","this"], ["לְזִכְרוֹן","in remembrance of"], ["דַּם","the blood of"], ["בִּנְךָ","your Son"], ["אֲשֶׁר","which"], ["נִשְׁפַּךְ","was shed"], ["בַּעֲדָם","for them"], ["וְיָעִידוּ","and witness"], ["לְךָ","unto you"], ["אֱלֹהִים","O God"], ["אָבִינוּ","our Father"], ["אֲשֶׁר־לְעוֹלָם","the Eternal"], ["כִּי","that"], ["יִזְכְּרוּ","they remember"], ["אוֹתוֹ","him"], ["תָּמִיד","always"], ["לְמַעַן","that"], ["יִהְיֶה","shall be"], ["רוּחוֹ","His Spirit"], ["אִתָּם","with them"], ["אָמֵן","amen"], ["׃",""]]}
];
renderVerseSet(mr_ch5Verses, 'mr-ch5-verses');
var mr_ch6Verses = [
  { num: "א", words: [["וְעַתָּה","and now"], ["אֲדַבֵּר","I speak"], ["עַל־הַטְּבִילָה","concerning baptism"], ["הִנֵּה","behold"], ["זְקֵנִים","elders"], ["וְכֹהֲנִים","and priests"], ["וּמוֹרִים","and teachers"], ["נִטְבְּלוּ","were baptized"], ["וְלֹא","and not"], ["נִטְבְּלוּ","baptized"], ["עַד־אֲשֶׁר","save"], ["הֵבִיאוּ","they brought forth"], ["פְּרִי","fruit"], ["נָכוֹן","meet"], ["כִּי","that"], ["נְכוֹנִים","worthy"], ["הֵם","they are"], ["לָהּ","of it"], ["׃",""]]},
  { num: "ב", words: [["וְגַם","and also"], ["לֹא","not"], ["קִבְּלוּ","did they receive"], ["אִישׁ","any"], ["לַטְּבִילָה","unto baptism"], ["עַד־אֲשֶׁר","save"], ["בָּאוּ","they came"], ["בְּלֵב־נִשְׁבָּר","with a broken heart"], ["וְרוּחַ","and a spirit"], ["נִדְכָּה","contrite"], ["וַיָּעִידוּ","and they witnessed"], ["לַקָּהָל","unto the church"], ["כִּי","that"], ["שָׁבוּ","they repented"], ["בֶּאֱמֶת","truly"], ["מִכׇּל","of all"], ["חַטֹּאתֵיהֶם","their sins"], ["׃",""]]},
  { num: "ג", words: [["וְלֹא","and none"], ["קִבְּלוּ","did they receive"], ["אִישׁ","any"], ["לַטְּבִילָה","unto baptism"], ["עַד־אֲשֶׁר","save"], ["נָשְׂאוּ","they took"], ["עֲלֵיהֶם","upon them"], ["אֶת־שֵׁם","the name of"], ["הַמָּשִׁיחַ","Christ"], ["בַּהֲכִינָם","having a determination"], ["לְעָבְדוֹ","to serve Him"], ["עַד־הַקֵּץ","until the end"], ["׃",""]]},
  { num: "ד", words: [["וְאַחֲרֵי","and after"], ["אֲשֶׁר","that"], ["נִתְקַבְּלוּ","were received"], ["לַטְּבִילָה","unto baptism"], ["וְנִפְעֲלוּ","and were wrought upon"], ["וְנִטְהֲרוּ","and cleansed"], ["בְּכֹחַ","by the power of"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["נִמְנוּ","they were numbered"], ["בְּעַם","among the people of"], ["קְהַל","the church of"], ["הַמָּשִׁיחַ","Christ"], ["וַיִּלָּקְחוּ","and were taken"], ["שְׁמוֹתָם","their names"], ["לְמַעַן","that"], ["יִזָּכְרוּ","they might be remembered"], ["וְיִזּוֹנוּ","and nourished"], ["בִּדְבַר","by the word of"], ["אֱלֹהִים","God"], ["הַטּוֹב","the good"], ["לִשְׁמֹר","to keep"], ["אוֹתָם","them"], ["בַּדֶּרֶךְ","in the way"], ["הַיְּשָׁרָה","the right"], ["לִשְׁמֹר","to keep"], ["אוֹתָם","them"], ["שֹׁקְדִים","watchful"], ["תָּמִיד","continually"], ["לַתְּפִלָּה","unto prayer"], ["נִשְׁעָנִים","relying"], ["רַק","alone"], ["עַל־צִדְקַת","upon the merits of"], ["הַמָּשִׁיחַ","Christ"], ["אֲשֶׁר","who"], ["הָיָה","was"], ["רֹאשׁ","the author of"], ["וּמַשְׁלִים","and finisher of"], ["אֱמוּנָתָם","their faith"], ["׃",""]]},
  { num: "ה", words: [["וְהַקָּהָל","and the church"], ["נִקְהֲלוּ","met"], ["יַחַד","together"], ["פְּעָמִים","at times"], ["רַבּוֹת","frequent"], ["לָצוּם","to fast"], ["וּלְהִתְפַּלֵּל","and to pray"], ["וּלְדַבֵּר","and to speak"], ["אִישׁ","one"], ["אֶל־רֵעֵהוּ","with another"], ["עַל־טוֹב","concerning the welfare of"], ["נַפְשׁוֹתָם","their souls"], ["׃",""]]},
  { num: "ו", words: [["וַיִּקָּהֲלוּ","and they met"], ["יַחַד","together"], ["פְּעָמִים","at times"], ["רַבּוֹת","frequent"], ["לֶאֱכֹל","to partake of"], ["לֶחֶם","bread"], ["וָיַיִן","and wine"], ["לְזִכְרוֹן","in remembrance of"], ["הָאָדוֹן","the Lord"], ["יֵשׁוּעַ","Jesus"], ["׃",""]]},
  { num: "ז", words: [["וַיִּשְׁמְרוּ","and they observed"], ["מְאֹד","strictly"], ["פֶּן","that not"], ["יִהְיֶה","there be"], ["עָוֹן","iniquity"], ["בְּתוֹכָם","among them"], ["וּמִי","and whoso"], ["אֲשֶׁר","that"], ["נִמְצָא","was found"], ["עֹשֶׂה","committing"], ["עָוֹן","iniquity"], ["וּשְׁלֹשָׁה","and three"], ["עֵדִים","witnesses"], ["מִן־הַקָּהָל","of the church"], ["הִרְשִׁיעוּהוּ","condemned him"], ["לִפְנֵי","before"], ["הַזְּקֵנִים","the elders"], ["וְאִם־לֹא","and if not"], ["שָׁבוּ","they repented"], ["וְלֹא","and not"], ["הִתְוַדּוּ","confessed"], ["נִמְחוּ","were blotted out"], ["שְׁמוֹתָם","their names"], ["וְלֹא","and not"], ["נִמְנוּ","were numbered"], ["בְּעַם","among the people of"], ["הַמָּשִׁיחַ","Christ"], ["׃",""]]},
  { num: "ח", words: [["אַךְ","but"], ["כַּאֲשֶׁר","as often as"], ["שָׁבוּ","they repented"], ["וּבַקֵּשׁ","and with real intent"], ["בִּקְשׁוּ","sought"], ["לְהִסָּלַח","to be forgiven"], ["לָהֶם","unto them"], ["נִסְלַח","they were forgiven"], ["לָהֶם","unto them"], ["׃",""]]},
  { num: "ט", words: [["וַיְנַהֲלוּ","and they conducted"], ["אֶת־אֲסֵפוֹתֵיהֶם","their meetings"], ["בַּקָּהָל","by the church"], ["כְּפִי","according to"], ["מַעֲשֵׂי","the workings of"], ["הָרוּחַ","the Spirit"], ["וּבְכֹחַ","and by the power of"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["כִּי","for"], ["כַּאֲשֶׁר","as"], ["הוֹבִילָם","led them"], ["כֹּחַ","the power of"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["אִם","whether"], ["לִדְרֹשׁ","to preach"], ["אוֹ","or"], ["לְהַזְהִיר","to exhort"], ["אוֹ","or"], ["לְהִתְפַּלֵּל","to pray"], ["אוֹ","or"], ["לְהִתְחַנֵּן","to supplicate"], ["אוֹ","or"], ["לְזַמֵּר","to sing"], ["כֵּן","even so"], ["נַעֲשָׂה","it was done"], ["׃",""]]}
];
renderVerseSet(mr_ch6Verses, 'mr-ch6-verses');
var mr_ch7Verses = [
  { num: "א", words: [["וְעַתָּה","and now"], ["אֲנִי","I"], ["מוֹרוֹנִי","Moroni"], ["כֹּתֵב","writing"], ["מִקְצָת","a few of"], ["דִּבְרֵי","words of"], ["אָבִי","my father"], ["מוֹרְמוֹן","Mormon"], ["אֲשֶׁר־דִּבֶּר","who spoke"], ["עַל־הָאֱמוּנָה","upon the faith"], ["וְהַתִּקְוָה","and the hope"], ["וְהַחֶסֶד","and the charity"], ["כִּי","that"], ["כָכָה","thus"], ["דִּבֶּר","spoke"], ["אֶל־הָעָם","unto the people"], ["בְּלַמְּדוֹ","in his teaching"], ["אוֹתָם","them"], ["בְּבֵית־הַכְּנֶסֶת","in the synagogue"], ["אֲשֶׁר","which"], ["בָּנוּ","they built"], ["לִמְקוֹם","for the place of"], ["עֲבוֹדָתָם","worship"], ["׃",""]]},
  { num: "ב", words: [["וְעַתָּה","and now"], ["מְדַבֵּר","speaks"], ["אֲנִי","I"], ["מוֹרְמוֹן","Mormon"], ["אֲלֵיכֶם","to you"], ["אַחַי","my brethren"], ["הָאֲהוּבִים","the beloved"], ["וּבְחֶסֶד","and by the grace of"], ["אֱלֹהִים","God"], ["הָאָב","the Father"], ["וַאֲדֹנֵנוּ","and our Lord"], ["יֵשׁוּעַ","Jesus"], ["הַמָּשִׁיחַ","Christ"], ["וּרְצוֹנוֹ","and his will"], ["הַקָּדוֹשׁ","the holy"], ["בַּעֲבוּר","because of"], ["מַתְּנַת","gift of"], ["קְרִיאָתוֹ","his calling"], ["אֹתִי","unto me"], ["נִתַּן","was given"], ["לִי","to me"], ["לְדַבֵּר","to speak"], ["אֲלֵיכֶם","to you"], ["בָּעֵת","in the time"], ["הַזֹּאת","this"], ["׃",""]]},
  { num: "ג", words: [["לָכֵן","therefore"], ["אֲדַבֵּר","I will speak"], ["אֲלֵיכֶם","to you"], ["אֲשֶׁר","which"], ["בַּקָּהָל","of the church"], ["הַהֹלְכִים","the ones walking"], ["בְּשָׁלוֹם","in peace"], ["אַחֲרֵי","after"], ["הַמָּשִׁיחַ","Christ"], ["וַאֲשֶׁר","and who"], ["הִשַּׂגְתֶּם","have obtained"], ["תִּקְוָה","hope"], ["מַסְפֶּקֶת","sufficient"], ["אֲשֶׁר","which"], ["בָּהּ","in it"], ["תּוּכְלוּ","you can"], ["לָבוֹא","enter"], ["אֶל־מְנוּחַת","unto the rest of"], ["יְהוָה","the Lord"], ["מֵהַיּוֹם","from the day"], ["הַזֶּה","this"], ["וָהָלְאָה","and onward"], ["עַד־אֲשֶׁר","until"], ["תָּנוּחוּ","you shall rest"], ["עִמּוֹ","with him"], ["בַּשָּׁמָיִם","in the heavens"], ["׃",""]]},
  { num: "ד", words: [["וְעַתָּה","and now"], ["אַחַי","my brethren"], ["אֶשְׁפֹּט","I shall judge"], ["אֶת־הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["עֲלֵיכֶם","of you"], ["בַּעֲבוּר","because of"], ["הֲלִיכַתְכֶם","your walk"], ["בְּשָׁלוֹם","in peace"], ["עִם־בְּנֵי","with the children of"], ["הָאָדָם","men"], ["׃",""]]},
  { num: "ה", words: [["כִּי","for"], ["אֶזְכֹּר","I remember"], ["אֶת־דְּבַר־אֱלֹהִים","word of God"], ["הָאֹמֵר","which saith"], ["בְּמַעֲשֵׂיהֶם","by their works"], ["תֵּדְעוּם","you shall know them"], ["כִּי־אִם","for if"], ["מַעֲשֵׂיהֶם","their works"], ["טוֹבִים","good"], ["גַּם־הֵם","also they"], ["טוֹבִים","good"], ["׃",""]]},
  { num: "ו", words: [["כִּי","for"], ["הִנֵּה","behold"], ["אָמַר","said"], ["אֱלֹהִים","God"], ["אִישׁ","a man"], ["רָע","evil"], ["לֹא־יוּכַל","cannot"], ["לַעֲשׂוֹת","to do"], ["הַטּוֹב","the good"], ["כִּי־אִם","for if"], ["יַקְרִיב","he shall offer"], ["מַתָּנָה","gift"], ["אוֹ","or"], ["יִתְפַּלֵּל","he shall pray"], ["אֶל־אֱלֹהִים","unto God"], ["בִּלְתִּי","except"], ["אִם־יַעֲשֶׂה","if he shall do"], ["בְּלֵב","with a heart"], ["שָׁלֵם","whole"], ["לֹא־יוֹעִיל","it profiteth not"], ["לוֹ","to him"], ["מְאוּמָה","anything"], ["׃",""]]},
  { num: "ז", words: [["כִּי","for"], ["הִנֵּה","behold"], ["לֹא","not"], ["יֵחָשֵׁב","it is counted"], ["לוֹ","to him"], ["לִצְדָקָה","for righteousness"], ["׃",""]]},
  { num: "ח", words: [["כִּי","for"], ["הִנֵּה","behold"], ["אִם־אִישׁ","if any man"], ["רָע","evil"], ["יִתֵּן","he shall give"], ["מַתָּנָה","gift"], ["וְיַעֲשֶׂנָּה","he doeth it"], ["בְּמֹר־נֶפֶשׁ","grudgingly"], ["וְלָכֵן","wherefore"], ["יֵחָשֵׁב","it is counted"], ["לוֹ","to him"], ["כְּאִלּוּ","as if"], ["הֶחֱזִיק","he had retained"], ["בַּמַּתָּנָה","in the gift"], ["וְלָכֵן","wherefore"], ["יֵחָשֵׁב","he is counted"], ["רָע","evil"], ["לִפְנֵי","before"], ["אֱלֹהִים","God"], ["׃",""]]},
  { num: "ט", words: [["וְכֵן","and likewise"], ["גַּם","also"], ["יֵחָשֵׁב","it is counted"], ["רָע","evil"], ["לְאִישׁ","for a man"], ["אִם־יִתְפַּלֵּל","if he prays"], ["וְלֹא","and not"], ["בְּלֵב","with a heart"], ["שָׁלֵם","whole"], ["אַף","yea"], ["לֹא־יוֹעִיל","does not profit"], ["לוֹ","to him"], ["מְאוּמָה","anything"], ["כִּי","for"], ["אֱלֹהִים","God"], ["לֹא","not"], ["יְקַבֵּל","he shall receive"], ["כָּאֵלֶּה","none such"], ["׃",""]]},
  { num: "י", words: [["לָכֵן","therefore"], ["אִישׁ","any man"], ["רָע","evil"], ["לֹא־יוּכַל","cannot"], ["לַעֲשׂוֹת","to do"], ["הַטּוֹב","the good"], ["וְגַם","and also"], ["לֹא־יִתֵּן","will he give"], ["מַתָּנָה","gift"], ["טוֹבָה","good"], ["׃",""]]},
  { num: "יא", words: [["כִּי","for"], ["הִנֵּה","behold"], ["מַעְיָן","a fountain"], ["מַר","bitter"], ["לֹא־יוּכַל","cannot"], ["לְהוֹצִיא","to bring forth"], ["מַיִם","waters"], ["טוֹבִים","good"], ["וְגַם","and also"], ["מַעְיָן","a fountain"], ["טוֹב","good"], ["לֹא־יוּכַל","cannot"], ["לְהוֹצִיא","to bring forth"], ["מַיִם","waters"], ["מָרִים","bitter"], ["לָכֵן","therefore"], ["אִישׁ","any man"], ["עֶבֶד","servant of"], ["הַשָּׂטָן","the devil"], ["לֹא־יוּכַל","cannot"], ["לָלֶכֶת","to walk"], ["אַחֲרֵי","after"], ["הַמָּשִׁיחַ","Christ"], ["וְאִם","and if"], ["יֵלֵךְ","he follow"], ["אַחֲרֵי","after"], ["הַמָּשִׁיחַ","Christ"], ["לֹא־יוּכַל","cannot"], ["לִהְיוֹת","to be"], ["עֶבֶד","servant of"], ["הַשָּׂטָן","the devil"], ["׃",""]]},
  { num: "יב", words: [["לָכֵן","therefore"], ["כׇּל־הַדְּבָרִים","all the things"], ["הַטּוֹבִים","the good"], ["מֵאֱלֹהִים","from God"], ["הֵם","are"], ["וְהָרָע","and the evil"], ["מִן־הַשָּׂטָן","from the devil"], ["כִּי","for"], ["הַשָּׂטָן","the devil"], ["אוֹיֵב","an enemy"], ["לֵאלֹהִים","to God"], ["וְנִלְחָם","and fights"], ["בּוֹ","against him"], ["תָּמִיד","continually"], ["וְיִקְרָא","and inviteth"], ["וִיפַתֶּה","and enticeth"], ["לַחֲטֹא","to sin"], ["וְלַעֲשׂוֹת","and to do"], ["הָרָע","the evil"], ["תָּמִיד","continually"], ["׃",""]]},
  { num: "יג", words: [["אַךְ","but"], ["הִנֵּה","behold"], ["הַדָּבָר","the thing"], ["אֲשֶׁר","which"], ["מֵאֱלֹהִים","from God"], ["יִקְרָא","inviteth"], ["וִיפַתֶּה","and enticeth"], ["לַעֲשׂוֹת","to do"], ["הַטּוֹב","the good"], ["תָּמִיד","continually"], ["לָכֵן","therefore"], ["כׇּל־דָּבָר","every thing"], ["אֲשֶׁר","which"], ["יִקְרָא","inviteth"], ["וִיפַתֶּה","and enticeth"], ["לַעֲשׂוֹת","to do"], ["הַטּוֹב","the good"], ["וְלֶאֱהֹב","and to love"], ["אֶת־אֱלֹהִים","God"], ["וּלְעָבְדוֹ","and to serve him"], ["מֵאֱלֹהִים","from God"], ["הוּא","is"], ["׃",""]]},
  { num: "יד", words: [["לָכֵן","therefore"], ["הִשָּׁמְרוּ","take heed"], ["אַחַי","my brethren"], ["הָאֲהוּבִים","the beloved"], ["פֶּן־תִּשְׁפְּטוּ","that you do not judge"], ["אֶת־הָרָע","the evil"], ["לִהְיוֹת","to be"], ["מֵאֱלֹהִים","from God"], ["אוֹ","or"], ["אֶת־הַטּוֹב","the good"], ["אֲשֶׁר","which"], ["מֵאֱלֹהִים","from God"], ["לִהְיוֹת","to be"], ["מִן־הַשָּׂטָן","of the devil"], ["׃",""]]},
  { num: "טו", words: [["כִּי","for"], ["הִנֵּה","behold"], ["אַחַי","my brethren"], ["נִתַּן","it is given"], ["לָכֶם","to you"], ["לִשְׁפֹּט","to judge"], ["לְמַעַן","in order that"], ["תֵּדְעוּ","you may know"], ["טוֹב","good"], ["מֵרָע","from evil"], ["וְהַדֶּרֶךְ","and the way"], ["לִשְׁפֹּט","to judge"], ["בָּרוּר","is as plain"], ["כְּאוֹר","as light of"], ["הַיּוֹם","the day"], ["מִן־הַלַּיְלָה","from the night"], ["הֶחָשֵׁךְ","the dark"], ["לְמַעַן","in order that"], ["תֵּדְעוּ","you may know"], ["בְּדַעַת","with knowledge"], ["תְּמִימָה","perfect"], ["׃",""]]},
  { num: "טז", words: [["כִּי","for"], ["הִנֵּה","behold"], ["רוּחַ","the Spirit of"], ["הַמָּשִׁיחַ","Christ"], ["נִתְּנָה","was given"], ["לְכׇל־אִישׁ","to every man"], ["לְמַעַן","in order that"], ["יֵדַע","he may know"], ["טוֹב","good"], ["מֵרָע","from evil"], ["לָכֵן","therefore"], ["אַרְאֶה","I will show"], ["לָכֶם","to you"], ["אֶת־דֶּרֶךְ","the way"], ["הַמִּשְׁפָּט","to judge"], ["כִּי","that"], ["כׇל־דָּבָר","every thing"], ["הַקּוֹרֵא","which inviteth"], ["לַעֲשׂוֹת","to do"], ["הַטּוֹב","the good"], ["וּלְהַאֲמִין","and to persuade to believe"], ["בַּמָּשִׁיחַ","in Christ"], ["בְּכֹחַ","by the power of"], ["הַמָּשִׁיחַ","Christ"], ["וּמַתְּנָתוֹ","and his gift"], ["נִשְׁלַח","is sent forth"], ["לָכֵן","therefore"], ["תֵּדְעוּ","you may know"], ["בְּדַעַת","with knowledge"], ["תְּמִימָה","perfect"], ["כִּי","that"], ["מֵאֱלֹהִים","from God"], ["הוּא","it is"], ["׃",""]]},
  { num: "יז", words: [["אַךְ","but"], ["כׇּל־דָּבָר","whatsoever thing"], ["אֲשֶׁר","which"], ["יְפַתֶּה","persuadeth"], ["אֲנָשִׁים","men"], ["לַעֲשׂוֹת","to do"], ["רָע","evil"], ["וְלֹא","and not"], ["לְהַאֲמִין","to believe"], ["בַּמָּשִׁיחַ","in Christ"], ["וְלִכְפֹּר","and deny"], ["בּוֹ","in him"], ["וְלֹא","and not"], ["לַעֲבֹד","to serve"], ["אֶת־אֱלֹהִים","God"], ["אָז","then"], ["תֵּדְעוּ","you may know"], ["בְּדַעַת","with knowledge"], ["תְּמִימָה","perfect"], ["כִּי","for"], ["מִן־הַשָּׂטָן","from the devil"], ["הוּא","it is"], ["כִּי","for"], ["כָּכָה","after this manner"], ["יַעֲשֶׂה","doth work"], ["הַשָּׂטָן","the devil"], ["כִּי־לֹא","that not"], ["יְפַתֶּה","persuadeth"], ["אִישׁ","no man"], ["לַעֲשׂוֹת","to do"], ["טוֹב","good"], ["אַף","no"], ["לֹא","not"], ["אֶחָד","one"], ["וְגַם","and also"], ["לֹא","not"], ["מַלְאָכָיו","his angels"], ["וְגַם","and also"], ["לֹא","not"], ["הַנִּכְנָעִים","they who subject themselves"], ["לוֹ","to him"], ["׃",""]]},
  { num: "יח", words: [["וְעַתָּה","and now"], ["אַחַי","my brethren"], ["אַחֲרֵי","seeing"], ["אֲשֶׁר","that"], ["יְדַעְתֶּם","you know"], ["אֶת־הָאוֹר","the light"], ["אֲשֶׁר־בּוֹ","by which"], ["תִּשְׁפְּטוּ","you may judge"], ["אֲשֶׁר","which"], ["הוּא","is"], ["אוֹר","the light of"], ["הַמָּשִׁיחַ","Christ"], ["רְאוּ","see"], ["פֶּן־תִּשְׁפְּטוּ","that you do not judge"], ["לְעַוֵּת","wrongfully"], ["כִּי","for"], ["בַּמִּשְׁפָּט","with the judgment"], ["אֲשֶׁר","which"], ["תִּשְׁפְּטוּ","you shall judge"], ["גַּם־אַתֶּם","you also"], ["תִּשָּׁפֵטוּ","shall be judged"], ["׃",""]]},
  { num: "יט", words: [["לָכֵן","therefore"], ["מִתְחַנֵּן","beseech"], ["אֲנִי","I"], ["אֲלֵיכֶם","to you"], ["אַחַי","brethren"], ["לִדְרֹשׁ","to search"], ["הֵיטֵב","diligently"], ["בְּאוֹר","in the light of"], ["הַמָּשִׁיחַ","Christ"], ["לְמַעַן","in order that"], ["תֵּדְעוּ","you may know"], ["טוֹב","good"], ["מֵרָע","from evil"], ["וְאִם","and if"], ["תֹּאחֲזוּ","you will lay hold"], ["בְּכׇל־דָּבָר","upon every thing"], ["טוֹב","good"], ["וְלֹא","and not"], ["תַרְשִׁיעוּהוּ","condemn it"], ["הָיֹה","surely"], ["תִהְיוּ","you shall be"], ["בְּנֵי","a child of"], ["הַמָּשִׁיחַ","Christ"], ["׃",""]]},
  { num: "כ", words: [["וְעַתָּה","and now"], ["אַחַי","my brethren"], ["אֵיךְ","how is it possible that"], ["תּוּכְלוּ","you can"], ["לֶאֱחֹז","to lay hold"], ["בְּכׇל־דָּבָר","upon every thing"], ["טוֹב","good"], ["׃",""]]},
  { num: "כא", words: [["וְעַתָּה","and now"], ["אָבוֹא","I come"], ["אֶל־הָאֱמוּנָה","to the faith"], ["הַהִיא","that"], ["אֲשֶׁר","which"], ["אָמַרְתִּי","I said"], ["לְדַבֵּר","I would speak"], ["עָלֶיהָ","thereof"], ["וְאַגִּיד","and I will tell"], ["לָכֶם","to you"], ["אֶת־הַדֶּרֶךְ","the way"], ["אֲשֶׁר","which"], ["בָּהּ","whereby"], ["תּוּכְלוּ","you may"], ["לֶאֱחֹז","to lay hold"], ["בְּכׇל־דָּבָר","on every thing"], ["טוֹב","good"], ["׃",""]]},
  { num: "כב", words: [["כִּי","for"], ["הִנֵּה","behold"], ["אֱלֹהִים","God"], ["הַיּוֹדֵעַ","knowing"], ["כׇּל־דָּבָר","all things"], ["הוּא","being"], ["מֵעוֹלָם","from everlasting"], ["וְעַד־עוֹלָם","to everlasting"], ["הִנֵּה","behold"], ["שָׁלַח","sent"], ["מַלְאָכִים","angels"], ["לְשָׁרֵת","to minister"], ["אֶת־בְּנֵי","the children of"], ["הָאָדָם","men"], ["לְהוֹדִיעַ","to make manifest"], ["עַל־בּוֹא","concerning the coming of"], ["הַמָּשִׁיחַ","Christ"], ["וּבַמָּשִׁיחַ","and in Christ"], ["יָבוֹא","shall come"], ["כׇּל־דָּבָר","every thing"], ["טוֹב","good"], ["׃",""]]},
  { num: "כג", words: [["וְגַם־הִגִּיד","and also declared"], ["אֱלֹהִים","God"], ["לַנְּבִיאִים","to the prophets"], ["מִפִּיו","by his own mouth"], ["כִּי","that"], ["הַמָּשִׁיחַ","Christ"], ["יָבוֹא","shall come"], ["׃",""]]},
  { num: "כד", words: [["וְהִנֵּה","and behold"], ["בִּדְרָכִים","in ways"], ["רַבּוֹת","divers"], ["הוֹדִיעַ","he did manifest"], ["דְּבָרִים","things"], ["טוֹבִים","good"], ["לִבְנֵי־הָאָדָם","to the children of men"], ["וְכׇל־הַדְּבָרִים","and all the things"], ["הַטּוֹבִים","the good"], ["מִן־הַמָּשִׁיחַ","from Christ"], ["הֵם","are"], ["וּבִלְעָדָיו","otherwise"], ["נָפַל","were fallen"], ["הָאָדָם","men"], ["וְלֹא","and not"], ["יָבוֹא","shall come"], ["אֲלֵיהֶם","to them"], ["דָּבָר","thing"], ["טוֹב","good"], ["׃",""]]},
  { num: "כה", words: [["לָכֵן","therefore"], ["בְּשָׁרֵת","by the ministering of"], ["הַמַּלְאָכִים","the angels"], ["וּבְכׇל־דָּבָר","and by every word"], ["אֲשֶׁר","which"], ["יָצָא","proceeded forth"], ["מִפִּי","from the mouth of"], ["אֱלֹהִים","God"], ["הֵחֵל","began"], ["הָאָדָם","men"], ["לְהַאֲמִין","to exercise faith"], ["בַּמָּשִׁיחַ","in Christ"], ["וּבָאֱמוּנָה הַזֹּאת","and thus by faith"], ["אָחֲזוּ","they did lay hold"], ["בְּכׇל־דָּבָר","upon every thing"], ["טוֹב","good"], ["וְכָכָה","and thus"], ["הָיָה","it was"], ["עַד־בּוֹא","until the coming of"], ["הַמָּשִׁיחַ","Christ"], ["׃",""]]},
  { num: "כו", words: [["וְאַחֲרֵי","and after"], ["בֹאוֹ","his coming"], ["נוֹשְׁעוּ","were saved"], ["גַם־אֲנָשִׁים","men also"], ["בֶּאֱמוּנָה","by faith"], ["בִּשְׁמוֹ","in his name"], ["וּבֶאֱמוּנָה","and in faith"], ["נִהְיוּ","they become"], ["לִבְנֵי","the sons of"], ["אֱלֹהִים","God"], ["וְכַאֲשֶׁר","and as sure as"], ["חַי","liveth"], ["הַמָּשִׁיחַ","Christ"], ["דִּבֵּר","spoke"], ["אֶת־הַדְּבָרִים","the words"], ["הָאֵלֶּה","these"], ["לַאֲבוֹתֵינוּ","to our fathers"], ["לֵאמֹר","saying"], ["כׇּל־דָּבָר","whatsoever thing"], ["אֲשֶׁר","which"], ["תִּשְׁאֲלוּ","you shall ask"], ["מֵאֵת","of"], ["הָאָב","the Father"], ["בִּשְׁמִי","in my name"], ["אֲשֶׁר","which"], ["טוֹב","good"], ["בֶּאֱמוּנָה","in faith"], ["בְּהַאֲמִינְכֶם","believing"], ["כִּי","that"], ["תְּקַבְּלוּ","you shall receive"], ["הִנֵּה","behold"], ["יֵעָשֶׂה","it shall be done"], ["לָכֶם","to you"], ["׃",""]]},
  { num: "כז", words: [["לָכֵן","therefore"], ["אַחַי","my brethren"], ["הָאֲהוּבִים","the beloved"], ["הֲחָדְלוּ","have ceased"], ["הַנִּפְלָאוֹת","miracles"], ["כִּי","because"], ["עָלָה","ascended"], ["הַמָּשִׁיחַ","Christ"], ["הַשָּׁמַיְמָה","into heaven"], ["וַיֵּשֶׁב","and hath sat down"], ["לִימִין","on the right hand of"], ["אֱלֹהִים","God"], ["לִתְבֹּעַ","to claim"], ["מֵאֵת","of"], ["הָאָב","the Father"], ["אֶת־צִדְקַת","the rights of"], ["חַסְדּוֹ","his mercy"], ["אֲשֶׁר־לוֹ","which he hath"], ["עַל־בְּנֵי","upon the children of"], ["הָאָדָם","men"], ["׃",""]]},
  { num: "כח", words: [["כִּי","for"], ["מִלֵּא","he hath answered"], ["אֶת־תַּכְלִית","the ends of"], ["הַתּוֹרָה","the law"], ["וְהוּא","and he"], ["תּוֹבֵעַ","claims"], ["אֶת־כׇּל־הַמַּאֲמִינִים","all those who have faith"], ["בּוֹ","in him"], ["וְהַמַּאֲמִינִים","and they who have faith"], ["בּוֹ","in him"], ["יִדְבְּקוּ","will cleave"], ["בְּכׇל־דָּבָר","unto every thing"], ["טוֹב","good"], ["לָכֵן","therefore"], ["יָלִיץ","he advocateth"], ["בְּעַד","the cause of"], ["בְּנֵי־הָאָדָם","the children of men"], ["וְהוּא","and he"], ["שֹׁכֵן","dwells"], ["לָעַד","eternally"], ["בַּשָּׁמָיִם","in the heavens"], ["׃",""]]},
  { num: "כט", words: [["וּבַעֲבוּר","and because"], ["כִּי־עָשָׂה","that he did"], ["זֹאת","this"], ["אַחַי","my brethren"], ["הָאֲהוּבִים","the beloved"], ["הֲחָדְלוּ","have ceased"], ["הַנִּפְלָאוֹת","miracles"], ["הִנֵּה","behold"], ["אֹמֵר","say"], ["אֲנִי","I"], ["לָכֶם","to you"], ["לֹא","nay"], ["וְגַם","and also"], ["לֹא","not"], ["חָדְלוּ","ceased"], ["הַמַּלְאָכִים","the angels"], ["לְשָׁרֵת","to minister"], ["אֶת־בְּנֵי","the children of"], ["הָאָדָם","men"], ["׃",""]]},
  { num: "ל", words: [["כִּי","for"], ["הִנֵּה","behold"], ["כְּפוּפִים","subject"], ["הֵם","are they"], ["לוֹ","to him"], ["לְשָׁרֵת","to minister"], ["כִּדְבַר","according to the word of"], ["מִצְוָתוֹ","his commandment"], ["וְנִרְאִים","showing themselves"], ["לַאֲשֶׁר","unto them of"], ["אֱמוּנָתָם","their faith"], ["חֲזָקָה","strong"], ["וְדַעְתָּם","and their mind"], ["נְכוֹנָה","firm"], ["בְּכׇל־צוּרַת","in every form of"], ["יִרְאַת","the fear of"], ["אֱלֹהִים","God"], ["׃",""]]},
  { num: "לא", words: [["וּפְקֻדַּת","and the office of"], ["שׇׁרְתָם","their ministry"], ["לִקְרֹא","to call"], ["לָאָדָם","men"], ["לָשׁוּב","unto repentance"], ["וּלְהָקִים","and to fulfil"], ["וְלַעֲשׂוֹת","and to do"], ["אֶת־מַעֲשֵׂה","the work of"], ["בְרִיתוֹת","the covenants of"], ["הָאָב","the Father"], ["אֲשֶׁר","which"], ["כָּרַת","he hath made"], ["עִם־בְּנֵי","unto the children of"], ["הָאָדָם","men"], ["לְהָכִין","to prepare"], ["הַדֶּרֶךְ","the way"], ["בֵּין","among"], ["בְּנֵי־הָאָדָם","the children of men"], ["בְּהַגִּידָם","in their declaring"], ["אֶת־דְּבַר","the word of"], ["הַמָּשִׁיחַ","Christ"], ["לִכְלֵי","unto the vessels"], ["בְחִירַת","chosen of"], ["יְהוָה","the Lord"], ["לְמַעַן","in order that"], ["יָעִידוּ","they testify"], ["עָלָיו","of him"], ["׃",""]]},
  { num: "לב", words: [["וּבַעֲשׂוֹתָם","and in their doing"], ["כֵּן","thus"], ["יָכִין","prepareth"], ["יְהוָה","the Lord"], ["אֱלֹהִים","God"], ["אֶת־הַדֶּרֶךְ","the way"], ["לְמַעַן","in order that"], ["תִּהְיֶה","there shall be"], ["לִשְׁאֵרִית","the residue of"], ["הָאָדָם","men"], ["אֱמוּנָה","faith"], ["בַּמָּשִׁיחַ","in Christ"], ["לְמַעַן","in order that"], ["יִהְיֶה","may have"], ["לְרוּחַ","the Spirit"], ["הַקֹּדֶשׁ","the Holy"], ["מָקוֹם","place"], ["בִּלְבָבָם","in their hearts"], ["כְּפִי","according to"], ["כֹחָהּ","the power thereof"], ["וּבַדֶּרֶךְ","and after manner"], ["הַזֹּאת","this"], ["מְבִיא","bringeth to pass"], ["הָאָב","the Father"], ["אֶת־הַבְּרִיתוֹת","the covenants"], ["אֲשֶׁר","which"], ["כָּרַת","he hath made"], ["עִם־בְּנֵי","unto the children of"], ["הָאָדָם","men"], ["׃",""]]},
  { num: "לג", words: [["וְהַמָּשִׁיחַ","and Christ"], ["אָמַר","said"], ["אִם־תַּאֲמִינוּ","if you will have faith"], ["בִי","in me"], ["יִהְיֶה","you shall have"], ["לָכֶם","to you"], ["כֹּחַ","power"], ["לַעֲשׂוֹת","to do"], ["כׇּל־דָּבָר","whatsoever thing"], ["הַמּוֹעִיל","is expedient"], ["בִּי","in me"], ["׃",""]]},
  { num: "לד", words: [["וְהוּא","and he"], ["אָמַר","said"], ["שׁוּבוּ","repent"], ["כׇּל־קַצְוֵי","all the ends of"], ["אֶרֶץ","the earth"], ["וּבֹאוּ","and come"], ["אֵלַי","to me"], ["וְהִטָּבְלוּ","and be baptized"], ["בִּשְׁמִי","in my name"], ["וְהַאֲמִינוּ","and have faith"], ["בִי","in me"], ["לְמַעַן","in order that"], ["תִּוָּשְׁעוּ","you may be saved"], ["׃",""]]},
  { num: "לה", words: [["וְעַתָּה","and now"], ["אַחַי","my brethren"], ["הָאֲהוּבִים","the beloved"], ["אִם־כֵּן","if thus"], ["הוּא","the case"], ["כִּי","that"], ["אֱמֶת","true"], ["הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["אֲשֶׁר","which"], ["דִּבַּרְתִּי","I have spoken"], ["אֲלֵיכֶם","to you"], ["וֵאלֹהִים","and God"], ["יַרְאֶה","will show"], ["לָכֶם","to you"], ["בְּכֹחַ","by the power of"], ["וּבְכָבוֹד","and in glory"], ["גָּדוֹל","great"], ["בַּיּוֹם","in the day"], ["הָאַחֲרוֹן","the last"], ["כִּי","that"], ["אֱמֶת","true"], ["הֵם","they"], ["וְאִם","and if"], ["אֱמֶת","true"], ["הֵם","they"], ["הֲחָדַל","has ceased"], ["יוֹם","the day of"], ["הַנִּפְלָאוֹת","miracles"], ["׃",""]]},
  { num: "לו", words: [["הֲחָדְלוּ","have ceased"], ["הַמַּלְאָכִים","the angels"], ["לְהֵרָאוֹת","to appear"], ["לִבְנֵי־הָאָדָם","to the children of men"], ["אוֹ","or"], ["הֲמָנַע","has he withheld"], ["מֵהֶם","from them"], ["אֶת־כֹּחַ","the power of"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["אוֹ","or"], ["הֲיִמְנַע","will he"], ["כׇּל־עוֹד","so long as"], ["יֶאֶרְכוּ","they shall continue"], ["הַיָּמִים","the days"], ["אוֹ","or"], ["תַעֲמֹד","stands"], ["הָאָרֶץ","the earth"], ["אוֹ","or"], ["יִהְיֶה","he shall be"], ["אִישׁ","any man"], ["אֶחָד","one"], ["עַל־פְּנֵיהָ","upon its face"], ["לְהִוָּשַׁע","to be saved"], ["׃",""]]},
  { num: "לז", words: [["הִנֵּה","behold"], ["אֹמֵר","say"], ["אֲנִי","I"], ["לָכֶם","to you"], ["לֹא","nay"], ["כִּי","for"], ["בֶאֱמוּנָה","in faith"], ["נַעֲשׂוּ","are wrought"], ["הַנִּפְלָאוֹת","miracles"], ["וּבֶאֱמוּנָה","and in faith"], ["יֵרָאוּ","appear"], ["הַמַּלְאָכִים","the angels"], ["וִישָׁרְתוּ","and minister"], ["לָאָדָם","unto men"], ["לָכֵן","therefore"], ["אִם־חָדְלוּ","if ceased"], ["הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["אוֹי","wo be"], ["לִבְנֵי־הָאָדָם","to the children of men"], ["כִּי־זֶה","for it is"], ["מִפְּנֵי","because of"], ["מַעַל","unbelief"], ["וְהַכֹּל","and all"], ["הָבֶל","is vain"], ["׃",""]]},
  { num: "לח", words: [["כִּי־לֹא","for no"], ["יִוָּשַׁע","he shall be saved"], ["אִישׁ","man"], ["כְּדִבְרֵי","according to the words of"], ["הַמָּשִׁיחַ","Christ"], ["בִּלְתִּי","save"], ["אִם־יַאֲמִינוּ","they shall have faith"], ["בִּשְׁמוֹ","in his name"], ["לָכֵן","therefore"], ["אִם־חָדְלוּ","if ceased"], ["הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["גַּם־חָדְלָה","then has ceased also"], ["הָאֱמוּנָה","the faith"], ["וְנוֹרָא","and awful"], ["דֶּרֶךְ","the state of"], ["הָאָדָם","man"], ["כִּי","for"], ["הֵם","they"], ["כְּאִלּוּ","as if"], ["לֹא־נַעֲשְׂתָה","had not been made"], ["גְאֻלָּה","redemption"], ["׃",""]]},
  { num: "לט", words: [["אַךְ","but"], ["הִנֵּה","behold"], ["אַחַי","my brethren"], ["הָאֲהוּבִים","the beloved"], ["אֶשְׁפֹּט","I shall judge"], ["עֲלֵיכֶם","of you"], ["דְּבָרִים","things"], ["טוֹבִים","better"], ["כִּי","for"], ["אֶשְׁפֹּט","I shall judge"], ["כִּי־יֵשׁ","that there is"], ["לָכֶם","to you"], ["אֱמוּנָה","faith"], ["בַּמָּשִׁיחַ","in Christ"], ["מִפְּנֵי","because of"], ["עַנְוַתְכֶם","your meekness"], ["כִּי־אִם","for if"], ["אֵין","there is not"], ["לָכֶם","to you"], ["אֱמוּנָה","faith"], ["בּוֹ","in him"], ["אֵינְכֶם","you are not"], ["נְכוֹנִים","fit"], ["לְהִמָּנוֹת","to be numbered"], ["בְּעַם","among the people of"], ["קְהִלָּתוֹ","his church"], ["׃",""]]},
  { num: "מ", words: [["וְעוֹד","and again"], ["אַחַי","my brethren"], ["הָאֲהוּבִים","the beloved"], ["אֲדַבֵּר","I would speak"], ["אֲלֵיכֶם","to you"], ["עַל־הַתִּקְוָה","concerning hope"], ["אֵיךְ","how is it that"], ["תּוּכְלוּ","you can"], ["לְהַשִּׂיג","attain unto"], ["אֱמוּנָה","faith"], ["בִּלְתִּי","save"], ["אִם־תִּהְיֶה","you shall have"], ["לָכֶם","to you"], ["תִּקְוָה","hope"], ["׃",""]]},
  { num: "מא", words: [["וּמַה־הוּא","and what is it"], ["אֲשֶׁר","which"], ["תְּקַוּוּ","you shall hope"], ["לוֹ","for"], ["הִנֵּה","behold"], ["אֹמֵר","say"], ["אֲנִי","I"], ["לָכֶם","to you"], ["כִּי","that"], ["תִּהְיֶה","you shall have"], ["לָכֶם","to you"], ["תִּקְוָה","hope"], ["דֶּרֶךְ","through"], ["כַּפָּרַת","atonement of"], ["הַמָּשִׁיחַ","Christ"], ["וְכֹחַ","and power of"], ["תְּקוּמָתוֹ","his resurrection"], ["לְהִנָּשֵׂא","to be raised"], ["לְחַיֵּי","to life of"], ["עוֹלָם","eternity"], ["וְזֹאת","and this"], ["בַּעֲבוּר","because of"], ["אֱמוּנַתְכֶם","your faith"], ["בּוֹ","in him"], ["כְּפִי","according to"], ["הַדָּבָר","the promise"], ["׃",""]]},
  { num: "מב", words: [["לָכֵן","therefore"], ["אִם־יֵשׁ","if there is"], ["לְאִישׁ","for a man"], ["אֱמוּנָה","faith"], ["הֲלֹא","he must needs"], ["תִהְיֶה","have"], ["לוֹ","to him"], ["תִּקְוָה","hope"], ["כִּי","for"], ["בְּלִי","without"], ["אֱמוּנָה","faith"], ["לֹא","not"], ["תִּהְיֶה","cannot be"], ["תִּקְוָה","hope"], ["׃",""]]},
  { num: "מג", words: [["וְעוֹד","and again"], ["הִנֵּה","behold"], ["אֹמֵר","say"], ["אֲנִי","I"], ["לָכֶם","to you"], ["כִּי־לֹא","that he cannot"], ["תִהְיֶה","have"], ["לוֹ","to him"], ["אֱמוּנָה","faith"], ["וְתִקְוָה","and hope"], ["בִּלְתִּי","save"], ["אִם־יִהְיֶה","he shall be"], ["עָנָו","meek"], ["וּשְׁפַל","and lowly of"], ["לֵב","heart"], ["׃",""]]},
  { num: "מד", words: [["וְאִם־כֵּן","if so"], ["אֱמוּנָתוֹ","his faith"], ["וְתִקְוָתוֹ","and his hope"], ["הָבֶל","is vain"], ["כִּי","for"], ["אֵין","none is"], ["נִרְצֶה","acceptable"], ["לִפְנֵי","before"], ["אֱלֹהִים","God"], ["זוּלַת","save"], ["הֶעָנָו","the meek"], ["וּשְׁפַל","and lowly of"], ["הַלֵּב","the heart"], ["וְאִם־יִהְיֶה","and if he shall be"], ["אִישׁ","any man"], ["עָנָו","meek"], ["וּשְׁפַל","and lowly of"], ["לֵב","heart"], ["וּמוֹדֶה","and confesses"], ["בְּכֹחַ","by the power of"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["כִּי","that"], ["יֵשׁוּעַ","Jesus"], ["הוּא","is"], ["הַמָּשִׁיחַ","Christ"], ["הֲלֹא","he must needs"], ["יִהְיֶה־לוֹ","have"], ["חֶסֶד","charity"], ["כִּי־אִם","for if"], ["אֵין־לוֹ","he have not"], ["חֶסֶד","charity"], ["אֵינֶנּוּ","he is not"], ["מְאוּמָה","anything"], ["לָכֵן","therefore"], ["יִהְיֶה־לוֹ","have"], ["חֶסֶד","charity"], ["׃",""]]},
  { num: "מה", words: [["וְהַחֶסֶד","and the charity"], ["מַאֲרִיךְ","is slow to"], ["אַף","anger"], ["וּמֵטִיב","and is kind"], ["וְלֹא","and not"], ["יְקַנֵּא","is envious"], ["וְלֹא","and not"], ["יִתְרוֹמֵם","is puffed up"], ["לֹא","not"], ["יְבַקֵּשׁ","seeks"], ["אֶת־אֲשֶׁר","that which"], ["לוֹ","is her own"], ["לֹא","not"], ["יִתְקַצֵּף","is provoked"], ["מְהֵרָה","easily"], ["לֹא","not"], ["יַחְשֹׁב","thinks"], ["רָעָה","evil"], ["וְלֹא","and not"], ["יִשְׂמַח","rejoices"], ["בָּעַוְלָה","in iniquity"], ["אַךְ","but"], ["יִשְׂמַח","rejoices"], ["בָּאֱמֶת","in truth"], ["יִשָּׂא","bears"], ["כֹל","all things"], ["יַאֲמִין","believes"], ["כֹּל","all things"], ["יְקַוֶּה","hopes"], ["כֹל","all things"], ["יִסְבֹּל","endures"], ["כֹּל","all things"], ["׃",""]]},
  { num: "מו", words: [["לָכֵן","therefore"], ["אַחַי","my brethren"], ["הָאֲהוּבִים","the beloved"], ["אִם־אֵין","if there is not"], ["לָכֶם","to you"], ["חֶסֶד","charity"], ["אֵינְכֶם","you are"], ["מְאוּמָה","anything"], ["כִּי","for"], ["הַחֶסֶד","the charity"], ["לֹא","not"], ["יִכָּשֵׁל","faileth"], ["לְעוֹלָם","never"], ["לָכֵן","therefore"], ["דִּבְקוּ","cleave"], ["בַחֶסֶד","in charity"], ["אֲשֶׁר","which"], ["הוּא","is"], ["הַגָּדוֹל","the greatest"], ["מִכֻּלָּם","of all"], ["כִּי","for"], ["כׇל־הַדְּבָרִים","all the things"], ["יִכָּשְׁלוּ","must fail"], ["׃",""]]},
  { num: "מז", words: [["אַךְ","but"], ["הַחֶסֶד","the charity"], ["הוּא","is"], ["חֶסֶד","the love of"], ["הַמָּשִׁיחַ","Christ"], ["הַטָּהוֹר","the pure"], ["וְהוּא","and it"], ["יַעֲמֹד","endures"], ["לָעַד","forever"], ["וְכׇל־הַנִּמְצָא","and whoso is found"], ["בוֹ","possessed of it"], ["בַּיּוֹם","in the day"], ["הָאַחֲרוֹן","the last"], ["יִיטַב","it shall be well"], ["לוֹ","to him"], ["׃",""]]},
  { num: "מח", words: [["לָכֵן","therefore"], ["אַחַי","my brethren"], ["הָאֲהוּבִים","the beloved"], ["הִתְפַּלְּלוּ","pray"], ["אֶל־הָאָב","unto the Father"], ["בְּכׇל־כֹּחַ","with all the energy of"], ["הַלֵּב","the heart"], ["לְמַעַן","in order that"], ["תִּמָּלְאוּ","you may be filled"], ["בַחֶסֶד","with the love"], ["הַזֶּה","this"], ["אֲשֶׁר־נָתַן","which he hath bestowed"], ["לְכׇל־הַהֹלְכִים","upon all who are"], ["בֶּאֱמֶת","true"], ["אַחֲרֵי","followers of"], ["בְנוֹ","his Son"], ["יֵשׁוּעַ","Jesus"], ["הַמָּשִׁיחַ","Christ"], ["לְמַעַן","in order that"], ["תִּהְיוּ","you may become"], ["בְּנֵי","sons of"], ["אֱלֹהִים","God"], ["לְמַעַן","in order that"], ["כַּאֲשֶׁר","when"], ["יֵרָאֶה","he shall appear"], ["נִהְיֶה","we shall be"], ["כָמֹהוּ","like him"], ["כִּי","for"], ["נִרְאֵהוּ","we shall see him"], ["כַּאֲשֶׁר","as"], ["הוּא","he"], ["לְמַעַן","in order that"], ["תִּהְיֶה","we may have"], ["לָנוּ","to us"], ["הַתִּקְוָה","the hope"], ["הַזֹּאת","this"], ["לְמַעַן","in order that"], ["נִטָּהֵר","we may be purified"], ["כַּאֲשֶׁר","even as"], ["הוּא","he"], ["טָהוֹר","pure"], ["אָמֵן","amen"], ["׃",""]]},
];
renderVerseSet(mr_ch7Verses, 'mr-ch7-verses');
var mr_ch8Verses = [
  { num: "א", words: [["אִגֶּרֶת","a letter of"], ["אָבִי","my father"], ["מֹרְמוֹן","Mormon"], ["אֲשֶׁר","which"], ["כָּתַב","wrote"], ["אֵלַי","to me"], ["מוֹרוֹנִי","Moroni"], ["וַיִּכְתֹּב","and he wrote"], ["אֵלַי","to me"], ["אַחֲרֵי","soon after"], ["קְרִיאָתִי","my calling"], ["לַעֲבוֹדָה","to the ministry"], ["וְכָכָה","and on this wise"], ["כָּתַב","wrote"], ["אֵלַי","to me"], ["לֵאמֹר","saying"], ["׃",""]]},
  { num: "ב", words: [["בְּנִי","my son"], ["הָאָהוּב","the beloved"], ["מוֹרוֹנִי","Moroni"], ["שָׂמַחְתִּי","I rejoice"], ["מְאֹד","exceedingly"], ["כִּי","that"], ["זָכַר","hath been mindful of"], ["אוֹתְךָ","you"], ["אֲדֹנְךָ","your Lord"], ["יֵשׁוּעַ","Jesus"], ["הַמָּשִׁיחַ","Christ"], ["וַיִּקְרָא","and he called"], ["אוֹתְךָ","you"], ["לַעֲבוֹדָתוֹ","to his ministry"], ["וְלִמְלַאכְתּוֹ","and to his work"], ["הַקְּדוֹשָׁה","the holy"], ["׃",""]]},
  { num: "ג", words: [["זוֹכֵר","am mindful of"], ["אֲנִי","I"], ["אוֹתְךָ","you"], ["תָּמִיד","always"], ["בִּתְפִלּוֹתַי","in my prayers"], ["וּמִתְפַּלֵּל","and praying"], ["מֵאֵין","without"], ["הֲפֻגוֹת","ceasing"], ["אֶל־הָאֱלֹהִים","unto God"], ["הָאָב","the Father"], ["בְּשֵׁם","in the name of"], ["יֶלֶד","child of"], ["קׇדְשׁוֹ","his holiness"], ["יֵשׁוּעַ","Jesus"], ["כִּי־הוּא","that he"], ["בְּטוּבוֹ","through his goodness"], ["וְחַסְדּוֹ","and his grace"], ["הָעַד־עוֹלָם","infinite"], ["יִשְׁמָרְךָ","he will keep you"], ["בַּעֲמִידַת","through the endurance of"], ["הָאֱמוּנָה","faith"], ["בִּשְׁמוֹ","in his name"], ["עַד־הַקֵּץ","until the end"], ["׃",""]]},
  { num: "ד", words: [["וְעַתָּה","and now"], ["בְּנִי","my son"], ["אֲדַבֵּר","I speak"], ["אֵלֶיךָ","to you"], ["עַל־הַדָּבָר","concerning the matter"], ["הַמַּכְאִיב","which grieveth"], ["אוֹתִי","me"], ["מְאֹד","exceedingly"], ["כִּי","that"], ["מַכְאִיב","it grieveth"], ["אוֹתִי","me"], ["כִּי","that"], ["יֵשׁ","there should rise"], ["מְרִיבוֹת","disputations"], ["בֵּינֵיכֶם","among you"], ["׃",""]]},
  { num: "ה", words: [["כִּי־אִם","for if"], ["לָמַדְתִּי","I learned"], ["אֶת־הָאֱמֶת","the truth"], ["הָיוּ","there have been"], ["מְרִיבוֹת","disputations"], ["בֵּינֵיכֶם","among you"], ["עַל־טְבִילַת","upon baptism of"], ["יַלְדֵיכֶם","your children"], ["הַקְּטַנִּים","the little"], ["׃",""]]},
  { num: "ו", words: [["וְעַתָּה","and now"], ["בְּנִי","my son"], ["חָפַצְתִּי","I desire"], ["כִּי","for"], ["תַּעֲבֹד","you should labor"], ["בְּחָזְקָה","diligently"], ["לְמַעַן","in order that"], ["יוּסַר","be removed"], ["הַשְּׁגִיאָה","the error"], ["הַכְּבֵדָה","the gross"], ["הַזֹּאת","this"], ["מִבֵּינֵיכֶם","from among you"], ["כִּי","for"], ["לְמַעַן","for the intent of"], ["זֹאת","this"], ["כָּתַבְתִּי","I wrote"], ["אֶת־הָאִגֶּרֶת","the epistle"], ["הַזֹּאת","this"], ["׃",""]]},
  { num: "ז", words: [["כִּי","for"], ["מִיָּד","immediately"], ["אַחֲרֵי","after"], ["אֲשֶׁר","that"], ["לָמַדְתִּי","I learned"], ["אֶת־הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["מִמְּךָ","from you"], ["דָּרַשְׁתִּי","I inquired"], ["מֵיְהוָה","of the Lord"], ["עַל־הָעִנְיָן","upon the matter"], ["וַיָּבֹא","and came"], ["אֵלַי","to me"], ["דְּבַר־יְהוָה","word of the Lord"], ["בְּכֹחַ","by the power of"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["לֵאמֹר","saying"], ["׃",""]]},
  { num: "ח", words: [["הַקְשֵׁב","listen"], ["לְדִבְרֵי","to the words of"], ["הַמָּשִׁיחַ","Christ"], ["גּוֹאַלְךָ","your Redeemer"], ["אֲדֹנְךָ","your Lord"], ["וֵאלֹהֶיךָ","and your God"], ["הִנֵּה","behold"], ["בָאתִי","I came"], ["לָעוֹלָם","to the world"], ["לֹא","not"], ["לִקְרֹא","to call"], ["לַצַּדִּיקִים","to the righteous"], ["כִּי־אִם","but"], ["לַחוֹטְאִים","to the sinners"], ["לָשׁוּב","to repentance"], ["הַבְּרִיאִים","the whole"], ["אֵינָם","they are not"], ["צְרִיכִים","needing"], ["לְרוֹפֵא","a physician"], ["כִּי־אִם","but"], ["הַחוֹלִים","the sick"], ["לָכֵן","therefore"], ["הַיְלָדִים","the children"], ["הַקְּטַנִּים","the little"], ["בְּרִיאִים","whole"], ["הֵם","they"], ["כִּי","for"], ["אֵינָם","they are not"], ["יְכוֹלִים","able"], ["לַחֲטֹא","to sin"], ["לָכֵן","therefore"], ["הוּסַר","is taken"], ["מֵהֶם","from them"], ["קִלְלַת","curse of"], ["אָדָם","Adam"], ["בִּי","in me"], ["וְאֵין־לָהּ","and it hath no"], ["כֹּחַ","power"], ["עֲלֵיהֶם","over them"], ["וְתוֹרַת","and law of"], ["הַמִּילָה","the circumcision"], ["בָּטְלָה","is done away"], ["בִּי","in me"], ["׃",""]]},
  { num: "ט", words: [["וְכָכָה","and thus"], ["הוֹדִיעַ","did manifest"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["אֶת־דְּבַר־אֱלֹהִים","word of God"], ["אֵלָי","unto me"], ["לָכֵן","therefore"], ["בְּנִי","my son"], ["הָאָהוּב","the beloved"], ["יוֹדֵעַ","know"], ["אֲנִי","I"], ["כִּי","that"], ["לָצוֹן","mockery"], ["נוֹרָא","solemn"], ["הִיא","is"], ["לִפְנֵי","before"], ["אֱלֹהִים","God"], ["כִּי","that"], ["תִּטְבְּלוּ","you should baptize"], ["יְלָדִים","children"], ["קְטַנִּים","little"], ["׃",""]]},
  { num: "י", words: [["הִנֵּה","behold"], ["אֹמֵר","say"], ["אֲנִי","I"], ["לְךָ","unto you"], ["אֶת־הַדָּבָר","the thing"], ["הַזֶּה","this"], ["תְּלַמֵּד","shall you teach"], ["לָשׁוּב","repentance"], ["וּלְהִטָּבֵל","and baptism"], ["לָאֵלֶּה","unto those"], ["הַיּוֹדְעִים","the ones knowing"], ["טוֹב","good"], ["וָרָע","and evil"], ["וִיכֹלִים","and capable"], ["לַחֲטֹא","to sin"], ["אַף","yea"], ["לַמֵּד","teach"], ["אֶת־הָאָבוֹת","the fathers"], ["וְאֶת־הָאִמָּהוֹת","and the mothers"], ["כִּי","that"], ["עֲלֵיהֶם","upon them"], ["לָשׁוּב","to repent"], ["וּלְהִטָּבֵל","and to be baptized"], ["וּלְהִתְעַנּוֹת","and to humble themselves"], ["כְּיַלְדֵיהֶם","as their children"], ["הַקְּטַנִּים","the little"], ["וְכֻלָּם","and all of them"], ["יִוָּשְׁעוּ","they shall be saved"], ["עִם־יַלְדֵיהֶם","with their children"], ["הַקְּטַנִּים","the little"], ["׃",""]]},
  { num: "יא", words: [["וְיַלְדֵיהֶם","and their children"], ["הַקְּטַנִּים","the little"], ["אֵין","there is not"], ["לָהֶם","to them"], ["צֹרֶךְ","need"], ["לָשׁוּב","to repent"], ["וְגַם","and also"], ["לֹא","not"], ["לְהִטָּבֵל","to be baptized"], ["הִנֵּה","behold"], ["הַטְּבִילָה","the baptism"], ["הִיא","is"], ["לָשׁוּב","unto repentance"], ["לְהַשְׁלִים","to the fulfilling"], ["אֶת־הַמִּצְוֹת","the commandments"], ["לְהִסָּלַח","for the remission of"], ["חֲטָאִים","sins"], ["׃",""]]},
  { num: "יב", words: [["אַךְ","but"], ["הַיְלָדִים","the children"], ["הַקְּטַנִּים","the little"], ["חַיִּים","living"], ["בַּמָּשִׁיחַ","in Christ"], ["מֵאָז","even from"], ["יְסוֹד","the foundation of"], ["הָעוֹלָם","the world"], ["אִם־לֹא","if not"], ["כֵן","so"], ["אֱלֹהִים","God"], ["הוּא","is"], ["אֵל","a God"], ["נוֹשֵׂא","partial"], ["פָּנִים","of face"], ["וְגַם","and also"], ["אֵל","a God"], ["מִשְׁתַּנֶּה","changeable"], ["וּמַכִּיר","and a respecter of"], ["פְּנֵי","the persons of"], ["אָדָם","men"], ["כִּי","for"], ["כַּמָּה","how many"], ["יְלָדִים","children"], ["קְטַנִּים","little"], ["מֵתוּ","died"], ["בְּלִי","without"], ["טְבִילָה","baptism"], ["׃",""]]},
  { num: "יג", words: [["לָכֵן","therefore"], ["אִם־לֹא","except"], ["יָכְלוּ","could"], ["הַיְלָדִים","the children"], ["הַקְּטַנִּים","the little"], ["לְהִוָּשַׁע","to be saved"], ["בְּלִי","without"], ["טְבִילָה","baptism"], ["הָיוּ","must have"], ["אֵלֶּה","these"], ["הוֹלְכִים","gone"], ["לִשְׁאוֹל","to hell"], ["עַד־עוֹלָם","endless"], ["׃",""]]},
  { num: "יד", words: [["הִנֵּה","behold"], ["אֹמֵר","say"], ["אֲנִי","I"], ["לְךָ","unto you"], ["הַחוֹשֵׁב","he that supposeth"], ["כִּי","for"], ["יְלָדִים","children"], ["קְטַנִּים","little"], ["צְרִיכִים","need"], ["טְבִילָה","baptism"], ["הוּא","is"], ["בִּמְרוֹרַת","in bitterness of"], ["רֹאשׁ","gall"], ["וּבְכַבְלֵי","and in bonds of"], ["עָוֹן","iniquity"], ["כִּי","for"], ["אֵין־לוֹ","there is not to him"], ["אֱמוּנָה","faith"], ["תִּקְוָה","hope"], ["וְלֹא","and not"], ["אַהֲבָה","charity"], ["לָכֵן","therefore"], ["אִם־יִכָּרֵת","should he be cut off"], ["בַּמַּחֲשָׁבָה","in the thought"], ["הַזֹּאת","this"], ["עָלָיו","he must"], ["לָרֶדֶת","go down"], ["שְׁאוֹלָה","to hell"], ["׃",""]]},
  { num: "טו", words: [["כִּי","for"], ["רֶשַׁע","wickedness"], ["נוֹרָא","awful"], ["הוּא","is"], ["לַחֲשֹׁב","to suppose"], ["כִּי","that"], ["אֱלֹהִים","God"], ["מוֹשִׁיעַ","saves"], ["יֶלֶד","child"], ["אֶחָד","one"], ["בַּעֲבוּר","because of"], ["טְבִילָה","baptism"], ["וְהָאַחֵר","and the other"], ["אָבֹד","must"], ["יֹאבַד","perish"], ["כִּי","because"], ["אֵין־לוֹ","there is not to him"], ["טְבִילָה","baptism"], ["׃",""]]},
  { num: "טז", words: [["אוֹי","wo be"], ["לָהֶם","to them"], ["אֲשֶׁר","which"], ["יְעַקְּשׁוּ","they shall pervert"], ["אֶת־דַּרְכֵי","the ways of"], ["יְהוָה","the Lord"], ["בַּדֶּרֶךְ","after the manner"], ["הַזֹּאת","this"], ["כִּי","for"], ["יֹאבֵדוּ","they shall perish"], ["אִם־לֹא","except"], ["יָשׁוּבוּ","they repent"], ["הִנֵּה","behold"], ["מְדַבֵּר","speak"], ["אֲנִי","I"], ["בְּעֹז","with boldness"], ["בְּסַמְכוּת","having authority"], ["מֵאֱלֹהִים","from God"], ["וְאֵינֶנִּי","and I am not"], ["יָרֵא","fearing"], ["מַה־יּוּכַל","what can"], ["הָאָדָם","man"], ["לַעֲשׂוֹת","to do"], ["כִּי","for"], ["אַהֲבָה","love"], ["שְׁלֵמָה","perfect"], ["מְגָרֶשֶׁת","casteth out"], ["כׇּל","all"], ["יִרְאָה","fear"], ["׃",""]]},
  { num: "יז", words: [["וַאֲנִי","and I"], ["מָלֵא","am filled with"], ["אַהֲבָה","charity"], ["אֲשֶׁר","which"], ["הִיא","is"], ["אַהֲבַת","love of"], ["עוֹלָם","eternity"], ["לָכֵן","therefore"], ["כׇּל־הַיְלָדִים","all the children"], ["שָׁוִים","alike"], ["לִי","to me"], ["לָכֵן","therefore"], ["אוֹהֵב","love"], ["אֲנִי","I"], ["אֶת־הַיְלָדִים","the children"], ["הַקְּטַנִּים","the little"], ["בְּאַהֲבָה","in love"], ["שְׁלֵמָה","perfect"], ["וְכֻלָּם","and all of them"], ["שָׁוִים","alike"], ["וּמְקַבְּלֵי","and partakers of"], ["יְשׁוּעָה","salvation"], ["׃",""]]},
  { num: "יח", words: [["כִּי","for"], ["יוֹדֵעַ","know"], ["אֲנִי","I"], ["כִּי","that"], ["אֱלֹהִים","God"], ["אֵינֶנּוּ","he is not"], ["אֵל","a God"], ["נוֹשֵׂא","partial"], ["פָּנִים","of face"], ["וְלֹא","and not"], ["יְצוּר","a being"], ["מִשְׁתַּנֶּה","changeable"], ["כִּי־הוּא","but he is"], ["בִּלְתִּי","not"], ["מִשְׁתַּנֶּה","changeable"], ["מֵעוֹלָם","from all eternity"], ["וְעַד־עוֹלָם","to all eternity"], ["׃",""]]},
  { num: "יט", words: [["יְלָדִים","children"], ["קְטַנִּים","little"], ["אֵינָם","they are not"], ["יְכוֹלִים","able"], ["לָשׁוּב","to repent"], ["לָכֵן","therefore"], ["רֶשַׁע","wickedness"], ["נוֹרָא","awful"], ["הוּא","it is"], ["לִמְנֹעַ","to deny"], ["מֵהֶם","from them"], ["אֶת־רַחֲמֵי","the mercies of"], ["אֱלֹהִים","God"], ["הַטְּהוֹרִים","the pure"], ["כִּי","for"], ["כֻלָּם","all of them"], ["חַיִּים","living"], ["בּוֹ","in him"], ["בַּעֲבוּר","because of"], ["רַחֲמָיו","His mercy"], ["׃",""]]},
  { num: "כ", words: [["וְהָאוֹמֵר","and he that saith"], ["כִּי","that"], ["יְלָדִים","children"], ["קְטַנִּים","little"], ["צְרִיכִים","need"], ["טְבִילָה","baptism"], ["כּוֹפֵר","denieth"], ["בְּרַחֲמֵי","in mercies of"], ["הַמָּשִׁיחַ","Christ"], ["וּמְבַטֵּל","and setteth at naught"], ["אֶת־כַּפָּרָתוֹ","his atonement"], ["וְאֶת־כֹּחַ","and the power of"], ["גְּאֻלָּתוֹ","his redemption"], ["׃",""]]},
  { num: "כא", words: [["אוֹי","wo"], ["לָהֶם","to them"], ["כִּי","for"], ["הֵם","they"], ["מְחֻיְּבֵי","in the danger of"], ["מָוֶת","death"], ["וּשְׁאוֹל","hell"], ["וְעֹנֶשׁ","and torment"], ["אֵין־קֵץ","endless"], ["בְּתֹקֶף","with boldness"], ["אֲדַבֵּר","I speak it"], ["כִּי","that"], ["אֱלֹהִים","God"], ["צִוָּנִי","commanded me"], ["שִׁמְעוּ","listen"], ["וְהַקְשִׁיבוּ","and give heed"], ["לִדְבָרַי","to my words"], ["פֶּן־יַעַמְדוּ","or they stand"], ["לְשָׂטָן","against"], ["לָכֶם","to you"], ["לִפְנֵי","before"], ["כִּסֵּא־מִשְׁפַּט","the judgment seat of"], ["הַמָּשִׁיחַ","Christ"], ["׃",""]]},
  { num: "כב", words: [["כִּי","for"], ["הִנֵּה","behold"], ["כׇּל־הַיְלָדִים","all the children"], ["הַקְּטַנִּים","the little"], ["חַיִּים","living"], ["בַּמָּשִׁיחַ","in Christ"], ["וְגַם","and also"], ["כׇּל־אֲשֶׁר","all who"], ["בְּלִי","without"], ["תוֹרָה","law"], ["כִּי","for"], ["כֹחַ","power of"], ["הַגְּאֻלָּה","the redemption"], ["יָבוֹא","shall come"], ["עַל־כׇּל־אֲשֶׁר","upon all who"], ["אֵין","there is not"], ["לָהֶם","to them"], ["תוֹרָה","law"], ["לָכֵן","therefore"], ["אֲשֶׁר","he that"], ["לֹא","not"], ["נֶאְשַׁם","is condemned"], ["אוֹ","or"], ["אֲשֶׁר","he that"], ["תַּחַת","under"], ["אַשְׁמָה","condemnation"], ["לֹא־יִתֵּן","is not placed"], ["לֹא־יוּכַל","not is able"], ["לָשׁוּב","to repent"], ["וְלָאֵלֶּה","and unto such"], ["הַטְּבִילָה","the baptism"], ["לְרִיק","availeth nothing"], ["׃",""]]},
  { num: "כג", words: [["כִּי","but"], ["לֵץ","mockery"], ["הוּא","it is"], ["לִפְנֵי","before"], ["אֱלֹהִים","God"], ["לְכַחֵשׁ","denying"], ["בְּרַחֲמֵי","in mercies of"], ["הַמָּשִׁיחַ","Christ"], ["וּבְכֹחַ","and by the power of"], ["רוּחַ","spirit"], ["קׇדְשׁוֹ","his holiness"], ["וְלָשִׂים","and putting"], ["מִבְטָח","trust"], ["בְּמַעֲשֵׂי","in works of"], ["מָוֶת","death"], ["׃",""]]},
  { num: "כד", words: [["הִנֵּה","behold"], ["בְנִי","my son"], ["הַדָּבָר","the thing"], ["הַזֶּה","this"], ["לֹא־יִהְיֶה","ought not to be"], ["כִּי","for"], ["לָשׁוּב","repentance is"], ["לַאֲשֶׁר","unto them that are"], ["תַּחַת","under"], ["אַשְׁמָה","condemnation"], ["וְתַחַת","and under"], ["קִלְלַת","curse of"], ["הַתּוֹרָה","the law"], ["הַמּוּפָרָה","the broken"], ["׃",""]]},
  { num: "כה", words: [["וְרֵאשִׁית","and the first of"], ["פְּרִי","the fruits of"], ["הַתְּשׁוּבָה","repentance"], ["הִיא","is"], ["הַטְּבִילָה","the baptism"], ["וְהַטְּבִילָה","and the baptism"], ["בָּאָה","comes"], ["בֶּאֱמוּנָה","in faith"], ["לְהַשְׁלִים","unto the fulfilling"], ["אֶת־הַמִּצְוֹת","the commandments"], ["וְהַשְׁלָמַת","and the fulfilling of"], ["הַמִּצְוֹת","the commandments"], ["מֵבִיא","bringeth"], ["כִּי","that"], ["נִסְלְחוּ","remission of"], ["חֲטָאִים","sins"], ["׃",""]]},
  { num: "כו", words: [["וְהִסָּלַח","and remission of"], ["הַחֲטָאִים","the sins"], ["מֵבִיא","bringeth"], ["עֲנָוָה","meekness"], ["וְשִׁפְלוּת","and lowliness of"], ["לֵב","heart"], ["וּבַעֲבוּר","and because of"], ["הָעֲנָוָה","meekness"], ["וְשִׁפְלוּת","and lowliness of"], ["הַלֵּב","the heart"], ["יָבוֹא","cometh"], ["פְּקֻדַּת","the visitation of"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["הַמְּנַחֵם","which Comforter"], ["הַמְמַלֵּא","filleth"], ["בְּתִקְוָה","with hope"], ["וּבְאַהֲבָה","and with love"], ["שְׁלֵמָה","perfect"], ["אֲשֶׁר","which"], ["תַּעֲמֹד","endureth"], ["שֹׁקֶדֶת","by diligence"], ["בִּתְפִלָּה","unto prayer"], ["עַד־בּוֹא","until coming of"], ["הַקֵּץ","the end"], ["כַּאֲשֶׁר","when"], ["יֵשְׁבוּ","they shall dwell"], ["כׇּל־הַקְּדוֹשִׁים","all the saints"], ["עִם־אֱלֹהִים","with God"], ["׃",""]]},
  { num: "כז", words: [["הִנֵּה","behold"], ["בְנִי","my son"], ["אֶכְתֹּב","I will write"], ["אֵלֶיךָ","to you"], ["שֵׁנִית","again"], ["אִם־לֹא","if not"], ["אֵצֵא","I go out"], ["מְהֵרָה","soon"], ["עַל־הַלָּמָנִים","against the Lamanites"], ["הִנֵּה","behold"], ["זְדוֹן","the pride of"], ["הַגּוֹי","the nation"], ["הַזֶּה","this"], ["עַם","or the people of"], ["הַנֶּפִיִּים","the Nephites"], ["הָיָה","hath proven"], ["לְאׇבְדָנָם","for their destruction"], ["אִם־לֹא","except"], ["יָשׁוּבוּ","they should repent"], ["׃",""]]},
  { num: "כח", words: [["הִתְפַּלֵּל","pray"], ["בַּעֲדָם","on their behalf"], ["בְּנִי","my son"], ["לְמַעַן","in order that"], ["יָשׁוּבוּ","they may repent"], ["אַךְ","but"], ["הִנֵּה","behold"], ["יָרֵא","fear"], ["אֲנִי","I"], ["פֶּן־חָדְלָה","lest has ceased"], ["הָרוּחַ","the Spirit"], ["מֵהֵאָבֵק","striving"], ["עִמָּם","with them"], ["וּבַחֶבֶל","and in this part of"], ["הָאָרֶץ הַזֶּה","the land"], ["מְבַקְשִׁים","are also seeking"], ["הֵם","they"], ["לְהַשְׁפִּיל","to put down"], ["כׇּל־כֹּחַ","all power"], ["וְסַמְכוּת","and authority"], ["הַבָּא","that comes"], ["מֵאֱלֹהִים","from God"], ["וְכֹפְרִים","and they are denying"], ["בְּרוּחַ","in the Spirit"], ["הַקֹּדֶשׁ","the Holy"], ["׃",""]]},
  { num: "כט", words: [["וְאַחֲרֵי","and after"], ["מׇאֳסָם","their rejecting"], ["דַּעַת","knowledge"], ["גְּדוֹלָה","great"], ["כָּזֹאת","such as this"], ["בְּנִי","my son"], ["יֹאבְדוּ","they shall perish"], ["מְהֵרָה","soon"], ["לְמַלֹּאות","unto the fulfilling of"], ["אֶת־דִּבְרֵי","the words of"], ["הַנְּבִיאִים","the prophets"], ["אֲשֶׁר","which"], ["דִּבֵּרוּ","spoke"], ["וְגַם","and also"], ["אֶת־דִּבְרֵי","the words of"], ["מוֹשִׁיעֵנוּ","our Savior himself"], ["׃",""]]},
  { num: "ל", words: [
    ["שָׁלוֹם","farewell"],["בְּנִי","my son"],["עַד־אֶכְתֹּב","until I will write"],["אֵלֶיךָ","to you"],["אוֹ","or"],["עַד־אֶפְגָּשְׁךָ","until I meet you"],["שֵׁנִית","again"],["אָמֵן","amen"], ["׃",""]
  ]},
];
renderVerseSet(mr_ch8Verses, 'mr-ch8-verses');
var mr_ch9Verses = [
  { num: "א", words: [["בְּנִי","my son"], ["הָאָהוּב","the beloved"], ["כֹּתֵב","write"], ["אֲנִי","I"], ["אֵלֶיךָ","to you"], ["שֵׁנִית","again"], ["לְמַעַן","in order that"], ["תֵּדַע","you may know"], ["כִּי","that"], ["עוֹדֶנִּי","I am still"], ["חָי","alive"], ["אַךְ","but"], ["אֶכְתֹּב","I will write"], ["מְעַט","somewhat"], ["מֵאֲשֶׁר","of that which"], ["מַכְאִיב","is grievous"], ["׃",""]]},
  { num: "ב", words: [["כִּי","for"], ["הִנֵּה","behold"], ["הָיְתָה","there was"], ["לִי","to me"], ["מִלְחָמָה","a battle"], ["קָשָׁה","sore"], ["עִם־הַלָּמָנִים","with the Lamanites"], ["אֲשֶׁר","which"], ["לֹא","not"], ["גָבַרְנוּ","we conquer"], ["בָהּ","in it"], ["וְאַרְכְאַנְתּוּס","and Archeantus"], ["נָפַל","fell"], ["לְפִי־חֶרֶב","by the sword"], ["וְגַם־לוּרָם","and also Luram"], ["וְעֶמְרוֹן","and Emron"], ["וְאַף","yea"], ["אָבַדְנוּ","we have lost"], ["מִסְפַּר","a number"], ["רַב","great"], ["מֵאַנְשֵׁי","of men of"], ["מִבְחָרֵנוּ","our choicest"], ["׃",""]]},
  { num: "ג", words: [["וְעַתָּה","and now"], ["הִנֵּה","behold"], ["בְנִי","my son"], ["יָרֵא","fear"], ["אֲנִי","I"], ["פֶּן־יַשְׁחִיתוּ","lest they destroy"], ["הַלָּמָנִים","the Lamanites"], ["אֶת־הָעָם","the people"], ["הַזֶּה","this"], ["כִּי־לֹא","for not"], ["יָשׁוּבוּ","they repent"], ["וְהַשָּׂטָן","and Satan"], ["מְסִיתָם","stirreth them up"], ["תָּמִיד","continually"], ["לִכְעֹס","to anger"], ["אִישׁ","one"], ["בְּרֵעֵהוּ","with another"], ["׃",""]]},
  { num: "ד", words: [["הִנֵּה","behold"], ["עָמֵל","laboring"], ["אֲנִי","I"], ["עִמָּם","with them"], ["תָּמִיד","continually"], ["וְכַאֲשֶׁר","and when"], ["אֲדַבֵּר","I shall speak"], ["דְּבַר־אֱלֹהִים","word of God"], ["בְּחָזְקָה","with sharpness"], ["יִרְגָּזוּ","they tremble"], ["וְיִכְעֲסוּ","and are angry"], ["עָלָי","against me"], ["וְכַאֲשֶׁר","and when"], ["לֹא","not"], ["אֲדַבֵּר","I shall speak"], ["בְּחָזְקָה","with sharpness"], ["יַקְשׁוּ","they harden"], ["לִבָּם","their hearts"], ["נֶגְדּוֹ","against it"], ["לָכֵן","therefore"], ["יָרֵא","fear"], ["אֲנִי","I"], ["פֶּן־חָדְלָה","lest has ceased"], ["רוּחַ","the Spirit of"], ["יְהוָה","the Lord"], ["מֵהֵאָבֵק","from striving"], ["עִמָּם","with them"], ["׃",""]]},
  { num: "ה", words: [["כִּי","for"], ["יִכְעֲסוּ","they are angry"], ["עַד־מְאֹד","so exceedingly"], ["וְנִרְאֶה","that it seemeth"], ["לִי","to me"], ["כִּי","that"], ["אֵין","there is not"], ["בָּהֶם","in them"], ["יִרְאַת","fear of"], ["מָוֶת","death"], ["וְאָבְדָה","and they have lost"], ["אַהֲבָתָם","their love"], ["אִישׁ","one"], ["אֶל־רֵעֵהוּ","towards another"], ["וְצָמְאוּ","and they thirst"], ["לְדָם","for blood"], ["וּלְנָקָם","and revenge"], ["תָּמִיד","continually"], ["׃",""]]},
  { num: "ו", words: [["וְעַתָּה","and now"], ["בְּנִי","my son"], ["הָאָהוּב","the beloved"], ["אַף־גַּם־זֹאת","notwithstanding"], ["קְשִׁי","hardness of"], ["לִבָּם","their heart"], ["נַעֲבֹד","let us labor"], ["בְּחָזְקָה","diligently"], ["כִּי־אִם","for if"], ["נַחְדַּל","we cease"], ["מֵעֲבֹד","from laboring"], ["נוּבָא","we should be brought"], ["תַחַת","under"], ["אַשְׁמָה","condemnation"], ["כִּי","for"], ["יֶשׁ־לָנוּ","we have"], ["עֲבוֹדָה","a labor"], ["לַעֲשׂוֹת","to perform"], ["בְּעוֹדֵנוּ","whilst in"], ["בְּמִשְׁכַּן","in the tabernacle of"], ["הֶחָמֶר","the clay"], ["הַזֶּה","this"], ["לְמַעַן","in order that"], ["נִגְבַּר","we may conquer"], ["עַל־אוֹיֵב","the enemy of"], ["כׇּל־צְדָקָה","all righteousness"], ["וְתָנוּחַ","and rest"], ["נַפְשֵׁנוּ","our souls"], ["בְּמַלְכוּתוֹ","in the kingdom of God"], ["׃",""]]},
  { num: "ז", words: [["וְעַתָּה","and now"], ["אֶכְתֹּב","I will write"], ["מְעַט","somewhat"], ["עַל־עִנּוּיֵי","concerning the sufferings of"], ["הָעָם־הַזֶּה","this people"], ["כִּי","for"], ["לְפִי","according to"], ["הַדַּעַת","the knowledge"], ["אֲשֶׁר","which"], ["קִבַּלְתִּי","I received"], ["מֵאָמוֹרוֹן","from Amoron"], ["הִנֵּה","behold"], ["יֵשׁ","there is"], ["לַלָּמָנִים","of the Lamanites"], ["שְׁבוּיִים","prisoners"], ["רַבִּים","many"], ["אֲשֶׁר","which"], ["לָקְחוּ","they took"], ["מִמִּגְדַּל","from the tower of"], ["שֶׁרִיזָה","Sherrizah"], ["וְהָיוּ","and there were"], ["שָׁם","there"], ["אֲנָשִׁים","men"], ["וְנָשִׁים","and women"], ["וָטָף","and children"], ["׃",""]]},
  { num: "ח", words: [["וְאֶת־הַבְּעָלִים","and the husbands"], ["וַאֲבוֹת","and fathers of"], ["הַנָּשִׁים","those women"], ["וְהַיְלָדִים הָאֵלֶּה","and children"], ["הֵמִיתוּ","they have slain"], ["וַיַּאֲכִילוּ","and they feed"], ["אֶת־הַנָּשִׁים","the women"], ["מִבְּשַׂר","from the flesh of"], ["בַּעְלֵיהֶן","their husbands"], ["וְאֶת־הַיְלָדִים","and the children"], ["מִבְּשַׂר","from the flesh of"], ["אֲבוֹתֵיהֶם","their fathers"], ["וּמַיִם","and no water"], ["מְעַט","save a little"], ["יִתְּנוּ","do they give"], ["לָהֶם","to them"], ["׃",""]]},
  { num: "ט", words: [["וְאַף־גַּם־זֹאת","and notwithstanding"], ["הַתּוֹעֵבָה","the abomination"], ["הַגְּדוֹלָה הַזֹּאת","this great"], ["לַלָּמָנִים","of the Lamanites"], ["לֹא","not"], ["תִגְדַּל","doth exceed"], ["מֵאֲשֶׁר","than that of"], ["לְעַמֵּנוּ","our people"], ["בְּמוֹרִיאַנְטוּם","in Moriantum"], ["כִּי","for"], ["הִנֵּה","behold"], ["רַבּוֹת","many"], ["מִבְּנוֹת","from the daughters of"], ["הַלָּמָנִים","the Lamanites"], ["לָקְחוּ","they took"], ["בַשֶּׁבִי","prisoners"], ["וְאַחֲרֵי","and after"], ["גׇזְלָם","depriving them"], ["מֵהֶן","from them"], ["אֶת־אֲשֶׁר","which"], ["יָקָר","precious"], ["וְנִכְבָּד","and dear"], ["מִכֹּל","of all"], ["הוּא","which is"], ["הַבֹּשֶׁת","chastity"], ["וְהַטֹּהַר","and virtue"], ["׃",""]]},
  { num: "י", words: [["וְאַחֲרֵי","and after"], ["עֲשׂוֹתָם","their doing"], ["אֶת־הַדָּבָר","the thing"], ["הַזֶּה","this"], ["רָצְחוּ","they did murder"], ["אוֹתָן","them"], ["בְּאַכְזָרִיּוּת","with cruelty"], ["רַבָּה","great"], ["וַיְעַנּוּ","torturing"], ["אֶת־גְּוִיָּתָן","their bodies"], ["עַד־מָוֶת","until death"], ["וְאַחֲרֵי","and after"], ["עֲשׂוֹתָם","their doing"], ["זֹאת","this"], ["אָכְלוּ","they devour"], ["אֶת־בְּשָׂרָן","their flesh"], ["כְּחַיּוֹת","as beasts of"], ["הַשָּׂדֶה","the wild"], ["מִפְּנֵי","because of"], ["קְשִׁי","hardness of"], ["לִבָּם","their heart"], ["וַיַּעֲשׂוּ","and they did"], ["זֹאת","this"], ["לְאוֹת","for a token of"], ["גְּבוּרָה","bravery"], ["׃",""]]},
  { num: "יא", words: [["הוֹי","O"], ["בְּנִי","my son"], ["הָאָהוּב","the beloved"], ["אֵיךְ","how can"], ["יִהְיֶה","be"], ["עַם","a people"], ["כָּזֶה","such"], ["אֲשֶׁר","which"], ["בְּלִי","without"], ["דֶרֶךְ","civilization"], ["׃",""]]},
  { num: "יב", words: [["וְרַק","and only"], ["שָׁנִים","years"], ["מְעַטּוֹת","a few"], ["עָבְרוּ","passed"], ["וַיִּהְיוּ","and they were"], ["עַם","people"], ["יְשָׁרִים","civil"], ["וְנָעִים","and delightsome"], ["׃",""]]},
  { num: "יג", words: [["אַךְ","but"], ["הוֹי","O"], ["בְּנִי","my son"], ["אֵיךְ","how can"], ["יִהְיֶה","be"], ["עַם","a people"], ["כָּזֶה","such"], ["אֲשֶׁר","which"], ["שִׂמְחָתָם","their delight"], ["בְּתוֹעֵבָה","in abomination"], ["רַבָּה","so much"], ["כָּזֹאת","such"], ["׃",""]]},
  { num: "יד", words: [["אֵיךְ","how"], ["נְצַפֶּה","can we expect"], ["כִּי","that"], ["יַחְשֹׁךְ","will stay"], ["אֱלֹהִים","God"], ["יָדוֹ","his hand"], ["מִמִּשְׁפָּט","in judgment"], ["עָלֵינוּ","against us"], ["׃",""]]},
  { num: "טו", words: [["הִנֵּה","behold"], ["לִבִּי","my heart"], ["זֹעֵק","cries"], ["אוֹי","wo"], ["לָעָם","to the people"], ["הַזֶּה","this"], ["קוּמָה","come out"], ["לַמִּשְׁפָּט","to the judgment"], ["יְהוָה","O Lord"], ["וְהַסְתֵּר","and hide"], ["חַטֹּאתָם","their sins"], ["וְרִשְׁעָם","and their wickedness"], ["וְתוֹעֲבוֹתֵיהֶם","and their abominations"], ["מִלְּפָנֶיךָ","from before your face"], ["׃",""]]},
  { num: "טז", words: [["וְעוֹד","and again"], ["בְּנִי","my son"], ["אַלְמָנוֹת","widows"], ["רַבּוֹת","many"], ["וּבְנוֹתֵיהֶן","and their daughters"], ["נִשְׁאֲרוּ","remained"], ["בְּשֶׁרִיזָה","in Sherrizah"], ["וְאֵת","and"], ["חֵלֶק","that part of"], ["הַצֵּדָה","the provisions"], ["אֲשֶׁר","which"], ["לֹא","not"], ["לָקְחוּ","did carry away"], ["הַלָּמָנִים","the Lamanites"], ["הִנֵּה","behold"], ["צְבָא","army of"], ["זֶנֶפִי","Zenephi"], ["לָקַח","has carried away"], ["וַיַּעַזְבוּם","and left them"], ["לָנוּעַ","to wander"], ["לְבַקֵּשׁ","to seek"], ["אֹכֶל","food"], ["בַּאֲשֶׁר","whithersoever"], ["יִמְצָאוּ","they can"], ["וְנָשִׁים","and women"], ["זְקֵנוֹת","old"], ["רַבּוֹת","many"], ["יִתְעַלַּפְנָה","do faint"], ["בַדֶּרֶךְ","on the way"], ["וַתָּמֹתְנָה","and die"], ["׃",""]]},
  { num: "יז", words: [["וְהַצָּבָא","and the army"], ["אֲשֶׁר","which"], ["עִמִּי","with me"], ["חַלָּשׁ","is weak"], ["וְצִבְאוֹת","and the armies of"], ["הַלָּמָנִים","the Lamanites"], ["בֵּין","betwixt"], ["שֶׁרִיזָה","Sherrizah"], ["וּבֵינִי","and between me"], ["וְכׇל־אֲשֶׁר","and all who"], ["נָסוּ","fled"], ["אֶל־צְבָא","unto the army of"], ["אַהֲרֹן","Aaron"], ["נָפְלוּ","have fallen"], ["קׇרְבָּן","victims"], ["לְאַכְזָרִיּוּתָם","to their brutality"], ["הַנּוֹרָאָה","awful"], ["׃",""]]},
  { num: "יח", words: [["הוֹי","O"], ["מְשׁוּבַת","depravity of"], ["עַמִּי","my people"], ["בְּלִי","without"], ["מִשְׁפָּט","order"], ["וּבְלִי־רַחֲמִים","and without mercy"], ["הֵמָּה","they are"], ["הִנֵּה","behold"], ["אֲנִי","I"], ["רַק","but"], ["אִישׁ","a man"], ["וְרַק","and only"], ["כֹּחַ","the strength of"], ["אִישׁ","a man"], ["לִי","to me"], ["וְלֹא","and not"], ["אוּכַל","I am able"], ["עוֹד","anymore"], ["לְהַעֲמִיד","to enforce"], ["מִצְוֹתָי","my commands"], ["׃",""]]},
  { num: "יט", words: [["וַיֶּחֶזְקוּ","and they have become strong"], ["בְּסוּרָם","in their perversion"], ["וַיִּהְיוּ","and they are"], ["כְּחַיּוֹת","as beasts"], ["כֻּלָּם","alike"], ["לֹא","not"], ["יַחְמְלוּ","sparing"], ["עַל־אִישׁ","none"], ["לֹא","not"], ["זָקֵן","old"], ["וְלֹא","and not"], ["צָעִיר","young"], ["וְיִשְׂמְחוּ","and they delight"], ["בְּכׇל־דָּבָר","in everything"], ["זוּלַת","save"], ["הַטּוֹב","the good"], ["וְעִנּוּי","and the suffering of"], ["נָשֵׁינוּ","our women"], ["וִילָדֵינוּ","and our children"], ["עַל־כׇּל־פְּנֵי","upon all face of"], ["הָאָרֶץ","the land"], ["הַזֹּאת","this"], ["גָּדְלָה","doth exceed"], ["מִכֹּל","everything"], ["לֹא־תוּכַל","not can"], ["לָשׁוֹן","tongue"], ["לְסַפֵּר","to tell"], ["וְלֹא","and not"], ["יִכָּתֵב","can it be written"], ["׃",""]]},
  { num: "כ", words: [["וְעַתָּה","and now"], ["בְּנִי","my son"], ["לֹא","not"], ["אוֹסִיף","I dwell"], ["לְהַאֲרִיךְ","longer"], ["בַּמַּרְאֶה","upon the scene"], ["הַנּוֹרָא","the horrible"], ["הַזֶּה","this"], ["הִנֵּה","behold"], ["יָדַעְתָּ","you know"], ["רִשְׁעַת","wickedness of"], ["הָעָם־הַזֶּה","this people"], ["יָדַעְתָּ","you know"], ["כִּי","that"], ["הֵם","they"], ["בְּלִי־חֹק","without principle"], ["וּבְלִי־רַחֲמִים","and past feeling"], ["וְרִשְׁעָתָם","and their wickedness"], ["עָלְתָה","doth exceed"], ["עַל־רִשְׁעַת","that of"], ["הַלָּמָנִים","the Lamanites"], ["׃",""]]},
  { num: "כא", words: [["הִנֵּה","behold"], ["בְנִי","my son"], ["לֹא","not"], ["אוּכַל","I am able"], ["לְהַפְגִּיעַ","recommend"], ["בַּעֲדָם","them"], ["אֶל־אֱלֹהִים","unto God"], ["פֶּן־יַכֶּה","lest shall smite"], ["אֹתִי","me"], ["׃",""]]},
  { num: "כב", words: [["אַךְ","but"], ["הִנֵּה","behold"], ["בְנִי","my son"], ["אוֹתְךָ","you"], ["אַפְקִיד","I recommend"], ["בְּיַד־אֱלֹהִים","unto God"], ["וְאֶבְטַח","and I shall trust"], ["בַּמָּשִׁיחַ","in Christ"], ["כִּי","that"], ["תִּוָּשֵׁעַ","you will be saved"], ["וַאֲנִי","and I"], ["מִתְפַּלֵּל","pray"], ["אֶל־אֱלֹהִים","unto God"], ["לַחֲשֹׂךְ","he will spare"], ["חַיֶּיךָ","your life"], ["לִרְאוֹת","to witness"], ["שׁוּב","the return of"], ["עַמּוֹ","his people"], ["אֵלָיו","unto him"], ["אוֹ","or"], ["שִׁבְרָם","their destruction"], ["כָּלִיל","utter"], ["כִּי","that"], ["יָדַעְתִּי","I know"], ["כִּי","that"], ["יֹאבֵדוּ","they shall perish"], ["אִם־לֹא","except"], ["יָשׁוּבוּ","they repent"], ["וְיָשׁוּבוּ","and return"], ["אֵלָיו","unto him"], ["׃",""]]},
  { num: "כג", words: [["וְאִם־יֹאבֵדוּ","and if they shall perish"], ["יִהְיֶה","it will be"], ["כַּיָּרֶדִים","as the Jaredites"], ["בַּעֲבוּר","because of"], ["זְדוֹן","the willfulness of"], ["לִבָּם","their hearts"], ["בְּבַקְשָׁם","seeking"], ["דָּם","blood"], ["וְנָקָם","and revenge"], ["׃",""]]},
  { num: "כד", words: [["וְאִם־כֵּן","and if thus"], ["יִהְיֶה","it so be"], ["כִּי","that"], ["יֹאבֵדוּ","they shall perish"], ["יָדַעְנוּ","we know"], ["כִּי־רַבִּים","that many"], ["מֵאַחֵינוּ","of our brethren"], ["עָבְרוּ","have deserted over"], ["אֶל־הַלָּמָנִים","unto the Lamanites"], ["וְרַבִּים","and many"], ["עוֹד","more"], ["יַעַבְרוּ","will also desert over"], ["אֲלֵיהֶם","to them"], ["לָכֵן","therefore"], ["כְּתֹב","write"], ["דְּבָרִים","things"], ["מְעַטִּים","few"], ["אִם־תִּנָּצֵל","if you are spared"], ["וַאֲנִי","and I"], ["אֶגְוַע","I shall perish"], ["וְלֹא","and not"], ["אֶרְאֶךָּ","see you"], ["אַךְ","but"], ["אֶבְטַח","I shall trust"], ["כִּי","that"], ["אֶרְאֶךָ","see you"], ["מְהֵרָה","soon"], ["כִּי־יֵשׁ","that there is"], ["לִי","to me"], ["כִּתְבֵי","records"], ["קֹדֶשׁ","sacred"], ["אֲשֶׁר","which"], ["אֶתְּנֵם","I would deliver up"], ["לְךָ","unto you"], ["׃",""]]},
  { num: "כה", words: [["בְּנִי","my son"], ["הֱיֵה","be"], ["נֶאֱמָן","faithful"], ["בַּמָּשִׁיחַ","in Christ"], ["וְאַל־יַעֲצִבוּךָ","and may not grieve you"], ["הַדְּבָרִים","the things"], ["אֲשֶׁר","which"], ["כָּתַבְתִּי","I wrote"], ["לְהַכְבִּידְךָ","to weigh you down"], ["עַד־מָוֶת","until death"], ["אַךְ","but"], ["יְרוֹמֵם","may lift up"], ["אוֹתְךָ","you"], ["הַמָּשִׁיחַ","Christ"], ["וִיהִי","and may be"], ["עִנּוּיָיו","his sufferings"], ["וּמוֹתוֹ","and his death"], ["וְהַרְאוֹת","and showing of"], ["גְּוִיָּתוֹ","his body"], ["לַאֲבוֹתֵינוּ","to our fathers"], ["וְחַסְדּוֹ","and his mercy"], ["וְאֹרֶךְ","and the longsuffering of"], ["רוּחוֹ","his spirit"], ["וְתִקְוַת","and hope of"], ["כְּבוֹדוֹ","his glory"], ["וְחַיֵּי","and life of"], ["עוֹלָם","eternity"], ["שׁוֹכְנִים","rest"], ["בְּרוּחֲךָ","in your mind"], ["לָעַד","forever"], ["׃",""]]},
  { num: "כו", words: [["וִיהִי","and may be"], ["חֶסֶד","the grace of"], ["אֱלֹהִים","God"], ["הָאָב","the Father"], ["אֲשֶׁר","which"], ["כִּסְאוֹ","his throne"], ["רָם","is high"], ["בַּשָּׁמַיִם","in the heavens"], ["וַאֲדֹנֵנוּ","and our Lord"], ["יֵשׁוּעַ","Jesus"], ["הַמָּשִׁיחַ","Christ"], ["הַיּוֹשֵׁב","who sitteth"], ["לִימִין","on the right hand of"], ["גְּבוּרָתוֹ","his power"], ["עַד","until"], ["יִהְיוּ","they shall be"], ["כׇל־הַדְּבָרִים","all the things"], ["נִכְנָעִים","subject"], ["לוֹ","to him"], ["עִמְּךָ","with you"], ["וְיִשְׁכְּנוּ","and abide"], ["בְּךָ","with you"], ["לְעוֹלָם","forever"], ["אָמֵן","amen"], ["׃",""]]},
];
renderVerseSet(mr_ch9Verses, 'mr-ch9-verses');
var mr_ch10Verses = [
  { num: "א", words: [["וְעַתָּה","and now"], ["אֲנִי","I"], ["מוֹרוֹנִי","Moroni"], ["כֹּתֵב","write"], ["כַּאֲשֶׁר","as"], ["יָשַׁר","seemeth good"], ["בְּעֵינַי","in my eyes"], ["וְכֹתֵב","and writing"], ["אֲנִי","I"], ["לְאַחַי","unto my brethren"], ["הַלָּמָנִים","the Lamanites"], ["וַאֲנִי","and I"], ["חָפֵץ","would"], ["כִּי","that"], ["יֵדְעוּ","they should know"], ["כִּי","that"], ["עָבְרוּ","have passed"], ["יוֹתֵר","more than"], ["מֵאַרְבַּע","four"], ["מֵאוֹת","hundred"], ["וְעֶשְׂרִים","and twenty"], ["שָׁנָה","years"], ["מֵאָז","since"], ["נִתַּן","was given"], ["הָאוֹת","the sign"], ["לְבוֹא","of the coming of"], ["הַמָּשִׁיחַ","Christ"], ["׃",""]]},
  { num: "ב", words: [
    ["וְאֶחְתֹּם","and I shall seal up"],["אֶת־הַסְּפָרִים","the records"], ["הָאֵלֶּה","these"],["אַחֲרֵי","after"],["דַבְּרִי","I have spoken"],["דְבָרִים","words"],["מְעַטִּים","a few"],["לְהַזְהִירְכֶם","by the way of exhortation unto you"], ["׃",""]
  ]},
  { num: "ג", words: [["הִנֵּה","behold"], ["אַזְהִיר","I would exhort"], ["אֶתְכֶם","you"], ["כִּי","that"], ["בְּקׇרְאֲכֶם","when you shall read"], ["אֶת־הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["אִם־חׇכְמָה","if be wisdom"], ["הִיא","it is"], ["בְּעֵינֵי","in the eyes of"], ["אֱלֹהִים","God"], ["כִּי","that"], ["תִקְרְאוּם","you should read them"], ["כִּי","that"], ["תִזְכְּרוּ","you would remember"], ["מַה־רַב","how great is"], ["חֶסֶד","the mercy of"], ["יְהוָה","the Lord"], ["עִם־בְּנֵי","unto the children of"], ["הָאָדָם","men"], ["מִבְּרִיאַת","from the creation of"], ["אָדָם","man"], ["וְעַד־הָעֵת","and even unto the time"], ["אֲשֶׁר","that"], ["תְּקַבְּלוּ","you shall receive"], ["הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["וַהֲגִיתֶם","and ponder it"], ["בִּלְבַבְכֶם","in your hearts"], ["׃",""]]},
  { num: "ד", words: [["וּבְקַבֶּלְכֶם","and when you shall receive"], ["אֶת־הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["אַזְהִיר","I would exhort"], ["אֶתְכֶם","you"], ["כִּי","that"], ["תִשְׁאֲלוּ","you would ask"], ["מֵאֱלֹהִים","God"], ["הָאָב","the Father"], ["אֲשֶׁר־לְעוֹלָם","the Eternal"], ["בְּשֵׁם","in the name of"], ["הַמָּשִׁיחַ","Christ"], ["אִם־לֹא","if not"], ["אֱמֶת","are true"], ["הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["וְאִם־שָׁאֹל","and if with real intent"], ["תִּשְׁאֲלוּ","you shall ask"], ["בְּלֵב","with a heart"], ["תָּמִים","sincere"], ["וֶאֱמוּנָה","having faith"], ["בַּמָּשִׁיחַ","in Christ"], ["יַגְלֶה","he will manifest"], ["לָכֶם","unto you"], ["אֲמִתָּתָם","the truth of it"], ["בְּכֹחַ","by the power of"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["׃",""]]},
  { num: "ה", words: [["וּבְכֹחַ","and by the power of"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["תּוּכְלוּ","you may"], ["לָדַעַת","know"], ["אֲמִתַּת","the truth of"], ["כׇּל־דָּבָר","all things"], ["׃",""]]},
  { num: "ו", words: [["וְכׇל־דָּבָר","and whatsoever thing"], ["טוֹב","good"], ["צַדִּיק","just"], ["וֶאֱמֶת","and true"], ["הוּא","is"], ["לָכֵן","wherefore"], ["כׇּל־טוֹב","nothing that is good"], ["לֹא־יְכַחֵשׁ","denieth"], ["בַּמָּשִׁיחַ","in Christ"], ["כִּי־אִם","but rather"], ["יוֹדֶה","acknowledgeth"], ["כִּי־הוּא","that He is"], ["׃",""]]},
  { num: "ז", words: [["וּבְכֹחַ","and by the power of"], ["רוּחַ","the Spirit of"], ["הַקֹּדֶשׁ","the Holy"], ["תֵּדְעוּ","you may know"], ["כִּי־הוּא","that He is"], ["לָכֵן","wherefore"], ["אַזְהִיר","I would exhort"], ["אֶתְכֶם","you"], ["לְבַל","that you"], ["תְּכַחֲשׁוּ","deny not"], ["בְּכֹחַ","the power of"], ["אֱלֹהִים","God"], ["כִּי־הוּא","for He"], ["פֹּעֵל","worketh"], ["בְּכֹחַ","by power"], ["כְּפִי","according to"], ["אֱמוּנַת","the faith of"], ["בְּנֵי־הָאָדָם","the children of men"], ["הוּא","he is"], ["הָאֵל","the same"], ["הַיּוֹם","today"], ["וּמָחָר","and tomorrow"], ["וּלְעוֹלָם","and forever"], ["׃",""]]},
  { num: "ח", words: [["וְעוֹד","and again"], ["אַזְהִיר","I exhort"], ["אֶתְכֶם","you"], ["אַחַי","my brethren"], ["אַל־תְּכַחֲשׁוּ","that you deny not"], ["בְּמַתְּנוֹת","the gifts of"], ["אֱלֹהִים","God"], ["כִּי","for"], ["רַבּוֹת","are many"], ["הֵנָּה","they"], ["וּמֵאֵל","and from God"], ["אֶחָד","the same"], ["בָּאוֹת","they come"], ["וְיֵשׁ","and there are"], ["דְּרָכִים","ways"], ["שׁוֹנוֹת","different"], ["אֲשֶׁר","that"], ["בָּהֶן","in them"], ["נִתָּנוֹת","are administered"], ["הַמַּתָּנוֹת","the gifts"], ["הָאֵלֶּה","these"], ["אַךְ","but"], ["הוּא","it is"], ["הָאֵל","God"], ["הָאֶחָד","the same"], ["הַפֹּעֵל","who worketh"], ["הַכֹּל","all"], ["בַּכֹּל","in all"], ["וְנִתָּנוֹת","and they are given"], ["אַף","yea"], ["בַּחֲזוֹן","by the manifestations of"], ["רוּחַ","the Spirit of"], ["אֱלֹהִים","God"], ["לִבְנֵי־הָאָדָם","unto men"], ["לְהוֹעִילָם","to profit them"], ["׃",""]]},
  { num: "ט", words: [["כִּי","for"], ["הִנֵּה","behold"], ["לָאֶחָד","to one"], ["נִתָּן","is given"], ["בְּרוּחַ","by the Spirit"], ["אֱלֹהִים","of God"], ["לְלַמֵּד","to teach"], ["דְּבַר","the word of"], ["חׇכְמָה","wisdom"], ["׃",""]]},
  { num: "י", words: [
    ["וּלְאַחֵר","and to another"],["לְלַמֵּד","to teach"],["דְּבַר","the word of"],["דַּעַת","knowledge"],["בָּרוּחַ","in the Spirit"], ["הַהִיא","that"], ["׃",""]
  ]},
  { num: "יא", words: [
    ["וּלְאַחֵר","and to another"],["אֱמוּנָה","faith"],["גְדוֹלָה","great"],["מְאֹד","exceedingly"],["וּלְאַחֵר","and to another"],["מַתְּנוֹת","the gifts of"],["הָרְפוּאָה","healing"],["בָּרוּחַ","in the Spirit"], ["הַהִיא","that"], ["׃",""]
  ]},
  { num: "יב", words: [["וְעוֹד","and again"], ["לְאַחֵר","to another"], ["לַעֲשׂוֹת","to do"], ["נִפְלָאוֹת","miracles"], ["גְּדוֹלוֹת","great"], ["׃",""]]},
  { num: "יג", words: [
    ["וְעוֹד","and again"],["לְאַחֵר","to another"],["לְהִנָּבֵא","that he may prophesy"],["עַל־כׇּל־דָּבָר","upon all things"], ["׃",""]
  ]},
  { num: "יד", words: [
    ["וְעוֹד","and again"],["לְאַחֵר","to another"],["לִרְאוֹת","to see"],["מַלְאָכִים","angels"],["וְרוּחוֹת","and spirits"],["מְשָׁרְתִים","ministering"], ["׃",""]
  ]},
  { num: "טו", words: [
    ["וְעוֹד","and again"],["לְאַחֵר","to another"],["כׇּל־מִינֵי","all manner of"],["לְשׁוֹנוֹת","tongues"], ["׃",""]
  ]},
  { num: "טז", words: [["וְעוֹד","and again"], ["לְאַחֵר","to another"], ["פִּתְרוֹן","the interpretation of"], ["שָׂפוֹת","languages"], ["וּמִינֵי","and of kinds of"], ["לְשׁוֹנוֹת","tongues"], ["שׁוֹנִים","divers"], ["׃",""]]},
  { num: "יז", words: [["וְכׇל־הַמַּתָּנוֹת","and the all gifts"], ["הָאֵלֶּה","these"], ["בָּאוֹת","come"], ["בְּרוּחַ","in the Spirit"], ["הַמָּשִׁיחַ","Christ"], ["וְתָבֹאנָה","and they shall come"], ["לְכׇל־אִישׁ","unto every man"], ["לְבַדּוֹ","severally"], ["כַּאֲשֶׁר","according as"], ["יַחְפֹּץ","he will"], ["׃",""]]},
  { num: "יח", words: [
    ["וַאֲנִי","and I"],["מַזְהִיר","would exhort"],["אֶתְכֶם","you"],["אַחַי","my brethren"],["הָאֲהוּבִים","beloved"],["כִּי","that"],["תִזְכְּרוּ","you remember"],["כִּי","that"],["כׇּל־מַתָּנָה","every gift"],["טוֹבָה","good"],["בָּאָה","comes"],["מֵאֵת","of"],["הַמָּשִׁיחַ","Christ"], ["׃",""]
  ]},
  { num: "יט", words: [["וַאֲנִי","and I"], ["מַזְהִיר","would exhort"], ["אֶתְכֶם","you"], ["אַחַי","my brethren"], ["הָאֲהוּבִים","beloved"], ["כִּי","that"], ["תִזְכְּרוּ","you remember"], ["כִּי","that"], ["הוּא","He is"], ["הוּא","the same"], ["אֶתְמוֹל","yesterday"], ["הַיּוֹם","today"], ["וּלְעוֹלָם","and forever"], ["וְכׇל־הַמַּתָּנוֹת","and the all gifts"], ["הָאֵלֶּה","these"], ["אֲשֶׁר","which"], ["דִּבַּרְתִּי","I have spoken"], ["עֲלֵיהֶן","of them"], ["אֲשֶׁר","which"], ["לָרוּחַ","spiritual"], ["הֵנָּה","are"], ["לֹא","not"], ["תִכָּלֶינָה","shall be done away"], ["לְעוֹלָם","ever"], ["כׇּל־עוֹד","as long as"], ["תַּעֲמֹד","shall stand"], ["הָאָרֶץ","the world"], ["זוּלַת","only"], ["בְּאֵין","in the absence of"], ["אֱמוּנַת","the faith of"], ["בְּנֵי־הָאָדָם","the children of men"], ["׃",""]]},
  { num: "כ", words: [["לָכֵן","wherefore"], ["תִּהְיֶה","there must be"], ["אֱמוּנָה","faith"], ["וְאִם־תִּהְיֶה","and if there must be"], ["אֱמוּנָה","faith"], ["תִּהְיֶה","there must also be"], ["גַּם־תִּקְוָה","also hope"], ["וְאִם־תִּהְיֶה","and if there must be"], ["תִּקְוָה","hope"], ["תִּהְיֶה","there must also be"], ["גַּם","also"], ["אַהֲבָה","charity"], ["׃",""]]},
  { num: "כא", words: [["וּבִלְתִּי","and except"], ["אִם־יֵשׁ","if there is"], ["לָכֶם","to you"], ["אַהֲבָה","charity"], ["הִוָּשֵׁעַ","in nowise"], ["לֹא","not"], ["תִּוָּשְׁעוּ","can you be saved"], ["בְּמַלְכוּתוֹ","in the kingdom of God"], ["וְלֹא","and neither"], ["תִּוָּשְׁעוּ","you can be saved"], ["בְּמַלְכוּתוֹ","in the kingdom of God"], ["אִם־אֵין","if there is no"], ["לָכֶם","to you"], ["אֱמוּנָה","faith"], ["וְגַם","and also"], ["לֹא","not"], ["אִם־אֵין","if there is no"], ["לָכֶם","to you"], ["תִּקְוָה","hope"], ["׃",""]]},
  { num: "כב", words: [["וְאִם־אֵין","and if there is no"], ["לָכֶם","to you"], ["תִּקְוָה","hope"], ["נוֹאָשִׁים","in despair"], ["תִּהְיוּ","you shall be"], ["וְהַנֹּאָשׁ","and despair"], ["בָּא","cometh"], ["מֵעָוֹן","because of iniquity"], ["׃",""]]},
  { num: "כג", words: [["וְהַמָּשִׁיחַ","and Christ"], ["אָמַר","said"], ["בֶּאֱמֶת","truly"], ["לַאֲבוֹתֵינוּ","unto our fathers"], ["אִם־יֵשׁ","if there is"], ["לָכֶם","to you"], ["אֱמוּנָה","faith"], ["תּוּכְלוּ","you can"], ["לַעֲשׂוֹת","do"], ["כׇּל־דָּבָר","all things"], ["הַמּוֹעִיל","which is expedient"], ["לִי","to me"], ["׃",""]]},
  { num: "כד", words: [["וְעַתָּה","and now"], ["אֲדַבֵּר","I shall speak"], ["אֶל־כׇּל־קְצוֹת","unto all the ends of"], ["הָאָרֶץ","the earth"], ["כִּי־אִם","that if"], ["יָבוֹא","shall come"], ["יוֹם","a day"], ["אֲשֶׁר","that"], ["כֹּחַ","the power"], ["אֱלֹהִים","of God"], ["וּמַתְּנוֹתָיו","and gifts"], ["יִכָּלוּ","they shall be done away"], ["בְּקִרְבְּכֶם","among you"], ["יִהְיֶה","it shall be"], ["זֶה","this"], ["בְּאֵין","because of the lack of"], ["אֱמוּנָה","faith"], ["׃",""]]},
  { num: "כה", words: [["וְאוֹי","and wo be"], ["לִבְנֵי־הָאָדָם","unto the children of men"], ["אִם־כֵּן","if thus"], ["יִהְיֶה","it be"], ["כִּי־לֹא","for not"], ["יִהְיֶה","there shall be"], ["עֹשֵׂה","that doeth"], ["טוֹב","good"], ["בָּכֶם","among you"], ["אַף","no"], ["לֹא","not"], ["אֶחָד","one"], ["כִּי־אִם","for if"], ["יֵשׁ","there be"], ["אֶחָד","one"], ["בָּכֶם","among you"], ["הָעֹשֶׂה","that doeth"], ["טוֹב","good"], ["יַעֲשֶׂה","he shall work"], ["בְּכֹחַ","by the power"], ["וּבְמַתְּנוֹת","and gifts of"], ["אֱלֹהִים","God"], ["׃",""]]},
  { num: "כו", words: [["וְאוֹי","and wo unto"], ["לָהֶם","them"], ["אֲשֶׁר","who"], ["יָסִירוּ","shall do away"], ["אֶת־הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["וְיָמוּתוּ","and die"], ["כִּי","for"], ["יָמוּתוּ","they die"], ["בְּחַטֹּאתָם","in their sins"], ["וְלֹא","and not"], ["יוּכְלוּ","they are able"], ["לְהִוָּשַׁע","be saved"], ["בְּמַלְכוּתוֹ","in the kingdom of God"], ["וַאֲנִי","and I"], ["מְדַבֵּר","speak it"], ["כְּפִי","according to"], ["דִבְרֵי","the words of"], ["הַמָּשִׁיחַ","Christ"], ["וְלֹא","and not"], ["אֲכַזֵּב","I lie"], ["׃",""]]},
  { num: "כז", words: [["וַאֲנִי","and I"], ["מַזְהִיר","exhort"], ["אֶתְכֶם","you"], ["לִזְכֹּר","to remember"], ["אֶת־הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["כִּי","for"], ["יְמַהֵר","shall hasten"], ["לָבוֹא","to come"], ["הָעֵת","the time"], ["אֲשֶׁר","that"], ["תֵּדְעוּ","you shall know"], ["כִּי־לֹא","that not"], ["אֲכַזֵּב","I lie"], ["כִּי","for"], ["תִרְאוּנִי","you shall see me"], ["לִפְנֵי","before"], ["כִּסֵּא","the bar of"], ["אֱלֹהִים","God"], ["וַיהוָה","and the Lord"], ["אֱלֹהִים","God"], ["יֹאמַר","he will say"], ["לָכֶם","unto you"], ["הֲלֹא","did I not"], ["הִגַּדְתִּי","declare"], ["לָכֶם","unto you"], ["אֶת־דְּבָרַי","my words"], ["אֲשֶׁר","which were"], ["נִכְתְּבוּ","written"], ["בְּיַד־הָאִישׁ","by the hand of man"], ["הַזֶּה","this"], ["כְּקוֹל","like as"], ["קוֹרֵא","one crying"], ["מִן־הַמֵּתִים","from the dead"], ["אַף","yea"], ["כְּדוֹבֵר","even as one speaking"], ["מִן־הֶעָפָר","out of the dust"], ["׃",""]]},
  { num: "כח", words: [["מַגִּיד","declare"], ["אֲנִי","I"], ["אֶת־הַדְּבָרִים","the things"], ["הָאֵלֶּה","these"], ["לְמַלֹּאות","unto the fulfilling of"], ["אֶת־הַנְּבוּאוֹת","the prophecies"], ["וְהִנֵּה","and behold"], ["יֵצְאוּ","they shall proceed"], ["מִפִּי","out of the mouth of"], ["אֵל","the God of"], ["עוֹלָם","eternal"], ["וּדְבָרוֹ","and His word"], ["יִשְׁרֹק","shall hiss forth"], ["מִדּוֹר","from generation"], ["לְדוֹר","to generation"], ["׃",""]]},
  { num: "כט", words: [["וֵאלֹהִים","and God"], ["יַרְאֶה","shall show"], ["לָכֶם","unto you"], ["כִּי","that"], ["אֲשֶׁר","that which"], ["כָּתַבְתִּי","I have written"], ["אֱמֶת","true"], ["הוּא","is"], ["׃",""]]},
  { num: "ל", words: [["וְעוֹד","and again"], ["אַזְהִיר","I would exhort"], ["אֶתְכֶם","you"], ["כִּי","that"], ["תָבֹאוּ","you would come"], ["אֶל־הַמָּשִׁיחַ","unto Christ"], ["וְהַחֲזִיקוּ","and lay hold upon"], ["בְּכׇל־מַתָּנָה","upon every gift"], ["טוֹבָה","good"], ["וְאַל־תִּגְּעוּ","and touch not"], ["בַּמַּתָּנָה","the gift"], ["הָרָעָה","the evil"], ["וְלֹא","nor"], ["בַדָּבָר","the thing"], ["הַטָּמֵא","the unclean"], ["׃",""]]},
  { num: "לא", words: [["הָקִיצִי","awake"], ["וְקוּמִי","and arise"], ["מֵעָפָר","from the dust"], ["יְרוּשָׁלָ͏ִם","O Jerusalem"], ["אַף","yea"], ["לִבְשִׁי","put on"], ["בִגְדֵי","your garments of"], ["תִפְאַרְתֵּךְ","beauty"], ["בַּת־צִיּוֹן","O daughter of Zion"], ["וְחַזְּקִי","and strengthen"], ["יְתֵדוֹתַיִךְ","your stakes"], ["וְהַרְחִיבִי","and enlarge"], ["גְּבוּלוֹתַיִךְ","your borders"], ["לָעַד","forever"], ["לְמַעַן","that"], ["לֹא־תֵבוֹשִׁי","not be confounded"], ["עוֹד","more"], ["לְמַעַן","that"], ["יָקוּמוּ","they shall stand"], ["בְּרִיתוֹת","the covenants of"], ["הָאָב","the Father"], ["אֲשֶׁר־לְעוֹלָם","the Eternal"], ["אֲשֶׁר","which"], ["כָּרַת","He hath made"], ["לָךְ","unto you"], ["בֵּית־יִשְׂרָאֵל","O house of Israel"], ["׃",""]]},
  { num: "לב", words: [["הֵן","yea"], ["בֹּאוּ","come"], ["אֶל־הַמָּשִׁיחַ","unto Christ"], ["וִהְיוּ","and be"], ["שְׁלֵמִים","perfected"], ["בוֹ","in Him"], ["וְהִתְנַזְּרוּ","and deny yourselves"], ["מִכׇּל־רֶשַׁע","of all ungodliness"], ["וְאִם־תִּתְנַזְּרוּ","and if you shall deny yourselves"], ["מִכׇּל־רֶשַׁע","of all ungodliness"], ["וַאֲהַבְתֶּם","and love"], ["אֱלֹהִים","God"], ["בְּכׇל־מְאֹדְכֶם","with all your might"], ["וְנַפְשְׁכֶם","and mind"], ["וּכֹחֲכֶם","and strength"], ["אָז","then"], ["יַסְפִּיק","is sufficient"], ["חַסְדּוֹ","His grace"], ["לָכֶם","for you"], ["לְמַעַן","that"], ["תִּהְיוּ","you may be"], ["שְׁלֵמִים","perfect"], ["בַּמָּשִׁיחַ","in Christ"], ["בְּחַסְדּוֹ","by His grace"], ["וְאִם־בְּחֶסֶד","and if by the grace of"], ["אֱלֹהִים","God"], ["אַתֶּם","you"], ["שְׁלֵמִים","perfect"], ["בַּמָּשִׁיחַ","in Christ"], ["לֹא","not"], ["תוּכְלוּ","you can"], ["לְכַחֵשׁ","deny"], ["בְּכֹחַ","the power of"], ["אֱלֹהִים","God"], ["׃",""]]},
  { num: "לג", words: [["וְעוֹד","and again"], ["אִם־בְּחֶסֶד","if by the grace of"], ["אֱלֹהִים","God"], ["אַתֶּם","you"], ["שְׁלֵמִים","perfect"], ["בַּמָּשִׁיחַ","in Christ"], ["וְלֹא","and not"], ["תְכַחֲשׁוּ","deny"], ["בְּכֹחוֹ","in His power"], ["אָז","then"], ["תִּתְקַדְּשׁוּ","you will be sanctified"], ["בַּמָּשִׁיחַ","in Christ"], ["בְּחֶסֶד","by the grace of"], ["אֱלֹהִים","God"], ["עַל־יְדֵי","through"], ["שְׁפִיכַת","the shedding of"], ["דַּם","the blood of"], ["הַמָּשִׁיחַ","Christ"], ["אֲשֶׁר","which is"], ["בִּבְרִית","in the covenant of"], ["הָאָב","the Father"], ["לְהִסָּלַח","for the remission of"], ["חַטֹּאתֵיכֶם","your sins"], ["לִהְיוֹת","to be"], ["קְדוֹשִׁים","holy"], ["בְּלִי־מוּם","without spot"], ["׃",""]]},
  { num: "לד", words: [["וְעַתָּה","and now"], ["אֹמַר","I bid"], ["לְכֻלְּכֶם","unto all"], ["שָׁלוֹם","farewell"], ["מְהֵרָה","soon"], ["אָנוּחַ","I shall rest"], ["בְּגַן־עֵדֶן","in the paradise of"], ["אֱלֹהִים","God"], ["עַד","until"], ["יִתְחַבְּרוּ","they shall reunite"], ["רוּחִי","my spirit"], ["וּגְוִיָּתִי","and my body"], ["שֵׁנִית","again"], ["וְאוּבָא","and I am brought forth"], ["מְנַצֵּחַ","triumphant"], ["דֶּרֶךְ","through"], ["הָרָקִיעַ","the air"], ["לִפְגֹּשׁ","to meet"], ["אֶתְכֶם","you"], ["לִפְנֵי","before"], ["כִּסֵּא","the bar of"], ["הַמִּשְׁפָּט","judgment"], ["הַנָּעִים","the pleasing"], ["לִפְנֵי","of"], ["יְהוָה","Jehovah"], ["הַגָּדוֹל","the great"], ["שׁוֹפֵט","the Judge of"], ["הַחַיִּים","both quick"], ["וְהַמֵּתִים","and the dead"], ["אֲשֶׁר־לְעוֹלָם","the Eternal"], ["אָמֵן","amen"], ["׃",""]]}
];
renderVerseSet(mr_ch10Verses, 'mr-ch10-verses');
})();
