// verses/words_of_mormon.js — Words of Mormon verse data
(function() {
var wm_ch1Verses = [
  { num:"א", words:[
    ["וְעַתָּה","and-now"],["קָרוֹב","soon"],["מוֹרְמוֹן","I-Mormon"],["לִמְסֹר","to-deliver-up"],["אֶת־הַכְּתָבִים","the-record"],["אֲשֶׁר","which"],["עָשִׂיתִי","I-made"],["בְּיַד","into-the-hands-of"],["בְּנִי","my-son"],["מוֹרוֹנִי","Moroni"],["הִנֵּה","behold"],["רָאִיתִי","I-saw"],["כִּמְעַט","nearly"],["אֶת־כָּל־הַשְׁמָדַת","all-the-destruction-of"],["עַמִּי","my-people"],["הַנֶּפִים","the-Nephites"],
  ]},
  { num:"ב", words:[
    ["וּמֵאוֹת","and-it-is-many-hundred"],["שָׁנִים","years"],["רַבּוֹת","many"],["אַחֲרֵי","after"],["בּוֹא","the-coming-of"],["הַמָּשִׁיחַ","the-Messiah"],["אֲנִי","I"],["מוֹסֵר","deliver"],["אֶת־הַכְּתָבִים","these-records"],["הָאֵלֶּה","these"],["בְּיַד","into-the-hands-of"],["בְּנִי","my-son"],["וַאֲנִי","and-I"],["מְשַׁעֵר","suppose"],["כִּי","that"],["יִרְאֶה","He-shall-manifest-Himself"],["אֶת־הַשְׁמָדַת","the-complete-destruction-of"],["עַמִּי","my-people"],["כֻּלָּהּ","all-of-it(f)"],["אַךְ","but"],["יִתֵּן","he-shall-give"],["אֱלֹהִים","God"],["כִּי","that"],["יִשְׂרֹד","he-may-survive-them"],["מֵהֶם","from-them"],["לְמַעַן","that"],["יִכְתֹּב","he-may-write"],["מְעַט","somewhat"],["עֲלֵיהֶם","concerning-them"],["וּמְעַט","and-somewhat"],["עַל־דְּבַר","upon-the-matter-of"],["הַמָּשִׁיחַ","the-Messiah"],["אוּלַי","perhaps"],["יוֹעִיל","profits"],["לָהֶם","unto-them"],["בְּיוֹם","in-some-day"],["מִן","from"],["הַיָּמִים","the-days"],
  ]},
  { num:"ג", words:[
    ["וְעַתָּה","and-now"],["אֲדַבֵּר","I-shall-speak"],["מְעַט","somewhat"],["עַל־אֲשֶׁר","upon-that-which"],["כָּתַבְתִּי","I-have-written"],["כִּי","for"],["אַחֲרֵי","after"],["כָתְבִי","I-had-made"],["בְקִצָּרָה","an-abridgment"],["מִלּוּחוֹת","from-the-plates-of"],["נֶפִי","Nephi"],["עַד־מַלְכוּת","until-the-reign-of"],["בִּנְיָמִין","Benjamin"],["הַמֶּלֶךְ","this-king"],["הַזֶּה","this"],["אֲשֶׁר־דִּבֶּר","which-spoke"],["עָלָיו","upon-him"],["עֲמָלֵקִי","Amaleki"],["חִפַּשְׂתִּי","I-searched"],["בֵּין","among"],["הַכְּתָבִים","the-records"],["אֲשֶׁר","which"],["נִמְסְרוּ","had-been-delivered"],["בְּיָדִי","by-my-hand"],["וָאֶמְצָא","and-I-found"],["אֶת־הַלֻּחוֹת","the-plates"],["הָאֵלֶּה","these"],["אֲשֶׁר","which"],["הֵכִילוּ","contained"],["אֶת־חֶשְׁבּוֹן","this-small-account"],["הַנְּבִיאִים","of-the-prophets"],["הַקָּטָן","small"],["הַזֶּה","this"],["מִיַּעֲקֹב","from-Jacob"],["עַד־מַלְכוּת","until-the-reign-of"],["בִּנְיָמִין","Benjamin"],["הַמֶּלֶךְ","this-king"],["הַזֶּה","this"],["וְגַם","and-also"],["דִּבְרֵי","many-of-the-words-of"],["נֶפִי","Nephi"],["רַבִּים","many"],
  ]},
  { num:"ד", words:[
    ["וַיִּישְׁרוּ","and-the-things-which-are"],["בְעֵינַי","please-me"],["הַדְּבָרִים","the-things"],["אֲשֶׁר","which-are"],["עַל־הַלֻּחוֹת","upon-the-plates"],["הָאֵלֶּה","these"],["בַּעֲבוּר","because-of"],["נְבוּאוֹת","the-prophecies"],["בּוֹא","of-the-coming-of"],["הַמָּשִׁיחַ","the-Messiah"],["וְיָדְעוּ","and-knew"],["אֲבוֹתַי","my-fathers"],["כִּי","that"],["רַבּוֹת","many-of-them"],["מֵהֶן","of-them"],["קָמוּ","have-been-fulfilled"],["הֵן","yea"],["וְגַם־אֲנִי","and-I-also-I"],["יוֹדֵעַ","knowing"],["כִּי","that"],["כָּל־הַדְּבָרִים","all-the-things"],["אֲשֶׁר","which"],["נִנְבְּאוּ","have-been-prophesied"],["עָלֵינוּ","concerning-us"],["עַד־הַיּוֹם","until-this-day"],["הַזֶּה","this"],["קָמוּ","have-been-fulfilled"],["וְכָל־אֲשֶׁר","and-as-many-as-which"],["יַעַבְרוּ","they-shall-pass"],["אֶת־הַיּוֹם","this-day"],["הַזֶּה","this"],["בּוֹא","must-surely"],["יָבוֹאוּ","come-to-pass"],
  ]},
  { num:"ה", words:[
    ["לָכֵן","wherefore"],["בָּחַרְתִּי","I-chose"],["בַדְּבָרִים","these-things"],["הָאֵלֶּה","these"],["לְכַלּוֹת","to-finish"],["אֶת־כְּתָבַי","my-record"],["עֲלֵיהֶם","upon-them"],["וְאֶת־יֶתֶר","and-the-remainder-of"],["כְּתָבַי","my-record"],["אֶקַּח","I-shall-take"],["מִלּוּחוֹת","from-the-plates-of"],["נֶפִי","Nephi"],["וְלֹא","and-I-cannot"],["אוּכַל","am-able"],["לִכְתֹּב","write"],["אֶחָד","one"],["מִמֵּאָה","of-a-hundred"],["מִדִּבְרֵי","of-the-things-of"],["עַמִּי","my-people"],
  ]},
  { num:"ו", words:[
    ["אַךְ","but"],["הִנֵּה","behold"],["אֶקַּח","I-shall-take"],["אֶת־הַלֻּחוֹת","the-plates"],["הָאֵלֶּה","these"],["הַמְכִילִים","which-contain"],["אֶת־הַנְּבוּאוֹת","the-prophesyings"],["וְהַחֶזְיוֹנוֹת","and-the-revelations"],["הָאֵלֶּה","these"],["וְאָשִׂים","and-put-them"],["אוֹתָם","them"],["עִם־יֶתֶר","with-the-remainder-of"],["כְּתָבַי","my-record"],["כִּי","for"],["יְקָרִים","precious"],["הֵם","they"],["לִי","unto-me"],["וְיָדַעְתִּי","and-I-know"],["כִּי","that"],["יִהְיוּ","they-shall-be"],["יְקָרִים","precious"],["לְאַחַי","unto-my-brethren"],
  ]},
  { num:"ז", words:[
    ["וַאֲנִי","and-I"],["עֹשֶׂה","do"],["זֹאת","this"],["לְדָבָר","for-a-purpose"],["חָכָם","wise"],["כִּי־כֵן","for-thus"],["לוֹחֵשׁ","it-whispers-me"],["לִי","unto-me"],["כְּפִי","according-to"],["פְּעֻלּוֹת","the-workings-of"],["רוּחַ","spirit"],["יְהוָה","the-Lord"],["אֲשֶׁר","which-is"],["בִּי","in-me"],["וְעַתָּה","and-now"],["לֹא־יָדַעְתִּי","I-do-not-know"],["אֶת־כָּל־הַדְּבָרִים","all-things"],["אַךְ","but"],["יְהוָה","the-Lord"],["יוֹדֵעַ","knows"],["אֶת־כָּל־הַדְּבָרִים","all-the-things"],["הַבָּאִים","which-are-to-come"],["לָכֵן","wherefore"],["פּוֹעֵל","He-works"],["בִּי","in-me"],["לַעֲשׂוֹת","to-do"],["כִּרְצוֹנוֹ","according-to-His-will"],
  ]},
  { num:"ח", words:[
    ["וּתְפִלָּתִי","and-my-prayer"],["לֵאלֹהִים","to-God"],["הִיא","is"],["בְּעַד","on-behalf-of"],["אַחַי","my-brethren"],["כִּי","that"],["יָשׁוּבוּ","repent"],["פַּעַם","once"],["אַחֶרֶת","other"],["לָדַעַת","to-the-knowledge-of"],["אֶת־אֱלֹהִים","God"],["הֵן","yea"],["גְּאֻלַּת","the-redemption-of"],["הַמָּשִׁיחַ","the-Messiah"],["כִּי","that"],["יִהְיוּ","they-shall-be"],["שׁוּב","again"],["לְעַם","a-people"],["נַחְמָד","delightsome"],
  ]},
  { num:"ט", words:[
    ["וְעַתָּה","and-now"],["הוֹלֵךְ","going"],["מוֹרְמוֹן","I-Mormon"],["לְכַלּוֹת","to-finish-out"],["אֶת־כְּתָבַי","my-record"],["אֲשֶׁר","which"],["אֶקַּח","I-shall-take"],["מִלּוּחוֹת","from-the-plates-of"],["נֶפִי","Nephi"],["וְעֹשֶׂה","and-I-make-it"],["אוֹתָם","them"],["כְּפִי","according-to"],["הַדַּעַת","the-knowledge"],["וְהַתְּבוּנָה","and-the-understanding"],["אֲשֶׁר־נָתַן","which-was-given"],["לִי","unto-me"],["אֱלֹהִים","God"],
  ]},
  { num:"י", words:[
    ["לָכֵן","wherefore"],["וַיְהִי","it-came-to-pass"],["אַחֲרֵי","that-after"],["מָסַר","had-delivered-up"],["עֲמָלֵקִי","Amaleki"],["אֶת־הַלֻּחוֹת","the-plates"],["הָאֵלֶּה","these"],["בְּיַד","into-the-hands-of"],["הַמֶּלֶךְ","king"],["בִּנְיָמִין","Benjamin"],["לְקָחָם","he-took-them"],["וַיָּשֶׂם","and-it-was-placed"],["אוֹתָם","them"],["עִם־הַלֻּחוֹת","with-the-other-plates"],["הָאֲחֵרִים","other"],["אֲשֶׁר","which"],["הֵכִילוּ","contained"],["כְתָבִים","records"],["אֲשֶׁר","which"],["נִמְסְרוּ","had-been-handed-down"],["מִדּוֹר","from-generation"],["לְדוֹר","to-generation"],["עַל־יְדֵי","by-the-hand-of"],["הַמְּלָכִים","the-kings"],["עַד־יְמֵי","until-the-days-of"],["הַמֶּלֶךְ","king"],["בִּנְיָמִין","Benjamin"],
  ]},
  { num:"יא", words:[
    ["וַיִּמָּסְרוּ","and-they-delivered"],["מִיַּד","from"],["הַמֶּלֶךְ","king"],["בִּנְיָמִין","Benjamin"],["מִדּוֹר","from-generation"],["לְדוֹר","to-generation"],["עַד־אֲשֶׁר","until"],["נָפְלוּ","fell"],["בְיָדָי","into-my-hands"],["וּמִתְפַּלֵּל","and-I-pray"],["מוֹרְמוֹן","I-Mormon"],["לֵאלֹהִים","to-God"],["כִּי","that"],["יִשָּׁמְרוּ","they-shall-be-kept"],["מֵהָעֵת","from-this-time"],["הַזֹּאת","is-this"],["וָהָלְאָה","henceforth"],["וְיָדַעְתִּי","and-I-know"],["כִּי","that"],["יִשָּׁמְרוּ","they-shall-be-kept"],["כִּי","for"],["כְּתוּבִים","there-are-written"],["דְבָרִים","things"],["גְּדוֹלִים","great"],["עֲלֵיהֶם","upon-them"],["אֲשֶׁר","out-of-which"],["מֵהֶם","from-them"],["יִשָּׁפְטוּ","they-shall-be-judged"],["עַמִּי","my-people"],["וַאֲחֵיהֶם","and-their-brethren"],["בַּיּוֹם","at-the-day"],["הַגָּדוֹל","the-great"],["וְהָאַחֲרוֹן","and-last"],["כִּדְבַר","according-to-the-word-of"],["אֱלֹהִים","God"],["הַכָּתוּב","which-is-written"],
  ]},
  { num:"יב", words:[
    ["וְעַתָּה","and-now"],["עַל־דְּבַר","upon-the-matter-of"],["הַמֶּלֶךְ","this-king"],["בִּנְיָמִין","Benjamin"],["הַזֶּה","this"],["הָיוּ","were"],["לוֹ","unto-him"],["מְרִיבוֹת","some-contentions"],["בְּקֶרֶב","among"],["עַמּוֹ","his-own-people"],
  ]},
  { num:"יג", words:[
    ["וַיְהִי","and-it-came-to-pass"],["גַם","also"],["כִּי","that"],["יָרְדוּ","came-down"],["צִבְאוֹת","of-Hosts"],["הַלָּמָנִים","the-Lamanites"],["מֵאֶרֶץ","out-of-the-land-of"],["נֶפִי","Nephi"],["לְהִלָּחֵם","to-battle"],["בְּעַמּוֹ","against-his-people"],["אַךְ","but"],["הִנֵּה","behold"],["קִבֵּץ","did-gather-together"],["הַמֶּלֶךְ","king"],["בִּנְיָמִין","Benjamin"],["אֶת־צְבָאוֹתָיו","his-armies"],["וַיַּעֲמֹד","and-he-did-stand"],["נֶגְדָּם","against-them"],["וַיִּלָּחֵם","and-he-did-fight"],["בְּכֹחַ","by-the-power-of"],["זְרוֹעוֹ","his-own-arm"],["בְּחֶרֶב","with-the-sword-of"],["לָבָן","Laban"],
  ]},
  { num:"יד", words:[
    ["וּבִגְבוּרַת","and-by-might-of"],["יְהוָה","the-Lord"],["נִלְחֲמוּ","they-did-contend"],["נֶגֶד","against"],["אוֹיְבֵיהֶם","their-enemies"],["עַד־אֲשֶׁר","until"],["הָרְגוּ","had-slain"],["אַלְפֵי","many-thousands"],["רַבִּים","many"],["מֵהַלָּמָנִים","of-the-Lamanites"],["וַיְהִי","and-it-came-to-pass"],["כִּי","that"],["נִלְחֲמוּ","they-did-contend"],["בַלָּמָנִים","against-the-Lamanites"],["עַד־אֲשֶׁר","until"],["גֵּרְשׁוּ","they-cast-out"],["אוֹתָם","them"],["מִכָּל־אַרְצוֹת","out-of-all-the-lands-of"],["נַחֲלָתָם","their-inheritance"],
  ]},
  { num:"טו", words:[
    ["וַיְהִי","and-it-came-to-pass"],["אַחֲרֵי","after"],["הָיוּ","were"],["מְשִׁיחֵי","Messiah-my"],["שֶׁקֶר","false"],["וְנֶסְתְּמוּ","and-their-mouths-had-been-shut"],["פִיהֶם","their-mouths"],["וַיֻּכּוּ","and-they-were-punished"],["כְּפִי","according-to"],["פִּשְׁעֵיהֶם","their-crimes"],
  ]},
  { num:"טז", words:[
    ["וְאַחֲרֵי","and-after"],["הָיוּ","were"],["נְבִיאֵי","false-prophets"],["שֶׁקֶר","false"],["וּמַטִּיפֵי","and-false-preachers"],["שֶׁקֶר","false"],["וּמוֹרִים","and-teachers"],["בְּקֶרֶב","among"],["הָעָם","the-people"],["וְכָל־אֵלֶּה","and-all-these"],["הֻכּוּ","they-were-smitten"],["כְּפִי","according-to"],["פִּשְׁעֵיהֶם","their-crimes"],["וְאַחֲרֵי","and-after"],["הָיוּ","were"],["מְרִיבוֹת","contentions"],["רַבּוֹת","much"],["וּפְלָגוֹת","and-many-dissensions"],["רַבּוֹת","many"],["לְמַחֲנֵה","away-unto"],["הַלָּמָנִים","the-Lamanites"],["הִנֵּה","behold"],["וַיְהִי","it-came-to-pass"],["כִּי","that"],["הַמֶּלֶךְ","king"],["בִּנְיָמִין","Benjamin"],["בְּעֶזְרַת","with-the-assistance-of"],["הַנְּבִיאִים","the-holy-prophets"],["הַקְּדוֹשִׁים","holy"],["אֲשֶׁר","which"],["הָיוּ","were"],["בְּקֶרֶב","among"],["עַמּוֹ","his-people"],
  ]},
  { num:"יז", words:[
    ["כִּי","for"],["הִנֵּה","behold"],["הָיָה","was"],["הַמֶּלֶךְ","king"],["בִּנְיָמִין","Benjamin"],["אִישׁ","a-man"],["קָדוֹשׁ","a-holy"],["וַיִּמְלֹךְ","and-he-did-reign"],["עַל־עַמּוֹ","upon-his-people"],["בְּצֶדֶק","in-righteousness"],["וַיְהִי","and-there-were"],["אֲנָשִׁים","men"],["קְדוֹשִׁים","holy"],["רַבִּים","many"],["בָּאָרֶץ","in-the-land"],["וַיְדַבְּרוּ","and-they-did-speak"],["אֶת־דְּבַר־אֱלֹהִים","the-word-of-God"],["בְּכֹחַ","with-power"],["וּבְסַמְכוּת","and-with-authority"],["וַיּוֹכִיחוּ","and-they-did-use"],["בְּחָרְפָה","much-sharpness"],["רַבָּה","much"],["מִפְּנֵי","because-of"],["קְשִׁי־עֹרֶף","hardness-of-neck"],["הָעָם","of-the-people"],
  ]},
  { num:"יח", words:[
    ["לָכֵן","wherefore"],["בְּעֶזְרַת","with-the-help-of"],["אֵלֶּה","these"],["הַמֶּלֶךְ","king"],["בִּנְיָמִין","Benjamin"],["בְּעָמְלוֹ","by-laboring"],["בְּכָל־כֹּחַ","with-all-power"],["גּוּפוֹ","his-body"],["וּבְכֹחַ","and-the-faculty-of"],["נַפְשׁוֹ","his-whole-soul"],["כֻּלָּהּ","all-of-it(f)"],["וְגַם","and-also"],["הֵקִימוּ","his-establishing"],["הַנְּבִיאִים","the-holy-prophets"],["שׁוּב","again"],["שָׁלוֹם","peace"],["בָּאָרֶץ","in-the-land"],
  ]},
];
renderVerseSet(wm_ch1Verses, 'wm-ch1-verses');
})();
