// verses/words_of_mormon.js — Words of Mormon verse data
(function() {
var wm_ch1Verses = [
  { num:"א", words:[
    ["וְעַתָּה","and now"],["אֲנִי","I"],["מוֹרְמוֹן","Mormon"],["קָרוֹב","am about"],["לִמְסֹר","to deliver up"],["אֶת־הַכְּתָבִים","the record"],["אֲשֶׁר","which"],["עָשִׂיתִי","I made"],["בְּיַד","into the hands of"],["בְּנִי","my son"],["מוֹרוֹנִי","Moroni"],["הִנֵּה","behold"],["רָאִיתִי","I saw"],["כִּמְעַט","nearly"],["אֶת־כׇּל־הַשְׁמָדַת","all the destruction of"],["עַמִּי","my people"],["הַנֶּפִיִּים","the Nephites"], ["׃",""]]},
  { num: "ב", words: [["וּמֵאוֹת","and hundreds"], ["שָׁנִים","years"], ["רַבּוֹת","many"], ["אַחֲרֵי","after"], ["בּוֹא","the coming of"], ["הַמָּשִׁיחַ","the Messiah"], ["אֲנִי","I"], ["מוֹסֵר","deliver"], ["אֶת־הַכְּתָבִים","the records"], ["הָאֵלֶּה","these"], ["בְּיַד","into the hands of"], ["בְּנִי","my son"], ["וַאֲנִי","and I"], ["חֹשֵׁב","suppose"], ["כִּי","that"], ["יִרְאֶה","he shall see"], ["אֶת־הַשְׁמָדַת","the destruction of"], ["עַמִּי","my people"], ["כֻּלָּהּ","all of it"], ["אַךְ","but"], ["יִתֵּן","may grant"], ["אֱלֹהִים","God"], ["כִּי","that"], ["יִשְׂרֹד","he may survive"], ["מֵהֶם","from them"], ["לְמַעַן","that"], ["יִכְתֹּב","he may write"], ["מְעַט","somewhat"], ["עֲלֵיהֶם","concerning them"], ["וּמְעַט","and somewhat"], ["עַל־דְּבַר","concerning"], ["הַמָּשִׁיחַ","the Messiah"], ["אוּלַי","perhaps"], ["יוֹעִיל","may profit"], ["לָהֶם","unto them"], ["בְּיוֹם","in a day"], ["מִן","from"], ["הַיָּמִים","the days"], ["׃",""]]},
  { num: "ג", words: [["וְעַתָּה","and now"], ["אֲדַבֵּר","I shall speak"], ["מְעַט","somewhat"], ["עַל־אֲשֶׁר","concerning that which"], ["כָּתַבְתִּי","I have written"], ["כִּי","for"], ["אַחֲרֵי","after"], ["כָּתְבִי","I had written"], ["בְקִצָּרָה","an abridgment"], ["מִלּוּחוֹת","from the plates of"], ["נֶפִי","Nephi"], ["עַד־מַלְכוּת","until the reign of"], ["בִּנְיָמִין","Benjamin"], ["הַמֶּלֶךְ","the king"], ["הַזֶּה","this"], ["אֲשֶׁר־דִּבֶּר","which spoke"], ["עָלָיו","of whom"], ["עֲמָלֵקִי","Amaleki"], ["חִפַּשְׂתִּי","I searched"], ["בֵּין","among"], ["הַכְּתָבִים","the records"], ["אֲשֶׁר","which"], ["נִמְסְרוּ","had been delivered"], ["בְּיָדִי","into my hand"], ["וָאֶמְצָא","and I found"], ["אֶת־הַלֻּחוֹת","the plates"], ["הָאֵלֶּה","these"], ["אֲשֶׁר","which"], ["הֵכִילוּ","contained"], ["אֶת־סֵפֶר","the account of"], ["הַנְּבִיאִים","the prophets"], ["הַקָּטָן הַזֶּה","this small"], ["מִיַּעֲקֹב","from Jacob"], ["עַד־מַלְכוּת","until the reign of"], ["בִּנְיָמִין","Benjamin"], ["הַמֶּלֶךְ","the king"], ["הַזֶּה","this"], ["וְגַם","and also"], ["דִּבְרֵי","the words of"], ["נֶפִי","Nephi"], ["רַבִּים","many"], ["׃",""]]},
  { num: "ד", words: [["וַיִּישְׁרוּ","and they were pleasing"], ["בְעֵינַי","in my eyes"], ["הַדְּבָרִים","the things"], ["אֲשֶׁר","which"], ["עַל־הַלֻּחוֹת","upon the plates"], ["הָאֵלֶּה","these"], ["בַּעֲבוּר","because of"], ["נְבוּאוֹת","the prophecies"], ["בּוֹא","the coming of"], ["הַמָּשִׁיחַ","the Messiah"], ["וְיָדְעוּ","and they knew"], ["אֲבוֹתַי","my fathers"], ["כִּי","that"], ["רַבּוֹת","many"], ["מֵהֶן","of them"], ["קָמוּ","have been fulfilled"], ["הֵן","yea"], ["וְגַם־אֲנִי","and also I"], ["יוֹדֵעַ","know"], ["כִּי","that"], ["כׇּל־הַדְּבָרִים","all the things"], ["אֲשֶׁר","which"], ["נִנְבְּאוּ","have been prophesied"], ["עָלֵינוּ","concerning us"], ["עַד־הַיּוֹם","until the day"], ["הַזֶּה","this"], ["קָמוּ","have been fulfilled"], ["וְכׇל־אֲשֶׁר","and as many as"], ["יַעַבְרוּ","they shall pass"], ["אֶת־הַיּוֹם","the day"], ["הַזֶּה","this"], ["בּוֹא","come to pass"], ["יָבוֹאוּ","they shall come to pass"], ["׃",""]]},
  { num:"ה", words:[
    ["לָכֵן","wherefore"],["בָּחַרְתִּי","I chose"],["בַדְּבָרִים","the things"], ["הָאֵלֶּה","these"],["לְכַלּוֹת","to finish"],["אֶת־כְּתָבַי","my record"],["עֲלֵיהֶם","upon them"],["וְאֶת־יֶתֶר","and the remainder of"],["כְּתָבַי","my record"],["אֶקַּח","I shall take"],["מִלּוּחוֹת","from the plates of"],["נֶפִי","Nephi"],["וְלֹא","and not"],["אוּכַל","can I"],["לִכְתֹּב","to write"],["אֶחָד","one"],["מִמֵּאָה","of a hundred"],["מִדִּבְרֵי","of the things of"],["עַמִּי","my people"], ["׃",""]]},
  { num:"ו", words:[
    ["אַךְ","but"],["הִנֵּה","behold"],["אֶקַּח","I shall take"],["אֶת־הַלֻּחוֹת","the plates"], ["הָאֵלֶּה","these"],["הַמְכִילִים","which contain"],["אֶת־הַנְּבוּאוֹת","the prophecies"],["וְהַחֶזְיוֹנוֹת","and the revelations"], ["הָאֵלֶּה","these"],["וְאָשִׂים","and put"],["אוֹתָם","them"],["עִם־יֶתֶר","with the remainder of"],["כְּתָבַי","my record"],["כִּי","for"],["יְקָרִים","precious"],["הֵם","are they"],["לִי","unto me"],["וְיָדַעְתִּי","and I know"],["כִּי","that"],["יִהְיוּ","they shall be"],["יְקָרִים","precious"],["לְאַחַי","unto my brethren"], ["׃",""]]},
  { num:"ז", words:[
    ["וַאֲנִי","and I"],["עֹשֶׂה","do"],["זֹאת","this"],["לְדָבָר","for a purpose"],["חָכָם","wise"],["כִּי־כֵן","for thus"],["לוֹחֵשׁ","it whispers"],["לִי","unto me"],["כְּפִי","according to"],["פְּעֻלּוֹת","the workings of"],["רוּחַ","the Spirit of"],["יְהוָה","the Lord"],["אֲשֶׁר","which"],["בִּי","in me"],["וְעַתָּה","and now"],["לֹא־יָדַעְתִּי","I do not know"],["אֶת־כׇּל־הַדְּבָרִים","all things"],["אַךְ","but"],["יְהוָה","the Lord"],["יוֹדֵעַ","knows"],["אֶת־כׇּל־הַדְּבָרִים","all the things"],["הַבָּאִים","which are to come"],["לָכֵן","wherefore"],["פּוֹעֵל","He works"],["בִּי","in me"],["לַעֲשׂוֹת","to do"],["כִּרְצוֹנוֹ","according to His will"], ["׃",""]]},
  { num: "ח", words: [["וּתְפִלָּתִי","and my prayer"], ["לֵאלֹהִים","to God"], ["הִיא","is"], ["בְּעַד","on behalf of"], ["אַחַי","my brethren"], ["כִּי","that"], ["יָשׁוּבוּ","they shall return"], ["פַּעַם","once"], ["אַחֶרֶת","more"], ["לָדַעַת","to the knowledge of"], ["אֶת־אֱלֹהִים","God"], ["אַף","yea"], ["גְּאֻלַּת","the redemption of"], ["הַמָּשִׁיחַ","the Messiah"], ["כִּי","that"], ["יִהְיוּ","they shall be"], ["עוֹד","again"], ["לְעַם","a people"], ["נַחְמָד","delightsome"], ["׃",""]]},
  { num:"ט", words:[
    ["וְעַתָּה","and now"],["הוֹלֵךְ","going"],["אֲנִי","I"],["מוֹרְמוֹן","Mormon"],["לְכַלּוֹת","to finish"],["אֶת־כְּתָבַי","my record"],["אֲשֶׁר","which"],["אֶקַּח","I shall take"],["מִלּוּחוֹת","from the plates of"],["נֶפִי","Nephi"],["וְעֹשֶׂה","and I make"],["אוֹתָם","them"],["כְּפִי","according to"],["הַדַּעַת","the knowledge"],["וְהַתְּבוּנָה","and the understanding"],["אֲשֶׁר־נָתַן","which gave"],["לִי","unto me"],["אֱלֹהִים","God"], ["׃",""]]},
  { num: "י", words: [["לָכֵן","wherefore"], ["אַחֲרֵי","that after"], ["מָסַר","had delivered up"], ["עֲמָלֵקִי","Amaleki"], ["אֶת־הַלֻּחוֹת","the plates"], ["הָאֵלֶּה","these"], ["בְּיַד","into the hands of"], ["הַמֶּלֶךְ","the king"], ["בִּנְיָמִין","Benjamin"], ["לְקָחָם","he took them"], ["וַיָּשֶׂם","and he placed"], ["אוֹתָם","them"], ["עִם־הַלֻּחוֹת","with the plates"], ["הָאֲחֵרִים","other"], ["אֲשֶׁר","which"], ["הֵכִילוּ","contained"], ["כְּתָבִים","records"], ["אֲשֶׁר","which"], ["נִמְסְרוּ","had been handed down"], ["מִדּוֹר","from generation"], ["לְדוֹר","to generation"], ["עַל־יְדֵי","by the hand of"], ["הַמְּלָכִים","the kings"], ["עַד־יְמֵי","until the days of"], ["הַמֶּלֶךְ","the king"], ["בִּנְיָמִין","Benjamin"], ["׃",""]]},
  { num:"יא", words:[
    ["וַיִּמָּסְרוּ","and they were handed down"],["מִיַּד","from the hand of"],["הַמֶּלֶךְ","the king"],["בִּנְיָמִין","Benjamin"],["מִדּוֹר","from generation"],["לְדוֹר","to generation"],["עַד־אֲשֶׁר","until"],["נָפְלוּ","they fell"],["בְיָדָי","into my hands"],["וּמִתְפַּלֵּל","and pray"],["אֲנִי","I"],["מוֹרְמוֹן","Mormon"],["לֵאלֹהִים","to God"],["כִּי","that"],["יִשָּׁמְרוּ","they shall be kept"],["מֵהָעֵת","from the time"], ["הַזֹּאת","this"],["וָהָלְאָה","henceforth"],["וְיָדַעְתִּי","and I know"],["כִּי","that"],["יִשָּׁמְרוּ","they shall be kept"],["כִּי","for"],["כְּתוּבִים","there are written"],["דְבָרִים","things"],["גְּדוֹלִים","great"],["עֲלֵיהֶם","upon them"],["אֲשֶׁר","which"],["מֵהֶם","from them"],["יִשָּׁפְטוּ","they shall be judged"],["עַמִּי","my people"],["וַאֲחֵיהֶם","and their brethren"],["בַּיּוֹם","at the day"],["הַגָּדוֹל","the great"],["וְהָאַחֲרוֹן","and last"],["כִּדְבַר","according to the word of"],["אֱלֹהִים","God"],["הַכָּתוּב","which is written"], ["׃",""]]},
  { num: "יב", words: [["וְעַתָּה","and now"], ["עַל־דְּבַר","concerning"], ["הַמֶּלֶךְ","the king"], ["בִּנְיָמִין","Benjamin"], ["הַזֶּה","this"], ["הָיוּ","were"], ["לוֹ","unto him"], ["מְרִיבוֹת","some contentions"], ["בְּקֶרֶב","among"], ["עַמּוֹ","his people"], ["׃",""]]},
  { num:"יג", words:[
    ["וַיְהִי","and it happened"],["גַם","also"],["כִּי","that"],["יָרְדוּ","came down"],["צִבְאוֹת","armies of"],["הַלָּמָנִים","the Lamanites"],["מֵאֶרֶץ","out of the land of"],["נֶפִי","Nephi"],["לְהִלָּחֵם","to battle"],["בְּעַמּוֹ","against his people"],["אַךְ","but"],["הִנֵּה","behold"],["קִבֵּץ","did gather together"],["הַמֶּלֶךְ","the king"],["בִּנְיָמִין","Benjamin"],["אֶת־צְבָאוֹתָיו","his armies"],["וַיַּעֲמֹד","and he did stand"],["נֶגְדָּם","against them"],["וַיִּלָּחֵם","and he did fight"],["בְּכֹחַ","by the power of"],["זְרוֹעוֹ","his arm"],["בְּחֶרֶב","with the sword of"],["לָבָן","Laban"], ["׃",""]]},
  { num:"יד", words:[["וּבִגְבוּרַת","and by the might of"], ["יְהוָה","the Lord"], ["נִלְחֲמוּ","they did contend"], ["נֶגֶד","against"], ["אוֹיְבֵיהֶם","their enemies"], ["עַד־אֲשֶׁר","until"], ["הָרְגוּ","they had slain"], ["אֲלָפִים","thousands"], ["רַבִּים","many"], ["מֵהַלָּמָנִים","of the Lamanites"], ["וַיְהִי","and it happened"], ["כִּי","that"], ["נִלְחֲמוּ","they did contend"], ["בַלָּמָנִים","against the Lamanites"], ["עַד־אֲשֶׁר","until"], ["גֵּרְשׁוּ","they cast out"], ["אוֹתָם","them"], ["מִכׇּל־אַרְצוֹת","out of all the lands of"], ["נַחֲלָתָם","their inheritance"], ["׃",""]]},
  { num:"טו", words:[
    ["וַיְהִי","and it happened"],["אַחֲרֵי","after"],["הָיוּ","were"],["מְשִׁיחֵי","christs of"],["שֶׁקֶר","falsehood"],["וְנֶסְתְּמוּ","and were shut"],["פִיהֶם","their mouths"],["וַיֻּכּוּ","and they were smitten"],["כְּפִי","according to"],["פִּשְׁעֵיהֶם","their crimes"], ["׃",""]]},
  { num: "טז", words: [["וְאַחֲרֵי","and after"], ["הָיוּ","were"], ["נְבִיאֵי","prophets of"], ["שֶׁקֶר","falsehood"], ["וּמַטִּיפֵי","and preachers of"], ["שֶׁקֶר","falsehood"], ["וּמוֹרִים","and teachers"], ["בְּקֶרֶב","among"], ["הָעָם","the people"], ["וְכׇל־אֵלֶּה","and all these"], ["הֻכּוּ","they were smitten"], ["כְּפִי","according to"], ["פִּשְׁעֵיהֶם","their crimes"], ["וְאַחֲרֵי","and after"], ["הָיוּ","were"], ["מְרִיבוֹת","contentions"], ["רַבּוֹת","many"], ["וּפְלָגוֹת","and dissensions"], ["רַבּוֹת","many"], ["לְמַחֲנֵה","unto the camp of"], ["הַלָּמָנִים","the Lamanites"], ["הִנֵּה","behold"], ["הַמֶּלֶךְ","the king"], ["בִּנְיָמִין","Benjamin"], ["בְּעֶזְרַת","with the assistance of"], ["הַנְּבִיאִים","the prophets"], ["הַקְּדוֹשִׁים","holy"], ["אֲשֶׁר","which"], ["הָיוּ","were"], ["בְּקֶרֶב","among"], ["עַמּוֹ","his people"], ["׃",""]]},
  { num: "יז", words: [["כִּי","for"], ["הִנֵּה","behold"], ["הָיָה","was"], ["הַמֶּלֶךְ","the king"], ["בִּנְיָמִין","Benjamin"], ["אִישׁ","a man"], ["קָדוֹשׁ","holy"], ["וַיִּמְלֹךְ","and he did reign"], ["עַל־עַמּוֹ","over his people"], ["בְּצֶדֶק","in righteousness"], ["וַיִּהְיוּ","and there were"], ["אֲנָשִׁים","men"], ["קְדוֹשִׁים","holy"], ["רַבִּים","many"], ["בָּאָרֶץ","in the land"], ["וַיְדַבְּרוּ","and they did speak"], ["אֶת־דְּבַר־אֱלֹהִים","the word of God"], ["בְּכֹחַ","with power"], ["וּבְסַמְכוּת","and with authority"], ["וַיּוֹכִיחוּ","and they did rebuke"], ["בְּקָשׁוֹת","sharpness"], ["רַבּוֹת","much"], ["מִפְּנֵי","because of"], ["קְשִׁי־עֹרֶף","the stiffneckedness of"], ["הָעָם","the people"], ["׃",""]]},
  { num:"יח", words:[["לָכֵן","wherefore"], ["בְּעֶזְרַת","with the help of"], ["אֵלֶּה","these"], ["הַמֶּלֶךְ","the king"], ["בִּנְיָמִין","Benjamin"], ["בְּעׇמְלוֹ","by his laboring"], ["בְּכׇל־כֹּחַ","with all the might of"], ["גְּוִיָּתוֹ","his body"], ["וּבְכֹחַ","and in the power of"], ["נַפְשׁוֹ","his soul"], ["כֻּלָּהּ","all of it"], ["וְגַם","and also"], ["הֵקִימוּ","they established"], ["הַנְּבִיאִים","the prophets"], ["עוֹד","again"], ["שָׁלוֹם","peace"], ["בָּאָרֶץ","in the land"], ["׃",""]]},
];
renderVerseSet(wm_ch1Verses, 'wm-ch1-verses');
})();
