// nt_verses/1th.js — 1 Thessalonians verse data
(function() {
var _1th_ch1Verses = [
  { num:"א", words:[["פּוֹלוֹס","Paul"],["וְסִלְוָנוֹס","and-Silvanus"],["וְטִימוֹתִיּוֹס","and-Timothy"],["אֶל־קְהִלַּת","to-church-of"],["הַתֶּסָּלוֹנִיקִיּים","the-Thessalonians"],["בֵּאלֹהִים","in-God"],["הָאָב","the-Father"],["וּבָאָדוֹן","and-in-the-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["חֶסֶד","grace"],["לָכֶם","to-you"],["וְשָׁלוֹם","and-peace"],["מֵאֵת","from"],["אֱלֹהִים","God"],["אָבִינוּ","our-father"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ב", words:[["נוֹדֶה","we-give-thanks"],["לֵאלֹהִים","to-God"],["עַל־כֻּלְּכֶם","upon-all-you"],["בְּכָל־עֵת","with-all-time"],["בְּהַזְכִּירֵנוּ","in-our-remembering"],["אֶתְכֶם","you"],["בִּתְפִלּוֹתֵינוּ","in-our-prayers"],["׃",""]] },
  { num:"ג", words:[["בְּזָכְרֵנוּ","when-remembered-we"],["תָמִיד","continually"],["לִפְנֵי","before"],["הָאֱלֹהִים","the-God"],["אָבִינוּ","our-father"],["אֶת־פֹּעַל","[ACC]-work-of"],["אֱמוּנַתְכֶם","your-faith"],["וִיגִיעַת","and-labor-of"],["אַהֲבַתְכֶם","your-love"],["וְסַבְלָנוּת","and-patience"],["תִּקְוַתְכֶם","your-hope"],["לַאֲדֹנֵינוּ","to-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["יָדַעְנוּ","we-know"],["אַחַי","my-brothers"],["חֲבִיבֵי","my-beloved"],["הָאֱלֹהִים","the-God"],["אֵת","[ACC]"],["אֲשֶׁר","that"],["נִבְחַרְתֶּם","you-were-chosen"],["׃",""]] },
  { num:"ה", words:[["בַּאֲשֶׁר","because"],["בְּשׂוֹרָתֵנוּ","tidings-of-us"],["לֹא","not"],["בָאָה","entered-into"],["לָכֶם","to-you"],["בְּדִבּוּר","in-speaking"],["לְבָד","alone"],["כִּי־גַם","because-also"],["בִּגְבוּרָה","with-power"],["וּבְרוּחַ","and-in-the-Spirit"],["הַקֹּדֶשׁ","the-Holy"],["וּבְדַעַת","and-with-knowledge"],["נְכוֹנָה","established/firm(f)"],["מְאֹד","exceedingly"],["כַּאֲשֶׁר","when/as"],["יְדַעְתֶּם","you-know"],["אֵת","[ACC]"],["אֲשֶׁר־הָיִינוּ","how-we-were"],["בְּתוֹכֲכֶם","among-you"],["לְמַעַנְכֶם","for-your-sakes"],["׃",""]] },
  { num:"ו", words:[["וִהְיִיתֶם","and-you-became"],["לְהֹלְכֵי","to-those who walk of"],["בְעִקְּבוֹתֵינוּ","in-the footprints of-our"],["וּבְעִקְּבוֹת","and-in-the footprints of"],["אֲדֹנֵינוּ","our-Lord"],["כִּי","because"],["קִבַּלְתֶּם","received"],["אֶת־הַדָּבָר","[ACC]-the-word"],["בְּתוֹךְ","among"],["עֳנִי","affliction"],["רָב","much"],["בְּחֶדְוַת","in-the joy of"],["רוּחַ","the-spirit-of"],["הַקֹּדֶשׁ","the-Holy"],["׃",""]] },
  { num:"ז", words:[["עַד־הֱיוֹתְכֶם","until-your-being"],["לְמוֹפֵת","an-example"],["לְכָל־הַמַּאֲמִינִים","to-all-the-believers"],["אֲשֶׁר","who-are"],["בְּמַקְדּוֹנְיָא","in-Macedonia"],["וּבַאֲכַיָּא","and-in-Achaia"],["׃",""]] },
  { num:"ח", words:[["כִּי","because"],["מֵאִתְּכֶם","of-you"],["נִשְׁמַע","was-heard"],["קוֹל","the-voice-of"],["דְּבַר","the-word-of"],["יְהוָֹה","the-Lord"],["לֹא","not"],["בְּמַקְדּוֹנְיָא","in-Macedonia"],["וַאֲכַיָּא","and-Achaia"],["לְבַד","alone"],["כִּי","because"],["בְּכָל־מָקוֹם","in-every-place"],["יָצְאָה","went-forth"],["אֱמוּנַתְכֶם","your-faith"],["לֵאלֹהִים","to-God"],["וְאֵין־לָנוּ","and-we-have-no"],["צֹרֶךְ","need"],["לְדַבֵּר","to-speak"],["עוֹד","any-more"],["דָּבָר","a-word"],["׃",""]] },
  { num:"ט", words:[["כִּי־פִיהֶם","because-their-mouths"],["הַמַּגִּיד","the-who-had told"],["מֶה־הָיָה","what-was"],["מְבוֹאֵנוּ","from-our-coming"],["אֲלֵיכֶם","unto-you"],["וְאֵיךְ","and-how"],["עֲזַבְתֶּם","you-left"],["הָאֱלִילִים","the-idols"],["וְשַׁבְתֶּם","and-you-turned"],["לֵאלֹהִים","to-God"],["לַעֲבֹד","to-labor"],["אֵל","God"],["חַי","living"],["וַאֲמִתִּי","and-true"],["׃",""]] },
  { num:"י", words:[["וּלְחַכּוֹת","and-to-wait-for"],["לִבְנוֹ","for-his-son"],["מִן־הַשָּׁמַיִם","from-the-heavens"],["אֲשֶׁר","whom"],["הֱעִירוֹ","he-raised"],["מִן־הַמֵּתִים","from-the-dead"],["לְיֵשׁוּעַ","to-Jesus"],["הַמַּצִּילֵנוּ","the-who-delivers-us"],["מִן־הֶחָרוֹן","from-the-wrath"],["הַבָּא","that-comes"],["׃",""]] },
];
renderVerseSet(_1th_ch1Verses, '1th-ch1-verses');

var _1th_ch2Verses = [
  { num:"א", words:[["כִּי","because"],["אַתֶּם","you-are"],["אַחַי","my-brothers"],["יְדַעְתֶּם","you-know"],["אֶת־מְבוֹאֵנוּ","[ACC]-our-coming"],["אֲלֵיכֶם","unto-you"],["כִּי","because"],["לֹא־הָיָה","not-was"],["לָרִיק","in-vain"],["׃",""]] },
  { num:"ב", words:[["וְאַחֲרֵי","and-after"],["אֲשֶׁר","that"],["עֻנֵּינוּ","we-were-afflicted"],["וּלְחֶרְפָּה","and-into-a reproach"],["הָיִינוּ","we-were"],["בְּפִילִפִּי","in-Philippi"],["כַּאֲשֶׁר","when/as"],["יְדַעְתֶּם","you-know"],["הִתְחַזַּקְנוּ","we-were-bold"],["בֵאלֹהֵינוּ","in-our-God"],["לְהַגִּיד","to-declare"],["גַּם־לָכֶם","also-to-you"],["אֶת־הַבְּשׂוֹרָה","[ACC]-the-good-tidings"],["בְּנַפְתּוּלִים","in-great-conflict"],["רַבִּים","many"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["תוֹכַחְתֵּנוּ","our-exhortation"],["אֵינֶנָּה","is-not"],["מִתּוֹךְ","from-midst-of"],["טָעוּת","error"],["וְלֹא","and-not"],["מִתּוֹךְ","from-midst-of"],["טֻמְאָה","filthiness"],["וְלֹא","and-not"],["בִּרְמִיָּה","in-deceit"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["כַּאֲשֶׁר","when/as"],["נִמְצֵאנוּ","we-were-approved"],["נֶאֱמָנִים","faithful"],["לֵאלֹהִים","to-God"],["לְהַפְקִיד","to-entrust"],["בְּיָדֵנוּ","in-our-hand"],["הַבְּשׂוֹרָה","the-gospel"],["כֵּן","thus"],["נְדַבֵּר","speak"],["וְלֹא","and-not"],["לִהְיוֹת","to-be"],["רְצוּיִם","desired"],["לִבְנֵי","unto-the-children-of"],["אָדָם","man"],["כִּי","because"],["אִם־לֵאלֹהִים","if-to-God"],["הַבֹּחֵן","the-who-tests"],["לִבּוֹתֵנוּ","the-hearts-of-us"],["׃",""]] },
  { num:"ה", words:[["כִּי","because"],["מֵעוֹלָם","never"],["לֹא","not"],["דִבַּרְנוּ","we have spoken"],["בִּשְׂפַת","in-the-language-of"],["חֲלָקוֹת","flattering-things"],["כַּאֲשֶׁר","when/as"],["יְדַעְתֶּם","you-know"],["וְלֹא","and-not"],["לְמַעַן","in-order-that"],["בְּצֹעַ","for-greed"],["בֶּצַע","gain/profit"],["בַּסָּתֶר","in-the-secret"],["עֵד","witness"],["הָאֱלֹהִים","the-God"],["׃",""]] },
  { num:"ו", words:[["גַּם","also"],["לֹא־בִקַּשְׁנוּ","not-we-sought"],["מִן־הָאָדָם","from-the-man"],["כָּבוֹד","glory"],["לֹא","not"],["מִכֶּם","from-you"],["וְלֹא","and-not"],["מֵאֲחֵרִים","from-others"],["אַף","yea"],["כִּי","because"],["יָכֹלְנוּ","we-were-able"],["לִהְיוֹת","to-be"],["בִּיקָר","in-honor"],["כִּשְׁלִיחֵי","as-apostles-of"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ז", words:[["אֶלָּא","but-rather"],["הָלַכְנוּ","we-went"],["לְאַט","softly"],["בְּתוֹכֲכֶם","among-you"],["כְּאֹמֶנֶת","as-a nurse"],["מְפַנֶּקֶת","cherishing"],["אֶת־בָּנֶיהָ","[ACC]-sons-her"],["׃",""]] },
  { num:"ח", words:[["וּבְחַבְּבֵנוּ","and-in-our-loving"],["אֶתְכֶם","you"],["כָּכָה","thus"],["חָפַצְנוּ","we-desired"],["לָתֵת","to-give"],["לָכֶם","to-you"],["לֹא","not"],["אֶת־בְּשׂוֹרַת","[ACC]-good-tidings-of"],["הָאֱלֹהִים","the-God"],["לְבַד","alone"],["אֶלָּא","but-rather"],["אַף","yea"],["נַפְשֹׁתֵינוּ","selves-our"],["יַעַן","because"],["כִּי־הֱיִיתֶם","because-you-were"],["חֲבִיבִים","beloved-ones"],["עָלֵינוּ","over-us"],["׃",""]] },
  { num:"ט", words:[["הֲלֹא","do-not"],["תִזְכְּרוּ","you-should-remember"],["אַחַי","my-brothers"],["אֶת־עֲמָלֵנוּ","[ACC]-our-labor"],["וְאֶת־תְּלָאָתֵנוּ","and-[ACC]-our-hardship"],["אֲשֶׁר","which"],["יָגַעְנוּ","we-toiled"],["לַיְלָה","night"],["וְיוֹמָם","and-by day"],["לְבִלְתִּי","to-not"],["הֱיוֹת","have"],["לְמַשָׂא","a-burden"],["לְאִישׁ","for-a-man"],["מִכֶּם","from-you"],["בְּבַשְׂרֵנוּ","in-our-flesh"],["בְקִרְבְּכֶם","among-you"],["אֶת־בְּשׂוֹרַת","[ACC]-good-tidings-of"],["הָאֱלֹהִים","the-God"],["׃",""]] },
  { num:"י", words:[["עֵדִים","many-witnesses"],["אַתֶּם","you-are"],["וְעֵד","and-witness"],["הָאֱלֹהִים","the-God"],["אִם־לֹא","if-not"],["בִקְדֻשָּׁה","in-holiness"],["וּבְצֶדֶק","and-with-righteousness"],["וּבְתָמִים","and-in-integrity"],["הָיִינוּ","we-were"],["עִמָּכֶם","with-you"],["הַמַּאֲמִינִים","the-believers"],["׃",""]] },
  { num:"יא", words:[["וְאַתֶּם","and-you"],["יְדַעְתֶּם","you-know"],["כִּי־כְאָב","because-like-a father"],["אֶת־בָּנָיו","[ACC] his-sons"],["הִזְהַרְנוּ","we-exhorted"],["אֶת־כָּל־אֶחָד","[ACC]-all-one"],["מִכֶּם","from-you"],["וְדִבַּרְנוּ","and-we have spoken"],["עַל","upon"],["לִבּוֹ","his-heart"],["׃",""]] },
  { num:"יב", words:[["וַנָּעַד","and-we-charged"],["בָּכֶם","in-you"],["לָלֶכֶת","to-go"],["כַּטּוֹב","as-the-is-fitting"],["לִפְנֵי","before"],["הָאֱלֹהִים","the-God"],["הַקּוֹרֵא","the-calling"],["אֶתְכֶם","you"],["לְמַלְכוּתוֹ","to-his-kingdom"],["וְלִכְבוֹדוֹ","and-to-his-glory"],["׃",""]] },
  { num:"יג", words:[["בַּעֲבוּר","because-of"],["זֹאת","this"],["אֲנַחְנוּ","we"],["לֹא","not"],["נֶחְדַּל","we-cease"],["לְהוֹדֹת","to-give-thanks"],["לֵאלֹהִים","to-God"],["כִּי","because"],["אַתֶּם","you-are"],["קִבַּלְתֶּם","received"],["מֵאִתָּנוּ","from-among-us"],["דְּבַר","the-word-of"],["שְׁמוּעַת","report-of"],["הָאֱלֹהִים","the-God"],["וְלֹא־קִבַּלְתֶּם","and-not-received"],["אוֹתוֹ","him"],["כִּדְבַר","according-to-the-word-of"],["בְּנֵי־אָדָם","the-children-of-men"],["כִּי","because"],["אִם־כְּמוֹ־שֶׁהוּא","if-as/like-that-He-is"],["בֶאֱמֶת","in-truth"],["כִּדְבַר","according-to-the-word-of"],["הָאֱלֹהִים","the-God"],["אֲשֶׁר","which"],["גַּם־פֹּעֵל","also-worketh"],["בָּכֶם","in-you"],["הַמַּאֲמִינִים","the-believers"],["׃",""]] },
  { num:"יד", words:[["כִּי־אַתֶּם","because-you-are"],["אַחַי","my-brothers"],["הֲלַכְתֶּם","you-went/are-gone"],["בְּעִקְּבֵי","in-the heels of"],["קְהִלּוֹת","churches"],["הָאֱלֹהִים","the-God"],["אֲשֶׁר־בְּאֶרֶץ","that-are-in-land-of"],["יְהוּדָה","Judah/Judas"],["בַּמָּשִׁיחַ","in-the-Messiah"],["יֵשׁוּעַ","Jesus"],["כִּי","because"],["גַּם־אַתֶּם","also-you"],["עֻנֵּיתֶם","you-were-afflicted"],["עַל־יְדֵי","by-means-of"],["בְנֵי־עַמְּכֶם","sons-of-your-people"],["כַּאֲשֶׁר","when/as"],["עֻנּוּ","were-afflicted"],["גַם־הֵם","they-also"],["עַל־יְדֵי","by-means-of"],["הַיְּהוּדִים","the-Jews"],["׃",""]] },
  { num:"טו", words:[["אֲשֶׁר","who"],["אַף־הָרְגוּ","even-slew"],["אֶת־הָאָדוֹן","[ACC]-the-Lord"],["יֵשׁוּעַ","Jesus"],["וְאֶת־נְבִיאֵיהֶם","and-their-prophets"],["וְאוֹתָנוּ","and-us"],["רָדָפוּ","persecuted"],["וְאֵינָם","and-they-are-not"],["טוֹבִים","good"],["בְּעֵינֵי","in-the-eyes-of"],["אֱלֹהִים","God"],["וּמִתְקוֹמֲמִים","and-those who rise up"],["לְכָל־אָדָם","unto-all-men"],["׃",""]] },
  { num:"טז", words:[["הָעֹצְרִים","the-who-hinder"],["אֹתָנוּ","us"],["מִדַּבֵּר","from-speaking"],["אֶל־הַגּוֹיִם","unto-the-nations"],["שֶׁיִּוָּשֵׁעוּ","that-shall-be-saved"],["לְמַעַן","in-order-that"],["אֲשֶׁר־יְמַלְאוּ","that-they-fill-up"],["אֶת־חַטֹּאתֵיהֶם","[ACC]-their-sins"],["בְּכָל־עֵת","with-all-time"],["וַתַּשִׂיגֵם","and-has-overtaken-them"],["הַחֵמָה","the-wrath"],["עַד־כַּלֵּה","until-make an end"],["׃",""]] },
  { num:"יז", words:[["וַאֲנַחְנוּ","and-we-are"],["אַחַי","my-brothers"],["אַחֲרֵי","after"],["אֲשֶׁר־שָׁכֹלְנוּ","that-we-were-bereaved-of"],["אֶתְכֶם","you"],["לִזְמַן","for-space-of"],["מְעַט","somewhat"],["לְפָנִים","formerly"],["וְלֹא","and-not"],["לַלֵּב","to-the-heart"],["חַשְׁנוּ","we-endeavored"],["עַד־מְאֹד","exceedingly"],["לִרְאוֹת","to-see"],["פְּנֵיכֶם","face-of-you"],["בִּתְשׁוּקָה","with-longing"],["רַבָּה","much"],["׃",""]] },
  { num:"יח", words:[["וְעַל־כֵּן","and-therefore"],["חָפַצְנוּ","we-desired"],["לָבוֹא","to-come"],["אֲלֵיכֶם","unto-you"],["אֲנִי","I"],["פוֹלוֹס","Paul"],["פַּעַם","once"],["וּשְׁתָּיִם","and-two times"],["וְהַשָׂטָן","and-the-adversary"],["עֲצָרָנוּ","hindered-us"],["׃",""]] },
  { num:"יט", words:[["כִּי","because"],["מִי","who"],["תִקְוָתֵנוּ","hope-our"],["וּמִי","and-who"],["שִׂמְחָתֵנוּ","joy-of-us"],["וַעֲטֶרֶת","and-a crown of"],["תִּפְאַרְתֵּנוּ","our-glory"],["הֲלֹא","do-not"],["גַם־אַתֶּם","also-you"],["לִפְנֵי","before"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["בְּבוֹאוֹ","when-came-he"],["׃",""]] },
  { num:"כ", words:[["אָמְנָם","truly"],["אַתֶּם","you-are"],["כְּבוֹדֵנוּ","the-glory-of-us"],["וְשִׂמְחָתֵנוּ","and-joy-of-us"],["׃",""]] },
];
renderVerseSet(_1th_ch2Verses, '1th-ch2-verses');

var _1th_ch3Verses = [
  { num:"א", words:[["וְעַל־כֵּן","and-therefore"],["לֹא","not"],["יָכֹלְנוּ","we-were-able"],["עוֹד","any-more"],["לְהִתְאַפֵּק","to-restrain himself"],["וַנִּוָּעַץ","and-we-resolved"],["לְהִוָּתֵר","to-remain"],["לְבַדֵּנוּ","alone"],["בְּאַתּוּנָה","in-Athens"],["׃",""]] },
  { num:"ב", words:[["וַנִּשְׁלַח","and-was-sent"],["אֶת־טִימוֹתִיּוֹס","[ACC]-Timothy"],["אָחִינוּ","our-brother"],["וּמְשָׁרֵת","and-minister-of"],["הָאֱלֹהִים","the-God"],["וְעֹזְרֵנוּ","and-our-helper"],["בִּבְשׂוֹרַת","in-good-news-of"],["הַמָּשִׁיחַ","the-Messiah"],["לְחַזֵּק","to-strengthen"],["אֶתְכֶם","you"],["וּלְהַזְהִיר","and-to-exhort"],["עַל־דְּבַר","upon-the-word-of"],["אֱמוּנַתְכֶם","your-faith"],["׃",""]] },
  { num:"ג", words:[["לְמַעַן","in-order-that"],["אֲשֶׁר","that"],["לֹא־יִמּוֹט","not-be-shaken"],["אִישׁ","a-man"],["בַּמְּצוּקוֹת","in-the-distress(pl)"],["הָאֵלֶּה","these"],["כִּי־יְדַעְתֶּם","because-you-know"],["אַף־אַתֶּם","yea-you-are"],["כִּי","because"],["לָזֹאת","to-this"],["יֻעָדְנוּ","we-are-destined"],["׃",""]] },
  { num:"ד", words:[["הֲלֹא","do-not"],["כְּבָר","already"],["אָמַרְנוּ","we-told"],["אֲלֵיכֶם","unto-you"],["בִּהְיוֹתֵנוּ","when-were-we"],["אֶצְלְכֶם","with-you"],["כִּי־עֲתִידִים","because-are-about"],["אֲנַחְנוּ","we"],["לְהִלָּחֵץ","to-be-afflicted"],["כַּאֲשֶׁר","when/as"],["גַּם־הָיָה","also-was"],["וְכַאֲשֶׁר","and-as"],["יְדַעְתֶּם","you-know"],["׃",""]] },
  { num:"ה", words:[["וּבַעֲבוּר","and-because"],["כֵּן","thus"],["לֹא־יָכֹלְתִּי","not-I-could"],["עוֹד","any-more"],["לְהִתְאַפֵּק","to-restrain himself"],["וָאֶשְׁלַח","and-I-sent"],["לָדַעַת","to-know"],["אֱמוּנַתְכֶם","your-faith"],["כִּי","because"],["אָמַרְתִּי","I-said"],["פֶּן־נִסָּה","lest-he put to the test"],["אֶתְכֶם","you"],["הַמְנַסֶּה","the-tempter"],["וְהָיְתָה","and-it-be"],["לָרִיק","in-vain"],["יְגִיעָתֵנוּ","hard work-our"],["׃",""]] },
  { num:"ו", words:[["וְעַתָּה","and-now"],["כְּשׁוּב","as-returns"],["אֵלֵינוּ","unto-us"],["טִימוֹתִיּוֹס","Timothy"],["מֵאִתְּכֶם","of-you"],["וַיְבַשֵׂר","and-he-preached"],["אֹתָנוּ","us"],["אֶת־בְּשׂוֹרַת","[ACC]-good-tidings-of"],["אֱמוּנַתְכֶם","your-faith"],["וְאַהֲבַתְכֶם","and-your-love"],["וְאֵת","and-[ACC]"],["אֲשֶׁר","which"],["אַתֶּם","you-are"],["זֹכְרִים","remembering"],["אֹתָנוּ","us"],["לְטוֹבָה","for-good"],["בְּכָל־עֵת","with-all-time"],["וְנִכְסָפִים","and-longing"],["לִרְאוֹת","to-see"],["אֹתָנוּ","us"],["כַּאֲשֶׁר","when/as"],["נִכְסֹף","we-long"],["גַּם־אֲנַחְנוּ","also-we"],["לִרְאוֹתְכֶם","to-see-you"],["׃",""]] },
  { num:"ז", words:[["אָז","then"],["נֻחַמְנוּ","we-were-comforted"],["עֲלֵיכֶם","over-you"],["אַחַי","my-brothers"],["בְּכָל־צָרָתֵנוּ","in-all-our-distress"],["וְלַחֲצֵנוּ","and-oppression-our"],["עַל־יְדֵי","by-means-of"],["אֱמוּנַתְכֶם","your-faith"],["׃",""]] },
  { num:"ח", words:[["כִּי","because"],["עַתָּה","now"],["נִחְיֶה","we-live"],["אִם־תַּעַמְדוּ","if-you-shall-stand"],["אַתֶּם","you-are"],["בַּאֲדֹנֵינוּ","in-the-our-Lord"],["׃",""]] },
  { num:"ט", words:[["כִּי","because"],["מַה־נָּשִׁיב","what-we-shall-return"],["לֵאלֹהִים","to-God"],["לְהוֹדוֹת","to-give-thanks"],["לוֹ","him"],["בַּעֲבוּרְכֶם","for-your-sakes"],["עַל","upon"],["כָּל־הַשִׂמְחָה","all-the-joy"],["אֲשֶׁר","that"],["שָׂמַחְנוּ","we-rejoiced"],["עֲלֵיכֶם","over-you"],["לִפְנֵי","before"],["אֱלֹהֵינוּ","our-God"],["׃",""]] },
  { num:"י", words:[["לַיְלָה","night"],["וְיוֹמָם","and-by day"],["מִתְפַּלְּלִים","those who pray"],["אֲנַחְנוּ","we"],["בְּרָב־תַּחֲנוּנִים","with-greatness of-supplications"],["לִרְאוֹת","to-see"],["אֶת־פְּנֵיכֶם","[ACC]-face-of-you"],["וּלְהַשְׁלִים","and-to-complete"],["אֶת־מַחֲסֹרֵי","[ACC]-the-lacks-of"],["אֱמוּנַתְכֶם","your-faith"],["׃",""]] },
  { num:"יא", words:[["וְהָאֱלֹהִים","and-the-God"],["אָבִינוּ","our-father"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["הוּא","he"],["יְיַשֵּׁר","will-make-straight"],["אֶת־דַּרְכֵּנוּ","[ACC]-journey-our"],["אֲלֵיכֶם","unto-you"],["׃",""]] },
  { num:"יב", words:[["וְאֶתְכֶם","and-you"],["יַרְבֶּה","may-increase"],["הָאָדוֹן","the-Lord"],["וְיַפְרֶה","and-abound"],["בְּאַהֲבַת","in-love-of"],["אִישׁ","a-man"],["אֶת־רֵעֵהוּ","[ACC]-another"],["וּבְאַהֲבַת","and-a-love-of"],["כָּל־אָדָם","all-men"],["כַּאֲשֶׁר","when/as"],["אֲנַחְנוּ","we"],["אֹהֲבִים","love"],["אֶתְכֶם","you"],["׃",""]] },
  { num:"יג", words:[["לְחַזֵּק","to-strengthen"],["אֶת־לְבַבְכֶם","[ACC]-your-hearts"],["לִהְיוֹת","to-be"],["תָּמִים","intent"],["בִּקְדֻשָּׁה","in-holiness"],["לִפְנֵי","before"],["אֱלֹהֵינוּ","our-God"],["אָבִינוּ","our-father"],["בְּבוֹא","when-comes"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲדֹנֵינוּ","our-Lord"],["עִם־כָּל־קְדשָׁיו","with-all-His-saints"],["׃",""]] },
];
renderVerseSet(_1th_ch3Verses, '1th-ch3-verses');

var _1th_ch4Verses = [
  { num:"א", words:[["וְעוֹד","and-again"],["נְבַקְשָׁה","let-us-seek"],["מִכֶּם","from-you"],["אַחַי","my-brothers"],["וְנַזְהִיר","and-we-exhort"],["אֶתְכֶם","you"],["בַּאֲדֹנֵינוּ","in-the-our-Lord"],["יֵשׁוּעַ","Jesus"],["כִּי","because"],["כַּאֲשֶׁר","when/as"],["קִבַּלְתֶּם","received"],["מֵאִתָּנוּ","from-among-us"],["אֵיךְ","how"],["עֲלֵיכֶם","over-you"],["לְהִתְהַלֵּךְ","to-walk"],["וְלִמְצֹא","and-to-find"],["חֵן","favor"],["בְּעֵינֵי","in-the-eyes-of"],["הָאֱלֹהִים","the-God"],["וְכַאֲשֶׁר","and-as"],["גַּם־הִתְהַלַּכְתֶּם","also-you-walk"],["כֵּן","thus"],["תּוֹסִיפוּ","continue"],["וְכֵן","and-so"],["תַּרְבּוּ","you-increase"],["עוֹד","any-more"],["׃",""]] },
  { num:"ב", words:[["כִּי","because"],["יְדַעְתֶּם","you-know"],["אֶת־הַמִּצְוֹת","[ACC]-the-commandments"],["אֲשֶׁר","which"],["נָתַנּוּ","we-put"],["לָכֶם","to-you"],["בְּשֵׁם","by-name"],["הָאָדוֹן","the-Lord"],["יֵשׁוּעַ","Jesus"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["זֶה","this"],["רְצוֹן","the-will-of"],["הָאֱלֹהִים","the-God"],["קְדֻשַּׁתְכֶם","your-sanctification"],["לְהִתְרַחֵק","to-distance-oneself"],["מִן־הַזְּנוּת","from-the-whoredom"],["׃",""]] },
  { num:"ד", words:[["וְיֵדַּע","for-he-shall-know"],["כָּל־אִישׁ","every-man"],["מִכֶּם","from-you"],["לְהִשְׁתַּמֵּשׁ","to-use"],["בְּכִלְיוֹ","in-his-vessel"],["בִּקְדֻשָּׁה","in-holiness"],["וִיקָר","and-honor"],["׃",""]] },
  { num:"ה", words:[["וְלֹא־בְתַאֲוַת","and-not-in-lust-of"],["זִמָּה","lust"],["כְּדֶרֶךְ","after-manner-of"],["הַגּוֹיִם","the-nations"],["אֲשֶׁר־אֵינָם","whose-they-are-not"],["יֹדְעִים","knowing"],["הָאֱלֹהִים","the-God"],["׃",""]] },
  { num:"ו", words:[["וְלֹא־יַעֲשֹׁק","and-not-defraud"],["אִישׁ","a-man"],["וְיוֹנֶה","and-wrong"],["אֶת־אָחִיו","[ACC] another"],["בְּמַשָׂא","in-business"],["וּמַתָּן","and-a-gift"],["כִּי־נוֹקֵם","because-an-avenger"],["יְהוָֹה","the-Lord"],["עַל־כָּל־זֹאת","upon-all-this"],["כַּאֲשֶׁר","when/as"],["כְּבָר","already"],["אָמַרְנוּ","we-told"],["אֲלֵיכֶם","unto-you"],["וְהַעִידֹנוּ","and-we-testified"],["בָכֶם","over-you"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["לֹא־קָרָא","not-called"],["אוֹתָנוּ","us"],["הָאֱלֹהִים","the-God"],["לַטֻּמְאָה","to-the-uncleanness"],["כִּי","because"],["אִם־לַקְּדֻשָּׁה","but-to-the-holiness"],["׃",""]] },
  { num:"ח", words:[["עַל־כֵּן","therefore"],["הַבּוֹזֶה","the-is despising"],["לֹא","not"],["בֶן־אָדָם","son-of-man"],["הוּא","he"],["בוֹזֶה","the one who despises"],["כִּי","because"],["אִם־אֶת־הָאֱלֹהִים","if-[ACC]-the-God"],["אֲשֶׁר","which"],["גַּם־שָׂם","also-set"],["בְּקִרְבֵּנוּ","among-us"],["אֶת־רוּחַ","[ACC]-the-Spirit-of"],["קָדְשׁוֹ","his-holiness"],["׃",""]] },
  { num:"ט", words:[["וְעַל־אַהֲבַת","and-upon-love-of"],["הָאַחִים","the-brethren"],["אֵין־צֹרֶךְ","there-is-no-need"],["לִכְתֹּב","to-write"],["אֲלֵיכֶם","unto-you"],["הֲלֹא","do-not"],["אַף־אַתֶּם","yea-you-are"],["לְמוּדֵי","who were trained of"],["יְהוָֹה","the-Lord"],["לְאַהֲבָה","to-love"],["אִישׁ","a-man"],["אֶת־רֵעֵהוּ","[ACC]-another"],["׃",""]] },
  { num:"י", words:[["וְגַם","and-also"],["עֲשִׂיתֶם","you-have-done"],["כֵּן","thus"],["לְכָל־אֲחֵיכֶם","to-all-your-brethren"],["אֲשֶׁר","which"],["בְּכָל־מַקְדּוֹנְיָא","in-all-Macedonia"],["אֲבָל","but/however"],["נְבַקְשָׁה","let-us-seek"],["מִכֶּם","from-you"],["אַחַי","my-brothers"],["אֲשֶׁר","which"],["כֵּן","thus"],["תַּעֲשׂוּ","you-do"],["וְכֵן","and-so"],["תּוֹסִיפוּ","continue"],["׃",""]] },
  { num:"יא", words:[["וְתִשְׁתַּדְּלוּ","and-you-shall-strive"],["לָשֶׁבֶת","to-dwell"],["בְּנָחַת","in-quietness"],["וְתַעֲשׂוּ","and-perform"],["אִישׁ","a-man"],["מְלַאכְתּוֹ","His-work"],["בַּעֲמַל","at-the trouble of"],["יְדֵיכֶם","your-hands"],["כַּאֲשֶׁר","when/as"],["צִוִּינוּ","we-commanded"],["אֶתְכֶם","you"],["׃",""]] },
  { num:"יב", words:[["לְמַעַן","in-order-that"],["תִּתְהַלְּכוּ","you-walk"],["כְהֹגֶן","properly"],["עִם־אֹתָם","with-them"],["שֶׁבַּחוּץ","that-are-outside"],["וְלֹא","and-not"],["תִּצְטָרֲכוּ","you-need"],["לְאָדָם","to-man"],["׃",""]] },
  { num:"יג", words:[["וְעַל־דְּבַר","and-upon-word-of"],["הַיְשֵׁנִים","those-who-sleep"],["אֶחָי","brothers-my"],["לֹא־נְכַחֵד","not-we will hide"],["מִכֶּם","from-you"],["דָּבָר","a-word"],["לְמַעַן","in-order-that"],["לֹא","not"],["תֵּעָצְבוּ","you be grieved"],["כַּאֲחֵרִים","as-the-others"],["אֲשֶׁר","which"],["אֵין־לָהֶם","there-is-no-to-them"],["תִּקְוָה","hope"],["׃",""]] },
  { num:"יד", words:[["כִּי","because"],["אִם־נַאֲמִין","if-we-believe"],["אֲשֶׁר־מֵת","whose-is-dead"],["יֵשׁוּעַ","Jesus"],["וַיֶּחִי","and-rose-again"],["כֵּן","thus"],["יָבִיא","shall-bring"],["הָאֱלֹהִים","the-God"],["גַּם","also"],["אֶת־הַיְשֵׁנִים","[ACC]-those-who-sleep"],["בְּיֵשׁוּעַ","in-Jesus"],["אִתּוֹ","with-him"],["׃",""]] },
  { num:"טו", words:[["כִּי","because"],["אֶת־זֹאת","[ACC]-this"],["נֹאמַר","it-was-said"],["לָכֶם","to-you"],["בִּדְבַר","of-the-promise-of"],["יְהוָֹה","the-Lord"],["כִּי","because"],["אֲנַחְנוּ","we"],["הַחַיִּים","the-life"],["הַנּוֹתָרִים","the-remaining"],["עַד־בֹּא","until-come"],["הָאָדוֹן","the-Lord"],["לֹאֹ","not"],["נְקַדֵּם","shall-precede"],["אֶת־הַיְשֵׁנִים","[ACC]-those-who-sleep"],["׃",""]] },
  { num:"טז", words:[["כִּי","because"],["הָאָדוֹן","the-Lord"],["הוּא","he"],["יֵרֵד","will-descend"],["מִן־הַשָּׁמַיִם","from-the-heavens"],["בִּתְרוּעָה","with-shouting"],["בְּקוֹל","the-voice-of"],["שַׂר","the-king's-captain"],["הַמַּלְאָכִים","the-angels"],["וּבְשׁוֹפַר","and-in-a ram's horn of"],["אֱלֹהִים","God"],["וְאָז","and-then"],["יָקוּמוּ","they-shall-stand"],["רִאשׁוֹנָה","first"],["הַמֵּתִים","the-dead"],["בַּמָּשִׁיחַ","in-the-Messiah"],["׃",""]] },
  { num:"יז", words:[["אַחֲרֵי־כֵן","hereafter"],["אֲנַחְנוּ","we"],["הַחַיִּים","the-life"],["הַנּוֹתָרִים","the-remaining"],["נִלָּקַח","we-will-be-caught-up"],["אִתָּם","with-them"],["יַחְדָּו","together"],["בַּעֲנָנִים","in-the-clouds"],["לִקְרַאת","to-meet"],["הָאָדוֹן","the-Lord"],["לָאֲוִיר","to-the-air"],["וּבְכֵן","and-in-such"],["נִהְיֶה","let-us-be"],["תָמִיד","continually"],["עִם־הָאָדוֹן","with-the-Lord"],["׃",""]] },
  { num:"יח", words:[["לָכֵן","therefore"],["נַחֲמוּ","comfort"],["זֶה","this"],["אֶת־זֶה","[ACC]-this"],["בַּדְּבָרִים","in-the-words"],["הָאֵלֶּה","these"],["׃",""]] },
];
renderVerseSet(_1th_ch4Verses, '1th-ch4-verses');

var _1th_ch5Verses = [
  { num:"א", words:[["וְעַל־דְּבַר","and-upon-word-of"],["הָעִתִּים","the-times"],["וְהַזְּמַנִּים","and-the-seasons"],["אֵין־צֹרֶךְ","there-is-no-need"],["לִכְתֹּב","to-write"],["אֲלֵיכֶם","unto-you"],["אֶחָי","brothers-my"],["׃",""]] },
  { num:"ב", words:[["הֲלֹא","do-not"],["אַף־אַתֶּם","yea-you-are"],["יְדַעְתֶּם","you-know"],["הֵיטֵב","well/diligently"],["כִּי","because"],["יוֹם־יְהוָֹה","the-day-of-the-LORD"],["כַּגַּנָּב","like-the-thief"],["בַּלַּיְלָה","in-the-night"],["כֵּן","thus"],["יָבוֹא","shall-come"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["בְאָמְרָם","because-will say-they"],["שָׁלוֹם","peace"],["וְשַׁלְוָה","and-quietness"],["יָבֹא","shall-come"],["עֲלֵיהֶם","upon-them"],["הַשֶּׁבֶר","the-destruction"],["פִּתְאֹם","suddenly"],["כְּחֶבְלֵי","as-pains-of"],["יוֹלֵדָה","a woman who gives birth"],["וְלֹא","and-not"],["יוּכְלוּ","could-they"],["הִמָּלֵט","escape"],["׃",""]] },
  { num:"ד", words:[["אֲבָל","but/however"],["אַתֶּם","you-are"],["אַחַי","my-brothers"],["לֹא","not"],["בַּחשֶׁךְ","in-the-darkness"],["אַתֶּם","you-are"],["שֶׁיַּשִׂיג","that-he-shall-overtake"],["אֶתְכֶם","you"],["הַיּוֹם","the-day"],["כַּגַּנָּב","like-the-thief"],["׃",""]] },
  { num:"ה", words:[["אַתֶּם","you-are"],["כֻּלְּכֶם","all-you"],["בְּנֵי","the-sons-of"],["הָאוֹר","the-light"],["וּבְנֵי","and-sons-of"],["הַיּוֹם","the-day"],["לֹא","not"],["בְנֵי־הַלַּיְלָה","sons-of-the-night"],["אֲנַחְנוּ","we"],["וְלֹא","and-not"],["בְּנֵי","the-sons-of"],["הַחשֶׁךְ","the-darkness"],["׃",""]] },
  { num:"ו", words:[["לָכֵן","therefore"],["אַל־נָא","do-not-I-pray"],["נֵרָדֵם","let-us-sleep"],["כְּמוֹ","as/like"],["הָאֲחֵרִים","the-other"],["כִּי","because"],["אִם־נִשְׁקֹד","let-us-watch"],["וְנִהְיֶה","and-let-us-be"],["ְמְפֻכָּחִים","sober"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["הַנִּרְדָּמִים","the-those-who-have-slumbered"],["נִרְדָּמִים","sleeping"],["בַּלָּיְלָה","by-the-night"],["וְהַמִּשְׁתַּכְּרִים","and-the-those-who-get-drunk"],["מִשְׁתַּכְּרִים","get-drunk"],["בַּלָּיְלָה","by-the-night"],["׃",""]] },
  { num:"ח", words:[["וַאֲנַחְנוּ","and-we-are"],["בְּנֵי","the-sons-of"],["הַיּוֹם","the-day"],["נִתְּפַּכֵּחַ־נָּא","let-us-be-sober"],["וְנִלְבַּשׁ","and-we-will-wear"],["אֶת־שִׁרְיוֹן","[ACC]-the-armor-of"],["הָאֱמוּנָה","the-faith"],["וְהָאַהֲבָה","and-the-love"],["וְכַכּוֹבַע","and-as-the-helmet"],["אֶת־תִּקְוַת","[ACC]-a-hope-of"],["הַיְשׁוּעָה","the-salvation"],["׃",""]] },
  { num:"ט", words:[["יַעַן","because"],["אֲשֶׁר","which"],["לֹא־יְעָדָנוּ","has-not-appointed-us"],["הָאֱלֹהִים","the-God"],["לְחָרוֹן","to-the-severity-of"],["כִּי","because"],["לָרֶשֶׁת","to-possess"],["אֶת־הַיְשׁוּעָה","[ACC]-the-salvation"],["עַל־יְדֵי","by-means-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"י", words:[["אֲשֶׁר","which"],["מֵת","is-dead"],["בַּעֲדֵנוּ","for-us"],["לְמַעַן","in-order-that"],["נִחְיֶה","we-live"],["עִמּוֹ","with-him"],["יָחַד","together"],["אִם־נִשְׁקֹד","let-us-watch"],["וְאִם־נִישָׁן","and-whether-we-sleep"],["׃",""]] },
  { num:"יא", words:[["עַל־כֵּן","therefore"],["נַחֲמוּ","comfort"],["זֶה","this"],["אֶת־זֶה","[ACC]-this"],["וּבְנוּ","and-build!(pl)"],["אִישׁ","a-man"],["אֶת־אָחִיו","[ACC] another"],["כַּאֲשֶׁר","when/as"],["עֲשִׂיתֶם","you-have-done"],["׃",""]] },
  { num:"יב", words:[["וְהִנְנוּ","and-behold-us"],["מְבַקְשִׁים","seek"],["מִכֶּם","from-you"],["אַחַי","my-brothers"],["לְהַכִּיר","to-knowledge-of"],["אֶת־הָעֲמֵלִים","[ACC]-the-those-who-labor"],["בָּכֶם","in-you"],["וְאֵת","and-[ACC]"],["הַנִּצָּבִים","the-those-appointed"],["עֲלֵיכֶם","over-you"],["בִּדְבַר","of-the-promise-of"],["הָאָדוֹן","the-Lord"],["וּמוֹכִיחִים","and-persuading-them"],["אֶתְכֶם","you"],["׃",""]] },
  { num:"יג", words:[["וְתִנְהֲגוּ־בָם","and-esteem-them"],["כָּבוֹד","glorious"],["גָּדוֹל","great"],["מְאֹד","exceedingly"],["בְּאַהֲבָה","and-in-love"],["לְמַעַן","in-order-that"],["פְּעֻלָּתָם","recompense-their"],["וִיהִי","and-may-be"],["שָׁלוֹם","peace"],["בֵּינֵיכֶם","among-you"],["׃",""]] },
  { num:"יד", words:[["וְהִנְנוּ","and-behold-us"],["מַזְהִירִים","exhorting"],["אֶתְכֶם","you"],["אֶחָי","brothers-my"],["הוֹכִיחוּ","warn"],["אֶת־הַמְעַקְּשִׁים","[ACC]-the-unruly"],["דַּרְכֵיהֶם","their-ways"],["אַמְּצוּ","encourage"],["אֶת־רַכֵּי","[ACC]-are-tender-of"],["הַלֵּבָב","the-heart"],["תִּמְכוּ","support"],["אֶת־הַחַלָּשִׁים","[ACC]-the-weak"],["וְהַאֲרִיכוּ","and-they-did-prolong"],["רוּחַ","the-spirit-of"],["אֶל־כָּל־אָדָם","to-all-man"],["׃",""]] },
  { num:"טו", words:[["וּרְאוּ","and-see"],["פֶּן־יְשַׁלֵּם","lest-he-will-complete"],["אִישׁ","a-man"],["לְרֵעֵהוּ","another"],["רָעָה","evil"],["תַּחַת","under"],["רָעָה","evil"],["כִּי","because"],["אִם־רִדְפוּ","if-pursue"],["בְּכָל־עֵת","with-all-time"],["אֶת־הַטּוֹב","[ACC]-that-the-which-is-good"],["הֵן","yea"],["לְאִישׁ","for-a-man"],["אִישׁ","a-man"],["מִכֶּם","from-you"],["הֵן","yea"],["לְכָל־אָדָם","unto-all-men"],["׃",""]] },
  { num:"טז", words:[["שִׂמְחוּ","rejoice"],["בְּכָל־עֵת","with-all-time"],["׃",""]] },
  { num:"יז", words:[["הִתְפַּלְּלוּ","pray!"],["כָּל־הַיּוֹם","every-the-day"],["׃",""]] },
  { num:"יח", words:[["הוֹדוּ","praise"],["עַל־הַכֹּל","upon-all-the"],["כִּי־זֶה","that-this"],["רְצוֹן","the-will-of"],["אֱלֹהִים","God"],["בַּמָּשִׁיחַ","in-the-Messiah"],["יֵשׁוּעַ","Jesus"],["אֲלֵיכֶם","unto-you"],["׃",""]] },
  { num:"יט", words:[["אֶת־הָרוּחַ","[ACC]-the-spirit"],["לֹא","not"],["תְּכַבּוּ","you-shall-quench"],["׃",""]] },
  { num:"כ", words:[["אֶת־הַנְּבוּאוֹת","[ACC] the-prophecies"],["לֹא","not"],["תִמְאָסוּ","you will reject"],["׃",""]] },
  { num:"כא", words:[["בַּחֲנוּ","test"],["כָּל־דָּבָר","all-things"],["וּבַטּוֹב","and-the-good"],["אֱחֹזוּ","hold-fast"],["׃",""]] },
  { num:"כב", words:[["הִתְרַחֲקוּ","abstain"],["מִכָּל־הַדּוֹמֶה","from-every-the-appearance-of"],["לָרָע","to-the-evil"],["׃",""]] },
  { num:"כג", words:[["וֵאלֹהֵי","and-God-of"],["הַשָּׁלוֹם","the-peace"],["הוּא","he"],["יְקַדֵּשׁ","will-consecrate"],["אֶתְכֶם","you"],["בִּקְדֻשָּׁה","in-holiness"],["שְׁלֵמָה","complete/perfect"],["וְכָל־רוּחֲכֶם","and-all-spirit-you"],["וְנַפְשְׁכֶם","and-soul"],["וְגוּפְכֶם","and-your-body"],["יִשָּׁמֵר","shall-be-kept"],["תָּמִים","intent"],["בְּבוֹא","when-comes"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"כד", words:[["נֶאֱמָן","more-faithful"],["הוּא","he"],["הַקּוֹרֵא","the-calling"],["אֶתְכֶם","you"],["אֲשֶׁר","which"],["גַּם־יַעֲשֶׂה","also-he-shall-do"],["׃",""]] },
  { num:"כה", words:[["אַחַי","my-brothers"],["הִתְפַּלֲלוּ","pray!"],["בַעֲדֵנוּ","for-us"],["׃",""]] },
  { num:"כו", words:[["שַׁאֲלוּ","greet"],["לִשְׁלוֹם","for-the-welfare-of"],["כָּל־הָאַחִים","all-the-brethren"],["בַּנְּשִׁיקָה","in-the-kiss"],["הַקְּדשָׁה","the-holiness"],["׃",""]] },
  { num:"כז", words:[["הִנְנִי","behold-I"],["מַשְׁבִּיעֲכֶם","I-charge-you"],["בָּאָדוֹן","in-the-Lord"],["אֲשֶׁר","which"],["תִּקָּרֵא","shall-be-proclaimed"],["הָאִגֶּרֶת","the-epistle"],["הַזֹּאת","this"],["בְּאָזְנֵי","in-ears-of"],["כָּל־הָאַחִים","all-the-brethren"],["הַקְּדוֹשִׁים","the-holy"],["׃",""]] },
  { num:"כח", words:[["חֶסֶד","grace"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲדֹנֵינוּ","our-Lord"],["עִמָּכֶם","with-you"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(_1th_ch5Verses, '1th-ch5-verses');

})();
