// nt_verses/1th.js — 1 Thessalonians verse data
(function() {
var _1th_ch1Verses = [
  { num:"א", words:[["פּוֹלוֹס","Paul"],["וְסִלְוָנוֹס","and-Silvanus"],["וְטִימוֹתִיּוֹס","and-Timothy"],["אֶל־קְהִלַּת","to-the-church-of"],["הַתֶּסָּלוֹנִיקִיּים","the-Thessalonians"],["בֵּאלֹהִים","in-God"],["הָאָב","the-Father"],["וּבָאָדוֹן","and-in-the-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["חֶסֶד","grace"],["לָכֶם","to-you"],["וְשָׁלוֹם","and-peace"],["מֵאֵת","from"],["אֱלֹהִים","God"],["אָבִינוּ","our-father"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ב", words:[["נוֹדֶה","we-give-thanks"],["לֵאלֹהִים","to-God"],["עַל־כֻּלְּכֶם","upon-all-you"],["בְּכׇל־עֵת","with-all-time"],["בְּהַזְכִּירֵנוּ","in-our-remembering"],["אֶתְכֶם","you"],["בִּתְפִלּוֹתֵינוּ","in-our-prayers"],["׃",""]] },
  { num:"ג", words:[["בְּזָכְרֵנוּ","remembering"],["תָמִיד","continually"],["לִפְנֵי","before"],["הָאֱלֹהִים","the-God"],["אָבִינוּ","our-father"],["אֶת־פֹּעַל","the-work-of"],["אֱמוּנַתְכֶם","your-faith"],["וִיגִיעַת","and-labour-of"],["אַהֲבַתְכֶם","your-love"],["וְסַבְלָנוּת","and-patience-of"],["תִּקְוַתְכֶם","your-hope"],["לַאֲדֹנֵינוּ","to-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["יָדַעְנוּ","knowing"],["אַחַי","my-brothers"],["חֲבִיבֵי","my-beloved"],["הָאֱלֹהִים","the-God"],["אֵת־אֲשֶׁר","your"],["נִבְחַרְתֶּם","election"],["׃",""]] },
  { num:"ה", words:[["בַּאֲשֶׁר","because"],["בְּשׂוֹרָתֵנוּ","our-gospel"],["לֹא","not"],["בָאָה","came"],["לָכֶם","to-you"],["בְּדִבּוּר","in-word"],["לְבָד","alone"],["כִּי־גַם","because-also"],["בִּגְבוּרָה","with-power"],["וּבְרוּחַ","and-in-the-Spirit-of"],["הַקֹּדֶשׁ","the-Holy"],["וּבְדַעַת","and-in-much"],["נְכוֹנָה","assurance"],["מְאֹד","exceedingly"],["כַּאֲשֶׁר","when/as"],["יְדַעְתֶּם","you-know"],["אֵת־אֲשֶׁר־הָיִינוּ","how-we-were"],["בְּתוֹכֲכֶם","among-you"],["לְמַעַנְכֶם","for-your-sakes"],["׃",""]] },
  { num:"ו", words:[["וִהְיִיתֶם","and-you-became-followers"],["לְהֹלְכֵי","to-those who walk of"],["בְעִקְּבוֹתֵינוּ","in-the footprints of-our"],["וּבְעִקְּבוֹת","and-in-the footprints of"],["אֲדֹנֵינוּ","our-Lord"],["כִּי","because"],["קִבַּלְתֶּם","received"],["אֶת־הַדָּבָר","the-word"],["בְּתוֹךְ","among"],["עֳנִי","affliction"],["רָב","much"],["בְּחֶדְוַת","in-the-joy-of"],["רוּחַ","the-Spirit-of"],["הַקֹּדֶשׁ","the-Holy"],["׃",""]] },
  { num:"ז", words:[["עַד־הֱיוֹתְכֶם","until-your-being"],["לְמוֹפֵת","an-example"],["לְכׇל־הַמַּאֲמִינִים","to-all-the-believers"],["אֲשֶׁר","who-are"],["בְּמַקְדּוֹנְיָא","in-Macedonia"],["וּבַאֲכַיָּא","and-in-Achaia"],["׃",""]] },
  { num:"ח", words:[["כִּי","because"],["מֵאִתְּכֶם","of-you"],["נִשְׁמַע","was-heard"],["קוֹל","the-voice-of"],["דְּבַר","the-word-of"],["יְהוָֹה","the-Lord"],["לֹא","not"],["בְּמַקְדּוֹנְיָא","in-Macedonia"],["וַאֲכַיָּא","and-Achaia"],["לְבַד","alone"],["כִּי","because"],["בְּכׇל־מָקוֹם","in-every-place"],["יָצְאָה","is-spread-abroad"],["אֱמוּנַתְכֶם","your-faith"],["לֵאלֹהִים","to-God"],["וְאֵין־לָנוּ","and-we-have-no"],["צֹרֶךְ","need"],["לְדַבֵּר","to-speak"],["עוֹד","any-more"],["דָּבָר","a-word"],["׃",""]] },
  { num:"ט", words:[["כִּי־פִיהֶם","for-they-themselves"],["הַמַּגִּיד","shew"],["מֶה־הָיָה","what"],["מְבוֹאֵנוּ","our-entering-in"],["אֲלֵיכֶם","unto-you"],["וְאֵיךְ","and-how"],["עֲזַבְתֶּם","you-forsook"],["הָאֱלִילִים","the-idols"],["וְשַׁבְתֶּם","and-you-turned"],["לֵאלֹהִים","to-God"],["לַעֲבֹד","to-serve"],["אֵל","God"],["חַי","living"],["וַאֲמִתִּי","and-true"],["׃",""]] },
  { num:"י", words:[["וּלְחַכּוֹת","and-to-wait-for"],["לִבְנוֹ","for-his-Son"],["מִן־הַשָּׁמַיִם","from-heaven"],["אֲשֶׁר","whom"],["הֱעִירוֹ","he-raised"],["מִן־הַמֵּתִים","from-the-dead"],["לְיֵשׁוּעַ","to-Jesus"],["הַמַּצִּילֵנוּ","which-delivered-us"],["מִן־הֶחָרוֹן","from-the-wrath"],["הַבָּא","that-comes"],["׃",""]] },
];
renderVerseSet(_1th_ch1Verses, '1th-ch1-verses');

var _1th_ch2Verses = [
  { num:"א", words:[["כִּי","because"],["אַתֶּם","you-are"],["אַחַי","my-brothers"],["יְדַעְתֶּם","you-know"],["אֶת־מְבוֹאֵנוּ","our-entrance"],["אֲלֵיכֶם","unto-you"],["כִּי","because"],["לֹא־הָיָה","not-was"],["לָרִיק","in-vain"],["׃",""]] },
  { num:"ב", words:[["וְאַחֲרֵי","and-after"],["אֲשֶׁר","that"],["עֻנֵּינוּ","we-had-suffered"],["וּלְחֶרְפָּה","and-into-a reproach"],["הָיִינוּ","we-were"],["בְּפִילִפִּי","in-Philippi"],["כַּאֲשֶׁר","when/as"],["יְדַעְתֶּם","you-know"],["הִתְחַזַּקְנוּ","we-were-bold"],["בֵאלֹהֵינוּ","in-our-God"],["לְהַגִּיד","to-declare"],["גַּם־לָכֶם","also-to-you"],["אֶת־הַבְּשׂוֹרָה","the-good-tidings"],["בְּנַפְתּוּלִים","in-great-conflict"],["רַבִּים","many"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["תוֹכַחְתֵּנוּ","our-exhortation"],["אֵינֶנָּה","is-not"],["מִתּוֹךְ","from-the-midst-of"],["טָעוּת","deceit"],["וְלֹא","and-not"],["מִתּוֹךְ","from-the-midst-of"],["טֻמְאָה","filthiness"],["וְלֹא","and-not"],["בִּרְמִיָּה","in-deceit"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["כַּאֲשֶׁר","when/as"],["נִמְצֵאנוּ","we-were-allowed"],["נֶאֱמָנִים","faithful"],["לֵאלֹהִים","to-God"],["לְהַפְקִיד","to-entrust"],["בְּיָדֵנוּ","in-our-hand"],["הַבְּשׂוֹרָה","the-gospel"],["כֵּן","thus"],["נְדַבֵּר","so-we-speak"],["וְלֹא","and-not"],["לִהְיוֹת","to-be"],["רְצוּיִם","pleasing"],["לִבְנֵי","unto-the-children-of"],["אָדָם","man"],["כִּי","but"],["אִם","rather"],["לֵאלֹהִים","God"],["הַבֹּחֵן","which-trieth"],["לִבּוֹתֵנוּ","our-hearts"],["׃",""]] },
  { num:"ה", words:[["כִּי","because"],["מֵעוֹלָם","never"],["לֹא","not"],["דִבַּרְנוּ","we-used"],["בִּשְׂפַת","in-the-language-of"],["חֲלָקוֹת","flattering-things"],["כַּאֲשֶׁר","when/as"],["יְדַעְתֶּם","you-know"],["וְלֹא","and-not"],["לְמַעַן","in-order-that"],["בְּצֹעַ","a-cloke-of"],["בֶּצַע","covetousness"],["בַּסָּתֶר","in-secret"],["עֵד","is-witness"],["הָאֱלֹהִים","the-God"],["׃",""]] },
  { num:"ו", words:[["גַּם","also"],["לֹא־בִקַּשְׁנוּ","not-we-sought"],["מִן־הָאָדָם","from-the-man"],["כָּבוֹד","glory"],["לֹא","not"],["מִכֶּם","from-you"],["וְלֹא","and-not"],["מֵאֲחֵרִים","from-others"],["אַף","yea"],["כִּי","because"],["יָכֹלְנוּ","we-might-have-been"],["לִהְיוֹת","to-be"],["בִּיקָר","burdensome"],["כִּשְׁלִיחֵי","as-apostles-of"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ז", words:[["אֶלָּא","but-rather"],["הָלַכְנוּ","we-were"],["לְאַט","gentle"],["בְּתוֹכֲכֶם","among-you"],["כְּאֹמֶנֶת","as-a nurse"],["מְפַנֶּקֶת","cherishing"],["אֶת־בָּנֶיהָ","sons-her"],["׃",""]] },
  { num:"ח", words:[["וּבְחַבְּבֵנוּ","being-affectionately-desirous-of"],["אֶתְכֶם","you"],["כָּכָה","thus"],["חָפַצְנוּ","we-were-willing"],["לָתֵת","to-give"],["לָכֶם","to-you"],["לֹא","not"],["אֶת־בְּשׂוֹרַת","good-tidings-of"],["הָאֱלֹהִים","the-God"],["לְבַד","alone"],["אֶלָּא","but-rather"],["אַף","yea"],["נַפְשֹׁתֵינוּ","our-own-souls"],["יַעַן","because"],["כִּי־הֱיִיתֶם","because-you-were"],["חֲבִיבִים","beloved-ones"],["עָלֵינוּ","over-us"],["׃",""]] },
  { num:"ט", words:[["הֲלֹא","do-not"],["תִזְכְּרוּ","you-remember"],["אַחַי","my-brothers"],["אֶת־עֲמָלֵנוּ","our-labor"],["וְאֶת־תְּלָאָתֵנוּ","and-travail"],["אֲשֶׁר","which"],["יָגַעְנוּ","labouring"],["לַיְלָה","night"],["וְיוֹמָם","and-by day"],["לְבִלְתִּי","to-not"],["הֱיוֹת","have"],["לְמַשָׂא","chargeable"],["לְאִישׁ","to-any"],["מִכֶּם","of-you"],["בְּבַשְׂרֵנוּ","we-preached"],["בְקִרְבְּכֶם","among-you"],["אֶת־בְּשׂוֹרַת","good-tidings-of"],["הָאֱלֹהִים","the-God"],["׃",""]] },
  { num:"י", words:[["עֵדִים","witnesses"],["אַתֶּם","you-are"],["וְעֵד","and-witness"],["הָאֱלֹהִים","the-God"],["אִם־לֹא","if-not"],["בִקְדֻשָּׁה","in-holiness"],["וּבְצֶדֶק","and-with-righteousness"],["וּבְתָמִים","and-unblameably"],["הָיִינוּ","we-behaved"],["עִמָּכֶם","with-you"],["הַמַּאֲמִינִים","the-believers"],["׃",""]] },
  { num:"יא", words:[["וְאַתֶּם","and-you"],["יְדַעְתֶּם","you-know"],["כִּי־כְאָב","because-like-a father"],["אֶת־בָּנָיו","his-sons"],["הִזְהַרְנוּ","we-exhorted"],["אֶת־כׇּל־אֶחָד","every-one"],["מִכֶּם","from-you"],["וְדִבַּרְנוּ","and-we have spoken"],["עַל","upon"],["לִבּוֹ","his-heart"],["׃",""]] },
  { num:"יב", words:[["וַנָּעַד","and-we-charged"],["בָּכֶם","in-you"],["לָלֶכֶת","to-go"],["כַּטּוֹב","worthy"],["לִפְנֵי","before"],["הָאֱלֹהִים","the-God"],["הַקּוֹרֵא","who-hath-called"],["אֶתְכֶם","you"],["לְמַלְכוּתוֹ","to-his-kingdom"],["וְלִכְבוֹדוֹ","and-to-his-glory"],["׃",""]] },
  { num:"יג", words:[["בַּעֲבוּר","because-of"],["זֹאת","this"],["אֲנַחְנוּ","we"],["לֹא","not"],["נֶחְדַּל","we-cease"],["לְהוֹדֹת","to-give-thanks"],["לֵאלֹהִים","to-God"],["כִּי","because"],["אַתֶּם","you-are"],["קִבַּלְתֶּם","received"],["מֵאִתָּנוּ","from-among-us"],["דְּבַר","the-word-of"],["שְׁמוּעַת","report-of"],["הָאֱלֹהִים","the-God"],["וְלֹא־קִבַּלְתֶּם","and-not-received"],["אוֹתוֹ","him"],["כִּדְבַר","according-to-the-word-of"],["בְּנֵי־אָדָם","the-children-of-men"],["כִּי","because"],["אִם־כְּמוֹ־שֶׁהוּא","but-as-it-is"],["בֶאֱמֶת","in-truth"],["כִּדְבַר","according-to-the-word-of"],["הָאֱלֹהִים","the-God"],["אֲשֶׁר","which"],["גַּם־פֹּעֵל","also-effectually-worketh"],["בָּכֶם","in-you"],["הַמַּאֲמִינִים","the-believers"],["׃",""]] },
  { num:"יד", words:[["כִּי־אַתֶּם","because-you-are"],["אַחַי","my-brothers"],["הֲלַכְתֶּם","became-followers"],["בְּעִקְּבֵי","of"],["קְהִלּוֹת","churches"],["הָאֱלֹהִים","the-God"],["אֲשֶׁר־בְּאֶרֶץ","that-are-in-the-land-of"],["יְהוּדָה","Judea"],["בַּמָּשִׁיחַ","in-the-Messiah"],["יֵשׁוּעַ","Jesus"],["כִּי","because"],["גַּם־אַתֶּם","also-you"],["עֻנֵּיתֶם","you-have-suffered"],["עַל־יְדֵי","by-means-of"],["בְנֵי־עַמְּכֶם","your-own-countrymen"],["כַּאֲשֶׁר","even-as"],["עֻנּוּ","they-have-suffered"],["גַם־הֵם","they-also"],["עַל־יְדֵי","by-means-of"],["הַיְּהוּדִים","the-Jews"],["׃",""]] },
  { num:"טו", words:[["אֲשֶׁר","who"],["אַף־הָרְגוּ","who-both-killed"],["אֶת־הָאָדוֹן","the-Lord"],["יֵשׁוּעַ","Jesus"],["וְאֶת־נְבִיאֵיהֶם","and-their-prophets"],["וְאוֹתָנוּ","and-us"],["רָדָפוּ","persecuted"],["וְאֵינָם","and-they-are-not"],["טוֹבִים","good"],["בְּעֵינֵי","in-the-eyes-of"],["אֱלֹהִים","God"],["וּמִתְקוֹמֲמִים","and-are-contrary"],["לְכׇל־אָדָם","unto-all-men"],["׃",""]] },
  { num:"טז", words:[["הָעֹצְרִים","forbidding"],["אֹתָנוּ","us"],["מִדַּבֵּר","from-speaking"],["אֶל־הַגּוֹיִם","unto-the-nations"],["שֶׁיִּוָּשֵׁעוּ","that-they-might-be-saved"],["לְמַעַן","in-order-that"],["אֲשֶׁר־יְמַלְאוּ","that-they-fill-up"],["אֶת־חַטֹּאתֵיהֶם","their-sins"],["בְּכׇל־עֵת","with-all-time"],["וַתַּשִׂיגֵם","is-come-upon-them"],["הַחֵמָה","the-wrath"],["עַד־כַּלֵּה","to-the-uttermost"],["׃",""]] },
  { num:"יז", words:[["וַאֲנַחְנוּ","and-we-are"],["אַחַי","my-brothers"],["אַחֲרֵי","after"],["אֲשֶׁר־שָׁכֹלְנוּ","being-taken-from"],["אֶתְכֶם","you"],["לִזְמַן","for-space-of"],["מְעַט","somewhat"],["לְפָנִים","in-presence"],["וְלֹא","not"],["לַלֵּב","in-heart"],["חַשְׁנוּ","we-endeavoured"],["עַד־מְאֹד","exceedingly"],["לִרְאוֹת","to-see"],["פְּנֵיכֶם","your-face"],["בִּתְשׁוּקָה","with-longing"],["רַבָּה","much"],["׃",""]] },
  { num:"יח", words:[["וְעַל־כֵּן","and-therefore"],["חָפַצְנוּ","we-desired"],["לָבוֹא","to-come"],["אֲלֵיכֶם","unto-you"],["אֲנִי","I"],["פוֹלוֹס","Paul"],["פַּעַם","once"],["וּשְׁתָּיִם","and-again"],["וְהַשָׂטָן","and-Satan"],["עֲצָרָנוּ","hindered-us"],["׃",""]] },
  { num:"יט", words:[["כִּי","because"],["מִי","who"],["תִקְוָתֵנוּ","our-hope"],["וּמִי","and-who"],["שִׂמְחָתֵנוּ","our-joy"],["וַעֲטֶרֶת","and-a crown of"],["תִּפְאַרְתֵּנוּ","our-rejoicing"],["הֲלֹא","do-not"],["גַם־אַתֶּם","also-you"],["לִפְנֵי","before"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["בְּבוֹאוֹ","at-his-coming"],["׃",""]] },
  { num:"כ", words:[["אׇמְנָם","truly"],["אַתֶּם","you-are"],["כְּבוֹדֵנוּ","our-glory"],["וְשִׂמְחָתֵנוּ","and-joy"],["׃",""]] },
];
renderVerseSet(_1th_ch2Verses, '1th-ch2-verses');

var _1th_ch3Verses = [
  { num:"א", words:[["וְעַל־כֵּן","and-therefore"],["לֹא","not"],["יָכֹלְנוּ","we-were-able"],["עוֹד","any-more"],["לְהִתְאַפֵּק","to-forbear"],["וַנִּוָּעַץ","we-thought-it-good"],["לְהִוָּתֵר","to-be-left"],["לְבַדֵּנוּ","alone"],["בְּאַתּוּנָה","in-Athens"],["׃",""]] },
  { num:"ב", words:[["וַנִּשְׁלַח","and-sent"],["אֶת־טִימוֹתִיּוֹס","Timothy"],["אָחִינוּ","our-brother"],["וּמְשָׁרֵת","and-minister-of"],["הָאֱלֹהִים","the-God"],["וְעֹזְרֵנוּ","and-our-helper"],["בִּבְשׂוֹרַת","in-the-gospel-of"],["הַמָּשִׁיחַ","the-Messiah"],["לְחַזֵּק","to-strengthen"],["אֶתְכֶם","you"],["וּלְהַזְהִיר","and-to-comfort"],["עַל־דְּבַר","concerning"],["אֱמוּנַתְכֶם","your-faith"],["׃",""]] },
  { num:"ג", words:[["לְמַעַן","in-order-that"],["אֲשֶׁר","that"],["לֹא־יִמּוֹט","no-man-be-moved"],["אִישׁ","a-man"],["בַּמְּצוּקוֹת","by-these-afflictions"],["הָאֵלֶּה","these"],["כִּי־יְדַעְתֶּם","because-you-know"],["אַף־אַתֶּם","yea-you-are"],["כִּי","because"],["לָזֹאת","to-this"],["יֻעָדְנוּ","we-are-appointed"],["׃",""]] },
  { num:"ד", words:[["הֲלֹא","do-not"],["כְּבָר","already"],["אָמַרְנוּ","we-told-you-before"],["אֲלֵיכֶם","unto-you"],["בִּהְיוֹתֵנוּ","when-were-we"],["אֶצְלְכֶם","with-you"],["כִּי־עֲתִידִים","that-we-should"],["אֲנַחְנוּ","we"],["לְהִלָּחֵץ","suffer-tribulation"],["כַּאֲשֶׁר","even-as"],["גַּם־הָיָה","it-came-to-pass"],["וְכַאֲשֶׁר","and-as"],["יְדַעְתֶּם","you-know"],["׃",""]] },
  { num:"ה", words:[["וּבַעֲבוּר","and-because"],["כֵּן","thus"],["לֹא־יָכֹלְתִּי","not-I-could"],["עוֹד","any-more"],["לְהִתְאַפֵּק","to-forbear"],["וָאֶשְׁלַח","I-sent"],["לָדַעַת","to-know"],["אֱמוּנַתְכֶם","your-faith"],["כִּי","because"],["אָמַרְתִּי","I-said"],["פֶּן־נִסָּה","lest-hath-tempted"],["אֶתְכֶם","you"],["הַמְנַסֶּה","the-tempter"],["וְהָיְתָה","and-be"],["לָרִיק","in-vain"],["יְגִיעָתֵנוּ","our-labour"],["׃",""]] },
  { num:"ו", words:[["וְעַתָּה","and-now"],["כְּשׁוּב","when-came"],["אֵלֵינוּ","unto-us"],["טִימוֹתִיּוֹס","Timothy"],["מֵאִתְּכֶם","of-you"],["וַיְבַשֵׂר","and-brought-us-good-tidings"],["אֹתָנוּ","us"],["אֶת־בְּשׂוֹרַת","good-tidings-of"],["אֱמוּנַתְכֶם","your-faith"],["וְאַהֲבַתְכֶם","and-your-love"],["וְאֵת","and"],["אֲשֶׁר","which"],["אַתֶּם","you-are"],["זֹכְרִים","have-remembrance-of"],["אֹתָנוּ","us"],["לְטוֹבָה","for-good"],["בְּכׇל־עֵת","with-all-time"],["וְנִכְסָפִים","and-longing"],["לִרְאוֹת","to-see"],["אֹתָנוּ","us"],["כַּאֲשֶׁר","when/as"],["נִכְסֹף","we-long"],["גַּם־אֲנַחְנוּ","also-we"],["לִרְאוֹתְכֶם","to-see-you"],["׃",""]] },
  { num:"ז", words:[["אָז","then"],["נֻחַמְנוּ","we-were-comforted"],["עֲלֵיכֶם","over-you"],["אַחַי","my-brothers"],["בְּכׇל־צָרָתֵנוּ","in-all-our-distress"],["וְלַחֲצֵנוּ","and-distress"],["עַל־יְדֵי","by-means-of"],["אֱמוּנַתְכֶם","your-faith"],["׃",""]] },
  { num:"ח", words:[["כִּי","because"],["עַתָּה","now"],["נִחְיֶה","we-live"],["אִם־תַּעַמְדוּ","if-you-stand-fast"],["אַתֶּם","you-are"],["בַּאֲדֹנֵינוּ","in-the-Lord"],["׃",""]] },
  { num:"ט", words:[["כִּי","because"],["מַה־נָּשִׁיב","what-thanks-can-we-render"],["לֵאלֹהִים","to-God"],["לְהוֹדוֹת","to-give-thanks"],["לוֹ","him"],["בַּעֲבוּרְכֶם","for-your-sakes"],["עַל","upon"],["כׇּל־הַשִׂמְחָה","all-the-joy"],["אֲשֶׁר","that"],["שָׂמַחְנוּ","we-joy"],["עֲלֵיכֶם","over-you"],["לִפְנֵי","before"],["אֱלֹהֵינוּ","our-God"],["׃",""]] },
  { num:"י", words:[["לַיְלָה","night"],["וְיוֹמָם","and-by day"],["מִתְפַּלְּלִים","praying"],["אֲנַחְנוּ","we"],["בְּרָב־תַּחֲנוּנִים","exceedingly"],["לִרְאוֹת","to-see"],["אֶת־פְּנֵיכֶם","face-of-you"],["וּלְהַשְׁלִים","and-might-perfect"],["אֶת־מַחֲסֹרֵי","that-which-is-lacking-in"],["אֱמוּנַתְכֶם","your-faith"],["׃",""]] },
  { num:"יא", words:[["וְהָאֱלֹהִים","and-the-God"],["אָבִינוּ","our-father"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["הוּא","he"],["יְיַשֵּׁר","direct"],["אֶת־דַּרְכֵּנוּ","our-way"],["אֲלֵיכֶם","unto-you"],["׃",""]] },
  { num:"יב", words:[["וְאֶתְכֶם","and-you"],["יַרְבֶּה","make-you-increase"],["הָאָדוֹן","the-Lord"],["וְיַפְרֶה","and-abound"],["בְּאַהֲבַת","in-love-of"],["אִישׁ","a-man"],["אֶת־רֵעֵהוּ","one-another"],["וּבְאַהֲבַת","and-a-love-of"],["כׇּל־אָדָם","all-men"],["כַּאֲשֶׁר","when/as"],["אֲנַחְנוּ","we"],["אֹהֲבִים","love"],["אֶתְכֶם","you"],["׃",""]] },
  { num:"יג", words:[["לְחַזֵּק","to-strengthen"],["אֶת־לְבַבְכֶם","your-hearts"],["לִהְיוֹת","to-be"],["תָּמִים","unblameable"],["בִּקְדֻשָּׁה","in-holiness"],["לִפְנֵי","before"],["אֱלֹהֵינוּ","our-God"],["אָבִינוּ","our-father"],["בְּבוֹא","at-the-coming-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲדֹנֵינוּ","our-Lord"],["עִם־כׇּל־קְדשָׁיו","with-all-His-saints"],["׃",""]] },
];
renderVerseSet(_1th_ch3Verses, '1th-ch3-verses');

var _1th_ch4Verses = [
  { num:"א", words:[["וְעוֹד","and-again"],["נְבַקְשָׁה","we-beseech"],["מִכֶּם","from-you"],["אַחַי","my-brothers"],["וְנַזְהִיר","and-exhort"],["אֶתְכֶם","you"],["בַּאֲדֹנֵינוּ","by-the-Lord"],["יֵשׁוּעַ","Jesus"],["כִּי","because"],["כַּאֲשֶׁר","when/as"],["קִבַּלְתֶּם","received"],["מֵאִתָּנוּ","from-among-us"],["אֵיךְ","how"],["עֲלֵיכֶם","you-ought"],["לְהִתְהַלֵּךְ","to-walk"],["וְלִמְצֹא","and-to-find"],["חֵן","favor"],["בְּעֵינֵי","in-the-eyes-of"],["הָאֱלֹהִים","the-God"],["וְכַאֲשֶׁר","and-as"],["גַּם־הִתְהַלַּכְתֶּם","also-you-walk"],["כֵּן","thus"],["תּוֹסִיפוּ","you-would-abound"],["וְכֵן","and-so"],["תַּרְבּוּ","abound-more-and-more"],["עוֹד","any-more"],["׃",""]] },
  { num:"ב", words:[["כִּי","because"],["יְדַעְתֶּם","you-know"],["אֶת־הַמִּצְוֹת","the-commandments"],["אֲשֶׁר","which"],["נָתַנּוּ","we-gave"],["לָכֶם","to-you"],["בְּשֵׁם","by-name"],["הָאָדוֹן","the-Lord"],["יֵשׁוּעַ","Jesus"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["זֶה","this"],["רְצוֹן","the-will-of"],["הָאֱלֹהִים","the-God"],["קְדֻשַּׁתְכֶם","your-sanctification"],["לְהִתְרַחֵק","that-you-abstain"],["מִן־הַזְּנוּת","from-fornication"],["׃",""]] },
  { num:"ד", words:[["וְיֵדַּע","that-should-know"],["כׇּל־אִישׁ","every-man"],["מִכֶּם","from-you"],["לְהִשְׁתַּמֵּשׁ","to-use"],["בְּכִלְיוֹ","in-his-vessel"],["בִּקְדֻשָּׁה","in-holiness"],["וִיקָר","and-honour"],["׃",""]] },
  { num:"ה", words:[["וְלֹא־בְתַאֲוַת","and-not-in-lust-of"],["זִמָּה","of-concupiscence"],["כְּדֶרֶךְ","after-manner-of"],["הַגּוֹיִם","the-nations"],["אֲשֶׁר־אֵינָם","whose-they-are-not"],["יֹדְעִים","knowing"],["הָאֱלֹהִים","the-God"],["׃",""]] },
  { num:"ו", words:[["וְלֹא־יַעֲשֹׁק","that-no-man-go-beyond"],["אִישׁ","a-man"],["וְיוֹנֶה","and-defraud"],["אֶת־אָחִיו","his-brother"],["בְּמַשָׂא","in-any"],["וּמַתָּן","matter"],["כִּי־נוֹקֵם","because-an-avenger"],["הָאָדוֹן","the-Lord"],["עַל־כׇּל־זֹאת","upon-all-this"],["כַּאֲשֶׁר","when/as"],["כְּבָר","already"],["אָמַרְנוּ","we-have-forewarned"],["אֲלֵיכֶם","unto-you"],["וְהַעִידֹנוּ","and-testified"],["בָכֶם","in-you"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["לֹא־קָרָא","hath-not-called"],["אוֹתָנוּ","us"],["הָאֱלֹהִים","the-God"],["לַטֻּמְאָה","unto-uncleanness"],["כִּי","because"],["אִם־לַקְּדֻשָּׁה","but-to-the-holiness"],["׃",""]] },
  { num:"ח", words:[["עַל־כֵּן","therefore"],["הַבּוֹזֶה","he-that-despiseth"],["לֹא","not"],["בֶן־אָדָם","man"],["הוּא","he"],["בוֹזֶה","despiseth"],["כִּי","because"],["אִם־אֶת־הָאֱלֹהִים","if-the-God"],["אֲשֶׁר","which"],["גַּם־שָׂם","hath-also-given"],["בְּקִרְבֵּנוּ","unto-us"],["אֶת־רוּחַ","his-holy"],["קׇדְשׁוֹ","Spirit"],["׃",""]] },
  { num:"ט", words:[["וְעַל־אַהֲבַת","and-upon-love-of"],["הָאַחִים","the-brethren"],["אֵין־צֹרֶךְ","there-is-no-need"],["לִכְתֹּב","to-write"],["אֲלֵיכֶם","unto-you"],["הֲלֹא","do-not"],["אַף־אַתֶּם","yea-you-are"],["לְמוּדֵי","taught-of"],["יְהוָֹה","God"],["לְאַהֲבָה","to-love"],["אִישׁ","a-man"],["אֶת־רֵעֵהוּ","one-another"],["׃",""]] },
  { num:"י", words:[["וְגַם","and-also"],["עֲשִׂיתֶם","you-have-done"],["כֵּן","thus"],["לְכׇל־אֲחֵיכֶם","to-all-your-brethren"],["אֲשֶׁר","which"],["בְּכׇל־מַקְדּוֹנְיָא","in-all-Macedonia"],["אֲבָל","but"],["נְבַקְשָׁה","we-beseech"],["מִכֶּם","from-you"],["אַחַי","my-brothers"],["אֲשֶׁר","which"],["כֵּן","thus"],["תַּעֲשׂוּ","you-do"],["וְכֵן","and-so"],["תּוֹסִיפוּ","you-would-abound"],["׃",""]] },
  { num:"יא", words:[["וְתִשְׁתַּדְּלוּ","and-that-you-study"],["לָשֶׁבֶת","to-be-quiet"],["בְּנָחַת","in-quietness"],["וְתַעֲשׂוּ","and-perform"],["אִישׁ","a-man"],["מְלַאכְתּוֹ","his-own-business"],["בַּעֲמַל","and-to-work-with"],["יְדֵיכֶם","your-hands"],["כַּאֲשֶׁר","when/as"],["צִוִּינוּ","we-commanded"],["אֶתְכֶם","you"],["׃",""]] },
  { num:"יב", words:[["לְמַעַן","in-order-that"],["תִּתְהַלְּכוּ","you-may-walk"],["כְהֹגֶן","honestly"],["עִם־אֹתָם","with-them"],["שֶׁבַּחוּץ","that-are-outside"],["וְלֹא","and-not"],["תִּצְטָרֲכוּ","you-may-have-lack"],["לְאָדָם","to-man"],["׃",""]] },
  { num:"יג", words:[["וְעַל־דְּבַר","and-upon-the-word-of"],["הַיְשֵׁנִים","them-which-are-asleep"],["אֶחָי","brothers-my"],["לֹא־נְכַחֵד","we-would-not-have-you-ignorant"],["מִכֶּם","from-you"],["דָּבָר","a-word"],["לְמַעַן","in-order-that"],["לֹא","not"],["תֵּעָצְבוּ","you-sorrow"],["כַּאֲחֵרִים","even-as-others"],["אֲשֶׁר","which"],["אֵין־לָהֶם","there-is-no-to-them"],["תִּקְוָה","hope"],["׃",""]] },
  { num:"יד", words:[["כִּי","because"],["אִם־נַאֲמִין","if-we-believe"],["אֲשֶׁר־מֵת","that-died"],["יֵשׁוּעַ","Jesus"],["וַיֶּחִי","and-rose-again"],["כֵּן","thus"],["יָבִיא","shall-bring"],["הָאֱלֹהִים","the-God"],["גַּם","also"],["אֶת־הַיְשֵׁנִים","them-which-are-asleep"],["בְּיֵשׁוּעַ","in-Jesus"],["אִתּוֹ","with-him"],["׃",""]] },
  { num:"טו", words:[["כִּי","because"],["אֶת־זֹאת","this"],["נֹאמַר","we-say"],["לָכֶם","to-you"],["בִּדְבַר","by-the-word-of"],["יְהוָֹה","the-Lord"],["כִּי","because"],["אֲנַחְנוּ","we"],["הַחַיִּים","which-are-alive"],["הַנּוֹתָרִים","and-remain"],["עַד־בֹּא","until-come"],["הָאָדוֹן","the-Lord"],["לֹאֹ","not"],["נְקַדֵּם","shall-prevent"],["אֶת־הַיְשֵׁנִים","them-which-are-asleep"],["׃",""]] },
  { num:"טז", words:[["כִּי","because"],["הָאָדוֹן","the-Lord"],["הוּא","himself"],["יֵרֵד","shall-descend"],["מִן־הַשָּׁמַיִם","from-heaven"],["בִּתְרוּעָה","with-a-shout"],["בְּקוֹל","with-the-voice-of"],["שַׂר","the-chief-of"],["הַמַּלְאָכִים","the-angels"],["וּבְשׁוֹפַר","and-with-the-trump-of"],["אֱלֹהִים","God"],["וְאָז","and-then"],["יָקוּמוּ","shall-rise"],["רִאשׁוֹנָה","first"],["הַמֵּתִים","the-dead"],["בַּמָּשִׁיחַ","in-the-Messiah"],["׃",""]] },
  { num:"יז", words:[["אַחֲרֵי־כֵן","hereafter"],["אֲנַחְנוּ","we"],["הַחַיִּים","which-are-alive"],["הַנּוֹתָרִים","and-remain"],["נִלָּקַח","we-will-be-caught-up"],["אִתָּם","with-them"],["יַחְדָּו","together"],["בַּעֲנָנִים","in-the-clouds"],["לִקְרַאת","to-meet"],["הָאָדוֹן","the-Lord"],["לָאֲוִיר","to-the-air"],["וּבְכֵן","and-so"],["נִהְיֶה","shall-we-be"],["תָמִיד","continually"],["עִם־הָאָדוֹן","with-the-Lord"],["׃",""]] },
  { num:"יח", words:[["לָכֵן","therefore"],["נַחֲמוּ","comfort"],["זֶה","one"],["אֶת־זֶה","another"],["בַּדְּבָרִים","in-the-words"],["הָאֵלֶּה","these"],["׃",""]] },
];
renderVerseSet(_1th_ch4Verses, '1th-ch4-verses');

var _1th_ch5Verses = [
  { num:"א", words:[["וְעַל־דְּבַר","and-upon-the-word-of"],["הָעִתִּים","the-times"],["וְהַזְּמַנִּים","and-the-seasons"],["אֵין־צֹרֶךְ","there-is-no-need"],["לִכְתֹּב","to-write"],["אֲלֵיכֶם","unto-you"],["אֶחָי","brothers-my"],["׃",""]] },
  { num:"ב", words:[["הֲלֹא","do-not"],["אַף־אַתֶּם","yea-you-are"],["יְדַעְתֶּם","you-know"],["הֵיטֵב","perfectly"],["כִּי","because"],["יוֹם־יְהוָֹה","the-day-of-the-LORD"],["כַּגַּנָּב","like-the-thief"],["בַּלַּיְלָה","in-the-night"],["כֵּן","thus"],["יָבוֹא","shall-come"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["בְאָמְרָם","when-they-shall-say"],["שָׁלוֹם","peace"],["וְשַׁלְוָה","and-quietness"],["יָבֹא","shall-come"],["עֲלֵיהֶם","upon-them"],["הַשֶּׁבֶר","the-destruction"],["פִּתְאֹם","suddenly"],["כְּחֶבְלֵי","as-pains-of"],["יוֹלֵדָה","a-woman-with-child"],["וְלֹא","and-not"],["יוּכְלוּ","they-shall"],["הִמָּלֵט","escape"],["׃",""]] },
  { num:"ד", words:[["אֲבָל","but"],["אַתֶּם","you-are"],["אַחַי","my-brothers"],["לֹא","not"],["בַּחֹשֶׁךְ","in-the-darkness"],["אַתֶּם","you-are"],["שֶׁיַּשִׂיג","that-he-shall-overtake"],["אֶתְכֶם","you"],["הַיּוֹם","that-day"],["כַּגַּנָּב","like-the-thief"],["׃",""]] },
  { num:"ה", words:[["אַתֶּם","you-are"],["כֻּלְּכֶם","all-you"],["בְּנֵי","the-sons-of"],["הָאוֹר","the-light"],["וּבְנֵי","and-sons-of"],["הַיּוֹם","the-day"],["לֹא","not"],["בְנֵי־הַלַּיְלָה","sons-of-the-night"],["אֲנַחְנוּ","we"],["וְלֹא","and-not"],["בְּנֵי","the-sons-of"],["הַחֹשֶׁךְ","the-darkness"],["׃",""]] },
  { num:"ו", words:[["לָכֵן","therefore"],["אַל־נָא","let-us-not"],["נֵרָדֵם","sleep"],["כְּמוֹ","as-do"],["הָאֲחֵרִים","others"],["כִּי","because"],["אִם־נִשְׁקֹד","but-let-us-watch"],["וְנִהְיֶה","and-let-us-be"],["ְמְפֻכָּחִים","sober"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["הַנִּרְדָּמִים","they-that-sleep"],["נִרְדָּמִים","sleep"],["בַּלָּיְלָה","in-the-night"],["וְהַמִּשְׁתַּכְּרִים","and-they-that-be-drunken"],["מִשְׁתַּכְּרִים","are-drunken"],["בַּלָּיְלָה","by-the-night"],["׃",""]] },
  { num:"ח", words:[["וַאֲנַחְנוּ","and-we-are"],["בְּנֵי","the-sons-of"],["הַיּוֹם","the-day"],["נִתְּפַּכֵּחַ־נָּא","let-us-be-sober"],["וְנִלְבַּשׁ","putting-on"],["אֶת־שִׁרְיוֹן","the-breastplate-of"],["הָאֱמוּנָה","the-faith"],["וְהָאַהֲבָה","and-the-love"],["וְכַכּוֹבַע","and-for-a-helmet"],["אֶת־תִּקְוַת","the-hope-of"],["הַיְשׁוּעָה","the-salvation"],["׃",""]] },
  { num:"ט", words:[["יַעַן","because"],["אֲשֶׁר","which"],["לֹא־יְעָדָנוּ","hath-not-appointed-us"],["הָאֱלֹהִים","the-God"],["לְחָרוֹן","to-wrath"],["כִּי","because"],["לָרֶשֶׁת","to-obtain"],["אֶת־הַיְשׁוּעָה","the-salvation"],["עַל־יְדֵי","by-means-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"י", words:[["אֲשֶׁר","which"],["מֵת","died"],["בַּעֲדֵנוּ","for-us"],["לְמַעַן","in-order-that"],["נִחְיֶה","we-live"],["עִמּוֹ","with-him"],["יָחַד","together"],["אִם־נִשְׁקֹד","whether-we-wake"],["וְאִם־נִישָׁן","and-whether-we-sleep"],["׃",""]] },
  { num:"יא", words:[["עַל־כֵּן","therefore"],["נַחֲמוּ","comfort"],["זֶה","one"],["אֶת־זֶה","another"],["וּבְנוּ","and-edify"],["אִישׁ","a-man"],["אֶת־אָחִיו","one-another"],["כַּאֲשֶׁר","when/as"],["עֲשִׂיתֶם","you-have-done"],["׃",""]] },
  { num:"יב", words:[["וְהִנְנוּ","and-behold-us"],["מְבַקְשִׁים","beseech"],["מִכֶּם","from-you"],["אַחַי","my-brothers"],["לְהַכִּיר","to-know"],["אֶת־הָעֲמֵלִים","them-which-labour"],["בָּכֶם","in-you"],["וְאֵת","and"],["הַנִּצָּבִים","are-over-you"],["עֲלֵיכֶם","over-you"],["בִּדְבַר","in"],["הָאָדוֹן","the-Lord"],["וּמוֹכִיחִים","and-admonish"],["אֶתְכֶם","you"],["׃",""]] },
  { num:"יג", words:[["וְתִנְהֲגוּ־בָם","and-to-esteem-them"],["כָּבוֹד","glorious"],["גָּדוֹל","great"],["מְאֹד","exceedingly"],["בְּאַהֲבָה","in-love"],["לְמַעַן","in-order-that"],["פְּעֻלָּתָם","their-works-sake"],["וִיהִי","and-be-at"],["שָׁלוֹם","peace"],["בֵּינֵיכֶם","among-you"],["׃",""]] },
  { num:"יד", words:[["וְהִנְנוּ","and-behold-us"],["מַזְהִירִים","exhorting"],["אֶתְכֶם","you"],["אֶחָי","brothers-my"],["הוֹכִיחוּ","warn"],["אֶת־הַמְעַקְּשִׁים","the-unruly"],["דַּרְכֵיהֶם","their-ways"],["אַמְּצוּ","comfort"],["אֶת־רַכֵּי","are-tender-of"],["הַלֵּבָב","the-heart"],["תִּמְכוּ","support"],["אֶת־הַחַלָּשִׁים","the-weak"],["וְהַאֲרִיכוּ","and-be-patient"],["רוּחַ","in-spirit"],["אֶל־כׇּל־אָדָם","to-all-man"],["׃",""]] },
  { num:"טו", words:[["וּרְאוּ","and-see"],["פֶּן־יְשַׁלֵּם","that-none-render"],["אִישׁ","a-man"],["לְרֵעֵהוּ","unto-any"],["רָעָה","evil"],["תַּחַת","under"],["רָעָה","evil"],["כִּי","because"],["אִם־רִדְפוּ","but-ever-follow"],["בְּכׇל־עֵת","alway"],["אֶת־הַטּוֹב","that-which-is-good"],["הֵן","yea"],["לְאִישׁ","for-a-man"],["אִישׁ","a-man"],["מִכֶּם","from-you"],["הֵן","yea"],["לְכׇל־אָדָם","unto-all-men"],["׃",""]] },
  { num:"טז", words:[["שִׂמְחוּ","rejoice"],["בְּכׇל־עֵת","with-all-time"],["׃",""]] },
  { num:"יז", words:[["הִתְפַּלְּלוּ","pray!"],["כׇּל־הַיּוֹם","every-the-day"],["׃",""]] },
  { num:"יח", words:[["הוֹדוּ","give-thanks"],["עַל־הַכֹּל","in-every-thing"],["כִּי־זֶה","that-this"],["רְצוֹן","the-will-of"],["אֱלֹהִים","God"],["בַּמָּשִׁיחַ","in-the-Messiah"],["יֵשׁוּעַ","Jesus"],["אֲלֵיכֶם","concerning-you"],["׃",""]] },
  { num:"יט", words:[["אֶת־הָרוּחַ","the-Spirit"],["לֹא","not"],["תְּכַבּוּ","quench"],["׃",""]] },
  { num:"כ", words:[["אֶת־הַנְּבוּאוֹת","prophesyings"],["לֹא","not"],["תִמְאָסוּ","despise"],["׃",""]] },
  { num:"כא", words:[["בַּחֲנוּ","prove"],["כׇּל־דָּבָר","all-things"],["וּבַטּוֹב","and-the-good"],["אֱחֹזוּ","hold-fast"],["׃",""]] },
  { num:"כב", words:[["הִתְרַחֲקוּ","abstain"],["מִכׇּל־הַדּוֹמֶה","from-all-appearance"],["לָרָע","of-evil"],["׃",""]] },
  { num:"כג", words:[["וֵאלֹהֵי","and-God-of"],["הַשָּׁלוֹם","the-peace"],["הוּא","he"],["יְקַדֵּשׁ","sanctify"],["אֶתְכֶם","you"],["בִּקְדֻשָּׁה","in-holiness"],["שְׁלֵמָה","complete/perfect"],["וְכׇל־רוּחֲכֶם","and-your-whole-spirit"],["וְנַפְשְׁכֶם","and-soul"],["וְגוּפְכֶם","and-your-body"],["יִשָּׁמֵר","be-preserved"],["תָּמִים","blameless"],["בְּבוֹא","unto-the-coming-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"כד", words:[["נֶאֱמָן","faithful"],["הוּא","he"],["הַקּוֹרֵא","he-that-calleth"],["אֶתְכֶם","you"],["אֲשֶׁר","which"],["גַּם־יַעֲשֶׂה","who-also-will-do-it"],["׃",""]] },
  { num:"כה", words:[["אַחַי","my-brothers"],["הִתְפַּלֲלוּ","pray!"],["בַעֲדֵנוּ","for-us"],["׃",""]] },
  { num:"כו", words:[["שַׁאֲלוּ","salute"],["לִשְׁלוֹם","for-the-welfare-of"],["כׇּל־הָאַחִים","all-the-brethren"],["בַּנְּשִׁיקָה","in-the-kiss"],["הַקְּדשָׁה","the-holiness"],["׃",""]] },
  { num:"כז", words:[["הִנְנִי","behold-I"],["מַשְׁבִּיעֲכֶם","I-charge-you"],["בָּאָדוֹן","in-the-Lord"],["אֲשֶׁר","which"],["תִּקָּרֵא","be-read"],["הָאִגֶּרֶת","the-epistle"],["הַזֹּאת","this"],["בְּאׇזְנֵי","in-the-ears-of"],["כׇּל־הָאַחִים","all-the-brethren"],["הַקְּדוֹשִׁים","the-holy"],["׃",""]] },
  { num:"כח", words:[["חֶסֶד","grace"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲדֹנֵינוּ","our-Lord"],["עִמָּכֶם","with-you"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(_1th_ch5Verses, '1th-ch5-verses');

})();
