// nt_verses/2jn.js — 2 John verse data
(function() {
var _2jn_ch1Verses = [
  { num:"א", words:[["הַזָּקֵן","the-elder"],["אֶל־הַגְּבִירָה","to-the-queen"],["הַבְּחִירָה","the-choice"],["וְאֶל־בָּנֶיהָ","and-sons-her"],["אֲשֶׁר","which"],["אֲנִי","I"],["אֹהֵב","loves"],["אֹתָם","them"],["בֶּאֱמֶת","in-truth"],["וְלֹא־אֲנִי","and-not-I"],["לְבַדִּי","alone"],["כִּי","because"],["אִם־גַּם","if-also"],["כָּל־יֹדְעֵי","all-knowing"],["הָאֱמֶת","the-true"],["׃",""]] },
  { num:"ב", words:[["לְמַעַן","in-order-that"],["הָאֱמֶת","the-true"],["הָעֹמֶדֶת","the-standing(f)"],["בְּקִרְבֵּנוּ","among-us"],["וְגַם־תִּהְיֶה","and-also-shall-be"],["עִמָּנוּ","with-us"],["לְעוֹלָם","forever"],["׃",""]] },
  { num:"ג", words:[["יְהִי","let-this-be"],["עִמָּנוּ","with-us"],["חֶסֶד","grace"],["וְרַחֲמִים","and-compassion"],["וְשָׁלוֹם","and-peace"],["מֵאֵת","from"],["הָאֱלֹהִים","the-God"],["אָבִינוּ","our-father"],["וּמֵאֵת","and-from-with"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["בֶּן־הָאָב","son-of-the-Father"],["בֶּאֱמֶת","in-truth"],["וּבְאַהֲבָה","and-in-love"],["׃",""]] },
  { num:"ד", words:[["שָׂמַחְתִּי","I-rejoiced"],["מְאֹד","exceedingly"],["כִּי־מָצָאתִי","because-I-found"],["מִבָּנַיִךְ","from-your-children"],["מִתְהַלְּכִים","walking"],["בָּאֱמֶת","in-truth"],["כַּמִּצְוָה","as-the-commandment"],["אֲשֶׁר","which"],["קִבַּלְנוּ","we-have-received"],["מֵאֵת","from"],["הָאָב","the-Father"],["׃",""]] },
  { num:"ה", words:[["וְעַתָּה","and-now"],["מְבַקֵּשׁ","desire"],["אֲנִי","I"],["מִמֵּךְ","from-you"],["הַגְּבִירָה","the-queen"],["וְלֹא","and-not"],["כְּכֹתֵב","as-writing"],["אֵלַיִךְ","into-you"],["מִצְוָה","commandment"],["חֲדָשָׁה","new"],["כִּי","because"],["אִם־אֵת","if-[ACC]"],["אֲשֶׁר","which"],["הָיְתָה־לָּנוּ","was-we"],["מֵרֹאשׁ","from-the-beginning"],["לְאַהֲבָה","to-love"],["אִישׁ","a-man"],["אֶת־רֵעֵהוּ","[ACC]-another"],["׃",""]] },
  { num:"ו", words:[["וְזֹאת","and-this"],["הִיא","she"],["הָאַהֲבָה","the-love"],["אֲשֶׁר","which"],["נִתְהַלֵּךְ","we-walk"],["בְּמִצְוֹתָיו","in-His-commandments"],["זֹאת","this"],["הִיא","she"],["הַמִּצְוָה","the-commandment"],["אֲשֶׁר","which"],["שְׁמַעְתֶּם","you-have-heard"],["מֵרֹאשׁ","from-the-beginning"],["לְהִתְהַלֵּךְ","to-walk"],["בָּהּ","in-it(f)"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["מַתְעִים","cause-them-to-err"],["רַבִּים","many"],["בָּאוּ","came"],["לָעוֹלָם","into-the-world"],["אֲשֶׁר","which"],["אֵינָם","they-are-not"],["מוֹדִים","confessing"],["בְּיֵשׁוּעַ","in-Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["הַבָּא","that-comes"],["בַבָּשָׂר","in-the-flesh"],["זֶה","this"],["הוּא","he"],["הַמַּתְעֶה","the-one-who-deceived"],["וְשׂוֹטֵן","and-adversary-of"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ח", words:[["הִזָּהֲרוּ","being-warned"],["פֶּן־תֹּאבַד","lest-you-will-perished"],["מִמֶּנּוּ","from-him"],["פְּעֻלָּתֵנוּ","the-working-of-us"],["כִּי","because"],["אִם־נִקַּח","if-let-us-take"],["מַשְׂכֻּרְתֵּנוּ","our-reward"],["שְׁלֵמָה","complete/perfect"],["׃",""]] },
  { num:"ט", words:[["כָּל־הָעֹבֵר","all-the-one who passes over"],["עַל־תּוֹרַת","concerning-the-doctrine-of"],["הַמָּשִׁיחַ","the-Messiah"],["וְאֵינֶנּוּ","and-it-is-not"],["עֹמֵד","standing"],["בָּהּ","in-it(f)"],["אֵין","there-is-no"],["לוֹ","him"],["אֱלֹהִים","God"],["וְהָעֹמֵד","and-the-who-stands"],["בְּתוֹרַת","the-tradition-of"],["הַמָּשִׁיחַ","the-Messiah"],["יֶשׁ־לוֹ","has-him"],["גַּם־הָאָב","also-the-Father"],["גַּם־הַבֵּן","also-the-Son"],["׃",""]] },
  { num:"י", words:[["כָּל־הַבָּא","all-that-comes"],["אֲלֵיכֶם","unto-you"],["וְלֹא","and-not"],["יָבִיא","shall-bring"],["אֶת־הַתּוֹרָה","[ACC]-the-law"],["הַזֹּאת","this"],["לֹא־תַאַסְפוּ","do-not-receive"],["אֹתוֹ","him"],["הַבַּיְתָה","the-home"],["וְלֹא","and-not"],["תִשְׁאֲלוּ־לוֹ","ye-would-ask-him"],["לְשָׁלוֹם","for-peace"],["׃",""]] },
  { num:"יא", words:[["כִּי","because"],["הַשֹּׁאֵל","the-enquire"],["בִּשְׁלוֹמוֹ","in-his-peace"],["חָבֵר","am a companion"],["הוּא","he"],["לְמַעֲשָׂיו","to-His-works"],["הָרָעִים","evil"],["׃",""]] },
  { num:"יב", words:[["הַרְבֵּה","much"],["יֶשׁ־לִי","has-to-me"],["לִכְתֹּב","to-write"],["אֲלֵיכֶם","unto-you"],["וְלֹא","and-not"],["חָפַצְתִּי","I-desire"],["בִּנְיָר","in-light"],["וּבִדְיוֹ","and-with-ink"],["כִּי","because"],["אִם־אֲקַוֶּה","if-I-hope"],["לָבוֹא","to-come"],["אֲלֵיכֶם","unto-you"],["וּלְדַבֵּר","and-to-speak"],["פֶּה","mouth"],["אֶל־פֶּה","to-mouth"],["לְמַעַן","in-order-that"],["תִּהְיֶה","shall-be"],["שִׂמְחָתֵנוּ","joy-of-us"],["שְׁלֵמָה","complete/perfect"],["׃",""]] },
  { num:"יג", words:[["בְּנֵי","the-sons-of"],["אֲחוֹתֵךְ","sister-your"],["הַבְּחִירָה","the-choice"],["שֹׁאֲלִים","asking"],["לִשְׁלוֹמֵךְ","to-your-peace"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(_2jn_ch1Verses, '2jn-ch1-verses');

})();
