// nt_verses/2jn.js — 2 John verse data
(function() {
var _2jn_ch1Verses = [
  { num:"א", words:[["הַזָּקֵן","the-elder"],["אֶל־הַגְּבִירָה","unto-the-lady"],["הַבְּחִירָה","elect"],["וְאֶל־בָּנֶיהָ","and-her-children"],["אֲשֶׁר","whom"],["אֲנִי","I"],["אֹהֵב","love"],["אֹתָם","them"],["בֶּאֱמֶת","in-the-truth"],["וְלֹא־אֲנִי","and-not-I"],["לְבַדִּי","only"],["כִּי","but"],["אִם־גַּם","also"],["כׇּל־יֹדְעֵי","all-they-that-have-known"],["הָאֱמֶת","the-truth"],["׃",""]] },
  { num:"ב", words:[["לְמַעַן","for-the-sake-of"],["הָאֱמֶת","the-truth"],["הָעֹמֶדֶת","which-dwelleth"],["בְּקִרְבֵּנוּ","in-us"],["וְגַם־תִּהְיֶה","and-shall-be"],["עִמָּנוּ","with-us"],["לְעוֹלָם","for-ever"],["׃",""]] },
  { num:"ג", words:[["יְהִי","be"],["עִמָּנוּ","with-us"],["חֶסֶד","grace"],["וְרַחֲמִים","mercy"],["וְשָׁלוֹם","and-peace"],["מֵאֵת","from"],["הָאֱלֹהִים","God"],["אָבִינוּ","the-Father"],["וּמֵאֵת","and-from"],["אֲדֹנֵינוּ","the-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["בֶּן־הָאָב","the-Son-of-the-Father"],["בֶּאֱמֶת","in-truth"],["וּבְאַהֲבָה","and-love"],["׃",""]] },
  { num:"ד", words:[["שָׂמַחְתִּי","I-rejoiced"],["מְאֹד","greatly"],["כִּי־מָצָאתִי","that-I-found"],["מִבָּנַיִךְ","of-your-children"],["מִתְהַלְּכִים","walking"],["בָּאֱמֶת","in-truth"],["כַּמִּצְוָה","as-the-commandment"],["אֲשֶׁר","which"],["קִבַּלְנוּ","we-have-received"],["מֵאֵת","from"],["הָאָב","the-Father"],["׃",""]] },
  { num:"ה", words:[["וְעַתָּה","and-now"],["מְבַקֵּשׁ","beseech"],["אֲנִי","I"],["מִמֵּךְ","you"],["הַגְּבִירָה","lady"],["וְלֹא","not"],["כְּכֹתֵב","as-though-I-wrote"],["אֵלַיִךְ","unto-you"],["מִצְוָה","a-commandment"],["חֲדָשָׁה","new"],["כִּי","but"],["אִם־אֵת","that"],["אֲשֶׁר","which"],["הָיְתָה־לָּנוּ","we-had"],["מֵרֹאשׁ","from-the-beginning"],["לְאַהֲבָה","that-we-love"],["אִישׁ","one"],["אֶת־רֵעֵהוּ","another"],["׃",""]] },
  { num:"ו", words:[["וְזֹאת","and-this"],["הִיא","is"],["הָאַהֲבָה","love"],["אֲשֶׁר","that"],["נִתְהַלֵּךְ","we-walk"],["בְּמִצְוֹתָיו","after-his-commandments"],["זֹאת","this"],["הִיא","is"],["הַמִּצְוָה","the-commandment"],["אֲשֶׁר","that"],["שְׁמַעְתֶּם","you-have-heard"],["מֵרֹאשׁ","from-the-beginning"],["לְהִתְהַלֵּךְ","you-should-walk"],["בָּהּ","in-it"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["מַתְעִים","deceivers"],["רַבִּים","many"],["בָּאוּ","are-entered"],["לָעוֹלָם","into-the-world"],["אֲשֶׁר","who"],["אֵינָם","not"],["מוֹדִים","confess"],["בְּיֵשׁוּעַ","that-Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["הַבָּא","is-come"],["בַבָּשָׂר","in-the-flesh"],["זֶה","this"],["הוּא","is"],["הַמַּתְעֶה","a-deceiver"],["וְשׂוֹטֵן","and-the-adversary-of"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ח", words:[["הִזָּהֲרוּ","look-to-yourselves"],["פֶּן־תֹּאבַד","lest-be-lost"],["מִמֶּנּוּ","of-it"],["פְּעֻלָּתֵנוּ","the-things-we-have-wrought"],["כִּי","but"],["אִם־נִקַּח","that-we-receive"],["מַשְׂכֻּרְתֵּנוּ","our-reward"],["שְׁלֵמָה","full"],["׃",""]] },
  { num:"ט", words:[["כׇּל־הָעֹבֵר","whosoever-transgresseth"],["עַל־תּוֹרַת","the-doctrine-of"],["הַמָּשִׁיחַ","the-Messiah"],["וְאֵינֶנּוּ","and...not"],["עֹמֵד","abideth"],["בָּהּ","in-it"],["אֵין","not"],["לוֹ","he-hath"],["אֱלֹהִים","God"],["וְהָעֹמֵד","he-that-abideth"],["בְּתוֹרַת","in-the-doctrine-of"],["הַמָּשִׁיחַ","the-Messiah"],["יֶשׁ־לוֹ","he-hath"],["גַּם־הָאָב","both-the-Father"],["גַּם־הַבֵּן","and-the-Son"],["׃",""]] },
  { num:"י", words:[["כׇּל־הַבָּא","if-there-come-any"],["אֲלֵיכֶם","unto-you"],["וְלֹא","and-not"],["יָבִיא","bring"],["אֶת־הַתּוֹרָה","the-doctrine"],["הַזֹּאת","this"],["לֹא־תַאַסְפוּ","receive-not"],["אֹתוֹ","him"],["הַבַּיְתָה","into-your-house"],["וְלֹא","neither"],["תִשְׁאֲלוּ־לוֹ","bid-him"],["לְשָׁלוֹם","God-speed"],["׃",""]] },
  { num:"יא", words:[["כִּי","for"],["הַשֹּׁאֵל","he-that-biddeth"],["בִּשְׁלוֹמוֹ","him-God-speed"],["חָבֵר","partaker"],["הוּא","is"],["לְמַעֲשָׂיו","of-his-deeds"],["הָרָעִים","evil"],["׃",""]] },
  { num:"יב", words:[["הַרְבֵּה","many-things"],["יֶשׁ־לִי","I-have"],["לִכְתֹּב","to-write"],["אֲלֵיכֶם","unto-you"],["וְלֹא","and-not"],["חָפַצְתִּי","I-would"],["בִּנְיָר","with-paper"],["וּבִדְיוֹ","and-ink"],["כִּי","but"],["אִם־אֲקַוֶּה","I-trust"],["לָבוֹא","to-come"],["אֲלֵיכֶם","unto-you"],["וּלְדַבֵּר","and-speak"],["פֶּה","face"],["אֶל־פֶּה","to-face"],["לְמַעַן","that"],["תִּהְיֶה","may-be"],["שִׂמְחָתֵנוּ","our-joy"],["שְׁלֵמָה","full"],["׃",""]] },
  { num:"יג", words:[["בְּנֵי","the-children-of"],["אֲחוֹתֵךְ","your-sister"],["הַבְּחִירָה","elect"],["שֹׁאֲלִים","greet"],["לִשְׁלוֹמֵךְ","you"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(_2jn_ch1Verses, '2jn-ch1-verses');

})();
