// nt_verses/2pe.js — 2 Peter verse data
(function() {
var _2pe_ch1Verses = [
  { num:"א", words:[["שִׁמְעוֹן","Simon"],["פֶּטְרוֹס","Peter"],["עֶבֶד","the-servant-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["וּשְׁלִיחוֹ","and-apostle-of-his"],["אֶל־אֲשֶׁר","to-them-that"],["קִבְּלוּ","have-obtained"],["אֱמוּנָה","faith"],["יְקָרָה","precious"],["כְּשֶׁלָּנוּ","like-with-us"],["בְּצִדְקַת","by-the-righteousness-of"],["אֱלֹהֵינוּ","our-God"],["וּמוֹשִׁיעֵנוּ","and-our-Savior"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ב", words:[["חֶסֶד","grace"],["וְשָׁלוֹם","and-peace"],["יִהְיוּ","shall-be"],["לָכֶם","to-you"],["לְמַכְבִּיר","be-multiplied"],["בְּדַעַת","through-the-knowledge-of"],["הָאֱלֹהִים","God"],["וְיֵשׁוּעַ","and-Jesus"],["אֲדֹנֵינוּ","our-Lord"],["׃",""]] },
  { num:"ג", words:[["בַּאֲשֶׁר","according-as"],["גְּבוּרָתוֹ","his-power"],["הָאֱלֹהִית","divine"],["נָתְנָה","hath-given"],["לָּנוּ","unto-us"],["אֵת־כׇּל־צָרְכֵינוּ","all-things-that-pertain"],["לַחַיִּים","unto-life"],["וְלַחֲסִידוּת","and-godliness"],["עַל־יְדֵי","through"],["דַעַת","the-knowledge-of"],["הַקּוֹרֵא","him-that-hath-called"],["אֹתָנוּ","us"],["בִּכְבוֹדוֹ","to-his-glory"],["וְחֵילוֹ","and-virtue"],["׃",""]] },
  { num:"ד", words:[["אֲשֶׁר","which"],["בָּהֶם","by-them"],["נָתַן־לָנוּ","are-given-unto-us"],["הַבְטָחוֹת","promises"],["גְּדֹלוֹת","great"],["מְאֹד","exceeding"],["וִיקָרוֹת","and-precious"],["לְמַעַן","that"],["תִּקְחוּ","you-might-be-partakers"],["עַל־יָדָן","by-these"],["חֵלֶק","a-part"],["בְּטֶבַע","of-the-nature-of"],["אֱלֹהִים","God"],["לְהִמָּלֵט","having-escaped"],["מִכִּלְיוֹן","the-corruption-of"],["הַתַּאֲוָה","the-lust"],["אֲשֶׁר","that-is"],["בָּעוֹלָם","in-the-world"],["׃",""]] },
  { num:"ה", words:[["בַּעֲבוּר","beside"],["זֹאת","this"],["שִׁקְדוּ","giving-all-diligence"],["לְהוֹסִיף","add"],["עַל־אֱמוּנַתְכֶם","to-your-faith"],["אֶת־מַעֲשֵׂה","the-doing-of"],["הַצְּדָקָה","virtue"],["וְעַל","and-to"],["מַעֲשֵׂה","the-doing-of"],["הַצְּדָקָה","virtue"],["אֶת־הַדָּעַת","knowledge"],["׃",""]] },
  { num:"ו", words:[["וְעַל־הַדַּעַת","and-to-knowledge"],["אֶת־הַפְּרִישׁוּת","temperance"],["וְעַל־הַפְּרִישׁוּת","and-to-temperance"],["אֶת־הַסַּבְלָנוּת","patience"],["וְעַל־הַסַּבְלָנוּת","and-to-patience"],["אֶת־הַחֲסִידוּת","godliness"],["׃",""]] },
  { num:"ז", words:[["וְעַל־הַחֲסִידוּת","and-to-godliness"],["אֶת־הָאַחֲוָה","brotherly-kindness"],["וְעַל־הָאַחֲוָה","and-to-brotherly-kindness"],["אֶת־הָאַהֲבָה","charity"],["׃",""]] },
  { num:"ח", words:[["כִּי","because"],["אִם־אֵלֶּה","if-these-things"],["יִמָּצְאוּ","be"],["וְיִרְבּוּ","and-abound"],["בָכֶם","in-you"],["לֹא־יִתְּנוּ","they-make-neither"],["אֶתְכֶם","you"],["לִהְיוֹת","be"],["מִתְעַצְּלִים","barren"],["וּבְטֵלִים","nor-unfruitful"],["מֵעֲשׂוֹת","from-bringing-forth"],["פְּרִי","fruit"],["לְדַעַת","in-the-knowledge-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ט", words:[["כִּי","because"],["הָאִישׁ","he"],["אֲשֶׁר","that"],["אֵין־אֵלֶּה","lacketh-these"],["לּוֹ","things"],["עִוֵּר","blind"],["הוּא","is"],["רְפֵה","dim-of"],["עֵינַיִם","eyes"],["וְשָׁכֵחַ","and-hath-forgotten"],["אֶת־טׇהֳרָתוֹ","his-purging"],["מֵחַטֹּאתָיו","from-his-sins"],["הָרִאשֹׁנוֹת","old"],["׃",""]] },
  { num:"י", words:[["לָכֵן","wherefore"],["אַחַי","brethren"],["הוֹסִיפוּ","the-rather"],["וְשִׁקְדוּ","give-diligence"],["לְחַזֵּק","to-make-sure"],["אֶת־קְרִיאַתְכֶם","your-calling"],["וּבְחִירַתְכֶם","and-election"],["בְּמַעֲשִׂים","by-works"],["טוֹבִים","good"],["כִּי","for"],["אִם","if"],["כֵּן","so"],["תַּעֲשׂוֹּ","you-do"],["לֹא","never"],["תִכָּשֵׁלוּ","you-shall-fall"],["׃",""]] },
  { num:"יא", words:[["כִּי־כֵן","for-so"],["יִפָּתַח","shall-be-opened"],["לִפְנֵיכֶם","unto-you"],["לָרְוָחָה","abundantly"],["מְבוֹא","an-entrance"],["מַלְכוּת","into-the-kingdom-of"],["עוֹלָם","the-everlasting"],["אֲשֶׁר","which-is"],["לַאֲדֹנֵינוּ","of-our-Lord"],["וּמוֹשִׁיעֵנוּ","and-Saviour"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"יב", words:[["עַל־כֵּן","wherefore"],["לֹא","not"],["אֶחְדַּל","I-will-be-negligent"],["לְהַזְכִּירְכֶם","to-put-you-in-remembrance"],["עַל־אֵלֶּה","of-these-things"],["בְּכׇל־עֵת","always"],["אַף־כִּי","though"],["יְדַעְתֶּם","you-know"],["אֶת־אֲמִתֵּנוּ","our-truth"],["זוּ","this"],["וְהִתְכּוֹנַנְתֶּם","and-are-established"],["בָּהּ","in-it"],["׃",""]] },
  { num:"יג", words:[["וְנָכוֹן","yea-it-is-meet"],["בְּעֵינַי","in-my-eyes"],["לְהַזְכִּיר","to-put-in-remembrance"],["וּלְהָעִיר","and-to-stir-up"],["אֶתְכֶם","you"],["כׇּל־יְמֵי","as-long-as"],["הֱיוֹתִי","I-am"],["בַּמִּשְׁכָּן","in-the-tabernacle"],["הַזֶּה","this"],["׃",""]] },
  { num:"יד", words:[["מִדַּעְתִּי","knowing"],["כִּי","that"],["מַהֵר","shortly"],["יֶעְתַּק","must-be-removed"],["מִשְׁכָּנִי","my-tabernacle"],["וְכֵן","even-as"],["גִּלָּה־לִי","hath-shewed-me"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"טו", words:[["וְאֶשְׁקֹד","and-I-will-endeavour"],["לִהְיוֹת","that-may-be"],["לָכֶם","for-you"],["תָּמִיד","always"],["זִכְרוֹן","a-remembrance-of"],["הַדְּבָרִים","the-things"],["הָאֵלֶּה","these"],["גַּם־אַחֲרֵי","also-after"],["פְטִירָתִי","my-decease"],["׃",""]] },
  { num:"טז", words:[["כִּי","because"],["לֹא","not"],["הָלַכְנוּ","we-have-followed"],["אַחֲרֵי","after"],["הַגָּדוֹת","fables"],["מְחֻכָּמוֹת","cunningly-devised"],["בְּהוֹדִיעֵנוּ","when-we-made-known"],["אֶתְכֶם","unto-you"],["גְּבוּרַת","the-power-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["וּבֹאוֹ","and-his-coming"],["כִּי","but"],["עֵינֵינוּ","our-eyes"],["הָיוּ","were"],["הָרֹאוֹת","the-witnesses-of"],["אֶת־גְּדֻלָּתוֹ","his-majesty"],["׃",""]] },
  { num:"יז", words:[["כִּי","because"],["נָשָׂא","he-received"],["יְקָר","honour"],["וְכָבוֹד","and-glory"],["מֵאֵת","from"],["אֱלֹהִים","God"],["הָאָב","the-Father"],["כְּבֹא","when-came"],["אֵלָיו","to-him"],["קוֹל","a-voice"],["מִלִּפְנֵי","from"],["הַדְרַת","the-excellent"],["כְּבוֹדוֹ","glory"],["לֵאמֹר","saying"],["זֶה","this"],["בְּנִי","is-my-Son"],["יְדִידִי","beloved"],["רָצְתָה","is-well-pleased"],["נַפְשִׁי","my-soul"],["בּוֹ","in-him"],["׃",""]] },
  { num:"יח", words:[["וְאֶת־הַקּוֹל","and-this-voice"],["הַהוּא","that"],["שָׁמַעְנוּ","we-heard"],["בְאׇזְנֵינוּ","in-our-ears"],["יֹצֵא","which-came"],["מִן־הַשָּׁמָיִם","from-heaven"],["בִּהְיוֹתֵנוּ","when-we-were"],["עִמּוֹ","with-him"],["בְּהַר","in-the-mount-of"],["הַקֹּדֶשׁ","holiness"],["׃",""]] },
  { num:"יט", words:[["וּדְבַר","and-the-word-of"],["הַנְּבוּאָה","prophecy"],["יוֹתֵר","more"],["קַיָּם","sure"],["אִתָּנוּ","with-us"],["וַהֲטִיבֹתֶם","you-do-well"],["עֲשׂוֹת","to-do"],["אֲשֶׁר","whereunto"],["שַׁתֶּם","you-take-heed"],["לִבְּכֶם","your-hearts"],["אֵלָיו","unto-it"],["כְּנֵר","as-a-light"],["מֵאִיר","that-shineth"],["בִּמְקוֹם","in-a-place-of"],["אֹפֶל","darkness"],["עַד־כִּי","until"],["יִבָּקַע","dawn"],["אוֹר","the-light-of"],["הַיּוֹם","the-day"],["וְזָרַח","and-arise"],["כּוֹכַב","the-star-of"],["הַנֹּגַהּ","the-brightness"],["בִּלְבַבְכֶם","in-your-hearts"],["׃",""]] },
  { num:"כ", words:[["וְזֹאת","this"],["תֵּדְעוּ","know"],["רִאשׁוֹנָה","first"],["אֲשֶׁר","that"],["כׇּל־נְבוּאַת","every-prophecy-of"],["הַמִּקְרָא","the-scripture"],["אֵינֶנָּה","is-not"],["כְּפִי","of-any"],["פִתְרוֹן","interpretation-of"],["אָדָם","a-man"],["מִלִּבּוֹ","from-his-own-heart"],["׃",""]] },
  { num:"כא", words:[["כִּי","because"],["מֵעוֹלָם","in-old-time"],["לֹא־יָצְאָה","came-not"],["נְבוּאָה","the-prophecy"],["בִּרְצוֹן","by-the-will-of"],["הָאָדָם","man"],["כִּי","but"],["אַנְשֵׁי","men-of"],["אֱלֹהִים","God"],["הַקְּדוֹשִׁים","holy"],["דִּבְּרוּ","spake"],["כַּאֲשֶׁר","as"],["נְשָׂאָם","they-were-moved"],["רוּחַ","the-Holy"],["הַקֹּדֶשׁ","Spirit"],["׃",""]] },
];
renderVerseSet(_2pe_ch1Verses, '2pe-ch1-verses');

var _2pe_ch2Verses = [
  { num:"א", words:[["וְגַם־נְבִיאֵי","and-also-prophets-of"],["שֶׁקֶר","false"],["הָיוּ","were"],["בָעָם","among-the-people"],["כַּאֲשֶׁר","even-as"],["יִהְיוּ","there-shall-be"],["מוֹרֵי","teachers-of"],["שֶׁקֶר","false"],["גַּם־בָּכֶם","also-among-you"],["אֲשֶׁר","who"],["יַכְנִיסוּ","shall-bring-in"],["כִּתּוֹת","heresies"],["מַשְׁחִיתוֹת","damnable"],["וִיכַחֲשׁוּ","denying"],["בַּמֹּשֵׁל","the-Lord"],["אֲשֶׁר","that"],["קָנָם","bought-them"],["וְיָבִיאוּ","and-bring"],["עַל־נַפְשָׁם","upon-themselves"],["כִּלָּיוֹן","destruction"],["פִּתְאֹם","swift"],["׃",""]] },
  { num:"ב", words:[["וְרַבִּים","and-many"],["יֵלְכוּ","shall-follow"],["אַחֲרֵי","after"],["תוֹעֲבוֹתָם","their-pernicious-ways"],["וּבַעֲבוּרָם","by-reason-of-whom"],["יֻתַּן","shall-be-given"],["דֶּרֶךְ","the-way-of"],["הָאֱמֶת","truth"],["לְגִדּוּפִים","to-evil-speaking"],["׃",""]] },
  { num:"ג", words:[["וּבְדִבְרֵי","and-through-words-of"],["בִדּוּי","feigned"],["יַעֲשׂוֹּ","shall-they-make"],["אֶתְכֶם","of-you"],["לְמִסְחָר","merchandise"],["לָהֶם","for-themselves"],["לְמַעַן","through"],["בְּצֹעַ","to-gain"],["בָּצַע","gain"],["אֲשֶׁר","whose"],["מִשְׁפָּטָם","judgment"],["מֵאָז","of-a-long-time"],["לֹא","not"],["יִתְמַהְמַהּ","lingereth"],["וְשִׁבְרָם","and-their-damnation"],["לֹא","not"],["יָנוּם","slumbereth"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["לֹא־חָס","spared-not"],["אֱלֹהִים","God"],["עַל־הַמַּלְאָכִים","the-angels"],["אֲשֶׁר","that"],["חָטְאוּ","sinned"],["כִּי","but"],["אִם־הוֹרִידָם","cast-them-down"],["לְקִצְבֵי","to-the-depths-of"],["הָרִים","the-mountains"],["וַיַסְגִּירֵם","and-delivered-them"],["בְּכַבְלֵי","into-chains-of"],["אֹפֶל","darkness"],["לְשָׁמְרָם","to-be-reserved"],["לַמִּשְׁפָּט","unto-judgment"],["׃",""]] },
  { num:"ה", words:[["וְגַם־עַל־הַדּוֹרוֹת","and-also-the-generations"],["הָרִאשֹׁנִים","of-old"],["לֹא","not"],["חָס","spared"],["וַיִּשְׁמֹר","but-saved"],["רַק","only"],["אֶת־נֹחַ","Noah"],["קֹרֵא","a-preacher-of"],["הַצֶּדֶק","righteousness"],["וְשִׁבְעָה","and-seven"],["עִמּוֹ","with-him"],["בַּהֲבִיאוֹ","bringing"],["אֶת־הַמַּבּוּל","the-flood"],["עַל־דּוֹר","upon-the-world-of"],["הָרְשָׁעִים","the-ungodly"],["׃",""]] },
  { num:"ו", words:[["וְאֶת־עָרֵי","and-the-cities-of"],["סְדוֹם","Sodom"],["וַעֲמֹרָה","and-Gomorrha"],["הָפַךְ","turned"],["לָאֵפֶר","into-ashes"],["וְדָנָם","condemned-them"],["בְּמַהְפֵּכָה","with-an-overthrow"],["וַיְשִׂימֵם","making-them"],["לְמָשָׁל","an-ensample"],["לַאֲשֶׁר","unto-those-that"],["עֲתִידִים","should"],["לַעֲשׂוֹת","commit"],["זִמָּה","ungodliness"],["׃",""]] },
  { num:"ז", words:[["וַיַּצֵּל","and-delivered"],["אֶת־לוֹט","Lot"],["הַצַּדִּיק","the-just"],["אֲשֶׁר","which"],["הֶלְאוּהוּ","vexed-him"],["אַנְשֵׁי","the-men-of"],["בְלִיַעַל","Belial"],["הָהֵם","those"],["בְּדַרְכֵי","with-the-ways-of"],["זִמָּתָם","their-lasciviousness"],["׃",""]] },
  { num:"ח", words:[["כִּי","because"],["הַצַּדִּיק","righteous-man"],["הַזֶּה","that"],["יָשַׁב","dwelling"],["בְּתוֹכָם","among-them"],["וְהוּא","and-he"],["רֹאֶה","seeing"],["אֹתָם","them"],["וְשֹׁמֵעַ","and-hearing"],["וְנַפְשׁוֹ","and-his-soul"],["הַיְשָׁרָה","righteous"],["עֲגוּמָה","was-vexed"],["עָלָיו","in-him"],["יוֹם","day"],["וָיוֹם","to-day"],["בְּמַעֲשֵׂי","with-the-deeds-of"],["רִשְׁעָם","their-wickedness"],["׃",""]] },
  { num:"ט", words:[["כִּי","for"],["יוֹדֵעַ","knoweth"],["יְהוָֹה","the-Lord"],["לְהַצִּיל","how-to-deliver"],["אֶת־חֲסִידָיו","the-godly"],["מִנִּסָּיוֹן","out-of-temptations"],["וְלַחֲשׂךְ","and-to-reserve"],["אֶת־הָרְשָׁעִים","the-unjust"],["לְיוֹם","unto-the-day-of"],["הַמִּשְׁפָּט","judgment"],["לְהָשִׁיב","to-render"],["גְּמוּלָם","their-recompense"],["לָהֶם","to-them"],["׃",""]] },
  { num:"י", words:[["וּבְיוֹתֵר","but-chiefly"],["אֶת־הַהֹלְכִים","them-that-walk"],["אַחֲרֵי","after"],["הַבָּשָׂר","the-flesh"],["בְּתַאֲוֹת","in-the-lust-of"],["תֶּבֶל","uncleanness"],["וּבֹזִים","and-despise"],["אֶת־הַמֶּמְשָׁלָה","government"],["עַזֵּי","presumptuous"],["פָנִים","are-they"],["הֹלְכִים","walking"],["בִּשְׁרִירוּת","in-the-stubbornness-of"],["לִבָּם","their-heart"],["וְלֹא","and-not"],["יֶחֶרְדוּ","are-they-afraid"],["מֵחָרֵף","to-speak-evil-of"],["אֶת־הַשְּׂרָרוֹת","dignities"],["׃",""]] },
  { num:"יא", words:[["אֲשֶׁר","which"],["אַף־הַמַּלְאָכִים","even-angels"],["הַגְּדוֹלִים","which-are-greater"],["מֵהֶם","than-them"],["בְּעֹז","in-power"],["וָכֹחַ","and-might"],["לֹא","not"],["יְגַדְּפוּם","bring-railing-accusation-against-them"],["לִפְנֵי","before"],["יְהוָֹה","the-Lord"],["בְּמִשְׁפָּטָם","in-judgment"],["׃",""]] },
  { num:"יב", words:[["וְאֵלֶּה","but-these"],["כַּבְּהֵמוֹת","as-beasts"],["הַסְּכָלוֹת","brute"],["הַנּוֹלָדוֹת","made"],["כְּחָק־טִבְעָם","by-nature"],["לַלֶּכֶד","to-be-taken"],["וְלַשָּׁחַת","and-destroyed"],["בְּחֵרְפָם","speak-evil-of"],["אֶת־אֲשֶׁר","the-things-that"],["לֹא","not"],["יָדְעוּ","they-understand"],["יִשָּׁחֲתוּ","shall-utterly-perish"],["בְּהַשְׁחִית","in-corruption"],["נַפְשָׁם","their-own"],["וּגְמוּל","and-the-reward-of"],["עַוְלָתָם","their-unrighteousness"],["יִשָּׂאוּ","shall-receive"],["׃",""]] },
  { num:"יג", words:[["אֲשֶׁר","which"],["עֶדְנַת","to-riot-in"],["יוֹמָם","the-daytime"],["לְעֹנֶג","a-pleasure"],["יַחְשֹׁבוּ","they-count"],["מְגֹאָלִים","spots"],["וּמְזֻהָמִים","and-blemishes"],["הַמִּתְפַּנְּקִים","sporting-themselves"],["בְּמַדּוּחֵי","with-the-deceivings-of"],["נַפְשָׁם","their-own"],["וְאֹכְלִים","while-they-feast"],["וְשֹׁתִים","and-drink"],["עִמָּכֶם","with-you"],["׃",""]] },
  { num:"יד", words:[["עֵינַיִם","eyes"],["לָהֶם","they-have"],["מְלֵאוֹת","full-of"],["נִאֻפִים","adultery"],["וְלֹא","and-that-cannot"],["תִּשְׂבַּעְנָה","cease"],["לַחֲטֹא","from-sin"],["וְאֶת־נַפְשׁוֹת","and-souls"],["הַפְּתָאִים","unstable"],["יְצוֹדֵדוּ","they-beguile"],["וְלֵב","and-an-heart"],["מְלֻמַּד־בֶּצַע","exercised-with-covetousness"],["לָהֶם","they-have"],["בְּנֵי","children-of"],["הַמְּאֵרָה","the-curse"],["׃",""]] },
  { num:"טו", words:[["אֶת־הַדֶּרֶךְ","the-way"],["הַיָּשָׁר","right"],["עָזְבוּ","they-have-forsaken"],["וַיִּתְעוּ","and-are-gone-astray"],["וַיֵּלְכוּ","and-follow"],["בְּדֶרֶךְ","the-way-of"],["בִּלְעָם","Balaam"],["בֶּן־בְּעוֹר","the-son-of-Beor"],["אֲשֶׁר","who"],["אָהֵב","loved"],["שְׂכַר","the-wages-of"],["הָעַוְלָה","unrighteousness"],["׃",""]] },
  { num:"טז", words:[["וַתְּהִי־לוֹ","but-he-was"],["תוֹכַחַת","rebuked"],["עַל־חַטָּאתוֹ","for-his-iniquity"],["כִּי","for"],["הַבְּהֵמָה","the-beast"],["הָאִלֶּמֶת","dumb"],["דִּבְּרָה","speaking"],["בְקוֹל־אָדָם","with-man's-voice"],["וַתַּעְצֹר","forbad"],["בְּאִוֶּלֶת","the-madness-of"],["הַקֹּסֵם","the-prophet"],["׃",""]] },
  { num:"יז", words:[["בְּאֵרוֹת","wells"],["בְּלִי־מַיִם","without-water"],["הֵמָּה","these-are"],["עָבִים","clouds"],["נִדָּפִים","carried"],["בִּסְעָרָה","with-a-tempest"],["אֲשֶׁר","to-whom"],["שָׁמוּר","is-reserved"],["לָהֶם","for-them"],["חֹשֶׁך־אֲפֵלָה","the-mist-of-darkness"],["לְעוֹלָם","for-ever"],["׃",""]] },
  { num:"יח", words:[["כִּי","because"],["בְּדַבְּרָם","when-they-speak"],["בְּגֵאוּת","great-swelling"],["דִּבְרֵי","words-of"],["שָׁוְא","vanity"],["יָצוּדוּ","they-allure"],["בְּתַאֲוֹת","through-the-lusts-of"],["הַבָּשָׂר","the-flesh"],["עַל־יְדֵי","through"],["זִמָּתָם","their-wantonness"],["אֵת־אֲשֶׁר","those-that"],["אַךְ־נִמְלְטוּ","were-clean-escaped"],["מִידֵי","from"],["הַהֹלְכִים","them-who-walk"],["בְּדֶרֶךְ","in-the-way-of"],["תּוֹעָה","error"],["׃",""]] },
  { num:"יט", words:[["חֻפְשָׁה","liberty"],["יַבְטִיחוּ","they-promise"],["לָהֶם","them"],["וְהֵם","they"],["בְּעַצְמָם","themselves"],["עֲבָדִים","are-servants"],["לַשָּׁחַת","of-corruption"],["כִּי","for"],["עֶבֶד","a-servant-is"],["הָאָדָם","the-man"],["לְכֹבְשׁוֹ","to-him-that-overcometh-him"],["׃",""]] },
  { num:"כ", words:[["כִּי","because"],["אַחֲרֵי","after"],["הִמָּלְטָם","they-have-escaped"],["מִטֻּמְאֹת","the-pollutions-of"],["הָעוֹלָם","the-world"],["בְּדַעַת","through-the-knowledge-of"],["אֲדֹנֵינוּ","our-Lord"],["וּמוֹשִׁיעֵנוּ","and-Saviour"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אִם־שָׁבוּ","if-again"],["וְהָטְבְּעוּ","they-are-entangled"],["בְתוֹכָן","therein"],["וְנִכְבָּשׁוּ","and-overcome"],["אַחֲרִיתָם","their-latter-end"],["תִּהְיֶה","is"],["רָעָה","worse"],["מֵרֵאשִׁיתָם","than-their-beginning"],["׃",""]] },
  { num:"כא", words:[["נוֹחַ","better"],["לָהֶם","for-them"],["שֶׁלּא","not"],["לָדַעַת","to-have-known"],["אֶת־דֶּרֶךְ","the-way-of"],["הַצְּדָקָה","righteousness"],["מֵאֲשֶׁר","than"],["יְדָעֻהוּ","they-have-known-it"],["וְנָסֹגוּ","and-turn"],["אָחוֹר","back"],["מִן־הַמִּצְוָה","from-the-commandment"],["הַקְּדוֹשָׁה","holy"],["הַמְּסוּרָה","delivered"],["לָהֶם","unto-them"],["׃",""]] },
  { num:"כב", words:[["וְקָרָה","but-it-is-happened"],["לָהֶם","unto-them"],["כַּאֲשֶׁר","according-as"],["יֹאמַר","saith"],["מְשַׁל","the-proverb-of"],["הָאֱמֶת","truth"],["הַכֶּלֶב","the-dog"],["שָׁב","is-turned"],["עַל־קֵאוֹ","to-his-vomit"],["וְהַחֲזִיר","and-the-sow"],["עֹלֶה","coming-up"],["מִן־הָרַחְצָה","from-the-washing"],["לְהִתְגֹּלֵל","to-wallow"],["בָּרָפֶשׁ","in-the-mire"],["׃",""]] },
];
renderVerseSet(_2pe_ch2Verses, '2pe-ch2-verses');

var _2pe_ch3Verses = [
  { num:"א", words:[["זֹאת","this"],["הָאִגֶּרֶת","epistle"],["הַשֵּׁנִית","second"],["אֲשֶׁר","which"],["אֲנִי","I"],["כֹתֵב","write"],["אֲלֵיכֶם","unto-you"],["חֲבִיבָי","beloved"],["וּבִשְׁתֵּיהֶן","in-both-which"],["כְּמַזְכִּיר","by-way-of-remembrance"],["אָעִיר","I-stir-up"],["אֶת־תֻּמַּת","the-pure"],["לְבַבְכֶם","your-minds"],["׃",""]] },
  { num:"ב", words:[["לִזְכֹּר","that-you-may-be-mindful-of"],["אֶת־הַדְּבָרִים","the-words"],["הַנֶּאֱמָרִים","which-were-spoken"],["מִקֶּדֶם","before"],["בִּידֵי","by"],["הַנְּבִיאִים","the-prophets"],["הַקְּדֹשִׁים","holy"],["וְאֶת־מִצְוַת","and-the-commandment-of"],["אֲדֹנֵינוּ","our-Lord"],["וּמוֹשִׁיעֵנוּ","and-Saviour"],["אֲשֶׁר","which"],["נִתְּנָה","was-given"],["עַל־יְדֵי","by"],["שְׁלִיחֵיכֶם","your-apostles"],["׃",""]] },
  { num:"ג", words:[["וּדְעוּ","knowing"],["זֹאת","this"],["לָכֶם","for-you"],["רִאשֹׁנָה","first"],["כִּי","that"],["בְּאַחֲרִית","in-the-last"],["הַיָּמִים","days"],["יָבֹאוּ","there-shall-come"],["לֵצִים","scoffers"],["הֹלְכִים","walking"],["אַחֲרֵי","after"],["תַאֲוֹת","the-lusts-of"],["נַפְשָׁם","their-own"],["וְיִתְלוֹצֲצוּ","and-scoffing"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ד", words:[["אַיֵּה","where-is"],["הַבְטָחַת","the-promise-of"],["בֹּאוֹ","his-coming"],["כִּי","for"],["מֵאָז","since"],["שָׁכְבוּ","fell-asleep"],["הָאָבוֹת","the-fathers"],["הַכֹּל","all-things"],["עֹמֵד","continue"],["כְּמוֹ","as-they-were"],["מֵרֵאשִׁית","from-the-beginning-of"],["הַבְּרִיאָה","the-creation"],["׃",""]] },
  { num:"ה", words:[["וְנֶעְלָם","for-is-hidden"],["מִדַּעְתָּם","from-their-knowledge"],["לִרְצוֹנָם","willingly"],["שֶׁלְּפָנִים","that-of-old"],["בִּדְבַר","by-the-word-of"],["אֱלֹהִים","God"],["נַעֲשׂוֹּ","were-made"],["הַשָּׁמַיִם","the-heavens"],["וְהָאָרֶץ","and-the-earth"],["מִן־הַמַּיִם","out-of-the-water"],["וְעַל־יְדֵי","and-in"],["הַמָּיִם","the-water"],["׃",""]] },
  { num:"ו", words:[["וְעַל","whereby"],["יְדֵיהֶם","by-them"],["אָבְדָה","perished"],["תֵבֵל","the-world"],["אֲשֶׁר","that"],["מֵאָז","then-was"],["כִּי","being"],["נִשְׁטְפָה","overflowed"],["בְּמֵי","with-the-waters-of"],["הַמַּבּוּל","the-flood"],["׃",""]] },
  { num:"ז", words:[["גַּם־הַשָּׁמַיִם","but-the-heavens"],["וְהָאָרֶץ","and-the-earth"],["אֲשֶׁר","which"],["לְפָנֵינוּ","are-now"],["נִצְפְּנוּ","are-kept-in-store"],["בִדְבָרוֹ","by-the-same-word"],["וְהֵם","and-they"],["שְׁמוּרִים","are-reserved"],["לָאֵשׁ","unto-fire"],["לְיוֹם","against-the-day-of"],["הַדִּין","judgment"],["וַאֲבֹד","and-perdition-of"],["אַנְשֵׁי","men-of"],["הָרֶשַׁע","ungodliness"],["׃",""]] },
  { num:"ח", words:[["וְזֹאת","but-this"],["הָאַחַת","one-thing"],["אַל־תֵּעָלֵם","be-not-ignorant-of"],["מִכֶּם","from-you"],["חֲבִיבָי","beloved"],["שֶׁיּוֹם","that-day"],["אֶחָד","one"],["כְּאֶלֶף","as-a-thousand"],["שָׁנִים","years"],["בְּעֵינֵי","in-the-eyes-of"],["יְהוָֹה","the-Lord"],["וְאֶלֶף","and-a-thousand"],["שָׁנִים","years"],["כְּיוֹם","as-day"],["אֶחָד","one"],["׃",""]] },
  { num:"ט", words:[["וְלֹא־יְאַחֵר","is-not-slack"],["יְהוָֹה","the-Lord"],["אֶת־אֲשֶׁר","concerning-that-which"],["הִבְטִיחַ","he-hath-promised"],["כַּאֲשֶׁר־יֵשׁ","as-there-are"],["חֹשְׁבִים","who-count"],["זֹאת","this"],["לְאִחוּר","slackness"],["כִּי","but"],["מַאֲרִיךְ","prolongeth"],["אַפּוֹ","his-patience"],["בַּעֲבוּרֵנוּ","to-us-ward"],["וְלֹא","not"],["יַחְפֹּץ","willing"],["בַּאֲבֹד","that-should-perish"],["הָאֹבְדִים","any"],["כִּי","but"],["אִם־בִּפְנוֹת","that-should-turn"],["כֻּלָּם","all"],["לַתְּשׁוּבָה","to-repentance"],["׃",""]] },
  { num:"י", words:[["בֹּא","surely"],["יָבֹא","shall-come"],["יוֹם־יְהוָֹה","the-day-of-the-Lord"],["כְּגַנָּב","as-a-thief"],["בַּלָּיְלָה","in-the-night"],["אָז","in-which"],["הַשָּׁמַיִם","the-heavens"],["בְּשָׁאוֹן","with-a-great-noise"],["יַחֲלֹפוּ","shall-pass-away"],["וְהַיְסֹדוֹת","and-the-elements"],["יְבֹעֲרוּ","shall-burn"],["וְהִתְמֹגֲגוּ","and-melt"],["וְהָאָרֶץ","and-the-earth"],["וְהַמַּעֲשִׂים","and-the-works"],["אֲשֶׁר","that-are"],["עָלֶיהָ","therein"],["יִשָּׂרֵפוּ","shall-be-burned-up"],["׃",""]] },
  { num:"יא", words:[["וְעַתָּה","seeing-then"],["אִם־כׇּל־אֵלֶּה","that-all-these"],["יָמוּגוּ","shall-be-dissolved"],["מַה־מְּאֹד","what-manner-of-persons"],["עֲלֵיכֶם","ought-you"],["לְהִתְהַלֵּךְ","to-walk"],["בִּקְדֻשָּׁה","in-holiness"],["וּבַחֲסִידוּת","and-godliness"],["׃",""]] },
  { num:"יב", words:[["וּלְחַכּוֹת","looking-for"],["לְיוֹם־יְהוָֹה","the-day-of-God"],["שֶׁיָּבֹא","that-shall-come"],["וּלְהָחִישׁ","and-hasting"],["אֹתוֹ","it"],["אֲשֶׁר","wherein"],["בּוֹ","in-it"],["הַשָּׁמַיִם","the-heavens"],["יָמוּגוּ","shall-be-dissolved"],["בָאֵשׁ","by-fire"],["וְהַיְסֹדוֹת","and-the-elements"],["יְבֹעֲרוּ","shall-burn"],["וְנָמַסּוּ","and-melt"],["׃",""]] },
  { num:"יג", words:[["וַאֲנַחְנוּ","but-we"],["כְּפִי","according-to"],["הַבְטָחָתוֹ","his-promise"],["מְחַכִּים","look-for"],["לְשָׁמַיִם","heavens"],["חֲדָשִׁים","new"],["וּלְאֶרֶץ","and-a-earth"],["חֲדָשָׁה","new"],["אֲשֶׁר־צֶדֶק","wherein-righteousness"],["יָלִין","dwelleth"],["בָּם","in-them"],["׃",""]] },
  { num:"יד", words:[["עַל־כֵּן","therefore"],["חֲבִיבַי","my-beloved"],["הַמְחַכִּים","seeing-you-look-for"],["לָאֵלֶּה","such-things"],["שִׁקְדוּ","be-diligent"],["לְהִמָּצֵא","that-you-may-be-found"],["לְפָנָיו","of-him"],["בְּשָׁלוֹם","in-peace"],["נְקִיִּם","without-spot"],["וְזַכִּים","and-blameless"],["מִפָּשַׁע","from-transgression"],["׃",""]] },
  { num:"טו", words:[["וְאֶת־אֹרֶךְ","and-the-longsuffering"],["רוּחַ","of-spirit-of"],["אֲדֹנֵינוּ","our-Lord"],["תַּחְשְׁבוּ","account"],["לִתְשׁוּעָה","is-salvation"],["כַּאֲשֶׁר","even-as"],["גַּם־אָחִינוּ","also-our-brother"],["הָאָהוּב","beloved"],["פּוֹלוֹס","Paul"],["כָּתַב","hath-written"],["אֲלֵיכֶם","unto-you"],["כְּפִי","according-to"],["הַחׇכְמָה","the-wisdom"],["הַנְּתוּנָה","given"],["לוֹ","unto-him"],["׃",""]] },
  { num:"טז", words:[["וְכֵן","as-also"],["בְּכׇל־אִגְּרוֹתָיו","in-all-his-epistles"],["בְּדַבְּרוֹ־שָׁם","speaking-therein"],["עַל־אֵלֶּה","of-these-things"],["וּבָהֶן","in-which"],["יֵשׁ","are"],["דְּבָרִים","things"],["קָשִׁים","hard"],["מֵהָבִין","to-be-understood"],["וְהַבֹּעֲרִים","which-the-unlearned"],["וְהַפְּתָאִים","and-unstable"],["יַהַפְכוּ","wrest"],["אֹתָם","them"],["כַּאֲשֶׁר","as"],["גַּם־יַעֲשׂוֹּ","they-do-also"],["בְּיֶתֶר","the-other"],["הַסְּפָרִים","scriptures"],["לְאָבְדַן","unto-the-destruction-of"],["נַפְשָׁם","their-own"],["׃",""]] },
  { num:"יז", words:[["וְאַתֶּם","you-therefore"],["חֲבִיבַי","beloved"],["אֲשֶׁר","which"],["יְדַעְתֶּם","you-know"],["זֹאת","this"],["מֵרֹאשׁ","before"],["הִשָּׁמְרוּ","beware"],["לְנַפְשֹׁתֵיכֶם","yourselves"],["פֶּן־תִּמָּשְׁכוּ","lest-you-be-led-away"],["אַחֲרֵי","with"],["טָעוּת","the-error-of"],["אַנְשֵׁי","the-men-of"],["בְלִיַּעַל","Belial"],["וּנְפַלְתֶּם","fall"],["מִמָּעֻזְּכֶם","from-your-own-stedfastness"],["׃",""]] },
  { num:"יח", words:[["וּרְבוּ","but-grow"],["בְּחֶסֶד","in-grace"],["וּבְדַעַת","and-in-the-knowledge-of"],["אֲדֹנֵינוּ","our-Lord"],["וּמוֹשִׁיעֵנוּ","and-Saviour"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲשֶׁר־לוֹ","to-whom-be"],["הַכָּבוֹד","glory"],["גַּם־הַיּוֹם","both-now"],["וְגַם־לְיוֹם","and-for"],["הָעוֹלָם","ever"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(_2pe_ch3Verses, '2pe-ch3-verses');

})();
