// nt_verses/2pe.js — 2 Peter verse data
(function() {
var _2pe_ch1Verses = [
  { num:"א", words:[["שִׁמְעוֹן","Simon"],["פֶּטְרוֹס","Peter"],["עֶבֶד","the-servant-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["וּשְׁלִיחוֹ","and-apostle-of-his"],["אֶל־אֲשֶׁר","unto-that-which"],["קִבְּלוּ","receive"],["אֱמוּנָה","faith"],["יְקָרָה","precious"],["כְּשֶׁלָּנוּ","as-that-we"],["בְּצִדְקַת","by-the-righteousness-of"],["אֱלֹהֵינוּ","our-God"],["וּמוֹשִׁיעֵנוּ","and-our-Savior"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ב", words:[["חֶסֶד","grace"],["וְשָׁלוֹם","and-peace"],["יִהְיוּ","shall-be"],["לָכֶם","to-you"],["לְמַכְבִּיר","to-abundance"],["בְּדַעַת","in-the-knowledge-of"],["הָאֱלֹהִים","the-God"],["וְיֵשׁוּעַ","and-Jesus"],["אֲדֹנֵינוּ","our-Lord"],["׃",""]] },
  { num:"ג", words:[["בַּאֲשֶׁר","because"],["גְּבוּרָתוֹ","his-power"],["הָאֱלֹהִית","the-divine(f)"],["נָתְנָה","was-given(f)"],["לָּנוּ","we"],["אֵת","[ACC]"],["כָּל־צָרְכֵינוּ","all-our-needs"],["לַחַיִּים","unto-life"],["וְלַחֲסִידוּת","and-to-godliness"],["עַל־יְדֵי","by-means-of"],["דַעַת","knowledge"],["הַקּוֹרֵא","the-calling"],["אֹתָנוּ","us"],["בִּכְבוֹדוֹ","in-his-glory"],["וְחֵילוֹ","and-his-power"],["׃",""]] },
  { num:"ד", words:[["אֲשֶׁר","which"],["בָּהֶם","in-them"],["נָתַן־לָנוּ","was-given-us"],["הַבְטָחוֹת","the-promises-of"],["גְּדֹלוֹת","great"],["מְאֹד","exceedingly"],["וִיקָרוֹת","and-precious"],["לְמַעַן","in-order-that"],["תִּקְחוּ","you will take"],["עַל־יָדָן","upon-hands-their"],["חֵלֶק","part"],["בְּטֶבַע","in-the-carnal-nature-of"],["אֱלֹהִים","God"],["לְהִמָּלֵט","to-escape"],["מִכִּלְיוֹן","from-the-consumption"],["הַתַּאֲוָה","the-desire"],["אֲשֶׁר","which"],["בָּעוֹלָם","of-the-world"],["׃",""]] },
  { num:"ה", words:[["בַּעֲבוּר","because-of"],["זֹאת","this"],["שִׁקְדוּ","watch"],["לְהוֹסִיף","to-add"],["עַל־אֱמוּנַתְכֶם","upon-your-faith"],["אֶת־מַעֲשֵׂה","[ACC]-work-of"],["הַצְּדָקָה","the-righteousness"],["וְעַל","and-upon"],["מַעֲשֵׂה","work-of"],["הַצְּדָקָה","the-righteousness"],["אֶת־הַדָּעַת","[ACC]-the-knowledge"],["׃",""]] },
  { num:"ו", words:[["וְעַל־הַדַּעַת","and-upon-the-knowledge"],["אֶת־הַפְּרִישׁוּת","[ACC]-the-temperance"],["וְעַל־הַפְּרִישׁוּת","and-upon-the-temperance"],["אֶת־הַסַּבְלָנוּת","[ACC]-the-patience"],["וְעַל־הַסַּבְלָנוּת","and-upon-the-patience"],["אֶת־הַחֲסִידוּת","[ACC]-the-godliness"],["׃",""]] },
  { num:"ז", words:[["וְעַל־הַחֲסִידוּת","and-upon-the-piety"],["אֶת־הָאַחֲוָה","[ACC]-the-brotherhood"],["וְעַל־הָאַחֲוָה","and-upon-the-brotherhood"],["אֶת־הָאַהֲבָה","[ACC]-the-love"],["׃",""]] },
  { num:"ח", words:[["כִּי","because"],["אִם־אֵלֶּה","if-these"],["יִמָּצְאוּ","be-found"],["וְיִרְבּוּ","so-they may increase"],["בָכֶם","over-you"],["לֹא־יִתְּנוּ","not-they-should-impart"],["אֶתְכֶם","you"],["לִהְיוֹת","to-be"],["מִתְעַצְּלִים","idle"],["וּבְטֵלִים","and-unfruitful"],["מֵעֲשׂוֹת","from-do"],["פְּרִי","fruit"],["לְדַעַת","to-the-knowledge-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ט", words:[["כִּי","because"],["הָאִישׁ","the-man"],["אֲשֶׁר","which"],["אֵין־אֵלֶּה","there-is-no-these"],["לּוֹ","upon-him"],["עִוֵּר","blind"],["הוּא","it"],["רְפֵה","slack of"],["עֵינַיִם","by-the-eyes-of"],["וְשָׁכֵחַ","and-oblivious"],["אֶת־טָהֳרָתוֹ","[ACC]-purification-his"],["מֵחַטֹּאתָיו","of-his-sins"],["הָרִאשֹׁנוֹת","the-first"],["׃",""]] },
  { num:"י", words:[["לָכֵן","therefore"],["אַחַי","my-brothers"],["הוֹסִיפוּ","they-continued"],["וְשִׁקְדוּ","and-watch"],["לְחַזֵּק","to-strengthen"],["אֶת־קְרִיאַתְכֶם","[ACC]-your-calling"],["וּבְחִירַתְכֶם","and-choosing-of-you(pl)"],["בְּמַעֲשִׂים","in-good-works"],["טוֹבִים","good"],["כִּי","because"],["אִם","if"],["כֵּן","thus"],["תַּעֲשׂוֹּ","you-do"],["לֹא","not"],["תִכָּשֵׁלוּ","you will stumble(they)"],["׃",""]] },
  { num:"יא", words:[["כִּי־כֵן","because-thus"],["יִפָּתַח","it will be opened"],["לִפְנֵיכֶם","unto-you"],["לָרְוָחָה","to-the-relief"],["מְבוֹא","from-the-coming-of"],["מַלְכוּת","the-reign-of"],["עוֹלָם","eternal"],["אֲשֶׁר","which"],["לַאֲדֹנֵינוּ","to-lord-our"],["וּמוֹשִׁיעֵנוּ","and-our-Savior"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"יב", words:[["עַל־כֵּן","therefore"],["לֹא","not"],["אֶחְדַּל","I-shall-cease"],["לְהַזְכִּירְכֶם","to-make remembrance-you(pl)"],["עַל־אֵלֶּה","upon-these"],["בְּכָל־עֵת","with-all-time"],["אַף־כִּי","yea-because"],["יְדַעְתֶּם","you-know"],["אֶת־אֲמִתֵּנוּ","[ACC]-our-truth"],["זוּ","which"],["וְהִתְכּוֹנַנְתֶּם","and-you-were-established"],["בָּהּ","in-it(f)"],["׃",""]] },
  { num:"יג", words:[["וְנָכוֹן","and-expedient"],["בְּעֵינַי","in-my-eyes"],["לְהַזְכִּיר","to-bring-to-remembrance"],["וּלְהָעִיר","and-to-stir-up"],["אֶתְכֶם","you"],["כָּל־יְמֵי","as-long-as"],["הֱיוֹתִי","being-I"],["בַּמִּשְׁכָּן","in-the-tabernacle"],["הַזֶּה","this"],["׃",""]] },
  { num:"יד", words:[["מִדַּעְתִּי","for-knew-I"],["כִּי","because"],["מַהֵר","soon"],["יֶעְתַּק","it moves"],["מִשְׁכָּנִי","dwelling place-my"],["וְכֵן","and-so"],["גִּלָּה־לִי","had-discovered-to-me"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"טו", words:[["וְאֶשְׁקֹד","and-I will keep watch"],["לִהְיוֹת","to-be"],["לָכֶם","to-you"],["תָּמִיד","continually"],["זִכְרוֹן","a-record-of"],["הַדְּבָרִים","the-things"],["הָאֵלֶּה","these"],["גַּם־אַחֲרֵי","also-after"],["פְטִירָתִי","my-departure"],["׃",""]] },
  { num:"טז", words:[["כִּי","because"],["לֹא","not"],["הָלַכְנוּ","we-went"],["אַחֲרֵי","after"],["הַגָּדוֹת","the-fables"],["מְחֻכָּמוֹת","cunningly-devised"],["בְּהוֹדִיעֵנוּ","in-make known to-us"],["אֶתְכֶם","you"],["גְּבוּרַת","might-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["וּבֹאוֹ","and-his-coming"],["כִּי","because"],["עֵינֵינוּ","our-eyes"],["הָיוּ","were"],["הָרֹאוֹת","the-beholders-of"],["אֶת־גְּדֻלָּתוֹ","[ACC]-His-greatness"],["׃",""]] },
  { num:"יז", words:[["כִּי","because"],["נָשָׂא","bore"],["יְקָר","the honor of"],["וְכָבוֹד","and-glory"],["מֵאֵת","from"],["אֱלֹהִים","God"],["הָאָב","the-Father"],["כְּבֹא","when-went"],["אֵלָיו","to-him"],["קוֹל","the-voice-of"],["מִלִּפְנֵי","from-presence-of"],["הַדְרַת","the glory of"],["כְּבוֹדוֹ","His-glory"],["לֵאמֹר","saying"],["זֶה","this"],["בְּנִי","my-son"],["יְדִידִי","my-beloved"],["רָצְתָה","it has accepted"],["נַפְשִׁי","my-life"],["בּוֹ","in-Him"],["׃",""]] },
  { num:"יח", words:[["וְאֶת־הַקּוֹל","and-[ACC]-the-voice"],["הַהוּא","that"],["שָׁמַעְנוּ","did-we-heed"],["בְאָזְנֵינוּ","in-our-ears"],["יֹצֵא","was going out"],["מִן־הַשָּׁמָיִם","from-the-heavens"],["בִּהְיוֹתֵנוּ","when-were-we"],["עִמּוֹ","with-him"],["בְּהַר","while-on-the-mount-of"],["הַקֹּדֶשׁ","the-Holy"],["׃",""]] },
  { num:"יט", words:[["וּדְבַר","and-spoke"],["הַנְּבוּאָה","the-prophecy"],["יוֹתֵר","more"],["קַיָּם","established"],["אִתָּנוּ","with-us"],["וַהֲטִיבֹתֶם","and-you-do-well"],["עֲשׂוֹת","do"],["אֲשֶׁר","which"],["שַׁתֶּם","that-the-end"],["לִבְּכֶם","to-your-hearts"],["אֵלָיו","to-him"],["כְּנֵר","as-lamp"],["מֵאִיר","was-lit"],["בִּמְקוֹם","at-the-place-of"],["אֹפֶל","darkness"],["עַד־כִּי","insomuch-that"],["יִבָּקַע","it will break forth"],["אוֹר","light"],["הַיּוֹם","the-day"],["וְזָרַח","and-he dawned"],["כּוֹכַב","the star of"],["הַנֹּגַהּ","the-brightness"],["בִּלְבַבְכֶם","in-your-hearts"],["׃",""]] },
  { num:"כ", words:[["וְזֹאת","and-this"],["תֵּדְעוּ","know-shall-you"],["רִאשׁוֹנָה","first"],["אֲשֶׁר","which"],["כָּל־נְבוּאַת","all-prophecies-of"],["הַמִּקְרָא","the-Scripture"],["אֵינֶנָּה","is-not"],["כְּפִי","according-to"],["פִתְרוֹן","the interpretation of"],["אָדָם","man"],["מִלִּבּוֹ","from-own heart-his"],["׃",""]] },
  { num:"כא", words:[["כִּי","because"],["מֵעוֹלָם","never"],["לֹא־יָצְאָה","not-went-forth"],["נְבוּאָה","a-prophecy"],["בִּרְצוֹן","in-the-will-of"],["הָאָדָם","the-man"],["כִּי","because"],["אַנְשֵׁי","the-men-of"],["אֱלֹהִים","God"],["הַקְּדוֹשִׁים","the-holy"],["דִּבְּרוּ","have-spoken"],["כַּאֲשֶׁר","when/as"],["נְשָׂאָם","we-carry-them"],["רוּחַ","the-spirit-of"],["הַקֹּדֶשׁ","the-Holy"],["׃",""]] },
];
renderVerseSet(_2pe_ch1Verses, '2pe-ch1-verses');

var _2pe_ch2Verses = [
  { num:"א", words:[["וְגַם־נְבִיאֵי","and-also-false-prophets"],["שֶׁקֶר","false"],["הָיוּ","were"],["בָעָם","on the-people"],["כַּאֲשֶׁר","when/as"],["יִהְיוּ","shall-be"],["מוֹרֵי","false-teachers"],["שֶׁקֶר","false"],["גַּם־בָּכֶם","also-in-you"],["אֲשֶׁר","which"],["יַכְנִיסוּ","they-shall-bring-in"],["כִּתּוֹת","heresies"],["מַשְׁחִיתוֹת","destructive"],["וִיכַחֲשׁוּ","and-they-denied"],["בַּמֹּשֵׁל","in-the-Master"],["אֲשֶׁר","which"],["קָנָם","bought-them"],["וְיָבִיאוּ","and-they-shall-bring"],["עַל־נַפְשָׁם","upon-their-soul"],["כִּלָּיוֹן","the-consumption"],["פִּתְאֹם","suddenly"],["׃",""]] },
  { num:"ב", words:[["וְרַבִּים","and-many"],["יֵלְכוּ","they-should-travel"],["אַחֲרֵי","after"],["תוֹעֲבוֹתָם","the abominations of-their"],["וּבַעֲבוּרָם","and-in-exchange"],["יֻתַּן","shall-be-given"],["דֶּרֶךְ","through"],["הָאֱמֶת","the-true"],["לְגִדּוּפִים","to-reviling words"],["׃",""]] },
  { num:"ג", words:[["וּבְדִבְרֵי","and-in-words-of"],["בִדּוּי","feigned"],["יַעֲשׂוֹּ","they have made"],["אֶתְכֶם","you"],["לְמִסְחָר","to-traffic"],["לָהֶם","to-them"],["לְמַעַן","in-order-that"],["בְּצֹעַ","to make unjust gain"],["בָּצַע","unjust gain"],["אֲשֶׁר","which"],["מִשְׁפָּטָם","from-judged-their"],["מֵאָז","since"],["לֹא","not"],["יִתְמַהְמַהּ","he delayed"],["וְשִׁבְרָם","and-their-destruction"],["לֹא","not"],["יָנוּם","shall-slumber"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["לֹא־חָס","not-spare"],["אֱלֹהִים","God"],["עַל־הַמַּלְאָכִים","upon-the-angels"],["אֲשֶׁר","which"],["חָטְאוּ","sinned"],["כִּי","because"],["אִם־הוֹרִידָם","if-take them down-them"],["לְקִצְבֵי","to-extremities of"],["הָרִים","mountains"],["וַיַסְגִּירֵם","and-He-delivered-them"],["בְּכַבְלֵי","in-chains-of"],["אֹפֶל","darkness"],["לְשָׁמְרָם","to-watch-them"],["לַמִּשְׁפָּט","to-the-judgment"],["׃",""]] },
  { num:"ה", words:[["וְגַם־עַל־הַדּוֹרוֹת","and-also-upon-the-generations"],["הָרִאשֹׁנִים","the-ancient"],["לֹא","not"],["חָס","spare"],["וַיִּשְׁמֹר","and-he-did-keep"],["רַק","only"],["אֶת־נֹחַ","[ACC]-Noah"],["קֹרֵא","a-preacher-of"],["הַצֶּדֶק","the-justice"],["וְשִׁבְעָה","and-seven"],["עִמּוֹ","with-him"],["בַּהֲבִיאוֹ","in-His-bringing"],["אֶת־הַמַּבּוּל","[ACC]-the-flood"],["עַל־דּוֹר","upon-generation"],["הָרְשָׁעִים","the-wicked"],["׃",""]] },
  { num:"ו", words:[["וְאֶת־עָרֵי","and-[ACC]-cities-of"],["סְדוֹם","Sodom"],["וַעֲמֹרָה","and-Gomorrah"],["הָפַךְ","it has turned"],["לָאֵפֶר","to-ashes"],["וְדָנָם","and-He-condemned-them"],["בְּמַהְפֵּכָה","in-a-mighty-change"],["וַיְשִׂימֵם","and-he-shall-make-them"],["לְמָשָׁל","a byword"],["לַאֲשֶׁר","unto-him-who"],["עֲתִידִים","are-about"],["לַעֲשׂוֹת","to-do"],["זִמָּה","lewdness"],["׃",""]] },
  { num:"ז", words:[["וַיַּצֵּל","and-he has taken away"],["אֶת־לוֹט","[ACC]-Lot"],["הַצַּדִּיק","the-righteous"],["אֲשֶׁר","which"],["הֶלְאוּהוּ","they-wearied-him"],["אַנְשֵׁי","the-men-of"],["בְלִיַעַל","wickedness"],["הָהֵם","those"],["בְּדַרְכֵי","in-ways-of"],["זִמָּתָם","a plan of-their"],["׃",""]] },
  { num:"ח", words:[["כִּי","because"],["הַצַּדִּיק","the-righteous"],["הַזֶּה","this"],["יָשַׁב","dwelt/sat"],["בְּתוֹכָם","among-them"],["וְהוּא","and-it"],["רֹאֶה","seeing"],["אֹתָם","them"],["וְשֹׁמֵעַ","and-shall-hearken"],["וְנַפְשׁוֹ","and-his-soul"],["הַיְשָׁרָה","the-right"],["עֲגוּמָה","was-grieved"],["עָלָיו","upon-him"],["יוֹם","day"],["וָיוֹם","and-day"],["בְּמַעֲשֵׂי","in-works-of"],["רִשְׁעָם","their-wickedness"],["׃",""]] },
  { num:"ט", words:[["כִּי","because"],["יוֹדֵעַ","knows"],["יְהוָֹה","the-Lord"],["לְהַצִּיל","to-deliver"],["אֶת־חֲסִידָיו","[ACC]-faithful people-his"],["מִנִּסָּיוֹן","from-trial"],["וְלַחֲשׂךְ","and-to-reserve"],["אֶת־הָרְשָׁעִים","ACC-the-wicked"],["לְיוֹם","to-day"],["הַמִּשְׁפָּט","the-judgment"],["לְהָשִׁיב","to-render"],["גְּמוּלָם","their-recompense"],["לָהֶם","to-them"],["׃",""]] },
  { num:"י", words:[["וּבְיוֹתֵר","and-in-more"],["אֶת־הַהֹלְכִים","[ACC]-the-ones-walking"],["אַחֲרֵי","after"],["הַבָּשָׂר","the-flesh"],["בְּתַאֲוֹת","in-lusts"],["תֶּבֶל","perversion"],["וּבֹזִים","and-plunder(pl)"],["אֶת־הַמֶּמְשָׁלָה","[ACC]-the-government"],["עַזֵּי","are mighty of"],["פָנִים","man"],["הֹלְכִים","walking"],["בִּשְׁרִירוּת","in-the stubbornness of"],["לִבָּם","their-hearts"],["וְלֹא","and-not"],["יֶחֶרְדוּ","they will tremble"],["מֵחָרֵף","from-reviling"],["אֶת־הַשְּׂרָרוֹת","[ACC]-the-dignities"],["׃",""]] },
  { num:"יא", words:[["אֲשֶׁר","which"],["אַף־הַמַּלְאָכִים","yea-the-angels"],["הַגְּדוֹלִים","the-great"],["מֵהֶם","of-them"],["בְּעֹז","with-boldness"],["וָכֹחַ","and-power-of"],["לֹא","not"],["יְגַדְּפוּם","they-bring-railing-against-them"],["לִפְנֵי","before"],["יְהוָֹה","the-Lord"],["בְּמִשְׁפָּטָם","in-their-judgment"],["׃",""]] },
  { num:"יב", words:[["וְאֵלֶּה","and-these"],["כַּבְּהֵמוֹת","like the-animals"],["הַסְּכָלוֹת","the-irrational"],["הַנּוֹלָדוֹת","the-who-had been born(pl)"],["כְּחָק־טִבְעָם","by-natural-instinct"],["לַלֶּכֶד","to-the-be-caught"],["וְלַשָּׁחַת","and-to-the-corruption"],["בְּחֵרְפָם","when-defied-they"],["אֶת־אֲשֶׁר","ACC-that-which"],["לֹא","not"],["יָדְעוּ","they-knew"],["יִשָּׁחֲתוּ","shall-be-destroyed"],["בְּהַשְׁחִית","in-to destroy"],["נַפְשָׁם","their-soul"],["וּגְמוּל","and-the dealing of"],["עַוְלָתָם","their-iniquity"],["יִשָּׂאוּ","take-in-vain"],["׃",""]] },
  { num:"יג", words:[["אֲשֶׁר","which"],["עֶדְנַת","pleasure-of"],["יוֹמָם","by-day"],["לְעֹנֶג","as-pleasure"],["יַחְשֹׁבוּ","shall-they-regard"],["מְגֹאָלִים","stained"],["וּמְזֻהָמִים","and-defiled"],["הַמִּתְפַּנְּקִים","the-reveling"],["בְּמַדּוּחֵי","in-deceptions-of"],["נַפְשָׁם","their-soul"],["וְאֹכְלִים","and-those who eat"],["וְשֹׁתִים","and-drinking"],["עִמָּכֶם","with-you"],["׃",""]] },
  { num:"יד", words:[["עֵינַיִם","by-the-eyes-of"],["לָהֶם","to-them"],["מְלֵאוֹת","full"],["נִאֻפִים","adultery"],["וְלֹא","and-not"],["תִּשְׂבַּעְנָה","they are satisfied"],["לַחֲטֹא","to-sin"],["וְאֶת־נַפְשׁוֹת","and-[ACC]-souls-of"],["הַפְּתָאִים","the-O naive people"],["יְצוֹדֵדוּ","they-entice"],["וְלֵב","and-heart"],["מְלֻמַּד־בֶּצַע","from-been-taught-gain/profit"],["לָהֶם","to-them"],["בְּנֵי","the-sons-of"],["הַמְּאֵרָה","the-curse"],["׃",""]] },
  { num:"טו", words:[["אֶת־הַדֶּרֶךְ","[ACC]-the-way"],["הַיָּשָׁר","the-straight"],["עָזְבוּ","left"],["וַיִּתְעוּ","and-they-shall-err"],["וַיֵּלְכוּ","and-they-went"],["בְּדֶרֶךְ","after-the-manner-of"],["בִּלְעָם","Balaam"],["בֶּן־בְּעוֹר","son-of-Beor"],["אֲשֶׁר","which"],["אָהֵב","he loves"],["שְׂכַר","reward"],["הָעַוְלָה","the-injustice"],["׃",""]] },
  { num:"טז", words:[["וַתְּהִי־לוֹ","and-was-him"],["תוֹכַחַת","rebuke"],["עַל־חַטָּאתוֹ","upon-the-crime"],["כִּי","because"],["הַבְּהֵמָה","the-livestock"],["הָאִלֶּמֶת","the-is-dumb"],["דִּבְּרָה","spoke"],["בְקוֹל־אָדָם","with-a voice-man"],["וַתַּעְצֹר","so-it may be restrained"],["בְּאִוֶּלֶת","in-ignorance"],["הַקֹּסֵם","the-diviner"],["׃",""]] },
  { num:"יז", words:[["בְּאֵרוֹת","wells"],["בְּלִי־מַיִם","without-water"],["הֵמָּה","they"],["עָבִים","clouds"],["נִדָּפִים","driven"],["בִּסְעָרָה","in-stormy(f)"],["אֲשֶׁר","which"],["שָׁמוּר","it was kept"],["לָהֶם","to-them"],["חֹשֶׁך־אֲפֵלָה","darkness-of-darkness"],["לְעוֹלָם","forever"],["׃",""]] },
  { num:"יח", words:[["כִּי","because"],["בְּדַבְּרָם","while-they-should-speak"],["בְּגֵאוּת","over-the swelling of"],["דִּבְרֵי","account-of"],["שָׁוְא","falsehood"],["יָצוּדוּ","they-shall-hunt"],["בְּתַאֲוֹת","in-lusts"],["הַבָּשָׂר","the-flesh"],["עַל־יְדֵי","by-means-of"],["זִמָּתָם","a plan of-their"],["אֵת","[ACC]"],["אֲשֶׁר","which"],["אַךְ־נִמְלְטוּ","but-escaped"],["מִידֵי","from-those-who"],["הַהֹלְכִים","the-ones-walking"],["בְּדֶרֶךְ","after-the-manner-of"],["תּוֹעָה","confusion"],["׃",""]] },
  { num:"יט", words:[["חֻפְשָׁה","freedom"],["יַבְטִיחוּ","he-shall-promise(they)"],["לָהֶם","to-them"],["וְהֵם","and-they"],["בְּעַצְמָם","in-themselves"],["עֲבָדִים","bondage"],["לַשָּׁחַת","to-the-pit"],["כִּי","because"],["עֶבֶד","the-servant-of"],["הָאָדָם","the-man"],["לְכֹבְשׁוֹ","to-they will subdue"],["׃",""]] },
  { num:"כ", words:[["כִּי","because"],["אַחֲרֵי","after"],["הִמָּלְטָם","their-escape"],["מִטֻּמְאֹת","from-the uncleanness of"],["הָעוֹלָם","the-world"],["בְּדַעַת","in-the-knowledge-of"],["אֲדֹנֵינוּ","our-Lord"],["וּמוֹשִׁיעֵנוּ","and-our-Savior"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אִם־שָׁבוּ","if-repented"],["וְהָטְבְּעוּ","and-they are sunk"],["בְתוֹכָן","therein"],["וְנִכְבָּשׁוּ","and-they-were-subdued"],["אַחֲרִיתָם","the-consequence"],["תִּהְיֶה","shall-be"],["רָעָה","evil"],["מֵרֵאשִׁיתָם","from-their-beginning"],["׃",""]] },
  { num:"כא", words:[["נוֹחַ","better"],["לָהֶם","for-them"],["שֶׁלּא","that-there-should-be-no"],["לָדַעַת","to-know"],["אֶת־דֶּרֶךְ","[ACC]-through"],["הַצְּדָקָה","the-righteousness"],["מֵאֲשֶׁר","than-that"],["יְדָעֻהוּ","they knew-it"],["וְנָסֹגוּ","and-withdrew"],["אָחוֹר","back"],["מִן־הַמִּצְוָה","from-the-commandment"],["הַקְּדוֹשָׁה","the-holy(f)"],["הַמְּסוּרָה","the-delivered"],["לָהֶם","to-them"],["׃",""]] },
  { num:"כב", words:[["וְקָרָה","and-happened"],["לָהֶם","to-them"],["כַּאֲשֶׁר","when/as"],["יֹאמַר","He-says"],["מְשַׁל","the proverb of"],["הָאֱמֶת","the-true"],["הַכֶּלֶב","the-dog"],["שָׁב","returned/repented"],["עַל־קֵאוֹ","upon-its-vomit"],["וְהַחֲזִיר","and-the-pig"],["עֹלֶה","ascends-up"],["מִן־הָרַחְצָה","from-the-washing"],["לְהִתְגֹּלֵל","to-the-shall-be-rolled-up"],["בָּרָפֶשׁ","in-mire"],["׃",""]] },
];
renderVerseSet(_2pe_ch2Verses, '2pe-ch2-verses');

var _2pe_ch3Verses = [
  { num:"א", words:[["זֹאת","this"],["הָאִגֶּרֶת","the-epistle"],["הַשֵּׁנִית","the-second"],["אֲשֶׁר","which"],["אֲנִי","I"],["כֹתֵב","writing"],["אֲלֵיכֶם","unto-you"],["חֲבִיבָי","my-beloved"],["וּבִשְׁתֵּיהֶן","and-in-both of-them"],["כְּמַזְכִּיר","as-one-who-reminds"],["אָעִיר","I-awaken"],["אֶת־תֻּמַּת","[ACC]-the integrity of"],["לְבַבְכֶם","your-hearts"],["׃",""]] },
  { num:"ב", words:[["לִזְכֹּר","to-remember"],["אֶת־הַדְּבָרִים","[ACC]-the-words"],["הַנֶּאֱמָרִים","the-it-was-said"],["מִקֶּדֶם","of-old"],["בִּידֵי","by-hands-of"],["הַנְּבִיאִים","the-prophets"],["הַקְּדֹשִׁים","the-holy"],["וְאֶת־מִצְוַת","and-[ACC]-the-commandments-of"],["אֲדֹנֵינוּ","our-Lord"],["וּמוֹשִׁיעֵנוּ","and-our-Savior"],["אֲשֶׁר","which"],["נִתְּנָה","was-given(f)"],["עַל־יְדֵי","by-means-of"],["שְׁלִיחֵיכֶם","apostle-your(pl)"],["׃",""]] },
  { num:"ג", words:[["וּדְעוּ","and-know"],["זֹאת","this"],["לָכֶם","to-you"],["רִאשֹׁנָה","first"],["כִּי","because"],["בְּאַחֲרִית","in-latter"],["הַיָּמִים","the-days"],["יָבֹאוּ","come"],["לֵצִים","mockers"],["הֹלְכִים","walking"],["אַחֲרֵי","after"],["תַאֲוֹת","lusts"],["נַפְשָׁם","their-soul"],["וְיִתְלוֹצֲצוּ","and-they-shall-mock"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ד", words:[["אַיֵּה","where-is"],["הַבְטָחַת","the-promise-of"],["בֹּאוֹ","His-coming"],["כִּי","because"],["מֵאָז","since"],["שָׁכְבוּ","they-lie"],["הָאָבוֹת","the-fathers"],["הַכֹּל","all-the"],["עֹמֵד","standing"],["כְּמוֹ","as/like"],["מֵרֵאשִׁית","from-the-beginning"],["הַבְּרִיאָה","the-creation"],["׃",""]] },
  { num:"ה", words:[["וְנֶעְלָם","and-hidden"],["מִדַּעְתָּם","from-their-minds"],["לִרְצוֹנָם","to-their-will"],["שֶׁלְּפָנִים","that-of-old"],["בִּדְבַר","by-the-word-of"],["אֱלֹהִים","God"],["נַעֲשׂוֹּ","were-done"],["הַשָּׁמַיִם","the-heavens"],["וְהָאָרֶץ","and-the-earth"],["מִן־הַמַּיִם","from-the-waters"],["וְעַל־יְדֵי","and-upon-hands-of"],["הַמָּיִם","the-water"],["׃",""]] },
  { num:"ו", words:[["וְעַל","and-upon"],["יְדֵיהֶם","their-hands"],["אָבְדָה","perished"],["תֵבֵל","the-world"],["אֲשֶׁר","which"],["מֵאָז","since"],["כִּי","because"],["נִשְׁטְפָה","was-flooded"],["בְּמֵי","in-the-waters-of"],["הַמַּבּוּל","the-flood"],["׃",""]] },
  { num:"ז", words:[["גַּם־הַשָּׁמַיִם","also-the-heavens"],["וְהָאָרֶץ","and-the-earth"],["אֲשֶׁר","which"],["לְפָנֵינוּ","before-us"],["נִצְפְּנוּ","are-stored-up"],["בִדְבָרוֹ","by-His-word"],["וְהֵם","and-they"],["שְׁמוּרִים","keep(pl)"],["לָאֵשׁ","to-the-fire"],["לְיוֹם","to-day"],["הַדִּין","the-judgment"],["וַאֲבֹד","and-the-perdition-of"],["אַנְשֵׁי","the-men-of"],["הָרֶשַׁע","the-wickedness"],["׃",""]] },
  { num:"ח", words:[["וְזֹאת","and-this"],["הָאַחַת","the-one"],["אַל־תֵּעָלֵם","do-not-you hide"],["מִכֶּם","from-you"],["חֲבִיבָי","my-beloved"],["שֶׁיּוֹם","that-day"],["אֶחָד","one"],["כְּאֶלֶף","about-a thousand"],["שָׁנִים","years"],["בְּעֵינֵי","in-the-eyes-of"],["יְהוָֹה","the-Lord"],["וְאֶלֶף","and-one thousand"],["שָׁנִים","years"],["כְּיוֹם","as-the-day-of"],["אֶחָד","one"],["׃",""]] },
  { num:"ט", words:[["וְלֹא־יְאַחֵר","and-not-he-delays"],["יְהוָֹה","the-Lord"],["אֶת־אֲשֶׁר","ACC-that-which"],["הִבְטִיחַ","has-promised"],["כַּאֲשֶׁר־יֵשׁ","when/as-there-is"],["חֹשְׁבִים","thought"],["זֹאת","this"],["לְאִחוּר","to-backwards"],["כִּי","because"],["מַאֲרִיךְ","is-slow(of)"],["אַפּוֹ","His-wrath"],["בַּעֲבוּרֵנוּ","because-of-us"],["וְלֹא","and-not"],["יַחְפֹּץ","delights"],["בַּאֲבֹד","that-any-should-perish"],["הָאֹבְדִים","the-lost"],["כִּי","because"],["אִם־בִּפְנוֹת","if-in-the-turning-of"],["כֻּלָּם","all-of-them"],["לַתְּשׁוּבָה","to-the-repentance"],["׃",""]] },
  { num:"י", words:[["בֹּא","come"],["יָבֹא","shall-come"],["יוֹם־יְהוָֹה","the-day-of-the-LORD"],["כְּגַנָּב","as-a-thief"],["בַּלָּיְלָה","by-the-night"],["אָז","then"],["הַשָּׁמַיִם","the-heavens"],["בְּשָׁאוֹן","in-uproar"],["יַחֲלֹפוּ","they may pass away"],["וְהַיְסֹדוֹת","and-the-foundations"],["יְבֹעֲרוּ","they will kindle"],["וְהִתְמֹגֲגוּ","and-they melt"],["וְהָאָרֶץ","and-the-earth"],["וְהַמַּעֲשִׂים","and-the-works"],["אֲשֶׁר","which"],["עָלֶיהָ","upon-it"],["יִשָּׂרֵפוּ","burned-shall-they-be"],["׃",""]] },
  { num:"יא", words:[["וְעַתָּה","and-now"],["אִם־כָּל־אֵלֶּה","if-all-these"],["יָמוּגוּ","they-shall-melt"],["מַה־מְּאֹד","what-exceedingly"],["עֲלֵיכֶם","over-you"],["לְהִתְהַלֵּךְ","to-walk"],["בִּקְדֻשָּׁה","in-holiness"],["וּבַחֲסִידוּת","and-in-godliness"],["׃",""]] },
  { num:"יב", words:[["וּלְחַכּוֹת","and-to-wait-for"],["לְיוֹם־יְהוָֹה","for-the-day-of-the-LORD"],["שֶׁיָּבֹא","that-shall-come"],["וּלְהָחִישׁ","and-to-to speed up"],["אֹתוֹ","him"],["אֲשֶׁר","which"],["בּוֹ","wherein"],["הַשָּׁמַיִם","the-heavens"],["יָמוּגוּ","they-shall-melt"],["בָאֵשׁ","in-fire"],["וְהַיְסֹדוֹת","and-the-foundations"],["יְבֹעֲרוּ","they will kindle"],["וְנָמַסּוּ","and-they will melt away"],["׃",""]] },
  { num:"יג", words:[["וַאֲנַחְנוּ","and-we-are"],["כְּפִי","according-to"],["הַבְטָחָתוֹ","the-promise-of-his"],["מְחַכִּים","waiting"],["לְשָׁמַיִם","to-the-heavens"],["חֲדָשִׁים","new-ones"],["וּלְאֶרֶץ","and-to-the-land-of"],["חֲדָשָׁה","new"],["אֲשֶׁר־צֶדֶק","whose-righteousness"],["יָלִין","it will remain overnight"],["בָּם","in-them"],["׃",""]] },
  { num:"יד", words:[["עַל־כֵּן","therefore"],["חֲבִיבַי","my-beloved"],["הַמְחַכִּים","those-who long"],["לָאֵלֶּה","to-such"],["שִׁקְדוּ","watch"],["לְהִמָּצֵא","to-actually"],["לְפָנָיו","before-him"],["בְּשָׁלוֹם","in-peace"],["נְקִיִּם","innocent"],["וְזַכִּים","and-spotless"],["מִפָּשַׁע","from-transgression"],["׃",""]] },
  { num:"טו", words:[["וְאֶת־אֹרֶךְ","and-[ACC]-he-was-long"],["רוּחַ","the-spirit-of"],["אֲדֹנֵינוּ","our-Lord"],["תַּחְשְׁבוּ","suppose"],["לִתְשׁוּעָה","to-deliverance"],["כַּאֲשֶׁר","when/as"],["גַּם־אָחִינוּ","also-our-brother"],["הָאָהוּב","the-beloved"],["פּוֹלוֹס","Paul"],["כָּתַב","he-wrote"],["אֲלֵיכֶם","unto-you"],["כְּפִי","according-to"],["הַחָכְמָה","the-wisdom"],["הַנְּתוּנָה","the-given"],["לוֹ","him"],["׃",""]] },
  { num:"טז", words:[["וְכֵן","and-so"],["בְּכָל־אִגְּרוֹתָיו","in-all-his-epistles"],["בְּדַבְּרוֹ־שָׁם","in-his-speaking-therein"],["עַל־אֵלֶּה","upon-these"],["וּבָהֶן","and-in-them(f)"],["יֵשׁ","there"],["דְּבָרִים","things"],["קָשִׁים","hard"],["מֵהָבִין","from-to understand"],["וְהַבֹּעֲרִים","and-the-O stupid ones"],["וְהַפְּתָאִים","and-the-simple people"],["יַהַפְכוּ","they may devastate"],["אֹתָם","them"],["כַּאֲשֶׁר","when/as"],["גַּם־יַעֲשׂוֹּ","also-they have made"],["בְּיֶתֶר","with-more"],["הַסְּפָרִים","the-Scriptures"],["לְאָבְדַן","to-loss-of"],["נַפְשָׁם","their-soul"],["׃",""]] },
  { num:"יז", words:[["וְאַתֶּם","and-will-you"],["חֲבִיבַי","my-beloved"],["אֲשֶׁר","which"],["יְדַעְתֶּם","you-know"],["זֹאת","this"],["מֵרֹאשׁ","from-the-beginning"],["הִשָּׁמְרוּ","beware"],["לְנַפְשֹׁתֵיכֶם","of-lives-you"],["פֶּן־תִּמָּשְׁכוּ","lest-you/she-will-draw"],["אַחֲרֵי","after"],["טָעוּת","error"],["אַנְשֵׁי","the-men-of"],["בְלִיַּעַל","Belial"],["וּנְפַלְתֶּם","and-you will fall"],["מִמָּעֻזְּכֶם","from-is refuge-your"],["׃",""]] },
  { num:"יח", words:[["וּרְבוּ","and-multiply"],["בְּחֶסֶד","in-the-grace-of"],["וּבְדַעַת","and-with-knowledge"],["אֲדֹנֵינוּ","our-Lord"],["וּמוֹשִׁיעֵנוּ","and-our-Savior"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲשֶׁר־לוֹ","whom"],["הַכָּבוֹד","the-glorious"],["גַּם־הַיּוֹם","also-the-day"],["וְגַם־לְיוֹם","and-also-to-day"],["הָעוֹלָם","the-world"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(_2pe_ch3Verses, '2pe-ch3-verses');

})();
