// nt_verses/2th.js — 2 Thessalonians verse data
(function() {
var _2th_ch1Verses = [
  { num:"א", words:[["פּוֹלוֹס","Paul"],["וְסִלְוָנוֹס","and-Silvanus"],["וְטִימוֹתִיּוֹס","and-Timothy"],["אֶל־קְהִלַּת","to-church-of"],["הַתֶּסָּלוֹנִיקִיּים","the-Thessalonians"],["בֵּאלֹהִים","in-God"],["אָבִינוּ","our-father"],["וּבַאֲדֹנֵינוּ","and-in-our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ב", words:[["חֶסֶד","grace"],["לָכֶם","to-you"],["וְשָׁלוֹם","and-peace"],["מֵאֵת","from"],["אֱלֹהִים","God"],["אָבִינוּ","our-father"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ג", words:[["חַיָּבִים","are-obligated"],["אֲנַחְנוּ","we"],["לְהוֹדוֹת","to-thanksgivings"],["תָּמִיד","continually"],["לֵאלֹהִים","God"],["עֲלֵיכֶם","over-you"],["אַחַי","my-brothers"],["כָּרָאוּי","as-fitting"],["כִּי","because"],["אֱמוּנַתְכֶם","your-faith"],["גָּדְלָה","great-was"],["מְאֹד","exceedingly"],["וְרַבָּה","and-it will become many"],["אַהֲבַת","love-of"],["כֻּלְּכֶם","all-you"],["אִישׁ","man-of"],["לְרֵעֵהוּ","another"],["׃",""]] },
  { num:"ד", words:[["עַד","until"],["שֶׁנִּתְהַלֵּל","that-we-shall-boast"],["בָּכֶם","in-you"],["בִּקְהִלּוֹת","in-churches"],["אֱלֹהִים","God"],["עַל־סַבְלָנוּתְכֶם","was over-patience-your(pl)"],["וְעַל־אֱמוּנַתְכֶם","and-upon-your-faith"],["בְּכָל־הָרְדִיפוֹת","in-all-the-persecutions"],["וּבְכָל־הַלַּחַץ","and-in-all-the-oppression"],["אֲשֶׁר","which"],["סְבַלְתֶּם","suffer(you-pl)"],["׃",""]] },
  { num:"ה", words:[["לְאוֹת","for-a-sign"],["צִדְקַת","righteousness-of"],["מִשְׁפַּט","judgment"],["אֱלֹהִים","God"],["לְמַעַן","in-order-that"],["תִּמָּצְאוּ","you-be-found"],["רְאוּיִם","worthy"],["לְמַלְכוּת","of-reign-of"],["הָאֱלֹהִים","the-God"],["אֲשֶׁר","which"],["בַּעֲבוּרָהּ","for-her-sake"],["תְּעֻנּוּ","you-suffer"],["׃",""]] },
  { num:"ו", words:[["בַּאֲשֶׁר","because"],["צַדִּיק","righteous"],["הוּא","it"],["הָאֱלֹהִים","the-God"],["לִגְמֹל","to-recompense"],["לַחַץ","oppression"],["לְלֹחֲצֵיכֶם","to-those who oppressed-you"],["׃",""]] },
  { num:"ז", words:[["וְלָכֶם","and-to-you"],["הַנִּלְחָצִים","the-oppressed"],["רְוָחָה","relief"],["עִמָּנוּ","with-us"],["יָחַד","together"],["בְּהִגָּלוֹת","because-were uncovered"],["הָאָדוֹן","the-Lord"],["יֵשׁוּעַ","Jesus"],["מִן־הַשָּׁמַיִם","from-the-heavens"],["עִם־מַלְאֲכֵי","with-the-angels-of"],["עֻזּוֹ","strength-his"],["׃",""]] },
  { num:"ח", words:[["בְּאֵשׁ","with-fire"],["לֶֶהָבָה","of-flame"],["לְהָשִׁיב","to-render"],["נָקָם","vengeance"],["לַאֲשֶׁר","unto-him-who"],["לֹא־יָדְעוּ","know-not"],["אֶת־הָאֱלֹהִים","[ACC]-God"],["וְלֹא","and-not"],["שָׁמְעוּ","they-heard"],["לִבְשׂוֹרַת","to-tidings-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ט", words:[["אֲשֶׁר","which"],["יִשְׂאוּ","shall-bear"],["מִשְׁפָּטָם","their-punishment"],["אָבְדַּן","perished"],["עוֹלָם","eternal"],["מֵאֵת","from"],["פְּנֵי","face-of"],["הָאָדוֹן","the-Lord"],["וּמֵהֲדַר","and-the-glory-of"],["גְּאוֹנוֹ","His-majesty"],["׃",""]] },
  { num:"י", words:[["בְּבֹאוֹ","when-came-he"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["לְהִכָּבֵד","to-be honored"],["בִּקְדשָׁיו","in-His-saints"],["וּלְהִתְפַּלֵּא","and-to-marvel"],["בְּכָל־הַמַּאֲמִינִים","in-all-the-believers"],["כִּי","because"],["הֶאֱמַנְתֶּם","you-believed"],["לְעֵדוּתֵנוּ","as-a-testimony-us"],["אֲלֵיכֶם","unto-you"],["׃",""]] },
  { num:"יא", words:[["לָזֹאת","to-this"],["גַּם־נִתְפַּלֵּל","also-we prayed"],["בַּעַדְכֶם","for-you"],["תָּמִיד","continually"],["אֲשֶׁר","which"],["יִתֵּן","shall-give"],["אֶתְכֶם","you"],["אֱלֹהֵינוּ","our-God"],["רְאוּיִם","worthy"],["לְמַה־שֶּׁאַתֶּם","to-what-you-are"],["מְקֹרָאִים","from-calling-on"],["וִימַלֵּא","so-may he fill?"],["בְעֹז","in-strength-of"],["כָּל־חֶפְצְכֶם","all-your-desire"],["בַּטּוֹב","the-good"],["וְכָל־מַעֲשֵׂה","and-all-work-of"],["אֱמוּנַתְכֶם","your-faith"],["׃",""]] },
  { num:"יב", words:[["לְמַעַן","in-order-that"],["יִכָּבֶד","be-glorified"],["בָּכֶם","in-you"],["שֵׁם","the-name-of"],["יֵשׁוּעַ","Jesus"],["אֲדֹנֵינוּ","our-Lord"],["וְאַתֶּם","and-will-you"],["תִּכָּבְדוּ","you-be-glorified"],["בוֹ","in-Him"],["עַל־פִּי","according-to"],["חֶסֶד","grace"],["אֱלֹהֵינוּ","our-God"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
];
renderVerseSet(_2th_ch1Verses, '2th-ch1-verses');

var _2th_ch2Verses = [
  { num:"א", words:[["וְהִנְנוּ","and-behold-us"],["מְבַקְשִׁים","seek"],["מִכֶּם","from-you"],["אֶחָי","brothers-my"],["עַל־אֹדוֹת","upon-concerning"],["בִּיאַת","the-coming-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["וַאֲסִיפָתֵנוּ","and-gathering-of-us"],["אֵלָיו","to-him"],["׃",""]] },
  { num:"ב", words:[["אֲשֶׁר","which"],["לֹא־תִטָּרֵף","not-be-shaken"],["דַּעְתְּכֶם","knowledge-you(pl)"],["פִּתְאֹם","suddenly"],["וַאֲשֶׁר","and-whom"],["לֹא","not"],["תִּבָּהֵלוּ","you be hasty(they)"],["לֹא","not"],["בְרוּחַ","by-the spirit of"],["וְלֹא","and-not"],["בְדִבּוּר","in-speaking"],["וְלֹא","and-not"],["בְאִגֶּרֶת","in-letter"],["כְּאִלּוּ","as-though"],["שְׁלוּחָה","which has been sent"],["מֵאִתָּנוּ","from-among-us"],["לֵאמֹר","saying"],["הִגִּיעַ","come-has"],["יוֹם","day"],["יְהוָֹה","the-Lord"],["׃",""]] },
  { num:"ג", words:[["אַל־יַתְעֶה","do-not-shall-deceive"],["אֶתְכֶם","you"],["אִישׁ","man-of"],["בְּשׁוּם","in-any/put"],["אוֹפֶן","manner"],["כִּי","because"],["לֹא־יָבֹא","not-shall-come"],["בְּטֶרֶם","before"],["יִהְיֶה","shall-be"],["בָרִאשׁוֹנָה","first-place"],["הַמֶּרֶד","the-rebellion"],["וְנִגְלָה","and-he has revealed himself"],["אִישׁ","man-of"],["הָחַטָּאָה","the-sin"],["בֶּן־הָאֲבַדּוֹן","the-son-of-perdition"],["׃",""]] },
  { num:"ד", words:[["הַמִּתְקוֹמֵם","the-one-who-rises-up"],["וְהַמִּתְרוֹמֵם","and-the-one-exalting-himself"],["עַל־כָּל־הַנִּקְרָא","upon-all-the-called"],["אֵל","God"],["אוֹ","or"],["עֲבוֹדָה","worship"],["כִּי","because"],["גַם־יֵשֵׁב","also-he-sits"],["בְּהֵיכַל","in-the temple of"],["הָאֱלֹהִים","the-God"],["כֵּאלֹהִים","as-God"],["וּמַרְאֶה","and-shows"],["אֶת־עַצְמוֹ","[ACC]-himself"],["כִּי","because"],["אֱלֹהִים","God"],["הוּא","it"],["׃",""]] },
  { num:"ה", words:[["הֲלֹא","do-not"],["תִזְכְּרוּ","you-should-remember"],["כִּי־בְעוֹד","because-in-yet"],["הֱיוֹתִי","being-I"],["אִתְּכֶם","with-you"],["אֵלֶּה","these"],["דִּבַּרְתִּי","I-have-spoken"],["אֲלֵיכֶם","unto-you"],["׃",""]] },
  { num:"ו", words:[["וְעַתָּה","and-now"],["יְדַעְתֶּם","you-know"],["אֶת","[ACC]"],["אֲשֶׁר","which"],["יִמְנָעֵהוּ","restrains-him"],["מִלְּהִגָּלוֹת","from-to-be revealed"],["בְּעִתּוֹ","in-its-time"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["סוֹד","counsels-of"],["הָרֶשַׁע","the-wickedness"],["כְּבָר","already-come"],["הֵחֵלָּה","began(f)"],["פְעֻלָּתוֹ","its-working"],["רַק","only"],["שֶׁיּוּסַר","that-be-removed"],["מִתָּוֶךְ","from-middle"],["הַמֹּנֵעַ","the-one-who-restrains"],["עַד־כֹּה","until-thus"],["׃",""]] },
  { num:"ח", words:[["וְאָז","and-then"],["יִגָּלֶה","He-shall-be-revealed"],["הָרָשָׁע","the-more-wicked"],["אֲשֶׁר","which"],["יְמִיתֶנּוּ","he will put to death-him"],["הָאָדוֹן","the-Lord"],["בְּרוּחַ","in-the-Spirit"],["שְׂפָתָיו","His-lips"],["וְיַשְׁבִּיתֶנּוּ","and-will-destroy-him"],["בְּהוֹפָעַת","with-the-brightness-of"],["בִּיאָתוֹ","his-coming"],["׃",""]] },
  { num:"ט", words:[["אֵת","[ACC]"],["אֲשֶׁר","which"],["יָבוֹא","shall-come"],["כְּפִי","according-to"],["פְּעֻלַּת","the-working-of"],["הַשָׂטָן","the-adversary"],["בְּרָב־כֹּחַ","with-greatness of-power"],["וּבְאֹתוֹת","and-by-signs"],["וּבְמוֹפְתֵי","and-in-types-of"],["שָׁקֶר","false"],["׃",""]] },
  { num:"י", words:[["וּבְכָל־מִרְמַת","and-in-all-deceit-of"],["אָוֶן","iniquity"],["בָּאֹבְדִים","in-the-lost"],["תַּחַת","under"],["אֲשֶׁר","which"],["לֹא","not"],["קִבְּלוּ","receive"],["אֶת־אַהֲבַת","[ACC]-love-of"],["הָאֱמֶת","the-true"],["לְהִוָּשֵׁעַ","to-shall-be"],["׃",""]] },
  { num:"יא", words:[["וּבַעֲבוּר","and-because"],["זֹאת","this"],["יְשַׁלַּח","shall-send"],["לָהֶם","to-them"],["הָאֱלֹהִים","the-God"],["מַדּוּחֵי","delusion-of"],["שָׁוְא","falsehood"],["לְהַאֲמִין","to-believe"],["בַּשָּׁקֶר","in-the-falsehood"],["׃",""]] },
  { num:"יב", words:[["לְמַעַן","in-order-that"],["יִדּוֹנוּ","be-damned"],["כָּל־אֲשֶׁר","all-which"],["לֹא־הֶאֱמִינוּ","not-did-they-believe"],["בָאֱמֶת","in-truth"],["וְרָצוּ","they-shall-be-pleased"],["בָּעַוְלָה","in-iniquity"],["׃",""]] },
  { num:"יג", words:[["אֲבָל","but/however"],["אֲנַחְנוּ","we"],["חַיָּבִים","are-obligated"],["לְהוֹדוֹת","to-thanksgivings"],["תָּמִיד","continually"],["לֵאלֹהִים","God"],["בַּעֲבוּרְכֶם","for-your-sakes"],["אַחַי","my-brothers"],["חֲבִיבֵי","my-beloved"],["הָאָדוֹן","the-Lord"],["אֲשֶׁר","which"],["מִבַּתְּחִלָּה","from-in-shall-begin"],["בָּחַר","chose"],["בָּכֶם","in-you"],["הָאֱלֹהִים","the-God"],["לִישׁוּעָה","unto-salvation"],["בִּקְדֻשַּׁת","with-holiness-of"],["הָרוּחַ","the-Spirit"],["וּבֶאֱמוּנַת","and-in-faith-of"],["הָאֱמֶת","the-true"],["׃",""]] },
  { num:"יד", words:[["לָזֹאת","to-this"],["קָרָא","called"],["אֶתְכֶם","you"],["בִּבְשׂוֹרָתֵנוּ","in-good-news-of-us"],["לְנַחֲלַת","for-the-inheritance-of"],["כְּבוֹד","the-glory-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"טו", words:[["לָכֵן","therefore"],["אַחַי","my-brothers"],["עִמְדוּ","stand"],["וְהַחֲזִיקוּ","and-the-lay-hold-upon"],["בַקַּבָּלוֹת","in-the-received(pl)"],["אֲשֶׁר","which"],["לֻמַּדְתֶּם","have-been-taught"],["אִם","[compound]"],["בִּדְבָרֵנוּ","by-our-word"],["אִם","[compound]"],["בְּאִגַּרְתֵּנוּ","in-our-epistle"],["׃",""]] },
  { num:"טז", words:[["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["וֵאלֹהֵינוּ","and-God-our"],["אָבִינוּ","our-father"],["אֲשֶׁר","which"],["אָהַב","He-loves"],["אֹתָנוּ","us"],["וַיִּתֶּן־לָנוּ","and-the-king-granted-unto-us"],["בְחַסְדּוֹ","in-His-lovingkindness"],["נֶחָמַת","consolation-of"],["עוֹלָם","eternal"],["וְתִקְוָה","and-hope"],["טוֹבָה","good"],["׃",""]] },
  { num:"יז", words:[["הוּא","it"],["יְנַחֵם","He-comforted"],["אֶת־לְבַבְכֶם","[ACC]-your-hearts"],["וִיכוֹנֵן","and-he will establish"],["אֶתְכֶם","you"],["בְּכָל־דָּבָר","in-all-things"],["וּמַעֲשֶׂה","and-a-work"],["טוֹב","good"],["׃",""]] },
];
renderVerseSet(_2th_ch2Verses, '2th-ch2-verses');

var _2th_ch3Verses = [
  { num:"א", words:[["וְעוֹד","and-again"],["אַחַי","my-brothers"],["הִתְפַּלֲלוּ","pray!"],["בַעֲדֵנוּ","for-us"],["אֲשֶׁר","which"],["יָרוּץ","he runs"],["דְּבַר","the-word-of"],["יְהוָֹה","the-Lord"],["וְיִכָּבֵד","and-be-glorified"],["כְּהִכָּבְדוֹ","as-it-was-glorified"],["בְקִרְבְּכֶם","among-you"],["׃",""]] },
  { num:"ב", words:[["וַאֲשֶׁר","and-whom"],["נִנָּצֵל","we-be-delivered"],["מִן־הָאֲנָשִׁים","from-the-men"],["הַתֹּעִים","the-wandering"],["וְהָרָעִים","and-evil"],["כִּי","because"],["לֹא","not"],["לְכָל־אָדָם","unto-all-men"],["הָאֱמוּנָה","the-faith"],["׃",""]] },
  { num:"ג", words:[["אֲבָל","but/however"],["נֶאֱמָן","more-faithful"],["הוּא","it"],["הָאָדוֹן","the-Lord"],["אֲשֶׁר","which"],["יְחַזֵּק","shall-strengthen"],["אֶתְכֶם","you"],["וְיִשְׁמָרְכֶם","and-shall-be-kept-you(pl)"],["מִן־הָרָע","from-that-which-is-evil"],["׃",""]] },
  { num:"ד", words:[["וַאֲנַחְנוּ","and-we-are"],["בְּטוּחִים","confident"],["עֲלֵיכֶם","over-you"],["בַּאֲדֹנֵינוּ","in-the-our-Lord"],["שֶׁעֹשִׂים","that-which-act"],["אַתֶּם","you-are"],["כְּמִצְוָתֵנוּ","as-our-precept"],["וְגַם־תּוֹסִיפוּ","and-also-continue"],["לַעֲשׂוֹת","to-do"],["׃",""]] },
  { num:"ה", words:[["וְהָאָדוֹן","and-the-Lord"],["הוּא","it"],["יְיַשֵּׁר","he will make straight"],["אֶת־לְבַבְכֶם","[ACC]-your-hearts"],["לְאַהֲבַת","to-love-of"],["הָאֱלֹהִים","the-God"],["וּלְסַבְלָנוּת","and-to-patience"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ו", words:[["וְהִנְנוּ","and-behold-us"],["מְצַוִּים","from-commands"],["אֶתְכֶם","you"],["אַחִים","brothers"],["בְּשֵׁם","by-name"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲשֶׁר","which"],["תִּבָּדְלוּ","you-separate"],["מִכָּל־אָח","above-all-a-brother"],["מְעַקֵּשׁ","one who perverts"],["דְּרָכָיו","His-ways"],["וְאֵינֶנּוּ","and-it-is-not"],["מִתְהַלֵּךְ","walking"],["עַל־פִּי","according-to"],["הַקַּבָּלָה","the-received"],["אֲשֶׁר","which"],["קִבֵּל","received"],["מֵאִתָּנוּ","from-among-us"],["׃",""]] },
  { num:"ז", words:[["הֲלֹא","do-not"],["אַתֶּם","you-are"],["יְדַעְתֶּם","you-know"],["שֶׁצְּרִיכִים","that-needing"],["אַתֶּם","you-are"],["לְהִתְהַלֵּךְ","to-walk"],["כָּמֹנוּ","like-us"],["כִּי","because"],["לֹא־הֶעֱוִינוּ","not-we have done wrong"],["אֶת־דַּרְכֵּנוּ","[ACC]-journey-our"],["בְּתוֹכֲכֶם","among-you"],["׃",""]] },
  { num:"ח", words:[["גַּם","also"],["לֹא־אָכַלְנוּ","not-have we eaten"],["לֶחֶם","bread"],["אִישׁ","man-of"],["חִנָּם","is-free"],["כִּי","because"],["בְּעָמָל","in-misery"],["וּתְלָאָה","and-hardship"],["לַיְלָה","night"],["וְיוֹמָם","and-by day"],["יָגַעְנוּ","we-toiled"],["לְבִלְתִּי","to-not"],["הֱיוֹת","have"],["לְאִישׁ","for-a-man"],["מִכֶּם","from-you"],["לְמַשָׂא","to-from-lift-up"],["׃",""]] },
  { num:"ט", words:[["לֹא","not"],["מִפְּנֵי","because-of"],["שֶׁאֵין־לָנוּ","whom-not-us"],["הָרְשׁוּת","the-authority"],["הַזֹּאת","is-this"],["כִּי","because"],["אִם־לָתֵת","[compound]-to-give"],["אֹתָנוּ","us"],["לָכֶם","to-you"],["לְמוֹפֵת","an-example"],["לָלֶכֶת","to-go"],["בְּעִקְּבוֹתֵינוּ","in-the footprints of-our"],["׃",""]] },
  { num:"י", words:[["כִּי","because"],["גַּם־בִּהְיוֹתֵנוּ","also-when-were-we"],["אֶצְלְכֶם","with-you"],["צִוִּינוּ","we-commanded"],["אֶתְכֶם","you"],["לֵאמֹר","saying"],["אֲשֶׁר","which"],["לֹא","not"],["יִרְצֶה","is-pleasing"],["לַעֲשׂוֹת","to-do"],["גַּם־לֹא","also-not"],["יֹאכֵל","shall-he-eat"],["׃",""]] },
  { num:"יא", words:[["כִּי","because"],["שָׁמַעְנוּ","did-we-heed"],["שֶׁיֵּשׁ","that-there-are"],["בָּכֶם","in-you"],["מְעַקְּשִׁים","disorderly"],["אָרְחֹתָם","their-ways"],["וְאֵינָם","and-are-not"],["עֹשִׂים","which-act"],["דָּבָר","things"],["וּמְבַלִּים","and-wasting"],["יְמֵיהֶם","their-days"],["בַּהֲבָלִים","in-the-futilities"],["׃",""]] },
  { num:"יב", words:[["וַאֲנָשִׁים","and-men"],["כָּאֵלֶּה","such-as-these"],["נְצַוֶּה","we-will-constitute"],["אוֹתָם","them"],["וְנַזְהִירֵם","and-exhort-them"],["בַּאֲדֹנֵינוּ","in-the-our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["לַעֲבֹד","to-labor"],["בְּנַחַת","in-quietness"],["לְמַעַן","in-order-that"],["יֹאכְלוּ","they-may-eat"],["אֶת־לַחְמָם","[ACC]-for food-their"],["מִשֶּׁלָּהֶם","from-that-unto-them"],["׃",""]] },
  { num:"יג", words:[["וְאַתֶּם","and-will-you"],["אֶחָי","brothers-my"],["אַל־תִּתְרַפּוּ","do-not-faint"],["בַּעֲשׂוֹת","in-committing"],["הַטּוֹב","the-good"],["׃",""]] },
  { num:"יד", words:[["וְאִם","and-if"],["לֹא־יִשְׁמַע","not-hearkens-to"],["אִישׁ","man-of"],["אֶל־דְּבָרֵנוּ","to-our-word"],["בָּאִגֶּרֶת","in-the-letter"],["הַזֹּאת","is-this"],["אֹתוֹ","him"],["תִרְשְׁמוּ","mark"],["לָכֶם","to-you"],["וְאַל־תִּתְעָרֲבוּ","and-do-not-associate"],["עִמּוֹ","with-him"],["לְמַעַן","in-order-that"],["יֵבוֹשׁ","be-ashamed"],["׃",""]] },
  { num:"טו", words:[["אַךְ","but"],["לֹא־כְאֹיֵב","not-as-an-enemy"],["תַּחְשְׁבֻהוּ","count-him"],["כִּי","because"],["אִם־תּוֹכִיחֻהוּ","but-admonish-him"],["כְּאָח","like-a brother"],["׃",""]] },
  { num:"טז", words:[["וְהוּא","and-it"],["וַאֲדוֹן","and-the-master-of"],["הַשָּׁלוֹם","the-peace"],["הוּא","it"],["יִתֵּן","shall-give"],["לָכֶם","to-you"],["הַשָּׁלוֹם","the-peace"],["תָּמִיד","continually"],["וּבְכָל־פָּנִים","and-by-all-means"],["יְהִי","let-this-be"],["הָאָדוֹן","the-Lord"],["עִם־כֻּלְּכֶם","with-all-you"],["׃",""]] },
  { num:"יז", words:[["שֹׁאֵל","ask"],["לִשְׁלוֹמְכֶם","for-your-peace"],["בִּכְתָב","in-writing"],["יָדִי","my-hand"],["אֲנִי","I"],["פוֹלוֹס","Paul"],["וְהִיא","and-she-was"],["הָאוֹת","the-sign"],["בְּכָל־הָאִגְּרוֹת","among-all-the-letters"],["כֵּן","thus"],["אָנֹכִי","I"],["כֹתֵב","writing"],["׃",""]] },
  { num:"יח", words:[["חֶסֶד","grace"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲדֹנֵינוּ","our-Lord"],["עִם־כֻּלְּכֶם","with-all-you"],["׃",""]] },
];
renderVerseSet(_2th_ch3Verses, '2th-ch3-verses');

})();
