// nt_verses/2th.js — 2 Thessalonians verse data
(function() {
var _2th_ch1Verses = [
  { num:"א", words:[["פּוֹלוֹס","Paul"],["וְסִלְוָנוֹס","and-Silvanus"],["וְטִימוֹתִיּוֹס","and-Timothy"],["אֶל־קְהִלַּת","to-the-church-of"],["הַתֶּסָּלוֹנִיקִיּים","the-Thessalonians"],["בֵּאלֹהִים","in-God"],["אָבִינוּ","our-father"],["וּבַאֲדֹנֵינוּ","and-in-our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ב", words:[["חֶסֶד","grace"],["לָכֶם","to-you"],["וְשָׁלוֹם","and-peace"],["מֵאֵת","from"],["אֱלֹהִים","God"],["אָבִינוּ","our-father"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ג", words:[["חַיָּבִים","are-bound"],["אֲנַחְנוּ","we"],["לְהוֹדוֹת","to-thank"],["תָּמִיד","always"],["לֵאלֹהִים","God"],["עֲלֵיכֶם","for-you"],["אַחַי","my-brothers"],["כָּרָאוּי","as-it-is-meet"],["כִּי","because"],["אֱמוּנַתְכֶם","your-faith"],["גָּדְלָה","groweth"],["מְאֹד","exceedingly"],["וְרַבָּה","and-aboundeth"],["אַהֲבַת","the-love-of"],["כֻּלְּכֶם","all-you"],["אִישׁ","a-man"],["לְרֵעֵהוּ","toward-another"],["׃",""]] },
  { num:"ד", words:[["עַד","until"],["שֶׁנִּתְהַלֵּל","that-we-glory"],["בָּכֶם","in-you"],["בִּקְהִלּוֹת","in-churches"],["אֱלֹהִים","God"],["עַל־סַבְלָנוּתְכֶם","for-your-patience"],["וְעַל־אֱמוּנַתְכֶם","and-upon-your-faith"],["בְּכׇל־הָרְדִיפוֹת","in-all-the-persecutions"],["וּבְכׇל־הַלַּחַץ","and-in-all-the-oppression"],["אֲשֶׁר","which"],["סְבַלְתֶּם","you-endure"],["׃",""]] },
  { num:"ה", words:[["לְאוֹת","a-manifest-token-of"],["צִדְקַת","righteousness-of"],["מִשְׁפַּט","judgment"],["אֱלֹהִים","God"],["לְמַעַן","in-order-that"],["תִּמָּצְאוּ","you-may-be-counted"],["רְאוּיִם","worthy"],["לְמַלְכוּת","of-reign-of"],["הָאֱלֹהִים","the-God"],["אֲשֶׁר","which"],["בַּעֲבוּרָהּ","for-which"],["תְּעֻנּוּ","you-also-suffer"],["׃",""]] },
  { num:"ו", words:[["בַּאֲשֶׁר","because"],["צַדִּיק","righteous"],["הוּא","he"],["הָאֱלֹהִים","the-God"],["לִגְמֹל","to-recompense"],["לַחַץ","tribulation"],["לְלֹחֲצֵיכֶם","to-them-that-trouble-you"],["׃",""]] },
  { num:"ז", words:[["וְלָכֶם","and-to-you"],["הַנִּלְחָצִים","who-are-troubled"],["רְוָחָה","rest"],["עִמָּנוּ","with-us"],["יָחַד","together"],["בְּהִגָּלוֹת","when-shall-be-revealed"],["הָאָדוֹן","the-Lord"],["יֵשׁוּעַ","Jesus"],["מִן־הַשָּׁמַיִם","from-heaven"],["עִם־מַלְאֲכֵי","with-the-angels-of"],["עֻזּוֹ","of-his-power"],["׃",""]] },
  { num:"ח", words:[["בְּאֵשׁ","with-fire"],["לֶֶהָבָה","flaming"],["לְהָשִׁיב","to-render"],["נָקָם","vengeance"],["לַאֲשֶׁר","unto-him-who"],["לֹא־יָדְעוּ","know-not"],["אֶת־הָאֱלֹהִים","God"],["וְלֹא","and-not"],["שָׁמְעוּ","obey"],["לִבְשׂוֹרַת","the-gospel-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ט", words:[["אֲשֶׁר","which"],["יִשְׂאוּ","shall-bear"],["מִשְׁפָּטָם","their-punishment"],["אָבְדַּן","destruction"],["עוֹלָם","everlasting"],["מֵאֵת","from"],["פְּנֵי","face-of"],["הָאָדוֹן","the-Lord"],["וּמֵהֲדַר","and-the-glory-of"],["גְּאוֹנוֹ","his-power"],["׃",""]] },
  { num:"י", words:[["בְּבֹאוֹ","when-he-shall-come"],["בַּיּוֹם","in-the-day"],["הַהוּא","that"],["לְהִכָּבֵד","to-be-glorified"],["בִּקְדשָׁיו","in-His-saints"],["וּלְהִתְפַּלֵּא","and-to-be-admired"],["בְּכׇל־הַמַּאֲמִינִים","in-all-the-believers"],["כִּי","because"],["הֶאֱמַנְתֶּם","was-believed"],["לְעֵדוּתֵנוּ","our-testimony"],["אֲלֵיכֶם","unto-you"],["׃",""]] },
  { num:"יא", words:[["לָזֹאת","to-this"],["גַּם־נִתְפַּלֵּל","also-we-pray"],["בַּעַדְכֶם","for-you"],["תָּמִיד","continually"],["אֲשֶׁר","which"],["יִתֵּן","would-count"],["אֶתְכֶם","you"],["אֱלֹהֵינוּ","our-God"],["רְאוּיִם","worthy"],["לְמַה־שֶּׁאַתֶּם","to-what-you-are"],["מְקֹרָאִים","called"],["וִימַלֵּא","and-fulfil"],["בְעֹז","with-power"],["כׇּל־חֶפְצְכֶם","all-your-desire"],["בַּטּוֹב","the-good"],["וְכׇל־מַעֲשֵׂה","and-all-work-of"],["אֱמוּנַתְכֶם","your-faith"],["׃",""]] },
  { num:"יב", words:[["לְמַעַן","in-order-that"],["יִכָּבֶד","be-glorified"],["בָּכֶם","in-you"],["שֵׁם","the-name-of"],["יֵשׁוּעַ","Jesus"],["אֲדֹנֵינוּ","our-Lord"],["וְאַתֶּם","and-you"],["תִּכָּבְדוּ","you-be-glorified"],["בוֹ","in-him"],["עַל־פִּי","according-to"],["חֶסֶד","grace"],["אֱלֹהֵינוּ","our-God"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
];
renderVerseSet(_2th_ch1Verses, '2th-ch1-verses');

var _2th_ch2Verses = [
  { num:"א", words:[["וְהִנְנוּ","and-behold-us"],["מְבַקְשִׁים","beseech"],["מִכֶּם","from-you"],["אֶחָי","brothers-my"],["עַל־אֹדוֹת","by"],["בִּיאַת","the-coming-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["וַאֲסִיפָתֵנוּ","and-our-gathering-together"],["אֵלָיו","to-him"],["׃",""]] },
  { num:"ב", words:[["אֲשֶׁר","which"],["לֹא־תִטָּרֵף","not-be-shaken"],["דַּעְתְּכֶם","in-mind"],["פִּתְאֹם","soon"],["וַאֲשֶׁר","and"],["לֹא","not"],["תִּבָּהֵלוּ","be-troubled"],["לֹא","neither"],["בְרוּחַ","by-spirit"],["וְלֹא","nor"],["בְדִבּוּר","by-word"],["וְלֹא","and-not"],["בְאִגֶּרֶת","in-letter"],["כְּאִלּוּ","as-though"],["שְׁלוּחָה","which has been sent"],["מֵאִתָּנוּ","from-among-us"],["לֵאמֹר","saying"],["הִגִּיעַ","is-at-hand"],["יוֹם","the-day-of"],["יְהוָֹה","the-Lord"],["׃",""]] },
  { num:"ג", words:[["אַל־יַתְעֶה","let-no-man-deceive"],["אֶתְכֶם","you"],["אִישׁ","a-man"],["בְּשׁוּם","by-any"],["אוֹפֶן","manner"],["כִּי","because"],["לֹא־יָבֹא","shall-not-come"],["בְּטֶרֶם","except"],["יִהְיֶה","come"],["בָרִאשׁוֹנָה","first"],["הַמֶּרֶד","a-falling-away"],["וְנִגְלָה","and-be-revealed"],["אִישׁ","the-man-of"],["הָחַטָּאָה","sin"],["בֶּן־הָאֲבַדּוֹן","the-son-of-perdition"],["׃",""]] },
  { num:"ד", words:[["הַמִּתְקוֹמֵם","who-opposeth"],["וְהַמִּתְרוֹמֵם","and-exalteth-himself"],["עַל־כׇּל־הַנִּקְרָא","above-all-that-is-called"],["אֵל","God"],["אוֹ","or"],["עֲבוֹדָה","that-is-worshipped"],["כִּי","because"],["גַם־יֵשֵׁב","so-that-he-sitteth"],["בְּהֵיכַל","in-the temple of"],["הָאֱלֹהִים","the-God"],["כֵּאלֹהִים","as-God"],["וּמַרְאֶה","shewing"],["אֶת־עַצְמוֹ","himself"],["כִּי","that"],["אֱלֹהִים","God"],["הוּא","he-is"],["׃",""]] },
  { num:"ה", words:[["הֲלֹא","do-not"],["תִזְכְּרוּ","you-remember"],["כִּי־בְעוֹד","because-in-yet"],["הֱיוֹתִי","being-I"],["אִתְּכֶם","with-you"],["אֵלֶּה","these"],["דִּבַּרְתִּי","I-told"],["אֲלֵיכֶם","unto-you"],["׃",""]] },
  { num:"ו", words:[["וְעַתָּה","and-now"],["יְדַעְתֶּם","you-know"],["אֶת־אֲשֶׁר","which"],["יִמְנָעֵהוּ","withholdeth"],["מִלְּהִגָּלוֹת","that-he-might-be-revealed"],["בְּעִתּוֹ","in-its-time"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["סוֹד","the-mystery-of"],["הָרֶשַׁע","iniquity"],["כְּבָר","already"],["הֵחֵלָּה","doth-work"],["פְעֻלָּתוֹ","its-working"],["רַק","only"],["שֶׁיּוּסַר","until-be-taken"],["מִתָּוֶךְ","out-of-the-way"],["הַמֹּנֵעַ","he-who-now-letteth"],["עַד־כֹּה","until-thus"],["׃",""]] },
  { num:"ח", words:[["וְאָז","and-then"],["יִגָּלֶה","shall-be-revealed"],["הָרָשָׁע","that-Wicked"],["אֲשֶׁר","whom"],["יְמִיתֶנּוּ","shall-consume"],["הָאָדוֹן","the-Lord"],["בְּרוּחַ","with-the-breath-of"],["שְׂפָתָיו","his-mouth"],["וְיַשְׁבִּיתֶנּוּ","and-shall-destroy"],["בְּהוֹפָעַת","with-the-brightness-of"],["בִּיאָתוֹ","his-coming"],["׃",""]] },
  { num:"ט", words:[["אֵת־אֲשֶׁר","which"],["יָבוֹא","shall-come"],["כְּפִי","according-to"],["פְּעֻלַּת","the-working-of"],["הַשָׂטָן","Satan"],["בְּרָב־כֹּחַ","with-all-power"],["וּבְאֹתוֹת","and-signs"],["וּבְמוֹפְתֵי","and-wonders-of"],["שָׁקֶר","lying"],["׃",""]] },
  { num:"י", words:[["וּבְכׇל־מִרְמַת","and-in-all-deceit-of"],["אָוֶן","iniquity"],["בָּאֹבְדִים","in-them-that-perish"],["תַּחַת","because"],["אֲשֶׁר","which"],["לֹא","not"],["קִבְּלוּ","received"],["אֶת־אַהֲבַת","the-love-of"],["הָאֱמֶת","the-truth"],["לְהִוָּשֵׁעַ","that-they-might-be-saved"],["׃",""]] },
  { num:"יא", words:[["וּבַעֲבוּר","and-because"],["זֹאת","this"],["יְשַׁלַּח","shall-send"],["לָהֶם","to-them"],["הָאֱלֹהִים","the-God"],["מַדּוּחֵי","strong-delusion"],["שָׁוְא","of-error"],["לְהַאֲמִין","that-they-should-believe"],["בַּשָּׁקֶר","in-the-falsehood"],["׃",""]] },
  { num:"יב", words:[["לְמַעַן","in-order-that"],["יִדּוֹנוּ","might-be-damned"],["כׇּל־אֲשֶׁר","all-who"],["לֹא־הֶאֱמִינוּ","believed-not"],["בָאֱמֶת","the-truth"],["וְרָצוּ","but-had-pleasure"],["בָּעַוְלָה","in-unrighteousness"],["׃",""]] },
  { num:"יג", words:[["אֲבָל","but"],["אֲנַחְנוּ","we"],["חַיָּבִים","are-bound"],["לְהוֹדוֹת","to-give-thanks"],["תָּמִיד","continually"],["לֵאלֹהִים","God"],["בַּעֲבוּרְכֶם","for-your-sakes"],["אַחַי","my-brothers"],["חֲבִיבֵי","my-beloved"],["הָאָדוֹן","the-Lord"],["אֲשֶׁר","which"],["מִבַּתְּחִלָּה","from-the-beginning"],["בָּחַר","chose"],["בָּכֶם","in-you"],["הָאֱלֹהִים","the-God"],["לִישׁוּעָה","unto-salvation"],["בִּקְדֻשַּׁת","with-the-holiness-of"],["הָרוּחַ","the-Spirit"],["וּבֶאֱמוּנַת","and-in-faith-of"],["הָאֱמֶת","the-true"],["׃",""]] },
  { num:"יד", words:[["לָזֹאת","to-this"],["קָרָא","he-called"],["אֶתְכֶם","you"],["בִּבְשׂוֹרָתֵנוּ","by-our-gospel"],["לְנַחֲלַת","for-the-inheritance-of"],["כְּבוֹד","the-glory-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"טו", words:[["לָכֵן","therefore"],["אַחַי","my-brothers"],["עִמְדוּ","stand-fast"],["וְהַחֲזִיקוּ","and-hold"],["בַקַּבָּלוֹת","the-traditions"],["אֲשֶׁר","which"],["לֻמַּדְתֶּם","you-have-been-taught"],["אִם","whether"],["בִּדְבָרֵנוּ","by-our-word"],["אִם","or"],["בְּאִגַּרְתֵּנוּ","in-our-epistle"],["׃",""]] },
  { num:"טז", words:[["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["וֵאלֹהֵינוּ","and-God-our"],["אָבִינוּ","our-father"],["אֲשֶׁר","which"],["אָהַב","hath-loved"],["אֹתָנוּ","us"],["וַיִּתֶּן־לָנוּ","and-hath-given-us"],["בְחַסְדּוֹ","in-His-lovingkindness"],["נֶחָמַת","consolation-of"],["עוֹלָם","eternal"],["וְתִקְוָה","and-hope"],["טוֹבָה","good"],["׃",""]] },
  { num:"יז", words:[["הוּא","he"],["יְנַחֵם","comfort"],["אֶת־לְבַבְכֶם","your-hearts"],["וִיכוֹנֵן","and-stablish"],["אֶתְכֶם","you"],["בְּכׇל־דָּבָר","in-every-word"],["וּמַעֲשֶׂה","and-work"],["טוֹב","good"],["׃",""]] },
];
renderVerseSet(_2th_ch2Verses, '2th-ch2-verses');

var _2th_ch3Verses = [
  { num:"א", words:[["וְעוֹד","and-again"],["אַחַי","my-brothers"],["הִתְפַּלֲלוּ","pray!"],["בַעֲדֵנוּ","for-us"],["אֲשֶׁר","which"],["יָרוּץ","may-have-free-course"],["דְּבַר","the-word-of"],["יְהוָֹה","the-Lord"],["וְיִכָּבֵד","and-be-glorified"],["כְּהִכָּבְדוֹ","even-as-it-is"],["בְקִרְבְּכֶם","among-you"],["׃",""]] },
  { num:"ב", words:[["וַאֲשֶׁר","and-whom"],["נִנָּצֵל","we-may-be-delivered"],["מִן־הָאֲנָשִׁים","from-the-men"],["הַתֹּעִים","unreasonable"],["וְהָרָעִים","and-wicked"],["כִּי","because"],["לֹא","not"],["לְכׇל־אָדָם","unto-all-men"],["הָאֱמוּנָה","have-faith"],["׃",""]] },
  { num:"ג", words:[["אֲבָל","but"],["נֶאֱמָן","faithful"],["הוּא","he"],["הָאָדוֹן","the-Lord"],["אֲשֶׁר","which"],["יְחַזֵּק","shall-stablish"],["אֶתְכֶם","you"],["וְיִשְׁמָרְכֶם","and-keep-you"],["מִן־הָרָע","from-that-which-is-evil"],["׃",""]] },
  { num:"ד", words:[["וַאֲנַחְנוּ","and-we-are"],["בְּטוּחִים","have-confidence"],["עֲלֵיכֶם","in-you"],["בַּאֲדֹנֵינוּ","in-the-Lord"],["שֶׁעֹשִׂים","that-you-do"],["אַתֶּם","you-are"],["כְּמִצְוָתֵנוּ","the-things-which-we-command"],["וְגַם־תּוֹסִיפוּ","and-will-do"],["לַעֲשׂוֹת","to-do"],["׃",""]] },
  { num:"ה", words:[["וְהָאָדוֹן","and-the-Lord"],["הוּא","he"],["יְיַשֵּׁר","direct"],["אֶת־לְבַבְכֶם","your-hearts"],["לְאַהֲבַת","to-love-of"],["הָאֱלֹהִים","the-God"],["וּלְסַבְלָנוּת","and-to-patience"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ו", words:[["וְהִנְנוּ","and-behold-us"],["מְצַוִּים","we-command"],["אֶתְכֶם","you"],["אַחִים","brothers"],["בְּשֵׁם","by-name"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲשֶׁר","which"],["תִּבָּדְלוּ","you-withdraw-yourselves"],["מִכׇּל־אָח","from-every-brother"],["מְעַקֵּשׁ","one who perverts"],["דְּרָכָיו","His-ways"],["וְאֵינֶנּוּ","and-there-is-not"],["מִתְהַלֵּךְ","walketh"],["עַל־פִּי","according-to"],["הַקַּבָּלָה","the-tradition"],["אֲשֶׁר","which"],["קִבֵּל","he-received"],["מֵאִתָּנוּ","from-among-us"],["׃",""]] },
  { num:"ז", words:[["הֲלֹא","do-not"],["אַתֶּם","you-are"],["יְדַעְתֶּם","you-know"],["שֶׁצְּרִיכִים","that-ought"],["אַתֶּם","you-are"],["לְהִתְהַלֵּךְ","to-walk"],["כָּמֹנוּ","like-us"],["כִּי","because"],["לֹא־הֶעֱוִינוּ","we-behaved-not-ourselves-disorderly"],["אֶת־דַּרְכֵּנוּ","journey-our"],["בְּתוֹכֲכֶם","among-you"],["׃",""]] },
  { num:"ח", words:[["גַּם","also"],["לֹא־אָכַלְנוּ","neither-did-we-eat"],["לֶחֶם","bread"],["אִישׁ","any-mans"],["חִנָּם","for-nought"],["כִּי","because"],["בְּעָמָל","in-misery"],["וּתְלָאָה","and-travail"],["לַיְלָה","night"],["וְיוֹמָם","and-day"],["יָגַעְנוּ","we-wrought"],["לְבִלְתִּי","to-not"],["הֱיוֹת","have"],["לְאִישׁ","for-a-man"],["מִכֶּם","from-you"],["לְמַשָׂא","chargeable"],["׃",""]] },
  { num:"ט", words:[["לֹא","not"],["מִפְּנֵי","because-of"],["שֶׁאֵין־לָנוּ","because-we-have-no"],["הָרְשׁוּת","power"],["הַזֹּאת","this"],["כִּי","but"],["אִם","rather"],["לָתֵת","to-give"],["אֹתָנוּ","us"],["לָכֶם","to-you"],["לְמוֹפֵת","an-ensample"],["לָלֶכֶת","to-go"],["בְּעִקְּבוֹתֵינוּ","in-the footprints of-our"],["׃",""]] },
  { num:"י", words:[["כִּי","because"],["גַּם־בִּהְיוֹתֵנוּ","also-when-were-we"],["אֶצְלְכֶם","with-you"],["צִוִּינוּ","we-commanded"],["אֶתְכֶם","you"],["לֵאמֹר","saying"],["אֲשֶׁר","which"],["לֹא","not"],["יִרְצֶה","is-pleasing"],["לַעֲשׂוֹת","work"],["גַּם־לֹא","neither"],["יֹאכֵל","shall-he-eat"],["׃",""]] },
  { num:"יא", words:[["כִּי","because"],["שָׁמַעְנוּ","we-hear"],["שֶׁיֵּשׁ","that-there-are"],["בָּכֶם","in-you"],["מְעַקְּשִׁים","disorderly"],["אָרְחֹתָם","their-ways"],["וְאֵינָם","and-are-not"],["עֹשִׂים","working"],["דָּבָר","at-all"],["וּמְבַלִּים","but-wasting"],["יְמֵיהֶם","their-days"],["בַּהֲבָלִים","in-the-futilities"],["׃",""]] },
  { num:"יב", words:[["וַאֲנָשִׁים","and-men"],["כָּאֵלֶּה","such-as-these"],["נְצַוֶּה","we-command"],["אוֹתָם","them"],["וְנַזְהִירֵם","and-exhort"],["בַּאֲדֹנֵינוּ","by-our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["לַעֲבֹד","that-they-work"],["בְּנַחַת","with-quietness"],["לְמַעַן","in-order-that"],["יֹאכְלוּ","they-may-eat"],["אֶת־לַחְמָם","their-own-bread"],["מִשֶּׁלָּהֶם","from-that-unto-them"],["׃",""]] },
  { num:"יג", words:[["וְאַתֶּם","but-you"],["אֶחָי","brothers-my"],["אַל־תִּתְרַפּוּ","be-not-weary"],["בַּעֲשׂוֹת","in-well-doing"],["הַטּוֹב","the-good"],["׃",""]] },
  { num:"יד", words:[["וְאִם","and-if"],["לֹא־יִשְׁמַע","obey-not"],["אִישׁ","a-man"],["אֶל־דְּבָרֵנוּ","to-our-word"],["בָּאִגֶּרֶת","in-the-letter"],["הַזֹּאת","this"],["אֹתוֹ","him"],["תִרְשְׁמוּ","note"],["לָכֶם","to-you"],["וְאַל־תִּתְעָרֲבוּ","and-have-no-company"],["עִמּוֹ","with-him"],["לְמַעַן","in-order-that"],["יֵבוֹשׁ","be-ashamed"],["׃",""]] },
  { num:"טו", words:[["אַךְ","but"],["לֹא־כְאֹיֵב","not-as-an-enemy"],["תַּחְשְׁבֻהוּ","count-him"],["כִּי","because"],["אִם־תּוֹכִיחֻהוּ","but-admonish-him"],["כְּאָח","like-a brother"],["׃",""]] },
  { num:"טז", words:[["וְהוּא","now"],["וַאֲדוֹן","the-Lord-of"],["הַשָּׁלוֹם","peace"],["הוּא","himself"],["יִתֵּן","give"],["לָכֶם","to-you"],["הַשָּׁלוֹם","the-peace"],["תָּמִיד","continually"],["וּבְכׇל־פָּנִים","by-all-means"],["יְהִי","let-this-be"],["הָאָדוֹן","the-Lord"],["עִם־כֻּלְּכֶם","with-all-you"],["׃",""]] },
  { num:"יז", words:[["שֹׁאֵל","the-salutation-of"],["לִשְׁלוֹמְכֶם","you"],["בִּכְתָב","by-the-hand-of"],["יָדִי","my-hand"],["אֲנִי","I"],["פוֹלוֹס","Paul"],["וְהִיא","which-is"],["הָאוֹת","the-token"],["בְּכׇל־הָאִגְּרוֹת","among-all-the-letters"],["כֵּן","thus"],["אָנֹכִי","I"],["כֹתֵב","writing"],["׃",""]] },
  { num:"יח", words:[["חֶסֶד","grace"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲדֹנֵינוּ","our-Lord"],["עִם־כֻּלְּכֶם","with-all-you"],["׃",""]] },
];
renderVerseSet(_2th_ch3Verses, '2th-ch3-verses');

})();
