// nt_verses/3jn.js — 3 John verse data
(function() {
var _3jn_ch1Verses = [
  { num:"א", words:[["הַזָּקֵן","the-elder"],["אֶל־גָּיוֹס","to-Gaius"],["יְדִידִי","my-beloved"],["אֲשֶׁר","which"],["אֲנִי","I"],["אֹהֵב","loves"],["אֹתוֹ","him"],["בֶּאֱמֶת","in-truth"],["׃",""]] },
  { num:"ב", words:[["יְדִידִי","my-beloved"],["רְצוֹנִי","my-desire"],["שֶׁיִּיטַב","that-it was good"],["לְךָ","for-you"],["לְכָל־דָּבָר","to-all-things"],["וְתִהְיֶה","and-is-to-come"],["בָרִיא","in-health"],["כְּטוֹב","like-good"],["לְנַפְשֶׁךָ","for-self-your"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["שָׂמַחְתִּי","I-rejoiced"],["מְאֹד","exceedingly"],["כַּאֲשֶׁר","when/as"],["בָּאוּ","came"],["אַחִים","brothers"],["וַיָּעִידוּ","and-testified"],["עַל־אֲמִתֶּךָ","upon-faithfulness-your"],["אֲשֶׁר","which"],["מִתְהַלֵּךְ","walking"],["אַתָּה","you"],["בָּאֱמֶת","in-truth"],["׃",""]] },
  { num:"ד", words:[["אֵין","there-is-no"],["לִי","to-me"],["שִׂמְחָה","joy"],["גְדוֹלָה","great"],["מִלִּשְׁמֹעַ","from-to-listen"],["אֶת־בָּנַי","[ACC]-my-sons"],["מִתְהַלְּכִים","walking"],["בָּאֱמֶת","in-truth"],["׃",""]] },
  { num:"ה", words:[["יְדִידִי","my-beloved"],["בֶּאֱמוּנָה","with-much-faith"],["כָּל־מַעֲשֶׂיךָ","all-Your-works"],["עִם־הָאַחִים","with-the-brethren"],["וְעִם־הָאֹרְחִים","and-equally with-the-travelers"],["׃",""]] },
  { num:"ו", words:[["אֲשֶׁר","which"],["הֵעִידוּ","testified"],["עַל־אַהֲבָתְךָ","upon-love-your"],["בִּפְנֵי","in-the-presence-of"],["הַקָּהָל","the-multitude"],["וְיָפֶה","and-fair"],["תַעֲשֶׂה","make"],["לְשַׁלַּח","by-letting go"],["אֹתָם","them"],["כָּרָאוּי","as-fitting"],["לִפְנֵי","before"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["לְמַעַן","in-order-that"],["שְׁמוֹ","his-name"],["יָצָאוּ","they went out"],["וְלֹא","and-not"],["לָקְחוּ","they-took"],["דָבָר","[thing]"],["מִן־הַגּוֹיִם","of-the-nations"],["׃",""]] },
  { num:"ח", words:[["עַל־כֵּן","therefore"],["עָלֵינוּ","over-us"],["לְקַבֵּל","to-receive"],["אֹתָם","them"],["לְמַעַן","in-order-that"],["נִהְיֶה","let-us-be"],["עֹזְרִים","help(pl)"],["לָאֱמֶת","to-the-truth"],["׃",""]] },
  { num:"ט", words:[["אֲנִי","I"],["כָתַבְתִּי","I-wrote"],["אֶל־הַקְּהִלָּה","unto-the-church"],["אֲבָל","but/however"],["דִּיּוֹטְרִיפַס","Diotrephes"],["הַמִּתְאַוֶּה","the-is coveting"],["לִהְיוֹת","to-be"],["לָהֶם","to-them"],["לְרֹאשׁ","the-head-of"],["אֵינֶנּוּ","it-is-not"],["מְקַבֵּל","from-received"],["אֹתָנוּ","us"],["׃",""]] },
  { num:"י", words:[["עַל־כֵּן","therefore"],["בְּבֹאִי","in-came-my"],["אַזְכִּיר","I will cause to be remembered"],["אֶת־מַעֲשָׂיו","[ACC]-His-works"],["אֲשֶׁר","which"],["הוּא","he"],["עֹשֶׂה","do"],["לְבַטֵּא","by-speaking rashly"],["עָלֵינוּ","over-us"],["דְּבָרִים","things"],["רָעִים","evil"],["וְלֹא","and-not"],["דַּי־לוֹ","is-sufficient-him"],["בָזֶה","in-this"],["כִּי","because"],["גַם","also"],["אֶת־הָאַחִים","[ACC]-the-brethren"],["לֹא","not"],["יְקַבֵּל","he-receives"],["וְיִמְנַע","and-none"],["אֶת־הַחֲפֵצִים","[ACC]-the-were-desirous"],["לְקַבְּלָם","obtain-them"],["וַיְגָרֲשֵׁם","and-he will drive out-them"],["מִתּוֹךְ","from-the-midst-of"],["הַקָּהָל","the-multitude"],["׃",""]] },
  { num:"יא", words:[["יְדִידִי","my-beloved"],["אַל־תֵּלֵךְ","do-not-should-go"],["בְּעִקְּבוֹת","in-the footprints of"],["הָרָעָה","the-evil"],["כִּי","because"],["אִם־בְּעִקְּבוֹת","if-in-the footprints of"],["הַטּוֹב","the-good"],["הָעֹשֶׂה","the-does"],["טוֹב","good"],["הוּא","he"],["מֵאֱלֹהִים","by-God"],["וְהָעֹשֶׂה","and-the-does"],["רַע","evil"],["לֹא","not"],["רָאָה","he-saw"],["אֶת־הָאֱלֹהִים","[ACC]-God"],["׃",""]] },
  { num:"יב", words:[["עַל־דְּמַטְרִיּוֹס","concerning-Demetrius"],["הֵעִידוּ","testified"],["הַכֹּל","all-the"],["וְגַם־הָאֱמֶת","and-also-the-true"],["עַצְמָהּ","strength"],["וְגַם־אֲנַחְנוּ","and-also-we"],["מְעִידִים","testify"],["עָלָיו","upon-him"],["וִידַעְתֶּם","and-you-shall-know"],["כִּי","because"],["עֵדוּתֵנוּ","testimony-of-us"],["נֶאֱמָנָה","is reliable"],["׃",""]] },
  { num:"יג", words:[["הַרְבֵּה","much"],["יֶשׁ־לִי","has-to-me"],["לִכְתֹּב","to-write"],["וְלֹא","and-not"],["חָפַצְתִּי","I-desire"],["לִכְתֹּב","to-write"],["אֵלֶיךָ","to-you"],["בִּדְיוֹ","with-ink"],["וּבְקוֹלָמוֹס","and-with-a-pen"],["׃",""]] },
  { num:"יד", words:[["אֲבָל","but/however"],["אֲקַוֶּה","I-hope"],["לִרְאוֹתְךָ","to-your-seeing"],["בִּמְהֵרָה","soon"],["וּפֶה","and-a mouth"],["אֶל־פֶּה","to-mouth"],["נְדַבֵּר","speak"],["׃",""]] },
  { num:"טו", words:[["שָׁלוֹם","peace"],["לָךְ","to-you"],["הָרֵעִים","the-friends"],["שֹׁאֲלִים","asking"],["לִשְׁלוֹמֶךָ","to-your-peace"],["שְׁאַל","ask"],["לִשְׁלוֹם","for-the-welfare-of"],["הָרֵעִים","the-friends"],["לְאִישׁ","for-a-man"],["אִישׁ","a-man"],["בִּשְׁמוֹ","in-His-name"],["׃",""]] },
];
renderVerseSet(_3jn_ch1Verses, '3jn-ch1-verses');

})();
