// nt_verses/3jn.js — 3 John verse data
(function() {
var _3jn_ch1Verses = [
  { num:"א", words:[["הַזָּקֵן","the-elder"],["אֶל־גָּיוֹס","unto-Gaius"],["יְדִידִי","the-wellbeloved"],["אֲשֶׁר","whom"],["אֲנִי","I"],["אֹהֵב","love"],["אֹתוֹ","him"],["בֶּאֱמֶת","in-the-truth"],["׃",""]] },
  { num:"ב", words:[["יְדִידִי","beloved"],["רְצוֹנִי","I-wish"],["שֶׁיִּיטַב","that-may-prosper"],["לְךָ","thou"],["לְכָל־דָּבָר","above-all-things"],["וְתִהְיֶה","and-be"],["בָרִיא","in-health"],["כְּטוֹב","even-as-prospereth"],["לְנַפְשֶׁךָ","thy-soul"],["׃",""]] },
  { num:"ג", words:[["כִּי","for"],["שָׂמַחְתִּי","I-rejoiced"],["מְאֹד","greatly"],["כַּאֲשֶׁר","when"],["בָּאוּ","came"],["אַחִים","the-brethren"],["וַיָּעִידוּ","and-testified"],["עַל־אֲמִתֶּךָ","of-thy-truth"],["אֲשֶׁר","even-as"],["מִתְהַלֵּךְ","walkest"],["אַתָּה","thou"],["בָּאֱמֶת","in-the-truth"],["׃",""]] },
  { num:"ד", words:[["אֵין","there-is-no"],["לִי","to-me"],["שִׂמְחָה","joy"],["גְדוֹלָה","greater"],["מִלִּשְׁמֹעַ","than-to-hear"],["אֶת־בָּנַי","my-children"],["מִתְהַלְּכִים","walk"],["בָּאֱמֶת","in-truth"],["׃",""]] },
  { num:"ה", words:[["יְדִידִי","beloved"],["בֶּאֱמוּנָה","faithfully"],["כָּל־מַעֲשֶׂיךָ","thou-doest-all-thy-works"],["עִם־הָאַחִים","to-the-brethren"],["וְעִם־הָאֹרְחִים","and-to-strangers"],["׃",""]] },
  { num:"ו", words:[["אֲשֶׁר","which"],["הֵעִידוּ","have-borne-witness"],["עַל־אַהֲבָתְךָ","of-thy-charity"],["בִּפְנֵי","before"],["הַקָּהָל","the-church"],["וְיָפֶה","and-well"],["תַעֲשֶׂה","thou-shalt-do"],["לְשַׁלַּח","to-bring-forward"],["אֹתָם","them"],["כָּרָאוּי","as-is-fitting"],["לִפְנֵי","before"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["לְמַעַן","for-the-sake-of"],["שְׁמוֹ","his-name"],["יָצָאוּ","they-went-forth"],["וְלֹא","and-not"],["לָקְחוּ","took"],["דָבָר","anything"],["מִן־הַגּוֹיִם","of-the-Gentiles"],["׃",""]] },
  { num:"ח", words:[["עַל־כֵּן","therefore"],["עָלֵינוּ","we-ought"],["לְקַבֵּל","to-receive"],["אֹתָם","them"],["לְמַעַן","that"],["נִהְיֶה","we-might-be"],["עֹזְרִים","fellowhelpers"],["לָאֱמֶת","to-the-truth"],["׃",""]] },
  { num:"ט", words:[["אֲנִי","I"],["כָתַבְתִּי","wrote"],["אֶל־הַקְּהִלָּה","unto-the-church"],["אֲבָל","but"],["דִּיּוֹטְרִיפַס","Diotrephes"],["הַמִּתְאַוֶּה","who-loveth"],["לִהְיוֹת","to-have"],["לָהֶם","among-them"],["לְרֹאשׁ","the-preeminence"],["אֵינֶנּוּ","not"],["מְקַבֵּל","receiveth"],["אֹתָנוּ","us"],["׃",""]] },
  { num:"י", words:[["עַל־כֵּן","wherefore"],["בְּבֹאִי","if-I-come"],["אַזְכִּיר","I-will-remember"],["אֶת־מַעֲשָׂיו","his-deeds"],["אֲשֶׁר","which"],["הוּא","he"],["עֹשֶׂה","doeth"],["לְבַטֵּא","prating"],["עָלֵינוּ","against-us"],["דְּבָרִים","words"],["רָעִים","malicious"],["וְלֹא","and-not"],["דַּי־לוֹ","content"],["בָזֶה","therewith"],["כִּי","but"],["גַם","also"],["אֶת־הָאַחִים","the-brethren"],["לֹא","not"],["יְקַבֵּל","doth-he-receive"],["וְיִמְנַע","and-forbiddeth"],["אֶת־הַחֲפֵצִים","them-that-would"],["לְקַבְּלָם","receive-them"],["וַיְגָרֲשֵׁם","and-casteth-them-out"],["מִתּוֹךְ","of"],["הַקָּהָל","the-church"],["׃",""]] },
  { num:"יא", words:[["יְדִידִי","beloved"],["אַל־תֵּלֵךְ","follow-not"],["בְּעִקְּבוֹת","the-footsteps-of"],["הָרָעָה","that-which-is-evil"],["כִּי","but"],["אִם־בְּעִקְּבוֹת","the-footsteps-of"],["הַטּוֹב","that-which-is-good"],["הָעֹשֶׂה","he-that-doeth"],["טוֹב","good"],["הוּא","is"],["מֵאֱלֹהִים","of-God"],["וְהָעֹשֶׂה","but-he-that-doeth"],["רַע","evil"],["לֹא","not"],["רָאָה","hath-seen"],["אֶת־הָאֱלֹהִים","God"],["׃",""]] },
  { num:"יב", words:[["עַל־דְּמַטְרִיּוֹס","of-Demetrius"],["הֵעִידוּ","have-borne-witness"],["הַכֹּל","all-men"],["וְגַם־הָאֱמֶת","and-also-the-truth"],["עַצְמָהּ","itself"],["וְגַם־אֲנַחְנוּ","yea-and-we-also"],["מְעִידִים","bear-record"],["עָלָיו","of-him"],["וִידַעְתֶּם","and-you-know"],["כִּי","that"],["עֵדוּתֵנוּ","our-record"],["נֶאֱמָנָה","is-true"],["׃",""]] },
  { num:"יג", words:[["הַרְבֵּה","many-things"],["יֶשׁ־לִי","I-have"],["לִכְתֹּב","to-write"],["וְלֹא","but-not"],["חָפַצְתִּי","I-would"],["לִכְתֹּב","write"],["אֵלֶיךָ","unto-thee"],["בִּדְיוֹ","with-ink"],["וּבְקוֹלָמוֹס","and-pen"],["׃",""]] },
  { num:"יד", words:[["אֲבָל","but"],["אֲקַוֶּה","I-trust"],["לִרְאוֹתְךָ","to-see-thee"],["בִּמְהֵרָה","shortly"],["וּפֶה","and-face"],["אֶל־פֶּה","to-face"],["נְדַבֵּר","we-shall-speak"],["׃",""]] },
  { num:"טו", words:[["שָׁלוֹם","peace"],["לָךְ","be-to-thee"],["הָרֵעִים","the-friends"],["שֹׁאֲלִים","salute"],["לִשְׁלוֹמֶךָ","thee"],["שְׁאַל","greet"],["לִשְׁלוֹם","the-welfare-of"],["הָרֵעִים","the-friends"],["לְאִישׁ","each"],["אִישׁ","one"],["בִּשְׁמוֹ","by-his-name"],["׃",""]] },
];
renderVerseSet(_3jn_ch1Verses, '3jn-ch1-verses');

})();
