// nt_verses/jude.js — Jude verse data
(function() {
var jude_ch1Verses = [
  { num:"א", words:[["יְהוּדָה","Jude"],["עֶבֶד","the-servant-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["וַאֲחִי","and-brother-of"],["יַעֲקֹב","James"],["אֶל־הַמְקֹרָאִים","to-the-called"],["אֲשֶׁר","who"],["הֵם","are"],["אֲהוּבִים","beloved"],["בֵּאלֹהִים","in-God"],["הָאָב","the-Father"],["וּשְׁמוּרִים","and-preserved"],["לְיֵשׁוּעַ","in-Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ב", words:[["רַחֲמִים","mercy"],["וְשָׁלוֹם","and-peace"],["וְאַהֲבָה","and-love"],["יִהְיוּ","be"],["לָכֶם","unto-you"],["לְמַכְבִּיר","multiplied"],["׃",""]] },
  { num:"ג", words:[["חֲבִיבַי","beloved"],["בְּשָׁקְדִי","when-I-gave-diligence"],["לִכְתֹּב","to-write"],["אֲלֵיכֶם","unto-you"],["עַל־דְּבַר","of"],["הַתְּשׁוּעָה","the-salvation"],["הָאַחַת","common"],["לְכֻלָּנוּ","to-us-all"],["הֱצִיקַתְנִי","constrained-me"],["רוּחִי","my-spirit"],["לְעוֹרֵר","to-exhort"],["אֶתְכֶם","you"],["בְּמִכְתָּב","in-writing"],["אֲשֶׁר","that"],["תִלָּחֲמוּ","you-should-contend"],["לָאֱמוּנָה","for-the-faith"],["הַמְּסוּרָה","which-was-delivered"],["פַּעַם","once"],["אַחַת","for-all"],["לַקְּדוֹשִׁים","unto-the-saints"],["׃",""]] },
  { num:"ד", words:[["כִּי","for"],["הִתְגַּנְּבוּ","crept-in"],["לָבוֹא","secretly"],["אֲנָשִׁים","certain-men"],["אֲשֶׁר","who"],["נִגְזַר","was-ordained"],["דִּינָם","their-condemnation"],["מֵאָז","of-old"],["אַנְשֵׁי","men-of"],["רֶשַׁע","ungodliness"],["הַהֹפְכִים","turning"],["אֶת־חֶסֶד","the-grace-of"],["אֱלֹהֵינוּ","our-God"],["לְזִמָּה","into-lasciviousness"],["וְכֹפְרִים","and-denying"],["בֵּאלֹהִים","God"],["הַמּשֵׁל","the-Master"],["הַיָּחִיד","the-only"],["וּבַאֲדֹנֵינוּ","and-our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ה", words:[["וְיֵשׁ","and-it-is-in"],["אֶת־נַפְשִׁי","my-soul"],["לְהַזְכִּיר","to-put-in-remembrance"],["אֶתְכֶם","you"],["אֶת־אֲשֶׁר","that-which"],["כְּבָר","already"],["יְדַעְתֶּם","you-know"],["כִּי","that"],["הוֹשִׁיעַ","saved"],["יְהוָֹה","the-Lord"],["אֶת־הָעָם","the-people"],["מִמִּצְרַיִם","out-of-Egypt"],["וַיַּשְׁמֵד","destroyed"],["אַחַר","after"],["כֵּן","that"],["אֶת־אֲשֶׁר","them-that"],["לֹא","not"],["הֶאֱמִינוּ","believed"],["׃",""]] },
  { num:"ו", words:[["וְהַמַּלְאָכִים","and-the-angels"],["אֲשֶׁר","which"],["לֹא־שָׁמְרוּ","kept-not"],["אֶת־מִשְׂרָתָם","their-first-estate"],["כִּי","but"],["אִם־עָזְבוּ","left"],["אֶת־מְעוֹנָם","their-own-habitation"],["שְׁמָרָם","he-hath-reserved"],["בְּמוֹסְרוֹת","in-chains-of"],["עוֹלָם","everlasting"],["בַּאֲפֵלָה","under-darkness"],["לְמִשְׁפַּט","unto-the-judgment-of"],["הַיּוֹם","the-day"],["הַגָּדוֹל","great"],["׃",""]] },
  { num:"ז", words:[["כַּאֲשֶׁר","even-as"],["נִהְיוּ","are-set-forth"],["לְמָשָׁל","for-an-example"],["סְדוֹם","Sodom"],["וַעֲמֹרָה","and-Gomorrha"],["וּבְנֹתֵיהֶן","and-their-daughter-cities"],["אֲשֶׁר","which"],["הִזְנוּ","committed-fornication"],["כְּמוֹהֶם","like-them"],["וַתֵּלַכְנָה","and-going"],["אַחֲרֵי","after"],["בָּשָׂר","flesh"],["זָר","strange"],["כִּי־נִמְסְרוּ","for-they-are-given"],["לְמוּסַר","to-the-punishment-of"],["אֵשׁ","fire"],["עוֹלָם","eternal"],["׃",""]] },
  { num:"ח", words:[["וְכֵן","likewise"],["בַּעֲלֵי","the-masters-of"],["הַחֲלֹמוֹת","dreams"],["הָאֵלֶּה","these"],["מְטַמְּאִים","defile"],["אֶת־הַבָּשָׂר","the-flesh"],["וְאֶת־הַמֶּמְשָׁלָה","and-dominion"],["יְנָאֲצוּ","despise"],["וְאֶת־הַשְּׂרָרוֹת","and-dignities"],["יְחָרֵפוּ","speak-evil-of"],["׃",""]] },
  { num:"ט", words:[["וּמִיכָאֵל","yet-Michael"],["שַׂר","the-prince-of"],["הַמַּלְאָכִים","the-angels"],["בְּהִתְוַכְּחוֹ","when-contending"],["עִם־הַשָּׂטָן","with-the-devil"],["וַיָּרֶב","and-disputed"],["אִתּוֹ","with-him"],["עַל־אֹדוֹת","about"],["גְּוִיַּת","the-body-of"],["מֹשֶׁה","Moses"],["לֹא־מְלָאוֹ","filled-not"],["לִבּוֹ","his-heart"],["לַחֲרֹץ","to-pronounce"],["מִשְׁפַּט","a-judgment-of"],["גִּדּוּפִים","railing"],["כִּי","but"],["אִם־אָמַר","said"],["יִגְעַר","rebuke"],["יְהוָֹה","the-Lord"],["בָּךְ","thee"],["׃",""]] },
  { num:"י", words:[["וְאֵלֶּה","but-these"],["מְחָרְפִים","speak-evil-of"],["אֶת־אֲשֶׁר","those-things-which"],["לֹא־יָדָעוּ","they-know-not"],["וּבַדְּבָרִים","and-what-things"],["אֲשֶׁר","which"],["יָבִינוּ","they-know"],["מֵחָק־טִבְעָם","naturally"],["כַּבְּהֵמוֹת","as-beasts"],["הַסְּכָלוֹת","brute"],["בָּהֵמָּה","in-those-things"],["יַשְׁחִיתוּ","they-corrupt"],["אֶת־נַפְשָׁם","themselves"],["׃",""]] },
  { num:"יא", words:[["אוֹי","woe"],["לָהֶם","unto-them"],["כִּי־בְדֶרֶךְ","for-in-the-way-of"],["קַיִן","Cain"],["הָלָכוּ","they-have-gone"],["וַיִּדַּחוּ","and-ran-greedily"],["בְּמַדּוּחֵי","after-the-error-of"],["בִלְעָם","Balaam"],["עֵקֶב","for"],["שָׂכָר","reward"],["וּבִמְרִי","and-in-the-gainsaying-of"],["קֹרַח","Korah"],["אָבָדוּ","perished"],["׃",""]] },
  { num:"יב", words:[["הֲלֹא","are-they-not"],["צוּרֵי","rocks-of"],["מִכְשׁוֹל","offence"],["הֵמָּה","they"],["בִּסְעוּדֹת","in-the-feasts-of"],["אַהֲבָה","charity"],["שֶׁלָּכֶם","your"],["אֹכְלִים","feeding"],["וְשֹׁתִים","and-drinking"],["עִמָּכֶם","with-you"],["בְּקַלּוּת","without"],["רֹאשׁ","fear"],["וְרֹעִים","feeding"],["אֶת־נַפְשָׁם","themselves"],["עָבִים","clouds"],["הֵם","they-are"],["בְּלִי","without"],["מַיִם","water"],["נִדָּפִים","carried-about"],["מִפְּנֵי","of"],["רוּחַ","winds"],["עֲצֵי־חֹרֶף","autumn-trees"],["בְּאֵין","without"],["פְּרִי","fruit"],["אֲשֶׁר","which"],["מֵתוּ","are-dead"],["פַעֲמַיִם","twice"],["וְנֶעֱקָרוּ","plucked-up-by-the-roots"],["׃",""]] },
  { num:"יג", words:[["מִשְׁבְּרֵי־יָם","waves-of-the-sea"],["עַזִּים","raging"],["אֲשֶׁר","which"],["יִגְרְשׁוּ","foam-out"],["בָשְׁתָּם","their-own-shame"],["כֹּכָבִים","stars"],["תֹּעִים","wandering"],["אֲשֶׁר־חשֶׁךְ","whose-darkness"],["אֲפֵלָה","of-blackness"],["צָפוּן","is-reserved"],["לָהֶם","for-them"],["עֲדֵי־עַד","for-ever"],["׃",""]] },
  { num:"יד", words:[["וְגַם־חֲנוֹךְ","and-also-Enoch"],["הַשְּׁבִיעִי","the-seventh"],["לְאָדָם","from-Adam"],["נִבָּא","prophesied"],["עֲלֵיהֶם","of-these"],["לֵאמֹר","saying"],["הִנֵּה","behold"],["יְהוָֹה","the-Lord"],["בָּא","cometh"],["בְּרִבֲבֹת","with-ten-thousands-of"],["קְדֹשָׁיו","his-saints"],["׃",""]] },
  { num:"טו", words:[["לַעֲשׂוֹת","to-execute"],["שְׁפָטִים","judgment"],["בְּכֻלָּם","upon-all"],["וּלְהוֹכִיחַ","and-to-convince"],["כׇּל־רִשְׁעֵי־אֶרֶץ","all-the-ungodly"],["עַל־כׇּל־מַעֲשֵׂי","of-all-the-deeds-of"],["רִשְׁעָתָם","their-ungodliness"],["וְעַל־כׇּל־הַקָּשׁוֹת","and-of-all-the-hard-speeches"],["אֲשֶׁר","which"],["דִּבְּרוּ","have-spoken"],["עָלָיו","against-him"],["חַטָּאִים","sinners"],["אַנְשֵׁי","the-men-of"],["רֶשַׁע","ungodliness"],["׃",""]] },
  { num:"טז", words:[["אֵלֶּה","these"],["הֵם","are"],["הָרֹגְנִים","murmurers"],["וְהַמִּתְאוֹנֲנִים","and-complainers"],["הַהֹלְכִים","walking"],["אַחֲרֵי","after"],["תַאֲוֹתֵיהֶם","their-own-lusts"],["אֲשֶׁר","and"],["פִּיהֶם","their-mouth"],["יְדַבֵּר","speaketh"],["עָתָק","great-swelling-words"],["הֹדְרֵי","admiring"],["פָנִים","persons"],["עֵקֶב","because-of"],["שֹׁחַד","advantage"],["׃",""]] },
  { num:"יז", words:[["וְאַתֶּם","but-you"],["חֲבִיבַי","beloved"],["זִכְרוּ","remember"],["אֶת־הַדְּבָרִים","the-words"],["הַנֶּאֱמָרִים","which-were-spoken"],["מִקֶּדֶם","before"],["בְּיַד","by"],["שְׁלִיחֵי","the-apostles-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"יח", words:[["בְּדַבְּרָם","how-that-they-said"],["אֲלֵיכֶם","unto-you"],["לֵאמֹר","saying"],["הִנֵּה","behold"],["בְּאַחֲרִית","in-the-last"],["הַיָּמִים","time"],["יָבֹאוּ","there-should-be"],["לֵצִים","mockers"],["הַהֹלְכִים","who-walk"],["אַחֲרֵי","after"],["תַּאֲוֹת","the-lusts-of"],["רִשְׁעָם","their-ungodliness"],["׃",""]] },
  { num:"יט", words:[["אֵלֶּה","these"],["הֵם","be-they"],["הַפֹּרְשִׁים","who-separate-themselves"],["מִן־הַצִּבּוּר","from-the-congregation"],["בַּעֲלֵי","men-of"],["נֶפֶשׁ","the-natural-soul"],["וְרוּחַ","and-the-Spirit"],["אֵין","is-not"],["בָּהֶם","in-them"],["׃",""]] },
  { num:"כ", words:[["וְאַתֶּם","but-you"],["חֲבִיבַי","beloved"],["הִבָּנוּ","build-up-yourselves"],["בֶּאֱמוּנַתְכֶם","on-your-faith"],["הַנַּעֲלָה","which-is-exalted"],["עַל־כֹּל","above-all"],["בִּקְדֻשָּׁתָהּ","in-its-holiness"],["וְהִתְפַּלֲלוּ","praying"],["בְּרוּחַ","in-the-Spirit-of"],["הַקֹּדֶשׁ","the-Holy"],["׃",""]] },
  { num:"כא", words:[["וּשְׁמַרְתֶּם","keep"],["אֶת־נַפְשֹׁתֵיכֶם","yourselves"],["בְּאַהֲבַת","in-the-love-of"],["אֱלֹהִים","God"],["וְחִכִּיתֶם","looking-for"],["לְרַחֲמֵי","the-mercy-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["לְחַיֵּי","unto-life-of"],["עוֹלָם","eternal"],["׃",""]] },
  { num:"כב", words:[["הַבְדִּילוּ","make-a-difference-with"],["אֶת־אֵלֶּה","these"],["וְהִתְנַהֲגוּ","and-deal"],["עִמָּהֶם","with-them"],["בְּרַחֲמִים","in-compassion"],["׃",""]] },
  { num:"כג", words:[["וְאֶת־אֵלֶּה","and-others"],["תּוֹשִׁיעוּ","save"],["בְאֵימָה","with-fear"],["וְחִלַּצְתֶּם","pulling"],["אֹתָם","them"],["מִתּוֹךְ","out-of"],["הָאֵשׁ","the-fire"],["וּמְאַסְתֶּם","hating"],["גַּם־אֶת־הַלְּבוּשׁ","even-the-garment"],["הַמְגֹאָל","spotted"],["בְּחֶלְאַת","by-the-filth-of"],["הַבָּשָׂר","the-flesh"],["׃",""]] },
  { num:"כד", words:[["וַאֲשֶׁר","now-unto-him-that"],["יָכוֹל","is-able"],["לִשְׁמָרְכֶם","to-keep-you"],["מִמִּכְשׁוֹל","from-falling"],["וּלְהַעֲמִיד","and-to-present"],["אֶתְכֶם","you"],["בְּשָׂשׂוֹן","with-exceeding-joy"],["תְּמִימִים","faultless"],["לִפְנֵי","before"],["כְבוֹדוֹ","his-glory"],["׃",""]] },
  { num:"כה", words:[["הָאֱלֹהִים","the-God"],["הֶחָכָם","wise"],["הַיָּחִיד","only"],["הַמּוֹשִׁיע","who-saveth"],["אֹתָנוּ","us"],["בְּיֵשׁוּעַ","by-Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲדֹנֵינוּ","our-Lord"],["לוֹ","to-him"],["הַכָּבוֹד","the-glory"],["וְהַגְּדֻלָּה","and-majesty"],["וְהָעֹז","and-might"],["וְהַמֶּמְשָׁלָה","and-dominion"],["לִפְנֵי","before"],["כׇל־עוֹלָם","all-ages"],["גַּם","both"],["עַתָּה","now"],["גַּם","and"],["לְעוֹלְמֵי","for"],["עַד","evermore"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(jude_ch1Verses, 'jude-ch1-verses');

})();
