// nt_verses/jude.js — Jude verse data
(function() {
var jude_ch1Verses = [
  { num:"א", words:[["יְהוּדָה","Judah/Judas"],["עֶבֶד","the-servant-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["וַאֲחִי","and-brother-of"],["יַעֲקֹב","James/Jacob"],["אֶל־הַמְקֹרָאִים","to-the-called"],["אֲשֶׁר","which"],["הֵם","they"],["אֲהוּבִים","beloved"],["בֵּאלֹהִים","in-God"],["הָאָב","the-Father"],["וּשְׁמוּרִים","and-preserved"],["לְיֵשׁוּעַ","to-Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ב", words:[["רַחֲמִים","mercy"],["וְשָׁלוֹם","and-peace"],["וְאַהֲבָה","and-love"],["יִהְיוּ","shall-be"],["לָכֶם","to-you"],["לְמַכְבִּיר","to-abundance"],["׃",""]] },
  { num:"ג", words:[["חֲבִיבַי","my-beloved"],["בְּשָׁקְדִי","in-my-diligence"],["לִכְתֹּב","to-write"],["אֲלֵיכֶם","unto-you"],["עַל־דְּבַר","upon-the-word-of"],["הַתְּשׁוּעָה","the-deliverance"],["הָאַחַת","the-one"],["לְכֻלָּנוּ","to-all of-us"],["הֱצִיקַתְנִי","it has constrained-me"],["רוּחִי","my-spirit"],["לְעוֹרֵר","to-it-stirs-up"],["אֶתְכֶם","you"],["בְּמִכְתָּב","in-writing"],["אֲשֶׁר","which"],["תִלָּחֲמוּ","you must fight"],["לָאֱמוּנָה","to-the-faith"],["הַמְּסוּרָה","the-delivered"],["פַּעַם","once"],["אַחַת","one"],["לַקְּדוֹשִׁים","for-the-saints"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["הִתְגַּנְּבוּ","the-steal(they)"],["לָבוֹא","to-come"],["אֲנָשִׁים","men"],["אֲשֶׁר","which"],["נִגְזַר","He-was-cut-off"],["דִּינָם","their-judgment"],["מֵאָז","since"],["אַנְשֵׁי","the-men-of"],["רֶשַׁע","wickedness"],["הַהֹפְכִים","O those-who turn"],["אֶת־חֶסֶד","[ACC]-the-grace-of"],["אֱלֹהֵינוּ","our-God"],["לְזִמָּה","to-lewdness"],["וְכֹפְרִים","and-denying"],["בֵּאלֹהִים","in-God"],["הַמּשֵׁל","the-ruler"],["הַיָּחִיד","the-Only-Begotten"],["וּבַאֲדֹנֵינוּ","and-in-our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ה", words:[["וְיֵשׁ","and-there-was"],["אֶת־נַפְשִׁי","[ACC]-my-soul"],["לְהַזְכִּיר","to-bring-to-remembrance"],["אֶתְכֶם","you"],["אֶת־אֲשֶׁר","ACC-that-which"],["כְּבָר","already-come"],["יְדַעְתֶּם","you-know"],["כִּי","because"],["הוֹשִׁיעַ","save!"],["יְהוָֹה","the-Lord"],["אֶת־הָעָם","ACC-the-people"],["מִמִּצְרַיִם","out-of-Egypt"],["וַיַּשְׁמֵד","and-he destroyed"],["אַחַר","after"],["כֵּן","thus"],["אֶת־אֲשֶׁר","ACC-that-which"],["לֹא","not"],["הֶאֱמִינוּ","did-they-believe"],["׃",""]] },
  { num:"ו", words:[["וְהַמַּלְאָכִים","and-the-angels"],["אֲשֶׁר","which"],["לֹא־שָׁמְרוּ","not-kept"],["אֶת־מִשְׂרָתָם","[ACC]-their-domain"],["כִּי","because"],["אִם־עָזְבוּ","[compound]-left"],["אֶת־מְעוֹנָם","[ACC]-their-habitation"],["שְׁמָרָם","preserved-them"],["בְּמוֹסְרוֹת","in-the-bands-of"],["עוֹלָם","eternal"],["בַּאֲפֵלָה","in-darkness"],["לְמִשְׁפַּט","for-the judgment of"],["הַיּוֹם","the-day"],["הַגָּדוֹל","the-great"],["׃",""]] },
  { num:"ז", words:[["כַּאֲשֶׁר","when/as"],["נִהְיוּ","they-become"],["לְמָשָׁל","a byword"],["סְדוֹם","Sodom"],["וַעֲמֹרָה","and-Gomorrah"],["וּבְנֹתֵיהֶן","and-their-daughters"],["אֲשֶׁר","which"],["הִזְנוּ","they will prostitute themselves"],["כְּמוֹהֶם","like-them"],["וַתֵּלַכְנָה","and-walk"],["אַחֲרֵי","after"],["בָּשָׂר","the-flesh"],["זָר","strange"],["כִּי־נִמְסְרוּ","because-had-been-handed-down"],["לְמוּסַר","to-the-chastisement-of"],["אֵשׁ","fire"],["עוֹלָם","eternal"],["׃",""]] },
  { num:"ח", words:[["וְכֵן","and-so"],["בַּעֲלֵי","they"],["הַחֲלֹמוֹת","the-dreams"],["הָאֵלֶּה","these"],["מְטַמְּאִים","from-unclean"],["אֶת־הַבָּשָׂר","[ACC]-the-flesh"],["וְאֶת־הַמֶּמְשָׁלָה","and-[ACC]-the-government"],["יְנָאֲצוּ","they-despise"],["וְאֶת־הַשְּׂרָרוֹת","and-[ACC]-the-dignities"],["יְחָרֵפוּ","they-shall-revile"],["׃",""]] },
  { num:"ט", words:[["וּמִיכָאֵל","and-Michael"],["שַׂר","the-king's-captain"],["הַמַּלְאָכִים","the-angels"],["בְּהִתְוַכְּחוֹ","in-to argue-his"],["עִם־הַשָּׂטָן","with-the-Adversary"],["וַיָּרֶב","and-he-pleaded"],["אִתּוֹ","with-him"],["עַל־אֹדוֹת","upon-concerning"],["גְּוִיַּת","the-body-of"],["מֹשֶׁה","Moses"],["לֹא־מְלָאוֹ","not-it has filled-him"],["לִבּוֹ","his-heart"],["לַחֲרֹץ","to-decide"],["מִשְׁפַּט","judgment"],["גִּדּוּפִים","blasphemies"],["כִּי","because"],["אִם־אָמַר","[compound]-said"],["יִגְעַר","may he rebuke"],["יְהוָֹה","the-Lord"],["בָּךְ","in-You"],["׃",""]] },
  { num:"י", words:[["וְאֵלֶּה","and-these"],["מְחָרְפִים","revile"],["אֶת־אֲשֶׁר","ACC-that-which"],["לֹא־יָדָעוּ","not-perceive"],["וּבַדְּבָרִים","and-with-the-words"],["אֲשֶׁר","which"],["יָבִינוּ","they-might-understand"],["מֵחָק־טִבְעָם","by-natural-instinct"],["כַּבְּהֵמוֹת","like the-animals"],["הַסְּכָלוֹת","the-irrational"],["בָּהֵמָּה","in-them"],["יַשְׁחִיתוּ","they-destroy"],["אֶת־נַפְשָׁם","[ACC]-their-souls"],["׃",""]] },
  { num:"יא", words:[["אוֹי","woe-be"],["לָהֶם","to-them"],["כִּי־בְדֶרֶךְ","because-on-a journey"],["קַיִן","Cain"],["הָלָכוּ","they walk"],["וַיִּדַּחוּ","and-they-were-driven"],["בְּמַדּוּחֵי","in-the-error-of"],["בִלְעָם","Balaam"],["עֵקֶב","for"],["שָׂכָר","reward"],["וּבִמְרִי","and-in-the rebellion of"],["קֹרַח","Korah"],["אָבָדוּ","perished"],["׃",""]] },
  { num:"יב", words:[["הֲלֹא","do-not"],["צוּרֵי","rocks-of"],["מִכְשׁוֹל","offence"],["הֵמָּה","they"],["בִּסְעוּדֹת","in-feasts-of"],["אַהֲבָה","love"],["שֶׁלָּכֶם","that-you"],["אֹכְלִים","feeding-upon"],["וְשֹׁתִים","and-drinking"],["עִמָּכֶם","with-you"],["בְּקַלּוּת","without-fear"],["רֹאשׁ","the-head-of"],["וְרֹעִים","and-feeding"],["אֶת־נַפְשָׁם","[ACC]-their-souls"],["עָבִים","clouds"],["הֵם","they"],["בְּלִי","without"],["מַיִם","water"],["נִדָּפִים","driven"],["מִפְּנֵי","because-of"],["רוּחַ","the-spirit-of"],["עֲצֵי־חֹרֶף","the-trees-of-winter"],["בְּאֵין","in-un"],["פְּרִי","fruit"],["אֲשֶׁר","which"],["מֵתוּ","have-died"],["פַעֲמַיִם","two times"],["וְנֶעֱקָרוּ","and-uprooted"],["׃",""]] },
  { num:"יג", words:[["מִשְׁבְּרֵי־יָם","the breakers of-the-sea"],["עַזִּים","fierce"],["אֲשֶׁר","which"],["יִגְרְשׁוּ","they have tossed up"],["בָשְׁתָּם","shame-their"],["כֹּכָבִים","to star(pl)"],["תֹּעִים","wandering"],["אֲשֶׁר־חשֶׁךְ","whose-darkness"],["אֲפֵלָה","thick-darkness"],["צָפוּן","is stored up"],["לָהֶם","to-them"],["עֲדֵי־עַד","forever-and-ever"],["׃",""]] },
  { num:"יד", words:[["וְגַם־חֲנוֹךְ","and-also-Enoch"],["הַשְּׁבִיעִי","the-seventh"],["לְאָדָם","to-man"],["נִבָּא","he-prophesied"],["עֲלֵיהֶם","against-them"],["לֵאמֹר","saying"],["הִנֵּה","behold"],["יְהוָֹה","the-Lord"],["בָּא","came"],["בְּרִבֲבֹת","in-ten thousands of"],["קְדֹשָׁיו","holy ones-his"],["׃",""]] },
  { num:"טו", words:[["לַעֲשׂוֹת","to-do"],["שְׁפָטִים","acts of judgment"],["בְּכֻלָּם","in-all"],["וּלְהוֹכִיחַ","and-to-he-reproved"],["כָּל־רִשְׁעֵי־אֶרֶץ","all-the wicked people of-land-of"],["עַל־כָּל־מַעֲשֵׂי","upon-all-works-of"],["רִשְׁעָתָם","their-wickedness"],["וְעַל־כָּל־הַקָּשׁוֹת","and-upon-all-the-hard-things"],["אֲשֶׁר","which"],["דִּבְּרוּ","have-spoken"],["עָלָיו","upon-him"],["חַטָּאִים","sinful"],["אַנְשֵׁי","the-men-of"],["רֶשַׁע","wickedness"],["׃",""]] },
  { num:"טז", words:[["אֵלֶּה","these"],["הֵם","they"],["הָרֹגְנִים","the-murmurers"],["וְהַמִּתְאוֹנֲנִים","and-the-complainers"],["הַהֹלְכִים","the-ones-walking"],["אַחֲרֵי","after"],["תַאֲוֹתֵיהֶם","their-lusts"],["אֲשֶׁר","which"],["פִּיהֶם","his-mouth"],["יְדַבֵּר","speaks"],["עָתָק","arrogance"],["הֹדְרֵי","admirers-of"],["פָנִים","man"],["עֵקֶב","for"],["שֹׁחַד","a-bribe"],["׃",""]] },
  { num:"יז", words:[["וְאַתֶּם","and-will-you"],["חֲבִיבַי","my-beloved"],["זִכְרוּ","remember"],["אֶת־הַדְּבָרִים","[ACC]-the-words"],["הַנֶּאֱמָרִים","the-it-was-said"],["מִקֶּדֶם","of-old"],["בְּיַד","in-hand-of"],["שְׁלִיחֵי","My-apostles"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"יח", words:[["בְּדַבְּרָם","while-they-should-speak"],["אֲלֵיכֶם","unto-you"],["לֵאמֹר","saying"],["הִנֵּה","behold"],["בְּאַחֲרִית","in-latter"],["הַיָּמִים","the-days"],["יָבֹאוּ","come"],["לֵצִים","mockers"],["הַהֹלְכִים","the-ones-walking"],["אַחֲרֵי","after"],["תַּאֲוֹת","the-lusts-of"],["רִשְׁעָם","their-wickedness"],["׃",""]] },
  { num:"יט", words:[["אֵלֶּה","these"],["הֵם","they"],["הַפֹּרְשִׁים","the-those-who-separate"],["מִן־הַצִּבּוּר","from-the-public"],["בַּעֲלֵי","they"],["נֶפֶשׁ","soul"],["וְרוּחַ","and-spirit-of"],["אֵין","there-is-no"],["בָּהֶם","in-them"],["׃",""]] },
  { num:"כ", words:[["וְאַתֶּם","and-will-you"],["חֲבִיבַי","my-beloved"],["הִבָּנוּ","build-up-yourselves"],["בֶּאֱמוּנַתְכֶם","in-your-faith"],["הַנַּעֲלָה","the-most-holy"],["עַל־כֹּל","upon-all"],["בִּקְדֻשָּׁתָהּ","with-holiness-of-her"],["וְהִתְפַּלֲלוּ","and-they-prayed"],["בְּרוּחַ","in-the-Spirit"],["הַקֹּדֶשׁ","the-Holy"],["׃",""]] },
  { num:"כא", words:[["וּשְׁמַרְתֶּם","and-have-kept"],["אֶת־נַפְשֹׁתֵיכֶם","[ACC]-your-souls"],["בְּאַהֲבַת","because-loves"],["אֱלֹהִים","God"],["וְחִכִּיתֶם","and-you-wait"],["לְרַחֲמֵי","to-compassion-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["לְחַיֵּי","to-life-of"],["עוֹלָם","eternal"],["׃",""]] },
  { num:"כב", words:[["הַבְדִּילוּ","they have made a distinction"],["אֶת־אֵלֶה","[ACC]-these"],["וְהִתְנַהֲגוּ","and-conduct-yourselves"],["עִמָּהֶם","with-them"],["בְּרַחֲמִים","in-mercies"],["׃",""]] },
  { num:"כג", words:[["וְאֶת־אֵלֶּה","and-[ACC]-these"],["תּוֹשִׁיעוּ","you save(they)"],["בְאֵימָה","in-terror"],["וְחִלַּצְתֶּם","and-you-rescue"],["אֹתָם","them"],["מִתּוֹךְ","from-midst-of"],["הָאֵשׁ","the-flames"],["וּמְאַסְתֶּם","and-you-rejected"],["גַּם־אֶת־הַלְּבוּשׁ","also-[ACC]-the-clothing"],["הַמְגֹאָל","the-defiled"],["בְּחֶלְאַת","in-filth-of"],["הַבָּשָׂר","the-flesh"],["׃",""]] },
  { num:"כד", words:[["וַאֲשֶׁר","and-whom"],["יָכוֹל","able"],["לִשְׁמָרְכֶם","to-the-keeps-you(pl)"],["מִמִּכְשׁוֹל","from-a stumbling block"],["וּלְהַעֲמִיד","and-by-establishing"],["אֶתְכֶם","you"],["בְּשָׂשׂוֹן","with-joy"],["תְּמִימִים","unblemished"],["לִפְנֵי","before"],["כְבוֹדוֹ","His-glory"],["׃",""]] },
  { num:"כה", words:[["הָאֱלֹהִים","the-God"],["הֶחָכָם","the-learned"],["הַיָּחִיד","the-Only-Begotten"],["הַמּוֹשִׁיע","the-Savior"],["אֹתָנוּ","us"],["בְּיֵשׁוּעַ","in-Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲדֹנֵינוּ","our-Lord"],["לוֹ","him"],["הַכָּבוֹד","the-glory"],["וְהַגְּדֻלָּה","and-the-greatness"],["וְהָעֹז","and-the-strength-of"],["וְהַמֶּמְשָׁלָה","and-the-government"],["לִפְנֵי","before"],["כָל־עוֹלָם","all-eternal"],["גַּם","also"],["עַתָּה","now"],["גַּם","also"],["לְעוֹלְמֵי","forever"],["עַד","until"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(jude_ch1Verses, 'jude-ch1-verses');

})();
