// nt_verses/phm.js — Philemon verse data
(function() {
var phm_ch1Verses = [
  { num:"א", words:[["פּוֹלוֹס","Paul"],["אֲסִיר","prisoner-of"],["הַמָּשִׁיחַ","the-Messiah"],["יֵשׁוּעַ","Jesus"],["וְטִימוֹתִיּוֹס","and-Timothy"],["הָאָח","the-brother"],["אֶל־פִילֵימוֹן","to-Philemon"],["הֶחָבִיב","the-beloved"],["וְהָעֹזֵר","and-the-fellow-worker"],["אֹתָנוּ","us"],["׃",""]] },
  { num:"ב", words:[["וְאֶל־אַפִּיָּה","and-to-Apphia"],["הָאֲהוּבָה","the-loved one"],["וְאֶל־אַרְכִפּוֹס","and-to-Archippus"],["הֶחָבֵר","the-fellow-soldier"],["לָנוּ","us"],["בְּמִלְחֲמֹתֵינוּ","in-the wars of-our"],["וְאֶל־הַקְּהִלָּה","and-the-church"],["אֲשֶׁר","whose"],["בְּבֵיתֶךָ","in-your-house"],["׃",""]] },
  { num:"ג", words:[["חֶסֶד","grace"],["לָכֶם","to-you"],["וְשָׁלוֹם","and-peace"],["מֵאֵת","from"],["אֱלֹהִים","God"],["אָבִינוּ","our-father"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ד", words:[["מוֹדֶה","am-very-thankful"],["אֲנִי","I"],["לֵאלֹהַי","to-my-God"],["בְּכָל־עֵת","with-all-time"],["בְּהַזְכִּירִי","in-to cause to be remembered-my"],["אֹתְךָ","you"],["בִּתְפִלּוֹתָי","in-my-prayers"],["׃",""]] },
  { num:"ה", words:[["אַחֲרֵי","after"],["שָׁמְעִי","had-heard"],["אַהֲבָתְךָ","love-your"],["וֶאֱמוּנָתְךָ","and-faith-of-your"],["אֲשֶׁר־בְּךָ","whose-in-You"],["לַאֲדֹנֵינוּ","to-lord-our"],["יֵשׁוּעַ","Jesus"],["וּלְכָל־הַקְּדוֹשִׁים","and-for-all-the-saints"],["׃",""]] },
  { num:"ו", words:[["לְמַעַן","in-order-that"],["אֲשֶׁר","whose"],["תִּתְחַזֵּק","will-become-effective"],["הִתְחַבְּרוּת","the-sharing-of"],["אֱמוּנָתְךָ","thine-exceeding-faith"],["בְּדַעַת","in-the-knowledge-of"],["כָּל־טוֹב","all-good"],["אֲשֶׁר","whose"],["בָּכֶם","in-you"],["לְשֵׁם","to-the name of"],["הַמָּשִׁיחַ","the-Messiah"],["יֵשׁוּעַ","Jesus"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["שִׂמְחָה","joy"],["גְדוֹלָה","great"],["וְנֶחָמָה","and-consolation"],["יֶשׁ־לָנוּ","we-have"],["בְּאַהֲבָתֶךָ","in-love-your"],["בַּאֲשֶׁר","because"],["הָיְתָה","was"],["רְוָחָה","relief"],["לִמְעֵי","to-the inward parts of"],["הַקְּדוֹשִׁים","the-saints"],["עַל־יָדְךָ","upon-your-hand"],["אָחִי","my-brother"],["׃",""]] },
  { num:"ח", words:[["לָכֵן","therefore"],["אַף־כִּי","yea-because"],["יֵשׁ־לִי","I-have"],["אֹמֶץ","courage"],["רַב","great"],["בַּמָּשִׁיחַ","in-the-Messiah"],["לְצַוֹּתְךָ","to-command-your"],["אֵת","[ACC]"],["הַנָּכוֹן","that-is-expedient"],["הִנֵּה","behold"],["בָחַרְתִּי","I chose"],["לְמַעַן","in-order-that"],["הָאַהֲבָה","the-love"],["לְחַלּוֹת","to-entreat"],["אֶת־פָּנֶיךָ","[ACC]-face-your"],["׃",""]] },
  { num:"ט", words:[["אָנֹכִי","I"],["פּוֹלוֹס","Paul"],["הַזָּקֵן","the-elder"],["וְעַתָּה","and-now"],["גַּם־אֲסִיר","also-prisoner-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"י", words:[["הִנְנִי","behold-I"],["מְחַלֶּה","entreating"],["אֶת־פָּנֶיךָ","[ACC]-face-your"],["עַל־בְּנִי","upon-my-son"],["אֲשֶׁר","whose"],["חוֹלַלְתִּיו","I-begot-him"],["בִּהְיוֹתי","being"],["בַּמַּאֲסָר","in-prison"],["עַל־אֳנִיסִימוֹס","concerning-Onesimus"],["׃",""]] },
  { num:"יא", words:[["אֲשֶׁר","whose"],["מִלְּפָנִים","from-before"],["לֹא־הוֹעִיל","not-unprofitable"],["לָךְ","[compound]"],["וְעַתָּה","and-now"],["הוּא","it-is"],["לְהוֹעִיל","to-profit"],["גַּם־לְךָ","also-for-you"],["גַם־לִי","also-to-me"],["וַהֲשִׁיבֹתִיו","and-I-have-sent-him-back"],["אֵלֶיךָ","to-you(f)"],["׃",""]] },
  { num:"יב", words:[["וְאַתָּה","for-you"],["קַבֶּל־נָא","take-I-pray"],["אֹתוֹ","him"],["שֶׁהוּא","that-He-is"],["יָקָר","fine"],["לְלִבִּי","to-my-heart"],["׃",""]] },
  { num:"יג", words:[["חָפַצְתִּי","I-desire"],["לַעֲצֹר","restrain"],["אֹתוֹ","him"],["אֶצְלִי","beside-me"],["שֶׁיְּשָׁרֲתֵנִי","that-he will serve-me"],["תַחְתֶּיךָ","in place of-you"],["בְּמוֹסְרוֹת","in-the-bands-of"],["הַבְּשׂוֹרָה","the-gospel"],["׃",""]] },
  { num:"יד", words:[["אֲבָל","but/however"],["לֹא","not"],["חָפַצְתִּי","I-desire"],["לַעֲשׂוֹת","to-do"],["דָּבָר","things"],["שֶׁלּא","that-there-should-be-no"],["בִרְצוֹנֶךָ","in-will-your"],["כְּדֵי","as-sufficient"],["שֶׁלּא־תִהְיֶה","that-not-be"],["טוֹבָתְךָ","goodness-your"],["בְּאֹנֶס","in-is oppressing"],["כִּי","because"],["אִם־בִּנְדָבָה","[compound]-in-voluntariness"],["׃",""]] },
  { num:"טו", words:[["כִּי","because"],["אוּלַי","perhaps"],["נִפְרַד","separate"],["מִמְּךָ","from-you"],["לְשָׁעָה","for-a-time"],["בַּעֲבוּר","because-of"],["אֲשֶׁר","whose"],["יִהְיֶה־לְּךָ","he-shall-be-have-you"],["לְעוֹלָם","forever"],["׃",""]] },
  { num:"טז", words:[["וּמֵעַתָּה","and-from-this-time"],["לֹא","not"],["כְעֶבֶד","as-servant-of"],["כִּי","because"],["אִם־לְמַעְלָה","[compound]-upward"],["מֵעֶבֶד","from-servant-of"],["כְּאָח","like-a brother"],["אָהוּב","he-was-beloved"],["בְּיוֹתֵר","exceedingly"],["לִי","to-me"],["וְאַף","and-yet"],["כִּי־לְךָ","because-for-you"],["הֵן","yea"],["בַּבָּשָׂר","in-the-flesh"],["הֵן","yea"],["בָּאָדוֹן","in-the-Lord"],["׃",""]] },
  { num:"יז", words:[["וְהִנֵּה","and-behold"],["אִם־תַּחְשְׁבֵנִי","[compound]-they consider-me"],["לְחָבֵר","as-a-partner"],["לָךְ","[compound]"],["תְּקַבְּלֶנּוּ","receive-him"],["כָּמוֹנִי","like-unto-me"],["׃",""]] },
  { num:"יח", words:[["וְאִם־הֵרַע","and-if-the-evil"],["לְךָ","for-you"],["בְּדָבָר","in-word"],["אוֹ","or"],["חַיָּב־הוּא","must/obligated-it-is"],["לְךָ","for-you"],["דָּבָר","things"],["חַשְּׁבֵהוּ","charge-it"],["לִי","to-me"],["׃",""]] },
  { num:"יט", words:[["אֲנִי","I"],["פּוֹלוֹס","Paul"],["כָּתַבְתִּי","I-have-written"],["בְיָדִי","in-hand-my"],["אֲנִי","I"],["אֲשַׁלֵּם","I-shall-repay"],["וְלֹא","and-not"],["אֹמַר","I-say"],["כִּי־אַתָּה","that-you"],["חַיָּב","must/obligated"],["לִי","to-me"],["גַּם־אֶת־נַפְשֶׁךָ","also-[ACC]-your-soul"],["׃",""]] },
  { num:"כ", words:[["כֵּן","thus"],["אָחִי","my-brother"],["אֵהָנֶה־נָּא","let-me-have-joy"],["מִמְּךָ","from-you"],["בָּאָדוֹן","in-the-Lord"],["נַחֶם־נָּא","comfort-now"],["אֶת־לִבִּי","[ACC]-my-heart"],["בָּאָדוֹן","in-the-Lord"],["׃",""]] },
  { num:"כא", words:[["כָּתַבְתִּי","I-have-written"],["אֵלֶיךָ","to-you(f)"],["וַאֲנִי","and-I"],["בָטוּחַ","confident"],["בְּךָ","in-You"],["שֶׁתִּשְׁמַע","that-you hear"],["לִי","to-me"],["וְיֹדֵעַ","and-the one who knows"],["אֲנִי","I"],["שֶׁתּוֹסִיף","that-you will add"],["לַעֲשׂוֹת","to-do"],["עַל־אֲשֶׁר","against-those-who"],["אָמָרְתִּי","I have spoken"],["׃",""]] },
  { num:"כב", words:[["וְגַם־לִי","and-also-to-me"],["תָכִין","you will establish"],["בֵּית","house-of"],["מָלוֹן","lodging"],["כִּי","because"],["אֲקַוֶּה","I-hope"],["אֲשֶׁר","whose"],["אֶנָּתֵן","I-will-be-given"],["לָכֶם","to-you"],["עַל־יְדֵי","by-means-of"],["תְּפִלּוֹתֵיכֶם","the-prayers-of-your(pl)"],["׃",""]] },
  { num:"כג", words:[["אֶפַּפְרָס","Epaphras"],["הָאָסוּר","the-prisoner"],["אִתִּי","with-me"],["בַּמָּשִׁיחַ","in-the-Messiah"],["יֵשׁוּעַ","Jesus"],["׃",""]] },
  { num:"כד", words:[["וּמַרְקוֹס","and-Mark"],["וַאֲרִסְטַרְכוֹס","and-Aristarchus"],["וְדִימָס","and-Demas"],["וְלוּקָס","and-Luke"],["עֹזְרַי","my-fellow-workers"],["שֹׁאֲלִים","asking"],["לִשְׁלוֹמֶךָ","to-your-peace"],["׃",""]] },
  { num:"כה", words:[["חֶסֶד","grace"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲדֹנֵינוּ","our-Lord"],["עִם־רוּחֲכֶם","with-spirit-you"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(phm_ch1Verses, 'phm-ch1-verses');

})();
