// nt_verses/phm.js — Philemon verse data
(function() {
var phm_ch1Verses = [
  { num:"א", words:[["פּוֹלוֹס","Paul"],["אֲסִיר","prisoner-of"],["הַמָּשִׁיחַ","the-Messiah"],["יֵשׁוּעַ","Jesus"],["וְטִימוֹתִיּוֹס","and-Timothy"],["הָאָח","the-brother"],["אֶל־פִילֵימוֹן","to-Philemon"],["הֶחָבִיב","the-beloved"],["וְהָעֹזֵר","and-the-fellow-worker"],["אֹתָנוּ","us"],["׃",""]] },
  { num:"ב", words:[["וְאֶל־אַפִּיָּה","and-to-Apphia"],["הָאֲהוּבָה","the-loved one"],["וְאֶל־אַרְכִפּוֹס","and-to-Archippus"],["הֶחָבֵר","the-fellow-soldier"],["לָנוּ","us"],["בְּמִלְחֲמֹתֵינוּ","in-the wars of-our"],["וְאֶל־הַקְּהִלָּה","and-the-church"],["אֲשֶׁר","which"],["בְּבֵיתֶךָ","in-your-house"],["׃",""]] },
  { num:"ג", words:[["חֶסֶד","grace"],["לָכֶם","to-you"],["וְשָׁלוֹם","and-peace"],["מֵאֵת","from"],["אֱלֹהִים","God"],["אָבִינוּ","our-father"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ד", words:[["מוֹדֶה","I-thank"],["אֲנִי","I"],["לֵאלֹהַי","my-God"],["בְּכׇל־עֵת","always"],["בְּהַזְכִּירִי","making-mention-of"],["אֹתְךָ","you"],["בִּתְפִלּוֹתָי","in-my-prayers"],["׃",""]] },
  { num:"ה", words:[["אַחֲרֵי","after"],["שָׁמְעִי","hearing-of"],["אַהֲבָתְךָ","your-love"],["וֶאֱמוּנָתְךָ","and-faith"],["אֲשֶׁר־בְּךָ","which-you-have"],["לַאֲדֹנֵינוּ","to-lord-our"],["יֵשׁוּעַ","Jesus"],["וּלְכׇל־הַקְּדוֹשִׁים","and-for-all-the-saints"],["׃",""]] },
  { num:"ו", words:[["לְמַעַן","in-order-that"],["אֲשֶׁר","which"],["תִּתְחַזֵּק","may-become-effectual"],["הִתְחַבְּרוּת","the-communication-of"],["אֱמוּנָתְךָ","your-faith"],["בְּדַעַת","by-the-acknowledging-of"],["כׇּל־טוֹב","all-good"],["אֲשֶׁר","which"],["בָּכֶם","in-you"],["לְשֵׁם","to-the name of"],["הַמָּשִׁיחַ","the-Messiah"],["יֵשׁוּעַ","Jesus"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["שִׂמְחָה","joy"],["גְדוֹלָה","great"],["וְנֶחָמָה","and-consolation"],["יֶשׁ־לָנוּ","we-have"],["בְּאַהֲבָתֶךָ","in-love-your"],["בַּאֲשֶׁר","because"],["הָיְתָה","was"],["רְוָחָה","are-refreshed"],["לִמְעֵי","the-bowels-of"],["הַקְּדוֹשִׁים","the-saints"],["עַל־יָדְךָ","by-you"],["אָחִי","my-brother"],["׃",""]] },
  { num:"ח", words:[["לָכֵן","therefore"],["אַף־כִּי","though"],["יֵשׁ־לִי","I-have"],["אֹמֶץ","boldness"],["רַב","much"],["בַּמָּשִׁיחַ","in-the-Messiah"],["לְצַוֹּתְךָ","to-enjoin-you"],["אֵת־הַנָּכוֹן","that-which-is-convenient"],["הִנֵּה","yet"],["בָחַרְתִּי","I-rather-beseech"],["לְמַעַן","in-order-that"],["הָאַהֲבָה","the-love"],["לְחַלּוֹת","to-entreat"],["אֶת־פָּנֶיךָ","face-your"],["׃",""]] },
  { num:"ט", words:[["אָנֹכִי","I"],["פּוֹלוֹס","Paul"],["הַזָּקֵן","the-aged"],["וְעַתָּה","and-now"],["גַּם־אֲסִיר","also-a-prisoner-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"י", words:[["הִנְנִי","behold-I"],["מְחַלֶּה","entreating"],["אֶת־פָּנֶיךָ","face-your"],["עַל־בְּנִי","for-my-son"],["אֲשֶׁר","whom"],["חוֹלַלְתִּיו","I-have-begotten"],["בִּהְיוֹתי","in"],["בַּמַּאֲסָר","my-bonds"],["עַל־אֳנִיסִימוֹס","concerning-Onesimus"],["׃",""]] },
  { num:"יא", words:[["אֲשֶׁר","which"],["מִלְּפָנִים","from-before"],["לֹא־הוֹעִיל","was-unprofitable"],["לָךְ","to-you"],["וְעַתָּה","but-now"],["הוּא","is"],["לְהוֹעִיל","profitable"],["גַּם־לְךָ","also-for-you"],["גַם־לִי","also-to-me"],["וַהֲשִׁיבֹתִיו","and-I-have-sent-him-back"],["אֵלֶיךָ","to-you"],["׃",""]] },
  { num:"יב", words:[["וְאַתָּה","for-you"],["קַבֶּל־נָא","receive"],["אֹתוֹ","him"],["שֶׁהוּא","that-is"],["יָקָר","mine-own"],["לְלִבִּי","bowels"],["׃",""]] },
  { num:"יג", words:[["חָפַצְתִּי","I-would"],["לַעֲצֹר","have-retained"],["אֹתוֹ","him"],["אֶצְלִי","with-me"],["שֶׁיְּשָׁרֲתֵנִי","that-he-might-minister-to-me"],["תַחְתֶּיךָ","in-thy-stead"],["בְּמוֹסְרוֹת","in-the-bands-of"],["הַבְּשׂוֹרָה","the-gospel"],["׃",""]] },
  { num:"יד", words:[["אֲבָל","but"],["לֹא","not"],["חָפַצְתִּי","I-would"],["לַעֲשׂוֹת","do"],["דָּבָר","nothing"],["שֶׁלּא","without"],["בִרְצוֹנֶךָ","your-mind"],["כְּדֵי","that"],["שֶׁלּא־תִהְיֶה","should-not-be"],["טוֹבָתְךָ","your-benefit"],["בְּאֹנֶס","of-necessity"],["כִּי","but"],["אִם־בִּנְדָבָה","willingly"],["׃",""]] },
  { num:"טו", words:[["כִּי","because"],["אוּלַי","perhaps"],["נִפְרַד","he-departed"],["מִמְּךָ","from-you"],["לְשָׁעָה","for-a-season"],["בַּעֲבוּר","that"],["אֲשֶׁר","which"],["יִהְיֶה־לְּךָ","you-shouldest-have-him"],["לְעוֹלָם","forever"],["׃",""]] },
  { num:"טז", words:[["וּמֵעַתָּה","and-from-this-time"],["לֹא","not"],["כְעֶבֶד","as-a-servant"],["כִּי","but"],["אִם","rather"],["לְמַעְלָה","above"],["מֵעֶבֶד","a-servant"],["כְּאָח","a-brother"],["אָהוּב","beloved"],["בְּיוֹתֵר","specially"],["לִי","to-me"],["וְאַף","and-yet"],["כִּי־לְךָ","because-for-you"],["הֵן","yea"],["בַּבָּשָׂר","in-the-flesh"],["הֵן","yea"],["בָּאָדוֹן","in-the-Lord"],["׃",""]] },
  { num:"יז", words:[["וְהִנֵּה","and-behold"],["אִם־תַּחְשְׁבֵנִי","if-you-count-me"],["לְחָבֵר","a-partner"],["לָךְ","to-you"],["תְּקַבְּלֶנּוּ","receive-him"],["כָּמוֹנִי","like-unto-me"],["׃",""]] },
  { num:"יח", words:[["וְאִם־הֵרַע","if-he-hath-wronged"],["לְךָ","you"],["בְּדָבָר","in-anything"],["אוֹ","or"],["חַיָּב־הוּא","oweth"],["לְךָ","you"],["דָּבָר","ought"],["חַשְּׁבֵהוּ","put-that-on-mine-account"],["לִי","to-me"],["׃",""]] },
  { num:"יט", words:[["אֲנִי","I"],["פּוֹלוֹס","Paul"],["כָּתַבְתִּי","I-have-written"],["בְיָדִי","in-hand-my"],["אֲנִי","I"],["אֲשַׁלֵּם","will-repay"],["וְלֹא","albeit-not"],["אֹמַר","I-do-say"],["כִּי־אַתָּה","that-you"],["חַיָּב","owest"],["לִי","to-me"],["גַּם־אֶת־נַפְשֶׁךָ","even-thine-own-self"],["׃",""]] },
  { num:"כ", words:[["כֵּן","thus"],["אָחִי","my-brother"],["אֵהָנֶה־נָּא","let-me-have-joy"],["מִמְּךָ","from-you"],["בָּאָדוֹן","in-the-Lord"],["נַחֶם־נָּא","refresh"],["אֶת־לִבִּי","my-bowels"],["בָּאָדוֹן","in-the-Lord"],["׃",""]] },
  { num:"כא", words:[["כָּתַבְתִּי","I-have-written"],["אֵלֶיךָ","to-you"],["וַאֲנִי","and-I"],["בָטוּחַ","having-confidence"],["בְּךָ","in-you"],["שֶׁתִּשְׁמַע","in-thy-obedience"],["לִי","to-me"],["וְיֹדֵעַ","and-knowing"],["אֲנִי","I"],["שֶׁתּוֹסִיף","you-wilt-also-do"],["לַעֲשׂוֹת","more-than"],["עַל־אֲשֶׁר","that"],["אָמָרְתִּי","I-say"],["׃",""]] },
  { num:"כב", words:[["וְגַם־לִי","and-also-to-me"],["תָכִין","prepare-me"],["בֵּית","a"],["מָלוֹן","lodging"],["כִּי","for"],["אֲקַוֶּה","I-trust"],["אֲשֶׁר","that"],["אֶנָּתֵן","I-shall-be-given"],["לָכֶם","to-you"],["עַל־יְדֵי","by-means-of"],["תְּפִלּוֹתֵיכֶם","the-prayers-of-your(pl)"],["׃",""]] },
  { num:"כג", words:[["אֶפַּפְרָס","Epaphras"],["הָאָסוּר","the-prisoner"],["אִתִּי","with-me"],["בַּמָּשִׁיחַ","in-the-Messiah"],["יֵשׁוּעַ","Jesus"],["׃",""]] },
  { num:"כד", words:[["וּמַרְקוֹס","and-Mark"],["וַאֲרִסְטַרְכוֹס","and-Aristarchus"],["וְדִימָס","and-Demas"],["וְלוּקָס","and-Luke"],["עֹזְרַי","my-fellowlabourers"],["שֹׁאֲלִים","salute"],["לִשְׁלוֹמֶךָ","you"],["׃",""]] },
  { num:"כה", words:[["חֶסֶד","grace"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["אֲדֹנֵינוּ","our-Lord"],["עִם־רוּחֲכֶם","with-your-spirit"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(phm_ch1Verses, 'phm-ch1-verses');

})();
