// nt_verses/tit.js — Titus verse data
(function() {
var tit_ch1Verses = [
  { num:"א", words:[["פּוֹלוֹס","Paul"],["עֶבֶד","servant-of"],["אֱלֹהִים","God"],["וּשְׁלִיחַ","and-apostle-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["לְפִי","according-to"],["אֱמוּנַת","the-faith-of"],["בְּחִירֵי","chosen ones-my"],["אֱלֹהִים","God"],["וְדַעַת","and-knowledge"],["הָאֱמֶת","the-true"],["אֲשֶׁר","which"],["לַחֲסִידוּת","to-godliness"],["׃",""]] },
  { num:"ב", words:[["עֲלֵי־תִקְוַת","on-the hope of"],["חַיֵּי","the-life-of"],["עוֹלָם","eternal"],["אֲשֶׁר","which"],["לִפְנֵי","before"],["יְמוֹת","the days of"],["עוֹלָם","eternal"],["הִבְטִיחַ","has-promised"],["הָאֵל","the-God"],["אֲשֶׁר","which"],["לֹא","not"],["יְכַזֵּב","does-lie"],["׃",""]] },
  { num:"ג", words:[["וְגִלָּה","and-he will uncover"],["אֶת־דְּבָרוֹ","[ACC]-His-word"],["בְּמוֹעֲדוֹ","in-its-appointed-time"],["עַל־יְדֵי","by-means-of"],["הַקְּרִיאָה","the-a-proclamation"],["הַמֻּפְקָדָה","the-musters"],["בְּיָדִי","by-my-hand"],["בְּמִצְוַת","by-the-commandment-of"],["הָאֱלֹהִים","the-God"],["מוֹשִׁיעֵנוּ","our-Savior"],["׃",""]] },
  { num:"ד", words:[["אֶל־טִיטוֹס","to-Titus"],["בְּנִי","my-son"],["הָאֲמִתִּי","the-true"],["בֶּאֱמוּנָה","with-much-faith"],["אֶחָת","one"],["חֶסֶד","grace"],["וְרַחֲמִים","and-compassion"],["וְשָׁלוֹם","and-peace"],["מֵאֵת","from"],["הָאֱלֹהִים","the-God"],["אָבִינוּ","our-father"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["מוֹשִׁיעֵנוּ","our-Savior"],["׃",""]] },
  { num:"ה", words:[["בַּעֲבוּר","because-of"],["זֹאת","this"],["הִנַּחְתִּיךָ","I-left-you"],["בִקְרֵיטִי","in-Crete"],["בַּעֲבוּר","because-of"],["אֲשֶׁר","which"],["תַּשְׁלִים","you-will-set-in-order"],["אֶת־הֶחָסֵר","[ACC]-the-lacking"],["וּתְמַנֶּה","and-appoint"],["זְקֵנִים","elders"],["בְּכָל־עִיר","with-all-city-of"],["וָעִיר","and-a city"],["כַּאֲשֶׁר","when/as"],["צִוִּיתִיךָ","I-commanded-you"],["׃",""]] },
  { num:"ו", words:[["אִם־יִמָּצֵא","[compound]-found"],["אִישׁ","man-of"],["תָּם","blameless"],["וּבַעַל־אִשָּׁה","and-husband-of-a-wife"],["אֶחָת","one"],["וְיֶשׁ־לוֹ","and-there-was-him"],["בָּנִים","children"],["מַאֲמִינִים","believing"],["וְאֵין","and-has-no"],["עֲלֵיהֶם","against-them"],["טַעֲנַת","charge-of"],["פְּרִיצוּת","immorality"],["וְאֵינָם","and-are-not"],["סוֹרֲרִים","rebellious people"],["׃",""]] },
  { num:"ז", words:[["כִּי־הֶגְמוֹן","that-bishop"],["הָעֵדָה","the-church"],["צָרִיךְ","necessary"],["לִהְיוֹת","to-be"],["אִישׁ","man-of"],["תָּם","blameless"],["כְּסֹכֵן","as-steward"],["לֵאלֹהִים","God"],["לֹא","not"],["עֹמֵד","standing"],["עַל־דַּעְתּוֹ","upon-his-mind"],["וְלֹא","and-not"],["רַגְזָן","quick-tempered"],["וְלֹא","and-not"],["אֹהֵב","loves"],["יַיִן","wine"],["וְלֹא־בַעַל","and-not-is a master of"],["אֶגְרֹף","a fist"],["וְלֹא","and-not"],["בֹצֵעַ","one greedy for unjust gain"],["בֶּצַע","gain/profit"],["רָע","evil"],["׃",""]] },
  { num:"ח", words:[["כִּי","because"],["אִם־יְהִי","[compound]-let-this-be"],["מַכְנִיס","hospitable"],["אֹרְחִים","travelers"],["וְאֹהֵב","and-he is loving"],["טוֹב","good"],["וְצָנוּעַ","and-modest"],["וְצַדִּיק","and-righteous"],["וְקָדוֹשׁ","and-holy"],["וְכֹבֵשׁ","and-self-controlled"],["אֶת־יִצְרוֹ","[ACC]-intention-its"],["׃",""]] },
  { num:"ט", words:[["וּמַחֲזִיק","and-to-take-hold-of"],["בַּדָּבָר","in-the-thing"],["הַנֶּאֱמָן","the-faithful"],["כְּפִי","according-to"],["הַהוֹרָאָה","the-instruction"],["לְמַעַן","in-order-that"],["יִהְיֶה־בּוֹ","he-shall-be-against-him"],["כֹחַ","power-of"],["לְהַזְהִיר","to-exhort"],["בַּלֶּקַח","in-the-teaching"],["הַבָּרִיא","the-sound"],["וּלְהוֹכִיחַ","and-to-he-reproved"],["אֶת־הַמְּרִיבִים","[ACC]-the-those-who-did-contend"],["׃",""]] },
  { num:"י", words:[["כִּי־יֵשׁ","that-there-is"],["הַרְבֵּה","much"],["מֹרְדִים","rebelling"],["דֹּבְרֵי","those who speak"],["הֶבֶל","the-vanities"],["וּמַתְעֵי","and-deceivers-of"],["נָפֶשׁ","souls"],["וְרֻבָּם","and-most-of-them"],["מִן־הַנִּמּוֹלִים","from-the-circumcised(pl)"],["׃",""]] },
  { num:"יא", words:[["אֲשֶׁר","which"],["סָכוֹר","surely"],["יִסָּכֵר","must-be-stopped"],["פִּיהֶם","his-mouth"],["הַהֹפְכִים","O those-who turn"],["בָּתִּים","buildings"],["כֻּלָּם","all-of-them"],["בְּהוֹרוֹתָם","by-their-teaching"],["דְּבָרִים","things"],["אֲשֶׁר","which"],["לֹא־כֵן","so"],["עֵקֶב","for"],["בָּצַע","unjust gain"],["׃",""]] },
  { num:"יב", words:[["וּכְבָר","and-already"],["אָמַר","said"],["אֶחָד","one"],["מֵהֶם","of-them"],["נְבִיאָם","prophets"],["מִקִּרְבָּם","from-among-them"],["בְּנֵי","the-sons-of"],["קְרֵיטִי","Crete"],["מְשַׁקְּרִים","from-lies"],["מֵעוֹלָם","never"],["וְחַיּוֹת","and-beasts"],["רָעוֹת","wild"],["הֵמָּה","they-are"],["וְגַם","and-also"],["כְּרֵשִׂים","gluttons"],["עֲצֵלִים","idle(pl)"],["׃",""]] },
  { num:"יג", words:[["וְהָעֵדוּת","and-the-testimony"],["הַזֹּאת","is-this"],["אֱמֶת","truth"],["וּבַעֲבוּר־כֵּן","and-because-thus"],["תּוֹכִיחֵם","rebuke-them"],["תּוֹכֵחָה","exceeding-harshness"],["קָשָׁה","hard"],["לְמַעַן","in-order-that"],["יִהְיוּ","shall-be"],["בְרִיאִים","healthy"],["בָּאֱמוּנָה","in-the-faith"],["׃",""]] },
  { num:"יד", words:[["וְלֹא","and-not"],["יָשִׂימוּ","set-at"],["לֵב","heart"],["אֶל־הַגָּדוֹת","to-the-fables"],["הַיְּהוּדִים","the-Jews"],["וְאֶל־מִצְוֹת","and-commandments-of"],["הָאֲנָשִׁים","the-men"],["הַסָּרִים","the-who-turn-away"],["מִן־הָאֱמֶת","from-the-true"],["׃",""]] },
  { num:"טו", words:[["הַכֹּל","all-the"],["טָהוֹר","pure"],["לַטְּהוֹרִים","to-the-pure"],["אֲבָל","but/however"],["לַנִּטְמְאִים","to-the-making yourselves unclean"],["וּלְחַסְרֵי","and-to-lacking-in"],["אֱמוּנָה","faith"],["אֵין־דָּבָר","there-is-no-things"],["טָהוֹר","pure"],["כִּי","because"],["נִטְמְאָה","she has made herself unclean"],["דַּעְתָּם","their-minds"],["וְרוּחָם","and-their-conscience"],["׃",""]] },
  { num:"טז", words:[["אֹמְרִים","said-of(pl)"],["הֵמָּה","they-are"],["יָדַעְנוּ","we-know"],["אֶת־הָאֱלֹהִים","[ACC]-God"],["וּבְמַעֲשֵׂיהֶם","and-by-their-deeds"],["כּוֹפְרִים","denies(pl)"],["בּוֹ","in-Him"],["כִּי","because"],["מְתֹעָבִים","abominable"],["וּמַמְרִים","and-rebelling"],["הֵם","they"],["וְלֹא־יִצְלְחוּ","and-not-are-good-for"],["לְכָל־מַעֲשֶׂה","to-all-a-work"],["טוֹב","good"],["׃",""]] },
];
renderVerseSet(tit_ch1Verses, 'tit-ch1-verses');

var tit_ch2Verses = [
  { num:"א", words:[["וְאַתָּה","for-you"],["דַּבֵּר","to-speak"],["אֶת־הַנָּאֶה","[ACC]-the-what-is-fitting"],["לַלֶּקַח","for-the-sound-teaching"],["הַבָּרִיא","the-sound"],["׃",""]] },
  { num:"ב", words:[["הַזְּקֵנִים","the-you-old-men"],["יִהְיוּ","shall-be"],["משְׁלִים","temperate"],["בְּרוּחָם","in-spirit"],["וּמְכֻבָּדִים","and-dignified"],["וּצְנוּעִים","and-modest people"],["וּבְרִיאִים","and-healthy"],["בָּאֱמוּנָה","in-the-faith"],["וּבָאַהֲבָה","and-in-love"],["וּבַסַּבְלָנוּת","and-in-the-patience"],["׃",""]] },
  { num:"ג", words:[["וְכֵן","and-so"],["הַזְּקֵנוֹת","the-elderly(f)"],["תְּהִי","let it be"],["דַרְכָּן","their-conduct"],["כַּאֲשֶׁר","when/as"],["נָאֲוָה","beautiful"],["לַקֹּדֶשׁ","at-the-holy"],["לֹא","not"],["תִהְיֶינָה","shall-there-be"],["מוֹצִיאוֹת","he is bringing out(pl)"],["דִּבָּה","slander"],["רָעָה","evil"],["וְלֹא","and-not"],["נְתֻנוֹת","will be given"],["לִסְבוֹא־יַיִן","to-much-wine"],["כִּי","because"],["אִם־מְלַמְּדוֹת","but-teaching"],["טוֹב","good"],["׃",""]] },
  { num:"ד", words:[["וּמְיַשְּׁרוֹת","and-training"],["אֶת־הַצְּעִירוֹת","[ACC]-the-young-women"],["לֶאֱהֹב","to-love"],["אֶת־בַּעֲלֵיהֶן","[ACC]-their-husbands"],["וְלֶאֱהֹב","and-to-love"],["אֶת־בְּנֵיהֶן","[ACC]-children-their"],["׃",""]] },
  { num:"ה", words:[["וְלִהְיוֹת","and-to-be"],["צְנוּעוֹת","modest(pl)"],["וּטְהֹרוֹת","and-pure"],["צוֹפִיּוֹת","keepers-of"],["הֲלִיכוֹת","the-affairs-of"],["בֵּיתָן","their-home"],["וְטֹבוֹת","and-good"],["וְנִכְנָעוֹת","and-subject"],["לִפְנֵי","before"],["בַעֲלֵיהֶן","their-husbands"],["לְמַעַן","in-order-that"],["אֲשֶׁר","which"],["לֹא־יְחֻלַּל","not-he will profane"],["דְּבַר","word-of"],["הָאֱלֹהִים","the-God"],["׃",""]] },
  { num:"ו", words:[["כָּכָה","thus"],["תַּזְהִיר","you/she-will-careful"],["גַּם","also"],["אֶת־הַבַּחוּרִים","[ACC]-the-you-young-men"],["שֶׁיִּהְיוּ","that"],["צְנוּעִים","modest people"],["׃",""]] },
  { num:"ז", words:[["וּבְכָל־דָּבָר","and-in-all-things"],["הֱיֵה","be!"],["אַתָּה","you"],["לְמוֹפֵת","an-example"],["בְּמַעֲשִׂים","in-good-works"],["טוֹבִים","good"],["בְּהוֹרָאָה","in-instruction"],["צְרוּפָה","is refined"],["וְנֶהְדָּרָה","and-glorious"],["׃",""]] },
  { num:"ח", words:[["וּבְדָבָר","and-a matter"],["בָּרִיא","sound"],["שֶׁאֵין־בּוֹ","whom-not-against-him"],["מוּם","imperfection"],["לְמַעַן","in-order-that"],["יֵבוֹשׁ","be-ashamed"],["הַמִּתְקוֹמֵם","the-one-who-rises-up"],["וְלֹא","and-not"],["יִמְצָא","shall-find"],["לְדַבֵּר","to-speak"],["עֲלֵיכֶם","over-you"],["רָע","evil"],["׃",""]] },
  { num:"ט", words:[["הָעֲבָדִים","the-servants"],["יִכָּנְעוּ","shall-be-subject"],["לַאֲדֹנֵיהֶם","to-master-their"],["וְיִתְרַצּוּ","and-be-pleasing"],["לָהֶם","to-them"],["לְכָל־דָּבָר","to-all-things"],["וְלֹא","and-not"],["יַמְרוּ","they rebelled"],["אֶת־דִּבְרֵיהֶם","[ACC]-their-words"],["׃",""]] },
  { num:"י", words:[["וְלֹא־יִמְעֲלוּ","and-not-they acted unfaithfully"],["מַעַל","unfaithfulness"],["כִּי","because"],["אִם־יַרְאוּ","[compound]-show"],["כָּל־אֱמוּנָה","all-faith"],["טוֹבָה","good"],["לְמַעַן","in-order-that"],["יְפָאֲרוּ","he-shall-glorify(they)"],["בַכֹּל","the-will be on-everyone"],["אֶת־לֶקַח","[ACC]-the-learning-of"],["אֱלֹהִים","God"],["מוֹשִׁיעֵנוּ","our-Savior"],["׃",""]] },
  { num:"יא", words:[["כִּי","because"],["הוֹפִיעַ","appeared"],["חֶסֶד","grace"],["אֱלֹהִים","God"],["לְהוֹשִׁיעַ","to-save"],["אֶת־כָּל־בְּנֵי","[ACC]-all-sons-of"],["הָאָדָם","the-man"],["׃",""]] },
  { num:"יב", words:[["וּלְהַדְרִיךְ","and-to-instruct"],["אֹתָנוּ","us"],["לְמַעַן","in-order-that"],["נְתַעֵב","we-renounce"],["הָרֶשַׁע","the-wickedness"],["וְתַאֲוֹת","and-the-desires-of"],["הָעוֹלָם","the-world"],["וְנִתְהַלֵּךְ","and-we-walk"],["בָּעוֹלָם","of-the-world"],["הַזֶּה","this"],["בִּצְנִיעוּת","in-the-chastity-of"],["וּבְצֶדֶק","and-with-righteousness"],["וּבַחֲסִידוּת","and-in-godliness"],["׃",""]] },
  { num:"יג", words:[["וּנְחַכֶּה","and-we-waited"],["לַתִּקְוָה","to-the-hope"],["הַמְאַשֶּׁרֶת","the-blessed"],["וּלְהוֹפָעַת","and-to-the-appearing-of"],["כְּבוֹד","the-glory-of"],["אֱלֹהֵינוּ","our-God"],["הַגָּדוֹל","the-great"],["וּמוֹשִׁיעֵנוּ","and-our-Savior"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"יד", words:[["אֲשֶׁר־נָתַן","whose-was-given"],["אֶת־נַפְשׁוֹ","his-life"],["בַּעֲדֵנוּ","for-us"],["לִפְדּוֹת","to-recover"],["אֹתָנוּ","us"],["מִכָּל־עָוֶל","above-all-iniquity"],["וּלְטַהֵר","and-to-purity"],["לוֹ","him"],["עַם","people"],["סְגֻלָּה","choice"],["הַזָּרִיז","the-quick"],["בְּמַעֲשִׂים","in-good-works"],["טוֹבִים","good"],["׃",""]] },
  { num:"טו", words:[["אֵלֶּה","these"],["תְדַבֵּר","you will speak"],["וְתַזְהִיר","and-exhort"],["וְתוֹכִיחַ","and-you will rebuke"],["בְּחָזְקָה","mightily"],["וְאִישׁ","and-the-man-of"],["אַל־יָבוּז","do-not-he will despise"],["לָךְ","[compound]"],["׃",""]] },
];
renderVerseSet(tit_ch2Verses, 'tit-ch2-verses');

var tit_ch3Verses = [
  { num:"א", words:[["הַזְכֵּר","the-remembered"],["אֹתָם","them"],["שֶׁיִּהְיוּ","that"],["נִכְנָעִים","subjecting-themselves"],["וְשֹׁמְעִים","and-who hear"],["לַשָׂרִים","to-the-princes"],["וְלַשִּׁלְטוֹנִים","and-to-the-authorities"],["וּנְכוֹנִים","and-willing"],["לְכָל־מַעֲשֶׂה","to-all-a-work"],["טוֹב","good"],["׃",""]] },
  { num:"ב", words:[["וּלְבִלְתִּי","and-that-death-should-have-no"],["דַּבֵּר","to-speak"],["רָע","evil"],["עַל","upon"],["כָּל־אָדָם","all-men"],["וְלַחֲדֹל","and-that-they-should-stop"],["מֵרִיב","from-strife of"],["וְלָדִין","and-to-judge"],["לְכַף","for-the sole of"],["זְכוּת","merit"],["וּלְהִתְנַהֵג","and-to-conduct-oneself"],["בָּעֲנָוָה","in-the-humility"],["לִפְנֵי","before"],["כָּל־אָדָם","all-men"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["גַם־אֲנַחְנוּ","also-we"],["הָיִינוּ","we-were"],["מִלְּפָנִים","from-before"],["חַסְרֵי","lacking-in"],["דַעַת","knowledge"],["וְסוֹרֲרִים","and-rebellious people"],["וְתוֹעִים","and-going-astray"],["וַעֲבָדִים","and-male servants"],["לְתַאֲוֹת","to-desires"],["וְלִתְשׁוּקוֹת","and-to-pleasures"],["שֹׁנוֹת","different"],["וּמִתְהַלְּכִים","and-walking"],["בְּרִשְׁעָה","in-iniquity"],["וְקִנְאָה","and-jealousy"],["וּשְׂנוּאִים","and-hated"],["וְשׂנְאִים","and-one who hates(pl)"],["אִישׁ","man-of"],["אֶת־אָחִיו","[ACC] another"],["׃",""]] },
  { num:"ד", words:[["אָמְנָם","truly"],["כַּאֲשֶׁר","when/as"],["נִגְלָה","has-been-made-manifest"],["נֹעַם","the kindness of"],["אֱלֹהִים","God"],["מוֹשִׁיעֵנוּ","our-Savior"],["וְאַהֲבָתוֹ","and-His-love"],["אֶת־הָאָדָם","[ACC]-the-man"],["׃",""]] },
  { num:"ה", words:[["לֹא","not"],["בִגְלַל","in-account of"],["מַעֲשֵׂי","works-of"],["הַצְּדָקָה","the-righteousness"],["אֲשֶׁר","which"],["עָשִׂינוּ","we-did/made"],["הוֹשִׁיעַ","save!"],["אֹתָנוּ","us"],["כִּי","because"],["אִם־בְּחַסְדּוֹ","[compound]-by-His-grace"],["עַל־יְדֵי","by-means-of"],["טְבִילַת","baptism-of"],["הַלִּידָה","the-rebirth"],["הַחֲדָשָׁה","the-new"],["וְחִדּוּשׁ","and-innovation"],["רוּחַ","spirit-of"],["הַקֹּדֶשׁ","the-Holy"],["׃",""]] },
  { num:"ו", words:[["אֲשֶׁר","which"],["שָׁפַךְ","poured-out"],["עָלֵינוּ","over-us"],["לְמַכְבִּיר","to-abundance"],["עַל־יְדֵי","by-means-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["מוֹשִׁיעֵנוּ","our-Savior"],["׃",""]] },
  { num:"ז", words:[["לְמַעַן","in-order-that"],["נִצְדַּק","it will be put right"],["בְּחַסְדּוֹ","by-His-grace"],["וְנִירַשׁ","and-become-heirs"],["לְפִי","according-to"],["הַתִּקְוָה","the-hope"],["אֶת־חַיֵּי","[ACC]-the-life-of"],["הָעוֹלָמִים","of-the-Eternity"],["׃",""]] },
  { num:"ח", words:[["אֱמֶת","truth"],["הַדָּבָר","the-thing"],["וְרֹצֶה","and-be pleased"],["אֲנִי","I"],["שֶׁתְּקַיֵּם","that-it-shall-be-fulfilled"],["אֶת־אֵלֶּה","[ACC]-these"],["לְמַעַן","in-order-that"],["אֲשֶׁר","which"],["יִשְׁקְדוּ","he kept watch(they)"],["הַמַּאֲמִינִים","the-believers"],["בֵּאלֹהִים","in-God"],["לַעֲסֹק","to-engage-in"],["בְּמַעֲשִׂים","in-good-works"],["טוֹבִים","good"],["כִּי","because"],["טוֹב","good"],["לַעֲשׂוֹת","to-do"],["כָּאֵלֶּה","such-as-these"],["וּמוֹעִיל","and-worth"],["לָאָדָם","for-man"],["׃",""]] },
  { num:"ט", words:[["אֲבָל","but/however"],["תִּרְחַק","you be far"],["מִן־הַשְּׁאֵלוֹת","from-the-questions"],["הַתְּפֵלוֹת","the-foolish"],["וּמִלִּמּוּדֵי","and-from-will be taught of"],["תוֹלָדוֹת","generations-of"],["וּמִמְּדָנִים","and-from-quarrels"],["וְרִיבוֹת","and-contentions"],["בִּדְבַר","of-the-promise-of"],["הַחֻקִּים","the-statutes"],["כִּי־אֵין","because-there-is-no"],["בָּהֶן","in-them(f)"],["מוֹעִיל","worth"],["וְהֶבֶל","and-vain"],["הֵנָּה","hither"],["׃",""]] },
  { num:"י", words:[["וְאִישׁ","and-the-man-of"],["הַחוֹלֵק","the-one who has shares"],["עַל־הָאֱמוּנָה","upon-the-faith"],["אִם־הוּכַח","[compound]-he is chastened"],["פַּעַם","once"],["וּשְׁתָּיִם","and-two times"],["שְׂטֵה","turn aside"],["מֵעָלָיו","from-with-him"],["׃",""]] },
  { num:"יא", words:[["וְדַע","and-know"],["כִּי־אִישׁ","because-man-of"],["כָּזֶה","such"],["הֲפַכְפַּךְ","is crooked"],["הוּא","it-is"],["וְחוֹטֵא","and-sinful"],["כְּמַרְשִׁיעַ","as-condemns"],["אֶת־נַפְשׁוֹ","his-life"],["׃",""]] },
  { num:"יב", words:[["בְּשָׁלְחִי","when-sent-I"],["אֵלֶיךָ","to-you(f)"],["אֶת־אַרְטְמָס","[ACC]-Artemas"],["אוֹ","or"],["אֶת־טוּכִיקוֹס","[ACC]-Tychicus"],["תְּמַהֵר","it will hasten"],["לָבוֹא","to-come"],["אֵלַי","to-me"],["לְנִקָפֹּלִיס","to-Nicopolis"],["כִּי־גָמַרְתִּי","because-I-have-decided"],["בְלִבִּי","in-heart-my"],["לָשֶׁבֶת","to-dwell"],["שָׁם","there"],["בִּימֵי","in-days-of"],["הַסְּתָיו","the-winter"],["׃",""]] },
  { num:"יג", words:[["שְׁקֹד","keeping watch"],["לְשַׁלֵּחַ","to-send"],["אֶת־זֵינָס","[ACC]-Zenas"],["בַּעַל","expert-in"],["הַתּוֹרָה","the-law"],["וְאֶת־אַפּוֹלוֹס","and-[ACC]-Apollos"],["לְמַעַן","in-order-that"],["לֹא־יַחְסְרוּ","not-they lack"],["דָבָר","[thing]"],["לְדַרְכָּם","to-their-march"],["׃",""]] },
  { num:"יד", words:[["וְיִלְמְדוּ","and-they-may-learn"],["גַּם־אַנְשֵׁי","also-the-men-of"],["עֲדָתֵנוּ","church-of-our/-us"],["לַעֲסֹק","to-engage-in"],["בְּמַעֲשִׂים","in-good-works"],["טוֹבִים","good"],["לַעֲזֹר","for-help"],["בְּכָל־מַחְסוֹר","in-all-lack"],["פֶּן־יִהְיוּ","lest-shall-be"],["בְּלִי־פֶרִי","without-fruit"],["׃",""]] },
  { num:"טו", words:[["כֹּל","all"],["אֲשֶׁר","which"],["עִמָּדִי","with-me"],["שֹׁאֲלִים","asking"],["לִשְׁלוֹמֶךָ","to-your-peace"],["שְׁאַל","ask"],["לִשְׁלוֹם","for-the-welfare-of"],["הָאֹהֲבִים","the-love"],["אֹתָנוּ","us"],["בֶּאֱמוּנָה","with-much-faith"],["הַחֶסֶד","the-grace"],["עִם־כֻּלְּכֶם","with-all-you"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(tit_ch3Verses, 'tit-ch3-verses');

})();
