// nt_verses/tit.js — Titus verse data
(function() {
var tit_ch1Verses = [
  { num:"א", words:[["פּוֹלוֹס","Paul"],["עֶבֶד","the-servant-of"],["אֱלֹהִים","God"],["וּשְׁלִיחַ","and-apostle-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["לְפִי","according-to"],["אֱמוּנַת","the-faith-of"],["בְּחִירֵי","of-the-elect-of"],["אֱלֹהִים","God"],["וְדַעַת","and-the-knowledge-of"],["הָאֱמֶת","the-truth"],["אֲשֶׁר","which"],["לַחֲסִידוּת","after-godliness"],["׃",""]] },
  { num:"ב", words:[["עֲלֵי־תִקְוַת","in-hope-of"],["חַיֵּי","the-life-of"],["עוֹלָם","eternal"],["אֲשֶׁר","which"],["לִפְנֵי","before"],["יְמוֹת","the-world"],["עוֹלָם","began"],["הִבְטִיחַ","promised"],["הָאֵל","God"],["אֲשֶׁר","that"],["לֹא","cannot"],["יְכַזֵּב","lie"],["׃",""]] },
  { num:"ג", words:[["וְגִלָּה","but-hath-manifested"],["אֶת־דְּבָרוֹ","his-word"],["בְּמוֹעֲדוֹ","in-due-times"],["עַל־יְדֵי","through"],["הַקְּרִיאָה","preaching"],["הַמֻּפְקָדָה","which-is-committed"],["בְּיָדִי","by-my-hand"],["בְּמִצְוַת","by-the-commandment-of"],["הָאֱלֹהִים","the-God"],["מוֹשִׁיעֵנוּ","our-Savior"],["׃",""]] },
  { num:"ד", words:[["אֶל־טִיטוֹס","to-Titus"],["בְּנִי","my-son"],["הָאֲמִתִּי","own"],["בֶּאֱמוּנָה","after-the-common"],["אֶחָת","faith"],["חֶסֶד","grace"],["וְרַחֲמִים","and-compassion"],["וְשָׁלוֹם","and-peace"],["מֵאֵת","from"],["הָאֱלֹהִים","the-God"],["אָבִינוּ","our-father"],["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["מוֹשִׁיעֵנוּ","our-Savior"],["׃",""]] },
  { num:"ה", words:[["בַּעֲבוּר","because-of"],["זֹאת","this"],["הִנַּחְתִּיךָ","I-left-you"],["בִקְרֵיטִי","in-Crete"],["בַּעֲבוּר","because-of"],["אֲשֶׁר","which"],["תַּשְׁלִים","you-shouldest-set-in-order"],["אֶת־הֶחָסֵר","the-things-wanting"],["וּתְמַנֶּה","and-ordain"],["זְקֵנִים","elders"],["בְּכׇל־עִיר","with-all-city-of"],["וָעִיר","and-a city"],["כַּאֲשֶׁר","as"],["צִוִּיתִיךָ","I-had-appointed-you"],["׃",""]] },
  { num:"ו", words:[["אִם־יִמָּצֵא","if-found"],["אִישׁ","a-man"],["תָּם","blameless"],["וּבַעַל־אִשָּׁה","and-husband-of-a-wife"],["אֶחָת","one"],["וְיֶשׁ־לוֹ","and-there-was-him"],["בָּנִים","children"],["מַאֲמִינִים","believing"],["וְאֵין","and-has-no"],["עֲלֵיהֶם","upon-them"],["טַעֲנַת","accused-of"],["פְּרִיצוּת","riot"],["וְאֵינָם","or"],["סוֹרֲרִים","unruly"],["׃",""]] },
  { num:"ז", words:[["כִּי־הֶגְמוֹן","for-a-bishop"],["הָעֵדָה","of-the-church"],["צָרִיךְ","must"],["לִהְיוֹת","be"],["אִישׁ","a-man"],["תָּם","blameless"],["כְּסֹכֵן","as-steward"],["לֵאלֹהִים","God"],["לֹא","not"],["עֹמֵד","not"],["עַל־דַּעְתּוֹ","selfwilled"],["וְלֹא","not"],["רַגְזָן","soon-angry"],["וְלֹא","and-not"],["אֹהֵב","loves"],["יַיִן","wine"],["וְלֹא־בַעַל","and-not-is a master of"],["אֶגְרֹף","a fist"],["וְלֹא","and-not"],["בֹצֵעַ","one greedy for unjust gain"],["בֶּצַע","filthy-lucre;"],["רָע","evil"],["׃",""]] },
  { num:"ח", words:[["כִּי","because"],["אִם־יְהִי","if-let-this-be"],["מַכְנִיס","a-lover-of-hospitality"],["אֹרְחִים","strangers"],["וְאֹהֵב","a-lover-of"],["טוֹב","good-men"],["וְצָנוּעַ","sober"],["וְצַדִּיק","and-righteous"],["וְקָדוֹשׁ","and-holy"],["וְכֹבֵשׁ","temperate"],["אֶת־יִצְרוֹ","himself"],["׃",""]] },
  { num:"ט", words:[["וּמַחֲזִיק","holding-fast"],["בַּדָּבָר","the-word"],["הַנֶּאֱמָן","faithful"],["כְּפִי","according-to"],["הַהוֹרָאָה","the-instruction"],["לְמַעַן","in-order-that"],["יִהְיֶה־בּוֹ","he-may-be"],["כֹחַ","able"],["לְהַזְהִיר","to-exhort"],["בַּלֶּקַח","by-doctrine"],["הַבָּרִיא","sound"],["וּלְהוֹכִיחַ","and-to-convince"],["אֶת־הַמְּרִיבִים","the-gainsayers"],["׃",""]] },
  { num:"י", words:[["כִּי־יֵשׁ","that-there-is"],["הַרְבֵּה","much"],["מֹרְדִים","unruly"],["דֹּבְרֵי","vain"],["הֶבֶל","talkers"],["וּמַתְעֵי","and-deceivers"],["נָפֶשׁ","specially"],["וְרֻבָּם","they"],["מִן־הַנִּמּוֹלִים","from-the-circumcised(pl)"],["׃",""]] },
  { num:"יא", words:[["אֲשֶׁר","which"],["סָכוֹר","whose"],["יִסָּכֵר","must-be-stopped"],["פִּיהֶם","mouths"],["הַהֹפְכִים","who-subvert"],["בָּתִּים","houses"],["כֻּלָּם","whole"],["בְּהוֹרוֹתָם","by-their-teaching"],["דְּבָרִים","things"],["אֲשֶׁר","which"],["לֹא־כֵן","they-ought-not"],["עֵקֶב","for"],["בָּצַע","filthy-lucres-sake"],["׃",""]] },
  { num:"יב", words:[["וּכְבָר","and-already"],["אָמַר","said"],["אֶחָד","one"],["מֵהֶם","of-them"],["נְבִיאָם","a-prophet-of-their-own"],["מִקִּרְבָּם","said"],["בְּנֵי","the-sons-of"],["קְרֵיטִי","Crete"],["מְשַׁקְּרִים","are-alway-liars"],["מֵעוֹלָם","ever"],["וְחַיּוֹת","evil"],["רָעוֹת","beasts"],["הֵמָּה","they"],["וְגַם","and-also"],["כְּרֵשִׂים","slow"],["עֲצֵלִים","bellies"],["׃",""]] },
  { num:"יג", words:[["וְהָעֵדוּת","this-witness"],["הַזֹּאת","this"],["אֱמֶת","is-true"],["וּבַעֲבוּר־כֵּן","wherefore"],["תּוֹכִיחֵם","rebuke-them"],["תּוֹכֵחָה","sharply"],["קָשָׁה","hard"],["לְמַעַן","in-order-that"],["יִהְיוּ","they-may-be"],["בְרִיאִים","sound"],["בָּאֱמוּנָה","in-the-faith"],["׃",""]] },
  { num:"יד", words:[["וְלֹא","and-not"],["יָשִׂימוּ","giving"],["לֵב","heed"],["אֶל־הַגָּדוֹת","to-fables"],["הַיְּהוּדִים","Jewish"],["וְאֶל־מִצְוֹת","and-commandments-of"],["הָאֲנָשִׁים","the-men"],["הַסָּרִים","that-turn"],["מִן־הָאֱמֶת","from-the-truth"],["׃",""]] },
  { num:"טו", words:[["הַכֹּל","all-things"],["טָהוֹר","pure"],["לַטְּהוֹרִים","to-the-pure"],["אֲבָל","but"],["לַנִּטְמְאִים","to-the-defiled"],["וּלְחַסְרֵי","and-unbelieving"],["אֱמוּנָה","faith"],["אֵין־דָּבָר","is-nothing"],["טָהוֹר","pure"],["כִּי","because"],["נִטְמְאָה","is-defiled"],["דַּעְתָּם","their-mind"],["וְרוּחָם","and-their-conscience"],["׃",""]] },
  { num:"טז", words:[["אֹמְרִים","they-profess"],["הֵמָּה","that-they"],["יָדַעְנוּ","know"],["אֶת־הָאֱלֹהִים","God"],["וּבְמַעֲשֵׂיהֶם","but-in-works"],["כּוֹפְרִים","they-deny"],["בּוֹ","in-him"],["כִּי","because"],["מְתֹעָבִים","abominable"],["וּמַמְרִים","and-disobedient"],["הֵם","they"],["וְלֹא־יִצְלְחוּ","and-reprobate"],["לְכׇל־מַעֲשֶׂה","to-all-a-work"],["טוֹב","good"],["׃",""]] },
];
renderVerseSet(tit_ch1Verses, 'tit-ch1-verses');

var tit_ch2Verses = [
  { num:"א", words:[["וְאַתָּה","for-you"],["דַּבֵּר","speak"],["אֶת־הַנָּאֶה","the-things-which-become"],["לַלֶּקַח","doctrine"],["הַבָּרִיא","sound"],["׃",""]] },
  { num:"ב", words:[["הַזְּקֵנִים","the-aged-men"],["יִהְיוּ","be"],["משְׁלִים","sober"],["בְּרוּחָם","in-spirit"],["וּמְכֻבָּדִים","grave"],["וּצְנוּעִים","temperate"],["וּבְרִיאִים","sound"],["בָּאֱמוּנָה","in-faith"],["וּבָאַהֲבָה","in-charity"],["וּבַסַּבְלָנוּת","in-patience"],["׃",""]] },
  { num:"ג", words:[["וְכֵן","and-so"],["הַזְּקֵנוֹת","the-aged-women"],["תְּהִי","let-be"],["דַרְכָּן","in-behavior"],["כַּאֲשֶׁר","as"],["נָאֲוָה","becometh"],["לַקֹּדֶשׁ","holiness"],["לֹא","not"],["תִהְיֶינָה","shall-there-be"],["מוֹצִיאוֹת","false"],["דִּבָּה","accusers"],["רָעָה","not"],["וְלֹא","and-not"],["נְתֻנוֹת","given"],["לִסְבוֹא־יַיִן","to-much-wine"],["כִּי","but"],["אִם־מְלַמְּדוֹת","teachers-of-good"],["טוֹב","good"],["׃",""]] },
  { num:"ד", words:[["וּמְיַשְּׁרוֹת","that-they-may-teach"],["אֶת־הַצְּעִירוֹת","the-young-women"],["לֶאֱהֹב","to-love"],["אֶת־בַּעֲלֵיהֶן","their-husbands"],["וְלֶאֱהֹב","and-to-love"],["אֶת־בְּנֵיהֶן","children-their"],["׃",""]] },
  { num:"ה", words:[["וְלִהְיוֹת","and-to-be"],["צְנוּעוֹת","discreet"],["וּטְהֹרוֹת","chaste"],["צוֹפִיּוֹת","keepers"],["הֲלִיכוֹת","at"],["בֵּיתָן","home"],["וְטֹבוֹת","good"],["וְנִכְנָעוֹת","obedient"],["לִפְנֵי","before"],["בַעֲלֵיהֶן","their-husbands"],["לְמַעַן","in-order-that"],["אֲשֶׁר","which"],["לֹא־יְחֻלַּל","be-not-blasphemed"],["דְּבַר","the-word-of"],["הָאֱלֹהִים","the-God"],["׃",""]] },
  { num:"ו", words:[["כָּכָה","likewise"],["תַּזְהִיר","exhort"],["גַּם","also"],["אֶת־הַבַּחוּרִים","the-young-men"],["שֶׁיִּהְיוּ","to-be"],["צְנוּעִים","sober-minded"],["׃",""]] },
  { num:"ז", words:[["וּבְכׇל־דָּבָר","and-in-all-things"],["הֱיֵה","be!"],["אַתָּה","you"],["לְמוֹפֵת","a-pattern"],["בְּמַעֲשִׂים","of-good-works"],["טוֹבִים","good"],["בְּהוֹרָאָה","in-doctrine"],["צְרוּפָה","shewing-uncorruptness"],["וְנֶהְדָּרָה","gravity"],["׃",""]] },
  { num:"ח", words:[["וּבְדָבָר","and-speech"],["בָּרִיא","sound"],["שֶׁאֵין־בּוֹ","that-cannot-be"],["מוּם","condemned"],["לְמַעַן","in-order-that"],["יֵבוֹשׁ","may-be-ashamed"],["הַמִּתְקוֹמֵם","he-of-the-contrary-part"],["וְלֹא","and-not"],["יִמְצָא","shall-find"],["לְדַבֵּר","to-speak"],["עֲלֵיכֶם","over-you"],["רָע","evil"],["׃",""]] },
  { num:"ט", words:[["הָעֲבָדִים","servants"],["יִכָּנְעוּ","to-be-obedient"],["לַאֲדֹנֵיהֶם","unto-their-own-masters"],["וְיִתְרַצּוּ","and-to-please-them-well"],["לָהֶם","to-them"],["לְכׇל־דָּבָר","in-all-things"],["וְלֹא","not"],["יַמְרוּ","answering-again"],["אֶת־דִּבְרֵיהֶם","their-words"],["׃",""]] },
  { num:"י", words:[["וְלֹא־יִמְעֲלוּ","not-purloining"],["מַעַל","aught"],["כִּי","but"],["אִם־יַרְאוּ","shewing"],["כׇּל־אֱמוּנָה","all-good"],["טוֹבָה","fidelity"],["לְמַעַן","in-order-that"],["יְפָאֲרוּ","they-may-adorn"],["בַכֹּל","in-all-things"],["אֶת־לֶקַח","the-doctrine-of"],["אֱלֹהִים","God"],["מוֹשִׁיעֵנוּ","our-Savior"],["׃",""]] },
  { num:"יא", words:[["כִּי","because"],["הוֹפִיעַ","hath-appeared"],["חֶסֶד","grace"],["אֱלֹהִים","God"],["לְהוֹשִׁיעַ","to-save"],["אֶת־כׇּל־בְּנֵי","all-sons-of"],["הָאָדָם","the-man"],["׃",""]] },
  { num:"יב", words:[["וּלְהַדְרִיךְ","teaching"],["אֹתָנוּ","us"],["לְמַעַן","that"],["נְתַעֵב","denying"],["הָרֶשַׁע","ungodliness"],["וְתַאֲוֹת","and-the-desires-of"],["הָעוֹלָם","the-world"],["וְנִתְהַלֵּךְ","we-should-live"],["בָּעוֹלָם","in-the-world"],["הַזֶּה","this-present"],["בִּצְנִיעוּת","soberly"],["וּבְצֶדֶק","righteously"],["וּבַחֲסִידוּת","and-godly"],["׃",""]] },
  { num:"יג", words:[["וּנְחַכֶּה","looking-for"],["לַתִּקְוָה","that-hope"],["הַמְאַשֶּׁרֶת","blessed"],["וּלְהוֹפָעַת","and-to-the-appearing-of"],["כְּבוֹד","the-glory-of"],["אֱלֹהֵינוּ","our-God"],["הַגָּדוֹל","the-great"],["וּמוֹשִׁיעֵנוּ","and-our-Savior"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"יד", words:[["אֲשֶׁר־נָתַן","whose-was-given"],["אֶת־נַפְשׁוֹ","his-life"],["בַּעֲדֵנוּ","for-us"],["לִפְדּוֹת","to-redeem"],["אֹתָנוּ","us"],["מִכׇּל־עָוֶל","from-all-iniquity"],["וּלְטַהֵר","and-purify"],["לוֹ","him"],["עַם","people"],["סְגֻלָּה","choice"],["הַזָּרִיז","zealous"],["בְּמַעֲשִׂים","in-good-works"],["טוֹבִים","good"],["׃",""]] },
  { num:"טו", words:[["אֵלֶּה","these"],["תְדַבֵּר","speak"],["וְתַזְהִיר","and-exhort"],["וְתוֹכִיחַ","and-rebuke"],["בְּחָזְקָה","with-all-authority"],["וְאִישׁ","let-no-man"],["אַל־יָבוּז","despise"],["לָךְ","to-you"],["׃",""]] },
];
renderVerseSet(tit_ch2Verses, 'tit-ch2-verses');

var tit_ch3Verses = [
  { num:"א", words:[["הַזְכֵּר","put-in-mind"],["אֹתָם","them"],["שֶׁיִּהְיוּ","to-be"],["נִכְנָעִים","subject"],["וְשֹׁמְעִים","to-obey-magistrates"],["לַשָׂרִים","to-principalities"],["וְלַשִּׁלְטוֹנִים","and-powers"],["וּנְכוֹנִים","to-be-ready"],["לְכׇל־מַעֲשֶׂה","to-all-a-work"],["טוֹב","good"],["׃",""]] },
  { num:"ב", words:[["וּלְבִלְתִּי","to-no"],["דַּבֵּר","speak-evil-of"],["רָע","any"],["עַל","of"],["כׇּל־אָדָם","man"],["וְלַחֲדֹל","to-be-no-brawlers"],["מֵרִיב","gentle"],["וְלָדִין","shewing"],["לְכַף","all"],["זְכוּת","meekness"],["וּלְהִתְנַהֵג","unto"],["בָּעֲנָוָה","all-men"],["לִפְנֵי","before"],["כׇּל־אָדָם","all-men"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["גַם־אֲנַחְנוּ","also-we"],["הָיִינוּ","we-were"],["מִלְּפָנִים","sometimes"],["חַסְרֵי","foolish"],["דַעַת","without-knowledge"],["וְסוֹרֲרִים","and-disobedient"],["וְתוֹעִים","deceived"],["וַעֲבָדִים","serving"],["לְתַאֲוֹת","lusts"],["וְלִתְשׁוּקוֹת","and-pleasures"],["שֹׁנוֹת","divers"],["וּמִתְהַלְּכִים","living"],["בְּרִשְׁעָה","in-malice"],["וְקִנְאָה","and-envy"],["וּשְׂנוּאִים","hateful"],["וְשׂנְאִים","and-hating"],["אִישׁ","a-man"],["אֶת־אָחִיו","one-another"],["׃",""]] },
  { num:"ד", words:[["אׇמְנָם","truly"],["כַּאֲשֶׁר","after-that"],["נִגְלָה","appeared"],["נֹעַם","the-kindness-of"],["אֱלֹהִים","God"],["מוֹשִׁיעֵנוּ","our-Savior"],["וְאַהֲבָתוֹ","and-his-love"],["אֶת־הָאָדָם","toward-man"],["׃",""]] },
  { num:"ה", words:[["לֹא","not"],["בִגְלַל","in-account of"],["מַעֲשֵׂי","works-of"],["הַצְּדָקָה","the-righteousness"],["אֲשֶׁר","which"],["עָשִׂינוּ","we-have-done"],["הוֹשִׁיעַ","he-saved"],["אֹתָנוּ","us"],["כִּי","but"],["אִם־בְּחַסְדּוֹ","according-to-his-mercy"],["עַל־יְדֵי","by"],["טְבִילַת","the-washing-of"],["הַלִּידָה","regeneration"],["הַחֲדָשָׁה","and"],["וְחִדּוּשׁ","renewing-of"],["רוּחַ־הַקֹּדֶשׁ","the Holy Ghost"],["׃",""]] },
  { num:"ו", words:[["אֲשֶׁר","which"],["שָׁפַךְ","he-shed"],["עָלֵינוּ","on-us"],["לְמַכְבִּיר","abundantly"],["עַל־יְדֵי","by-means-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Messiah"],["מוֹשִׁיעֵנוּ","our-Savior"],["׃",""]] },
  { num:"ז", words:[["לְמַעַן","in-order-that"],["נִצְדַּק","being-justified"],["בְּחַסְדּוֹ","by-his-grace"],["וְנִירַשׁ","we-should-be-made-heirs"],["לְפִי","according-to"],["הַתִּקְוָה","the-hope"],["אֶת־חַיֵּי","the-life-of"],["הָעוֹלָמִים","eternal"],["׃",""]] },
  { num:"ח", words:[["אֱמֶת","true"],["הַדָּבָר","is-the-saying"],["וְרֹצֶה","and-will"],["אֲנִי","I"],["שֶׁתְּקַיֵּם","that-you-affirm-constantly"],["אֶת־אֵלֶּה","these-things"],["לְמַעַן","in-order-that"],["אֲשֶׁר","which"],["יִשְׁקְדוּ","might-be-careful"],["הַמַּאֲמִינִים","the-believers"],["בֵּאלֹהִים","in-God"],["לַעֲסֹק","to-engage-in"],["בְּמַעֲשִׂים","in-good-works"],["טוֹבִים","good"],["כִּי","for"],["טוֹב","good"],["לַעֲשׂוֹת","are"],["כָּאֵלֶּה","these-things"],["וּמוֹעִיל","and-profitable"],["לָאָדָם","unto-men"],["׃",""]] },
  { num:"ט", words:[["אֲבָל","but"],["תִּרְחַק","avoid"],["מִן־הַשְּׁאֵלוֹת","questions"],["הַתְּפֵלוֹת","foolish"],["וּמִלִּמּוּדֵי","and"],["תוֹלָדוֹת","genealogies"],["וּמִמְּדָנִים","and-contentions"],["וְרִיבוֹת","and-strivings"],["בִּדְבַר","about"],["הַחֻקִּים","the-law"],["כִּי־אֵין","for-they-are"],["בָּהֶן","unprofitable"],["מוֹעִיל","and-vain"],["וְהֶבֶל","and-vain"],["הֵנָּה","hither"],["׃",""]] },
  { num:"י", words:[["וְאִישׁ","and-the-man-of"],["הַחוֹלֵק","that-divideth"],["עַל־הָאֱמוּנָה","the-faith"],["אִם־הוּכַח","after-the-first"],["פַּעַם","and-second"],["וּשְׁתָּיִם","admonition"],["שְׂטֵה","reject"],["מֵעָלָיו","from-him"],["׃",""]] },
  { num:"יא", words:[["וְדַע","and-know"],["כִּי־אִישׁ","because-man-of"],["כָּזֶה","such"],["הֲפַכְפַּךְ","is-subverted"],["הוּא","he"],["וְחוֹטֵא","and-sinneth"],["כְּמַרְשִׁיעַ","condemned-of"],["אֶת־נַפְשׁוֹ","himself"],["׃",""]] },
  { num:"יב", words:[["בְּשָׁלְחִי","when-I-shall-send"],["אֵלֶיךָ","unto-you"],["אֶת־אַרְטְמָס","Artemas"],["אוֹ","or"],["אֶת־טוּכִיקוֹס","Tychicus"],["תְּמַהֵר","be-diligent"],["לָבוֹא","to-come"],["אֵלַי","unto-me"],["לְנִקָפֹּלִיס","to-Nicopolis"],["כִּי־גָמַרְתִּי","for-I-have-determined"],["בְלִבִּי","in-heart-my"],["לָשֶׁבֶת","to-dwell"],["שָׁם","there"],["בִּימֵי","in-the-days-of"],["הַסְּתָיו","the-winter"],["׃",""]] },
  { num:"יג", words:[["שְׁקֹד","diligently"],["לְשַׁלֵּחַ","bring-on-their-journey"],["אֶת־זֵינָס","Zenas"],["בַּעַל","the-lawyer"],["הַתּוֹרָה","the-law"],["וְאֶת־אַפּוֹלוֹס","and-Apollos"],["לְמַעַן","in-order-that"],["לֹא־יַחְסְרוּ","that-they-lack"],["דָבָר","nothing"],["לְדַרְכָּם","on-their-journey"],["׃",""]] },
  { num:"יד", words:[["וְיִלְמְדוּ","and-they-may-learn"],["גַּם־אַנְשֵׁי","also-the-men-of"],["עֲדָתֵנוּ","ours"],["לַעֲסֹק","to-maintain"],["בְּמַעֲשִׂים","good-works"],["טוֹבִים","good"],["לַעֲזֹר","for"],["בְּכׇל־מַחְסוֹר","necessary-uses"],["פֶּן־יִהְיוּ","that-they-be-not"],["בְּלִי־פֶרִי","unfruitful"],["׃",""]] },
  { num:"טו", words:[["כֹּל","all"],["אֲשֶׁר","which"],["עִמָּדִי","with-me"],["שֹׁאֲלִים","salute"],["לִשְׁלוֹמֶךָ","you"],["שְׁאַל","greet"],["לִשְׁלוֹם","for-the-welfare-of"],["הָאֹהֲבִים","them-that-love"],["אֹתָנוּ","us"],["בֶּאֱמוּנָה","in-the-faith"],["הַחֶסֶד","grace"],["עִם־כֻּלְּכֶם","with-all-you"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(tit_ch3Verses, 'tit-ch3-verses');

})();
