// jst_verses/jst1sa.js — 1 Samuel (JST) verse data
(function() {
var jst1sa_ch1Verses = [
  { num:"א", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["אֶל־שְׁמוּאֵל","to-Samuel"],["עַד־מָתַי","until-when"],["אַתָּה","you"],["מִתְאַבֵּל","mourning"],["אֶל־שָׁאוּל","to-Saul"],["וַאֲנִי","and-I"],["מְאַסְתִּיו","I have rejected-him"],["מִמְּלֹךְ","from-reigning"],["עַל־יִשְׂרָאֵל","upon-Israel"],["מַלֵּא","fill"],["קַרְנְךָ","your-horn"],["שֶׁמֶן","oil"],["וְלֵךְ","and-go"],["אֶשְׁלָחֲךָ","I will send-you"],["אֶל־יִשַׁי","to-Jesse"],["בֵּית־הַלַּחְמִי","house-of--lehemite"],["כִּי־רָאִיתִי","because-I-saw"],["בְּבָנָיו","in-his-sons"],["לִי","to-me"],["מֶלֶךְ","king-of"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמֶר","and-said"],["שְׁמוּאֵל","Samuel"],["אֵיךְ","how"],["אֵלֵךְ","will-go"],["וְשָׁמַע","and-heard"],["שָׁאוּל","Saul"],["וַהֲרָגָנִי","and-he will kill-me"],["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["עֶגְלַת","a-young-cow"],["בָּקָר","of-the-herd"],["תִּקַּח","you-shall-take"],["בְּיָדֶךָ","into-thy-hands"],["וְאָמַרְתָּ","and-say"],["לִזְבֹּחַ","to-offer"],["לַיהֹוָה","to-Yahweh"],["בָּאתִי","when-I-came"],["׃",""]] },
  { num:"ג", words:[["וְקָרָאתָ","and-you-read"],["לְיִשַׁי","Jesse"],["בַּזָּבַח","at the-sacrifice"],["וְאָנֹכִי","yet-I"],["אוֹדִיעֲךָ","I will make known to-you"],["אֵת","[ACC]"],["אֲשֶׁר־תַּעֲשֶׂה","which-you-make"],["וּמָשַׁחְתָּ","and-you will anoint"],["לִי","to-me"],["אֵת","[ACC]"],["אֲשֶׁר־אֹמַר","whose-I-say"],["אֵלֶיךָ","to-you(f)"],["׃",""]] },
  { num:"ד", words:[["וַיַּעַשׂ","and-did"],["שְׁמוּאֵל","Samuel"],["אֵת","[ACC]"],["אֲשֶׁר","whose"],["דִּבֶּר","spoke"],["יְהֹוָה","the-LORD"],["וַיָּבֹא","and-came"],["בֵּית","house-of"],["לָחֶם","food"],["וַיֶּחֶרְדוּ","and-they trembled"],["זִקְנֵי","the-elders-of"],["הָעִיר","the-city"],["לִקְרָאתוֹ","to-you-called-his"],["וַיֹּאמֶר","and-said"],["שָׁלֹם","in peace"],["בּוֹאֶךָ","at-your-coming"],["׃",""]] },
  { num:"ה", words:[["וַיֹּאמֶר","and-said"],["שָׁלוֹם","peace"],["לִזְבֹּחַ","to-offer"],["לַיהֹוָה","to-Yahweh"],["בָּאתִי","when-I-came"],["הִתְקַדְּשׁוּ","sanctify yourselves"],["וּבָאתֶם","and-you-have-come"],["אִתִּי","with-me"],["בַּזָּבַח","at the-sacrifice"],["וַיְקַדֵּשׁ","and-He-sanctified"],["אֶת־יִשַׁי","[ACC]-Jesse"],["וְאֶת־בָּנָיו","and-[ACC]-his-sons"],["וַיִּקְרָא","and-he-called"],["לָהֶם","to-them"],["לַזָּבַח","for the-sacrifice"],["׃",""]] },
  { num:"ו", words:[["וַיְהִי","and-it-came-to-pass"],["בְּבוֹאָם","when-came-they"],["וַיַּרְא","and-he-saw"],["אֶת־אֱלִיאָב","[ACC]-Eliab"],["וַיֹּאמֶר","and-said"],["אַךְ","but"],["נֶגֶד","against"],["יְהֹוָה","the-LORD"],["מְשִׁיחוֹ","anointed-his"],["׃",""]] },
  { num:"ז", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["אֶל־שְׁמוּאֵל","to-Samuel"],["אַל־תַּבֵּט","do-not-you look"],["אֶל־מַרְאֵהוּ","to-from-saw-his"],["וְאֶל־גְּבֹהַּ","and-the height of"],["קוֹמָתוֹ","stature-his"],["כִּי","because"],["מְאַסְתִּיהוּ","I have rejected-him"],["כִּי","because"],["לֹא","not"],["אֲשֶׁר","whose"],["יִרְאֶה","He-shall-manifest-Himself"],["הָאָדָם","man"],["כִּי","because"],["הָאָדָם","man"],["יִרְאֶה","He-shall-manifest-Himself"],["לַעֵינַיִם","to the-eyes"],["וַיהֹוָה","and-Yahweh"],["יִרְאֶה","He-shall-manifest-Himself"],["לַלֵּבָב","to the-heart"],["׃",""]] },
  { num:"ח", words:[["וַיִּקְרָא","and-he-called"],["יִשַׁי","Jesse"],["אֶל־אֲבִינָדָב","to-Abinadab"],["וַיַּעֲבִרֵהוּ","and-he made pass by-him"],["לִפְנֵי","before"],["שְׁמוּאֵל","Samuel"],["וַיֹּאמֶר","and-said"],["גַּם־בָּזֶה","also-herein"],["לֹא־בָחַר","not-chose"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ט", words:[["וַיַּעֲבֵר","and-he made to pass"],["יִשַׁי","Jesse"],["שַׁמָּה","there"],["וַיֹּאמֶר","and-said"],["גַּם־בָּזֶה","also-herein"],["לֹא־בָחַר","not-chose"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"י", words:[["וַיַּעֲבֵר","and-he made to pass"],["יִשַׁי","Jesse"],["שִׁבְעַת","seven-of"],["בָּנָיו","his-sons"],["לִפְנֵי","before"],["שְׁמוּאֵל","Samuel"],["וַיֹּאמֶר","and-said"],["שְׁמוּאֵל","Samuel"],["אֶל־יִשַׁי","to-Jesse"],["לֹא־בָחַר","not-chose"],["יְהֹוָה","the-LORD"],["בָּאֵלֶּה","in-these"],["׃",""]] },
  { num:"יא", words:[["וַיֹּאמֶר","and-said"],["שְׁמוּאֵל","Samuel"],["אֶל־יִשַׁי","to-Jesse"],["הֲתַמּוּ","¿-are they finished"],["הַנְּעָרִים","the-children"],["וַיֹּאמֶר","and-said"],["עוֹד","any-more"],["שָׁאַר","he remains"],["הַקָּטָן","small"],["וְהִנֵּה","and-behold"],["רֹעֶה","shepherd"],["בַּצֹּאן","the-flock"],["וַיֹּאמֶר","and-said"],["שְׁמוּאֵל","Samuel"],["אֶל־יִשַׁי","to-Jesse"],["שִׁלְחָה","send-!"],["וְקָחֶנּוּ","and-bring-him"],["כִּי","because"],["לֹא־נָסֹב","not-we will turn round"],["עַד־בֹּאוֹ","until-his-coming"],["פֹה","mouth"],["׃",""]] },
  { num:"יב", words:[["וַיִּשְׁלַח","and-he-sent"],["וַיְבִיאֵהוּ","and-He-shall-bring"],["וְהוּא","and-it"],["אַדְמוֹנִי","red"],["עִם־יְפֵה","with-handsome of"],["עֵינַיִם","by-the-eyes-of"],["וְטוֹב","and-better"],["רֹאִי","the one who sees-me"],["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["קוּם","arise"],["מְשָׁחֵהוּ","anoint-him"],["כִּי־זֶה","that-this"],["הוּא","it-is"],["׃",""]] },
  { num:"יג", words:[["וַיִּקַּח","and-took"],["שְׁמוּאֵל","Samuel"],["אֶת־קֶרֶן","[ACC]-the horn of"],["הַשֶּׁמֶן","the-oil"],["וַיִּמְשַׁח","and-he-consecrated"],["אֹתוֹ","him"],["בְּקֶרֶב","among"],["אֶחָיו","his-elder"],["וַתִּצְלַח","and-it rushed"],["רוּחַ־יְהֹוָה","spirit-of-the-LORD"],["אֶל־דָּוִד","to-David"],["מֵהַיּוֹם","from-that-time"],["הַהוּא","that"],["וָמָעְלָה","and-up--wards"],["וַיָּקׇם","and-may he carry out"],["שְׁמוּאֵל","Samuel"],["וַיֵּלֶךְ","and-he-went"],["הָרָמָתָה","Ramah-towards"],["׃",""]] },
  { num:"יד", words:[["וְרוּחַ","and-spirit-of"],["יְהֹוָה","the-LORD"],["סָרָה","ceasing"],["מֵעִם","from"],["שָׁאוּל","Saul"],["וּבִעֲתַתּוּ","and-it terrified-him"],["רוּחַ־רָעָה","spirit-of-evil"],["מֵאֵת","from"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"טו", words:[["וַיֹּאמְרוּ","and-they-said"],["עַבְדֵי־שָׁאוּל","servants-of-Saul"],["אֵלָיו","to-him"],["הִנֵּה־נָא","behold-I-pray"],["רוּחַ־אֱלֹהִים","spirit-of-God"],["רָעָה","evil"],["מְבַעִתֶּךָ","is terrifying-you"],["׃",""]] },
  { num:"טז", words:[["יֹאמַר־נָא","He-says-I-pray"],["אֲדֹנֵנוּ","our-Lord"],["עֲבָדֶיךָ","servants-your"],["לְפָנֶיךָ","before-you"],["יְבַקְשׁוּ","seek"],["אִישׁ","man-of"],["יֹדֵעַ","He-knows"],["מְנַגֵּן","playing"],["בַּכִּנּוֹר","on the-harp"],["וְהָיָה","and-be"],["בִּהְיוֹת","while-was"],["עָלֶיךָ","upon-you(f)"],["רוּחַ־אֱלֹהִים","spirit-of-God"],["רָעָה","evil"],["וְנִגֵּן","and-he will play"],["בְּיָדוֹ","in-his-hand"],["וְטוֹב","and-better"],["לָךְ","[compound]"],["׃",""]] },
  { num:"יז", words:[["וַיֹּאמֶר","and-said"],["שָׁאוּל","Saul"],["אֶל־עֲבָדָיו","to-His-servants"],["רְאוּ־נָא","behold-I-pray"],["לִי","to-me"],["אִישׁ","man-of"],["מֵיטִיב","who does well"],["לְנַגֵּן","to-play"],["וַהֲבִיאוֹתֶם","and-you will bring him"],["אֵלָי","unto-me"],["׃",""]] },
  { num:"יח", words:[["וַיַּעַן","and-he-answered"],["אֶחָד","one"],["מֵהַנְּעָרִים","from-the-young men"],["וַיֹּאמֶר","and-said"],["הִנֵּה","behold"],["רָאִיתִי","I-saw"],["בֵּן","a-son"],["לְיִשַׁי","Jesse"],["בֵּית","house-of"],["הַלַּחְמִי","-lehemite"],["יֹדֵעַ","He-knows"],["נַגֵּן","to play"],["וְגִבּוֹר","and-mighty"],["חַיִל","might"],["וְאִישׁ","and-the-man-of"],["מִלְחָמָה","war"],["וּנְבוֹן","and-the-eloquent"],["דָּבָר","things"],["וְאִישׁ","and-the-man-of"],["תֹּאַר","form"],["וַיהֹוָה","and-Yahweh"],["עִמּוֹ","with-him"],["׃",""]] },
  { num:"יט", words:[["וַיִּשְׁלַח","and-he-sent"],["שָׁאוּל","Saul"],["מַלְאָכִים","angels"],["אֶל־יִשָׁי","to-Jesse"],["וַיֹּאמֶר","and-said"],["שִׁלְחָה","send-!"],["אֵלַי","to-me"],["אֶת־דָּוִד","[ACC]-David"],["בִּנְךָ","your-Son"],["אֲשֶׁר","whose"],["בַּצֹּאן","the-flock"],["׃",""]] },
  { num:"כ", words:[["וַיִּקַּח","and-took"],["יִשַׁי","Jesse"],["חֲמוֹר","a-donkey"],["לֶחֶם","bread"],["וְנֹאד","and-a skin-bottle of"],["יַיִן","wine"],["וּגְדִי","and-a kid of"],["עִזִּים","goats"],["אֶחָד","one"],["וַיִּשְׁלַח","and-he-sent"],["בְּיַד־דָּוִד","in-hand-of-David"],["בְּנוֹ","his-son"],["אֶל־שָׁאוּל","to-Saul"],["׃",""]] },
  { num:"כא", words:[["וַיָּבֹא","and-came"],["דָוִד","David"],["אֶל־שָׁאוּל","to-Saul"],["וַיַּעֲמֹד","and-stood"],["לְפָנָיו","before-him"],["וַיֶּאֱהָבֵהוּ","and-he loved-him"],["מְאֹד","exceedingly"],["וַיְהִי־לוֹ","and-it-came-to-pass-him"],["נֹשֵׂא","bearing"],["כֵלִים","weapons"],["׃",""]] },
  { num:"כב", words:[["וַיִּשְׁלַח","and-he-sent"],["שָׁאוּל","Saul"],["אֶל־יִשַׁי","to-Jesse"],["לֵאמֹר","saying"],["יַעֲמׇד־נָא","he appointed-I-pray"],["דָוִד","David"],["לְפָנַי","before-me"],["כִּי־מָצָא","because-found"],["חֵן","favor"],["בְּעֵינָי","in-view-my"],["׃",""]] },
  { num:"כג", words:[["וְהָיָה","and-be"],["בִּהְיוֹת","while-was"],["רוּחַ־אֱלֹהִים","spirit-of-God"],["אֶל־שָׁאוּל","to-Saul"],["וְלָקַח","and-take"],["דָּוִד","David"],["אֶת־הַכִּנּוֹר","[ACC]-the-harp"],["וְנִגֵּן","and-he will play"],["בְּיָדוֹ","in-his-hand"],["וְרָוַח","and-it was relief"],["לְשָׁאוּל","of-Shaul"],["וְטוֹב","and-better"],["לוֹ","him"],["וְסָרָה","and-shall-depart"],["מֵעָלָיו","from-with-him"],["רוּחַ","spirit-of"],["הָרָעָה","the-evil"],["׃",""]] },
];
renderVerseSet(jst1sa_ch1Verses, 'jst1sa-ch1-verses');

})();
