// jst_verses/jst1pe.js — 1 Peter (JST) verse data
(function() {
var jst1pe_ch1Verses = [
  { num:"א", words:[["וְכֵן","and-so"],["אַתֵּנָה","you"],["הַנָּשִׁים","that-the-women"],["הִכָּנַעְנָה","???"],["לִפְנֵי","before"],["בַעֲלֵיכֶן","in-to-you"],["לְמַעַן","in-order-that"],["אֲשֶׁר־יִקָּנוּ","whose-they will be bought"],["בְּאֵין־אֹמֶר","in-un-utterance"],["וּדְבָרִים","and-things"],["עַל־יְדֵי","by-means-of"],["מַעֲשֵׂי","works-of"],["הַנָּשִׁים","that-the-women"],["מִי","who"],["שֶׁאֵינָם","that-they-are-not"],["שֹׁמְעִים","obedient"],["לַדָּבָר","for-the-intent"],["׃",""]] },
  { num:"ב", words:[["בִּרְאוֹתָם","when-they-saw"],["כִּי","because"],["תִצְנַעְנָה","???"],["לֶכֶת","departing-of"],["בְּיִרְאָה","in-He-shall-manifest-Himself"],["׃",""]] },
  { num:"ג", words:[["וּפְאֵרְכֶן","???"],["אַל־יְהִי","do-not-let-this-be"],["מִבַּחוּץ","from-in-the-except"],["בְּמַחְלְפוֹת","in-the plaits of"],["שֵׂעָר","hair"],["וַעֲדִי","and-ornaments of"],["זָהָב","gold"],["וּלְבִישַׁת","???"],["מַחֲלָצוֹת","robes"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["אִם־הָאָדָם","[compound]-man"],["הַצָּפוּן","the-north"],["פְּנִימָה","inside"],["בְּרוּחַ","in-the-Spirit"],["עֲנָוָה","humility"],["וְהַשְׁקֵט","and-be-quiet"],["אֲשֶׁר","whose"],["לֹא","not"],["יִכְלֶה","perishes"],["הוּא","it-is"],["יָקָר","fine"],["בְּעֵינֵי","in-eyes-of"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"ה", words:[["כִּי","because"],["כֵן","thus"],["הִתְקַשְּׁטוּ","???"],["לְפָנִים","formerly"],["גַּם־הַנָּשִׁים","also-that-the-women"],["הַקְּדֹשׁוֹת","the-cult prostitutes"],["הַמְיַחֲלוֹת","the-waiting(pl)"],["לֵאלֹהִים","God"],["בְּהִכָּנְעָן","in-be-subdued-their"],["לִפְנֵי","before"],["בַעֲלֵיהֶן","in-them"],["׃",""]] },
  { num:"ו", words:[["כְּשָׂרָה","as-is Sarah"],["אֲשֶׁר","whose"],["שָׁמְעָה","she-heard"],["בְּקוֹל","the-voice-of"],["אַבְרָהָם","Abraham"],["וַתִּקְרָא־לוֹ","and-she called-him"],["אָדוֹן","is master"],["אֲשֶׁר","whose"],["אַתֶּן","thou"],["הֱיִיתֶן","???"],["לָהּ","it"],["לְבָנוֹת","white"],["בַּעֲשׂוֹתְכֶן","???"],["הַטּוֹב","good"],["וְלֹא","and-not"],["תִירֶאנָה","???"],["מִפָּחַד","from-fear"],["׃",""]] },
  { num:"ז", words:[["וְכֵן","and-so"],["אַתֶּם","you-are"],["הָאֲנָשִׁים","men"],["שְׁבוּ","they-returned"],["עִמָּהֶן","with-them(f)"],["בִּתְבוּנָה","with-understanding"],["כִּי־כְלִי","because-an-instrument"],["רָפֶה","feeble"],["הָאִשָּׁה","the-a-woman"],["וּתְנוּ־לָהּ","and-give!-it"],["כָּבוֹד","glorious"],["כִּי","because"],["גַם־לָהֶן","also-for-them"],["יֶשׁ־חֵלֶק","has-part"],["בְּנַחֲלַת","on-the inheritance of"],["מַתְּנַת","gift-of"],["הַחַיִּים","life"],["פֶּן־תִּכָּלְאוּ","???"],["מִתְּפִלּוֹתֵיכֶם","from-the-prayers-of-your(pl)"],["׃",""]] },
  { num:"ח", words:[["וְסוֹף","and-end"],["דָּבָר","things"],["הֱיוּ","be"],["כֻלְּכֶם","all-of-you"],["לֵב","heart"],["אֶחָד","one"],["בַּעֲלֵי","they-are"],["חֶמְלָה","commiseration"],["אֹהֲבֵי","those who love"],["הָאַחִים","the-brethren"],["רַחֲמָנִים","merciful"],["וְשִׁפְלֵי","and-low-my"],["רוּחַ","spirit-of"],["׃",""]] },
  { num:"ט", words:[["אַל־תְּשַׁלְּמוּ","???"],["רָעָה","evil"],["תַּחַת","under"],["רָעָה","evil"],["וְלֹא","and-not"],["חֶרְפָּה","reproach"],["תַּחַת","under"],["חֶרְפָּה","reproach"],["כִּי","because"],["אִם־תְּבָרֵכוּ","[compound]-you-may-be-blessed"],["מִפְּנֵי","because-of"],["שֶׁיֹּדְעִים","that-knowledgeable"],["אַתֶּם","you-are"],["שֶׁלָּזֹאת","that-for-this-cause"],["נִקְרֵאתֶם","ye-are-called"],["שֶׁתִּירְשׁוּ","that-you will take possession of"],["אֶת־הַבְּרָכָה","[ACC]-the-blessing"],["׃",""]] },
  { num:"י", words:[["כִּי","because"],["הָאִישׁ","the-man"],["הֶחָפֵץ","was-desirous"],["חַיִּים","living"],["אֹהֵב","loves"],["יָמִים","days"],["לִרְאוֹת","to-see"],["טוֹב","good"],["יִצֹּר","let it keep"],["לְשׁוֹנוֹ","his-tongue"],["מֵרָע","from-evil"],["וּשְׂפָתָיו","and-lips-his"],["מִדַּבֵּר","from-speaking"],["מִרְמָה","deceit"],["יָסוּר","shall-be-taken-away"],["מֵרָע","from-evil"],["וְיַעֲשֶׂה־טּוֹב","and-He-do-is good"],["יְבַקֵּשׁ","he-should-look-for"],["שָׁלוֹם","peace"],["וְיִרְדְּפֵהוּ","and-he-was-pursued-by"],["׃",""]] },
  { num:"יא", words:[["כִּי־עֵינֵי","because-eyes-of"],["יְהוָֹה","the-Lord"],["אֶל־צַדִּיקִים","to-just"],["וְאָזְנָיו","and-ears-his"],["אֶל־שַׁוְעָתָם","to-cry for help-their"],["׃",""]] },
  { num:"יב", words:[["וּפְנֵי","and-the-faces-of"],["יְהוָֹה","the-Lord"],["בְּעֹשֵׂי","among-those who did"],["רָע","evil"],["׃",""]] },
  { num:"יג", words:[["וּמִי","and-whoso"],["יָרֵעַ","he will do harm"],["לָכֶם","to-you"],["אִם־תְּקַנְאוּ","???"],["לַעֲשׂוֹת","to-do"],["הַטּוֹב","good"],["׃",""]] },
  { num:"יד", words:[["וְאַשְׁרֵיכֶם","and-blessed-are-you"],["גַּם","also"],["אִם־תְּעֻנּוּ","[compound]-Tno"],["לְמַעַן","in-order-that"],["הַצְּדָקָה","the-righteousness"],["רַק־מוֹרָאָם","???"],["לֹא־תִירְאוּ","fear-you-not"],["וְלֹא","and-not"],["תַעֲרִיצוּ","be-afraid"],["׃",""]] },
  { num:"טו", words:[["אֶת־יְהוָֹה","[ACC]-the-LORD"],["אֱלֹהִים","God"],["אֹתוֹ","him"],["תַקְדִּישׁוּ","sanctify"],["בִּלְבַבְכֶם","in-your-hearts"],["וִהְיוּ","and-be"],["נְכֹנִים","prepared"],["תָּמִיד","continually"],["לְהָשִׁיב","to-he-restored"],["דָּבָר","things"],["בַּעֲנָוָה","the-humble"],["וּבְיִרְאָה","and-in-He-shall-manifest-Himself"],["לְכָל־מְבַקֵּשׁ","to-all-desire"],["מֵאִתְּכֶם","of-you"],["חֶשְׁבּוֹן","account"],["הַתּוֹחֶלֶת","the-the hope of"],["אֲשֶׁר","whose"],["בְּקִרְבְּכֶם","among-you"],["׃",""]] },
  { num:"טז", words:[["רוּחַ","spirit-of"],["נָכוֹן","expedient"],["יְהִי","let-this-be"],["לָכֶם","to-you"],["לְמַעַן","in-order-that"],["יֵבֹשׁוּ","ashamed-shall-be"],["הַמְנַאֲצִים","???"],["דַּרְכְּכֶם","your-ways"],["הַטּוֹבָה","the-good"],["בַמָּשִׁיחַ","in-anointed"],["לְהַלְשִׁין","???"],["אֶתְכֶם","you"],["כְּפֹעֲלֵי","as-those who do"],["אָוֶן","iniquity"],["׃",""]] },
  { num:"יז", words:[["כִּי","because"],["טוֹב","good"],["לָכֶם","to-you"],["אֲשֶׁר","whose"],["תְּעֻנּוּ","Tno"],["בִּרְצוֹן","in-the-will-of"],["אֱלֹהִים","God"],["בַּעֲשׂוֹתְכֶם","in-do-you(pl)"],["הַטּוֹב","good"],["מִשֶּׁתְּעֻנּוּ","from-that-Tno"],["בַּעֲשׂוֹתְכֶם","in-do-you(pl)"],["רָע","evil"],["׃",""]] },
  { num:"יח", words:[["כִּי","because"],["גַם־הַמָּשִׁיחַ","also-the-Messiah"],["מֵת","is-dead"],["פַּעַם","once"],["אַחַת","one"],["עַל־חַטֹּאתֵינוּ","upon-our-sins"],["הַצַּדִּיק","the-righteous"],["בְּעַד","on-behalf-of"],["הָרְשָׁעִים","the-wicked"],["לְקָרֵב","to-draws-near"],["אֹתָנוּ","us"],["אֶל־הָאֱלֹהִים","unto-God"],["הוּמַת","was-slain"],["בַּבָּשָׂר","in-the-flesh"],["וַיְחִי","and-lived"],["בָרוּחַ","in-the-Spirit"],["׃",""]] },
  { num:"יט", words:[["וּבְכֵן","and-in-such"],["הָלַךְ","went"],["וַיִּקְרָא","and-he-called"],["לָרוּחוֹת","to-the-spirits-of"],["אֲשֶׁר","whose"],["בַּמִּשְׁמָר","in-custody"],["׃",""]] },
  { num:"כ", words:[["אֲשֶׁר","whose"],["לְפָנִים","formerly"],["לֹא","not"],["הֶאֱמִינוּ","did-they-believe"],["כַּאֲשֶׁר","when/as"],["חִכָּה","he-waited"],["אֱלֹהִים","God"],["בְּאֹרֶךְ","in-he-was-long"],["אַפּוֹ","His-wrath"],["בִּימֵי","in-days-of"],["נֹחַ","Noah"],["בְּהֵעָשׂוֹת","in-be done"],["הַתֵּבָה","the-ark"],["אֲשֶׁר","whose"],["נִמְלְטוּ","escaped"],["אֵלֶיהָ","to-her"],["מְעַטִּים","a-few"],["וְהֵם","and-they"],["שְׁמֹנֶה","eight"],["נְפָשׁוֹת","souls"],["מִן־הַמָּיִם","from-the-water"],["׃",""]] },
  { num:"כא", words:[["וְהוּא","and-it"],["דְּמוּת","likeness-of"],["הַטְּבִילָה","the-baptism"],["אֲשֶׁר","whose"],["כָּעֵת","as-yet"],["תּוֹשִׁיעַ","you save"],["גַּם־אֶתְכֶם","also-you"],["לֹא","not"],["לְהָסִיר","to-he-removed"],["חֶלְאַת","???"],["הַבָּשָׂר","the-flesh"],["כִּי","because"],["אִם־לִשְׁאָל־לָנוּ","[compound]-to-enquire-us"],["מֵאֵת","from"],["אֱלֹהִים","God"],["רוּחַ","spirit-of"],["שְׁלֵמָה","complete/perfect"],["עַל־יְדֵי","by-means-of"],["הֲקָמַת","you will set up"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"כב", words:[["אֲשֶׁר","whose"],["עָבַר","passed"],["הַשָּׁמַיְמָה","unto-the-heavens"],["וַיֵּשֶׁב","and-he-sat/dwelt"],["לִימִין","at-right-of"],["אֱלֹהִים","God"],["וַיִּכָּנְעוּ","and-they-submitted"],["מִפָּנָיו","from-before-him"],["הַמַּלְאָכִים","the-angels"],["וְהָרְשֻׁיּוֹת","???"],["וְהַגְּבוּרוֹת","and-the-mighty"],["׃",""]] },
];
renderVerseSet(jst1pe_ch1Verses, 'jst1pe-ch1-verses');

var jst1pe_ch2Verses = [
  { num:"א", words:[["וְעַתָּה","and-now"],["כַּאֲשֶׁר","when/as"],["עֻנָּה","was replying"],["הַמָּשִׁיחַ","the-Messiah"],["בַּעֲדֵנוּ","in-until-us"],["בַּבָּשָׂר","in-the-flesh"],["כֵּן","thus"],["הֱיוּ","be"],["גַם־אַתֶּם","also-you"],["מְזֻיָּנִים","armed"],["בַּדַּעַת","in-the-true-knowledge"],["הַהִיא","that"],["כִּי","because"],["הַמְעֻנֶּה","the-from-answered"],["בַבָּשָׂר","in-the-flesh"],["חָדַל","ceased"],["לַחֲטוֹא","to-the-sinning"],["׃",""]] },
  { num:"ב", words:[["לְמַעַן","in-order-that"],["אֲשֶׁר","whose"],["לֹא","not"],["תִחְיוּ","you-will-live"],["עוֹד","any-more"],["לְתַאֲוֹת","to-chambers"],["בְּנֵי","sons-of"],["אָדָם","man"],["כִּי","because"],["אִם־לִרְצוֹן","[compound]-to-the-will-of"],["אֱלֹהִים","God"],["כָּל־יְמֵי","as-long-as"],["הֱיֹתְכֶם","you will become-you(pl)"],["עוֹד","any-more"],["בַּבָּשָׂר","in-the-flesh"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["רַב","great"],["לָנוּ","us"],["עֲשׂוֹת","do"],["כְּחֵפֶץ","as-desire/precious"],["הַגּוֹיִם","the-nations"],["בַּיָּמִים","in-the-days"],["הָרִאשֹׁנִים","his-first"],["יְמֵי","days-of"],["לֶכְתֵּנוּ","departing-of-our/-us"],["בְּדַרְכֵי","in-ways-of"],["זִמָּה","there-could-not"],["וּבְתַאֲוֹת","???"],["כְּסֹבְאֵי","as-drunkards of"],["יַיִן","wine"],["וְזֹלֲלֵי","and-gluttons of"],["בָשָׂר","carnal"],["וְרֹדְפֵי","and-you-who-follow-after"],["שֵׁכָר","strong-drink"],["וְתוֹעֲבוֹת","and-abominations-of"],["עֲבֹדַת","the service of"],["הָאֱלִילִים","idols"],["׃",""]] },
  { num:"ד", words:[["וְעַל־זֹאת","and-for-this-cause"],["תְּמֵהִים","wondered(pl)"],["הֵמָּה","they-are"],["וּמְגַדְּפִים","and-revile-against"],["כִּי","because"],["לֹא־תָרוּצוּ","???"],["עִמָּהֶם","with-them"],["לִהְיוֹת","to-be"],["שְׁטוּפִים","???"],["בְּזִמָּה","in-there-could-not"],["כְּמוֹהֶם","like-them"],["׃",""]] },
  { num:"ה", words:[["אֲשֶׁר","whose"],["יִתְּנוּ","they-should-impart"],["חֶשְׁבּוֹן","account"],["לִפְנֵי","before"],["הֶעָתִיד","the-future"],["לִשְׁפֹּט","to-judge"],["הַחַיִּים","life"],["וְהַמֵּתִים","and-the-dead"],["׃",""]] },
  { num:"ו", words:[["כִּי","because"],["עַל־כֵּן","therefore"],["הִתְבַּשְׂרוּ","???"],["גַּם־הַמֵּתִים","also-the-dead"],["לְמַעַן","in-order-that"],["יִדּוֹנוּ","be-damned"],["בַבָּשָׂר","in-the-flesh"],["כִּבְנֵי־אָדָם","like-young ones of-man"],["וְיִחְיוּ","and-they-shall-live"],["בָּרוּחַ","in-the-Spirit"],["כְּדֶרֶךְ","after-manner-of"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"ז", words:[["הֵן","yea"],["קֵץ","end"],["הַכֹּל","all"],["קָרֵב","draws-near"],["לָכֵן","therefore"],["הֱיוּ","be"],["צְנוּעִים","modest people"],["וְעֵרִים","and-cities"],["לְהִתְפַּלֵּל","to-pray"],["׃",""]] },
  { num:"ח", words:[["וְקֹדֶם","and-before"],["כָּל־דָּבָר","all-things"],["אֶהֱבוּ","they-loved"],["אִישׁ","man-of"],["אֶת־אָחִיו","[ACC] another"],["אַהֲבָה","love"],["עַזָּה","exceedingly"],["כִּי","because"],["עַל־רֹב","upon-much"],["פְּשָׁעִים","transgressions"],["תְּכַסֶּה","you will cover"],["הָאַהֲבָה","the-love"],["׃",""]] },
  { num:"ט", words:[["הֱיוּ","be"],["מְאָרֲחִים","from-travelers"],["אִישׁ","man-of"],["אֶת־רֵעֵהוּ","[ACC]-another"],["בִּבְלִי","with-no"],["תְלֻנּוֹת","complaints"],["׃",""]] },
  { num:"י", words:[["אִישׁ","man-of"],["אִישׁ","man-of"],["כְּמַתַּן","as-from-sea-serpent"],["הַחֶסֶד","mercy"],["אֲשֶׁר","whose"],["קִבֵּל","received"],["תַּעַזְרוּ","will-succor"],["אִישׁ","man-of"],["לְרֵעֵהוּ","another"],["כְּסֹכְנִים","???"],["מְמֻנִּים","were appointed"],["עַל־חַסְדֵי","upon-lovingkindnesses-of"],["אֱלֹהִים","God"],["הָרַבִּים","the-many"],["׃",""]] },
  { num:"יא", words:[["הַמְדַבֵּר","who-spoke"],["יְדַבֵּר","speaks"],["אִמְרֵי־אֵל","words of-God"],["וְהָעֹזֵר","and-the-who was helping"],["יַעֲזֹר","shall-help"],["מִתּוֹךְ","from-midst-of"],["הַחַיִל","the-wealth"],["אֲשֶׁר","whose"],["חֲנָנוֹ","they showed favor to"],["אֱלֹהִים","God"],["לְמַעַן","in-order-that"],["יִכָּבֵד","it was unresponsive"],["אֱלֹהִים","God"],["בַּכֹּל","in-all"],["עַל־יְדֵי","by-means-of"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["אֲשֶׁר","whose"],["לוֹ","him"],["הַכָּבוֹד","the-glorious"],["וְהָעֹז","and-the-strength-of"],["לְעוֹלְמֵי","forever"],["עוֹלָמִים","everlasting"],["אָמֵן","amen"],["׃",""]] },
  { num:"יב", words:[["חֲבִיבַי","my-beloved"],["בְּבֹאֲכֶם","when-you-are-brought"],["בְּתוֹךְ","among"],["כּוּר","the furnace of"],["עֳנִי","affliction"],["לְמַעַן","in-order-that"],["נַסֹּתְכֶם","???"],["אַל־נָא","do-not-I-pray"],["תִתְמָהוּ","you-shall-wonder"],["כְּאִלּוּ","as-though"],["קָרָה","happened"],["אֶתְכֶם","you"],["מִקְרֶה","chance"],["זָר","strange"],["׃",""]] },
  { num:"יג", words:[["כִּי","because"],["אִם־שִׂמְחוּ","[compound]-rejoice"],["עַל־אֲשֶׁר","against-those-who"],["חֵלֶק","part"],["לָכֶם","to-you"],["בְּעִנּוּיֵי","with-eternal-torment"],["הַמָּשִׁיחַ","the-Messiah"],["לְמַעַן","in-order-that"],["גַּם־תִּשְׂמְחוּ","also-you-shall-always-rejoice"],["וְתַעַלְצוּ","???"],["בְּהִגָּלוֹת","because-were uncovered"],["כְּבוֹדוֹ","His-glory"],["׃",""]] },
  { num:"יד", words:[["אִם־יְחָרֲפוּ","[compound]-they-shall-revile"],["אֶתְכֶם","you"],["לְמַעַן־שֵׁם","in-order-that-name-of"],["הַמָּשִׁיחַ","the-Messiah"],["אַשְׁרֵיכֶם","blessed-are-you"],["כִּי","because"],["נָחָה","rested"],["עֲלֵיכֶם","over-you"],["רוּחַ","spirit-of"],["הַכָּבוֹד","the-glorious"],["וְהַגְּבוּרָה","and-the-might"],["רוּחַ","spirit-of"],["אֱלֹהִים","God"],["אֶצְלָם","beside-them"],["מְנֹּאָף","adulterous"],["הוּא","it-is"],["וְאֶצְלְכֶם","and-beside-you(pl)"],["נִכְבָּד","was-glorious"],["׃",""]] },
  { num:"טו", words:[["כִּי","because"],["אַל־יְעֻנֶּה","do-not-should-be-oppressed"],["אִישׁ","man-of"],["מִכֶּם","from-you"],["כְּרֹצֵחַ","as-a killer"],["אוֹ","or"],["כְגַנָּב","as-a thief"],["אוֹ־כְפֹעֵל","???"],["אָוֶן","iniquity"],["אוֹ־כְנִכְנָס","???"],["בִּתְחוּם","???"],["שֶׁאֵינוֹ","that-Ino"],["שֶׁלּוֹ","that-upon-him"],["׃",""]] },
  { num:"טז", words:[["וְכִי־יְעֻנֶּה","and-that-should-be-oppressed"],["כְּאַחַד","as-one"],["הַמְּשִׁיחִיִּים","the-false-messiahs"],["אַל־יֵבוֹשׁ","do-not-be-ashamed"],["כִּי","because"],["אִם־יוֹדֶה","[compound]-acknowledgeth"],["לֵאלֹהִים","God"],["עַל־הַדָּבָר","concerning-this-thing"],["הַזֶּה","this"],["׃",""]] },
  { num:"יז", words:[["כִּי","because"],["עֵת","time"],["הָחֵל","began"],["הַמִּשְׁפָּט","the-judgment"],["מִבֵּית","from-house-of"],["אֱלֹהִים","God"],["וְאִם־מִמֶּנּוּ","and-if-from-him"],["רִאשֹׁנָה","first"],["מַה־תִּהְיֶה","what-shall-be"],["אַחֲרִית","final-state-of"],["הַמַּמְרִים","the-from-Mary"],["אֶת־בְּשׂוֹרַת","[ACC]-good-tidings-of"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"יח", words:[["הֵן","yea"],["צַדִּיק","righteous"],["כִּמְעַט","nearly"],["לֹא","not"],["יִוָּשֵׁעַ","saved"],["אַף","yea"],["כִּי־רָשָׁע","because-wicked"],["וְחוֹטֵא","and-sinful"],["׃",""]] },
  { num:"יט", words:[["לָכֵן","therefore"],["גַּם־הַמְעֻנִּים","???"],["כִּרְצוֹן","according-to-the-desires-of"],["אֱלֹהִים","God"],["יַפְקִידוּ","he-has-laid-up(they)"],["אֶת־נַפְשֹׁתֵיהֶם","???"],["בְּיַד","in-hand-of"],["אֱלֹהִים","God"],["הַבֹּרֵא","the-creation-of"],["הַנֶּאֱמָן","the-faithful"],["וְיוֹסִיפוּ","so-they may add"],["לַעֲשׂוֹת","to-do"],["הַטּוֹב","good"],["׃",""]] },
];
renderVerseSet(jst1pe_ch2Verses, 'jst1pe-ch2-verses');

})();
