// jst_verses/jst1th.js — 1 Thessalonians (JST) verse data
(function() {
var jst1th_ch1Verses = [
  { num:"א", words:[["וְעוֹד","and-again"],["נְבַקְשָׁה","???"],["מִכֶּם","from-you"],["אַחַי","my-brothers"],["וְנַזְהִיר","???"],["אֶתְכֶם","you"],["בַּאֲדֹנֵינוּ","in-the-our-Lord"],["יֵשׁוּעַ","Yeshua"],["כִּי","because"],["כַּאֲשֶׁר","when/as"],["קִבַּלְתֶּם","received"],["מֵאִתָּנוּ","from-among-us"],["אֵיךְ","how"],["עֲלֵיכֶם","over-you"],["לְהִתְהַלֵּךְ","to-walk"],["וְלִמְצֹא","and-to-find"],["חֵן","favor"],["בְּעֵינֵי","in-eyes-of"],["הָאֱלֹהִים","the-God"],["וְכַאֲשֶׁר","and-as"],["גַּם־הִתְהַלַּכְתֶּם","???"],["כֵּן","thus"],["תּוֹסִיפוּ","continue"],["וְכֵן","and-so"],["תַּרְבּוּ","you-will-they-multiplied"],["עוֹד","any-more"],["׃",""]] },
  { num:"ב", words:[["כִּי","because"],["יְדַעְתֶּם","you-know"],["אֶת־הַמִּצְוֹת","[ACC]-the-commandments"],["אֲשֶׁר","whose"],["נָתַנּוּ","we-put"],["לָכֶם","to-you"],["בְּשֵׁם","by-name"],["הָאָדוֹן","the-Lord"],["יֵשׁוּעַ","Yeshua"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["זֶה","this"],["רְצוֹן","the-will-of"],["הָאֱלֹהִים","the-God"],["קְדֻשַּׁתְכֶם","you will consecrate-you(pl)"],["לְהִתְרַחֵק","???"],["מִן־הַזְּנוּת","from-the-whoredom"],["׃",""]] },
  { num:"ד", words:[["וְיֵדַּע","for-he-shall-know"],["כָּל־אִישׁ","every-man"],["מִכֶּם","from-you"],["לְהִשְׁתַּמֵּשׁ","to-use"],["בְּכִלְיוֹ","in-utensils-its"],["בִּקְדֻשָּׁה","in-holiness"],["וִיקָר","and-honor"],["׃",""]] },
  { num:"ה", words:[["וְלֹא־בְתַאֲוַת","and-not-???"],["זִמָּה","there-could-not"],["כְּדֶרֶךְ","after-manner-of"],["הַגּוֹיִם","the-nations"],["אֲשֶׁר־אֵינָם","whose-they-are-not"],["יֹדְעִים","knowing"],["הָאֱלֹהִים","the-God"],["׃",""]] },
  { num:"ו", words:[["וְלֹא־יַעֲשֹׁק","and-not-it is violent"],["אִישׁ","man-of"],["וְיוֹנֶה","and-he oppressed"],["אֶת־אָחִיו","[ACC] another"],["בְּמַשָׂא","in-from-lift-up"],["וּמַתָּן","and-a-gift"],["כִּי־נוֹקֵם","???"],["יְהוָֹה","the-Lord"],["עַל־כָּל־זֹאת","upon-all-this"],["כַּאֲשֶׁר","when/as"],["כְּבָר","already-come"],["אָמַרְנוּ","said-us"],["אֲלֵיכֶם","unto-you"],["וְהַעִידֹנוּ","???"],["בָכֶם","over-you"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["לֹא־קָרָא","not-called"],["אוֹתָנוּ","us"],["הָאֱלֹהִים","the-God"],["לַטֻּמְאָה","to-the-uncleanness"],["כִּי","because"],["אִם־לַקְּדֻשָּׁה","???"],["׃",""]] },
  { num:"ח", words:[["עַל־כֵּן","therefore"],["הַבּוֹזֶה","the-is despising"],["לֹא","not"],["בֶן־אָדָם","Bn-man"],["הוּא","it-is"],["בוֹזֶה","the one who despises"],["כִּי","because"],["אִם־אֶת־הָאֱלֹהִים","[compound]-[ACC]-the-God"],["אֲשֶׁר","whose"],["גַּם־שָׂם","also-set"],["בְּקִרְבֵּנוּ","among-us"],["אֶת־רוּחַ","[ACC]-the-Spirit-of"],["קָדְשׁוֹ","his-holiness"],["׃",""]] },
  { num:"ט", words:[["וְעַל־אַהֲבַת","and-upon-love-of"],["הָאַחִים","the-brethren"],["אֵין־צֹרֶךְ","there-is-no-need"],["לִכְתֹּב","to-write"],["אֲלֵיכֶם","unto-you"],["הֲלֹא","do-not"],["אַף־אַתֶּם","yea-you-are"],["לְמוּדֵי","who were trained of"],["יְהוָֹה","the-Lord"],["לְאַהֲבָה","to-love"],["אִישׁ","man-of"],["אֶת־רֵעֵהוּ","[ACC]-another"],["׃",""]] },
  { num:"י", words:[["וְגַם","and-also"],["עֲשִׂיתֶם","you-have-done"],["כֵּן","thus"],["לְכָל־אֲחֵיכֶם","to-all-your-brethren"],["אֲשֶׁר","whose"],["בְּכָל־מַקְדּוֹנְיָא","in-all-Macedonia"],["אֲבָל","but/however"],["נְבַקְשָׁה","???"],["מִכֶּם","from-you"],["אַחַי","my-brothers"],["אֲשֶׁר","whose"],["כֵּן","thus"],["תַּעֲשׂוּ","you-do"],["וְכֵן","and-so"],["תּוֹסִיפוּ","continue"],["׃",""]] },
  { num:"יא", words:[["וְתִשְׁתַּדְּלוּ","and-you-shall-strive"],["לָשֶׁבֶת","to-dwell"],["בְּנָחַת","in-will we descend"],["וְתַעֲשׂוּ","and-perform"],["אִישׁ","man-of"],["מְלַאכְתּוֹ","His-work"],["בַּעֲמַל","at-the trouble of"],["יְדֵיכֶם","your-hands"],["כַּאֲשֶׁר","when/as"],["צִוִּינוּ","we-commanded"],["אֶתְכֶם","you"],["׃",""]] },
  { num:"יב", words:[["לְמַעַן","in-order-that"],["תִּתְהַלְּכוּ","you-walk"],["כְהֹגֶן","as-Hgn"],["עִם־אֹתָם","with-them"],["שֶׁבַּחוּץ","that-in-the-except"],["וְלֹא","and-not"],["תִּצְטָרֲכוּ","you-need"],["לְאָדָם","to-man"],["׃",""]] },
  { num:"יג", words:[["וְעַל־דְּבַר","and-upon-word-of"],["הַיְשֵׁנִים","the-old"],["אֶחָי","brothers-my"],["לֹא־נְכַחֵד","not-we will hide"],["מִכֶּם","from-you"],["דָּבָר","things"],["לְמַעַן","in-order-that"],["לֹא","not"],["תֵּעָצְבוּ","you be grieved"],["כַּאֲחֵרִים","as-the-others"],["אֲשֶׁר","whose"],["אֵין־לָהֶם","there-is-no-to-them"],["תִּקְוָה","hope"],["׃",""]] },
  { num:"יד", words:[["כִּי","because"],["אִם־נַאֲמִין","[compound]-we-believe"],["אֲשֶׁר־מֵת","whose-is-dead"],["יֵשׁוּעַ","Yeshua"],["וַיֶּחִי","and-has it lived?"],["כֵּן","thus"],["יָבִיא","shall-bring"],["הָאֱלֹהִים","the-God"],["גַּם","also"],["אֶת־הַיְשֵׁנִים","[ACC]-the-old"],["בְּיֵשׁוּעַ","in-Jesus"],["אִתּוֹ","with-him"],["׃",""]] },
  { num:"טו", words:[["כִּי","because"],["אֶת־זֹאת","[ACC]-this"],["נֹאמַר","it-was-said"],["לָכֶם","to-you"],["בִּדְבַר","of-the-promise-of"],["יְהוָֹה","the-Lord"],["כִּי","because"],["אֲנַחְנוּ","we"],["הַחַיִּים","life"],["הַנּוֹתָרִים","the-remaining"],["עַד־בֹּא","until-come"],["הָאָדוֹן","the-Lord"],["לֹאֹ","not"],["נְקַדֵּם","???"],["אֶת־הַיְשֵׁנִים","[ACC]-the-old"],["׃",""]] },
  { num:"טז", words:[["כִּי","because"],["הָאָדוֹן","the-Lord"],["הוּא","it-is"],["יֵרֵד","Jared"],["מִן־הַשָּׁמַיִם","from-the-heavens"],["בִּתְרוּעָה","with-shouting"],["בְּקוֹל","the-voice-of"],["שַׂר","the-king's-captain"],["הַמַּלְאָכִים","the-angels"],["וּבְשׁוֹפַר","and-in-a ram's horn of"],["אֱלֹהִים","God"],["וְאָז","and-then"],["יָקוּמוּ","they-shall-stand"],["רִאשׁוֹנָה","first"],["הַמֵּתִים","the-dead"],["בַּמָּשִׁיחַ","in-the-Messiah"],["׃",""]] },
  { num:"יז", words:[["אַחֲרֵי־כֵן","hereafter"],["אֲנַחְנוּ","we"],["הַחַיִּים","life"],["הַנּוֹתָרִים","the-remaining"],["נִלָּקַח","we-will-took"],["אִתָּם","with-them"],["יַחְדָּו","together"],["בַּעֲנָנִים","in-the-clouds"],["לִקְרַאת","to-meet"],["הָאָדוֹן","the-Lord"],["לָאֲוִיר","to-the-air"],["וּבְכֵן","and-in-such"],["נִהְיֶה","let-us-be"],["תָמִיד","continually"],["עִם־הָאָדוֹן","with-the-Lord"],["׃",""]] },
  { num:"יח", words:[["לָכֵן","therefore"],["נַחֲמוּ","comfort"],["זֶה","this"],["אֶת־זֶה","[ACC]-this"],["בַּדְּבָרִים","in-the-words"],["הָאֵלֶּה","these"],["׃",""]] },
];
renderVerseSet(jst1th_ch1Verses, 'jst1th-ch1-verses');

})();
