// jst_verses/jst1ti.js — 1 Timothy (JST) verse data
(function() {
var jst1ti_ch1Verses = [
  { num:"א", words:[["וְעַתָּה","and-now"],["קֹדֶם","before"],["כָּל־דָּבָר","all-things"],["אֲבַקְשָׁה","I will seek"],["מִכֶּם","from-you"],["לָשֵׂאת","to-bear"],["תְּפִלּוֹת","the-prayers-of"],["וְתַחֲנוּנִים","and-supplication"],["וּבַקָּשׁוֹת","and-to seek(pl)"],["וְתוֹדוֹת","and-thank-offerings"],["בְּעַד","on-behalf-of"],["כָּל־בְּנֵי","all-the-sons-of"],["אָדָם","man"],["׃",""]] },
  { num:"ב", words:[["בְּעַד","on-behalf-of"],["הַמְּלָכִים","the-kings"],["וְכָל־הַשַּׁלִּיטִים","and-all-???"],["לְמַעַן","in-order-that"],["נִחְיֶה","we-will-lived"],["חַיֵּי","the-life-of"],["הַשְׁקֵט","will be quietness"],["וָבֶטַח","and-security"],["בְּכָל־חֲסִידוּת","in-all-???"],["וָישֶׁר","and-he struggled"],["׃",""]] },
  { num:"ג", words:[["כִּי־כֵן","because-thus"],["טוֹב","good"],["וְרָצוּי","and-was acceptable"],["בְּעֵינֵי","in-eyes-of"],["אֱלֹהִים","God"],["מוֹשִׁיעֵנוּ","our-Savior"],["׃",""]] },
  { num:"ד", words:[["אֲשֶׁר","whose"],["חֶפְצוֹ","His-pleasure"],["כִּי","because"],["יִוָּשְׁעוּ","shall-be-saved"],["כָּל־בְּנֵי","all-the-sons-of"],["הָאָדָם","man"],["וִיקַבְּלוּ","and-they received it"],["דַּעַת","true-knowledge"],["הָאֱמֶת","the-true"],["׃",""]] },
  { num:"ה", words:[["כִּי","because"],["אֶחָד","one"],["הָאֱלֹהִים","the-God"],["וְאֶחָד","and-one"],["הַסַּרְסוֹר","???"],["בֵּין","among"],["אֱלֹהִים","God"],["וּבֵין","and-between"],["בְּנֵי","sons-of"],["אָדָם","man"],["הוּא","it-is"],["בֶן־אָדָם","Bn-man"],["הַמָּשִׁיחַ","the-Messiah"],["יֵשׁוּעַ","Yeshua"],["׃",""]] },
  { num:"ו", words:[["אֲשֶׁר","whose"],["נָתַן","was-given"],["אֶת־נַפְשׁוֹ","his-life"],["כֹּפֶר","a ransom"],["בְּעַד","on-behalf-of"],["הַכֹּל","all"],["וְזֹאת","and-this"],["הָעֵדוּת","the-testimony"],["הַבָּאָה","the-coming"],["בְּעִתָּהּ","at-appropriate time-its"],["׃",""]] },
  { num:"ז", words:[["אֲשֶׁר","whose"],["אֲנִי","I"],["הָפְקַדְתִּי","have-I-deposited"],["לָהּ","it"],["לְכָרוֹז","to-a-proclamation"],["וּלְשָׁלִיחַ","and-to-apostle"],["אֱמֶת","truth"],["אֲנִי","I"],["מַגִּיד","declare"],["בַּמָּשִׁיחַ","in-the-Messiah"],["וְלֹא","and-not"],["אֲשַׁקֵּר","I will deal falsely"],["מוֹרֵה","teacher(f)"],["הַגּוֹיִם","the-nations"],["בֶּאֱמוּנָה","with-much-faith"],["וּבֶאֱמֶת","be-a-happier"],["׃",""]] },
  { num:"ח", words:[["לָכֵן","therefore"],["רְצוֹנִי","my-desire"],["שֶׁיִּתְפַּלֲלוּ","that-they will pray"],["הָאֲנָשִׁים","men"],["בְּכָל־מָקוֹם","with-all-place"],["וְיִשְׂאוּ","and-bear"],["יְדֵיהֶם","their-hands"],["קֹדֶשׁ","holy"],["בְּלִי־רֹגֶז","without-turmoil"],["וּמְזִמּוֹת","and-purposes"],["׃",""]] },
  { num:"ט", words:[["וְכֵן","and-so"],["גַּם־הַנָּשִׁים","also-that-the-women"],["תִּתְיַפֶּינָה","???"],["בְּתִלְבּשֶׁת","in-clothing"],["נָאָה","exceedingly-fine"],["בְּבשֶׁת","with-shame"],["פָּנִים","face"],["וּצְנִיעוּת","???"],["לֹא","not"],["בְּמַחְלְפוֹת","in-the plaits of"],["הָרֹאשׁ","the-head"],["לֹא","not"],["בְזָהָב","in-gold"],["לֹא","not"],["בִפְנִינִים","in-fine-things-of"],["וְלֹא","and-not"],["בְּמַלְבּוּשִׁים","???"],["יְקָרִים","precious"],["׃",""]] },
  { num:"י", words:[["אֶלָּא","but-rather"],["בְּמַעֲשִׂים","in-good-works"],["טוֹבִים","good"],["כָּרָאוּי","as-fitting"],["לַנָּשִׁים","to-women"],["אֲשֶׁר","whose"],["בָּחֲרוּ","they-chose"],["לָהֶן","for-them"],["יִרְאַת","the-fear-of"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"יא", words:[["הָאִשָּׁה","the-a-woman"],["תִּלְמַד","you-will-taught"],["דּוּמָם","silence"],["בְּכָל־הַכְנָעָה","in-all-???"],["׃",""]] },
  { num:"יב", words:[["וְאֵינֶנִּי","and-I-am-not"],["נֹתֵן","was-given"],["רְשׁוּת","authority"],["לָאִשָּׁה","to the-woman"],["לְלַמֵּד","to-teach"],["אַף","yea"],["לֹא","not"],["לְהִתְנַשֵׂא","to-be-lifted-up"],["עַל־הָאִישׁ","upon-the-man"],["אַךְ","but"],["תִּדּוֹם","???"],["׃",""]] },
  { num:"יג", words:[["כִּי","because"],["אָדָם","man"],["נוֹצַר","it was formed"],["בָּרִאשׁוֹנָה","at-first"],["וְאַחֲרָיו","and-after-it"],["חַוָּה","Eve"],["׃",""]] },
  { num:"יד", words:[["וְאָדָם","and-Adam"],["לֹא","not"],["נִפְתָּה","it has been deceived"],["כִּי","because"],["אִם־הָאִשָּׁה","[compound]-the-a-woman"],["שָׁמְעָה","she-heard"],["לְקוֹל","to-voice-of"],["הַמֵּסִית","the-was-stirring-up"],["וַתָּבֹא","and-comes"],["לִידֵי","unto"],["עֲבֵרָה","is fury"],["׃",""]] },
  { num:"טו", words:[["אֲבָל","but/however"],["תִּוָּשַׁע","it will be saved"],["בְּלִדְתָּהּ","when-gave birth-she"],["בָּנִים","children"],["אִם","[compound]"],["תַּעֲמֹדְנָה","they stood"],["בָּאֱמוּנָה","in-the-faith"],["וּבָאַהֲבָה","and-in-love"],["וּבַקְּדֻשָּׁה","and-in-holiness"],["עִם־הַצְּנִיעוּת","???"],["׃",""]] },
];
renderVerseSet(jst1ti_ch1Verses, 'jst1ti-ch1-verses');

var jst1ti_ch2Verses = [
  { num:"א", words:[["אֱמֶת","truth"],["הַדָּבָר","the-thing"],["אִישׁ","man-of"],["כִּי־יְבַקֵּשׁ","because-he-should-look-for"],["לִהְיוֹת","to-be"],["הֶגְמוֹן","???"],["לְמַעֲשֶׂה","to-a-work"],["טוֹב","good"],["מִתְאַוֶּה","from-it will desire"],["׃",""]] },
  { num:"ב", words:[["וְהֶגְמוֹן","???"],["הָעֵדָה","the-church"],["צָרִיךְ","necessary"],["לִהְיוֹת","to-be"],["בְּאֵין","in-un"],["דֹּפִי","a fault"],["בַּעַל־אִשָּׁה","in-the-yoke-a-woman"],["אַחַת","one"],["משֵׁל","saying"],["בְּרוּחוֹ","in-His-Spirit"],["צָנוּעַ","???"],["וְנֶחְמָד","and-desirable"],["לַבְּרִיּוֹת","to-the-people pure of(pl)"],["מַכְנִיס","from-as-fugitive"],["אֹרְחִים","travelers"],["וּמֵבִין","and-understanding"],["לְלַמֵּד","to-teach"],["וְלֹא","and-not"],["אֹהֵב","loves"],["יַיִן","wine"],["וְלֹא־בַעַל","and-not-is a master of"],["אֶגְרֹף","a fist"],["וְלֹא","and-not"],["בֹצֵעַ","one greedy for unjust gain"],["בֶּצַע","gain/profit"],["רָע","evil"],["׃",""]] },
  { num:"ג", words:[["כִּי","because"],["אִם־דָּן","[compound]-Dan"],["לְכַף־זְכוּת","for-the sole of-merit"],["וְלֹא","and-not"],["אִישׁ","man-of"],["מִדְיָנִים","Midianites"],["וְלֹא","and-not"],["אֹהֵב","loves"],["כָּסֶף","silverlings"],["׃",""]] },
  { num:"ד", words:[["וִיהִי","and-may-be"],["מַנְהִיג","leader"],["אֶת־בֵּיתוֹ","his-household"],["בְּטוֹב","the-welfare-of"],["וּמַדְרִיךְ","???"],["אֶת־בָּנָיו","[ACC] his-sons"],["לְמִשְׁמַעְתּוֹ","to-bodyguard-his"],["בְּכָל־הַיּשֶׁר","in-all-???"],["׃",""]] },
  { num:"ה", words:[["כִּי","because"],["אִם־לֹא","if-not"],["יֵדַע","shall-know"],["אִישׁ","man-of"],["לְהַנְהִיג","???"],["אֶת־בֵּיתוֹ","his-household"],["אֵיכָכָה","how?"],["יוּכַל","can"],["לְהַשְׁגִּיחַ","to-he-watched-over"],["עַל־עֲדַת","upon-church-of"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"ו", words:[["וְאַל־יְהִי","and-do-not-let-this-be"],["תַּלְמִיד","disciple"],["חָדָשׁ","fresh/new"],["פֶּן־יִרְהַב","???"],["לִבּוֹ","his-heart"],["וְיִפֹּל","and-shall-fall"],["בְּדִין","in-of-judgment-of"],["הַמַּשְׂטִין","???"],["׃",""]] },
  { num:"ז", words:[["וְהוּא","and-it"],["גַם־צָרִיךְ","also-necessary"],["הֱיוֹת","have"],["לוֹ","him"],["שֵׁם","name-of"],["טוֹב","good"],["בְּפִי","by-mouth-of"],["אֹתָם","them"],["שֶׁבַּחוּץ","that-in-the-except"],["פֶּן־יִפֹּל","lest-shall-fall"],["בְּחֶרְפָּה","in-scorn"],["וּבְמוֹקֵשׁ","and-in-will be a snare"],["הַמַּשְׂטִין","???"],["׃",""]] },
  { num:"ח", words:[["וְכֵן","and-so"],["גַּם־הַשַּׁמָּשִׁים","???"],["יִהְיוּ","shall-be"],["יְשָׁרִים","just"],["וְלֹא","and-not"],["מַחֲלִיקֵי","???"],["לָשׁוֹן","tongue"],["וְלֹא","and-not"],["אֹהֲבִים","love"],["סְבֹא־יַיִן","a drunkard-wine"],["וְלֹא","and-not"],["נֹטִים","???"],["אַחֲרֵי","after"],["בֶצַע־רָע","unjust gain-evil"],["׃",""]] },
  { num:"ט", words:[["כִּי","because"],["אִם־יִשְׁמְרוּ","if-they-keep"],["אֶת־סוֹד","[ACC]-counsels-of"],["הָאֱמוּנָה","the-faith"],["בְּרוּחַ","in-the-Spirit"],["טְהוֹרָה","is pure"],["׃",""]] },
  { num:"י", words:[["וְגַם־הֵם","that-they-also"],["יִבָּחֲנוּ","they may be tested"],["בָרִאשֹׁנָה","at the-first"],["וְאַחַר","and-then"],["כֵּן","thus"],["יְשַׁמְּשׁוּ","???"],["אִם־אֵין","if-there-be-no"],["בָּהֶם","in-them"],["דֹּפִי","a fault"],["׃",""]] },
  { num:"יא", words:[["וְכֵן","and-so"],["הַנָּשִׁים","that-the-women"],["תִּהְיֶינָה","there-shall-be(f)"],["יְשָׁרוֹת","upright(f.pl)"],["וְלֹא","and-not"],["מַלְשִׁינוֹת","???"],["משְׁלוֹת","saying(pl)"],["בְּרוּחָן","in-the-Spirit-their"],["וְנֶאֱמָנוֹת","and-lasting"],["בַּכֹּל","in-all"],["׃",""]] },
  { num:"יב", words:[["הַשַּׁמָּשִׁים","???"],["יִהְיוּ","shall-be"],["כָל־אֶחָד","all-one"],["בַּעַל־אִשָּׁה","in-the-yoke-a-woman"],["אֶחָת","one"],["וּמְנַהֲלִים","and-to-guide(pl)"],["בְּטוֹב","the-welfare-of"],["אֶת־בְּנֵיהֶם","[ACC]-their-children"],["וְאֶת־בָּתֵּיהֶם","and-[ACC]-their-own-houses"],["׃",""]] },
  { num:"יג", words:[["כִּי","because"],["הַמְשַׁמְּשִׁים","???"],["כַּהֹגֶן","as-the-Hgn"],["יִקְנוּ","people will buy"],["לְנַפְשָׁם","to-their-own-souls"],["מַעֲלָה","is bringing up"],["טוֹבָה","good"],["וּבִטָּחוֹן","and-confidence"],["רַב","great"],["בֶּאֱמוּנַת","in-faith-of"],["הַמָּשִׁיחַ","the-Messiah"],["יֵשׁוּעַ","Yeshua"],["׃",""]] },
  { num:"יד", words:[["זֹאת","this"],["אֲנִי","I"],["כֹתֵב","writing"],["לְךָ","for-you"],["וַאֲקַוֶּה","and-I may wait for"],["לָבֹא","to-come-forth"],["אֵלֶיךָ","to-you(f)"],["בִּמְהֵרָה","soon"],["׃",""]] },
  { num:"טו", words:[["וְאִם־אֶתְמַהְמַהּ","and-[compound]-???"],["הִנֵּה","behold"],["תֵדַע","you will know"],["אֵיךְ","how"],["לְהִתְנַהֵג","to-conduct-oneself"],["בְּבֵית","in-house-of"],["הָאֱלֹהִים","the-God"],["אֲשֶׁר","whose"],["הִיא","it-is"],["עֲדַת","church-of"],["אֱלֹהִים","God"],["חַיִּים","living"],["עַמּוּד","the pillar of"],["הָאֱמֶת","the-true"],["וּמְכוֹנָהּ","and-stand"],["׃",""]] },
  { num:"טז", words:[["וּבְוַדָּי","???"],["גָּדוֹל","great"],["סוֹד","counsels-of"],["הַחֲסִידוּת","the-piety"],["אֲשֶׁר","whose"],["נִגְלָה","has-been-made-manifest"],["בַבָּשָׂר","in-the-flesh"],["נִצְדַּק","it will be put right"],["בָּרוּחַ","in-the-Spirit"],["נִרְאָה","appeared"],["לַמַּלְאָכִים","to the-messengers"],["הֻגַּד","it-was-declared"],["בַּגּוֹיִם","by-the-nations"],["נִתְקַבֵּל","???"],["בֶּאֱמוּנָה","with-much-faith"],["בָּעוֹלָם","of-the-world"],["נַעֲלָה","it was taken up"],["בְּכָבוֹד","in-glory"],["׃",""]] },
];
renderVerseSet(jst1ti_ch2Verses, 'jst1ti-ch2-verses');

var jst1ti_ch3Verses = [
  { num:"א", words:[["כֹּל","all"],["אֲשֶׁר־עֹל","whose-yoke"],["הָעַבְדוּת","bondage"],["עֲלֵיהֶם","against-them"],["יִהְיוּ","shall-be"],["אֲדֹנֵיהֶם","master-their"],["בְּעֵינֵיהֶם","in-their-eyes"],["רְאוּיִם","worthy"],["לְכָל־כָּבוֹד","to-all-glorious"],["לְמַעַן","in-order-that"],["אֲשֶׁר","whose"],["לֹא־יְחֻלַּל","not-he will profane"],["שֵׁם","name-of"],["הָאֱלֹהִים","the-God"],["וְהַלֶּקַח","and-the being taken of"],["׃",""]] },
  { num:"ב", words:[["וְאֹתָם","and-with-them"],["שֶׁאֲדֹנֵיהֶם","that-master-their"],["מַאֲמִינִים","believing"],["אַל־יֵקַלּוּ","do-not-they-shall-be-eased"],["בְעֵינֵיהֶם","own-eyes"],["מִפְּנֵי","because-of"],["שֶׁהֵם","that-they"],["אַחִים","brothers"],["כִּי","because"],["אִם־יַעַבְדוּ","if-they-labor"],["אֹתָם","them"],["יוֹתֵר","more"],["מִפְּנֵי","because-of"],["שֶׁמַּאֲמִינִים","that-believing"],["וַאֲהוּבִים","and-beloved(pl)"],["הֵם","they"],["הַמְקַבְּלִים","the-from-received"],["אֶת־הַטּוֹבָה","[ACC]-the-good"],["אֶת־זֹאת","[ACC]-this"],["תְּלַמֵּד","you-shall-have-taught"],["וּתְצַוֶּה","and-you will command"],["׃",""]] },
  { num:"ג", words:[["הָאִישׁ","the-man"],["אֲשֶׁר","whose"],["יוֹרֶה","teaches"],["תּוֹרָה","a-Bible"],["אַחֶרֶת","any-other"],["וְלֹא","and-not"],["יַעֲמֹד","shall-stand"],["בְּדִבְרֵי","with-words-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["הַבְּרִיאִים","the-whole/healthy"],["וּבְלֶקַח","and-in-the-learning-of"],["הַחֲסִידוּת","the-piety"],["׃",""]] },
  { num:"ד", words:[["נַפְשׁוֹ","his-soul"],["עֻפְּלָה","it is swollen"],["וְלֹא","and-not"],["יָדַע","he-knew"],["מְאוּמָה","anything"],["כִּי","because"],["אִם־חֹלֶה","[compound]-is sick"],["הוּא","it-is"],["בִּשְׁאֵלוֹת","in-he has asked(pl)"],["וְתוֹכְחוֹת","and-rebukes of"],["מִלִּים","utterance"],["הַמּוֹלִידוֹת","the-one who causes to bring forth(pl)"],["קִנְאָה","jealousy"],["וּמְרִיבָה","and-contention"],["וְגִדּוּפִים","and-blasphemies"],["וַחֲשָׁד","???"],["רָע","evil"],["׃",""]] },
  { num:"ה", words:[["וִכּוּחֵי","???"],["הֶבֶל","the-vanities"],["מֵאֲנָשִׁים","there-were-of-men"],["נִשְׁחֲתֵי","???"],["דַעַת","knowledge"],["וּמְחֻסְּרֵי","???"],["אֱמֶת","truth"],["הַשָׂמִים","the-who-put"],["אֶת־הַחֲסִידוּת","[ACC]-the-piety"],["לִדְבַר","to-word-of"],["בָּצַע","unjust gain"],["סוּר","depart"],["מֵאֲנָשִׁים","there-were-of-men"],["כָּאֵלֶּה","such-as-these"],["׃",""]] },
  { num:"ו", words:[["וְאָמְנָם","and-indeed"],["בֶּצַע","gain/profit"],["גָּדוֹל","great"],["הִיא","it-is"],["הַחֲסִידוּת","the-piety"],["עִם־לֵב","with-heart"],["שָׂמֵחַ","happy"],["בְּחֶלְקוֹ","in-his-part"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["בָאנוּ","we-came"],["לָעוֹלָם","into-the-world"],["וְאֵין","and-has-no"],["בְּיָדֵינוּ","in-our-hands"],["מְאוּמָה","anything"],["וְיָדוּעַ","and-known"],["שֶׁאַף","that-yea"],["נֵצֵא","let-us-go-forth"],["מִמֶּנּוּ","from-him"],["וְאֵין","and-has-no"],["בְּיָדֵינוּ","in-our-hands"],["מְאוּמָה","anything"],["׃",""]] },
  { num:"ח", words:[["וְעַל־כֵּן","and-therefore"],["אִם","[compound]"],["מָזוֹן","nourishment"],["וּכְסוּת","and-as-clothing"],["לָנוּ","us"],["נִסְתַּפְּקָה","???"],["בָּהֶם","in-them"],["׃",""]] },
  { num:"ט", words:[["אֲבָל","but/however"],["הַמְבַקְשִׁים","the-ones-seeking"],["לְהַעֲשִׁיר","to-the-rich"],["יָבֹאוּ","come"],["לִידֵי","unto"],["נִסָּיוֹן","an-attempt"],["וְיִפְּלוּ","and-they-shall-fall"],["בְמוֹקְשִׁים","in-snares"],["וּבְרֹב","and-His-great"],["תַּאֲוֹת","chambers"],["סְכָלוֹת","folly"],["וּמַשְׁחִיתוֹת","and-a destroyer of(pl)"],["הַמַּשְׁקִיעוֹת","???"],["אֶת־הָאָדָם","[ACC]-man"],["בַּשַּׁחַת","in-the-pit"],["וּבָאֲבַדּוֹן","and-in-Abaddon"],["׃",""]] },
  { num:"י", words:[["כִּי","because"],["שֹׁרֶשׁ","the-root-of"],["כָּל־הָרָעוֹת","all-the-injuries"],["אַהֲבַת","love-of"],["הַכָּסֶף","the-money"],["וְיֵשׁ","and-there-was"],["לְהוּטִים","???"],["אַחֲרָיו","after-him"],["אֲשֶׁר","whose"],["סָרוּ","they-have-all-gone"],["מִן־הָאֱמוּנָה","from-the-faith"],["וַיַּעֲצִיבוּ","???"],["אֶת־נַפְשָׁם","[ACC]-their-souls"],["בְּמַכְאֹבִים","in-are pains"],["רַבִּים","many"],["׃",""]] },
  { num:"יא", words:[["וְאַתָּה","for-you"],["אִישׁ","man-of"],["הָאֱלֹהִים","the-God"],["בְּרַח־לְךָ","flee-for-you"],["מֵאֵלֶּה","than-these"],["וּרְדֹף","and-pursue"],["צְדָקָה","a-state-of-righteousness"],["וַחֲסִידוּת","???"],["וֶאֱמוּנָה","and-great-faith"],["וְאַהֲבָה","and-love"],["וְסַבְלָנוּת","and-patience"],["וַעֲנָוָה","and-humility"],["׃",""]] },
  { num:"יב", words:[["הִלָּחֵם","fight"],["הַמִּלְחָמָה","the-battle"],["הַטּוֹבָה","the-good"],["מִלְחֶמֶת","war"],["הָאֱמוּנָה","the-faith"],["וֶאֱחֹז","and-hold"],["אֶת־חַיֵּי","[ACC]-the-life-of"],["הָעוֹלָמִים","of-Eternity"],["אֲשֶׁר","whose"],["נִקְרֵאתָ","we-will-you-called"],["לָהֶם","to-them"],["וְהוֹדֵיתָ","???"],["הוֹדָאָה","???"],["יָפָה","yea-even-a-very-beautiful"],["בִּפְנֵי","in-presence-of"],["עֵדִים","many-witnesses"],["רַבִּים","many"],["׃",""]] },
  { num:"יג", words:[["הִנְנִי","behold-I"],["מְצַוְּךָ","am commanding-you"],["נֶגֶד","against"],["הָאֱלֹהִים","the-God"],["הַמְחַיֶּה","the-are preserving alive"],["אֶת־כֹּל","[ACC]-all"],["וְנֶגֶד","and-against"],["הַמָּשִׁיחַ","the-Messiah"],["יֵשׁוּעַ","Yeshua"],["אֲשֶׁר","whose"],["הֵעִיד","he-testified"],["הַהוֹדָאָה","???"],["הַיָּפָה","the-beautiful"],["לִפְנֵי","before"],["פָּנְטִיּוֹס","???"],["פִּילָטוֹס","Pilate"],["׃",""]] },
  { num:"יד", words:[["אֲשֶׁר","whose"],["תִּשְׁמֹר","you-keep"],["אֶת־הַמִּצְוָה","[ACC]-the-commandment"],["בְּאֵין־שֶׁמֶץ","in-un-inkling"],["וָדֹפִי","and-a fault"],["עַד־הוֹפָעַת","until-you have shone forth"],["הַמָּשִׁיחַ","the-Messiah"],["יֵשׁוּעַ","Yeshua"],["אֲדֹנֵינוּ","our-Lord"],["׃",""]] },
  { num:"טו", words:[["אֲשֶׁר","whose"],["יַרְאֶנָּה","he will see-it"],["בְעִתָּהּ","in-is-her-time"],["הַמְבֹרָךְ","the-blessed-are"],["וְהַשַּׁלִּיט","and-was the-ruler"],["לְבַדּוֹ","alone"],["מֶלֶךְ","king-of"],["הַמְּלָכִים","the-kings"],["וַאֲדֹנֵי","and-the lord of"],["הָאֲדֹנִים","the-lords"],["׃",""]] },
  { num:"טז", words:[["אֲשֶׁר","whose"],["הוּא","it-is"],["לְבַדּוֹ","alone"],["חַי","living"],["וְקַיָּם","and-enduring"],["וְהוּא","and-it"],["שֹׁכֵן","dwells"],["אוֹר","light"],["נִשְׂגָּב","is-exalted"],["וְאִישׁ","and-the-man-of"],["לֹא","not"],["רָאָהוּ","saw-Him"],["וְלֹא","and-not"],["יוּכַל","can"],["לִרְאוֹתוֹ","to-see-him"],["וְלוֹ","and-unto-him"],["הַכָּבוֹד","the-glorious"],["וּגְבוּרַת","and-power-of"],["עוֹלָמִים","everlasting"],["אָמֵן","amen"],["׃",""]] },
  { num:"יז", words:[["אֶת־עֲשִׁירֵי","[ACC]-rich ones of"],["הָעוֹלָם","the-world"],["הַזֶּה","this"],["תְּצַוֶּה","you will command"],["שֶׁלּא","that-there-should-be-no"],["יָרוּם","he-shall-be-exalted"],["לְבָבָם","their-hearts"],["וְלֹא־יִבְטְחוּ","and-not-they may trust"],["בָּעֹשֶׂר","in-riches"],["הַבּוֹגֵד","the-traitor"],["כִּי","because"],["אִם־בֵּאלֹהִים","[compound]-in-God"],["חַיִּים","living"],["הַמַּסְפִּיק","the-sufficient"],["לָנוּ","us"],["דַּי","is-sufficient"],["וְהוֹתֵר","and-it was more than enough"],["לִשְׂבֹּעַ","to-be satisfied"],["׃",""]] },
  { num:"יח", words:[["וְיִגְמְלוּ","and-shall-be-rewarded(they)"],["טוֹב","good"],["וְיַעְשִׁירוּ","and-they have gained riches"],["בְּמַעֲשִׂים","in-good-works"],["טוֹבִים","good"],["לָתֵת","to-give"],["מֵהוֹנָם","from-their-wealth"],["וְלַעֲזֹר","and-for-help"],["לְזוּלָתָם","to-besides-them"],["׃",""]] },
  { num:"יט", words:[["וְיַאַצְרוּ","and-it will be stored up(they)"],["לָהֶם","to-them"],["אוֹצָר","treasure"],["לִיסוֹד","for-a-foundation"],["טוֹב","good"],["לֶעָתִיד","to-future"],["לָבֹא","to-come-forth"],["לְמַעַן","in-order-that"],["יַשִׂיגוּ","they overtook"],["אֶת־חַיֵּי","[ACC]-the-life-of"],["הָאֱמֶת","the-true"],["׃",""]] },
  { num:"כ", words:[["אַתָּה","you"],["טִימוֹתִיּוֹס","Timothy"],["שְׁמֹר","watch"],["אֶת־הַפִּקָּדוֹן","[ACC]-the-item entrusted"],["וְהִתְרַחֵק","???"],["מִדִּבְרֵי","of-things-of"],["הֶבֶל","the-vanities"],["הַפְּסוּלִים","???"],["וּמִן־וִכּוּחֵי","and-from-???"],["הַמַּדָּע","the-knowledge"],["הַנִּקְרָא","the-called"],["כֵן","thus"],["בְּטָעוּת","???"],["׃",""]] },
  { num:"כא", words:[["אֲשֶׁר","whose"],["יֵשׁ","there-is"],["מִתְפָּאֲרִים","from-you will go over the boughs(pl)"],["בּוֹ","against-him"],["וַיִּתְעוּ","and-they-shall-err"],["מִן־הָאֱמוּנָה","from-the-faith"],["הַחֶסֶד","mercy"],["עִמָּךְ","your-people"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(jst1ti_ch3Verses, 'jst1ti-ch3-verses');

})();
