// jst_verses/jst1ch.js — 1 Chronicles (JST) verse data
(function() {
var jst1ch_ch1Verses = [
  { num:"א", words:[["וַיַּעֲמֹד","and-stood"],["שָׂטָן","adversary"],["עַל־יִשְׂרָאֵל","upon-Israel"],["וַיָּסֶת","and-he-incited"],["אֶת־דָּוִיד","[ACC]-David"],["לִמְנוֹת","to-count"],["אֶת־יִשְׂרָאֵל","[ACC]-Israel"],["׃",""]] },
  { num:"ב", words:[["וַיֹּאמֶר","and-said"],["דָּוִיד","David"],["אֶל־יוֹאָב","to-Joab"],["וְאֶל־שָׂרֵי","and-captains-of"],["הָעָם","the-people"],["לְכוּ","go"],["סִפְרוּ","count"],["אֶת־יִשְׂרָאֵל","[ACC]-Israel"],["מִבְּאֵר","from-Beer"],["שֶׁבַע","seven"],["וְעַד־דָּן","and-unto-Dan"],["וְהָבִיאוּ","and-bring"],["אֵלַי","to-me"],["וְאֵדְעָה","so-let me know"],["אֶת־מִסְפָּרָם","[ACC]-in-number"],["׃",""]] },
  { num:"ג", words:[["וַיֹּאמֶר","and-said"],["יוֹאָב","Joab"],["יוֹסֵף","Joseph"],["יְהֹוָה","the-LORD"],["עַל־עַמּוֹ","upon-his-people"],["כָּהֵם","like-them"],["מֵאָה","a-hundredth"],["פְעָמִים","times"],["הֲלֹא","do-not"],["אֲדֹנִי","my-Lord"],["הַמֶּלֶךְ","the-king"],["כֻּלָּם","all-of-them"],["לַאדֹנִי","to-master-my"],["לַעֲבָדִים","for-servants"],["לָמָּה","why"],["יְבַקֵּשׁ","he-should-look-for"],["זֹאת","this"],["אֲדֹנִי","my-Lord"],["לָמָּה","why"],["יִהְיֶה","he-shall-be"],["לְאַשְׁמָה","to-guilt"],["לְיִשְׂרָאֵל","to-Israel"],["׃",""]] },
  { num:"ד", words:[["וּדְבַר־הַמֶּלֶךְ","and-spoke-the-king"],["חָזַק","it was severe"],["עַל־יוֹאָב","upon-Joab"],["וַיֵּצֵא","and-went-out"],["יוֹאָב","Joab"],["וַיִּתְהַלֵּךְ","and-go-forth"],["בְּכׇל־יִשְׂרָאֵל","in-all-Israel"],["וַיָּבֹא","and-came"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["׃",""]] },
  { num:"ה", words:[["וַיִּתֵּן","and-gave"],["יוֹאָב","Joab"],["אֶת־מִסְפַּר","[ACC]-so-many-of"],["מִפְקַד־הָעָם","the muster of-the-people"],["אֶל־דָּוִיד","to-David"],["וַיְהִי","and-it-came-to-pass"],["כׇל־יִשְׂרָאֵל","all-Israel"],["אֶלֶף","thousand"],["אֲלָפִים","two-thousand"],["וּמֵאָה","and-one hundred"],["אֶלֶף","thousand"],["אִישׁ","man-of"],["שֹׁלֵף","who drew"],["חֶרֶב","the-sword-of"],["וִיהוּדָה","and-Judah"],["אַרְבַּע","four"],["מֵאוֹת","hundred"],["וְשִׁבְעִים","and-seventy"],["אֶלֶף","thousand"],["אִישׁ","man-of"],["שֹׁלֵף־חָרֶב","who drew-a-sword"],["׃",""]] },
  { num:"ו", words:[["וְלֵוִי","Oloi"],["וּבִנְיָמִן","and-Benjamin"],["לֹא","not"],["פָקַד","he had observed"],["בְּתוֹכָם","among-them"],["כִּי־נִתְעַב","because-it was abhorred"],["דְּבַר־הַמֶּלֶךְ","word-of-the-king"],["אֶת־יוֹאָב","[ACC]-Joab"],["׃",""]] },
  { num:"ז", words:[["וַיֵּרַע","were-displeased-with"],["בְּעֵינֵי","in-eyes-of"],["הָאֱלֹהִים","the-God"],["עַל־הַדָּבָר","concerning-this-thing"],["הַזֶּה","this"],["וַיַּךְ","and-he-smote"],["אֶת־יִשְׂרָאֵל","[ACC]-Israel"],["׃",""]] },
  { num:"ח", words:[["וַיֹּאמֶר","and-said"],["דָּוִיד","David"],["אֶל־הָאֱלֹהִים","unto-God"],["חָטָאתִי","have I sinned"],["מְאֹד","exceedingly"],["אֲשֶׁר","whose"],["עָשִׂיתִי","I-made"],["אֶת־הַדָּבָר","[ACC]-the-word"],["הַזֶּה","this"],["וְעַתָּה","and-now"],["הַעֲבֶר־נָא","take away-I-pray"],["אֶת־עֲווֹן","[ACC]-the guilt of"],["עַבְדְּךָ","your-manservant"],["כִּי","because"],["נִסְכַּלְתִּי","I have acted foolishly"],["מְאֹד","exceedingly"],["׃",""]] },
  { num:"ט", words:[["וַיְדַבֵּר","and-he-spoke"],["יְהֹוָה","the-LORD"],["אֶל־גָּד","to-Gad"],["חֹזֵה","the seer of"],["דָוִיד","David"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"י", words:[["לֵךְ","go"],["וְדִבַּרְתָּ","and-you will speak"],["אֶל־דָּוִיד","to-David"],["לֵאמֹר","saying"],["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["שָׁלוֹשׁ","three"],["אֲנִי","I"],["נֹטֶה","am holding out"],["עָלֶיךָ","upon-you(f)"],["בְּחַר־לְךָ","choose-for-you"],["אַחַת","one"],["מֵהֵנָּה","of-them"],["וְאֶעֱשֶׂה־לָּךְ","and-do-to-you"],["׃",""]] },
  { num:"יא", words:[["וַיָּבֹא","and-came"],["גָד","Gad"],["אֶל־דָּוִיד","to-David"],["וַיֹּאמֶר","and-said"],["לוֹ","him"],["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["קַבֶּל־לָךְ","take-[compound]"],["׃",""]] },
  { num:"יב", words:[["אִם־שָׁלוֹשׁ","[compound]-three"],["שָׁנִים","years"],["רָעָב","hungry"],["וְאִם־שְׁלֹשָׁה","and-if-three"],["חֳדָשִׁים","months"],["נִסְפֶּה","we-perish"],["מִפְּנֵי־צָרֶיךָ","because-of-opponents-your"],["וְחֶרֶב","and-sword-of"],["אוֹיְבֶיךָ","enemies-your"],["לְמַשֶּׂגֶת","to-overtaking you"],["וְאִם־שְׁלֹשֶׁת","and-if-three-of"],["יָמִים","days"],["חֶרֶב","the-sword-of"],["יְהֹוָה","the-LORD"],["וְדֶבֶר","and-pestilences"],["בָּאָרֶץ","in-the-land"],["וּמַלְאַךְ","and-angel-of"],["יְהֹוָה","the-LORD"],["מַשְׁחִית","destroys"],["בְּכׇל־גְּבוּל","in-all-border-of"],["יִשְׂרָאֵל","Israel"],["וְעַתָּה","and-now"],["רְאֵה","behold"],["מָה־אָשִׁיב","what-recall"],["אֶת־שֹׁלְחִי","[ACC]-the one who sent-me"],["דָּבָר","things"],["׃",""]] },
  { num:"יג", words:[["וַיֹּאמֶר","and-said"],["דָּוִיד","David"],["אֶל־גָּד","to-Gad"],["צַר־לִי","narrow/enemy-to-me"],["מְאֹד","exceedingly"],["אֶפְּלָה־נָּא","let me fall-now"],["בְיַד־יְהֹוָה","by-the hand of-the-LORD"],["כִּי־רַבִּים","that-many"],["רַחֲמָיו","His-mercy"],["מְאֹד","exceedingly"],["וּבְיַד־אָדָם","and-by-the-hand-of-man"],["אַל־אֶפֹּל","do-not-I fall"],["׃",""]] },
  { num:"יד", words:[["וַיִּתֵּן","and-gave"],["יְהֹוָה","the-LORD"],["דֶּבֶר","a pestilence"],["בְּיִשְׂרָאֵל","Israel"],["וַיִּפֹּל","and-fell"],["מִיִּשְׂרָאֵל","from-Israel"],["שִׁבְעִים","seventy"],["אֶלֶף","thousand"],["אִישׁ","man-of"],["׃",""]] },
  { num:"טו", words:[["וַיִּשְׁלַח","and-he-sent"],["הָאֱלֹהִים","the-God"],["מַלְאָךְ","an-angel"],["לִירוּשָׁלַ͏ִם","to-Jerusalem"],["לְהַשְׁחִיתָהּ","to-destroy-it"],["וּכְהַשְׁחִית","and-just as-was destroying it"],["רָאָה","he-saw"],["יְהֹוָה","the-LORD"],["וַיִּנָּחֶם","and-he regretted"],["עַל־הָרָעָה","upon-the-evil"],["וַיֹּאמֶר","and-said"],["לַמַּלְאָךְ","unto-that-angel"],["הַמַּשְׁחִית","which-doth-corrupt"],["רַב","great"],["עַתָּה","now"],["הֶרֶף","ceasing"],["יָדֶךָ","your-hand"],["וּמַלְאַךְ","and-angel-of"],["יְהֹוָה","the-LORD"],["עֹמֵד","standing"],["עִם־גֹּרֶן","with-the threshing floor of"],["אׇרְנָן","I shout for joy"],["הַיְבוּסִי","the-Jebusites"],["׃",""]] },
  { num:"טז", words:[["וַיִּשָּׂא","and-he-cast"],["דָוִיד","David"],["אֶת־עֵינָיו","[ACC]-his-eyes"],["וַיַּרְא","and-he-saw"],["אֶת־מַלְאַךְ","[ACC]-angel-of"],["יְהֹוָה","the-LORD"],["עֹמֵד","standing"],["בֵּין","among"],["הָאָרֶץ","the-earth"],["וּבֵין","and-between"],["הַשָּׁמַיִם","the-heavens"],["וְחַרְבּוֹ","and-sword-his"],["שְׁלוּפָה","drawn"],["בְּיָדוֹ","in-his-hand"],["נְטוּיָה","is-stretched-out"],["עַל־יְרוּשָׁלָ͏ִם","upon-Jerusalem"],["וַיִּפֹּל","and-fell"],["דָּוִיד","David"],["וְהַזְּקֵנִים","and-the-elders"],["מְכֻסִּים","was-covered-with"],["בַּשַּׂקִּים","in-sackcloth(pl)"],["עַל־פְּנֵיהֶם","upon-their-faces"],["׃",""]] },
  { num:"יז", words:[["וַיֹּאמֶר","and-said"],["דָּוִיד","David"],["אֶל־הָאֱלֹהִים","unto-God"],["הֲלֹא","do-not"],["אֲנִי","I"],["אָמַרְתִּי","I-said"],["לִמְנוֹת","to-count"],["בָּעָם","over-the-people"],["וַאֲנִי־הוּא","and-I-it-is"],["אֲשֶׁר־חָטָאתִי","whose-have I sinned"],["וְהָרֵעַ","and-exceedingly"],["הֲרֵעוֹתִי","I have done evil"],["וְאֵלֶּה","and-these"],["הַצֹּאן","the-flock"],["מֶה","what"],["עָשׂוּ","they-did"],["יְהֹוָה","the-LORD"],["אֱלֹהַי","my-God"],["תְּהִי","let it be"],["נָא","I-pray"],["יָדְךָ","your-hand"],["בִּי","against-me"],["וּבְבֵית","and-in-the house of"],["אָבִי","my-father"],["וּבְעַמְּךָ","and-on-people-your"],["לֹא","not"],["לְמַגֵּפָה","to-a plague"],["׃",""]] },
  { num:"יח", words:[["וּמַלְאַךְ","and-angel-of"],["יְהֹוָה","the-LORD"],["אָמַר","said"],["אֶל־גָּד","to-Gad"],["לֵאמֹר","saying"],["לְדָוִיד","of-David"],["כִּי","because"],["יַעֲלֶה","let-ascend"],["דָוִיד","David"],["לְהָקִים","to-raise-up"],["מִזְבֵּחַ","an altar"],["לַיהֹוָה","to-Yahweh"],["בְּגֹרֶן","at-the threshing floor of"],["אׇרְנָן","I shout for joy"],["הַיְבֻסִי","the-Jebusites"],["׃",""]] },
  { num:"יט", words:[["וַיַּעַל","and-he-ascended"],["דָּוִיד","David"],["בִּדְבַר־גָּד","of-the-promise-of-Gad"],["אֲשֶׁר","whose"],["דִּבֶּר","spoke"],["בְּשֵׁם","by-name"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"כ", words:[["וַיָּשׇׁב","and-he will turn"],["אׇרְנָן","I shout for joy"],["וַיַּרְא","and-he-saw"],["אֶת־הַמַּלְאָךְ","[ACC]-the-angel"],["וְאַרְבַּעַת","and-four-of"],["בָּנָיו","his-sons"],["עִמּוֹ","with-him"],["מִתְחַבְּאִים","were hiding themselves"],["וְאׇרְנָן","so-I may sing for joy"],["דָּשׁ","he threshed"],["חִטִּים","wheat"],["׃",""]] },
  { num:"כא", words:[["וַיָּבֹא","and-came"],["דָוִיד","David"],["עַד־אׇרְנָן","until-I shout for joy"],["וַיַּבֵּט","Oibt"],["אׇרְנָן","I shout for joy"],["וַיַּרְא","and-he-saw"],["אֶת־דָּוִיד","[ACC]-David"],["וַיֵּצֵא","and-went-out"],["מִן־הַגֹּרֶן","from-the-threshing floor"],["וַיִּשְׁתַּחוּ","and-bowed-himself"],["לְדָוִיד","of-David"],["אַפַּיִם","with-face"],["אָרְצָה","to-the-earth"],["׃",""]] },
  { num:"כב", words:[["וַיֹּאמֶר","and-said"],["דָּוִיד","David"],["אֶל־אׇרְנָן","to-I shout for joy"],["תְּנָה־לִּי","give(f)-to-me"],["מְקוֹם","the-place"],["הַגֹּרֶן","the-threshing floor"],["וְאֶבְנֶה־בּוֹ","so-I may build-against-him"],["מִזְבֵּחַ","an altar"],["לַיהֹוָה","to-Yahweh"],["בְּכֶסֶף","in-money"],["מָלֵא","full-of"],["תְּנֵהוּ","give-it"],["לִי","to-me"],["וְתֵעָצַר","so-it may be restrained"],["הַמַּגֵּפָה","the-plague"],["מֵעַל","from-upon"],["הָעָם","the-people"],["׃",""]] },
  { num:"כג", words:[["וַיֹּאמֶר","and-said"],["אׇרְנָן","I shout for joy"],["אֶל־דָּוִיד","to-David"],["קַח־לָךְ","take-[compound]"],["וְיַעַשׂ","so-may he do"],["אֲדֹנִי","my-Lord"],["הַמֶּלֶךְ","the-king"],["הַטּוֹב","good"],["בְּעֵינָיו","in-His-eyes"],["רְאֵה","behold"],["נָתַתִּי","I-gave"],["הַבָּקָר","the-herd"],["לָעֹלוֹת","for the-burnt offerings"],["וְהַמּוֹרִגִּים","and-the-threshing-sledges"],["לָעֵצִים","the-wood"],["וְהַחִטִּים","and-the-wheat"],["לַמִּנְחָה","to the-grain offering"],["הַכֹּל","all"],["נָתָתִּי","I give"],["׃",""]] },
  { num:"כד", words:[["וַיֹּאמֶר","and-said"],["הַמֶּלֶךְ","the-king"],["דָּוִיד","David"],["לְאׇרְנָן","to-Ornan"],["לֹא","not"],["כִּי־קָנֹה","because-you will buy"],["אֶקְנֶה","I-shall-acquire"],["בְּכֶסֶף","in-money"],["מָלֵא","full-of"],["כִּי","because"],["לֹא־אֶשָּׂא","not-I-carry"],["אֲשֶׁר־לְךָ","whose-for-you"],["לַיהֹוָה","to-Yahweh"],["וְהַעֲלוֹת","and-to offer up"],["עוֹלָה","ascends-up"],["חִנָּם","is-free"],["׃",""]] },
  { num:"כה", words:[["וַיִּתֵּן","and-gave"],["דָּוִיד","David"],["לְאׇרְנָן","to-Ornan"],["בַּמָּקוֹם","the-space"],["שִׁקְלֵי","shekels of"],["זָהָב","gold"],["מִשְׁקָל","weight"],["שֵׁשׁ","six"],["מֵאוֹת","hundred"],["׃",""]] },
  { num:"כו", words:[["וַיִּבֶן","and-built"],["שָׁם","there-is"],["דָּוִיד","David"],["מִזְבֵּחַ","an altar"],["לַיהֹוָה","to-Yahweh"],["וַיַּעַל","and-he-ascended"],["עֹלוֹת","burnt-offerings"],["וּשְׁלָמִים","and-peace offerings"],["וַיִּקְרָא","and-he-called"],["אֶל־יְהֹוָה","to-the-Lord"],["וַיַּעֲנֵהוּ","and-answered-them"],["בָאֵשׁ","in-fire"],["מִן־הַשָּׁמַיִם","from-the-heavens"],["עַל","upon"],["מִזְבַּח","altar"],["הָעֹלָה","the-burnt offering"],["׃",""]] },
  { num:"כז", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["לַמַּלְאָךְ","unto-that-angel"],["וַיָּשֶׁב","and-he-returned"],["חַרְבּוֹ","his-sword"],["אֶל־נְדָנָהּ","to-sheath-its"],["׃",""]] },
  { num:"כח", words:[["בָּעֵת","at-the-time"],["הַהִיא","that"],["בִּרְאוֹת","in-seeing-of"],["דָּוִיד","David"],["כִּי־עָנָהוּ","because-he answered-him"],["יְהֹוָה","the-LORD"],["בְּגֹרֶן","at-the threshing floor of"],["אׇרְנָן","I shout for joy"],["הַיְבוּסִי","the-Jebusites"],["וַיִּזְבַּח","and-he-sacrificed"],["שָׁם","there-is"],["׃",""]] },
  { num:"כט", words:[["וּמִשְׁכַּן","and-the tabernacle of"],["יְהֹוָה","the-LORD"],["אֲשֶׁר־עָשָׂה","which-did"],["מֹשֶׁה","Moses"],["בַמִּדְבָּר","in-the-wilderness"],["וּמִזְבַּח","and-the altar of"],["הָעוֹלָה","ascending"],["בָּעֵת","at-the-time"],["הַהִיא","that"],["בַּבָּמָה","at the-high place"],["בְּגִבְעוֹן","at-Gibeon"],["׃",""]] },
  { num:"ל", words:[["וְלֹא־יָכֹל","and-could-not"],["דָּוִיד","David"],["לָלֶכֶת","to-go"],["לְפָנָיו","before-him"],["לִדְרֹשׁ","to-preach"],["אֱלֹהִים","God"],["כִּי","because"],["נִבְעַת","he was terrified"],["מִפְּנֵי","because-of"],["חֶרֶב","the-sword-of"],["מַלְאַךְ","angel-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
];
renderVerseSet(jst1ch_ch1Verses, 'jst1ch-ch1-verses');

})();
