// jst_verses/jst2pe.js — 2 Peter (JST) verse data
(function() {
var jst2pe_ch1Verses = [
  { num:"א", words:[["זֹאת","this"],["הָאִגֶּרֶת","the-epistle"],["הַשֵּׁנִית","the-second"],["אֲשֶׁר","whose"],["אֲנִי","I"],["כֹתֵב","writing"],["אֲלֵיכֶם","unto-you"],["חֲבִיבָי","my-beloved"],["וּבִשְׁתֵּיהֶן","and-in-both of-them"],["כְּמַזְכִּיר","as-one-who-reminds"],["אָעִיר","I-awaken"],["אֶת־תֻּמַּת","[ACC]-the integrity of"],["לְבַבְכֶם","your-hearts"],["׃",""]] },
  { num:"ב", words:[["לִזְכֹּר","to-remember"],["אֶת־הַדְּבָרִים","[ACC]-the-words"],["הַנֶּאֱמָרִים","the-it-was-said"],["מִקֶּדֶם","of-old"],["בִּידֵי","by-hands-of"],["הַנְּבִיאִים","the-prophets"],["הַקְּדֹשִׁים","the-the holy ones"],["וְאֶת־מִצְוַת","and-[ACC]-the-commandments-of"],["אֲדֹנֵינוּ","our-Lord"],["וּמוֹשִׁיעֵנוּ","and-our-Savior"],["אֲשֶׁר","whose"],["נִתְּנָה","was-given(f)"],["עַל־יְדֵי","by-means-of"],["שְׁלִיחֵיכֶם","apostle-your(pl)"],["׃",""]] },
  { num:"ג", words:[["וּדְעוּ","and-know"],["זֹאת","this"],["לָכֶם","to-you"],["רִאשֹׁנָה","first"],["כִּי","because"],["בְּאַחֲרִית","in-latter"],["הַיָּמִים","the-days"],["יָבֹאוּ","come"],["לֵצִים","mockers"],["הֹלְכִים","walking"],["אַחֲרֵי","after"],["תַאֲוֹת","chambers"],["נַפְשָׁם","their-soul"],["וְיִתְלוֹצֲצוּ","and-they-shall-mock"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ד", words:[["אַיֵּה","where-is"],["הַבְטָחַת","the-promise-of"],["בֹּאוֹ","went-he"],["כִּי","because"],["מֵאָז","since"],["שָׁכְבוּ","they-lie"],["הָאָבוֹת","the-fathers"],["הַכֹּל","all"],["עֹמֵד","standing"],["כְּמוֹ","as/like"],["מֵרֵאשִׁית","from-the-beginning"],["הַבְּרִיאָה","creation"],["׃",""]] },
  { num:"ה", words:[["וְנֶעְלָם","and-hidden"],["מִדַּעְתָּם","from-their-minds"],["לִרְצוֹנָם","to-their-will"],["שֶׁלְּפָנִים","that-to the-face"],["בִּדְבַר","of-the-promise-of"],["אֱלֹהִים","God"],["נַעֲשׂוֹּ","were-done"],["הַשָּׁמַיִם","the-heavens"],["וְהָאָרֶץ","and-the-earth"],["מִן־הַמַּיִם","from-the-waters"],["וְעַל־יְדֵי","and-upon-hands-of"],["הַמָּיִם","the-water"],["׃",""]] },
  { num:"ו", words:[["וְעַל","and-upon"],["יְדֵיהֶם","their-hands"],["אָבְדָה","perished"],["תֵבֵל","the-world"],["אֲשֶׁר","whose"],["מֵאָז","since"],["כִּי","because"],["נִשְׁטְפָה","???"],["בְּמֵי","in-the-waters-of"],["הַמַּבּוּל","the-flood"],["׃",""]] },
  { num:"ז", words:[["גַּם־הַשָּׁמַיִם","also-the-heavens"],["וְהָאָרֶץ","and-the-earth"],["אֲשֶׁר","whose"],["לְפָנֵינוּ","before-us"],["נִצְפְּנוּ","can-we-expect-our/-us"],["בִדְבָרוֹ","by-His-word"],["וְהֵם","and-they"],["שְׁמוּרִים","keep(pl)"],["לָאֵשׁ","to-the-fire"],["לְיוֹם","to-day"],["הַדִּין","judgment"],["וַאֲבֹד","and-that-any-human"],["אַנְשֵׁי","the-men-of"],["הָרֶשַׁע","the-wickedness"],["׃",""]] },
  { num:"ח", words:[["וְזֹאת","and-this"],["הָאַחַת","the-one"],["אַל־תֵּעָלֵם","do-not-you hide"],["מִכֶּם","from-you"],["חֲבִיבָי","my-beloved"],["שֶׁיּוֹם","that-day"],["אֶחָד","one"],["כְּאֶלֶף","about-a thousand"],["שָׁנִים","years"],["בְּעֵינֵי","in-eyes-of"],["יְהוָֹה","the-Lord"],["וְאֶלֶף","and-one thousand"],["שָׁנִים","years"],["כְּיוֹם","as-the-day-of"],["אֶחָד","one"],["׃",""]] },
  { num:"ט", words:[["וְלֹא־יְאַחֵר","and-not-he-delays"],["יְהוָֹה","the-Lord"],["אֶת־אֲשֶׁר","ACC-that-which"],["הִבְטִיחַ","has-promised"],["כַּאֲשֶׁר־יֵשׁ","when/as-there-is"],["חֹשְׁבִים","thought"],["זֹאת","this"],["לְאִחוּר","to-backwards"],["כִּי","because"],["מַאֲרִיךְ","is-slow(of)"],["אַפּוֹ","His-wrath"],["בַּעֲבוּרֵנוּ","because-of-us"],["וְלֹא","and-not"],["יַחְפֹּץ","delights"],["בַּאֲבֹד","in-the-that-any-human"],["הָאֹבְדִים","the-lost"],["כִּי","because"],["אִם־בִּפְנוֹת","???"],["כֻּלָּם","all-of-them"],["לַתְּשׁוּבָה","to-repentance"],["׃",""]] },
  { num:"י", words:[["בֹּא","come"],["יָבֹא","shall-come"],["יוֹם־יְהוָֹה","the-day-of-the-LORD"],["כְּגַנָּב","as-a-thief"],["בַּלָּיְלָה","by-night"],["אָז","then"],["הַשָּׁמַיִם","the-heavens"],["בְּשָׁאוֹן","in-uproar"],["יַחֲלֹפוּ","they may pass away"],["וְהַיְסֹדוֹת","???"],["יְבֹעֲרוּ","they will kindle"],["וְהִתְמֹגֲגוּ","and-they melt"],["וְהָאָרֶץ","and-the-earth"],["וְהַמַּעֲשִׂים","and-the-works"],["אֲשֶׁר","whose"],["עָלֶיהָ","upon-it"],["יִשָּׂרֵפוּ","burned-shall-they-be"],["׃",""]] },
  { num:"יא", words:[["וְעַתָּה","and-now"],["אִם־כָּל־אֵלֶּה","[compound]-all-these"],["יָמוּגוּ","???"],["מַה־מְּאֹד","what-exceedingly"],["עֲלֵיכֶם","over-you"],["לְהִתְהַלֵּךְ","to-walk"],["בִּקְדֻשָּׁה","in-holiness"],["וּבַחֲסִידוּת","???"],["׃",""]] },
  { num:"יב", words:[["וּלְחַכּוֹת","and-to-they-waited-of"],["לְיוֹם־יְהוָֹה","to-day-???"],["שֶׁיָּבֹא","that-he went"],["וּלְהָחִישׁ","???"],["אֹתוֹ","him"],["אֲשֶׁר","whose"],["בּוֹ","against-him"],["הַשָּׁמַיִם","the-heavens"],["יָמוּגוּ","???"],["בָאֵשׁ","in-fire"],["וְהַיְסֹדוֹת","???"],["יְבֹעֲרוּ","they will kindle"],["וְנָמַסּוּ","and-they will melt away"],["׃",""]] },
  { num:"יג", words:[["וַאֲנַחְנוּ","and-we-are"],["כְּפִי","according-to"],["הַבְטָחָתוֹ","the-promise-of-his"],["מְחַכִּים","waiting"],["לְשָׁמַיִם","to-the-heavens"],["חֲדָשִׁים","new-ones"],["וּלְאֶרֶץ","and-to-the-land-of"],["חֲדָשָׁה","new"],["אֲשֶׁר־צֶדֶק","whose-righteousness"],["יָלִין","it will remain overnight"],["בָּם","in-them"],["׃",""]] },
  { num:"יד", words:[["עַל־כֵּן","therefore"],["חֲבִיבַי","my-beloved"],["הַמְחַכִּים","those-who long"],["לָאֵלֶּה","to-such"],["שִׁקְדוּ","watch"],["לְהִמָּצֵא","to-actually"],["לְפָנָיו","before-him"],["בְּשָׁלוֹם","again-peace"],["נְקִיִּם","innocent"],["וְזַכִּים","and-spotless"],["מִפָּשַׁע","from-he has rebelled"],["׃",""]] },
  { num:"טו", words:[["וְאֶת־אֹרֶךְ","and-[ACC]-he-was-long"],["רוּחַ","spirit-of"],["אֲדֹנֵינוּ","our-Lord"],["תַּחְשְׁבוּ","suppose"],["לִתְשׁוּעָה","to-deliverance"],["כַּאֲשֶׁר","when/as"],["גַּם־אָחִינוּ","also-our-brother"],["הָאָהוּב","the-beloved"],["פּוֹלוֹס","Paul"],["כָּתַב","he-wrote"],["אֲלֵיכֶם","unto-you"],["כְּפִי","according-to"],["הַחָכְמָה","wisdom"],["הַנְּתוּנָה","the-given"],["לוֹ","him"],["׃",""]] },
  { num:"טז", words:[["וְכֵן","and-so"],["בְּכָל־אִגְּרוֹתָיו","in-all-???"],["בְּדַבְּרוֹ־שָׁם","speaking-of-there-is"],["עַל־אֵלֶּה","upon-these"],["וּבָהֶן","and-in-them(f)"],["יֵשׁ","there-is"],["דְּבָרִים","things"],["קָשִׁים","hard"],["מֵהָבִין","from-to understand"],["וְהַבֹּעֲרִים","and-the-O stupid ones"],["וְהַפְּתָאִים","???"],["יַהַפְכוּ","they may devastate"],["אֹתָם","them"],["כַּאֲשֶׁר","when/as"],["גַּם־יַעֲשׂוֹּ","also-they have made"],["בְּיֶתֶר","with-more"],["הַסְּפָרִים","the-records"],["לְאָבְדַן","to-loss-of"],["נַפְשָׁם","their-soul"],["׃",""]] },
  { num:"יז", words:[["וְאַתֶּם","and-will-you"],["חֲבִיבַי","my-beloved"],["אֲשֶׁר","whose"],["יְדַעְתֶּם","you-know"],["זֹאת","this"],["מֵרֹאשׁ","from-the-beginning"],["הִשָּׁמְרוּ","beware"],["לְנַפְשֹׁתֵיכֶם","of-lives-you"],["פֶּן־תִּמָּשְׁכוּ","???"],["אַחֲרֵי","after"],["טָעוּת","???"],["אַנְשֵׁי","the-men-of"],["בְלִיַּעַל","Belial"],["וּנְפַלְתֶּם","and-you will fall"],["מִמָּעֻזְּכֶם","from-is refuge-your"],["׃",""]] },
  { num:"יח", words:[["וּרְבוּ","and-multiply"],["בְּחֶסֶד","in-the-grace-of"],["וּבְדַעַת","and-with-knowledge"],["אֲדֹנֵינוּ","our-Lord"],["וּמוֹשִׁיעֵנוּ","and-our-Savior"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["אֲשֶׁר־לוֹ","whom"],["הַכָּבוֹד","the-glorious"],["גַּם־הַיּוֹם","also-the-day"],["וְגַם־לְיוֹם","and-also-to-day"],["הָעוֹלָם","the-world"],["אָמֵן","amen"],["׃",""]] },
];
renderVerseSet(jst2pe_ch1Verses, 'jst2pe-ch1-verses');

})();
