// jst_verses/jst2sa.js — 2 Samuel (JST) verse data
(function() {
var jst2sa_ch1Verses = [
  { num:"א", words:[["וַיִּשְׁלַח","and-he-sent"],["יְהֹוָה","the-LORD"],["אֶת־נָתָן","[ACC]-Nathan"],["אֶל־דָּוִד","to-David"],["וַיָּבֹא","and-came"],["אֵלָיו","to-him"],["וַיֹּאמֶר","and-said"],["לוֹ","him"],["שְׁנֵי","two"],["אֲנָשִׁים","men"],["הָיוּ","were"],["בְּעִיר","in-the-city-of"],["אֶחָת","one"],["אֶחָד","one"],["עָשִׁיר","rich"],["וְאֶחָד","and-one"],["רָאשׁ","was poor"],["׃",""]] },
  { num:"ב", words:[["לְעָשִׁיר","to-the rich man"],["הָיָה","was"],["צֹאן","flocks"],["וּבָקָר","and-herds"],["הַרְבֵּה","much"],["מְאֹד","exceedingly"],["׃",""]] },
  { num:"ג", words:[["וְלָרָשׁ","and-belonged to the-poor man"],["אֵין־כֹּל","there-is-no-all"],["כִּי","because"],["אִם־כִּבְשָׂה","[compound]-a ewe-lamb"],["אַחַת","one"],["קְטַנָּה","sin"],["אֲשֶׁר","whose"],["קָנָה","he-acquired"],["וַיְחַיֶּהָ","and-he nourished-it"],["וַתִּגְדַּל","unto-them"],["עִמּוֹ","with-him"],["וְעִם־בָּנָיו","and-with-his-sons"],["יַחְדָּו","together"],["מִפִּתּוֹ","from-morsel-his"],["תֹאכַל","you must eat"],["וּמִכֹּסוֹ","and-from-cup-his"],["תִשְׁתֶּה","you will drink"],["וּבְחֵיקוֹ","and-in-bosom-his"],["תִשְׁכָּב","it lay down"],["וַתְּהִי־לוֹ","and-was-him"],["כְּבַת","like-a daughter"],["׃",""]] },
  { num:"ד", words:[["וַיָּבֹא","and-came"],["הֵלֶךְ","a flowing of"],["לְאִישׁ","for-a-man"],["הֶעָשִׁיר","the-rich"],["וַיַּחְמֹל","and-he-had-compassion"],["לָקַחַת","to-take"],["מִצֹּאנוֹ","one of-own sheep-his"],["וּמִבְּקָרוֹ","and-one of-own cattle-his"],["לַעֲשׂוֹת","to-do"],["לָאֹרֵחַ","for the-traveler"],["הַבָּא־לוֹ","that-comes-him"],["וַיִּקַּח","and-took"],["אֶת־כִּבְשַׂת","[ACC]-the ewe-lamb of"],["הָאִישׁ","the-man"],["הָרָאשׁ","poor"],["וַיַּעֲשֶׂהָ","and-he offered-it"],["לָאִישׁ","be-unto-that-man"],["הַבָּא","that-comes"],["אֵלָיו","to-him"],["׃",""]] },
  { num:"ה", words:[["וַיִּחַר־אַף","and-was-kindled-the-anger-of"],["דָּוִד","David"],["בָּאִישׁ","the-man"],["מְאֹד","exceedingly"],["וַיֹּאמֶר","and-said"],["אֶל־נָתָן","to-Nathan"],["חַי־יְהֹוָה","as-the-LORD-lives"],["כִּי","because"],["בֶן־מָוֶת","Bn-death"],["הָאִישׁ","the-man"],["הָעֹשֶׂה","does"],["זֹאת","this"],["׃",""]] },
  { num:"ו", words:[["וְאֶת־הַכִּבְשָׂה","and-[ACC]-the-ewe-lamb"],["יְשַׁלֵּם","he-will-complete"],["אַרְבַּעְתָּיִם","fourfold"],["עֵקֶב","for"],["אֲשֶׁר","whose"],["עָשָׂה","he-did"],["אֶת־הַדָּבָר","[ACC]-the-word"],["הַזֶּה","this"],["וְעַל","and-upon"],["אֲשֶׁר","whose"],["לֹא־חָמָל","not-he showed pity"],["׃",""]] },
  { num:"ז", words:[["וַיֹּאמֶר","and-said"],["נָתָן","Nathan"],["אֶל־דָּוִד","to-David"],["אַתָּה","you"],["הָאִישׁ","the-man"],["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["אֱלֹהֵי","God-of"],["יִשְׂרָאֵל","Israel"],["אָנֹכִי","I"],["מְשַׁחְתִּיךָ","I anointed-you"],["לְמֶלֶךְ","king"],["עַל־יִשְׂרָאֵל","upon-Israel"],["וְאָנֹכִי","yet-I"],["הִצַּלְתִּיךָ","I delivered-you"],["מִיַּד","from-hand-of"],["שָׁאוּל","Saul"],["׃",""]] },
  { num:"ח", words:[["וָאֶתְּנָה","and-I have given-!"],["לְךָ","for-you"],["אֶת־בֵּית","[ACC]-house-of"],["אֲדֹנֶיךָ","master-your"],["וְאֶת־נְשֵׁי","and-[ACC]-the-wives-and"],["אֲדֹנֶיךָ","master-your"],["בְּחֵיקֶךָ","in-bosom-your"],["וָאֶתְּנָה","and-I have given-!"],["לְךָ","for-you"],["אֶת־בֵּית","[ACC]-house-of"],["יִשְׂרָאֵל","Israel"],["וִיהוּדָה","and-Judah"],["וְאִם־מְעָט","and-if-a-little"],["וְאֹסִפָה","and-I will add"],["לְּךָ","have-you"],["כָּהֵנָּה","like-those"],["וְכָהֵנָּה","and-as-hither"],["׃",""]] },
  { num:"ט", words:[["מַדּוּעַ","why"],["בָּזִיתָ","have you despised"],["אֶת־דְּבַר","ACC-word-of"],["יְהֹוָה","the-LORD"],["לַעֲשׂוֹת","to-do"],["הָרַע","the-bad"],["(בעינו)","with-His-eye"],["[בְּעֵינַי]","in-my-eyes"],["אֵת","[ACC]"],["אוּרִיָּה","Uriah"],["הַחִתִּי","the-Hittites"],["הִכִּיתָ","you struck"],["בַחֶרֶב","by-the-sword"],["וְאֶת־אִשְׁתּוֹ","and-[ACC]-his-wife"],["לָקַחְתָּ","you have taken"],["לְּךָ","have-you"],["לְאִשָּׁה","for-wife"],["וְאֹתוֹ","and-him"],["הָרַגְתָּ","you killed"],["בְּחֶרֶב","with-the-sword-of"],["בְּנֵי","sons-of"],["עַמּוֹן","Ammon"],["׃",""]] },
  { num:"י", words:[["וְעַתָּה","and-now"],["לֹא־תָסוּר","not-you will turn aside"],["חֶרֶב","the-sword-of"],["מִבֵּיתְךָ","from-house-your"],["עַד־עוֹלָם","forever"],["עֵקֶב","for"],["כִּי","because"],["בְזִתָנִי","you despised-me"],["וַתִּקַּח","and-she took"],["אֶת־אֵשֶׁת","[ACC]-the-wife-of"],["אוּרִיָּה","Uriah"],["הַחִתִּי","the-Hittites"],["לִהְיוֹת","to-be"],["לְךָ","for-you"],["לְאִשָּׁה","for-wife"],["׃",""],["{}","???"],["׃",""]] },
  { num:"יא", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["הִנְנִי","behold-I"],["מֵקִים","about to establish"],["עָלֶיךָ","upon-you(f)"],["רָעָה","evil"],["מִבֵּיתֶךָ","from-own house-your"],["וְלָקַחְתִּי","and-I will take"],["אֶת־נָשֶׁיךָ","[ACC]-wives-your"],["לְעֵינֶיךָ","to-eyes-your"],["וְנָתַתִּי","and-I-will-give"],["לְרֵעֶיךָ","to-neighbor-your"],["וְשָׁכַב","and-he will lie"],["עִם־נָשֶׁיךָ","with-wives-your"],["לְעֵינֵי","in-the-eyes-of"],["הַשֶּׁמֶשׁ","the-sun"],["הַזֹּאת","is-this"],["׃",""]] },
  { num:"יב", words:[["כִּי","because"],["אַתָּה","you"],["עָשִׂיתָ","you-did"],["בַסָּתֶר","in-secret"],["וַאֲנִי","and-I"],["אֶעֱשֶׂה","I-do"],["אֶת־הַדָּבָר","[ACC]-the-word"],["הַזֶּה","this"],["נֶגֶד","against"],["כׇּל־יִשְׂרָאֵל","all-Israel"],["וְנֶגֶד","and-against"],["הַשָּׁמֶשׁ","the-sun"],["׃",""]] },
  { num:"יג", words:[["וַיֹּאמֶר","and-said"],["דָּוִד","David"],["אֶל־נָתָן","to-Nathan"],["חָטָאתִי","have I sinned"],["לַיהֹוָה","to-Yahweh"],["וַיֹּאמֶר","and-said"],["נָתָן","Nathan"],["אֶל־דָּוִד","to-David"],["גַּם־יְהֹוָה","also-the-LORD"],["הֶעֱבִיר","he brought in"],["חַטָּאתְךָ","sin offering-your"],["לֹא","not"],["תָמוּת","you-will-death"],["׃",""]] },
  { num:"יד", words:[["אֶפֶס","save"],["כִּי־נִאֵץ","because-indeed"],["נִאַצְתָּ","you have declared contemptible"],["אֶת־אֹיְבֵי","[ACC]-the enemies of"],["יְהֹוָה","the-LORD"],["בַּדָּבָר","in-the-thing"],["הַזֶּה","this"],["גַּם","also"],["הַבֵּן","the-Son"],["הַיִּלּוֹד","born"],["לְךָ","for-you"],["מוֹת","death-of"],["יָמוּת","who-shall-die"],["׃",""]] },
  { num:"טו", words:[["וַיֵּלֶךְ","and-he-went"],["נָתָן","Nathan"],["אֶל־בֵּיתוֹ","to-his-house"],["וַיִּגֹּף","and-he struck"],["יְהֹוָה","the-LORD"],["אֶת־הַיֶּלֶד","[ACC]-a-child"],["אֲשֶׁר","whose"],["יָלְדָה","she bore"],["אֵשֶׁת־אוּרִיָּה","the-wife-of-Uriah"],["לְדָוִד","of-David"],["וַיֵּאָנַשׁ","and-he was sick"],["׃",""]] },
  { num:"טז", words:[["וַיְבַקֵּשׁ","and-requested"],["דָּוִד","David"],["אֶת־הָאֱלֹהִים","[ACC]-God"],["בְּעַד","on-behalf-of"],["הַנָּעַר","the-lad"],["וַיָּצׇם","and-he fasted"],["דָּוִד","David"],["צוֹם","fasting"],["וּבָא","and-come"],["וְלָן","and-he passed the night"],["וְשָׁכַב","and-he will lie"],["אָרְצָה","to-the-earth"],["׃",""]] },
  { num:"יז", words:[["וַיָּקֻמוּ","and-were-fulfilled"],["זִקְנֵי","the-elders-of"],["בֵיתוֹ","his-house"],["עָלָיו","upon-him"],["לַהֲקִימוֹ","to-raise-him"],["מִן־הָאָרֶץ","from-the-land"],["וְלֹא","and-not"],["אָבָה","was-willing"],["וְלֹא־בָרָא","and-not-He-created"],["אִתָּם","with-them"],["לָחֶם","food"],["׃",""]] },
  { num:"יח", words:[["וַיְהִי","and-it-came-to-pass"],["בַּיּוֹם","in-the-day"],["הַשְּׁבִיעִי","the-seventh"],["וַיָּמׇת","and-he-died"],["הַיָּלֶד","the-boy"],["וַיִּרְאוּ","and-they-saw"],["עַבְדֵי","servants-of"],["דָוִד","David"],["לְהַגִּיד","to-declare"],["לוֹ","him"],["כִּי־מֵת","because-is-dead"],["הַיֶּלֶד","a-child"],["כִּי","because"],["אָמְרוּ","they-said"],["הִנֵּה","behold"],["בִהְיוֹת","when-was"],["הַיֶּלֶד","a-child"],["חַי","living"],["דִּבַּרְנוּ","we-have-spoken-of"],["אֵלָיו","to-him"],["וְלֹא־שָׁמַע","and-not-heard"],["בְּקוֹלֵנוּ","to-voice-our"],["וְאֵיךְ","and-how"],["נֹאמַר","it-was-said"],["אֵלָיו","to-him"],["מֵת","is-dead"],["הַיֶּלֶד","a-child"],["וְעָשָׂה","and-done"],["רָעָה","evil"],["׃",""]] },
  { num:"יט", words:[["וַיַּרְא","and-he-saw"],["דָּוִד","David"],["כִּי","because"],["עֲבָדָיו","His-servants"],["מִתְלַחֲשִׁים","were whispering to one another"],["וַיָּבֶן","and-he understood"],["דָּוִד","David"],["כִּי","because"],["מֵת","is-dead"],["הַיָּלֶד","the-boy"],["וַיֹּאמֶר","and-said"],["דָּוִד","David"],["אֶל־עֲבָדָיו","to-His-servants"],["הֲמֵת","¿-has he died"],["הַיֶּלֶד","a-child"],["וַיֹּאמְרוּ","and-they-said"],["מֵת","is-dead"],["׃",""]] },
  { num:"כ", words:[["וַיָּקׇם","and-may he carry out"],["דָּוִד","David"],["מֵהָאָרֶץ","from-the-land"],["וַיִּרְחַץ","and-he washed"],["וַיָּסֶךְ","and-he covered"],["וַיְחַלֵּף","and-he changed"],["שִׂמְלֹתָו","is cloak-his"],["וַיָּבֹא","and-came"],["בֵית־יְהֹוָה","house-of-the-LORD"],["וַיִּשְׁתָּחוּ","and-he bowed down"],["וַיָּבֹא","and-came"],["אֶל־בֵּיתוֹ","to-his-house"],["וַיִּשְׁאַל","and-asked"],["וַיָּשִׂימוּ","and-began-to-put"],["לוֹ","him"],["לֶחֶם","bread"],["וַיֹּאכַל","and-he-shall-eat"],["׃",""]] },
  { num:"כא", words:[["וַיֹּאמְרוּ","and-they-said"],["עֲבָדָיו","His-servants"],["אֵלָיו","to-him"],["מָה־הַדָּבָר","what-the-thing"],["הַזֶּה","this"],["אֲשֶׁר","whose"],["עָשִׂיתָה","have you done"],["בַּעֲבוּר","because-of"],["הַיֶּלֶד","a-child"],["חַי","living"],["צַמְתָּ","you fasted"],["וַתֵּבְךְּ","and-she wept"],["וְכַאֲשֶׁר","and-as"],["מֵת","is-dead"],["הַיֶּלֶד","a-child"],["קַמְתָּ","you arose"],["וַתֹּאכַל","and-she ate"],["לָחֶם","food"],["׃",""]] },
  { num:"כב", words:[["וַיֹּאמֶר","and-said"],["בְּעוֹד","in-yet"],["הַיֶּלֶד","a-child"],["חַי","living"],["צַמְתִּי","I-fasted"],["וָאֶבְכֶּה","and-I wept"],["כִּי","because"],["אָמַרְתִּי","I-said"],["מִי","who"],["יוֹדֵעַ","knows"],["(יחנני)","He-show-me-mercy"],["[וְחַנַּנִי]","and-show favor to-me"],["יְהֹוָה","the-LORD"],["וְחַי","and-as"],["הַיָּלֶד","the-boy"],["׃",""]] },
  { num:"כג", words:[["וְעַתָּה","and-now"],["מֵת","is-dead"],["לָמָּה","why"],["זֶּה","Zh"],["אֲנִי","I"],["צָם","he-has-fasted"],["הַאוּכַל","¿-am I able"],["לַהֲשִׁיבוֹ","to-restore-him"],["עוֹד","any-more"],["אֲנִי","I"],["הֹלֵךְ","going"],["אֵלָיו","to-him"],["וְהוּא","and-it"],["לֹא־יָשׁוּב","not-repent"],["אֵלָי","unto-me"],["׃",""]] },
  { num:"כד", words:[["וַיְנַחֵם","and-he comforted"],["דָּוִד","David"],["אֵת","[ACC]"],["בַּת־שֶׁבַע","Bathsheba"],["אִשְׁתּוֹ","his-wife"],["וַיָּבֹא","and-came"],["אֵלֶיהָ","to-her"],["וַיִּשְׁכַּב","and-would-lie-down"],["עִמָּהּ","with-her"],["וַתֵּלֶד","and-bore"],["בֵּן","a-son"],["(ויקרא)","and-caused-to-be-read"],["[וַתִּקְרָא]","and-salvation-should-be-declared"],["אֶת־שְׁמוֹ","[ACC]-his-name"],["שְׁלֹמֹה","Solomon"],["וַיהֹוָה","and-Yahweh"],["אֲהֵבוֹ","they-loved"],["׃",""]] },
  { num:"כה", words:[["וַיִּשְׁלַח","and-he-sent"],["בְּיַד","in-hand-of"],["נָתָן","Nathan"],["הַנָּבִיא","the-prophet"],["וַיִּקְרָא","and-he-called"],["אֶת־שְׁמוֹ","[ACC]-his-name"],["יְדִידְיָהּ","Jedidiah"],["בַּעֲבוּר","because-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"כו", words:[["וַיִּלָּחֶם","and-he-fought"],["יוֹאָב","Joab"],["בְּרַבַּת","in-Rabbah of"],["בְּנֵי","sons-of"],["עַמּוֹן","Ammon"],["וַיִּלְכֹּד","and-he-captured"],["אֶת־עִיר","ACC-city-of"],["הַמְּלוּכָה","the-capital"],["׃",""]] },
  { num:"כז", words:[["וַיִּשְׁלַח","and-he-sent"],["יוֹאָב","Joab"],["מַלְאָכִים","angels"],["אֶל־דָּוִד","to-David"],["וַיֹּאמֶר","and-said"],["נִלְחַמְתִּי","I-fought"],["בְרַבָּה","against-Rabbah"],["גַּם־לָכַדְתִּי","also-I have captured"],["אֶת־עִיר","ACC-city-of"],["הַמָּיִם","the-water"],["׃",""]] },
  { num:"כח", words:[["וְעַתָּה","and-now"],["אֱסֹף","to-take-away"],["אֶת־יֶתֶר","ACC-remainder-of"],["הָעָם","the-people"],["וַחֲנֵה","and-encamp"],["עַל־הָעִיר","upon-the-city"],["וְלׇכְדָהּ","and-he will capture-her"],["פֶּן־אֶלְכֹּד","lest-I should take"],["אֲנִי","I"],["אֶת־הָעִיר","ACC-the-city"],["וְנִקְרָא","and-was-called"],["שְׁמִי","my-name"],["עָלֶיהָ","upon-it"],["׃",""]] },
  { num:"כט", words:[["וַיֶּאֱסֹף","and-it-came-to-pass-that-Alma-and-his-people"],["דָּוִד","David"],["אֶת־כׇּל־הָעָם","[ACC]-all-the-people"],["וַיֵּלֶךְ","and-he-went"],["רַבָּתָה","Rabbah-towards"],["וַיִּלָּחֶם","and-he-fought"],["בָּהּ","in-it(f)"],["וַיִּלְכְּדָהּ","and-he captured-it"],["׃",""]] },
  { num:"ל", words:[["וַיִּקַּח","and-took"],["אֶת־עֲטֶרֶת־מַלְכָּם","[ACC]-crown-of-their-king"],["מֵעַל","from-upon"],["רֹאשׁוֹ","his-head"],["וּמִשְׁקָלָהּ","and-weight-its"],["כִּכַּר","the valley of"],["זָהָב","gold"],["וְאֶבֶן","and-the-stone-of"],["יְקָרָה","precious"],["וַתְּהִי","and-was"],["עַל־רֹאשׁ","upon-the-heads-of"],["דָּוִד","David"],["וּשְׁלַל","and-the booty of"],["הָעִיר","the-city"],["הוֹצִיא","has-brought"],["הַרְבֵּה","much"],["מְאֹד","exceedingly"],["׃",""]] },
  { num:"לא", words:[["וְאֶת־הָעָם","and-[ACC]-the-people"],["אֲשֶׁר־בָּהּ","whose-in-it(f)"],["הוֹצִיא","has-brought"],["וַיָּשֶׂם","and-made-He"],["בַּמְּגֵרָה","at the-saws"],["וּבַחֲרִצֵי","and-at-the picks of"],["הַבַּרְזֶל","the-iron"],["וּבְמַגְזְרֹת","and-at-the axes of"],["הַבַּרְזֶל","the-iron"],["וְהֶעֱבִיר","and-he caused to pass"],["אוֹתָם","them"],["(במלכן)","???"],["[בַּמַּלְבֵּן]","in the-brick molds"],["וְכֵן","and-so"],["יַעֲשֶׂה","he-shall-do"],["לְכֹל","for-all"],["עָרֵי","cities-of"],["בְנֵי־עַמּוֹן","sons-of-Ammon"],["וַיָּשׇׁב","and-he will turn"],["דָּוִד","David"],["וְכׇל־הָעָם","and-all-the-people"],["יְרוּשָׁלָ͏ִם","Jerusalem"],["׃",""]] },
];
renderVerseSet(jst2sa_ch1Verses, 'jst2sa-ch1-verses');

})();
