// jst_verses/jst2th.js — 2 Thessalonians (JST) verse data
(function() {
var jst2th_ch1Verses = [
  { num:"א", words:[["וְהִנְנוּ","and-behold-us"],["מְבַקְשִׁים","seek"],["מִכֶּם","from-you"],["אֶחָי","brothers-my"],["עַל־אֹדוֹת","upon-concerning"],["בִּיאַת","the-coming-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["וַאֲסִיפָתֵנוּ","and-gathering-of-us"],["אֵלָיו","to-him"],["׃",""]] },
  { num:"ב", words:[["אֲשֶׁר","whose"],["לֹא־תִטָּרֵף","???"],["דַּעְתְּכֶם","knowledge-you(pl)"],["פִּתְאֹם","suddenly"],["וַאֲשֶׁר","and-whom"],["לֹא","not"],["תִּבָּהֵלוּ","you be hasty(they)"],["לֹא","not"],["בְרוּחַ","by-the spirit of"],["וְלֹא","and-not"],["בְדִבּוּר","in-speaking"],["וְלֹא","and-not"],["בְאִגֶּרֶת","in-letter"],["כְּאִלּוּ","as-though"],["שְׁלוּחָה","which has been sent"],["מֵאִתָּנוּ","from-among-us"],["לֵאמֹר","saying"],["הִגִּיעַ","come-has"],["יוֹם","day"],["יְהוָֹה","the-Lord"],["׃",""]] },
  { num:"ג", words:[["אַל־יַתְעֶה","do-not-shall-deceive"],["אֶתְכֶם","you"],["אִישׁ","man-of"],["בְּשׁוּם","in-any/put"],["אוֹפֶן","a wheel"],["כִּי","because"],["לֹא־יָבֹא","not-shall-come"],["בְּטֶרֶם","before"],["יִהְיֶה","he-shall-be"],["בָרִאשׁוֹנָה","first-place"],["הַמֶּרֶד","the-rebellion"],["וְנִגְלָה","and-he has revealed himself"],["אִישׁ","man-of"],["הָחַטָּאָה","the-sin"],["בֶּן־הָאֲבַדּוֹן","son-of-H'bdvn"],["׃",""]] },
  { num:"ד", words:[["הַמִּתְקוֹמֵם","???"],["וְהַמִּתְרוֹמֵם","???"],["עַל־כָּל־הַנִּקְרָא","upon-all-the-called"],["אֵל","God"],["אוֹ","or"],["עֲבוֹדָה","labor/work"],["כִּי","because"],["גַם־יֵשֵׁב","also-remained"],["בְּהֵיכַל","in-the temple of"],["הָאֱלֹהִים","the-God"],["כֵּאלֹהִים","as-God"],["וּמַרְאֶה","and-shows"],["אֶת־עַצְמוֹ","[ACC]-himself"],["כִּי","because"],["אֱלֹהִים","God"],["הוּא","it-is"],["׃",""]] },
  { num:"ה", words:[["הֲלֹא","do-not"],["תִזְכְּרוּ","you-should-remember"],["כִּי־בְעוֹד","because-in-yet"],["הֱיוֹתִי","being-I"],["אִתְּכֶם","with-you"],["אֵלֶּה","these"],["דִּבַּרְתִּי","I-have-spoken"],["אֲלֵיכֶם","unto-you"],["׃",""]] },
  { num:"ו", words:[["וְעַתָּה","and-now"],["יְדַעְתֶּם","you-know"],["אֶת","[ACC]"],["אֲשֶׁר","whose"],["יִמְנָעֵהוּ","???"],["מִלְּהִגָּלוֹת","from-to-be revealed"],["בְּעִתּוֹ","in-its-time"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["סוֹד","counsels-of"],["הָרֶשַׁע","the-wickedness"],["כְּבָר","already-come"],["הֵחֵלָּה","began(f)"],["פְעֻלָּתוֹ","recompense-his"],["רַק","only"],["שֶׁיּוּסַר","that-be-removed"],["מִתָּוֶךְ","from-middle"],["הַמֹּנֵעַ","has-withheld?"],["עַד־כֹּה","until-thus"],["׃",""]] },
  { num:"ח", words:[["וְאָז","and-then"],["יִגָּלֶה","He-shall-be-revealed"],["הָרָשָׁע","the-more-wicked"],["אֲשֶׁר","whose"],["יְמִיתֶנּוּ","he will put to death-him"],["הָאָדוֹן","the-Lord"],["בְּרוּחַ","in-the-Spirit"],["שְׂפָתָיו","His-lips"],["וְיַשְׁבִּיתֶנּוּ","???"],["בְּהוֹפָעַת","in-you have shone forth"],["בִּיאָתוֹ","in-they agreed"],["׃",""]] },
  { num:"ט", words:[["אֵת","[ACC]"],["אֲשֶׁר","whose"],["יָבוֹא","shall-come"],["כְּפִי","according-to"],["פְּעֻלַּת","the wages of"],["הַשָׂטָן","the-adversary"],["בְּרָב־כֹּחַ","with-greatness of-power"],["וּבְאֹתוֹת","and-by-signs"],["וּבְמוֹפְתֵי","and-in-types-of"],["שָׁקֶר","false"],["׃",""]] },
  { num:"י", words:[["וּבְכָל־מִרְמַת","and-with-all-???"],["אָוֶן","iniquity"],["בָּאֹבְדִים","in-the-lost"],["תַּחַת","under"],["אֲשֶׁר","whose"],["לֹא","not"],["קִבְּלוּ","receive"],["אֶת־אַהֲבַת","[ACC]-love-of"],["הָאֱמֶת","the-true"],["לְהִוָּשֵׁעַ","to-shall-be"],["׃",""]] },
  { num:"יא", words:[["וּבַעֲבוּר","and-because"],["זֹאת","this"],["יְשַׁלַּח","shall-send"],["לָהֶם","to-them"],["הָאֱלֹהִים","the-God"],["מַדּוּחֵי","???"],["שָׁוְא","falsehood"],["לְהַאֲמִין","to-believe"],["בַּשָּׁקֶר","in-falsehood"],["׃",""]] },
  { num:"יב", words:[["לְמַעַן","in-order-that"],["יִדּוֹנוּ","be-damned"],["כָּל־אֲשֶׁר","all-which"],["לֹא־הֶאֱמִינוּ","not-did-they-believe"],["בָאֱמֶת","in-truth"],["וְרָצוּ","they-shall-be-pleased"],["בָּעַוְלָה","in-iniquity"],["׃",""]] },
  { num:"יג", words:[["אֲבָל","but/however"],["אֲנַחְנוּ","we"],["חַיָּבִים","are-obligated"],["לְהוֹדוֹת","to-thanksgivings"],["תָּמִיד","continually"],["לֵאלֹהִים","God"],["בַּעֲבוּרְכֶם","for-your-sakes"],["אַחַי","my-brothers"],["חֲבִיבֵי","my-beloved"],["הָאָדוֹן","the-Lord"],["אֲשֶׁר","whose"],["מִבַּתְּחִלָּה","from-in-shall-begin"],["בָּחַר","chose"],["בָּכֶם","in-you"],["הָאֱלֹהִים","the-God"],["לִישׁוּעָה","unto-salvation"],["בִּקְדֻשַּׁת","with-holiness-of"],["הָרוּחַ","the-Spirit"],["וּבֶאֱמוּנַת","and-in-faith-of"],["הָאֱמֶת","the-true"],["׃",""]] },
  { num:"יד", words:[["לָזֹאת","to-this"],["קָרָא","called"],["אֶתְכֶם","you"],["בִּבְשׂוֹרָתֵנוּ","in-good-news-of-us"],["לְנַחֲלַת","for-the-inheritance-of"],["כְּבוֹד","the-glory-of"],["אֲדֹנֵינוּ","our-Lord"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"טו", words:[["לָכֵן","therefore"],["אַחַי","my-brothers"],["עִמְדוּ","stand"],["וְהַחֲזִיקוּ","and-lay-hold-upon"],["בַקַּבָּלוֹת","in-received(pl)"],["אֲשֶׁר","whose"],["לֻמַּדְתֶּם","have-been-taught"],["אִם","[compound]"],["בִּדְבָרֵנוּ","in-business-our"],["אִם","[compound]"],["בְּאִגַּרְתֵּנוּ","???"],["׃",""]] },
  { num:"טז", words:[["וַאֲדֹנֵינוּ","and-lord-our"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["וֵאלֹהֵינוּ","and-God-our"],["אָבִינוּ","our-father"],["אֲשֶׁר","whose"],["אָהַב","He-loves"],["אֹתָנוּ","us"],["וַיִּתֶּן־לָנוּ","and-the-king-granted-unto-us"],["בְחַסְדּוֹ","in-His-lovingkindness"],["נֶחָמַת","???"],["עוֹלָם","eternal"],["וְתִקְוָה","and-hope"],["טוֹבָה","good"],["׃",""]] },
  { num:"יז", words:[["הוּא","it-is"],["יְנַחֵם","He-comforted"],["אֶת־לְבַבְכֶם","[ACC]-your-hearts"],["וִיכוֹנֵן","and-he will establish"],["אֶתְכֶם","you"],["בְּכָל־דָּבָר","in-all-things"],["וּמַעֲשֶׂה","and-a-work"],["טוֹב","good"],["׃",""]] },
];
renderVerseSet(jst2th_ch1Verses, 'jst2th-ch1-verses');

})();
