// jst_verses/jst2co.js — 2 Corinthians (JST) verse data
(function() {
var jst2co_ch1Verses = [
  { num:"א", words:[["הֵן","yea"],["יָדַעְנוּ","we-know"],["כִּי","because"],["בֵּהָרֵס","???"],["בֵּית","house-of"],["אָהֳלֵנוּ","the tent of-us"],["אֲשֶׁר","whose"],["בָּאָרֶץ","in-the-land"],["יֶשׁ־לָנוּ","we-have"],["בִנְיָן","the-building-of"],["מֵאֵת","from"],["הָאֱלֹהִים","the-God"],["בַּיִת","house"],["אֲשֶׁר","whose"],["אֵינֶנּוּ","it-is-not"],["מַעֲשֵׂה","work-of"],["יָדַיִם","both hands"],["וְהוּא","and-it"],["קַיָּם","established"],["לְעוֹלָם","forever"],["בַּשָּׁמָיִם","in-the-heavens"],["׃",""]] },
  { num:"ב", words:[["כִּי","because"],["גַם־עַתָּה","also-now"],["נֶאֱנָחִים","are groaning"],["וְנִכְסָפִים","and-longing"],["אֲנַחְנוּ","we"],["לְהִתְעַטֵּף","to-faints away"],["בְּבֵיתֵנוּ","in-house-of-us"],["אֲשֶׁר","whose"],["מִן־הַשָּׁמָיִם","from-the-heavens"],["׃",""]] },
  { num:"ג", words:[["וּבִלְבַד","and-only"],["שֶׁאַחֲרֵי","that-after"],["לְבַשְׁנֻהוּ","to-shame(they)"],["לֹא","not"],["נִמָּצֵא","be-found"],["עֲרֻמִּים","naked"],["׃",""]] },
  { num:"ד", words:[["כִּי","because"],["בְּאָהֳלֵנוּ","in-tent-us"],["זֶה","this"],["נֵאָנַח","groaning"],["תַּחַת","under"],["הַמַּשָּׂא","the-burdens"],["מִתְאַוִּים","craved"],["לְהִתְעַטֵּף","to-faints away"],["וְלֹא","and-not"],["לִפְשֹׁט","to-strip"],["לְמַעַן","in-order-that"],["יְבֻלַּע","is-swallowed-up"],["הַמָּוֶת","death"],["עַל־יְדֵי","by-means-of"],["הַחַיִּים","life"],["׃",""]] },
  { num:"ה", words:[["וֵאלֹהִים","and-God"],["תִּקֵּן","he arranged in order"],["אֹתָנוּ","us"],["לְכָךְ","to-so"],["אֲשֶׁר","whose"],["גַּם־נָתַן","also-was-given"],["לָנוּ","us"],["אֶת־רוּחוֹ","[ACC]-His-Spirit"],["לְעֵרָבוֹן","to-a pledge"],["׃",""]] },
  { num:"ו", words:[["לָכֵן","therefore"],["בְּטוּחִים","Btoch(pl)"],["אֲנַחְנוּ","we"],["בְּכָל־עֵת","with-all-time"],["וְיֹדְעִים","and-O those who know"],["כִּי","because"],["כָל־עוֹד","all-any-more"],["שֶׁמּוֹשָׁבֵנוּ","that-was returned-us"],["בַגּוּף","in-the-body"],["רְחוֹקִים","are distant"],["אֲנַחְנוּ","we"],["מִן־הָאָדוֹן","from-the-Lord"],["׃",""]] },
  { num:"ז", words:[["כִּי","because"],["בֶאֱמוּנָה","in-faith"],["נִתְהַלֵּךְ","we-walk"],["וְלֹא","and-not"],["בִּרְאוּת","in-the sight of"],["עֵינָיִם","eyes"],["׃",""]] },
  { num:"ח", words:[["אֲבָל","but/however"],["בְּטוּחִים","Btoch(pl)"],["אֲנַחְנוּ","we"],["וְהַטּוֹב","and-the-good"],["בְּעֵינֵינוּ","in-our-eyes"],["לְהִתְרַחֵק","to-distance-oneself"],["מִן־הַגּוּף","from-the-body"],["וְלִהְיוֹת","and-to-be"],["קְרוֹבִים","about"],["אֶל־הָאָדוֹן","to-the-Lord"],["׃",""]] },
  { num:"ט", words:[["וְלָכֵן","therefore"],["אִם־קְרוֹבִים","[compound]-about"],["אֲנַחְנוּ","we"],["אִם־רְחוֹקִים","[compound]-are distant"],["נִשְׁתַּדֵּל","???"],["לִמְצֹא","to-find"],["חֵן","favor"],["בְּעֵינָיו","in-His-eyes"],["׃",""]] },
  { num:"י", words:[["כִּי","because"],["כֻלָּנוּ","all"],["עֲתִידִים","are-about"],["לְהֵרָאוֹת","appear"],["לִפְנֵי","before"],["כִסֵּא־דִין","throne-of-judgment-of"],["הַמָּשִׁיחַ","the-Messiah"],["לְמַעַן","in-order-that"],["יִשָּׂא","takes-away"],["אִישׁ","man-of"],["כְּפָעֳלוֹ","according to-work-his"],["בְּחַיֵּי","in-the-life-of"],["גוּפוֹ","his-body"],["אִם־טוֹב","if-good"],["וְאִם־רָע","and-if-evil"],["׃",""]] },
  { num:"יא", words:[["וְעַתָּה","and-now"],["יַעַן","because"],["אֲשֶׁר","whose"],["יִרְאַת","the-fear-of"],["אֲדֹנָי","Lord"],["לְנֶגֶד","before"],["עֵינֵינוּ","our-eyes"],["נְדַבֵּר","speak"],["עַל־לֵב","upon-heart"],["בְּנֵי","sons-of"],["אָדָם","man"],["וְלֵאלֹהִים","and-God"],["אֲנַחְנוּ","we"],["גְלוּיִם","???"],["וַאֲקַוֶּה","and-I may wait for"],["כִּי־גְלוּיִם","???"],["אֲנַחְנוּ","we"],["גַּם","also"],["בְּמַדָּעֲכֶם","in-knowledge-you(pl)"],["׃",""]] },
  { num:"יב", words:[["כִּי","because"],["אֵין","there-is-no"],["אֲנַחְנוּ","we"],["מִשְׁתַּבְּחִים","???"],["שֵׁנִית","again"],["לִפְנֵיכֶם","unto-you"],["כִּי","because"],["אִם","[compound]"],["מַמְצִיאִים","am about to deliver(pl)"],["לָכֶם","to-you"],["מָקוֹם","a-place"],["לְהִתְפָּאֵר","to-boast"],["בָּנוּ","in-us"],["כְּנֶגֶד","as-against"],["הַמִּתְפָּאֲרִים","???"],["בִּפְנֵיהֶם","in-their-faces"],["וְלֹא","and-not"],["בְלִבָּם","in-their-heart"],["׃",""]] },
  { num:"יג", words:[["כִּי","because"],["אִם־הִשְׁתַּגַּעְנוּ","???"],["הִשְׁתַּגַּעְנוּ","???"],["לֵאלֹהִים","God"],["וְאִם־הִשְׂכַּלְנוּ","and-[compound]-???"],["הִשְׂכַּלְנוּ","???"],["לָכֶם","to-you"],["׃",""]] },
  { num:"יד", words:[["כִּי־אֲחוּזֵי","because-seized-by"],["אַהֲבַת","love-of"],["הַמָּשִׁיחַ","the-Messiah"],["אֲנַחְנוּ","we"],["הַדָּנִים","the-judging"],["שֶׁאִם־מֵת","that-[compound]-is-dead"],["אֶחָד","one"],["בְּעַד","on-behalf-of"],["כֻּלָּם","all-of-them"],["כֻּלָּם","all-of-them"],["מֵתוּ","have-died"],["׃",""]] },
  { num:"טו", words:[["וּבְעַד","and-for"],["כֻּלָּם","all-of-them"],["מֵת","is-dead"],["לְמַעַן","in-order-that"],["לֹא־יִחְיוּ","not-they-shall-live"],["הַחַיִּים","life"],["עוֹד","any-more"],["לְנַפְשָׁם","to-their-own-souls"],["כִּי","because"],["אִם־לַאֲשֶׁר","[compound]-unto-him-who"],["מֵת","is-dead"],["וְקָם","and-shall-arise"],["בַּעֲדָם","for-them"],["׃",""]] },
  { num:"טז", words:[["לָכֵן","therefore"],["מֵעַתָּה","from-this-time"],["אֲנַחְנוּ","we"],["לֹא־נֵדַע","not-we-shall-have"],["אִישׁ","man-of"],["מִן־הַבָּשָׂר","from-the-flesh"],["וְגַם","and-also"],["אִם־יָדַעְנוּ","[compound]-we-know"],["אֶת־הַמָּשִׁיחַ","[ACC]-the-Messiah"],["מִן־הַבָּשָׂר","from-the-flesh"],["מֵעַתָּה","from-this-time"],["לֹא־נֵדָעֵהוּ","???"],["עוֹד","any-more"],["׃",""]] },
  { num:"יז", words:[["לָכֵן","therefore"],["מִי","who"],["שֶׁהוּא","that-He-is"],["בַמָּשִׁיחַ","in-anointed"],["בְּרִיָּה","creature"],["חֲדָשָׁה","new"],["הוּא","it-is"],["הָרִאשֹׁנוֹת","the-first"],["עָבָרוּ","they have passed"],["הִנֵּה","behold"],["הַכֹּל","all"],["נַעֲשׂוֹּ","were-done"],["חֲדָשׁוֹת","new"],["׃",""]] },
  { num:"יח", words:[["וְהַכֹּל","and-all"],["מֵאֵת","from"],["הָאֱלֹהִים","the-God"],["הַמְרַצֶּה","the-oppression"],["אֹתָנוּ","us"],["לְעַצְמוֹ","to-himself"],["עַל־יְדֵי","by-means-of"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["וַיִּתֶּן־לָנוּ","and-the-king-granted-unto-us"],["שֵׁרוּת","freedom"],["הָרִצּוּי","the-favored"],["׃",""]] },
  { num:"יט", words:[["יַעַן","because"],["אֲשֶׁר","whose"],["אֱלֹהִים","God"],["הָיָה","was"],["בַמָּשִׁיחַ","in-anointed"],["מְרַצֶּה","oppression"],["אֶת־הָעוֹלָם","[ACC]-the-world"],["לְעַצְמוֹ","to-himself"],["וְלֹא־חָשַׁב","and-not-he-thought"],["לָהֶם","to-them"],["אֶת־פִּשְׁעֵיהֶם","[ACC]-their-crimes"],["וַיָּשֶׂם","and-made-He"],["בָּנוּ","in-us"],["אֶת־דְּבַר","ACC-word-of"],["הָרִצּוּי","the-favored"],["׃",""]] },
  { num:"כ", words:[["וּבְכֵן","and-in-such"],["מְלִיצֵי","the envoys of"],["הַמָּשִׁיחַ","the-Messiah"],["אֲנַחְנוּ","we"],["וְהָאֱלֹהִים","and-the-God"],["מַזְהִיר","would-exhort"],["אֶתְכֶם","you"],["עַל־יָדֵנוּ","upon-our-hand"],["נְבַקֵּשׁ","we-ask"],["מִכֶּם","from-you"],["בְּעַד","on-behalf-of"],["הַמָּשִׁיחַ","the-Messiah"],["הִתְכַּפְּרוּ־נָא","???"],["לֵאלֹהִים","God"],["׃",""]] },
  { num:"כא", words:[["כִּי","because"],["אֶת־אֲשֶׁר","ACC-that-which"],["לֹא־יָדַע","not-he-knew"],["חֲטָאָה","this-people"],["אֹתוֹ","him"],["עָשָׂה","he-did"],["לַחֲטָאָה","sin"],["בַּעֲדֵנוּ","in-until-us"],["לְמַעַן","in-order-that"],["נִהְיֶה־בּוֹ","let-us-be-against-him"],["אֲנַחְנוּ","we"],["לְצִדְקַת","to-righteousness-of"],["אֱלֹהִים","God"],["׃",""]] },
];
renderVerseSet(jst2co_ch1Verses, 'jst2co-ch1-verses');

})();
