// jst_verses/jstamo.js — Amos (JST) verse data
(function() {
var jstamo_ch1Verses = [
  { num:"א", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown-me"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["וְהִנֵּה","and-behold"],["יוֹצֵר","potter"],["גֹּבַי","locusts"],["בִּתְחִלַּת","in-the-commencement-of"],["עֲלוֹת","the-ascending-of"],["הַלָּקֶשׁ","the-spring-crop"],["וְהִנֵּה־לֶקֶשׁ","and-behold-a spring-crop"],["אַחַר","after"],["גִּזֵּי","the mowings of"],["הַמֶּלֶךְ","the-king"],["׃",""]] },
  { num:"ב", words:[["וְהָיָה","and-be"],["אִם־כִּלָּה","[compound]-all-of-it(f)"],["לֶאֱכוֹל","to-eat"],["אֶת־עֵשֶׂב","[ACC]-plants"],["הָאָרֶץ","the-earth"],["וָאֹמַר","and-I-said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["סְלַח־נָא","forgive-I-pray"],["מִי","who"],["יָקוּם","he-shall-rise"],["יַעֲקֹב","Jacob"],["כִּי","because"],["קָטֹן","little-are"],["הוּא","it-is"],["׃",""]] },
  { num:"ג", words:[["נִחַם","comforted"],["יְהֹוָה","the-LORD"],["עַל־זֹאת","upon-this"],["לֹא","not"],["תִהְיֶה","be"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ד", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown-me"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["וְהִנֵּה","and-behold"],["קֹרֵא","I-call"],["לָרִב","to-contest a lawsuit"],["בָּאֵשׁ","by-fire"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["וַתֹּאכַל","and-she ate"],["אֶת־תְּהוֹם","[ACC]-gulf"],["רַבָּה","much"],["וְאָכְלָה","and-shall-devour"],["אֶת־הַחֵלֶק","[ACC]-the-part-of"],["׃",""]] },
  { num:"ה", words:[["וָאֹמַר","and-I-said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["חֲדַל־נָא","cease-I-pray"],["מִי","who"],["יָקוּם","he-shall-rise"],["יַעֲקֹב","Jacob"],["כִּי","because"],["קָטֹן","little-are"],["הוּא","it-is"],["׃",""]] },
  { num:"ו", words:[["נִחַם","comforted"],["יְהֹוָה","the-LORD"],["עַל־זֹאת","upon-this"],["גַּם־הִיא","also-it-is"],["לֹא","not"],["תִהְיֶה","be"],["אָמַר","said"],["אֲדֹנָי","Lord"],["יֱהֹוִה","Yahweh"],["׃",""]] },
  { num:"ז", words:[["כֹּה","thus"],["הִרְאַנִי","he has shown-me"],["וְהִנֵּה","and-behold"],["אֲדֹנָי","Lord"],["נִצָּב","stands-up"],["עַל־חוֹמַת","upon-the-walls-of"],["אֲנָךְ","tin"],["וּבְיָדוֹ","and-in-his-hand"],["אֲנָךְ","tin"],["׃",""]] },
  { num:"ח", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["אֵלַי","to-me"],["מָה־אַתָּה","what-you"],["רֹאֶה","I-perceive"],["עָמוֹס","Amos"],["וָאֹמַר","and-I-said"],["אֲנָךְ","tin"],["וַיֹּאמֶר","and-said"],["אֲדֹנָי","Lord"],["הִנְנִי","behold-I"],["שָׂם","set"],["אֲנָךְ","tin"],["בְּקֶרֶב","among"],["עַמִּי","my-people"],["יִשְׂרָאֵל","Israel"],["לֹא־אוֹסִיף","not-more"],["עוֹד","any-more"],["עֲבוֹר","to pass on"],["לוֹ","him"],["׃",""]] },
  { num:"ט", words:[["וְנָשַׁמּוּ","and-they will be desolate"],["בָּמוֹת","Bamoth"],["יִשְׂחָק","he laughs"],["וּמִקְדְּשֵׁי","and-the sanctuaries of"],["יִשְׂרָאֵל","Israel"],["יֶחֱרָבוּ","they will become desolate"],["וְקַמְתִּי","for-I-will-rise-up"],["עַל־בֵּית","to-the-house-of"],["יָרׇבְעָם","Jeroboam"],["בֶּחָרֶב","by-the-sword"],["׃",""]] },
  { num:"י", words:[["וַיִּשְׁלַח","and-he-sent"],["אֲמַצְיָה","Amaziah"],["כֹּהֵן","one-priest"],["בֵּית־אֵל","Bethel"],["אֶל־יָרׇבְעָם","to-Jeroboam"],["מֶלֶךְ־יִשְׂרָאֵל","king-of-Israel"],["לֵאמֹר","saying"],["קָשַׁר","he has conspired"],["עָלֶיךָ","upon-you(f)"],["עָמוֹס","Amos"],["בְּקֶרֶב","among"],["בֵּית","house-of"],["יִשְׂרָאֵל","Israel"],["לֹא־תוּכַל","not-can"],["הָאָרֶץ","the-earth"],["לְהָכִיל","to-contain"],["אֶת־כׇּל־דְּבָרָיו","[ACC]-all-of-his-words"],["׃",""]] },
  { num:"יא", words:[["כִּי־כֹה","because-thus"],["אָמַר","said"],["עָמוֹס","Amos"],["בַּחֶרֶב","with-the-sword"],["יָמוּת","who-shall-die"],["יָרׇבְעָם","Jeroboam"],["וְיִשְׂרָאֵל","though-Israel"],["גָּלֹה","certainly"],["יִגְלֶה","he uncovers"],["מֵעַל","from-upon"],["אַדְמָתוֹ","land-his"],["׃",""]] },
  { num:"יב", words:[["וַיֹּאמֶר","and-said"],["אֲמַצְיָה","Amaziah"],["אֶל־עָמוֹס","to-Amos"],["חֹזֶה","a-seer"],["לֵךְ","go"],["בְּרַח־לְךָ","flee-for-you"],["אֶל־אֶרֶץ","to-land-of"],["יְהוּדָה","Judah"],["וֶאֱכׇל־שָׁם","and-eat-there-is"],["לֶחֶם","bread"],["וְשָׁם","and-there"],["תִּנָּבֵא","you-shall-prophesy"],["׃",""]] },
  { num:"יג", words:[["וּבֵית־אֵל","and-house-of-God"],["לֹא־תוֹסִיף","not-Tosif"],["עוֹד","any-more"],["לְהִנָּבֵא","to-prophesy"],["כִּי","because"],["מִקְדַּשׁ־מֶלֶךְ","the sanctuary of-king-of"],["הוּא","it-is"],["וּבֵית","and-house-of"],["מַמְלָכָה","kingdom"],["הוּא","it-is"],["׃",""]] },
  { num:"יד", words:[["וַיַּעַן","and-he-answered"],["עָמוֹס","Amos"],["וַיֹּאמֶר","and-said"],["אֶל־אֲמַצְיָה","to-Amaziah"],["לֹא־נָבִיא","not-a-prophet"],["אָנֹכִי","I"],["וְלֹא","and-not"],["בֶן־נָבִיא","Bn-a-prophet"],["אָנֹכִי","I"],["כִּי־בוֹקֵר","because-was a herdsman"],["אָנֹכִי","I"],["וּבוֹלֵס","and-a fig picker of"],["שִׁקְמִים","the-sycamores"],["׃",""]] },
  { num:"טו", words:[["וַיִּקָּחֵנִי","and-he took-me"],["יְהֹוָה","the-LORD"],["מֵאַחֲרֵי","from-after"],["הַצֹּאן","the-flock"],["וַיֹּאמֶר","and-said"],["אֵלַי","to-me"],["יְהֹוָה","the-LORD"],["לֵךְ","go"],["הִנָּבֵא","and-prophesy"],["אֶל־עַמִּי","unto-my-people"],["יִשְׂרָאֵל","Israel"],["׃",""]] },
  { num:"טז", words:[["וְעַתָּה","and-now"],["שְׁמַע","hearken"],["דְּבַר־יְהֹוָה","the-word-of-the-LORD"],["אַתָּה","you"],["אֹמֵר","say"],["לֹא","not"],["תִנָּבֵא","you must prophesy"],["עַל־יִשְׂרָאֵל","upon-Israel"],["וְלֹא","and-not"],["תַטִּיף","you must prophesy"],["עַל־בֵּית","to-the-house-of"],["יִשְׂחָק","he laughs"],["׃",""]] },
  { num:"יז", words:[["לָכֵן","therefore"],["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["אִשְׁתְּךָ","was wife-your"],["בָּעִיר","in-the-city"],["תִּזְנֶה","she will be a prostitute"],["וּבָנֶיךָ","and-your-sons"],["וּבְנֹתֶיךָ","and-daughters-your"],["בַּחֶרֶב","with-the-sword"],["יִפֹּלוּ","they-must-fall"],["וְאַדְמָתְךָ","and-land-your"],["בַּחֶבֶל","with-rope"],["תְּחֻלָּק","it will be divided"],["וְאַתָּה","for-you"],["עַל־אֲדָמָה","upon-ground/earth"],["טְמֵאָה","filthy"],["תָּמוּת","to-death"],["וְיִשְׂרָאֵל","though-Israel"],["גָּלֹה","certainly"],["יִגְלֶה","he uncovers"],["מֵעַל","from-upon"],["אַדְמָתוֹ","land-his"],["׃",""]] },
];
renderVerseSet(jstamo_ch1Verses, 'jstamo-ch1-verses');

})();
