// jst_verses/jstcol.js — Colossians (JST) verse data
(function() {
var jstcol_ch1Verses = [
  { num:"א", words:[["הִנְנִי","behold-I"],["מוֹדִיעַ","making-known"],["אֶתְכֶם","you"],["גֹּדֶל","the-greatness-of"],["הַקְרָב","the-battle"],["שֶׁלִּי","which-belongs to-me"],["בַּעַדְכֶם","in-until-you"],["וּבְעַד","and-for"],["אַנְשֵׁי","the-men-of"],["לוּדְקְיָא","???"],["וּבְעַד","and-for"],["כֹּל","all"],["אֲשֶׁר","whose"],["לֹא־רָאוּ","not-saw"],["אֶת־פָּנַי","[ACC]-presence-my"],["בַּבָּשָׂר","in-the-flesh"],["׃",""]] },
  { num:"ב", words:[["לְמַעַן","in-order-that"],["יְנֻחֲמוּ","shall-be-comforted"],["לִבּוֹתָם","their-hearts"],["וְנִקְשְׁרוּ","???"],["יַחַד","oft"],["בְּאַהֲבָה","and-in-love"],["וּלְכָל־עשֶׁר","and-to-all-???"],["דַּעַת","true-knowledge"],["נְכוֹנָה","established/firm(f)"],["לְהָבִין","understand-them"],["וּלְהַשְׂכִּיל","and-to-gain insight"],["סוֹד","counsels-of"],["הָאֱלֹהִים","the-God"],["אָבִינוּ","our-father"],["וְסוֹד","and-the secret of"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ג", words:[["אֲשֶׁר","whose"],["גְּנוּזִים","???"],["בּוֹ","against-him"],["כָּל־אֹצְרוֹת","all-the treasures of"],["הַחָכְמָה","wisdom"],["וְהַדָּעַת","and-knowledge"],["׃",""]] },
  { num:"ד", words:[["וְזֹאת","and-this"],["אֹמֵר","say"],["אֲנִי","I"],["לָכֶם","to-you"],["לְמַעַן","in-order-that"],["אֲשֶׁר־לֹא","whose-not"],["יַטְעֶה","???"],["אֶתְכֶם","you"],["אִישׁ","man-of"],["בְּשִׂפְתֵי","on-the lips of"],["חֲלָקוֹת","flattering-things"],["׃",""]] },
  { num:"ה", words:[["כִּי","because"],["גַּם־אִם","also-[compound]"],["בִּבְשָׂרִי","in-flesh-my"],["אֲנִי","I"],["רָחוֹק","far"],["מִכֶּם","from-you"],["הִנֵּה","behold"],["בְרוּחִי","in-my-spirit"],["אֲנִי","I"],["אֶצְלְכֶם","I delivered-you(pl)"],["וְאֶשְׂמַח","and-I-may-have-joy"],["בִּרְאֹתִי","when-saw-I"],["אֶת־מַעֲמַדְכֶם","???"],["וְתֹקֶף","and-the power of"],["אֱמוּנַתְכֶם","your-faith"],["בַּמָּשִׁיחַ","in-the-Messiah"],["׃",""]] },
  { num:"ו", words:[["לָכֵן","therefore"],["כַּאֲשֶׁר","when/as"],["קִבַּלְתֶּם","received"],["אֶת־הַמָּשִׁיחַ","[ACC]-the-Messiah"],["אֵת","[ACC]"],["יֵשׁוּעַ","Yeshua"],["אֲדֹנֵינוּ","our-Lord"],["כֵּן","thus"],["גַּם־הִתְהַלְּכוּ","also-they walked about"],["בוֹ","in-Him"],["׃",""]] },
  { num:"ז", words:[["מַשְׁרִישִׁים","???"],["וְנִבְנִים","and-understanding"],["בּוֹ","against-him"],["וְקַיָּמִים","and-exist"],["בָּאֱמוּנָה","in-the-faith"],["כַּאֲשֶׁר","when/as"],["לֻמַּדְתֶּם","have-been-taught"],["וּמַרְבִּים","and-who had many"],["בְּתוֹדָה","with-thanksgiving"],["בָּהּ","in-it(f)"],["׃",""]] },
  { num:"ח", words:[["הִזָּהֲרוּ","being-warned"],["פֶּן־יוֹלִיךְ","lest-will-lead-away"],["אֶתְכֶם","you"],["אִישׁ","man-of"],["שׁוֹלָל","barefoot"],["בְּפִילֹסוֹפְיָה","???"],["וּבְמַדּוּחֵי","???"],["שָׁוְא","falsehood"],["לְפִי","according-to"],["קַבָּלַת","you-received"],["בְּנֵי","sons-of"],["הָאָדָם","man"],["וְתִקּוּנֵי","???"],["הָעוֹלָם","the-world"],["וְלֹא","and-not"],["עַל־פִּי","according-to"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ט", words:[["כִּי","because"],["בוֹ","in-Him"],["בְּגוּפוֹ","in-body"],["שֹׁכֵן","dwells"],["כָּל־מְלֹא","all-fullness-of"],["הָאֱלָהוּת","???"],["וּבוֹ","and-in-Him"],["אַתֶּם","you-are"],["נִמְלָאִים","filled-was(pl)"],["׃",""]] },
  { num:"י", words:[["אֲשֶׁר","whose"],["הוּא","it-is"],["רֹאשׁ","head-of"],["כָּל־שְׂרָרָה","all-authority"],["וְשָׁלְטָן","and-dominion"],["׃",""]] },
  { num:"יא", words:[["וּבוֹ","and-in-Him"],["גַם־נִמַּלְתֶּם","also-you will be circumcised"],["מִילָה","Mil"],["שֶׁלּא","that-there-should-be-no"],["בְיָדָיִם","in-both hands"],["בְּהַפְשָׁטַת","???"],["גּוּף","body-of"],["הַבָּשָׂר","the-flesh"],["הַחוֹטֵא","the-sinner"],["הִיא","it-is"],["מִילַת","???"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"יב", words:[["כִּי","because"],["נִקְבַּרְתֶּם","we-will-buried(you-pl)"],["אִתּוֹ","with-him"],["בַּטְּבִילָה","in-baptism"],["אַף־קַמְתֶּם","yea-you have risen up"],["אִתּוֹ","with-him"],["בַּתְּחִיָּה","in-the-resurrection"],["עַל־יְדֵי","by-means-of"],["הָאֱמוּנָה","the-faith"],["בִּגְבוּרַת","by-the-power-of"],["אֱלֹהִים","God"],["אֲשֶׁר","whose"],["הֱעִירוֹ","arouse"],["מִן־הַמֵּתִים","from-the-dead"],["׃",""]] },
  { num:"יג", words:[["גַּם־אֶתְכֶם","also-you"],["הַמֵּתִים","the-dead"],["בַּפְּשָׁעִים","in-the-transgressions"],["וּבְעָרְלַת","and-in-the foreskin of"],["בְּשַׂרְכֶם","flesh-your"],["הֶחֱיָה","the-lived"],["אִתּוֹ","with-him"],["בִּסְלֹחַ","in-to forgive"],["לָכֶם","to-you"],["אֶת־כָּל־פִּשְׁעֵיכֶם","[ACC]-all-your-crimes"],["׃",""]] },
  { num:"יד", words:[["וַיִּמְחַק","???"],["אֶת־הַשְּׁטָר","???"],["הַמֵּעִיד","which-bears-record-of"],["בָּנוּ","in-us"],["בְּחֻקֹּתָיו","in-statutes-its"],["וַיִּשָׂאֵהוּ","and-they took-it"],["מִתּוֹכֵנוּ","???"],["וַיִּתְקָעֵהוּ","and-it blew-it"],["בַּצְּלוּב","in-the-crucified"],["׃",""]] },
  { num:"טו", words:[["וַיַּפְשֵׁט","and-he stripped off"],["אֶת־הַשָׂרִים","[ACC]-the-officials"],["וְהַשַּׁלִּיטִים","and-was the-ruler(pl)"],["וַיִּתְּנֵם","and-he-shall-give-them"],["לְרַאֲוָה","to-look"],["בָּם","in-them"],["רַבִּים","many"],["וַיּוֹלִיכֵם","and-leads-them-away"],["בּוֹ","against-him"],["שֶׁבִי","that-against-Me"],["׃",""]] },
  { num:"טז", words:[["עַל־כֵּן","therefore"],["לֹא־יָדִין","not-he will judge"],["אִישׁ","man-of"],["אֶתְכֶם","you"],["עַל־דְּבַר","upon-the-word-of"],["מַאֲכָל","food"],["וּמַשְׁקֶה","and-drink"],["אוֹ־עַל","or-upon"],["מוֹעֲדִים","times"],["וְרָאשֵׁי","and-the-heads-of"],["חֳדָשִׁים","months"],["וְשַׁבָּתוֹת","and-sabbaths"],["׃",""]] },
  { num:"יז", words:[["אֲשֶׁר","whose"],["הֵם","they"],["צֵל","is-a-shadow-of"],["הַדְּבָרִים","the-things"],["הָעֲתִידִים","the-to-come"],["לָבֹא","to-come-forth"],["וְגוּפָם","and-their-body"],["הוּא","it-is"],["בַמָּשִׁיחַ","in-anointed"],["׃",""]] },
  { num:"יח", words:[["אַל־תִּתְּנוּ","do-not-you-should-render"],["לְאִישׁ","for-a-man"],["לְהַאֲבִיד","to-destroy"],["שְׂכַרְכֶם","reward-you"],["עַל־יְדֵי","by-means-of"],["שִׁפְלוּת","the-depths-of"],["רוּחַ","spirit-of"],["וַעֲבוֹדַת","and-worship-of"],["מַלְאָכִים","angels"],["וְהוּא","and-it"],["מְהַלֵּךְ","walking about"],["בִּדְבָרִים","with-things"],["אֲשֶׁר","whose"],["לֹא","not"],["רָאוּ","saw"],["עֵינָיו","their-eyes"],["וּמָלֵא","and-full"],["רוּחַ","spirit-of"],["גַּאֲוָה","pride"],["עַל־לֹא־דָבָר","upon-not-[thing]"],["מִשֵׂכֶל","from-insight"],["בְּשָׂרוֹ","his-skin"],["׃",""]] },
  { num:"יט", words:[["וְאֵינֶנּוּ","and-it-is-not"],["אֹחֵז","one who holds"],["בָּרֹאשׁ","in-the-head-of"],["אֲשֶׁר","whose"],["מִמֶּנּוּ","from-him"],["כָּל־הַגּוּף","all-the-body"],["הַמְחֻבָּר","the-from-companion"],["וְהַמָּאֳחָז","???"],["בְּצִירָיו","the grape harvest of-his"],["וּדְבָקָיו","and-he cleaves-his"],["יִגְדַּל","shall-grow"],["גִּדּוּל","great"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"כ", words:[["לָכֵן","therefore"],["אִם־מַתֶּם","[compound]-men"],["עִם־הַמָּשִׁיחַ","with-the-Messiah"],["לְתִקּוּנֵי","???"],["הָעוֹלָם","the-world"],["לָמָּה","why"],["תִשְׁתַּעְבְּדוּ","???"],["לְחֻקִּים","and-statutes"],["כְּאִלּוּ","as-though"],["עֹדְכֶם","ever-you(pl)"],["חַיִּים","living"],["בָּעוֹלָם","of-the-world"],["׃",""]] },
  { num:"כא", words:[["אַל־תֹּאחֵז","do-not-she took hold"],["אַל־תִּטְעַם","???"],["אַל־תִּגָּע","touch-not"],["׃",""]] },
  { num:"כב", words:[["וְהֵם","and-they"],["עֹמְדִים","standing"],["לִכְלוֹת","the-end-of"],["בְּתַשְׁמִישָׁם","???"],["לְפִי","according-to"],["מִצְוֹת","commandments-of"],["אֲנָשִׁים","men"],["וְלִמּוּדֵיהֶם","and-who were trained of-them"],["׃",""]] },
  { num:"כג", words:[["הַנִּרְאִים","the-visible"],["כְּעֵין","was like-the appearance of"],["חָכְמָה","wisdom"],["בַּעֲבוֹדָה","in-the-labor/work"],["בְדוּיָה","in-the illness of"],["מִלֵּב","from-the heart"],["וּבְשִׁפְלוּת","and-in-lowering of"],["רוּחַ","spirit-of"],["וּבְעִנּוּי","and-in-a-never-ending-torment"],["הַגּוּף","the-body"],["שֶׁאֵין","whom-not"],["בּוֹ","against-him"],["מוֹעִיל","worth"],["רַק־לְהַשְׂבִּיעַ","only-to-satisfy"],["הַבָּשָׂר","the-flesh"],["׃",""]] },
];
renderVerseSet(jstcol_ch1Verses, 'jstcol-ch1-verses');

})();
