// jst_verses/jstdeu.js — Deuteronomy (JST) verse data
(function() {
var jstdeu_ch1Verses = [
  { num:"א", words:[["בָּעֵת","at-the-time"],["הַהִוא","that"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["אֵלַי","to-me"],["פְּסׇל־לְךָ","carved image-for-you"],["שְׁנֵי־לוּחֹת","two-plates-of"],["אֲבָנִים","stones"],["כָּרִאשֹׁנִים","like the-former tablets"],["וַעֲלֵה","and-go-up"],["אֵלַי","to-me"],["הָהָרָה","to-the-mountain"],["וְעָשִׂיתָ","and-do"],["לְּךָ","have-you"],["אֲרוֹן","an ark of"],["עֵץ","a-tree"],["׃",""]] },
  { num:"ב", words:[["וְאֶכְתֹּב","and-I-write"],["עַל־הַלֻּחֹת","upon-the-plates"],["אֶת־הַדְּבָרִים","[ACC]-the-words"],["אֲשֶׁר","whose"],["הָיוּ","were"],["עַל־הַלֻּחֹת","upon-the-plates"],["הָרִאשֹׁנִים","his-first"],["אֲשֶׁר","whose"],["שִׁבַּרְתָּ","you shattered"],["וְשַׂמְתָּם","and-you will appoint-them"],["בָּאָרוֹן","in the-coffin"],["׃",""]] },
  { num:"ג", words:[["וָאַעַשׂ","and-I-caused"],["אֲרוֹן","an ark of"],["עֲצֵי","the-trees-of"],["שִׁטִּים","acacia"],["וָאֶפְסֹל","and-I cut out"],["שְׁנֵי־לֻחֹת","two-tablets"],["אֲבָנִים","stones"],["כָּרִאשֹׁנִים","like the-former tablets"],["וָאַעַל","and-ascended-I"],["הָהָרָה","to-the-mountain"],["וּשְׁנֵי","and-the-two"],["הַלֻּחֹת","the-plates"],["בְּיָדִי","by-my-hand"],["׃",""]] },
  { num:"ד", words:[["וַיִּכְתֹּב","and-he-wrote"],["עַל־הַלֻּחֹת","upon-the-plates"],["כַּמִּכְתָּב","like the-writing"],["הָרִאשׁוֹן","the-first"],["אֵת","[ACC]"],["עֲשֶׂרֶת","ten"],["הַדְּבָרִים","the-things"],["אֲשֶׁר","whose"],["דִּבֶּר","spoke"],["יְהֹוָה","the-LORD"],["אֲלֵיכֶם","unto-you"],["בָּהָר","in-mountain"],["מִתּוֹךְ","from-midst-of"],["הָאֵשׁ","the-flames"],["בְּיוֹם","in-day-of"],["הַקָּהָל","the-multitude"],["וַיִּתְּנֵם","and-he-shall-give-them"],["יְהֹוָה","the-LORD"],["אֵלָי","unto-me"],["׃",""]] },
  { num:"ה", words:[["וָאֵפֶן","and-I turned"],["וָאֵרֵד","and-I have come down"],["מִן־הָהָר","from-the-mountain"],["וָאָשִׂם","and-I put"],["אֶת־הַלֻּחֹת","[ACC]-the-plates"],["בָּאָרוֹן","in the-coffin"],["אֲשֶׁר","whose"],["עָשִׂיתִי","I-made"],["וַיִּהְיוּ","and-they-were"],["שָׁם","there-is"],["כַּאֲשֶׁר","when/as"],["צִוַּנִי","commanded-me"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ו", words:[["וּבְנֵי","and-sons-of"],["יִשְׂרָאֵל","Israel"],["נָסְעוּ","did-they-progress"],["מִבְּאֵרֹת","from-Beeroth"],["בְּנֵי־יַעֲקָן","sons-of-jaakan"],["מוֹסֵרָה","Moserah"],["שָׁם","there-is"],["מֵת","is-dead"],["אַהֲרֹן","Aaron"],["וַיִּקָּבֵר","and-was-buried"],["שָׁם","there-is"],["וַיְכַהֵן","and-he served as priest"],["אֶלְעָזָר","Eleazar"],["בְּנוֹ","his-son"],["תַּחְתָּיו","in-his-stead"],["׃",""]] },
  { num:"ז", words:[["מִשָּׁם","from-there"],["נָסְעוּ","did-they-progress"],["הַגֻּדְגֹּדָה","Gudgodah-towards"],["וּמִן־הַגֻּדְגֹּדָה","and-from-Gudgodah-towards"],["יׇטְבָתָה","Jotbathah"],["אֶרֶץ","land-of"],["נַחֲלֵי","a-river-of-my"],["מָיִם","water"],["׃",""]] },
  { num:"ח", words:[["בָּעֵת","at-the-time"],["הַהִוא","that"],["הִבְדִּיל","divides"],["יְהֹוָה","the-LORD"],["אֶת־שֵׁבֶט","[ACC]-the-rod-of"],["הַלֵּוִי","the-Levite"],["לָשֵׂאת","to-bear"],["אֶת־אֲרוֹן","[ACC]-an ark of"],["בְּרִית־יְהֹוָה","covenant-of-the-LORD"],["לַעֲמֹד","to-stand"],["לִפְנֵי","before"],["יְהֹוָה","the-LORD"],["לְשָׁרְתוֹ","to-ministered-his"],["וּלְבָרֵךְ","and-to-bless"],["בִּשְׁמוֹ","in-His-name"],["עַד","until"],["הַיּוֹם","the-day"],["הַזֶּה","this"],["׃",""]] },
  { num:"ט", words:[["עַל־כֵּן","therefore"],["לֹא־הָיָה","not-was"],["לְלֵוִי","to-Levi"],["חֵלֶק","part"],["וְנַחֲלָה","and-inheritance"],["עִם־אֶחָיו","with-his-elder"],["יְהֹוָה","the-LORD"],["הוּא","it-is"],["נַחֲלָתוֹ","inheritance-of-his"],["כַּאֲשֶׁר","when/as"],["דִּבֶּר","spoke"],["יְהֹוָה","the-LORD"],["אֱלֹהֶיךָ","your-God"],["לוֹ","him"],["׃",""]] },
  { num:"י", words:[["וְאָנֹכִי","yet-I"],["עָמַדְתִּי","I-stood"],["בָהָר","on the-mountain"],["כַּיָּמִים","like the-days"],["הָרִאשֹׁנִים","his-first"],["אַרְבָּעִים","forty"],["יוֹם","day"],["וְאַרְבָּעִים","and-forty"],["לָיְלָה","night"],["וַיִּשְׁמַע","and-he-obeyed"],["יְהֹוָה","the-LORD"],["אֵלַי","to-me"],["גַּם","also"],["בַּפַּעַם","for-the-time"],["הַהִוא","that"],["לֹא־אָבָה","not-was-willing"],["יְהֹוָה","the-LORD"],["הַשְׁחִיתֶךָ","to destroy-you"],["׃",""]] },
  { num:"יא", words:[["וַיֹּאמֶר","and-said"],["יְהֹוָה","the-LORD"],["אֵלַי","to-me"],["קוּם","arise"],["לֵךְ","go"],["לְמַסַּע","to-journeying"],["לִפְנֵי","before"],["הָעָם","the-people"],["וְיָבֹאוּ","and-shall-come"],["וְיִירְשׁוּ","and-they-possess"],["אֶת־הָאָרֶץ","[ACC]-the-earth"],["אֲשֶׁר־נִשְׁבַּעְתִּי","whose-I-made"],["לַאֲבֹתָם","to-ancestors-their"],["לָתֵת","to-give"],["לָהֶם","to-them"],["׃",""]] },
  { num:"יב", words:[["וְעַתָּה","and-now"],["יִשְׂרָאֵל","Israel"],["מָה","what"],["יְהֹוָה","the-LORD"],["אֱלֹהֶיךָ","your-God"],["שֹׁאֵל","ask"],["מֵעִמָּךְ","from-with-you"],["כִּי","because"],["אִם־לְיִרְאָה","[compound]-to-He-shall-manifest-Himself"],["אֶת־יְהֹוָה","[ACC]-the-LORD"],["אֱלֹהֶיךָ","your-God"],["לָלֶכֶת","to-go"],["בְּכׇל־דְּרָכָיו","in-all-His-ways"],["וּלְאַהֲבָה","and-to-love"],["אֹתוֹ","him"],["וְלַעֲבֹד","and-to-work"],["אֶת־יְהֹוָה","[ACC]-the-LORD"],["אֱלֹהֶיךָ","your-God"],["בְּכׇל־לְבָבְךָ","in-all-heart-your"],["וּבְכׇל־נַפְשֶׁךָ","and-in-all-your-soul"],["׃",""]] },
  { num:"יג", words:[["לִשְׁמֹר","in-keeping"],["אֶת־מִצְוֺת","[ACC]-the-commandments-of"],["יְהֹוָה","the-LORD"],["וְאֶת־חֻקֹּתָיו","and-[ACC]-statutes-its"],["אֲשֶׁר","whose"],["אָנֹכִי","I"],["מְצַוְּךָ","am commanding-you"],["הַיּוֹם","the-day"],["לְטוֹב","for-good"],["לָךְ","[compound]"],["׃",""]] },
  { num:"יד", words:[["הֵן","yea"],["לַיהֹוָה","to-Yahweh"],["אֱלֹהֶיךָ","your-God"],["הַשָּׁמַיִם","the-heavens"],["וּשְׁמֵי","and-the heavens of"],["הַשָּׁמָיִם","the-heavens"],["הָאָרֶץ","the-earth"],["וְכׇל־אֲשֶׁר־בָּהּ","and-all-whose-in-it(f)"],["׃",""]] },
  { num:"טו", words:[["רַק","only"],["בַּאֲבֹתֶיךָ","ancestors-your"],["חָשַׁק","he loved"],["יְהֹוָה","the-LORD"],["לְאַהֲבָה","to-love"],["אוֹתָם","them"],["וַיִּבְחַר","and-chose"],["בְּזַרְעָם","with-their-seed"],["אַחֲרֵיהֶם","after-them"],["בָּכֶם","in-you"],["מִכׇּל־הָעַמִּים","from-all-the-people"],["כַּיּוֹם","at-this-day"],["הַזֶּה","this"],["׃",""]] },
  { num:"טז", words:[["וּמַלְתֶּם","and-you will circumcise"],["אֵת","[ACC]"],["עׇרְלַת","the foreskin of"],["לְבַבְכֶם","your-hearts"],["וְעׇרְפְּכֶם","and-neck-your"],["לֹא","not"],["תַקְשׁוּ","you-harden"],["עוֹד","any-more"],["׃",""]] },
  { num:"יז", words:[["כִּי","because"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיכֶם","your-God"],["הוּא","it-is"],["אֱלֹהֵי","God-of"],["הָאֱלֹהִים","the-God"],["וַאֲדֹנֵי","and-the lord of"],["הָאֲדֹנִים","the-lords"],["הָאֵל","the-God"],["הַגָּדֹל","the-great"],["הַגִּבֹּר","mighty"],["וְהַנּוֹרָא","and-the-awesome"],["אֲשֶׁר","whose"],["לֹא־יִשָּׂא","shall-not-lift-up"],["פָנִים","man"],["וְלֹא","and-not"],["יִקַּח","take-upon-him"],["שֹׁחַד","a-bribe"],["׃",""]] },
  { num:"יח", words:[["עֹשֶׂה","do"],["מִשְׁפַּט","judgment"],["יָתוֹם","a fatherless one"],["וְאַלְמָנָה","and-a widow"],["וְאֹהֵב","and-he is loving"],["גֵּר","am a sojourner"],["לָתֶת","that-I-might"],["לוֹ","him"],["לֶחֶם","bread"],["וְשִׂמְלָה","and-garments"],["׃",""]] },
  { num:"יט", words:[["וַאֲהַבְתֶּם","and-love"],["אֶת־הַגֵּר","[ACC]-the-stranger"],["כִּי־גֵרִים","because-sojourners"],["הֱיִיתֶם","because-you-have-been"],["בְּאֶרֶץ","in-land-of"],["מִצְרָיִם","Egypt"],["׃",""]] },
  { num:"כ", words:[["אֶת־יְהֹוָה","[ACC]-the-LORD"],["אֱלֹהֶיךָ","your-God"],["תִּירָא","you fear"],["אֹתוֹ","him"],["תַעֲבֹד","you will till"],["וּבוֹ","and-in-Him"],["תִדְבָּק","you will cleave"],["וּבִשְׁמוֹ","and-in-his-name"],["תִּשָּׁבֵעַ","you will swear oaths"],["׃",""]] },
  { num:"כא", words:[["הוּא","it-is"],["תְהִלָּתְךָ","is praise-your"],["וְהוּא","and-it"],["אֱלֹהֶיךָ","your-God"],["אֲשֶׁר־עָשָׂה","which-did"],["אִתְּךָ","with-thee"],["אֶת־הַגְּדֹלֹת","[ACC]-great"],["וְאֶת־הַנּוֹרָאֹת","and-[ACC]-the-awesome deeds"],["הָאֵלֶּה","these"],["אֲשֶׁר","whose"],["רָאוּ","saw"],["עֵינֶיךָ","your-eyes"],["׃",""]] },
  { num:"כב", words:[["בְּשִׁבְעִים","seventy"],["נֶפֶשׁ","soul"],["יָרְדוּ","came-down"],["אֲבֹתֶיךָ","your-fathers"],["מִצְרָיְמָה","into-Egypt"],["וְעַתָּה","and-now"],["שָׂמְךָ","did he appoint-you"],["יְהֹוָה","the-LORD"],["אֱלֹהֶיךָ","your-God"],["כְּכוֹכְבֵי","like-the stars of"],["הַשָּׁמַיִם","the-heavens"],["לָרֹב","in-abundance"],["׃",""]] },
];
renderVerseSet(jstdeu_ch1Verses, 'jstdeu-ch1-verses');

})();
