// jst_verses/jsteph.js — Ephesians (JST) verse data
(function() {
var jsteph_ch1Verses = [
  { num:"א", words:[["עַל־כֵּן","therefore"],["אַזְהִירְכֶם","I-would-exhort-you(pl)"],["אֲנִי","I"],["הָאָסוּר","the-forbidden"],["בָּאָדוֹן","in-the-is master"],["לְהִתְהַלֵּךְ","to-walk"],["כַּאֲשֶׁר","when/as"],["יָאֲתָה","it is befitting"],["לְמִשְׁמַרְתְּכֶם","to-your-duty"],["אֲשֶׁר","whose"],["נִקְרֵאתֶם","ye-are-called"],["לָהּ","it"],["׃",""]] },
  { num:"ב", words:[["בְּכָל־נְמִיכוּת","among-all-lowness"],["וַעֲנָוָה","and-humility"],["וּבְאֹרֶךְ","and-in-he-was-long"],["רוּחַ","spirit-of"],["לָשֵׂאת","to-bear"],["אִישׁ","man-of"],["אֶת־רֵעֵהוּ","[ACC]-another"],["בְּאַהֲבָה","and-in-love"],["׃",""]] },
  { num:"ג", words:[["וְשִׁקְדוּ","and-watch"],["לִשְׁמֹר","in-keeping"],["אֶת־אַחֲדוּת","[ACC]-one"],["הָרוּחַ","the-Spirit"],["בַּאֲגֻדַּת","in-the-a bunch of"],["הַשָּׁלוֹם","peace"],["׃",""]] },
  { num:"ד", words:[["גּוּף","body-of"],["אֶחָד","one"],["וְרוּחַ","and-spirit-of"],["אֶחָד","one"],["כַּאֲשֶׁר","when/as"],["גַּם־נִקְרֵאתֶם","also-ye-are-called"],["בְּתִקְוַת","in-a-hope-of"],["מִשְׁמַרְתְּכֶם","your-duty"],["הָאֶחָת","one"],["׃",""]] },
  { num:"ה", words:[["אָדוֹן","is master"],["אֶחָד","one"],["אֱמוּנָה","faith"],["אַחַת","one"],["טְבִילָה","baptism"],["אֶחָת","one"],["׃",""]] },
  { num:"ו", words:[["אֵל","God"],["וְאָב","and-a parent"],["אֶחָד","one"],["לַכֹּל","to-all"],["שֶׁהוּא","that-He-is"],["עַל־כֹּל","upon-all"],["וְאֶת־כֹּל","and-[ACC]-all"],["וּבְתוֹךְ","and-within"],["כֹּל","all"],["׃",""]] },
  { num:"ז", words:[["אֲבָל","but/however"],["לְכָל־אֶחָד","to-each-one"],["וְאֶחָד","and-one"],["מִמֶּנּוּ","from-him"],["נִתַּן","was-given"],["הֶחָסֶד","the-covenant loyalty"],["כְּמִדַּת","as-measure-of"],["מַתְּנַת","gift-of"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"ח", words:[["עַל־כֵּן","therefore"],["הוּא","it-is"],["אוֹמֵר","say"],["עָלָה","ascended"],["לַמָּרוֹם","on-high"],["שָׁבָה","she-returned"],["שֶׁבִי","that-against-Me"],["וַיִּתֵּן","and-gave"],["מַתָּנוֹת","gifts"],["לָאָדָם","for-man"],["׃",""]] },
  { num:"ט", words:[["וְעָלָה","and-he-shall-come-up"],["שֶׁאָמַר","that-said"],["מַה־הוּא","what-he/it"],["אִם־לֹא","if-not"],["שֶׁיָּרַד","that-is running down"],["מִקֹּדֶם","before"],["לְתַחְתִּיּוֹת","to-the lower parts of"],["אָרֶץ","the-earth"],["׃",""]] },
  { num:"י", words:[["הוּא","it-is"],["הַיֹּרֵד","which-was coming down"],["וְהוּא","and-it"],["הָעֹלֶה","which-goes up"],["לְמַעְלָה","upward"],["מִכָּל־הַשָּׁמָיִם","above-all-the-heavens"],["לְמַעַן","in-order-that"],["יְמַלֵּא","should-fill"],["אֶת־הַכֹּל","[ACC]-all"],["׃",""]] },
  { num:"יא", words:[["וְהוּא","and-it"],["נָתַן","was-given"],["אֶת־אֵלֶּה","[ACC]-these"],["שְׁלִיחִים","apostles"],["וְאֶת־אֵלֶּה","and-[ACC]-these"],["נְבִיאִים","prophets"],["וְאֶת־אֵלֶּה","and-[ACC]-these"],["מְבַשְׂרִים","from-the-songs"],["וְאֶת־אֵלֶּה","and-[ACC]-these"],["רֹעִים","pasturing"],["וּמְלַמְּדִים","and-teaching"],["׃",""]] },
  { num:"יב", words:[["לְהַשְׁלִים","to-fulfill"],["אֶת־הַקְּדשִׁים","[ACC]-the-holy-things"],["לְמַעֲשֵׂה","unto-the-work-of"],["הָעֲבוֹדָה","the-ministry"],["לְבִנְיַן","to-the-building-of"],["גּוּף","body-of"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"יג", words:[["עַד","until"],["כִּי־נַגִּיעַ","???"],["כֻּלָּנוּ","us-all"],["לְאַחֲדוּת","to-one"],["הָאֱמוּנָה","the-faith"],["וְדַעַת","and-knowledge"],["בֶּן־הָאֱלֹהִים","Son-of-God"],["כְּאִישׁ","as-a-man"],["אֶחָד","one"],["שָׁלֵם","Shelem"],["לְשִׁעוּר","to-barley"],["קוֹמַת","the height of"],["מְלוֹא","the-fullness-of"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"יד", words:[["וְלֹא־נִהְיֶה","and-not-let-us-be"],["עוֹד","any-more"],["יְלָדִים","little-children"],["נִגְרָשִׁים","we-will-inverted commas"],["וְנִדָּפִים","and-driven"],["בְּכָל־רוּחַ","in-all-spirit-of"],["הַלִּמּוּד","the-study"],["בְּתַרְמִית","in-the deceitfulness of"],["בְּנֵי","sons-of"],["אָדָם","man"],["וּמֹקְשׁוֹתָם","and-the snares of-their"],["אֲשֶׁר","whose"],["שָׁתוּ","they-have-drunk"],["לְהַתְעוֹת","to-he-did-lead-away(pl.f)"],["׃",""]] },
  { num:"טו", words:[["כִּי","because"],["אִם־נְדַבֵּר","[compound]-speak"],["הָאֱמֶת","the-true"],["בְּאַהֲבָה","and-in-love"],["וְנִגְדְּלָה","and-we-magnified"],["בְכָל־דָּבָר","with-all-things"],["לוֹ","him"],["לַמָּשִׁיחַ","unto-the-Messiah"],["אֲשֶׁר","whose"],["הוּא","it-is"],["הָרֹאשׁ","the-head"],["׃",""]] },
  { num:"טז", words:[["אֲשֶׁר","whose"],["מִמֶּנּוּ","from-him"],["כָּל־הַגּוּף","all-the-body"],["הַמֻּרְכָּב","saddle"],["וּמְדֻבָּק","and-has been made to cling to"],["בְּכָל־חִבּוּר","in-all-communion"],["הַשִּׁמּוּשׁ","the-use"],["כְּמִדַּת","as-measure-of"],["הַכֹּחַ","the-power"],["הַנָּתוּן","the-given"],["לְכָל־אֵבָר","to-all-wings"],["וְאֵבָר","and-limb"],["יִרְבֶּה","it should increase"],["וְיִגְדַּל","and-it may be great"],["לְהַשְׁלָמַת","to-the-the retribution of"],["בִּנְיָנוֹ","our-sons"],["בְּאַהֲבָה","and-in-love"],["׃",""]] },
  { num:"יז", words:[["וְהִנֵּה","and-behold"],["זֹאת","this"],["אֲנִי","I"],["אֹמֵר","say"],["וּמֵעִיד","and-testifying"],["בָּאָדוֹן","in-the-is master"],["כִּי","because"],["מֵעַתָּה","from-this-time"],["לֹא־תֵלְכוּ","not-go"],["עוֹד","any-more"],["כְּיֶתֶר","as-the-remainder-of"],["הַגּוֹיִם","the-nations"],["הַהֹלְכִים","the-ones-walking"],["בְּהַבְלֵי","in-the-things-of"],["שִׂכְלָם","that-all of-them"],["׃",""]] },
  { num:"יח", words:[["חֲשֻׁכֵי","darkness-my"],["הַדַּעַת","the-knowledge"],["וּמוּזָרִים","and-Mozr(pl)"],["לְחַיֵּי","to-life-of"],["אֱלֹהִים","God"],["מִפְּנֵי","because-of"],["אִוַּלְתָּם","???"],["אֲשֶׁר","whose"],["בָּהֶם","in-them"],["כִּי־טַח","because-it is besmeared"],["מֵהַשְׂכִּיל","from-having insight"],["לְבָבָם","their-hearts"],["׃",""]] },
  { num:"יט", words:[["אֲשֶׁר","whose"],["הִשְׁמִינוּ","they-grew-fat"],["וַיִּתְּנוּ","and-they-gave"],["אֶת־נַפְשָׁם","[ACC]-their-souls"],["לַזִּמָּה","to-the-licentiousness"],["לַעֲשׂוֹת","to-do"],["כָּל־תּוֹעֵבָה","all-abomination"],["לִבְצֹעַ","to-gain"],["בָּצַע","unjust gain"],["׃",""]] },
  { num:"כ", words:[["וְאַתֶּם","and-will-you"],["לֹא","not"],["כֵן","thus"],["לְמַדְתֶּם","you-have-studied"],["אֶת־הַמָּשִׁיחַ","[ACC]-the-Messiah"],["׃",""]] },
  { num:"כא", words:[["אִם־אָמְנָם","[compound]-truly"],["שְׁמַעְתֶּם","you-have-heard"],["אֹתוֹ","him"],["וּבוֹ","and-in-Him"],["לֻמַּדְתֶּם","have-been-taught"],["כְּפִי","according-to"],["הָאֱמֶת","the-true"],["אֲשֶׁר","whose"],["בְּיֵשׁוּעַ","in-Jesus"],["׃",""]] },
  { num:"כב", words:[["לָסוּר","changed-from"],["מִדַּרְכֵיכֶם","from-your-ways"],["הָרִאשֹׁנִים","his-first"],["וְלִפְשֹׁט","and-to-strip"],["אֶת־הָאָדָם","[ACC]-man"],["הַיָּשָׁן","the-old harvest"],["הַנִּשְׁחָת","the-had-become-corrupt"],["בְּתַאֲוֹת","in-chambers"],["רְמִיָּה","deceit"],["׃",""]] },
  { num:"כג", words:[["לְהִתְחַדֵּשׁ","to-you may renew"],["בְּרוּחַ","in-the-Spirit"],["שִׂכְלְכֶם","your-understanding"],["׃",""]] },
  { num:"כד", words:[["וְלִלְבּשׁ","and-to-wear"],["אֶת־הָאָדָם","[ACC]-man"],["הֶחָדָשׁ","new"],["הַנִּבְרָא","the-was-created"],["כִּדְמוּת","in-the-likeness-of"],["אֱלֹהִים","God"],["בִּצְדָקָה","in-righteousness"],["וּקְדֻשַּׁת","and-holiness-of"],["הָאֱמֶת","the-true"],["׃",""]] },
  { num:"כה", words:[["עַל־כֵּן","therefore"],["הָסִירוּ","remove"],["מִכֶּם","from-you"],["אֶת־הַשֶּׁקֶר","[ACC]-the-falsehood"],["וְדַבְּרוּ","and-His-word"],["אֱמֶת","truth"],["אִישׁ","man-of"],["אֶת־רֵעֵהוּ","[ACC]-another"],["כִּי","because"],["אֵבָרִים","mighty horses"],["אֲנַחְנוּ","we"],["אִישׁ","man-of"],["לְאָחִיו","of-his-brother"],["׃",""]] },
  { num:"כו", words:[["רִגְזוּ","tremble"],["וְאַל־תֶּחֱטָאוּ","and-do-not-you sin"],["וְלֹא","and-not"],["תָבֹא","come"],["הַשֶּׁמֶשׁ","the-sun"],["עַל־רָגְזְכֶם","super- (superhuman, supernatural)-to become angry-your(pl)"],["׃",""]] },
  { num:"כז", words:[["וְאַל־תִּתְּנוּ","and-do-not-you-will-administer"],["מָקוֹם","a-place"],["לַשָׂטָן","to-the-adversary"],["׃",""]] },
  { num:"כח", words:[["מִי","who"],["שֶׁגָּנַב","that-stole"],["אַל־יֹסֶף","do-not-may he add"],["לִגְנֹב","to-steal"],["כִּי","because"],["אִם־יִיגַע","[compound]-he becomes weary"],["וּבְיָדָיו","and-by-hands-his"],["יַעֲשֶׂה","he-shall-do"],["אֶת־הַטּוֹב","[ACC]-that-which-is-good"],["לְמַעַן","in-order-that"],["יִהְיֶה־לּוֹ","he-shall-be-upon-him"],["לָתֵת","to-give"],["לְאִישׁ","for-a-man"],["מַחְסוֹר","lack"],["׃",""]] },
  { num:"כט", words:[["וְלֹא־יֵצֵא","and-not-he-go-forth"],["מִפִּיכֶם","from-mouth-your"],["כָּל־דְּבַר","all-word-of"],["נִבּוּל","vulgarity"],["כִּי","because"],["אִם־הַטּוֹב","[compound]-good"],["וְהַמּוֹעִיל","and-which-is-expedient"],["לִבְנוֹת","white"],["לְפִי","according-to"],["הַצֹּרֶךְ","the-need"],["לְמַעַן","in-order-that"],["יִתֵּן","shall-give"],["חֵן","favor"],["לְשֹׁמְעָיו","to-my-hearing-his"],["׃",""]] },
  { num:"ל", words:[["וְלֹא","and-not"],["תְעַצְּבוּ","you be grieved"],["אֶת־רוּחַ","[ACC]-the-Spirit-of"],["הַקֹּדֶשׁ","the-Holy"],["שֶׁל־אֱלֹהִים","of-God"],["אֲשֶׁר","whose"],["נֶחְתַּמְתֶּם","???"],["בּוֹ","against-him"],["לְיוֹם","to-day"],["הַגְּאֻלָּה","redemption"],["׃",""]] },
  { num:"לא", words:[["כָּל־מְרִירוּת","all-bitterness"],["וְחֵמָה","and-wrath"],["וָרֹגֶז","and-turmoil"],["וּצְעָקָה","and-a-cry"],["וְגִדּוּף","and-vilification"],["תָּסִירוּ","you will remove(they)"],["מִכֶּם","from-you"],["עִם","with"],["כָּל־הָרִשְׁעָה","all-wickedness"],["׃",""]] },
  { num:"לב", words:[["וִהְיוּ","and-be"],["טוֹבִים","good"],["אִישׁ","man-of"],["לְרֵעֵהוּ","another"],["וְרַחֲמָנִים","and-merciful"],["וְנֹשְׂאִים","and-you are lifting up"],["אִישׁ","man-of"],["לְחַטַּאת","the sin of"],["אָחִיו","another"],["כַּאֲשֶׁר","when/as"],["נָשָׂא","bore"],["לָכֶם","to-you"],["הָאֱלֹהִים","the-God"],["בַּמָּשִׁיחַ","in-the-Messiah"],["׃",""]] },
];
renderVerseSet(jsteph_ch1Verses, 'jsteph-ch1-verses');

})();
