// jst_verses/jstgal.js — Galatians (JST) verse data
(function() {
var jstgal_ch1Verses = [
  { num:"א", words:[["אֲהָהּ","alas!"],["גָּלָטִים","???"],["חַסְרֵי","lacking-in"],["דָעַת","knowledge"],["מִי","who"],["הִתְעָה","he-did-lead-away"],["אֶתְכֶם","you"],["בִּכְשָׁפָיו","???"],["לְבִלְתִּי","to-not"],["שְׁמֹעַ","hears"],["אֶל־הָאֱמֶת","to-the-true"],["אַחֲרֵי","after"],["אֲשֶׁר","whose"],["צֻיַּר","betake oneself"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["הַצָּלוּב","the-crucified"],["לְנֶגֶד","before"],["עֵינֵיכֶם","your-eyes"],["׃",""]] },
  { num:"ב", words:[["רַק","only"],["זֹאת","this"],["אֶחְפֹּץ","I-will"],["לִלְמֹד","to-be-learned"],["מִכֶּם","from-you"],["הַאִם","the-if"],["מִמַּעֲשֵׂי","of-the-proceedings-of"],["הַתּוֹרָה","the-law"],["קִבַּלְתֶּם","received"],["אֶת־הָרוּחַ","[ACC]-the-spirit"],["אוֹ","or"],["מִשְּׁמוּעַת","???"],["הָאֱמוּנָה","the-faith"],["׃",""]] },
  { num:"ג", words:[["הַסְכָלִים","the-fools"],["אַתֶּם","you-are"],["כָּל־כָּךְ","all-so"],["הַחִלּוֹתֶם","you-are-beginning"],["בָּרוּחַ","in-the-Spirit"],["וְעַתָּה","and-now"],["תְּכַלּוּ","may you put an end to(they)"],["בַבָּשָׂר","in-the-flesh"],["׃",""]] },
  { num:"ד", words:[["הֲכָזֹאת","???"],["נַעֲנֵיתֶם","???"],["לָרִיק","to-emptiness"],["אִם־אָמְנָם","[compound]-truly"],["לָרִיק","to-emptiness"],["׃",""]] },
  { num:"ה", words:[["הִנֵּה","behold"],["הַמֵּפִיק","???"],["לָכֶם","to-you"],["אֶת־הָרוּחַ","[ACC]-the-spirit"],["וּפֹעֵל","and-one who does"],["בָּכֶם","in-you"],["גְּבוּרוֹת","mighty"],["הֲמִכֹּחַ","???"],["מַעֲשֵׂי","works-of"],["הַתּוֹרָה","the-law"],["הוּא","it-is"],["עֹשֶׂה","do"],["אֵלֶּה","these"],["אוֹ","or"],["מִכֹּחַ","than-the-strength-of"],["שְׁמוּעַת","???"],["הָאֱמוּנָה","the-faith"],["׃",""]] },
  { num:"ו", words:[["כַּאֲשֶׁר","when/as"],["הֶאֱמִין","believed"],["אַבְרָהָם","Abraham"],["בֵּאלֹהִים","in-God"],["וַתֵּחָשֶׁב","and-it was reckoned"],["לוֹ","him"],["לִצְדָקָה","for-righteousness"],["׃",""]] },
  { num:"ז", words:[["דְּעוּ","know!(pl)"],["אֵפוֹא","Fo"],["כִּי־בְנֵי","because-sons-of"],["הָאֱמוּנָה","the-faith"],["בְּנֵי","sons-of"],["אַבְרָהָם","Abraham"],["הֵמָּה","they-are"],["׃",""]] },
  { num:"ח", words:[["וְהַכָּתוּב","and-which-is-written"],["צָפָה","inundation"],["שֶׁעָתִיד","that-future"],["הָאֱלֹהִים","the-God"],["לְהַצְדִּיק","to-excuse"],["אֶת־הַגּוֹיִם","[ACC]-the-nations"],["מִתּוֹךְ","from-midst-of"],["הָאֱמוּנָה","the-faith"],["וְקִדֵּם","and-front"],["לְבַשֵׂר","according-to-the-flesh"],["אֶת־אַבְרָהָם","[ACC]-with-Abraham"],["לֵאמֹר","saying"],["וְנִבְרְכוּ","and-they-were-blessed"],["בְךָ","in-You"],["כָּל־הַגּוֹיִם","all-the-nations"],["׃",""]] },
  { num:"ט", words:[["עַל־כֵּן","therefore"],["יִתְבָּרֲכוּ","blessed-shall-be"],["בְּנֵי","sons-of"],["הָאֱמוּנָה","the-faith"],["עִם־אַבְרָהָם","with-Abraham"],["הַמַּאֲמִין","the-one-believing"],["׃",""]] },
  { num:"י", words:[["כִּי","because"],["בְנֵי","sons-of"],["מַעֲשֵׂי","works-of"],["הַתּוֹרָה","the-law"],["עֲלֵיהֶם","against-them"],["הַקְּלָלָה","the-curse"],["כִּי","because"],["כָתוּב","written"],["אָרוּר","cursed-is"],["אֲשֶׁר","whose"],["לֹא־יָקִים","not-shall-raise-up"],["אֶת־כָּל־הַדְּבָרִים","[ACC] all-the-things"],["הַכְּתוּבִים","the-scriptures"],["בְּסֵפֶר","in-a-book"],["הַתּוֹרָה","the-law"],["לַעֲשׂוֹת","to-do"],["אוֹתָם","them"],["׃",""]] },
  { num:"יא", words:[["וְגָלוּי","and-who is uncovered of"],["וְיָדוּעַ","and-known"],["שֶׁבַּתּוֹרָה","that-by-the-law"],["לֹא־יִצְדַּק","no-flesh-is-justified"],["הָאָדָם","man"],["לִפְנֵי","before"],["הָאֱלֹהִים","the-God"],["כִּי־צַדִּיק","because-righteous"],["בֶּאֱמוּנָתוֹ","through-faith"],["יִחְיֶה","he-shall-live"],["׃",""]] },
  { num:"יב", words:[["וְהַתּוֹרָה","and-the-law"],["לֹא","not"],["מִן־הָאֱמוּנָה","from-the-faith"],["הִיא","it-is"],["כִּי","because"],["אִם־אֲשֶׁר־יַעֲשֶׂה","[compound]-whose-he-shall-do"],["אֹתָם","them"],["הָאָדָם","man"],["וָחַי","and-living"],["בָּהֶם","in-them"],["׃",""]] },
  { num:"יג", words:[["הַמָּשִׁיחַ","the-Messiah"],["פָּדָנוּ","???"],["מִקִּלְלַת","from-curse-of"],["הַתּוֹרָה","the-law"],["בִּהְיוֹתוֹ","being"],["לִקְלָלָה","into-a curse"],["בַּעֲדֵנוּ","in-until-us"],["כַּכָּתוּב","according-to-that-which-is-written"],["קִלְלַת","curse-of"],["אֱלֹהִים","God"],["תָּלוּי","one who is hanged"],["׃",""]] },
  { num:"יד", words:[["לְמַעַן","in-order-that"],["אֲשֶׁר","whose"],["תָּבֹא","comes"],["בִּרְכַּת","blessing-of"],["אַבְרָהָם","Abraham"],["בַּמָּשִׁיחַ","in-the-Messiah"],["יֵשׁוּעַ","Yeshua"],["עַל־הַגּוֹיִם","upon-the-nations"],["לְמַעַן","in-order-that"],["אֲשֶׁר","whose"],["נִקַּח","let-us-take"],["אֶת־הַבְטָחַת","[ACC]-the-promise-of"],["הָרוּחַ","the-Spirit"],["עַל־יְדֵי","by-means-of"],["הָאֱמוּנָה","the-faith"],["׃",""]] },
  { num:"טו", words:[["אַחַי","my-brothers"],["כְּדֶרֶךְ־אָדָם","after-manner-of-man"],["אֲנִי","I"],["מְדַבֵּר","speaks"],["אֲפִלּוּ","even/also"],["צַוָּאָה","excrement"],["שֶׁל־בֶּן־אָדָם","of-son-of-man"],["אִם־מְקֻיֶּמֶת","???"],["הִיא","it-is"],["לֹא","not"],["יְפֵרֶנָּה","???"],["אִישׁ","man-of"],["וְלֹא־יוֹסִיף","and-not-He-shall-set"],["עָלֶיהָ","upon-it"],["׃",""]] },
  { num:"טז", words:[["וְהִנֵּה","and-behold"],["לְאַבְרָהָם","unto-Abraham"],["נֶאֶמְרוּ","were-spoken"],["הַהַבְטָחוֹת","the-promises"],["וּלְזַרְעוֹ","and-for-offspring-his"],["וְלֹא־אָמַר","and-not-said"],["וְלִזְרָעֶיךָ","and-to-sow-your"],["כְּאִלּוּ","as-though"],["לָרַבִּים","by-many people"],["אֶלָּא","but-rather"],["כְּאִלּוּ","as-though"],["לְיָחִיד","to-am solitary"],["וְלְזַרְעֲךָ","and-unto-your-seed"],["וְהוּא","and-it"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"יז", words:[["וְזֹאת","and-this"],["אֲנִי","I"],["אֹמֵר","say"],["כִּי","because"],["בְּרִית","covenant-of"],["אֲשֶׁר","whose"],["קִיְּמָהּ","will be enduring"],["הָאֱלֹהִים","the-God"],["מֵאָז","since"],["לֹא","not"],["תוּכַל","can"],["הַתּוֹרָה","the-law"],["הַבָּאָה","the-coming"],["אַחֲרֵי","after"],["אַרְבַּע","four"],["מֵאוֹת","hundred"],["וּשְׁלשִׁים","and-thirty"],["שָׁנָה","years"],["לְהָפֵר","to-break"],["אוֹתָהּ","it"],["וּלְבַטֵּל","???"],["אֶת־הַהַבְטָחָה","[ACC]-the-promise"],["׃",""]] },
  { num:"יח", words:[["כִּי","because"],["אִם־הַנַּחֲלָה","[compound]-inheritance (e.g. promise)"],["מִתּוֹךְ","from-midst-of"],["הַתּוֹרָה","the-law"],["הִיא","it-is"],["אֵינֶנָּה","is-not"],["עוֹד","any-more"],["מִתּוֹךְ","from-midst-of"],["הַהַבְטָחָה","the-promise"],["וְהָאֱלֹהִים","and-the-God"],["חָנַן","was-gracious"],["אֶת־אַבְרָהָם","[ACC]-with-Abraham"],["עַל־יְדֵי","by-means-of"],["הַבְטָחָה","a-promise"],["׃",""]] },
  { num:"יט", words:[["אִם־כֵּן־הַתּוֹרָה","[compound]-thus-the-law"],["מַה־הִיא","what-it-is"],["מִפְּנֵי","because-of"],["הַפְּשָׁעִים","the-transgressions"],["נוֹסָפָה","it will be added"],["עַד","until"],["כִּי־יָבוֹא","because-shall-come"],["הַזֶּרַע","the-seed"],["אֲשֶׁר־לוֹ","whom"],["הַהַבְטָחָה","the-promise"],["וְהִיא","and-she-was"],["עֲרוּכָה","arranged"],["עַל־יְדֵי","by-means-of"],["הַמַּלְאָכִים","the-angels"],["וּבְיַד","and-by-the-hand-of"],["מְתַוֵּךְ","from-among"],["׃",""]] },
  { num:"כ", words:[["וְאֵין","and-has-no"],["מְתַוֵיךְ","???"],["לְאֶחָד","into-one"],["אֲבָל","but/however"],["הָאֱלֹהִים","the-God"],["הוּא","it-is"],["אֶחָד","one"],["׃",""]] },
  { num:"כא", words:[["וְעַתָּה","and-now"],["הַמְבַטֶּלֶת","???"],["הַתּוֹרָה","the-law"],["אֶת־הַבְטָחוֹת","[ACC]-the-promises-of"],["הָאֱלֹהִים","the-God"],["חָלִילָה","far-be-it"],["כִּי","because"],["אִלּוּ","if"],["נִתְּנָה","was-given(f)"],["תוֹרָה","Torah/law"],["שֶׁבְּכֹחָהּ","that-in-her-power"],["לְהַחֲיוֹת","to-preserve alive"],["אָז","then"],["בֶּאֱמֶת","in-truth"],["הָיְתָה","was"],["הַצְּדָקָה","the-righteousness"],["עַל־יְדֵי","by-means-of"],["הַתּוֹרָה","the-law"],["׃",""]] },
  { num:"כב", words:[["אֲבָל","but/however"],["הַכָּתוּב","which-is-written"],["הִסְגִּיר","which he has shut up"],["אֶת־הַכֹּל","[ACC]-all"],["בְּיַד","in-hand-of"],["הַחֵטְא","sin"],["לְמַעַן","in-order-that"],["תִּנָּתֵן","it will be given"],["הַהַבְטָחָה","the-promise"],["אֶל־הַמַּאֲמִינִים","to-the-believers"],["בֶּאֱמוּנַת","in-faith-of"],["יֵשׁוּעַ","Yeshua"],["הַמָּשִׁיחַ","the-Messiah"],["׃",""]] },
  { num:"כג", words:[["וְלִפְנֵי","and-before"],["בוֹא","the-coming-of"],["הָאֱמוּנָה","the-faith"],["שְׁמוּרִים","keep(pl)"],["וּסְגוּרִים","and-shut(pl)"],["הָיִינוּ","we-were"],["תַּחַת","under"],["הַתּוֹרָה","the-law"],["אֱלֵי","to"],["הָאֱמוּנָה","the-faith"],["הָעֲתִידָה","the-future"],["לְהִגָּלוֹת","to-be-revealed"],["׃",""]] },
  { num:"כד", words:[["וּבְכֵן","and-in-such"],["הַתּוֹרָה","the-law"],["הָיְתָה","was"],["אֹמֶנֶת","a nurse"],["אוֹתָנוּ","us"],["לַמָּשִׁיחַ","unto-the-Messiah"],["לְמַעַן","in-order-that"],["נִצְדַּק","it will be put right"],["בָּאֱמוּנָה","in-the-faith"],["׃",""]] },
  { num:"כה", words:[["אֲבָל","but/however"],["עַתָּה","now"],["אַחֲרֵי","after"],["אֲשֶׁר","whose"],["בָּאָה","comes"],["הָאֱמוּנָה","the-faith"],["אֵינֶנּוּ","it-is-not"],["עוֹד","any-more"],["תַּחַת","under"],["יַד","hand-of"],["הָאֹמֵן","foster-father"],["׃",""]] },
  { num:"כו", words:[["כִּי־אַתֶּם","because-you-are"],["כֻּלְּכֶם","all-you"],["בְּנֵי","sons-of"],["אֱלֹהִים","God"],["עַל־יְדֵי","by-means-of"],["הָאֱמוּנָה","the-faith"],["בַּמָּשִׁיחַ","in-the-Messiah"],["יֵשׁוּעַ","Yeshua"],["׃",""]] },
  { num:"כז", words:[["כִּי","because"],["כֻלְּכֶם","all-of-you"],["אֲשֶׁר","whose"],["לַמָּשִׁיחַ","unto-the-Messiah"],["נִטְבַּלְתֶּם","baptized(you-pl)"],["לְבַשְׁתֶּם","to-shame-their"],["אֶת־הַמָּשִׁיחַ","[ACC]-the-Messiah"],["׃",""]] },
  { num:"כח", words:[["וְאֵין","and-has-no"],["עוֹד","any-more"],["יְהוּדִי","Jew"],["וְלֹא","and-not"],["יְוָנִי","Jevanite"],["אֵין","there-is-no"],["עֶבֶד","servant-of"],["וְלֹא","and-not"],["בֶן־חוֹרִין","Bn-free"],["אֵין","there-is-no"],["זָכָר","male"],["וְלֹא","and-not"],["נְקֵבָה","a female"],["כִּי","because"],["כֻלְּכֶם","all-of-you"],["אֶחָד","one"],["אַתֶּם","you-are"],["בַּמָּשִׁיחַ","in-the-Messiah"],["יֵשׁוּעַ","Yeshua"],["׃",""]] },
  { num:"כט", words:[["וְאִם־לַמָּשִׁיחַ","and-if-unto-the-Messiah"],["אַתֶּם","you-are"],["הִנְּכֶם","you-see"],["זֶרַע","seed"],["אַבְרָהָם","Abraham"],["וְיוֹרְשִׁים","and-inheriting"],["כְּפִי","according-to"],["הַהַבְטָחָה","the-promise"],["׃",""]] },
];
renderVerseSet(jstgal_ch1Verses, 'jstgal-ch1-verses');

})();
