// jst_verses/jstjohn.js — John (JST) verse data
(function() {

// === CH1: JST John 1:1–34 ===
// The gospel preached from the beginning through the Son. John the Baptist as Elias.
var jstjohn_ch1Verses = [
  { num:"א", words:[["בְּרֵאשִׁית","in-the-beginning"],["הֻטְפְּצָה","was-preached"],["הַבְּשׂוֹרָה","the-gospel"],["עַל","through"],["יְדֵי","the"],["הַבֵּן","the-Son"],["וְהַבְּשׂוֹרָה","and-the-gospel"],["הָיְתָה","was"],["הַדָּבָר","the-word"],["וְהַדָּבָר","and-the-word"],["הָיָה","was"],["עִם","with"],["הַבֵּן","the-Son"],["וְהַבֵּן","and-the-Son"],["הָיָה","was"],["עִם","with"],["אֱלֹהִים","God"],["וְהַבֵּן","and-the-Son"],["הָיָה","was-of"],["מֵאֱלֹהִים","God"],["׃",""]] },
  { num:"ב", words:[["הוּא","the-same"],["הָיָה","was"],["בְּרֵאשִׁית","in-the-beginning"],["עִם","with"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"ג", words:[["הַכֹּל","all-the-things"],["נַעֲשָׂה","were-made"],["עַל","by"],["יָדוֹ","him"],["וּמִבַּלְעָדָיו","and-without-him"],["לֹא","was-not"],["נַעֲשָׂה","made"],["דָּבָר","anything"],["אֲשֶׁר","which"],["נַעֲשָׂה","was-made"],["׃",""]] },
  { num:"ד", words:[["בּוֹ","in-him"],["הָיְתָה","was"],["הַבְּשׂוֹרָה","the-gospel"],["וְהַבְּשׂוֹרָה","and-the-gospel"],["הָיְתָה","was"],["הַחַיִּים","the-life"],["וְהַחַיִּים","and-the-life"],["הָיוּ","were"],["אוֹר","the-light-of"],["בְּנֵי","the-sons-of"],["אָדָם","men"],["׃",""]] },
  { num:"ה", words:[["וְהָאוֹר","and-the-light"],["מֵאִיר","shineth"],["בָּעוֹלָם","in-the-world"],["וְהָעוֹלָם","and-the-world"],["אֵינוֹ","it-doth-not"],["מַשִּׂיג","perceive"],["אוֹתוֹ","it"],["׃",""]] },
  { num:"ו", words:[["הָיָה","there-was"],["אִישׁ","a-man"],["שָׁלוּחַ","sent"],["מֵאֱלֹהִים","from-God"],["שְׁמוֹ","whose-name-was"],["יוֹחָנָן","John"],["׃",""]] },
  { num:"ז", words:[["הוּא","the-same"],["בָּא","came"],["אֶל","into"],["הָעוֹלָם","the-world"],["לְעֵד","for-a-witness"],["לְהָעִיד","to-bear-witness-of"],["עַל","of"],["הָאוֹר","the-light"],["לְהָעִיד","to-bear-record-of"],["עַל","of"],["הַבְּשׂוֹרָה","the-gospel"],["עַל","through"],["יְדֵי","the-hands-of"],["הַבֵּן","the-Son"],["אֶל","unto"],["הַכֹּל","all"],["לְמַעַן","that"],["עַל","through"],["יָדוֹ","him"],["יַאֲמִינוּ","might-believe"],["בְּנֵי","the-sons-of"],["אָדָם","men"],["׃",""]] },
  { num:"ח", words:[["הוּא","he"],["לֹא","not"],["הָיָה","was"],["הָאוֹר","the-light"],["הַהוּא","that"],["אֶלָּא","but"],["בָּא","came"],["לְהָעִיד","to-bear-witness"],["עַל","of"],["הָאוֹר","the-light"],["הַהוּא","that"],["׃",""]] },
  { num:"ט", words:[["אֲשֶׁר","which-was"],["הָאוֹר","the-true"],["הָאֲמִתִּי","the-light"],["הַמֵּאִיר","the-which-lighteth"],["לְכׇל","every"],["אָדָם","man"],["הַבָּא","who-cometh"],["אֶל","into"],["הָעוֹלָם","the-world"],["׃",""]] },
  { num:"י", words:[["הוּא","he-was"],["הָיָה","in"],["בָּעוֹלָם","the-world"],["וְהָעוֹלָם","and-the-world"],["נַעֲשָׂה","was-made"],["עַל","by"],["יָדוֹ","him"],["וְהָעוֹלָם","and-the-world"],["לֹא","knew-him"],["הִכִּירוֹ","not"],["׃",""]] },
  { num:"יא", words:[["אֶל","unto"],["שֶׁלּוֹ","his-own"],["בָּא","he-came"],["וְשֶׁלּוֹ","and-his-own"],["לֹא","not"],["קִבְּלוּהוּ","received-him"],["׃",""]] },
  { num:"יב", words:[["אַךְ","but"],["לְכׇל","as-many-as"],["הַמְּקַבְּלִים","the-received"],["אוֹתוֹ","him"],["נָתַן","to-them-gave-he"],["לָהֶם","power"],["כֹּחַ","to-become"],["לִהְיוֹת","the-sons-of"],["בְּנֵי","God"],["אֱלֹהִים","only"],["רַק","to-them-that"],["לַמַּאֲמִינִים","the-believe"],["בִּשְׁמוֹ","on-his-name"],["׃",""]] },
  { num:"יג", words:[["הוּא","he"],["הָיָה","was"],["נוֹלָד","born"],["לֹא","not"],["מִדָּם","of-blood"],["וְלֹא","nor"],["מֵרְצוֹן","of-the-will-of"],["בָּשָׂר","the-flesh"],["וְלֹא","nor"],["מֵרְצוֹן","of-the-will-of"],["אִישׁ","man"],["כִּי","but"],["מֵאֱלֹהִים","of-God"],["׃",""]] },
  { num:"יד", words:[["וְהַדָּבָר","and-the-same-word"],["נַעֲשָׂה","was-made"],["בָּשָׂר","flesh"],["וְשָׁכַן","and-dwelt"],["בְּתוֹכֵנוּ","among-us"],["וְרָאִינוּ","and-we-beheld"],["אֶת־כְּבוֹדוֹ","his-glory"],["כְּבוֹד","the-glory"],["הַבֵּן","as-of-the"],["הַיָּחִיד","the-Only-Begotten"],["מֵאֵת","of"],["הָאָב","the-Father"],["מָלֵא","full-of"],["חֶסֶד","grace"],["וֶאֱמֶת","and-truth"],["׃",""]] },
  { num:"טו", words:[["יוֹחָנָן","John"],["הֵעִיד","bore-record-of"],["עָלָיו","him"],["וַיִּקְרָא","and-cried"],["לֵאמֹר","saying"],["זֶה","this-is-he"],["הוּא","of-whom"],["אֲשֶׁר","whom"],["דִּבַּרְתִּי","I-spake"],["הַבָּא","he-who-cometh"],["אַחֲרַי","after-me"],["קָדַם","is-preferred-before"],["לְפָנַי","me"],["כִּי","for"],["הָיָה","he-was"],["לְפָנַי","before-me"],["׃",""]] },
  { num:"טז", words:[["כִּי","for"],["בְּרֵאשִׁית","in-the-beginning"],["הָיָה","was"],["הַדָּבָר","the-Word"],["אַף","even"],["הַבֵּן","the-Son"],["אֲשֶׁר","who"],["נַעֲשָׂה","is-made"],["בָּשָׂר","flesh"],["וְנִשְׁלַח","and-sent"],["אֵלֵינוּ","unto-us"],["בִּרְצוֹן","by-the-will-of"],["הָאָב","the-Father"],["וְכׇל","and-as-many-as"],["הַמַּאֲמִינִים","believe"],["בִּשְׁמוֹ","on-his-name"],["יְקַבְּלוּ","shall-receive"],["מִמְּלֹאוֹ","of-his-fullness"],["וּמִמְּלֹאוֹ","and-of-his-fullness"],["קִבַּלְנוּ","have-received"],["כֻּלָּנוּ","all-we"],["אַף","even"],["אַלְמָוֶת","immortality"],["וְחַיֵּי","and-life"],["עוֹלָם","eternal"],["עַל","through"],["יְדֵי","the-hands-of"],["חַסְדּוֹ","his-grace"],["׃",""]] },
  { num:"יז", words:[["כִּי","for"],["הַתּוֹרָה","the-law"],["נִתְּנָה","was-given"],["עַל","through"],["יְדֵי","the-hands-of"],["מֹשֶׁה","Moses"],["אַךְ","but"],["הַחַיִּים","the-life"],["וְהָאֱמֶת","and-the-truth"],["בָּאוּ","came"],["עַל","through"],["יְדֵי","the-hands-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Christ"],["׃",""]] },
  { num:"יח", words:[["כִּי","for"],["הַתּוֹרָה","the-law"],["הָיְתָה","was"],["עַל","after"],["פִּי","the-mouth-of"],["מִצְוַת","a-commandment-of"],["בָּשָׂר","flesh"],["לְשֵׁרוּת","to-the-administration-of"],["הַמָּוֶת","the-death"],["אַךְ","but"],["הַבְּשׂוֹרָה","the-gospel"],["הָיְתָה","was"],["עַל","after"],["פִּי","the-mouth-of"],["כֹּחַ","the-power-of"],["חַיִּים","a-life"],["אֵין־קֵץ","endless"],["עַל","through"],["יְדֵי","the-hands-of"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Christ"],["הַבֵּן","the-Son"],["הַיָּחִיד","the-Only-Begotten"],["אֲשֶׁר","who-is"],["בְּחֵיק","in-the-bosom-of"],["הָאָב","the-Father"],["׃",""]] },
  { num:"יט", words:[["וְאִישׁ","and-no-man"],["לֹא","not"],["רָאָה","hath-seen"],["אֶת־אֱלֹהִים","God"],["מֵעוֹלָם","at-any-time"],["בִּלְתִּי","except"],["אִם","that"],["הֵעִיד","he-hath-borne-record"],["עַל","of"],["הַבֵּן","the-Son"],["כִּי","for"],["בִּלְתִּי","except"],["עַל","through"],["יָדוֹ","his-hand"],["לֹא","not"],["יִוָּשַׁע","can-be-saved"],["אִישׁ","any-man"],["׃",""]] },
  { num:"כ", words:[["וְזוֹ","and-this-is"],["עֵדוּת","the-record-of"],["יוֹחָנָן","John"],["כַּאֲשֶׁר","when"],["שָׁלְחוּ","sent"],["הַיְּהוּדִים","the-Jews"],["כֹּהֲנִים","priests"],["וּלְוִיִּם","and-Levites"],["מִירוּשָׁלַיִם","from-Jerusalem"],["לִשְׁאֹל","to-ask"],["אוֹתוֹ","him"],["מִי","who"],["אַתָּה","art-thou"],["׃",""]] },
  { num:"כא", words:[["וַיּוֹדֶה","and-he-confessed"],["וְלֹא","and-not"],["כִחֵשׁ","he-denied"],["וַיּוֹדֶה","but-confessed"],["לֵאמֹר","saying"],["אֵינֶנִּי","I-am-not"],["הַמָּשִׁיחַ","the-Christ"],["׃",""]] },
  { num:"כב", words:[["וַיִּשְׁאֲלוּהוּ","and-they-asked-him"],["לֵאמֹר","saying"],["וּמָה","and-what"],["אֵפוֹא","then"],["אֵלִיָּהוּ","Elias"],["אַתָּה","art-thou"],["וַיֹּאמֶר","and-he-said"],["אֵינֶנִּי","I-am-not"],["אֵלִיָּהוּ","Elias"],["הַהוּא","that"],["אֲשֶׁר","who"],["עָתִיד","was"],["לְהָשִׁיב","to-restore"],["אֶת־כׇּל","all"],["הַדְּבָרִים","the-things"],["וַיִּשְׁאֲלוּהוּ","and-they-asked-him"],["לֵאמֹר","saying"],["הַנָּבִיא","the-prophet"],["הַהוּא","that"],["אַתָּה","art-thou"],["וַיַּעַן","and-he-answered"],["לֹא","no"],["׃",""]] },
  { num:"כג", words:[["וַיֹּאמְרוּ","then-said-they"],["לוֹ","unto-him"],["מִי","who"],["אַתָּה","art-thou"],["לְמַעַן","that"],["נָשִׁיב","we-may-give"],["דָּבָר","an-answer"],["לְשׁוֹלְחֵינוּ","to-them-that-sent-us"],["מָה","what"],["אוֹמֵר","sayest"],["אַתָּה","thou"],["עַל","of"],["עַצְמְךָ","thyself"],["׃",""]] },
  { num:"כד", words:[["אָמַר","he-said"],["אֲנִי","I-am"],["קוֹל","the-voice-of"],["קוֹרֵא","one-crying"],["בַּמִּדְבָּר","in-the-wilderness"],["יַשְּׁרוּ","make-straight"],["דֶּרֶךְ","the-way-of"],["יְהוָה","the-LORD"],["כַּאֲשֶׁר","as"],["אָמַר","said"],["יְשַׁעְיָהוּ","Esaias"],["הַנָּבִיא","the-prophet"],["׃",""]] },
  { num:"כה", words:[["וְהַשְּׁלוּחִים","and-the-they-who-were-sent"],["הָיוּ","were"],["מִן","of"],["הַפְּרוּשִׁים","the-Pharisees"],["׃",""]] },
  { num:"כו", words:[["וַיִּשְׁאֲלוּהוּ","and-they-asked-him"],["וַיֹּאמְרוּ","and-said"],["לוֹ","unto-him"],["מַדּוּעַ","why"],["מַטְבִּיל","baptizest"],["אַתָּה","thou"],["אִם","if"],["אֵינְךָ","thou-be-not"],["הַמָּשִׁיחַ","the-Christ"],["וְלֹא","nor"],["אֵלִיָּהוּ","Elias"],["אֲשֶׁר","who"],["עָתִיד","was"],["לְהָשִׁיב","to-restore"],["אֶת־כׇּל","all"],["הַדְּבָרִים","the-things"],["וְלֹא","neither"],["הַנָּבִיא","the-prophet"],["הַהוּא","that"],["׃",""]] },
  { num:"כז", words:[["עָנָה","answered"],["יוֹחָנָן","John"],["לֵאמֹר","saying"],["אֲנִי","I"],["מַטְבִּיל","baptize"],["בְּמַיִם","with-water"],["אַךְ","but"],["בְּתוֹכְכֶם","in-the-midst-of-you"],["עוֹמֵד","there-standeth"],["אֶחָד","one"],["אֲשֶׁר","whom"],["אֵינְכֶם","ye-are-not"],["יוֹדְעִים","knowing"],["׃",""]] },
  { num:"כח", words:[["הוּא","he"],["אֲשֶׁר","of-whom"],["אֲנִי","I"],["מֵעִיד","bear-record"],["עָלָיו","of-him"],["הוּא","he-is"],["הַנָּבִיא","the-prophet"],["הַהוּא","that"],["אַף","even"],["אֵלִיָּהוּ","Elias"],["אֲשֶׁר","who"],["בָּא","coming"],["אַחֲרַי","after-me"],["וְנִעְדָּף","is-preferred"],["עָלַי","before-me"],["אֲשֶׁר","whose"],["שְׂרוֹךְ","latchet-of"],["נַעֲלוֹ","his-shoe"],["אֵינֶנִּי","I-am-not"],["רָאוּי","worthy"],["לְהַתִּיר","to-unloose"],["אוֹ","or"],["אֲשֶׁר","whose"],["אֶת־מְקוֹמוֹ","his-place"],["אֵינֶנִּי","I-am-not"],["יָכוֹל","able"],["לְמַלֵּא","to-fill"],["כִּי","for"],["הוּא","he"],["יַטְבִּיל","shall-baptize"],["לֹא","not"],["בְּמַיִם","with-water"],["בִּלְבַד","only"],["כִּי","but"],["אִם","rather"],["בָּאֵשׁ","with-fire"],["וּבְרוּחַ","and-with-the-Spirit"],["הַקֹּדֶשׁ","the-Holy"],["׃",""]] },
  { num:"כט", words:[["מִמׇּחֳרָת","the-next-day"],["רוֹאֶה","seeth"],["יוֹחָנָן","John"],["אֶת־יֵשׁוּעַ","Jesus"],["בָּא","coming"],["אֵלָיו","unto-him"],["וַיֹּאמֶר","and-saith"],["הִנֵּה","behold"],["שֶׂה","the-Lamb-of"],["הָאֱלֹהִים","God"],["הַנּוֹשֵׂא","the-which-taketh-away"],["אֶת־חַטֹּאת","the-sin-of"],["הָעוֹלָם","the-world"],["׃",""]] },
  { num:"ל", words:[["וְזֶה","and-this-is-he"],["הוּא","of-whom"],["אֲשֶׁר","I"],["אָמַרְתִּי","said"],["אַחֲרַי","after-me"],["בָּא","cometh"],["אִישׁ","a-man"],["אֲשֶׁר","who-is"],["נִעְדָּף","preferred-before"],["עָלַי","me"],["כִּי","for"],["הָיָה","he-was"],["לְפָנַי","before-me"],["וַאֲנִי","and-I"],["לֹא","knew-him"],["יְדַעְתִּיו","not"],["אַךְ","but"],["לְמַעַן","that"],["יִגָּלֶה","he-should-be-made-manifest"],["לְיִשְׂרָאֵל","to-Israel"],["לָכֵן","therefore"],["בָּאתִי","am-I-come"],["מַטְבִּיל","baptizing"],["בְּמַיִם","with-water"],["׃",""]] },
  { num:"לא", words:[["וַיָּעַד","and-bore-record"],["יוֹחָנָן","John"],["לֵאמֹר","saying"],["רָאִיתִי","I-saw"],["אֶת־הָרוּחַ","the-Spirit"],["יוֹרֶדֶת","descending"],["מִן","from"],["הַשָּׁמַיִם","the-heaven"],["כְּיוֹנָה","like-a-dove"],["וַתָּנַח","and-it-abode"],["עָלָיו","upon-him"],["׃",""]] },
  { num:"לב", words:[["וַאֲנִי","and-I"],["לֹא","knew-him"],["יְדַעְתִּיו","not"],["אַךְ","but"],["הַשּׁוֹלֵחַ","the-he-that-sent"],["אוֹתִי","me"],["לְהַטְבִּיל","to-baptize"],["בְּמַיִם","with-water"],["הוּא","the-same"],["אָמַר","said"],["אֵלַי","unto-me"],["עַל","upon"],["מִי","whomsoever"],["שֶׁתִּרְאֶה","thou-shalt-see"],["אֶת־הָרוּחַ","the-Spirit"],["יוֹרֶדֶת","descending"],["וְנָחָה","and-remaining"],["עָלָיו","on-him"],["הוּא","the-same-is-he"],["הַמַּטְבִּיל","the-who-baptizeth"],["בְּרוּחַ","with-the-Spirit-of"],["הַקֹּדֶשׁ","the-Holiness"],["׃",""]] },
  { num:"לג", words:[["וַאֲנִי","and-I"],["רָאִיתִי","saw"],["וָאָעִיד","and-bare-record"],["כִּי","that"],["זֶה","this"],["הוּא","is"],["בֶּן","the-Son-of"],["הָאֱלֹהִים","God"],["׃",""]] },
  { num:"לד", words:[["אֵלֶּה","these"],["הַדְּבָרִים","the-things"],["נַעֲשׂוּ","were-done"],["בְּבֵית","in-Beth-"],["עַנְיָה","abara"],["מֵעֵבֶר","beyond"],["לַיַּרְדֵּן","the-Jordan"],["אֲשֶׁר","where"],["הָיָה","was"],["יוֹחָנָן","John"],["מַטְבִּיל","baptizing"],["׃",""]] }
];
renderVerseSet(jstjohn_ch1Verses, 'jstjohn-ch1-verses');

// === CH2: JST John 4:1–4, 26 ===
// The Pharisees desire to kill Jesus. God promises His Spirit to true believers.
var jstjohn_ch2Verses = [
  { num:"א", words:[["כַּאֲשֶׁר","when-therefore"],["שָׁמְעוּ","had-heard"],["הַפְּרוּשִׁים","the-Pharisees"],["כִּי","that"],["יֵשׁוּעַ","Jesus"],["עָשָׂה","made"],["וְהִטְבִּיל","and-baptized"],["תַּלְמִידִים","disciples"],["רַבִּים","more"],["מִיּוֹחָנָן","than-John"],["׃",""]] },
  { num:"ב", words:[["בִּקְשׁוּ","they-sought"],["בְּיֶתֶר","with-more"],["שְׁקִידָה","diligence"],["אֶמְצָעִים","some-means"],["לַהֲמִיתוֹ","that-they-might-put-him-to-death"],["כִּי","for"],["רַבִּים","many"],["קִבְּלוּ","received"],["אֶת־יוֹחָנָן","John"],["כְּנָבִיא","as-a-prophet"],["אַךְ","but"],["לֹא","not"],["הֶאֱמִינוּ","they-believed"],["בְּיֵשׁוּעַ","Jesus"],["׃",""]] },
  { num:"ג", words:[["וְהָאָדוֹן","now-the-Lord"],["יָדַע","knew"],["זֹאת","this"],["אַף","though"],["הוּא","he-himself"],["לֹא","baptized-not"],["הִטְבִּיל","so-many-as"],["כְּמוֹ","his"],["תַּלְמִידָיו","disciples"],["׃",""]] },
  { num:"ד", words:[["כִּי","for"],["הִרְשָׁה","he-suffered"],["לָהֶם","them"],["לְמוֹפֵת","for-an-example"],["מַעֲדִיפִים","preferring"],["זֶה","one"],["אֶת־זֶה","another"],["׃",""]] },
  { num:"כו", words:[["כִּי","for"],["לְכָאֵלֶּה","unto-such"],["הִבְטִיחַ","hath-promised"],["אֱלֹהִים","God"],["אֶת־רוּחוֹ","his-Spirit"],["וְהַמִּשְׁתַּחֲוִים","and-the-they-who-worship"],["לוֹ","him"],["חַיָּבִים","must"],["לְהִשְׁתַּחֲווֹת","worship"],["בְּרוּחַ","in-spirit"],["וּבֶאֱמֶת","and-in-truth"],["׃",""]] }
];
renderVerseSet(jstjohn_ch2Verses, 'jstjohn-ch2-verses');

// === CH3: JST John 6:44 ===
// The Father's will is that all receive Jesus.
var jstjohn_ch3Verses = [
  { num:"מד", words:[["אֵין","no"],["אִישׁ","man"],["יָכוֹל","can"],["לָבוֹא","come"],["אֵלַי","unto-me"],["אֶלָּא","except"],["אִם","he-doeth"],["עוֹשֶׂה","the-will-of"],["רְצוֹן","my-Father"],["אָבִי","who"],["אֲשֶׁר","hath-sent"],["שְׁלָחַנִי","me"],["וְזֶה","and-this-is"],["רְצוֹן","the-will-of"],["הַשּׁוֹלֵחַ","the-him-who-hath-sent"],["אוֹתִי","me"],["כִּי","that"],["תְּקַבְּלוּ","ye-receive"],["אֶת־הַבֵּן","the-Son"],["כִּי","for"],["הָאָב","the-Father"],["מֵעִיד","beareth-record-of"],["עָלָיו","him"],["וְהַמְּקַבֵּל","and-the-he-who-receiveth"],["אֶת־הָעֵדוּת","the-testimony"],["וְעוֹשֶׂה","and-doeth"],["רְצוֹן","the-will-of"],["הַשּׁוֹלְחֵנִי","the-him-who-sent-me"],["אֲקִימֶנּוּ","I-will-raise-him-up"],["בִּתְחִיַּת","in-the-resurrection-of"],["הַצַּדִּיקִים","the-just"],["׃",""]] }
];
renderVerseSet(jstjohn_ch3Verses, 'jstjohn-ch3-verses');

// === CH4: JST John 13:8–10 ===
// Jesus washes the feet of the Apostles to fulfill the law.
var jstjohn_ch4Verses = [
  { num:"ח", words:[["אָמַר","saith"],["לוֹ","unto-him"],["פֶּטְרוֹס","Peter"],["אֵינְךָ","thou-art-not"],["צָרִיךְ","needing"],["לִרְחֹץ","to-wash"],["אֶת־רַגְלַי","my-feet"],["עָנָה","answered"],["יֵשׁוּעַ","Jesus"],["אוֹתוֹ","him"],["אִם","if"],["אֵינֶנִּי","I-am-not"],["רוֹחֲצְךָ","washing-thee"],["אֵין","there-is-no"],["לְךָ","to-thee"],["חֵלֶק","part"],["אִתִּי","with-me"],["׃",""]] },
  { num:"ט", words:[["אָמַר","saith"],["לוֹ","unto-him"],["שִׁמְעוֹן","Simon"],["פֶּטְרוֹס","Peter"],["אֲדֹנִי","Lord"],["לֹא","not"],["רַק","only"],["רַגְלַי","my-feet"],["אֶלָּא","but"],["גַּם","also"],["יָדַי","my-hands"],["וְרֹאשִׁי","and-my-head"],["׃",""]] },
  { num:"י", words:[["אָמַר","saith"],["לוֹ","to-him"],["יֵשׁוּעַ","Jesus"],["הָרוֹחֵץ","he-that-washeth"],["יָדָיו","his-hands"],["וְרֹאשׁוֹ","and-his-head"],["אֵינוֹ","needeth-not"],["צָרִיךְ","needing"],["אֶלָּא","save"],["לִרְחֹץ","to-wash"],["רַגְלָיו","his-feet"],["אֲבָל","but"],["טָהוֹר","clean"],["כֻּלּוֹ","every-whit"],["וְאַתֶּם","and-ye"],["טְהוֹרִים","are-clean"],["אַךְ","but"],["לֹא","not"],["כֻּלְּכֶם","all-of-you"],["וְזֶה","and-this"],["הָיָה","was"],["מִנְהַג","the-custom-of"],["הַיְּהוּדִים","the-Jews"],["עַל","under"],["פִּי","the-mouth-of"],["תּוֹרָתָם","their-law"],["לָכֵן","wherefore"],["עָשָׂה","did"],["יֵשׁוּעַ","Jesus"],["זֹאת","this"],["לְמַעַן","that"],["תִּתְמַלֵּא","might-be-fulfilled"],["הַתּוֹרָה","the-law"],["׃",""]] }
];
renderVerseSet(jstjohn_ch4Verses, 'jstjohn-ch4-verses');

// === CH5: JST John 14:30 ===
// The prince of darkness is of this world.
var jstjohn_ch5Verses = [
  { num:"ל", words:[["מֵעַתָּה","hereafter"],["לֹא","I-will-not"],["אֲדַבֵּר","talk"],["עִמָּכֶם","with-you"],["הַרְבֵּה","much"],["כִּי","for"],["שַׂר","the-prince-of"],["הַחֹשֶׁךְ","the-darkness"],["אֲשֶׁר","who-is"],["מִן","of"],["הָעוֹלָם","the-world"],["הַזֶּה","this"],["בָּא","cometh"],["אַךְ","but"],["אֵין","there-is-no"],["לוֹ","to-him"],["כֹּחַ","power"],["עָלַי","over-me"],["אַךְ","but"],["יֵשׁ","there-is"],["לוֹ","to-him"],["כֹּחַ","power"],["עֲלֵיכֶם","over-you"],["׃",""]] }
];
renderVerseSet(jstjohn_ch5Verses, 'jstjohn-ch5-verses');

})();
