// jst_verses/jstjohn.js — John (JST) verse data
(function() {

// === CH1: JST John 1:1–34 ===
// The gospel preached from the beginning through the Son. John the Baptist as Elias.
var jstjohn_ch1Verses = [
  { num:"א", words:[["בְּרֵאשִׁית","in-the-beginning"],["הֻטְפְּצָה","was-preached"],["הַבְּשׂוֹרָה","the-gospel"],["עַל","through"],["יְדֵי","the"],["הַבֵּן","the-Son"],["וְהַבְּשׂוֹרָה","and-the-gospel"],["הָיְתָה","was"],["הַדָּבָר","the-word"],["וְהַדָּבָר","and-the-word"],["הָיָה","was"],["עִם","with"],["הַבֵּן","the-Son"],["וְהַבֵּן","and-the-Son"],["הָיָה","was"],["עִם","with"],["אֱלֹהִים","God"],["וְהַבֵּן","and-the-Son"],["הָיָה","was-of"],["מֵאֱלֹהִים","God"],["׃",""]] },
  { num:"ב", words:[["הוּא","the-same"],["הָיָה","was"],["בְּרֵאשִׁית","in-the-beginning"],["עִם","with"],["אֱלֹהִים","God"],["׃",""]] },
  { num:"ג", words:[["הַכֹּל","all-the-things"],["נַעֲשָׂה","were-made"],["עַל","by"],["יָדוֹ","him"],["וּמִבַּלְעָדָיו","and-without-him"],["לֹא","was-not"],["נַעֲשָׂה","made"],["דָּבָר","anything"],["אֲשֶׁר","which"],["נַעֲשָׂה","was-made"],["׃",""]] },
  { num:"ד", words:[["בּוֹ","in-him"],["הָיְתָה","was"],["הַבְּשׂוֹרָה","the-gospel"],["וְהַבְּשׂוֹרָה","and-the-gospel"],["הָיְתָה","was"],["הַחַיִּים","the-life"],["וְהַחַיִּים","and-the-life"],["הָיוּ","were"],["אוֹר","the-light-of"],["בְּנֵי","sons-of"],["אָדָם","men"],["׃",""]] },
  { num:"ה", words:[["וְהָאוֹר","and-the-light"],["מֵאִיר","shineth"],["בָּעוֹלָם","in-the-world"],["וְהָעוֹלָם","and-the-world"],["אֵינוֹ","perceiveth-it"],["מַשִּׂיג","not"],["אוֹתוֹ","[it]"],["׃",""]] },
  { num:"ו", words:[["הָיָה","there-was"],["אִישׁ","a-man"],["שָׁלוּחַ","sent"],["מֵאֱלֹהִים","from-God"],["שְׁמוֹ","whose-name-was"],["יוֹחָנָן","John"],["׃",""]] },
  { num:"ז", words:[["הוּא","the-same"],["בָּא","came"],["אֶל","into"],["הָעוֹלָם","the-world"],["לְעֵד","for-a-witness"],["לְהָעִיד","to-bear-witness-of"],["עַל","[ACC]"],["הָאוֹר","the-light"],["לְהָעִיד","to-bear-record-of"],["עַל","[ACC]"],["הַבְּשׂוֹרָה","the-gospel"],["עַל","through"],["יְדֵי","the"],["הַבֵּן","the-Son"],["אֶל","unto"],["הַכֹּל","all-the"],["לְמַעַן","that"],["עַל","through"],["יָדוֹ","him"],["יַאֲמִינוּ","men-might-believe"],["בְּנֵי","[sons]"],["אָדָם","[men]"],["׃",""]] },
  { num:"ח", words:[["הוּא","he"],["לֹא","was-not"],["הָיָה","that"],["הָאוֹר","the-light"],["הַהוּא","[that]"],["אֶלָּא","but-came"],["בָּא","to-bear-witness-of"],["לְהָעִיד","that"],["עַל","light"],["הָאוֹר","the-[light]"],["הַהוּא","[that]"],["׃",""]] },
  { num:"ט", words:[["אֲשֶׁר","which-was"],["הָאוֹר","the-true"],["הָאֲמִתִּי","the-light"],["הַמֵּאִיר","the-which-lighteth"],["לְכׇל","every"],["אָדָם","man"],["הַבָּא","who-cometh"],["אֶל","into"],["הָעוֹלָם","the-world"],["׃",""]] },
  { num:"י", words:[["הוּא","he-was"],["הָיָה","in"],["בָּעוֹלָם","the-world"],["וְהָעוֹלָם","and-the-world"],["נַעֲשָׂה","was-made"],["עַל","by"],["יָדוֹ","him"],["וְהָעוֹלָם","and-the-world"],["לֹא","knew-him"],["הִכִּירוֹ","not"],["׃",""]] },
  { num:"יא", words:[["אֶל","he-came"],["שֶׁלּוֹ","unto-his-own"],["בָּא","[came]"],["וְשֶׁלּוֹ","and-his-own"],["לֹא","received-him"],["קִבְּלוּהוּ","not"],["׃",""]] },
  { num:"יב", words:[["אַךְ","but"],["לְכׇל","as-many-as"],["הַמְּקַבְּלִים","the-received"],["אוֹתוֹ","him"],["נָתַן","to-them-gave-he"],["לָהֶם","power"],["כֹּחַ","to-become"],["לִהְיוֹת","the-sons-of"],["בְּנֵי","God"],["אֱלֹהִים","only"],["רַק","to-them-that"],["לַמַּאֲמִינִים","the-believe"],["בִּשְׁמוֹ","on-his-name"],["׃",""]] },
  { num:"יג", words:[["הוּא","he"],["הָיָה","was"],["נוֹלָד","born"],["לֹא","not"],["מִדָּם","of-blood"],["וְלֹא","nor"],["מֵרְצוֹן","of-the-will-of"],["בָּשָׂר","the-flesh"],["וְלֹא","nor"],["מֵרְצוֹן","of-the-will-of"],["אִישׁ","man"],["כִּי","but"],["מֵאֱלֹהִים","of-God"],["׃",""]] },
  { num:"יד", words:[["וְהַדָּבָר","and-the-same-word"],["נַעֲשָׂה","was-made"],["בָּשָׂר","flesh"],["וְשָׁכַן","and-dwelt"],["בְּתוֹכֵנוּ","among-us"],["וְרָאִינוּ","and-we-beheld"],["אֶת","[ACC]"],["כְּבוֹדוֹ","his-glory"],["כְּבוֹד","the-glory"],["הַבֵּן","as-of-the"],["הַיָּחִיד","the-Only-Begotten"],["מֵאֵת","of"],["הָאָב","the-Father"],["מָלֵא","full-of"],["חֶסֶד","grace"],["וֶאֱמֶת","and-truth"],["׃",""]] },
  { num:"טו", words:[["יוֹחָנָן","John"],["הֵעִיד","bore-record-of"],["עָלָיו","him"],["וַיִּקְרָא","and-cried"],["לֵאמֹר","saying"],["זֶה","this-is-he"],["הוּא","of-whom"],["אֲשֶׁר","I-spake"],["דִּבַּרְתִּי","[spake]"],["הַבָּא","he-who-cometh"],["אַחֲרַי","after-me"],["קָדַם","is-preferred-before"],["לְפָנַי","me"],["כִּי","for"],["הָיָה","he-was"],["לְפָנַי","before-me"],["׃",""]] },
  { num:"טז", words:[["כִּי","for"],["בַּיּוֹם","in-the-day"],["שֶׁהוּא","that-he"],["יָבוֹא","shall-come"],["הוּא","he"],["יָעִיד","shall-bear-record"],["וְיֹאמַר","and-shall-say"],["זֶה","this-is-he"],["הוּא","of-whom"],["אֲשֶׁר","I-spake"],["דִּבַּרְתִּי","[spake]"],["הַבָּא","he-who-cometh"],["אַחֲרַי","after-me"],["וְהוּא","and-is"],["קָדַם","preferred-before"],["לְפָנַי","me"],["כִּי","for"],["הָיָה","he-was"],["לְפָנַי","before-me"],["׃",""]] },
  { num:"יז", words:[["וּמִמְלֹאוֹ","and-of-his-fulness"],["קִבַּלְנוּ","have-we-received"],["כֻּלָּנוּ","all-of-us"],["חֶסֶד","grace"],["תַּחַת","for"],["חֶסֶד","grace"],["׃",""]] },
  { num:"יח", words:[["כִּי","for"],["הַתּוֹרָה","the-law"],["נִתְּנָה","was-given"],["עַל","through"],["יְדֵי","[by]"],["מֹשֶׁה","Moses"],["אַךְ","but"],["הַחֶסֶד","the-grace"],["וְהָאֱמֶת","and-the-truth"],["בָּאוּ","came"],["עַל","through"],["יְדֵי","[by]"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Christ"],["׃",""]] },
  { num:"יט", words:[["כִּי","for"],["הַתּוֹרָה","the-law"],["נִתְּנָה","was"],["אַחֲרֵי","after"],["מֹשֶׁה","Moses"],["אַךְ","but"],["מְלֹאת","the-fulness-of"],["הַבְּשׂוֹרָה","the-gospel"],["בָּאָה","came"],["עַל","through"],["יְדֵי","[by]"],["יֵשׁוּעַ","Jesus"],["הַמָּשִׁיחַ","the-Christ"],["׃",""]] },
  { num:"כ", words:[["אֱלֹהִים","no-man"],["לֹא","hath-seen"],["רָאָה","God"],["אִישׁ","at-any"],["מֵעוֹלָם","time"],["אֶלָּא","except"],["הַמֵּעִיד","the-he-hath-borne-record"],["עָלָיו","of-him"],["כִּי","for"],["מֵעוֹלָם","except"],["לֹא","through"],["רָאָה","him"],["אִישׁ","can-any-man"],["אֶת","be"],["אֱלֹהִים","saved"],["׃",""]] },
  { num:"כא", words:[["וְזוֹ","and-this-is"],["עֵדוּת","the-record-of"],["יוֹחָנָן","John"],["כַּאֲשֶׁר","when"],["שָׁלְחוּ","sent"],["הַיְּהוּדִים","the-Jews"],["כֹּהֲנִים","priests"],["וּלְוִיִּם","and-Levites"],["מִירוּשָׁלַיִם","from-Jerusalem"],["לִשְׁאֹל","to-ask"],["אוֹתוֹ","him"],["מִי","who"],["אַתָּה","art-thou"],["׃",""]] },
  { num:"כב", words:[["וַיּוֹדֶה","and-he-confessed"],["וְלֹא","and-denied-not"],["כִחֵשׁ","[denied]"],["וַיּוֹדֶה","but-confessed"],["לֵאמֹר","saying"],["אֵינֶנִּי","I-am-not"],["הַמָּשִׁיחַ","the-Christ"],["׃",""]] },
  { num:"כג", words:[["וַיִּשְׁאֲלוּהוּ","and-they-asked-him"],["מָה","what-then"],["אֵלִיָּהוּ","art-thou-Elias"],["אַתָּה","[thou]"],["וַיֹּאמֶר","and-he-saith"],["אֵינֶנִּי","I-am-not"],["הַנָּבִיא","that-the-prophet"],["אַתָּה","art-thou"],["וַיַּעַן","and-he-answered"],["לֹא","no"],["׃",""]] },
  { num:"כד", words:[["וַיֹּאמְרוּ","then-said-they"],["לוֹ","unto-him"],["מִי","who"],["אַתָּה","art-thou"],["לְמַעַן","that"],["נָשִׁיב","we-may-give"],["דָּבָר","an-answer"],["לְשׁוֹלְחֵינוּ","to-them-that-sent-us"],["מָה","what"],["אוֹמֵר","sayest-thou"],["אַתָּה","[thou]"],["עַל","of"],["עַצְמְךָ","thyself"],["׃",""]] },
  { num:"כה", words:[["אָמַר","he-said"],["אֲנִי","I-am"],["קוֹל","the-voice-of"],["קוֹרֵא","one-crying"],["בַּמִּדְבָּר","in-the-wilderness"],["יַשְּׁרוּ","make-straight"],["דֶּרֶךְ","the-way-of"],["יְהוָה","the-LORD"],["כַּאֲשֶׁר","as"],["אָמַר","said"],["יְשַׁעְיָהוּ","the-prophet-Esaias"],["הַנָּבִיא","the-[prophet]"],["׃",""]] },
  { num:"כו", words:[["וְהַשְּׁלוּחִים","and-the-they-who-were-sent"],["הָיוּ","were"],["מִן","of"],["הַפְּרוּשִׁים","the-Pharisees"],["׃",""]] },
  { num:"כז", words:[["וַיִּשְׁאֲלוּהוּ","and-they-asked-him"],["וַיֹּאמְרוּ","and-said"],["לוֹ","unto-him"],["מַדּוּעַ","why-then"],["מַטְבִּיל","baptizest-thou"],["אַתָּה","[thou]"],["אִם","if"],["אֵינְךָ","thou-be-not"],["הַמָּשִׁיחַ","that-the-Christ"],["וְלֹא","nor"],["אֵלִיָּהוּ","Elias"],["וְלֹא","neither"],["הַנָּבִיא","that-the-prophet"],["הַהוּא","[that]"],["׃",""]] },
  { num:"כח", words:[["עָנָה","answered"],["יוֹחָנָן","John"],["לֵאמֹר","saying"],["אֲנִי","I"],["מַטְבִּיל","baptize"],["בְּמַיִם","with-water"],["אַךְ","but"],["בְּתוֹכְכֶם","in-the-midst-of-you"],["עוֹמֵד","there-standeth"],["אֶחָד","one"],["אֲשֶׁר","whom"],["אֵינְכֶם","ye-know-not"],["יוֹדְעִים","[know]"],["׃",""]] },
  { num:"כט", words:[["הוּא","he-it-is"],["הַבָּא","who-coming"],["אַחֲרַי","after-me"],["וְנִעְדָּף","is-preferred-before"],["עָלַי","me"],["אֲשֶׁר","which"],["שְׂרוֹךְ","latchet-of"],["נַעֲלוֹ","his-shoe"],["אֵינֶנִּי","I-am-not"],["רָאוּי","worthy"],["לְהַתִּיר","to-unloose"],["׃",""]] },
  { num:"ל", words:[["אֵלֶּה","these-things"],["הַדְּבָרִים","the-[things]"],["נַעֲשׂוּ","were-done"],["בְּבֵית","in-Beth-"],["עַנְיָה","abara"],["מֵעֵבֶר","beyond"],["לַיַּרְדֵּן","the-Jordan"],["אֲשֶׁר","where"],["הָיָה","was"],["יוֹחָנָן","John"],["מַטְבִּיל","baptizing"],["׃",""]] },
  { num:"לא", words:[["מִמָּחֳרָת","the-next-day"],["רוֹאֶה","seeth"],["יוֹחָנָן","John"],["אֶת","[ACC]"],["יֵשׁוּעַ","Jesus"],["בָּא","coming"],["אֵלָיו","unto-him"],["וַיֹּאמֶר","and-saith"],["הִנֵּה","behold"],["שֶׂה","the-Lamb-of"],["הָאֱלֹהִים","God"],["הַנּוֹשֵׂא","the-which-taketh-away"],["אֶת","[ACC]"],["חַטֹּאת","the-sin-of"],["הָעוֹלָם","the-world"],["׃",""]] },
  { num:"לב", words:[["וְזֶה","and-this-is-he"],["הוּא","of-whom"],["אֲשֶׁר","I"],["אָמַרְתִּי","said"],["אַחֲרַי","after-me"],["בָּא","cometh"],["אִישׁ","a-man"],["אֲשֶׁר","who-is"],["נִעְדָּף","preferred-before"],["עָלַי","me"],["כִּי","for"],["הָיָה","he-was"],["לְפָנַי","before-me"],["וַאֲנִי","and-I"],["לֹא","knew-him"],["יְדַעְתִּיו","not"],["אַךְ","but"],["לְמַעַן","that"],["יִגָּלֶה","he-should-be-made-manifest"],["לְיִשְׂרָאֵל","to-Israel"],["לָכֵן","therefore"],["בָּאתִי","am-I-come"],["מַטְבִּיל","baptizing"],["בְּמַיִם","with-water"],["׃",""]] },
  { num:"לג", words:[["וַיָּעַד","and-bore-record"],["יוֹחָנָן","John"],["לֵאמֹר","saying"],["רָאִיתִי","I-saw"],["אֶת","[ACC]"],["הָרוּחַ","the-Spirit"],["יוֹרֶדֶת","descending"],["מִן","from"],["הַשָּׁמַיִם","the-heaven"],["כְּיוֹנָה","like-a-dove"],["וַתָּנַח","and-it-abode"],["עָלָיו","upon-him"],["׃",""]] },
  { num:"לד", words:[["וַאֲנִי","and-I"],["לֹא","knew-him"],["יְדַעְתִּיו","not"],["אַךְ","but"],["הַשּׁוֹלֵחַ","the-he-that-sent"],["אוֹתִי","me"],["לְהַטְבִּיל","to-baptize"],["בְּמַיִם","with-water"],["הוּא","the-same"],["אָמַר","said"],["אֵלַי","unto-me"],["עַל","upon"],["מִי","whomsoever"],["שֶׁתִּרְאֶה","thou-shalt-see"],["אֶת","[ACC]"],["הָרוּחַ","the-Spirit"],["יוֹרֶדֶת","descending"],["וְנָחָה","and-remaining"],["עָלָיו","on-him"],["הוּא","the-same-is-he"],["הַמַּטְבִּיל","the-who-baptizeth"],["בְּרוּחַ","with-the-Spirit-of"],["הַקֹּדֶשׁ","the-Holiness"],["׃",""]] }
];
renderVerseSet(jstjohn_ch1Verses, 'jstjohn-ch1-verses');

// === CH2: JST John 4:1–4, 26 ===
// The Pharisees desire to kill Jesus. God promises His Spirit to true believers.
var jstjohn_ch2Verses = [
  { num:"א", words:[["כַּאֲשֶׁר","when-therefore"],["שָׁמְעוּ","had-heard"],["הַפְּרוּשִׁים","the-Pharisees"],["כִּי","that"],["יֵשׁוּעַ","Jesus"],["עָשָׂה","made"],["וְהִטְבִּיל","and-baptized"],["תַּלְמִידִים","disciples"],["רַבִּים","more"],["מִיּוֹחָנָן","than-John"],["׃",""]] },
  { num:"ב", words:[["בִּקְשׁוּ","they-sought"],["בְּיֶתֶר","more-diligently"],["שְׁקִידָה","[diligently]"],["אֶמְצָעִים","some-means"],["לַהֲמִיתוֹ","that-they-might-put-him-to-death"],["כִּי","for"],["רַבִּים","many"],["קִבְּלוּ","received"],["אֶת","[ACC]"],["יוֹחָנָן","John"],["כְּנָבִיא","as-a-prophet"],["אַךְ","but"],["לֹא","they-believed-not"],["הֶאֱמִינוּ","on"],["בְּיֵשׁוּעַ","Jesus"],["׃",""]] },
  { num:"ג", words:[["וְהָאָדוֹן","now-the-Lord"],["יָדַע","knew"],["זֹאת","this"],["אַף","though"],["הוּא","he-himself"],["לֹא","baptized-not"],["הִטְבִּיל","so-many-as"],["כְּמוֹ","his"],["תַּלְמִידָיו","disciples"],["׃",""]] },
  { num:"ד", words:[["כִּי","for"],["הִרְשָׁה","he-suffered"],["לָהֶם","them"],["לְמוֹפֵת","for-an-example"],["מַעֲדִיפִים","preferring"],["זֶה","one"],["אֶת","[ACC]"],["זֶה","another"],["׃",""]] },
  { num:"כו", words:[["כִּי","for"],["לְכָאֵלֶּה","unto-such"],["הִבְטִיחַ","hath-promised"],["אֱלֹהִים","God"],["אֶת","[ACC]"],["רוּחוֹ","his-Spirit"],["וְהַמִּשְׁתַּחֲוִים","and-the-they-who-worship"],["לוֹ","him"],["חַיָּבִים","must"],["לְהִשְׁתַּחֲווֹת","worship"],["בְּרוּחַ","in-spirit"],["וּבֶאֱמֶת","and-in-truth"],["׃",""]] }
];
renderVerseSet(jstjohn_ch2Verses, 'jstjohn-ch2-verses');

// === CH3: JST John 6:44 ===
// The Father's will is that all receive Jesus.
var jstjohn_ch3Verses = [
  { num:"מד", words:[["אֵין","no"],["אִישׁ","man"],["יָכוֹל","can"],["לָבוֹא","come"],["אֵלַי","unto-me"],["אֶלָּא","except"],["אִם","he-doeth"],["עוֹשֶׂה","the-will-of"],["רְצוֹן","my-Father"],["אָבִי","who"],["אֲשֶׁר","hath-sent"],["שְׁלָחַנִי","me"],["וְזֶה","and-this-is"],["רְצוֹן","the-will-of"],["הַשּׁוֹלֵחַ","the-him-who-hath-sent"],["אוֹתִי","me"],["כִּי","that"],["תְּקַבְּלוּ","ye-receive"],["אֶת","[ACC]"],["הַבֵּן","the-Son"],["כִּי","for"],["הָאָב","the-Father"],["מֵעִיד","beareth-record-of"],["עָלָיו","him"],["וְהַמְּקַבֵּל","and-the-he-who-receiveth"],["אֶת","[ACC]"],["הָעֵדוּת","the-testimony"],["וְעוֹשֶׂה","and-doeth"],["רְצוֹן","the-will-of"],["הַשּׁוֹלְחֵנִי","the-him-who-sent-me"],["אֲקִימֶנּוּ","I-will-raise-him-up"],["בִּתְחִיַּת","in-the-resurrection-of"],["הַצַּדִּיקִים","the-just"],["׃",""]] }
];
renderVerseSet(jstjohn_ch3Verses, 'jstjohn-ch3-verses');

// === CH4: JST John 13:8–10 ===
// Jesus washes the feet of the Apostles to fulfill the law.
var jstjohn_ch4Verses = [
  { num:"ח", words:[["אָמַר","saith"],["לוֹ","unto-him"],["פֶּטְרוֹס","Peter"],["אֵינְךָ","thou-needest-not"],["צָרִיךְ","to-wash"],["לִרְחֹץ","my"],["אֶת","feet"],["רַגְלַי","[feet]"],["עָנָה","answered"],["יֵשׁוּעַ","Jesus"],["אוֹתוֹ","him"],["אִם","if"],["אֵינֶנִּי","I-wash-thee-not"],["רוֹחֲצְךָ","thou-hast-no"],["אֵין","part"],["לְךָ","with"],["חֵלֶק","me"],["אִתִּי","[me]"],["׃",""]] },
  { num:"ט", words:[["אָמַר","saith"],["לוֹ","unto-him"],["שִׁמְעוֹן","Simon"],["פֶּטְרוֹס","Peter"],["אֲדֹנִי","Lord"],["לֹא","not"],["רַק","only"],["רַגְלַי","my-feet"],["אֶלָּא","but"],["גַּם","also"],["יָדַי","my-hands"],["וְרֹאשִׁי","and-my-head"],["׃",""]] },
  { num:"י", words:[["אָמַר","saith"],["לוֹ","to-him"],["יֵשׁוּעַ","Jesus"],["הָרוֹחֵץ","the-he-that-has-washed"],["יָדָיו","his-hands"],["וְרֹאשׁוֹ","and-his-head"],["אֵינוֹ","needeth-not-save"],["צָרִיךְ","to-wash"],["אֶלָּא","his"],["לִרְחֹץ","feet"],["רַגְלָיו","but"],["אֲבָל","is-clean"],["טָהוֹר","every-whit"],["כֻּלּוֹ","and-ye"],["וְאַתֶּם","are-clean"],["טְהוֹרִים","but"],["אַךְ","not-all"],["לֹא","now"],["כֻּלְּכֶם","this"],["וְזֶה","was"],["הָיָה","the-custom-of"],["מִנְהַג","the-Jews"],["הַיְּהוּדִים","under-the"],["עַל","their"],["פִּי","law"],["תּוֹרָתָם","wherefore"],["לָכֵן","Jesus"],["עָשָׂה","did"],["יֵשׁוּעַ","this"],["זֹאת","that"],["לְמַעַן","the-law"],["תִּתְמַלֵּא","might-be-fulfilled"],["הַתּוֹרָה","the-[fulfilled]"],["׃",""]] }
];
renderVerseSet(jstjohn_ch4Verses, 'jstjohn-ch4-verses');

// === CH5: JST John 14:30 ===
// The prince of darkness is of this world.
var jstjohn_ch5Verses = [
  { num:"ל", words:[["מֵעַתָּה","hereafter"],["לֹא","I-will-not"],["אֲדַבֵּר","talk"],["עִמָּכֶם","with-you"],["הַרְבֵּה","much"],["כִּי","for"],["שַׂר","the-prince-of"],["הַחֹשֶׁךְ","the-darkness"],["אֲשֶׁר","who-is-of"],["מִן","this"],["הָעוֹלָם","the-world"],["הַזֶּה","[this]"],["בָּא","cometh"],["אַךְ","but"],["אֵין","hath-no"],["לוֹ","power"],["כֹּחַ","over"],["עָלַי","me"],["אַךְ","but"],["יֵשׁ","hath"],["לוֹ","power"],["כֹּחַ","over"],["עֲלֵיכֶם","you"],["׃",""]] }
];
renderVerseSet(jstjohn_ch5Verses, 'jstjohn-ch5-verses');

})();
