// jst_verses/jstjer.js — Jeremiah (JST) verse data
(function() {
var jstjer_ch1Verses = [
  { num:"א", words:[["בְּרֵאשִׁית","in-the-beginning-of"],["מַמְלְכוּת","the kingdom of"],["יְהוֹיָקִים","Jehoiakim"],["בֶּן־יֹאשִׁיָּהוּ","son-of-Josiah"],["מֶלֶךְ","king-of"],["יְהוּדָה","Judah"],["הָיָה","was"],["הַדָּבָר","the-thing"],["הַזֶּה","this"],["מֵאֵת","from"],["יְהֹוָה","the-LORD"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"ב", words:[["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["עֲמֹד","shall-stand"],["בַּחֲצַר","in-the courtyard of"],["בֵּית־יְהֹוָה","the-house-of-the-LORD"],["וְדִבַּרְתָּ","and-you will speak"],["עַל־כׇּל־עָרֵי","upon-all-cities-of"],["יְהוּדָה","Judah"],["הַבָּאִים","to-come"],["לְהִשְׁתַּחֲוֺת","to-bow down"],["בֵּית־יְהֹוָה","the-house-of-the-LORD"],["אֵת","[ACC]"],["כׇּל־הַדְּבָרִים","all-the-things"],["אֲשֶׁר","whose"],["צִוִּיתִיךָ","I-commanded-you"],["לְדַבֵּר","to-speak"],["אֲלֵיהֶם","to-them"],["אַל־תִּגְרַע","do-not-you hold back"],["דָּבָר","things"],["׃",""]] },
  { num:"ג", words:[["אוּלַי","perhaps"],["יִשְׁמְעוּ","they-hearken"],["וְיָשֻׁבוּ","so-they may turn back"],["אִישׁ","man-of"],["מִדַּרְכּוֹ","from-his-way"],["הָרָעָה","the-evil"],["וְנִחַמְתִּי","and-I repent"],["אֶל־הָרָעָה","to-the-evil"],["אֲשֶׁר","whose"],["אָנֹכִי","I"],["חֹשֵׁב","curious"],["לַעֲשׂוֹת","to-do"],["לָהֶם","to-them"],["מִפְּנֵי","because-of"],["רֹעַ","the wickedness of"],["מַעַלְלֵיהֶם","their-doings"],["׃",""]] },
  { num:"ד", words:[["וְאָמַרְתָּ","and-say"],["אֲלֵיהֶם","to-them"],["כֹּה","thus"],["אָמַר","said"],["יְהֹוָה","the-LORD"],["אִם־לֹא","if-not"],["תִשְׁמְעוּ","you-hearken"],["אֵלַי","to-me"],["לָלֶכֶת","to-go"],["בְּתוֹרָתִי","in-my-law"],["אֲשֶׁר","whose"],["נָתַתִּי","I-gave"],["לִפְנֵיכֶם","unto-you"],["׃",""]] },
  { num:"ה", words:[["לִשְׁמֹעַ","to-hear"],["עַל־דִּבְרֵי","upon-the-words-of"],["עֲבָדַי","are servants-my"],["הַנְּבִאִים","the-prophets"],["אֲשֶׁר","whose"],["אָנֹכִי","I"],["שֹׁלֵחַ","sent"],["אֲלֵיכֶם","unto-you"],["וְהַשְׁכֵּם","and-rising early"],["וְשָׁלֹחַ","and-sending"],["וְלֹא","and-not"],["שְׁמַעְתֶּם","you-have-heard"],["׃",""]] },
  { num:"ו", words:[["וְנָתַתִּי","and-I-will-give"],["אֶת־הַבַּיִת","[ACC]-the-house"],["הַזֶּה","this"],["כְּשִׁלֹה","like-Shiloh"],["וְאֶת־הָעִיר","and-[ACC]-the-city"],["(הזאתה)","???"],["[הַזֹּאת]","is-this"],["אֶתֵּן","shall-give"],["לִקְלָלָה","into-a curse"],["לְכֹל","for-all"],["גּוֹיֵ","the nations of"],["הָאָרֶץ","the-earth"],["׃",""]] },
  { num:"ז", words:[["וַיִּשְׁמְעוּ","and-they-heard"],["הַכֹּהֲנִים","the-priests"],["וְהַנְּבִאִים","and-the-prophets"],["וְכׇל־הָעָם","and-all-the-people"],["אֶת־יִרְמְיָהוּ","[ACC]-Jeremiah"],["מְדַבֵּר","speaks"],["אֶת־הַדְּבָרִים","[ACC]-the-words"],["הָאֵלֶּה","these"],["בְּבֵית","in-house-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"ח", words:[["וַיְהִי","and-it-came-to-pass"],["כְּכַלּוֹת","Mosiah-had-made-an-end-of"],["יִרְמְיָהוּ","Jeremiah"],["לְדַבֵּר","to-speak"],["אֵת","[ACC]"],["כׇּל־אֲשֶׁר־צִוָּה","all-whose-commanded"],["יְהֹוָה","the-LORD"],["לְדַבֵּר","to-speak"],["אֶל־כׇּל־הָעָם","to-all-the-people"],["וַיִּתְפְּשׂוּ","and-they-seized"],["אֹתוֹ","him"],["הַכֹּהֲנִים","the-priests"],["וְהַנְּבִיאִים","and-the-prophets"],["וְכׇל־הָעָם","and-all-the-people"],["לֵאמֹר","saying"],["מוֹת","death-of"],["תָּמוּת","to-death"],["׃",""]] },
  { num:"ט", words:[["מַדּוּעַ","why"],["נִבֵּיתָ","have you prophesied"],["בְשֵׁם־יְהֹוָה","in-name-of-the-LORD"],["לֵאמֹר","saying"],["כְּשִׁלוֹ","like-Shiloh"],["יִהְיֶה","he-shall-be"],["הַבַּיִת","the-house"],["הַזֶּה","this"],["וְהָעִיר","and-the-city"],["הַזֹּאת","is-this"],["תֶּחֱרַב","it will be desolate"],["מֵאֵין","without"],["יוֹשֵׁב","sitting"],["וַיִּקָּהֵל","and-gathered"],["כׇּל־הָעָם","all-the-people"],["אֶל־יִרְמְיָהוּ","to-Jeremiah"],["בְּבֵית","in-house-of"],["יְהֹוָה","the-LORD"],["׃",""]] },
  { num:"י", words:[["וַיִּשְׁמְעוּ","and-they-heard"],["שָׂרֵי","captains-of"],["יְהוּדָה","Judah"],["אֵת","[ACC]"],["הַדְּבָרִים","the-things"],["הָאֵלֶּה","these"],["וַיַּעֲלוּ","and-they-ascended"],["מִבֵּית־הַמֶּלֶךְ","from-house-of-the-king"],["בֵּית","house-of"],["יְהֹוָה","the-LORD"],["וַיֵּשְׁבוּ","and-they-had-dwelt"],["בְּפֶתַח","at-the-entrance-of"],["שַׁעַר־יְהֹוָה","gate-of-the-LORD"],["הֶחָדָשׁ","new"],["׃",""]] },
  { num:"יא", words:[["וַיֹּאמְרוּ","and-they-said"],["הַכֹּהֲנִים","the-priests"],["וְהַנְּבִאִים","and-the-prophets"],["אֶל־הַשָּׂרִים","to-the-princes"],["וְאֶל־כׇּל־הָעָם","and-all-the-people"],["לֵאמֹר","saying"],["מִשְׁפַּט־מָוֶת","judgment-death"],["לָאִישׁ","be-unto-that-man"],["הַזֶּה","this"],["כִּי","because"],["נִבָּא","he-prophesied"],["אֶל־הָעִיר","to-the-city"],["הַזֹּאת","is-this"],["כַּאֲשֶׁר","when/as"],["שְׁמַעְתֶּם","you-have-heard"],["בְּאׇזְנֵיכֶם","in-ears-my-you(pl)"],["׃",""]] },
  { num:"יב", words:[["וַיֹּאמֶר","and-said"],["יִרְמְיָהוּ","Jeremiah"],["אֶל־כׇּל־הַשָּׂרִים","to-all-the-princes"],["וְאֶל־כׇּל־הָעָם","and-all-the-people"],["לֵאמֹר","saying"],["יְהֹוָה","the-LORD"],["שְׁלָחַנִי","sent-me"],["לְהִנָּבֵא","to-prophesy"],["אֶל־הַבַּיִת","to-the-house"],["הַזֶּה","this"],["וְאֶל־הָעִיר","and-the-city"],["הַזֹּאת","is-this"],["אֵת","[ACC]"],["כׇּל־הַדְּבָרִים","all-the-things"],["אֲשֶׁר","whose"],["שְׁמַעְתֶּם","you-have-heard"],["׃",""]] },
  { num:"יג", words:[["וְעַתָּה","and-now"],["הֵיטִיבוּ","they-did-well"],["דַרְכֵיכֶם","are ways-your"],["וּמַעַלְלֵיכֶם","and-deeds-your"],["וְשִׁמְעוּ","and-hear"],["בְּקוֹל","the-voice-of"],["יְהֹוָה","the-LORD"],["אֱלֹהֵיכֶם","your-God"],["וְיִנָּחֵם","so-he may repent"],["יְהֹוָה","the-LORD"],["אֶל־הָרָעָה","to-the-evil"],["אֲשֶׁר","whose"],["דִּבֶּר","spoke"],["עֲלֵיכֶם","over-you"],["׃",""]] },
  { num:"יד", words:[["וַאֲנִי","and-I"],["הִנְנִי","behold-I"],["בְיֶדְכֶם","in-hand-you"],["עֲשׂוּ־לִי","do-to-me"],["כַּטּוֹב","as-seems-you-good"],["וְכַיָּשָׁר","and-according to the-right"],["בְּעֵינֵיכֶם","in-view-your"],["׃",""]] },
  { num:"טו", words:[["אַךְ","but"],["יָדֹעַ","surely"],["תֵּדְעוּ","know-shall-you"],["כִּי","because"],["אִם־מְמִתִים","[compound]-are about to put to death"],["אַתֶּם","you-are"],["אֹתִי","me"],["כִּי־דָם","because-blood"],["נָקִי","blameless"],["אַתֶּם","you-are"],["נֹתְנִים","were giving"],["עֲלֵיכֶם","over-you"],["וְאֶל־הָעִיר","and-the-city"],["הַזֹּאת","is-this"],["וְאֶל־יֹשְׁבֶיהָ","and-its-inhabitants"],["כִּי","because"],["בֶאֱמֶת","in-truth"],["שְׁלָחַנִי","sent-me"],["יְהֹוָה","the-LORD"],["עֲלֵיכֶם","over-you"],["לְדַבֵּר","to-speak"],["בְּאׇזְנֵיכֶם","in-ears-my-you(pl)"],["אֵת","[ACC]"],["כׇּל־הַדְּבָרִים","all-the-things"],["הָאֵלֶּה","these"],["׃",""]] },
  { num:"טז", words:[["וַיֹּאמְרוּ","and-they-said"],["הַשָּׂרִים","the-princes"],["וְכׇל־הָעָם","and-all-the-people"],["אֶל־הַכֹּהֲנִים","to-the-priests"],["וְאֶל־הַנְּבִיאִים","and-the-prophets"],["אֵין־לָאִישׁ","there-is-no-be-unto-that-man"],["הַזֶּה","this"],["מִשְׁפַּט־מָוֶת","judgment-death"],["כִּי","because"],["בְּשֵׁם","by-name"],["יְהֹוָה","the-LORD"],["אֱלֹהֵינוּ","our-God"],["דִּבֶּר","spoke"],["אֵלֵינוּ","unto-us"],["׃",""]] },
  { num:"יז", words:[["וַיָּקֻמוּ","and-were-fulfilled"],["אֲנָשִׁים","men"],["מִזִּקְנֵי","from-elders-of"],["הָאָרֶץ","the-earth"],["וַיֹּאמְרוּ","and-they-said"],["אֶל־כׇּל־קְהַל","to-all-multitude-of"],["הָעָם","the-people"],["לֵאמֹר","saying"],["׃",""]] },
  { num:"יח", words:[["(מיכיה)","Micaiah"],["[מִיכָה]","Micah"],["הַמּוֹרַשְׁתִּי","the-Morasthite"],["הָיָה","was"],["נִבָּא","he-prophesied"],["בִּימֵי","in-days-of"],["חִזְקִיָּהוּ","Hezekiah"],["מֶלֶךְ־יְהוּדָה","king-of-Judah"],["וַיֹּאמֶר","and-said"],["אֶל־כׇּל־עַם","to-all-people"],["יְהוּדָה","Judah"],["לֵאמֹר","saying"],["כֹּה־אָמַר","thus-says"],["יְהֹוָה","the-LORD"],["צְבָאוֹת","of-Hosts"],["צִיּוֹן","Zion"],["שָׂדֶה","field"],["תֵחָרֵשׁ","it will be plowed"],["וִירוּשָׁלַיִם","and-Jerusalem"],["עִיִּים","heaps of ruins"],["תִּהְיֶה","shall-be"],["וְהַר","and-the mountain of"],["הַבַּיִת","the-house"],["לְבָמוֹת","high places of"],["יָעַר","the forest"],["׃",""]] },
  { num:"יט", words:[["הֶהָמֵת","¿-really"],["הֱמִתֻהוּ","did they put to death-him"],["חִזְקִיָּהוּ","Hezekiah"],["מֶלֶךְ־יְהוּדָה","king-of-Judah"],["וְכׇל־יְהוּדָה","and-all-Judah"],["הֲלֹא","do-not"],["יָרֵא","he-feared"],["אֶת־יְהֹוָה","[ACC]-the-LORD"],["וַיְחַל","and-he entreated"],["אֶת־פְּנֵי","ACC-face-of"],["יְהֹוָה","the-LORD"],["וַיִּנָּחֶם","and-he regretted"],["יְהֹוָה","the-LORD"],["אֶל־הָרָעָה","to-the-evil"],["אֲשֶׁר־דִּבֶּר","whose-spoke"],["עֲלֵיהֶם","against-them"],["וַאֲנַחְנוּ","and-we-are"],["עֹשִׂים","which-act"],["רָעָה","evil"],["גְדוֹלָה","great"],["עַל־נַפְשׁוֹתֵינוּ","upon-our-souls"],["׃",""]] },
  { num:"כ", words:[["וְגַם־אִישׁ","and-also-man-of"],["הָיָה","was"],["מִתְנַבֵּא","prophesying"],["בְּשֵׁם","by-name"],["יְהֹוָה","the-LORD"],["אוּרִיָּהוּ","Uriah"],["בֶּן־שְׁמַעְיָהוּ","son-of-Shemaiah"],["מִקִּרְיַת","from-the town of"],["הַיְּעָרִים","Jearim"],["וַיִּנָּבֵא","and-has-prophesied"],["עַל־הָעִיר","upon-the-city"],["הַזֹּאת","is-this"],["וְעַל־הָאָרֶץ","and-upon-the-land"],["הַזֹּאת","is-this"],["כְּכֹל","according-to-all"],["דִּבְרֵי","account-of"],["יִרְמְיָהוּ","Jeremiah"],["׃",""]] },
  { num:"כא", words:[["וַיִּשְׁמַע","and-he-obeyed"],["הַמֶּלֶךְ־יְהוֹיָקִים","the-king-Jehoiakim"],["וְכׇל־גִּבּוֹרָיו","and-all-warriors-his"],["וְכׇל־הַשָּׂרִים","and-all-the-princes"],["אֶת־דְּבָרָיו","[ACC] his-words"],["וַיְבַקֵּשׁ","and-requested"],["הַמֶּלֶךְ","the-king"],["הֲמִיתוֹ","to kill-him"],["וַיִּשְׁמַע","and-he-obeyed"],["אוּרִיָּהוּ","Uriah"],["וַיִּרָא","and-he was afraid"],["וַיִּבְרַח","and-he fled"],["וַיָּבֹא","and-came"],["מִצְרָיִם","Egypt"],["׃",""]] },
  { num:"כב", words:[["וַיִּשְׁלַח","and-he-sent"],["הַמֶּלֶךְ","the-king"],["יְהוֹיָקִים","Jehoiakim"],["אֲנָשִׁים","men"],["מִצְרָיִם","Egypt"],["אֵת","[ACC]"],["אֶלְנָתָן","Elnathan"],["בֶּן־עַכְבּוֹר","son-of-Achbor"],["וַאֲנָשִׁים","and-men"],["אִתּוֹ","with-him"],["אֶל־מִצְרָיִם","to-Egypt"],["׃",""]] },
  { num:"כג", words:[["וַיּוֹצִיאוּ","and-they-brought-out"],["אֶת־אוּרִיָּהוּ","[ACC]-Uriah"],["מִמִּצְרַיִם","out-of-Egypt"],["וַיְבִאֻהוּ","and-they brought-it"],["אֶל־הַמֶּלֶךְ","unto-the-king"],["יְהוֹיָקִים","Jehoiakim"],["וַיַּכֵּהוּ","and-smote-them"],["בֶּחָרֶב","by-the-sword"],["וַיַּשְׁלֵךְ","and-he-cast"],["אֶת־נִבְלָתוֹ","[ACC]-corpse-his"],["אֶל־קִבְרֵי","to-the graves of"],["בְּנֵי","sons-of"],["הָעָם","the-people"],["׃",""]] },
  { num:"כד", words:[["אַךְ","but"],["יַד","hand-of"],["אֲחִיקָם","Ahikam"],["בֶּן־שָׁפָן","son-of-Shaphan"],["הָיְתָה","was"],["אֶת־יִרְמְיָהוּ","[ACC]-Jeremiah"],["לְבִלְתִּי","to-not"],["תֵּת־אֹתוֹ","Tt-him"],["בְיַד־הָעָם","by-the hand of-the-people"],["לַהֲמִיתוֹ","to-slay-him"],["׃",""]] },
];
renderVerseSet(jstjer_ch1Verses, 'jstjer-ch1-verses');

})();
