// generated by tools/build_verse_manifests.js from jst_english.js — Dual-view English for the chapters of jst_verses/jst1th.js
registerEnglish([["1 Thessalonians",1,1,"For this we say unto you by the word of the Lord, that they who are alive at the coming of the Lord, shall not prevent them who remain unto the coming of the Lord, who are asleep."]]);
