// generated by tools/build_verse_manifests.js from jst_english.js — Dual-view English for the chapters of jst_verses/jst2co.js
registerEnglish([["2 Corinthians",1,1,"Wherefore, henceforth live we no more after the flesh; yea, though we once lived after the flesh, yet since we have known Christ, now henceforth live we no more after the flesh."]]);
