// generated by tools/build_verse_manifests.js from jst_english.js — Dual-view English for the chapters of jst_verses/jst2sa.js
registerEnglish([["2 Samuel",1,1,"And David said unto Nathan, I have sinned against the Lord. And Nathan said unto David, The Lord also hath not put away thy sin that thou shalt not die."]]);
