// generated by tools/build_verse_manifests.js from jst_english.js — Dual-view English for the chapters of jst_verses/jst2ch.js
registerEnglish([["2 Chronicles",1,1,"Now therefore, behold, the Lord hath found a lying spirit in the mouth of these thy prophets, and the Lord hath spoken evil against thee."]]);
