// generated by tools/build_verse_manifests.js from jst_english.js — Dual-view English for the chapters of jst_verses/jstamo.js
registerEnglish([["Amos",1,1,"And the Lord said, concerning Jacob, Jacob shall repent for this, therefore I will not utterly destroy him, saith the Lord."]]);
