// generated by tools/build_verse_manifests.js from jst_english.js — Dual-view English for the chapters of jst_verses/jstdeu.js
registerEnglish([["Deuteronomy",1,1,"And I will write on the tables the words that were on the first tables, which thou brakest, save the words of the everlasting covenant of the holy priesthood, and thou shalt put them in the ark."]]);
