// generated by tools/build_verse_manifests.js from jst_english.js — Dual-view English for the chapters of jst_verses/jsteph.js
registerEnglish([["Ephesians",1,1,"Can ye be angry, and not sin? let not the sun go down upon your wrath;"]]);
