// generated by tools/build_verse_manifests.js from jst_english.js — Dual-view English for the chapters of jst_verses/jstjer.js
registerEnglish([["Jeremiah",1,1,"Therefore now, amend your ways and your doings, and obey the voice of the Lord your God, and repent, and the Lord will turn away the evil that he hath pronounced against you."]]);
