#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract the Hebrew verb-root inventory from Brauner's SHOROSHIM into
shoroshim_roots.js.  Usage: python3 tools/extract_shoroshim.py <shoroshim.pdf>
Requires pypdf.  The PDF is the translator's own copy and is not in this repo."""
import sys, re, io, json
import pypdf
src = sys.argv[1] if len(sys.argv) > 1 else '~/Desktop/shoroshim.pdf'
r = pypdf.PdfReader(__import__('os').path.expanduser(src))
HEB = r'[א-ת]'
entries, seealso = {}, {}
for i, p in enumerate(r.pages):
    if i < 9:                      # front matter and the guideline pages
        continue
    for line in (p.extract_text() or '').split('\n'):
        line = line.strip()
        m = re.match(r'^(' + HEB + r'{2,5})\s*[♦◊]*\s*(.*)$', line)
        if not m:
            continue
        root, rest = m.group(1), m.group(2).strip()
        sa = re.match(r'^See\s+(' + HEB + r'{2,5})', rest)
        if sa:
            seealso[root] = sa.group(1); continue
        if rest and re.search(r'[A-Za-z]', rest):
            entries.setdefault(root, rest[:150])
allroots = sorted(set(entries) | set(seealso) | set(seealso.values()))
hdr = ['// shoroshim_roots.js — Hebrew verb-root inventory.',
 '// Extracted from SHOROSHIM: The Ultimate and Unique English Thesaurus of',
 '// Hebrew Verb Roots, compiled by Reuven Brauner (c) 2014, Raanana, Israel.',
 '// Used as a VALIDATION set: a resolver result that is not a real root is a',
 '// peel that has gone wrong.',
 '// Generated by tools/extract_shoroshim.py. DO NOT EDIT BY HAND.']
io.open('shoroshim_roots.js', 'w', encoding='utf-8').write('\n'.join(hdr) +
  '\nwindow._shoroshimRoots = ' + json.dumps(allroots, ensure_ascii=False) + ';' +
  '\nwindow._shoroshimSee = ' + json.dumps(seealso, ensure_ascii=False) + ';\n')
print('%d roots written' % len(allroots))
